# 1 "data/maps/CeladonCity_Condominiums_Roof/scripts.pory"

# 2 "data/maps/CeladonCity_Condominiums_Roof/scripts.pory"
CeladonCity_Condominiums_Roof_MapScripts::
# 3 "data/maps/CeladonCity_Condominiums_Roof/scripts.pory"
	.byte 0
# 4 "data/maps/CeladonCity_Condominiums_Roof/scripts.pory"

# 5 "data/maps/CeladonCity_Condominiums_Roof/scripts.pory"
CeladonCity_Condominiums_Roof_EventScript_Sign::
# 6 "data/maps/CeladonCity_Condominiums_Roof/scripts.pory"
	msgbox CeladonCity_Condominiums_Roof_Text_IKnowEverything, MSGBOX_SIGN
# 7 "data/maps/CeladonCity_Condominiums_Roof/scripts.pory"
	end
