
	.align 2
gDirectSoundWaveData_0:: @ 84A3DA8
	.incbin "baserom.gba", 0x4A3DA8, 0x6A4

gDirectSoundWaveData_1:: @ 84A444C
	.incbin "baserom.gba", 0x4A444C, 0x7F8

gDirectSoundWaveData_2:: @ 84A4C44
	.incbin "baserom.gba", 0x4A4C44, 0xBCC

gDirectSoundWaveData_3:: @ 84A5810
	.incbin "baserom.gba", 0x4A5810, 0xF38

gDirectSoundWaveData_4:: @ 84A6748
	.incbin "baserom.gba", 0x4A6748, 0xC74

gDirectSoundWaveData_5:: @ 84A73BC
	.incbin "baserom.gba", 0x4A73BC, 0x14D0

gDirectSoundWaveData_6:: @ 84A888C
	.incbin "baserom.gba", 0x4A888C, 0x16B0

gDirectSoundWaveData_7:: @ 84A9F3C
	.incbin "baserom.gba", 0x4A9F3C, 0x1344

gDirectSoundWaveData_8:: @ 84AB280
	.incbin "baserom.gba", 0x4AB280, 0xAA4

gDirectSoundWaveData_9:: @ 84ABD24
	.incbin "baserom.gba", 0x4ABD24, 0x1314

gDirectSoundWaveData_10:: @ 84AD038
	.incbin "baserom.gba", 0x4AD038, 0x35FC

gDirectSoundWaveData_11:: @ 84B0634
	.incbin "baserom.gba", 0x4B0634, 0x4D8

gDirectSoundWaveData_12:: @ 84B0B0C
	.incbin "baserom.gba", 0x4B0B0C, 0x18DC

gDirectSoundWaveData_13:: @ 84B23E8
	.incbin "baserom.gba", 0x4B23E8, 0x1328

gDirectSoundWaveData_14:: @ 84B3710
	.incbin "baserom.gba", 0x4B3710, 0x4A0

gDirectSoundWaveData_15:: @ 84B3BB0
	.incbin "baserom.gba", 0x4B3BB0, 0x6F4

gDirectSoundWaveData_16:: @ 84B42A4
	.incbin "baserom.gba", 0x4B42A4, 0x890

gDirectSoundWaveData_17:: @ 84B4B34
	.incbin "baserom.gba", 0x4B4B34, 0x878

gDirectSoundWaveData_18:: @ 84B53AC
	.incbin "baserom.gba", 0x4B53AC, 0x8B4

gDirectSoundWaveData_19:: @ 84B5C60
	.incbin "baserom.gba", 0x4B5C60, 0x8E4

gDirectSoundWaveData_20:: @ 84B6544
	.incbin "baserom.gba", 0x4B6544, 0xF2C

gDirectSoundWaveData_21:: @ 84B7470
	.incbin "baserom.gba", 0x4B7470, 0x518

gDirectSoundWaveData_22:: @ 84B7988
	.incbin "baserom.gba", 0x4B7988, 0x5C8

gDirectSoundWaveData_23:: @ 84B7F50
	.incbin "baserom.gba", 0x4B7F50, 0xF18

gDirectSoundWaveData_24:: @ 84B8E68
	.incbin "baserom.gba", 0x4B8E68, 0x1974

gDirectSoundWaveData_25:: @ 84BA7DC
	.incbin "baserom.gba", 0x4BA7DC, 0x20DC

gDirectSoundWaveData_26:: @ 84BC8B8
	.incbin "baserom.gba", 0x4BC8B8, 0x7830

gDirectSoundWaveData_27:: @ 84C40E8
	.incbin "baserom.gba", 0x4C40E8, 0x9B8

gDirectSoundWaveData_28:: @ 84C4AA0
	.incbin "baserom.gba", 0x4C4AA0, 0xE80

gDirectSoundWaveData_29:: @ 84C5920
	.incbin "baserom.gba", 0x4C5920, 0xE74

gDirectSoundWaveData_30:: @ 84C6794
	.incbin "baserom.gba", 0x4C6794, 0x1814

gDirectSoundWaveData_31:: @ 84C7FA8
	.incbin "baserom.gba", 0x4C7FA8, 0x15A4

gDirectSoundWaveData_32:: @ 84C954C
	.incbin "baserom.gba", 0x4C954C, 0x15E4

gDirectSoundWaveData_33:: @ 84CAB30
	.incbin "baserom.gba", 0x4CAB30, 0x10F4

gDirectSoundWaveData_34:: @ 84CBC24
	.incbin "baserom.gba", 0x4CBC24, 0xF60

gDirectSoundWaveData_35:: @ 84CCB84
	.incbin "baserom.gba", 0x4CCB84, 0x1660

gDirectSoundWaveData_36:: @ 84CE1E4
	.incbin "baserom.gba", 0x4CE1E4, 0x155C

gDirectSoundWaveData_37:: @ 84CF740
	.incbin "baserom.gba", 0x4CF740, 0xB8C

gDirectSoundWaveData_38:: @ 84D02CC
	.incbin "baserom.gba", 0x4D02CC, 0x35A4

gDirectSoundWaveData_39:: @ 84D3870
	.incbin "baserom.gba", 0x4D3870, 0x231C

gDirectSoundWaveData_40:: @ 84D5B8C
	.incbin "baserom.gba", 0x4D5B8C, 0x36CC

gDirectSoundWaveData_41:: @ 84D9258
	.incbin "baserom.gba", 0x4D9258, 0x1350

gDirectSoundWaveData_42:: @ 84DA5A8
	.incbin "baserom.gba", 0x4DA5A8, 0x1510

gDirectSoundWaveData_43:: @ 84DBAB8
	.incbin "baserom.gba", 0x4DBAB8, 0x1420

gDirectSoundWaveData_44:: @ 84DCED8
	.incbin "baserom.gba", 0x4DCED8, 0x109C

gDirectSoundWaveData_45:: @ 84DDF74
	.incbin "baserom.gba", 0x4DDF74, 0x105C

gDirectSoundWaveData_46:: @ 84DEFD0
	.incbin "baserom.gba", 0x4DEFD0, 0x6F94

gDirectSoundWaveData_47:: @ 84E5F64
	.incbin "baserom.gba", 0x4E5F64, 0x4584

gDirectSoundWaveData_48:: @ 84EA4E8
	.incbin "baserom.gba", 0x4EA4E8, 0x764

gDirectSoundWaveData_49:: @ 84EAC4C
	.incbin "baserom.gba", 0x4EAC4C, 0x1C50

gDirectSoundWaveData_50:: @ 84EC89C
	.incbin "baserom.gba", 0x4EC89C, 0x14D0

gDirectSoundWaveData_51:: @ 84EDD6C
	.incbin "baserom.gba", 0x4EDD6C, 0xA0C

gDirectSoundWaveData_52:: @ 84EE778
	.incbin "baserom.gba", 0x4EE778, 0x1C14

gDirectSoundWaveData_53:: @ 84F038C
	.incbin "baserom.gba", 0x4F038C, 0x1960

gDirectSoundWaveData_54:: @ 84F1CEC
	.incbin "baserom.gba", 0x4F1CEC, 0x14C4

gDirectSoundWaveData_55:: @ 84F31B0
	.incbin "baserom.gba", 0x4F31B0, 0x73C

gDirectSoundWaveData_56:: @ 84F38EC
	.incbin "baserom.gba", 0x4F38EC, 0x1BF0

gDirectSoundWaveData_57:: @ 84F54DC
	.incbin "baserom.gba", 0x4F54DC, 0x13B4

gDirectSoundWaveData_58:: @ 84F6890
	.incbin "baserom.gba", 0x4F6890, 0x2684

gDirectSoundWaveData_59:: @ 84F8F14
	.incbin "baserom.gba", 0x4F8F14, 0x1244

gDirectSoundWaveData_60:: @ 84FA158
	.incbin "baserom.gba", 0x4FA158, 0x1010

gDirectSoundWaveData_61:: @ 84FB168
	.incbin "baserom.gba", 0x4FB168, 0x1308

gDirectSoundWaveData_62:: @ 84FC470
	.incbin "baserom.gba", 0x4FC470, 0x210C

gDirectSoundWaveData_63:: @ 84FE57C
	.incbin "baserom.gba", 0x4FE57C, 0x1FDC

gDirectSoundWaveData_64:: @ 8500558
	.incbin "baserom.gba", 0x500558, 0x2210

gDirectSoundWaveData_65:: @ 8502768
	.incbin "baserom.gba", 0x502768, 0x7CC

gDirectSoundWaveData_66:: @ 8502F34
	.incbin "baserom.gba", 0x502F34, 0x1970

gDirectSoundWaveData_67:: @ 85048A4
	.incbin "baserom.gba", 0x5048A4, 0x414

gDirectSoundWaveData_68:: @ 8504CB8
	.incbin "baserom.gba", 0x504CB8, 0x1FB0

gDirectSoundWaveData_69:: @ 8506C68
	.incbin "baserom.gba", 0x506C68, 0x32E0

gDirectSoundWaveData_70:: @ 8509F48
	.incbin "baserom.gba", 0x509F48, 0xA30

gDirectSoundWaveData_71:: @ 850A978
	.incbin "baserom.gba", 0x50A978, 0xA34

gDirectSoundWaveData_72:: @ 850B3AC
	.incbin "baserom.gba", 0x50B3AC, 0x1B40

gDirectSoundWaveData_73:: @ 850CEEC
	.incbin "baserom.gba", 0x50CEEC, 0x8C8

gDirectSoundWaveData_74:: @ 850D7B4
	.incbin "baserom.gba", 0x50D7B4, 0x13D0

gDirectSoundWaveData_75:: @ 850EB84
	.incbin "baserom.gba", 0x50EB84, 0x1040

	.align 2
Cry_Bulbasaur:: @ 850FBC4
	.incbin "sound/direct_sound_samples/cry_bulbasaur.bin"

	.align 2
Cry_Ivysaur:: @ 8510C50
	.incbin "sound/direct_sound_samples/cry_ivysaur.bin"

	.align 2
Cry_Venusaur:: @ 8511CE0
	.incbin "sound/direct_sound_samples/cry_venusaur.bin"

	.align 2
Cry_Charmander:: @ 8513038
	.incbin "sound/direct_sound_samples/cry_charmander.bin"

	.align 2
Cry_Charmeleon:: @ 8513EA8
	.incbin "sound/direct_sound_samples/cry_charmeleon.bin"

	.align 2
Cry_Charizard:: @ 8514D28
	.incbin "sound/direct_sound_samples/cry_charizard.bin"

	.align 2
Cry_Squirtle:: @ 8516070
	.incbin "sound/direct_sound_samples/cry_squirtle.bin"

	.align 2
Cry_Wartortle:: @ 8516EE4
	.incbin "sound/direct_sound_samples/cry_wartortle.bin"

	.align 2
Cry_Blastoise:: @ 8518024
	.incbin "sound/direct_sound_samples/cry_blastoise.bin"

	.align 2
Cry_Caterpie:: @ 851936C
	.incbin "sound/direct_sound_samples/cry_caterpie.bin"

	.align 2
Cry_Metapod:: @ 8519BC4
	.incbin "sound/direct_sound_samples/cry_metapod.bin"

	.align 2
Cry_Butterfree:: @ 851B314
	.incbin "sound/direct_sound_samples/cry_butterfree.bin"

	.align 2
Cry_Weedle:: @ 851BD1C
	.incbin "sound/direct_sound_samples/cry_weedle.bin"

	.align 2
Cry_Kakuna:: @ 851CD60
	.incbin "sound/direct_sound_samples/cry_kakuna.bin"

	.align 2
Cry_Beedrill:: @ 851DF9C
	.incbin "sound/direct_sound_samples/cry_beedrill.bin"

	.align 2
Cry_Pidgey:: @ 851F2F8
	.incbin "sound/direct_sound_samples/cry_pidgey.bin"

	.align 2
Cry_Pidgeotto:: @ 851F6E0
	.incbin "sound/direct_sound_samples/cry_pidgeotto.bin"

	.align 2
Cry_Pidgeot:: @ 85205E8
	.incbin "sound/direct_sound_samples/cry_pidgeot.bin"

	.align 2
Cry_Rattata:: @ 852171C
	.incbin "sound/direct_sound_samples/cry_rattata.bin"

	.align 2
Cry_Raticate:: @ 8521EFC
	.incbin "sound/direct_sound_samples/cry_raticate.bin"

	.align 2
Cry_Spearow:: @ 8522880
	.incbin "sound/direct_sound_samples/cry_spearow.bin"

	.align 2
Cry_Fearow:: @ 8523A24
	.incbin "sound/direct_sound_samples/cry_fearow.bin"

	.align 2
Cry_Ekans:: @ 8524B60
	.incbin "sound/direct_sound_samples/cry_ekans.bin"

	.align 2
Cry_Arbok:: @ 8525EAC
	.incbin "sound/direct_sound_samples/cry_arbok.bin"

	.align 2
Cry_Pikachu:: @ 8527204
	.incbin "sound/direct_sound_samples/cry_pikachu.bin"

	.align 2
Cry_Raichu:: @ 85282AC
	.incbin "sound/direct_sound_samples/cry_raichu.bin"

	.align 2
Cry_Sandshrew:: @ 8529A6C
	.incbin "sound/direct_sound_samples/cry_sandshrew.bin"

	.align 2
Cry_Sandslash:: @ 852A3C0
	.incbin "sound/direct_sound_samples/cry_sandslash.bin"

	.align 2
Cry_NidoranF:: @ 852B150
	.incbin "sound/direct_sound_samples/cry_nidoran_f.bin"

	.align 2
Cry_Nidorina:: @ 852BB00
	.incbin "sound/direct_sound_samples/cry_nidorina.bin"

	.align 2
Cry_Nidoqueen:: @ 852C7C8
	.incbin "sound/direct_sound_samples/cry_nidoqueen.bin"

	.align 2
Cry_NidoranM:: @ 852D8A8
	.incbin "sound/direct_sound_samples/cry_nidoran_m.bin"

	.align 2
Cry_Nidorino:: @ 852E310
	.incbin "sound/direct_sound_samples/cry_nidorino.bin"

	.align 2
Cry_Nidoking:: @ 852EF24
	.incbin "sound/direct_sound_samples/cry_nidoking.bin"

	.align 2
Cry_Clefairy:: @ 8530790
	.incbin "sound/direct_sound_samples/cry_clefairy.bin"

	.align 2
Cry_Clefable:: @ 8531000
	.incbin "sound/direct_sound_samples/cry_clefable.bin"

	.align 2
Cry_Vulpix:: @ 8531A90
	.incbin "sound/direct_sound_samples/cry_vulpix.bin"

	.align 2
Cry_Ninetales:: @ 8533260
	.incbin "sound/direct_sound_samples/cry_ninetales.bin"

	.align 2
Cry_Jigglypuff:: @ 8534ACC
	.incbin "sound/direct_sound_samples/cry_jigglypuff.bin"

	.align 2
Cry_Wigglytuff:: @ 8535030
	.incbin "sound/direct_sound_samples/cry_wigglytuff.bin"

	.align 2
Cry_Zubat:: @ 85356F8
	.incbin "sound/direct_sound_samples/cry_zubat.bin"

	.align 2
Cry_Golbat:: @ 8536A64
	.incbin "sound/direct_sound_samples/cry_golbat.bin"

	.align 2
Cry_Oddish:: @ 8537DC8
	.incbin "sound/direct_sound_samples/cry_oddish.bin"

	.align 2
Cry_Gloom:: @ 8538C64
	.incbin "sound/direct_sound_samples/cry_gloom.bin"

	.align 2
Cry_Vileplume:: @ 85398E0
	.incbin "sound/direct_sound_samples/cry_vileplume.bin"

	.align 2
Cry_Paras:: @ 853B27C
	.incbin "sound/direct_sound_samples/cry_paras.bin"

	.align 2
Cry_Parasect:: @ 853CE70
	.incbin "sound/direct_sound_samples/cry_parasect.bin"

	.align 2
Cry_Venonat:: @ 853ECD8
	.incbin "sound/direct_sound_samples/cry_venonat.bin"

	.align 2
Cry_Venomoth:: @ 853FC58
	.incbin "sound/direct_sound_samples/cry_venomoth.bin"

	.align 2
Cry_Diglett:: @ 8540C5C
	.incbin "sound/direct_sound_samples/cry_diglett.bin"

	.align 2
Cry_Dugtrio:: @ 8541FCC
	.incbin "sound/direct_sound_samples/cry_dugtrio.bin"

	.align 2
Cry_Meowth:: @ 8543338
	.incbin "sound/direct_sound_samples/cry_meowth.bin"

	.align 2
Cry_Persian:: @ 8543CC8
	.incbin "sound/direct_sound_samples/cry_persian.bin"

	.align 2
Cry_Psyduck:: @ 8544FA4
	.incbin "sound/direct_sound_samples/cry_psyduck.bin"

	.align 2
Cry_Golduck:: @ 8545CCC
	.incbin "sound/direct_sound_samples/cry_golduck.bin"

	.align 2
Cry_Mankey:: @ 8546814
	.incbin "sound/direct_sound_samples/cry_mankey.bin"

	.align 2
Cry_Primeape:: @ 8547874
	.incbin "sound/direct_sound_samples/cry_primeape.bin"

	.align 2
Cry_Growlithe:: @ 85488A4
	.incbin "sound/direct_sound_samples/cry_growlithe.bin"

	.align 2
Cry_Arcanine:: @ 8549608
	.incbin "sound/direct_sound_samples/cry_arcanine.bin"

	.align 2
Cry_Poliwag:: @ 854A744
	.incbin "sound/direct_sound_samples/cry_poliwag.bin"

	.align 2
Cry_Poliwhirl:: @ 854B260
	.incbin "sound/direct_sound_samples/cry_poliwhirl.bin"

	.align 2
Cry_Poliwrath:: @ 854B908
	.incbin "sound/direct_sound_samples/cry_poliwrath.bin"

	.align 2
Cry_Abra:: @ 854C42C
	.incbin "sound/direct_sound_samples/cry_abra.bin"

	.align 2
Cry_Kadabra:: @ 854DB90
	.incbin "sound/direct_sound_samples/cry_kadabra.bin"

	.align 2
Cry_Alakazam:: @ 854F678
	.incbin "sound/direct_sound_samples/cry_alakazam.bin"

	.align 2
Cry_Machop:: @ 8551614
	.incbin "sound/direct_sound_samples/cry_machop.bin"

	.align 2
Cry_Machoke:: @ 8552378
	.incbin "sound/direct_sound_samples/cry_machoke.bin"

	.align 2
Cry_Machamp:: @ 8553108
	.incbin "sound/direct_sound_samples/cry_machamp.bin"

	.align 2
Cry_Bellsprout:: @ 8554190
	.incbin "sound/direct_sound_samples/cry_bellsprout.bin"

	.align 2
Cry_Weepinbell:: @ 855491C
	.incbin "sound/direct_sound_samples/cry_weepinbell.bin"

	.align 2
Cry_Victreebel:: @ 85557BC
	.incbin "sound/direct_sound_samples/cry_victreebel.bin"

	.align 2
Cry_Tentacool:: @ 8556B08
	.incbin "sound/direct_sound_samples/cry_tentacool.bin"

	.align 2
Cry_Tentacruel:: @ 8557AF8
	.incbin "sound/direct_sound_samples/cry_tentacruel.bin"

	.align 2
Cry_Geodude:: @ 85591F4
	.incbin "sound/direct_sound_samples/cry_geodude.bin"

	.align 2
Cry_Graveler:: @ 855A9A8
	.incbin "sound/direct_sound_samples/cry_graveler.bin"

	.align 2
Cry_Golem:: @ 855C590
	.incbin "sound/direct_sound_samples/cry_golem.bin"

	.align 2
Cry_Ponyta:: @ 855D3BC
	.incbin "sound/direct_sound_samples/cry_ponyta.bin"

	.align 2
Cry_Rapidash:: @ 855E2CC
	.incbin "sound/direct_sound_samples/cry_rapidash.bin"

	.align 2
Cry_Slowpoke:: @ 855F56C
	.incbin "sound/direct_sound_samples/cry_slowpoke.bin"

	.align 2
Cry_Slowbro:: @ 855FCD4
	.incbin "sound/direct_sound_samples/cry_slowbro.bin"

	.align 2
Cry_Magnemite:: @ 8560A44
	.incbin "sound/direct_sound_samples/cry_magnemite.bin"

	.align 2
Cry_Magneton:: @ 8561D88
	.incbin "sound/direct_sound_samples/cry_magneton.bin"

	.align 2
Cry_Farfetchd:: @ 8563570
	.incbin "sound/direct_sound_samples/cry_farfetchd.bin"

	.align 2
Cry_Doduo:: @ 8563CEC
	.incbin "sound/direct_sound_samples/cry_doduo.bin"

	.align 2
Cry_Dodrio:: @ 8565030
	.incbin "sound/direct_sound_samples/cry_dodrio.bin"

	.align 2
Cry_Seel:: @ 85663A8
	.incbin "sound/direct_sound_samples/cry_seel.bin"

	.align 2
Cry_Dewgong:: @ 8567598
	.incbin "sound/direct_sound_samples/cry_dewgong.bin"

	.align 2
Cry_Grimer:: @ 8568ABC
	.incbin "sound/direct_sound_samples/cry_grimer.bin"

	.align 2
Cry_Muk:: @ 8569544
	.incbin "sound/direct_sound_samples/cry_muk.bin"

	.align 2
Cry_Shellder:: @ 856A404
	.incbin "sound/direct_sound_samples/cry_shellder.bin"

	.align 2
Cry_Cloyster:: @ 856B378
	.incbin "sound/direct_sound_samples/cry_cloyster.bin"

	.align 2
Cry_Gastly:: @ 856C83C
	.incbin "sound/direct_sound_samples/cry_gastly.bin"

	.align 2
Cry_Haunter:: @ 856DF8C
	.incbin "sound/direct_sound_samples/cry_haunter.bin"

	.align 2
Cry_Gengar:: @ 856F70C
	.incbin "sound/direct_sound_samples/cry_gengar.bin"

	.align 2
Cry_Onix:: @ 85705CC
	.incbin "sound/direct_sound_samples/cry_onix.bin"

	.align 2
Cry_Drowzee:: @ 8571E90
	.incbin "sound/direct_sound_samples/cry_drowzee.bin"

	.align 2
Cry_Hypno:: @ 8573BA8
	.incbin "sound/direct_sound_samples/cry_hypno.bin"

	.align 2
Cry_Krabby:: @ 85758AC
	.incbin "sound/direct_sound_samples/cry_krabby.bin"

	.align 2
Cry_Kingler:: @ 85770F8
	.incbin "sound/direct_sound_samples/cry_kingler.bin"

	.align 2
Cry_Voltorb:: @ 8578950
	.incbin "sound/direct_sound_samples/cry_voltorb.bin"

	.align 2
Cry_Electrode:: @ 857A214
	.incbin "sound/direct_sound_samples/cry_electrode.bin"

	.align 2
Cry_Exeggcute:: @ 857BB4C
	.incbin "sound/direct_sound_samples/cry_exeggcute.bin"

	.align 2
Cry_Exeggutor:: @ 857CE2C
	.incbin "sound/direct_sound_samples/cry_exeggutor.bin"

	.align 2
Cry_Cubone:: @ 857EE10
	.incbin "sound/direct_sound_samples/cry_cubone.bin"

	.align 2
Cry_Marowak:: @ 857FD30
	.incbin "sound/direct_sound_samples/cry_marowak.bin"

	.align 2
Cry_Hitmonlee:: @ 8580BA0
	.incbin "sound/direct_sound_samples/cry_hitmonlee.bin"

	.align 2
Cry_Hitmonchan:: @ 8581E4C
	.incbin "sound/direct_sound_samples/cry_hitmonchan.bin"

	.align 2
Cry_Lickitung:: @ 8583024
	.incbin "sound/direct_sound_samples/cry_lickitung.bin"

	.align 2
Cry_Koffing:: @ 8583F4C
	.incbin "sound/direct_sound_samples/cry_koffing.bin"

	.align 2
Cry_Weezing:: @ 85853A8
	.incbin "sound/direct_sound_samples/cry_weezing.bin"

	.align 2
Cry_Rhyhorn:: @ 8586954
	.incbin "sound/direct_sound_samples/cry_rhyhorn.bin"

	.align 2
Cry_Rhydon:: @ 8587CC0
	.incbin "sound/direct_sound_samples/cry_rhydon.bin"

	.align 2
Cry_Chansey:: @ 858912C
	.incbin "sound/direct_sound_samples/cry_chansey.bin"

	.align 2
Cry_Tangela:: @ 8589FF8
	.incbin "sound/direct_sound_samples/cry_tangela.bin"

	.align 2
Cry_Kangaskhan:: @ 858AF14
	.incbin "sound/direct_sound_samples/cry_kangaskhan.bin"

	.align 2
Cry_Horsea:: @ 858C1C8
	.incbin "sound/direct_sound_samples/cry_horsea.bin"

	.align 2
Cry_Seadra:: @ 858CB44
	.incbin "sound/direct_sound_samples/cry_seadra.bin"

	.align 2
Cry_Goldeen:: @ 858D3B0
	.incbin "sound/direct_sound_samples/cry_goldeen.bin"

	.align 2
Cry_Seaking:: @ 858DD88
	.incbin "sound/direct_sound_samples/cry_seaking.bin"

	.align 2
Cry_Staryu:: @ 858F0E0
	.incbin "sound/direct_sound_samples/cry_staryu.bin"

	.align 2
Cry_Starmie:: @ 85904C8
	.incbin "sound/direct_sound_samples/cry_starmie.bin"

	.align 2
Cry_MrMime:: @ 85919A4
	.incbin "sound/direct_sound_samples/cry_mr_mime.bin"

	.align 2
Cry_Scyther:: @ 8592C94
	.incbin "sound/direct_sound_samples/cry_scyther.bin"

	.align 2
Cry_Jynx:: @ 85939F0
	.incbin "sound/direct_sound_samples/cry_jynx.bin"

	.align 2
Cry_Electabuzz:: @ 8596964
	.incbin "sound/direct_sound_samples/cry_electabuzz.bin"

	.align 2
Cry_Magmar:: @ 8598848
	.incbin "sound/direct_sound_samples/cry_magmar.bin"

	.align 2
Cry_Pinsir:: @ 85997C4
	.incbin "sound/direct_sound_samples/cry_pinsir.bin"

	.align 2
Cry_Tauros:: @ 859A420
	.incbin "sound/direct_sound_samples/cry_tauros.bin"

	.align 2
Cry_Magikarp:: @ 859B674
	.incbin "sound/direct_sound_samples/cry_magikarp.bin"

	.align 2
Cry_Gyarados:: @ 859C97C
	.incbin "sound/direct_sound_samples/cry_gyarados.bin"

	.align 2
Cry_Lapras:: @ 859DDB0
	.incbin "sound/direct_sound_samples/cry_lapras.bin"

	.align 2
Cry_Ditto:: @ 859EC84
	.incbin "sound/direct_sound_samples/cry_ditto.bin"

	.align 2
Cry_Eevee:: @ 859F7A0
	.incbin "sound/direct_sound_samples/cry_eevee.bin"

	.align 2
Cry_Vaporeon:: @ 85A05D8
	.incbin "sound/direct_sound_samples/cry_vaporeon.bin"

	.align 2
Cry_Jolteon:: @ 85A1BF0
	.incbin "sound/direct_sound_samples/cry_jolteon.bin"

	.align 2
Cry_Flareon:: @ 85A2BC4
	.incbin "sound/direct_sound_samples/cry_flareon.bin"

	.align 2
Cry_Porygon:: @ 85A3B48
	.incbin "sound/direct_sound_samples/cry_porygon.bin"

	.align 2
Cry_Omanyte:: @ 85A4F54
	.incbin "sound/direct_sound_samples/cry_omanyte.bin"

	.align 2
Cry_Omastar:: @ 85A5CAC
	.incbin "sound/direct_sound_samples/cry_omastar.bin"

	.align 2
Cry_Kabuto:: @ 85A6A00
	.incbin "sound/direct_sound_samples/cry_kabuto.bin"

	.align 2
Cry_Kabutops:: @ 85A7654
	.incbin "sound/direct_sound_samples/cry_kabutops.bin"

	.align 2
Cry_Aerodactyl:: @ 85A8410
	.incbin "sound/direct_sound_samples/cry_aerodactyl.bin"

	.align 2
Cry_Snorlax:: @ 85A9C6C
	.incbin "sound/direct_sound_samples/cry_snorlax.bin"

	.align 2
Cry_Articuno:: @ 85AA1A8
	.incbin "sound/direct_sound_samples/cry_articuno.bin"

	.align 2
Cry_Zapdos:: @ 85AB950
	.incbin "sound/direct_sound_samples/cry_zapdos.bin"

	.align 2
Cry_Moltres:: @ 85AC8C8
	.incbin "sound/direct_sound_samples/cry_moltres.bin"

	.align 2
Cry_Dratini:: @ 85AE074
	.incbin "sound/direct_sound_samples/cry_dratini.bin"

	.align 2
Cry_Dragonair:: @ 85AEC10
	.incbin "sound/direct_sound_samples/cry_dragonair.bin"

	.align 2
Cry_Dragonite:: @ 85AFCB8
	.incbin "sound/direct_sound_samples/cry_dragonite.bin"

	.align 2
Cry_Mewtwo:: @ 85B0FC4
	.incbin "sound/direct_sound_samples/cry_mewtwo.bin"

	.align 2
Cry_Mew:: @ 85B2E2C
	.incbin "sound/direct_sound_samples/cry_mew.bin"

	.align 2
Cry_Chikorita:: @ 85B4C94
	.incbin "sound/direct_sound_samples/cry_chikorita.bin"

	.align 2
Cry_Bayleef:: @ 85B51D4
	.incbin "sound/direct_sound_samples/cry_bayleef.bin"

	.align 2
Cry_Meganium:: @ 85B5AA0
	.incbin "sound/direct_sound_samples/cry_meganium.bin"

	.align 2
Cry_Cyndaquil:: @ 85B6AD8
	.incbin "sound/direct_sound_samples/cry_cyndaquil.bin"

	.align 2
Cry_Quilava:: @ 85B71DC
	.incbin "sound/direct_sound_samples/cry_quilava.bin"

	.align 2
Cry_Typhlosion:: @ 85B7DC4
	.incbin "sound/direct_sound_samples/cry_typhlosion.bin"

	.align 2
Cry_Totodile:: @ 85BA3D4
	.incbin "sound/direct_sound_samples/cry_totodile.bin"

	.align 2
Cry_Croconaw:: @ 85BB62C
	.incbin "sound/direct_sound_samples/cry_croconaw.bin"

	.align 2
Cry_Feraligatr:: @ 85BCA68
	.incbin "sound/direct_sound_samples/cry_feraligatr.bin"

	.align 2
Cry_Sentret:: @ 85BE3EC
	.incbin "sound/direct_sound_samples/cry_sentret.bin"

	.align 2
Cry_Furret:: @ 85BE814
	.incbin "sound/direct_sound_samples/cry_furret.bin"

	.align 2
Cry_Hoothoot:: @ 85BEE5C
	.incbin "sound/direct_sound_samples/cry_hoothoot.bin"

	.align 2
Cry_Noctowl:: @ 85BF940
	.incbin "sound/direct_sound_samples/cry_noctowl.bin"

	.align 2
Cry_Ledyba:: @ 85C0E70
	.incbin "sound/direct_sound_samples/cry_ledyba.bin"

	.align 2
Cry_Ledian:: @ 85C1568
	.incbin "sound/direct_sound_samples/cry_ledian.bin"

	.align 2
Cry_Spinarak:: @ 85C1DCC
	.incbin "sound/direct_sound_samples/cry_spinarak.bin"

	.align 2
Cry_Ariados:: @ 85C2B30
	.incbin "sound/direct_sound_samples/cry_ariados.bin"

	.align 2
Cry_Crobat:: @ 85C3784
	.incbin "sound/direct_sound_samples/cry_crobat.bin"

	.align 2
Cry_Chinchou:: @ 85C4EB4
	.incbin "sound/direct_sound_samples/cry_chinchou.bin"

	.align 2
Cry_Lanturn:: @ 85C5B64
	.incbin "sound/direct_sound_samples/cry_lanturn.bin"

	.align 2
Cry_Pichu:: @ 85C65F0
	.incbin "sound/direct_sound_samples/cry_pichu.bin"

	.align 2
Cry_Cleffa:: @ 85C6D44
	.incbin "sound/direct_sound_samples/cry_cleffa.bin"

	.align 2
Cry_Igglybuff:: @ 85C7334
	.incbin "sound/direct_sound_samples/cry_igglybuff.bin"

	.align 2
Cry_Togepi:: @ 85C7A30
	.incbin "sound/direct_sound_samples/cry_togepi.bin"

	.align 2
Cry_Togetic:: @ 85C8518
	.incbin "sound/direct_sound_samples/cry_togetic.bin"

	.align 2
Cry_Natu:: @ 85C8C18
	.incbin "sound/direct_sound_samples/cry_natu.bin"

	.align 2
Cry_Xatu:: @ 85C96A8
	.incbin "sound/direct_sound_samples/cry_xatu.bin"

	.align 2
Cry_Mareep:: @ 85CA574
	.incbin "sound/direct_sound_samples/cry_mareep.bin"

	.align 2
Cry_Flaaffy:: @ 85CACCC
	.incbin "sound/direct_sound_samples/cry_flaaffy.bin"

	.align 2
Cry_Ampharos:: @ 85CBA80
	.incbin "sound/direct_sound_samples/cry_ampharos.bin"

	.align 2
Cry_Bellossom:: @ 85CCB00
	.incbin "sound/direct_sound_samples/cry_bellossom.bin"

	.align 2
Cry_Marill:: @ 85CD918
	.incbin "sound/direct_sound_samples/cry_marill.bin"

	.align 2
Cry_Azumarill:: @ 85CE62C
	.incbin "sound/direct_sound_samples/cry_azumarill.bin"

	.align 2
Cry_Sudowoodo:: @ 85CF718
	.incbin "sound/direct_sound_samples/cry_sudowoodo.bin"

	.align 2
Cry_Politoed:: @ 85D0748
	.incbin "sound/direct_sound_samples/cry_politoed.bin"

	.align 2
Cry_Hoppip:: @ 85D198C
	.incbin "sound/direct_sound_samples/cry_hoppip.bin"

	.align 2
Cry_Skiploom:: @ 85D21F8
	.incbin "sound/direct_sound_samples/cry_skiploom.bin"

	.align 2
Cry_Jumpluff:: @ 85D2F00
	.incbin "sound/direct_sound_samples/cry_jumpluff.bin"

	.align 2
Cry_Aipom:: @ 85D3F3C
	.incbin "sound/direct_sound_samples/cry_aipom.bin"

	.align 2
Cry_Sunkern:: @ 85D4D5C
	.incbin "sound/direct_sound_samples/cry_sunkern.bin"

	.align 2
Cry_Sunflora:: @ 85D5570
	.incbin "sound/direct_sound_samples/cry_sunflora.bin"

	.align 2
Cry_Yanma:: @ 85D6550
	.incbin "sound/direct_sound_samples/cry_yanma.bin"

	.align 2
Cry_Wooper:: @ 85D7658
	.incbin "sound/direct_sound_samples/cry_wooper.bin"

	.align 2
Cry_Quagsire:: @ 85D7DB8
	.incbin "sound/direct_sound_samples/cry_quagsire.bin"

	.align 2
Cry_Espeon:: @ 85D8B18
	.incbin "sound/direct_sound_samples/cry_espeon.bin"

	.align 2
Cry_Umbreon:: @ 85D9ECC
	.incbin "sound/direct_sound_samples/cry_umbreon.bin"

	.align 2
Cry_Murkrow:: @ 85DAE4C
	.incbin "sound/direct_sound_samples/cry_murkrow.bin"

	.align 2
Cry_Slowking:: @ 85DBF10
	.incbin "sound/direct_sound_samples/cry_slowking.bin"

	.align 2
Cry_Misdreavus:: @ 85DD6F4
	.incbin "sound/direct_sound_samples/cry_misdreavus.bin"

	.align 2
Cry_Unown:: @ 85DE294
	.incbin "sound/direct_sound_samples/cry_unown.bin"

	.align 2
Cry_Wobbuffet:: @ 85DEFBC
	.incbin "sound/direct_sound_samples/cry_wobbuffet.bin"

	.align 2
Cry_Girafarig:: @ 85E0458
	.incbin "sound/direct_sound_samples/cry_girafarig.bin"

	.align 2
Cry_Pineco:: @ 85E130C
	.incbin "sound/direct_sound_samples/cry_pineco.bin"

	.align 2
Cry_Forretress:: @ 85E206C
	.incbin "sound/direct_sound_samples/cry_forretress.bin"

	.align 2
Cry_Dunsparce:: @ 85E3474
	.incbin "sound/direct_sound_samples/cry_dunsparce.bin"

	.align 2
Cry_Gligar:: @ 85E4454
	.incbin "sound/direct_sound_samples/cry_gligar.bin"

	.align 2
Cry_Steelix:: @ 85E5074
	.incbin "sound/direct_sound_samples/cry_steelix.bin"

	.align 2
Cry_Snubbull:: @ 85E769C
	.incbin "sound/direct_sound_samples/cry_snubbull.bin"

	.align 2
Cry_Granbull:: @ 85E8510
	.incbin "sound/direct_sound_samples/cry_granbull.bin"

	.align 2
Cry_Qwilfish:: @ 85E9CB4
	.incbin "sound/direct_sound_samples/cry_qwilfish.bin"

	.align 2
Cry_Scizor:: @ 85EA850
	.incbin "sound/direct_sound_samples/cry_scizor.bin"

	.align 2
Cry_Shuckle:: @ 85EBF4C
	.incbin "sound/direct_sound_samples/cry_shuckle.bin"

	.align 2
Cry_Heracross:: @ 85EC980
	.incbin "sound/direct_sound_samples/cry_heracross.bin"

	.align 2
Cry_Sneasel:: @ 85EDBD4
	.incbin "sound/direct_sound_samples/cry_sneasel.bin"

	.align 2
Cry_Teddiursa:: @ 85EE4F8
	.incbin "sound/direct_sound_samples/cry_teddiursa.bin"

	.align 2
Cry_Ursaring:: @ 85EF584
	.incbin "sound/direct_sound_samples/cry_ursaring.bin"

	.align 2
Cry_Slugma:: @ 85F135C
	.incbin "sound/direct_sound_samples/cry_slugma.bin"

	.align 2
Cry_Magcargo:: @ 85F2474
	.incbin "sound/direct_sound_samples/cry_magcargo.bin"

	.align 2
Cry_Swinub:: @ 85F397C
	.incbin "sound/direct_sound_samples/cry_swinub.bin"

	.align 2
Cry_Piloswine:: @ 85F4624
	.incbin "sound/direct_sound_samples/cry_piloswine.bin"

	.align 2
Cry_Corsola:: @ 85F5318
	.incbin "sound/direct_sound_samples/cry_corsola.bin"

	.align 2
Cry_Remoraid:: @ 85F5FF8
	.incbin "sound/direct_sound_samples/cry_remoraid.bin"

	.align 2
Cry_Octillery:: @ 85F6A88
	.incbin "sound/direct_sound_samples/cry_octillery.bin"

	.align 2
Cry_Delibird:: @ 85F84CC
	.incbin "sound/direct_sound_samples/cry_delibird.bin"

	.align 2
Cry_Mantine:: @ 85F9500
	.incbin "sound/direct_sound_samples/cry_mantine.bin"

	.align 2
Cry_Skarmory:: @ 85FA4C8
	.incbin "sound/direct_sound_samples/cry_skarmory.bin"

	.align 2
Cry_Houndour:: @ 85FBCD0
	.incbin "sound/direct_sound_samples/cry_houndour.bin"

	.align 2
Cry_Houndoom:: @ 85FC978
	.incbin "sound/direct_sound_samples/cry_houndoom.bin"

	.align 2
Cry_Kingdra:: @ 85FDD28
	.incbin "sound/direct_sound_samples/cry_kingdra.bin"

	.align 2
Cry_Phanpy:: @ 85FEB00
	.incbin "sound/direct_sound_samples/cry_phanpy.bin"

	.align 2
Cry_Donphan:: @ 85FF650
	.incbin "sound/direct_sound_samples/cry_donphan.bin"

	.align 2
Cry_Porygon2:: @ 8600774
	.incbin "sound/direct_sound_samples/cry_porygon2.bin"

	.align 2
Cry_Stantler:: @ 860172C
	.incbin "sound/direct_sound_samples/cry_stantler.bin"

	.align 2
Cry_Smeargle:: @ 8602DA8
	.incbin "sound/direct_sound_samples/cry_smeargle.bin"

	.align 2
Cry_Tyrogue:: @ 86037DC
	.incbin "sound/direct_sound_samples/cry_tyrogue.bin"

	.align 2
Cry_Hitmontop:: @ 8604804
	.incbin "sound/direct_sound_samples/cry_hitmontop.bin"

	.align 2
Cry_Smoochum:: @ 86055E4
	.incbin "sound/direct_sound_samples/cry_smoochum.bin"

	.align 2
Cry_Elekid:: @ 8606198
	.incbin "sound/direct_sound_samples/cry_elekid.bin"

	.align 2
Cry_Magby:: @ 8606C24
	.incbin "sound/direct_sound_samples/cry_magby.bin"

	.align 2
Cry_Miltank:: @ 8607A94
	.incbin "sound/direct_sound_samples/cry_miltank.bin"

	.align 2
Cry_Blissey:: @ 8608970
	.incbin "sound/direct_sound_samples/cry_blissey.bin"

	.align 2
Cry_Raikou:: @ 8609A04
	.incbin "sound/direct_sound_samples/cry_raikou.bin"

	.align 2
Cry_Entei:: @ 860AB74
	.incbin "sound/direct_sound_samples/cry_entei.bin"

	.align 2
Cry_Suicune:: @ 860BFE8
	.incbin "sound/direct_sound_samples/cry_suicune.bin"

	.align 2
Cry_Larvitar:: @ 860D230
	.incbin "sound/direct_sound_samples/cry_larvitar.bin"

	.align 2
Cry_Pupitar:: @ 860DEE0
	.incbin "sound/direct_sound_samples/cry_pupitar.bin"

	.align 2
Cry_Tyranitar:: @ 860E750
	.incbin "sound/direct_sound_samples/cry_tyranitar.bin"

	.align 2
Cry_Lugia:: @ 860FEB0
	.incbin "sound/direct_sound_samples/cry_lugia.bin"

	.align 2
Cry_HoOh:: @ 86124A8
	.incbin "sound/direct_sound_samples/cry_ho_oh.bin"

	.align 2
Cry_Celebi:: @ 8613B3C
	.incbin "sound/direct_sound_samples/cry_celebi.bin"

	.align 2
Cry_Kecleon:: @ 86149B4
	.incbin "sound/direct_sound_samples/cry_kecleon.bin"

	.align 2
Cry_Roselia:: @ 8615214
	.incbin "sound/direct_sound_samples/cry_roselia.bin"

	.align 2
Cry_Torkoal:: @ 8615CD4
	.incbin "sound/direct_sound_samples/cry_torkoal.bin"

	.align 2
Cry_Electrike:: @ 8616620
	.incbin "sound/direct_sound_samples/cry_electrike.bin"

	.align 2
Cry_Manectric:: @ 861727C
	.incbin "sound/direct_sound_samples/cry_manectric.bin"

	.align 2
Cry_Duskull:: @ 8618784
	.incbin "sound/direct_sound_samples/cry_duskull.bin"

	.align 2
Cry_Latias:: @ 861921C
	.incbin "sound/direct_sound_samples/cry_latias.bin"

	.align 2
Cry_Wynaut:: @ 8619E4C
	.incbin "sound/direct_sound_samples/cry_wynaut.bin"

	.align 2
Cry_Seviper:: @ 861AC2C
	.incbin "sound/direct_sound_samples/cry_seviper.bin"

	.align 2
Cry_Sharpedo:: @ 861B7CC
	.incbin "sound/direct_sound_samples/cry_sharpedo.bin"

	.align 2
Cry_Zangoose:: @ 861CED8
	.incbin "sound/direct_sound_samples/cry_zangoose.bin"

	.align 2
Cry_Azurill:: @ 861D868
	.incbin "sound/direct_sound_samples/cry_azurill.bin"

	.align 2
Cry_Swablu:: @ 861E2D0
	.incbin "sound/direct_sound_samples/cry_swablu.bin"

	.align 2
Cry_Altaria:: @ 861E868
	.incbin "sound/direct_sound_samples/cry_altaria.bin"

	.align 2
Cry_Unused265:: @ 861F384
	.incbin "sound/direct_sound_samples/cry_unused_265.bin"

	.align 2
Cry_Taillow:: @ 861FCD8
	.incbin "sound/direct_sound_samples/cry_taillow.bin"

	.align 2
Cry_Swellow:: @ 86202D8
	.incbin "sound/direct_sound_samples/cry_swellow.bin"

	.align 2
Cry_Unused268:: @ 8620BDC
	.incbin "sound/direct_sound_samples/cry_unused_268.bin"

	.align 2
Cry_Spinda:: @ 8621D8C
	.incbin "sound/direct_sound_samples/cry_spinda.bin"

	.align 2
Cry_Torchic:: @ 86229F8
	.incbin "sound/direct_sound_samples/cry_torchic.bin"

	.align 2
Cry_Combusken:: @ 86233A0
	.incbin "sound/direct_sound_samples/cry_combusken.bin"

	.align 2
Cry_Blaziken:: @ 8625074
	.incbin "sound/direct_sound_samples/cry_blaziken.bin"

	.align 2
Cry_Treecko:: @ 8626FF4
	.incbin "sound/direct_sound_samples/cry_treecko.bin"

	.align 2
Cry_Grovyle:: @ 8627B9C
	.incbin "sound/direct_sound_samples/cry_grovyle.bin"

	.align 2
Cry_Sceptile:: @ 8629010
	.incbin "sound/direct_sound_samples/cry_sceptile.bin"

	.align 2
Cry_Mudkip:: @ 862AA2C
	.incbin "sound/direct_sound_samples/cry_mudkip.bin"

	.align 2
Cry_Marshtomp:: @ 862B1B0
	.incbin "sound/direct_sound_samples/cry_marshtomp.bin"

	.align 2
Cry_Swampert:: @ 862C2B4
	.incbin "sound/direct_sound_samples/cry_swampert.bin"

	.align 2
Cry_Pelipper:: @ 862D934
	.incbin "sound/direct_sound_samples/cry_pelipper.bin"

	.align 2
Cry_Wingull:: @ 862E4FC
	.incbin "sound/direct_sound_samples/cry_wingull.bin"

	.align 2
Cry_Banette:: @ 862F13C
	.incbin "sound/direct_sound_samples/cry_banette.bin"

	.align 2
Cry_Shuppet:: @ 862FDE4
	.incbin "sound/direct_sound_samples/cry_shuppet.bin"

	.align 2
Cry_Lotad:: @ 8630624
	.incbin "sound/direct_sound_samples/cry_lotad.bin"

	.align 2
Cry_Lombre:: @ 8630A8C
	.incbin "sound/direct_sound_samples/cry_lombre.bin"

	.align 2
Cry_Ludicolo:: @ 8631920
	.incbin "sound/direct_sound_samples/cry_ludicolo.bin"

	.align 2
Cry_Seedot:: @ 86329F0
	.incbin "sound/direct_sound_samples/cry_seedot.bin"

	.align 2
Cry_Nuzleaf:: @ 863321C
	.incbin "sound/direct_sound_samples/cry_nuzleaf.bin"

	.align 2
Cry_Shiftry:: @ 8633D84
	.incbin "sound/direct_sound_samples/cry_shiftry.bin"

	.align 2
Cry_Carvanha:: @ 8635148
	.incbin "sound/direct_sound_samples/cry_carvanha.bin"

	.align 2
Cry_Wurmple:: @ 8635B5C
	.incbin "sound/direct_sound_samples/cry_wurmple.bin"

	.align 2
Cry_Silcoon:: @ 8636428
	.incbin "sound/direct_sound_samples/cry_silcoon.bin"

	.align 2
Cry_Beautifly:: @ 8637454
	.incbin "sound/direct_sound_samples/cry_beautifly.bin"

	.align 2
Cry_Cascoon:: @ 8637C8C
	.incbin "sound/direct_sound_samples/cry_cascoon.bin"

	.align 2
Cry_Dustox:: @ 8638CD0
	.incbin "sound/direct_sound_samples/cry_dustox.bin"

	.align 2
Cry_Ralts:: @ 863997C
	.incbin "sound/direct_sound_samples/cry_ralts.bin"

	.align 2
Cry_Kirlia:: @ 863A398
	.incbin "sound/direct_sound_samples/cry_kirlia.bin"

	.align 2
Cry_Gardevoir:: @ 863AFC8
	.incbin "sound/direct_sound_samples/cry_gardevoir.bin"

	.align 2
Cry_Slakoth:: @ 863C82C
	.incbin "sound/direct_sound_samples/cry_slakoth.bin"

	.align 2
Cry_Vigoroth:: @ 863D0B0
	.incbin "sound/direct_sound_samples/cry_vigoroth.bin"

	.align 2
Cry_Slaking:: @ 863DF08
	.incbin "sound/direct_sound_samples/cry_slaking.bin"

	.align 2
Cry_Nincada:: @ 863E8F4
	.incbin "sound/direct_sound_samples/cry_nincada.bin"

	.align 2
Cry_Ninjask:: @ 863EF64
	.incbin "sound/direct_sound_samples/cry_ninjask.bin"

	.align 2
Cry_Shedinja:: @ 863FB8C
	.incbin "sound/direct_sound_samples/cry_shedinja.bin"

	.align 2
Cry_Makuhita:: @ 8640344
	.incbin "sound/direct_sound_samples/cry_makuhita.bin"

	.align 2
Cry_Hariyama:: @ 8640AA0
	.incbin "sound/direct_sound_samples/cry_hariyama.bin"

	.align 2
Cry_Nosepass:: @ 8641B58
	.incbin "sound/direct_sound_samples/cry_nosepass.bin"

	.align 2
Cry_Glalie:: @ 86428BC
	.incbin "sound/direct_sound_samples/cry_glalie.bin"

	.align 2
Cry_Plusle:: @ 8643DA0
	.incbin "sound/direct_sound_samples/cry_plusle.bin"

	.align 2
Cry_Minun:: @ 864469C
	.incbin "sound/direct_sound_samples/cry_minun.bin"

	.align 2
Cry_Surskit:: @ 86456A4
	.incbin "sound/direct_sound_samples/cry_surskit.bin"

	.align 2
Cry_Masquerain:: @ 8646124
	.incbin "sound/direct_sound_samples/cry_masquerain.bin"

	.align 2
Cry_Skitty:: @ 86474D8
	.incbin "sound/direct_sound_samples/cry_skitty.bin"

	.align 2
Cry_Delcatty:: @ 8647BEC
	.incbin "sound/direct_sound_samples/cry_delcatty.bin"

	.align 2
Cry_Gulpin:: @ 8649104
	.incbin "sound/direct_sound_samples/cry_gulpin.bin"

	.align 2
Cry_Swalot:: @ 8649908
	.incbin "sound/direct_sound_samples/cry_swalot.bin"

	.align 2
Cry_Numel:: @ 864AA68
	.incbin "sound/direct_sound_samples/cry_numel.bin"

	.align 2
Cry_Camerupt:: @ 864B3B4
	.incbin "sound/direct_sound_samples/cry_camerupt.bin"

	.align 2
Cry_Barboach:: @ 864CAD4
	.incbin "sound/direct_sound_samples/cry_barboach.bin"

	.align 2
Cry_Whiscash:: @ 864D410
	.incbin "sound/direct_sound_samples/cry_whiscash.bin"

	.align 2
Cry_Corphish:: @ 864E50C
	.incbin "sound/direct_sound_samples/cry_corphish.bin"

	.align 2
Cry_Crawdaunt:: @ 864F110
	.incbin "sound/direct_sound_samples/cry_crawdaunt.bin"

	.align 2
Cry_Spoink:: @ 86509C8
	.incbin "sound/direct_sound_samples/cry_spoink.bin"

	.align 2
Cry_Grumpig:: @ 8651108
	.incbin "sound/direct_sound_samples/cry_grumpig.bin"

	.align 2
Cry_Trapinch:: @ 8651DA8
	.incbin "sound/direct_sound_samples/cry_trapinch.bin"

	.align 2
Cry_Vibrava:: @ 86527CC
	.incbin "sound/direct_sound_samples/cry_vibrava.bin"

	.align 2
Cry_Flygon:: @ 86535D0
	.incbin "sound/direct_sound_samples/cry_flygon.bin"

	.align 2
Cry_Cacnea:: @ 8654FD8
	.incbin "sound/direct_sound_samples/cry_cacnea.bin"

	.align 2
Cry_Cacturne:: @ 86558C8
	.incbin "sound/direct_sound_samples/cry_cacturne.bin"

	.align 2
Cry_Baltoy:: @ 8656F78
	.incbin "sound/direct_sound_samples/cry_baltoy.bin"

	.align 2
Cry_Claydol:: @ 8657BFC
	.incbin "sound/direct_sound_samples/cry_claydol.bin"

	.align 2
Cry_Lunatone:: @ 8658F5C
	.incbin "sound/direct_sound_samples/cry_lunatone.bin"

	.align 2
Cry_Solrock:: @ 865A758
	.incbin "sound/direct_sound_samples/cry_solrock.bin"

	.align 2
Cry_Feebas:: @ 865B784
	.incbin "sound/direct_sound_samples/cry_feebas.bin"

	.align 2
Cry_Milotic:: @ 865BF58
	.incbin "sound/direct_sound_samples/cry_milotic.bin"

	.align 2
Cry_Absol:: @ 865E69C
	.incbin "sound/direct_sound_samples/cry_absol.bin"

	.align 2
Cry_Meditite:: @ 865F118
	.incbin "sound/direct_sound_samples/cry_meditite.bin"

	.align 2
Cry_Medicham:: @ 865F938
	.incbin "sound/direct_sound_samples/cry_medicham.bin"

	.align 2
Cry_Spheal:: @ 86609BC
	.incbin "sound/direct_sound_samples/cry_spheal.bin"

	.align 2
Cry_Sealeo:: @ 8660F70
	.incbin "sound/direct_sound_samples/cry_sealeo.bin"

	.align 2
Cry_Walrein:: @ 8661B48
	.incbin "sound/direct_sound_samples/cry_walrein.bin"

	.align 2
Cry_Clamperl:: @ 8663F94
	.incbin "sound/direct_sound_samples/cry_clamperl.bin"

	.align 2
Cry_Huntail:: @ 86651E4
	.incbin "sound/direct_sound_samples/cry_huntail.bin"

	.align 2
Cry_Gorebyss:: @ 86661CC
	.incbin "sound/direct_sound_samples/cry_gorebyss.bin"

	.align 2
Cry_Lileep:: @ 8667838
	.incbin "sound/direct_sound_samples/cry_lileep.bin"

	.align 2
Cry_Cradily:: @ 86681E0
	.incbin "sound/direct_sound_samples/cry_cradily.bin"

	.align 2
Cry_Anorith:: @ 8669F10
	.incbin "sound/direct_sound_samples/cry_anorith.bin"

	.align 2
Cry_Armaldo:: @ 866AAC8
	.incbin "sound/direct_sound_samples/cry_armaldo.bin"

	.align 2
Cry_Beldum:: @ 866C19C
	.incbin "sound/direct_sound_samples/cry_beldum.bin"

	.align 2
Cry_Metang:: @ 866CB3C
	.incbin "sound/direct_sound_samples/cry_metang.bin"

	.align 2
Cry_Metagross:: @ 866DE10
	.incbin "sound/direct_sound_samples/cry_metagross.bin"

	.align 2
Cry_Bagon:: @ 8670588
	.incbin "sound/direct_sound_samples/cry_bagon.bin"

	.align 2
Cry_Shelgon:: @ 8670D5C
	.incbin "sound/direct_sound_samples/cry_shelgon.bin"

	.align 2
Cry_Regirock:: @ 8672164
	.incbin "sound/direct_sound_samples/cry_regirock.bin"

	.align 2
Cry_Regice:: @ 8674140
	.incbin "sound/direct_sound_samples/cry_regice.bin"

	.align 2
Cry_Registeel:: @ 8676140
	.incbin "sound/direct_sound_samples/cry_registeel.bin"

	.align 2
Cry_Castform:: @ 8677844
	.incbin "sound/direct_sound_samples/cry_castform.bin"

	.align 2
Cry_Volbeat:: @ 86784DC
	.incbin "sound/direct_sound_samples/cry_volbeat.bin"

	.align 2
Cry_Illumise:: @ 8679064
	.incbin "sound/direct_sound_samples/cry_illumise.bin"

	.align 2
Cry_Poochyena:: @ 867A17C
	.incbin "sound/direct_sound_samples/cry_poochyena.bin"

	.align 2
Cry_Mightyena:: @ 867AAC4
	.incbin "sound/direct_sound_samples/cry_mightyena.bin"

	.align 2
Cry_Dusclops:: @ 867BE50
	.incbin "sound/direct_sound_samples/cry_dusclops.bin"

	.align 2
Cry_Sableye:: @ 867CC08
	.incbin "sound/direct_sound_samples/cry_sableye.bin"

	.align 2
Cry_Mawile:: @ 867D7AC
	.incbin "sound/direct_sound_samples/cry_mawile.bin"

	.align 2
Cry_Aron:: @ 867E32C
	.incbin "sound/direct_sound_samples/cry_aron.bin"

	.align 2
Cry_Lairon:: @ 867EC58
	.incbin "sound/direct_sound_samples/cry_lairon.bin"

	.align 2
Cry_Aggron:: @ 8680130
	.incbin "sound/direct_sound_samples/cry_aggron.bin"

	.align 2
Cry_Relicanth:: @ 8681AD4
	.incbin "sound/direct_sound_samples/cry_relicanth.bin"

	.align 2
Cry_Luvdisc:: @ 8682F04
	.incbin "sound/direct_sound_samples/cry_luvdisc.bin"

	.align 2
Cry_Groudon:: @ 86833E0
	.incbin "sound/direct_sound_samples/cry_groudon.bin"

	.align 2
Cry_Kyogre:: @ 86858EC
	.incbin "sound/direct_sound_samples/cry_kyogre.bin"

	.align 2
Cry_Rayquaza:: @ 8687CA4
	.incbin "sound/direct_sound_samples/cry_rayquaza.bin"

	.align 2
Cry_Salamence:: @ 86899D0
	.incbin "sound/direct_sound_samples/cry_salamence.bin"

	.align 2
Cry_Breloom:: @ 868B2EC
	.incbin "sound/direct_sound_samples/cry_breloom.bin"

	.align 2
Cry_Shroomish:: @ 868BFAC
	.incbin "sound/direct_sound_samples/cry_shroomish.bin"

	.align 2
Cry_Linoone:: @ 868C884
	.incbin "sound/direct_sound_samples/cry_linoone.bin"

	.align 2
Cry_Tropius:: @ 868E720
	.incbin "sound/direct_sound_samples/cry_tropius.bin"

	.align 2
Cry_Wailmer:: @ 86907E4
	.incbin "sound/direct_sound_samples/cry_wailmer.bin"

	.align 2
Cry_Zigzagoon:: @ 8692444
	.incbin "sound/direct_sound_samples/cry_zigzagoon.bin"

	.align 2
Cry_Exploud:: @ 8692FD4
	.incbin "sound/direct_sound_samples/cry_exploud.bin"

	.align 2
Cry_Loudred:: @ 8694C1C
	.incbin "sound/direct_sound_samples/cry_loudred.bin"

	.align 2
Cry_Wailord:: @ 8695944
	.incbin "sound/direct_sound_samples/cry_wailord.bin"

	.align 2
Cry_Whismur:: @ 8698354
	.incbin "sound/direct_sound_samples/cry_whismur.bin"

	.align 2
Cry_Snorunt:: @ 8698B78
	.incbin "sound/direct_sound_samples/cry_snorunt.bin"

	.align 2
Cry_Latios:: @ 8699C80
	.incbin "sound/direct_sound_samples/cry_latios.bin"

	.align 2
Cry_Jirachi:: @ 869B278
	.incbin "sound/direct_sound_samples/cry_jirachi.bin"

	.align 2
Cry_Deoxys:: @ 869BFFC
	.incbin "sound/direct_sound_samples/cry_deoxys.bin"

	.align 2
Cry_Chimecho:: @ 869D4D0
	.incbin "sound/direct_sound_samples/cry_chimecho.bin"

	.align 2

gDirectSoundWaveData_76:: @ 869DEE0
	.incbin "baserom.gba", 0x69DEE0, 0x1F60

gDirectSoundWaveData_77:: @ 869FE40
	.incbin "baserom.gba", 0x69FE40, 0x1AA0

gDirectSoundWaveData_78:: @ 86A18E0
	.incbin "baserom.gba", 0x6A18E0, 0x1F70

gDirectSoundWaveData_79:: @ 86A3850
	.incbin "baserom.gba", 0x6A3850, 0x1838

gDirectSoundWaveData_80:: @ 86A5088
	.incbin "baserom.gba", 0x6A5088, 0x13D0

gDirectSoundWaveData_81:: @ 86A6458
	.incbin "baserom.gba", 0x6A6458, 0x11C4

gDirectSoundWaveData_82:: @ 86A761C
	.incbin "baserom.gba", 0x6A761C, 0x1E70

gDirectSoundWaveData_83:: @ 86A948C
	.incbin "baserom.gba", 0x6A948C, 0x2FF0

gDirectSoundWaveData_84:: @ 86AC47C
	.incbin "baserom.gba", 0x6AC47C, 0x2C54

gDirectSoundWaveData_85:: @ 86AF0D0
	.incbin "baserom.gba", 0x6AF0D0, 0xA60

gDirectSoundWaveData_86:: @ 86AFB30
	.incbin "baserom.gba", 0x6AFB30, 0x2668

gDirectSoundWaveData_87:: @ 86B2198
	.incbin "baserom.gba", 0x6B2198, 0x13A8

gDirectSoundWaveData_88:: @ 86B3540
	.incbin "baserom.gba", 0x6B3540, 0x2100
