
gProgrammableWaveData_84A31EC::
	.incbin "sound/programmable_wave_samples/84A31EC.pcm"

gProgrammableWaveData_84A31FC::
	.incbin "sound/programmable_wave_samples/84A31FC.pcm"

gProgrammableWaveData_84A320C::
	.incbin "sound/programmable_wave_samples/84A320C.pcm"

gProgrammableWaveData_84A321C::
	.incbin "sound/programmable_wave_samples/84A321C.pcm"

gProgrammableWaveData_84A322C::
	.incbin "sound/programmable_wave_samples/84A322C.pcm"

gProgrammableWaveData_84A323C::
	.incbin "sound/programmable_wave_samples/84A323C.pcm"

gProgrammableWaveData_84A324C::
	.incbin "sound/programmable_wave_samples/84A324C.pcm"

gProgrammableWaveData_84A325C::
	.incbin "sound/programmable_wave_samples/84A325C.pcm"

gProgrammableWaveData_84A326C::
	.incbin "sound/programmable_wave_samples/84A326C.pcm"

gProgrammableWaveData_84A327C::
	.incbin "sound/programmable_wave_samples/84A327C.pcm"

gProgrammableWaveData_84A328C::
	.incbin "sound/programmable_wave_samples/84A328C.pcm"
