
gProgrammableWaveData_84A31EC:: @ 84A31EC
	.incbin "baserom.gba", 0x4A31EC, 0x10

gProgrammableWaveData_84A31FC:: @ 84A31FC
	.incbin "baserom.gba", 0x4A31FC, 0x10

gProgrammableWaveData_84A320C:: @ 84A320C
	.incbin "baserom.gba", 0x4A320C, 0x10

gProgrammableWaveData_84A321C:: @ 84A321C
	.incbin "baserom.gba", 0x4A321C, 0x10

gProgrammableWaveData_84A322C:: @ 84A322C
	.incbin "baserom.gba", 0x4A322C, 0x10

gProgrammableWaveData_84A323C:: @ 84A323C
	.incbin "baserom.gba", 0x4A323C, 0x10

gProgrammableWaveData_84A324C:: @ 84A324C
	.incbin "baserom.gba", 0x4A324C, 0x10

gProgrammableWaveData_84A325C:: @ 84A325C
	.incbin "baserom.gba", 0x4A325C, 0x10

gProgrammableWaveData_84A326C:: @ 84A326C
	.incbin "baserom.gba", 0x4A326C, 0x10

gProgrammableWaveData_84A327C:: @ 84A327C
	.incbin "baserom.gba", 0x4A327C, 0x10

gProgrammableWaveData_84A328C:: @ 84A328C
	.incbin "baserom.gba", 0x4A328C, 0x10
