	.align 2
voicegroup229::                                                                                             @ Num | Type         | Instrument Name
	voice_keysplit voicegroup233, KeySplitTable35                                                           @ 000 | Direct Sound | Piano 1
	voice_keysplit voicegroup234, KeySplitTable36                                                           @ 001 | Direct Sound | Piano 2
	voice_keysplit voicegroup235, KeySplitTable37                                                           @ 002 | Direct Sound | Piano 3 (Octave)
	voice_keysplit voicegroup236, KeySplitTable9                                                            @ 003 | Direct Sound | Rhodes 1
	voice_keysplit voicegroup237, KeySplitTable9                                                            @ 004 | Direct Sound | Rhodes 2
	voice_keysplit voicegroup238, KeySplitTable36                                                           @ 005 | Direct Sound | Vibraphone
	voice_keysplit voicegroup239, KeySplitTable38                                                           @ 006 | Direct Sound | Marimba
	voice_keysplit voicegroup240, KeySplitTable39                                                           @ 007 | Direct Sound | Xylophone
	voice_keysplit voicegroup241, KeySplitTable25                                                           @ 008 | Direct Sound | Tubular Bell
	voice_keysplit voicegroup242, KeySplitTable36                                                           @ 009 | Direct Sound | Glockenspiel
	voice_keysplit voicegroup243, KeySplitTable38                                                           @ 010 | Direct Sound | Music Box
	voice_keysplit voicegroup244, KeySplitTable40                                                           @ 011 | Direct Sound | Drawbar Organ
	voice_keysplit voicegroup245, KeySplitTable40                                                           @ 012 | Direct Sound | Jazz Organ
	voice_keysplit voicegroup246, KeySplitTable40                                                           @ 013 | Direct Sound | Accordion
	voice_keysplit voicegroup247, KeySplitTable41                                                           @ 014 | Direct Sound | Nylon Guitar
	voice_keysplit voicegroup248, KeySplitTable41                                                           @ 015 | Direct Sound | Martin Guitar
	voice_keysplit voicegroup249, KeySplitTable32                                                           @ 016 | Direct Sound | Distortion Guitar 1
	voice_keysplit voicegroup250, KeySplitTable32                                                           @ 017 | Direct Sound | Distortion Guitar 2
	voice_keysplit voicegroup251, KeySplitTable41                                                           @ 018 | Direct Sound | Clean Guitar
	voice_keysplit voicegroup252, KeySplitTable42                                                           @ 019 | Direct Sound | Upright Bass
	voice_keysplit voicegroup253, KeySplitTable43                                                           @ 020 | Direct Sound | Fingered Bass
	voice_directsound 60, 0, DirectSoundWaveData_dp_slapbass_c1_16, 255, 0, 255, 192                        @ 021 | Direct Sound | Slap Bass
	voice_keysplit voicegroup254, KeySplitTable44                                                           @ 022 | Direct Sound | Synth Bass
	voice_keysplit voicegroup255, KeySplitTable45                                                           @ 023 | Direct Sound | Strings
	voice_keysplit voicegroup256, KeySplitTable46                                                           @ 024 | Direct Sound | Violin
	voice_keysplit voicegroup257, KeySplitTable47                                                           @ 025 | Direct Sound | Cello
	voice_keysplit voicegroup258, KeySplitTable48                                                           @ 026 | Direct Sound | Pizzicato
	voice_keysplit voicegroup259, KeySplitTable40                                                           @ 027 | Direct Sound | Harp
	voice_keysplit voicegroup260, KeySplitTable40                                                           @ 028 | Direct Sound | Timpani
	voice_keysplit voicegroup261, KeySplitTable39                                                           @ 029 | Direct Sound | Trumpets
	voice_keysplit voicegroup262, KeySplitTable47                                                           @ 030 | Direct Sound | Trombones
	voice_keysplit voicegroup263, KeySplitTable49                                                           @ 031 | Direct Sound | French Horn Solo
	voice_keysplit voicegroup264, KeySplitTable50                                                           @ 032 | Direct Sound | French Horns
	voice_keysplit voicegroup265, KeySplitTable51                                                           @ 033 | Direct Sound | Oboe
	voice_keysplit voicegroup266, KeySplitTable52                                                           @ 034 | Direct Sound | Clarinet
	voice_keysplit voicegroup267, KeySplitTable53                                                           @ 035 | Direct Sound | Flute
	voice_keysplit voicegroup268, KeySplitTable54                                                           @ 036 | Direct Sound | Bassoon
	voice_keysplit voicegroup269, KeySplitTable55                                                           @ 037 | Direct Sound | Orchestra Hit
	voice_keysplit voicegroup270, KeySplitTable38                                                           @ 038 | Direct Sound | Square Wave
	voice_keysplit_all voicegroup230				                                                        @ 039 | Direct Sound | Drum (Main)
	voice_keysplit_all voicegroup231				                                                        @ 040 | Direct Sound | Drum (Taiko)
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_d3_16, 255, 251, 0, 171                        @ 041 | Direct Sound | Wood Bass
	voice_keysplit voicegroup271, KeySplitTable56                                                           @ 042 | Direct Sound | Koto
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 40, 211                           @ 043 | Direct Sound | Sampled Square 50% 1
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_wind, 67, 243, 155, 224                            @ 044 | Direct Sound | Wind Effect
	voice_directsound 60, 0, DirectSoundWaveData_dp_explosion, 67, 255, 0, 245                              @ 045 | Direct Sound | Explosion Effect
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 250, 0, 171                      @ 046 | Direct Sound | Sampled Square | 1 octave too low
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_bubbles, 255, 0, 255, 0                            @ 047 | Direct Sound | Bubble Effect
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 25, 0                             @ 048 | Direct Sound | Sampled Square 50% 2 | also 066 in BATTLE4 and DUNGEON4
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 252, 0, 96                             @ 049 | Direct Sound | Sampled Square 50% 3
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 250, 0, 220                            @ 050 | Direct Sound | Sampled Square 50% 4
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 224, 242, 101, 220                          @ 051 | Direct Sound | Sampled Square 50% 5
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 224, 242, 101, 192                          @ 052 | Direct Sound | Sampled Square 50% 6
	voice_directsound 60, 0, DirectSoundWaveData_purenoise, 42, 0, 57, 192                                  @ 053 | Direct Sound | Sampled Noise 1
	voice_directsound 60, 0, DirectSoundWaveData_purenoise, 240, 242, 0, 192                                @ 054 | Direct Sound | Sampled Noise 2
@	voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 246, 78, 192                        @ 055 | Direct Sound | Whistle (DP) | Starting this line are remaining voices wraping around to voicegroup230
@	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 0, 255, 16                           @ 056 | Direct Sound | Reverse Cymbal 1 (DP)
@	voice_directsound 60, 0, DirectSoundWaveData_dp_org5_c3_16, 255, 167, 235, 171                          @ 057 | Direct Sound | Organ (DP)
@	voice_directsound 60, 0, DirectSoundWaveData_puresquare_37, 80, 234, 191, 220                           @ 058 | Direct Sound | Sampled Square 37.5%
@	voice_directsound 60, 0, DirectSoundWaveData_puresquare_12, 80, 234, 191, 220                           @ 059 | Direct Sound | Sampled Square 12.5%
@	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitmajor60, 255, 197, 255, 171                      @ 060 | Direct Sound | Orchestra Hit Major (DP)
@	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitminor60, 255, 197, 255, 171                      @ 061 | Direct Sound | Orchestra Hit Minor (DP)
@	voice_keysplit_all voicegroup232                                                                        @ 062 | Direct Sound | Drum (Synth Kick + Snare)
@	voice_keysplit voicegroup216, KeySplitTable27                                                           @ 063 | Direct Sound | Timpani (DP)
@	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass1_c2_16, 255, 42, 255, 192                       @ 064 | Direct Sound | Synth Bass 1 (DP)
@	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass2_c1_16, 255, 0, 255, 220                        @ 065 | Direct Sound | Synth Bass 2 (DP)
@	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171                      @ 066 | Direct Sound | Sawtooth
@	voice_keysplit voicegroup272, KeySplitTable57                                                           @ 067 | Direct Sound | Shamisen
@	voice_directsound 60, 0, DirectSoundWaveData_hg_hyoshigi, 255, 0, 255, 171                              @ 068 | Direct Sound | Hyoshigi
@	voice_directsound 60, 0, DirectSoundWaveData_hg_kodaiko, 255, 0, 255, 171                               @ 069 | Direct Sound | Kodaiko
@	voice_directsound 60, 0, DirectSoundWaveData_hg_tsuzumi, 255, 0, 255, 171                               @ 070 | Direct Sound | Tsuzumi
@	voice_directsound 60, 0, DirectSoundWaveData_hg_jinglebell, 255, 0, 255, 171                            @ 071 | Direct Sound | Jingle Bell
@	voice_directsound 60, 0, DirectSoundWaveData_hg_hoohclap, 255, 0, 255, 0                                @ 072 | Direct Sound | Hand Clap (Ho-Oh)
@	voice_directsound 60, 0, DirectSoundWaveData_dp_tenorchoir48, 255, 197, 255, 171                        @ 073 | Direct Sound | Tenor Choir (DP)
@	voice_directsound 60, 0, DirectSoundWaveData_dp_sopranochoir60, 255, 197, 255, 171                      @ 074 | Direct Sound | Soprano Choir (DP)
@	voice_directsound 60, 0, DirectSoundWaveData_hg_choirc5, 255, 197, 255, 171                             @ 075 | Direct Sound | Choir | 1 octave too low
@	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 197, 255, 171 	                    @ 076 | Direct Sound | Reverse Cymbal 1 (DP) | 1 octave too high
@	voice_directsound 60, 0, DirectSoundWaveData_dp_spearpillarwind60, 255, 0, 255, 32                      @ 077 | Direct Sound | Wind Effect (Spear Pillar)
@	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, 255, 216, 252, 192                       @ 078 | Direct Sound | Altosax
@	voice_directsound 60, 0, DirectSoundWaveData_dp_synthsnare, 255, 0, 255, 171                            @ 079 | Direct Sound | Synth Snare
@	voice_keysplit voicegroup273, KeySplitTable58                                                           @ 080 | Direct Sound | Piano 4 (National Park)
@	voice_directsound 60, 0, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32                                @ 081 | Direct Sound | Tom
@	voice_keysplit voicegroup219, KeySplitTable29                                                           @ 082 | Direct Sound | Trumpets (Arceus)
@	voice_keysplit voicegroup220, KeySplitTable30                                                           @ 083 | Direct Sound | Trombones (Arceus)
