OneIsland_PokemonCenter_1F_Text_BillHeyThereCelio:: @ 81A0CDE
    .string "Bill: Hey, there!\n"
    .string "Celio!$"

OneIsland_PokemonCenter_1F_Text_CelioCantBelieveYouCameOut:: @ 81A0CF7
    .string "Celio: Bill!\n"
    .string "I can't believe you came out here.$"

OneIsland_PokemonCenter_1F_Text_BillHowsYourResearchComing:: @ 81A0D27
    .string "Bill: Well, absolutely!\n"
    .string "How's your research coming along?\p"
    .string "…Oh, wait a sec.$"

OneIsland_PokemonCenter_1F_Text_ThisIsMyBuddyCelio:: @ 81A0D72
    .string "{PLAYER}, this is my buddy Celio.\n"
    .string "He's one dedicated PC Maniac!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsRisingPokemonChamp:: @ 81A0DAC
    .string "Celio, this is {PLAYER}, a rising\n"
    .string "contender as the Pokémon Champ!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsReigningPokemonChamp:: @ 81A0DE8
    .string "Celio, this is {PLAYER}, the\n"
    .string "reigning Pokémon Champ!$"

OneIsland_PokemonCenter_1F_Text_CelioThatsReallyImpressive:: @ 81A0E17
    .string "Celio: That's really impressive.\p"
    .string "I hate to say it, but I have zero\n"
    .string "aptitude for battling.\p"
    .string "Anyways, I'm glad to meet you.$"

OneIsland_PokemonCenter_1F_Text_BillBringMeUpToSpeed:: @ 81A0E90
    .string "Bill: So, bring me up to speed.\n"
    .string "How's your machine running?$"

OneIsland_PokemonCenter_1F_Text_CelioPCsCantLinkWithYours:: @ 81A0ECC
    .string "Celio: It's running fine, but we're\n"
    .string "too remote out here.\p"
    .string "The PCs on this island just can't\n"
    .string "link with your PC, Bill.$"

OneIsland_PokemonCenter_1F_Text_BillLetMeHelpYou:: @ 81A0F40
    .string "Bill: Oh, yeah?\n"
    .string "Okay, let me take a look-see.\p"
    .string "…Hang on here…\n"
    .string "I think we can make it work.\l"
    .string "Let me help you, okay?$"

OneIsland_PokemonCenter_1F_Text_CanYouDeliverThisMeteoritePlayer:: @ 81A0FB1
    .string "{PLAYER}, can I get you to wait for\n"
    .string "me just a bit?\p"
    .string "…Actually, can I get you to do\n"
    .string "me a favor?\p"
    .string "The island next to this one's\n"
    .string "called Two Island.\p"
    .string "There's a guy there that runs\n"
    .string "a Game Corner.\p"
    .string "He has this thing for rare rocks\n"
    .string "and gems.\p"
    .string "We keep in touch, being fellow\n"
    .string "maniacs.\p"
    .string "So, can I get you to deliver this\n"
    .string "Meteorite to him?$"

OneIsland_PokemonCenter_1F_Text_AcceptedMeteoriteFromBill:: @ 81A10EE
    .string "{PLAYER} accepted the Meteorite\n"
    .string "from Bill.$"

OneIsland_PokemonCenter_1F_Text_CelioPleaseTakeThis:: @ 81A1113
    .string "Celio: {PLAYER}, if you are going\n"
    .string "to Two Island, please take this.$"

OneIsland_PokemonCenter_1F_Text_PassLetsYouTravelBetweenIslands:: @ 81A1150
    .string "It's a Pass for the ferry service\n"
    .string "serving the local islands.\p"
    .string "It will let you travel between the\n"
    .string "Islands One, Two, and Three.\p"
    .string "Oh, you should have this, too.$"

OneIsland_PokemonCenter_1F_Text_ReceivedExtraPageForTownMap:: @ 81A11EC
    .string "{PLAYER} received an extra page\n"
    .string "for the Town Map!$"

OneIsland_PokemonCenter_1F_Text_ReceivedTownMap:: @ 81A1218
    .string "{PLAYER} received\n"
    .string "a Town Map!$"

OneIsland_PokemonCenter_1F_Text_BillCatchYouLater:: @ 81A1230
    .string "Bill: I'll catch you later!\n"
    .string "Say hi to the guy for me!$"

OneIsland_PokemonCenter_1F_Text_HmmHowAboutLikeThis:: @ 81A1266
    .string "Hmm…\p"
    .string "How about we try this like this…$"

OneIsland_PokemonCenter_1F_Text_GotPCWorkingStrollAWhileMore:: @ 81A128C
    .string "Oh, hey, {PLAYER}!\p"
    .string "Did you see?\n"
    .string "We got the PC working!\p"
    .string "I've got a few things to show\n"
    .string "Celio here.\p"
    .string "Can you go out on a stroll or\n"
    .string "something for a while more?$"

OneIsland_PokemonCenter_1F_Text_SorryForBeingPoorHost:: @ 81A1321
    .string "I'm sorry for taking up so much of\n"
    .string "Bill's time.\p"
    .string "I'm also sorry for being such a \n"
    .string "poor host on your visit here.$"

OneIsland_PokemonCenter_1F_Text_UsualPCServicesUnavailable:: @ 81A1390
    .string "The usual PC services aren't\n"
    .string "available…$"

OneIsland_PokemonCenter_1F_Text_BillOhHeyPlayer:: @ 81A13B8
    .string "Bill: Oh, hey!\n"
    .string "{PLAYER}!$"

OneIsland_PokemonCenter_1F_Text_BillWeGotItDone:: @ 81A13CB
    .string "Bill: What kept you so long?\n"
    .string "Been out having a good time?\p"
    .string "We got it done.\n"
    .string "The PCs are up and running!$"

OneIsland_PokemonCenter_1F_Text_CelioJobWentQuick:: @ 81A1431
    .string "Celio: The job went incredibly\n"
    .string "quick.\p"
    .string "Bill is one amazing guy…$"

OneIsland_PokemonCenter_1F_Text_BillYouveLearnedALot:: @ 81A1470
    .string "Bill: No, no! There was almost\n"
    .string "nothing left for me to do.\p"
    .string "Celio, I have to hand it to you.\n"
    .string "You've learned a lot.$"

OneIsland_PokemonCenter_1F_Text_CelioOhReallyEhehe:: @ 81A14E1
    .string "Celio: Oh, really?\n"
    .string "Ehehe…$"

OneIsland_PokemonCenter_1F_Text_BillWeShouldHeadBackToKanto:: @ 81A14FB
    .string "Bill: Well, there you have it.\n"
    .string "I'm finished with the job.\l"
    .string "We should head back to Kanto.\p"
    .string "Celio, I'll be seeing you again.$"

OneIsland_PokemonCenter_1F_Text_CelioPromiseIllShowYouAroundSometime:: @ 81A1574
    .string "Celio: {PLAYER}, I'm really sorry\n"
    .string "that we sent you off alone today.\p"
    .string "I promise, I will show you around\n"
    .string "these islands sometime.$"

OneIsland_PokemonCenter_1F_Text_CelioImModifyingMyNetworkMachine:: @ 81A15EC
    .string "Celio: Hello!\n"
    .string "You look awfully busy as always.\p"
    .string "How am I doing?\p"
    .string "Well, I'm modifying my Network\n"
    .string "Machine.\p"
    .string "When I get done with the machine,\n"
    .string "I hope you'll be first to use it,\l"
    .string "{PLAYER}.$"

OneIsland_PokemonCenter_1F_Text_CelioCaughtMoreMonMaybeICanBeUseful:: @ 81A169B
    .string "Celio: {PLAYER}, how have things\n"
    .string "been for you?\p"
    .string "Oh, is that right?\n"
    .string "You've caught more Pokémon.\p"
    .string "Do you know what?\n"
    .string "Maybe I can be useful to you.$"

OneIsland_PokemonCenter_1F_Text_YoullBeTradingFromTrainersFarAway:: @ 81A1723
    .string "I'm modifying the Network Machine\n"
    .string "right now.\p"
    .string "I'm changing it so it can handle\n"
    .string "trades over long distances.\p"
    .string "When I get finished, you'll be\n"
    .string "trading for exotic Pokémon from\l"
    .string "Trainers far away.$"

OneIsland_PokemonCenter_1F_Text_NeedsSpecialGemstone:: @ 81A17DF
    .string "But, there is a slight catch.\p"
    .string "For the link to work, the Machine\n"
    .string "needs a special gemstone.\p"
    .string "It's supposed to be on One Island,\n"
    .string "but I haven't found one yet.\p"
    .string "Who knows where it could be.$"

OneIsland_PokemonCenter_1F_Text_TryingToFindGem:: @ 81A1896
    .string "I was trying to find the gem\n"
    .string "even while I was studying.\p"
    .string "As a result, I've made no headway\n"
    .string "in both my search and studies…\p"
    .string "If I relied on Bill, I'm sure my\n"
    .string "research would progress.\p"
    .string "But this time, I want to try to do\n"
    .string "things by myself.$"

OneIsland_PokemonCenter_1F_Text_OhThats:: @ 81A197E
    .string "Oh!\n"
    .string "Th-that's…$"

OneIsland_PokemonCenter_1F_Text_HandedRubyToCelio:: @ 81A198D
    .string "{PLAYER} handed the Ruby\n"
    .string "to Celio.$"

OneIsland_PokemonCenter_1F_Text_MayIAskOneMoreFavor:: @ 81A19AA
    .string "Thank you!\n"
    .string "{PLAYER}, you're simply amazing.\p"
    .string "… … …  … … …\p"
    .string "Um… May I ask one more giant favor\n"
    .string "of you?$"

OneIsland_PokemonCenter_1F_Text_PleaseINeedYourHelp:: @ 81A1A08
    .string "It… It's not anything weird.\n"
    .string "Please, I need your help.$"

OneIsland_PokemonCenter_1F_Text_AnotherGemstoneInSeviiIslands:: @ 81A1A3F
    .string "While I was studying gemstones,\n"
    .string "I discovered something important.\p"
    .string "There is another gem that forms\n"
    .string "a pair with this Ruby.\p"
    .string "That other gemstone is supposed to\n"
    .string "be in the Sevii Islands.\p"
    .string "{PLAYER}, please, I need you to go\n"
    .string "find the other gem.\p"
    .string "{PLAYER}, may I have your ferry\n"
    .string "Pass and the Town Map?$"

OneIsland_PokemonCenter_1F_Text_ReturnedTriPassForRainbowPass:: @ 81A1B56
    .string "{PLAYER} returned the Tri-Pass and\n"
    .string "received the Rainbow Pass.$"

OneIsland_PokemonCenter_1F_Text_ObtainedExtraMapPage:: @ 81A1B8E
    .string "Obtained an extra page for the\n"
    .string "Town Map!$"

OneIsland_PokemonCenter_1F_Text_PassLetYouGetToAllIslands:: @ 81A1BB7
    .string "This is my own ferry Pass.\p"
    .string "It will let you get to all the\n"
    .string "Sevii Islands.\p"
    .string "{PLAYER}, please, I can't do\n"
    .string "it without your help.$"

OneIsland_PokemonCenter_1F_Text_HandedSapphireToCelio:: @ 81A1C2D
    .string "{PLAYER} handed the Sapphire\n"
    .string "to Celio.$"

OneIsland_PokemonCenter_1F_Text_ThankYouGiveMeTime:: @ 81A1C4E
    .string "Celio: So this is the gem that\n"
    .string "forms a pair with the Ruby…\p"
    .string "{PLAYER}, you've gone through a lot\n"
    .string "to get this, didn't you?\p"
    .string "You don't have to tell me. I know\n"
    .string "it wasn't easy.\p"
    .string "Thank you so much!\p"
    .string "Now it's my turn to work for you!\n"
    .string "Please give me a little time.$"

OneIsland_PokemonCenter_1F_Text_OkayThisIsGood:: @ 81A1D45
    .string "Okay, this is good…$"

OneIsland_PokemonCenter_1F_Text_LinkedUpWithLanette:: @ 81A1D59
    .string "I did it!\n"
    .string "I linked up with Lanette!$"

OneIsland_PokemonCenter_1F_Text_ManagedToLinkWithHoennThankYou:: @ 81A1D7D
    .string "{PLAYER}…\n"
    .string "{PLAYER}, I did it!\p"
    .string "I've managed to link up with\n"
    .string "Trainers in the Hoenn region!\p"
    .string "Finally, the Network Machine is\n"
    .string "fully operational!\p"
    .string "{PLAYER}, I owe it all to you!\p"
    .string "Thanks to you, my dream came\n"
    .string "true…$"

OneIsland_PokemonCenter_1F_Text_WishYouBestOfLuck:: @ 81A1E39
    .string "I…\n"
    .string "I'm not crying.\p"
    .string "That's enough about me!\p"
    .string "{PLAYER}, you're going to keep\n"
    .string "looking for exotic Pokémon, right?\p"
    .string "I wish you the best of luck!$"

OneIsland_PokemonCenter_1F_Text_CelioHearingRumorsAboutYou:: @ 81A1EBD
    .string "Celio: Hello!\p"
    .string "{PLAYER}, I've been hearing rumors\n"
    .string "about you.$"

OneIsland_PokemonCenter_1F_Text_BillsFirstMonWasAbra:: @ 81A1EF3
    .string "{PLAYER}, what's your favorite kind\n"
    .string "of Pokémon?\p"
    .string "Bill is a Pokémaniac, so he loves\n"
    .string "every kind.\p"
    .string "Apparently, the first one he caught\n"
    .string "was an Abra.$"

OneIsland_PokemonCenter_1F_Text_BillsHometownInGoldenrod:: @ 81A1F7C
    .string "By the way, {PLAYER}, you're from\n"
    .string "Pallet Town, aren't you?\p"
    .string "I've heard that it's a quiet and\n"
    .string "pleasant place.\p"
    .string "Bill's hometown is Goldenrod City,\n"
    .string "where his folks still live.\p"
    .string "I've heard that it's quite the\n"
    .string "festive, bustling city.\p"
    .string "I'd like to go there one day.$"

OneIsland_PokemonCenter_1F_Text_BillCantStomachMilk:: @ 81A2076
    .string "{PLAYER}, is there anything that\n"
    .string "you can't stand?\p"
    .string "Apparently, Bill simply can't\n"
    .string "stomach milk at all.$"

OneIsland_PokemonCenter_1F_Text_CameFromPalletDontKnowIt:: @ 81A20D5
    .string "Oh, you're a stranger here!\n"
    .string "Hi! Where did you come from?\p"
    .string "…Pallet Town?\n"
    .string "I don't know it!$"

OneIsland_PokemonCenter_1F_Text_EnormousVolcanoOnIsland:: @ 81A212D
    .string "On this island, there's an enormous\n"
    .string "volcano.\p"
    .string "It hasn't erupted lately, so why\n"
    .string "not enjoy a hike?$"

OneIsland_PokemonCenter_1F_Text_WishICouldTradeWithBoyfriend:: @ 81A218D
    .string "I wish I could trade Pokémon with\n"
    .string "my boyfriend who lives far away…$"

OneIsland_PokemonCenter_1F_Text_TradedWithFarAwayBoyfriend:: @ 81A21D0
    .string "I traded Pokémon with my boyfriend\n"
    .string "far away!\p"
    .string "Everyone's saying that we can\n"
    .string "thank you and Celio.\p"
    .string "So, thank you!$"

OneIsland_PokemonCenter_1F_Text_MachineUnderAdjustment:: @ 81A223F
    .string "Network Machine\n"
    .string "Link Level 0\p"
    .string "…Pokémon Storage System under\n"
    .string "adjustment…$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKanto:: @ 81A2286
    .string "Network Machine\n"
    .string "Link Level 1\p"
    .string "Link established with the Kanto\n"
    .string "region.$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKantoAndHoenn:: @ 81A22CB
    .string "Network Machine\n"
    .string "Link Level 2\p"
    .string "Link established with the Kanto\n"
    .string "and Hoenn regions.$"

OneIsland_PokemonCenter_1F_Text_ObtainedTriPass:: @ 81A231B
    .string "Obtained the Tri-Pass!$"

