gUnknown_81759F5:: @ 81759F5
    .string "Sssh!\n"
    .string "Can't you see I'm hiding?$"

gUnknown_8175A15:: @ 8175A15
    .string "Huh?\n"
    .string "TEAM ROCKET is gone?$"

Text_175A2F:: @ 8175A2F
    .string "TEAM ROCKET has taken control\n"
    .string "of SILPH CO.!$"

Text_175A5B:: @ 8175A5B
    .string "Arrgh!$"

gUnknown_8175A62:: @ 8175A62
    .string "Fwahahaha!\n"
    .string "My BOSS has been after this place!$"

Text_175A90:: @ 8175A90
    .string "My POKéMON is my loyal servant.$"

Text_175AB0:: @ 8175AB0
    .string "Darn!\n"
    .string "You weak POKéMON!$"

gUnknown_8175AC8:: @ 8175AC8
    .string "The doors are electronically\n"
    .string "locked.\p"
    .string "It takes a CARD KEY to open the\n"
    .string "doors here.$"

Text_175B19:: @ 8175B19
    .string "Intruder spotted!$"

Text_175B2B:: @ 8175B2B
    .string "Who are you?$"

gUnknown_8175B38:: @ 8175B38
    .string "I better tell the BOSS on 11F!$"

gUnknown_8175B57:: @ 8175B57
    .string "SILPH CO. HEAD OFFICE\n"
    .string "4F$"

