SilphCo_4F_Text_CantYouSeeImHiding:: @ 81759F5
    .string "Sssh!\n"
    .string "Can't you see I'm hiding?$"

SilphCo_4F_Text_TeamRocketIsGone:: @ 8175A15
    .string "Huh?\n"
    .string "Team Rocket is gone?$"

SilphCo_4F_Text_Grunt1Intro:: @ 8175A2F
    .string "Team Rocket has taken control\n"
    .string "of Silph Co.!$"

SilphCo_4F_Text_Grunt1Defeat:: @ 8175A5B
    .string "Arrgh!$"

SilphCo_4F_Text_Grunt1PostBattle:: @ 8175A62
    .string "Fwahahaha!\n"
    .string "My Boss has been after this place!$"

SilphCo_4F_Text_RodneyIntro:: @ 8175A90
    .string "My Pokémon is my loyal servant.$"

SilphCo_4F_Text_RodneyDefeat:: @ 8175AB0
    .string "Darn!\n"
    .string "You weak Pokémon!$"

SilphCo_4F_Text_RodneyPostBattle:: @ 8175AC8
    .string "The doors are electronically\n"
    .string "locked.\p"
    .string "It takes a Card Key to open the\n"
    .string "doors here.$"

SilphCo_4F_Text_Grunt2Intro:: @ 8175B19
    .string "Intruder spotted!$"

SilphCo_4F_Text_Grunt2Defeat:: @ 8175B2B
    .string "Who are you?$"

SilphCo_4F_Text_Grunt2PostBattle:: @ 8175B38
    .string "I better tell the Boss on 11F!$"

SilphCo_4F_Text_FloorSign:: @ 8175B57
    .string "Silph Co. Head Office\n"
    .string "4F$"

