SixIsland_GreenPath_Text_JaclynIntro:: @ 818B7B0
    .string "…Huh?\p"
    .string "I was envisioning my house, but\n"
    .string "this is where I TELEPORT?$"

SixIsland_GreenPath_Text_JaclynDefeat:: @ 818B7F0
    .string "Big boo-boo!$"

SixIsland_GreenPath_Text_JaclynPostBattle:: @ 818B7FD
    .string "I am so scatterbrained!\p"
    .string "I need to focus so I can TELEPORT\n"
    .string "properly to my house!$"

SixIsland_GreenPath_Text_LeftRouteSign:: @ 818B84D
    .string "GREEN PATH\n"
    .string "PATTERN BUSH AHEAD$"

SixIsland_GreenPath_Text_RightRouteSign:: @ 818B86B
    .string "GREEN PATH\n"
    .string "Think Green, Keep Nature Clean!$"

