FuchsiaCity_WardensHouse_Text_HifFuffHefifoo::
    .string "Warden: Hif fuff hefifoo!\p"
    .string "Ha lof ha feef ee hafahi ho.\n"
    .string "Heff hee fwee!$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo::
    .string "Ah howhee ho hoo!\n"
    .string "Eef ee hafahi ho!$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo::
    .string "Ha?\n"
    .string "He ohay heh ha hoo ee haheh!$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden::
    .string "{PLAYER} gave the Gold Teeth\n"
    .string "to the Warden.$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth::
    .string "The Warden popped in his teeth!$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething::
    .string "Warden: Thanks, son!\n"
    .string "You're a real lifesaver!\p"
    .string "No one could understand a word\n"
    .string "that I said, not a one!\p"
    .string "I was too ashamed to show my face\n"
    .string "around the Office, even.\p"
    .string "Let me give you something for your\n"
    .string "trouble.$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething::
    .string "Warden: Thank you, lassie!\n"
    .string "You're a real lifesaver!\p"
    .string "No one could understand a word\n"
    .string "that I said, not a one!\p"
    .string "I was too ashamed to show my face\n"
    .string "around the Office, even.\p"
    .string "Let me give you something for your\n"
    .string "trouble.$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden::
    .string "{PLAYER} received HM04\n"
    .string "from the Warden.$"

FuchsiaCity_WardensHouse_Text_ExplainStrength::
    .string "Warden: Inside HM04 you'll find\n"
    .string "Strength.\p"
    .string "It lets Pokémon move boulders when\n"
    .string "you're outside of battle.\p"
    .string "Oh yes, did you find the Secret\n"
    .string "House in the Safari Zone?$"

@ Unused
FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff::
    .string "なんや　にもつ\n"
    .string "いっぱいやんけ！$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay::
    .string "Pokémon photos and fossils are on\n"
    .string "display.$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay::
    .string "Old Pokémon merchandise is on\n"
    .string "display.$"

