RockTunnel_B1F_MapScripts:: @ 8162E8A
	.byte 0

RockTunnel_B1F_EventScript_162E8B:: @ 8162E8B
	trainerbattle 0, 158, 0, Text_179657, Text_1796B9
	loadword 0, gUnknown_81796CE
	callstd 6
	end

RockTunnel_B1F_EventScript_162EA2:: @ 8162EA2
	trainerbattle 0, 159, 0, Text_1798AD, Text_1798DD
	loadword 0, gUnknown_81798E9
	callstd 6
	end

RockTunnel_B1F_EventScript_162EB9:: @ 8162EB9
	trainerbattle 0, 189, 0, Text_1796E1, Text_179700
	loadword 0, gUnknown_8179712
	callstd 6
	end

RockTunnel_B1F_EventScript_162ED0:: @ 8162ED0
	trainerbattle 0, 190, 0, Text_179829, Text_179856
	loadword 0, gUnknown_817987A
	callstd 6
	end

RockTunnel_B1F_EventScript_162EE7:: @ 8162EE7
	trainerbattle 0, 191, 0, Text_179916, Text_179932
	loadword 0, gUnknown_817993E
	callstd 6
	end

RockTunnel_B1F_EventScript_162EFE:: @ 8162EFE
	trainerbattle 0, 164, 0, Text_17973A, Text_17975F
	loadword 0, gUnknown_8179777
	callstd 6
	end

RockTunnel_B1F_EventScript_162F15:: @ 8162F15
	trainerbattle 0, 165, 0, Text_1797A4, Text_1797CB
	loadword 0, gUnknown_81797DE
	callstd 6
	end

RockTunnel_B1F_EventScript_162F2C:: @ 8162F2C
	trainerbattle 0, 166, 0, Text_179968, Text_179997
	loadword 0, gUnknown_81799AC
	callstd 6
	end
