# 1 "data/maps/RockTunnel_B1F/scripts.pory"

# 2 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_MapScripts::
# 3 "data/maps/RockTunnel_B1F/scripts.pory"
	.byte 0
# 4 "data/maps/RockTunnel_B1F/scripts.pory"

# 5 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Sofia::
# 6 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_PICNICKER_SOFIA, RockTunnel_B1F_Text_SofiaIntro, RockTunnel_B1F_Text_SofiaDefeat
# 7 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_SofiaPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 9 "data/maps/RockTunnel_B1F/scripts.pory"

# 10 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Martha::
# 11 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_PICNICKER_MARTHA, RockTunnel_B1F_Text_MarthaIntro, RockTunnel_B1F_Text_MarthaDefeat
# 12 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_MarthaPostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 14 "data/maps/RockTunnel_B1F/scripts.pory"

# 15 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Dudley::
# 16 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_HIKER_DUDLEY, RockTunnel_B1F_Text_DudleyIntro, RockTunnel_B1F_Text_DudleyDefeat
# 17 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_DudleyPostBattle, MSGBOX_AUTOCLOSE
# 18 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 19 "data/maps/RockTunnel_B1F/scripts.pory"

# 20 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Allen::
# 21 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_HIKER_ALLEN, RockTunnel_B1F_Text_AllenIntro, RockTunnel_B1F_Text_AllenDefeat
# 22 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_AllenPostBattle, MSGBOX_AUTOCLOSE
# 23 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 24 "data/maps/RockTunnel_B1F/scripts.pory"

# 25 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Eric::
# 26 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_HIKER_ERIC, RockTunnel_B1F_Text_EricIntro, RockTunnel_B1F_Text_EricDefeat
# 27 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_EricPostBattle, MSGBOX_AUTOCLOSE
# 28 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 29 "data/maps/RockTunnel_B1F/scripts.pory"

# 30 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Cooper::
# 31 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_POKEMANIAC_COOPER, RockTunnel_B1F_Text_CooperIntro, RockTunnel_B1F_Text_CooperDefeat
# 32 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_CooperPostBattle, MSGBOX_AUTOCLOSE
# 33 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 34 "data/maps/RockTunnel_B1F/scripts.pory"

# 35 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Steve::
# 36 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_POKEMANIAC_STEVE, RockTunnel_B1F_Text_SteveIntro, RockTunnel_B1F_Text_SteveDefeat
# 37 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_StevePostBattle, MSGBOX_AUTOCLOSE
# 38 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 39 "data/maps/RockTunnel_B1F/scripts.pory"

# 40 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Winston::
# 41 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_POKEMANIAC_WINSTON, RockTunnel_B1F_Text_WinstonIntro, RockTunnel_B1F_Text_WinstonDefeat
# 42 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_WinstonPostBattle, MSGBOX_AUTOCLOSE
# 43 "data/maps/RockTunnel_B1F/scripts.pory"
	end
