RockTunnel_B1F_MapScripts:: @ 8162E8A
	.byte 0

RockTunnel_B1F_EventScript_162E8B:: @ 8162E8B
	trainerbattle_single TRAINER_PICNICKER_SOFIA, Text_179657, Text_1796B9
	msgbox gUnknown_81796CE, MSGBOX_AUTOCLOSE
	end

RockTunnel_B1F_EventScript_162EA2:: @ 8162EA2
	trainerbattle_single TRAINER_PICNICKER_MARTHA, Text_1798AD, Text_1798DD
	msgbox gUnknown_81798E9, MSGBOX_AUTOCLOSE
	end

RockTunnel_B1F_EventScript_162EB9:: @ 8162EB9
	trainerbattle_single TRAINER_HIKER_DUDLEY, Text_1796E1, Text_179700
	msgbox gUnknown_8179712, MSGBOX_AUTOCLOSE
	end

RockTunnel_B1F_EventScript_162ED0:: @ 8162ED0
	trainerbattle_single TRAINER_HIKER_ALLEN, Text_179829, Text_179856
	msgbox gUnknown_817987A, MSGBOX_AUTOCLOSE
	end

RockTunnel_B1F_EventScript_162EE7:: @ 8162EE7
	trainerbattle_single TRAINER_HIKER_ERIC, Text_179916, Text_179932
	msgbox gUnknown_817993E, MSGBOX_AUTOCLOSE
	end

RockTunnel_B1F_EventScript_162EFE:: @ 8162EFE
	trainerbattle_single TRAINER_POKEMANIAC_COOPER, Text_17973A, Text_17975F
	msgbox gUnknown_8179777, MSGBOX_AUTOCLOSE
	end

RockTunnel_B1F_EventScript_162F15:: @ 8162F15
	trainerbattle_single TRAINER_POKEMANIAC_STEVE, Text_1797A4, Text_1797CB
	msgbox gUnknown_81797DE, MSGBOX_AUTOCLOSE
	end

RockTunnel_B1F_EventScript_162F2C:: @ 8162F2C
	trainerbattle_single TRAINER_POKEMANIAC_WINSTON, Text_179968, Text_179997
	msgbox gUnknown_81799AC, MSGBOX_AUTOCLOSE
	end
