CeladonCity_Condominiums_1F_Text_Meowth::
    .string "Meowth: Meow!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .string "You shouldn't spend all your money\n"
    .string "on drinks.\p"
    .string "Try this instead.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
    .string "Nothing beats thirst like some hot\n"
    .string "Tea.\p"
    .string "It really is the best.$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
    .string "My dear Pokémon keep me company.\n"
    .string "Meowth even brings money home!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
    .string "Oh, hello, dearie.\n"
    .string "Did you enjoy my Tea?\p"
    .string "By the way, dear. Are you, by any\n"
    .string "chance, from Pallet Town?\p"
    .string "A girl from Pallet Town, Daisy,\n"
    .string "she enjoys Tea every day.\p"
    .string "She visits the Celadon Dept. Store\n"
    .string "to buy some Tea.$"

CeladonCity_Condominiums_1F_Text_Clefairy::
    .string "Clefairy: Pi pippippi!$"

CeladonCity_Condominiums_1F_Text_Nidoran::
    .string "Nidoran♀: Kya kyaoo!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
    .string "Celadon Mansion\n"
    .string "Manager's Suite$"

