CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons:: @ 819685B
    .string "A POKé FLUTE awakens sleeping\n"
    .string "POKéMON. You know that.\p"
    .string "It does so with a sound that only\n"
    .string "they can hear.$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia:: @ 81968C2
    .string "I rode here from FUCHSIA.\p"
    .string "It's an uphill ride on CYCLING\n"
    .string "ROAD, so I'm exhausted.$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike:: @ 8196913
    .string "If I had a BIKE, I would go to\n"
    .string "CYCLING ROAD!$"

