FuchsiaCity_Mart_EventObjects:
	object_event 1, 68, 0, 2, 0, 3, 0, 0, 10, 17, 0, 0, 0, 0, 0, FuchsiaCity_Mart_EventScript_16D4F3, 0, 0, 0
	object_event 2, 61, 0, 6, 0, 3, 0, 3, 1, 17, 0, 0, 0, 0, 0, FuchsiaCity_Mart_EventScript_16D4EA, 0, 0, 0
	object_event 3, 42, 0, 9, 0, 5, 0, 3, 2, 17, 0, 0, 0, 0, 0, FuchsiaCity_Mart_EventScript_16D4E1, 0, 0, 0

FuchsiaCity_Mart_MapWarps:
	warp_def 3, 7, 3, 2, 775
	warp_def 4, 7, 3, 2, 775
	warp_def 5, 7, 3, 2, 775

FuchsiaCity_Mart_MapEvents::
	map_events FuchsiaCity_Mart_EventObjects, FuchsiaCity_Mart_MapWarps, 0x0, 0x0
