Route16_NorthEntrance_2F_Text_OnBikeRideWithGirlfriend::
    .string "I'm on a relaxing ride on my new\n"
    .string "bike with my girlfriend.$"

Route16_NorthEntrance_2F_Text_RidingTogetherOnNewBikes::
    .string "We're going riding together on our\n"
    .string "new bikes.$"

Route16_NorthEntrance_2F_Text_ItsCeladonDeptStore::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "It's the CELADON DEPT. STORE!$"

Route16_NorthEntrance_2F_Text_LongPathOverWater::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "There's a long path over water far\n"
    .string "away.$"

Route16_NorthEntrance_2F_Text_GiveAmuletCoinIfCaught40::
    .string "I'm one of PROF. OAK's RICH AIDES.\n"
    .string "So, {PLAYER}, let me ask you...\p"
    .string "Have you gathered data on at least\n"
    .string "40 kinds of POKéMON?$"

Route16_NorthEntrance_2F_Text_GreatHereYouGo::
    .string "Congratulations, here you go!$"

Route16_NorthEntrance_2F_Text_ReceivedAmuletCoinFromAide::
    .string "{PLAYER} received ¥40,000\n"
    .string "from the RICH AIDE.$"

Route16_NorthEntrance_2F_Text_ExplainAmuletCoin::
    .string "Man, am I rich or what?!$"

