gUnknown_819FA07:: @ 819FA07
    .string "I'm on a relaxing ride on my new\n"
    .string "bike with my girlfriend.$"

gUnknown_819FA41:: @ 819FA41
    .string "We're going riding together on our\n"
    .string "new bikes.$"

gUnknown_819FA6F:: @ 819FA6F
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "It's the CELADON DEPT. STORE!$"

gUnknown_819FAB9:: @ 819FAB9
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "There's a long path over water far\n"
    .string "away.$"

gUnknown_819FB0E:: @ 819FB0E
    .string "Hi! Remember me?\n"
    .string "I'm one of PROF. OAK's AIDES.\p"
    .string "If your POKéDEX has complete data\n"
    .string "on 40 species, I'm supposed to\l"
    .string "give you a reward.\p"
    .string "PROF. OAK entrusted me with an\n"
    .string "AMULET COIN for you.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "40 kinds of POKéMON?$"

gUnknown_819FC15:: @ 819FC15
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"

gUnknown_819FC68:: @ 819FC68
    .string "{PLAYER} received the AMULET COIN\n"
    .string "from the AIDE.$"

gUnknown_819FC93:: @ 819FC93
    .string "An AMULET COIN is an item to be\n"
    .string "held by a POKéMON.\p"
    .string "If the POKéMON appears in a winning\n"
    .string "battle, you will earn more money.$"

