SafariZone_East_RestHouse_MapScripts:: @ 81623FE
	.byte 0

SafariZone_East_RestHouse_EventScript_Rocker:: @ 81623FF
	msgbox SafariZone_East_Text_CaughtChanseyAllWorthwhile, MSGBOX_NPC
	end

SafariZone_East_RestHouse_EventScript_Scientist:: @ 8162408
	msgbox SafariZone_East_Text_HowManyDidYouCatch, MSGBOX_NPC
	end

SafariZone_East_RestHouse_EventScript_BaldingMan:: @ 8162411
	msgbox SafariZone_East_Text_TiredFromAllTheFun, MSGBOX_NPC
	end
