ThreeIsland_DunsparceTunnel_Text_ProspectingForGold::
    .string "Hey, there!\n"
    .string "How's it going?\p"
    .string "What am I doing here, you ask?\n"
    .string "Why, I'm prospecting for gold!\p"
    .string "When I strike it rich, I'm buying\n"
    .string "a house in KANTO.$"

ThreeIsland_DunsparceTunnel_Text_StruckGoldThisIsForYou::
    .string "Hey, there! How's it going?\n"
    .string "Did you hear? I've struck gold!\p"
    .string "You remembered that I was\n"
    .string "prospecting, didn't you?\p"
    .string "You can't begin to imagine just\n"
    .string "how happy I am.\p"
    .string "So, I'll show you!\n"
    .string "This is for you!$"

ThreeIsland_DunsparceTunnel_Text_ThatsANugget::
    .string "That's a NUGGET!\p"
    .string "I can't give you any nuggets of\n"
    .string "wisdom, so that'll have to do!$"

ThreeIsland_DunsparceTunnel_Text_WhoopsBagCrammedFull::
    .string "Whoops, your BAG is crammed full!\n"
    .string "I'll give this to you later.$"

