MtEmber_RubyPath_B5F_EventObjects:
	object_event 1, 99, 0, 7, 0, 7, 0, 0, 8, 0, 0, 0, 0, 0, 0, MtEmber_RubyPath_B5F_EventScript_163C49, 138, 0, 0

MtEmber_RubyPath_B5F_MapWarps:
	warp_def 11, 7, 3, 0, 352

MtEmber_RubyPath_B5F_MapBGEvents:
	bg_event 7, 2, 0, 1, 0, MtEmber_RubyPath_B5F_EventScript_163BAB

MtEmber_RubyPath_B5F_MapEvents::
	map_events MtEmber_RubyPath_B5F_EventObjects, MtEmber_RubyPath_B5F_MapWarps, 0x0, MtEmber_RubyPath_B5F_MapBGEvents
