Text_199E8A:: @ 8199E8A
    .string "It's a photo of BLAINE and\n"
    .string "MR. FUJI.\p"
    .string "They're standing shoulder to\n"
    .string "shoulder with big grins.$"

gUnknown_8199EE5:: @ 8199EE5
    .string "We study POKéMON extensively\n"
    .string "every day.\p"
    .string "People often bring us rare POKéMON\n"
    .string "for examination.$"

gUnknown_8199F41:: @ 8199F41
    .string "A photo of the LAB's founder…\n"
    .string "DR. FUJI?!$"

gUnknown_8199F6A:: @ 8199F6A
    .string "POKéMON LAB\n"
    .string "Meeting Room$"

gUnknown_8199F83:: @ 8199F83
    .string "POKéMON LAB\n"
    .string "R & D Room$"

gUnknown_8199F9A:: @ 8199F9A
    .string "POKéMON LAB\n"
    .string "Testing Room$"

