CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji::
    .string "It's a photo of BLAINE and\n"
    .string "MR. FUJI.\p"
    .string "They're standing shoulder to\n"
    .string "shoulder with big grins.$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
    .string "We study POKéMON extensively\n"
    .string "every day.\p"
    .string "People often bring us rare POKéMON\n"
    .string "for examination.$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
    .string "A photo of the LAB's founder…\n"
    .string "DR. FUJI?!$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
    .string "POKéMON LAB\n"
    .string "Meeting Room$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
    .string "POKéMON LAB\n"
    .string "R & D Room$"

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
    .string "POKéMON LAB\n"
    .string "Testing Room$"

