MtMoon_1F_Text_MarcosIntro:: @ 817279D
    .string "WHOA!\n"
    .string "You shocked me!\l"
    .string "…Oh, you're just a kid!$"

MtMoon_1F_Text_MarcosDefeat:: @ 81727CB
    .string "Wow!\n"
    .string "Shocked again!$"

MtMoon_1F_Text_MarcosPostBattle:: @ 81727DF
    .string "Kids like you shouldn't be\n"
    .string "wandering around here in the dark.$"

MtMoon_1F_Text_JoshIntro:: @ 817281D
    .string "Did you come to explore the cave,\n"
    .string "too?$"

MtMoon_1F_Text_JoshDefeat:: @ 8172844
    .string "Losing stinks!\n"
    .string "It's so uncool.$"

MtMoon_1F_Text_JoshPostBattle:: @ 8172863
    .string "I came all the way down here to\n"
    .string "show off to girls.$"

MtMoon_1F_Text_MiriamIntro:: @ 8172896
    .string "Wow! It's way bigger in here than\n"
    .string "I thought!$"

MtMoon_1F_Text_MiriamDefeat:: @ 81728C3
    .string "Oh!\n"
    .string "I lost it!$"

MtMoon_1F_Text_MiriamPostBattle:: @ 81728D2
    .string "How do you get out of here?\n"
    .string "It's so big, I may get lost.$"

MtMoon_1F_Text_JovanIntro:: @ 817290B
    .string "What!\n"
    .string "Don't sneak up on me!$"

MtMoon_1F_Text_JovanDefeat:: @ 8172927
    .string "My POKéMON won't do!$"

MtMoon_1F_Text_JovanPostBattle:: @ 817293C
    .string "I have to find stronger POKéMON.\n"
    .string "Where might they be?$"

MtMoon_1F_Text_IrisIntro:: @ 8172972
    .string "What?\n"
    .string "I'm waiting for my friends to find\l"
    .string "me here.$"

MtMoon_1F_Text_IrisDefeat:: @ 81729A4
    .string "I lost?$"

MtMoon_1F_Text_IrisPostBattle:: @ 81729AC
    .string "I came because I heard there are\n"
    .string "some very rare fossils here.$"

MtMoon_1F_Text_KentIntro:: @ 81729EA
    .string "Suspicious men are in the cave.\n"
    .string "What about you?$"

MtMoon_1F_Text_KentDefeat:: @ 8172A1A
    .string "You got me!$"

MtMoon_1F_Text_KentPostBattle:: @ 8172A26
    .string "I saw them!\n"
    .string "I'm sure they're from TEAM ROCKET!$"

MtMoon_1F_Text_RobbyIntro:: @ 8172A55
    .string "You need to go through this cave\n"
    .string "to get to CERULEAN CITY.$"

MtMoon_1F_Text_RobbyDefeat:: @ 8172A8F
    .string "I lost.$"

MtMoon_1F_Text_RobbyPostBattle:: @ 8172A97
    .string "ZUBAT is tough!\n"
    .string "But if you can catch one, you'll\l"
    .string "be able to count on it.$"

MtMoon_1F_Text_ZubatIsABloodsucker:: @ 8172AE0
    .string "Beware!\n"
    .string "ZUBAT is a bloodsucker!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils:: @ 8172B00
    .string "Hi, I'm excavating for fossils here\n"
    .string "under MT. MOON.\p"
    .string "Sometimes, BROCK of PEWTER GYM\n"
    .string "lends me a hand.$"
