@PENDIENTE UN / UNA

MtMoon_1F_Text_MarcosIntro::
    .string "¡Eh!\p"
    .string "¡Me asustaste!\p"
    .string "...Ah, ¡solo eres un{A} niñ{OA}!$"

MtMoon_1F_Text_MarcosDefeat::
    .string "¡GUAU!\n"
    .string "¡OTRA VEZ ME SORPRENDISTE!$"

MtMoon_1F_Text_MarcosPostBattle::
    .string "L{OA}s niñ{OA}s como tú no deberían\n"
    .string "andar por aquí en la oscuridad.$"

MtMoon_1F_Text_JoshIntro::
    .string "¿También viniste a explorar la\n"
    .string "cueva?$"

MtMoon_1F_Text_JoshDefeat::
    .string "¡PERDER APESTA!\n"
    .string "NO TIENE NADA DE GENIAL.$"

MtMoon_1F_Text_JoshPostBattle::
    .string "Vine hasta aquí de profundo para\n"
    .string "presumir ante las chicas.$"

MtMoon_1F_Text_MiriamIntro::
    .string "¡Guau! ¡Es mucho más grande\n"
    .string "de lo que pensaba!$"

MtMoon_1F_Text_MiriamDefeat::
    .string "¡OH!\n"
    .string "¡PERDÍ!$"

MtMoon_1F_Text_MiriamPostBattle::
    .string "¿Cómo salgo de aquí?\n"
    .string "Es tan grande que puedo perderme.$"

MtMoon_1F_Text_JovanIntro::
    .string "¡¿Qué?!\n"
    .string "¡No te acerques así!$"

MtMoon_1F_Text_JovanDefeat::
    .string "¡MIS POKÉMON NO PUEDEN MÁS!$"

MtMoon_1F_Text_JovanPostBattle::
    .string "Tengo que encontrar {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} más\n"
    .string "fuertes...\p"
    .string "¿Dónde estarán?$"

MtMoon_1F_Text_IrisIntro::
    .string "¿Qué?\p"
    .string "Estoy esperando a que mis amigos\n"
    .string "me encuentren aquí.$"

MtMoon_1F_Text_IrisDefeat::
    .string "¿PERDÍ?$"

MtMoon_1F_Text_IrisPostBattle::
    .string "Vine porque oí que hay fósiles\n"
    .string "muy raros aquí.$"

MtMoon_1F_Text_KentIntro::
    .string "Hay personas sospechosas en la\n"
    .string "cueva.\p"
    .string "¿Y tú?$"

MtMoon_1F_Text_KentDefeat::
    .string "¡ME VENCISTE!$"

MtMoon_1F_Text_KentPostBattle::
    .string "¡Los vi!\p"
    .string "¡Estoy seguro de que son del\n" 
    .string "{SHADOW DYNAMIC_COLOR4}EQUIPO ROCKET{SHADOW LIGHT_GRAY}!$"

MtMoon_1F_Text_RobbyIntro::
    .string "Debes pasar por esta cueva\n"
    .string "para llegar a {SHADOW DYNAMIC_COLOR4}CIUDAD CELESTE{SHADOW LIGHT_GRAY}.$"

MtMoon_1F_Text_RobbyDefeat::
    .string "PERDÍ.$"

MtMoon_1F_Text_RobbyPostBattle::
    .string "¡{SHADOW DYNAMIC_COLOR4}ZUBAT{SHADOW LIGHT_GRAY} es resistente!\n"
    .string "Pero si logras atrapar uno, podrás\l"
    .string "contar con él.$"

MtMoon_1F_Text_ZubatIsABloodsucker::
    .string "¡Cuidado!\n"
    .string "¡ZUBAT es un chupasangre!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
    .string "Estoy excavando fósiles aquí bajo el \n"
    .string "{SHADOW DYNAMIC_COLOR4}MONTE LUNAR{SHADOW LIGHT_GRAY}.\p"
    .string "A veces, {SHADOW DYNAMIC_COLOR4}BROCK{SHADOW LIGHT_GRAY} de {SHADOW DYNAMIC_COLOR4}CIUDAD PLATEADO{SHADOW LIGHT_GRAY}\n"
    .string "me echa una mano...$"

MtMoon_1F_Text_Sign01::
    .string "{SHADOW DYNAMIC_COLOR4}MONTE LUNAR{SHADOW LIGHT_GRAY}\n"
    .string "La cuna de las estrellas$"

MtMoon_1F_Text_Silvio_EsperaUnSegundo::
    .string "¡Eh! ¡Tú! Espera un segundo...$"

MtMoon_1F_Text_Silvio_EresEntrenadora::
    .string "¿Eres {SHADOW DYNAMIC_COLOR4}ENTRENADORA POKéMON{SHADOW LIGHT_GRAY}?$"

MtMoon_1F_Text_Silvio_EresEntrenador::
    .string "¿Eres {SHADOW DYNAMIC_COLOR4}ENTRENADOR POKéMON{SHADOW LIGHT_GRAY}?$"

MtMoon_1F_Text_Silvio_QueSorpresa::
    .string "Qué sorpresa encontrar alguien as\n"
    .string "tan adentro del {SHADOW DYNAMIC_COLOR4}MONTE LUNAR{SHADOW LIGHT_GRAY}.\p"
    .string "Me llamo {SHADOW DYNAMIC_COLOR4}SILVIO{SHADOW LIGHT_GRAY}. Fui geólogo por\n"
    .string "muchos años en el {SHADOW DYNAMIC_COLOR4}MUSEO DE CIENCIA{SHADOW LIGHT_GRAY}\l"
    .string "de {SHADOW DYNAMIC_COLOR4}CIUDAD PLATEADA{SHADOW LIGHT_GRAY}.\p"
    .string "Aunque ya no trabajo allí, no puedo\n"
    .string "evitar regresar de vez en cuando...$"

MtMoon_1F_Text_EsteLugar::
    .string "Este lugar es especial. Estas vetas\n"
    .string "de roca, estas grietas...\p"
    .string "A veces ocultan fragmentos de\n"
    .string "piedras evolutivas.\p"
    .string "Si sabes observar, el monte te habla.$"

MtMoon_1F_Text_SilvioIntro::
    .string "Pero claro, no todo se aprende\n"
    .string "observando.\p"
    .string "¿Qué te parece si medimos tu instinto\n"
    .string "con una batalla?\p"
    .string "Nada muy formal, solo un combate\n"
    .string "amistoso entre colegas de caminos\l"
    .string "polvorientos.$"

MtMoon_1F_Text_SilvioDefeat::
    .string "¡ESO FUE MAGNÍFICO!\n"
    .string "BUEN OJO Y AÚN MEJOR ESTRATEGIA$"
    
MtMoon_1F_Text_CuandoVuelvas::
    .string "Cuando vuelvas a {SHADOW DYNAMIC_COLOR4}CIUDAD PLATEADA{SHADOW LIGHT_GRAY},\n"
    .string "pasa por mi tienda.\p"
    .string "Tengo algunas piedras que podrían\n"
    .string "pudarte a evolucionar tu equipo.\p"
    .string "Será un gusto hacer negocios con\n"
    .string "alguien que sabe luchar.$"