Text_17279D:: @ 817279D
    .string "WHOA!\n"
    .string "You shocked me!\l"
    .string "…Oh, you're just a kid!$"

Text_1727CB:: @ 81727CB
    .string "Wow!\n"
    .string "Shocked again!$"

gUnknown_81727DF:: @ 81727DF
    .string "Kids like you shouldn't be\n"
    .string "wandering around here in the dark.$"

Text_17281D:: @ 817281D
    .string "Did you come to explore the cave,\n"
    .string "too?$"

Text_172844:: @ 8172844
    .string "Losing stinks!\n"
    .string "It's so uncool.$"

gUnknown_8172863:: @ 8172863
    .string "I came all the way down here to\n"
    .string "show off to girls.$"

Text_172896:: @ 8172896
    .string "Wow! It's way bigger in here than\n"
    .string "I thought!$"

Text_1728C3:: @ 81728C3
    .string "Oh!\n"
    .string "I lost it!$"

gUnknown_81728D2:: @ 81728D2
    .string "How do you get out of here?\n"
    .string "It's so big, I may get lost.$"

Text_17290B:: @ 817290B
    .string "What!\n"
    .string "Don't sneak up on me!$"

Text_172927:: @ 8172927
    .string "My POKéMON won't do!$"

gUnknown_817293C:: @ 817293C
    .string "I have to find stronger POKéMON.\n"
    .string "Where might they be?$"

Text_172972:: @ 8172972
    .string "What?\n"
    .string "I'm waiting for my friends to find\l"
    .string "me here.$"

Text_1729A4:: @ 81729A4
    .string "I lost?$"

gUnknown_81729AC:: @ 81729AC
    .string "I came because I heard there are\n"
    .string "some very rare fossils here.$"

Text_1729EA:: @ 81729EA
    .string "Suspicious men are in the cave.\n"
    .string "What about you?$"

Text_172A1A:: @ 8172A1A
    .string "You got me!$"

gUnknown_8172A26:: @ 8172A26
    .string "I saw them!\n"
    .string "I'm sure they're from TEAM ROCKET!$"

Text_172A55:: @ 8172A55
    .string "You need to go through this cave\n"
    .string "to get to CERULEAN CITY.$"

Text_172A8F:: @ 8172A8F
    .string "I lost.$"

gUnknown_8172A97:: @ 8172A97
    .string "ZUBAT is tough!\n"
    .string "But if you can catch one, you'll\l"
    .string "be able to count on it.$"

gUnknown_8172AE0:: @ 8172AE0
    .string "Beware!\n"
    .string "ZUBAT is a bloodsucker!$"

