Text_1776C0:: @ 81776C0
    .string "Uh-oh…\n"
    .string "Where am I now?$"

Text_1776D7:: @ 81776D7
    .string "Awooh!$"

gUnknown_81776DE:: @ 81776DE
    .string "You can find stuff lying around.\n"
    .string "The residents must've left them.$"

Text_177720:: @ 8177720
    .string "This place is ideal for a lab.\n"
    .string "Look at all this space.$"

Text_177757:: @ 8177757
    .string "What was that for?$"

gUnknown_817776A:: @ 817776A
    .string "I like it here.\n"
    .string "It's conducive to my studies.$"

gUnknown_8177798:: @ 8177798
    .string "Diary: Sept. 1\n"
    .string "MEWTWO is far too powerful.\p"
    .string "We have failed to curb its vicious\n"
    .string "tendencies…$"

