Text_18C1ED:: @ 818C1ED
    .string "I sensed your approach.$"

Text_18C205:: @ 818C205
    .string "Give up…$"

Text_18C20E:: @ 818C20E
    .string "In your future, I sense that you\n"
    .string "will meet many others.\p"
    .string "I think you will be linked to each\n"
    .string "other by a strange power.$"

Text_18C283:: @ 818C283
    .string "Somewhere on this island, peculiar\n"
    .string "POKéMON are sleeping.$"

Text_18C2BC:: @ 818C2BC
    .string "What an amazing TRAINER!$"

Text_18C2D5:: @ 818C2D5
    .string "Somewhere on this island, peculiar\n"
    .string "POKéMON are sleeping.\p"
    .string "Could it be that they're waiting\n"
    .string "for you?$"

gUnknown_818C338:: @ 818C338
    .string "TRAINER TOWER ENTRANCE\n"
    .string "Rise to the Challenge, TRAINERS!$"

gUnknown_818C370:: @ 818C370
    .string "TRAINER TOWER AHEAD$"

