SevenIsland_TrainerTower_Text_DarioIntro:: @ 818C1ED
    .string "I sensed your approach.$"

SevenIsland_TrainerTower_Text_DarioDefeat:: @ 818C205
    .string "Give up…$"

SevenIsland_TrainerTower_Text_DarioPostBattle:: @ 818C20E
    .string "In your future, I sense that you\n"
    .string "will meet many others.\p"
    .string "I think you will be linked to each\n"
    .string "other by a strange power.$"

SevenIsland_TrainerTower_Text_RodetteIntro:: @ 818C283
    .string "Somewhere on this island, peculiar\n"
    .string "POKéMON are sleeping.$"

SevenIsland_TrainerTower_Text_RodetteDefeat:: @ 818C2BC
    .string "What an amazing TRAINER!$"

SevenIsland_TrainerTower_Text_RodettePostBattle:: @ 818C2D5
    .string "Somewhere on this island, peculiar\n"
    .string "POKéMON are sleeping.\p"
    .string "Could it be that they're waiting\n"
    .string "for you?$"

SevenIsland_TrainerTower_Text_TrainerTowerSign:: @ 818C338
    .string "TRAINER TOWER ENTRANCE\n"
    .string "Rise to the Challenge, TRAINERS!$"

SevenIsland_TrainerTower_Text_TrainerTowerAhead:: @ 818C370
    .string "TRAINER TOWER AHEAD$"

@ Unused text perhaps indicating Trainer Tower was planned to be unlocked by something
SevenIsland_TrainerTower_Text_LooksLikeTrainerTowerIsClosed:: @ 818C384
    .string "トレーナータワーには\n"
    .string "いまは　はいれない　みたい‥$"

SevenIsland_TrainerTower_Text_TrainerTowerIsOpenLetsGoIn:: @ 818C39E
    .string "トレーナータワーが　あいてる！\n"
    .string "さっそく　はいってみよう！$"

