VermilionCity_PokemonFanClub_Text_AdmirePikachusTail::
    .string "Won't you admire my Pikachu's\n"
    .string "adorable tail?$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute::
    .string "Humph!\p"
    .string "My Pikachu is twice as cute as\n"
    .string "that one!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel::
    .string "I just adore my Seel!\n"
    .string "It's so lovable!\p"
    .string "It squeals, “Kyuuuh,” when I\n"
    .string "hug it!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive::
    .string "Oh, dear!\p"
    .string "My Seel is far more attractive.\n"
    .string "By double, I would say.$"

VermilionCity_PokemonFanClub_Text_Pikachu::
    .string "Pikachu: Chu! Pikachu!$"

VermilionCity_PokemonFanClub_Text_Seel::
    .string "Seel: Kyuoo!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons::
    .string "I chair the Pokémon Fan Club!\p"
    .string "I raise more than a hundred\n"
    .string "Pokémon!\p"
    .string "I'm very fussy when it comes to\n"
    .string "Pokémon! I surely am!\p"
    .string "So…\p"
    .string "Did you come visit to hear about\n"
    .string "my Pokémon?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory::
    .string "Good!\n"
    .string "Then listen up!\p"
    .string "My favorite Rapidash…\p"
    .string "It's…cute…lovely…smart… \n"
    .string "plus…amazing…you think so?…\l"
    .string "oh yes…it's…stunning…\l"
    .string "kindly…love it!\p"
    .string "Hug it…when…sleeping…warm\n"
    .string "and cuddly…spectacular…\l"
    .string "ravishing…\l"
    .string "…Oops! Look at the time!\l"
    .string "I kept you too long!\p"
    .string "Thanks for hearing me out!\n"
    .string "I want you to have this!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman::
    .string "{PLAYER} received a Bike Voucher\n"
    .string "from the Chairman.$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher::
    .string "Take that Bike Voucher to the\n"
    .string "Bike Shop in Cerulean City.\p"
    .string "Exchange that for a Bicycle\n"
    .string "free of charge!\p"
    .string "Don't worry, my favorite Fearow\n"
    .string "will Fly me anywhere I need to go.\p"
    .string "So, I have no need for a Bicycle.\p"
    .string "I hope you like cycling!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory::
    .string "Oh. Come back when you want to\n"
    .string "hear my story!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain::
    .string "Hello, {PLAYER}!\p"
    .string "Did you come see me about my\n"
    .string "Pokémon again?\p"
    .string "No?\n"
    .string "Too bad!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis::
    .string "Make room for this!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon::
    .string "Our Chairman is very vocal about\n"
    .string "Pokémon.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers::
    .string "Let's all listen politely to other\n"
    .string "Trainers!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack::
    .string "If someone brags, brag right back!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons::
    .string "Our Chairman really does adore his\n"
    .string "Pokémon.\p"
    .string "But the person who is most liked by\n"
    .string "Pokémon is Daisy, I think.$"
