FuchsiaCity_House1_EventObjects:
	object_event 1, 32, 0, 7, 0, 4, 0, 3, 9, 17, 0, 0, 0, 0, 0, FuchsiaCity_House1_EventScript_16D6CF, 0, 0, 0
	object_event 2, 28, 0, 1, 0, 2, 0, 3, 7, 17, 0, 0, 0, 0, 0, FuchsiaCity_House1_EventScript_16D6C6, 0, 0, 0
	object_event 3, 16, 0, 2, 0, 5, 0, 3, 2, 17, 0, 0, 0, 0, 0, FuchsiaCity_House1_EventScript_16D6E8, 0, 0, 0

FuchsiaCity_House1_MapWarps:
	warp_def 3, 7, 3, 5, 775
	warp_def 4, 7, 3, 5, 775
	warp_def 5, 7, 3, 5, 775

FuchsiaCity_House1_MapEvents::
	map_events FuchsiaCity_House1_EventObjects, FuchsiaCity_House1_MapWarps, 0x0, 0x0
