gUnknown_8198BBB:: @ 8198BBB
    .string "The SAFARI ZONE's WARDEN is old, \n"
    .string "but he's still very much active.\p"
    .string "All his teeth are false, though.$"

gUnknown_8198C1F:: @ 8198C1F
    .string "Hmm?\n"
    .string "You've met BILL?\p"
    .string "He's my grandson!\p"
    .string "He always liked collecting things,\n"
    .string "even as a child!$"

gUnknown_8198C7B:: @ 8198C7B
    .string "BILL files his own POKéMON data on\n"
    .string "his PC.\p"
    .string "Did he show you?$"

