CinnabarIsland_PokemonLab_Lounge_EventObjects:
	object_event 1, 55, 0, 5, 0, 3, 0, 3, 2, 17, 0, 0, 0, 0, 0, CinnabarIsland_PokemonLab_Lounge_EventScript_16E2B9, 0, 0, 0
	object_event 2, 33, 0, 4, 0, 6, 0, 3, 8, 17, 0, 0, 0, 0, 0, CinnabarIsland_PokemonLab_Lounge_EventScript_16E2C2, 0, 0, 0
	object_event 3, 28, 0, 10, 0, 5, 0, 3, 8, 17, 0, 0, 0, 0, 0, CinnabarIsland_PokemonLab_Lounge_EventScript_16E33E, 0, 0, 0

CinnabarIsland_PokemonLab_Lounge_MapWarps:
	warp_def 7, 9, 3, 3, 3073

CinnabarIsland_PokemonLab_Lounge_MapEvents::
	map_events CinnabarIsland_PokemonLab_Lounge_EventObjects, CinnabarIsland_PokemonLab_Lounge_MapWarps, 0x0, 0x0
