SaffronCity_CopycatsHouse_1F_Text_DaughterIsSelfCentered:: @ 819AB9B
    .string "My daughter is so self-centered.\n"
    .string "She has but a few friends.$"

SaffronCity_CopycatsHouse_1F_Text_DaughterLikesToMimicPeople:: @ 819ABD7
    .string "My daughter likes to mimic people.\n"
    .string "It's rather vexing.\p"
    .string "Her mimicry has earned her the\n"
    .string "nickname COPYCAT around here.$"

SaffronCity_CopycatsHouse_1F_Text_Chansey:: @ 819AC4B
    .string "CHANSEY: Chaan! Sii!$"

