PokemonTower_7F_Text_Grunt1Intro::
    .string "What do you want?\n"
    .string "Why are you here?$"

PokemonTower_7F_Text_Grunt1Defeat::
    .string "I give up!$"

PokemonTower_7F_Text_Grunt1PostBattle::
    .string "I'm not going to forget this!$"

PokemonTower_7F_Text_Grunt2Intro::
    .string "This old guy marched right up to\n"
    .string "our HIDEOUT.\p"
    .string "Then, he starts ranting about how\n"
    .string "TEAM ROCKET's abusing POKéMON.\p"
    .string "So, we're just talking it over as\n"
    .string "adults.$"

PokemonTower_7F_Text_Grunt2Defeat::
    .string "Please!\n"
    .string "No more!$"

PokemonTower_7F_Text_Grunt2PostBattle::
    .string "POKéMON are only good for making\n"
    .string "money. Why not use them?\p"
    .string "You stay out of our business!$"

PokemonTower_7F_Text_Grunt3Intro::
    .string "You're not saving anyone, kid!$"

PokemonTower_7F_Text_Grunt3Defeat::
    .string "Don't fight us ROCKETS!$"

PokemonTower_7F_Text_Grunt3PostBattle::
    .string "You're not getting away with this!$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe::
    .string "MR. FUJI: Heh?\n"
    .string "You came to save me?\p"
    .string "Thank you. But, I came here of my\n"
    .string "own free will.\p"
    .string "I came to calm the spirit of\n"
    .string "CUBONE's mother.\p"
    .string "I think MAROWAK's spirit has\n"
    .string "finally left us.\p"
    .string "I must thank you for your kind\n"
    .string "concern.\p"
    .string "Follow me to my home, POKéMON\n"
    .string "HOUSE, at the foot of this tower.$"

