# 1 "data/maps/UndergroundPath_SouthEntrance/scripts.pory"

# 2 "data/maps/UndergroundPath_SouthEntrance/scripts.pory"
UndergroundPath_SouthEntrance_MapScripts::
# 3 "data/maps/UndergroundPath_SouthEntrance/scripts.pory"
	.byte 0
# 4 "data/maps/UndergroundPath_SouthEntrance/scripts.pory"

# 5 "data/maps/UndergroundPath_SouthEntrance/scripts.pory"
UndergroundPath_SouthEntrance_EventScript_Woman::
# 6 "data/maps/UndergroundPath_SouthEntrance/scripts.pory"
	msgbox UndergroundPath_SouthEntrance_Text_PeopleLoseThingsInTheDarkness, MSGBOX_NPC
# 7 "data/maps/UndergroundPath_SouthEntrance/scripts.pory"
	end
