SevenIsland_TrainerTower_4F_MapScripts:: @ 8164742
    map_script 5, SevenIsland_TrainerTower_4F_MapScript1_1C4F54
    map_script 3, SevenIsland_TrainerTower_4F_MapScript2_1C4F62
    map_script 2, SevenIsland_TrainerTower_4F_MapScript3_1C5046
    .byte 0

SevenIsland_TrainerTower_4F_EventScript_164752:: @ 8164752
    call EventScript_1C52F4
    end

EventScript_164758:: @ 8164758
    call EventScript_1C533B
    end

EventScript_16475E:: @ 816475E
    call EventScript_1C5382
    end

EventScript_164764:: @ 8164764
    call EventScript_1C538C
    end

EventScript_16476A:: @ 816476A
    call EventScript_1C53AA
    end
