SSAnne_B1F_Room5_EventObjects:
	object_event 1, 19, 0, 3, 0, 5, 0, 3, 8, 17, 0, 0, 0, 0, 0, SSAnne_B1F_Room5_EventScript_160DD6, 0, 0, 0
	object_event 2, 134, 0, 2, 0, 5, 0, 3, 8, 17, 0, 0, 0, 0, 0, SSAnne_B1F_Room5_EventScript_160DDF, 0, 0, 0
	object_event 3, 92, 0, 2, 0, 2, 0, 0, 8, 17, 0, 0, 0, 0, 0, SSAnne_B1F_Room5_EventScript_1BE69F, 361, 0, 0

SSAnne_B1F_Room5_MapWarps:
	warp_def 4, 7, 3, 5, 264

SSAnne_B1F_Room5_MapEvents::
	map_events SSAnne_B1F_Room5_EventObjects, SSAnne_B1F_Room5_MapWarps, 0x0, 0x0
