PewterCity_Museum_1F_Text_Its50YForChildsTicket:: @ 81904B5
    .string "Yes, yes.\n"
    .string "It's ¥50 for a child's ticket.\p"
    .string "Would you like to come in?$"

PewterCity_Museum_1F_Text_ComeAgain:: @ 81904F9
    .string "Come again!$"

PewterCity_Museum_1F_Text_Right50YThankYou:: @ 8190505
    .string "Right, ¥50!\n"
    .string "Thank you!$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney:: @ 819051C
    .string "You don't have enough money.$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself:: @ 8190539
    .string "Please enjoy yourself.$"

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs:: @ 8190550
    .string "You can't sneak in the back way!\n"
    .string "Nice try, kid, but no.\p"
    .string "Oh, whatever!\n"
    .string "Do you know what AMBER is?$"

PewterCity_Museum_1F_Text_AmberContainsGeneticMatter:: @ 81905B1
    .string "AMBER contains the genetic matter\n"
    .string "of ancient POKéMON.\p"
    .string "There's a LAB somewhere trying to\n"
    .string "resurrect POKéMON from AMBER.$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap:: @ 8190627
    .string "AMBER is actually sap, that gooey\n"
    .string "stuff that oozes from trees.\p"
    .string "The ancient sap fossilized over\n"
    .string "time to become rock-hard AMBER.$"

@ Unused
PewterCity_Museum_1F_Text_PleaseGoAround:: @ 81906A6
    .string "あちらへ　おまわりください$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife:: @ 81906B4
    .string "I should be grateful for my long\n"
    .string "life.\p"
    .string "Never did I think I would get to\n"
    .string "see the bones of a dragon!$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined:: @ 8190717
    .string "Ssh! Listen, I need to share a\n"
    .string "secret with someone.\p"
    .string "I think that this chunk of AMBER\n"
    .string "contains POKéMON DNA!\p"
    .string "It would be a shattering scientific\n"
    .string "breakthrough if POKéMON could be\l"
    .string "resurrected from it.\p"
    .string "But, my colleagues just ignore\n"
    .string "what I have to say.\p"
    .string "So, I have a favor to ask!\p"
    .string "I want you to get this examined at\n"
    .string "a POKéMON LAB somewhere.$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan:: @ 8190866
    .string "{PLAYER} received the OLD AMBER\n"
    .string "from the man.$"

PewterCity_Museum_1F_Text_GetOldAmberChecked:: @ 819088E
    .string "Ssh!\n"
    .string "Get the OLD AMBER checked!$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis:: @ 81908AE
    .string "You don't have space for this.$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit:: @ 81908CD
    .string "We have two fossils of rare,\n"
    .string "prehistoric POKéMON on exhibit.$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber:: @ 819090A
    .string "There is a beautiful piece of\n"
    .string "AMBER in a clear gold color.$"

PewterCity_Museum_1F_Text_AerodactylFossil:: @ 8190945
    .string "AERODACTYL Fossil\n"
    .string "A primitive and rare POKéMON.$"

PewterCity_Museum_1F_Text_KabutopsFossil:: @ 8190975
    .string "KABUTOPS Fossil\n"
    .string "A primitive and rare POKéMON.$"

