PewterCity_Museum_1F_Text_FossilsTeachAboutPast::
    .string " ...Y así es como los fósiles nos\n"
    .string "permiten aprender sobre el pasado\l"
    .string "de los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}...$"

PewterCity_Museum_1F_Text_SpecialVisitorFemale::
    .string "¡Oh, parece que tenemos una visitante\n"
    .string "especial!\p"
    .string "¿Eres tú quien desea desafiarme en el\n"
    .string "{SHADOW DYNAMIC_COLOR4}GIMNASIO{SHADOW LIGHT_GRAY}?$"

PewterCity_Museum_1F_Text_SpecialVisitorMale::
    .string "¡Oh, parece que tenemos un visitante\n"
    .string "especial!\p"
    .string "¿Eres tú quien desea desafiarme en el\n"
    .string "{SHADOW DYNAMIC_COLOR4}GIMNASIO{SHADOW LIGHT_GRAY}?$"

PewterCity_Museum_1F_Text_AlwaysExcited::
    .string "Siempre emocionado de enfrentarme a\n"
    .string "nuevos retadores...\p"
    .string "Permíteme terminar aquí y nos\n"
    .string "encontraremos en el {SHADOW DYNAMIC_COLOR4}GIMNASIO{SHADOW LIGHT_GRAY} para\l"
    .string "nuestro combate.\p"
    .string "Mientras tanto, ¿por qué no echas un\n"
    .string "vistazo a las exhibiciones?$"

PewterCity_Museum_1F_Text_BrockWaitAMoment::
    .string "Un momento, por favor...$"

PewterCity_Museum_1F_Text_BrockBusy::
    .string "Estoy dando una explicación\n"
    .string "sobre estos fósiles.\p"
    .string "Échales un vistazo tú también.\n"
    .string "Luego hablamos, ¿de acuerdo?$"

PewterCity_Museum_1F_Text_DontLeaveWithoutLooking::
    .string "¡No te vayas sin echarle un vistazo a\n"
    .string "las exhibiciones!$"

PewterCity_Museum_1F_Text_FossilsTeachUs::
    .string "...los fósiles nos enseñan sobre el\n"
    .string "pasado y nos inspiran para nuestros\l"
    .string "viajes...\p"
    .string "¡Gracias por venir!$"

@pendiente A mayuscula
PewterCity_Museum_1F_Text_HelloTrainer::
    .string "¡Hola {SHADOW DYNAMIC_COLOR4}ENTRENADOR{A}{SHADOW LIGHT_GRAY}!\n"
    .string "Gracias por venir hasta aquí.\p"
    .string "Espero que hayas aprendido algo\n"
    .string "sobre los fósiles.$"

PewterCity_Museum_1F_Text_IHeardThat::
    .string "He oído que has venido a desafiarme\n"
    .string "en el {SHADOW DYNAMIC_COLOR4}GIMNASIO{SHADOW LIGHT_GRAY}.\p"
    .string "¡Vamos de inmediato para nuestra\n"
    .string "batalla!$"

PewterCity_Museum_1F_Text_Kabuto::
    .string "{SHADOW DYNAMIC_COLOR4}FÓSIL DE KABUTO{SHADOW LIGHT_GRAY}\n"
    .string "Antiguo caparazón petrificado de\l"
    .string "un {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} prehistórico extinto,\l"
    .string "similar a un cangrejo.$"

PewterCity_Museum_1F_Text_Omanyte::
    .string "{SHADOW DYNAMIC_COLOR4}FÓSIL DE OMANYTE{SHADOW LIGHT_GRAY}\n"
    .string "Restos petrificados de un {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}\l"
    .string "marino extinto con una concha en\l"
    .string "forma de espiral.$"

PewterCity_Museum_1F_Text_Its100YForChildsTicket::
    .string "Bienvenid{oa} al {SHADOW DYNAMIC_COLOR4}MUSEO DE CIENCIA{SHADOW LIGHT_GRAY}.\n"
    .string "L{oa}s niñ{oa}s pagan ¥100...\p"
    .string "¿Te gustaría entrar?$"

PewterCity_Museum_1F_Text_ComeAgain::
    .string "¡Hasta pronto!$"

PewterCity_Museum_1F_Text_Right50YThankYou::
    .string "¡¥100! ¡Vale!\n"
    .string "¡Gracias!$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney::
    .string "No tienes suficiente dinero.$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself::
    .string "¡Disfruta del {SHADOW DYNAMIC_COLOR4}MUSEO DE CIENCIA{SHADOW LIGHT_GRAY}!$"

PewterCity_Museum_1F_Text_Silvio::
    .string "Esta {SHADOW DYNAMIC_COLOR4}PIEDRA LUNAR{SHADOW LIGHT_GRAY} es increíble...\p"
    .string "Siempre he soñado con encontrar\n"
    .string "una en el {SHADOW DYNAMIC_COLOR4}MONTE MOON{SHADOW LIGHT_GRAY}.$"

PewterCity_Museum_1F_Text_AerodactylFossil::
    .string "{SHADOW DYNAMIC_COLOR4}FÓSIL DE AERODACTYL{SHADOW LIGHT_GRAY}\n"
    .string "Restos petrificados de un {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}\l"
    .string "volador extinto, con aspecto de\l"
    .string "dragón prehistórico.$"

PewterCity_Museum_1F_Text_Scientist::
    .string "Este espécimen es uno de los más\n"
    .string "raros que hemos encontrado.\p"
    .string "Imagina cómo debió ser en su hábitat\n"
    .string "original...$"

PewterCity_Museum_1F_Text_Spectator1::
    .string "¡Qué maravillosa exhibición!\p"
    .string "{SHADOW DYNAMIC_COLOR4}BROCK{SHADOW LIGHT_GRAY} realmente tiene una pasión por\n"
    .string "los fósiles.$"

PewterCity_Museum_1F_Text_Spectator2::
    .string "¡Vaya, qué interesante!\p"
    .string "Nunca había visto tantos fósiles de\n"
    .string "cerca.\p"
    .string "{SHADOW DYNAMIC_COLOR4}BROCK{SHADOW LIGHT_GRAY} sabe mucho sobre estos\n"
    .string "{SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} antiguos.$"

PewterCity_Museum_1F_Text_Spectator3::
    .string "Es fascinante, ¿verdad?\p"
    .string "{SHADOW DYNAMIC_COLOR4}BROCK{SHADOW LIGHT_GRAY} conoce mucho sobre estos\n"
    .string "fósiles.$"

PewterCity_Museum_1F_Text_Spectator4::
    .string "¡Esos fósiles  son enormes!\p"
    .string "¿Cómo era el mundo de los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}\n"
    .string "antes?$"

PewterCity_Museum_1F_Text_Spectator5::
    .string "{SHADOW DYNAMIC_COLOR4}BROCK{SHADOW LIGHT_GRAY} demuestra un profundo\n"
    .string "conocimiento de los fósiles.$"

@No incluido en la beta
PewterCity_Museum_1F_Text_AmberContainsGeneticMatter::
    .string "AMBER contains the genetic matter\n"
    .string "of ancient POKéMON.\p"
    .string "There's a LAB somewhere trying to\n"
    .string "resurrect POKéMON from AMBER.$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap::
    .string "AMBER is actually sap, that gooey\n"
    .string "stuff that oozes from trees.\p"
    .string "The ancient sap fossilized over\n"
    .string "time to become rock-hard AMBER.$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife::
    .string "I should be grateful for my long\n"
    .string "life.\p"
    .string "Never did I think I would get to\n"
    .string "see the bones of a dragon!$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined::
    .string "Ssh! Listen, I need to share a\n"
    .string "secret with someone.\p"
    .string "I think that this chunk of AMBER\n"
    .string "contains POKéMON DNA!\p"
    .string "It would be a shattering scientific\n"
    .string "breakthrough if POKéMON could be\l"
    .string "resurrected from it.\p"
    .string "But, my colleagues just ignore\n"
    .string "what I have to say.\p"
    .string "So, I have a favor to ask!\p"
    .string "I want you to get this examined at\n"
    .string "a POKéMON LAB somewhere.$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan::
    .string "{PLAYER} received the OLD AMBER\n"
    .string "from the man.$"

PewterCity_Museum_1F_Text_GetOldAmberChecked::
    .string "Ssh!\n"
    .string "Get the OLD AMBER checked!$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis::
    .string "You don't have space for this.$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit::
    .string "We have two fossils of rare,\n"
    .string "prehistoric POKéMON on exhibit.$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber::
    .string "There is a beautiful piece of\n"
    .string "AMBER in a clear gold color.$"