LavenderTown_PokemonCenter_2F_MapScripts:: @ 816B122
	map_script MAP_SCRIPT_ON_FRAME_TABLE, LavenderTown_PokemonCenter_2F_MapScript1_1BB2A3
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, LavenderTown_PokemonCenter_2F_MapScript2_1BB1ED
	map_script MAP_SCRIPT_ON_LOAD, LavenderTown_PokemonCenter_2F_MapScript3_1BB237
	map_script MAP_SCRIPT_ON_TRANSITION, LavenderTown_PokemonCenter_2F_MapScript4_1BB1B4
	.byte 0

LavenderTown_PokemonCenter_2F_EventScript_16B137:: @ 816B137
	call EventScript_1BB4A3
	end

EventScript_16B13D:: @ 816B13D
	call EventScript_1BB6AB
	end

EventScript_16B143:: @ 816B143
	call EventScript_1BB7DE
	end
