gUnknown_81A4D72:: @ 81A4D72
    .string "Dance, dance!\n"
    .string "CHANSEY Dance!\p"
    .string "You join in, too!\n"
    .string "Dance, dance!$"

gUnknown_81A4DAF:: @ 81A4DAF
    .string "Would you like to dance?$"

gUnknown_81A4DC8:: @ 81A4DC8
    .string "Come on, dance!$"

gUnknown_81A4DD8:: @ 81A4DD8
    .string "{PLAYER} danced the CHANSEY Dance!$"

gUnknown_81A4DF5:: @ 81A4DF5
    .string "Ahahahaha!\p"
    .string "There, you're all chipper now!\n"
    .string "Lucky!$"

gUnknown_81A4E26:: @ 81A4E26
    .string "CHANSEY: Chansi! Chansi!$"
