VermilionCity_House3_Text_PidgeyFlyLetterToSaffron:: @ 81953AF
    .string "I'm getting my PIDGEY to fly a\n"
    .string "letter to SAFFRON in the north.$"

VermilionCity_House3_Text_Pidgey:: @ 81953EE
    .string "PIDGEY: Kurukkoo!$"

VermilionCity_House3_Text_DearPippiLetter:: @ 8195400
    .string "Dear PIPPI,\n"
    .string "I hope to see you soon.\p"
    .string "I heard SAFFRON has problems with\n"
    .string "TEAM ROCKET.\p"
    .string "VERMILION appears to be safe.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom:: @ 8195471
    .string "I want to exchange MAIL with all\n"
    .string "sorts of people.\p"
    .string "I send my PIDGEY to a UNION ROOM\n"
    .string "to exchange MAIL for me.$"

