Route18_Text_WiltonIntro:: @ 8187640
    .string "I always check every grassy area\n"
    .string "for new POKéMON.$"

Route18_Text_WiltonDefeat:: @ 8187672
    .string "Tch!$"

Route18_Text_WiltonPostBattle:: @ 8187677
    .string "I wish I had a BIKE!$"

Route18_Text_RamiroIntro:: @ 818768C
    .string "Kurukkoo!\n"
    .string "How do you like my birdcall?$"

Route18_Text_RamiroDefeat:: @ 81876B3
    .string "I had to bug you!$"

Route18_Text_RamiroPostBattle:: @ 81876C5
    .string "I collect sea POKéMON on weekends\n"
    .string "because the sea is so close.$"

Route18_Text_JacobIntro:: @ 8187704
    .string "This is my turf!\n"
    .string "Get out of here!$"

Route18_Text_JacobDefeat:: @ 8187726
    .string "Darn!$"

Route18_Text_JacobPostBattle:: @ 818772C
    .string "This is my fave area for catching\n"
    .string "POKéMON.$"

Route18_Text_RouteSign:: @ 8187757
    .string "ROUTE 18\n"
    .string "CELADON CITY - FUCHSIA CITY$"

Route18_Text_CyclingRoadSign:: @ 818777C
    .string "CYCLING ROAD\n"
    .string "No pedestrians permitted!$"

