Route18_Text_WiltonIntro::
    .string "I always check every grassy area\n"
    .string "for new Pokémon.$"

Route18_Text_WiltonDefeat::
    .string "Tch!$"

Route18_Text_WiltonPostBattle::
    .string "I wish I had a Bike!$"

Route18_Text_RamiroIntro::
    .string "Kurukkoo!\n"
    .string "How do you like my birdcall?$"

Route18_Text_RamiroDefeat::
    .string "I had to bug you!$"

Route18_Text_RamiroPostBattle::
    .string "I collect sea Pokémon on weekends\n"
    .string "because the sea is so close.$"

Route18_Text_JacobIntro::
    .string "This is my turf!\n"
    .string "Get out of here!$"

Route18_Text_JacobDefeat::
    .string "Darn!$"

Route18_Text_JacobPostBattle::
    .string "This is my fave area for catching\n"
    .string "Pokémon.$"

Route18_Text_RouteSign::
    .string "Route 18\n"
    .string "Celadon City - Fuchsia City$"

Route18_Text_CyclingRoadSign::
    .string "Cycling Road\n"
    .string "No pedestrians permitted!$"

