import subprocess

good_moves = set([
  # Status moves.
  'acidarmor',
  'agility',
  'aromatherapy',
  'auroraveil',
  'autotomize',
  'banefulbunker',
  'batonpass',
  'bellydrum',
  'bulkup',
  'burningbulwark',
  'calmmind',
  'chillyreception',
  'clangoroussoul',
  'coil',
  'cottonguard',
  'courtchange',
  'curse',
  'defog',
  'destinybond',
  'detect',
  # 'disable',
  'dragondance',
  'dragonrush',  # Added manually.
  # 'encore',
  'extremeevoboost',
  'filletaway',
  'geomancy',
  'glare',
  # 'haze',
  'healbell',
  'healingwish',
  'healorder',
  'heartswap',
  'honeclaws',
  'kingsshield',
  'leechseed',
  'lightscreen',
  'lovelykiss',
  'lunardance',
  'magiccoat',
  'maxguard',
  'memento',
  'milkdrink',
  'moonlight',
  'morningsun',
  'nastyplot',
  'naturesmadness',
  'noretreat',
  'ominouswind',  # Added manually.
  'obstruct',
  'painsplit',
  'partingshot',
  'perishsong',
  'protect',
  'quiverdance',
  'recover',
  'reflect',
  'reflecttype',
  'rest',
  'revivalblessing',
  'roar',
  'rockpolish',
  'roost',
  'shedtail',
  'shellsmash',
  'shiftgear',
  'shoreup',
  'silktrap',
  'slackoff',
  'sleeppowder',
  'sleeptalk',
  'softboiled',
  'spikes',
  'spikyshield',
  'spore',
  'stealthrock',
  'stickyweb',
  'strengthsap',
  'substitute',
  'switcheroo',
  'swordsdance',
  'synthesis',
  'tailglow',
  'tailwind',
  'taunt',
  'thunderwave',
  'tidyup',
  'toxic',
  'transform',
  'trick',
  'victorydance',
  'whirlwind',
  'willowisp',
  'wish',
  'yawn',
  # "Weak" moves.
  'accelerock',
  'acrobatics',
  'aquacutter',
  'avalanche',
  'barbbarrage',
  'bonemerang',
  'bouncybubble',
  'bulletpunch',
  'buzzybuzz',
  'ceaselessedge',
  'circlethrow',
  'clearsmog',
  'doubleironbash',
  'dragondarts',
  'dragontail',
  'drainingkiss',
  'endeavor',
  'facade',
  'firefang',
  'flipturn',
  'flowertrick',
  'freezedry',
  'frustration',
  'geargrind',
  'gigadrain',
  'grassknot',
  'gyroball',
  'icefang',
  'iceshard',
  'iciclespear',
  'infernalparade',
  'knockoff',
  'lastrespects',
  'lowkick',
  'machpunch',
  'mortalspin',
  'mysticalpower',
  'naturesmadness',
  'nightshade',
  'nuzzle',
  'pikapapow',
  'populationbomb',
  'psychocut',
  'psyshieldbash',
  'pursuit',
  'quickattack',
  'ragefist',
  'rapidspin',
  'return',
  'rockblast',
  'ruination',
  'saltcure',
  'scorchingsands',
  'seismictoss',
  'shadowclaw',
  'shadowsneak',
  'sizzlyslide',
  'stoneaxe',
  'storedpower',
  'stormthrow',
  'suckerpunch',
  'superfang',
  'surgingstrikes',
  'tachyoncutter',
  'tailslap',
  'thunderclap',
  'tripleaxel',
  'tripledive',
  'twinbeam',
  'uturn',
  'veeveevolley',
  'voltswitch',
  'watershuriken',
  # 'weatherball',

  # Conditionally good moves.
  'megakick',  # Added manually
  'fakeout',
  'flamecharge',
  'nuzzle',
  'poweruppunch',
  'trailblaze',
  'solarbeam',
  'solarblade',
  'dynamicpunch',
  'grasswhistle',
  'inferno',
  'sing',
  'heatcrash',
  'heavyslam',
  'aerialace',
  'ancientpower',
  'aquajet',
  'aurawheel',
  'axekick',
  'bellydrum',
  'bulletseed',
  'chillingwater',
  'counter',
  'dazzlinggleam',
  'darkvoid',
  'dualwingbeat',
  'electroshot',
  # 'feint',
  'futuresight',
  'grassyglide',
  'gyroball',
  'headbutt',
  'hex',
  'hiddenpower',
  'hyperspacefury',
  'hypnosis',
  'icepunch',
  'iciclecrash',
  'iciclespear',
  'icywind',
  'infestation',
  # 'irondefense',
  'irontail',
  'jumpkick',
  'lastresort',
  'leafblade',
  # 'leechlife',
  'magiccoat',
  'meteorbeam',
  'mysticalfire',
  'naturepower',
  'needlearm',
  'nightslash',
  'outrage',
  'petaldance',
  'phantomforce',
  'poisonfang',
  'raindance',
  'relicsong',
  # 'refresh',
  'risingvoltage',
  'rocktomb',
  'selfdestruct',
  'shadowpunch',
  'shelter',
  'skyuppercut',
  'smackdown',
  'smartstrike',
  'soak',
  'steelwing',
  'stompingtantrum',
  'stunspore',
  'sunnyday',
  'technoblast',
  # 'teleport',
  'temperflare',
  'terrainpulse',
  'waterpulse',
  'thief',
  'toxicspikes',
  'triattack',
  'trickroom',
  'wildcharge',
  'zapcannon',
])

bad_moves = set([
  # Bad strong moves.
  'belch',
  'burnup',
  'crushclaw',
  # 'dragonrush',
  'dreameater',
  'eggbomb',
  'firepledge',
  'flyingpress',
  'futuresight',
  'grasspledge',
  'hyperbeam',
  'hyperfang',
  'hyperspacehole',
  'jawlock',
  'landswrath',
  'megapunch',
  'mistyexplosion',
  'muddywater',
  'nightdaze',
  'pollenpuff',
  'rockclimb',
  # 'selfdestruct',
  'shelltrap',
  'skyuppercut',
  'slam',
  'strength',
  'submission',
  'synchronoise',
  'takedown',
  'thrash',
  'uproar',
  'waterpledge',
  # Doubles moves.
  'allyswitch',
  'bulldoze',
  'coaching',
  'electroweb',
  'faketears',
  'fling',
  'followme',
  'healpulse',
  'helpinghand',
  'junglehealing',
  'lifedew',
  'lunarblessing',
  'muddywater',
  'pollenpuff',
  'psychup',
  'ragepowder',
  'safeguard',
  'skillswap',
  'snipeshot',
  'wideguard',
])

mod_moves = {
  'POUND': 40,
  'KARATE_CHOP': 50,
  'DOUBLE_SLAP': 15,
  'COMET_PUNCH': 18,
  'MEGA_PUNCH': 80,
  'PAY_DAY': 40,
  'FIRE_PUNCH': 75,
  'ICE_PUNCH': 75,
  'THUNDER_PUNCH': 75,
  'SCRATCH': 40,
  'VICE_GRIP': 55,
  'GUILLOTINE': 1,
  'RAZOR_WIND': 80,
  'SWORDS_DANCE': 0,
  'CUT': 50,
  'GUST': 40,
  'WING_ATTACK': 60,
  'WHIRLWIND': 0,
  'FLY': 70,
  'BIND': 15,
  'SLAM': 80,
  'VINE_WHIP': 35,
  'STOMP': 65,
  'DOUBLE_KICK': 30,
  'MEGA_KICK': 120,
  'JUMP_KICK': 70,
  'ROLLING_KICK': 60,
  'SAND_ATTACK': 0,
  'HEADBUTT': 70,
  'HORN_ATTACK': 65,
  'FURY_ATTACK': 15,
  'HORN_DRILL': 1,
  'TACKLE': 35,
  'BODY_SLAM': 85,
  'WRAP': 15,
  'TAKE_DOWN': 90,
  'THRASH': 90,
  'DOUBLE_EDGE': 120,
  'TAIL_WHIP': 0,
  'POISON_STING': 15,
  'TWINEEDLE': 25,
  'PIN_MISSILE': 14,
  'LEER': 0,
  'BITE': 60,
  'GROWL': 0,
  'ROAR': 0,
  'SING': 0,
  'SUPERSONIC': 0,
  'SONIC_BOOM': 1,
  'DISABLE': 0,
  'ACID': 40,
  'EMBER': 40,
  'FLAMETHROWER': 95,
  'MIST': 0,
  'WATER_GUN': 40,
  'HYDRO_PUMP': 120,
  'SURF': 95,
  'ICE_BEAM': 95,
  'BLIZZARD': 120,
  'PSYBEAM': 65,
  'BUBBLE_BEAM': 65,
  'AURORA_BEAM': 65,
  'HYPER_BEAM': 150,
  'PECK': 35,
  'DRILL_PECK': 80,
  'SUBMISSION': 80,
  'LOW_KICK': 1,
  'COUNTER': 1,
  'SEISMIC_TOSS': 1,
  'STRENGTH': 80,
  'ABSORB': 20,
  'MEGA_DRAIN': 40,
  'LEECH_SEED': 0,
  'GROWTH': 0,
  'RAZOR_LEAF': 55,
  'SOLAR_BEAM': 120,
  'POISON_POWDER': 0,
  'STUN_SPORE': 0,
  'SLEEP_POWDER': 0,
  'PETAL_DANCE': 70,
  'STRING_SHOT': 0,
  'DRAGON_RAGE': 1,
  'FIRE_SPIN': 15,
  'THUNDER_SHOCK': 40,
  'THUNDERBOLT': 95,
  'THUNDER_WAVE': 0,
  'THUNDER': 120,
  'ROCK_THROW': 50,
  'EARTHQUAKE': 100,
  'FISSURE': 1,
  'DIG': 60,
  'TOXIC': 0,
  'CONFUSION': 50,
  'PSYCHIC': 90,
  'HYPNOSIS': 0,
  'MEDITATE': 0,
  'AGILITY': 0,
  'QUICK_ATTACK': 40,
  'RAGE': 20,
  'TELEPORT': 0,
  'NIGHT_SHADE': 1,
  'MIMIC': 0,
  'SCREECH': 0,
  'DOUBLE_TEAM': 0,
  'RECOVER': 0,
  'HARDEN': 0,
  'MINIMIZE': 0,
  'SMOKESCREEN': 0,
  'CONFUSE_RAY': 0,
  'WITHDRAW': 0,
  'DEFENSE_CURL': 0,
  'BARRIER': 0,
  'LIGHT_SCREEN': 0,
  'HAZE': 0,
  'REFLECT': 0,
  'FOCUS_ENERGY': 0,
  'BIDE': 1,
  'METRONOME': 0,
  'MIRROR_MOVE': 0,
  'SELF_DESTRUCT': 200,
  'EGG_BOMB': 100,
  'LICK': 20,
  'SMOG': 20,
  'SLUDGE': 65,
  'BONE_CLUB': 65,
  'FIRE_BLAST': 120,
  'WATERFALL': 80,
  'CLAMP': 35,
  'SWIFT': 60,
  'SKULL_BASH': 100,
  'SPIKE_CANNON': 20,
  'CONSTRICT': 10,
  'AMNESIA': 0,
  'KINESIS': 0,
  'SOFT_BOILED': 0,
  'HI_JUMP_KICK': 85,
  'GLARE': 0,
  'DREAM_EATER': 100,
  'POISON_GAS': 0,
  'BARRAGE': 15,
  'LEECH_LIFE': 20,
  'LOVELY_KISS': 0,
  'SKY_ATTACK': 140,
  'TRANSFORM': 0,
  'BUBBLE': 20,
  'DIZZY_PUNCH': 70,
  'SPORE': 0,
  'FLASH': 0,
  'PSYWAVE': 1,
  'SPLASH': 0,
  'ACID_ARMOR': 0,
  'CRABHAMMER': 90,
  'EXPLOSION': 250,
  'FURY_SWIPES': 18,
  'BONEMERANG': 50,
  'REST': 0,
  'ROCK_SLIDE': 75,
  'HYPER_FANG': 80,
  'SHARPEN': 0,
  'CONVERSION': 0,
  'TRI_ATTACK': 80,
  'SUPER_FANG': 1,
  'SLASH': 70,
  'SUBSTITUTE': 0,
  'STRUGGLE': 50,
  'SKETCH': 0,
  'TRIPLE_KICK': 10,
  'THIEF': 40,
  'SPIDER_WEB': 0,
  'MIND_READER': 0,
  'NIGHTMARE': 0,
  'FLAME_WHEEL': 60,
  'SNORE': 40,
  'CURSE': 0,
  'FLAIL': 1,
  'CONVERSION_2': 0,
  'AEROBLAST': 100,
  'COTTON_SPORE': 0,
  'REVERSAL': 1,
  'SPITE': 0,
  'POWDER_SNOW': 40,
  'PROTECT': 0,
  'MACH_PUNCH': 40,
  'SCARY_FACE': 0,
  'FAINT_ATTACK': 60,
  'SWEET_KISS': 0,
  'BELLY_DRUM': 0,
  'SLUDGE_BOMB': 90,
  'MUD_SLAP': 20,
  'OCTAZOOKA': 65,
  'SPIKES': 0,
  'ZAP_CANNON': 100,
  'FORESIGHT': 0,
  'DESTINY_BOND': 0,
  'PERISH_SONG': 0,
  'ICY_WIND': 55,
  'DETECT': 0,
  'BONE_RUSH': 25,
  'LOCK_ON': 0,
  'OUTRAGE': 90,
  'SANDSTORM': 0,
  'GIGA_DRAIN': 60,
  'ENDURE': 0,
  'CHARM': 0,
  'ROLLOUT': 30,
  'FALSE_SWIPE': 40,
  'SWAGGER': 0,
  'MILK_DRINK': 0,
  'SPARK': 65,
  'FURY_CUTTER': 10,
  'STEEL_WING': 70,
  'MEAN_LOOK': 0,
  'ATTRACT': 0,
  'SLEEP_TALK': 0,
  'HEAL_BELL': 0,
  'RETURN': 1,
  'PRESENT': 1,
  'FRUSTRATION': 1,
  'SAFEGUARD': 0,
  'PAIN_SPLIT': 0,
  'SACRED_FIRE': 100,
  'MAGNITUDE': 1,
  'DYNAMIC_PUNCH': 100,
  'MEGAHORN': 120,
  'DRAGON_BREATH': 60,
  'BATON_PASS': 0,
  'ENCORE': 0,
  'PURSUIT': 40,
  'RAPID_SPIN': 20,
  'SWEET_SCENT': 0,
  'IRON_TAIL': 100,
  'METAL_CLAW': 50,
  'VITAL_THROW': 70,
  'MORNING_SUN': 0,
  'SYNTHESIS': 0,
  'MOONLIGHT': 0,
  'HIDDEN_POWER': 1,
  'CROSS_CHOP': 100,
  'TWISTER': 40,
  'RAIN_DANCE': 0,
  'SUNNY_DAY': 0,
  'CRUNCH': 80,
  'MIRROR_COAT': 1,
  'PSYCH_UP': 0,
  'EXTREME_SPEED': 80,
  'ANCIENT_POWER': 60,
  'SHADOW_BALL': 80,
  'FUTURE_SIGHT': 80,
  'ROCK_SMASH': 20,
  'WHIRLPOOL': 15,
  'BEAT_UP': 10,
  'FAKE_OUT': 40,
  'UPROAR': 50,
  'STOCKPILE': 0,
  'SPIT_UP': 0,  # Changed manually
  'SWALLOW': 0,
  'HEAT_WAVE': 100,
  'HAIL': 0,
  'TORMENT': 0,
  'FLATTER': 0,
  'WILL_O_WISP': 0,
  'MEMENTO': 0,
  'FACADE': 70,
  'FOCUS_PUNCH': 150,
  'SMELLING_SALT': 60,
  'FOLLOW_ME': 0,
  'NATURE_POWER': 0,
  'CHARGE': 0,
  'TAUNT': 0,
  'HELPING_HAND': 0,
  'TRICK': 0,
  'ROLE_PLAY': 0,
  'WISH': 0,
  'ASSIST': 0,
  'INGRAIN': 0,
  'SUPERPOWER': 120,
  'MAGIC_COAT': 0,
  'RECYCLE': 0,
  'REVENGE': 60,
  'BRICK_BREAK': 75,
  'YAWN': 0,
  'KNOCK_OFF': 20,
  'ENDEAVOR': 1,
  'ERUPTION': 150,
  'SKILL_SWAP': 0,
  'IMPRISON': 0,
  'REFRESH': 0,
  'GRUDGE': 0,
  'SNATCH': 0,
  'SECRET_POWER': 70,
  'DIVE': 60,
  'ARM_THRUST': 15,
  'CAMOUFLAGE': 0,
  'TAIL_GLOW': 0,
  'LUSTER_PURGE': 70,
  'MIST_BALL': 70,
  'FEATHER_DANCE': 0,
  'TEETER_DANCE': 0,
  'BLAZE_KICK': 85,
  'MUD_SPORT': 0,
  'ICE_BALL': 30,
  'NEEDLE_ARM': 60,
  'SLACK_OFF': 0,
  'HYPER_VOICE': 90,
  'POISON_FANG': 50,
  'CRUSH_CLAW': 75,
  'BLAST_BURN': 150,
  'HYDRO_CANNON': 150,
  'METEOR_MASH': 100,
  'ASTONISH': 30,
  'WEATHER_BALL': 50,
  'AROMATHERAPY': 0,
  'FAKE_TEARS': 0,
  'AIR_CUTTER': 55,
  'OVERHEAT': 140,
  'ODOR_SLEUTH': 0,
  'ROCK_TOMB': 50,
  'SILVER_WIND': 60,
  'METAL_SOUND': 0,
  'GRASS_WHISTLE': 0,
  'TICKLE': 0,
  'COSMIC_POWER': 0,
  'WATER_SPOUT': 150,
  'SIGNAL_BEAM': 75,
  'SHADOW_PUNCH': 60,
  'EXTRASENSORY': 80,
  'SKY_UPPERCUT': 85,
  'SAND_TOMB': 15,
  'SHEER_COLD': 1,
  'MUDDY_WATER': 95,
  'BULLET_SEED': 10,
  'AERIAL_ACE': 60,
  'ICICLE_SPEAR': 10,
  'IRON_DEFENSE': 0,
  'BLOCK': 0,
  'HOWL': 0,
  'DRAGON_CLAW': 80,
  'FRENZY_PLANT': 150,
  'BULK_UP': 0,
  'BOUNCE': 85,
  'MUD_SHOT': 55,
  'POISON_TAIL': 50,
  'COVET': 40,
  'VOLT_TACKLE': 120,
  'MAGICAL_LEAF': 60,
  'WATER_SPORT': 0,
  'CALM_MIND': 0,
  'LEAF_BLADE': 70,
  'DRAGON_DANCE': 0,
  'ROCK_BLAST': 25,
  'SHOCK_WAVE': 60,
  'WATER_PULSE': 60,
  'DOOM_DESIRE': 120,
  'PSYCHO_BOOST': 140,
  'AIR_SLASH': 75,
  'AQUA_JET': 40,
  'AQUA_RING': 0,
  'AQUA_TAIL': 90,
  'ASSURANCE': 60,
  'ATTACK_ORDER': 90,
  'AURA_SPHERE': 80,
  'AVALANCHE': 60,
  'BRAVE_BIRD': 120,
  'BRINE': 65,
  'BUG_BITE': 60,
  'BUG_BUZZ': 90,
  'BULLET_PUNCH': 40,
  'CAPTIVATE': 0,
  'CHARGE_BEAM': 50,
  'CHATTER': 65,
  'CLOSE_COMBAT': 120,
  'COPYCAT': 0,
  'CROSS_POISON': 70,
  'CRUSH_GRIP': 0,
  'DARK_PULSE': 80,
  'DARK_VOID': 0,
  'DEFEND_ORDER': 0,
  ' DEFOG': 0,
  'DISCHARGE': 80,
  'DOUBLE_HIT': 35,
  'DRACO_METEOR': 130,
  'DRAGON_PULSE': 85,
  'DRAGON_RUSH': 100,
  'DRAIN_PUNCH': 75,
  'EARTH_POWER': 90,
  'EMBARGO': 0,
  'ENERGY_BALL': 90,
  'FEINT': 35,
  'FIRE_FANG': 65,
  'FLARE_BLITZ': 120,
  'FLASH_CANNON': 80,
  'FLING': 35,
  'FOCUS_BLAST': 120,
  'FORCE_PALM': 60,
  'GASTRO_ACID': 0,
  'GIGA_IMPACT': 150,
  'GRASS_KNOT': 70,
  'GRAVITY': 0,
  'GUARD_SWAP': 0,
  'GUNK_SHOT': 120,
  'GYRO_BALL': 70,
  'HAMMER_ARM': 100,
  'HEAD_SMASH': 150,
  'HEAL_BLOCK': 0,
  'HEAL_ORDER': 0,
  'HEALING_WISH': 0,
  'HEART_SWAP': 0,
  'ICE_FANG': 65,
  'ICE_SHARD': 40,
  'IRON_HEAD': 80,
  'JUDGMENT': 100,
  'LAST_RESORT': 0,
  'LAVA_PLUME': 80,
  'LEAF_STORM': 140,
  'LUCKY_CHANT': 0,
  'LUNAR_DANCE': 0,
  'MAGMA_STORM': 100,
  'MAGNET_BOMB': 60,
  'MAGNET_RISE': 0,
  'ME_FIRST': 0,
  'METAL_BURST': 60,
  'MIRACLE_EYE': 0,
  'MIRROR_SHOT': 65,
  'MUD_BOMB': 65,
  'NASTY_PLOT': 0,
  'NATURAL_GIFT': 60,
  'NIGHT_SLASH': 70,
  'OMINOUS_WIND': 60,
  'PAYBACK': 75,
  'PLUCK': 60,
  'POISON_JAB': 80,
  'POWER_GEM': 70,
  'POWER_SWAP': 0,
  'POWER_TRICK': 0,
  'POWER_WHIP': 120,
  'PSYCHO_CUT': 70,
  'PSYCHO_SHIFT': 0,
  'PUNISHMENT': 60,
  'ROAR_OF_TIME': 150,
  'ROCK_CLIMB': 90,
  'ROCK_POLISH': 0,
  'ROCK_WRECKER': 150,
  'ROOST': 0,
  'SEED_BOMB': 80,
  'SEED_FLARE': 120,
  'SHADOW_CLAW': 70,
  'SHADOW_FORCE': 120,
  'SHADOW_SNEAK': 40,
  'SPACIAL_REND': 100,
  'STEALTH_ROCK': 0,
  'STONE_EDGE': 100,
  'SUCKER_PUNCH': 80,
  'SWITCHEROO': 0,
  'TAILWIND': 0,
  'THUNDER_FANG': 65,
  'TOXIC_SPIKES': 0,
  'TRICK_ROOM': 0,
  'TRUMP_CARD': 60,
  'U_TURN': 70,
  'VACUUM_WAVE': 40,
  'WAKE_UP_SLAP': 70,
  'WOOD_HAMMER': 120,
  'WORRY_SEED': 0,
  'WRING_OUT': 61,
  'X_SCISSOR': 80,
  'ZEN_HEADBUTT': 80,
}

original_tms = [
  'FOCUS_PUNCH',
  'DRAGON_CLAW',
  'WATER_PULSE',
  'CALM_MIND',
  'ROAR',
  'TOXIC',
  'HAIL',
  'BULK_UP',
  'BULLET_SEED',
  'HIDDEN_POWER',
  'SUNNY_DAY',
  'TAUNT',
  'ICE_BEAM',
  'BLIZZARD',
  'HYPER_BEAM',
  'LIGHT_SCREEN',
  'PROTECT',
  'RAIN_DANCE',
  'GIGA_DRAIN',
  'SAFEGUARD',
  'FRUSTRATION',
  'SOLAR_BEAM',
  'IRON_TAIL',
  'THUNDERBOLT',
  'THUNDER',
  'EARTHQUAKE',
  'RETURN',
  'DIG',
  'PSYCHIC',
  'SHADOW_BALL',
  'BRICK_BREAK',
  'DOUBLE_TEAM',
  'REFLECT',
  'SHOCK_WAVE',
  'FLAMETHROWER',
  'SLUDGE_BOMB',
  'SANDSTORM',
  'FIRE_BLAST',
  'ROCK_TOMB',
  'AERIAL_ACE',
  'TORMENT',
  'FACADE',
  'SECRET_POWER',
  'REST',
  'ATTRACT',
  'THIEF',
  'STEEL_WING',
  'SKILL_SWAP',
  'SNATCH',
  'OVERHEAT',
  'ROOST',
  'FOCUS_BLAST',
  'ENERGY_BALL',
  'FALSE_SWIPE',
  'BRINE',
  'FLING',
  'CHARGE_BEAM',
  'ENDURE',
  'DRAGON_PULSE',
  'DRAIN_PUNCH',
  'WILL_O_WISP',
  'SILVER_WIND',
  'EMBARGO',
  'EXPLOSION',
  'SHADOW_CLAW',
  'PAYBACK',
  'RECYCLE',
  'GIGA_IMPACT',
  'ROCK_POLISH',
  'FLASH',
  'STONE_EDGE',
  'AVALANCHE',
  'THUNDER_WAVE',
  'GYRO_BALL',
  'SWORDS_DANCE',
  'STEALTH_ROCK',
  'PSYCH_UP',
  'CAPTIVATE',
  'DARK_PULSE',
  'ROCK_SLIDE',
  'X_SCISSOR',
  'SLEEP_TALK',
  'NATURAL_GIFT',
  'POISON_JAB',
  'DREAM_EATER',
  'GRASS_KNOT',
  'SWAGGER',
  'PLUCK',
  'U_TURN',
  'SUBSTITUTE',
  'FLASH_CANNON',
  'TRICK_ROOM',
]

hms = set([
  'CUT',
  'FLY',
  'SURF',
  'STRENGTH',
  'FLASH',
  'ROCK_SMASH',
  'WATERFALL',
  'DIVE',
])

tm_counts = {}
non_tm_counts = {}

for m in original_tms:
  move = m.lower().replace('_', '').replace('-', '')
  count = subprocess.getoutput('grep -woP' + " '[\t]" + move + ":.*$' " + 'filtered_learnsets.ts | grep -P \'"(4|3T)\' | grep -v \'"4L[1-3]\' | wc -l')
  tm_counts[move] = int(count)

for m, p in mod_moves.items():
  move = m.lower().replace('_', '').replace('-', '')
  if move in tm_counts or m in hms:
    continue
  count = subprocess.getoutput('grep -woP' + " '[\t]" + move + ":.*$' " + 'filtered_learnsets.ts | grep -P \'"(4|3T)\' | grep -v \'"4L[1-3]\' | wc -l')
  if ((p < 75 and move in good_moves) or (p >= 75 and move not in bad_moves)) and (int(count) >= 9 or move == 'dracometeor' or move == 'dragonrush'):
    tm_counts[move] = int(count)
  elif int(count) > 0:
    count = subprocess.getoutput('grep -woP' + " '[\t]" + move + ":.*$' " + 'filtered_learnsets.ts | grep -P \'"(4|3)(E|T|M)\' | grep -v \'"4L\' | wc -l')
    non_tm_counts[move] = int(count)

print(' === TMS === ')
i = 0
for move, count in tm_counts.items():
  i += 1
  print("TM%03d" % (int(i),) + ": " + move + ' (' + str(count) + ')')

print('\n === NEW LV1 MOVES === ')
i = 0
for move, count in non_tm_counts.items():
  if count == 0:
    continue
  i += 1
  print(str(i) + ": " + move + ' (' + str(count) + ')')

