import csv

mon2moves = {}

with open('serebii_gen4_tm_learnsets.csv') as csv_file:
  reader = csv.reader(csv_file)
  for i, row in enumerate(reader):
    move = 'TM' + str(51+i) + '_' + row[0].strip().replace(' ', '_').replace('-', '_').upper()
    dex_no = 0
    for i in range(1, len(row)):
      if len(row[i]) == 0:
        continue
      elif row[i][0] == '#':
        dex_no = int(row[i][1:])
      elif (dex_no > 0) and (len(row[i]) > 0):
        mon = 'SPECIES_' + row[i].strip().replace(' ', '_').replace('-', '_').replace('.', '').replace("'", '').replace('♀', '_F').replace('♂', '_M').upper()
        if dex_no not in mon2moves:
          mon2moves[dex_no] = (mon, [])
        mon2moves[dex_no][1].append(move)
        dex_no = 0

# print(mon2moves.keys())
# print(len(mon2moves.keys()))
# print(mon2moves[42])

s = '''
// +--------------------------------------------------------+
// | !!! AUTOGENERATED BY generate_gen4_tm_learnsets.py !!! |
// +--------------------------------------------------------+

#define G4TMHM_LEARNSET(moves) {(u32)(moves), ((u64)(moves) >> 32)}                                                                                                                                                                             
#define G4TMHM(tmhm) ((u64)1 << (ITEM_##tmhm - ITEM_TM51_ROOST))

// This table is similar to the one in tmhm_learnsets.h.
static const u32 sGen4TMHMLearnsets[][2] =
{
  [SPECIES_NONE]      = G4TMHM_LEARNSET(0),

'''

with open('src/data/pokemon/gen4_tmhm_learnsets.h', 'w') as c_file:
  for dex_no in range (1, 359):
    if dex_no not in mon2moves:
      s += '[' + str(dex_no) + '] = G4TMHM_LEARNSET(0),\n\n'
    else:
      mon, moves = mon2moves[dex_no]
      s += '  [' + mon + '] = G4TMHM_LEARNSET(G4TMHM(' + moves[0] + ')'
      for i in range (1, len(moves)):
        s += '\n' + (40*' ') + '| G4TMHM(' + moves[i] + ')'
      s += '),\n\n'
  c_file.write(s + '};')
      
