included_mons_input = [
  'BULBASAUR',
  'IVYSAUR',
  'VENUSAUR',
  'CHARMANDER',
  'CHARMELEON',
  'CHARIZARD',
  'SQUIRTLE',
  'WARTORTLE',
  'BLASTOISE',
  'CATERPIE',
  'METAPOD',
  'BUTTERFREE',
  'WEEDLE',
  'KAKUNA',
  'BEEDRILL',
  'PIDGEY',
  'PIDGEOTTO',
  'PIDGEOT',
  'RATTATA',
  'RATICATE',
  'SPEAROW',
  'FEAROW',
  'EKANS',
  'ARBOK',
  'PIKACHU',
  'RAICHU',
  'SANDSHREW',
  'SANDSLASH',
  'NIDORAN_F',
  'NIDORINA',
  'NIDOQUEEN',
  'NIDORAN_M',
  'NIDORINO',
  'NIDOKING',
  'CLEFAIRY',
  'CLEFABLE',
  'VULPIX',
  'NINETALES',
  'JIGGLYPUFF',
  'WIGGLYTUFF',
  'ZUBAT',
  'GOLBAT',
  'ODDISH',
  'GLOOM',
  'VILEPLUME',
  'PARAS',
  'PARASECT',
  'VENONAT',
  'VENOMOTH',
  'DIGLETT',
  'DUGTRIO',
  'MEOWTH',
  'PERSIAN',
  'PSYDUCK',
  'GOLDUCK',
  'MANKEY',
  'PRIMEAPE',
  'GROWLITHE',
  'ARCANINE',
  'POLIWAG',
  'POLIWHIRL',
  'POLIWRATH',
  'ABRA',
  'KADABRA',
  'ALAKAZAM',
  'MACHOP',
  'MACHOKE',
  'MACHAMP',
  'BELLSPROUT',
  'WEEPINBELL',
  'VICTREEBEL',
  'TENTACOOL',
  'TENTACRUEL',
  'GEODUDE',
  'GRAVELER',
  'GOLEM',
  'PONYTA',
  'RAPIDASH',
  'SLOWPOKE',
  'SLOWBRO',
  'MAGNEMITE',
  'MAGNETON',
  'FARFETCHD',
  'DODUO',
  'DODRIO',
  'SEEL',
  'DEWGONG',
  'GRIMER',
  'MUK',
  'SHELLDER',
  'CLOYSTER',
  'GASTLY',
  'HAUNTER',
  'GENGAR',
  'ONIX',
  'DROWZEE',
  'HYPNO',
  'KRABBY',
  'KINGLER',
  'VOLTORB',
  'ELECTRODE',
  'EXEGGCUTE',
  'EXEGGUTOR',
  'CUBONE',
  'MAROWAK',
  'HITMONLEE',
  'HITMONCHAN',
  'LICKITUNG',
  'KOFFING',
  'WEEZING',
  'RHYHORN',
  'RHYDON',
  'CHANSEY',
  'TANGELA',
  'KANGASKHAN',
  'HORSEA',
  'SEADRA',
  'GOLDEEN',
  'SEAKING',
  'STARYU',
  'STARMIE',
  'MR_MIME',
  'SCYTHER',
  'JYNX',
  'ELECTABUZZ',
  'MAGMAR',
  'PINSIR',
  'TAUROS',
  'MAGIKARP',
  'GYARADOS',
  'LAPRAS',
  'DITTO',
  'EEVEE',
  'VAPOREON',
  'JOLTEON',
  'FLAREON',
  'PORYGON',
  'OMANYTE',
  'OMASTAR',
  'KABUTO',
  'KABUTOPS',
  'AERODACTYL',
  'SNORLAX',
  'ARTICUNO',
  'ZAPDOS',
  'MOLTRES',
  'DRATINI',
  'DRAGONAIR',
  'DRAGONITE',
  'MIME_JR',
  'BUDEW',
  'CHIKORITA',
  'BAYLEEF',
  'MEGANIUM',
  'CYNDAQUIL',
  'QUILAVA',
  'TYPHLOSION',
  'TOTODILE',
  'CROCONAW',
  'FERALIGATR',
  'SENTRET',
  'FURRET',
  'HOOTHOOT',
  'NOCTOWL',
  'LEDYBA',
  'LEDIAN',
  'SPINARAK',
  'ARIADOS',
  'CROBAT',
  'CHINCHOU',
  'LANTURN',
  'PICHU',
  'CLEFFA',
  'IGGLYBUFF',
  'TOGEPI',
  'TOGETIC',
  'NATU',
  'XATU',
  'MAREEP',
  'FLAAFFY',
  'AMPHAROS',
  'BELLOSSOM',
  'MARILL',
  'AZUMARILL',
  'SUDOWOODO',
  'POLITOED',
  'HOPPIP',
  'SKIPLOOM',
  'JUMPLUFF',
  'AIPOM',
  'SUNKERN',
  'SUNFLORA',
  'YANMA',
  'WOOPER',
  'QUAGSIRE',
  'ESPEON',
  'UMBREON',
  'MURKROW',
  'SLOWKING',
  'MISDREAVUS',
  'WEAVILE',
  'GLISCOR',
  'GIRAFARIG',
  'PINECO',
  'FORRETRESS',
  'DUNSPARCE',
  'GLIGAR',
  'STEELIX',
  'SNUBBULL',
  'GRANBULL',
  'QWILFISH',
  'SCIZOR',
  'SHUCKLE',
  'HERACROSS',
  'SNEASEL',
  'TEDDIURSA',
  'URSARING',
  'SLUGMA',
  'MAGCARGO',
  'SWINUB',
  'PILOSWINE',
  'CORSOLA',
  'REMORAID',
  'OCTILLERY',
  'DELIBIRD',
  'MANTINE',
  'SKARMORY',
  'HOUNDOUR',
  'HOUNDOOM',
  'KINGDRA',
  'PHANPY',
  'DONPHAN',
  'PORYGON2',
  'STANTLER',
  'PROBOPASS',
  'TYROGUE',
  'HITMONTOP',
  'SMOOCHUM',
  'ELEKID',
  'MAGBY',
  'MILTANK',
  'BLISSEY',
  'ROSERADE',
  'TANGROWTH',
  'YANMEGA',
  'LARVITAR',
  'PUPITAR',
  'TYRANITAR',
  'MISMAGIUS',
  'HONCHKROW',
  'FROSLASS',
  'TREECKO',
  'GROVYLE',
  'SCEPTILE',
  'TORCHIC',
  'COMBUSKEN',
  'BLAZIKEN',
  'MUDKIP',
  'MARSHTOMP',
  'SWAMPERT',
  'POOCHYENA',
  'MIGHTYENA',
  'ZIGZAGOON',
  'LINOONE',
  'WURMPLE',
  'SILCOON',
  'BEAUTIFLY',
  'CASCOON',
  'DUSTOX',
  'LOTAD',
  'LOMBRE',
  'LUDICOLO',
  'SEEDOT',
  'NUZLEAF',
  'SHIFTRY',
  'NINCADA',
  'NINJASK',
  'ELECTIVIRE',
  'TAILLOW',
  'SWELLOW',
  'SHROOMISH',
  'BRELOOM',
  'SPINDA',
  'WINGULL',
  'PELIPPER',
  'SURSKIT',
  'MASQUERAIN',
  'WAILMER',
  'WAILORD',
  'SKITTY',
  'DELCATTY',
  'KECLEON',
  'BALTOY',
  'CLAYDOL',
  'NOSEPASS',
  'TORKOAL',
  'SABLEYE',
  'BARBOACH',
  'WHISCASH',
  'HAPPINY',
  'CORPHISH',
  'CRAWDAUNT',
  'FEEBAS',
  'MILOTIC',
  'CARVANHA',
  'SHARPEDO',
  'TRAPINCH',
  'VIBRAVA',
  'FLYGON',
  'MAKUHITA',
  'HARIYAMA',
  'ELECTRIKE',
  'MANECTRIC',
  'NUMEL',
  'CAMERUPT',
  'SPHEAL',
  'SEALEO',
  'WALREIN',
  'CACNEA',
  'CACTURNE',
  'SNORUNT',
  'GLALIE',
  'LUNATONE',
  'SOLROCK',
  'AZURILL',
  'SPOINK',
  'GRUMPIG',
  'PLUSLE',
  'AMBIPOM',
  'MAWILE',
  'MEDITITE',
  'MEDICHAM',
  'SWABLU',
  'ALTARIA',
  'TOGEKISS',
  'DUSKULL',
  'DUSCLOPS',
  'ROSELIA',
  'SLAKOTH',
  'VIGOROTH',
  'SLAKING',
  'GULPIN',
  'SWALOT',
  'TROPIUS',
  'WHISMUR',
  'LOUDRED',
  'EXPLOUD',
  'CLAMPERL',
  'HUNTAIL',
  'GOREBYSS',
  'ABSOL',
  'SHUPPET',
  'BANETTE',
  'SEVIPER',
  'ZANGOOSE',
  'RELICANTH',
  'ARON',
  'LAIRON',
  'AGGRON',
  'MAGMORTAR',
  'VOLBEAT',
  'ILLUMISE',
  'LILEEP',
  'CRADILY',
  'ANORITH',
  'ARMALDO',
  'RALTS',
  'KIRLIA',
  'GARDEVOIR',
  'BAGON',
  'SHELGON',
  'SALAMENCE',
  'BELDUM',
  'METANG',
  'METAGROSS',
  'MUNCHLAX',
  'LICKILICKY',
  'MAGNEZONE',
  'PORYGON_Z',
  'GALLADE',
  'DUSKNOIR',
  'RHYPERIOR',
  'MAMOSWINE',
  'LEAFEON',
  'GLACEON',
  'CHIMECHO',
]

evos = {}
evolving_mons = set()
with open('src/data/pokemon/evolution.h','r') as evo_file:
  for line in evo_file:
    l = line.replace('{', '').replace('}', '').replace('SPECIES_', '').replace('[', '').replace(']', '').replace('=', ',').replace(' ', '').replace('_', '').lower()
    l_split = l.split(',')
    if len(l_split) == 5:
      evos[l_split[3]] = l_split[0]
      evolving_mons.add(l_split[0])

included_mons = set()
for mon in included_mons_input:
  included_mons.add(mon.lower().replace('_','').replace('-',''))

egg_moves = {}
with open('../pokemon-showdown/data/learnsets.ts','r') as in_file:
  mon = None
  in_learnset = False
  for line in in_file:
    if line[1].isalpha() and line.strip().endswith(': {'):
      mon = line.strip().replace(': {','')
    elif 'learnset:' in line:
      in_learnset = True
    elif in_learnset and ('},' in line):
      in_learnset = False

    if mon not in included_mons:
      continue

    if in_learnset and ('"4E' in line or '"3E'):
      if mon not in egg_moves:
        egg_moves[mon] = []
      egg_moves[mon].append(line)

s =''
with open('../pokemon-showdown/data/learnsets.ts','r') as in_file:
  mon = None
  in_learnset = False
  for line in in_file:
    if line[1].isalpha() and line.strip().endswith(': {'):
      mon = line.strip().replace(': {','')
      s += line
    elif 'learnset:' in line:
      in_learnset = True
      s += line
    elif not in_learnset:
      continue

    if '"4' in line or '"3' in line:
      s += line
    elif '},' in line:
      if mon in included_mons and mon not in evolving_mons:
        m = mon
        while m != None:
          for egg_move in egg_moves.get(m, []):
            s += egg_move
          m = evos.get(m)
      in_learnset = False
      s += line

with open('filtered_learnsets.ts','w') as out_file:
  out_file.write(s)
