m = {
  'MOVE_FOCUS_PUNCH,': 'TM01_FOCUS_PUNCH',
  'MOVE_DRAGON_CLAW,': 'TM02_DRAGON_CLAW',
  'MOVE_WATER_PULSE,': 'TM03_WATER_PULSE',
  'MOVE_CALM_MIND,': 'TM04_CALM_MIND',
  'MOVE_ROAR,': 'TM05_ROAR',
  'MOVE_TOXIC,': 'TM06_TOXIC',
  'MOVE_HAIL,': 'TM07_HAIL',
  'MOVE_BULK_UP,': 'TM08_BULK_UP',
  'MOVE_BULLET_SEED,': 'TM09_BULLET_SEED',
  'MOVE_HIDDEN_POWER,': 'TM10_HIDDEN_POWER',
  'MOVE_SUNNY_DAY,': 'TM11_SUNNY_DAY',
  'MOVE_TAUNT,': 'TM12_TAUNT',
  'MOVE_ICE_BEAM,': 'TM13_ICE_BEAM',
  'MOVE_BLIZZARD,': 'TM14_BLIZZARD',
  'MOVE_HYPER_BEAM,': 'TM15_HYPER_BEAM',
  'MOVE_LIGHT_SCREEN,': 'TM16_LIGHT_SCREEN',
  'MOVE_PROTECT,': 'TM17_PROTECT',
  'MOVE_RAIN_DANCE,': 'TM18_RAIN_DANCE',
  'MOVE_GIGA_DRAIN,': 'TM19_GIGA_DRAIN',
  'MOVE_SAFEGUARD,': 'TM20_SAFEGUARD',
  'MOVE_FRUSTRATION,': 'TM21_FRUSTRATION',
  'MOVE_SOLAR_BEAM,': 'TM22_SOLAR_BEAM',
  'MOVE_IRON_TAIL,': 'TM23_IRON_TAIL',
  'MOVE_THUNDERBOLT,': 'TM24_THUNDERBOLT',
  'MOVE_THUNDER,': 'TM25_THUNDER',
  'MOVE_EARTHQUAKE,': 'TM26_EARTHQUAKE',
  'MOVE_RETURN,': 'TM27_RETURN',
  'MOVE_DIG,': 'TM28_DIG',
  'MOVE_PSYCHIC,': 'TM29_PSYCHIC',
  'MOVE_SHADOW_BALL,': 'TM30_SHADOW_BALL',
  'MOVE_BRICK_BREAK,': 'TM31_BRICK_BREAK',
  'MOVE_DOUBLE_TEAM,': 'TM32_DOUBLE_TEAM',
  'MOVE_REFLECT,': 'TM33_REFLECT',
  'MOVE_SHOCK_WAVE,': 'TM34_SHOCK_WAVE',
  'MOVE_FLAMETHROWER,': 'TM35_FLAMETHROWER',
  'MOVE_SLUDGE_BOMB,': 'TM36_SLUDGE_BOMB',
  'MOVE_SANDSTORM,': 'TM37_SANDSTORM',
  'MOVE_FIRE_BLAST,': 'TM38_FIRE_BLAST',
  'MOVE_ROCK_TOMB,': 'TM39_ROCK_TOMB',
  'MOVE_AERIAL_ACE,': 'TM40_AERIAL_ACE',
  'MOVE_TORMENT,': 'TM41_TORMENT',
  'MOVE_FACADE,': 'TM42_FACADE',
  'MOVE_SECRET_POWER,': 'TM43_SECRET_POWER',
  'MOVE_REST,': 'TM44_REST',
  'MOVE_ATTRACT,': 'TM45_ATTRACT',
  'MOVE_THIEF,': 'TM46_THIEF',
  'MOVE_STEEL_WING,': 'TM47_STEEL_WING',
  'MOVE_SKILL_SWAP,': 'TM48_SKILL_SWAP',
  'MOVE_SNATCH,': 'TM49_SNATCH',
  'MOVE_OVERHEAT,': 'TM50_OVERHEAT'
}

s = ''
with open('teachable_learnsets.h', 'r') as in_file:
  for line in in_file:
    if not line.startswith('    MOVE_'):
      s += line
      continue
    mapped = m.get(line.strip(), None)
    if mapped is None:
      continue
    s += '                                        | TMHM(' + m.get(line.strip(), '') + ')\n'

with open('teachable_learnsets_out.h', 'w') as out_file:
  out_file.write(s)
 
