Route19_Text_RichardIntro:: @ 81877A3
    .string "I have to exercise and warm up\n"
    .string "before going out for a swim.$"

Route19_Text_RichardDefeat:: @ 81877DF
    .string "All warmed up!$"

Route19_Text_RichardPostBattle:: @ 81877EE
    .string "Thanks, kid!\n"
    .string "I'm ready for a swim.$"

Route19_Text_ReeceIntro:: @ 8187811
    .string "Wait! Slow down!\n"
    .string "You'll have a heart attack!$"

Route19_Text_ReeceDefeat:: @ 818783E
    .string "Ooh!\n"
    .string "That's chilly!$"

Route19_Text_ReecePostBattle:: @ 8187852
    .string "Watch out for TENTACOOL.\n"
    .string "They sting so painfully.$"

Route19_Text_MatthewIntro:: @ 8187884
    .string "I love swimming!\n"
    .string "What about you?$"

Route19_Text_MatthewDefeat:: @ 81878A5
    .string "Belly flop!$"

Route19_Text_MatthewPostBattle:: @ 81878B1
    .string "I can beat even marine POKéMON\n"
    .string "at swimming.$"

Route19_Text_DouglasIntro:: @ 81878DD
    .string "What's beyond the horizon?$"

Route19_Text_DouglasDefeat:: @ 81878F8
    .string "Glub!$"

Route19_Text_DouglasPostBattle:: @ 81878FE
    .string "I see a couple of islands over\n"
    .string "yonder!$"

Route19_Text_DavidIntro:: @ 8187925
    .string "I tried diving for POKéMON, but it\n"
    .string "was a no-go.$"

Route19_Text_DavidDefeat:: @ 8187955
    .string "Help!$"

Route19_Text_DavidPostBattle:: @ 818795B
    .string "I guess you have to fish for sea\n"
    .string "POKéMON.$"

Route19_Text_TonyIntro:: @ 8187985
    .string "I look at the sea to forget all\n"
    .string "the bad things that happened.$"

Route19_Text_TonyDefeat:: @ 81879C3
    .string "Ooh!\n"
    .string "Traumatic!$"

Route19_Text_TonyPostBattle:: @ 81879D3
    .string "I'm looking at the sea to forget\n"
    .string "the bad thing that happened!$"

Route19_Text_AnyaIntro:: @ 8187A11
    .string "Oh, I just love your ride!\n"
    .string "Can I have it if I win?$"

Route19_Text_AnyaDefeat:: @ 8187A44
    .string "Oh! I lost!$"

Route19_Text_AnyaPostBattle:: @ 8187A50
    .string "It's still a long way to go to\n"
    .string "SEAFOAM ISLANDS…\p"
    .string "I want to go back to FUCHSIA…$"

Route19_Text_AliceIntro:: @ 8187A9E
    .string "Swimming's great!\n"
    .string "Sunburns aren't!$"

Route19_Text_AliceDefeat:: @ 8187AC1
    .string "Shocker!$"

Route19_Text_AlicePostBattle:: @ 8187ACA
    .string "My boyfriend wanted to swim to\n"
    .string "SEAFOAM ISLANDS.$"

Route19_Text_AxleIntro:: @ 8187AFA
    .string "Ahoy, there!\n"
    .string "These waters are treacherous!$"

Route19_Text_AxleDefeat:: @ 8187B25
    .string "Ooh!\n"
    .string "Dangerous!$"

Route19_Text_AxlePostBattle:: @ 8187B35
    .string "M-my legs! They cramped up!\n"
    .string "Glub, glub…$"

Route19_Text_ConnieIntro:: @ 8187B5D
    .string "I swam here with my friends…\n"
    .string "I'm tired…$"

Route19_Text_ConnieDefeat:: @ 8187B85
    .string "I'm exhausted…$"

Route19_Text_ConniePostBattle:: @ 8187B94
    .string "If I were to ride a POKéMON on\n"
    .string "the sea, I'd like a LAPRAS.\p"
    .string "LAPRAS is so big, I bet it\n"
    .string "would keep me dry on water.$"

Route19_Text_RouteSign:: @ 8187C06
    .string "SEA ROUTE 19\n"
    .string "FUCHSIA CITY - SEAFOAM ISLANDS$"

Route19_Text_LiaIntro:: @ 8187C32
    .string "LIA: I'm looking after my brother.\n"
    .string "He just became a TRAINER.$"

Route19_Text_LiaDefeat:: @ 8187C6F
    .string "LIA: That's no way to treat my\n"
    .string "little brother!$"

Route19_Text_LiaPostBattle:: @ 8187C9E
    .string "LIA: Do you have a younger\n"
    .string "brother?\p"
    .string "I hope you're teaching him all\n"
    .string "sorts of things.$"

Route19_Text_LiaNotEnoughMons:: @ 8187CF2
    .string "LIA: I want to battle together\n"
    .string "with my little brother.\p"
    .string "Don't you have two POKéMON?$"

Route19_Text_LucIntro:: @ 8187D45
    .string "LUC: My big sis taught me how\n"
    .string "to swim and train POKéMON.$"

Route19_Text_LucDefeat:: @ 8187D7E
    .string "LUC: Oh, wow!\n"
    .string "Someone tougher than my big sis!$"

Route19_Text_LucPostBattle:: @ 8187DAD
    .string "LUC: My big sis is strong and nice.\n"
    .string "I think she's awesome!$"

Route19_Text_LucNotEnoughMons:: @ 8187DE8
    .string "LUC: I don't want to if I can't\n"
    .string "battle you with my big sis.\p"
    .string "Don't you have two POKéMON?$"
