Text_174710:: @ 8174710
    .string "I wonder if you are good enough\n"
    .string "for me?$"

Text_174738:: @ 8174738
    .string "I lost out…$"

gUnknown_8174744:: @ 8174744
    .string "I never wanted to lose to anybody,\n"
    .string "especially to a younger kid…$"

Text_174784:: @ 8174784
    .string "I can see you're good.\n"
    .string "Let me see exactly how good!$"

Text_1747B8:: @ 81747B8
    .string "I had a chance…$"

gUnknown_81747C8:: @ 81747C8
    .string "Tch!\n"
    .string "I concede, you are better than I!$"

