VictoryRoad_1F_Text_NaomiIntro::
    .string "I wonder if you are good enough\n"
    .string "for me?$"

VictoryRoad_1F_Text_NaomiDefeat::
    .string "I lost out…$"

VictoryRoad_1F_Text_NaomiPostBattle::
    .string "I never wanted to lose to anybody,\n"
    .string "especially to a younger kid…$"

VictoryRoad_1F_Text_RolandoIntro::
    .string "I can see you're good.\n"
    .string "Let me see exactly how good!$"

VictoryRoad_1F_Text_RolandoDefeat::
    .string "I had a chance…$"

VictoryRoad_1F_Text_RolandoPostBattle::
    .string "Tch!\n"
    .string "I concede, you are better than I!$"

