SevenIsland_TanobyRuins_Text_BrandonIntro:: @ 818CFFB
    .string "Do you know anything about this\n"
    .string "stone chamber?$"

SevenIsland_TanobyRuins_Text_BrandonDefeat:: @ 818D02A
    .string "That was uncalled for.\n"
    .string "You didn't have to be so rough.$"

SevenIsland_TanobyRuins_Text_BrandonPostBattle:: @ 818D061
    .string "The TANOBY RUINS date back at\n"
    .string "least 1,500 years.\p"
    .string "But it's a baffling mystery as to\n"
    .string "why it was built in the first place.$"

SevenIsland_TanobyRuins_Text_BenjaminIntro:: @ 818D0D9
    .string "A mystic POKéMON is said to sleep\n"
    .string "inside here.$"

SevenIsland_TanobyRuins_Text_BenjaminDefeat:: @ 818D108
    .string "I'm not much good in battle.$"

SevenIsland_TanobyRuins_Text_BenjaminPostBattle:: @ 818D125
    .string "I hear there are other ruins like\n"
    .string "the one here.\p"
    .string "Might they be the resting places\n"
    .string "of other mystic POKéMON?$"

SevenIsland_TanobyRuins_Text_EdnaIntro:: @ 818D18F
    .string "CLIFFORD is teaching me how to\n"
    .string "paint.$"

SevenIsland_TanobyRuins_Text_EdnaDefeat:: @ 818D1B5
    .string "We might get in trouble for being\n"
    .string "noisy here.$"

SevenIsland_TanobyRuins_Text_EdnaPostBattle:: @ 818D1E3
    .string "I said that I wanted to paint an\n"
    .string "old building.\p"
    .string "So CLIFFORD brought me here.$"

SevenIsland_TanobyRuins_Text_CliffordIntro:: @ 818D22F
    .string "Today, in addition to our lesson,\n"
    .string "we came to see the chamber.$"

SevenIsland_TanobyRuins_Text_CliffordDefeat:: @ 818D26D
    .string "My, how extraordinary.$"

SevenIsland_TanobyRuins_Text_CliffordPostBattle:: @ 818D284
    .string "Ah, so you are studying POKéMON\n"
    .string "on your own…\p"
    .string "Yes, you certainly are quite the\n"
    .string "extraordinary person, indeed.$"
