CeruleanCity_House1_Text_AnyInterestInBerries::
.string "Preparo todo tipo de medicinas\n"
.string "con {SHADOW DYNAMIC_COLOR4}POLVO DE BAYAS{SHADOW LIGHT_GRAY}.\p"
.string "Usando buen {SHADOW DYNAMIC_COLOR4}POLVO DE BAYAS{SHADOW LIGHT_GRAY}, puedo\n"
.string "hacer cualquier medicina.\p"
.string "Ahora dime, ¿tienes algún interés\n"
.string "en las {SHADOW DYNAMIC_COLOR4}BAYAS{SHADOW LIGHT_GRAY}?$"

CeruleanCity_House1_Text_HaveJustTheThing::
.string "¡Ah, bien! Entonces tengo justo\n"
.string "lo que necesitas.$"

CeruleanCity_House1_Text_GoCrushBerriesAtDirectCorner::
.string "Hay algo nuevo en el segundo piso\n"
.string "de los CENTROS POKéMON, en la\l"
.string "ESQUINA DIRECTA.\p"
.string "Instalaron una máquina con\n"
.string "Adaptador Inalámbrico para triturar BAYAS.\p"
.string "Aquí es donde entras tú.\p"
.string "Tengo un favor que pedirte, uno que\n"
.string "solo puedo confiarte a ti.\p"
.string "¿Podrías hacer POLVO DE BAYAS para\n"
.string "mí usando esa máquina?\p"
.string "No lo olvides, la máquina está en la\n"
.string "ESQUINA DIRECTA de los CENTROS POKéMON.\p"
.string "Prepararé medicina para ti si\n"
.string "me traes algo de POLVO DE BAYAS.\p"
.string "No lo olvides, tritura BAYAS para\n"
.string "hacer POLVO DE BAYAS y tráemelo.$"

CeruleanCity_House1_Text_WhyMustYouLieNoBerries::
.string "¿Por qué me mientes?\p"
.string "¿Cuántas {SHADOW DYNAMIC_COLOR4}BAYAS{SHADOW LIGHT_GRAY} tienes?\n"
.string "¡Ni una!$"

CeruleanCity_House1_Text_TakeInterestInAllSortsOfThings::
.string "¿No tienes interés en las {SHADOW DYNAMIC_COLOR4}BAYAS{SHADOW LIGHT_GRAY}?\p"
.string "Jovencit{OA}, es importante interesarse\n"
.string "en todo tipo de cosas.$"

CeruleanCity_House1_Text_HaveYouBroughtBerryPowder::
.string "¡Ejem! ¿Me trajiste algo de\n"
.string "POLVO DE BAYAS?$"

CeruleanCity_House5_Text_ExchangeWithWhat::
.string "¿Por qué te gustaría\n"
.string "cambiarlo?$"

CeruleanCity_House1_Text_YoullExchangeBerryPowderForItem::
.string "Bien, ¿cambiarás tu POLVO DE BAYAS\n"
.string "por un {STR_VAR_1}?$"

CeruleanCity_House1_Text_DontHaveEnoughBerryPowder::
.string "¿Eh? No tienes suficiente\n"
.string "POLVO DE BAYAS.$"

CeruleanCity_House1_Text_TradeMoreBerryPowder::
.string "Este POLVO DE BAYAS es excelente.\n"
.string "Haré una medicina magnífica.\p"
.string "¿Quieres cambiar más POLVO DE BAYAS\n"
.string "por algo más?$"

CeruleanCity_House1_Text_HopeToSeeYouAgain::
.string "Está bien, entonces.\n"
.string "Espero verte de nuevo.$"

CeruleanCity_House1_Text_SeeMeIfYoudLikeToTradePowder::
.string "Ven a verme si quieres cambiar\n"
.string "tu POLVO DE BAYAS.$"

