# 1 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"

# 2 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
Route2_ViridianForest_NorthEntrance_MapScripts::
# 3 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
	.byte 0
# 4 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"

# 5 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
Route2_ViridianForest_NorthEntrance_EventScript_Youngster::
# 6 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
	msgbox Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests, MSGBOX_NPC
# 7 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
	end
# 8 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"

# 9 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
Route2_ViridianForest_NorthEntrance_EventScript_OldMan::
# 10 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees, MSGBOX_NPC
# 11 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
	end
# 12 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"

# 13 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
Route2_ViridianForest_NorthEntrance_EventScript_CooltrainerF::
# 14 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution, MSGBOX_NPC
# 15 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
	end
