Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
    .string "Muchos {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} sólo viven\n"
    .string "en bosques y cuevas.\p"
    .string "¡Tienes que mirar por todas partes\n"
    .string "para conseguirlos todos!$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
    .string "¿Has visto los arbustos junto al\n"
    .string "camino?\p"
    .string "Puedes cortarlos con un\n"
    .string "{SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
    .string "¿Sabías que puedes cancelar la\n"
    .string "evolución de un {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}?\p"
    .string "Cuando un {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} esté\n"
    .string "evolucionando, puedes detenerlo y\l"
    .string "dejarlo como está.$"
