gUnknown_819D85C:: @ 819D85C
    .string "Many POKéMON live only in forests \n"
    .string "and caves.\p"
    .string "You need to be persistent and look\n"
    .string "everywhere to get different kinds.$"

gUnknown_819D8D0:: @ 819D8D0
    .string "Have you noticed the skinny trees\n"
    .string "on the roadside?\p"
    .string "They can be cut down by a special\n"
    .string "POKéMON move, I hear.$"

gUnknown_819D93B:: @ 819D93B
    .string "Do you know the evolution-cancel\n"
    .string "technique?\p"
    .string "When a POKéMON is evolving, you\n"
    .string "can stop the process.\p"
    .string "It's a technique for raising\n"
    .string "POKéMON the way they are.$"

