[DIFFICULTY_NORMAL] =
{
    [TRAINER_PLAYER_LEAF] =
    {
        [TRAINER_SLIDE_BEFORE_FIRST_TURN] = COMPOUND_STRING("Trainer A: This message plays before the first turn.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_PLAYER_LANDS_FIRST_CRITICAL_HIT] = COMPOUND_STRING("Trainer A: This message plays after the player lands their first critical hit.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_ENEMY_LANDS_FIRST_CRITICAL_HIT] = COMPOUND_STRING("Trainer A: This message plays after the enemy lands their first critical hit.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_PLAYER_LANDS_FIRST_SUPER_EFFECTIVE_HIT] = COMPOUND_STRING("Trainer A: This message plays after the player lands their first super effective hit.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_PLAYER_LANDS_FIRST_DOWN] = COMPOUND_STRING("Trainer A: This message plays after the player KOs one enemy mon.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_ENEMY_MON_UNAFFECTED] = COMPOUND_STRING("Trainer A: Player attacked enemy with ineffective move.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_PLAYER_LANDS_FIRST_STAB_MOVE] = COMPOUND_STRING("Trainer A: Player lands their first STAB move.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_LAST_SWITCHIN] = COMPOUND_STRING("Trainer A: This message plays after the enemy switches in their last Pokemon.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_LAST_HALF_HP] = COMPOUND_STRING("Trainer A: Enemy last Mon has < 51% HP.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_LAST_LOW_HP] = COMPOUND_STRING("Trainer A: Enemy last Mon has < 26% HP.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_MEGA_EVOLUTION] = COMPOUND_STRING("Trainer A: This message plays before the enemy activates the Mega Evolution gimmick.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_Z_MOVE] = COMPOUND_STRING("Trainer A: This message plays before the enemy activates the Z-Move gimmick.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_DYNAMAX] = COMPOUND_STRING("Trainer A: This message plays before the enemy activates the Dynamax gimmick.{PAUSE_UNTIL_PRESS}"),
    },
    [TRAINER_PLAYER_RED] =
    {
        [TRAINER_SLIDE_BEFORE_FIRST_TURN] = COMPOUND_STRING("Trainer B: This message plays before the first turn.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_PLAYER_LANDS_FIRST_CRITICAL_HIT] = COMPOUND_STRING("Trainer B: This message plays after the player lands their first critical hit.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_ENEMY_LANDS_FIRST_CRITICAL_HIT] = COMPOUND_STRING("Trainer B: This message plays after the enemy lands their first critical hit.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_PLAYER_LANDS_FIRST_SUPER_EFFECTIVE_HIT] = COMPOUND_STRING("Trainer B: This message plays after the player lands their first super effective hit.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_PLAYER_LANDS_FIRST_DOWN] = COMPOUND_STRING("Trainer B: This message plays after the player KOs one enemy mon.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_ENEMY_MON_UNAFFECTED] = COMPOUND_STRING("Trainer B: Player attacked enemy with ineffective move.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_PLAYER_LANDS_FIRST_STAB_MOVE] = COMPOUND_STRING("Trainer B: Player lands their first STAB move.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_LAST_SWITCHIN] = COMPOUND_STRING("Trainer B: This message plays after the enemy switches in their last Pokemon.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_LAST_HALF_HP] = COMPOUND_STRING("Trainer B: Enemy last Mon has < 51% HP.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_LAST_LOW_HP] = COMPOUND_STRING("Trainer B: Enemy last Mon has < 26% HP.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_MEGA_EVOLUTION] = COMPOUND_STRING("Trainer B: This message plays before the enemy activates the Mega Evolution gimmick.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_Z_MOVE] = COMPOUND_STRING("Trainer B: This message plays before the enemy activates the Z-Move gimmick.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_DYNAMAX] = COMPOUND_STRING("Trainer B: This message plays before the enemy activates the Dynamax gimmick.{PAUSE_UNTIL_PRESS}"),
    },
    [TRAINER_PARTNER(PARTNER_STEVEN)] =
    {
        [TRAINER_SLIDE_BEFORE_FIRST_TURN] = COMPOUND_STRING("Trainer Partner: This message plays before the first turn.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_PLAYER_LANDS_FIRST_CRITICAL_HIT] = COMPOUND_STRING("Trainer Partner: This message plays after the player lands their first critical hit.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_ENEMY_LANDS_FIRST_CRITICAL_HIT] = COMPOUND_STRING("Trainer Partner: This message plays after the enemy lands their first critical hit.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_PLAYER_LANDS_FIRST_SUPER_EFFECTIVE_HIT] = COMPOUND_STRING("Trainer Partner: This message plays after the player lands their first super effective hit.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_PLAYER_LANDS_FIRST_DOWN] = COMPOUND_STRING("Trainer Partner: This message plays after the player KOs one enemy mon.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_ENEMY_MON_UNAFFECTED] = COMPOUND_STRING("Trainer Partner: Player attacked enemy with ineffective move.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_PLAYER_LANDS_FIRST_STAB_MOVE] = COMPOUND_STRING("Trainer Partner: Player lands their first STAB move.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_LAST_SWITCHIN] = COMPOUND_STRING("Trainer Partner: This message plays after the enemy switches in their last Pokemon.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_LAST_HALF_HP] = COMPOUND_STRING("Trainer Partner: Enemy last Mon has < 51% HP.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_LAST_LOW_HP] = COMPOUND_STRING("Trainer Partner: Enemy last Mon has < 26% HP.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_MEGA_EVOLUTION] = COMPOUND_STRING("Trainer Partner: This message plays before the enemy activates the Mega Evolution gimmick.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_Z_MOVE] = COMPOUND_STRING("Trainer Partner: This message plays before the enemy activates the Z-Move gimmick.{PAUSE_UNTIL_PRESS}"),
        [TRAINER_SLIDE_DYNAMAX] = COMPOUND_STRING("Trainer Partner: This message plays before the enemy activates the Dynamax gimmick.{PAUSE_UNTIL_PRESS}"),
    },
},

