Text_187E40:: @ 8187E40
    .string "The water is shallow here.\n"
    .string "There are many people swimming.$"

Text_187E7B:: @ 8187E7B
    .string "Splash!$"

Text_187E83:: @ 8187E83
    .string "I wish I could ride my POKéMON.\n"
    .string "I bet you're not tired.$"

Text_187EBB:: @ 8187EBB
    .string "SEAFOAM is a quiet getaway.\n"
    .string "I'm vacationing here.$"

Text_187EED:: @ 8187EED
    .string "Quit it!$"

Text_187EF6:: @ 8187EF6
    .string "There's a huge cavern underneath\n"
    .string "this island.$"

Text_187F24:: @ 8187F24
    .string "I love floating with the fishes\n"
    .string "here among the waves.$"

Text_187F5A:: @ 8187F5A
    .string "Yowch!$"

Text_187F61:: @ 8187F61
    .string "Want to float with me?$"

Text_187F78:: @ 8187F78
    .string "Are you on vacation, too?$"

Text_187F92:: @ 8187F92
    .string "No mercy at all!$"

Text_187FA3:: @ 8187FA3
    .string "SEAFOAM used to be a single island\n"
    .string "in the distant past.$"

Text_187FDB:: @ 8187FDB
    .string "Check out my buff physique!$"

Text_187FF7:: @ 8187FF7
    .string "Wimpy!$"

Text_187FFE:: @ 8187FFE
    .string "I should've been buffing up my\n"
    .string "POKéMON, not me!$"

Text_18802E:: @ 818802E
    .string "Why are you riding a POKéMON?\n"
    .string "Can't you swim?$"

Text_18805C:: @ 818805C
    .string "Ouch!\n"
    .string "Torpedoed!$"

Text_18806D:: @ 818806D
    .string "Riding a POKéMON sure looks fun!$"

Text_18808E:: @ 818808E
    .string "I rode my bird POKéMON here.$"

Text_1880AB:: @ 81880AB
    .string "Oh, no!\n"
    .string "Now what am I to do?$"

Text_1880C8:: @ 81880C8
    .string "My birds are exhausted.\n"
    .string "They can't FLY me back!$"

Text_1880F8:: @ 81880F8
    .string "My boyfriend gave me big pearls.$"

Text_188119:: @ 8188119
    .string "Oh, no!\n"
    .string "My pearls were in them!$"

Text_188139:: @ 8188139
    .string "Will my pearls grow bigger inside\n"
    .string "CLOYSTER?$"

Text_188165:: @ 8188165
    .string "I swam here from CINNABAR ISLAND.\n"
    .string "It wasn't easy, I tell you.$"

Text_1881A3:: @ 81881A3
    .string "I'm so disappointed!$"

Text_1881B8:: @ 81881B8
    .string "POKéMON have taken over an\n"
    .string "abandoned mansion on CINNABAR.\p"
    .string "They call it the POKéMON MANSION\n"
    .string "now.$"

Text_188218:: @ 8188218
    .string "CINNABAR, in the west, has a LAB\n"
    .string "for POKéMON.\p"
    .string "My daddy works there.$"

Text_18825C:: @ 818825C
    .string "Wait!\n"
    .string "You're supposed to wait!$"

Text_18827B:: @ 818827B
    .string "CINNABAR is a volcanic island.\p"
    .string "I heard it rose out of the sea\n"
    .string "when a volcano erupted.$"

gUnknown_81882D1:: @ 81882D1
    .string "SEAFOAM ISLANDS$"

Text_1882E1:: @ 81882E1
    .string "Strong TRAINERS and WATER POKéMON\n"
    .string "are common sights in these parts.\p"
    .string "They say that MISTY of the\n"
    .string "CERULEAN GYM trains here.$"
