PalletTown_PlayersHouse_1F_Layout:: @ 82D5200
    .incbin "baserom.gba", 0x2D5200, 0xFC

PalletTown_PlayersHouse_2F_Layout:: @ 82D52FC
    .incbin "baserom.gba", 0x2D52FC, 0x128

PalletTown_GarysHouse_Layout:: @ 82D5424
    .incbin "baserom.gba", 0x2D5424, 0xB4

UnusedLayout_82D54D8_Layout:: @ 82D54D8
    .incbin "baserom.gba", 0x2D54D8, 0x190

PalletTown_ProfessorOaksLab_Layout:: @ 82D5668
    .incbin "baserom.gba", 0x2D5668, 0xEC

House1_Layout:: @ shared
    .incbin "baserom.gba", 0x2D5754, 0xEC

House2_Layout:: @ shared
    .incbin "baserom.gba", 0x2D5840, 0x150

PokemonCenter_1F_Layout:: @ shared
    .incbin "baserom.gba", 0x2D5990, 0x150

PokemonCenter_2F_Layout:: @ shared
    .incbin "baserom.gba", 0x2D5AE0, 0xEC

Mart_Layout:: @ shared
    .incbin "baserom.gba", 0x2D5BCC, 0xEC

House3_Layout:: @ shared
    .incbin "baserom.gba", 0x2D5CB8, 0x2CC

CeruleanCity_Gym_Layout:: @ 82D5F84
    .incbin "baserom.gba", 0x2D5F84, 0xEC

House4_Layout:: @ shared
    .incbin "baserom.gba", 0x2D6070, 0xD4

UnusedLayout_82D6144_Layout:: @ 82D6144
    .incbin "baserom.gba", 0x2D6144, 0x22C

CeladonCity_Gym_Layout:: @ 82D6370
    .incbin "baserom.gba", 0x2D6370, 0x120

UnusedLayout_82D6490_Layout:: @ 82D6490
    .incbin "baserom.gba", 0x2D6490, 0xEC

FiveIsland_ResortGorgeous_House_Layout:: @ 82D657C
    .incbin "baserom.gba", 0x2D657C, 0xD8

UnusedLayout_82D6654_Layout:: @ 82D6654
    .incbin "baserom.gba", 0x2D6654, 0xD8

UnusedLayout_82D672C_Layout:: @ 82D672C
    .incbin "baserom.gba", 0x2D672C, 0x2D8

FuchsiaCity_Gym_Layout:: @ 82D6A04
    .incbin "baserom.gba", 0x2D6A04, 0xEC

House5_Layout:: @ shared
    .incbin "baserom.gba", 0x2D6AF0, 0x144

UnusedLayout_82D6C34_Layout:: @ 82D6C34
    .incbin "baserom.gba", 0x2D6C34, 0x1F4

VermilionCity_Gym_Layout:: @ 82D6E28
    .incbin "baserom.gba", 0x2D6E28, 0x100

CeruleanCity_BikeShop_Layout:: @ 82D6F28
    .incbin "baserom.gba", 0x2D6F28, 0x240

CeladonCity_GameCorner_Layout:: @ 82D7168
    .incbin "baserom.gba", 0x2D7168, 0x1C4

PewterCity_Gym_Layout:: @ 82D732C
    .incbin "baserom.gba", 0x2D732C, 0xEC

FourIsland_LoreleisHouse_Layout:: @ 82D7418
    .incbin "baserom.gba", 0x2D7418, 0xEC

ThreeIsland_House1_Layout:: @ 82D7504
    .incbin "baserom.gba", 0x2D7504, 0xEC

UnusedLayout_82D75F0_Layout:: @ 82D75F0
    .incbin "baserom.gba", 0x2D75F0, 0x84

UnusedLayout_82D7674_Layout:: @ 82D7674
    .incbin "baserom.gba", 0x2D7674, 0x5D0

SaffronCity_Gym_Layout:: @ 82D7C44
    .incbin "baserom.gba", 0x2D7C44, 0x84

UnusedLayout_82D7CC8_Layout:: @ 82D7CC8
    .incbin "baserom.gba", 0x2D7CC8, 0x600

CinnabarIsland_Gym_Layout:: @ 82D82C8
    .incbin "baserom.gba", 0x2D82C8, 0x3E4

ViridianCity_Gym_Layout:: @ 82D86AC
    .incbin "baserom.gba", 0x2D86AC, 0x21C

UnusedLayout_82D88C8_Layout:: @ 82D88C8
    .incbin "baserom.gba", 0x2D88C8, 0x120

UnknownMap_00_00_Layout:: @ 82D89E8
    .incbin "baserom.gba", 0x2D89E8, 0xFC

UnknownMap_00_01_Layout:: @ 82D8AE4
    .incbin "baserom.gba", 0x2D8AE4, 0x1B4

UnknownMap_00_02_Layout:: @ 82D8C98
    .incbin "baserom.gba", 0x2D8C98, 0x120

UnknownMap_00_03_Layout:: @ 82D8DB8
    .incbin "baserom.gba", 0x2D8DB8, 0xC8

FuchsiaCity_SafariZone_Entrance_Layout:: @ 82D8E80
    .incbin "baserom.gba", 0x2D8E80, 0xCA4

UnusedLayout_82D9B24_Layout:: @ 82D9B24
    .incbin "baserom.gba", 0x2D9B24, 0xCA4

UnusedLayout_82DA7C8_Layout:: @ 82DA7C8
    .incbin "baserom.gba", 0x2DA7C8, 0xCA4

UnusedLayout_82DB46C_Layout:: @ 82DB46C
	.incbin "baserom.gba", 0x2DB46C, 0x84

UnusedLayout_82DB4F0_Layout:: @ 82DB4F0
	.incbin "baserom.gba", 0x2DB4F0, 0x6F0

UnusedLayout_82DBBE0_Layout:: @ 82DBBE0
	.incbin "baserom.gba", 0x2DBBE0, 0x1F8

UnusedLayout_82DBDD8_Layout:: @ 82DBDD8
	.incbin "baserom.gba", 0x2DBDD8, 0x1E0

UnusedLayout_82DBFB8_Layout:: @ 82DBFB8
	.incbin "baserom.gba", 0x2DBFB8, 0x534

UnusedLayout_82DC4EC_Layout:: @ 82DC4EC
	.incbin "baserom.gba", 0x2DC4EC, 0x120

UnusedLayout_82DC60C_Layout:: @ 82DC60C
	.incbin "baserom.gba", 0x2DC60C, 0x120

UnusedLayout_82DC72C_Layout:: @ 82DC72C
	.incbin "baserom.gba", 0x2DC72C, 0x120

UnusedLayout_82DC84C_Layout:: @ 82DC84C
	.incbin "baserom.gba", 0x2DC84C, 0x224

UnusedLayout_82DCA70_Layout:: @ 82DCA70
	.incbin "baserom.gba", 0x2DCA70, 0xD4

UnusedLayout_82DCB44_Layout:: @ 82DCB44
	.incbin "baserom.gba", 0x2DCB44, 0xFC

UnusedLayout_82DCC40_Layout:: @ 82DCC40
	.incbin "baserom.gba", 0x2DCC40, 0x94

UnusedLayout_82DCCD4_Layout:: @ 82DCCD4
	.incbin "baserom.gba", 0x2DCCD4, 0x94

UnusedLayout_82DCD68_Layout:: @ 82DCD68
	.incbin "baserom.gba", 0x2DCD68, 0x94

UnusedLayout_82DCDFC_Layout:: @ 82DCDFC
	.incbin "baserom.gba", 0x2DCDFC, 0x104

UnusedLayout_82DCF00_Layout:: @ 82DCF00
	.incbin "baserom.gba", 0x2DCF00, 0x104

UnusedLayout_82DD004_Layout:: @ 82DD004
	.incbin "baserom.gba", 0x2DD004, 0xD8

UnusedLayout_82DD0DC_Layout:: @ 82DD0DC
	.incbin "baserom.gba", 0x2DD0DC, 0x3E4

PalletTown_Layout:: @ 82DD4C0
    .incbin "baserom.gba", 0x2DD4C0, 0xF24

ViridianCity_Layout:: @ 82DE3E4
    .incbin "baserom.gba", 0x2DE3E4, 0xF24

PewterCity_Layout:: @ 82DF308
    .incbin "baserom.gba", 0x2DF308, 0xF24

CeruleanCity_Layout:: @ 82E022C
    .incbin "baserom.gba", 0x2E022C, 0x3E4

LavenderTown_Layout:: @ 82E0610
    .incbin "baserom.gba", 0x2E0610, 0xF24

VermilionCity_Layout:: @ 82E1534
    .incbin "baserom.gba", 0x2E1534, 0x12E4

CeladonCity_Layout:: @ 82E2818
    .incbin "baserom.gba", 0x2E2818, 0xF24

FuchsiaCity_Layout:: @ 82E373C
    .incbin "baserom.gba", 0x2E373C, 0x3E4

CinnabarIsland_Layout:: @ 82E3B20
    .incbin "baserom.gba", 0x2E3B20, 0x3E4

IndigoPlateau_Exterior_Layout:: @ 82E3F04
    .incbin "baserom.gba", 0x2E3F04, 0xF24

SaffronCity_Layout:: @ 82E4E28
    .incbin "baserom.gba", 0x2E4E28, 0x7A4

Route1_Layout:: @ shared
    .incbin "baserom.gba", 0x2E55CC, 0xF24

Route2_Layout:: @ 82E64F0
    .incbin "baserom.gba", 0x2E64F0, 0xD44

Route3_Layout:: @ 82E7234
    .incbin "baserom.gba", 0x2E7234, 0x1104

Route4_Layout:: @ 82E8338
    .incbin "baserom.gba", 0x2E8338, 0xF24

Route5_Layout:: @ 82E925C
    .incbin "baserom.gba", 0x2E925C, 0x7A4

Route6_Layout:: @ 82E9A00
    .incbin "baserom.gba", 0x2E9A00, 0x3E4

Route7_Layout:: @ 82E9DE4
    .incbin "baserom.gba", 0x2E9DE4, 0xB64

Route8_Layout:: @ 82EA948
    .incbin "baserom.gba", 0x2EA948, 0xB64

Route9_Layout:: @ 82EB4AC
    .incbin "baserom.gba", 0x2EB4AC, 0xF24

Route10_Layout:: @ 82EC3D0
    .incbin "baserom.gba", 0x2EC3D0, 0xB64

Route11_Layout:: @ 82ECF34
    .incbin "baserom.gba", 0x2ECF34, 0x16A4

Route12_Layout:: @ 82EE5D8
    .incbin "baserom.gba", 0x2EE5D8, 0xB64

Route13_Layout:: @ 82EF13C
    .incbin "baserom.gba", 0x2EF13C, 0xB64

Route14_Layout:: @ 82EFCA0
    .incbin "baserom.gba", 0x2EFCA0, 0xB64

Route15_Layout:: @ 82F0804
    .incbin "baserom.gba", 0x2F0804, 0x7A4

Route16_Layout:: @ 82F0FA8
    .incbin "baserom.gba", 0x2F0FA8, 0x1E24

Route17_Layout:: @ 82F2DCC
    .incbin "baserom.gba", 0x2F2DCC, 0x984

Route18_Layout:: @ 82F3750
    .incbin "baserom.gba", 0x2F3750, 0xB64

Route19_Layout:: @ 82F42B4
    .incbin "baserom.gba", 0x2F42B4, 0x12E4

Route20_Layout:: @ 82F5598
    .incbin "baserom.gba", 0x2F5598, 0x984

Route21_North_Layout:: @ 82F5F1C
    .incbin "baserom.gba", 0x2F5F1C, 0x924

Route22_Layout:: @ 82F6840
    .incbin "baserom.gba", 0x2F6840, 0x1E24

Route23_Layout:: @ 82F8664
    .incbin "baserom.gba", 0x2F8664, 0x7A4

Route24_Layout:: @ 82F8E08
    .incbin "baserom.gba", 0x2F8E08, 0xB64

Route25_Layout:: @ 82F996C
    .incbin "baserom.gba", 0x2F996C, 0xF24

MtMoon_1F_Layout:: @ 82FA890
    .incbin "baserom.gba", 0x2FA890, 0xF74

MtMoon_B1F_Layout:: @ 82FB804
    .incbin "baserom.gba", 0x2FB804, 0xF24

MtMoon_B2F_Layout:: @ 82FC728
    .incbin "baserom.gba", 0x2FC728, 0x1D44

ViridianForest_Layout:: @ 82FE46C
    .incbin "baserom.gba", 0x2FE46C, 0x11A4

SSAnne_Exterior_Layout:: @ 82FF610
    .incbin "baserom.gba", 0x2FF610, 0x53C

SSAnne_1F_Corridor_Layout:: @ 82FFB4C
    .incbin "baserom.gba", 0x2FFB4C, 0x464

SSAnne_2F_Corridor_Layout:: @ 82FFFB0
    .incbin "baserom.gba", 0x2FFFB0, 0x158

SSAnne_3F_Corridor_Layout:: @ 8300108
    .incbin "baserom.gba", 0x300108, 0x168

SSAnne_B1F_Corridor_Layout:: @ 8300270
    .incbin "baserom.gba", 0x300270, 0x3B4

SSAnne_Deck_Layout:: @ 8300624
    .incbin "baserom.gba", 0x300624, 0x3544

DiglettsCave_B1F_Layout:: @ 8303B68
    .incbin "baserom.gba", 0x303B68, 0x864

VictoryRoad_1F_Layout:: @ 83043CC
    .incbin "baserom.gba", 0x3043CC, 0x8E8

VictoryRoad_2F_Layout:: @ 8304CB4
    .incbin "baserom.gba", 0x304CB4, 0x7E0

VictoryRoad_3F_Layout:: @ 8305494
    .incbin "baserom.gba", 0x305494, 0x794

RocketHideout_B1F_Layout:: @ 8305C28
    .incbin "baserom.gba", 0x305C28, 0x5A4

RocketHideout_B2F_Layout:: @ 83061CC
    .incbin "baserom.gba", 0x3061CC, 0x4C8

RocketHideout_B3F_Layout:: @ 8306694
    .incbin "baserom.gba", 0x306694, 0x504

RocketHideout_B4F_Layout:: @ 8306B98
    .incbin "baserom.gba", 0x306B98, 0x654

SilphCo_1F_Layout:: @ 83071EC
    .incbin "baserom.gba", 0x3071EC, 0x654

SilphCo_2F_Layout:: @ 8307840
    .incbin "baserom.gba", 0x307840, 0x654

SilphCo_3F_Layout:: @ 8307E94
    .incbin "baserom.gba", 0x307E94, 0x654

SilphCo_4F_Layout:: @ 83084E8
    .incbin "baserom.gba", 0x3084E8, 0x654

SilphCo_5F_Layout:: @ 8308B3C
    .incbin "baserom.gba", 0x308B3C, 0x4C0

SilphCo_6F_Layout:: @ 8308FFC
    .incbin "baserom.gba", 0x308FFC, 0x4C0

SilphCo_7F_Layout:: @ 83094BC
    .incbin "baserom.gba", 0x3094BC, 0x4C0

SilphCo_8F_Layout:: @ 830997C
    .incbin "baserom.gba", 0x30997C, 0x4C0

SilphCo_9F_Layout:: @ 8309E3C
    .incbin "baserom.gba", 0x309E3C, 0x2AC

SilphCo_10F_Layout:: @ 830A0E8
    .incbin "baserom.gba", 0x30A0E8, 0x2CC

SilphCo_11F_Layout:: @ 830A3B4
    .incbin "baserom.gba", 0x30A3B4, 0xA88

PokemonMansion_1F_Layout:: @ 830AE3C
    .incbin "baserom.gba", 0x30AE3C, 0xB6C

PokemonMansion_2F_Layout:: @ 830B9A8
    .incbin "baserom.gba", 0x30B9A8, 0xA88

PokemonMansion_3F_Layout:: @ 830C430
    .incbin "baserom.gba", 0x30C430, 0xA88

PokemonMansion_B1F_Layout:: @ 830CEB8
    .incbin "baserom.gba", 0x30CEB8, 0xE80

SafariZone_Center_Layout:: @ 830DD38
    .incbin "baserom.gba", 0x30DD38, 0xEEC

SafariZone_East_Layout:: @ 830EC24
    .incbin "baserom.gba", 0x30EC24, 0x11F8

SafariZone_North_Layout:: @ 830FE1C
    .incbin "baserom.gba", 0x30FE1C, 0xDA8

SafariZone_West_Layout:: @ 8310BC4
    .incbin "baserom.gba", 0x310BC4, 0x754

CeruleanCave_1F_Layout:: @ 8311318
    .incbin "baserom.gba", 0x311318, 0x754

CeruleanCave_2F_Layout:: @ 8311A6C
    .incbin "baserom.gba", 0x311A6C, 0x754

CeruleanCave_B1F_Layout:: @ 83121C0
    .incbin "baserom.gba", 0x3121C0, 0xF24

RockTunnel_1F_Layout:: @ 83130E4
    .incbin "baserom.gba", 0x3130E4, 0xF24

RockTunnel_B1F_Layout:: @ 8314008
    .incbin "baserom.gba", 0x314008, 0x744

SeafoamIslands_1F_Layout:: @ 831474C
    .incbin "baserom.gba", 0x31474C, 0x6F8

SeafoamIslands_B1F_Layout:: @ 8314E44
    .incbin "baserom.gba", 0x314E44, 0x744

SeafoamIslands_B2F_Layout:: @ 8315588
    .incbin "baserom.gba", 0x315588, 0x744

SeafoamIslands_B3F_Layout:: @ 8315CCC
    .incbin "baserom.gba", 0x315CCC, 0x744

SeafoamIslands_B4F_Layout:: @ 8316410
    .incbin "baserom.gba", 0x316410, 0x3E4

PokemonTower_1F_Layout:: @ 83167F4
    .incbin "baserom.gba", 0x3167F4, 0x3E4

PokemonTower_2F_Layout:: @ 8316BD8
    .incbin "baserom.gba", 0x316BD8, 0x3E4

PokemonTower_3F_Layout:: @ 8316FBC
    .incbin "baserom.gba", 0x316FBC, 0x3E4

PokemonTower_4F_Layout:: @ 83173A0
    .incbin "baserom.gba", 0x3173A0, 0x3E4

PokemonTower_5F_Layout:: @ 8317784
    .incbin "baserom.gba", 0x317784, 0x3E4

PokemonTower_6F_Layout:: @ 8317B68
    .incbin "baserom.gba", 0x317B68, 0x3E4

PokemonTower_7F_Layout:: @ 8317F4C
    .incbin "baserom.gba", 0x317F4C, 0xF74

PowerPlant_Layout:: @ 8318EC0
    .incbin "baserom.gba", 0x318EC0, 0x170

Route25_SeaCottage_Layout:: @ 8319030
    .incbin "baserom.gba", 0x319030, 0x1E4

SSAnne_Kitchen_Layout:: @ 8319214
    .incbin "baserom.gba", 0x319214, 0xD8

SSAnne_CaptainsOffice_Layout:: @ 83192EC
    .incbin "baserom.gba", 0x3192EC, 0x128

UndergroundPath_Entrance_Layout:: @ shared
    .incbin "baserom.gba", 0x319414, 0x484

UndergroundPath_EastWestTunnel_Layout:: @ 8319898
    .incbin "baserom.gba", 0x319898, 0x414

UndergroundPath_NorthSouthTunnel_Layout:: @ 8319CAC
    .incbin "baserom.gba", 0x319CAC, 0x144

Route12_NorthEntrance_1F_Layout:: @ 8319DF0
    .incbin "baserom.gba", 0x319DF0, 0x84

SSAnne_Room1_Layout:: @ shared
    .incbin "baserom.gba", 0x319E74, 0x90

SSAnne_Room2_Layout:: @ shared
    .incbin "baserom.gba", 0x319F04, 0x6C

CeladonCity_DepartmentStore_Elevator_Layout:: @ 8319F70
    .incbin "baserom.gba", 0x319F70, 0x28C

PewterCity_Museum_1F_Layout:: @ 831A1FC
    .incbin "baserom.gba", 0x31A1FC, 0x1A0

PewterCity_Museum_2F_Layout:: @ 831A39C
    .incbin "baserom.gba", 0x31A39C, 0xD8

CeruleanCity_House2_Layout:: @ 831A474
    .incbin "baserom.gba", 0x31A474, 0xEC

CeruleanCity_House1_Layout:: @ 831A560
    .incbin "baserom.gba", 0x31A560, 0x27C

CeladonCity_Condominiums_1F_Layout:: @ 831A7DC
    .incbin "baserom.gba", 0x31A7DC, 0x27C

CeladonCity_Condominiums_2F_Layout:: @ 831AA58
    .incbin "baserom.gba", 0x31AA58, 0x27C

CeladonCity_Condominiums_3F_Layout:: @ 831ACD4
    .incbin "baserom.gba", 0x31ACD4, 0x2A8

CeladonCity_Condominiums_Roof_Layout:: @ 831AF7C
    .incbin "baserom.gba", 0x31AF7C, 0xD8

CeladonCity_Condominiums_RoofRoom_Layout:: @ 831B054
    .incbin "baserom.gba", 0x31B054, 0xD8

CeladonCity_GameCorner_PrizeRoom_Layout:: @ 831B12C
    .incbin "baserom.gba", 0x31B12C, 0x170

CeladonCity_Restaurant_Layout:: @ 831B29C
    .incbin "baserom.gba", 0x31B29C, 0x19C

CeladonCity_Hotel_Layout:: @ 831B438
    .incbin "baserom.gba", 0x31B438, 0x1C4

CeladonCity_DepartmentStore_1F_Layout:: @ 831B5FC
    .incbin "baserom.gba", 0x31B5FC, 0x1AC

CeladonCity_DepartmentStore_2F_Layout:: @ 831B7A8
    .incbin "baserom.gba", 0x31B7A8, 0x1AC

CeladonCity_DepartmentStore_3F_Layout:: @ 831B954
    .incbin "baserom.gba", 0x31B954, 0x1AC

CeladonCity_DepartmentStore_4F_Layout:: @ 831BB00
    .incbin "baserom.gba", 0x31BB00, 0x1AC

CeladonCity_DepartmentStore_5F_Layout:: @ 831BCAC
    .incbin "baserom.gba", 0x31BCAC, 0x238

CeladonCity_DepartmentStore_Roof_Layout:: @ 831BEE4
    .incbin "baserom.gba", 0x31BEE4, 0x144

SafariZone_Building_Layout:: @ shared
    .incbin "baserom.gba", 0x31C028, 0x144

SafariZone_SecretHouse_Layout:: @ 831C16C
    .incbin "baserom.gba", 0x31C16C, 0x1DC

FuchsiaCity_ZooBuilding_Layout:: @ 831C348
    .incbin "baserom.gba", 0x31C348, 0x144

FuchsiaCity_Building1_Layout:: @ 831C48C
    .incbin "baserom.gba", 0x31C48C, 0xEC

FuchsiaCity_House2_Layout:: @ 831C578
    .incbin "baserom.gba", 0x31C578, 0x28C

CinnabarIsland_PokemonLab_Entrance_Layout:: @ 831C804
    .incbin "baserom.gba", 0x31C804, 0x170

CinnabarIsland_PokemonLab_Lounge_Layout:: @ 831C974
    .incbin "baserom.gba", 0x31C974, 0x170

CinnabarIsland_PokemonLab_ResearchRoom_Layout:: @ 831CAE4
    .incbin "baserom.gba", 0x31CAE4, 0x170

CinnabarIsland_PokemonLab_ExperimentRoom_Layout:: @ 831CC54
    .incbin "baserom.gba", 0x31CC54, 0x1C80

SaffronCity_Duplicate_Layout:: @ 831E8D4
    .incbin "baserom.gba", 0x31E8D4, 0xEC

SaffronCity_NorthSouthEntrance_Layout:: @ shared
    .incbin "baserom.gba", 0x31E9C0, 0x110

SaffronCity_EastWestEntrance_Layout:: @ shared
    .incbin "baserom.gba", 0x31EAD0, 0xC4

DiglettsCave_NorthEntrance_Layout:: @ 831EB94
    .incbin "baserom.gba", 0x31EB94, 0xC4

DiglettsCave_SouthEntrance_Layout:: @ 831EC58
    .incbin "baserom.gba", 0x31EC58, 0x3A8

IndigoPlateau_PokemonCenter_1F_Layout:: @ 831F000
    .incbin "baserom.gba", 0x31F000, 0x178

PokemonLeague_LoreleisRoom_Layout:: @ 831F178
    .incbin "baserom.gba", 0x31F178, 0x178

PokemonLeague_BrunosRoom_Layout:: @ 831F2F0
    .incbin "baserom.gba", 0x31F2F0, 0x178

PokemonLeague_AgathasRoom_Layout:: @ 831F468
    .incbin "baserom.gba", 0x31F468, 0x564

PokemonLeague_LancesRoom_Layout:: @ 831F9CC
    .incbin "baserom.gba", 0x31F9CC, 0x22C

PokemonLeague_ChampionsRoom_Layout:: @ 831FBF8
    .incbin "baserom.gba", 0x31FBF8, 0x144

PokemonLeague_HallOfFame_Layout:: @ 831FD3C
    .incbin "baserom.gba", 0x31FD3C, 0x984

Route21_South_Layout:: @ 83206C0
    .incbin "baserom.gba", 0x3206C0, 0x144

Entrance_2F_Layout:: @ shared
    .incbin "baserom.gba", 0x320804, 0x18C

Route2_Entrance_Layout:: @ shared
    .incbin "baserom.gba", 0x320990, 0x18C

Route22_NorthEntrance_Layout:: @ 8320B1C
    .incbin "baserom.gba", 0x320B1C, 0x1F8

Route16_NorthEntrance_1F_Layout:: @ 8320D14
    .incbin "baserom.gba", 0x320D14, 0x15C

Entrance_1F_Layout:: @ shared
    .incbin "baserom.gba", 0x320E70, 0x6C

RocketHideout_Elevator_Layout:: @ 8320EDC
    .incbin "baserom.gba", 0x320EDC, 0x128

SaffronCity_House1_1F_Layout:: @ 8321004
    .incbin "baserom.gba", 0x321004, 0xFC

SaffronCity_House1_2F_Layout:: @ 8321100
    .incbin "baserom.gba", 0x321100, 0x1C4

SaffronCity_Dojo_Layout:: @ 83212C4
    .incbin "baserom.gba", 0x3212C4, 0x6C

SilphCo_Elevator_Layout:: @ 8321330
    .incbin "baserom.gba", 0x321330, 0x3E4

OneIsland_Layout:: @ 8321714
    .incbin "baserom.gba", 0x321714, 0x7A4

TwoIsland_Layout:: @ 8321EB8
    .incbin "baserom.gba", 0x321EB8, 0x7A4

ThreeIsland_Layout:: @ 832265C
    .incbin "baserom.gba", 0x32265C, 0xF24

FourIsland_Layout:: @ 8323580
    .incbin "baserom.gba", 0x323580, 0x3E4

FiveIsland_Layout:: @ 8323964
    .incbin "baserom.gba", 0x323964, 0x3E4

SevenIsland_Layout:: @ 8323D48
    .incbin "baserom.gba", 0x323D48, 0x5C4

SixIsland_Layout:: @ 832430C
    .incbin "baserom.gba", 0x32430C, 0x1A64

OneIsland_KindleRoad_Layout:: @ 8325D70
    .incbin "baserom.gba", 0x325D70, 0x7A4

OneIsland_TreasureBeach_Layout:: @ 8326514
    .incbin "baserom.gba", 0x326514, 0x7A4

TwoIsland_CapeBrink_Layout:: @ 8326CB8
    .incbin "baserom.gba", 0x326CB8, 0xF24

ThreeIsland_BondBridge_Layout:: @ 8327BDC
    .incbin "baserom.gba", 0x327BDC, 0x7A4

ThreeIsland_Port_Layout:: @ 8328380
    .incbin "baserom.gba", 0x328380, 0x28

UnknownMap_03_50_Layout:: @ 83283A8
    .incbin "baserom.gba", 0x3283A8, 0x28

UnknownMap_03_51_Layout:: @ 83283D0
    .incbin "baserom.gba", 0x3283D0, 0xD44

UnknownMap_03_52_Layout:: @ 8329114
    .incbin "baserom.gba", 0x329114, 0xB64

UnknownMap_03_53_Layout:: @ 8329C78
    .incbin "baserom.gba", 0x329C78, 0xB64

FiveIsland_ResortGorgeous_Layout:: @ 832A7DC
    .incbin "baserom.gba", 0x32A7DC, 0xB64

FiveIsland_WaterLabyrinth_Layout:: @ 832B340
    .incbin "baserom.gba", 0x32B340, 0x7A4

FiveIsland_Meadow_Layout:: @ 832BAE4
    .incbin "baserom.gba", 0x32BAE4, 0xB64

FiveIsland_MemorialPillar_Layout:: @ 832C648
    .incbin "baserom.gba", 0x32C648, 0xF24

SixIsland_OutcastIsland_Layout:: @ 832D56C
    .incbin "baserom.gba", 0x32D56C, 0xB64

SixIsland_GreenPath_Layout:: @ 832E0D0
    .incbin "baserom.gba", 0x32E0D0, 0x12E4

SixIsland_WaterPath_Layout:: @ 832F3B4
    .incbin "baserom.gba", 0x32F3B4, 0xF24

SixIsland_RuinValley_Layout:: @ 83302D8
    .incbin "baserom.gba", 0x3302D8, 0x25A4

SevenIsland_TrainerTower_Layout:: @ 833287C
    .incbin "baserom.gba", 0x33287C, 0x7A4

SevenIsland_SevaultCanyon_Entrance_Layout:: @ 8333020
    .incbin "baserom.gba", 0x333020, 0xF24

SevenIsland_SevaultCanyon_Layout:: @ 8333F44
    .incbin "baserom.gba", 0x333F44, 0x16A4

SevenIsland_TanobyRuins_Layout:: @ 83355E8
	.incbin "baserom.gba", 0x3355E8, 0xB64

UnusedLayout_833614C_Layout:: @ 833614C
	.incbin "baserom.gba", 0x33614C, 0x16A4

UnusedLayout_83377F0_Layout:: @ 83377F0
	.incbin "baserom.gba", 0x3377F0, 0xB64

UnusedLayout_8338354_Layout:: @ 8338354
	.incbin "baserom.gba", 0x338354, 0x3E4

UnusedLayout_8338738_Layout:: @ 8338738
	.incbin "baserom.gba", 0x338738, 0x18C

UnknownMap_00_04_Layout:: @ 83388C4
    .incbin "baserom.gba", 0x3388C4, 0x19C

SaffronCity_PokemonTrainerFanClub_Layout:: @ 8338A60
	.incbin "baserom.gba", 0x338A60, 0xEC

UnusedLayout_8338B4C_Layout:: @ 8338B4C
	.incbin "baserom.gba", 0x338B4C, 0xFC

SevenIsland_House_Room2_Layout:: @ 8338C48
    .incbin "baserom.gba", 0x338C48, 0xD8

ViridianCity_House2_Layout:: @ 8338D20
	.incbin "baserom.gba", 0x338D20, 0x170

UnusedLayout_8338E90_Layout:: @ 8338E90
	.incbin "baserom.gba", 0x338E90, 0x19C

UnusedLayout_833902C_Layout:: @ 833902C
	.incbin "baserom.gba", 0x33902C, 0x264

MtEmber_RubyPath_B4F_Layout:: @ 8339290
    .incbin "baserom.gba", 0x339290, 0x1518

ThreeIsland_BerryForest_Layout:: @ 833A7A8
    .incbin "baserom.gba", 0x33A7A8, 0x1C8

OneIsland_PokemonCenter_1F_Layout:: @ 833A970
    .incbin "baserom.gba", 0x33A970, 0x114

TwoIsland_JoyfulGameCorner_Layout:: @ 833AA84
    .incbin "baserom.gba", 0x33AA84, 0x144

VermilionCity_PokemonFanClub_Layout:: @ 833ABC8
    .incbin "baserom.gba", 0x33ABC8, 0xFC

LavenderTown_VolunteerPokemonHouse_Layout:: @ 833ACC4
    .incbin "baserom.gba", 0x33ACC4, 0xFC

Route5_PokemonDayCare_Layout:: @ 833ADC0
    .incbin "baserom.gba", 0x33ADC0, 0xEC

ViridianCity_House1_Layout:: @ 833AEAC
    .incbin "baserom.gba", 0x33AEAC, 0xFC

FourIsland_PokemonDayCare_Layout:: @ 833AFA8
	.incbin "baserom.gba", 0x33AFA8, 0x744

UnusedLayout_833B6EC_Layout:: @ 833B6EC
	.incbin "baserom.gba", 0x33B6EC, 0x744

UnusedLayout_833BE30_Layout:: @ 833BE30
	.incbin "baserom.gba", 0x33BE30, 0x1830

MtEmber_Exterior_Layout:: @ 833D660
    .incbin "baserom.gba", 0x33D660, 0x368

MtEmber_Summit_Layout:: @ 833D9C8
    .incbin "baserom.gba", 0x33D9C8, 0x240

MtEmber_SummitPath_1F_Layout:: @ 833DC08
    .incbin "baserom.gba", 0x33DC08, 0x1164

MtEmber_SummitPath_2F_Layout:: @ 833ED6C
    .incbin "baserom.gba", 0x33ED6C, 0x170

MtEmber_SummitPath_3F_Layout:: @ 833EEDC
    .incbin "baserom.gba", 0x33EEDC, 0x428

SSAnne_Kitchen3_Layout:: @ 833F304
    .incbin "baserom.gba", 0x33F304, 0x220

MtEmber_RubyPath_B1F_Layout:: @ 833F524
    .incbin "baserom.gba", 0x33F524, 0x184

MtEmber_RubyPath_B2F_Layout:: @ 833F6A8
    .incbin "baserom.gba", 0x33F6A8, 0x5B8

MtEmber_RubyPath_B3F_Layout:: @ 833FC60
    .incbin "baserom.gba", 0x33FC60, 0x78

MtEmber_RubyPath_B1F_Stairs_Layout:: @ 833FCD8
    .incbin "baserom.gba", 0x33FCD8, 0x84

MtEmber_RubyPath_B2F_Stairs_Layout:: @ 833FD5C
    .incbin "baserom.gba", 0x33FD5C, 0x204

MtEmber_RubyPath_B5F_Layout:: @ 833FF60
    .incbin "baserom.gba", 0x33FF60, 0x644

SSAnne_CaptainsOffice4_Layout:: @ 83405A4
    .incbin "baserom.gba", 0x3405A4, 0x894

FourIsland_IcefallCave_Entrance_Layout:: @ 8340E38
    .incbin "baserom.gba", 0x340E38, 0x344

FourIsland_IcefallCave_1F_Layout:: @ 834117C
    .incbin "baserom.gba", 0x34117C, 0x3E4

SSAnne_CaptainsOffice2_Layout:: @ 8341560
    .incbin "baserom.gba", 0x341560, 0x538

SSAnne_CaptainsOffice3_Layout:: @ 8341A98
    .incbin "baserom.gba", 0x341A98, 0x2AC

SevenIsland_TrainerTower_Lobby_Layout:: @ 8341D44
    .incbin "baserom.gba", 0x341D44, 0x288

SevenIsland_TrainerTower_1F_Layout:: @ 8341FCC
    .incbin "baserom.gba", 0x341FCC, 0x288

SevenIsland_TrainerTower_2F_Layout:: @ 8342254
    .incbin "baserom.gba", 0x342254, 0x288

SevenIsland_TrainerTower_3F_Layout:: @ 83424DC
    .incbin "baserom.gba", 0x3424DC, 0x288

SevenIsland_TrainerTower_4F_Layout:: @ 8342764
    .incbin "baserom.gba", 0x342764, 0x288

SevenIsland_TrainerTower_5F_Layout:: @ 83429EC
    .incbin "baserom.gba", 0x3429EC, 0x288

SevenIsland_TrainerTower_6F_Layout:: @ 8342C74
    .incbin "baserom.gba", 0x342C74, 0x288

SevenIsland_TrainerTower_7F_Layout:: @ 8342EFC
    .incbin "baserom.gba", 0x342EFC, 0x288

SevenIsland_TrainerTower_8F_Layout:: @ 8343184
    .incbin "baserom.gba", 0x343184, 0x264

SevenIsland_TrainerTower_Roof_Layout:: @ 83433E8
    .incbin "baserom.gba", 0x3433E8, 0x6C

SevenIsland_TrainerTower_Elevator_Layout:: @ 8343454
    .incbin "baserom.gba", 0x343454, 0xEC

CeruleanCity_House5_Layout:: @ 8343540
    .incbin "baserom.gba", 0x343540, 0x184

SSAnne_CaptainsOffice5_Layout:: @ 83436C4
    .incbin "baserom.gba", 0x3436C4, 0x144

SixIsland_DottedHole_B1F_Layout:: @ 8343808
    .incbin "baserom.gba", 0x343808, 0x144

SixIsland_DottedHole_B2F_Layout:: @ 834394C
    .incbin "baserom.gba", 0x34394C, 0x144

SixIsland_DottedHole_B3F_Layout:: @ 8343A90
    .incbin "baserom.gba", 0x343A90, 0x144

SSAnne_CaptainsOffice9_Layout:: @ 8343BD4
    .incbin "baserom.gba", 0x343BD4, 0x204

SixIsland_DottedHole_SapphireRoom_Layout:: @ 8343DD8
    .incbin "baserom.gba", 0x343DD8, 0x1E0

Island_Harbor_Layout:: @ shared
    .incbin "baserom.gba", 0x343FB8, 0x150

OneIsland_PokemonCenter_2F_Layout:: @ 8344108
    .incbin "baserom.gba", 0x344108, 0xF28

SSAnne_1F_Room11_Layout:: @ 8345030
    .incbin "baserom.gba", 0x345030, 0x1C8

ThreeIsland_DunsparceTunnel_Layout:: @ 83451F8
	.incbin "baserom.gba", 0x3451F8, 0x1C8

UnusedLayout_83453C0_Layout:: @ 83453C0
	.incbin "baserom.gba", 0x3453C0, 0x118

FiveIsland_LostCave_Entrance_Layout:: @ 83454D8
    .incbin "baserom.gba", 0x3454D8, 0x118

FiveIsland_LostCave_Room1_Layout:: @ 83455F0
    .incbin "baserom.gba", 0x3455F0, 0x118

FiveIsland_LostCave_Room2_Layout:: @ 8345708
    .incbin "baserom.gba", 0x345708, 0x118

FiveIsland_LostCave_Room3_Layout:: @ 8345820
    .incbin "baserom.gba", 0x345820, 0x118

FiveIsland_LostCave_Room4_Layout:: @ 8345938
    .incbin "baserom.gba", 0x345938, 0x118

FiveIsland_LostCave_Room5_Layout:: @ 8345A50
    .incbin "baserom.gba", 0x345A50, 0x118

FiveIsland_LostCave_Room6_Layout:: @ 8345B68
    .incbin "baserom.gba", 0x345B68, 0x118

FiveIsland_LostCave_Room7_Layout:: @ 8345C80
    .incbin "baserom.gba", 0x345C80, 0x118

FiveIsland_LostCave_Room8_Layout:: @ 8345D98
    .incbin "baserom.gba", 0x345D98, 0x118

FiveIsland_LostCave_Room9_Layout:: @ 8345EB0
    .incbin "baserom.gba", 0x345EB0, 0x118

FiveIsland_LostCave_Room10_Layout:: @ 8345FC8
    .incbin "baserom.gba", 0x345FC8, 0x118

FiveIsland_LostCave_Room11_Layout:: @ 83460E0
    .incbin "baserom.gba", 0x3460E0, 0x118

FiveIsland_LostCave_Room12_Layout:: @ 83461F8
    .incbin "baserom.gba", 0x3461F8, 0x118

FiveIsland_LostCave_Room13_Layout:: @ 8346310
    .incbin "baserom.gba", 0x346310, 0x118

FiveIsland_LostCave_Room14_Layout:: @ 8346428
    .incbin "baserom.gba", 0x346428, 0x334

SevenIsland_TanobyRuins_MoneanChamber_Layout:: @ 834675C
    .incbin "baserom.gba", 0x34675C, 0x334

SevenIsland_TanobyRuins_LiptooChamber_Layout:: @ 8346A90
    .incbin "baserom.gba", 0x346A90, 0x334

SevenIsland_TanobyRuins_WeepthChamber_Layout:: @ 8346DC4
    .incbin "baserom.gba", 0x346DC4, 0x334

SevenIsland_TanobyRuins_DilfordChamber_Layout:: @ 83470F8
    .incbin "baserom.gba", 0x3470F8, 0x334

SevenIsland_TanobyRuins_ScufibChamber_Layout:: @ 834742C
    .incbin "baserom.gba", 0x34742C, 0x624

SSAnne_1F_Room12_Layout:: @ 8347A50
    .incbin "baserom.gba", 0x347A50, 0x204

SevenIsland_SeavaultCanyon_TanobyKey_Layout:: @ 8347C54
    .incbin "baserom.gba", 0x347C54, 0x72C

BirthIsland_Exterior_Layout:: @ 8348380
    .incbin "baserom.gba", 0x348380, 0x3BC

NavelRock_Exterior_Layout:: @ 834873C
    .incbin "baserom.gba", 0x34873C, 0x398

NavelRock_1F_Layout:: @ 8348AD4
    .incbin "baserom.gba", 0x348AD4, 0x3DC

NavelRock_Summit_Layout:: @ 8348EB0
    .incbin "baserom.gba", 0x348EB0, 0x3EC

NavelRock_Base_Layout:: @ 834929C
    .incbin "baserom.gba", 0x34929C, 0x88

NavelRock_SummitPath_2F_Layout:: @ 8349324
    .incbin "baserom.gba", 0x349324, 0x88

NavelRock_SummitPath_3F_Layout:: @ 83493AC
    .incbin "baserom.gba", 0x3493AC, 0x88

NavelRock_SummitPath_4F_Layout:: @ 8349434
    .incbin "baserom.gba", 0x349434, 0x88

NavelRock_SummitPath_5F_Layout:: @ 83494BC
    .incbin "baserom.gba", 0x3494BC, 0x88

NavelRock_BasePath_B1F_Layout:: @ 8349544
    .incbin "baserom.gba", 0x349544, 0x88

NavelRock_BasePath_B2F_Layout:: @ 83495CC
    .incbin "baserom.gba", 0x3495CC, 0x88

NavelRock_BasePath_B3F_Layout:: @ 8349654
    .incbin "baserom.gba", 0x349654, 0x88

NavelRock_BasePath_B4F_Layout:: @ 83496DC
    .incbin "baserom.gba", 0x3496DC, 0x88

NavelRock_BasePath_B5F_Layout:: @ 8349764
    .incbin "baserom.gba", 0x349764, 0x88

NavelRock_BasePath_B6F_Layout:: @ 83497EC
    .incbin "baserom.gba", 0x3497EC, 0x88

NavelRock_BasePath_B7F_Layout:: @ 8349874
    .incbin "baserom.gba", 0x349874, 0x88

NavelRock_BasePath_B8F_Layout:: @ 83498FC
    .incbin "baserom.gba", 0x3498FC, 0x88

NavelRock_BasePath_B9F_Layout:: @ 8349984
    .incbin "baserom.gba", 0x349984, 0x88

NavelRock_BasePath_B10F_Layout:: @ 8349A0C
    .incbin "baserom.gba", 0x349A0C, 0x88

NavelRock_BasePath_B11F_Layout:: @ 8349A94
    .incbin "baserom.gba", 0x349A94, 0x334

SevenIsland_TanobyRuins_RixyChamber_Layout:: @ 8349DC8
    .incbin "baserom.gba", 0x349DC8, 0x334

SevenIsland_TanobyRuins_ViapoisChamber_Layout:: @ 834A0FC
    .incbin "baserom.gba", 0x34A0FC, 0x114

NavelRock_B1F_Layout:: @ 834A210
    .incbin "baserom.gba", 0x34A210, 0x1794

NavelRock_Fork_Layout:: @ 834B9A4
	.incbin "baserom.gba", 0x34B9A4, 0x288

UnusedLayout_834BC2C_Layout:: @ 834BC2C
	.incbin "baserom.gba", 0x34BC2C, 0x288

UnusedLayout_834BEB4_Layout:: @ 834BEB4
	.incbin "baserom.gba", 0x34BEB4, 0x288

UnusedLayout_834C13C_Layout:: @ 834C13C
	.incbin "baserom.gba", 0x34C13C, 0x288

UnusedLayout_834C3C4_Layout:: @ 834C3C4
	.incbin "baserom.gba", 0x34C3C4, 0x288

UnusedLayout_834C64C_Layout:: @ 834C64C
	.incbin "baserom.gba", 0x34C64C, 0x288

UnusedLayout_834C8D4_Layout:: @ 834C8D4
	.incbin "baserom.gba", 0x34C8D4, 0x288

UnusedLayout_834CB5C_Layout:: @ 834CB5C
	.incbin "baserom.gba", 0x34CB5C, 0x288

UnusedLayout_834CDE4_Layout:: @ 834CDE4
	.incbin "baserom.gba", 0x34CDE4, 0x288

UnusedLayout_834D06C_Layout:: @ 834D06C
	.incbin "baserom.gba", 0x34D06C, 0x288

UnusedLayout_834D2F4_Layout:: @ 834D2F4
	.incbin "baserom.gba", 0x34D2F4, 0x288

UnusedLayout_834D57C_Layout:: @ 834D57C
	.incbin "baserom.gba", 0x34D57C, 0x288

UnusedLayout_834D804_Layout:: @ 834D804
	.incbin "baserom.gba", 0x34D804, 0x288

UnusedLayout_834DA8C_Layout:: @ 834DA8C
	.incbin "baserom.gba", 0x34DA8C, 0x288

UnusedLayout_834DD14_Layout:: @ 834DD14
	.incbin "baserom.gba", 0x34DD14, 0x288

UnusedLayout_834DF9C_Layout:: @ 834DF9C
	.incbin "baserom.gba", 0x34DF9C, 0x288

UnusedLayout_834E224_Layout:: @ 834E224
	.incbin "baserom.gba", 0x34E224, 0xEC

SevenIsland_House_Room1_Layout:: @ 834E310
    .incbin "baserom.gba", 0x34E310, 0x860

OneIsland_KindleRoad_EmberSpa_Layout:: @ 834EB70
    .incbin "baserom.gba", 0x34EB70, 0x1C
