gUnknown_81733F8:: @ 81733F8
    .string "You, mon petit!\n"
    .string "We're busy here!\l"
    .string "Out of the way!$"

gUnknown_8173429:: @ 8173429
    .string "I saw an odd BERRY in the trash.\n"
    .string "I wonder what that was?$"

gUnknown_8173462:: @ 8173462
    .string "I'm so busy I'm getting dizzy!\n"
    .string "You have to give me room here!$"

gUnknown_81734A0:: @ 81734A0
    .string "Hum-de-hum-de-ho…\p"
    .string "I peel spuds every day!\n"
    .string "Hum-hum…$"

gUnknown_81734D3:: @ 81734D3
    .string "Did you hear about SNORLAX?\n"
    .string "It's a glutton.\p"
    .string "No other POKéMON eats and sleeps\n"
    .string "the way SNORLAX can and does!$"

gUnknown_817353E:: @ 817353E
    .string "Snivel… Sniff…\p"
    .string "I only get to peel onions…\n"
    .string "Snivel…$"

gUnknown_8173570:: @ 8173570
    .string "Er-hem!\n"
    .string "Indeed I am le CHEF!\p"
    .string "Le main course is$"

gUnknown_817359F:: @ 817359F
    .string "Salmon du Salad!\p"
    .string "Les guests may gripe it's fish\n"
    .string "again, however!$"

gUnknown_81735DF:: @ 81735DF
    .string "Eels au Barbecue!\p"
    .string "Les guests will mutiny, I fear.$"

gUnknown_8173611:: @ 8173611
    .string "Prime Beefsteak!\p"
    .string "But, have I enough fillets du\n"
    .string "beef?$"

