Text_175562:: @ 8175562
    .string "Help!\n"
    .string "I'm a SILPH employee.$"

Text_17557E:: @ 817557E
    .string "How did you know\n"
    .string "I was a ROCKET?$"

gUnknown_817559F:: @ 817559F
    .string "I work for both SILPH and TEAM\n"
    .string "ROCKET.$"

Text_1755C6:: @ 81755C6
    .string "It's off-limits here!\n"
    .string "Go home!$"

Text_1755E5:: @ 81755E5
    .string "You're good.$"

gUnknown_81755F2:: @ 81755F2
    .string "Can you solve the maze in here?\n"
    .string "It's not easy, I tell you!$"

Text_17562D:: @ 817562D
    .string "No kids are allowed in here!$"

Text_17564A:: @ 817564A
    .string "Tough!$"

gUnknown_8175651:: @ 8175651
    .string "Diamond-shaped tiles are teleport\n"
    .string "blocks.\p"
    .string "They're transporters for this\n"
    .string "high-tech building.$"

Text_1756AD:: @ 81756AD
    .string "Hey, kid!\n"
    .string "What are you wandering here for?$"

Text_1756D8:: @ 81756D8
    .string "I goofed!$"

gUnknown_81756E2:: @ 81756E2
    .string "SILPH CO. will be associated with\n"
    .string "TEAM ROCKET!$"

Text_175711:: @ 8175711
    .string "Eeek!\n"
    .string "No! Stop! Help!\p"
    .string "Oh, you're not with TEAM ROCKET.\n"
    .string "I'm sorry, I thought…\p"
    .string "Will you forgive me if I teach\n"
    .string "you the THUNDER WAVE technique?$"

Text_17579D:: @ 817579D
    .string "Oh…\n"
    .string "But THUNDER WAVE is convenient…$"

Text_1757C1:: @ 81757C1
    .string "Which POKéMON should I teach\n"
    .string "THUNDER WAVE?$"

Text_1757EC:: @ 81757EC
    .string "THUNDER WAVE causes paralysis in\n"
    .string "the target POKéMON.\p"
    .string "A paralyzed POKéMON may be unable\n"
    .string "to move in battle.\p"
    .string "It's an ELECTRIC-type move, so it\n"
    .string "won't work on some POKéMON.$"

gUnknown_8175894:: @ 8175894
    .string "SILPH CO. HEAD OFFICE\n"
    .string "2F$"

