Text_1884D4:: @ 81884D4
	.string "I caught my POKéMON at sea.$"

Text_1884F0:: @ 81884F0
	.string "Diver!!\n"
	.string "Down!!$"

Text_1884FF:: @ 81884FF
	.string "Where'd you catch your POKéMON?$"

Text_18851F:: @ 818851F
	.string "Right now, I'm in a triathlon meet.$"

Text_188543:: @ 8188543
	.string "Pant…\n"
	.string "Pant… Pant…$"

Text_188555:: @ 8188555
	.string "I'm beat! But, I still have the\n"
	.string "bike race and marathon left!$"

Text_188592:: @ 8188592
	.string "Ahh!\n"
	.string "Feel the sun and the wind!$"

Text_1885B2:: @ 81885B2
	.string "Yow!\n"
	.string "I lost!$"

Text_1885BF:: @ 81885BF
	.string "I'm sunburnt to a crisp!$"

Text_1885D8:: @ 81885D8
	.string "Hey, don't scare away the fish!$"

Text_1885F8:: @ 81885F8
	.string "Sorry! I'm just so frustrated from\n"
	.string "not catching anything.$"

Text_188632:: @ 8188632
	.string "Sheesh, I haven't caught a thing.\n"
	.string "Could this place actually be a\l"
	.string "giant pool or something?$"

Text_18868C:: @ 818868C
	.string "Keep me company till I get a hit.$"

Text_1886AE:: @ 81886AE
	.string "That burned some time.$"

Text_1886C5:: @ 81886C5
	.string "Oh wait!\n"
	.string "I got a bite! Yeah!$"

Text_1886E2:: @ 81886E2
	.string "LIL: Huh? A battle?\n"
	.string "IAN, can't you do it alone?$"

Text_188712:: @ 8188712
	.string "LIL: Oh, see?\n"
	.string "We lost. Happy now?$"

Text_188734:: @ 8188734
	.string "LIL: I'm tired.\n"
	.string "Can't we go home already?$"

Text_18875E:: @ 818875E
	.string "LIL: Huh? A battle?\n"
	.string "I can't be bothered to do it alone.\l"
	.string "Bring two POKéMON, won't you?$"

Text_1887B4:: @ 81887B4
	.string "IAN: My sis doesn't get enough\n"
	.string "exercise, so I made her come.$"

Text_1887F1:: @ 81887F1
	.string "IAN: Awww, Sis!\n"
	.string "Get it together!$"

Text_188812:: @ 8188812
	.string "IAN: Come on, Sis!\p"
	.string "You're not going to lose weight\n"
	.string "like this!$"

Text_188850:: @ 8188850
	.string "IAN: We want a two-on-two battle.\n"
	.string "So can you bring two POKéMON?$"
