Route21_South_Text_JackIntro:: @ 81884D4
	.string "I caught my POKéMON at sea.$"

Route21_South_Text_JackDefeat:: @ 81884F0
	.string "Diver!!\n"
	.string "Down!!$"

Route21_South_Text_JackPostBattle:: @ 81884FF
	.string "Where'd you catch your POKéMON?$"

Route21_South_Text_JeromeIntro:: @ 818851F
	.string "Right now, I'm in a triathlon meet.$"

Route21_South_Text_JeromeDefeat:: @ 8188543
	.string "Pant…\n"
	.string "Pant… Pant…$"

Route21_South_Text_JeromePostBattle:: @ 8188555
	.string "I'm beat! But, I still have the\n"
	.string "bike race and marathon left!$"

Route21_South_Text_RolandIntro:: @ 8188592
	.string "Ahh!\n"
	.string "Feel the sun and the wind!$"

Route21_South_Text_RolandDefeat:: @ 81885B2
	.string "Yow!\n"
	.string "I lost!$"

Route21_South_Text_RolandPostBattle:: @ 81885BF
	.string "I'm sunburnt to a crisp!$"

Route21_South_Text_ClaudeIntro:: @ 81885D8
	.string "Hey, don't scare away the fish!$"

Route21_South_Text_ClaudeDefeat:: @ 81885F8
	.string "Sorry! I'm just so frustrated from\n"
	.string "not catching anything.$"

Route21_South_Text_ClaudePostBattle:: @ 8188632
	.string "Sheesh, I haven't caught a thing.\n"
	.string "Could this place actually be a\l"
	.string "giant pool or something?$"

Route21_South_Text_NolanIntro:: @ 818868C
	.string "Keep me company till I get a hit.$"

Route21_South_Text_NolanDefeat:: @ 81886AE
	.string "That burned some time.$"

Route21_South_Text_NolanPostBattle:: @ 81886C5
	.string "Oh wait!\n"
	.string "I got a bite! Yeah!$"

Route21_North_Text_LilIntro:: @ 81886E2
	.string "LIL: Huh? A battle?\n"
	.string "IAN, can't you do it alone?$"

Route21_North_Text_LilDefeat:: @ 8188712
	.string "LIL: Oh, see?\n"
	.string "We lost. Happy now?$"

Route21_North_Text_LilPostBattle:: @ 8188734
	.string "LIL: I'm tired.\n"
	.string "Can't we go home already?$"

Route21_North_Text_LilNotEnoughMons:: @ 818875E
	.string "LIL: Huh? A battle?\n"
	.string "I can't be bothered to do it alone.\l"
	.string "Bring two POKéMON, won't you?$"

Route21_North_Text_IanIntro:: @ 81887B4
	.string "IAN: My sis doesn't get enough\n"
	.string "exercise, so I made her come.$"

Route21_North_Text_IanDefeat:: @ 81887F1
	.string "IAN: Awww, Sis!\n"
	.string "Get it together!$"

Route21_North_Text_IanPostBattle:: @ 8188812
	.string "IAN: Come on, Sis!\p"
	.string "You're not going to lose weight\n"
	.string "like this!$"

Route21_North_Text_IanNotEnoughMons:: @ 8188850
	.string "IAN: We want a two-on-two battle.\n"
	.string "So can you bring two POKéMON?$"
