#ifndef GUARD_BATTLE_STRING_IDS_H
#define GUARD_BATTLE_STRING_IDS_H

enum StringID
{
    STRINGID_INTROMSG,
    STRINGID_INTROSENDOUT,
    STRINGID_RETURNMON,
    STRINGID_SWITCHINMON,
    STRINGID_USEDMOVE,
    STRINGID_BATTLEEND,
    STRINGID_TRAINERSLIDE,
    STRINGID_TABLE_START, // Make sure to add new messages below this marker
    // todo: make some of those names less vague: attacker/target vs pkmn, etc.
    STRINGID_TRAINER1LOSETEXT,
    STRINGID_PKMNGAINEDEXP,
    STRINGID_PKMNGREWTOLV,
    STRINGID_PKMNLEARNEDMOVE,
    STRINGID_TRYTOLEARNMOVE1,
    STRINGID_TRYTOLEARNMOVE2,
    STRINGID_TRYTOLEARNMOVE3,
    STRINGID_PKMNFORGOTMOVE,
    STRINGID_STOPLEARNINGMOVE,
    STRINGID_DIDNOTLEARNMOVE,
    STRINGID_PKMNLEARNEDMOVE2,
    STRINGID_ATTACKMISSED,
    STRINGID_PKMNPROTECTEDITSELF,
    STRINGID_STATSWONTINCREASE2,
    STRINGID_AVOIDEDDAMAGE,
    STRINGID_ITDOESNTAFFECT,
    STRINGID_ATTACKERFAINTED,
    STRINGID_TARGETFAINTED,
    STRINGID_PLAYERGOTMONEY,
    STRINGID_PLAYERWHITEOUT,
    STRINGID_PLAYERWHITEOUT2,
    STRINGID_PREVENTSESCAPE,
    STRINGID_HITXTIMES,
    STRINGID_PKMNFELLASLEEP,
    STRINGID_PKMNMADESLEEP,
    STRINGID_PKMNALREADYASLEEP,
    STRINGID_PKMNALREADYASLEEP2,
    STRINGID_PKMNWASNTAFFECTED,
    STRINGID_PKMNWASPOISONED,
    STRINGID_PKMNPOISONEDBY,
    STRINGID_PKMNHURTBYPOISON,
    STRINGID_PKMNALREADYPOISONED,
    STRINGID_PKMNBADLYPOISONED,
    STRINGID_PKMNENERGYDRAINED,
    STRINGID_PKMNWASBURNED,
    STRINGID_PKMNBURNEDBY,
    STRINGID_PKMNHURTBYBURN,
    STRINGID_PKMNWASFROZEN,
    STRINGID_PKMNFROZENBY,
    STRINGID_PKMNISFROZEN,
    STRINGID_PKMNWASDEFROSTED,
    STRINGID_PKMNWASDEFROSTED2,
    STRINGID_PKMNWASDEFROSTEDBY,
    STRINGID_PKMNWASPARALYZED,
    STRINGID_PKMNWASPARALYZEDBY,
    STRINGID_PKMNISPARALYZED,
    STRINGID_PKMNISALREADYPARALYZED,
    STRINGID_PKMNHEALEDPARALYSIS,
    STRINGID_PKMNDREAMEATEN,
    STRINGID_STATSWONTINCREASE,
    STRINGID_STATSWONTDECREASE,
    STRINGID_TEAMSTOPPEDWORKING,
    STRINGID_FOESTOPPEDWORKING,
    STRINGID_PKMNISCONFUSED,
    STRINGID_PKMNHEALEDCONFUSION,
    STRINGID_PKMNWASCONFUSED,
    STRINGID_PKMNALREADYCONFUSED,
    STRINGID_PKMNFELLINLOVE,
    STRINGID_PKMNINLOVE,
    STRINGID_PKMNIMMOBILIZEDBYLOVE,
    STRINGID_PKMNBLOWNAWAY,
    STRINGID_PKMNCHANGEDTYPE,
    STRINGID_PKMNFLINCHED,
    STRINGID_PKMNREGAINEDHEALTH,
    STRINGID_PKMNHPFULL,
    STRINGID_PKMNRAISEDSPDEF,
    STRINGID_PKMNRAISEDDEF,
    STRINGID_PKMNCOVEREDBYVEIL,
    STRINGID_PKMNUSEDSAFEGUARD,
    STRINGID_PKMNSAFEGUARDEXPIRED,
    STRINGID_PKMNWENTTOSLEEP,
    STRINGID_PKMNSLEPTHEALTHY,
    STRINGID_PKMNWHIPPEDWHIRLWIND,
    STRINGID_PKMNTOOKSUNLIGHT,
    STRINGID_PKMNLOWEREDHEAD,
    STRINGID_PKMNISGLOWING,
    STRINGID_PKMNFLEWHIGH,
    STRINGID_PKMNDUGHOLE,
    STRINGID_PKMNSQUEEZEDBYBIND,
    STRINGID_PKMNTRAPPEDINVORTEX,
    STRINGID_PKMNWRAPPEDBY,
    STRINGID_PKMNCLAMPED,
    STRINGID_PKMNHURTBY,
    STRINGID_PKMNFREEDFROM,
    STRINGID_PKMNCRASHED,
    STRINGID_PKMNSHROUDEDINMIST,
    STRINGID_PKMNPROTECTEDBYMIST,
    STRINGID_PKMNGETTINGPUMPED,
    STRINGID_PKMNHITWITHRECOIL,
    STRINGID_PKMNPROTECTEDITSELF2,
    STRINGID_PKMNBUFFETEDBYSANDSTORM,
    STRINGID_PKMNPELTEDBYHAIL,
    STRINGID_PKMNSEEDED,
    STRINGID_PKMNEVADEDATTACK,
    STRINGID_PKMNSAPPEDBYLEECHSEED,
    STRINGID_PKMNFASTASLEEP,
    STRINGID_PKMNWOKEUP,
    STRINGID_PKMNUPROARKEPTAWAKE,
    STRINGID_PKMNWOKEUPINUPROAR,
    STRINGID_PKMNCAUSEDUPROAR,
    STRINGID_PKMNMAKINGUPROAR,
    STRINGID_PKMNCALMEDDOWN,
    STRINGID_PKMNCANTSLEEPINUPROAR,
    STRINGID_PKMNSTOCKPILED,
    STRINGID_PKMNCANTSTOCKPILE,
    STRINGID_PKMNCANTSLEEPINUPROAR2,
    STRINGID_UPROARKEPTPKMNAWAKE,
    STRINGID_PKMNSTAYEDAWAKEUSING,
    STRINGID_PKMNSTORINGENERGY,
    STRINGID_PKMNUNLEASHEDENERGY,
    STRINGID_PKMNFATIGUECONFUSION,
    STRINGID_PLAYERPICKEDUPMONEY,
    STRINGID_PKMNUNAFFECTED,
    STRINGID_PKMNTRANSFORMEDINTO,
    STRINGID_PKMNMADESUBSTITUTE,
    STRINGID_PKMNHASSUBSTITUTE,
    STRINGID_SUBSTITUTEDAMAGED,
    STRINGID_PKMNSUBSTITUTEFADED,
    STRINGID_PKMNMUSTRECHARGE,
    STRINGID_PKMNRAGEBUILDING,
    STRINGID_PKMNMOVEWASDISABLED,
    STRINGID_PKMNMOVEISDISABLED,
    STRINGID_PKMNMOVEDISABLEDNOMORE,
    STRINGID_PKMNGOTENCORE,
    STRINGID_PKMNENCOREENDED,
    STRINGID_PKMNTOOKAIM,
    STRINGID_PKMNSKETCHEDMOVE,
    STRINGID_PKMNTRYINGTOTAKEFOE,
    STRINGID_PKMNTOOKFOE,
    STRINGID_PKMNREDUCEDPP,
    STRINGID_PKMNSTOLEITEM,
    STRINGID_TARGETCANTESCAPENOW,
    STRINGID_PKMNFELLINTONIGHTMARE,
    STRINGID_PKMNLOCKEDINNIGHTMARE,
    STRINGID_PKMNLAIDCURSE,
    STRINGID_PKMNAFFLICTEDBYCURSE,
    STRINGID_SPIKESSCATTERED,
    STRINGID_PKMNHURTBYSPIKES,
    STRINGID_PKMNIDENTIFIED,
    STRINGID_PKMNPERISHCOUNTFELL,
    STRINGID_PKMNBRACEDITSELF,
    STRINGID_PKMNENDUREDHIT,
    STRINGID_MAGNITUDESTRENGTH,
    STRINGID_PKMNCUTHPMAXEDATTACK,
    STRINGID_PKMNCOPIEDSTATCHANGES,
    STRINGID_PKMNGOTFREE,
    STRINGID_PKMNSHEDLEECHSEED,
    STRINGID_PKMNBLEWAWAYSPIKES,
    STRINGID_PKMNFLEDFROMBATTLE,
    STRINGID_PKMNFORESAWATTACK,
    STRINGID_PKMNTOOKATTACK,
    STRINGID_PKMNATTACK,
    STRINGID_PKMNCENTERATTENTION,
    STRINGID_PKMNCHARGINGPOWER,
    STRINGID_NATUREPOWERTURNEDINTO,
    STRINGID_PKMNSTATUSNORMAL,
    STRINGID_PKMNHASNOMOVESLEFT,
    STRINGID_PKMNSUBJECTEDTOTORMENT,
    STRINGID_PKMNCANTUSEMOVETORMENT,
    STRINGID_PKMNTIGHTENINGFOCUS,
    STRINGID_PKMNFELLFORTAUNT,
    STRINGID_PKMNCANTUSEMOVETAUNT,
    STRINGID_PKMNREADYTOHELP,
    STRINGID_PKMNSWITCHEDITEMS,
    STRINGID_PKMNCOPIEDFOE,
    STRINGID_PKMNMADEWISH,
    STRINGID_PKMNWISHCAMETRUE,
    STRINGID_PKMNPLANTEDROOTS,
    STRINGID_PKMNABSORBEDNUTRIENTS,
    STRINGID_PKMNANCHOREDITSELF,
    STRINGID_PKMNWASMADEDROWSY,
    STRINGID_PKMNKNOCKEDOFF,
    STRINGID_PKMNSWAPPEDABILITIES,
    STRINGID_PKMNSEALEDOPPONENTMOVE,
    STRINGID_PKMNCANTUSEMOVESEALED,
    STRINGID_PKMNWANTSGRUDGE,
    STRINGID_PKMNLOSTPPGRUDGE,
    STRINGID_PKMNSHROUDEDITSELF,
    STRINGID_PKMNMOVEBOUNCED,
    STRINGID_PKMNWAITSFORTARGET,
    STRINGID_PKMNSNATCHEDMOVE,
    STRINGID_PKMNMADEITRAIN,
    STRINGID_PKMNRAISEDSPEED,
    STRINGID_PKMNPROTECTEDBY,
    STRINGID_PKMNPREVENTSUSAGE,
    STRINGID_PKMNRESTOREDHPUSING,
    STRINGID_PKMNCHANGEDTYPEWITH,
    STRINGID_PKMNPREVENTSPARALYSISWITH,
    STRINGID_PKMNPREVENTSROMANCEWITH,
    STRINGID_PKMNPREVENTSPOISONINGWITH,
    STRINGID_PKMNPREVENTSCONFUSIONWITH,
    STRINGID_PKMNRAISEDFIREPOWERWITH,
    STRINGID_PKMNANCHORSITSELFWITH,
    STRINGID_PKMNCUTSATTACKWITH,
    STRINGID_PKMNPREVENTSSTATLOSSWITH,
    STRINGID_PKMNHURTSWITH,
    STRINGID_PKMNTRACED,
    STRINGID_STATSHARPLY,
    STRINGID_STATROSE,
    STRINGID_STATHARSHLY,
    STRINGID_STATFELL,
    STRINGID_ATTACKERSSTATROSE,
    STRINGID_DEFENDERSSTATROSE,
    STRINGID_ATTACKERSSTATFELL,
    STRINGID_DEFENDERSSTATFELL,
    STRINGID_CRITICALHIT,
    STRINGID_ONEHITKO,
    STRINGID_123POOF,
    STRINGID_ANDELLIPSIS,
    STRINGID_NOTVERYEFFECTIVE,
    STRINGID_SUPEREFFECTIVE,
    STRINGID_GOTAWAYSAFELY,
    STRINGID_WILDPKMNFLED,
    STRINGID_NORUNNINGFROMTRAINERS,
    STRINGID_CANTESCAPE,
    STRINGID_DONTLEAVEBIRCH,
    STRINGID_BUTNOTHINGHAPPENED,
    STRINGID_BUTITFAILED,
    STRINGID_ITHURTCONFUSION,
    STRINGID_MIRRORMOVEFAILED,
    STRINGID_STARTEDTORAIN,
    STRINGID_DOWNPOURSTARTED,
    STRINGID_RAINCONTINUES,
    STRINGID_DOWNPOURCONTINUES,
    STRINGID_RAINSTOPPED,
    STRINGID_SANDSTORMBREWED,
    STRINGID_SANDSTORMRAGES,
    STRINGID_SANDSTORMSUBSIDED,
    STRINGID_SUNLIGHTGOTBRIGHT,
    STRINGID_SUNLIGHTSTRONG,
    STRINGID_SUNLIGHTFADED,
    STRINGID_STARTEDHAIL,
    STRINGID_HAILCONTINUES,
    STRINGID_HAILSTOPPED,
    STRINGID_FAILEDTOSPITUP,
    STRINGID_FAILEDTOSWALLOW,
    STRINGID_WINDBECAMEHEATWAVE,
    STRINGID_STATCHANGESGONE,
    STRINGID_COINSSCATTERED,
    STRINGID_TOOWEAKFORSUBSTITUTE,
    STRINGID_SHAREDPAIN,
    STRINGID_BELLCHIMED,
    STRINGID_FAINTINTHREE,
    STRINGID_NOPPLEFT,
    STRINGID_BUTNOPPLEFT,
    STRINGID_PLAYERUSEDITEM,
    STRINGID_WALLYUSEDITEM,
    STRINGID_TRAINERBLOCKEDBALL,
    STRINGID_DONTBEATHIEF,
    STRINGID_ITDODGEDBALL,
    STRINGID_YOUMISSEDPKMN,
    STRINGID_PKMNBROKEFREE,
    STRINGID_ITAPPEAREDCAUGHT,
    STRINGID_AARGHALMOSTHADIT,
    STRINGID_SHOOTSOCLOSE,
    STRINGID_GOTCHAPKMNCAUGHTPLAYER,
    STRINGID_GOTCHAPKMNCAUGHTWALLY,
    STRINGID_GIVENICKNAMECAPTURED,
    STRINGID_PKMNSENTTOPC,
    STRINGID_PKMNDATAADDEDTODEX,
    STRINGID_ITISRAINING,
    STRINGID_SANDSTORMISRAGING,
    STRINGID_CANTESCAPE2,
    STRINGID_PKMNIGNORESASLEEP,
    STRINGID_PKMNIGNOREDORDERS,
    STRINGID_PKMNBEGANTONAP,
    STRINGID_PKMNLOAFING,
    STRINGID_PKMNWONTOBEY,
    STRINGID_PKMNTURNEDAWAY,
    STRINGID_PKMNPRETENDNOTNOTICE,
    STRINGID_ENEMYABOUTTOSWITCHPKMN,
    STRINGID_CREPTCLOSER,
    STRINGID_CANTGETCLOSER,
    STRINGID_PKMNWATCHINGCAREFULLY,
    STRINGID_PKMNCURIOUSABOUTX,
    STRINGID_PKMNENTHRALLEDBYX,
    STRINGID_PKMNIGNOREDX,
    STRINGID_THREWPOKEBLOCKATPKMN,
    STRINGID_OUTOFSAFARIBALLS,
    STRINGID_PKMNSITEMCUREDPARALYSIS,
    STRINGID_PKMNSITEMCUREDPOISON,
    STRINGID_PKMNSITEMHEALEDBURN,
    STRINGID_PKMNSITEMDEFROSTEDIT,
    STRINGID_PKMNSITEMWOKEIT,
    STRINGID_PKMNSITEMSNAPPEDOUT,
    STRINGID_PKMNSITEMCUREDPROBLEM,
    STRINGID_PKMNSITEMRESTOREDHEALTH,
    STRINGID_PKMNSITEMRESTOREDPP,
    STRINGID_PKMNSITEMRESTOREDSTATUS,
    STRINGID_PKMNSITEMRESTOREDHPALITTLE,
    STRINGID_ITEMALLOWSONLYYMOVE,
    STRINGID_PKMNHUNGONWITHX,
    STRINGID_EMPTYSTRING3,
    STRINGID_PKMNSXPREVENTSBURNS,
    STRINGID_PKMNSXBLOCKSY,
    STRINGID_PKMNSXRESTOREDHPALITTLE2,
    STRINGID_PKMNSXWHIPPEDUPSANDSTORM,
    STRINGID_PKMNSXPREVENTSYLOSS,
    STRINGID_PKMNSXINFATUATEDY,
    STRINGID_PKMNSXMADEYINEFFECTIVE,
    STRINGID_PKMNSXCUREDYPROBLEM,
    STRINGID_ITSUCKEDLIQUIDOOZE,
    STRINGID_PKMNTRANSFORMED,
    STRINGID_ELECTRICITYWEAKENED,
    STRINGID_FIREWEAKENED,
    STRINGID_PKMNHIDUNDERWATER,
    STRINGID_PKMNSPRANGUP,
    STRINGID_HMMOVESCANTBEFORGOTTEN,
    STRINGID_XFOUNDONEY,
    STRINGID_PLAYERDEFEATEDTRAINER1,
    STRINGID_SOOTHINGAROMA,
    STRINGID_ITEMSCANTBEUSEDNOW,
    STRINGID_FORXCOMMAYZ,
    STRINGID_USINGITEMSTATOFPKMNROSE,
    STRINGID_PKMNUSEDXTOGETPUMPED,
    STRINGID_PKMNSXMADEYUSELESS,
    STRINGID_PKMNTRAPPEDBYSANDTOMB,
    STRINGID_EMPTYSTRING4,
    STRINGID_ABOOSTED,
    STRINGID_PKMNSXINTENSIFIEDSUN,
    STRINGID_PKMNMAKESGROUNDMISS,
    STRINGID_YOUTHROWABALLNOWRIGHT,
    STRINGID_PKMNSXTOOKATTACK,
    STRINGID_PKMNCHOSEXASDESTINY,
    STRINGID_PKMNLOSTFOCUS,
    STRINGID_USENEXTPKMN,
    STRINGID_PKMNFLEDUSINGITS,
    STRINGID_PKMNFLEDUSING,
    STRINGID_PKMNWASDRAGGEDOUT,
    STRINGID_PREVENTEDFROMWORKING,
    STRINGID_PKMNSITEMNORMALIZEDSTATUS,
    STRINGID_TRAINER1USEDITEM,
    STRINGID_BOXISFULL,
    STRINGID_PKMNAVOIDEDATTACK,
    STRINGID_PKMNSXMADEITINEFFECTIVE,
    STRINGID_PKMNSXPREVENTSFLINCHING,
    STRINGID_PKMNALREADYHASBURN,
    STRINGID_STATSWONTDECREASE2,
    STRINGID_PKMNSXBLOCKSY2,
    STRINGID_PKMNSXWOREOFF,
    STRINGID_PKMNRAISEDDEFALITTLE,
    STRINGID_PKMNRAISEDSPDEFALITTLE,
    STRINGID_THEWALLSHATTERED,
    STRINGID_PKMNSXPREVENTSYSZ,
    STRINGID_PKMNSXCUREDITSYPROBLEM,
    STRINGID_ATTACKERCANTESCAPE,
    STRINGID_PKMNOBTAINEDX,
    STRINGID_PKMNOBTAINEDX2,
    STRINGID_PKMNOBTAINEDXYOBTAINEDZ,
    STRINGID_BUTNOEFFECT,
    STRINGID_PKMNSXHADNOEFFECTONY,
    STRINGID_TWOENEMIESDEFEATED,
    STRINGID_TRAINER2LOSETEXT,
    STRINGID_PKMNINCAPABLEOFPOWER,
    STRINGID_GLINTAPPEARSINEYE,
    STRINGID_PKMNGETTINGINTOPOSITION,
    STRINGID_PKMNBEGANGROWLINGDEEPLY,
    STRINGID_PKMNEAGERFORMORE,
    STRINGID_DEFEATEDOPPONENTBYREFEREE,
    STRINGID_LOSTTOOPPONENTBYREFEREE,
    STRINGID_TIEDOPPONENTBYREFEREE,
    STRINGID_QUESTIONFORFEITMATCH,
    STRINGID_FORFEITEDMATCH,
    STRINGID_PKMNTRANSFERREDSOMEONESPC,
    STRINGID_PKMNTRANSFERREDLANETTESPC,
    STRINGID_PKMNBOXSOMEONESPCFULL,
    STRINGID_PKMNBOXLANETTESPCFULL,
    STRINGID_TRAINER1WINTEXT,
    STRINGID_TRAINER2WINTEXT,
    STRINGID_ENDUREDSTURDY,
    STRINGID_POWERHERB,
    STRINGID_HURTBYITEM,
    STRINGID_PSNBYITEM,
    STRINGID_BRNBYITEM,
    STRINGID_DEFABILITYIN,
    STRINGID_GRAVITYINTENSIFIED,
    STRINGID_TARGETIDENTIFIED,
    STRINGID_TARGETWOKEUP,
    STRINGID_PKMNSTOLEANDATEITEM,
    STRINGID_TAILWINDBLEW,
    STRINGID_PKMNWENTBACK,
    STRINGID_PKMNCANTUSEITEMSANYMORE,
    STRINGID_PKMNFLUNG,
    STRINGID_PKMNPREVENTEDFROMHEALING,
    STRINGID_PKMNSWITCHEDATKANDDEF,
    STRINGID_PKMNSABILITYSUPPRESSED,
    STRINGID_SHIELDEDFROMCRITICALHITS,
    STRINGID_SWITCHEDATKANDSPATK,
    STRINGID_SWITCHEDDEFANDSPDEF,
    STRINGID_PKMNACQUIREDABILITY,
    STRINGID_POISONSPIKESSCATTERED,
    STRINGID_PKMNSWITCHEDSTATCHANGES,
    STRINGID_PKMNSURROUNDEDWITHVEILOFWATER,
    STRINGID_PKMNLEVITATEDONELECTROMAGNETISM,
    STRINGID_PKMNTWISTEDDIMENSIONS,
    STRINGID_POINTEDSTONESFLOAT,
    STRINGID_CLOAKEDINMYSTICALMOONLIGHT,
    STRINGID_TRAPPEDBYSWIRLINGMAGMA,
    STRINGID_VANISHEDINSTANTLY,
    STRINGID_PROTECTEDTEAM,
    STRINGID_SHAREDITSGUARD,
    STRINGID_SHAREDITSPOWER,
    STRINGID_SWAPSDEFANDSPDEFOFALLPOKEMON,
    STRINGID_BECAMENIMBLE,
    STRINGID_HURLEDINTOTHEAIR,
    STRINGID_HELDITEMSLOSEEFFECTS,
    STRINGID_FELLSTRAIGHTDOWN,
    STRINGID_TARGETCHANGEDTYPE,
    STRINGID_PKMNACQUIREDSIMPLE,
    STRINGID_EMPTYSTRING5,
    STRINGID_KINDOFFER,
    STRINGID_RESETSTARGETSSTATLEVELS,
    STRINGID_EMPTYSTRING6,
    STRINGID_ALLYSWITCHPOSITION,
    STRINGID_RESTORETARGETSHEALTH,
    STRINGID_TOOKPJMNINTOTHESKY,
    STRINGID_FREEDFROMSKYDROP,
    STRINGID_POSTPONETARGETMOVE,
    STRINGID_REFLECTTARGETSTYPE,
    STRINGID_TRANSFERHELDITEM,
    STRINGID_EMBARGOENDS,
    STRINGID_ELECTROMAGNETISM,
    STRINGID_BUFFERENDS,
    STRINGID_TELEKINESISENDS,
    STRINGID_TAILWINDENDS,
    STRINGID_LUCKYCHANTENDS,
    STRINGID_TRICKROOMENDS,
    STRINGID_WONDERROOMENDS,
    STRINGID_MAGICROOMENDS,
    STRINGID_MUDSPORTENDS,
    STRINGID_WATERSPORTENDS,
    STRINGID_GRAVITYENDS,
    STRINGID_AQUARINGHEAL,
    STRINGID_ELECTRICTERRAINENDS,
    STRINGID_MISTYTERRAINENDS,
    STRINGID_PSYCHICTERRAINENDS,
    STRINGID_GRASSYTERRAINENDS,
    STRINGID_TARGETABILITYSTATRAISE,
    STRINGID_TARGETSSTATWASMAXEDOUT,
    STRINGID_ATTACKERABILITYSTATRAISE,
    STRINGID_POISONHEALHPUP,
    STRINGID_BADDREAMSDMG,
    STRINGID_MOLDBREAKERENTERS,
    STRINGID_TERAVOLTENTERS,
    STRINGID_TURBOBLAZEENTERS,
    STRINGID_SLOWSTARTENTERS,
    STRINGID_SLOWSTARTEND,
    STRINGID_SOLARPOWERHPDROP,
    STRINGID_AFTERMATHDMG,
    STRINGID_ANTICIPATIONACTIVATES,
    STRINGID_FOREWARNACTIVATES,
    STRINGID_ICEBODYHPGAIN,
    STRINGID_SNOWWARNINGHAIL,
    STRINGID_FRISKACTIVATES,
    STRINGID_UNNERVEENTERS,
    STRINGID_HARVESTBERRY,
    STRINGID_MAGICBOUNCEACTIVATES,
    STRINGID_PROTEANTYPECHANGE,
    STRINGID_SYMBIOSISITEMPASS,
    STRINGID_STEALTHROCKDMG,
    STRINGID_TOXICSPIKESABSORBED,
    STRINGID_TOXICSPIKESPOISONED,
    STRINGID_STICKYWEBSWITCHIN,
    STRINGID_HEALINGWISHCAMETRUE,
    STRINGID_HEALINGWISHHEALED,
    STRINGID_LUNARDANCECAMETRUE,
    STRINGID_CUSEDBODYDISABLED,
    STRINGID_ATTACKERACQUIREDABILITY,
    STRINGID_TARGETABILITYSTATLOWER,
    STRINGID_TARGETSTATWONTGOHIGHER,
    STRINGID_PKMNMOVEBOUNCEDABILITY,
    STRINGID_IMPOSTERTRANSFORM,
    STRINGID_ASSAULTVESTDOESNTALLOW,
    STRINGID_GRAVITYPREVENTSUSAGE,
    STRINGID_HEALBLOCKPREVENTSUSAGE,
    STRINGID_NOTDONEYET,
    STRINGID_STICKYWEBUSED,
    STRINGID_QUASHSUCCESS,
    STRINGID_PKMNBLEWAWAYTOXICSPIKES,
    STRINGID_PKMNBLEWAWAYSTICKYWEB,
    STRINGID_PKMNBLEWAWAYSTEALTHROCK,
    STRINGID_IONDELUGEON,
    STRINGID_TOPSYTURVYSWITCHEDSTATS,
    STRINGID_TERRAINBECOMESMISTY,
    STRINGID_TERRAINBECOMESGRASSY,
    STRINGID_TERRAINBECOMESELECTRIC,
    STRINGID_TERRAINBECOMESPSYCHIC,
    STRINGID_TARGETELECTRIFIED,
    STRINGID_MEGAEVOREACTING,
    STRINGID_MEGAEVOEVOLVED,
    STRINGID_DRASTICALLY,
    STRINGID_SEVERELY,
    STRINGID_INFESTATION,
    STRINGID_NOEFFECTONTARGET,
    STRINGID_BURSTINGFLAMESHIT,
    STRINGID_BESTOWITEMGIVING,
    STRINGID_THIRDTYPEADDED,
    STRINGID_FELLFORFEINT,
    STRINGID_POKEMONCANNOTUSEMOVE,
    STRINGID_COVEREDINPOWDER,
    STRINGID_POWDEREXPLODES,
    STRINGID_BELCHCANTSELECT,
    STRINGID_SPECTRALTHIEFSTEAL,
    STRINGID_GRAVITYGROUNDING,
    STRINGID_MISTYTERRAINPREVENTS,
    STRINGID_GRASSYTERRAINHEALS,
    STRINGID_ELECTRICTERRAINPREVENTS,
    STRINGID_PSYCHICTERRAINPREVENTS,
    STRINGID_SAFETYGOGGLESPROTECTED,
    STRINGID_FLOWERVEILPROTECTED,
    STRINGID_SWEETVEILPROTECTED,
    STRINGID_AROMAVEILPROTECTED,
    STRINGID_CELEBRATEMESSAGE,
    STRINGID_USEDINSTRUCTEDMOVE,
    STRINGID_THROATCHOPENDS,
    STRINGID_PKMNCANTUSEMOVETHROATCHOP,
    STRINGID_LASERFOCUS,
    STRINGID_GEMACTIVATES,
    STRINGID_BERRYDMGREDUCES,
    STRINGID_AIRBALLOONFLOAT,
    STRINGID_AIRBALLOONPOP,
    STRINGID_INCINERATEBURN,
    STRINGID_BUGBITE,
    STRINGID_ILLUSIONWOREOFF,
    STRINGID_ATTACKERCUREDTARGETSTATUS,
    STRINGID_ATTACKERLOSTFIRETYPE,
    STRINGID_HEALERCURE,
    STRINGID_SCRIPTINGABILITYSTATRAISE,
    STRINGID_RECEIVERABILITYTAKEOVER,
    STRINGID_PKNMABSORBINGPOWER,
    STRINGID_NOONEWILLBEABLETORUNAWAY,
    STRINGID_DESTINYKNOTACTIVATES,
    STRINGID_CLOAKEDINAFREEZINGLIGHT,
    STRINGID_CLEARAMULETWONTLOWERSTATS,
    STRINGID_FERVENTWISHREACHED,
    STRINGID_AIRLOCKACTIVATES,
    STRINGID_PRESSUREENTERS,
    STRINGID_DARKAURAENTERS,
    STRINGID_FAIRYAURAENTERS,
    STRINGID_AURABREAKENTERS,
    STRINGID_COMATOSEENTERS,
    STRINGID_SCREENCLEANERENTERS,
    STRINGID_FETCHEDPOKEBALL,
    STRINGID_BATTLERABILITYRAISEDSTAT,
    STRINGID_ASANDSTORMKICKEDUP,
    STRINGID_PKMNSWILLPERISHIN3TURNS,
    STRINGID_ABILITYRAISEDSTATDRASTICALLY,
    STRINGID_AURAFLAREDTOLIFE,
    STRINGID_ASONEENTERS,
    STRINGID_CURIOUSMEDICINEENTERS,
    STRINGID_CANACTFASTERTHANKSTO,
    STRINGID_MICLEBERRYACTIVATES,
    STRINGID_PKMNSHOOKOFFTHETAUNT,
    STRINGID_PKMNGOTOVERITSINFATUATION,
    STRINGID_ITEMCANNOTBEREMOVED,
    STRINGID_STICKYBARBTRANSFER,
    STRINGID_PKMNBURNHEALED,
    STRINGID_REDCARDACTIVATE,
    STRINGID_EJECTBUTTONACTIVATE,
    STRINGID_ATKGOTOVERINFATUATION,
    STRINGID_TORMENTEDNOMORE,
    STRINGID_HEALBLOCKEDNOMORE,
    STRINGID_ATTACKERBECAMEFULLYCHARGED,
    STRINGID_ATTACKERBECAMEASHSPECIES,
    STRINGID_EXTREMELYHARSHSUNLIGHT,
    STRINGID_EXTREMESUNLIGHTFADED,
    STRINGID_MOVEEVAPORATEDINTHEHARSHSUNLIGHT,
    STRINGID_EXTREMELYHARSHSUNLIGHTWASNOTLESSENED,
    STRINGID_HEAVYRAIN,
    STRINGID_HEAVYRAINLIFTED,
    STRINGID_MOVEFIZZLEDOUTINTHEHEAVYRAIN,
    STRINGID_NORELIEFROMHEAVYRAIN,
    STRINGID_MYSTERIOUSAIRCURRENT,
    STRINGID_STRONGWINDSDISSIPATED,
    STRINGID_MYSTERIOUSAIRCURRENTBLOWSON,
    STRINGID_ATTACKWEAKENEDBSTRONGWINDS,
    STRINGID_STUFFCHEEKSCANTSELECT,
    STRINGID_PKMNREVERTEDTOPRIMAL,
    STRINGID_BUTPOKEMONCANTUSETHEMOVE,
    STRINGID_BUTHOOPACANTUSEIT,
    STRINGID_BROKETHROUGHPROTECTION,
    STRINGID_ABILITYALLOWSONLYMOVE,
    STRINGID_SWAPPEDABILITIES,
    STRINGID_PASTELVEILPROTECTED,
    STRINGID_PASTELVEILENTERS,
    STRINGID_BATTLERTYPECHANGEDTO,
    STRINGID_BOTHCANNOLONGERESCAPE,
    STRINGID_CANTESCAPEDUETOUSEDMOVE,
    STRINGID_PKMNBECAMEWEAKERTOFIRE,
    STRINGID_ABOUTTOUSEPOLTERGEIST,
    STRINGID_CANTESCAPEBECAUSEOFCURRENTMOVE,
    STRINGID_NEUTRALIZINGGASENTERS,
    STRINGID_NEUTRALIZINGGASOVER,
    STRINGID_TARGETTOOHEAVY,
    STRINGID_PKMNTOOKTARGETHIGH,
    STRINGID_PKMNINSNAPTRAP,
    STRINGID_METEORBEAMCHARGING,
    STRINGID_HEATUPBEAK,
    STRINGID_COURTCHANGE,
    STRINGID_PLAYERLOSTTOENEMYTRAINER,
    STRINGID_PLAYERPAIDPRIZEMONEY,
    STRINGID_ZPOWERSURROUNDS,
    STRINGID_ZMOVEUNLEASHED,
    STRINGID_ZMOVERESETSSTATS,
    STRINGID_ZMOVEALLSTATSUP,
    STRINGID_ZMOVEZBOOSTCRIT,
    STRINGID_ZMOVERESTOREHP,
    STRINGID_ZMOVESTATUP,
    STRINGID_ZMOVEHPTRAP,
    STRINGID_ATTACKEREXPELLEDTHEPOISON,
    STRINGID_ATTACKERSHOOKITSELFAWAKE,
    STRINGID_ATTACKERBROKETHROUGHPARALYSIS,
    STRINGID_ATTACKERHEALEDITSBURN,
    STRINGID_ATTACKERMELTEDTHEICE,
    STRINGID_TARGETTOUGHEDITOUT,
    STRINGID_ATTACKERLOSTELECTRICTYPE,
    STRINGID_ATTACKERSWITCHEDSTATWITHTARGET,
    STRINGID_BEINGHITCHARGEDPKMNWITHPOWER,
    STRINGID_SUNLIGHTACTIVATEDABILITY,
    STRINGID_STATWASHEIGHTENED,
    STRINGID_ELECTRICTERRAINACTIVATEDABILITY,
    STRINGID_ABILITYWEAKENEDSURROUNDINGMONSSTAT,
    STRINGID_ATTACKERGAINEDSTRENGTHFROMTHEFALLEN,
    STRINGID_PKMNSABILITYPREVENTSABILITY,
    STRINGID_PREPARESHELLTRAP,
    STRINGID_SHELLTRAPDIDNTWORK,
    STRINGID_SPIKESDISAPPEAREDFROMTEAM,
    STRINGID_TOXICSPIKESDISAPPEAREDFROMTEAM,
    STRINGID_STICKYWEBDISAPPEAREDFROMTEAM,
    STRINGID_STEALTHROCKDISAPPEAREDFROMTEAM,
    STRINGID_COULDNTFULLYPROTECT,
    STRINGID_STOCKPILEDEFFECTWOREOFF,
    STRINGID_PKMNREVIVEDREADYTOFIGHT,
    STRINGID_ITEMRESTOREDSPECIESHEALTH,
    STRINGID_ITEMCUREDSPECIESSTATUS,
    STRINGID_ITEMRESTOREDSPECIESPP,
    STRINGID_THUNDERCAGETRAPPED,
    STRINGID_PKMNHURTBYFROSTBITE,
    STRINGID_PKMNGOTFROSTBITE,
    STRINGID_PKMNSITEMHEALEDFROSTBITE,
    STRINGID_ATTACKERHEALEDITSFROSTBITE,
    STRINGID_PKMNFROSTBITEHEALED,
    STRINGID_PKMNFROSTBITEHEALED2,
    STRINGID_PKMNFROSTBITEHEALEDBY,
    STRINGID_MIRRORHERBCOPIED,
    STRINGID_STARTEDSNOW,
    STRINGID_SNOWCONTINUES,
    STRINGID_SNOWSTOPPED,
    STRINGID_SNOWWARNINGSNOW,
    STRINGID_PKMNITEMMELTED,
    STRINGID_ULTRABURSTREACTING,
    STRINGID_ULTRABURSTCOMPLETED,
    STRINGID_TEAMGAINEDEXP,
    STRINGID_CURRENTMOVECANTSELECT,
    STRINGID_TARGETISBEINGSALTCURED,
    STRINGID_TARGETISHURTBYSALTCURE,
    STRINGID_TARGETCOVEREDINSTICKYCANDYSYRUP,
    STRINGID_SHARPSTEELFLOATS,
    STRINGID_SHARPSTEELDMG,
    STRINGID_PKMNBLEWAWAYSHARPSTEEL,
    STRINGID_SHARPSTEELDISAPPEAREDFROMTEAM,
    STRINGID_TEAMTRAPPEDWITHVINES,
    STRINGID_PKMNHURTBYVINES,
    STRINGID_TEAMCAUGHTINVORTEX,
    STRINGID_PKMNHURTBYVORTEX,
    STRINGID_TEAMSURROUNDEDBYFIRE,
    STRINGID_PKMNBURNINGUP,
    STRINGID_TEAMSURROUNDEDBYROCKS,
    STRINGID_PKMNHURTBYROCKSTHROWN,
    STRINGID_MOVEBLOCKEDBYDYNAMAX,
    STRINGID_ZEROTOHEROTRANSFORMATION,
    STRINGID_THETWOMOVESBECOMEONE,
    STRINGID_ARAINBOWAPPEAREDONSIDE,
    STRINGID_THERAINBOWDISAPPEARED,
    STRINGID_WAITINGFORPARTNERSMOVE,
    STRINGID_SEAOFFIREENVELOPEDSIDE,
    STRINGID_HURTBYTHESEAOFFIRE,
    STRINGID_THESEAOFFIREDISAPPEARED,
    STRINGID_SWAMPENVELOPEDSIDE,
    STRINGID_THESWAMPDISAPPEARED,
    STRINGID_PKMNTELLCHILLINGRECEPTIONJOKE,
    STRINGID_HOSPITALITYRESTORATION,
    STRINGID_ELECTROSHOTCHARGING,
    STRINGID_ITEMWASUSEDUP,
    STRINGID_ATTACKERLOSTITSTYPE,
    STRINGID_SHEDITSTAIL,
    STRINGID_CLOAKEDINAHARSHLIGHT,
    STRINGID_SUPERSWEETAROMAWAFTS,
    STRINGID_DIMENSIONSWERETWISTED,
    STRINGID_BIZARREARENACREATED,
    STRINGID_BIZARREAREACREATED,
    STRINGID_TIDYINGUPCOMPLETE,
    STRINGID_PKMNTERASTALLIZEDINTO,
    STRINGID_BOOSTERENERGYACTIVATES,
    STRINGID_FOGCREPTUP,
    STRINGID_FOGISDEEP,
    STRINGID_FOGLIFTED,
    STRINGID_PKMNMADESHELLGLEAM,
    STRINGID_FICKLEBEAMDOUBLED,
    STRINGID_COMMANDERACTIVATES,
    STRINGID_POKEFLUTECATCHY,
    STRINGID_POKEFLUTE,
    STRINGID_MONHEARINGFLUTEAWOKE,
    STRINGID_SUNLIGHTISHARSH,
    STRINGID_ITISHAILING,
    STRINGID_ITISSNOWING,
    STRINGID_ISCOVEREDWITHGRASS,
    STRINGID_MISTSWIRLSAROUND,
    STRINGID_ELECTRICCURRENTISRUNNING,
    STRINGID_SEEMSWEIRD,
    STRINGID_WAGGLINGAFINGER,
    STRINGID_BLOCKEDBYSLEEPCLAUSE,
    STRINGID_SUPEREFFECTIVETWOFOES,
    STRINGID_NOTVERYEFFECTIVETWOFOES,
    STRINGID_ITDOESNTAFFECTTWOFOES,
    STRINGID_SENDCAUGHTMONPARTYORBOX,
    STRINGID_PKMNSENTTOPCAFTERCATCH,
    STRINGID_PKMNDYNAMAXED,
    STRINGID_PKMNGIGANTAMAXED,
    STRINGID_TIMETODYNAMAX,
    STRINGID_TIMETOGIGANTAMAX,
    STRINGID_QUESTIONFORFEITBATTLE,
    STRINGID_FORFEITBATTLEGAVEMONEY,
    
    // pokefirered specific
    STRINGID_OLDMANUSEDITEM,
    STRINGID_GOTCHAPKMNCAUGHTOLDMAN,
    STRINGID_THREWROCK,
    STRINGID_THREWBAIT,
    STRINGID_PKMNANGRY,
    STRINGID_PKMNEATING,
    STRINGID_PKMNTRANSFERREDBILLSPC,
    STRINGID_PKMNBOXBILLSPCFULL,
    STRINGID_POKEDUDEUSED,
    STRINGID_MONTOOSCAREDTOMOVE,
    STRINGID_GHOSTGETOUTGETOUT,
    STRINGID_SILPHSCOPEUNVEILED,
    STRINGID_GHOSTWASMAROWAK,
    STRINGID_TRAINER1MON1COMEBACK,
    STRINGID_TRAINER1MON2COMEBACK,
    STRINGID_TRAINER1MON1AND2COMEBACK,

    STRINGID_COUNT
};

// The below IDs are all indexes into battle message tables,
// used to determine which of a set of messages to print.
// They are assigned to the MULTISTRING_CHOOSER byte of gBattleCommunication
// and read when e.g. the command printfromtable is used.

// gStatUpStringIds
#define B_MSG_ATTACKER_STAT_ROSE 0
#define B_MSG_DEFENDER_STAT_ROSE 1
#define B_MSG_STAT_WONT_INCREASE 2
#define B_MSG_STAT_ROSE_EMPTY    3
#define B_MSG_STAT_ROSE_ITEM     4
#define B_MSG_USED_DIRE_HIT      5

// gStatDownStringIds
#define B_MSG_ATTACKER_STAT_FELL 0
#define B_MSG_DEFENDER_STAT_FELL 1
#define B_MSG_STAT_WONT_DECREASE 2
#define B_MSG_STAT_FELL_EMPTY    3

// gMissStringIds
#define B_MSG_MISSED       0
#define B_MSG_PROTECTED    1
#define B_MSG_AVOIDED_ATK  2
#define B_MSG_AVOIDED_DMG  3
#define B_MSG_GROUND_MISS  4

// gAbsorbDrainStringIds
#define B_MSG_ABSORB      0
#define B_MSG_ABSORB_OOZE 1

// gLeechSeedStringIds
#define B_MSG_LEECH_SEED_SET   0
#define B_MSG_LEECH_SEED_MISS  1
#define B_MSG_LEECH_SEED_FAIL  2
#define B_MSG_LEECH_SEED_DRAIN 3
#define B_MSG_LEECH_SEED_OOZE  4

// gFirstTurnOfTwoStringIds
#define B_MSG_TURN1_RAZOR_WIND  0
#define B_MSG_TURN1_SOLAR_BEAM  1
#define B_MSG_TURN1_SKULL_BASH  2
#define B_MSG_TURN1_SKY_ATTACK  3
#define B_MSG_TURN1_FLY         4
#define B_MSG_TURN1_DIG         5
#define B_MSG_TURN1_DIVE        6
#define B_MSG_TURN1_BOUNCE      7

// gMoveWeatherChangeStringIds
#define B_MSG_STARTED_RAIN      0
#define B_MSG_STARTED_DOWNPOUR  1
#define B_MSG_WEATHER_FAILED    2
#define B_MSG_STARTED_SANDSTORM 3
#define B_MSG_STARTED_SUNLIGHT  4
#define B_MSG_STARTED_HAIL      5
#define B_MSG_STARTED_SNOW      6
#define B_MSG_STARTED_FOG       7

// gWeatherEndsStringIds
#define B_MSG_WEATHER_END_RAIN         0
#define B_MSG_WEATHER_END_SANDSTORM    1
#define B_MSG_WEATHER_END_SUN          2
#define B_MSG_WEATHER_END_HAIL         3
#define B_MSG_WEATHER_END_STRONG_WINDS 4
#define B_MSG_WEATHER_END_SNOW         5
#define B_MSG_WEATHER_END_FOG          6
#define B_MSG_WEATHER_END_COUNT        7

// gWeatherTurnStringIds
#define B_MSG_WEATHER_TURN_RAIN         0
#define B_MSG_WEATHER_TURN_DOWNPOUR     1
#define B_MSG_WEATHER_TURN_SUN          2
#define B_MSG_WEATHER_TURN_SANDSTORM    3
#define B_MSG_WEATHER_TURN_HAIL         4
#define B_MSG_WEATHER_TURN_SNOW         5
#define B_MSG_WEATHER_TURN_FOG          6
#define B_MSG_WEATHER_TURN_STRONG_WINDS 7
#define B_MSG_WEATHER_TURN_COUNT        8

// gRainContinuesStringIds
#define B_MSG_RAIN_CONTINUES     0
#define B_MSG_DOWNPOUR_CONTINUES 1
#define B_MSG_RAIN_STOPPED       2

// gSandStormHailSnowContinuesStringIds / gSandStormHailDmgStringIds/ gSandStormHailSnowEndStringIds
#define B_MSG_SANDSTORM  0
#define B_MSG_HAIL       1
#define B_MSG_SNOW       2

// gReflectLightScreenSafeguardStringIds
#define B_MSG_SIDE_STATUS_FAILED     0
#define B_MSG_SET_REFLECT_SINGLE     1
#define B_MSG_SET_REFLECT_DOUBLE     2
#define B_MSG_SET_LIGHTSCREEN_SINGLE 3
#define B_MSG_SET_LIGHTSCREEN_DOUBLE 4
#define B_MSG_SET_SAFEGUARD          5

// gProtectLikeUsedStringIds
#define B_MSG_PROTECTED_ITSELF 0
#define B_MSG_BRACED_ITSELF    1
#define B_MSG_PROTECT_FAILED   2
#define B_MSG_PROTECTED_TEAM   3

// gRestUsedStringIds
#define B_MSG_REST           0
#define B_MSG_REST_STATUSED  1

// gWokeUpStringIds
#define B_MSG_WOKE_UP        0
#define B_MSG_WOKE_UP_UPROAR 1

// gUproarAwakeStringIds
#define B_MSG_CANT_SLEEP_UPROAR  0
#define B_MSG_UPROAR_KEPT_AWAKE  1
#define B_MSG_STAYED_AWAKE_USING 2

// gUproarOverTurnStringIds
#define B_MSG_UPROAR_CONTINUES  0
#define B_MSG_UPROAR_ENDS       1

// gStockpileUsedStringIds
#define B_MSG_STOCKPILED     0
#define B_MSG_CANT_STOCKPILE 1

// gSwallowFailStringIds
#define B_MSG_SWALLOW_FAILED  0
#define B_MSG_SWALLOW_FULL_HP 1

// gKOFailedStringIds
#define B_MSG_KO_MISS       0
#define B_MSG_KO_UNAFFECTED 1

// gMistUsedStringIds
#define B_MSG_SET_MIST    0
#define B_MSG_MIST_FAILED 1

// gFocusEnergyUsedStringIds
#define B_MSG_GETTING_PUMPED      0
#define B_MSG_FOCUS_ENERGY_FAILED 1

// gTransformUsedStringIds
#define B_MSG_TRANSFORMED      0
#define B_MSG_TRANSFORM_FAILED 1

// gSubstituteUsedStringIds
#define B_MSG_SET_SUBSTITUTE    0
#define B_MSG_SUBSTITUTE_FAILED 1

// gPartyStatusHealStringIds
#define B_MSG_BELL                     0
#define B_MSG_BELL_SOUNDPROOF_ATTACKER 1
#define B_MSG_BELL_SOUNDPROOF_PARTNER  2
#define B_MSG_BELL_BOTH_SOUNDPROOF     3
#define B_MSG_SOOTHING_AROMA           4

// gFutureMoveUsedStringIds
#define B_MSG_FUTURE_SIGHT 0
#define B_MSG_DOOM_DESIRE  1

// gItemSwapStringIds
#define B_MSG_ITEM_SWAP_TAKEN 0
#define B_MSG_ITEM_SWAP_GIVEN 1
#define B_MSG_ITEM_SWAP_BOTH  2

// gSportsUsedStringIds
#define B_MSG_WEAKEN_ELECTRIC 0
#define B_MSG_WEAKEN_FIRE     1

// gCaughtMonStringIds
#define B_MSG_NO_MESSSAGE_SKIP   0
#define B_MSG_SENT_SOMEONES_PC   1
#define B_MSG_SENT_BILLS_PC      2
#define B_MSG_SOMEONES_BOX_FULL  3
#define B_MSG_BILLS_BOX_FULL     4
#define B_MSG_SWAPPED_INTO_PARTY 5

// gPrimalWeatherBlocksStringIds
#define B_MSG_PRIMAL_WEATHER_FIZZLED_BY_RAIN    0
#define B_MSG_PRIMAL_WEATHER_EVAPORATED_IN_SUN  1

// gInobedientStringIds
#define B_MSG_LOAFING            0
#define B_MSG_WONT_OBEY          1
#define B_MSG_TURNED_AWAY        2
#define B_MSG_PRETEND_NOT_NOTICE 3
#define B_MSG_INCAPABLE_OF_POWER 4
// For randomly selecting a disobey string
// Skips the one used for Battle Palace
#define NUM_LOAF_STRINGS 4

// gSafariGetNearStringIds
#define B_MSG_CREPT_CLOSER    0
#define B_MSG_CANT_GET_CLOSER 1

// gSafariReactionStringIds
#define B_MSG_MON_WATCHING   0
#define B_MSG_MON_ANGRY      1
#define B_MSG_MON_EATING     2
#define NUM_SAFARI_REACTIONS 3

// gFlashFireStringIds
#define B_MSG_FLASH_FIRE_BOOST    0
#define B_MSG_FLASH_FIRE_NO_BOOST 1

// gBerryEffectStringIds
#define B_MSG_CURED_PROBLEM     0
#define B_MSG_NORMALIZED_STATUS 1

// gNoEscapeStringIds
#define B_MSG_CANT_ESCAPE          0
#define B_MSG_DONT_LEAVE_BIRCH     1
#define B_MSG_PREVENTS_ESCAPE      2
#define B_MSG_CANT_ESCAPE_2        3
#define B_MSG_ATTACKER_CANT_ESCAPE 4

// gGotPoisonedStringIds / gGotParalyzedStringIds / gFellAsleepStringIds
// gGotBurnedStringIds / gGotFrozenStringIds / gAttractUsedStringIds
#define B_MSG_STATUSED            0
#define B_MSG_STATUSED_BY_ABILITY 1

// gBRNPreventionStringIds / gPRLZPreventionStringIds / gPSNPreventionStringIds
#define B_MSG_ABILITY_PREVENTS_MOVE_STATUS    0
#define B_MSG_ABILITY_PREVENTS_ABILITY_STATUS 1
#define B_MSG_STATUS_HAD_NO_EFFECT            2

// gGotDefrostedStringIds
#define B_MSG_DEFROSTED         0
#define B_MSG_DEFROSTED_BY_MOVE 1

// gFrostbiteHealedStringIds
#define B_MSG_FROSTBITE_HEALED         0
#define B_MSG_FROSTBITE_HEALED_BY_MOVE 1

// gSwitchInAbilityStringIds
#define B_MSG_SWITCHIN_MOLDBREAKER      0
#define B_MSG_SWITCHIN_TERAVOLT         1
#define B_MSG_SWITCHIN_TURBOBLAZE       2
#define B_MSG_SWITCHIN_SLOWSTART        3
#define B_MSG_SWITCHIN_UNNERVE          4
#define B_MSG_SWITCHIN_ANTICIPATION     5
#define B_MSG_SWITCHIN_FOREWARN         6
#define B_MSG_SWITCHIN_PRESSURE         7
#define B_MSG_SWITCHIN_DARKAURA         8
#define B_MSG_SWITCHIN_FAIRYAURA        9
#define B_MSG_SWITCHIN_AURABREAK        10
#define B_MSG_SWITCHIN_COMATOSE         11
#define B_MSG_SWITCHIN_SCREENCLEANER    12
#define B_MSG_SWITCHIN_ASONE            13
#define B_MSG_SWITCHIN_CURIOUS_MEDICINE 14
#define B_MSG_SWITCHIN_PASTEL_VEIL      15
#define B_MSG_SWITCHIN_NEUTRALIZING_GAS 16

// gMentalHerbCureStringIds
#define B_MSG_MENTALHERBCURE_INFATUATION       0
#define B_MSG_MENTALHERBCURE_TAUNT             1
#define B_MSG_MENTALHERBCURE_ENCORE            2
#define B_MSG_MENTALHERBCURE_TORMENT           3
#define B_MSG_MENTALHERBCURE_HEALBLOCK         4
#define B_MSG_MENTALHERBCURE_DISABLE           5

// gTerrainPreventsStringIds
#define B_MSG_TERRAINPREVENTS_MISTY     0
#define B_MSG_TERRAINPREVENTS_ELECTRIC  1
#define B_MSG_TERRAINPREVENTS_PSYCHIC   2

// gTerrainStringIds
#define B_MSG_TERRAIN_SET_MISTY     0
#define B_MSG_TERRAIN_SET_ELECTRIC  1
#define B_MSG_TERRAIN_SET_PSYCHIC   2
#define B_MSG_TERRAIN_SET_GRASSY    3
#define B_MSG_TERRAIN_END_MISTY     4
#define B_MSG_TERRAIN_END_ELECTRIC  5
#define B_MSG_TERRAIN_END_PSYCHIC   6
#define B_MSG_TERRAIN_END_GRASSY    7
#define B_MSG_TERRAIN_COUNT         8

// gStartingStatusStringIds
#define B_MSG_TERRAIN_SET_MISTY     0
#define B_MSG_TERRAIN_SET_ELECTRIC  1
#define B_MSG_TERRAIN_SET_PSYCHIC   2
#define B_MSG_TERRAIN_SET_GRASSY    3
#define B_MSG_SET_TRICK_ROOM        4
#define B_MSG_SET_MAGIC_ROOM        5
#define B_MSG_SET_WONDER_ROOM       6
#define B_MSG_SET_TAILWIND          7
#define B_MSG_SET_RAINBOW           8
#define B_MSG_SET_SEA_OF_FIRE       9
#define B_MSG_SET_SWAMP             10
#define B_MSG_STARTING_STATUS_COUNT 11

// gWrappedStringIds
#define B_MSG_WRAPPED_BIND         0
#define B_MSG_WRAPPED_WRAP         1
#define B_MSG_WRAPPED_FIRE_SPIN    2
#define B_MSG_WRAPPED_CLAMP        3
#define B_MSG_WRAPPED_WHIRLPOOL    4
#define B_MSG_WRAPPED_SAND_TOMB    5
#define B_MSG_WRAPPED_MAGMA_STORM  6
#define B_MSG_WRAPPED_INFESTATION  7
#define B_MSG_WRAPPED_SNAP_TRAP    8
#define B_MSG_WRAPPED_THUNDER_CAGE 9
#define NUM_TRAPPING_MOVES         10

// z effects (gZEffectStringIds)
#define B_MSG_Z_RESET_STATS   0
#define B_MSG_Z_ALL_STATS_UP  1
#define B_MSG_Z_BOOST_CRITS   2
#define B_MSG_Z_FOLLOW_ME     3
#define B_MSG_Z_RECOVER_HP    4
#define B_MSG_Z_STAT_UP       5
#define B_MSG_Z_HP_TRAP       6

// gDmgHazardsStringIds
#define B_MSG_PKMNHURTBYSPIKES   0
#define B_MSG_STEALTHROCKDMG     1
#define B_MSG_SHARPSTEELDMG      2
#define B_MSG_POINTEDSTONESFLOAT 3
#define B_MSG_SPIKESSCATTERED    4
#define B_MSG_SHARPSTEELFLOATS   5

// gDamageNonTypesStartStringIds
#define B_MSG_TRAPPED_WITH_VINES  0
#define B_MSG_CAUGHT_IN_VORTEX    1
#define B_MSG_SURROUNDED_BY_FIRE  2
#define B_MSG_SURROUNDED_BY_ROCKS 3

// gDamageNonTypesDmgStringIds
#define B_MSG_HURT_BY_VINES  0
#define B_MSG_HURT_BY_VORTEX    1
#define B_MSG_BURNING_UP  2
#define B_MSG_HURT_BY_ROCKS_THROWN 3

#endif // GUARD_BATTLE_STRING_IDS_H
