#define AnimAbilityPopUpBox 0
#define DoAftermathDamage 1
#define MaxAttackAngerPoint 2
#define TryDoAnticipationShudder 3
#define TryBadDreamsSecondDamage 4
#define GetStatRaiseDownload 5
#define GetStrongestMoveForewarn 6
#define TryFriskFirstTarget 7
#define TryFriskSecondTarget 8
