#ifndef GUARD_CONSTANTS_FANFARES_H
#define GUARD_CONSTANTS_FANFARES_H

enum Fanfares
{
    FANFARE_00,
    FANFARE_01,
    FANFARE_02,
    FANFARE_03,
    FANFARE_04,
    FANFARE_05,
    FANFARE_06,
    FANFARE_07,
    FANFARE_08,
    FANFARE_09,
    FANFARE_10,
    FANFARE_POKEFLUTE,
    FANFARE_KEY_ITEM,
    FANFARE_DEX_EVAL
};

#endif //GUARD_CONSTANTS_FANFARES_H
