#ifndef GUARD_CONSTANTS_FIELD_MOVE_H 
#define GUARD_CONSTANTS_FIELD_MOVE_H 

#define FIELD_MOVE_CUT          0
#define FIELD_MOVE_FLY          1
#define FIELD_MOVE_SURF         2
#define FIELD_MOVE_STRENGTH     3
#define FIELD_MOVE_FLASH        4
#define FIELD_MOVE_ROCK_SMASH   5
#define FIELD_MOVE_WATERFALL    6
#define FIELD_MOVE_TELEPORT     7
#define FIELD_MOVE_DIG          8
#define FIELD_MOVE_MILK_DRINK   9
#define FIELD_MOVE_SOFT_BOILED  10
#define FIELD_MOVE_SWEET_SCENT  11
#define FIELD_MOVE_COUNT        12

#endif // GUARD_CONSTANTS_FIELD_MOVE_H