#ifndef GUARD_CONSTANTS_FIELD_POISON_H
#define GUARD_CONSTANTS_FIELD_POISON_H

enum {
    FLDPSN_NONE,
    FLDPSN_PSN,
    FLDPSN_FNT
};

#define FLDPSN_NO_WHITEOUT        0
#define FLDPSN_WHITEOUT           1
#define FLDPSN_FRONTIER_WHITEOUT  2

#endif //GUARD_CONSTANTS_FIELD_POISON_H