#ifndef GUARD_CONSTANTS_GENERATIONAL_CHANGES_H
#define GUARD_CONSTANTS_GENERATIONAL_CHANGES_H

enum GenConfigTag
{
    GEN_CONFIG_CRIT_CHANCE,
    GEN_CONFIG_CRIT_MULTIPLIER,
    GEN_CONFIG_FOCUS_ENERGY_CRIT_RATIO,
    GEN_CONFIG_PARALYSIS_SPEED,
    GEN_CONFIG_CONFUSION_SELF_DMG_CHANCE,
    GEN_CONFIG_MULTI_HIT_CHANCE,
    GEN_CONFIG_GALE_WINGS,
    GEN_CONFIG_HEAL_BELL_SOUNDPROOF,
    GEN_CONFIG_COUNT
};

#endif // GUARD_CONSTANTS_GENERATIONAL_CHANGES_H
