#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

enum {
    HEAL_LOCATION_NONE,
    HEAL_LOCATION_PALLET_TOWN,
    HEAL_LOCATION_VIRIDIAN_CITY,
    HEAL_LOCATION_PEWTER_CITY,
    HEAL_LOCATION_CERULEAN_CITY,
    HEAL_LOCATION_LAVENDER_TOWN,
    HEAL_LOCATION_VERMILION_CITY,
    HEAL_LOCATION_CELADON_CITY,
    HEAL_LOCATION_FUCHSIA_CITY,
    HEAL_LOCATION_CINNABAR_ISLAND,
    HEAL_LOCATION_INDIGO_PLATEAU,
    HEAL_LOCATION_SAFFRON_CITY,
    HEAL_LOCATION_ROUTE4,
    HEAL_LOCATION_ROUTE10,
    HEAL_LOCATION_ONE_ISLAND,
    HEAL_LOCATION_TWO_ISLAND,
    HEAL_LOCATION_THREE_ISLAND,
    HEAL_LOCATION_FOUR_ISLAND,
    HEAL_LOCATION_FIVE_ISLAND,
    HEAL_LOCATION_SEVEN_ISLAND,
    HEAL_LOCATION_SIX_ISLAND,
};

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
