#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

#define SPAWN_PALLET_TOWN 1
#define SPAWN_VIRIDIAN_CITY 2
#define SPAWN_PEWTER_CITY 3
#define SPAWN_CERULEAN_CITY 4
#define SPAWN_LAVENDER_TOWN 5
#define SPAWN_VERMILION_CITY 6
#define SPAWN_CELADON_CITY 7
#define SPAWN_FUCHSIA_CITY 8
#define SPAWN_CINNABAR_ISLAND 9
#define SPAWN_INDIGO_PLATEAU 10
#define SPAWN_SAFFRON_CITY 11
#define SPAWN_ROUTE4 12
#define SPAWN_ROUTE10 13
#define SPAWN_ONE_ISLAND 14
#define SPAWN_TWO_ISLAND 15
#define SPAWN_THREE_ISLAND 16
#define SPAWN_FOUR_ISLAND 17
#define SPAWN_FIVE_ISLAND 18
#define SPAWN_SEVEN_ISLAND 19
#define SPAWN_SIX_ISLAND 20

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
