#ifndef GUARD_CONSTANTS_ITEM_MENU_H
#define GUARD_CONSTANTS_ITEM_MENU_H

#define ITEMMENUACTION_USE           0
#define ITEMMENUACTION_TOSS          1
#define ITEMMENUACTION_REGISTER      2
#define ITEMMENUACTION_GIVE          3
#define ITEMMENUACTION_CANCEL        4
#define ITEMMENUACTION_BATTLE_USE    5
#define ITEMMENUACTION_CHECK         6
#define ITEMMENUACTION_OPEN          7
#define ITEMMENUACTION_OPEN_BERRIES  8
#define ITEMMENUACTION_WALK          9
#define ITEMMENUACTION_DESELECT     10
#define ITEMMENUACTION_DUMMY        11

#endif //GUARD_CONSTANTS_ITEM_MENU_H
