#ifndef GUARD_CONSTANTS_ITEM_MENU_H
#define GUARD_CONSTANTS_ITEM_MENU_H

#define OPEN_BAG_ITEMS     0
#define OPEN_BAG_KEYITEMS  1
#define OPEN_BAG_POKEBALLS 2
#define OPEN_BAG_LAST      3

#define ITEMMENULOCATION_FIELD            0
#define ITEMMENULOCATION_PARTY            1
#define ITEMMENULOCATION_SHOP             2
#define ITEMMENULOCATION_ITEMPC           3
#define ITEMMENULOCATION_PCBOX            4
#define ITEMMENULOCATION_BATTLE           5
#define ITEMMENULOCATION_OLD_MAN          6
#define ITEMMENULOCATION_TTVSCR_STATUS    7
#define ITEMMENULOCATION_TTVSCR_CATCHING  8
#define ITEMMENULOCATION_TTVSCR_REGISTER  9
#define ITEMMENULOCATION_TTVSCR_TMS      10
#define ITEMMENULOCATION_LAST            11

#define ITEMMENUACTION_USE           0
#define ITEMMENUACTION_TOSS          1
#define ITEMMENUACTION_REGISTER      2
#define ITEMMENUACTION_GIVE          3
#define ITEMMENUACTION_CANCEL        4
#define ITEMMENUACTION_BATTLE_USE    5
#define ITEMMENUACTION_CHECK         6
#define ITEMMENUACTION_OPEN          7
#define ITEMMENUACTION_OPEN_BERRIES  8
#define ITEMMENUACTION_WALK          9
#define ITEMMENUACTION_DESELECT     10
#define ITEMMENUACTION_DUMMY        11

#endif //GUARD_CONSTANTS_ITEM_MENU_H
