#ifndef GUARD_CONSTANTS_POKEMON_SPECIAL_ANIM_H
#define GUARD_CONSTANTS_POKEMON_SPECIAL_ANIM_H

enum
{
    PSA_TEXT_ITEM_USED,
    PSA_TEXT_LEVEL_ELEVATED,
    PSA_TEXT_FORGET_1,
    PSA_TEXT_FORGET_2_AND,
    PSA_TEXT_FORGET_POOF,
    PSA_TEXT_FORGET_FORGOT,
    PSA_TEXT_FORGET_AND,
    PSA_TEXT_MACHINE_SET,
    PSA_TEXT_HUH,
    PSA_TEXT_LEARNED_MOVE
};

enum
{
    PSA_ITEM_ANIM_TYPE_DEFAULT,
    PSA_ITEM_ANIM_TYPE_POTION,
    PSA_ITEM_ANIM_TYPE_UNUSED1,
    PSA_ITEM_ANIM_TYPE_UNUSED2,
    PSA_ITEM_ANIM_TYPE_TMHM
};

#endif // GUARD_CONSTANTS_POKEMON_SPECIAL_ANIM_H
