#ifndef GUARD_CONSTANTS_SPAWN_POINTS_H
#define GUARD_CONSTANTS_SPAWN_POINTS_H

#define SPAWN_PALLET_TOWN      0
#define SPAWN_VIRIDIAN_CITY    1
#define SPAWN_PEWTER_CITY      2
#define SPAWN_CERULEAN_CITY    3
#define SPAWN_LAVENDER_TOWN    4
#define SPAWN_VERMILION_CITY   5
#define SPAWN_CELADON_CITY     6
#define SPAWN_FUCHSIA_CITY     7
#define SPAWN_CINNABAR_ISLAND  8
#define SPAWN_INDIGO_PLATEAU   9
#define SPAWN_SAFFRON_CITY    10
#define SPAWN_ROUTE4          11
#define SPAWN_ROUTE10         12
#define SPAWN_ONE_ISLAND      13
#define SPAWN_TWO_ISLAND      14
#define SPAWN_THREE_ISLAND    15
#define SPAWN_FOUR_ISLAND     16
#define SPAWN_FIVE_ISLAND     17
#define SPAWN_SEVEN_ISLAND    18
#define SPAWN_SIX_ISLAND      19
#define NUM_SPAWN_POINTS      20

#endif //GUARD_CONSTANTS_SPAWN_POINTS_H
