#ifndef GUARD_CONSTANTS_SPECIES_H
#define GUARD_CONSTANTS_SPECIES_H

#define SPECIES_NONE 0
#define SPECIES_BULBASAUR 1
#define SPECIES_IVYSAUR 2
#define SPECIES_VENUSAUR 3
#define SPECIES_CHARMANDER 4
#define SPECIES_CHARMELEON 5
#define SPECIES_CHARIZARD 6
#define SPECIES_SQUIRTLE 7
#define SPECIES_WARTORTLE 8
#define SPECIES_BLASTOISE 9
#define SPECIES_CATERPIE 10
#define SPECIES_METAPOD 11
#define SPECIES_BUTTERFREE 12
#define SPECIES_WEEDLE 13
#define SPECIES_KAKUNA 14
#define SPECIES_BEEDRILL 15
#define SPECIES_PIDGEY 16
#define SPECIES_PIDGEOTTO 17
#define SPECIES_PIDGEOT 18
#define SPECIES_RATTATA 19
#define SPECIES_RATICATE 20
#define SPECIES_SPEAROW 21
#define SPECIES_FEAROW 22
#define SPECIES_EKANS 23
#define SPECIES_ARBOK 24
#define SPECIES_PIKACHU 25
#define SPECIES_RAICHU 26
#define SPECIES_SANDSHREW 27
#define SPECIES_SANDSLASH 28
#define SPECIES_NIDORAN_F 29
#define SPECIES_NIDORINA 30
#define SPECIES_NIDOQUEEN 31
#define SPECIES_NIDORAN_M 32
#define SPECIES_NIDORINO 33
#define SPECIES_NIDOKING 34
#define SPECIES_CLEFAIRY 35
#define SPECIES_CLEFABLE 36
#define SPECIES_VULPIX 37
#define SPECIES_NINETALES 38
#define SPECIES_JIGGLYPUFF 39
#define SPECIES_WIGGLYTUFF 40
#define SPECIES_ZUBAT 41
#define SPECIES_GOLBAT 42
#define SPECIES_ODDISH 43
#define SPECIES_GLOOM 44
#define SPECIES_VILEPLUME 45
#define SPECIES_PARAS 46
#define SPECIES_PARASECT 47
#define SPECIES_VENONAT 48
#define SPECIES_VENOMOTH 49
#define SPECIES_DIGLETT 50
#define SPECIES_DUGTRIO 51
#define SPECIES_MEOWTH 52
#define SPECIES_PERSIAN 53
#define SPECIES_PSYDUCK 54
#define SPECIES_GOLDUCK 55
#define SPECIES_MANKEY 56
#define SPECIES_PRIMEAPE 57
#define SPECIES_GROWLITHE 58
#define SPECIES_ARCANINE 59
#define SPECIES_POLIWAG 60
#define SPECIES_POLIWHIRL 61
#define SPECIES_POLIWRATH 62
#define SPECIES_ABRA 63
#define SPECIES_KADABRA 64
#define SPECIES_ALAKAZAM 65
#define SPECIES_MACHOP 66
#define SPECIES_MACHOKE 67
#define SPECIES_MACHAMP 68
#define SPECIES_BELLSPROUT 69
#define SPECIES_WEEPINBELL 70
#define SPECIES_VICTREEBEL 71
#define SPECIES_TENTACOOL 72
#define SPECIES_TENTACRUEL 73
#define SPECIES_GEODUDE 74
#define SPECIES_GRAVELER 75
#define SPECIES_GOLEM 76
#define SPECIES_PONYTA 77
#define SPECIES_RAPIDASH 78
#define SPECIES_SLOWPOKE 79
#define SPECIES_SLOWBRO 80
#define SPECIES_MAGNEMITE 81
#define SPECIES_MAGNETON 82
#define SPECIES_FARFETCHD 83
#define SPECIES_DODUO 84
#define SPECIES_DODRIO 85
#define SPECIES_SEEL 86
#define SPECIES_DEWGONG 87
#define SPECIES_GRIMER 88
#define SPECIES_MUK 89
#define SPECIES_SHELLDER 90
#define SPECIES_CLOYSTER 91
#define SPECIES_GASTLY 92
#define SPECIES_HAUNTER 93
#define SPECIES_GENGAR 94
#define SPECIES_ONIX 95
#define SPECIES_DROWZEE 96
#define SPECIES_HYPNO 97
#define SPECIES_KRABBY 98
#define SPECIES_KINGLER 99
#define SPECIES_VOLTORB 100
#define SPECIES_ELECTRODE 101
#define SPECIES_EXEGGCUTE 102
#define SPECIES_EXEGGUTOR 103
#define SPECIES_CUBONE 104
#define SPECIES_MAROWAK 105
#define SPECIES_HITMONLEE 106
#define SPECIES_HITMONCHAN 107
#define SPECIES_LICKITUNG 108
#define SPECIES_KOFFING 109
#define SPECIES_WEEZING 110
#define SPECIES_RHYHORN 111
#define SPECIES_RHYDON 112
#define SPECIES_CHANSEY 113
#define SPECIES_TANGELA 114
#define SPECIES_KANGASKHAN 115
#define SPECIES_HORSEA 116
#define SPECIES_SEADRA 117
#define SPECIES_GOLDEEN 118
#define SPECIES_SEAKING 119
#define SPECIES_STARYU 120
#define SPECIES_STARMIE 121
#define SPECIES_MR_MIME 122
#define SPECIES_SCYTHER 123
#define SPECIES_JYNX 124
#define SPECIES_ELECTABUZZ 125
#define SPECIES_MAGMAR 126
#define SPECIES_PINSIR 127
#define SPECIES_TAUROS 128
#define SPECIES_MAGIKARP 129
#define SPECIES_GYARADOS 130
#define SPECIES_LAPRAS 131
#define SPECIES_DITTO 132
#define SPECIES_EEVEE 133
#define SPECIES_VAPOREON 134
#define SPECIES_JOLTEON 135
#define SPECIES_FLAREON 136
#define SPECIES_PORYGON 137
#define SPECIES_OMANYTE 138
#define SPECIES_OMASTAR 139
#define SPECIES_KABUTO 140
#define SPECIES_KABUTOPS 141
#define SPECIES_AERODACTYL 142
#define SPECIES_SNORLAX 143
#define SPECIES_ARTICUNO 144
#define SPECIES_ZAPDOS 145
#define SPECIES_MOLTRES 146
#define SPECIES_DRATINI 147
#define SPECIES_DRAGONAIR 148
#define SPECIES_DRAGONITE 149
#define SPECIES_MEWTWO 150
#define SPECIES_MEW 151

#define KANTO_SPECIES_END SPECIES_MEW

#define SPECIES_CHIKORITA 152
#define SPECIES_BAYLEEF 153
#define SPECIES_MEGANIUM 154
#define SPECIES_CYNDAQUIL 155
#define SPECIES_QUILAVA 156
#define SPECIES_TYPHLOSION 157
#define SPECIES_TOTODILE 158
#define SPECIES_CROCONAW 159
#define SPECIES_FERALIGATR 160
#define SPECIES_SENTRET 161
#define SPECIES_FURRET 162
#define SPECIES_HOOTHOOT 163
#define SPECIES_NOCTOWL 164
#define SPECIES_LEDYBA 165
#define SPECIES_LEDIAN 166
#define SPECIES_SPINARAK 167
#define SPECIES_ARIADOS 168
#define SPECIES_CROBAT 169
#define SPECIES_CHINCHOU 170
#define SPECIES_LANTURN 171
#define SPECIES_PICHU 172
#define SPECIES_CLEFFA 173
#define SPECIES_IGGLYBUFF 174
#define SPECIES_TOGEPI 175
#define SPECIES_TOGETIC 176
#define SPECIES_NATU 177
#define SPECIES_XATU 178
#define SPECIES_MAREEP 179
#define SPECIES_FLAAFFY 180
#define SPECIES_AMPHAROS 181
#define SPECIES_BELLOSSOM 182
#define SPECIES_MARILL 183
#define SPECIES_AZUMARILL 184
#define SPECIES_SUDOWOODO 185
#define SPECIES_POLITOED 186
#define SPECIES_HOPPIP 187
#define SPECIES_SKIPLOOM 188
#define SPECIES_JUMPLUFF 189
#define SPECIES_AIPOM 190
#define SPECIES_SUNKERN 191
#define SPECIES_SUNFLORA 192
#define SPECIES_YANMA 193
#define SPECIES_WOOPER 194
#define SPECIES_QUAGSIRE 195
#define SPECIES_ESPEON 196
#define SPECIES_UMBREON 197
#define SPECIES_MURKROW 198
#define SPECIES_SLOWKING 199
#define SPECIES_MISDREAVUS 200
#define SPECIES_UNOWN 201
#define SPECIES_WOBBUFFET 202
#define SPECIES_GIRAFARIG 203
#define SPECIES_PINECO 204
#define SPECIES_FORRETRESS 205
#define SPECIES_DUNSPARCE 206
#define SPECIES_GLIGAR 207
#define SPECIES_STEELIX 208
#define SPECIES_SNUBBULL 209
#define SPECIES_GRANBULL 210
#define SPECIES_QWILFISH 211
#define SPECIES_SCIZOR 212
#define SPECIES_SHUCKLE 213
#define SPECIES_HERACROSS 214
#define SPECIES_SNEASEL 215
#define SPECIES_TEDDIURSA 216
#define SPECIES_URSARING 217
#define SPECIES_SLUGMA 218
#define SPECIES_MAGCARGO 219
#define SPECIES_SWINUB 220
#define SPECIES_PILOSWINE 221
#define SPECIES_CORSOLA 222
#define SPECIES_REMORAID 223
#define SPECIES_OCTILLERY 224
#define SPECIES_DELIBIRD 225
#define SPECIES_MANTINE 226
#define SPECIES_SKARMORY 227
#define SPECIES_HOUNDOUR 228
#define SPECIES_HOUNDOOM 229
#define SPECIES_KINGDRA 230
#define SPECIES_PHANPY 231
#define SPECIES_DONPHAN 232
#define SPECIES_PORYGON2 233
#define SPECIES_STANTLER 234
#define SPECIES_SMEARGLE 235
#define SPECIES_TYROGUE 236
#define SPECIES_HITMONTOP 237
#define SPECIES_SMOOCHUM 238
#define SPECIES_ELEKID 239
#define SPECIES_MAGBY 240
#define SPECIES_MILTANK 241
#define SPECIES_BLISSEY 242
#define SPECIES_RAIKOU 243
#define SPECIES_ENTEI 244
#define SPECIES_SUICUNE 245
#define SPECIES_LARVITAR 246
#define SPECIES_PUPITAR 247
#define SPECIES_TYRANITAR 248
#define SPECIES_LUGIA 249
#define SPECIES_HO_OH 250
#define SPECIES_CELEBI 251
#define SPECIES_TREECKO                                 252
#define SPECIES_GROVYLE                                 253
#define SPECIES_SCEPTILE                                254
#define SPECIES_TORCHIC                                 255
#define SPECIES_COMBUSKEN                               256
#define SPECIES_BLAZIKEN                                257
#define SPECIES_MUDKIP                                  258
#define SPECIES_MARSHTOMP                               259
#define SPECIES_SWAMPERT                                260
#define SPECIES_POOCHYENA                               261
#define SPECIES_MIGHTYENA                               262
#define SPECIES_ZIGZAGOON                               263
#define SPECIES_LINOONE                                 264
#define SPECIES_WURMPLE                                 265
#define SPECIES_SILCOON                                 266
#define SPECIES_BEAUTIFLY                               267
#define SPECIES_CASCOON                                 268
#define SPECIES_DUSTOX                                  269
#define SPECIES_LOTAD                                   270
#define SPECIES_LOMBRE                                  271
#define SPECIES_LUDICOLO                                272
#define SPECIES_SEEDOT                                  273
#define SPECIES_NUZLEAF                                 274
#define SPECIES_SHIFTRY                                 275
#define SPECIES_NINCADA                                 276
#define SPECIES_NINJASK                                 277
#define SPECIES_SHEDINJA                                278
#define SPECIES_TAILLOW                                 279
#define SPECIES_SWELLOW                                 280
#define SPECIES_SHROOMISH                               281
#define SPECIES_BRELOOM                                 282
#define SPECIES_SPINDA                                  283
#define SPECIES_WINGULL                                 284
#define SPECIES_PELIPPER                                285
#define SPECIES_SURSKIT                                 286
#define SPECIES_MASQUERAIN                              287
#define SPECIES_WAILMER                                 288
#define SPECIES_WAILORD                                 289
#define SPECIES_SKITTY                                  290
#define SPECIES_DELCATTY                                291
#define SPECIES_KECLEON                                 292
#define SPECIES_BALTOY                                  293
#define SPECIES_CLAYDOL                                 294
#define SPECIES_NOSEPASS                                295
#define SPECIES_TORKOAL                                 296
#define SPECIES_SABLEYE                                 297
#define SPECIES_BARBOACH                                298
#define SPECIES_WHISCASH                                299
#define SPECIES_LUVDISC                                 300
#define SPECIES_CORPHISH                                301
#define SPECIES_CRAWDAUNT                               302
#define SPECIES_FEEBAS                                  303
#define SPECIES_MILOTIC                                 304
#define SPECIES_CARVANHA                                305
#define SPECIES_SHARPEDO                                306
#define SPECIES_TRAPINCH                                307
#define SPECIES_VIBRAVA                                 308
#define SPECIES_FLYGON                                  309
#define SPECIES_MAKUHITA                                310
#define SPECIES_HARIYAMA                                311
#define SPECIES_ELECTRIKE                               312
#define SPECIES_MANECTRIC                               313
#define SPECIES_NUMEL                                   314
#define SPECIES_CAMERUPT                                315
#define SPECIES_SPHEAL                                  316
#define SPECIES_SEALEO                                  317
#define SPECIES_WALREIN                                 318
#define SPECIES_CACNEA                                  319
#define SPECIES_CACTURNE                                320
#define SPECIES_SNORUNT                                 321
#define SPECIES_GLALIE                                  322
#define SPECIES_LUNATONE                                323
#define SPECIES_SOLROCK                                 324
#define SPECIES_AZURILL                                 325
#define SPECIES_SPOINK                                  326
#define SPECIES_GRUMPIG                                 327
#define SPECIES_PLUSLE                                  328
#define SPECIES_MINUN                                   329
#define SPECIES_MAWILE                                  330
#define SPECIES_MEDITITE                                331
#define SPECIES_MEDICHAM                                332
#define SPECIES_SWABLU                                  333
#define SPECIES_ALTARIA                                 334
#define SPECIES_WYNAUT                                  335
#define SPECIES_DUSKULL                                 336
#define SPECIES_DUSCLOPS                                337
#define SPECIES_ROSELIA                                 338
#define SPECIES_SLAKOTH                                 339
#define SPECIES_VIGOROTH                                340
#define SPECIES_SLAKING                                 341
#define SPECIES_GULPIN                                  342
#define SPECIES_SWALOT                                  343
#define SPECIES_TROPIUS                                 344
#define SPECIES_WHISMUR                                 345
#define SPECIES_LOUDRED                                 346
#define SPECIES_EXPLOUD                                 347
#define SPECIES_CLAMPERL                                348
#define SPECIES_HUNTAIL                                 349
#define SPECIES_GOREBYSS                                350
#define SPECIES_ABSOL                                   351
#define SPECIES_CHIMECHO                                352
#define SPECIES_SHUPPET                                 353
#define SPECIES_BANETTE                                 354
#define SPECIES_SEVIPER                                 355
#define SPECIES_ZANGOOSE                                356
#define SPECIES_RELICANTH                               357
#define SPECIES_ARON                                    358
#define SPECIES_LAIRON                                  359
#define SPECIES_AGGRON                                  360
#define SPECIES_CASTFORM                                361
#define SPECIES_VOLBEAT                                 362
#define SPECIES_ILLUMISE                                363
#define SPECIES_LILEEP                                  364
#define SPECIES_CRADILY                                 365
#define SPECIES_ANORITH                                 366
#define SPECIES_ARMALDO                                 367
#define SPECIES_RALTS                                   368
#define SPECIES_KIRLIA                                  369
#define SPECIES_GARDEVOIR                               370
#define SPECIES_BAGON                                   371
#define SPECIES_SHELGON                                 372
#define SPECIES_SALAMENCE                               373
#define SPECIES_BELDUM                                  374
#define SPECIES_METANG                                  375
#define SPECIES_METAGROSS                               376
#define SPECIES_REGIROCK                                377
#define SPECIES_REGICE                                  378
#define SPECIES_REGISTEEL                               379
#define SPECIES_KYOGRE                                  380
#define SPECIES_GROUDON                                 381
#define SPECIES_RAYQUAZA                                382
#define SPECIES_LATIAS                                  383
#define SPECIES_LATIOS                                  384
#define SPECIES_JIRACHI                                 385
#define SPECIES_DEOXYS                                  386
#define SPECIES_TURTWIG                                 387
#define SPECIES_GROTLE                                  388
#define SPECIES_TORTERRA                                389
#define SPECIES_CHIMCHAR                                390
#define SPECIES_MONFERNO                                391
#define SPECIES_INFERNAPE                               392
#define SPECIES_PIPLUP                                  393
#define SPECIES_PRINPLUP                                394
#define SPECIES_EMPOLEON                                395
#define SPECIES_STARLY                                  396
#define SPECIES_STARAVIA                                397
#define SPECIES_STARAPTOR                               398
#define SPECIES_BIDOOF                                  399
#define SPECIES_BIBAREL                                 400
#define SPECIES_KRICKETOT                               401
#define SPECIES_KRICKETUNE                              402
#define SPECIES_SHINX                                   403
#define SPECIES_LUXIO                                   404
#define SPECIES_LUXRAY                                  405
#define SPECIES_BUDEW                                   406
#define SPECIES_ROSERADE                                407
#define SPECIES_CRANIDOS                                408
#define SPECIES_RAMPARDOS                               409
#define SPECIES_SHIELDON                                410
#define SPECIES_BASTIODON                               411
#define SPECIES_BURMY                                   412
#define SPECIES_WORMADAM                                413
#define SPECIES_MOTHIM                                  414
#define SPECIES_COMBEE                                  415
#define SPECIES_VESPIQUEN                               416
#define SPECIES_PACHIRISU                               417
#define SPECIES_BUIZEL                                  418
#define SPECIES_FLOATZEL                                419
#define SPECIES_CHERUBI                                 420
#define SPECIES_CHERRIM                                 421
#define SPECIES_SHELLOS                                 422
#define SPECIES_GASTRODON                               423
#define SPECIES_AMBIPOM                                 424
#define SPECIES_DRIFLOON                                425
#define SPECIES_DRIFBLIM                                426
#define SPECIES_BUNEARY                                 427
#define SPECIES_LOPUNNY                                 428
#define SPECIES_MISMAGIUS                               429
#define SPECIES_HONCHKROW                               430
#define SPECIES_GLAMEOW                                 431
#define SPECIES_PURUGLY                                 432
#define SPECIES_CHINGLING                               433
#define SPECIES_STUNKY                                  434
#define SPECIES_SKUNTANK                                435
#define SPECIES_BRONZOR                                 436
#define SPECIES_BRONZONG                                437
#define SPECIES_BONSLY                                  438
#define SPECIES_MIME_JR                                 439
#define SPECIES_HAPPINY                                 440
#define SPECIES_CHATOT                                  441
#define SPECIES_SPIRITOMB                               442
#define SPECIES_GIBLE                                   443
#define SPECIES_GABITE                                  444
#define SPECIES_GARCHOMP                                445
#define SPECIES_MUNCHLAX                                446
#define SPECIES_RIOLU                                   447
#define SPECIES_LUCARIO                                 448
#define SPECIES_HIPPOPOTAS                              449
#define SPECIES_HIPPOWDON                               450
#define SPECIES_SKORUPI                                 451
#define SPECIES_DRAPION                                 452
#define SPECIES_CROAGUNK                                453
#define SPECIES_TOXICROAK                               454
#define SPECIES_CARNIVINE                               455
#define SPECIES_FINNEON                                 456
#define SPECIES_LUMINEON                                457
#define SPECIES_MANTYKE                                 458
#define SPECIES_SNOVER                                  459
#define SPECIES_ABOMASNOW                               460
#define SPECIES_WEAVILE                                 461
#define SPECIES_MAGNEZONE                               462
#define SPECIES_LICKILICKY                              463
#define SPECIES_RHYPERIOR                               464
#define SPECIES_TANGROWTH                               465
#define SPECIES_ELECTIVIRE                              466
#define SPECIES_MAGMORTAR                               467
#define SPECIES_TOGEKISS                                468
#define SPECIES_YANMEGA                                 469
#define SPECIES_LEAFEON                                 470
#define SPECIES_GLACEON                                 471
#define SPECIES_GLISCOR                                 472
#define SPECIES_MAMOSWINE                               473
#define SPECIES_PORYGON_Z                               474
#define SPECIES_GALLADE                                 475
#define SPECIES_PROBOPASS                               476
#define SPECIES_DUSKNOIR                                477
#define SPECIES_FROSLASS                                478
#define SPECIES_ROTOM                                   479
#define SPECIES_UXIE                                    480
#define SPECIES_MESPRIT                                 481
#define SPECIES_AZELF                                   482
#define SPECIES_DIALGA                                  483
#define SPECIES_PALKIA                                  484
#define SPECIES_HEATRAN                                 485
#define SPECIES_REGIGIGAS                               486
#define SPECIES_GIRATINA                                487
#define SPECIES_CRESSELIA                               488
#define SPECIES_PHIONE                                  489
#define SPECIES_MANAPHY                                 490
#define SPECIES_DARKRAI                                 491
#define SPECIES_SHAYMIN                                 492
#define SPECIES_ARCEUS                                  493
#define SPECIES_VICTINI                                 494
#define SPECIES_SNIVY                                   495
#define SPECIES_SERVINE                                 496
#define SPECIES_SERPERIOR                               497
#define SPECIES_TEPIG                                   498
#define SPECIES_PIGNITE                                 499
#define SPECIES_EMBOAR                                  500
#define SPECIES_OSHAWOTT                                501
#define SPECIES_DEWOTT                                  502
#define SPECIES_SAMUROTT                                503
#define SPECIES_PATRAT                                  504
#define SPECIES_WATCHOG                                 505
#define SPECIES_LILLIPUP                                506
#define SPECIES_HERDIER                                 507
#define SPECIES_STOUTLAND                               508
#define SPECIES_PURRLOIN                                509
#define SPECIES_LIEPARD                                 510
#define SPECIES_PANSAGE                                 511
#define SPECIES_SIMISAGE                                512
#define SPECIES_PANSEAR                                 513
#define SPECIES_SIMISEAR                                514
#define SPECIES_PANPOUR                                 515
#define SPECIES_SIMIPOUR                                516
#define SPECIES_MUNNA                                   517
#define SPECIES_MUSHARNA                                518
#define SPECIES_PIDOVE                                  519
#define SPECIES_TRANQUILL                               520
#define SPECIES_UNFEZANT                                521
#define SPECIES_BLITZLE                                 522
#define SPECIES_ZEBSTRIKA                               523
#define SPECIES_ROGGENROLA                              524
#define SPECIES_BOLDORE                                 525
#define SPECIES_GIGALITH                                526
#define SPECIES_WOOBAT                                  527
#define SPECIES_SWOOBAT                                 528
#define SPECIES_DRILBUR                                 529
#define SPECIES_EXCADRILL                               530
#define SPECIES_AUDINO                                  531
#define SPECIES_TIMBURR                                 532
#define SPECIES_GURDURR                                 533
#define SPECIES_CONKELDURR                              534
#define SPECIES_TYMPOLE                                 535
#define SPECIES_PALPITOAD                               536
#define SPECIES_SEISMITOAD                              537
#define SPECIES_THROH                                   538
#define SPECIES_SAWK                                    539
#define SPECIES_SEWADDLE                                540
#define SPECIES_SWADLOON                                541
#define SPECIES_LEAVANNY                                542
#define SPECIES_VENIPEDE                                543
#define SPECIES_WHIRLIPEDE                              544
#define SPECIES_SCOLIPEDE                               545
#define SPECIES_COTTONEE                                546
#define SPECIES_WHIMSICOTT                              547
#define SPECIES_PETILIL                                 548
#define SPECIES_LILLIGANT                               549
#define SPECIES_BASCULIN                                550
#define SPECIES_SANDILE                                 551
#define SPECIES_KROKOROK                                552
#define SPECIES_KROOKODILE                              553
#define SPECIES_DARUMAKA                                554
#define SPECIES_DARMANITAN                              555
#define SPECIES_MARACTUS                                556
#define SPECIES_DWEBBLE                                 557
#define SPECIES_CRUSTLE                                 558
#define SPECIES_SCRAGGY                                 559
#define SPECIES_SCRAFTY                                 560
#define SPECIES_SIGILYPH                                561
#define SPECIES_YAMASK                                  562
#define SPECIES_COFAGRIGUS                              563
#define SPECIES_TIRTOUGA                                564
#define SPECIES_CARRACOSTA                              565
#define SPECIES_ARCHEN                                  566
#define SPECIES_ARCHEOPS                                567
#define SPECIES_TRUBBISH                                568
#define SPECIES_GARBODOR                                569
#define SPECIES_ZORUA                                   570
#define SPECIES_ZOROARK                                 571
#define SPECIES_MINCCINO                                572
#define SPECIES_CINCCINO                                573
#define SPECIES_GOTHITA                                 574
#define SPECIES_GOTHORITA                               575
#define SPECIES_GOTHITELLE                              576
#define SPECIES_SOLOSIS                                 577
#define SPECIES_DUOSION                                 578
#define SPECIES_REUNICLUS                               579
#define SPECIES_DUCKLETT                                580
#define SPECIES_SWANNA                                  581
#define SPECIES_VANILLITE                               582
#define SPECIES_VANILLISH                               583
#define SPECIES_VANILLUXE                               584
#define SPECIES_DEERLING                                585
#define SPECIES_SAWSBUCK                                586
#define SPECIES_EMOLGA                                  587
#define SPECIES_KARRABLAST                              588
#define SPECIES_ESCAVALIER                              589
#define SPECIES_FOONGUS                                 590
#define SPECIES_AMOONGUSS                               591
#define SPECIES_FRILLISH                                592
#define SPECIES_JELLICENT                               593
#define SPECIES_ALOMOMOLA                               594
#define SPECIES_JOLTIK                                  595
#define SPECIES_GALVANTULA                              596
#define SPECIES_FERROSEED                               597
#define SPECIES_FERROTHORN                              598
#define SPECIES_KLINK                                   599
#define SPECIES_KLANG                                   600
#define SPECIES_KLINKLANG                               601
#define SPECIES_TYNAMO                                  602
#define SPECIES_EELEKTRIK                               603
#define SPECIES_EELEKTROSS                              604
#define SPECIES_ELGYEM                                  605
#define SPECIES_BEHEEYEM                                606
#define SPECIES_LITWICK                                 607
#define SPECIES_LAMPENT                                 608
#define SPECIES_CHANDELURE                              609
#define SPECIES_AXEW                                    610
#define SPECIES_FRAXURE                                 611
#define SPECIES_HAXORUS                                 612
#define SPECIES_CUBCHOO                                 613
#define SPECIES_BEARTIC                                 614
#define SPECIES_CRYOGONAL                               615
#define SPECIES_SHELMET                                 616
#define SPECIES_ACCELGOR                                617
#define SPECIES_STUNFISK                                618
#define SPECIES_MIENFOO                                 619
#define SPECIES_MIENSHAO                                620
#define SPECIES_DRUDDIGON                               621
#define SPECIES_GOLETT                                  622
#define SPECIES_GOLURK                                  623
#define SPECIES_PAWNIARD                                624
#define SPECIES_BISHARP                                 625
#define SPECIES_BOUFFALANT                              626
#define SPECIES_RUFFLET                                 627
#define SPECIES_BRAVIARY                                628
#define SPECIES_VULLABY                                 629
#define SPECIES_MANDIBUZZ                               630
#define SPECIES_HEATMOR                                 631
#define SPECIES_DURANT                                  632
#define SPECIES_DEINO                                   633
#define SPECIES_ZWEILOUS                                634
#define SPECIES_HYDREIGON                               635
#define SPECIES_LARVESTA                                636
#define SPECIES_VOLCARONA                               637
#define SPECIES_COBALION                                638
#define SPECIES_TERRAKION                               639
#define SPECIES_VIRIZION                                640
#define SPECIES_TORNADUS                                641
#define SPECIES_THUNDURUS                               642
#define SPECIES_RESHIRAM                                643
#define SPECIES_ZEKROM                                  644
#define SPECIES_LANDORUS                                645
#define SPECIES_KYUREM                                  646
#define SPECIES_KELDEO                                  647
#define SPECIES_MELOETTA                                648
#define SPECIES_GENESECT                                649
#define SPECIES_CHESPIN                                 650
#define SPECIES_QUILLADIN                               651
#define SPECIES_CHESNAUGHT                              652
#define SPECIES_FENNEKIN                                653
#define SPECIES_BRAIXEN                                 654
#define SPECIES_DELPHOX                                 655
#define SPECIES_FROAKIE                                 656
#define SPECIES_FROGADIER                               657
#define SPECIES_GRENINJA                                658
#define SPECIES_BUNNELBY                                659
#define SPECIES_DIGGERSBY                               660
#define SPECIES_FLETCHLING                              661
#define SPECIES_FLETCHINDER                             662
#define SPECIES_TALONFLAME                              663
#define SPECIES_SCATTERBUG                              664
#define SPECIES_SPEWPA                                  665
#define SPECIES_VIVILLON                                666
#define SPECIES_LITLEO                                  667
#define SPECIES_PYROAR                                  668
#define SPECIES_FLABEBE                                 669
#define SPECIES_FLOETTE                                 670
#define SPECIES_FLORGES                                 671
#define SPECIES_SKIDDO                                  672
#define SPECIES_GOGOAT                                  673
#define SPECIES_PANCHAM                                 674
#define SPECIES_PANGORO                                 675
#define SPECIES_FURFROU                                 676
#define SPECIES_ESPURR                                  677
#define SPECIES_MEOWSTIC                                678
#define SPECIES_HONEDGE                                 679
#define SPECIES_DOUBLADE                                680
#define SPECIES_AEGISLASH                               681
#define SPECIES_SPRITZEE                                682
#define SPECIES_AROMATISSE                              683
#define SPECIES_SWIRLIX                                 684
#define SPECIES_SLURPUFF                                685
#define SPECIES_INKAY                                   686
#define SPECIES_MALAMAR                                 687
#define SPECIES_BINACLE                                 688
#define SPECIES_BARBARACLE                              689
#define SPECIES_SKRELP                                  690
#define SPECIES_DRAGALGE                                691
#define SPECIES_CLAUNCHER                               692
#define SPECIES_CLAWITZER                               693
#define SPECIES_HELIOPTILE                              694
#define SPECIES_HELIOLISK                               695
#define SPECIES_TYRUNT                                  696
#define SPECIES_TYRANTRUM                               697
#define SPECIES_AMAURA                                  698
#define SPECIES_AURORUS                                 699
#define SPECIES_SYLVEON                                 700
#define SPECIES_HAWLUCHA                                701
#define SPECIES_DEDENNE                                 702
#define SPECIES_CARBINK                                 703
#define SPECIES_GOOMY                                   704
#define SPECIES_SLIGGOO                                 705
#define SPECIES_GOODRA                                  706
#define SPECIES_KLEFKI                                  707
#define SPECIES_PHANTUMP                                708
#define SPECIES_TREVENANT                               709
#define SPECIES_PUMPKABOO                               710
#define SPECIES_GOURGEIST                               711
#define SPECIES_BERGMITE                                712
#define SPECIES_AVALUGG                                 713
#define SPECIES_NOIBAT                                  714
#define SPECIES_NOIVERN                                 715
#define SPECIES_XERNEAS                                 716
#define SPECIES_YVELTAL                                 717
#define SPECIES_ZYGARDE                                 718
#define SPECIES_DIANCIE                                 719
#define SPECIES_HOOPA                                   720
#define SPECIES_VOLCANION                               721
#define SPECIES_EGG                                     722

#define NUM_SPECIES SPECIES_EGG

#endif  // GUARD_CONSTANTS_SPECIES_H
