#ifndef GUARD_CONSTANTS_TRAINERS_H
#define GUARD_CONSTANTS_TRAINERS_H

#include "constants/opponents.h"
#include "constants/battle_frontier_trainers.h"

#define TRAINER_ENCOUNTER_MUSIC_MALE         0 // standard male encounter music
#define TRAINER_ENCOUNTER_MUSIC_FEMALE       1 // standard female encounter music
#define TRAINER_ENCOUNTER_MUSIC_GIRL         2 // used for male Tubers and Young Couples too
#define TRAINER_ENCOUNTER_MUSIC_SUSPICIOUS   3
#define TRAINER_ENCOUNTER_MUSIC_INTENSE      4
#define TRAINER_ENCOUNTER_MUSIC_COOL         5
#define TRAINER_ENCOUNTER_MUSIC_AQUA         6
#define TRAINER_ENCOUNTER_MUSIC_MAGMA        7
#define TRAINER_ENCOUNTER_MUSIC_SWIMMER      8
#define TRAINER_ENCOUNTER_MUSIC_TWINS        9 // used for other trainer classes too
#define TRAINER_ENCOUNTER_MUSIC_ELITE_FOUR  10
#define TRAINER_ENCOUNTER_MUSIC_HIKER       11 // used for other trainer classes too
#define TRAINER_ENCOUNTER_MUSIC_INTERVIEWER 12
#define TRAINER_ENCOUNTER_MUSIC_RICH        13 // Rich Boys and Gentlemen


// placeholders
#define FACILITY_CLASS_TUBER_M          FACILITY_CLASS_RUIN_MANIAC
#define FACILITY_CLASS_PKMN_BREEDER_M   FACILITY_CLASS_RUIN_MANIAC

#define FACILITY_CLASS_TUBER_F          FACILITY_CLASS_AROMA_LADY
#define FACILITY_CLASS_PKMN_BREEDER_F   FACILITY_CLASS_AROMA_LADY

#define TRAINER_CLASS_RIVAL    TRAINER_CLASS_RIVAL_LATE
#define TRAINER_CLASS_TUBER_M  TRAINER_CLASS_RS_TUBER_M
#define TRAINER_CLASS_TUBER_F  TRAINER_CLASS_RS_TUBER_F



enum __attribute__((packed)) TrainerPicID
{
    TRAINER_PIC_AQUA_LEADER_ARCHIE,
    TRAINER_PIC_AQUA_GRUNT_M,
    TRAINER_PIC_AQUA_GRUNT_F,
    TRAINER_PIC_RS_AROMA_LADY,
    TRAINER_PIC_RS_RUIN_MANIAC,
    TRAINER_PIC_INTERVIEWER,
    TRAINER_PIC_RS_TUBER_F,
    TRAINER_PIC_RS_TUBER_M,
    TRAINER_PIC_RS_COOLTRAINER_M,
    TRAINER_PIC_RS_COOLTRAINER_F,
    TRAINER_PIC_HEX_MANIAC,
    TRAINER_PIC_RS_LADY,
    TRAINER_PIC_RS_BEAUTY,
    TRAINER_PIC_RICH_BOY,
    TRAINER_PIC_RS_POKEMANIAC,
    TRAINER_PIC_RS_SWIMMER_M,
    TRAINER_PIC_RS_BLACK_BELT,
    TRAINER_PIC_GUITARIST,
    TRAINER_PIC_KINDLER,
    TRAINER_PIC_RS_CAMPER,
    TRAINER_PIC_BUG_MANIAC,
    TRAINER_PIC_RS_PSYCHIC_M,
    TRAINER_PIC_RS_PSYCHIC_F,
    TRAINER_PIC_RS_GENTLEMAN,
    TRAINER_PIC_ELITE_FOUR_SIDNEY,
    TRAINER_PIC_ELITE_FOUR_PHOEBE,
    TRAINER_PIC_LEADER_ROXANNE,
    TRAINER_PIC_LEADER_BRAWLY,
    TRAINER_PIC_LEADER_TATE_AND_LIZA,
    TRAINER_PIC_SCHOOL_KID_M,
    TRAINER_PIC_SCHOOL_KID_F,
    TRAINER_PIC_SR_AND_JR,
    TRAINER_PIC_POKEFAN_M,
    TRAINER_PIC_POKEFAN_F,
    TRAINER_PIC_EXPERT_M,
    TRAINER_PIC_EXPERT_F,
    TRAINER_PIC_RS_YOUNGSTER,
    TRAINER_PIC_CHAMPION_STEVEN,
    TRAINER_PIC_RS_FISHERMAN,
    TRAINER_PIC_CYCLING_TRIATHLETE_M,
    TRAINER_PIC_CYCLING_TRIATHLETE_F,
    TRAINER_PIC_RUNNING_TRIATHLETE_M,
    TRAINER_PIC_RUNNING_TRIATHLETE_F,
    TRAINER_PIC_SWIMMING_TRIATHLETE_M,
    TRAINER_PIC_SWIMMING_TRIATHLETE_F,
    TRAINER_PIC_DRAGON_TAMER,
    TRAINER_PIC_RS_BIRD_KEEPER,
    TRAINER_PIC_NINJA_BOY,
    TRAINER_PIC_BATTLE_GIRL,
    TRAINER_PIC_PARASOL_LADY,
    TRAINER_PIC_RS_SWIMMER_F,
    TRAINER_PIC_RS_PICNICKER,
    TRAINER_PIC_RS_TWINS,
    TRAINER_PIC_RS_SAILOR,
    TRAINER_PIC_COLLECTOR,
    TRAINER_PIC_WALLY,
    TRAINER_PIC_RS_BRENDAN_1,
    TRAINER_PIC_RS_MAY_1,
    TRAINER_PIC_RS_POKEMON_BREEDER_M,
    TRAINER_PIC_RS_POKEMON_BREEDER_F,
    TRAINER_PIC_RS_POKEMON_RANGER_M,
    TRAINER_PIC_RS_POKEMON_RANGER_F,
    TRAINER_PIC_MAGMA_LEADER_MAXIE,
    TRAINER_PIC_MAGMA_GRUNT_M,
    TRAINER_PIC_MAGMA_GRUNT_F,
    TRAINER_PIC_RS_LASS,
    TRAINER_PIC_RS_BUG_CATCHER,
    TRAINER_PIC_RS_HIKER,
    TRAINER_PIC_RS_YOUNG_COUPLE,
    TRAINER_PIC_OLD_COUPLE,
    TRAINER_PIC_RS_SIS_AND_BRO,
    TRAINER_PIC_AQUA_ADMIN_M,
    TRAINER_PIC_AQUA_ADMIN_F,
    TRAINER_PIC_MAGMA_ADMIN_M,
    TRAINER_PIC_MAGMA_ADMIN_F,
    TRAINER_PIC_LEADER_WATTSON,
    TRAINER_PIC_LEADER_FLANNERY,
    TRAINER_PIC_LEADER_NORMAN,
    TRAINER_PIC_LEADER_WINONA,
    TRAINER_PIC_LEADER_WALLACE,
    TRAINER_PIC_ELITE_FOUR_GLACIA,
    TRAINER_PIC_ELITE_FOUR_DRAKE,
    TRAINER_PIC_YOUNGSTER,
    TRAINER_PIC_BUG_CATCHER,
    TRAINER_PIC_LASS,
    TRAINER_PIC_SAILOR,
    TRAINER_PIC_CAMPER,
    TRAINER_PIC_PICNICKER,
    TRAINER_PIC_POKEMANIAC,
    TRAINER_PIC_SUPER_NERD,
    TRAINER_PIC_HIKER,
    TRAINER_PIC_BIKER,
    TRAINER_PIC_BURGLAR,
    TRAINER_PIC_ENGINEER,
    TRAINER_PIC_FISHERMAN,
    TRAINER_PIC_SWIMMER_M,
    TRAINER_PIC_CUE_BALL,
    TRAINER_PIC_GAMER,
    TRAINER_PIC_BEAUTY,
    TRAINER_PIC_SWIMMER_F,
    TRAINER_PIC_PSYCHIC_M,
    TRAINER_PIC_ROCKER,
    TRAINER_PIC_JUGGLER,
    TRAINER_PIC_TAMER,
    TRAINER_PIC_BIRD_KEEPER,
    TRAINER_PIC_BLACK_BELT,
    TRAINER_PIC_RIVAL_EARLY,
    TRAINER_PIC_SCIENTIST,
    TRAINER_PIC_LEADER_GIOVANNI,
    TRAINER_PIC_ROCKET_GRUNT_M,
    TRAINER_PIC_COOLTRAINER_M,
    TRAINER_PIC_COOLTRAINER_F,
    TRAINER_PIC_ELITE_FOUR_LORELEI,
    TRAINER_PIC_ELITE_FOUR_BRUNO,
    TRAINER_PIC_ELITE_FOUR_AGATHA,
    TRAINER_PIC_ELITE_FOUR_LANCE,
    TRAINER_PIC_LEADER_BROCK,
    TRAINER_PIC_LEADER_MISTY,
    TRAINER_PIC_LEADER_LT_SURGE,
    TRAINER_PIC_LEADER_ERIKA,
    TRAINER_PIC_LEADER_KOGA,
    TRAINER_PIC_LEADER_BLAINE,
    TRAINER_PIC_LEADER_SABRINA,
    TRAINER_PIC_GENTLEMAN,
    TRAINER_PIC_RIVAL_LATE,
    TRAINER_PIC_CHAMPION_RIVAL,
    TRAINER_PIC_CHANNELER,
    TRAINER_PIC_TWINS,
    TRAINER_PIC_COOL_COUPLE,
    TRAINER_PIC_YOUNG_COUPLE,
    TRAINER_PIC_CRUSH_KIN,
    TRAINER_PIC_SIS_AND_BRO,
    TRAINER_PIC_PROFESSOR_OAK,
    TRAINER_PIC_RS_BRENDAN_2,
    TRAINER_PIC_RS_MAY_2,
    TRAINER_PIC_RED,
    TRAINER_PIC_LEAF,
    TRAINER_PIC_ROCKET_GRUNT_F,
    TRAINER_PIC_PSYCHIC_F,
    TRAINER_PIC_CRUSH_GIRL,
    TRAINER_PIC_TUBER_F,
    TRAINER_PIC_POKEMON_BREEDER,
    TRAINER_PIC_POKEMON_RANGER_M,
    TRAINER_PIC_POKEMON_RANGER_F,
    TRAINER_PIC_AROMA_LADY,
    TRAINER_PIC_RUIN_MANIAC,
    TRAINER_PIC_LADY,
    TRAINER_PIC_PAINTER,
};

// The player back pics are assumed to alternate according to the gender values (MALE/FEMALE)
#define TRAINER_BACK_PIC_RED                    0
#define TRAINER_BACK_PIC_LEAF                   1
#define TRAINER_BACK_PIC_RUBY_SAPPHIRE_BRENDAN  2
#define TRAINER_BACK_PIC_RUBY_SAPPHIRE_MAY      3
#define TRAINER_BACK_PIC_POKEDUDE               4
#define TRAINER_BACK_PIC_OLD_MAN                5
#define TRAINER_BACK_PIC_STEVEN                 6

// Special Trainer Ids.
#define TRAINER_RECORD_MIXING_FRIEND        FRONTIER_TRAINERS_COUNT
#define TRAINER_RECORD_MIXING_APPRENTICE    1020
#define TRAINER_EREADER                     1021
#define TRAINER_FRONTIER_BRAIN              1022
#define TRAINER_PLAYER                      1023
#define TRAINER_UNION_ROOM                  0xC00
#define TRAINER_LINK_OPPONENT               0x800
#define TRAINER_SECRET_BASE                 0x400

enum TrainerClassID
{
    TRAINER_CLASS_PKMN_TRAINER_1,
    TRAINER_CLASS_PKMN_TRAINER_2,
    TRAINER_CLASS_AQUA_LEADER,
    TRAINER_CLASS_TEAM_AQUA,
    TRAINER_CLASS_RS_AROMA_LADY,
    TRAINER_CLASS_RS_RUIN_MANIAC,
    TRAINER_CLASS_INTERVIEWER,
    TRAINER_CLASS_RS_TUBER_F,
    TRAINER_CLASS_RS_TUBER_M,
    TRAINER_CLASS_RS_COOLTRAINER,
    TRAINER_CLASS_HEX_MANIAC,
    TRAINER_CLASS_RS_LADY,
    TRAINER_CLASS_RS_BEAUTY,
    TRAINER_CLASS_RICH_BOY,
    TRAINER_CLASS_RS_POKEMANIAC,
    TRAINER_CLASS_RS_SWIMMER_M,
    TRAINER_CLASS_RS_BLACK_BELT,
    TRAINER_CLASS_GUITARIST,
    TRAINER_CLASS_KINDLER,
    TRAINER_CLASS_RS_CAMPER,
    TRAINER_CLASS_BUG_MANIAC,
    TRAINER_CLASS_RS_PSYCHIC,
    TRAINER_CLASS_RS_GENTLEMAN,
    TRAINER_CLASS_RS_ELITE_FOUR,
    TRAINER_CLASS_RS_LEADER,
    TRAINER_CLASS_SCHOOL_KID,
    TRAINER_CLASS_SR_AND_JR,
    TRAINER_CLASS_POKEFAN,
    TRAINER_CLASS_EXPERT,
    TRAINER_CLASS_RS_YOUNGSTER,
    TRAINER_CLASS_RS_CHAMPION,
    TRAINER_CLASS_RS_FISHERMAN,
    TRAINER_CLASS_TRIATHLETE,
    TRAINER_CLASS_DRAGON_TAMER,
    TRAINER_CLASS_RS_BIRD_KEEPER,
    TRAINER_CLASS_NINJA_BOY,
    TRAINER_CLASS_BATTLE_GIRL,
    TRAINER_CLASS_PARASOL_LADY,
    TRAINER_CLASS_RS_SWIMMER_F,
    TRAINER_CLASS_RS_PICNICKER,
    TRAINER_CLASS_RS_TWINS,
    TRAINER_CLASS_RS_SAILOR,
    TRAINER_CLASS_BOARDER,
    TRAINER_CLASS_COLLECTOR,
    TRAINER_CLASS_PKMN_TRAINER,
    TRAINER_CLASS_RS_PKMN_BREEDER,
    TRAINER_CLASS_RS_PKMN_RANGER,
    TRAINER_CLASS_MAGMA_LEADER,
    TRAINER_CLASS_TEAM_MAGMA,
    TRAINER_CLASS_RS_LASS,
    TRAINER_CLASS_RS_BUG_CATCHER,
    TRAINER_CLASS_RS_HIKER,
    TRAINER_CLASS_RS_YOUNG_COUPLE,
    TRAINER_CLASS_OLD_COUPLE,
    TRAINER_CLASS_RS_SIS_AND_BRO,
    TRAINER_CLASS_AQUA_ADMIN,
    TRAINER_CLASS_MAGMA_ADMIN,
    TRAINER_CLASS_YOUNGSTER,
    TRAINER_CLASS_BUG_CATCHER,
    TRAINER_CLASS_LASS,
    TRAINER_CLASS_SAILOR,
    TRAINER_CLASS_CAMPER,
    TRAINER_CLASS_PICNICKER,
    TRAINER_CLASS_POKEMANIAC,
    TRAINER_CLASS_SUPER_NERD,
    TRAINER_CLASS_HIKER,
    TRAINER_CLASS_BIKER,
    TRAINER_CLASS_BURGLAR,
    TRAINER_CLASS_ENGINEER,
    TRAINER_CLASS_FISHERMAN,
    TRAINER_CLASS_SWIMMER_M,
    TRAINER_CLASS_CUE_BALL,
    TRAINER_CLASS_GAMER,
    TRAINER_CLASS_BEAUTY,
    TRAINER_CLASS_SWIMMER_F,
    TRAINER_CLASS_PSYCHIC,
    TRAINER_CLASS_ROCKER,
    TRAINER_CLASS_JUGGLER,
    TRAINER_CLASS_TAMER,
    TRAINER_CLASS_BIRD_KEEPER,
    TRAINER_CLASS_BLACK_BELT,
    TRAINER_CLASS_RIVAL_EARLY,
    TRAINER_CLASS_SCIENTIST,
    TRAINER_CLASS_BOSS,
    TRAINER_CLASS_LEADER,
    TRAINER_CLASS_TEAM_ROCKET,
    TRAINER_CLASS_COOLTRAINER,
    TRAINER_CLASS_ELITE_FOUR,
    TRAINER_CLASS_GENTLEMAN,
    TRAINER_CLASS_RIVAL_LATE,
    TRAINER_CLASS_CHAMPION,
    TRAINER_CLASS_CHANNELER,
    TRAINER_CLASS_TWINS,
    TRAINER_CLASS_COOL_COUPLE,
    TRAINER_CLASS_YOUNG_COUPLE,
    TRAINER_CLASS_CRUSH_KIN,
    TRAINER_CLASS_SIS_AND_BRO,
    TRAINER_CLASS_PKMN_PROF,
    TRAINER_CLASS_PLAYER,
    TRAINER_CLASS_CRUSH_GIRL,
    TRAINER_CLASS_TUBER,
    TRAINER_CLASS_PKMN_BREEDER,
    TRAINER_CLASS_PKMN_RANGER,
    TRAINER_CLASS_AROMA_LADY,
    TRAINER_CLASS_RUIN_MANIAC,
    TRAINER_CLASS_LADY,
    TRAINER_CLASS_PAINTER,

    TRAINER_CLASS_COUNT
};

#define FACILITY_CLASS_AQUA_LEADER_ARCHIE     0
#define FACILITY_CLASS_AQUA_GRUNT_M           1
#define FACILITY_CLASS_AQUA_GRUNT_F           2
#define FACILITY_CLASS_RS_AROMA_LADY          3
#define FACILITY_CLASS_RS_RUIN_MANIAC         4
#define FACILITY_CLASS_INTERVIEWER            5
#define FACILITY_CLASS_RS_TUBER_F             6
#define FACILITY_CLASS_RS_TUBER_M             7
#define FACILITY_CLASS_RS_COOLTRAINER_M       8
#define FACILITY_CLASS_RS_COOLTRAINER_F       9
#define FACILITY_CLASS_HEX_MANIAC             10
#define FACILITY_CLASS_RS_LADY                11
#define FACILITY_CLASS_RS_BEAUTY              12
#define FACILITY_CLASS_RICH_BOY               13
#define FACILITY_CLASS_RS_POKEMANIAC          14
#define FACILITY_CLASS_RS_SWIMMER_M           15
#define FACILITY_CLASS_RS_BLACK_BELT          16
#define FACILITY_CLASS_GUITARIST              17
#define FACILITY_CLASS_KINDLER                18
#define FACILITY_CLASS_RS_CAMPER              19
#define FACILITY_CLASS_BUG_MANIAC             20
#define FACILITY_CLASS_RS_PSYCHIC_M           21
#define FACILITY_CLASS_RS_PSYCHIC_F           22
#define FACILITY_CLASS_RS_GENTLEMAN           23
#define FACILITY_CLASS_ELITE_FOUR_SIDNEY      24
#define FACILITY_CLASS_ELITE_FOUR_PHOEBE      25
#define FACILITY_CLASS_LEADER_ROXANNE         26
#define FACILITY_CLASS_LEADER_BRAWLY          27
#define FACILITY_CLASS_LEADER_TATE_AND_LIZA   28
#define FACILITY_CLASS_SCHOOL_KID_M           29
#define FACILITY_CLASS_SCHOOL_KID_F           30
#define FACILITY_CLASS_SR_AND_JR              31
#define FACILITY_CLASS_POKEFAN_M              32
#define FACILITY_CLASS_POKEFAN_F              33
#define FACILITY_CLASS_EXPERT_M               34
#define FACILITY_CLASS_EXPERT_F               35
#define FACILITY_CLASS_RS_YOUNGSTER           36
#define FACILITY_CLASS_CHAMPION_STEVEN        37
#define FACILITY_CLASS_RS_FISHERMAN           38
#define FACILITY_CLASS_CYCLING_TRIATHLETE_M   39
#define FACILITY_CLASS_CYCLING_TRIATHLETE_F   40
#define FACILITY_CLASS_RUNNING_TRIATHLETE_M   41
#define FACILITY_CLASS_RUNNING_TRIATHLETE_F   42
#define FACILITY_CLASS_SWIMMING_TRIATHLETE_M  43
#define FACILITY_CLASS_SWIMMING_TRIATHLETE_F  44
#define FACILITY_CLASS_DRAGON_TAMER           45
#define FACILITY_CLASS_RS_BIRD_KEEPER         46
#define FACILITY_CLASS_NINJA_BOY              47
#define FACILITY_CLASS_BATTLE_GIRL            48
#define FACILITY_CLASS_PARASOL_LADY           49
#define FACILITY_CLASS_RS_SWIMMER_F           50
#define FACILITY_CLASS_RS_PICNICKER           51
#define FACILITY_CLASS_RS_TWINS               52
#define FACILITY_CLASS_RS_SAILOR              53
#define FACILITY_CLASS_BOARDER_M              54
#define FACILITY_CLASS_BOARDER_F              55
#define FACILITY_CLASS_COLLECTOR              56
#define FACILITY_CLASS_PKMN_TRAINER_WALLY     57
#define FACILITY_CLASS_PKMN_TRAINER_BRENDAN   58
#define FACILITY_CLASS_PKMN_TRAINER_BRENDAN_2 59
#define FACILITY_CLASS_PKMN_TRAINER_BRENDAN_3 60
#define FACILITY_CLASS_PKMN_TRAINER_MAY       61
#define FACILITY_CLASS_PKMN_TRAINER_MAY_2     62
#define FACILITY_CLASS_PKMN_TRAINER_MAY_3     63
#define FACILITY_CLASS_RS_PKMN_BREEDER_M      64
#define FACILITY_CLASS_RS_PKMN_BREEDER_F      65
#define FACILITY_CLASS_RS_PKMN_RANGER_M       66
#define FACILITY_CLASS_RS_PKMN_RANGER_F       67
#define FACILITY_CLASS_MAGMA_LEADER_MAXIE     68
#define FACILITY_CLASS_MAGMA_GRUNT_M          69
#define FACILITY_CLASS_MAGMA_GRUNT_F          70
#define FACILITY_CLASS_RS_LASS                71
#define FACILITY_CLASS_RS_BUG_CATCHER         72
#define FACILITY_CLASS_RS_HIKER               73
#define FACILITY_CLASS_RS_YOUNG_COUPLE        74
#define FACILITY_CLASS_OLD_COUPLE             75
#define FACILITY_CLASS_RS_SIS_AND_BRO         76
#define FACILITY_CLASS_AQUA_ADMIN_M           77
#define FACILITY_CLASS_AQUA_ADMIN_F           78
#define FACILITY_CLASS_MAGMA_ADMIN_M          79
#define FACILITY_CLASS_MAGMA_ADMIN_F          80
#define FACILITY_CLASS_LEADER_WATTSON         81
#define FACILITY_CLASS_LEADER_FLANNERY        82
#define FACILITY_CLASS_LEADER_NORMAN          83
#define FACILITY_CLASS_LEADER_WINONA          84
#define FACILITY_CLASS_LEADER_WALLACE         85
#define FACILITY_CLASS_ELITE_FOUR_GLACIA      86
#define FACILITY_CLASS_ELITE_FOUR_DRAKE       87
#define FACILITY_CLASS_YOUNGSTER              88
#define FACILITY_CLASS_BUG_CATCHER            89
#define FACILITY_CLASS_LASS                   90
#define FACILITY_CLASS_SAILOR                 91
#define FACILITY_CLASS_CAMPER                 92
#define FACILITY_CLASS_PICNICKER              93
#define FACILITY_CLASS_POKEMANIAC             94
#define FACILITY_CLASS_SUPER_NERD             95
#define FACILITY_CLASS_HIKER                  96
#define FACILITY_CLASS_BIKER                  97
#define FACILITY_CLASS_BURGLAR                98
#define FACILITY_CLASS_ENGINEER               99
#define FACILITY_CLASS_FISHERMAN              100
#define FACILITY_CLASS_SWIMMER_M              101
#define FACILITY_CLASS_CUE_BALL               102
#define FACILITY_CLASS_GAMER                  103
#define FACILITY_CLASS_BEAUTY                 104
#define FACILITY_CLASS_SWIMMER_F              105
#define FACILITY_CLASS_PSYCHIC_M              106
#define FACILITY_CLASS_ROCKER                 107
#define FACILITY_CLASS_JUGGLER                108
#define FACILITY_CLASS_TAMER                  109
#define FACILITY_CLASS_BIRD_KEEPER            110
#define FACILITY_CLASS_BLACK_BELT             111
#define FACILITY_CLASS_RIVAL_EARLY            112
#define FACILITY_CLASS_SCIENTIST              113
#define FACILITY_CLASS_BOSS                   114
#define FACILITY_CLASS_ROCKET_GRUNT_M         115
#define FACILITY_CLASS_COOLTRAINER_M          116
#define FACILITY_CLASS_COOLTRAINER_F          117
#define FACILITY_CLASS_ELITE_FOUR_LORELEI     118
#define FACILITY_CLASS_ELITE_FOUR_BRUNO       119
#define FACILITY_CLASS_LEADER_M               120
#define FACILITY_CLASS_LEADER_F               121
#define FACILITY_CLASS_GENTLEMAN              122
#define FACILITY_CLASS_RIVAL_LATE             123
#define FACILITY_CLASS_CHAMPION_RIVAL         124
#define FACILITY_CLASS_CHANNELER              125
#define FACILITY_CLASS_TWINS                  126
#define FACILITY_CLASS_COOL_COUPLE            127
#define FACILITY_CLASS_YOUNG_COUPLE           128
#define FACILITY_CLASS_CRUSH_KIN              129
#define FACILITY_CLASS_SIS_AND_BRO            130
#define FACILITY_CLASS_PKMN_PROF              131
#define FACILITY_CLASS_BRENDAN                132
#define FACILITY_CLASS_MAY                    133
#define FACILITY_CLASS_RED                    134
#define FACILITY_CLASS_LEAF                   135
#define FACILITY_CLASS_ROCKET_GRUNT_F         136
#define FACILITY_CLASS_PSYCHIC_F              137
#define FACILITY_CLASS_CRUSH_GIRL             138
#define FACILITY_CLASS_TUBER                  139
#define FACILITY_CLASS_PKMN_BREEDER           140
#define FACILITY_CLASS_PKMN_RANGER_M          141
#define FACILITY_CLASS_PKMN_RANGER_F          142
#define FACILITY_CLASS_AROMA_LADY             143
#define FACILITY_CLASS_RUIN_MANIAC            144
#define FACILITY_CLASS_LADY                   145
#define FACILITY_CLASS_PAINTER                146
#define FACILITY_CLASS_ELITE_FOUR_AGATHA      147
#define FACILITY_CLASS_ELITE_FOUR_LANCE       148
#define FACILITY_CLASS_CHAMPION_RIVAL_2       149

#define TRAINER_GENDER_MALE   0
#define TRAINER_GENDER_FEMALE 1

// Trainer party defines
#define TRAINER_MON_MALE    1
#define TRAINER_MON_FEMALE  2
#define TRAINER_MON_RANDOM_GENDER 3

// All trainer parties specify the IV, level, and species for each Pokémon in the
// party. Some trainer parties also specify held items and custom moves for each
// Pokémon.
#define F_TRAINER_PARTY_CUSTOM_MOVESET (1 << 0)
#define F_TRAINER_PARTY_HELD_ITEM      (1 << 1)

#endif  // GUARD_CONSTANTS_TRAINERS_H
