#ifndef GUARD_TRAINERS_H
#define GUARD_TRAINERS_H

#define TRAINER_ENCOUNTER_MUSIC_MALE         0 // standard male encounter music
#define TRAINER_ENCOUNTER_MUSIC_FEMALE       1 // standard female encounter music
#define TRAINER_ENCOUNTER_MUSIC_GIRL         2 // used for male Tubers and Young Couples too
#define TRAINER_ENCOUNTER_MUSIC_SUSPICIOUS   3
#define TRAINER_ENCOUNTER_MUSIC_INTENSE      4
#define TRAINER_ENCOUNTER_MUSIC_COOL         5
#define TRAINER_ENCOUNTER_MUSIC_AQUA         6
#define TRAINER_ENCOUNTER_MUSIC_MAGMA        7
#define TRAINER_ENCOUNTER_MUSIC_SWIMMER      8
#define TRAINER_ENCOUNTER_MUSIC_TWINS        9 // used for other trainer classes too
#define TRAINER_ENCOUNTER_MUSIC_ELITE_FOUR  10
#define TRAINER_ENCOUNTER_MUSIC_HIKER       11 // used for other trainer classes too
#define TRAINER_ENCOUNTER_MUSIC_INTERVIEWER 12
#define TRAINER_ENCOUNTER_MUSIC_RICH        13 // Rich Boys and Gentlemen

#define F_TRAINER_FEMALE (1 << 7)

#define TRAINER_PIC_AQUA_LEADER 0
#define TRAINER_PIC_TEAM_AQUA 1
#define TRAINER_PIC_TEAM_AQUA_2 2
#define TRAINER_PIC_AROMA_LADY 3
#define TRAINER_PIC_RUIN_MANIAC 4
#define TRAINER_PIC_INTERVIEWER 5
#define TRAINER_PIC_TUBER 6
#define TRAINER_PIC_TUBER_2 7
#define TRAINER_PIC_COOLTRAINER 8
#define TRAINER_PIC_COOLTRAINER_2 9
#define TRAINER_PIC_HEX_MANIAC 10
#define TRAINER_PIC_LADY 11
#define TRAINER_PIC_BEAUTY 12
#define TRAINER_PIC_RICH_BOY 13
#define TRAINER_PIC_POKEMANIAC 14
#define TRAINER_PIC_SWIMMER_MALE 15
#define TRAINER_PIC_BLACK_BELT 16
#define TRAINER_PIC_GUITARIST 17
#define TRAINER_PIC_KINDLER 18
#define TRAINER_PIC_CAMPER 19
#define TRAINER_PIC_BUG_MANIAC 20
#define TRAINER_PIC_PSYCHIC 21
#define TRAINER_PIC_PSYCHIC_2 22
#define TRAINER_PIC_GENTLEMAN 23
#define TRAINER_PIC_SIDNEY 24
#define TRAINER_PIC_PHOEBE 25
#define TRAINER_PIC_ROXANNE 26
#define TRAINER_PIC_BRAWLY 27
#define TRAINER_PIC_TATE_LIZA 28
#define TRAINER_PIC_SCHOOL_KID 29
#define TRAINER_PIC_SCHOOL_KID_2 30
#define TRAINER_PIC_SR_AND_JR 31
#define TRAINER_PIC_POKEFAN 32
#define TRAINER_PIC_POKEFAN_2 33
#define TRAINER_PIC_EXPERT 34
#define TRAINER_PIC_EXPERT_2 35
#define TRAINER_PIC_BOARDER 36
#define TRAINER_PIC_CHAMPION 37
#define TRAINER_PIC_FISHERMAN 38
#define TRAINER_PIC_TRIATHLETE 39
#define TRAINER_PIC_TRIATHLETE_2 40
#define TRAINER_PIC_TRIATHLETE_3 41
#define TRAINER_PIC_TRIATHLETE_4 42
#define TRAINER_PIC_TRIATHLETE_5 43
#define TRAINER_PIC_TRIATHLETE_6 44
#define TRAINER_PIC_DRAGON_TAMER 45
#define TRAINER_PIC_BIRD_KEEPER 46
#define TRAINER_PIC_NINJA_BOY 47
#define TRAINER_PIC_BATTLE_GIRL 48
#define TRAINER_PIC_PARASOL_LADY 49
#define TRAINER_PIC_SWIMMER_FEMALE 50
#define TRAINER_PIC_PICNICKER 51
#define TRAINER_PIC_TWINS 52
#define TRAINER_PIC_SAILOR 53
#define TRAINER_PIC_COLLECTOR 54
#define TRAINER_PIC_PKMN_TRAINER 55
#define TRAINER_PIC_PKMN_TRAINER_2 56
#define TRAINER_PIC_PKMN_TRAINER_3 57
#define TRAINER_PIC_PKMN_BREEDER 58
#define TRAINER_PIC_PKMN_BREEDER_2 59
#define TRAINER_PIC_PKMN_RANGER 60
#define TRAINER_PIC_PKMN_RANGER_2 61
#define TRAINER_PIC_MAGMA_LEADER 62
#define TRAINER_PIC_TEAM_MAGMA 63
#define TRAINER_PIC_TEAM_MAGMA_2 64
#define TRAINER_PIC_LASS 65
#define TRAINER_PIC_BUG_CATCHER 66
#define TRAINER_PIC_HIKER 67
#define TRAINER_PIC_YOUNG_COUPLE 68
#define TRAINER_PIC_OLD_COUPLE 69
#define TRAINER_PIC_SIS_AND_BRO 70
#define TRAINER_PIC_MATT 71
#define TRAINER_PIC_SHELLY 72
#define TRAINER_PIC_TABITHA 73
#define TRAINER_PIC_COURTNEY 74
#define TRAINER_PIC_WATTSON 75
#define TRAINER_PIC_FLANNERY 76
#define TRAINER_PIC_NORMAN 77
#define TRAINER_PIC_WINONA 78
#define TRAINER_PIC_WALLACE 79
#define TRAINER_PIC_GLACIA 80
#define TRAINER_PIC_DRAKE 81
#define TRAINER_PIC_YOUNGSTER 82
#define TRAINER_PIC_BUG_CATCHER_2 83
#define TRAINER_PIC_LASS_2 84
#define TRAINER_PIC_SAILOR_2 85
#define TRAINER_PIC_CAMPER_2 86
#define TRAINER_PIC_PICNICKER_2 87
#define TRAINER_PIC_POKEMANIAC_2 88
#define TRAINER_PIC_SUPER_NERD 89
#define TRAINER_PIC_HIKER_2 90
#define TRAINER_PIC_BIKER 91
#define TRAINER_PIC_BURGLAR 92
#define TRAINER_PIC_ENGINEER 93
#define TRAINER_PIC_FISHERMAN_2 94
#define TRAINER_PIC_SWIMMER_MALE_2 95
#define TRAINER_PIC_CUE_BALL 96
#define TRAINER_PIC_GAMER 97
#define TRAINER_PIC_BEAUTY_2 98
#define TRAINER_PIC_SWIMMER_FEMALE_2 99
#define TRAINER_PIC_PSYCHIC_3 100
#define TRAINER_PIC_ROCKER 101
#define TRAINER_PIC_JUGGLER 102
#define TRAINER_PIC_TAMER 103
#define TRAINER_PIC_BIRD_KEEPER_2 104
#define TRAINER_PIC_BLACK_BELT_2 105
#define TRAINER_PIC_RIVAL 106
#define TRAINER_PIC_SCIENTIST 107
#define TRAINER_PIC_BOSS 108
#define TRAINER_PIC_TEAM_ROCKET 109
#define TRAINER_PIC_COOLTRAINER_3 110
#define TRAINER_PIC_COOLTRAINER_4 111
#define TRAINER_PIC_LORELEI 112
#define TRAINER_PIC_BRUNO 113
#define TRAINER_PIC_AGATHA 114
#define TRAINER_PIC_LANCE 115
#define TRAINER_PIC_BROCK 116
#define TRAINER_PIC_MISTY 117
#define TRAINER_PIC_LT_SURGE 118
#define TRAINER_PIC_ERIKA 119
#define TRAINER_PIC_KOGA 120
#define TRAINER_PIC_BLAINE 121
#define TRAINER_PIC_SABRINA 122
#define TRAINER_PIC_GENTLEMAN_2 123
#define TRAINER_PIC_RIVAL_2 124
#define TRAINER_PIC_RIVAL_3 125
#define TRAINER_PIC_CHANNELER 126
#define TRAINER_PIC_TWINS_2 127
#define TRAINER_PIC_COOL_COUPLE 128
#define TRAINER_PIC_YOUNG_COUPLE_2 129
#define TRAINER_PIC_CRUSH_KIN 130
#define TRAINER_PIC_SIS_AND_BRO_2 131
#define TRAINER_PIC_PROF_OAK 132
#define TRAINER_PIC_BRENDAN 133
#define TRAINER_PIC_MAY 134
#define TRAINER_PIC_RED 135
#define TRAINER_PIC_LEAF 136
#define TRAINER_PIC_TEAM_ROCKET_2 137
#define TRAINER_PIC_PSYCHIC_4 138
#define TRAINER_PIC_CRUSH_GIRL 139
#define TRAINER_PIC_TUBER_3 140
#define TRAINER_PIC_PKMN_BREEDER_3 141
#define TRAINER_PIC_PKMN_RANGER_3 142
#define TRAINER_PIC_PKMN_RANGER_4 143
#define TRAINER_PIC_AROMA_LADY_2 144
#define TRAINER_PIC_RUIN_MANIAC_2 145
#define TRAINER_PIC_LADY_2 146
#define TRAINER_PIC_PAINTER 147

// All trainer parties specify the IV, level, and species for each Pokémon in the
// party. Some trainer parties also specify held items and custom moves for each
// Pokémon.
#define F_TRAINER_PARTY_CUSTOM_MOVESET (1 << 0)
#define F_TRAINER_PARTY_HELD_ITEM      (1 << 1)

#endif  // GUARD_TRAINERS_H
