#ifndef GUARD_CONSTANTS_TRAINER_CARD_H
#define GUARD_CONSTANTS_TRAINER_CARD_H

#define TRAINER_CARD_PROFILE_LENGTH  4
#define TRAINER_CARD_STICKER_TYPES   3

#define CARD_TYPE_FRLG     0
#define CARD_TYPE_RSE      1

#define MON_ICON_TINT_NORMAL  0
#define MON_ICON_TINT_BLACK   1
#define MON_ICON_TINT_PINK    2
#define MON_ICON_TINT_SEPIA   3

#define NUM_LINK_TRAINER_CARD_CLASSES 8

#endif // GUARD_CONSTANTS_TRAINER_CARD_H
