SafariZone_West_MapScripts:: @ 81623C6
	.byte 0

SafariZone_West_EventScript_1623C7:: @ 81623C7
	msgbox gUnknown_817796E, MSGBOX_SIGN
	end

SafariZone_West_EventScript_1623D0:: @ 81623D0
	msgbox gUnknown_8177979, MSGBOX_SIGN
	end

SafariZone_West_EventScript_1623D9:: @ 81623D9
	msgbox gUnknown_81779F8, MSGBOX_SIGN
	end

SafariZone_West_EventScript_1623E2:: @ 81623E2
	msgbox gUnknown_8177A41, MSGBOX_SIGN
	end
