SafariZone_West_MapScripts:: @ 81623C6
	.byte 0

SafariZone_West_EventScript_1623C7:: @ 81623C7
	loadword 0, gUnknown_817796E
	callstd 3
	end

SafariZone_West_EventScript_1623D0:: @ 81623D0
	loadword 0, gUnknown_8177979
	callstd 3
	end

SafariZone_West_EventScript_1623D9:: @ 81623D9
	loadword 0, gUnknown_81779F8
	callstd 3
	end

SafariZone_West_EventScript_1623E2:: @ 81623E2
	loadword 0, gUnknown_8177A41
	callstd 3
	end
