SafariZone_West_Text_RestHouse:: @ 817796E
    .string "Rest House$"

SafariZone_West_Text_PleaseFindWardensLostTeeth:: @ 8177979
    .string "Request Notice\p"
    .string "Please find the Safari Warden's\n"
    .string "lost Gold Teeth.\l"
    .string "They're around here somewhere.\p"
    .string "Reward offered!\n"
    .string "Contact: Warden$"

SafariZone_West_Text_SearchForSecretHouse:: @ 81779F8
    .string "Trainer Tips\p"
    .string "Zone Exploration Campaign!\n"
    .string "The Search for the Secret House!$"

SafariZone_West_Text_AreaSign:: @ 8177A41
    .string "Area 3\n"
    .string "East: Center Area$"

