SafariZone_West_Text_RestHouse:: @ 817796E
    .string "REST HOUSE$"

SafariZone_West_Text_PleaseFindWardensLostTeeth:: @ 8177979
    .string "REQUEST NOTICE\p"
    .string "Please find the SAFARI WARDEN's\n"
    .string "lost GOLD TEETH.\l"
    .string "They're around here somewhere.\p"
    .string "Reward offered!\n"
    .string "Contact: WARDEN$"

SafariZone_West_Text_SearchForSecretHouse:: @ 81779F8
    .string "TRAINER TIPS\p"
    .string "Zone Exploration Campaign!\n"
    .string "The Search for the SECRET HOUSE!$"

SafariZone_West_Text_AreaSign:: @ 8177A41
    .string "AREA 3\n"
    .string "EAST: CENTER AREA$"

