SSAnne_CaptainsOffice4_EventObjects:
	object_event 1, 49, 0, 15, 0, 11, 0, 3, 17, 17, 0, 1, 0, 1, 0, SSAnne_CaptainsOffice4_EventScript_163FE6, 136, 0, 0
	object_event 2, 49, 0, 17, 0, 15, 0, 3, 10, 17, 0, 1, 0, 1, 0, SSAnne_CaptainsOffice4_EventScript_163FFD, 136, 0, 0
	object_event 3, 50, 0, 27, 0, 16, 0, 3, 9, 17, 0, 1, 0, 3, 0, SSAnne_CaptainsOffice4_EventScript_164087, 136, 0, 0
	object_event 4, 49, 0, 25, 0, 11, 0, 3, 10, 17, 0, 1, 0, 3, 0, SSAnne_CaptainsOffice4_EventScript_164014, 136, 0, 0
	object_event 5, 50, 0, 6, 0, 6, 0, 3, 16, 17, 0, 1, 0, 3, 0, SSAnne_CaptainsOffice4_EventScript_164070, 136, 0, 0
	object_event 6, 55, 0, 27, 0, 4, 0, 3, 9, 17, 0, 1, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F93, 0, 0, 0
	object_event 7, 92, 0, 8, 0, 25, 0, 3, 8, 17, 0, 0, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_1BED87, 500, 0, 0
	object_event 8, 92, 0, 17, 0, 3, 0, 0, 8, 17, 0, 0, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_1BED94, 501, 0, 0
	object_event 9, 92, 0, 1, 0, 16, 0, 3, 8, 17, 0, 0, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_1BEDA1, 502, 0, 0
	object_event 10, 92, 0, 4, 0, 5, 0, 3, 8, 17, 0, 0, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_1BEDAE, 503, 0, 0

SSAnne_CaptainsOffice4_MapWarps:
	warp_def 24, 25, 3, 0, 824

SSAnne_CaptainsOffice4_MapCoordEvents:
	coord_event 22, 11, 3, 0, 16520, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F81
	coord_event 23, 11, 3, 0, 16520, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F81
	coord_event 24, 11, 3, 0, 16520, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F81

SSAnne_CaptainsOffice4_MapBGEvents:
	bg_event 11, 2, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 26, 11, 0, 3, 0, SSAnne_CaptainsOffice4_EventScript_163F78
	bg_event 27, 2, 0, 7, 0, 8, 68, 1
	bg_event 7, 16, 0, 7, 0, 6, 69, 1
	bg_event 12, 2, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 10, 2, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 9, 2, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 8, 2, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 7, 2, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 11, 5, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 10, 5, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 11, 4, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 10, 4, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 8, 4, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 7, 4, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 8, 5, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 7, 5, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 5, 3, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 4, 3, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 5, 4, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 4, 4, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 3, 4, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 2, 4, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 2, 5, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A
	bg_event 3, 5, 0, 0, 0, SSAnne_CaptainsOffice4_EventScript_163F5A

SSAnne_CaptainsOffice4_MapEvents::
	map_events SSAnne_CaptainsOffice4_EventObjects, SSAnne_CaptainsOffice4_MapWarps, SSAnne_CaptainsOffice4_MapCoordEvents, SSAnne_CaptainsOffice4_MapBGEvents
