SSAnne_1F_Room6_Text_TakeAShortRest::
    .string "You look tired. Would you like to\n"
    .string "take a short rest?$"

SSAnne_1F_Room6_Text_GladEveryoneIsRefreshed::
    .string "I'm glad to see that everyone is\n"
    .string "looking refreshed and chipper.$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother::
    .string "Oh, I'm sorry for fussing over you.\n"
    .string "You look like my little brother…$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister::
    .string "Oh, I'm sorry for fussing over you.\n"
    .string "You look like my little sister…$"

