CinnabarIsland_PokemonLab_ResearchRoom_MapScripts:: @ 816E3DE
	.byte 0

CinnabarIsland_PokemonLab_ResearchRoom_EventScript_16E3DF:: @ 816E3DF
	goto EventScript_1C4C8E
	end

CinnabarIsland_PokemonLab_ResearchRoom_EventScript_16E3E5:: @ 816E3E5
	loadword 0, gUnknown_819A015
	callstd 2
	end

CinnabarIsland_PokemonLab_ResearchRoom_EventScript_16E3EE:: @ 816E3EE
	loadword 0, gUnknown_819A04A
	callstd 3
	end

CinnabarIsland_PokemonLab_ResearchRoom_EventScript_16E3F7:: @ 816E3F7
	loadword 0, gUnknown_819A128
	callstd 3
	end
