CinnabarIsland_PokemonLab_ResearchRoom_MapScripts:: @ 816E3DE
	.byte 0

CinnabarIsland_PokemonLab_ResearchRoom_EventScript_16E3DF:: @ 816E3DF
	goto EventScript_1C4C8E
	end

CinnabarIsland_PokemonLab_ResearchRoom_EventScript_16E3E5:: @ 816E3E5
	msgbox gUnknown_819A015, MSGBOX_NPC
	end

CinnabarIsland_PokemonLab_ResearchRoom_EventScript_16E3EE:: @ 816E3EE
	msgbox gUnknown_819A04A, MSGBOX_SIGN
	end

CinnabarIsland_PokemonLab_ResearchRoom_EventScript_16E3F7:: @ 816E3F7
	msgbox gUnknown_819A128, MSGBOX_SIGN
	end
