Route4_PokemonCenter_1F_EventObjects:
	object_event 1, 64, 0, 7, 0, 2, 0, 0, 8, 17, 0, 0, 0, 0, 0, Route4_PokemonCenter_1F_EventScript_16F8BB, 0, 0, 0
	object_event 2, 30, 0, 1, 0, 3, 0, 3, 1, 17, 0, 0, 0, 0, 0, Route4_PokemonCenter_1F_EventScript_16F75F, 0, 0, 0
	object_event 3, 61, 0, 12, 0, 5, 0, 3, 8, 17, 0, 0, 0, 0, 0, Route4_PokemonCenter_1F_EventScript_16F754, 0, 0, 0
	object_event 4, 19, 0, 5, 0, 4, 0, 3, 2, 17, 0, 0, 0, 0, 0, Route4_PokemonCenter_1F_EventScript_16F74B, 0, 0, 0
	object_event 5, 18, 0, 14, 0, 4, 0, 3, 1, 17, 0, 0, 0, 0, 0, Route4_PokemonCenter_1F_EventScript_16F8C4, 0, 0, 0
	object_event 6, 105, 0, 12, 0, 6, 0, 0, 8, 17, 0, 0, 0, 0, 0, Route4_PokemonCenter_1F_EventScript_16F8CD, 0, 0, 0

Route4_PokemonCenter_1F_MapWarps:
	warp_def 6, 8, 3, 2, 790
	warp_def 7, 8, 3, 2, 790
	warp_def 8, 8, 3, 2, 790
	warp_def 1, 6, 4, 0, 4097

Route4_PokemonCenter_1F_MapEvents::
	map_events Route4_PokemonCenter_1F_EventObjects, Route4_PokemonCenter_1F_MapWarps, 0x0, 0x0
