Route4_PokemonCenter_1F_Text_CanHaveSixMonsWithYou:: @ 819D9D4
    .string "Okay, set six POKé BALLS in my\n"
    .string "belt…\p"
    .string "Yeah, that'll do it. At most, you\n"
    .string "can have six POKéMON with you.$"

Route4_PokemonCenter_1F_Text_TeamRocketAttacksCerulean:: @ 819DA3A
    .string "TEAM ROCKET attacks CERULEAN\n"
    .string "citizens…\p"
    .string "Not a day goes by without TEAM\n"
    .string "ROCKET being in the news.$"

Route4_PokemonCenter_1F_Text_LaddieBuyMagikarpForJust500:: @ 819DA9A
    .string "MAN: Hello there, laddie!\n"
    .string "Have I got a deal just for you!\p"
    .string "I'll let you have a secret POKéMON\n"
    .string "- a MAGIKARP - for just ¥500!\p"
    .string "So, you'll buy it, am I right?$"

Route4_PokemonCenter_1F_Text_SweetieBuyMagikarpForJust500:: @ 819DB34
    .string "MAN: Hello there, sweetie pie!\n"
    .string "Have I got a deal just for you!\p"
    .string "I'll let you have a secret POKéMON\n"
    .string "- a MAGIKARP - for just ¥500!\p"
    .string "So, you'll buy it, am I right?$"

Route4_PokemonCenter_1F_Text_PaidOutrageouslyForMagikarp:: @ 819DBD3
    .string "{PLAYER} paid an outrageous ¥500\n"
    .string "and bought the MAGIKARP…$"

Route4_PokemonCenter_1F_Text_OnlyDoingThisAsFavorToYou:: @ 819DC07
    .string "No? You say no? I'm only doing this\n"
    .string "as a favor to you!$"

Route4_PokemonCenter_1F_Text_NoRoomForMorePokemon:: @ 819DC3E
    .string "There's no more room for any more\n"
    .string "POKéMON, it looks like.$"

Route4_PokemonCenter_1F_Text_YoullNeedMoreMoney:: @ 819DC78
    .string "You'll need more money than that!$"

Route4_PokemonCenter_1F_Text_IDontGiveRefunds:: @ 819DC9A
    .string "MAN: Well, I don't give refunds.\n"
    .string "You knew what you were getting!$"

Route4_PokemonCenter_1F_Text_ShouldStoreMonsUsingPC:: @ 819DCDB
    .string "Sometimes, you'll have too many\n"
    .string "POKéMON with you to add any more.\p"
    .string "In that case, you should just\n"
    .string "store some using any PC.$"

Route4_PokemonCenter_1F_Text_ItsANewspaper:: @ 819DD54
    .string "It's a newspaper.$"

