Route4_PokemonCenter_1F_Text_CanHaveSixMonsWithYou::
    .string "Okay, set six POKé BALLS in my\n"
    .string "belt…\p"
    .string "Yeah, that'll do it. At most, you\n"
    .string "can have six POKéMON with you.$"

Route4_PokemonCenter_1F_Text_TeamRocketAttacksCerulean::
    .string "TEAM ROCKET attacks CERULEAN\n"
    .string "citizens…\p"
    .string "Not a day goes by without TEAM\n"
    .string "ROCKET being in the news.$"

Route4_PokemonCenter_1F_Text_LaddieBuyMagikarpForJust500::
    .string "MAN: Hello there, laddie!\n"
    .string "Have I got a deal just for you!\p"
    .string "I'll let you have a secret POKéMON\n"
    .string "- a MAGIKARP - for just ¥500!\p"
    .string "So, you'll buy it, am I right?$"

Route4_PokemonCenter_1F_Text_SweetieBuyMagikarpForJust500::
    .string "MAN: Hello there, sweetie pie!\n"
    .string "Have I got a deal just for you!\p"
    .string "I'll let you have a secret POKéMON\n"
    .string "- a MAGIKARP - for just ¥500!\p"
    .string "So, you'll buy it, am I right?$"

Route4_PokemonCenter_1F_Text_PaidOutrageouslyForMagikarp::
    .string "{PLAYER} paid an outrageous ¥500\n"
    .string "and bought the MAGIKARP…$"

Route4_PokemonCenter_1F_Text_OnlyDoingThisAsFavorToYou::
    .string "No? You say no? I'm only doing this\n"
    .string "as a favor to you!$"

Route4_PokemonCenter_1F_Text_NoRoomForMorePokemon::
    .string "There's no more room for any more\n"
    .string "POKéMON, it looks like.$"

Route4_PokemonCenter_1F_Text_YoullNeedMoreMoney::
    .string "You'll need more money than that!$"

Route4_PokemonCenter_1F_Text_IDontGiveRefunds::
    .string "MAN: Well, I don't give refunds.\n"
    .string "You knew what you were getting!$"

Route4_PokemonCenter_1F_Text_ShouldStoreMonsUsingPC::
    .string "Sometimes, you'll have too many\n"
    .string "POKéMON with you to add any more.\p"
    .string "In that case, you should just\n"
    .string "store some using any PC.$"

Route4_PokemonCenter_1F_Text_ItsANewspaper::
    .string "It's a newspaper.$"

