PokemonLeague_BrunosRoom_Text_Intro::
    .string "I am BRUNO of the ELITE FOUR!\p"
    .string "Through rigorous training, people\n"
    .string "and POKéMON can become stronger\l"
    .string "without limit.\p"
    .string "I've lived and trained with my\n"
    .string "fighting POKéMON!\l"
    .string "And that will never change!\p"
    .string "{PLAYER}!\p"
    .string "We will grind you down with our\n"
    .string "superior power!\p"
    .string "Hoo hah!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_RematchIntro::
    .string "I am BRUNO of the ELITE FOUR!\p"
    .string "Through rigorous training, people\n"
    .string "and POKéMON can become stronger\l"
    .string "without limit.\p"
    .string "I've lived and trained with my\n"
    .string "fighting POKéMON!\l"
    .string "And that will never change!\p"
    .string "{PLAYER}!\p"
    .string "We will grind you down with our\n"
    .string "superior power!\p"
    .string "Hoo hah!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_Defeat::
    .string "Why?\n"
    .string "How could I lose?$"

PokemonLeague_BrunosRoom_Text_PostBattle::
    .string "My job is done.\n"
    .string "Go face your next challenge.$"

