SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
    .string "Captain: Ooargh…\n"
    .string "I feel hideous…\l"
    .string "Urrp! Seasick…$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
    .string "{PLAYER} rubbed the Captain's\n"
    .string "back!\p"
    .string "Rub-rub…\n"
    .string "Rub-rub…$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
    .string "Captain: Whew! Thank you!\n"
    .string "I'm feeling much better now.\p"
    .string "You want to see my hidden Cut\n"
    .string "technique?\p"
    .string "I could show you my prized Cut\n"
    .string "technique if I weren't so ill…\p"
    .string "I know! You can have this!\n"
    .string "This Hidden Machine!\p"
    .string "Teach Cut to your Pokémon, and\n"
    .string "you can see it Cut anytime!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
    .string "{PLAYER} obtained HM01\n"
    .string "from the Captain!$"

SSAnne_CaptainsOffice_Text_ExplainCut::
    .string "Using Cut, you can chop down\n"
    .string "small trees.\p"
    .string "Why not try it with the trees\n"
    .string "around Vermilion City?$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
    .string "Captain: …Whew!\p"
    .string "Now that I'm not sick anymore,\n"
    .string "I guess it's time.\p"
    .string "The S.S. Anne will set sail soon!\p"
    .string "Farewell, until our return to\n"
    .string "Vermilion City!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
    .string "Oh, no!\n"
    .string "You have no room for this!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
    .string "Yuck!\n"
    .string "Shouldn't have looked!$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
    .string "How to Conquer Seasickness…\n"
    .string "The Captain's reading this!$"

