SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick:: @ 8173646
    .string "Captain: Ooargh…\n"
    .string "I feel hideous…\l"
    .string "Urrp! Seasick…$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack:: @ 8173676
    .string "{PLAYER} rubbed the Captain's\n"
    .string "back!\p"
    .string "Rub-rub…\n"
    .string "Rub-rub…$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut:: @ 81736A6
    .string "Captain: Whew! Thank you!\n"
    .string "I'm feeling much better now.\p"
    .string "You want to see my hidden Cut\n"
    .string "technique?\p"
    .string "I could show you my prized Cut\n"
    .string "technique if I weren't so ill…\p"
    .string "I know! You can have this!\n"
    .string "This Hidden Machine!\p"
    .string "Teach Cut to your Pokémon, and\n"
    .string "you can see it Cut anytime!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain:: @ 81737AF
    .string "{PLAYER} obtained HM01\n"
    .string "from the Captain!$"

SSAnne_CaptainsOffice_Text_ExplainCut:: @ 81737D2
    .string "Using Cut, you can chop down\n"
    .string "small trees.\p"
    .string "Why not try it with the trees\n"
    .string "around Vermilion City?$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon:: @ 8173831
    .string "Captain: …Whew!\p"
    .string "Now that I'm not sick anymore,\n"
    .string "I guess it's time.\p"
    .string "The S.S. Anne will set sail soon!\p"
    .string "Farewell, until our return to\n"
    .string "Vermilion City!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis:: @ 81738C3
    .string "Oh, no!\n"
    .string "You have no room for this!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked:: @ 81738E6
    .string "Yuck!\n"
    .string "Shouldn't have looked!$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness:: @ 8173903
    .string "How to Conquer Seasickness…\n"
    .string "The Captain's reading this!$"

