SevenIsland_TrainerTower_3F_MapScripts:: @ 8164714
	map_script MAP_SCRIPT_ON_RESUME, SevenIsland_TrainerTower_3F_MapScript1_1C4F54
	map_script MAP_SCRIPT_ON_TRANSITION, SevenIsland_TrainerTower_3F_MapScript2_1C4F62
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SevenIsland_TrainerTower_3F_MapScript3_1C5046
	.byte 0

SevenIsland_TrainerTower_3F_EventScript_164724:: @ 8164724
	call EventScript_1C52F4
	end

EventScript_16472A:: @ 816472A
	call EventScript_1C533B
	end

EventScript_164730:: @ 8164730
	call EventScript_1C5382
	end

EventScript_164736:: @ 8164736
	call EventScript_1C538C
	end

EventScript_16473C:: @ 816473C
	call EventScript_1C53AA
	end
