gUnknown_817696D:: @ 817696D
    .string "I wonder if SILPH is finished…$"

gUnknown_817698C:: @ 817698C
    .string "Thanks for saving us!$"

Text_1769A2:: @ 81769A2
    .string "That's as far as you'll go!$"

Text_1769BE:: @ 81769BE
    .string "Not enough grit!$"

gUnknown_81769CF:: @ 81769CF
    .string "If you don't turn back…\n"
    .string "I'll call for backup!$"

Text_1769FD:: @ 81769FD
    .string "You're causing us problems!$"

Text_176A19:: @ 8176A19
    .string "Huh?\n"
    .string "I lost?$"

gUnknown_8176A26:: @ 8176A26
    .string "So, what do you think of SILPH\n"
    .string "BUILDING's maze?$"

Text_176A56:: @ 8176A56
    .string "I am one of the four ROCKET\n"
    .string "BROTHERS!$"

Text_176A7C:: @ 8176A7C
    .string "Whoo!\n"
    .string "Oh, Brothers!$"

gUnknown_8176A90:: @ 8176A90
    .string "I'll leave you up to my brothers.$"

gUnknown_8176AB2:: @ 8176AB2
    .string "SILPH CO. HEAD OFFICE\n"
    .string "8F$"

