SSAnne_2F_Room4_EventObjects:
	object_event 1, 61, 0, 0, 0, 5, 0, 3, 10, 17, 0, 1, 0, 3, 0, SSAnne_2F_Room4_EventScript_160CF3, 0, 0, 0
	object_event 2, 22, 0, 3, 0, 3, 0, 3, 8, 17, 0, 1, 0, 3, 0, SSAnne_2F_Room4_EventScript_160D0A, 0, 0, 0
	object_event 3, 92, 0, 2, 0, 4, 0, 3, 8, 17, 0, 0, 0, 0, 0, SSAnne_2F_Room4_EventScript_1BE678, 358, 0, 0

SSAnne_2F_Room4_MapWarps:
	warp_def 4, 7, 3, 6, 262

SSAnne_2F_Room4_MapEvents::
	map_events SSAnne_2F_Room4_EventObjects, SSAnne_2F_Room4_MapWarps, 0x0, 0x0
