Text_173F07:: @ 8173F07
    .string "Which do you find more worthy,\n"
    .string "a strong or a rare POKéMON?$"

Text_173F42:: @ 8173F42
    .string "I must salute you!$"

gUnknown_8173F55:: @ 8173F55
    .string "Personally, I prefer strong and\n"
    .string "rare POKéMON.$"

Text_173F83:: @ 8173F83
    .string "I don't believe I saw you at the\n"
    .string "party?$"

Text_173FAB:: @ 8173FAB
    .string "Take it easy!$"

gUnknown_8173FB9:: @ 8173FB9
    .string "Oh, I adore your strong POKéMON!\n"
    .string "Oh, how I envy you for them!$"

