SSAnne_2F_Room4_Text_LamarIntro:: @ 8173F07
    .string "Which do you find more worthy,\n"
    .string "a strong or a rare POKéMON?$"

SSAnne_2F_Room4_Text_LamarDefeat:: @ 8173F42
    .string "I must salute you!$"

SSAnne_2F_Room4_Text_LamarPostBattle:: @ 8173F55
    .string "Personally, I prefer strong and\n"
    .string "rare POKéMON.$"

SSAnne_2F_Room4_Text_DawnIntro:: @ 8173F83
    .string "I don't believe I saw you at the\n"
    .string "party?$"

SSAnne_2F_Room4_Text_DawnDefeat:: @ 8173FAB
    .string "Take it easy!$"

SSAnne_2F_Room4_Text_DawnPostBattle:: @ 8173FB9
    .string "Oh, I adore your strong POKéMON!\n"
    .string "Oh, how I envy you for them!$"

