SafariZone_East_Text_KeepAnyItemFoundOnSafari::
    .string "You can keep any item you find in\n"
    .string "the Safari Zone.\p"
    .string "But, you'll run out of time if you\n"
    .string "try for all of them at once.$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
    .string "Go to the deepest part of the\n"
    .string "Safari Zone. You will win a prize!$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
    .string "My Eevee evolved into Flareon.\p"
    .string "But, a friend's Eevee turned into a\n"
    .string "Vaporeon. I wonder why?$"

