ThreeIsland_PokemonCenter_1F_EventObjects:
	object_event 1, 64, 0, 7, 0, 2, 0, 0, 8, 17, 0, 0, 0, 0, 0, ThreeIsland_PokemonCenter_1F_EventScript_171841, 0, 0, 0
	object_event 2, 26, 0, 12, 0, 2, 0, 3, 8, 17, 0, 0, 0, 0, 0, ThreeIsland_PokemonCenter_1F_EventScript_17185C, 0, 0, 0
	object_event 3, 22, 0, 3, 0, 4, 0, 3, 5, 17, 0, 0, 0, 0, 0, ThreeIsland_PokemonCenter_1F_EventScript_171853, 0, 0, 0
	object_event 4, 62, 0, 11, 0, 5, 0, 3, 8, 17, 0, 0, 0, 0, 0, ThreeIsland_PokemonCenter_1F_EventScript_17184A, 0, 0, 0

ThreeIsland_PokemonCenter_1F_MapWarps:
	warp_def 7, 8, 3, 1, 782
	warp_def 1, 6, 4, 0, 8706

ThreeIsland_PokemonCenter_1F_MapEvents::
	map_events ThreeIsland_PokemonCenter_1F_EventObjects, ThreeIsland_PokemonCenter_1F_MapWarps, 0x0, 0x0
