OneIsland_KindleRoad_EventObjects:
	object_event 1, 44, 0, 11, 0, 32, 0, 1, 14, 17, 0, 1, 0, 4, 0, OneIsland_KindleRoad_EventScript_1ABBF1, 0, 0, 0
	object_event 2, 46, 0, 17, 0, 132, 0, 3, 8, 17, 0, 1, 0, 2, 0, OneIsland_KindleRoad_EventScript_1ABC2F, 0, 0, 0
	object_event 3, 43, 0, 7, 0, 39, 0, 1, 52, 54, 0, 1, 0, 1, 0, OneIsland_KindleRoad_EventScript_1ABC6D, 0, 0, 0
	object_event 4, 45, 0, 19, 0, 79, 0, 3, 8, 17, 0, 1, 0, 1, 0, OneIsland_KindleRoad_EventScript_1ABCAB, 0, 0, 0
	object_event 5, 57, 0, 15, 0, 25, 0, 3, 9, 17, 0, 1, 0, 0, 0, OneIsland_KindleRoad_EventScript_1ABCE9, 0, 0, 0
	object_event 6, 24, 0, 9, 0, 53, 0, 3, 26, 113, 0, 1, 0, 1, 0, OneIsland_KindleRoad_EventScript_1ABD27, 0, 0, 0
	object_event 7, 24, 0, 18, 0, 105, 0, 4, 50, 65, 0, 1, 0, 1, 0, OneIsland_KindleRoad_EventScript_1ABD65, 0, 0, 0
	object_event 8, 54, 0, 16, 0, 64, 0, 3, 27, 18, 0, 1, 0, 1, 0, OneIsland_KindleRoad_EventScript_1ABDA3, 0, 0, 0
	object_event 9, 54, 0, 11, 0, 64, 0, 3, 28, 18, 0, 1, 0, 1, 0, OneIsland_KindleRoad_EventScript_1ABDE1, 0, 0, 0
	object_event 10, 39, 0, 11, 0, 89, 0, 3, 14, 17, 0, 1, 0, 3, 0, OneIsland_KindleRoad_EventScript_1ABE1F, 0, 0, 0
	object_event 11, 40, 0, 9, 0, 108, 0, 3, 1, 17, 0, 1, 0, 1, 0, OneIsland_KindleRoad_EventScript_1ABE5D, 0, 0, 0
	object_event 12, 54, 0, 8, 0, 68, 0, 3, 8, 17, 0, 1, 0, 1, 0, OneIsland_KindleRoad_EventScript_1ABEE1, 0, 0, 0
	object_event 13, 24, 0, 9, 0, 68, 0, 3, 8, 17, 0, 1, 0, 1, 0, OneIsland_KindleRoad_EventScript_1ABE9B, 0, 0, 0
	object_event 14, 96, 0, 8, 0, 104, 0, 3, 1, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EventScript_1BE00C, 19, 0, 0
	object_event 15, 96, 0, 11, 0, 95, 0, 3, 1, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EventScript_1BE00C, 21, 0, 0
	object_event 16, 96, 0, 12, 0, 96, 0, 3, 1, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EventScript_1BE00C, 22, 0, 0
	object_event 17, 96, 0, 10, 0, 95, 0, 3, 1, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EventScript_1BE00C, 23, 0, 0
	object_event 18, 96, 0, 9, 0, 105, 0, 3, 1, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EventScript_1BE00C, 24, 0, 0
	object_event 19, 96, 0, 15, 0, 75, 0, 3, 1, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EventScript_1BE00C, 25, 0, 0
	object_event 20, 96, 0, 9, 0, 84, 0, 3, 1, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EventScript_1BE00C, 26, 0, 0
	object_event 21, 96, 0, 15, 0, 74, 0, 3, 1, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EventScript_1BE00C, 27, 0, 0
	object_event 22, 96, 0, 15, 0, 73, 0, 3, 1, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EventScript_1BE00C, 28, 0, 0
	object_event 23, 96, 0, 18, 0, 111, 0, 4, 1, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EventScript_1BE00C, 29, 0, 0
	object_event 24, 96, 0, 10, 0, 86, 0, 3, 1, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EventScript_1BE00C, 30, 0, 0
	object_event 25, 96, 0, 9, 0, 110, 0, 3, 1, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EventScript_1BE00C, 31, 0, 0
	object_event 26, 96, 0, 18, 0, 112, 0, 4, 1, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EventScript_1BE00C, 17, 0, 0
	object_event 27, 92, 0, 15, 0, 70, 0, 3, 8, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EventScript_1BEC42, 475, 0, 0
	object_event 28, 92, 0, 17, 0, 103, 0, 3, 8, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EventScript_1BEC4F, 476, 0, 0
	object_event 29, 92, 0, 18, 0, 114, 0, 4, 8, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EventScript_1BEC5C, 477, 0, 0

OneIsland_KindleRoad_MapWarps:
	warp_def 11, 6, 3, 0, 353
	warp_def 12, 6, 3, 1, 353
	warp_def 15, 58, 3, 0, 569

OneIsland_KindleRoad_MapBGEvents:
	bg_event 13, 59, 0, 0, 0, OneIsland_KindleRoad_EventScript_168762
	bg_event 8, 115, 0, 0, 0, OneIsland_KindleRoad_EventScript_168759

OneIsland_KindleRoad_MapEvents::
	map_events OneIsland_KindleRoad_EventObjects, OneIsland_KindleRoad_MapWarps, 0x0, OneIsland_KindleRoad_MapBGEvents
