# 1 "data/maps/OneIsland_KindleRoad/scripts.pory"

# 2 "data/maps/OneIsland_KindleRoad/scripts.pory"
OneIsland_KindleRoad_MapScripts::
# 3 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.byte 0
# 4 "data/maps/OneIsland_KindleRoad/scripts.pory"

# 5 "data/maps/OneIsland_KindleRoad/scripts.pory"
OneIsland_KindleRoad_EventScript_RouteSign::
# 6 "data/maps/OneIsland_KindleRoad/scripts.pory"
	msgbox OneIsland_KindleRoad_Text_RouteSign, MSGBOX_SIGN
# 7 "data/maps/OneIsland_KindleRoad/scripts.pory"
	end
# 8 "data/maps/OneIsland_KindleRoad/scripts.pory"

# 9 "data/maps/OneIsland_KindleRoad/scripts.pory"
OneIsland_KindleRoad_EventScript_EmberSpaSign::
# 10 "data/maps/OneIsland_KindleRoad/scripts.pory"
	msgbox OneIsland_KindleRoad_Text_EmberSpaSign, MSGBOX_SIGN
# 11 "data/maps/OneIsland_KindleRoad/scripts.pory"
	end
