SevenIsland_SeavaultCanyon_TanobyKey_EventObjects:
	object_event 1, 97, 0, 7, 0, 6, 0, 3, 1, 0, 0, 0, 0, 0, 0, SevenIsland_SeavaultCanyon_TanobyKey_EventScript_1BE11D, 0, 0, 0
	object_event 2, 97, 0, 8, 0, 6, 0, 3, 1, 0, 0, 0, 0, 0, 0, SevenIsland_SeavaultCanyon_TanobyKey_EventScript_1BE11D, 0, 0, 0
	object_event 3, 97, 0, 8, 0, 9, 0, 3, 1, 0, 0, 0, 0, 0, 0, SevenIsland_SeavaultCanyon_TanobyKey_EventScript_1BE11D, 0, 0, 0
	object_event 4, 97, 0, 6, 0, 10, 0, 3, 1, 0, 0, 0, 0, 0, 0, SevenIsland_SeavaultCanyon_TanobyKey_EventScript_1BE11D, 0, 0, 0
	object_event 5, 97, 0, 8, 0, 10, 0, 3, 1, 0, 0, 0, 0, 0, 0, SevenIsland_SeavaultCanyon_TanobyKey_EventScript_1BE11D, 0, 0, 0
	object_event 6, 97, 0, 6, 0, 9, 0, 3, 1, 0, 0, 0, 0, 0, 0, SevenIsland_SeavaultCanyon_TanobyKey_EventScript_1BE11D, 0, 0, 0
	object_event 7, 97, 0, 6, 0, 6, 0, 3, 1, 0, 0, 0, 0, 0, 0, SevenIsland_SeavaultCanyon_TanobyKey_EventScript_1BE11D, 0, 0, 0

SevenIsland_SeavaultCanyon_TanobyKey_MapWarps:
	warp_def 7, 13, 3, 0, 832

SevenIsland_SeavaultCanyon_TanobyKey_MapCoordEvents:
	coord_event 7, 2, 3, 0, 16385, 99, 0, SevenIsland_SeavaultCanyon_TanobyKey_EventScript_164E39
	coord_event 9, 8, 3, 0, 16391, 99, 0, SevenIsland_SeavaultCanyon_TanobyKey_EventScript_164F0B
	coord_event 5, 8, 3, 0, 16390, 99, 0, SevenIsland_SeavaultCanyon_TanobyKey_EventScript_164EE8
	coord_event 9, 6, 3, 0, 16389, 99, 0, SevenIsland_SeavaultCanyon_TanobyKey_EventScript_164EC5
	coord_event 5, 6, 3, 0, 16388, 99, 0, SevenIsland_SeavaultCanyon_TanobyKey_EventScript_164EA2
	coord_event 10, 4, 3, 0, 16387, 99, 0, SevenIsland_SeavaultCanyon_TanobyKey_EventScript_164E7F
	coord_event 4, 4, 3, 0, 16386, 99, 0, SevenIsland_SeavaultCanyon_TanobyKey_EventScript_164E5C

SevenIsland_SeavaultCanyon_TanobyKey_MapEvents::
	map_events SevenIsland_SeavaultCanyon_TanobyKey_EventObjects, SevenIsland_SeavaultCanyon_TanobyKey_MapWarps, SevenIsland_SeavaultCanyon_TanobyKey_MapCoordEvents, 0x0
