PokemonTower_4F_EventObjects:
	object_event 1, 58, 0, 17, 0, 7, 0, 3, 8, 17, 0, 1, 0, 3, 0, PokemonTower_4F_EventScript_163404, 0, 0, 0
	object_event 2, 58, 0, 15, 0, 13, 0, 3, 9, 17, 0, 1, 0, 5, 0, PokemonTower_4F_EventScript_16341B, 0, 0, 0
	object_event 3, 58, 0, 4, 0, 12, 0, 3, 10, 17, 0, 1, 0, 2, 0, PokemonTower_4F_EventScript_1633ED, 0, 0, 0
	object_event 4, 92, 0, 12, 0, 11, 0, 3, 8, 17, 0, 0, 0, 0, 0, PokemonTower_4F_EventScript_1BE762, 376, 0, 0
	object_event 5, 92, 0, 8, 0, 11, 0, 3, 8, 17, 0, 0, 0, 0, 0, PokemonTower_4F_EventScript_1BE76F, 377, 0, 0
	object_event 6, 92, 0, 11, 0, 16, 0, 3, 8, 17, 0, 0, 0, 0, 0, PokemonTower_4F_EventScript_1BE77C, 378, 0, 0

PokemonTower_4F_MapWarps:
	warp_def 4, 10, 3, 0, 348
	warp_def 18, 10, 3, 1, 346

PokemonTower_4F_MapEvents::
	map_events PokemonTower_4F_EventObjects, PokemonTower_4F_MapWarps, 0x0, 0x0
