PokemonTower_4F_MapScripts:: @ 81633EC
	.byte 0

PokemonTower_4F_EventScript_1633ED:: @ 81633ED
	trainerbattle_single TRAINER_CHANNELER_PAULA, Text_17A004, Text_17A017
	msgbox gUnknown_817A02B, MSGBOX_AUTOCLOSE
	end

PokemonTower_4F_EventScript_163404:: @ 8163404
	trainerbattle_single TRAINER_CHANNELER_LAUREL, Text_17A046, Text_17A061
	msgbox gUnknown_817A067, MSGBOX_AUTOCLOSE
	end

PokemonTower_4F_EventScript_16341B:: @ 816341B
	trainerbattle_single TRAINER_CHANNELER_JODY, Text_17A096, Text_17A0AB
	msgbox gUnknown_817A0BB, MSGBOX_AUTOCLOSE
	end
