PokemonTower_4F_MapScripts:: @ 81633EC
	.byte 0

PokemonTower_4F_EventScript_1633ED:: @ 81633ED
	trainerbattle 0, 444, 0, Text_17A004, Text_17A017
	loadword 0, gUnknown_817A02B
	callstd 6
	end

PokemonTower_4F_EventScript_163404:: @ 8163404
	trainerbattle 0, 445, 0, Text_17A046, Text_17A061
	loadword 0, gUnknown_817A067
	callstd 6
	end

PokemonTower_4F_EventScript_16341B:: @ 816341B
	trainerbattle 0, 446, 0, Text_17A096, Text_17A0AB
	loadword 0, gUnknown_817A0BB
	callstd 6
	end
