PokemonTower_4F_Text_PaulaIntro:: @ 817A004
    .string "Ghost! No!\n"
    .string "Kwaaah!$"

PokemonTower_4F_Text_PaulaDefeat:: @ 817A017
    .string "Where is the ghost?$"

PokemonTower_4F_Text_PaulaPostBattle:: @ 817A02B
    .string "I must have been dreaming…$"

PokemonTower_4F_Text_LaurelIntro:: @ 817A046
    .string "Be cursed with me!\n"
    .string "Kwaaah!$"

PokemonTower_4F_Text_LaurelDefeat:: @ 817A061
    .string "What!$"

PokemonTower_4F_Text_LaurelPostBattle:: @ 817A067
    .string "We can't determine the identity of\n"
    .string "the ghosts…$"

PokemonTower_4F_Text_JodyIntro:: @ 817A096
    .string "Huhuhu…\n"
    .string "Beat me not!$"

PokemonTower_4F_Text_JodyDefeat:: @ 817A0AB
    .string "Huh?\n"
    .string "Who? What?$"

PokemonTower_4F_Text_JodyPostBattle:: @ 817A0BB
    .string "May the departed POKéMON rest in\n"
    .string "peace…$"

