SilphCo_5F_Text_RocketsInUproarAboutIntruder:: @ 8175B70
    .string "TEAM ROCKET is in an uproar over\n"
    .string "some intruder.\p"
    .string "That's you, right?$"

SilphCo_5F_Text_YoureOurHeroThankYou:: @ 8175BB3
    .string "TEAM ROCKET took off!\n"
    .string "You're our hero! Thank you!$"

SilphCo_5F_Text_Grunt1Intro:: @ 8175BE5
    .string "I heard a kid was wandering\n"
    .string "around.$"

SilphCo_5F_Text_Grunt1Defeat:: @ 8175C09
    .string "Boom!$"

SilphCo_5F_Text_Grunt1PostBattle:: @ 8175C0F
    .string "It's not smart to pick a fight with\n"
    .string "TEAM ROCKET!$"

SilphCo_5F_Text_BeauIntro:: @ 8175C40
    .string "We study POKé BALL technology on\n"
    .string "this floor.$"

SilphCo_5F_Text_BeauDefeat:: @ 8175C6D
    .string "Dang!\n"
    .string "Blast it!$"

SilphCo_5F_Text_BeauPostBattle:: @ 8175C7D
    .string "We worked on the ultimate POKé\n"
    .string "BALL which would catch anything.$"

SilphCo_5F_Text_DaltonIntro:: @ 8175CBD
    .string "Whaaat?\p"
    .string "There shouldn't be any children\n"
    .string "here!$"

SilphCo_5F_Text_DaltonDefeat:: @ 8175CEB
    .string "Oh, goodness!$"

SilphCo_5F_Text_DaltonPostBattle:: @ 8175CF9
    .string "You're only on 5F.\n"
    .string "It's a long way to my BOSS!$"

SilphCo_5F_Text_Grunt2Intro:: @ 8175D28
    .string "Show TEAM ROCKET a little respect!$"

SilphCo_5F_Text_Grunt2Defeat:: @ 8175D4B
    .string "Cough…\n"
    .string "Cough…$"

SilphCo_5F_Text_Grunt2PostBattle:: @ 8175D59
    .string "Which reminds me.\p"
    .string "KOFFING evolves into WEEZING!$"

SilphCo_5F_Text_PorygonFirstVRMon:: @ 8175D89
    .string "It's a POKéMON REPORT!\p"
    .string "POKéMON LAB created PORYGON,\n"
    .string "the first virtual-reality POKéMON.$"

SilphCo_5F_Text_Over350TechniquesConfirmed:: @ 8175DE0
    .string "It's a POKéMON REPORT!\p"
    .string "Over 350 POKéMON techniques have\n"
    .string "been confirmed.$"

SilphCo_5F_Text_SomeMonsEvolveWhenTraded:: @ 8175E28
    .string "It's a POKéMON REPORT!\p"
    .string "Some POKéMON have been confirmed\n"
    .string "to evolve when they are traded.$"

SilphCo_5F_Text_FloorSign:: @ 8175E80
    .string "SILPH CO. HEAD OFFICE\n"
    .string "5F$"

SilphCo_5F_Text_RocketBossLookingForStrongMons:: @ 8175E99
    .string "Those thugs that took over our\n"
    .string "building…\p"
    .string "Their BOSS said he was looking for\n"
    .string "strong POKéMON.\p"
    .string "I hope our PRESIDENT managed to\n"
    .string "avoid trouble…$"
