LavenderTown_Mart_Text_SearchingForStatRaiseItems::
    .string "Estoy buscando objetos que aumenten\n"
    .string "las estadísticas de los POKéMON.\p"
    .string "Son efectivos durante un solo\n"
    .string "combate.\p"
    .string "X ATAQUE, X DEFENSA, X VELOCIDAD,\n"
    .string "y X ESPECIAL son los que busco.\p"
    .string "¿Sabes dónde puedo conseguirlos?$"

LavenderTown_Mart_Text_DidYouBuyRevives::
    .string "¿Compraste REVIVIR?\n"
    .string "¡Reviven a cualquier POKéMON debilitado!$"

LavenderTown_Mart_Text_TrainerDuosCanChallengeYou::
    .string "A veces, un dúo de ENTRENADORES\n"
    .string "te desafiará con dos POKéMON\l"
    .string "al mismo tiempo.\p"
    .string "Si eso pasa, tú también debes\n"
    .string "enviar dos POKéMON a combatir.$"

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000::
    .string "Hace poco, en lo profundo de\n"
    .string "las montañas, encontré una PEPITA.\p"
    .string "No sirve para nada, pero cuando\n"
    .string "la vendí, ¡me dieron 5000¥!$"

