Text_19B123:: @ 819B123
    .string "？　みえないぞ‥$"

Text_19B12C:: @ 819B12C
    .string "Grunt!\p"
    .string "I am the KARATE MASTER!\n"
    .string "I am the LEADER here!\p"
    .string "You wish to challenge us?\n"
    .string "Expect no mercy!\p"
    .string "Fwaaa!$"

Text_19B193:: @ 819B193
    .string "Hwa!\n"
    .string "Arrgh! Beaten!$"

gUnknown_819B1A7:: @ 819B1A7
    .string "Indeed, I have lost!\p"
    .string "But, I beseech you, do not take\n"
    .string "our emblem as your trophy!\p"
    .string "In return, I will give you a prized\n"
    .string "FIGHTING POKéMON!\p"
    .string "Choose whichever one you like!$"

gUnknown_819B24C:: @ 819B24C
    .string "Grunt!\n"
    .string "Stay and train at karate with us!$"

Text_19B275:: @ 819B275
    .string "Hoargh!\n"
    .string "Take your shoes off!$"

Text_19B292:: @ 819B292
    .string "I give up!$"

gUnknown_819B29D:: @ 819B29D
    .string "You wait 'til you see our MASTER!\n"
    .string "I'm a small fry compared to him!$"

Text_19B2E0:: @ 819B2E0
    .string "I hear you're good!\n"
    .string "Show me!$"

Text_19B2FD:: @ 819B2FD
    .string "Judge!\n"
    .string "One point!$"

gUnknown_819B30F:: @ 819B30F
    .string "Our MASTER is a pro fighter.\n"
    .string "Be prepared to lose!$"

Text_19B341:: @ 819B341
    .string "Hiyah!\n"
    .string "I have no fear for anything tough!\p"
    .string "I shatter boulders for training\n"
    .string "every day!$"

Text_19B396:: @ 819B396
    .string "Yow!\n"
    .string "Stubbed fingers!$"

gUnknown_819B3AC:: @ 819B3AC
    .string "The only thing that frightens us is\n"
    .string "psychic power!$"

Text_19B3DF:: @ 819B3DF
    .string "Hwaah!\p"
    .string "You're trespassing in our\n"
    .string "FIGHTING DOJO!$"

Text_19B40F:: @ 819B40F
    .string "Oof!\n"
    .string "I give up!$"

gUnknown_819B41F:: @ 819B41F
    .string "The prime fighters across the land\n"
    .string "train here.$"

gUnknown_819B44E:: @ 819B44E
    .string "You want the hard-kicking\n"
    .string "HITMONLEE?$"

Text_19B473:: @ 819B473
    .string "{PLAYER} received the {STR_VAR_1}\n"
    .string "from the KARATE MASTER.$"

gUnknown_819B49E:: @ 819B49E
    .string "You want the piston-punching\n"
    .string "HITMONCHAN?$"

Text_19B4C7:: @ 819B4C7
    .string "{PLAYER}は　カラテ　だいおう　から\n"
    .string "{STR_VAR_1}を　もらった！$"

gUnknown_819B4E1:: @ 819B4E1
    .string "Better not get greedy…$"

gUnknown_819B4F8:: @ 819B4F8
    .string "Enemies on every side!$"

gUnknown_819B50F:: @ 819B50F
    .string "What goes around comes around.$"

gUnknown_819B52E:: @ 819B52E
    .string "FIGHTING DOJO$"

