gUnknown_81A9288:: @ 81A9288
	.braille "UP$"

gUnknown_81A928B:: @ 81A928B
	.braille "DOWN$"

gUnknown_81A9290:: @ 81A9290
	.braille "RIGHT$"

gUnknown_81A9296:: @ 81A9296
	.braille "LEFT$"

gUnknown_81A929B:: @ 81A929B
	.braille "CUT$"

gUnknown_81A929F:: @ 81A929F
	.braille "ABC$"

gUnknown_81A92A3:: @ 81A92A3
	.braille "GHI$"

gUnknown_81A92A7:: @ 81A92A7
	.braille "MNO$"

gUnknown_81A92AB:: @ 81A92AB
	.braille "TUV$"

gUnknown_81A92AF:: @ 81A92AF
	.braille "DEF$"

gUnknown_81A92B3:: @ 81A92B3
	.braille "JKL$"

gUnknown_81A92B7:: @ 81A92B7
	.braille "PQRS$"

gUnknown_81A92BC:: @ 81A92BC
	.braille "WXYZ$"

gUnknown_81A92C1:: @ 81A92C1
	.braille ".$"

gUnknown_81A92C3:: @ 81A92C3
	.braille ",$"

gUnknown_81A92C5:: @ 81A92C5
	.braille "EVERYTHING$"

gUnknown_81A92D0:: @ 81A92D0
	.braille "HAS MEANING$"

gUnknown_81A92DC:: @ 81A92DC
	.braille "EXISTENCE$"

gUnknown_81A92E6:: @ 81A92E6
	.braille "HAS MEANING$"

gUnknown_81A92F2:: @ 81A92F2
	.braille "BEING ALIVE$"

gUnknown_81A92FE:: @ 81A92FE
	.braille "HAS MEANING$"

gUnknown_81A930A:: @ 81A930A
	.braille "HAVE DREAMS$"

gUnknown_81A9316:: @ 81A9316
	.braille "USE POWER.$"

gUnknown_81A9321:: @ 81A9321
	.braille "LET THE TWO$"

gUnknown_81A932D:: @ 81A932D
	.braille "GLITTERING$"

gUnknown_81A9338:: @ 81A9338
	.braille "STONES$"

gUnknown_81A933F:: @ 81A933F
	.braille "ONE IN RED$"

gUnknown_81A934A:: @ 81A934A
	.braille "ONE IN BLUE$"

gUnknown_81A9356:: @ 81A9356
	.braille "CONNECT THE$"

gUnknown_81A9362:: @ 81A9362
	.braille "PAST.$"

gUnknown_81A9368:: @ 81A9368
	.braille "TWO FRIENDS$"

gUnknown_81A9374:: @ 81A9374
	.braille "SHARING$"

gUnknown_81A937C:: @ 81A937C
	.braille "POWER OPEN$"

gUnknown_81A9387:: @ 81A9387
	.braille "A WINDOW TO$"

gUnknown_81A9393:: @ 81A9393
	.braille "A NEW WORLD$"

gUnknown_81A939F:: @ 81A939F
	.braille "THAT GLOWS.$"

gUnknown_81A93AB:: @ 81A93AB
	.braille "THE NEXT$"

gUnknown_81A93B4:: @ 81A93B4
	.braille "WORLD WAITS$"

gUnknown_81A93C0:: @ 81A93C0
	.braille "FOR YOU.$"
