Braille_Text_Up:: @ 81A9288
	.braille "UP$"

Braille_Text_Down:: @ 81A928B
	.braille "DOWN$"

Braille_Text_Right:: @ 81A9290
	.braille "RIGHT$"

Braille_Text_Left:: @ 81A9296
	.braille "LEFT$"

Braille_Text_Cut:: @ 81A929B
	.braille "CUT$"

Braille_Text_ABC:: @ 81A929F
	.braille "ABC$"

Braille_Text_GHI:: @ 81A92A3
	.braille "GHI$"

Braille_Text_MNO:: @ 81A92A7
	.braille "MNO$"

Braille_Text_TUV:: @ 81A92AB
	.braille "TUV$"

Braille_Text_DEF:: @ 81A92AF
	.braille "DEF$"

Braille_Text_JKL:: @ 81A92B3
	.braille "JKL$"

Braille_Text_PQRS:: @ 81A92B7
	.braille "PQRS$"

Braille_Text_WXYZ:: @ 81A92BC
	.braille "WXYZ$"

Braille_Text_Period:: @ 81A92C1
	.braille ".$"

Braille_Text_Comma:: @ 81A92C3
	.braille ",$"

Braille_Text_Everything:: @ 81A92C5
	.braille "EVERYTHING$"

Braille_Text_HasMeaning1:: @ 81A92D0
	.braille "HAS MEANING$"

Braille_Text_Existence:: @ 81A92DC
	.braille "EXISTENCE$"

Braille_Text_HasMeaning2:: @ 81A92E6
	.braille "HAS MEANING$"

Braille_Text_BeingAlive:: @ 81A92F2
	.braille "BEING ALIVE$"

Braille_Text_HasMeaning3:: @ 81A92FE
	.braille "HAS MEANING$"

Braille_Text_HaveDreams:: @ 81A930A
	.braille "HAVE DREAMS$"

Braille_Text_UsePower:: @ 81A9316
	.braille "USE POWER.$"

Braille_Text_LetTheTwo:: @ 81A9321
	.braille "LET THE TWO$"

Braille_Text_Glittering:: @ 81A932D
	.braille "GLITTERING$"

Braille_Text_Stones:: @ 81A9338
	.braille "STONES$"

Braille_Text_OneInRed:: @ 81A933F
	.braille "ONE IN RED$"

Braille_Text_OneInBlue:: @ 81A934A
	.braille "ONE IN BLUE$"

Braille_Text_ConnectThe:: @ 81A9356
	.braille "CONNECT THE$"

Braille_Text_Past:: @ 81A9362
	.braille "PAST.$"

Braille_Text_TwoFriends:: @ 81A9368
	.braille "TWO FRIENDS$"

Braille_Text_Sharing:: @ 81A9374
	.braille "SHARING$"

Braille_Text_PowerOpen:: @ 81A937C
	.braille "POWER OPEN$"

Braille_Text_AWindowTo:: @ 81A9387
	.braille "A WINDOW TO$"

Braille_Text_ANewWorld:: @ 81A9393
	.braille "A NEW WORLD$"

Braille_Text_ThatGlows:: @ 81A939F
	.braille "THAT GLOWS.$"

Braille_Text_TheNext:: @ 81A93AB
	.braille "THE NEXT$"

Braille_Text_WorldWaits:: @ 81A93B4
	.braille "WORLD WAITS$"

Braille_Text_ForYou:: @ 81A93C0
	.braille "FOR YOU.$"
