@ The text here is a copy/paste from Hoenn's competitive brothers, the NPCs in Sootopolis who request to see big Barboach/Shroomish (Seedot/Lotad in Emerald). It's all unused and untranslated

SootopolisCity_Text_PleaseShowMeBigMon:: @ 81C0283
    .string "わしは　おおきな　{STR_VAR_1}に\n"
    .string "とても　きょうみが　ある！\p"
    .string "ん？　きみ　{STR_VAR_1}　もってるの？\n"
    .string "ちょ　ちょ　ちょっと···\l"
    .string "おじさんに　みせて　おくれ！$"

SootopolisCity_Text_GrandMonThanksForShowingMe:: @ 81C02CB
    .string "おお！　こいつは　でかい！\n"
    .string "とても　すばらしい　{STR_VAR_1}だ！\p"
    .string "みせて　くれて　ありがとう\n"
    .string "おれいに　これを　もって　いきなさい$"

SootopolisCity_Text_ReceivedOneItem:: @ 81C0309
    .string "{PLAYER}は\n"
    .string "{STR_VAR_2}を　もらった！$"

SootopolisCity_Text_HuhBagIsCrammedFull:: @ 81C0317
    .string "ありゃ？\n"
    .string "きみ　もちもの　いっぱいだね$"

SootopolisCity_Text_IveSeenBiggerMonThanThisOne:: @ 81C032B
    .string "ううむ　わしは　これより　おおきい\n"
    .string "{STR_VAR_1}を　みたこと　あるな···$"

SootopolisCity_Text_QuiteSomethingButNotMon:: @ 81C034D
    .string "おお　こいつは　なかなか···って\n"
    .string "これ　{STR_VAR_1}じゃ　ないよ！$"

SootopolisCity_Text_TooBadDontHaveBigMon:: @ 81C036C
    .string "おおきい　{STR_VAR_1}　もってないの？\l"
    .string "それは　ざんねん···\n"
    .string "こんど　おおきい　{STR_VAR_1}　みせてね$"

SootopolisCity_Text_BiggestMonPlayersXCmColossus:: @ 81C0399
    .string "しじょう　さいだいの　{STR_VAR_1}！\n"
    .string "{STR_VAR_2}の　{STR_VAR_3}cmのやつ！$"
