gUnknown_8454238:: @ 8454238
	.string "A small desk built\n"
	.string "for one.$"

gUnknown_8454254:: @ 8454254
	.string "A small desk built in\n"
	.string "the shape of a POKé\n"
	.string "BALL.$"

gUnknown_8454284:: @ 8454284
	.string "A large desk made\n"
	.string "of steel. Put some\n"
	.string "decorations on it.$"

gUnknown_84542BC:: @ 84542BC
	.string "A large desk made\n"
	.string "of wood. Put some\n"
	.string "decorations on it.$"

gUnknown_84542F3:: @ 84542F3
	.string "A large desk made\n"
	.string "of leaves. Put some\n"
	.string "decorations on it.$"

gUnknown_845432C:: @ 845432C
	.string "A huge desk made\n"
	.string "of glass. Holds lots\n"
	.string "of decorations.$"

gUnknown_8454362:: @ 8454362
	.string "A huge desk made\n"
	.string "of brick. Holds lots\n"
	.string "of decorations.$"

gUnknown_8454398:: @ 8454398
	.string "A huge desk made\n"
	.string "of logs. Put lots of\n"
	.string "decorations on it.$"

gUnknown_84543D1:: @ 84543D1
	.string "A huge desk made\n"
	.string "of rocks. Holds\n"
	.string "many decorations.$"

gUnknown_8454404:: @ 8454404
	.string "A small chair made\n"
	.string "for one.$"

gUnknown_8454420:: @ 8454420
	.string "A small chair built\n"
	.string "in the shape of a\n"
	.string "POKé BALL.$"

gUnknown_8454451:: @ 8454451
	.string "A small chair made\n"
	.string "of steel.$"

gUnknown_845446E:: @ 845446E
	.string "A small chair made\n"
	.string "of glass.$"

gUnknown_845448B:: @ 845448B
	.string "A small chair made\n"
	.string "of leaves.$"

gUnknown_84544A9:: @ 84544A9
	.string "A small chair made\n"
	.string "of wood.$"

gUnknown_84544C5:: @ 84544C5
	.string "A small chair made\n"
	.string "of brick.$"

gUnknown_84544E2:: @ 84544E2
	.string "A small chair made\n"
	.string "of logs.$"

gUnknown_84544FE:: @ 84544FE
	.string "A small chair made\n"
	.string "of rock.$"

gUnknown_845451A:: @ 845451A
	.string "A vivid red potted\n"
	.string "plant.$"

gUnknown_8454534:: @ 8454534
	.string "A flowering tropical\n"
	.string "plant in a pot.$"

gUnknown_8454559:: @ 8454559
	.string "A pot of cute\n"
	.string "flowers.$"

gUnknown_8454570:: @ 8454570
	.string "A large pot with\n"
	.string "many colorful\n"
	.string "flowers.$"

gUnknown_8454598:: @ 8454598
	.string "A large, umbrella-\n"
	.string "shaped plant in a\n"
	.string "big pot.$"

gUnknown_84545C6:: @ 84545C6
	.string "A large, impressive\n"
	.string "plant in a big pot.$"

gUnknown_84545EE:: @ 84545EE
	.string "A red-colored brick.\n"
	.string "Decorations can be\n"
	.string "placed on top.$"

gUnknown_8454625:: @ 8454625
	.string "A yellow-colored\n"
	.string "brick. Put some\n"
	.string "decorations on top.$"

gUnknown_845465A:: @ 845465A
	.string "A blue-colored\n"
	.string "brick. Put some\n"
	.string "decorations on top.$"

gUnknown_845468D:: @ 845468D
	.string "A red balloon filled\n"
	.string "with water. Bursts\n"
	.string "if stepped on.$"

gUnknown_84546C4:: @ 84546C4
	.string "A blue balloon filled\n"
	.string "with water. Bursts\n"
	.string "if stepped on.$"

gUnknown_84546FC:: @ 84546FC
	.string "A yellow balloon\n"
	.string "filled with water.\n"
	.string "Pops if stepped on.$"

gUnknown_8454734:: @ 8454734
	.string "A large red tent.\n"
	.string "You can hide inside\n"
	.string "it.$"

gUnknown_845475E:: @ 845475E
	.string "A large blue tent.\n"
	.string "You can hide inside\n"
	.string "it.$"

gUnknown_8454789:: @ 8454789
	.string "Place over a hole to\n"
	.string "cross to the other\n"
	.string "side.$"

gUnknown_84547B7:: @ 84547B7
	.string "Use to slide down\n"
	.string "from the platform.$"

gUnknown_84547DC:: @ 84547DC
	.string "A small fence that\n"
	.string "blocks passage.$"

gUnknown_84547FF:: @ 84547FF
	.string "A small fence that\n"
	.string "blocks passage.$"

gUnknown_8454822:: @ 8454822
	.string "An old large tire.\n"
	.string "Decorations can be\n"
	.string "placed on top.$"

gUnknown_8454857:: @ 8454857
	.string "A large pedestal\n"
	.string "with steps.$"

gUnknown_8454874:: @ 8454874
	.string "A large ball of mud.\n"
	.string "Crumbles if stepped\n"
	.string "on.$"

gUnknown_84548A1:: @ 84548A1
	.string "A weird door that\n"
	.string "people can walk\n"
	.string "right through.$"

gUnknown_84548D2:: @ 84548D2
	.string "An ornament made\n"
	.string "of sand. Crumbles if\n"
	.string "touched.$"

gUnknown_8454901:: @ 8454901
	.string "Awarded for 50\n"
	.string "straight wins at\n"
	.string "the BATTLE TOWER.$"

gUnknown_8454933:: @ 8454933
	.string "Awarded for 100\n"
	.string "straight wins at\n"
	.string "the BATTLE TOWER.$"

gUnknown_8454966:: @ 8454966
	.string "A glass replica of\n"
	.string "a famous sculpture\n"
	.string "at the ART MUSEUM.$"

gUnknown_845499F:: @ 845499F
	.string "A small, gray-\n"
	.string "colored toy TV.$"

gUnknown_84549BE:: @ 84549BE
	.string "A toy TV modeled\n"
	.string "in the image of a\n"
	.string "SEEDOT.$"

gUnknown_84549E9:: @ 84549E9
	.string "A toy TV modeled\n"
	.string "in the image of a\n"
	.string "SKITTY.$"

gUnknown_8454A14:: @ 8454A14
	.string "An odd mat that\n"
	.string "glitters if stepped\n"
	.string "on.$"

gUnknown_8454A3C:: @ 8454A3C
	.string "A trick mat that\n"
	.string "jumps when it is\n"
	.string "stepped on.$"

gUnknown_8454A6A:: @ 8454A6A
	.string "A trick mat that\n"
	.string "spins around when\n"
	.string "stepped on.$"

gUnknown_8454A99:: @ 8454A99
	.string "A mat that plays\n"
	.string "a low C note when\n"
	.string "stepped on.$"

gUnknown_8454AC8:: @ 8454AC8
	.string "A mat that plays\n"
	.string "a D note when\n"
	.string "stepped on.$"

gUnknown_8454AF3:: @ 8454AF3
	.string "A mat that plays\n"
	.string "an E note when\n"
	.string "stepped on.$"

gUnknown_8454B1F:: @ 8454B1F
	.string "A mat that plays\n"
	.string "an F note when\n"
	.string "stepped on.$"

gUnknown_8454B4B:: @ 8454B4B
	.string "A mat that plays\n"
	.string "a G note when\n"
	.string "stepped on.$"

gUnknown_8454B76:: @ 8454B76
	.string "A mat that plays\n"
	.string "an A note when\n"
	.string "stepped on.$"

gUnknown_8454BA2:: @ 8454BA2
	.string "A mat that plays\n"
	.string "a B note when\n"
	.string "stepped on.$"

gUnknown_8454BCD:: @ 8454BCD
	.string "A mat that plays\n"
	.string "a high C note when\n"
	.string "stepped on.$"

gUnknown_8454BFD:: @ 8454BFD
	.string "A mat designed with\n"
	.string "a SURF image.\n"
	.string "Put items on top.$"

gUnknown_8454C31:: @ 8454C31
	.string "A mat designed with\n"
	.string "a THUNDER image.\n"
	.string "Put items on top.$"

gUnknown_8454C68:: @ 8454C68
	.string "A mat designed with\n"
	.string "a FIRE BLAST image.\n"
	.string "Put items on top.$"

gUnknown_8454CA2:: @ 8454CA2
	.string "A mat with a POWDER\n"
	.string "SNOW image design.\n"
	.string "Put items on top.$"

gUnknown_8454CDB:: @ 8454CDB
	.string "A mat designed with\n"
	.string "an ATTRACT image.\n"
	.string "Put items on top.$"

gUnknown_8454D13:: @ 8454D13
	.string "A mat designed with\n"
	.string "a FISSURE image.\n"
	.string "Put items on top.$"

gUnknown_8454D4A:: @ 8454D4A
	.string "A mat designed with\n"
	.string "a SPIKES image.\n"
	.string "Put items on top.$"

gUnknown_8454D80:: @ 8454D80
	.string "A small poster\n"
	.string "printed with POKé\n"
	.string "BALLS.$"

gUnknown_8454DA8:: @ 8454DA8
	.string "A small poster with\n"
	.string "a TREECKO print.$"

gUnknown_8454DCD:: @ 8454DCD
	.string "A small poster with\n"
	.string "a TORCHIC print.$"

gUnknown_8454DF2:: @ 8454DF2
	.string "A small poster with\n"
	.string "a MUDKIP print.$"

gUnknown_8454E16:: @ 8454E16
	.string "A small poster with\n"
	.string "an AZURILL print.$"

gUnknown_8454E3C:: @ 8454E3C
	.string "A large poster with\n"
	.string "a PIKACHU and\n"
	.string "PICHU print.$"

gUnknown_8454E6B:: @ 8454E6B
	.string "A large poster with\n"
	.string "a SEVIPER print.$"

gUnknown_8454E90:: @ 8454E90
	.string "A large poster with\n"
	.string "a RELICANTH print.$"

gUnknown_8454EB7:: @ 8454EB7
	.string "A large poster with\n"
	.string "a WINGULL print.$"

gUnknown_8454EDC:: @ 8454EDC
	.string "A large poster with\n"
	.string "a SMOOCHUM print.$"

gUnknown_8454F02:: @ 8454F02
	.string "A PICHU doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_8454F2D:: @ 8454F2D
	.string "A PIKACHU doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_8454F5A:: @ 8454F5A
	.string "A MARILL doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_8454F86:: @ 8454F86
	.string "A TOGEPI doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_8454FB2:: @ 8454FB2
	.string "A CYNDAQUIL doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_8454FE1:: @ 8454FE1
	.string "A CHIKORITA doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_8455010:: @ 8455010
	.string "A TOTODILE doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_845503E:: @ 845503E
	.string "A JIGGLYPUFF doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_845506E:: @ 845506E
	.string "A MEOWTH doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_845509A:: @ 845509A
	.string "A CLEFAIRY doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_84550C8:: @ 84550C8
	.string "A DITTO doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_84550F3:: @ 84550F3
	.string "A SMOOCHUM doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_8455121:: @ 8455121
	.string "A TREECKO doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_845514E:: @ 845514E
	.string "A TORCHIC doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_845517B:: @ 845517B
	.string "A MUDKIP doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_84551A7:: @ 84551A7
	.string "A DUSKULL doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_84551D4:: @ 84551D4
	.string "A WYNAUT doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_8455200:: @ 8455200
	.string "A BALTOY doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_845522C:: @ 845522C
	.string "A KECLEON doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_8455259:: @ 8455259
	.string "An AZURILL doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_8455287:: @ 8455287
	.string "A SKITTY doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_84552B3:: @ 84552B3
	.string "A SWABLU doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_84552DF:: @ 84552DF
	.string "A GULPIN doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_845530B:: @ 845530B
	.string "A LOTAD doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_8455336:: @ 8455336
	.string "A SEEDOT doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_8455362:: @ 8455362
	.string "A PIKACHU cushion.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_8455392:: @ 8455392
	.string "A MARILL cushion.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_84553C1:: @ 84553C1
	.string "A SMOOCHUM\n"
	.string "cushion. Place it on\n"
	.string "a mat or a desk.$"

gUnknown_84553F2:: @ 84553F2
	.string "A ZIGZAGOON\n"
	.string "cushion. Place it on\n"
	.string "a mat or a desk.$"

gUnknown_8455424:: @ 8455424
	.string "A SPINDA cushion.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_8455453:: @ 8455453
	.string "A SABLEYE cushion.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_8455483:: @ 8455483
	.string "A BALL cushion.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_84554B0:: @ 84554B0
	.string "A grass-mark\n"
	.string "cushion. Place it on\n"
	.string "a mat or a desk.$"

gUnknown_84554E3:: @ 84554E3
	.string "A fire-mark\n"
	.string "cushion. Place it on\n"
	.string "a mat or a desk.$"

gUnknown_8455515:: @ 8455515
	.string "A water-mark\n"
	.string "cushion. Place it on\n"
	.string "a mat or a desk.$"

gUnknown_8455548:: @ 8455548
	.string "A large doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_8455573:: @ 8455573
	.string "A large doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_845559E:: @ 845559E
	.string "A large doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_84555C9:: @ 84555C9
	.string "A large doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_84555F4:: @ 84555F4
	.string "A large doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_845561F:: @ 845561F
	.string "A large doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_845564A:: @ 845564A
	.string "A large doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_8455675:: @ 8455675
	.string "A large doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_84556A0:: @ 84556A0
	.string "A large doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"

gUnknown_84556CB:: @ 84556CB
	.string "A large doll.\n"
	.string "Place it on a mat\n"
	.string "or a desk.$"
