@ The text here is a copy/paste from Hoenn's Eon Ticket event, all unused and untranslated

Text_DadLetterArrivedForYouPlayer:: @ 81C03B5
	.string "パパ“{PLAYER}！　よく　きたな！\n"
	.string "{PLAYER}あての　てがみが　とどけられたぞ$"

Text_DadPassForShipNeverSeenBefore:: @ 81C03D7
	.string "パパ“わたしも　みたことのない\n"
	.string "ふねの　チケット　だな‥‥\l"
	.string "ミナモに　いってみると　いいだろう$"

Text_FerryToSlateportOhThatPass:: @ 81C0407
	.string "カイナいき　れんらくせん‥‥\p"
	.string "あら？\n"
	.string "その　チケットは‥‥！$"

Text_YoureOneWhoBroughtOddPass:: @ 81C0426
	.string "ヘンテコな　チケットを\n"
	.string "もってきたのは　おまえさんか？\p"
	.string "おまえが　いこうと　しているのは\n"
	.string "みなみの　はての　ちっぽけな　しま‥‥\p"
	.string "そこでは　なにが　おこるのか\n"
	.string "だれも　わからねえ‥‥\l"
	.string "ううむ　ふなのりの　ちが　さわぐぜ！\p"
	.string "さあ　のりな！$"

Text_NothingHereSailBackToLilycove:: @ 81C049D
	.string "なにもねえ　ちんけな　しま　だな‥‥\n"
	.string "ミナモへ　かえるか？$"

Text_SailHomeWeWill:: @ 81C04BB
	.string "よし！　かえると　するか！$"

Text_AsYouLikeThen:: @ 81C04C9
	.string "そうかい\n"
	.string "まあ　すきにするが　いいさ$"

SouthernIsland_Interior_Text_Sign:: @ 81C04DC
	.string "すべての　ゆめは　もうひとつの　げんじつ\n"
	.string "それを　わすれるべからず‥‥$"

SouthernIsland_Exterior_Text_Sign:: @ 81C0500
	.string "きおく　かすみし　ものは\n"
	.string "こころに　きざみつける　ことを　のぞむ‥‥$"
