gFameCheckerFlavorText_ProfOak0:: @ 0x81AD106
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{COLOR RED}{SHADOW GREEN}OAK POKéMON RESEARCH LAB$"

gFameCheckerFlavorText_ProfOak1:: @ 0x81AD145
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}To make a complete guide on all\n"
	.string "the POKéMON in the world…\p"
	.string "That was my dream!$"

gFameCheckerFlavorText_ProfOak2:: @ 0x81AD1BB
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}PROF. OAK may not look like much,\n"
	.string "but he's the authority on POKéMON.\p"
	.string "Many POKéMON TRAINERS hold him in\n"
	.string "high regard.$"

gFameCheckerFlavorText_ProfOak3:: @ 0x81AD258
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Family and friends?\p"
	.string "{COLOR RED}{SHADOW GREEN}PROF. OAK reportedly lives with his\n"
	.string "grandchildren, DAISY and {RIVAL}.$"

gFameCheckerFlavorText_ProfOak4:: @ 0x81AD2B9
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Family and friends?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}I hear OAK's taken a lot of\n"
	.string "interest in you, child.\p"
	.string "That old duff was once tough and\n"
	.string "handsome.\p"
	.string "But that was decades ago.\n"
	.string "He's a shadow of his former self.$"

gFameCheckerFlavorText_ProfOak5:: @ 0x81AD377
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}PROF. OAK is going to have his own\n"
	.string "radio show soon.\p"
	.string "The program will be called PROF.\n"
	.string "OAK'S POKéMON SEMINAR.$"

gFameCheckerFlavorText_Daisy0:: @ 0x81AD40C
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}If you show DAISY your POKéMON,\n"
	.string "she can tell how much it likes you.\p"
	.string "Occasionally, she will even groom\n"
	.string "a POKéMON for you.$"

gFameCheckerFlavorText_Daisy1:: @ 0x81AD4AE
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}But the person who is most liked by\n"
	.string "POKéMON is DAISY, I think.$"

gFameCheckerFlavorText_Daisy2:: @ 0x81AD516
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}She was gently grooming POKéMON…\n"
	.string "She was a little angel.\p"
	.string "That little girl's name…\n"
	.string "I think it was DAISY.$"

gFameCheckerFlavorText_Daisy3:: @ 0x81AD5A7
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Family and friends?\p"
	.string "{COLOR RED}{SHADOW GREEN}PROF. OAK reportedly lives with his\n"
	.string "grandchildren, DAISY and {RIVAL}.$"

gFameCheckerFlavorText_Daisy4:: @ 0x81AD608
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}A girl from PALLET TOWN, DAISY,\n"
	.string "she enjoys TEA every day.\p"
	.string "She visits the CELADON DEPT. STORE\n"
	.string "to buy some TEA.$"

gFameCheckerFlavorText_Daisy5:: @ 0x81AD69F
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}There's a rumor…\p"
	.string "{COLOR RED}{SHADOW GREEN}The Spring POKéMON CONTEST's\n"
	.string "Grand Champion is DAISY OAK of\l"
	.string "PALLET TOWN!$"

gFameCheckerFlavorText_Brock0:: @ 0x81AD705
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{COLOR RED}{SHADOW GREEN}PEWTER CITY POKéMON GYM\n"
	.string "LEADER: BROCK\l"
	.string "The Rock-Solid POKéMON TRAINER!$"

gFameCheckerFlavorText_Brock1:: @ 0x81AD771
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Favorite kind of POKéMON?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}My rock-hard willpower is evident\n"
	.string "in even my POKéMON.\p"
	.string "My POKéMON are all rock hard and\n"
	.string "have true-grit determination.\p"
	.string "That's right - my POKéMON are all\n"
	.string "the ROCK type!$"

gFameCheckerFlavorText_Brock2:: @ 0x81AD840
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}There aren't many serious POKéMON\n"
	.string "TRAINERS here.\p"
	.string "They're all like BUG CATCHERS,\n"
	.string "you know, just hobbyists.\p"
	.string "But PEWTER GYM's BROCK isn't like\n"
	.string "that, not one bit.$"

gFameCheckerFlavorText_Brock3:: @ 0x81AD908
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}BROCK is cool. He's not just tough.\n"
	.string "People like and respect him.\p"
	.string "I want to become a GYM LEADER\n"
	.string "like him.$"

gFameCheckerFlavorText_Brock4:: @ 0x81AD99A
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}Hi, I'm excavating for fossils here\n"
	.string "under MT. MOON.\p"
	.string "Sometimes, BROCK of PEWTER GYM\n"
	.string "lends me a hand.$"

gFameCheckerFlavorText_Brock5:: @ 0x81ADA27
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{COLOR RED}{SHADOW GREEN}BROCK rarely laughs, but is said to\n"
	.string "be unable to stop if he starts.$"

gFameCheckerFlavorText_Misty0:: @ 0x81ADA91
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{COLOR RED}{SHADOW GREEN}CERULEAN CITY POKéMON GYM\n"
	.string "LEADER: MISTY\l"
	.string "The Tomboyish Mermaid!$"

gFameCheckerFlavorText_Misty1:: @ 0x81ADAF6
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Favorite kind of POKéMON?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}My policy is an all-out offensive\n"
	.string "with WATER-type POKéMON!$"

gFameCheckerFlavorText_Misty2:: @ 0x81ADB5A
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}MISTY is a TRAINER who's going to\n"
	.string "keep improving.\p"
	.string "She won't lose to someone like you!$"

gFameCheckerFlavorText_Misty3:: @ 0x81ADBD9
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}There's a rumor…\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}Strong TRAINERS and WATER POKéMON\n"
	.string "are common sights in these parts.\p"
	.string "They say that MISTY of the\n"
	.string "CERULEAN GYM trains here.$"

gFameCheckerFlavorText_Misty4:: @ 0x81ADC72
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}There's a rumor…\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}This cape is a famous date spot.\p"
	.string "MISTY, the GYM LEADER, has high\n"
	.string "hopes about this place.$"

gFameCheckerFlavorText_Misty5:: @ 0x81ADCEB
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}There's a rumor…\p"
	.string "{COLOR RED}{SHADOW GREEN}MISTY is said to worship LORELEI\n"
	.string "of the ELITE FOUR.$"

gFameCheckerFlavorText_LtSurge0:: @ 0x81ADD3C
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{COLOR RED}{SHADOW GREEN}VERMILION CITY POKéMON GYM\n"
	.string "LEADER: LT. SURGE\l"
	.string "The Lightning American!$"

gFameCheckerFlavorText_LtSurge1:: @ 0x81ADDA7
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Favorite kind of POKéMON?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}I tell you, kid, electric POKéMON\n"
	.string "saved me during the war!$"

gFameCheckerFlavorText_LtSurge2:: @ 0x81ADE0B
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}When I was in the Army, LT. SURGE\n"
	.string "was my strict CO.\p"
	.string "He was a hard taskmaster.$"

gFameCheckerFlavorText_LtSurge3:: @ 0x81ADE82
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}LT. SURGE was always famous for\n"
	.string "his cautious nature in the Army.$"

gFameCheckerFlavorText_LtSurge4:: @ 0x81ADEEC
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}LT. SURGE installed the traps in\n"
	.string "the GYM himself.\p"
	.string "He set up double locks everywhere.$"

gFameCheckerFlavorText_LtSurge5:: @ 0x81ADF6A
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}There's a rumor…\p"
	.string "{COLOR RED}{SHADOW GREEN}LT. SURGE is rumored to have been\n"
	.string "a pilot while home in America.\p"
	.string "He used the electricity generated\n"
	.string "by POKéMON to power his plane.$"

gFameCheckerFlavorText_Erika0:: @ 0x81AE009
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{COLOR RED}{SHADOW GREEN}CELADON CITY POKéMON GYM\n"
	.string "LEADER: ERIKA\l"
	.string "The Nature-Loving Princess!$"

gFameCheckerFlavorText_Erika1:: @ 0x81AE072
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Favorite kind of POKéMON?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}I am a student of the art of\n"
	.string "flower arranging.\p"
	.string "My POKéMON are solely of the\n"
	.string "GRASS type.$"

gFameCheckerFlavorText_Erika2:: @ 0x81AE0F3
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}Our LEADER ERIKA might be quiet,\n"
	.string "but she's famous around here.$"

gFameCheckerFlavorText_Erika3:: @ 0x81AE15B
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}We only use GRASS-type POKéMON at\n"
	.string "our GYM.\p"
	.string "Why? We also use them for making\n"
	.string "flower arrangements!$"

gFameCheckerFlavorText_Erika4:: @ 0x81AE1E5
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Favorite kind of POKéMON?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}I would never collect POKéMON if\n"
	.string "they were unattractive.$"

gFameCheckerFlavorText_Erika5:: @ 0x81AE247
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}There's a rumor…\p"
	.string "{COLOR RED}{SHADOW GREEN}Rumor has it that if you peek into\n"
	.string "CELADON GYM, you can often\l"
	.string "see ERIKA snoozing.$"

gFameCheckerFlavorText_Koga0:: @ 0x81AE2B6
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{COLOR RED}{SHADOW GREEN}FUCHSIA CITY POKéMON GYM\n"
	.string "LEADER: KOGA\l"
	.string "The Poisonous Ninja Master$"

gFameCheckerFlavorText_Koga1:: @ 0x81AE31D
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Favorite kind of POKéMON?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}Despair to the creeping horror of\n"
	.string "POISON-type POKéMON!$"

gFameCheckerFlavorText_Koga2:: @ 0x81AE37D
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}Even though I've lost, I will keep\n"
	.string "training according to the teachings\l"
	.string "of KOGA, my ninja master.$"

gFameCheckerFlavorText_Koga3:: @ 0x81AE407
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Family and friends?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}My father is the GYM LEADER of\n"
	.string "this town.\p"
	.string "I'm training to use POISON POKéMON\n"
	.string "as well as my father.$"

gFameCheckerFlavorText_Koga4:: @ 0x81AE48D
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}There's a rumor…\p"
	.string "{COLOR RED}{SHADOW GREEN}KOGA is said to have a thorough\n"
	.string "knowledge of medicine.\p"
	.string "He even concocts medicine to nurse\n"
	.string "his POKéMON to health.$"

gFameCheckerFlavorText_Koga5:: @ 0x81AE51B
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}The SAFARI ZONE's huge, wouldn't\n"
	.string "you say?\p"
	.string "FUCHSIA's GYM LEADER, KOGA, \n"
	.string "patrols the grounds every so often.\p"
	.string "Thanks to him, we can play here\n"
	.string "knowing that we're safe.$"

gFameCheckerFlavorText_Sabrina0:: @ 0x81AE5E8
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{COLOR RED}{SHADOW GREEN}SAFFRON CITY POKéMON GYM\n"
	.string "LEADER: SABRINA\l"
	.string "The Master of PSYCHIC POKéMON!$"

gFameCheckerFlavorText_Sabrina1:: @ 0x81AE656
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Favorite kind of POKéMON?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}You know about a girl GYM LEADER\n"
	.string "in SAFFRON CITY?\p"
	.string "She uses PSYCHIC-type POKéMON,\n"
	.string "right?$"

gFameCheckerFlavorText_Sabrina2:: @ 0x81AE6D7
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}I have had psychic powers since\n"
	.string "I was a child.\p"
	.string "It started when a spoon I\n"
	.string "carelessly tossed, bent.$"

gFameCheckerFlavorText_Sabrina3:: @ 0x81AE762
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}I dislike battling, but if you wish,\n"
	.string "I will show you my powers!$"

gFameCheckerFlavorText_Sabrina4:: @ 0x81AE7CB
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}There's a rumor…\p"
	.string "{COLOR RED}{SHADOW GREEN}People say that SABRINA can\n"
	.string "communicate with her POKéMON\l"
	.string "during battle without speaking.$"

gFameCheckerFlavorText_Sabrina5:: @ 0x81AE841
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}SABRINA just wiped out the KARATE\n"
	.string "MASTER next door.$"

gFameCheckerFlavorText_Blaine0:: @ 0x81AE89E
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{COLOR RED}{SHADOW GREEN}CINNABAR ISLAND POKéMON GYM\n"
	.string "LEADER: BLAINE\l"
	.string "The Hotheaded Quiz Master!$"

gFameCheckerFlavorText_Blaine1:: @ 0x81AE90A
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Favorite kind of POKéMON?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}My fiery POKéMON are all rough\n"
	.string "and ready with intense heat!\p"
	.string "They incinerate all challengers!$"

gFameCheckerFlavorText_Blaine2:: @ 0x81AE990
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Favorite kind of POKéMON?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}Our LEADER, BLAINE, became lost\n"
	.string "in the mountains but good.\p"
	.string "Night fell when a fiery bird\n"
	.string "POKéMON appeared.\p"
	.string "Its light allowed BLAINE to find\n"
	.string "his way down safely.$"

gFameCheckerFlavorText_Blaine3:: @ 0x81AEA59
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}CINNABAR GYM's BLAINE is quite the\n"
	.string "odd fellow.\p"
	.string "He's lived on the island since way\n"
	.string "before the LAB was built.$"

gFameCheckerFlavorText_Blaine4:: @ 0x81AEAEE
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Family and friends?\p"
	.string "{COLOR RED}{SHADOW GREEN}It's a photo of BLAINE and\n"
	.string "MR. FUJI.\p"
	.string "They're standing shoulder to\n"
	.string "shoulder with big grins.$"

gFameCheckerFlavorText_Blaine5:: @ 0x81AEB69
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}There's a rumor…\p"
	.string "{COLOR RED}{SHADOW GREEN}BLAINE is said to remove his dark\n"
	.string "shades only when he is thinking up\l"
	.string "new quiz questions.$"

gFameCheckerFlavorText_Lorelei0:: @ 0x81AEBDF
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}I am LORELEI of the ELITE FOUR.$"

gFameCheckerFlavorText_Lorelei1:: @ 0x81AEC28
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Favorite kind of POKéMON?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}No one can best me when it comes\n"
	.string "to icy POKéMON.$"

gFameCheckerFlavorText_Lorelei2:: @ 0x81AEC82
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Where was this person born?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}We've had a great and powerful\n"
	.string "TRAINER grow up on this island.\p"
	.string "I bet even you'd know her.\n"
	.string "It's LORELEI of the ELITE FOUR!$"

gFameCheckerFlavorText_Lorelei3:: @ 0x81AED27
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{COLOR RED}{SHADOW GREEN}Known for her logical, calculated,\n"
	.string "and cool battling style, LORELEI\l"
	.string "has a surprising secret!$"

gFameCheckerFlavorText_Lorelei4:: @ 0x81AEDAA
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}Did you know that LORELEI has lots\n"
	.string "and lots of stuffed dolls?\p"
	.string "Every time she comes back to\n"
	.string "FOUR ISLAND, her collection grows!$"

gFameCheckerFlavorText_Lorelei5:: @ 0x81AEE51
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Favorite kind of POKéMON?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}The LAPRAS she has, I imagine it\n"
	.string "to be the one she met as a child.\p"
	.string "I believe it was in ICEFALL CAVE\n"
	.string "that she caught it.\p"
	.string "Perhaps that POKéMON has been with\n"
	.string "her ever since.$"

gFameCheckerFlavorText_Bruno0:: @ 0x81AEF25
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}I am BRUNO of the ELITE FOUR!$"

gFameCheckerFlavorText_Bruno1:: @ 0x81AEF6C
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Favorite kind of POKéMON?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}I've lived and trained with my\n"
	.string "fighting POKéMON!$"

gFameCheckerFlavorText_Bruno2:: @ 0x81AEFC6
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{COLOR RED}{SHADOW GREEN}BRUNO apparently joined the ELITE\n"
	.string "FOUR out of his burning ambition to\l"
	.string "battle the best TRAINERS.$"

gFameCheckerFlavorText_Bruno3:: @ 0x81AF04C
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}BRUNO, who's a senior ahead of me,\n"
	.string "visits the SPA on occasion.\p"
	.string "He comes to rehab injuries, both\n"
	.string "his own and his POKéMON's.$"

gFameCheckerFlavorText_Bruno4:: @ 0x81AF0F0
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}There's a rumor…\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}He's one of the ELITE FOUR.\n"
	.string "His name is BRUNO.\p"
	.string "He went away disappointed when he\n"
	.string "found out that they were all sold\l"
	.string "out of Rage Candybars.$"

gFameCheckerFlavorText_Bruno5:: @ 0x81AF19A
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Family and friends?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}Even BRUNO…\n"
	.string "He trained with a fellow by the\l"
	.string "name of BRAWLY before.$"

gFameCheckerFlavorText_Agatha0:: @ 0x81AF200
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}I am AGATHA of the ELITE FOUR.$"

gFameCheckerFlavorText_Agatha1:: @ 0x81AF248
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Favorite kind of POKéMON?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}AGATHA's GHOST-type POKéMON are\n"
	.string "horrifically terrifying in toughness.$"

gFameCheckerFlavorText_Agatha2:: @ 0x81AF2B7
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}That old lady's also got a really\n"
	.string "short fuse, too.\p"
	.string "It doesn't take anything to get\n"
	.string "that scary lady hollering.$"

gFameCheckerFlavorText_Agatha3:: @ 0x81AF34E
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}There's a rumor…\p"
	.string "{COLOR RED}{SHADOW GREEN}In her youth, AGATHA and PROF.\n"
	.string "OAK were rivals who vied for\l"
	.string "supremacy as TRAINERS.$"

gFameCheckerFlavorText_Agatha4:: @ 0x81AF3BE
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Family and friends?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}I hear OAK's taken a lot of\n"
	.string "interest in you, child.\p"
	.string "That old duff was once tough and\n"
	.string "handsome.\p"
	.string "But that was decades ago.\n"
	.string "He's a shadow of his former self.$"

gFameCheckerFlavorText_Agatha5:: @ 0x81AF47C
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}Take AGATHA, for example.\p"
	.string "She set a record for being the\n"
	.string "oldest-ever ELITE FOUR member.$"

gFameCheckerFlavorText_Lance0:: @ 0x81AF4FD
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}I lead the ELITE FOUR.\p"
	.string "You can call me LANCE the dragon\n"
	.string "TRAINER.$"

gFameCheckerFlavorText_Lance1:: @ 0x81AF567
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Favorite kind of POKéMON?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}You know that dragons are\n"
	.string "mythical POKéMON.\p"
	.string "They're hard to catch and raise,\n"
	.string "but their powers are superior.\p"
	.string "They're virtually indestructible.\n"
	.string "There's no being clever with them.$"

gFameCheckerFlavorText_Lance2:: @ 0x81AF641
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}He stands for justice!\n"
	.string "He's cool, and yet passionate!\l"
	.string "He's the greatest, LANCE!$"

gFameCheckerFlavorText_Lance3:: @ 0x81AF6BA
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}There's a rumor…\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}We have a customer, LANCE, who\n"
	.string "occasionally comes.\p"
	.string "He always buys capes.\p"
	.string "I wonder… Does he have many\n"
	.string "identical capes at home?$"

gFameCheckerFlavorText_Lance4:: @ 0x81AF758
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Family and friends?\p"
	.string "{COLOR RED}{SHADOW GREEN}LANCE's grandfather is thought to\n"
	.string "be the elder of a famous clan of\l"
	.string "dragon masters.$"

gFameCheckerFlavorText_Lance5:: @ 0x81AF7CB
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Family and friends?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}From what I've heard, LANCE has\n"
	.string "a cousin who's a GYM LEADER\l"
	.string "somewhere far away.$"

gFameCheckerFlavorText_Bill0:: @ 0x81AF83E
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}After all, BILL's world-famous as a\n"
	.string "POKéMANIAC.\p"
	.string "He invented the POKéMON Storage\n"
	.string "System on PC, too.$"

gFameCheckerFlavorText_Bill1:: @ 0x81AF8CA
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Favorite kind of POKéMON?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}BILL has lots of POKéMON!\n"
	.string "He collects rare ones, too!$"

gFameCheckerFlavorText_Bill2:: @ 0x81AF929
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}He's my grandson!\p"
	.string "He always liked collecting things,\n"
	.string "even as a child!$"

gFameCheckerFlavorText_Bill3:: @ 0x81AF998
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Favorite kind of POKéMON?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}BILL is a POKéMANIAC, so he loves\n"
	.string "every kind.\p"
	.string "Apparently, the first one he caught\n"
	.string "was an ABRA.$"

gFameCheckerFlavorText_Bill4:: @ 0x81AFA20
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Family and friends?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}BILL's hometown is GOLDENROD CITY,\n"
	.string "where his folks still live.\p"
	.string "I've heard that it's quite the\n"
	.string "festive, bustling city.$"

gFameCheckerFlavorText_Bill5:: @ 0x81AFAB9
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}There's a rumor…\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}Apparently, BILL simply can't\n"
	.string "stomach milk at all.$"

gFameCheckerFlavorText_MrFuji0:: @ 0x81AFB0C
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}He's really kind.\p"
	.string "He looks after abandoned and\n"
	.string "orphaned POKéMON.$"

gFameCheckerFlavorText_MrFuji1:: @ 0x81AFB76
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}This old guy marched right up to\n"
	.string "our HIDEOUT.\p"
	.string "Then, he starts ranting about how\n"
	.string "TEAM ROCKET's abusing POKéMON.\p"
	.string "So, we're just talking it over as\n"
	.string "adults.$"

gFameCheckerFlavorText_MrFuji2:: @ 0x81AFC38
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{COLOR RED}{SHADOW GREEN}POKéMON FAN MAGAZINE\n"
	.string "Monthly Grand Prize Drawing!\p"
	.string "The application form is…\p"
	.string "Gone! It's been clipped out.\n"
	.string "Someone must have applied already.$"

gFameCheckerFlavorText_MrFuji3:: @ 0x81AFCE9
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}There's a rumor…\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}I hear that MR. FUJI's not from\n"
	.string "these parts originally, either.$"

gFameCheckerFlavorText_MrFuji4:: @ 0x81AFD49
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Family and friends?\p"
	.string "{COLOR RED}{SHADOW GREEN}It's a photo of BLAINE and\n"
	.string "MR. FUJI.\p"
	.string "They're standing shoulder to\n"
	.string "shoulder with big grins.$"

gFameCheckerFlavorText_MrFuji5:: @ 0x81AFDC4
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{COLOR RED}{SHADOW GREEN}Editor: The shy MR. FUJI turned\n"
	.string "down our interview requests.\p"
	.string "He is a kindly man who is adored\n"
	.string "and respected in LAVENDER TOWN.$"

gFameCheckerFlavorText_Giovanni0:: @ 0x81AFE68
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}TEAM ROCKET captures POKéMON from\n"
	.string "around the world.\p"
	.string "They're important tools for keeping\n"
	.string "our criminal enterprise going.\p"
	.string "I am the leader, GIOVANNI!$"

gFameCheckerFlavorText_Giovanni1:: @ 0x81AFF23
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Favorite kind of POKéMON?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}Those thugs that took over our\n"
	.string "building…\p"
	.string "Their BOSS said he was looking for\n"
	.string "strong POKéMON.$"

gFameCheckerFlavorText_Giovanni2:: @ 0x81AFFA8
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What is this person like?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}TEAM ROCKET's BOSS is terribly\n"
	.string "cruel!\p"
	.string "To him, POKéMON are just tools to\n"
	.string "be used.$"

gFameCheckerFlavorText_Giovanni3:: @ 0x81B0022
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}Welcome to my hideout!\p"
	.string "It shall be so until I can restore\n"
	.string "TEAM ROCKET to its former glory.$"

gFameCheckerFlavorText_Giovanni4:: @ 0x81B00A6
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}What does this person do?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}Blow me away! GIOVANNI was the\n"
	.string "GYM LEADER of VIRIDIAN?$"

gFameCheckerFlavorText_Giovanni5:: @ 0x81B0106
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}Family and friends?\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}You… You're not GIOVANNI's kid,\n"
	.string "are you?\p"
	.string "No, that can't be right.\n"
	.string "GIOVANNI's kid has red hair.$"


gFameCheckerPersonName_ProfOak:: @ 0x81B0188
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}PROF. OAK$"

gFameCheckerPersonQuote_ProfOak:: @ 0x81B0198
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}From: PROF. OAK\n"
	.string "To: {PLAYER}\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}Why do POKéMON compete and battle\n"
	.string "so hard for you?\p"
	.string "They do so because they can see\n"
	.string "the love and trust you have\l"
	.string "towards POKéMON.\p"
	.string "Never forget that.$"

gFameCheckerPersonName_Daisy:: @ 0x81B0251
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}DAISY$"

gFameCheckerPersonQuote_Daisy:: @ 0x81B025D
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}From: DAISY\n"
	.string "To: {PLAYER}\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}While I was comfortably enjoying\n"
	.string "my tea breaks, you've grown very\l"
	.string "skilled and powerful.\p"
	.string "I hope you'll remain a good rival\n"
	.string "to my little brother.$"

gFameCheckerPersonName_Brock:: @ 0x81B030F
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}BROCK$"

gFameCheckerPersonQuote_Brock:: @ 0x81B031B
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}From: BROCK\n"
	.string "To: {PLAYER}\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}In this big world of ours, there\n"
	.string "must be many tough TRAINERS.\p"
	.string "Let's both keep training and\n"
	.string "making ourselves stronger!$"

gFameCheckerPersonName_Misty:: @ 0x81B03B3
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}MISTY$"

gFameCheckerPersonQuote_Misty:: @ 0x81B03BF
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}From: MISTY\n"
	.string "To: {PLAYER}\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}I'm going to keep training here at\n"
	.string "this GYM.\p"
	.string "When I get better, I'd love to hit\n"
	.string "the road and travel.$"

gFameCheckerPersonName_LtSurge:: @ 0x81B0446
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}LT. SURGE$"

gFameCheckerPersonQuote_LtSurge:: @ 0x81B0456
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}From: LT. SURGE\n"
	.string "To: {PLAYER}\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}Hey, kid!\n"
	.string "You electrified me in our battle!\p"
	.string "I didn't know that there were\n"
	.string "gutsy TRAINERS like you.\p"
	.string "It made me change my mind about\n"
	.string "you!$"

gFameCheckerPersonName_Erika:: @ 0x81B0504
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}ERIKA$"

gFameCheckerPersonQuote_Erika:: @ 0x81B0510
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}From: ERIKA\n"
	.string "To: {PLAYER}\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}I am so glad that there are strong\n"
	.string "TRAINERS like you.\p"
	.string "That awareness alone inspires and\n"
	.string "motivates me to try harder.\p"
	.string "Please visit me again.\n"
	.string "Zzz…$"

gFameCheckerPersonName_Koga:: @ 0x81B05C2
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}KOGA$"

gFameCheckerPersonQuote_Koga:: @ 0x81B05CD
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}From: KOGA\n"
	.string "To: {PLAYER}\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}You and I, we must both set our\n"
	.string "sights higher and work towards\l"
	.string "meeting our challenges.\p"
	.string "Now, I must go train my daughter.$"

gFameCheckerPersonName_Sabrina:: @ 0x81B0667
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}SABRINA$"

gFameCheckerPersonQuote_Sabrina:: @ 0x81B0675
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}From: SABRINA\n"
	.string "To: {PLAYER}\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}The love you have towards your\n"
	.string "POKéMON…\p"
	.string "It was a power that was never\n"
	.string "bested by my psychic power.$"

gFameCheckerPersonName_Blaine:: @ 0x81B06FB
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}BLAINE$"

gFameCheckerPersonQuote_Blaine:: @ 0x81B0708
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}From: BLAINE\n"
	.string "To: {PLAYER}\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}My fire POKéMON!\n"
	.string "They'll become even more powerful!\p"
	.string "And now, a quiz. How many kinds of\n"
	.string "FIRE-type POKéMON are there?$"

gFameCheckerPersonName_Lorelei:: @ 0x81B079F
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}LORELEI$"

gFameCheckerPersonQuote_Lorelei:: @ 0x81B07AD
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}From: LORELEI\n"
	.string "To: {PLAYER}\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}I needed to thank you for your\n"
	.string "help.\p"
	.string "But that has nothing to do with our\n"
	.string "battles.\p"
	.string "You'd better watch out next time!$"

gFameCheckerPersonName_Bruno:: @ 0x81B0845
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}BRUNO$"

gFameCheckerPersonQuote_Bruno:: @ 0x81B0851
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}From: BRUNO\n"
	.string "To: {PLAYER}\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}The super power of your POKéMON\n"
	.string "and you I've experienced myself.\p"
	.string "Next time, maybe I should show you\n"
	.string "how to train yourself.$"

gFameCheckerPersonName_Agatha:: @ 0x81B08EE
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}AGATHA$"

gFameCheckerPersonQuote_Agatha:: @ 0x81B08FB
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}From: AGATHA\n"
	.string "To: {PLAYER}\p"
	.string "{SIZE 05}{COLOR RED}{SHADOW GREEN}When you grow older, don't you\n"
	.string "dare go soft like that coot OAK!\p"
	.string "Be like me and keep battling on!$"

gFameCheckerPersonName_Lance:: @ 0x81B097F
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}LANCE$"

gFameCheckerPersonQuote_Lance:: @ 0x81B098B
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}From: LANCE\n"
	.string "To: {PLAYER}\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}I'm considering going back to my\n"
	.string "hometown.\p"
	.string "I want to retrain my DRAGON-type\n"
	.string "POKéMON and strengthen them.\p"
	.string "I'd like to invite you to my\n"
	.string "hometown one day.$"

gFameCheckerPersonName_Bill:: @ 0x81B0A45
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}BILL$"

gFameCheckerPersonQuote_Bill:: @ 0x81B0A50
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}From: BILL\n"
	.string "To: {PLAYER}\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}Hey, there! CELIO had nothing but\n"
	.string "praise for you.\p"
	.string "Hearing that makes me happy.\p"
	.string "When you catch some rare POKéMON,\n"
	.string "come show me, okay? Promise!$"

gFameCheckerPersonName_MrFuji:: @ 0x81B0AFF
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}MR. FUJI$"

gFameCheckerPersonQuote_MrFuji:: @ 0x81B0B0E
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}From: MR. FUJI\n"
	.string "To: {PLAYER}\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}Instead of hoping for the happiness\n"
	.string "of just your POKéMON…\p"
	.string "…Can I get you to wish for the\n"
	.string "happiness of all POKéMON?$"

gFameCheckerPersonName_Giovanni:: @ 0x81B0BA6
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}GIOVANNI$"

gFameCheckerPersonQuote_Giovanni:: @ 0x81B0BB5
	.string "{COLOR LIGHT_GRAY}{SHADOW BLACK}From: GIOVANNI\n"
	.string "To: {PLAYER}\p"
	.string "{SIZE 04}{COLOR RED}{SHADOW GREEN}There is nothing that I wish to say\n"
	.string "to you.\p"
	.string "I will concentrate solely on\n"
	.string "bettering myself, and none other.$"

gFameCheckerFlavorTextOriginLocation_ProfOak0:: @ 0x81B0C45
	.string "PALLET TOWN$"

gFameCheckerFlavorTextOriginLocation_ProfOak1:: @ 81B0C51
	.string "RESEARCH LAB$"

gFameCheckerFlavorTextOriginLocation_ProfOak2:: @ 81B0C5E
	.string "RESEARCH LAB$"

gFameCheckerFlavorTextOriginLocation_ProfOak3:: @ 81B0C6B
	.string "VIRIDIAN CITY$"

gFameCheckerFlavorTextOriginLocation_ProfOak4:: @ 81B0C79
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_ProfOak5:: @ 81B0C88
	.string "RESEARCH LAB$"

gFameCheckerFlavorTextOriginLocation_Daisy0:: @ 81B0C95
	.string "RESEARCH LAB$"

gFameCheckerFlavorTextOriginLocation_Daisy1:: @ 81B0CA2
	.string "VERMILION CITY$"

gFameCheckerFlavorTextOriginLocation_Daisy2:: @ 81B0CB1
	.string "WATER LABYRINTH$"

gFameCheckerFlavorTextOriginLocation_Daisy3:: @ 81B0CC1
	.string "VIRIDIAN CITY$"

gFameCheckerFlavorTextOriginLocation_Daisy4:: @ 81B0CCF
	.string "CELADON MANSION$"

gFameCheckerFlavorTextOriginLocation_Daisy5:: @ 81B0CDF
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Brock0:: @ 81B0CEB
	.string "PEWTER CITY$"

gFameCheckerFlavorTextOriginLocation_Brock1:: @ 81B0CF7
	.string "PEWTER GYM$"

gFameCheckerFlavorTextOriginLocation_Brock2:: @ 81B0D02
	.string "PEWTER CITY$"

gFameCheckerFlavorTextOriginLocation_Brock3:: @ 81B0D0E
	.string "ROUTE 4$"

gFameCheckerFlavorTextOriginLocation_Brock4:: @ 81B0D16
	.string "MT. MOON$"

gFameCheckerFlavorTextOriginLocation_Brock5:: @ 81B0D1F
	.string "PEWTER MUSEUM$"

gFameCheckerFlavorTextOriginLocation_Misty0:: @ 81B0D2D
	.string "CERULEAN CITY$"

gFameCheckerFlavorTextOriginLocation_Misty1:: @ 81B0D3B
	.string "CERULEAN GYM$"

gFameCheckerFlavorTextOriginLocation_Misty2:: @ 81B0D48
	.string "CERULEAN GYM$"

gFameCheckerFlavorTextOriginLocation_Misty3:: @ 81B0D55
	.string "SEAFOAM ISLANDS$"

gFameCheckerFlavorTextOriginLocation_Misty4:: @ 81B0D65
	.string "CERULEAN CAPE$"

gFameCheckerFlavorTextOriginLocation_Misty5:: @ 81B0D73
	.string "CERULEAN CITY$"

gFameCheckerFlavorTextOriginLocation_LtSurge0:: @ 81B0D81
	.string "VERMILION CITY$"

gFameCheckerFlavorTextOriginLocation_LtSurge1:: @ 81B0D90
	.string "VERMILION GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge2:: @ 81B0D9E
	.string "VERMILION GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge3:: @ 81B0DAC
	.string "VERMILION GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge4:: @ 81B0DBA
	.string "VERMILION GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge5:: @ 81B0DC8
	.string "VERMILION CITY$"

gFameCheckerFlavorTextOriginLocation_Erika0:: @ 81B0DD7
	.string "CELADON CITY$"

gFameCheckerFlavorTextOriginLocation_Erika1:: @ 81B0DE4
	.string "CELADON GYM$"

gFameCheckerFlavorTextOriginLocation_Erika2:: @ 81B0DF0
	.string "CELADON GYM$"

gFameCheckerFlavorTextOriginLocation_Erika3:: @ 81B0DFC
	.string "CELADON GYM$"

gFameCheckerFlavorTextOriginLocation_Erika4:: @ 81B0E08
	.string "CELADON GYM$"

gFameCheckerFlavorTextOriginLocation_Erika5:: @ 81B0E14
	.string "CELADON MANSION$"

gFameCheckerFlavorTextOriginLocation_Koga0:: @ 81B0E24
	.string "FUCHSIA CITY$"

gFameCheckerFlavorTextOriginLocation_Koga1:: @ 81B0E31
	.string "FUCHSIA GYM$"

gFameCheckerFlavorTextOriginLocation_Koga2:: @ 81B0E3D
	.string "FUCHSIA GYM$"

gFameCheckerFlavorTextOriginLocation_Koga3:: @ 81B0E49
	.string "FUCHSIA CITY$"

gFameCheckerFlavorTextOriginLocation_Koga4:: @ 81B0E56
	.string "FUCHSIA CITY$"

gFameCheckerFlavorTextOriginLocation_Koga5:: @ 81B0E63
	.string "SAFARI ZONE$"

gFameCheckerFlavorTextOriginLocation_Sabrina0:: @ 81B0E6F
	.string "SAFFRON CITY$"

gFameCheckerFlavorTextOriginLocation_Sabrina1:: @ 81B0E7C
	.string "THREE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Sabrina2:: @ 81B0E89
	.string "SAFFRON GYM$"

gFameCheckerFlavorTextOriginLocation_Sabrina3:: @ 81B0E95
	.string "SAFFRON GYM$"

gFameCheckerFlavorTextOriginLocation_Sabrina4:: @ 81B0EA1
	.string "SAFFRON CITY$"

gFameCheckerFlavorTextOriginLocation_Sabrina5:: @ 81B0EAE
	.string "SAFFRON GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine0:: @ 81B0EBA
	.string "CINNABAR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Blaine1:: @ 81B0ECA
	.string "CINNABAR GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine2:: @ 81B0ED7
	.string "CINNABAR GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine3:: @ 81B0EE4
	.string "CINNABAR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Blaine4:: @ 81B0EF4
	.string "CINNABAR GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine5:: @ 81B0F01
	.string "RESORT GORGEOUS$"

gFameCheckerFlavorTextOriginLocation_Lorelei0:: @ 81B0F11
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lorelei1:: @ 81B0F20
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lorelei2:: @ 81B0F2F
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lorelei3:: @ 81B0F3B
	.string "FIVE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lorelei4:: @ 81B0F47
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lorelei5:: @ 81B0F53
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bruno0:: @ 81B0F5F
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Bruno1:: @ 81B0F6E
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Bruno2:: @ 81B0F7D
	.string "SAFFRON CITY$"

gFameCheckerFlavorTextOriginLocation_Bruno3:: @ 81B0F8A
	.string "EMBER SPA$"

gFameCheckerFlavorTextOriginLocation_Bruno4:: @ 81B0F94
	.string "TWO ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bruno5:: @ 81B0F9F
	.string "SEVAULT CANYON$"

gFameCheckerFlavorTextOriginLocation_Agatha0:: @ 81B0FAE
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Agatha1:: @ 81B0FBD
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Agatha2:: @ 81B0FCC
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Agatha3:: @ 81B0FDB
	.string "SEVEN ISLAND$"

gFameCheckerFlavorTextOriginLocation_Agatha4:: @ 81B0FE8
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Agatha5:: @ 81B0FF7
	.string "SIX ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lance0:: @ 81B1002
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lance1:: @ 81B1011
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lance2:: @ 81B1020
	.string "SAFFRON CITY$"

gFameCheckerFlavorTextOriginLocation_Lance3:: @ 81B102D
	.string "CELADON DEPT.$"

gFameCheckerFlavorTextOriginLocation_Lance4:: @ 81B103B
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Lance5:: @ 81B104A
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Bill0:: @ 81B1059
	.string "CERULEAN CITY$"

gFameCheckerFlavorTextOriginLocation_Bill1:: @ 81B1067
	.string "CERULEAN CITY$"

gFameCheckerFlavorTextOriginLocation_Bill2:: @ 81B1075
	.string "FUCHSIA CITY$"

gFameCheckerFlavorTextOriginLocation_Bill3:: @ 81B1082
	.string "ONE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bill4:: @ 81B108D
	.string "ONE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bill5:: @ 81B1098
	.string "ONE ISLAND$"

gFameCheckerFlavorTextOriginLocation_MrFuji0:: @ 81B10A3
	.string "LAVENDER TOWN$"

gFameCheckerFlavorTextOriginLocation_MrFuji1:: @ 81B10B1
	.string "POKéMON TOWER$"

gFameCheckerFlavorTextOriginLocation_MrFuji2:: @ 81B10BF
	.string "LAVENDER TOWN$"

gFameCheckerFlavorTextOriginLocation_MrFuji3:: @ 81B10CD
	.string "LAVENDER TOWN$"

gFameCheckerFlavorTextOriginLocation_MrFuji4:: @ 81B10DB
	.string "CINNABAR GYM$"

gFameCheckerFlavorTextOriginLocation_MrFuji5:: @ 81B10E8
	.string "CINNABAR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Giovanni0:: @ 81B10F8
	.string "ROCKET HIDEOUT$"

gFameCheckerFlavorTextOriginLocation_Giovanni1:: @ 81B1107
	.string "SILPH CO.$"

gFameCheckerFlavorTextOriginLocation_Giovanni2:: @ 81B1111
	.string "SILPH CO.$"

gFameCheckerFlavorTextOriginLocation_Giovanni3:: @ 81B111B
	.string "VIRIDIAN GYM$"

gFameCheckerFlavorTextOriginLocation_Giovanni4:: @ 81B1128
	.string "VIRIDIAN GYM$"

gFameCheckerFlavorTextOriginLocation_Giovanni5:: @ 81B1135
	.string "ROCKET WAREHOUSE$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0:: @ 81B1146
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1:: @ 81B114B
	.string "PROF. OAK$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2:: @ 81B1155
	.string "AIDE$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3:: @ 81B115A
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4:: @ 81B116A
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5:: @ 81B1171
	.string "AIDE$"

gFameCheckerFlavorTextOriginObjectName_Daisy0:: @ 81B1176
	.string "AIDE$"

gFameCheckerFlavorTextOriginObjectName_Daisy1:: @ 81B117B
	.string "WOMAN$"

gFameCheckerFlavorTextOriginObjectName_Daisy2:: @ 81B1181
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_Daisy3:: @ 81B1185
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Daisy4:: @ 81B1195
	.string "OLD LADY$"

gFameCheckerFlavorTextOriginObjectName_Daisy5:: @ 81B119E
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Brock0:: @ 81B11AE
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Brock1:: @ 81B11B3
	.string "BROCK$"

gFameCheckerFlavorTextOriginObjectName_Brock2:: @ 81B11B9
	.string "YOUNG MAN$"

gFameCheckerFlavorTextOriginObjectName_Brock3:: @ 81B11C3
	.string "BOY$"

gFameCheckerFlavorTextOriginObjectName_Brock4:: @ 81B11C7
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_Brock5:: @ 81B11CB
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Misty0:: @ 81B11DB
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Misty1:: @ 81B11E0
	.string "MISTY$"

gFameCheckerFlavorTextOriginObjectName_Misty2:: @ 81B11E6
	.string "LUIS$"

gFameCheckerFlavorTextOriginObjectName_Misty3:: @ 81B11EB
	.string "YOUNG MAN$"

gFameCheckerFlavorTextOriginObjectName_Misty4:: @ 81B11F5
	.string "DAME$"

gFameCheckerFlavorTextOriginObjectName_Misty5:: @ 81B11FA
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0:: @ 81B120A
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1:: @ 81B120F
	.string "LT. SURGE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2:: @ 81B1219
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3:: @ 81B1220
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4:: @ 81B1227
	.string "DWAYNE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5:: @ 81B122E
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Erika0:: @ 81B123E
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Erika1:: @ 81B1243
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika2:: @ 81B1249
	.string "LOLA$"

gFameCheckerFlavorTextOriginObjectName_Erika3:: @ 81B124E
	.string "TAMIA$"

gFameCheckerFlavorTextOriginObjectName_Erika4:: @ 81B1254
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika5:: @ 81B125A
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Koga0:: @ 81B126A
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Koga1:: @ 81B126F
	.string "KOGA$"

gFameCheckerFlavorTextOriginObjectName_Koga2:: @ 81B1274
	.string "KIRK$"

gFameCheckerFlavorTextOriginObjectName_Koga3:: @ 81B1279
	.string "CHARINE$"

gFameCheckerFlavorTextOriginObjectName_Koga4:: @ 81B1281
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Koga5:: @ 81B1291
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0:: @ 81B1295
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1:: @ 81B129A
	.string "YOUNG MAN$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2:: @ 81B12A4
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3:: @ 81B12AC
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4:: @ 81B12B4
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5:: @ 81B12C4
	.string "TYRON$"

gFameCheckerFlavorTextOriginObjectName_Blaine0:: @ 81B12CA
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Blaine1:: @ 81B12CF
	.string "BLAINE$"

gFameCheckerFlavorTextOriginObjectName_Blaine2:: @ 81B12D6
	.string "DEREK$"

gFameCheckerFlavorTextOriginObjectName_Blaine3:: @ 81B12DC
	.string "WOMAN$"

gFameCheckerFlavorTextOriginObjectName_Blaine4:: @ 81B12E2
	.string "PHOTO$"

gFameCheckerFlavorTextOriginObjectName_Blaine5:: @ 81B12E8
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0:: @ 81B12F8
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1:: @ 81B1300
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2:: @ 81B1308
	.string "OLD MAN$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3:: @ 81B1310
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4:: @ 81B1320
	.string "LITTLE GIRL$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5:: @ 81B132C
	.string "OLD LADY$"

gFameCheckerFlavorTextOriginObjectName_Bruno0:: @ 81B1335
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno1:: @ 81B133B
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno2:: @ 81B1341
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Bruno3:: @ 81B1351
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Bruno4:: @ 81B1359
	.string "WOMAN$"

gFameCheckerFlavorTextOriginObjectName_Bruno5:: @ 81B135F
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha0:: @ 81B1367
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha1:: @ 81B136E
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha2:: @ 81B1376
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha3:: @ 81B137E
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Agatha4:: @ 81B138E
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha5:: @ 81B1395
	.string "OLD LADY$"

gFameCheckerFlavorTextOriginObjectName_Lance0:: @ 81B139E
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance1:: @ 81B13A4
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance2:: @ 81B13AA
	.string "WOMAN$"

gFameCheckerFlavorTextOriginObjectName_Lance3:: @ 81B13B0
	.string "LITTLE GIRL$"

gFameCheckerFlavorTextOriginObjectName_Lance4:: @ 81B13BC
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lance5:: @ 81B13CC
	.string "YOUNG MAN$"

gFameCheckerFlavorTextOriginObjectName_Bill0:: @ 81B13D6
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1:: @ 81B13D9
	.string "LITTLE BOY$"

gFameCheckerFlavorTextOriginObjectName_Bill2:: @ 81B13E4
	.string "OLD MAN$"

gFameCheckerFlavorTextOriginObjectName_Bill3:: @ 81B13EC
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill4:: @ 81B13F2
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill5:: @ 81B13F8
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0:: @ 81B13FE
	.string "LITTLE GIRL$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1:: @ 81B140A
	.string "TEAM ROCKET$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2:: @ 81B1416
	.string "MAGAZINE$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3:: @ 81B141F
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4:: @ 81B1423
	.string "PHOTO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5:: @ 81B1429
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0:: @ 81B1439
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1:: @ 81B1442
	.string "SCIENTIST$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2:: @ 81B144C
	.string "SCIENTIST$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3:: @ 81B1456
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4:: @ 81B145F
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5:: @ 81B1463
	.string "GIDEON$"

PokemonJournal_Text_SpecialFeatureBrock:: @ 81B146A
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: PEWTER GYM\n"
	.string "LEADER BROCK!\p"
	.string "BROCK rarely laughs, but is said to\n"
	.string "be unable to stop if he starts.$"

PokemonJournal_Text_SpecialFeatureMisty:: @ 81B14E8
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CERULEAN GYM\n"
	.string "LEADER MISTY!\p"
	.string "MISTY is said to worship LORELEI\n"
	.string "of the ELITE FOUR.$"

gUnknown_81B1558:: @ 81B1558
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: VERMILION GYM\n"
	.string "LEADER LT. SURGE!\p"
	.string "LT. SURGE is rumored to have been\n"
	.string "a pilot while home in America.\p"
	.string "He used the electricity generated\n"
	.string "by POKéMON to power his plane.$"

gUnknown_81B161B:: @ 81B161B
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CELADON GYM\n"
	.string "LEADER ERIKA!\p"
	.string "Rumor has it that if you peek into\n"
	.string "CELADON GYM, you can often\l"
	.string "see ERIKA snoozing.$"

PokemonJournal_Text_SpecialFeatureKoga:: @ 81B16A8
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: FUCHSIA GYM\n"
	.string "LEADER KOGA!\p"
	.string "KOGA is said to have a thorough\n"
	.string "knowledge of medicine.\p"
	.string "He even concocts medicine to nurse\n"
	.string "his POKéMON to health.$"

gUnknown_81B1753:: @ 81B1753
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: SAFFRON GYM\n"
	.string "LEADER SABRINA!\p"
	.string "People say that SABRINA can\n"
	.string "communicate with her POKéMON\l"
	.string "during battle without speaking.$"

gUnknown_81B17E9:: @ 81B17E9
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CINNABAR GYM\n"
	.string "LEADER BLAINE!\p"
	.string "BLAINE is said to remove his dark\n"
	.string "shades only when he is thinking up\l"
	.string "new quiz questions.$"

gUnknown_81B187F:: @ 81B187F
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's LORELEI!\p"
	.string "Known for her logical, calculated,\n"
	.string "and cool battling style, LORELEI\l"
	.string "has a surprising secret!$"

gUnknown_81B1913:: @ 81B1913
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's BRUNO!\p"
	.string "BRUNO apparently joined the ELITE\n"
	.string "FOUR out of his burning ambition to\l"
	.string "battle the best TRAINERS.$"

gUnknown_81B19A8:: @ 81B19A8
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's AGATHA!\p"
	.string "In her youth, AGATHA and PROF.\n"
	.string "OAK were rivals who vied for\l"
	.string "supremacy as TRAINERS.$"

gUnknown_81B1A31:: @ 81B1A31
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's LANCE!\p"
	.string "LANCE's grandfather is thought to\n"
	.string "be the elder of a famous clan of\l"
	.string "dragon masters.$"

gUnknown_81B1AB9:: @ 81B1AB9
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: PROF. OAK,\n"
	.string "the POKéMON Researcher!\p"
	.string "PROF. OAK reportedly lives with his\n"
	.string "grandchildren DAISY and {RIVAL}.$"

gUnknown_81B1B3D:: @ 81B1B3D
	.string "This is a POKéMON JOURNAL from\n"
	.string "years ago…\p"
	.string "POKéMON JOURNAL\n"
	.string "CONTEST Special!\p"
	.string "The Spring POKéMON CONTEST's\n"
	.string "Grand Champion is DAISY OAK of\l"
	.string "PALLET TOWN!$"

PokemonJournal_Text_SpecialFeatureMrFuji:: @ 81B1BD1
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "MR. FUJI of POKéMON HOUSE!\p"
	.string "Editor: The shy MR. FUJI turned\n"
	.string "down our interview requests.\p"
	.string "He is a kindly man who is adored\n"
	.string "and respected in LAVENDER TOWN.$"

gUnknown_81B1C8B:: @ 81B1C8B
	.string "Hmm…\n"
	.string "Is that right…$"

gUnknown_81B1C9F:: @ 81B1C9F
	.string "Oh!\n"
	.string "Look, look!$"

gUnknown_81B1CAF:: @ 81B1CAF
	.string "Read it, read it!$"

gUnknown_81B1CC1:: @ 81B1CC1
	.string "TRAINER TIPS\p"
	.string "Press START to open the MENU!$"

gUnknown_81B1CEC:: @ 81B1CEC
	.string "Signs are useful, aren't they?$"

gUnknown_81B1D0B:: @ 81B1D0B
	.string "Look, look!\p"
	.string "I copied what it said on one of\n"
	.string "those TRAINER TIPS signs!$"

gUnknown_81B1D51:: @ 81B1D51
	.string "TRAINER TIPS!\p"
	.string "Press START to open the MENU!$"

gUnknown_81B1D7D:: @ 81B1D7D
	.string "It's a POKéMON PRINTER!\p"
	.string "It can put a print of your POKéMON\n"
	.string "on the back of your TRAINER CARD.\p"
	.string "It costs only ¥50.\n"
	.string "Would you like to try it?$"

gUnknown_81B1E07:: @ 81B1E07
	.string "You don't have enough money.$"

gUnknown_81B1E24:: @ 81B1E24
	.string "Please choose the print type.$"

gUnknown_81B1E42:: @ 81B1E42
	.string "A big smile for the photo, please!\n"
	.string "Three… Two… One…\p"
	.string "Flash!$"

gUnknown_81B1E7D:: @ 81B1E7D
	.string "Your POKéMON print is ready!\n"
	.string "Check your TRAINER CARD.$"

gUnknown_81B1EB3:: @ 81B1EB3
	.string "Giggle…\n"
	.string "I collected a ton of STICKERS.\l"
	.string "I wish I could show them off…$"

gUnknown_81B1EF8:: @ 81B1EF8
	.string "Oh, excellent!\n"
	.string "You've come to the right place!\p"
	.string "Look, look! See? See?\n"
	.string "These are my STICKERS!\l"
	.string "Look how many I got!\p"
	.string "I bet you want some.\n"
	.string "I bet you do!\p"
	.string "I'll give a STICKER if you can tell\n"
	.string "me something awesome about\l"
	.string "yourself.\p"
	.string "What will you brag about?$"

gUnknown_81B1FEF:: @ 81B1FEF
	.string "Brag about something for me.\n"
	.string "I'll give you a STICKER.$"

gUnknown_81B2025:: @ 81B2025
	.string "Oh, hi!\n"
	.string "Here comes the braggart.\p"
	.string "What are you going to brag about\n"
	.string "today?$"

gUnknown_81B206E:: @ 81B206E
	.string "Oh, wow, you made it into the\n"
	.string "HALL OF FAME.\p"
	.string "That's pretty good, yup!\n"
	.string "I'll give you one of these.$"

gUnknown_81B20CF:: @ 81B20CF
	.string "Oh, wow, you've entered the\n"
	.string "HALL OF FAME often!\p"
	.string "That's impressive, yup!\n"
	.string "I'll give you one of these.$"

gUnknown_81B2133:: @ 81B2133
	.string "Whoa! You've made it into the\n"
	.string "HALL OF FAME that often?\l"
	.string "That's seriously incredible, yup!\p"
	.string "You own the POKéMON LEAGUE!\n"
	.string "I'll give you one of these.$"

gUnknown_81B21C4:: @ 81B21C4
	.string "No way! You've gone into the\n"
	.string "HALL OF FAME that many times?\p"
	.string "You're beyond incredible, yup!\n"
	.string "That's it, I have to give you this.$"

gUnknown_81B2242:: @ 81B2242
	.string "The HALL OF FAME STICKER was\n"
	.string "applied to the TRAINER CARD.$"

gUnknown_81B227C:: @ 81B227C
	.string "Hmm…\p"
	.string "Come back with a better story next\n"
	.string "time, okay?$"

gUnknown_81B22B0:: @ 81B22B0
	.string "Oh, no, no can do.\p"
	.string "You're practically a living legend.\n"
	.string "I have no SITCKERS left to give.$"

gUnknown_81B2308:: @ 81B2308
	.string "Oh, wow, there are POKéMON EGGS?\n"
	.string "I didn't know that!\p"
	.string "That's pretty good, yup!\n"
	.string "I'll give you one of these.$"

gUnknown_81B2372:: @ 81B2372
	.string "You've hatched that many EGGS?\n"
	.string "You really must like them!\p"
	.string "That's impressive, yup!\n"
	.string "I'll give you one of these.$"

gUnknown_81B23E0:: @ 81B23E0
	.string "Whoa! You've hatched a whole\n"
	.string "bunch of EGGS!\p"
	.string "You're an EGG-hatching machine!\n"
	.string "I'll give you one of these.$"

gUnknown_81B2448:: @ 81B2448
	.string "Wh… You hatched that many EGGS?\p"
	.string "What's behind your love of EGGS?\n"
	.string "It's beyond incredible, yup!\p"
	.string "You're too awesome, I tell you.\n"
	.string "That's it, I have to give you this.$"

gUnknown_81B24EA:: @ 81B24EA
	.string "The EGG STICKER was applied\n"
	.string "to the TRAINER CARD.$"

gUnknown_81B251B:: @ 81B251B
	.string "Hmm…\p"
	.string "Come back with a better story next\n"
	.string "time, okay?$"

gUnknown_81B254F:: @ 81B254F
	.string "Oh, no, no can do.\p"
	.string "You're practically a living legend.\n"
	.string "I have no SITCKERS left to give.$"

gUnknown_81B25A7:: @ 81B25A7
	.string "Oh, wow, you've had success\n"
	.string "link battling?\p"
	.string "You're pretty strong, yup!\n"
	.string "I'll give you one of these.$"

gUnknown_81B2609:: @ 81B2609
	.string "You've beaten your friends a lot\n"
	.string "link battling, huh?\p"
	.string "You're impressively strong, yup!\n"
	.string "I'll give you one of these.$"

gUnknown_81B267B:: @ 81B267B
	.string "Whoa! You've beaten your friends\n"
	.string "a frightful number of times.\p"
	.string "Have you lost friends over this?\n"
	.string "I'll give you one of these.$"

gUnknown_81B26F6:: @ 81B26F6
	.string "Wh… Wickedly whoa!\n"
	.string "You've won mind-blowingly often!\p"
	.string "It just knocks me out thinking\n"
	.string "about how tough you are.\p"
	.string "You're the stuff of nightmares!\n"
	.string "That's it, I have to give you this.$"

gUnknown_81B27A6:: @ 81B27A6
	.string "The VICTORY STICKER was applied\n"
	.string "to the TRAINER CARD.$"

gUnknown_81B27DB:: @ 81B27DB
	.string "Hmm…\p"
	.string "Come back with a better story next\n"
	.string "time, okay?$"

gUnknown_81B280F:: @ 81B280F
	.string "Oh, no, no can do.\p"
	.string "You're practically a living legend.\n"
	.string "I have no SITCKERS left to give.$"
