gUnknown_83EECFC::
	.string "PALLET TOWN$"

gUnknown_83EED08:: @ 83EED08
	.string "VIRIDIAN CITY$"

gUnknown_83EED16:: @ 83EED16
	.string "PEWTER CITY$"

gUnknown_83EED22:: @ 83EED22
	.string "CERULEAN CITY$"

gUnknown_83EED30:: @ 83EED30
	.string "LAVENDER TOWN$"

gUnknown_83EED3E:: @ 83EED3E
	.string "VERMILION CITY$"

gUnknown_83EED4D:: @ 83EED4D
	.string "CELADON CITY$"

gUnknown_83EED5A:: @ 83EED5A
	.string "FUCHSIA CITY$"

gUnknown_83EED67:: @ 83EED67
	.string "CINNABAR ISLAND$"

gUnknown_83EED77:: @ 83EED77
	.string "INDIGO PLATEAU$"

gUnknown_83EED86:: @ 83EED86
	.string "SAFFRON CITY$"

gUnknown_83EED93:: @ 83EED93
	.string "ROUTE 4$"

gUnknown_83EED9B:: @ 83EED9B
	.string "ROUTE 10$"

gUnknown_83EEDA4:: @ 83EEDA4
	.string "ROUTE 1$"

gUnknown_83EEDAC:: @ 83EEDAC
	.string "ROUTE 2$"

gUnknown_83EEDB4:: @ 83EEDB4
	.string "ROUTE 3$"

gUnknown_83EEDBC:: @ 83EEDBC
	.string "ROUTE 4$"

gUnknown_83EEDC4:: @ 83EEDC4
	.string "ROUTE 5$"

gUnknown_83EEDCC:: @ 83EEDCC
	.string "ROUTE 6$"

gUnknown_83EEDD4:: @ 83EEDD4
	.string "ROUTE 7$"

gUnknown_83EEDDC:: @ 83EEDDC
	.string "ROUTE 8$"

gUnknown_83EEDE4:: @ 83EEDE4
	.string "ROUTE 9$"

gUnknown_83EEDEC:: @ 83EEDEC
	.string "ROUTE 10$"

gUnknown_83EEDF5:: @ 83EEDF5
	.string "ROUTE 11$"

gUnknown_83EEDFE:: @ 83EEDFE
	.string "ROUTE 12$"

gUnknown_83EEE07:: @ 83EEE07
	.string "ROUTE 13$"

gUnknown_83EEE10:: @ 83EEE10
	.string "ROUTE 14$"

gUnknown_83EEE19:: @ 83EEE19
	.string "ROUTE 15$"

gUnknown_83EEE22:: @ 83EEE22
	.string "ROUTE 16$"

gUnknown_83EEE2B:: @ 83EEE2B
	.string "ROUTE 17$"

gUnknown_83EEE34:: @ 83EEE34
	.string "ROUTE 18$"

gUnknown_83EEE3D:: @ 83EEE3D
	.string "ROUTE 19$"

gUnknown_83EEE46:: @ 83EEE46
	.string "ROUTE 20$"

gUnknown_83EEE4F:: @ 83EEE4F
	.string "ROUTE 21$"

gUnknown_83EEE58:: @ 83EEE58
	.string "ROUTE 22$"

gUnknown_83EEE61:: @ 83EEE61
	.string "ROUTE 23$"

gUnknown_83EEE6A:: @ 83EEE6A
	.string "ROUTE 24$"

gUnknown_83EEE73:: @ 83EEE73
	.string "ROUTE 25$"

gUnknown_83EEE7C:: @ 83EEE7C
	.string "VIRIDIAN FOREST$"

gUnknown_83EEE8C:: @ 83EEE8C
	.string "MT. MOON$"

gUnknown_83EEE95:: @ 83EEE95
	.string "S.S. ANNE$"

gUnknown_83EEE9F:: @ 83EEE9F
	.string "UNDERGROUND PATH$"

gUnknown_83EEEB0:: @ 83EEEB0
	.string "UNDERGROUND PATH$"

gUnknown_83EEEC1:: @ 83EEEC1
	.string "DIGLETT’S CAVE$"

gUnknown_83EEED0:: @ 83EEED0
	.string "VICTORY ROAD$"

gUnknown_83EEEDD:: @ 83EEEDD
	.string "ROCKET HIDEOUT$"

gUnknown_83EEEEC:: @ 83EEEEC
	.string "SILPH CO.$"

gUnknown_83EEEF6:: @ 83EEEF6
	.string "POKéMON MANSION$"

gUnknown_83EEF06:: @ 83EEF06
	.string "SAFARI ZONE$"

gUnknown_83EEF12:: @ 83EEF12
	.string "POKéMON LEAGUE$"

gUnknown_83EEF21:: @ 83EEF21
	.string "ROCK TUNNEL$"

gUnknown_83EEF2D:: @ 83EEF2D
	.string "SEAFOAM ISLANDS$"

gUnknown_83EEF3D:: @ 83EEF3D
	.string "POKéMON TOWER$"

gUnknown_83EEF4B:: @ 83EEF4B
	.string "CERULEAN CAVE$"

gUnknown_83EEF59:: @ 83EEF59
	.string "POWER PLANT$"

gUnknown_83EEF65:: @ 83EEF65
	.string "ONE ISLAND$"

gUnknown_83EEF70:: @ 83EEF70
	.string "TWO ISLAND$"

gUnknown_83EEF7B:: @ 83EEF7B
	.string "THREE ISLAND$"

gUnknown_83EEF88:: @ 83EEF88
	.string "FOUR ISLAND$"

gUnknown_83EEF94:: @ 83EEF94
	.string "FIVE ISLAND$"

gUnknown_83EEFA0:: @ 83EEFA0
	.string "SEVEN ISLAND$"

gUnknown_83EEFAD:: @ 83EEFAD
	.string "SIX ISLAND$"

gUnknown_83EEFB8:: @ 83EEFB8
	.string "KINDLE ROAD$"

gUnknown_83EEFC4:: @ 83EEFC4
	.string "TREASURE BEACH$"

gUnknown_83EEFD3:: @ 83EEFD3
	.string "CAPE BRINK$"

gUnknown_83EEFDE:: @ 83EEFDE
	.string "BOND BRIDGE$"

gUnknown_83EEFEA:: @ 83EEFEA
	.string "THREE ISLE PORT$"

gUnknown_83EEFFA:: @ 83EEFFA
	.string "SEVII ISLE 6$"

gUnknown_83EF007:: @ 83EF007
	.string "SEVII ISLE 7$"

gUnknown_83EF014:: @ 83EF014
	.string "SEVII ISLE 8$"

gUnknown_83EF021:: @ 83EF021
	.string "SEVII ISLE 9$"

gUnknown_83EF02E:: @ 83EF02E
	.string "RESORT GORGEOUS$"

gUnknown_83EF03E:: @ 83EF03E
	.string "WATER LABYRINTH$"

gUnknown_83EF04E:: @ 83EF04E
	.string "FIVE ISLE MEADOW$"

gUnknown_83EF05F:: @ 83EF05F
	.string "MEMORIAL PILLAR$"

gUnknown_83EF06F:: @ 83EF06F
	.string "OUTCAST ISLAND$"

gUnknown_83EF07E:: @ 83EF07E
	.string "GREEN PATH$"

gUnknown_83EF089:: @ 83EF089
	.string "WATER PATH$"

gUnknown_83EF094:: @ 83EF094
	.string "RUIN VALLEY$"

gUnknown_83EF0A0:: @ 83EF0A0
	.string "TRAINER TOWER$"

gUnknown_83EF0AE:: @ 83EF0AE
	.string "CANYON ENTRANCE$"

gUnknown_83EF0BE:: @ 83EF0BE
	.string "SEVAULT CANYON$"

gUnknown_83EF0CD:: @ 83EF0CD
	.string "TANOBY RUINS$"

gUnknown_83EF0DA:: @ 83EF0DA
	.string "SEVII ISLE 22$"

gUnknown_83EF0E8:: @ 83EF0E8
	.string "SEVII ISLE 23$"

gUnknown_83EF0F6:: @ 83EF0F6
	.string "SEVII ISLE 24$"

gUnknown_83EF104:: @ 83EF104
	.string "NAVEL ROCK$"

gUnknown_83EF10F:: @ 83EF10F
	.string "MT. EMBER$"

gUnknown_83EF119:: @ 83EF119
	.string "BERRY FOREST$"

gUnknown_83EF126:: @ 83EF126
	.string "ICEFALL CAVE$"

gUnknown_83EF133:: @ 83EF133
	.string "ROCKET WAREHOUSE$"

gUnknown_83EF144:: @ 83EF144
	.string "TRAINER TOWER$"

gUnknown_83EF152:: @ 83EF152
	.string "DOTTED HOLE$"

gUnknown_83EF15E:: @ 83EF15E
	.string "LOST CAVE$"

gUnknown_83EF168:: @ 83EF168
	.string "PATTERN BUSH$"

gUnknown_83EF175:: @ 83EF175
	.string "ALTERING CAVE$"

gUnknown_83EF183:: @ 83EF183
	.string "TANOBY CHAMBERS$"

gUnknown_83EF193:: @ 83EF193
	.string "THREE ISLE PATH$"

gUnknown_83EF1A3:: @ 83EF1A3
	.string "TANOBY KEY$"

gUnknown_83EF1AE:: @ 83EF1AE
	.string "BIRTH ISLAND$"

gUnknown_83EF1BB:: @ 83EF1BB
	.string "MONEAN CHAMBER$"

gUnknown_83EF1CA:: @ 83EF1CA
	.string "LIPTOO CHAMBER$"

gUnknown_83EF1D9:: @ 83EF1D9
	.string "WEEPTH CHAMBER$"

gUnknown_83EF1E8:: @ 83EF1E8
	.string "DILFORD CHAMBER$"

gUnknown_83EF1F8:: @ 83EF1F8
	.string "SCUFIB CHAMBER$"

gUnknown_83EF207:: @ 83EF207
	.string "RIXY CHAMBER$"

gUnknown_83EF214:: @ 83EF214
	.string "VIAPOIS CHAMBER$"

gUnknown_83EF224:: @ 83EF224
	.string "EMBER SPA$"

gUnknown_83EF22E:: @ 83EF22E
	.string "CELADON DEPT.$"

