Text_BootedUpPC:: @ 81A5075
	.string "{PLAYER} booted up the PC.$"

Text_AccessWhichPC:: @ 81A508A
	.string "Which PC should be accessed?$"

Text_AccessedSomeonesPC:: @ 81A50A7
	.string "Accessed Someone's PC.$"

Text_OpenedPkmnStorage:: @ 81A50BE
	.string "POKéMON Storage System opened.$"

Text_AccessedPlayersPC:: @ 81A50DD
	.string "Accessed {PLAYER}'s PC.$"

Text_AccessedBillsPC:: @ 81A50EF
	.string "Accessed BILL's PC.$"
