Text_MonSentToBoxInSomeonesPC::
    .string "{STR_VAR_2} was transferred to\n"
    .string "Someone's PC.\p"
    .string "It was placed in \n"
    .string "BOX “{STR_VAR_1}.”$"

Text_MonSentToBoxInBillsPC::
    .string "{STR_VAR_2} was transferred to\n"
    .string "BILL'S PC.\p"
    .string "It was placed in \n"
    .string "BOX “{STR_VAR_1}.”$"

Text_MonSentToBoxSomeonesBoxFull::
    .string "BOX “{STR_VAR_3}” on\n"
    .string "Someone's PC was full.\p"
    .string "{STR_VAR_2} was transferred to\n"
    .string "BOX “{STR_VAR_1}.”$"

Text_MonSentToBoxBillsBoxFull::
    .string "BOX “{STR_VAR_3}” on\n"
    .string "BILL'S PC was full.\p"
    .string "{STR_VAR_2} was transferred to\n"
    .string "BOX “{STR_VAR_1}.”$"

Text_PlayerObtainedTheMon::
    .string "{PLAYER} obtained\n"
    .string "the {STR_VAR_1}!$"

@ Unused. Translated below
@ You cannot carry any more Pokemon, so {STR_VAR_2} was sent to PC Box {STR_VAR_1}!
Text_MonSentToBoxInPC::
    .string "ポケモンを　もちきれないので\n"
    .string "パソコンの　ボックス“{STR_VAR_1}”　に\l"
    .string "{STR_VAR_2}を　てんそうした！$"

Text_NoMoreRoomForPokemon::
    .string "There's no more room for POKéMON!\p"
    .string "The POKéMON BOXES are full and\n"
    .string "can't accept any more!$"
