Text_MonSentToBoxInSomeonesPC:: @ 81A5CF1
    .string "{STR_VAR_2} was transferred to\n"
    .string "Someone's PC.\p"
    .string "It was placed in \n"
    .string "BOX “{STR_VAR_1}.”$"

Text_MonSentToBoxInBillsPC:: @ 81A5D31
    .string "{STR_VAR_2} was transferred to\n"
    .string "BILL'S PC.\p"
    .string "It was placed in \n"
    .string "BOX “{STR_VAR_1}.”$"

Text_MonSentToBoxSomeonesBoxFull:: @ 81A5D6E
    .string "BOX “{STR_VAR_3}” on\n"
    .string "Someone's PC was full.\p"
    .string "{STR_VAR_2} was transferred to\n"
    .string "BOX “{STR_VAR_1}.”$"

Text_MonSentToBoxBillsBoxFull:: @ 81A5DB1
    .string "BOX “{STR_VAR_3}” on\n"
    .string "BILL'S PC was full.\p"
    .string "{STR_VAR_2} was transferred to\n"
    .string "BOX “{STR_VAR_1}.”$"

Text_PlayerObtainedTheMon:: @ 81A5DF1
    .string "{PLAYER} obtained\n"
    .string "the {STR_VAR_1}!$"

@ Unused. Translated below
@ You cannot carry any more Pokemon, so {STR_VAR_2} was sent to PC Box {STR_VAR_1}!
Text_MonSentToBoxInPC:: @ 81A5E05
    .string "ポケモンを　もちきれないので\n"
    .string "パソコンの　ボックス“{STR_VAR_1}”　に\l"
    .string "{STR_VAR_2}を　てんそうした！$"

Text_NoMoreRoomForPokemon:: @ 81A5E31
    .string "There's no more room for POKéMON!\p"
    .string "The POKéMON BOXES are full and\n"
    .string "can't accept any more!$"
