Pokedude_Text_SpeedierBattlerGoesFirst::
	.string "POKé DUDE: The speedier of the\n"
	.string "battlers gets to attack first.$"

Pokedude_Text_MyRattataFasterThanPidgey::
	.string "It looks like my RATTATA was\n"
	.string "faster than the PIDGEY.$"

Pokedude_Text_BattlersTakeTurnsAttacking::
	.string "The battlers take turns attacking\n"
	.string "and reducing each other's HP.$"

Pokedude_Text_MyRattataWonGetsEXP::
	.string "My RATTATA reduced the foe's HP\n"
	.string "to zero, so it wins!\p"
	.string "The POKéMON that took part in the\n"
	.string "battle get EXP. Points.\p"
	.string "When a POKéMON collects enough\n"
	.string "EXP. Points, it levels up.\p"
	.string "Leveling up makes your POKéMON\n"
	.string "stronger than before.$"

Pokedude_Text_UhOhRattataPoisoned::
	.string "POKé DUDE: Uh-oh…\n"
	.string "My RATTATA has been poisoned…\p"
	.string "If a POKéMON is poisoned, it loses\n"
	.string "HP steadily.$"

Pokedude_Text_HealStatusRightAway::
	.string "If a POKéMON develops a status\n"
	.string "problem, heal it right away.$"

Pokedude_Text_UsingItemTakesTurn::
	.string "Using an item on a POKéMON uses\n"
	.string "up one turn, though.\p"
	.string "Now, it's the opponent's turn!$"

Pokedude_Text_YayWeManagedToWin::
	.string "Yay!\n"
	.string "We managed to win!$"

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass::
	.string "POKé DUDE: The move BUBBLE is\n"
	.string "a WATER-type attack.\p"
	.string "The targeted ODDISH is a\n"
	.string "GRASS/POISON-type POKéMON.\p"
	.string "The WATER-type attack is absorbed\n"
	.string "by the GRASS-type POKéMON…\p"
	.string "As a result, the move becomes not\n"
	.string "very effective, and inflicts only\l"
	.string "half the usual damage.$"

Pokedude_Text_GrassEffectiveAgainstWater::
	.string "Uh-oh, this is not good!\p"
	.string "The ABSORB attack you just saw\n"
	.string "is a GRASS-type move.\p"
	.string "POLIWAG is a WATER-type POKéMON.\p"
	.string "So, ABSORB becomes super\n"
	.string "effective, doubling the damage.$"

Pokedude_Text_LetsTryShiftingMons::
	.string "It's not going to be easy to win\n"
	.string "with this matchup…\p"
	.string "Let's try shifting POKéMON!$"

Pokedude_Text_ShiftingUsesTurn::
	.string "Shifting POKéMON in and out uses\n"
	.string "up one turn.\p"
	.string "Now, it's the opponent's turn.$"

Pokedude_Text_ButterfreeDoubleResistsGrass::
	.string "BUTTERFREE is a BUG/FLYING-type\n"
	.string "POKéMON.\p"
	.string "Against this POKéMON, a GRASS-\n"
	.string "type attack…\p"
	.string "…inflicts only half the usual\n"
	.string "damage on a BUG-type POKéMON…\p"
	.string "…And, it also causes only half the\n"
	.string "damage on a FLYING-type POKéMON.\p"
	.string "Therefore, BUTTERFREE, being a\n"
	.string "BUG/FLYING POKéMON, only takes\l"
	.string "one quarter of the usual damage.$"

Pokedude_Text_ButterfreeGoodAgainstOddish::
	.string "ODDISH is a GRASS/POISON-type\n"
	.string "POKéMON.\p"
	.string "A FLYING- or PSYCHIC-type attack\n"
	.string "is super effective against it.\p"
	.string "One of those types of attacks will\n"
	.string "inflict double the usual damage.\p"
	.string "Okay, here we go!$"

Pokedude_Text_YeahWeWon::
	.string "Yeah!\n"
	.string "We won!$"

Pokedude_Text_WeakenMonBeforeCatching::
	.string "POKé DUDE: When you're trying to\n"
	.string "catch a POKéMON, don't throw any\l"
	.string "POKé BALLS right away.\p"
	.string "First, you need to weaken it by\n"
	.string "reducing its HP.$"

Pokedude_Text_BestIfTargetStatused::
	.string "Okay, that should be good enough.\p"
	.string "But, if it's possible, it would be\n"
	.string "best if the target has a status\l"
	.string "problem.\p"
	.string "For instance, it would be easier\n"
	.string "to catch if it were asleep or\l"
	.string "paralyzed.$"

Pokedude_Text_CantDoubleUpOnStatus::
	.string "This will make the POKéMON a lot\n"
	.string "easier to catch!\p"
	.string "Oh, yes. If you paralyze a\n"
	.string "POKéMON, you can't make it fall\l"
	.string "asleep on top of paralysis.\p"
	.string "In other words, you can't double\n"
	.string "up status problems, okay?$"

Pokedude_Text_LetMeThrowBall::
	.string "Okay!\n"
	.string "Let me throw my POKé BALL!$"

Pokedude_Text_PickBestKindOfBall::
	.string "Before you throw a POKé BALL,\n"
	.string "consider the condition and the\l"
	.string "type of POKéMON, and pick the kind\l"
	.string "of BALL that would work best.$"
