QuestLog_Text_PreviouslyOnYourQuest:: @ 841A155
	.string "Previously on your quest…$"

QuestLog_Text_SwitchMon1WithMon2:: @ 841A16F
	.string "{PLAYER} switched the POKéMON\n"
	.string "{STR_VAR_1} with {STR_VAR_2}.$"

QuestLog_Text_SwappedHeldItemsOnMon:: @ 841A193
	.string "Took the item {STR_VAR_2} from\n"
	.string "{STR_VAR_1} and gave it the item\n"
	.string "{STR_VAR_3} to hold.$"

QuestLog_Text_TookHeldItemFromMon:: @ 841A1CD
	.string "Took the item {STR_VAR_2} from\n"
	.string "{STR_VAR_1}.$"

QuestLog_Text_UsedItemOnMonAtThisLocation:: @ 841A1E7
	.string "Used the item {STR_VAR_1} on {STR_VAR_2}\n"
	.string "at this location.$"

QuestLog_Text_UsedTheItem:: @ 841A210
	.string "{PLAYER} used the\n"
	.string "{STR_VAR_1}.$"

QuestLog_Text_UsedTheKeyItem:: @ 841A220
	.string "Used the item {STR_VAR_1}, which was\n"
	.string "in the KEY ITEMS POCKET.$"

QuestLog_Text_MonLearnedMoveFromTM:: @ 841A255
	.string "{STR_VAR_1} learned the move\n"
	.string "{STR_VAR_2} from a TM.$"

QuestLog_Text_MonReplacedMoveWithTM:: @ 841A277
	.string "{STR_VAR_1} learned the move\n"
	.string "{STR_VAR_2} from a TM and forgot\n"
	.string "the move {STR_VAR_3}.$"

QuestLog_Text_MonsWereFullyRestoredAtCenter:: @ 841A2B0
	.string "POKéMON were fully restored\n"
	.string "at a POKéMON CENTER.$"

QuestLog_Text_PlayerBattledChampionRival:: @ 841A2E1
	.string "{DYNAMIC 0x00} had a marvelous battle\n"
	.string "with the CHAMPION, {DYNAMIC 0x01}.$"

QuestLog_Text_PlayerSentOutMon1RivalSentOutMon2:: @ 841A312
	.string "In the end, {DYNAMIC 0x00} sent out {DYNAMIC 0x01}\n"
	.string "while {DYNAMIC 0x02} countered with\n"
	.string "{DYNAMIC 0x03}.$"

QuestLog_Text_WonTheMatchAsAResult:: @ 841A349
	.string "And, as a result of battling with every\n"
	.string "bit of power, {DYNAMIC 0x00} won\n"
	.string "the match.$"

QuestLog_Text_StoredItemInPC:: @ 841A391
	.string "Removed the item {STR_VAR_1} from\n"
	.string "the BAG's ITEMS POCKET and stored it\n"
	.string "on the PC.$"

QuestLog_Text_WithdrewItemFromPC:: @ 841A3DA
	.string "{PLAYER} withdrew the item {STR_VAR_1}\n"
	.string "from the PC.$"

QuestLog_Text_TradedMon1ForPersonsMon2:: @ 841A3FF
	.string "Traded {STR_VAR_3} in exchange for\n"
	.string "{STR_VAR_1}'s {STR_VAR_2}.$"

QuestLog_Text_SingleBattleWithPersonResultedInOutcome:: @ 841A422
	.string "Took on {DYNAMIC 0x00} in a SINGLE BATTLE.\n"
	.string "It was a hotly contested match that\n"
	.string "resulted in a {DYNAMIC 0x01}.$"

QuestLog_Text_DoubleBattleWithPersonResultedInOutcome:: @ 841A477
	.string "Took on {DYNAMIC 0x00} in a DOUBLE BATTLE.\n"
	.string "It was an extended match that resulted\n"
	.string "in a {DYNAMIC 0x01}.$"

QuestLog_Text_MultiBattleWithPeopleResultedInOutcome:: @ 841A4C6
	.string "{DYNAMIC 0x00} and {DYNAMIC 0x01} took on\n"
	.string "{DYNAMIC 0x02} and {DYNAMIC 0x03} in a\n"
	.string "MULTI BATTLE and got a {DYNAMIC 0x04}.$"

QuestLog_Text_Win::
	.string "win$"

QuestLog_Text_Loss::
	.string "loss$"

QuestLog_Text_MingledInUnionRoom:: @ 841A50B
	.string "Mingled with other TRAINERS in\n"
	.string "the UNION ROOM.$"

QuestLog_Text_DepartedPlaceInTownForNextDestination:: @ 841A53A
	.string "Departed {STR_VAR_2}\n"
	.string "in {STR_VAR_1} for the next\n"
	.string "destination.$"

QuestLog_Text_SwitchedMonsBetweenBoxes:: @ 841A566
	.string "After consideration, switched\n"
	.string "{DYNAMIC 0x01} in {DYNAMIC 0x00} with\n"
	.string "{DYNAMIC 0x03} in {DYNAMIC 0x02}.$"

QuestLog_Text_MovedMonToNewBox:: @ 841A59C
	.string "After deep thought, switched\n"
	.string "{DYNAMIC 0x01} in BOX “{DYNAMIC 0x00}” to\n"
	.string "the BOX “{DYNAMIC 0x02}.”$"

QuestLog_Text_SwitchedMonsWithinBox:: @ 841A5D9
	.string "Switched around {DYNAMIC 0x01} and\n"
	.string "{DYNAMIC 0x02} in {DYNAMIC 0x00}.$"

QuestLog_Text_MovedMonWithinBox:: @ 841A5FA
	.string "Moved {DYNAMIC 0x01} in {DYNAMIC 0x00}.$"

QuestLog_Text_SwitchedPartyMonForPCMon:: @ 841A60A
	.string "Switched {DYNAMIC 0x01} in {DYNAMIC 0x00}\n"
	.string "with {DYNAMIC 0x02} in the party.$"

QuestLog_Text_WithdrewMonFromPC:: @ 841A632
	.string "Added {DYNAMIC 0x01} in {DYNAMIC 0x00}\n"
	.string "to the party.$"

QuestLog_Text_DepositedMonInPC:: @ 841A64F
	.string "Moved {DYNAMIC 0x00} from the party\n"
	.string "to {DYNAMIC 0x01}.$"

QuestLog_Text_SwitchedMultipleMons:: @ 841A66E
	.string "Moved a group of POKéMON in\n"
	.string "{DYNAMIC 0x00} to {DYNAMIC 0x01}.$"

QuestLog_Text_ADifferentSpot:: @ 841A694
	.string "a different spot$"

QuestLog_Text_GaveMonHeldItemFromPC:: @ 841A6A5
	.string "Removed the item {STR_VAR_1} from\n"
	.string "{PLAYER}'s PC and gave it to {STR_VAR_2}\n"
	.string "to hold.$"

QuestLog_Text_SwappedHeldItemFromPC:: @ 841A6E1
	.string "Removed the item {STR_VAR_1} from\n"
	.string "a PC, gave it to {STR_VAR_2}, and put\n"
	.string "the {STR_VAR_3} it held in the BAG.$"

QuestLog_Text_ChattedWithManyTrainers:: @ 841A732
	.string "Chatted with many TRAINERS.$"

QuestLog_Text_Handily::
	.string "handily$"

QuestLog_Text_Tenaciously::
	.string "tenaciously$"

QuestLog_Text_Somehow::
	.string "somehow$"

QuestLog_Text_TradedMon1ForTrainersMon2:: @ 841A76A
	.string "Met and traded with {STR_VAR_1}.\n"
	.string "Obtained the TRAINER's {STR_VAR_2} in\n"
	.string "exchange for {STR_VAR_3}.$"

QuestLog_Text_BattledTrainerEndedInOutcome:: @ 841A7B0
	.string "Met and battled {STR_VAR_1}.\n"
	.string "The match ended in a {STR_VAR_2}.$"

QuestLog_Text_BoughtItem:: @ 841A7DD
	.string "Went to the POKéMON MART in\n"
	.string "{DYNAMIC 0x00} and bought one \n"
	.string "{DYNAMIC 0x01}.$"

QuestLog_Text_BoughtItemsIncludingItem:: @ 841A810
	.string "Went to the POKéMON MART in\n"
	.string "{DYNAMIC 0x00} and spent ¥{DYNAMIC 0x02} for\n"
	.string "items including {DYNAMIC 0x01}(s).$"

QuestLog_Text_SoldNumOfItem:: @ 841A858
	.string "{DYNAMIC 0x00} went to the POKéMON MART in\n"
	.string "{DYNAMIC 0x01} and sold {DYNAMIC 0x03} of\n"
	.string "the item {DYNAMIC 0x02}.$"

QuestLog_Text_SoldItemsIncludingItem:: @ 841A896
	.string "Sold items including {DYNAMIC 0x01} at\n"
	.string "the POKéMON MART in {DYNAMIC 0x00},\n"
	.string "worth ¥{DYNAMIC 0x02}.$"

QuestLog_Text_JustOne:: @ 841A8D4
	.string "just one$"

QuestLog_Text_Num:: @ 841A8DD
	.string "{DYNAMIC 0x04}$"

QuestLog_Text_UsedSoftboiled:: @ 841A8E0
	.string "{STR_VAR_1} shared its HP using the move\n"
	.string "SOFTBOILED.$"

QuestLog_Text_UsedMilkDrink:: @ 841A90C
	.string "{STR_VAR_1} shared its HP using the move\n"
	.string "MILK DRINK.$"

QuestLog_Text_MonLearnedMoveFromHM:: @ 841A938
	.string "{STR_VAR_1} securely learned the move\n"
	.string "{STR_VAR_2} using an HM.$"

QuestLog_Text_MonReplacedMoveWithHM:: @ 841A965
	.string "{STR_VAR_1} securely learned the move\n"
	.string "{STR_VAR_2} using an HM and forgot\n"
	.string "the move {STR_VAR_3}.$"

QuestLog_Text_DefeatedWildMon:: @ 841A9A9
	.string "{DYNAMIC 0x05} managed to defeat the POKéMON\n"
	.string "{DYNAMIC 0x01} in {DYNAMIC 0x00}.$"

QuestLog_Text_DefeatedWildMons:: @ 841A9D4
	.string "Defeated {DYNAMIC 0x02} wild POKéMON including\n"
	.string "{DYNAMIC 0x01} in {DYNAMIC 0x00}.$"

QuestLog_Text_CaughtWildMon:: @ 841AA01
	.string "{DYNAMIC 0x05} managed to catch the POKéMON\n"
	.string "{DYNAMIC 0x03} in {DYNAMIC 0x00}.$"

QuestLog_Text_CaughtWildMons:: @ 841AA2B
	.string "Threw POKé BALLS in a frenzy, catching\n"
	.string "{DYNAMIC 0x04} POKéMON including {DYNAMIC 0x03} here\n"
	.string "in {DYNAMIC 0x00}.$"

QuestLog_Text_DefeatedWildMonAndCaughtWildMon:: @ 841AA76
	.string "{DYNAMIC 0x05} defeated the POKéMON\n"
	.string "{DYNAMIC 0x01} and caught one {DYNAMIC 0x03}\n"
	.string "in {DYNAMIC 0x00}.$"

QuestLog_Text_DefeatedWildMonAndCaughtWildMons:: @ 841AAAA
	.string "Defeated the POKéMON {DYNAMIC 0x01}\n"
	.string "and caught {DYNAMIC 0x04} POKéMON including\n"
	.string "{DYNAMIC 0x03} in {DYNAMIC 0x00}.$"

QuestLog_Text_DefeatedWildMonsAndCaughtWildMon:: @ 841AAEC
	.string "{DYNAMIC 0x05} defeated {DYNAMIC 0x02} POKéMON including\n"
	.string "{DYNAMIC 0x01} and caught one {DYNAMIC 0x03}\n"
	.string "in {DYNAMIC 0x00}.$"

QuestLog_Text_DefeatedWildMonsAndCaughtWildMons:: @ 841AB29
	.string "Defeated {DYNAMIC 0x02} POKéMON including\n"
	.string "{DYNAMIC 0x01} and caught {DYNAMIC 0x04} POKéMON\n"
	.string "including {DYNAMIC 0x03} in {DYNAMIC 0x00}.$"

QuestLog_Text_GaveMonHeldItem:: @ 841AB74
	.string "Made {STR_VAR_1} hold the item\n"
	.string "{STR_VAR_2}.$"

QuestLog_Text_GaveMonHeldItem2:: @ 841AB8E
	.string "{PLAYER} made {STR_VAR_1} hold the item\n"
	.string "{STR_VAR_2}.$"

QuestLog_Text_UsedCut:: @ 841ABAB
	.string "{STR_VAR_1} used the Hidden Move\n"
	.string "CUT here.$"

QuestLog_Text_UsedFly:: @ 841ABCD
	.string "{STR_VAR_1} used the Hidden Move\n"
	.string "FLY and flew to {STR_VAR_2}.$"

QuestLog_Text_UsedSurf:: @ 841ABF9
	.string "{STR_VAR_1} used the Hidden Move\n"
	.string "SURF and rode the waves.$"

QuestLog_Text_UsedStrength:: @ 841AC2A
	.string "{STR_VAR_1} used the Hidden Move\n"
	.string "STRENGTH here.$"

QuestLog_Text_UsedFlash:: @ 841AC51
	.string "{STR_VAR_1} used the Hidden Move\n"
	.string "FLASH and illuminated a pitch-black\n"
	.string "cave.$"

QuestLog_Text_UsedRockSmash:: @ 841AC93
	.string "{STR_VAR_1} used the Hidden Move\n"
	.string "ROCK SMASH here.$"

QuestLog_Text_UsedWaterfall:: @ 841ACBC
	.string "{STR_VAR_1} used the Hidden Move\n"
	.string "WATERFALL to scale a raging torrent.$"

@ Unused
QuestLog_Text_UsedDive:: @ 841ACF9
	.string "{STR_VAR_1}は　ふかい　ところを　めざし\n"
    .string "ひでんわざ\n"
    .string "ダイビングを　つかった！$"

QuestLog_Text_UsedDigInLocation:: @ 841AD1D
	.string "{STR_VAR_1} used DIG to escape from\n"
	.string "{STR_VAR_2}.$"

QuestLog_Text_UsedSweetScent:: @ 841AD3C
	.string "{STR_VAR_1} used SWEET SCENT to attract\n"
	.string "wild POKéMON.$"

QuestLog_Text_UsedTeleportToLocation:: @ 841AD69
	.string "{STR_VAR_1} used TELEPORT, transporting\n"
	.string "the party to {STR_VAR_2}'s\n"
	.string "{STR_VAR_3}.$"

QuestLog_Text_LeftTownsLocationForNextDestination:: @ 841AD9E
	.string "{PLAYER} left {STR_VAR_1}'s\n"
	.string "{STR_VAR_2} for the next\n"
	.string "destination.$"

QuestLog_Text_PlayedGamesAtGameCorner:: @ 841ADC8
	.string "Played a lot of games at the ROCKET\n"
	.string "GAME CORNER in {STR_VAR_1}.$"

QuestLog_Text_RestedAtHome:: @ 841ADFF
	.string "{PLAYER} rested comfortably at home.$"

QuestLog_Text_LeftOaksLab:: @ 841AE1E
	.string "{PLAYER} left PROF. OAK's POKéMON\n"
	.string "RESEARCH LAB.$"

QuestLog_Text_GymWasFullOfToughTrainers:: @ 841AE48
	.string "The GYM in {STR_VAR_1} was full of\n"
	.string "tough TRAINERS…\n"
	.string "Preparations had to be made.$"

QuestLog_Text_DepartedGym:: @ 841AE8F
	.string "Departed the GYM in {STR_VAR_1}.$"

QuestLog_Text_HadGreatTimeInSafariZone:: @ 841AEA7
	.string "{PLAYER} had a great time with POKéMON\n"
	.string "in the SAFARI ZONE.$"

QuestLog_Text_ManagedToGetOutOfLocation:: @ 841AEDC
	.string "Managed to get out of {STR_VAR_2}\n"
	.string "after wandering about.$"

QuestLog_Text_TookOnGymLeadersMonWithMonAndWon:: @ 841AF0C
	.string "Took on {DYNAMIC 0x00} GYM LEADER\n"
	.string "{DYNAMIC 0x01}'s {DYNAMIC 0x02} with {DYNAMIC 0x03}\n"
	.string "and won {DYNAMIC 0x04}!$"

QuestLog_Text_TookOnEliteFoursMonWithMonAndWon:: @ 841AF3E
	.string "Took on ELITE FOUR {DYNAMIC 0x00}'s\n"
	.string "{DYNAMIC 0x01} with {DYNAMIC 0x02} and\n"
	.string "won {DYNAMIC 0x03}!$"

QuestLog_Text_TookOnTrainersMonWithMonAndWon:: @ 841AF6D
	.string "In {DYNAMIC 0x00}, took on\n"
	.string "{DYNAMIC 0x01}'s {DYNAMIC 0x02} with {DYNAMIC 0x03}\n"
	.string "and won {DYNAMIC 0x04}!$"

QuestLog_Text_Coolly:: @ 841AF98
	.string "coolly$"

QuestLog_Text_Barely:: @ 841AF9F
	.string "barely$"

QuestLog_Text_UsedEscapeRope:: @ 841AFA6
	.string "{PLAYER} used an ESCAPE ROPE to get\n"
	.string "out from {STR_VAR_2}.$"

QuestLog_Text_Draw:: @ 841AFD1
	.string "draw$"

QuestLog_Text_DepartedTheLocationForNextDestination:: @ 841AFD6
	.string "Departed from the {STR_VAR_2}\n"
	.string "for the next destination.$"

QuestLog_Text_DepartedFromLocationToNextDestination:: @ 841B005
	.string "{PLAYER} departed from\n"
	.string "{STR_VAR_2} and made way\n"
	.string "to the next destination.$"

QuestLog_Text_ObtainedItemInLocation:: @ 841B03F
	.string "Here in {STR_VAR_1}, {PLAYER}\n"
	.string "obtained the item {STR_VAR_2}.$"

QuestLog_Text_ArrivedInLocation:: @ 841B064
	.string "Arrived in {STR_VAR_1}.$"

QuestLog_Text_SavedGameAtLocation:: @ 841B073
	.string "And {PLAYER} saved the game at this\n"
	.string "location: {STR_VAR_1}.$"

QuestLog_Text_Home:: @ 841B09F
	.string "HOME$"

QuestLog_Text_OakResearchLab:: @ 841B0A4
	.string "OAK RESEARCH LAB$"

QuestLog_Text_Gym:: @ 841B0B5
	.string "GYM$"

QuestLog_Text_PokemonLeagueGate:: @ 841B0B9
	.string "POKéMON LEAGUE GATE$"

QuestLog_Text_ViridianForest:: @ 841B0CD
	.string "VIRIDIAN FOREST$"

QuestLog_Text_PewterMuseumOfScience:: @ 841B0DD
	.string "PEWTER MUSEUM OF SCIENCE$"

QuestLog_Text_MtMoon:: @ 841B0F6
	.string "MT. MOON$"

QuestLog_Text_BikeShop:: @ 841B0FF
	.string "BIKE SHOP$"

QuestLog_Text_BillsHouse:: @ 841B109
	.string "BILL'S HOUSE$"

QuestLog_Text_DayCare:: @ 841B116
	.string "DAY CARE$"

QuestLog_Text_UndergroundPath:: @ 841B11F
	.string "UNDERGROUND PATH$"

QuestLog_Text_PokemonFanClub:: @ 841B130
	.string "POKéMON FAN CLUB$"

QuestLog_Text_SSAnne:: @ 841B141
	.string "S.S. ANNE$"

QuestLog_Text_DiglettsCave:: @ 841B14B
	.string "DIGLETT'S CAVE$"

QuestLog_Text_RockTunnel:: @ 841B15A
	.string "ROCK TUNNEL$"

QuestLog_Text_PowerPlant:: @ 841B166
	.string "POWER PLANT$"

QuestLog_Text_PokemonTower:: @ 841B172
	.string "POKéMON TOWER$"

QuestLog_Text_VolunteerHouse:: @ 841B180
	.string "VOLUNTEER HOUSE$"

QuestLog_Text_NameRatersHouse:: @ 841B190
	.string "NAME RATER'S HOUSE$"

QuestLog_Text_CeladonDeptStore:: @ 841B1A3
	.string "CELADON DEPT. STORE$"

QuestLog_Text_CeladonMansion:: @ 841B1B7
	.string "CELADON MANSION$"

QuestLog_Text_RocketGameCorner:: @ 841B1C7
	.string "ROCKET GAME CORNER$"

QuestLog_Text_Restaurant:: @ 841B1DA
	.string "RESTAURANT$"

QuestLog_Text_RocketHideout:: @ 841B1E5
	.string "ROCKET HIDEOUT$"

QuestLog_Text_SafariZone:: @ 841B1F4
	.string "SAFARI ZONE$"

QuestLog_Text_WardensHome:: @ 841B200
	.string "WARDEN'S HOME$"

QuestLog_Text_FightingDojo:: @ 841B20E
	.string "FIGHTING DOJO$"

QuestLog_Text_SilphCo:: @ 841B21C
	.string "SILPH CO.$"

QuestLog_Text_SeafoamIslands:: @ 841B226
	.string "SEAFOAM ISLANDS$"

QuestLog_Text_PokemonMansion:: @ 841B236
	.string "POKéMON MANSION$"

QuestLog_Text_PokemonResearchLab:: @ 841B246
	.string "POKéMON RESEARCH LAB$"

QuestLog_Text_VictoryRoad:: @ 841B25B
	.string "VICTORY ROAD$"

QuestLog_Text_PokemonLeague:: @ 841B268
	.string "POKéMON LEAGUE$"

QuestLog_Text_CeruleanCave:: @ 841B277
	.string "CERULEAN CAVE$"
