Text_OnlySkilledTrainersAllowedThrough:: @ 81A572A
	.string "Only truly skilled TRAINERS are\n"
	.string "allowed through.\p"
	.string "You don't have the {STR_VAR_1}\n"
	.string "yet!$"

Text_CantLetYouPass:: @ 81A5776
	.string "Rules are rules.\n"
	.string "I can't let you pass.$"

Text_OhThatsBadgeGoRightAhead:: @ 81A579D
	.string "Oh! That is the {STR_VAR_1}!\n"
	.string "Go right ahead.$"

Text_OnlyPassWithBadgeDontHaveYet:: @ 81A57C1
	.string "You can pass here only if you have\n"
	.string "the {STR_VAR_1}.\p"
	.string "You don't have the {STR_VAR_1}\n"
	.string "yet.\p"
	.string "You have to have it to get to\n"
	.string "the POKéMON LEAGUE.$"

Text_OnlyPassWithBadgeOhGoAhead:: @ 81A5839
	.string "You can pass here only if you have\n"
	.string "the {STR_VAR_1}.\p"
	.string "Oh! That is the {STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM}{MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "Okay, then.\n"
	.string "Please, go right ahead.$"
