gText_WouldYouLikeToSaveTheGame::
	.string "Would you like to save the game?$"

gText_AlreadySaveFile_WouldLikeToOverwrite::
	.string "There is already a saved file.\n"
	.string "Is it okay to overwrite it?$"

gText_SavingDontTurnOffThePower::
	.string "Saving…\n"
	.string "Don't Turn Off The Power.$"

gText_PlayerSavedTheGame::
	.string "{PLAYER} saved the game.$"

gText_SaveFailed2::
	.string "セーブに　しっぱい　しました‥$"

gText_DifferentGameFile::
	.string "Warning!\p"
	.string "There is a different game file that\n"
	.string "is already saved.\p"
	.string "If you save now, the other file's\n"
	.string "adventure, including items and\l"
	.string "Pokémon, will be entirely lost.\p"
	.string "Are you sure you want to save now\n"
	.string "and overwrite the other save file?$"
