gText_WouldYouLikeToSaveTheGame::
	.string "¿Quieres guardar la partida?$"

gText_AlreadySaveFile_WouldLikeToOverwrite::
	.string "Ya hay una partida guardada.\n"
	.string "¿Quieres sobrescribirla?$"

gText_SavingDontTurnOffThePower::
	.string "{SHADOW DYNAMIC_COLOR4}GUARDANDO...\n"
	.string "{COLOR RED}{SHADOW LIGHT_RED}NO APAGUES LA CONSOLA$"

gText_PlayerSavedTheGame::
	.string "{SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY} ha guardado la partida.$"

gText_SaveFailed2::
	.string "セーブに　しっぱい　しました‥$"

gText_DifferentGameFile::
	.string "{COLOR RED}{SHADOW LIGHT_RED}¡ADVERTENCIA!\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ya hay una partida guardada.\n"
	.string "Si guardas ahora, perderás los\n"
	.string "datos de la otra partida,\l"
	.string "incluyendo objetos y POKéMON.\p"
	.string "¿Quieres guardar ahora y\n"
	.string "sobrescribir la otra partida?$"