@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight:: @ 81B1C8B
	.string "Hmm…\n"
	.string "Is that right…$"

PalletTown_Text_OhLookLook:: @ 81B1C9F
	.string "Oh!\n"
	.string "Look, look!$"

PalletTown_Text_ReadItReadIt:: @ 81B1CAF
	.string "Read it, read it!$"

@ Used by sign
PalletTown_Text_PressStartToOpenMenu:: @ 81B1CC1
	.string "TRAINER TIPS\p"
	.string "Press START to open the MENU!$"

PalletTown_Text_SignsAreUsefulArentThey:: @ 81B1CEC
	.string "Signs are useful, aren't they?$"

PalletTown_Text_LookCopiedTrainerTipsSign:: @ 81B1D0B
	.string "Look, look!\p"
	.string "I copied what it said on one of\n"
	.string "those TRAINER TIPS signs!$"

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy:: @ 81B1D51
	.string "TRAINER TIPS!\p"
	.string "Press START to open the MENU!$"
