gUnknown_81C137C:: @ 81C137C
	.string "The battery isn't charged enough.\p"
	.string "No. of steps required to fully\n"
	.string "charge the battery: {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gUnknown_81C13D6:: @ 81C13D6
	.string "There are no TRAINERS within range\n"
	.string "who can battle…\p"
	.string "The VS SEEKER was turned off.{PAUSE_UNTIL_PRESS}$"

gUnknown_81C1429:: @ 81C1429
	.string "The other TRAINERS don't appear\n"
	.string "to be ready for battle.\p"
	.string "Let's wait till later.{PAUSE_UNTIL_PRESS}$"

Text_1C147A:: @ 81C147A
	.string "Hey!\n"
	.string "I saw you in VIRIDIAN FOREST!$"

Text_1C149D:: @ 81C149D
	.string "Hi! I like shorts!\n"
	.string "They're comfy and easy to wear!\p"
	.string "You should be wearing shorts, too!$"

Text_1C14F3:: @ 81C14F3
	.string "Excuse me!\n"
	.string "You keep looking at me, don't you?$"

Text_1C1521:: @ 81C1521
	.string "You're a TRAINER, aren't you?\n"
	.string "Let's get with it right away!$"

Text_1C155D:: @ 81C155D
	.string "That look you give me…\n"
	.string "It intrigues me so!$"

Text_1C1588:: @ 81C1588
	.string "Hey! What's wrong with you?\n"
	.string "You're still not wearing shorts!$"

Text_1C15C5:: @ 81C15C5
	.string "I'll battle you with the POKéMON\n"
	.string "I started raising.$"

Text_1C15F9:: @ 81C15F9
	.string "Eek!\n"
	.string "Did you push me?$"

Text_1C160F:: @ 81C160F
	.string "I always catch mushroom POKéMON\n"
	.string "on MT. MOON.$"

Text_1C163C:: @ 81C163C
	.string "Oh! You're that nosy kid who\n"
	.string "eavesdropped on us!$"

Text_1C166D:: @ 81C166D
	.string "Excuse me! Didn't I tell you that\n"
	.string "this is a private conversation?\p"
	.string "You shouldn't be listening in,\n"
	.string "you uncouth person!$"

Text_1C16E2:: @ 81C16E2
	.string "I'm trying to find something good\n"
	.string "that's not a BUG POKéMON, but…$"

Text_1C1723:: @ 81C1723
	.string "Huh?\n"
	.string "You want to go with me again?$"

Text_1C1746:: @ 81C1746
	.string "Me?\n"
	.string "Well, okay. I'll play this once.$"

Text_1C176B:: @ 81C176B
	.string "Hey, long time!\n"
	.string "Have you gotten better?$"

Text_1C1793:: @ 81C1793
	.string "You are good at POKéMON, but how\n"
	.string "is your chemistry grade?$"

Text_1C17CD:: @ 81C17CD
	.string "All right!\n"
	.string "Let's play another game!$"

Text_1C17F1:: @ 81C17F1
	.string "You need strategy to win at\n"
	.string "battling.\p"
	.string "Are you following my advice?$"

Text_1C1834:: @ 81C1834
	.string "I've collected many NIDORAN.\n"
	.string "I don't want them to evolve, but…$"

Text_1C1873:: @ 81C1873
	.string "School is fun, but I still think\n"
	.string "POKéMON are fun, too.$"

Text_1C18AA:: @ 81C18AA
	.string "MEOWTH and PERSIAN are so cute,\n"
	.string "meow, meow, meow!$"

Text_1C18DC:: @ 81C18DC
	.string "We may look silly standing here\n"
	.string "like this, but I can still battle.$"

Text_1C191F:: @ 81C191F
	.string "I'm a rambling, gaming dude!\n"
	.string "I'm on a winning streak!$"

Text_1C1955:: @ 81C1955
	.string "What's a cute, round, and fluffy\n"
	.string "POKéMON?\p"
	.string "You already know, don't you?$"

Text_1C199C:: @ 81C199C
	.string "My bike's still acting up, man.$"

Text_1C19BC:: @ 81C19BC
	.string "Okay, kid!\n"
	.string "Don't expect mercy this time!$"

Text_1C19E5:: @ 81C19E5
	.string "ELI: Our twin power became even\n"
	.string "better!$"

Text_1C1A0D:: @ 81C1A0D
	.string "ANNE: Our twin power powered up!$"

Text_1C1A2E:: @ 81C1A2E
	.string "We're to battle again?\n"
	.string "This time, you're mine!$"

Text_1C1A5D:: @ 81C1A5D
	.string "I haven't forgotten you were with\n"
	.string "those good-looking POKéMON.$"

Text_1C1A9B:: @ 81C1A9B
	.string "I'm taking ROCK TUNNEL to go to\n"
	.string "LAVENDER…\p"
	.string "But I keep getting stopped by\n"
	.string "everyone along the way…$"

Text_1C1AFB:: @ 81C1AFB
	.string "Don't you dare patronize me today!\n"
	.string "We're playing for keeps!$"

Text_1C1B37:: @ 81C1B37
	.string "Bwahaha!\n"
	.string "Great! I was bored again, eh!$"

Text_1C1B5E:: @ 81C1B5E
	.string "Hahaha!\n"
	.string "A little toughie, as always!$"

Text_1C1B83:: @ 81C1B83
	.string "I got up early every day to train\n"
	.string "my POKéMON from cocoons!$"

Text_1C1BBE:: @ 81C1BBE
	.string "Hahahaha!\n"
	.string "I'll win this time!$"

Text_1C1BDC:: @ 81C1BDC
	.string "Go win, my super BUG POKéMON!$"

Route10_Text_MarkRematchIntro:: @ 81C1BFA
	.string "Wow, you came here again?\n"
	.string "Maybe you're a POKéMANIAC, too?\l"
	.string "Want to see my collection?$"

Route10_Text_ClarkRematchIntro:: @ 81C1C4F
	.string "Ha-hahah-ah-ha!\n"
	.string "I can't stop sneezing!$"

Route10_Text_HermanRematchIntro:: @ 81C1C76
	.string "Hi, kid!\n"
	.string "Did I show you my POKéMON?$"

Route10_Text_HeidiRematchIntro:: @ 81C1C9A
	.string "I went out to a POKéMON GYM again.\p"
	.string "…But I lost as usual.$"

Route10_Text_TrentRematchIntro:: @ 81C1CD3
	.string "Ah!\n"
	.string "This mountain air is delicious!\l"
	.string "It's so good, I can't leave!$"

Route10_Text_CarolRematchIntro:: @ 81C1D14
	.string "My head is starting to spin.\n"
	.string "I've been hiking for too long…$"

Route11_Text_HugoRematchIntro:: @ 81C1D50
	.string "Win, lose, or draw!\n"
	.string "Now for our rematch!$"

Route11_Text_JasperRematchIntro:: @ 81C1D79
	.string "Competing is the ultimate thrill.\n"
	.string "I still can't get enough!$"

Route11_Text_EddieRematchIntro:: @ 81C1DB5
	.string "You know, right?\n"
	.string "Let's go, but don't cheat!$"

Route11_Text_BraxtonRematchIntro:: @ 81C1DE1
	.string "Hi, there!\p"
	.string "But be careful!\n"
	.string "I'm still laying down some cables!$"

Route11_Text_DillonRematchIntro:: @ 81C1E1F
	.string "I became a TRAINER a while ago.\n"
	.string "But, I think I can win.$"

Route11_Text_DirkRematchIntro:: @ 81C1E57
	.string "Fwahaha!\n"
	.string "I have never lost!\p"
	.string "…And if I did, I've forgotten all\n"
	.string "about it!$"

Route11_Text_DarianRematchIntro:: @ 81C1E9F
	.string "I have never won before…\p"
	.string "Perhaps I am destined to remain\n"
	.string "that way…$"

Route11_Text_YasuRematchIntro:: @ 81C1EE2
	.string "I'm the best in my class.\n"
	.string "I train every morning and night!$"

Route11_Text_BernieRematchIntro:: @ 81C1F1D
	.string "Keep your eyes out for live wires!$"

Route11_Text_DaveRematchIntro:: @ 81C1F40
	.string "I raised my POKéMON carefully.\n"
	.string "They should be ready by now.\l"
	.string "This time, they should win, too.$"

Route12_Text_NedRematchIntro:: @ 81C1F9D
	.string "Yeah!\n"
	.string "I got a bite, here!\l"
	.string "Th-this might be the real thing!$"

Route12_Text_ChipRematchIntro:: @ 81C1FD8
	.string "You're finally here.\n"
	.string "Fishing is a waiting game.$"

Route12_Text_JustinRematchIntro:: @ 81C2008
	.string "Still can't find a MOON STONE…\n"
	.string "Have you found one?$"

Route12_Text_LucaRematchIntro:: @ 81C203B
	.string "Electricity has always been my\n"
	.string "specialty.\p"
	.string "I don't know a thing about POKéMON\n"
	.string "of the sea, though.$"

Route12_Text_HankRematchIntro:: @ 81C209C
	.string "The FISHING FOOL vs. POKéMON KID!\n"
	.string "Another round, fight!$"

Route12_Text_ElliotRematchIntro:: @ 81C20D4
	.string "I love fishing, don't get me wrong.\n"
	.string "But, I wish I had more work…\l"
	.string "…It's hard to give up fishing!$"

Route12_Text_AndrewRematchIntro:: @ 81C2134
	.string "What's catching?\p"
	.string "You'll never know unless you beat\n"
	.string "me!$"

Route12_Text_JesRematchIntro:: @ 81C216B
	.string "JES: I'll win here today and\n"
	.string "propose to my GIA.$"

Route12_Text_GiaRematchIntro:: @ 81C219B
	.string "GIA: Hey, JES…\n"
	.string "I've been waiting a long time now.\p"
	.string "If we win today, I'll marry you!$"

Route13_Text_SebastianRematchIntro:: @ 81C21EE
	.string "My bird POKéMON remember you!$"

Route13_Text_SusieRematchIntro:: @ 81C220C
	.string "I want to be the best TRAINER \n"
	.string "while I'm a kid!$"

Route13_Text_ValerieRematchIntro:: @ 81C223C
	.string "Wow!\n"
	.string "You got more cool BADGES!$"

Route13_Text_GwenRematchIntro:: @ 81C225B
	.string "My cutely grown POKéMON wish to\n"
	.string "become reacquainted with you.$"

Route13_Text_AlmaRematchIntro:: @ 81C2299
	.string "I cleaned out my savings and\n"
	.string "bought more CARBOS.$"

Route13_Text_PerryRematchIntro:: @ 81C22CA
	.string "I'm not going to lose this time.\n"
	.string "The wind's blowing my way!$"

Route13_Text_LolaRematchIntro:: @ 81C2306
	.string "Oh, you're back?\p"
	.string "Sure, I'll play again with you,\n"
	.string "sweetie.$"

Route13_Text_SheilaRematchIntro:: @ 81C2340
	.string "Can't you forget that you battled\n"
	.string "with me?$"

Route13_Text_JaredRematchIntro:: @ 81C236B
	.string "What're you starin' at?$"

Route13_Text_RobertRematchIntro:: @ 81C2383
	.string "I always go with bird POKéMON.\n"
	.string "I've dedicated myself to them.$"

Route14_Text_CarterRematchIntro:: @ 81C23C1
	.string "I used TMs to teach good moves\n"
	.string "to my POKéMON.$"

Route14_Text_MitchRematchIntro:: @ 81C23EF
	.string "My bird POKéMON should be ready\n"
	.string "for battle this time.$"

Route14_Text_BeckRematchIntro:: @ 81C2425
	.string "Are you using TMs on POKéMON?\n"
	.string "Just holding them is useless.$"

Route14_Text_MarlonRematchIntro:: @ 81C2461
	.string "Have you taught your bird POKéMON\n"
	.string "how to FLY?\p"
	.string "You'll be able to soar with it into\n"
	.string "the sky! Give it a try.$"

Route14_Text_DonaldRematchIntro:: @ 81C24CB
	.string "The legend of the winged mirages…\n"
	.string "You've heard it, right?$"

Route14_Text_BennyRematchIntro:: @ 81C2505
	.string "I'm really not into it, but okay.\n"
	.string "Let's go!$"

Route14_Text_LukasRematchIntro:: @ 81C2531
	.string "Hey!\n"
	.string "I remember you!\p"
	.string "C'mon, c'mon.\n"
	.string "Let's go, let's go, let's go!$"

Route14_Text_IsaacRematchIntro:: @ 81C2572
	.string "You're here again, huh?\n"
	.string "Shut up and battle.$"

Route14_Text_GeraldRematchIntro:: @ 81C259E
	.string "We've been riding here because of\n"
	.string "the wide-open spaces.$"

Route14_Text_MalikRematchIntro:: @ 81C25D6
	.string "POKéMON battle, right?\n"
	.string "Cool! Rumble!$"

Route14_Text_KiriRematchIntro:: @ 81C25FB
	.string "KIRI: JAN, I hope we win today.$"

Route14_Text_JanRematchIntro:: @ 81C261B
	.string "JAN: KIRI, here we go!\n"
	.string "Let's win for sure this time!$"

Text_1C2650:: @ 81C2650
	.string "I'm going to keep battling with the\n"
	.string "POKéMON I got in trades.$"

Text_1C268D:: @ 81C268D
	.string "You look gentle, so I think I can\n"
	.string "beat you.\p"
	.string "I'll give it one more go!$"

Text_1C26D3:: @ 81C26D3
	.string "When I whistle, bird POKéMON\n"
	.string "gather around.\p"
	.string "They're amazingly cute!$"

Text_1C2717:: @ 81C2717
	.string "Hmm? My birds are shivering!\n"
	.string "Wait, aren't you that TRAINER…$"

Text_1C2753:: @ 81C2753
	.string "Oh, you're a little cutie!\n"
	.string "So like a darling POKéMON!\l"
	.string "I remember you now!$"

Text_1C279D:: @ 81C279D
	.string "I raise POKéMON for protection\n"
	.string "because I live alone.\p"
	.string "That hasn't changed.$"

Text_1C27E7:: @ 81C27E7
	.string "Hey, kid! C'mon!\n"
	.string "I got these off some loser!$"

Text_1C2814:: @ 81C2814
	.string "Fork over all your cash when you\n"
	.string "lose to me, kid!$"

Text_1C2846:: @ 81C2846
	.string "What's cool and happening?\n"
	.string "Trading POKéMON, of course.$"

Text_1C287D:: @ 81C287D
	.string "Want to play with my POKéMON\n"
	.string "again?$"

Text_1C28A1:: @ 81C28A1
	.string "MYA: Hi, we keep meeting,\n"
	.string "don't we?\p"
	.string "Help me train my little brother\n"
	.string "again?$"

Text_1C28EC:: @ 81C28EC
	.string "RON: My sister's gotten more\n"
	.string "powerful…$"

Text_1C2913:: @ 81C2913
	.string "What do you want?$"

Text_1C2925:: @ 81C2925
	.string "Nice BIKE!\n"
	.string "Hand it over quick!$"

Text_1C2944:: @ 81C2944
	.string "Come out and play, little mouse.\n"
	.string "I'll treat you right!$"

Text_1C297B:: @ 81C297B
	.string "Hey, wait a second!\n"
	.string "Don't call me and then run away!$"

Text_1C29B0:: @ 81C29B0
	.string "I'm feeling hungry and mean!\n"
	.string "I really need a punching bag!$"

Text_1C29EB:: @ 81C29EB
	.string "Hey, there!\n"
	.string "We'll have ourselves a good time!$"

Text_1C2A19:: @ 81C2A19
	.string "JED: Are you here to see our\n"
	.string "love, which knows no bounds?$"

Text_1C2A53:: @ 81C2A53
	.string "LEA: Sometimes, the intensity of\n"
	.string "our love scares me.$"

Text_1C2A88:: @ 81C2A88
	.string "I told you, there's no getting rich\n"
	.string "quick in battling kids.$"

Text_1C2AC4:: @ 81C2AC4
	.string "I'm mighty proud of my bod, kiddo.\n"
	.string "Come on!$"

Text_1C2AF0:: @ 81C2AF0
	.string "You out for a stroll?$"

Text_1C2B06:: @ 81C2B06
	.string "We're BIKERS!\n"
	.string "We rule the roads, man!$"

Text_1C2B2C:: @ 81C2B2C
	.string "VOLTORB's going to seriously\n"
	.string "electrify you today!$"

Text_1C2B5E:: @ 81C2B5E
	.string "I leveled up my POKéMON, but it\n"
	.string "absolutely won't evolve. Why?$"

Text_1C2B9C:: @ 81C2B9C
	.string "Gaah! I really need to exercise\n"
	.string "and seriously trim some flab!$"

Text_1C2BDA:: @ 81C2BDA
	.string "Be a rebel!$"

Text_1C2BE6:: @ 81C2BE6
	.string "Yep, that's a nice BIKE!\n"
	.string "How's it handle?$"

Text_1C2C10:: @ 81C2C10
	.string "Get lost, kid!\n"
	.string "I'm bushed!$"

Text_1C2C2B:: @ 81C2C2B
	.string "I've been checking every grassy\n"
	.string "area for new POKéMON.\p"
	.string "But it's not always easy…$"

Text_1C2C7B:: @ 81C2C7B
	.string "Koorukukukoo!\n"
	.string "Is my birdcall getting better?$"

Text_1C2CA8:: @ 81C2CA8
	.string "I warned you before, this is my\n"
	.string "turf!\p"
	.string "I don't want you coming around.$"

Text_1C2CEE:: @ 81C2CEE
	.string "I'm almost warmed up to go\n"
	.string "out for a swim.$"

Text_1C2D19:: @ 81C2D19
	.string "Wait! Slow down!\n"
	.string "What if you have a heart attack?$"

Text_1C2D4B:: @ 81C2D4B
	.string "I love swimming!\n"
	.string "I guess you're the surfing type.$"

Text_1C2D7D:: @ 81C2D7D
	.string "What's beyond the horizon?\n"
	.string "Have you seen?$"

Text_1C2DA7:: @ 81C2DA7
	.string "I tried diving for POKéMON again,\n"
	.string "but it was a no-go like before.$"

Text_1C2DE9:: @ 81C2DE9
	.string "I look at the sea to forget all\n"
	.string "the bad things that happened.\p"
	.string "…Like losing to you the last time!$"

Text_1C2E4A:: @ 81C2E4A
	.string "You always get to ride your\n"
	.string "POKéMON…\p"
	.string "It looks so relaxing.\n"
	.string "Can I have it if I win?$"

Text_1C2E9D:: @ 81C2E9D
	.string "Swimming's great!\n"
	.string "Sunburns aren't!$"

Text_1C2EC0:: @ 81C2EC0
	.string "These waters are treacherous!\n"
	.string "You shouldn't come back here!$"

Text_1C2EFC:: @ 81C2EFC
	.string "I swam here with my friends…\n"
	.string "I'm tired…\l"
	.string "Must we really battle again?$"

Text_1C2F41:: @ 81C2F41
	.string "LIA: You know my brother just\n"
	.string "became a TRAINER, right?\p"
	.string "I want to make him better, so I\n"
	.string "need your help again.$"

Text_1C2FAE:: @ 81C2FAE
	.string "LUC: My big sis taught me all\n"
	.string "about POKéMON.\p"
	.string "I wonder if I'm better?$"

Text_1C2FF3:: @ 81C2FF3
	.string "The water is shallow here.\n"
	.string "There are many people swimming.$"

Text_1C302E:: @ 81C302E
	.string "Are you jealous that I'm\n"
	.string "vacationing on SEAFOAM?$"

Text_1C305F:: @ 81C305F
	.string "I love floating with the fishes\n"
	.string "here among the waves.$"

Text_1C3095:: @ 81C3095
	.string "Were you on vacation, too?$"

Text_1C30B0:: @ 81C30B0
	.string "Check out my physique!\p"
	.string "It's even more buff than ever\n"
	.string "before!$"

Text_1C30ED:: @ 81C30ED
	.string "Why are you riding a POKéMON?\n"
	.string "Haven't you learned to swim yet?$"

Text_1C312C:: @ 81C312C
	.string "I rode my bird POKéMON here.$"

Text_1C3149:: @ 81C3149
	.string "My boyfriend gave me big pearls.\n"
	.string "And, they've grown bigger!$"

Text_1C3185:: @ 81C3185
	.string "I swam here from CINNABAR ISLAND.\n"
	.string "It wasn't easy, like I said.$"

Text_1C31C4:: @ 81C31C4
	.string "CINNABAR, in the west, has a LAB\n"
	.string "for POKéMON.\p"
	.string "My daddy works there.$"

Text_1C3208:: @ 81C3208
	.string "You want to know if the fish are\n"
	.string "biting?$"

Text_1C3231:: @ 81C3231
	.string "I got a big haul again!\n"
	.string "Wanna go for it once more?$"

Text_1C3264:: @ 81C3264
	.string "The sea cleanses my body and soul!$"

Text_1C3287:: @ 81C3287
	.string "きょうも　およぎに\n"
	.string "きちまったぜ$"

Text_1C3298:: @ 81C3298
	.string "I caught my POKéMON at sea.\n"
	.string "And that's where I train them.$"

Text_1C32D3:: @ 81C32D3
	.string "Right now, I'm in another triathlon\n"
	.string "meet!$"

Text_1C32FD:: @ 81C32FD
	.string "Ahh!\n"
	.string "Feel the sun and the wind!$"

Text_1C331D:: @ 81C331D
	.string "Hey, cut it out already.\n"
	.string "You always scare away the fish!$"

Text_1C3356:: @ 81C3356
	.string "Keep me company till I get a hit.$"

Text_1C3378:: @ 81C3378
	.string "LIL: Huh? A battle again?\n"
	.string "IAN, can't you do it alone?$"

Text_1C33AE:: @ 81C33AE
	.string "IAN: My sis is still a slob.\n"
	.string "Help me get her into shape!$"

Text_1C33E7:: @ 81C33E7
	.string "I won't lose while I'm here!$"

Text_1C3404:: @ 81C3404
	.string "Dad took me to a great party on\n"
	.string "the S.S. ANNE at VERMILION CITY.$"

Text_1C3445:: @ 81C3445
	.string "I'm a cool guy.\n"
	.string "I've got a girlfriend!\p"
	.string "I'll show her how cool I am for\n"
	.string "sure this time!$"

Text_1C349C:: @ 81C349C
	.string "Hi!\n"
	.string "My boyfriend is cool!\l"
	.string "My conditioning's good today!$"

Text_1C34D4:: @ 81C34D4
	.string "I had this feeling…\n"
	.string "I knew I had to battle you again!$"

Text_1C350A:: @ 81C350A
	.string "My friend has many cute POKéMON.\n"
	.string "I'm so jealous!$"

Text_1C353B:: @ 81C353B
	.string "I just trained up on MT. MOON,\n"
	.string "but I've still got gas in the tank!$"

Text_1C357E:: @ 81C357E
	.string "A POKéMANIAC lives on the cape.\n"
	.string "Have you seen his collection?$"

Text_1C35BC:: @ 81C35BC
	.string "You're going to see BILL again?\n"
	.string "First, we battle!$"

Text_1C35EE:: @ 81C35EE
	.string "I saw your feat from the grass!$"

Text_1C360E:: @ 81C360E
	.string "Okay!\n"
	.string "I'll stomp you!$"

Text_1C3624:: @ 81C3624
	.string "You always look so busy…\n"
	.string "Aren't you getting tired?$"

Text_1C3657:: @ 81C3657
	.string "You really must love coming to\n"
	.string "NUGGET BRIDGE.$"

Text_1C3685:: @ 81C3685
	.string "The time we battled…\p"
	.string "Even though I was the second in\n"
	.string "line, I was the best, wasn't I?$"

Text_1C36DA:: @ 81C36DA
	.string "People call this the NUGGET\n"
	.string "BRIDGE!\p"
	.string "You've already beaten us, so you're\n"
	.string "not allowed to take the challenge…\p"
	.string "…But, you're welcome to battle with\n"
	.string "us again.$"

Text_1C3773:: @ 81C3773
	.string "Lying back, rocked by the waves…\n"
	.string "I don't notice time slipping by…$"

Text_1C37B5:: @ 81C37B5
	.string "The weather's gorgeous!\n"
	.string "I'll try not to spoil it.$"

Text_1C37E7:: @ 81C37E7
	.string "My sunburn is starting to hurt…$"

Text_1C3807:: @ 81C3807
	.string "The fire bird's mountain casts\n"
	.string "a huge shadow…$"

Text_1C3835:: @ 81C3835
	.string "I have this strong feeling that\n"
	.string "I can win this time!$"

Text_1C386A:: @ 81C386A
	.string "Wait! Wait a second!\n"
	.string "I'm sure I've hooked a big one!$"

Text_1C389F:: @ 81C389F
	.string "You'll help me out with my\n"
	.string "training again?$"

Text_1C38CA:: @ 81C38CA
	.string "We haven't missed a single day of\n"
	.string "training yet!$"

Text_1C38FA:: @ 81C38FA
	.string "Every morning, before breakfast,\n"
	.string "I swim around this island…\l"
	.string "Three times!$"

Text_1C3943:: @ 81C3943
	.string "Dress appropriately for battle!\n"
	.string "Lose that frivolous outfit, I said!$"

Text_1C3987:: @ 81C3987
	.string "You know, everything tastes great\n"
	.string "when you're out in the wild.$"

Text_1C39C6:: @ 81C39C6
	.string "I ate too much again, so will you\n"
	.string "battle us for some exercise?$"

Text_1C3A05:: @ 81C3A05
	.string "KIA: My big brother and I make\n"
	.string "an awesome combination!\p"
	.string "We won't lose this time!$"

Text_1C3A55:: @ 81C3A55
	.string "MIK: Together with KIA, we're\n"
	.string "afraid of nothing!\p"
	.string "We'll prove it to you this time!$"

Text_1C3AA7:: @ 81C3AA7
	.string "Are we to battle again?$"

Text_1C3ABF:: @ 81C3ABF
	.string "From where have you come, and\n"
	.string "where are you bound?$"

Text_1C3AF2:: @ 81C3AF2
	.string "I want to swim without my float\n"
	.string "ring soon.$"

Text_1C3B1D:: @ 81C3B1D
	.string "Yay, yay!\n"
	.string "POKéMON!$"

Text_1C3B30:: @ 81C3B30
	.string "Oh, no, didn't I tell you already?\n"
	.string "Please, stay away from me!$"

Text_1C3B6E:: @ 81C3B6E
	.string "JOY: We've gotten stronger!\n"
	.string "Lots and lots!$"

Text_1C3B99:: @ 81C3B99
	.string "MEG: You can't beat us today!$"

Text_1C3BB7:: @ 81C3BB7
	.string "Oh, hello!\p"
	.string "Are you raising your POKéMON in a\n"
	.string "good environment?$"

Text_1C3BF6:: @ 81C3BF6
	.string "With these hands, I will create\n"
	.string "my victory today.$"

Text_1C3C28:: @ 81C3C28
	.string "Must I repeat myself?\n"
	.string "I'm trying to paint.\l"
	.string "Please keep out of my sight!$"

Text_1C3C70:: @ 81C3C70
	.string "I haven't made any progress…\n"
	.string "I still can't get the right angle…$"

Text_1C3CB0:: @ 81C3CB0
	.string "Oh, you will give me another\n"
	.string "opportunity to match wits with you?$"

Text_1C3CF1:: @ 81C3CF1
	.string "They're almost finished making the\n"
	.string "pool for my POKéMON.\p"
	.string "You must drop in for a visit.$"

Text_1C3D47:: @ 81C3D47
	.string "I'm a good runner.\n"
	.string "I've gotten even faster!$"

Text_1C3D73:: @ 81C3D73
	.string "I say, friend!\n"
	.string "Let us enjoy our time together!$"

Text_1C3DA2:: @ 81C3DA2
	.string "I'm the eldest of the BIRD\n"
	.string "BROTHERS. Remember me?\p"
	.string "That's right, I'm the one who loves\n"
	.string "birds for their beaks!$"

Text_1C3E0F:: @ 81C3E0F
	.string "I'm the middle kid of the BIRD\n"
	.string "BROTHERS.\p"
	.string "I'm the one that loves wings.\n"
	.string "Let's battle again!$"

Text_1C3E6A:: @ 81C3E6A
	.string "I'm the youngest of the BIRD\n"
	.string "BROTHERS.\p"
	.string "I love birds for their down.\n"
	.string "I didn't think I'd see you again!$"

Text_1C3ED0:: @ 81C3ED0
	.string "I'm still having no luck at all.\n"
	.string "A battle'd be a change of pace!$"

Text_1C3F11:: @ 81C3F11
	.string "Gasp… Gasp…\p"
	.string "I swam here from SIX ISLAND's port\n"
	.string "in one go again.$"

Text_1C3F51:: @ 81C3F51
	.string "You always come along while I'm\n"
	.string "swimming.$"

Text_1C3F7B:: @ 81C3F7B
	.string "AVA: Let's have another\n"
	.string "two-on-two marine battle today!$"

Text_1C3FB3:: @ 81C3FB3
	.string "GEB: My big sister and I are way\n"
	.string "tougher than before!$"

Text_1C3FE9:: @ 81C3FE9
	.string "…Huh?\p"
	.string "I envision my house, but TELEPORT\n"
	.string "always brings me here!$"

Text_1C4028:: @ 81C4028
	.string "Oh, hello.\n"
	.string "A pleasant breeze is blowing again.$"

Text_1C4057:: @ 81C4057
	.string "Hehehe, I'm practicing in secret\n"
	.string "again.$"

Text_1C407F:: @ 81C407F
	.string "What, you're sick of seeing\n"
	.string "SWIMMERS like me?\p"
	.string "Aww, don't be hatin'!\n"
	.string "Battle with me again.$"

Text_1C40D9:: @ 81C40D9
	.string "Sigh…\n"
	.string "My boyfriend's busy again…$"

Text_1C40FA:: @ 81C40FA
	.string "Come on, tell me, where are the\n"
	.string "mountains around these parts?$"

Text_1C4138:: @ 81C4138
	.string "MIU: Hello, POKéMON!\n"
	.string "It's time to play again!$"

Text_1C4166:: @ 81C4166
	.string "MIA: Hello, POKéMON!\n"
	.string "It's time to battle again!$"

Text_1C4196:: @ 81C4196
	.string "There appear to be many secrets\n"
	.string "still unsolved in this world.$"

Text_1C41D4:: @ 81C41D4
	.string "Hi, didn't we meet before?\n"
	.string "What compelled you to come back?$"

Text_1C4210:: @ 81C4210
	.string "It's been said that there are\n"
	.string "mysterious stones on this island.\p"
	.string "Have you discovered anything since\n"
	.string "we last met?$"

Text_1C4280:: @ 81C4280
	.string "A rematch with you, so high up!$"

Text_1C42A0:: @ 81C42A0
	.string "I'm pretty familiar with the land\n"
	.string "around these parts.$"

Text_1C42D6:: @ 81C42D6
	.string "I sensed your approach.$"

Text_1C42EE:: @ 81C42EE
	.string "Somewhere on this island, peculiar\n"
	.string "POKéMON are sleeping.$"

Text_1C4327:: @ 81C4327
	.string "Kyahaha!\p"
	.string "Coming back won't change a thing.\n"
	.string "I'll flick you away effortlessly!$"

Text_1C4374:: @ 81C4374
	.string "Howdy! You're a member of my\n"
	.string "fan club, isn't that right?$"

Text_1C43AD:: @ 81C43AD
	.string "This island is too spread out…\n"
	.string "Patrolling the place is a drag…$"

Text_1C43EC:: @ 81C43EC
	.string "I don't forgive people who abuse\n"
	.string "POKéMON!$"

Text_1C4416:: @ 81C4416
	.string "EVE: I'll team up with JON and\n"
	.string "battle together again.$"

Text_1C444C:: @ 81C444C
	.string "JON: When I'm with EVE, it feels\n"
	.string "like we could never lose, not ever.$"

Text_1C4491:: @ 81C4491
	.string "Let's have another battle.\n"
	.string "My conditioning's in top form!$"

Text_1C44CB:: @ 81C44CB
	.string "It doesn't matter if you happen to\n"
	.string "have the strongest POKéMON…\p"
	.string "It doesn't mean a thing if you don't\n"
	.string "know how to use them properly!$"

Text_1C454E:: @ 81C454E
	.string "I work to protect the environment.\n"
	.string "In turn, nature protects me!$"

Text_1C458E:: @ 81C458E
	.string "Every time we meet, you have those\n"
	.string "snazzy shoes on.$"

Text_1C45C2:: @ 81C45C2
	.string "You must have gotten tougher.\n"
	.string "Let me battle you, please!$"

Text_1C45FB:: @ 81C45FB
	.string "I was given the best possible\n"
	.string "education to become this strong.\p"
	.string "I won't lose this time.\n"
	.string "Absolutely not!$"

Text_1C4662:: @ 81C4662
	.string "LEX: My darling NYA, together\n"
	.string "we will win for certain!$"

Text_1C4699:: @ 81C4699
	.string "NYA: I won't drag down my mentor\n"
	.string "LEX! We're going to win!$"

SevenIsland_TanobyRuins_Text_BrandonRematchIntro:: @ 81C46D3
	.string "Have you discovered anything about\n"
	.string "this stone chamber?$"

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro:: @ 81C470A
	.string "A mystic POKéMON is said to sleep\n"
	.string "inside here.$"

SevenIsland_TanobyRuins_Text_EdnaRematchIntro:: @ 81C4739
	.string "My teacher is showing me how to\n"
	.string "paint some more.$"

SevenIsland_TanobyRuins_Text_CliffordRematchIntro:: @ 81C476A
	.string "Today, in addition to our lesson,\n"
	.string "we came to see the chamber again.$"
