CeladonCity_GameCorner_Text_TryPokemonPrinter:: @ 81B1D7D
	.string "It's a POKéMON PRINTER!\p"
	.string "It can put a print of your POKéMON\n"
	.string "on the back of your TRAINER CARD.\p"
	.string "It costs only ¥50.\n"
	.string "Would you like to try it?$"

CeladonCity_GameCorner_Text_DontHaveEnoughMoney:: @ 81B1E07
	.string "You don't have enough money.$"

CeladonCity_GameCorner_Text_ChoosePrintType:: @ 81B1E24
	.string "Please choose the print type.$"

CeladonCity_GameCorner_Text_BigSmileForPhoto:: @ 81B1E42
	.string "A big smile for the photo, please!\n"
	.string "Three… Two… One…\p"
	.string "Flash!$"

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard:: @ 81B1E7D
	.string "Your POKéMON print is ready!\n"
	.string "Check your TRAINER CARD.$"

FourIsland_House2_Text_WishICouldShowOffStickers:: @ 81B1EB3
	.string "Giggle…\n"
	.string "I collected a ton of STICKERS.\l"
	.string "I wish I could show them off…$"

FourIsland_House2_Text_GiveYouStickerIfYouBrag:: @ 81B1EF8
	.string "Oh, excellent!\n"
	.string "You've come to the right place!\p"
	.string "Look, look! See? See?\n"
	.string "These are my STICKERS!\l"
	.string "Look how many I got!\p"
	.string "I bet you want some.\n"
	.string "I bet you do!\p"
	.string "I'll give a STICKER if you can tell\n"
	.string "me something awesome about\l"
	.string "yourself.\p"
	.string "What will you brag about?$"

FourIsland_House2_Text_BragAboutSomethingForMe:: @ 81B1FEF
	.string "Brag about something for me.\n"
	.string "I'll give you a STICKER.$"

FourIsland_House2_Text_BragAboutWhatToday:: @ 81B2025
	.string "Oh, hi!\n"
	.string "Here comes the braggart.\p"
	.string "What are you going to brag about\n"
	.string "today?$"

FourIsland_House2_Text_WowHoFLowest:: @ 81B206E
	.string "Oh, wow, you made it into the\n"
	.string "HALL OF FAME.\p"
	.string "That's pretty good, yup!\n"
	.string "I'll give you one of these.$"

FourIsland_House2_Text_WowHoFLow:: @ 81B20CF
	.string "Oh, wow, you've entered the\n"
	.string "HALL OF FAME often!\p"
	.string "That's impressive, yup!\n"
	.string "I'll give you one of these.$"

FourIsland_House2_Text_WowHoFHigh:: @ 81B2133
	.string "Whoa! You've made it into the\n"
	.string "HALL OF FAME that often?\l"
	.string "That's seriously incredible, yup!\p"
	.string "You own the POKéMON LEAGUE!\n"
	.string "I'll give you one of these.$"

FourIsland_House2_Text_WowHoFHighest:: @ 81B21C4
	.string "No way! You've gone into the\n"
	.string "HALL OF FAME that many times?\p"
	.string "You're beyond incredible, yup!\n"
	.string "That's it, I have to give you this.$"

FourIsland_House2_Text_HoFStickerApplied:: @ 81B2242
	.string "The HALL OF FAME STICKER was\n"
	.string "applied to the TRAINER CARD.$"

FourIsland_House2_Text_ComeBackWithBetterStoryHoF:: @ 81B227C
	.string "Hmm…\p"
	.string "Come back with a better story next\n"
	.string "time, okay?$"

FourIsland_House2_Text_LivingLegendHoF:: @ 81B22B0
	.string "Oh, no, no can do.\p"
	.string "You're practically a living legend.\n"
	.string "I have no SITCKERS left to give.$"

FourIsland_House2_Text_WowEggsLowest:: @ 81B2308
	.string "Oh, wow, there are POKéMON EGGS?\n"
	.string "I didn't know that!\p"
	.string "That's pretty good, yup!\n"
	.string "I'll give you one of these.$"

FourIsland_House2_Text_WowEggsLow:: @ 81B2372
	.string "You've hatched that many EGGS?\n"
	.string "You really must like them!\p"
	.string "That's impressive, yup!\n"
	.string "I'll give you one of these.$"

FourIsland_House2_Text_WowEggsHigh:: @ 81B23E0
	.string "Whoa! You've hatched a whole\n"
	.string "bunch of EGGS!\p"
	.string "You're an EGG-hatching machine!\n"
	.string "I'll give you one of these.$"

FourIsland_House2_Text_WowEggsHighest:: @ 81B2448
	.string "Wh… You hatched that many EGGS?\p"
	.string "What's behind your love of EGGS?\n"
	.string "It's beyond incredible, yup!\p"
	.string "You're too awesome, I tell you.\n"
	.string "That's it, I have to give you this.$"

FourIsland_House2_Text_EggStickerApplied:: @ 81B24EA
	.string "The EGG STICKER was applied\n"
	.string "to the TRAINER CARD.$"

FourIsland_House2_Text_ComeBackWithBetterStoryEggs:: @ 81B251B
	.string "Hmm…\p"
	.string "Come back with a better story next\n"
	.string "time, okay?$"

FourIsland_House2_Text_LivingLegendEggs:: @ 81B254F
	.string "Oh, no, no can do.\p"
	.string "You're practically a living legend.\n"
	.string "I have no SITCKERS left to give.$"

FourIsland_House2_Text_WowLinkWinsLowest:: @ 81B25A7
	.string "Oh, wow, you've had success\n"
	.string "link battling?\p"
	.string "You're pretty strong, yup!\n"
	.string "I'll give you one of these.$"

FourIsland_House2_Text_WowLinkWinsLow:: @ 81B2609
	.string "You've beaten your friends a lot\n"
	.string "link battling, huh?\p"
	.string "You're impressively strong, yup!\n"
	.string "I'll give you one of these.$"

FourIsland_House2_Text_WowLinkWinsHigh:: @ 81B267B
	.string "Whoa! You've beaten your friends\n"
	.string "a frightful number of times.\p"
	.string "Have you lost friends over this?\n"
	.string "I'll give you one of these.$"

FourIsland_House2_Text_WowLinkWinsHighest:: @ 81B26F6
	.string "Wh… Wickedly whoa!\n"
	.string "You've won mind-blowingly often!\p"
	.string "It just knocks me out thinking\n"
	.string "about how tough you are.\p"
	.string "You're the stuff of nightmares!\n"
	.string "That's it, I have to give you this.$"

FourIsland_House2_Text_VictoryStickerApplied:: @ 81B27A6
	.string "The VICTORY STICKER was applied\n"
	.string "to the TRAINER CARD.$"

FourIsland_House2_Text_ComeBackWithBetterStoryLinkWins:: @ 81B27DB
	.string "Hmm…\p"
	.string "Come back with a better story next\n"
	.string "time, okay?$"

FourIsland_House2_Text_LivingLegendLinkWins:: @ 81B280F
	.string "Oh, no, no can do.\p"
	.string "You're practically a living legend.\n"
	.string "I have no SITCKERS left to give.$"
