Text_FirstShouldRestoreMonsHealth::
	.string "{COLOR DARK_GRAY}Primero, deberías devolverles\n"
	.string "la forma a tus {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}.$"

Text_MonsHealedShouldBuyPotions::
	.string "{COLOR DARK_GRAY}Tus {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} están de nuevo\n"
	.string "en forma.\p"
	.string "Ven a vernos cuando la energía\n"
	.string "de tus {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}, los {SHADOW DYNAMIC_COLOR4}PS{SHADOW LIGHT_GRAY}, estén\l"
	.string "bajos de nivel.\p"
	.string "Cuando vayas a hacer un largo\n"
	.string "viaje, conviene que compres\l"
	.string "{SHADOW DYNAMIC_COLOR4}POCIONES{SHADOW LIGHT_GRAY} en la {SHADOW DYNAMIC_COLOR4}TIENDA POKéMON{SHADOW LIGHT_GRAY}.\p"
	.string "¡Demuestra lo que vales!$"

Text_MonsHealed::
	.string "Your POKéMON have been healed\n"
	.string "to perfect health.\p"
	.string "We hope you excel!$"

Text_HadQuiteAnExperienceTakeRest::
	.string "{COLOR DARK_GRAY}¡Hola, cielo!\p"
	.string "¡Tienes cara de haber aprendido\n"
	.string "bastante!\p"
	.string "¡Descansa un poco, criatura!$"

Text_MomExplainHPGetPotions::
	.string "{COLOR DARK_GRAY}Muy bien, tú y tus {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} están \n"
	.string "en plena forma.\p"
	.string "El {SHADOW DYNAMIC_COLOR4}PROF. OAK{SHADOW LIGHT_GRAY} me ha contado que la\n"
	.string "energía de los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} se mide\n"
	.string "en {SHADOW DYNAMIC_COLOR4}PS{SHADOW LIGHT_GRAY}.\p"	
	.string "Si tus {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} pierden {SHADOW DYNAMIC_COLOR4}PS{SHADOW LIGHT_GRAY}, puedes\n"
	.string "recuperarlos en cualquier {SHADOW DYNAMIC_COLOR4}CENTRO\l"
	.string "POKéMON.{SHADOW LIGHT_GRAY}\p"
	.string "Para viajes largos, los {SHADOW DYNAMIC_COLOR4}ENTRENADORES{SHADOW LIGHT_GRAY}\n"
	.string "más espabilados compran unas\l"
	.string "cuantas {SHADOW DYNAMIC_COLOR4}POCIONES{SHADOW LIGHT_GRAY} en la\l"
	.string "{SHADOW DYNAMIC_COLOR4}TIENDA POKéMON{SHADOW LIGHT_GRAY}.\p"
	.string "¡Demuestra a todos quién eres!\n"
	.string "¡Cuídate mucho!$"

Text_WhitedOutLostMoney::
	.string "{PLAYER} is out of usable\n"
	.string "POKéMON!\p"
	.string "{PLAYER} panicked and lost ¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "{PLAYER} whited out!$"

Text_WhitedOut::
	.string "{PLAYER} is out of usable\n"
	.string "POKéMON!\p"
	.string "{PLAYER} whited out!$"
