SevenIsland_PokemonCenter_1F_EventObjects:
	object_event 1, 64, 0, 7, 0, 2, 0, 3, 8, 17, 0, 0, 0, 0, 0, SevenIsland_PokemonCenter_1F_EventScript_170B98, 0, 0, 0
	object_event 2, 32, 0, 11, 0, 5, 0, 3, 8, 17, 0, 0, 0, 0, 0, SevenIsland_PokemonCenter_1F_EventScript_170BA1, 0, 0, 0
	object_event 3, 62, 0, 14, 0, 6, 0, 3, 9, 17, 0, 0, 0, 0, 0, SevenIsland_PokemonCenter_1F_EventScript_170BAA, 0, 0, 0
	object_event 4, 29, 0, 4, 0, 4, 0, 3, 10, 17, 0, 0, 0, 0, 0, SevenIsland_PokemonCenter_1F_EventScript_170BB3, 0, 0, 0
	object_event 5, 0, 0, 3, 0, 1, 0, 0, 76, 17, 0, 0, 0, 0, 0, SevenIsland_PokemonCenter_1F_EventScript_1ACFD4, 157, 0, 0
	object_event 6, 0, 0, 2, 0, 1, 0, 0, 76, 17, 0, 0, 0, 0, 0, SevenIsland_PokemonCenter_1F_EventScript_1ACFD4, 157, 0, 0

SevenIsland_PokemonCenter_1F_MapWarps:
	warp_def 7, 8, 3, 2, 785
	warp_def 1, 6, 4, 0, 7940

SevenIsland_PokemonCenter_1F_MapEvents::
	map_events SevenIsland_PokemonCenter_1F_EventObjects, SevenIsland_PokemonCenter_1F_MapWarps, 0x0, 0x0
