gUnknown_81A0B98:: @ 81A0B98
    .string "On this island, different events\n"
    .string "occur depending on connections.\p"
    .string "What are those connections?\p"
    .string "They are for you to discover on\n"
    .string "your own.$"

gUnknown_81A0C1F:: @ 81A0C1F
    .string "Did you ride a SEAGALLOP ferry\n"
    .string "to get here?\p"
    .string "There are at least ten of those\n"
    .string "high-speed ships.\p"
    .string "I don't know where they all go,\n"
    .string "though.$"

gUnknown_81A0CA5:: @ 81A0CA5
    .string "If you're confident, you should\n"
    .string "check out TRAINER TOWER.$"

