OneIsland_Text_BillLetsGoSeeCelio::
    .string "BILL: Here we are!\n"
    .string "This is ONE ISLAND.\p"
    .string "There are several islands around\n"
    .string "here, and this is one of them.\p"
    .string "My friend CELIO sent the boat to\n"
    .string "fetch me here.\p"
    .string "He's in charge of the island's PC\n"
    .string "network by his lonesome.\p"
    .string "…Why am I telling you this now?\n"
    .string "Let's just go see CELIO!$"

Text_WhereDoYouWantToSail::
    .string "Ahoy, there!\n"
    .string "Where do you want to sail?$"

OneIsland_Text_LuckyToHaveCelioHere::
    .string "Here we are on an island smack in\n"
    .string "the middle of nowhere.\p"
    .string "We're lucky to have an upstanding\n"
    .string "young man like CELIO here.\p"
    .string "My granddaughter was in a tizzy\n"
    .string "over CELIO's friend.\p"
    .string "Something about a famous\n"
    .string "POKéMANIAC?\p"
    .string "I'm not sure what that means, but\n"
    .string "CELIO is quite the man!$"

OneIsland_Text_HavePCLinkageWithKanto::
    .string "My granddaughter was in a tizzy\n"
    .string "over a new breakthrough.\p"
    .string "She said we now have PC linkage\n"
    .string "with people in KANTO.\p"
    .string "I'm not sure what that means, but\n"
    .string "CELIO is quite the man!$"

OneIsland_Text_HavePCLinkageWithHoenn::
    .string "My granddaughter was in a tizzy\n"
    .string "over a new breakthrough.\p"
    .string "She said we finally have PC linkage\n"
    .string "with people in HOENN.\p"
    .string "I'm not sure what that means, but\n"
    .string "CELIO is quite the man.\p"
    .string "He would make a fine husband for\n"
    .string "my granddaughter!$"

OneIsland_Text_IslandSign::
    .string "ONE ISLAND\n"
    .string "Friends Gather at Knot Island$"

OneIsland_Text_PokemonNetCenterSign::
    .string "Expanding the POKéMON World!\n"
    .string "POKéMON NET CENTER$"

@ Unused
OneIsland_Text_ReturnToCinnabar::
    .string "グレンタウンに　もどりますか？$"

OneIsland_Text_IsntWarmClimateHereGreat::
    .string "Hi, sight-seeing, are you?\n"
    .string "Isn't the warm climate here great?$"

