LavenderTown_Text_DoYouBelieveInGhosts:: @ 817F52E
    .string "Do you believe in ghosts?$"

LavenderTown_Text_SoThereAreBelievers:: @ 817F548
    .string "Really?\n"
    .string "So there are believers…$"

LavenderTown_Text_JustImaginingWhiteHand:: @ 817F568
    .string "Hahaha, I guess not.\p"
    .string "That white hand on your shoulder…\n"
    .string "I'm just imagining it.$"

LavenderTown_Text_TownKnownAsMonGraveSite:: @ 817F5B6
    .string "This town is known as the grave\n"
    .string "site of POKéMON.\p"
    .string "Memorial services are held in\n"
    .string "POKéMON TOWER.$"

LavenderTown_Text_GhostsAppearedInTower:: @ 817F614
    .string "Ghosts appeared in POKéMON TOWER.\p"
    .string "I think they're the spirits of\n"
    .string "POKéMON that the ROCKETS killed.$"

LavenderTown_Text_TownSign:: @ 817F676
    .string "LAVENDER TOWN\n"
    .string "The Noble Purple Town$"

LavenderTown_Text_SilphScopeNotice:: @ 817F69A
    .string "New SILPH SCOPE!\n"
    .string "Make the Invisible Plain to See!\p"
    .string "SILPH CO.$"

LavenderTown_Text_VolunteerPokemonHouse:: @ 817F6D6
    .string "LAVENDER VOLUNTEER\n"
    .string "POKéMON HOUSE$"

LavenderTown_Text_PokemonTowerSign:: @ 817F6F7
    .string "POKéMON TOWER\n"
    .string "Becalm the Spirits of POKéMON$"

