LavenderTown_Text_DoYouBelieveInGhosts::
    .string "¿Crees en los fantasmas?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "¿En serio?\n"
    .string "Así que sí hay creyentes…$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "Jajaja, supongo que no.\p"
    .string "Esa mano blanca en tu hombro…\n"
    .string "Sólo la estoy imaginando.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "Este pueblo es conocido como el\n"
    .string "cementerio de los POKéMON.\p"
    .string "Las ceremonias se realizan en la\n"
    .string "TORRE POKéMON.$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "Aparecieron fantasmas en la TORRE\n"
    .string "POKéMON.\p"
    .string "Creo que son los espíritus de los\n"
    .string "POKéMON que los ROCKETS mataron.$"

LavenderTown_Text_TownSign::
    .string "PUEBLO LAVANDA\n"
    .string "La noble ciudad púrpura$"

LavenderTown_Text_SilphScopeNotice::
    .string "¡Nuevo VISOR SILPH!\n"
    .string "¡Haz visible lo invisible!\p"
    .string "SILPH S.A.$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "CASA POKéMON VOLUNTARIA\n"
    .string "DE LAVANDA$"

LavenderTown_Text_PokemonTowerSign::
    .string "TORRE POKéMON\n"
    .string "Calma a los espíritus POKéMON$"

