PokemonMansion_Text_PressSecretSwitchJP:: @ 81775B4
    .string "ひみつの　スイッチが　ある！\p"
    .string "おして　みますか？$"

PokemonMansion_Text_LetsTryIt:: @ 81775CD
    .string "おしてみよう！　‥ポチッとな$"

PokemonMansion_Text_GaveUpOnPressingSwitch:: @ 81775DC
    .string "おすのは　あきらめた$"

PokemonMansion_1F_Text_SimonIntro:: @ 81775E7
    .string "This place is, like, huge!$"

PokemonMansion_1F_Text_SimonDefeat:: @ 8177602
    .string "Ayah!$"

PokemonMansion_1F_Text_SimonPostBattle:: @ 8177608
    .string "I wonder where my partner went.$"

PokemonMansion_1F_Text_BraydonIntro:: @ 8177628
    .string "My mentor once lived here.$"

PokemonMansion_1F_Text_BraydonDefeat:: @ 8177643
    .string "Whew!\n"
    .string "Overwhelming!$"

PokemonMansion_1F_Text_BraydonPostBattle:: @ 8177657
    .string "So, you're stuck?\n"
    .string "Try jumping off over there!$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo:: @ 8177685
    .string "Diary: Feb. 6\n"
    .string "MEW gave birth.\p"
    .string "We named the newborn MEWTWO.$"

