Text_1775B4:: @ 81775B4
    .string "ひみつの　スイッチが　ある！\p"
    .string "おして　みますか？$"

Text_1775CD:: @ 81775CD
    .string "おしてみよう！　‥ポチッとな$"

Text_1775DC:: @ 81775DC
    .string "ÈÒçè ÀÊúòŒ$"

Text_1775E7:: @ 81775E7
    .string "This place is, like, huge!$"

Text_177602:: @ 8177602
    .string "Ayah!$"

gUnknown_8177608:: @ 8177608
    .string "I wonder where my partner went.$"

Text_177628:: @ 8177628
    .string "My mentor once lived here.$"

Text_177643:: @ 8177643
    .string "Whew!\n"
    .string "Overwhelming!$"

gUnknown_8177657:: @ 8177657
    .string "So, you're stuck?\n"
    .string "Try jumping off over there!$"

gUnknown_8177685:: @ 8177685
    .string "Diary: Feb. 6\n"
    .string "MEW gave birth.\p"
    .string "We named the newborn MEWTWO.$"

