LavenderTown_PokemonCenter_1F_Text_RocketsDoAnythingForMoney::
    .string "Team Rocket will do anything for\n"
    .string "the sake of money!\p"
    .string "There is no job too dirty, no deed\n"
    .string "too heinous, no crime too wicked!$"

LavenderTown_PokemonCenter_1F_Text_CubonesMotherKilledByRockets::
    .string "I saw Cubone's mother trying to\n"
    .string "escape from Team Rocket.\p"
    .string "She was killed trying to get away…$"

LavenderTown_PokemonCenter_1F_Text_PeoplePayForCuboneSkulls::
    .string "You know how the Cubone species\n"
    .string "wears skulls, right?\p"
    .string "People will pay a lot for one.$"

