gUnknown_819D64F:: @ 819D64F
    .string "Hi! Remember me?\n"
    .string "I'm one of PROF. OAK's AIDES.\p"
    .string "If your POKéDEX has complete data\n"
    .string "on ten species, I'm supposed to\l"
    .string "give you a reward.\p"
    .string "PROF. OAK entrusted me with\n"
    .string "HM05 for you.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "ten kinds of POKéMON?$"

gUnknown_819D74E:: @ 819D74E
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"

gUnknown_819D7A1:: @ 819D7A1
    .string "{PLAYER} received HM05\n"
    .string "from the AIDE.$"

gUnknown_819D7C1:: @ 819D7C1
    .string "HM05 contains the hidden move\n"
    .string "FLASH.\p"
    .string "FLASH lights up even the darkest\n"
    .string "of caves and dungeons.$"

gUnknown_819D81E:: @ 819D81E
    .string "Once a POKéMON learns FLASH, you\n"
    .string "can get through ROCK TUNNEL.$"

