Route17_Text_RaulIntro:: @ 818717E
    .string "There's no getting rich quick in\n"
    .string "battling kids.$"

Route17_Text_RaulDefeat:: @ 81871AE
    .string "Burned out!$"

Route17_Text_RaulPostBattle:: @ 81871BA
    .string "You can find good stuff lying\n"
    .string "around on CYCLING ROAD.\p"
    .string "There's good money in picking them\n"
    .string "up and selling them.$"

Route17_Text_IsaiahIntro:: @ 8187228
    .string "I'm mighty proud of my bod, kiddo.\n"
    .string "Come on!$"

Route17_Text_IsaiahDefeat:: @ 8187254
    .string "Whoo!$"

Route17_Text_IsaiahPostBattle:: @ 818725A
    .string "I could belly-bump you outta\n"
    .string "here!$"

Route17_Text_VirgilIntro:: @ 818727D
    .string "You heading to FUCHSIA?$"

Route17_Text_VirgilDefeat:: @ 8187295
    .string "Crash and burn!$"

Route17_Text_VirgilPostBattle:: @ 81872A5
    .string "I love racing downhill!$"

Route17_Text_BillyIntro:: @ 81872BD
    .string "We're BIKERS!\n"
    .string "We rule the roads, man!$"

Route17_Text_BillyDefeat:: @ 81872E3
    .string "Smoked!$"

Route17_Text_BillyPostBattle:: @ 81872EB
    .string "Are you looking for adventure?$"

Route17_Text_NikolasIntro:: @ 818730A
    .string "Let VOLTORB electrify you!$"

Route17_Text_NikolasDefeat:: @ 8187325
    .string "Grounded out!$"

Route17_Text_NikolasPostBattle:: @ 8187333
    .string "I got my VOLTORB at the abandoned\n"
    .string "POWER PLANT.$"

Route17_Text_ZeekIntro:: @ 8187362
    .string "I leveled up my POKéMON, but it\n"
    .string "won't evolve. Why?$"

Route17_Text_ZeekDefeat:: @ 8187395
    .string "Why, you!$"

Route17_Text_ZeekPostBattle:: @ 818739F
    .string "Maybe some POKéMON need element\n"
    .string "STONES to evolve.$"

Route17_Text_JamalIntro:: @ 81873D1
    .string "I need a little exercise!$"

Route17_Text_JamalDefeat:: @ 81873EB
    .string "Whew!\n"
    .string "Good workout!$"

Route17_Text_JamalPostBattle:: @ 81873FF
    .string "I'm sure I lost weight there!$"

Route17_Text_CoreyIntro:: @ 818741D
    .string "Be a rebel!$"

Route17_Text_CoreyDefeat:: @ 8187429
    .string "Aaaargh!$"

Route17_Text_CoreyPostBattle:: @ 8187432
    .string "Be ready to fight for your beliefs!$"

Route17_Text_JaxonIntro:: @ 8187456
    .string "Nice BIKE!\n"
    .string "How's it handle?$"

Route17_Text_JaxonDefeat:: @ 8187472
    .string "Shoot!$"

Route17_Text_JaxonPostBattle:: @ 8187479
    .string "The slope makes it hard to steer.$"

Route17_Text_WilliamIntro:: @ 818749B
    .string "Get lost, kid!\n"
    .string "I'm bushed!$"

Route17_Text_WilliamDefeat:: @ 81874B6
    .string "Are you satisfied?$"

Route17_Text_WilliamPostBattle:: @ 81874C9
    .string "I need to catch a few z's!$"

Route17_Text_WatchOutForDiscardedItems:: @ 81874E4
    .string "It's a notice.\p"
    .string "Watch out for discarded items.$"

Route17_Text_SameSpeciesGrowDifferentRates:: @ 8187512
    .string "TRAINER TIPS\p"
    .string "All POKéMON are unique.\p"
    .string "Even POKéMON of the same species\n"
    .string "and level grow at different rates.$"

Route17_Text_PressBToStayInPlace:: @ 818757B
    .string "TRAINER TIPS\p"
    .string "Press the B Button to stay in place\n"
    .string "while on a slope.$"

Route17_Text_RouteSign:: @ 81875BE
    .string "ROUTE 17\n"
    .string "CELADON CITY - FUCHSIA CITY$"

Route17_Text_DontThrowGameThrowBalls:: @ 81875E3
    .string "It's a notice!\p"
    .string "Don't throw the game, throw POKé\n"
    .string "BALLS instead!$"

Route17_Text_CyclingRoadSign:: @ 8187622
    .string "CYCLING ROAD\n"
    .string "Slope ends here!$"

