Text_186FBD:: @ 8186FBD
    .string "JED: Our love knows no bounds.\n"
    .string "We're in love and we show it!$"

Text_186FFA:: @ 8186FFA
    .string "JED: Oh, no!\n"
    .string "My love has seen me as a loser!$"

Text_187027:: @ 8187027
    .string "JED: Listen, LEA.\n"
    .string "You need to focus less on me.$"

Text_187057:: @ 8187057
    .string "JED: You have just one POKéMON?\n"
    .string "Is there no love in your heart?$"

Text_187097:: @ 8187097
    .string "LEA: Sometimes, the intensity of\n"
    .string "our love scares me.$"

Text_1870CC:: @ 81870CC
    .string "LEA: Ohh! But JED looks cool\n"
    .string "even in a loss!$"

Text_1870F9:: @ 81870F9
    .string "LEA: Ehehe, I'm sorry.\n"
    .string "JED is so cool.$"

Text_187120:: @ 8187120
    .string "LEA: Oh, you don't have two\n"
    .string "POKéMON with you?\p"
    .string "Doesn't it feel lonely for you or\n"
    .string "your POKéMON?$"

Text_18717E:: @ 818717E
    .string "There's no getting rich quick in\n"
    .string "battling kids.$"

Text_1871AE:: @ 81871AE
    .string "Burned out!$"

Text_1871BA:: @ 81871BA
    .string "You can find good stuff lying\n"
    .string "around on CYCLING ROAD.\p"
    .string "There's good money in picking them\n"
    .string "up and selling them.$"

Text_187228:: @ 8187228
    .string "I'm mighty proud of my bod, kiddo.\n"
    .string "Come on!$"

Text_187254:: @ 8187254
    .string "Whoo!$"

Text_18725A:: @ 818725A
    .string "I could belly-bump you outta\n"
    .string "here!$"

Text_18727D:: @ 818727D
    .string "You heading to FUCHSIA?$"

Text_187295:: @ 8187295
    .string "Crash and burn!$"

Text_1872A5:: @ 81872A5
    .string "I love racing downhill!$"

Text_1872BD:: @ 81872BD
    .string "We're BIKERS!\n"
    .string "We rule the roads, man!$"

Text_1872E3:: @ 81872E3
    .string "Smoked!$"

Text_1872EB:: @ 81872EB
    .string "Are you looking for adventure?$"

Text_18730A:: @ 818730A
    .string "Let VOLTORB electrify you!$"

Text_187325:: @ 8187325
    .string "Grounded out!$"

Text_187333:: @ 8187333
    .string "I got my VOLTORB at the abandoned\n"
    .string "POWER PLANT.$"

Text_187362:: @ 8187362
    .string "I leveled up my POKéMON, but it\n"
    .string "won't evolve. Why?$"

Text_187395:: @ 8187395
    .string "Why, you!$"

Text_18739F:: @ 818739F
    .string "Maybe some POKéMON need element\n"
    .string "STONES to evolve.$"

Text_1873D1:: @ 81873D1
    .string "I need a little exercise!$"

Text_1873EB:: @ 81873EB
    .string "Whew!\n"
    .string "Good workout!$"

Text_1873FF:: @ 81873FF
    .string "I'm sure I lost weight there!$"

Text_18741D:: @ 818741D
    .string "Be a rebel!$"

Text_187429:: @ 8187429
    .string "Aaaargh!$"

Text_187432:: @ 8187432
    .string "Be ready to fight for your beliefs!$"

Text_187456:: @ 8187456
    .string "Nice BIKE!\n"
    .string "How's it handle?$"

Text_187472:: @ 8187472
    .string "Shoot!$"

Text_187479:: @ 8187479
    .string "The slope makes it hard to steer.$"

Text_18749B:: @ 818749B
    .string "Get lost, kid!\n"
    .string "I'm bushed!$"

Text_1874B6:: @ 81874B6
    .string "Are you satisfied?$"

Text_1874C9:: @ 81874C9
    .string "I need to catch a few z's!$"

gUnknown_81874E4:: @ 81874E4
    .string "It's a notice.\p"
    .string "Watch out for discarded items.$"

gUnknown_8187512:: @ 8187512
    .string "TRAINER TIPS\p"
    .string "All POKéMON are unique.\p"
    .string "Even POKéMON of the same species\n"
    .string "and level grow at different rates.$"

gUnknown_818757B:: @ 818757B
    .string "TRAINER TIPS\p"
    .string "Press the B Button to stay in place\n"
    .string "while on a slope.$"

gUnknown_81875BE:: @ 81875BE
    .string "ROUTE 17\n"
    .string "CELADON CITY - FUCHSIA CITY$"

gUnknown_81875E3:: @ 81875E3
    .string "It's a notice!\p"
    .string "Don't throw the game, throw POKé\n"
    .string "BALLS instead!$"

gUnknown_8187622:: @ 8187622
    .string "CYCLING ROAD\n"
    .string "Slope ends here!$"

