SevenIsland_SevaultCanyon_Entrance_EventObjects:
	object_event 1, 28, 0, 12, 0, 6, 0, 3, 9, 17, 0, 1, 0, 5, 0, SevenIsland_SevaultCanyon_Entrance_EventScript_1AC8C9, 0, 0, 0
	object_event 2, 29, 0, 3, 0, 34, 0, 3, 10, 17, 0, 1, 0, 1, 0, SevenIsland_SevaultCanyon_Entrance_EventScript_1AC907, 0, 0, 0
	object_event 3, 25, 0, 4, 0, 34, 0, 3, 9, 17, 0, 1, 0, 1, 0, SevenIsland_SevaultCanyon_Entrance_EventScript_1AC94D, 0, 0, 0
	object_event 4, 39, 0, 11, 0, 26, 0, 3, 20, 17, 0, 1, 0, 2, 0, SevenIsland_SevaultCanyon_Entrance_EventScript_1AC9D1, 0, 0, 0
	object_event 5, 40, 0, 10, 0, 26, 0, 3, 19, 17, 0, 1, 0, 2, 0, SevenIsland_SevaultCanyon_Entrance_EventScript_1ACA0F, 0, 0, 0
	object_event 6, 26, 0, 11, 0, 17, 0, 5, 23, 17, 0, 1, 0, 1, 0, SevenIsland_SevaultCanyon_Entrance_EventScript_1AC993, 0, 0, 0
	object_event 7, 65321, 0, 7, 0, 254, 255, 1, 0, 0, 0, 17, 0, 3, 0, 0x0, 0, 0, 0

SevenIsland_SevaultCanyon_Entrance_MapBGEvents:
	bg_event 8, 29, 5, 7, 0, 136, 188, 1
	bg_event 14, 26, 0, 0, 0, SevenIsland_SevaultCanyon_Entrance_EventScript_168BF4

SevenIsland_SevaultCanyon_Entrance_MapEvents::
	map_events SevenIsland_SevaultCanyon_Entrance_EventObjects, 0x0, 0x0, SevenIsland_SevaultCanyon_Entrance_MapBGEvents
