SevenIsland_SevaultCanyon_Entrance:: @ 8350CFC
    .4byte SevenIsland_SevaultCanyon_Entrance_Layout @ 0x8333020
    .4byte gMapEvents_SevenIsland_SevaultCanyon_Entrance @ 0x83B93FC
    .4byte gMapScripts_SevenIsland_SevaultCanyon_Entrance @ 0x8168BF3
    .4byte SevenIsland_SevaultCanyon_Entrance_MapConnections @ 0x8352EB0
    .2byte BGM_FRLG_SEVII_ISLANDS
    .2byte 255
    .byte 0xa8, 0x00, 0x02, 0x03, 0x01, 0x06, 0x00, 0x00
