# 1 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"

# 2 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_MapScripts::
# 3 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.byte 0
# 4 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"

# 5 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
SevenIsland_SevaultCanyon_Entrance_EventScript_RouteSign::
# 6 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	msgbox SevenIsland_SevaultCanyon_Entrance_Text_RouteSign, MSGBOX_SIGN
# 7 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	end
