SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
    .string "Kyahaha!\n"
    .string "I'll flick you away effortlessly!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
    .string "Tch!\n"
    .string "Too strong for me!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
    .string "What's that?\n"
    .string "I don't act the way I look?\p"
    .string "Heh, that's a part of my strategy!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
    .string "Howdy!\n"
    .string "Are you a member of my fan club?$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
    .string "Oh, so you're not a fan…\p"
    .string "Well, I can change that.\n"
    .string "Let me sing for you!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
    .string "Lalalah…\n"
    .string "My Pokémon, I send them out,\l"
    .string "all the girls scream and shout!$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
    .string "This island is too spread out…\n"
    .string "It's not easy patrolling the place.$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
    .string "Uh-huh…$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
    .string "Trainers like you from cities,\n"
    .string "they sure are tough.\p"
    .string "You'll be headed for the Tower,\n"
    .string "won't you?$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
    .string "I punish people who abuse\n"
    .string "Pokémon!$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
    .string "You don't seem to be a problem\n"
    .string "Trainer.$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
    .string "If you treat your Pokémon with\n"
    .string "kindness, they'll understand.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
    .string "Eve: I'll team up with Jon and\n"
    .string "battle together.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
    .string "Eve: Me and Jon, we lost.\n"
    .string "Ehehe.$"

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
    .string "Eve: I'm going to work harder with\n"
    .string "Jon.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
    .string "Eve: I want to team up with Jon\n"
    .string "when I battle you.\p"
    .string "Come back with two Pokémon, okay?$"

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
    .string "Jon: When I'm with Eve, it feels\n"
    .string "like we could never lose.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
    .string "Jon: When I'm with Eve,\n"
    .string "it doesn't feel like I've lost!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
    .string "Jon: When I'm with Eve, I feel\n"
    .string "giddy whether I win or lose.\p"
    .string "It's magical!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
    .string "Jon: If it's with Eve, I'll be\n"
    .string "happy to battle with you.\p"
    .string "So, I'd like to make it a\n"
    .string "two-on-two battle, if I may.$"

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
    .string "Sevault Canyon Entrance\p"
    .string "Trainers are asked to refrain from\n"
    .string "damaging plants in the Canyon.$"

