SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro:: @ 818C3BC
    .string "Kyahaha!\n"
    .string "I'll flick you away effortlessly!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat:: @ 818C3E7
    .string "Tch!\n"
    .string "Too strong for me!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle:: @ 818C3FF
    .string "What's that?\n"
    .string "I don't act the way I look?\p"
    .string "Heh, that's a part of my strategy!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro:: @ 818C44B
    .string "Howdy!\n"
    .string "Are you a member of my fan club?$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat:: @ 818C473
    .string "Oh, so you're not a fan…\p"
    .string "Well, I can change that.\n"
    .string "Let me sing for you!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle:: @ 818C4BA
    .string "Lalalah…\n"
    .string "My POKéMON, I send them out,\l"
    .string "all the girls scream and shout!$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro:: @ 818C500
    .string "This island is too spread out…\n"
    .string "It's not easy patrolling the place.$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat:: @ 818C543
    .string "Uh-huh…$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle:: @ 818C54B
    .string "TRAINERS like you from cities,\n"
    .string "they sure are tough.\p"
    .string "You'll be headed for the TOWER,\n"
    .string "won't you?$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro:: @ 818C5AA
    .string "I punish people who abuse\n"
    .string "POKéMON!$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat:: @ 818C5CD
    .string "You don't seem to be a problem\n"
    .string "TRAINER.$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle:: @ 818C5F5
    .string "If you treat your POKéMON with\n"
    .string "kindness, they'll understand.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro:: @ 818C632
    .string "EVE: I'll team up with JON and\n"
    .string "battle together.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat:: @ 818C662
    .string "EVE: Me and JON, we lost.\n"
    .string "Ehehe.$"

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle:: @ 818C683
    .string "EVE: I'm going to work harder with\n"
    .string "JON.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons:: @ 818C6AB
    .string "EVE: I want to team up with JON\n"
    .string "when I battle you.\p"
    .string "Come back with two POKéMON, okay?$"

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro:: @ 818C700
    .string "JON: When I'm with EVE, it feels\n"
    .string "like we could never lose.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat:: @ 818C73B
    .string "JON: When I'm with EVE,\n"
    .string "it doesn't feel like I've lost!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle:: @ 818C773
    .string "JON: When I'm with EVE, I feel\n"
    .string "giddy whether I win or lose.\p"
    .string "It's magical!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons:: @ 818C7BD
    .string "JON: If it's with EVE, I'll be\n"
    .string "happy to battle with you.\p"
    .string "So, I'd like to make it a\n"
    .string "two-on-two battle, if I may.$"

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign:: @ 818C82D
    .string "SEVAULT CANYON ENTRANCE\p"
    .string "TRAINERS are asked to refrain from\n"
    .string "damaging plants in the CANYON.$"

