SafariZone_Building1_EventObjects:
	object_event 1, 55, 0, 3, 0, 4, 0, 3, 2, 17, 0, 0, 0, 0, 0, SafariZone_Building1_EventScript_1623F5, 0, 0, 0
	object_event 2, 23, 0, 7, 0, 3, 0, 3, 8, 17, 0, 0, 0, 0, 0, SafariZone_Building1_EventScript_1623EC, 0, 0, 0

SafariZone_Building1_MapWarps:
	warp_def 3, 9, 3, 12, 319
	warp_def 4, 9, 3, 12, 319
	warp_def 5, 9, 3, 12, 319

SafariZone_Building1_MapEvents::
	map_events SafariZone_Building1_EventObjects, SafariZone_Building1_MapWarps, 0x0, 0x0
