TwoIsland_PokemonCenter_2F_MapScripts:: @ 81717DE
	map_script MAP_SCRIPT_ON_FRAME_TABLE, TwoIsland_PokemonCenter_2F_MapScript1_1BB2A3
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, TwoIsland_PokemonCenter_2F_MapScript2_1BB1ED
	map_script MAP_SCRIPT_ON_LOAD, TwoIsland_PokemonCenter_2F_MapScript3_1BB237
	map_script MAP_SCRIPT_ON_TRANSITION, TwoIsland_PokemonCenter_2F_MapScript4_1BB1B4
	.byte 0

TwoIsland_PokemonCenter_2F_EventScript_1717F3:: @ 81717F3
	call EventScript_1BB4A3
	end

EventScript_1717F9:: @ 81717F9
	call EventScript_1BB6AB
	end

EventScript_1717FF:: @ 81717FF
	call EventScript_1BB7DE
	end
