TwoIsland_PokemonCenter_2F_MapScripts:: @ 81717DE
    map_script 2, TwoIsland_PokemonCenter_2F_MapScript1_1BB2A3
    map_script 4, TwoIsland_PokemonCenter_2F_MapScript2_1BB1ED
    map_script 1, TwoIsland_PokemonCenter_2F_MapScript3_1BB237
    map_script 3, TwoIsland_PokemonCenter_2F_MapScript4_1BB1B4
    .byte 0

TwoIsland_PokemonCenter_2F_EventScript_1717F3:: @ 81717F3
    call EventScript_1BB4A3
    end

EventScript_1717F9:: @ 81717F9
    call EventScript_1BB6AB
    end

EventScript_1717FF:: @ 81717FF
    call EventScript_1BB7DE
    end
