gUnknown_819C142:: @ 819C142
    .string "…Wait! Don't say a word!\p"
    .string "You wanted this!$"

gUnknown_819C16C:: @ 819C16C
    .string "{PLAYER} received TM29\n"
    .string "from MR. PSYCHIC.$"

gUnknown_819C18F:: @ 819C18F
    .string "You already know, don't you?\n"
    .string "TM29 is PSYCHIC.\p"
    .string "It's an attack that may also lower\n"
    .string "the target's special stats.$"

gUnknown_819C1FC:: @ 819C1FC
    .string "Where do you plan to put this?\n"
    .string "You've no room.$"

