PokemonTower_6F_Text_AngelicaIntro:: @ 817A243
    .string "Give…me…\n"
    .string "blood…$"

PokemonTower_6F_Text_AngelicaDefeat:: @ 817A253
    .string "Groan!$"

PokemonTower_6F_Text_AngelicaPostBattle:: @ 817A25A
    .string "I feel anemic and weak…$"

PokemonTower_6F_Text_EmiliaIntro:: @ 817A272
    .string "Urff…\n"
    .string "Kwaah!$"

PokemonTower_6F_Text_EmiliaDefeat:: @ 817A27F
    .string "Something fell out!$"

PokemonTower_6F_Text_EmiliaPostBattle:: @ 817A293
    .string "My hair didn't fall out!\n"
    .string "It was a malevolent spirit!$"

PokemonTower_6F_Text_JenniferIntro:: @ 817A2C8
    .string "Ke…ke…ke…\n"
    .string "ke…ke…ke!$"

PokemonTower_6F_Text_JenniferDefeat:: @ 817A2DC
    .string "Keee!$"

PokemonTower_6F_Text_JenniferPostBattle:: @ 817A2E2
    .string "What's going on here?$"

PokemonTower_6F_Text_BeGoneIntruders:: @ 817A2F8
    .string "Be gone…\n"
    .string "Intruders…$"

PokemonTower_6F_Text_GhostWasCubonesMother:: @ 817A30C
    .string "The ghost was the restless spirit\n"
    .string "of CUBONE's mother!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed:: @ 817A342
    .string "The mother's spirit was calmed.\p"
    .string "It departed to the afterlife…$"

