PokemonTower_6F_Text_AngelicaIntro::
    .string "Give…me…\n"
    .string "blood…$"

PokemonTower_6F_Text_AngelicaDefeat::
    .string "Groan!$"

PokemonTower_6F_Text_AngelicaPostBattle::
    .string "I feel anemic and weak…$"

PokemonTower_6F_Text_EmiliaIntro::
    .string "Urff…\n"
    .string "Kwaah!$"

PokemonTower_6F_Text_EmiliaDefeat::
    .string "Something fell out!$"

PokemonTower_6F_Text_EmiliaPostBattle::
    .string "My hair didn't fall out!\n"
    .string "It was a malevolent spirit!$"

PokemonTower_6F_Text_JenniferIntro::
    .string "Ke…ke…ke…\n"
    .string "ke…ke…ke!$"

PokemonTower_6F_Text_JenniferDefeat::
    .string "Keee!$"

PokemonTower_6F_Text_JenniferPostBattle::
    .string "What's going on here?$"

PokemonTower_6F_Text_BeGoneIntruders::
    .string "Be gone…\n"
    .string "Intruders…$"

PokemonTower_6F_Text_GhostWasCubonesMother::
    .string "The ghost was the restless spirit\n"
    .string "of CUBONE's mother!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed::
    .string "The mother's spirit was calmed.\p"
    .string "It departed to the afterlife…$"

