PokemonTower_6F_Text_AngelicaIntro::
    .string "Give…me…\n"
    .string "blood…$"

PokemonTower_6F_Text_AngelicaDefeat::
    .string "Groan!$"

PokemonTower_6F_Text_AngelicaPostBattle::
    .string "I feel anemic and weak…$"

PokemonTower_6F_Text_EmiliaIntro::
    .string "Urff…\n"
    .string "Kwaah!$"

PokemonTower_6F_Text_EmiliaDefeat::
    .string "Something fell out!$"

PokemonTower_6F_Text_EmiliaPostBattle::
    .string "My hair didn't fall out!\n"
    .string "It was a malevolent spirit!$"

PokemonTower_6F_Text_JenniferIntro::
    .string "Ke…ke…ke…\n"
    .string "ke…ke…ke!$"

PokemonTower_6F_Text_JenniferDefeat::
    .string "Keee!$"

PokemonTower_6F_Text_JenniferPostBattle::
    .string "What's going on here?$"

PokemonTower_6F_Text_BeGoneIntruders::
    .string "The air grows cold.\p"
    .string "Something is here.\p"
    .string "A presence\n"
    .string "that refuses to fade.\p"
    .string "The Soul before you\n"
    .string "trembles with anger.\p"
    .string "It cannot move on.\p"
    .string "It is protecting\n"
    .string "something.\p"
    .string "The restless Soul\n"
    .string "took the form\n"
    .string "of a POKéMON.\p"
    .string "MAROWAK appeared!$"

PokemonTower_6F_Text_GhostWasCubonesMother::
    .string "The angry Soul\n"
    .string "calmed down.\p"
    .string "It was the Soul\n"
    .string "of MAROWAK.\p"
    .string "It refused to fade\n"
    .string "after death.\p"
    .string "Its final strength\n"
    .string "remained behind…\p"
    .string "to protect\n"
    .string "its child.$"

PokemonTower_6F_Text_MothersSpiritWasCalmed::
    .string "The Soul disperses\n"
    .string "peacefully.\p"
    .string "The air feels lighter.$"
