FourIsland_IcefallCave_1F_EventObjects:
	object_event 1, 92, 0, 11, 0, 7, 0, 3, 8, 17, 0, 0, 0, 0, 0, FourIsland_IcefallCave_1F_EventScript_1BED53, 496, 0, 0
	object_event 2, 92, 0, 12, 0, 16, 0, 3, 8, 17, 0, 0, 0, 0, 0, FourIsland_IcefallCave_1F_EventScript_1BED60, 497, 0, 0

FourIsland_IcefallCave_1F_MapWarps:
	warp_def 3, 17, 0, 1, 366
	warp_def 2, 8, 3, 2, 366
	warp_def 12, 12, 3, 0, 368
	warp_def 12, 3, 3, 1, 368
	warp_def 15, 16, 3, 2, 368
	warp_def 3, 6, 3, 0, 369

FourIsland_IcefallCave_1F_MapEvents::
	map_events FourIsland_IcefallCave_1F_EventObjects, FourIsland_IcefallCave_1F_MapWarps, 0x0, 0x0
