SixIsland_DottedHole_B2F_MapWarps:
	warp_def 6, 7, 3, 1, 372
	warp_def 6, 1, 3, 3, 371
	warp_def 11, 5, 3, 3, 371
	warp_def 6, 9, 3, 3, 371
	warp_def 1, 5, 3, 0, 374

SixIsland_DottedHole_B2F_MapBGEvents:
	bg_event 6, 5, 0, 1, 0, SixIsland_DottedHole_B2F_EventScript_1641A7

SixIsland_DottedHole_B2F_MapEvents::
	map_events 0x0, SixIsland_DottedHole_B2F_MapWarps, 0x0, SixIsland_DottedHole_B2F_MapBGEvents
