SafariZone_Building3_EventObjects:
	object_event 1, 61, 0, 3, 0, 4, 0, 3, 2, 17, 0, 0, 0, 0, 0, SafariZone_Building3_EventScript_16242D, 0, 0, 0
	object_event 2, 55, 0, 7, 0, 5, 0, 3, 2, 17, 0, 0, 0, 0, 0, SafariZone_Building3_EventScript_162424, 0, 0, 0
	object_event 3, 57, 0, 6, 0, 2, 0, 3, 1, 17, 0, 0, 0, 0, 0, SafariZone_Building3_EventScript_16241B, 0, 0, 0
	object_event 4, 30, 0, 11, 0, 2, 0, 3, 7, 17, 0, 0, 0, 0, 0, SafariZone_Building3_EventScript_1ACED3, 0, 0, 0

SafariZone_Building3_MapWarps:
	warp_def 3, 9, 3, 12, 321
	warp_def 4, 9, 3, 12, 321
	warp_def 5, 9, 3, 12, 321

SafariZone_Building3_MapEvents::
	map_events SafariZone_Building3_EventObjects, SafariZone_Building3_MapWarps, 0x0, 0x0
