gUnknown_8177B38:: @ 8177B38
    .string "You can keep any item you find in\n"
    .string "the SAFARI ZONE.\p"
    .string "But, you'll run out of time if you\n"
    .string "try for all of them at once.$"

gUnknown_8177BAB:: @ 8177BAB
    .string "Go to the deepest part of the\n"
    .string "SAFARI ZONE. You will win a prize!$"

gUnknown_8177BEC:: @ 8177BEC
    .string "My EEVEE evolved into FLAREON.\p"
    .string "But, a friend's EEVEE turned into a\n"
    .string "VAPOREON. I wonder why?$"

