SixIsland_Text_IslandSign:: @ 81831C6
    .string "SIX ISLAND\n"
    .string "Fortune Island of Aged Wisdom$"

SixIsland_Text_ThatWayToWaterPathRuinValley:: @ 81831EF
    .string "Keep going this way and you'll get\n"
    .string "to the WATER PATH.\p"
    .string "Stay on that and you'll get to\n"
    .string "the RUIN VALLEY.$"

SixIsland_Text_SkyAtNightIsFantastic:: @ 8183255
    .string "When you're this far away from the\n"
    .string "city, the sky at night is fantastic.$"

