SixIsland_Text_IslandSign::
    .string "Six Island\n"
    .string "Fortune Island of Aged Wisdom$"

SixIsland_Text_ThatWayToWaterPathRuinValley::
    .string "Keep going this way and you'll get\n"
    .string "to the Water Path.\p"
    .string "Stay on that and you'll get to\n"
    .string "the Ruin Valley.$"

SixIsland_Text_SkyAtNightIsFantastic::
    .string "When you're this far away from the\n"
    .string "city, the sky at night is fantastic.$"

