Text_RockSlideTeach::
    .string "When you're up on a rocky mountain\n"
    .string "like this, rockslides are a threat.\p"
    .string "Can you imagine?\n"
    .string "Boulders tumbling down on you?\p"
    .string "That'd be, like, waaaaaaaaaaah!\n"
    .string "Total terror!\p"
    .string "You don't seem to be scared.\n"
    .string "Want to try using Rock Slide?$"

Text_RockSlideDeclined::
    .string "Oh, so you are scared after all.$"

Text_RockSlideWhichMon::
    .string "Which Pokémon should I teach\n"
    .string "Rock Slide?$"

Text_RockSlideTaught::
    .string "It might be scary to use it in this\n"
    .string "tunnel…$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
    .string "Hint: Boulders might change the\n"
    .string "flow of water.$"

SeafoamIslands_B4F_Text_DangerFastCurrent::
    .string "Danger\n"
    .string "Fast current!$"

