UnknownMap_00_00_EventObjects:
	object_event 1, 66, 0, 9, 0, 3, 0, 3, 9, 0, 0, 0, 0, 0, 0, UnknownMap_00_00_EventScript_1BB9AF, 0, 0, 0

UnknownMap_00_00_MapWarps:
	warp_def 6, 8, 3, 127, 32639
	warp_def 7, 8, 3, 127, 32639

UnknownMap_00_00_MapCoordEvents:
	coord_event 3, 5, 3, 0, 16384, 0, 0, UnknownMap_00_00_EventScript_1BB8C3
	coord_event 10, 5, 3, 0, 16384, 0, 0, UnknownMap_00_00_EventScript_1BB8CF

UnknownMap_00_00_MapEvents::
	map_events UnknownMap_00_00_EventObjects, UnknownMap_00_00_MapWarps, UnknownMap_00_00_MapCoordEvents, 0x0
