CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers::
    .string "Pokémon stat enhancers can be\n"
    .string "bought only here.\p"
    .string "HP Up increases the base HP of a\n"
    .string "Pokémon.\p"
    .string "Calcium raises the base Sp. Atk\n"
    .string "stat of one Pokémon.\p"
    .string "Zinc boosts the base Sp. Def stat\n"
    .string "of one Pokémon.\p"
    .string "Carbos enhances the base Speed\n"
    .string "stat.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers::
    .string "I'm here for Pokémon stat\n"
    .string "enhancers.\p"
    .string "Protein increases the base Attack\n"
    .string "power.\p"
    .string "Iron increases the base Defense\n"
    .string "stat.$"

CeladonCity_DepartmentStore_5F_Text_Drugstore::
    .string "5F: Drugstore$"

