FiveIsland_PokemonCenter_2F_MapScripts:: @ 8171D1B
	map_script MAP_SCRIPT_ON_FRAME_TABLE, FiveIsland_PokemonCenter_2F_MapScript1_1BB2A3
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, FiveIsland_PokemonCenter_2F_MapScript2_1BB1ED
	map_script MAP_SCRIPT_ON_LOAD, FiveIsland_PokemonCenter_2F_MapScript3_1BB237
	map_script MAP_SCRIPT_ON_TRANSITION, FiveIsland_PokemonCenter_2F_MapScript4_1BB1B4
	.byte 0

FiveIsland_PokemonCenter_2F_EventScript_171D30:: @ 8171D30
	call EventScript_1BB4A3
	end

EventScript_171D36:: @ 8171D36
	call EventScript_1BB6AB
	end

EventScript_171D3C:: @ 8171D3C
	call EventScript_1BB7DE
	end
