gUnknown_8176266:: @ 8176266
    .string "Oh! Hi! You're not a ROCKET!\n"
    .string "You came to save us?\l"
    .string "Why, thank you!\p"
    .string "I want you to have this POKéMON\n"
    .string "for saving us.$"

Text_1762D7:: @ 81762D7
    .string "{PLAYER} obtained a LAPRAS from\n"
    .string "the SILPH employee!$"

gUnknown_8176305:: @ 8176305
    .string "It's a LAPRAS.\n"
    .string "It's a very intelligent POKéMON.\p"
    .string "We kept it in our lab, but it will\n"
    .string "be much better off with you.\p"
    .string "I think you will be a good TRAINER\n"
    .string "for LAPRAS!\p"
    .string "It's a good swimmer.\n"
    .string "It'll give you a lift across water!$"

gUnknown_81763DD:: @ 81763DD
    .string "TEAM ROCKET's BOSS went to the\n"
    .string "boardroom!\p"
    .string "Is our PRESIDENT okay?\n"
    .string "I'm worried.$"

Text_17642B:: @ 817642B
    .string "あ‥　もう　もてないぞ$"

Text_176437:: @ 8176437
    .string "たすかったよ　ありがと！$"

gUnknown_8176444:: @ 8176444
    .string "TEAM ROCKET was after the MASTER\n"
    .string "BALL, which catches any POKéMON.$"

gUnknown_8176486:: @ 8176486
    .string "We canceled the MASTER BALL\n"
    .string "project because of TEAM ROCKET.$"

gUnknown_81764C2:: @ 81764C2
    .string "It would be bad if TEAM ROCKET\n"
    .string "took over SILPH or our POKéMON.$"

gUnknown_8176501:: @ 8176501
    .string "Wow!\p"
    .string "You chased off TEAM ROCKET all by\n"
    .string "yourself?$"

gUnknown_8176532:: @ 8176532
    .string "You!\n"
    .string "It's really dangerous here!\p"
    .string "You came to save me?\n"
    .string "You can't!$"

gUnknown_8176573:: @ 8176573
    .string "Thank you so much!$"

Text_176586:: @ 8176586
    .string "Uh-oh!\n"
    .string "I smell a little mouse!$"

Text_1765A5:: @ 81765A5
    .string "Lights out!$"

gUnknown_81765B1:: @ 81765B1
    .string "You won't find my BOSS by just\n"
    .string "scurrying around!$"

Text_1765E2:: @ 81765E2
    .string "Heheh!\p"
    .string "You mistook me for a SILPH worker?$"

Text_17660C:: @ 817660C
    .string "I'm done!$"

gUnknown_8176616:: @ 8176616
    .string "Despite your age, you are a\n"
    .string "skilled TRAINER!$"

Text_176643:: @ 8176643
    .string "I am one of the four ROCKET\n"
    .string "BROTHERS!$"

Text_176669:: @ 8176669
    .string "Aack!\n"
    .string "Brothers, I lost!$"

gUnknown_8176681:: @ 8176681
    .string "Doesn't matter.\n"
    .string "My brothers will repay the favor!$"

Text_1766B3:: @ 81766B3
    .string "A child intruder?\n"
    .string "That must be you!$"

Text_1766D7:: @ 81766D7
    .string "Fine!\n"
    .string "I lost!$"

gUnknown_81766E5:: @ 81766E5
    .string "Go on home before my BOSS gets\n"
    .string "ticked off!$"

gUnknown_8176710:: @ 8176710
    .string "{RIVAL}: What kept you, {PLAYER}?$"

gUnknown_8176727:: @ 8176727
    .string "{RIVAL}: Hahaha! I thought you'd\n"
    .string "turn up if I waited here!\p"
    .string "I guess TEAM ROCKET slowed you\n"
    .string "down! Not that I care!\p"
    .string "I saw you in SAFFRON, so I decided\n"
    .string "to see if you got better!$"

Text_1767D0:: @ 81767D0
    .string "Oh, man!\n"
    .string "So, you are ready for BOSS\l"
    .string "ROCKET!$"

Text_1767FC:: @ 81767FC
    .string "{RIVAL}“おまえなあ‥\p"
    .string "こんな　うでまえじゃ\n"
    .string "まだまだ‥\l"
    .string "いちにんまえ　とは　いえないぜ$"

gUnknown_8176827:: @ 8176827
    .string "Well, {PLAYER}!\n"
    .string "I'm moving on up and ahead!\p"
    .string "By checking my POKéDEX, I'm\n"
    .string "starting to see what's strong and\l"
    .string "how they evolve!\p"
    .string "Am I a genius or what?\p"
    .string "I'm going to the POKéMON LEAGUE to\n"
    .string "boot out the ELITE FOUR.\p"
    .string "I'll become the world's most\n"
    .string "powerful TRAINER!\p"
    .string "{PLAYER}, well, good luck to you!\n"
    .string "Don't sweat it!\l"
    .string "Smell ya!$"

gUnknown_8176954:: @ 8176954
    .string "SILPH CO. HEAD OFFICE\n"
    .string "7F$"

