Route8_WestEntrance_Text_ThirstyOnGuardDuty::
    .string "I'm on guard duty.\n"
    .string "Gee, I'm thirsty, though!\p"
    .string "Oh, wait there, the road's closed.$"

Route8_WestEntrance_Text_ThatTeaLooksTasty::
    .string "Oh, that Tea…\n"
    .string "It looks awfully tasty…$"

Route8_WestEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "Huh? I can have this drink?\n"
    .string "Gee, thanks!\l"
    .string "… …\l"
    .string "Glug, glug…\l"
    .string "… …\l"
    .string "Gulp…\l"
    .string "If you want to go to Saffron\l"
    .string "City…\l"
    .string "… …\l"
    .string "You can go on through.\p"
    .string "I'll share this Tea with the other\n"
    .string "guards!$"

Route8_WestEntrance_Text_HiHowsItGoing::
    .string "Hi, how's it going?$"

