ViridianCity_Gym_EventObjects:
	object_event 1, 54, 0, 10, 0, 2, 0, 3, 8, 17, 0, 1, 0, 3, 0, ViridianCity_Gym_EventScript_169FD6, 0, 0, 0
	object_event 2, 41, 0, 12, 0, 10, 0, 3, 8, 17, 0, 1, 0, 3, 0, ViridianCity_Gym_EventScript_16A004, 0, 0, 0
	object_event 3, 54, 0, 11, 0, 14, 0, 3, 7, 17, 0, 1, 0, 3, 0, ViridianCity_Gym_EventScript_169FA8, 0, 0, 0
	object_event 4, 25, 0, 10, 0, 10, 0, 3, 8, 17, 0, 1, 0, 3, 0, ViridianCity_Gym_EventScript_169F7A, 0, 0, 0
	object_event 5, 25, 0, 2, 0, 21, 0, 3, 10, 17, 0, 1, 0, 2, 0, ViridianCity_Gym_EventScript_169F91, 0, 0, 0
	object_event 6, 54, 0, 3, 0, 11, 0, 3, 9, 17, 0, 1, 0, 2, 0, ViridianCity_Gym_EventScript_169FBF, 0, 0, 0
	object_event 7, 41, 0, 6, 0, 8, 0, 3, 8, 17, 0, 1, 0, 3, 0, ViridianCity_Gym_EventScript_169FED, 0, 0, 0
	object_event 8, 87, 0, 2, 0, 2, 0, 3, 8, 17, 0, 0, 0, 0, 0, ViridianCity_Gym_EventScript_169ECA, 85, 0, 0
	object_event 9, 41, 0, 13, 0, 7, 0, 3, 10, 17, 0, 1, 0, 3, 0, ViridianCity_Gym_EventScript_16A01B, 0, 0, 0
	object_event 10, 91, 0, 16, 0, 20, 0, 3, 8, 17, 0, 0, 0, 0, 0, ViridianCity_Gym_EventScript_16A032, 0, 0, 0

ViridianCity_Gym_MapWarps:
	warp_def 16, 22, 3, 2, 769
	warp_def 17, 22, 3, 2, 769
	warp_def 18, 22, 3, 2, 769

ViridianCity_Gym_MapBGEvents:
	bg_event 15, 20, 0, 0, 0, ViridianCity_Gym_EventScript_16A05E
	bg_event 19, 20, 0, 0, 0, ViridianCity_Gym_EventScript_16A05E
	bg_event 2, 2, 3, 7, 0, 181, 189, 129

ViridianCity_Gym_MapEvents::
	map_events ViridianCity_Gym_EventObjects, ViridianCity_Gym_MapWarps, 0x0, ViridianCity_Gym_MapBGEvents
