ViridianCity_Gym_Text_GiovanniIntro::
    .string "So, you made it to me again.\n"
    .string "Persistent... and strong.\p"
    .string "I was ready to rebuild TEAM ROCKET\n"
    .string "from the shadows.\p"
    .string "But if you stand in my way,\n"
    .string "I will crush you without mercy!\p"
    .string "Come, then!\n"
    .string "Face GIOVANNI at full power!{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

ViridianCity_Gym_Text_GiovanniDefeat::
    .string "...Impressive.\n"
    .string "You have broken my defense.\p"
    .string "You earned this battle...\n"
    .string "and the EARTHBADGE with it!\n"
    .string "{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"

ViridianCity_Gym_Text_GiovanniPostBattle::
    .string "I have no excuse for this loss.\n"
    .string "My men will not forgive it.\p"
    .string "From this day on, TEAM ROCKET\n"
    .string "is dissolved.\p"
    .string "I will leave and train in silence\n"
    .string "until I find my answer.\p"
    .string "We may meet again someday.\n"
    .string "Until then... farewell.$"

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis::
    .string "The EARTHBADGE will make POKéMON\n"
    .string "of any level obey you.\p"
    .string "It proves your strength, but more\n"
    .string "than strength, your resolve.\p"
    .string "Power carries the weight of souls.\n"
    .string "Use that power wisely.\p"
    .string "Now take this TM as well.\n"
    .string "It will aid your LEAGUE challenge.$"

ViridianCity_Gym_Text_ReceivedTM26FromGiovanni::
    .string "{PLAYER} received TM26\n"
    .string "from GIOVANNI.$"

ViridianCity_Gym_Text_ExplainTM26::
    .string "TM26 contains EARTHQUAKE.\p"
    .string "It is a powerful attack that causes\n"
    .string "a massive tremor.\p"
    .string "I made it when I ran the GYM here,\n"
    .string "far too long ago… $"

ViridianCity_Gym_Text_YouDoNotHaveSpace::
    .string "You do not have space for this!$"

ViridianCity_Gym_Text_YujiIntro::
    .string "Heh!\n"
    .string "You must be running out of steam\l"
    .string "by now!$"

ViridianCity_Gym_Text_YujiDefeat::
    .string "I ran out of gas!$"

ViridianCity_Gym_Text_YujiPostBattle::
    .string "You'll need power to keep up with\n"
    .string "our GYM LEADER.$"

ViridianCity_Gym_Text_AtsushiIntro::
    .string "Rrrroar!\n"
    .string "I'm working myself into a rage!$"

ViridianCity_Gym_Text_AtsushiDefeat::
    .string "Wargh!$"

ViridianCity_Gym_Text_AtsushiPostBattle::
    .string "I'm still not worthy!$"

ViridianCity_Gym_Text_JasonIntro::
    .string "POKéMON and I, we make wonderful\n"
    .string "music together!$"

ViridianCity_Gym_Text_JasonDefeat::
    .string "You are in perfect harmony!$"

ViridianCity_Gym_Text_JasonPostBattle::
    .string "Do you know the identity of our\n"
    .string "GYM LEADER?$"

ViridianCity_Gym_Text_KiyoIntro::
    .string "Karate is the ultimate form of\n"
    .string "martial arts!$"

ViridianCity_Gym_Text_KiyoDefeat::
    .string "Aiyah!$"

ViridianCity_Gym_Text_KiyoPostBattle::
    .string "If my POKéMON were as good at\n"
    .string "karate as I…$"

ViridianCity_Gym_Text_WarrenIntro::
    .string "The truly talented win with style.$"

ViridianCity_Gym_Text_WarrenDefeat::
    .string "I lost my grip!$"

ViridianCity_Gym_Text_WarrenPostBattle::
    .string "The LEADER will scold me for\n"
    .string "losing this way…$"

ViridianCity_Gym_Text_TakashiIntro::
    .string "I'm the KARATE KING!\n"
    .string "Your fate rests with me!$"

ViridianCity_Gym_Text_TakashiDefeat::
    .string "Ayah!$"

ViridianCity_Gym_Text_TakashiPostBattle::
    .string "The POKéMON LEAGUE?\n"
    .string "You? Don't get cocky!$"

ViridianCity_Gym_Text_ColeIntro::
    .string "Your POKéMON will cower at the\n"
    .string "crack of my whip!$"

ViridianCity_Gym_Text_ColeDefeat::
    .string "Yowch!\n"
    .string "Whiplash!$"

ViridianCity_Gym_Text_ColePostBattle::
    .string "Wait!\n"
    .string "I was just careless!$"

ViridianCity_Gym_Text_SamuelIntro::
    .string "VIRIDIAN GYM was closed for a\n"
    .string "long time.\p"
    .string "But now, our LEADER is back!$"

ViridianCity_Gym_Text_SamuelDefeat::
    .string "I was beaten?$"

ViridianCity_Gym_Text_SamuelPostBattle::
    .string "You can go on to the POKéMON\n"
    .string "LEAGUE only by defeating our GYM\l"
    .string "LEADER!$"

ViridianCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "Even I don't know the VIRIDIAN\n"
    .string "LEADER's identity.\p"
    .string "But one thing's certain.\n"
    .string "This will be the toughest of all\l"
    .string "the GYM LEADERS.\p"
    .string "Also, I heard that the TRAINERS\n"
    .string "here like GROUND-type POKéMON.$"

ViridianCity_Gym_Text_GymGuyPostVictory::
    .string "Blow me away! GIOVANNI was the\n"
    .string "GYM LEADER of VIRIDIAN?$"

ViridianCity_Gym_Text_GymStatue::
    .string "VIRIDIAN POKéMON GYM\n"
    .string "LEADER: ?\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
    .string "VIRIDIAN POKéMON GYM\n"
    .string "LEADER: GIOVANNI\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"
