RocketHideout_B1F_Text_Grunt1Intro:: @ 8174ECA
    .string "Who are you?\n"
    .string "How did you get here?$"

RocketHideout_B1F_Text_Grunt1Defeat:: @ 8174EED
    .string "Oww!\n"
    .string "Beaten!$"

RocketHideout_B1F_Text_Grunt1PostBattle:: @ 8174EFA
    .string "Blast it… You're dissing TEAM\n"
    .string "ROCKET, aren't you?$"

RocketHideout_B1F_Text_Grunt2Intro:: @ 8174F2C
    .string "You broke into TEAM ROCKET's\n"
    .string "operation? What nerve!$"

RocketHideout_B1F_Text_Grunt2Defeat:: @ 8174F60
    .string "Boom!$"

RocketHideout_B1F_Text_Grunt2PostBattle:: @ 8174F66
    .string "You're not going to get away with\n"
    .string "this, brat!$"

RocketHideout_B1F_Text_Grunt3Intro:: @ 8174F94
    .string "Intruder alert!$"

RocketHideout_B1F_Text_Grunt3Defeat:: @ 8174FA4
    .string "I can't do it!$"

RocketHideout_B1F_Text_Grunt3PostBattle:: @ 8174FB3
    .string "SILPH SCOPE? Humph!\n"
    .string "I don't know where it is.$"

RocketHideout_B1F_Text_Grunt4Intro:: @ 8174FE1
    .string "Why did you come here?$"

RocketHideout_B1F_Text_Grunt4Defeat:: @ 8174FF8
    .string "This won't do!$"

RocketHideout_B1F_Text_Grunt4PostBattle:: @ 8175007
    .string "Okay, I'll talk…\n"
    .string "Take the elevator to see my BOSS.$"

RocketHideout_B1F_Text_Grunt5Intro:: @ 817503A
    .string "Are you lost, you little mouse?$"

RocketHideout_B1F_Text_Grunt5Defeat:: @ 817505A
    .string "Why…?$"

RocketHideout_B1F_Text_Grunt5PostBattle:: @ 8175060
    .string "Uh-oh, that ruckus somehow opened\n"
    .string "the door!$"

