RocketHideout_B1F_Text_Grunt1Intro::
    .string "Who are you?\n"
    .string "How did you get here?$"

RocketHideout_B1F_Text_Grunt1Defeat::
    .string "Oww!\n"
    .string "Beaten!$"

RocketHideout_B1F_Text_Grunt1PostBattle::
    .string "Blast it… You're dissing Team\n"
    .string "Rocket, aren't you?$"

RocketHideout_B1F_Text_Grunt2Intro::
    .string "You broke into Team Rocket's\n"
    .string "operation? What nerve!$"

RocketHideout_B1F_Text_Grunt2Defeat::
    .string "Boom!$"

RocketHideout_B1F_Text_Grunt2PostBattle::
    .string "You're not going to get away with\n"
    .string "this, brat!$"

RocketHideout_B1F_Text_Grunt3Intro::
    .string "Intruder alert!$"

RocketHideout_B1F_Text_Grunt3Defeat::
    .string "I can't do it!$"

RocketHideout_B1F_Text_Grunt3PostBattle::
    .string "Silph Scope? Humph!\n"
    .string "I don't know where it is.$"

RocketHideout_B1F_Text_Grunt4Intro::
    .string "Why did you come here?$"

RocketHideout_B1F_Text_Grunt4Defeat::
    .string "This won't do!$"

RocketHideout_B1F_Text_Grunt4PostBattle::
    .string "Okay, I'll talk…\n"
    .string "Take the elevator to see my Boss.$"

RocketHideout_B1F_Text_Grunt5Intro::
    .string "Are you lost, you little mouse?$"

RocketHideout_B1F_Text_Grunt5Defeat::
    .string "Why…?$"

RocketHideout_B1F_Text_Grunt5PostBattle::
    .string "Uh-oh, that ruckus somehow opened\n"
    .string "the door!$"

