SixIsland_PokemonCenter_1F_EventObjects:
	object_event 1, 64, 0, 7, 0, 2, 0, 3, 8, 17, 0, 0, 0, 0, 0, SixIsland_PokemonCenter_1F_EventScript_171E05, 0, 0, 0
	object_event 2, 72, 0, 5, 0, 5, 0, 3, 9, 17, 0, 0, 0, 0, 0, 0x0, 152, 0, 0
	object_event 3, 56, 0, 13, 0, 3, 0, 3, 7, 17, 0, 0, 0, 0, 0, SixIsland_PokemonCenter_1F_EventScript_171E0E, 0, 0, 0
	object_event 4, 33, 0, 12, 0, 5, 0, 3, 8, 17, 0, 0, 0, 0, 0, SixIsland_PokemonCenter_1F_EventScript_171E17, 0, 0, 0

SixIsland_PokemonCenter_1F_MapWarps:
	warp_def 7, 8, 3, 1, 786
	warp_def 1, 6, 4, 0, 9473

SixIsland_PokemonCenter_1F_MapEvents::
	map_events SixIsland_PokemonCenter_1F_EventObjects, SixIsland_PokemonCenter_1F_MapWarps, 0x0, 0x0
