RocketHideout_B4F_Text_GiovanniIntro::
    .string "So...\n"
    .string "You're the TRAINER\n"
    .string "disrupting my operation.\p"
    .string "TRAINERS collect SOULS\n"
    .string "one battle at a time.\p"
    .string "I collect them\n"
    .string "by the thousands.$"

RocketHideout_B4F_Text_GiovanniDefeat::
    .string "Impossible...\n"
    .string "A child ruined\n"
    .string "my extraction site?$"

RocketHideout_B4F_Text_GiovanniPostBattle::
    .string "You carry SOULS\n"
    .string "but do not hoard them.\p"
    .string "Remember this:\n"
    .string "Power belongs\n"
    .string "to whoever takes it.$"

RocketHideout_B4F_Text_Grunt2Intro::
    .string "I know you!\n"
    .string "You ruined our plans at MT. MOON!$"

RocketHideout_B4F_Text_Grunt2Defeat::
    .string "Burned again!$"

RocketHideout_B4F_Text_Grunt2PostBattle::
    .string "Do you have something against TEAM\n"
    .string "ROCKET?$"

RocketHideout_B4F_Text_Grunt3Intro::
    .string "How can you not see the beauty of\n"
    .string "our evil?$"

RocketHideout_B4F_Text_Grunt3Defeat::
    .string "Ayaya!$"

RocketHideout_B4F_Text_Grunt3PostBattle::
    .string "BOSS!\n"
    .string "I'm sorry I failed you!$"

RocketHideout_B4F_Text_Grunt1Intro::
    .string "The elevator doesn't work?\n"
    .string "Who has the LIFT KEY?$"

RocketHideout_B4F_Text_Grunt1Defeat::
    .string "No!$"

RocketHideout_B4F_Text_Grunt1PostBattle::
    .string "Oh, no!\n"
    .string "I dropped the LIFT KEY!$"

