# 1 "data/maps/SSAnne_B1F_Room3/scripts.pory"

# 2 "data/maps/SSAnne_B1F_Room3/scripts.pory"
SSAnne_B1F_Room3_MapScripts::
# 3 "data/maps/SSAnne_B1F_Room3/scripts.pory"
	.byte 0
# 4 "data/maps/SSAnne_B1F_Room3/scripts.pory"

# 5 "data/maps/SSAnne_B1F_Room3/scripts.pory"
SSAnne_B1F_Room3_EventScript_Dylan::
# 6 "data/maps/SSAnne_B1F_Room3/scripts.pory"
	trainerbattle_single TRAINER_SAILOR_DYLAN, SSAnne_B1F_Room3_Text_DylanIntro, SSAnne_B1F_Room3_Text_DylanDefeat
# 7 "data/maps/SSAnne_B1F_Room3/scripts.pory"
	msgbox SSAnne_B1F_Room3_Text_DylanPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/SSAnne_B1F_Room3/scripts.pory"
	end
