FuchsiaCity_ZooBuilding_EventObjects:
	object_event 1, 47, 0, 2, 0, 2, 0, 3, 7, 17, 0, 0, 0, 0, 0, FuchsiaCity_ZooBuilding_EventScript_16D532, 0, 0, 0
	object_event 2, 47, 0, 12, 0, 3, 0, 3, 2, 17, 0, 0, 0, 0, 0, FuchsiaCity_ZooBuilding_EventScript_16D53B, 0, 0, 0
	object_event 3, 47, 0, 6, 0, 4, 0, 3, 10, 17, 0, 0, 0, 0, 0, FuchsiaCity_ZooBuilding_EventScript_16D529, 0, 0, 0
	object_event 4, 47, 0, 10, 0, 8, 0, 3, 9, 18, 0, 0, 0, 0, 0, FuchsiaCity_ZooBuilding_EventScript_16D544, 0, 0, 0

FuchsiaCity_ZooBuilding_MapWarps:
	warp_def 5, 9, 0, 3, 775
	warp_def 6, 9, 0, 3, 775
	warp_def 7, 9, 3, 3, 775

FuchsiaCity_ZooBuilding_MapEvents::
	map_events FuchsiaCity_ZooBuilding_EventObjects, FuchsiaCity_ZooBuilding_MapWarps, 0x0, 0x0
