gUnknown_818BD47:: @ 818BD47
    .string "I can't figure out how I'm supposed\n"
    .string "to get inside.$"

gUnknown_818BD7A:: @ 818BD7A
    .string "Let me tell you, I found this\n"
    .string "place.\p"
    .string "Don't look so envious, will you?$"

gUnknown_818BDC0:: @ 818BDC0
    .string "The door doesn't budge at all.\n"
    .string "Check it more thoroughly?$"

gUnknown_818BDF9:: @ 818BDF9
    .string "{PLAYER} left the door alone.$"

gUnknown_818BE11:: @ 818BE11
    .string "On closer inspection, there are\n"
    .string "several dots on the door…$"

gUnknown_818BE4B:: @ 818BE4B
    .string "The door is open.$"

