SafariZone_North_MapScripts:: @ 8162398
    .byte 0

SafariZone_North_EventScript_162399:: @ 8162399
    loadword 0, gUnknown_817789D
    callstd 3
    end

SafariZone_North_EventScript_1623A2:: @ 81623A2
    loadword 0, gUnknown_81778A8
    callstd 3
    end

SafariZone_North_EventScript_1623AB:: @ 81623AB
    loadword 0, gUnknown_81778D6
    callstd 3
    end

SafariZone_North_EventScript_1623B4:: @ 81623B4
    loadword 0, gUnknown_81778DD
    callstd 3
    end

SafariZone_North_EventScript_1623BD:: @ 81623BD
    loadword 0, gUnknown_8177935
    callstd 3
    end
