# 1 "data/maps/SafariZone_North/scripts.pory"

# 2 "data/maps/SafariZone_North/scripts.pory"
SafariZone_North_MapScripts::
# 3 "data/maps/SafariZone_North/scripts.pory"
	.byte 0
# 4 "data/maps/SafariZone_North/scripts.pory"

# 5 "data/maps/SafariZone_North/scripts.pory"
SafariZone_North_EventScript_RestHouseSign::
# 6 "data/maps/SafariZone_North/scripts.pory"
	msgbox SafariZone_North_Text_RestHouse, MSGBOX_SIGN
# 7 "data/maps/SafariZone_North/scripts.pory"
	end
# 8 "data/maps/SafariZone_North/scripts.pory"

# 9 "data/maps/SafariZone_North/scripts.pory"
SafariZone_North_EventScript_TrainerTips1::
# 10 "data/maps/SafariZone_North/scripts.pory"
	msgbox SafariZone_North_Text_SecretHouseStillAhead, MSGBOX_SIGN
# 11 "data/maps/SafariZone_North/scripts.pory"
	end
# 12 "data/maps/SafariZone_North/scripts.pory"

# 13 "data/maps/SafariZone_North/scripts.pory"
SafariZone_North_EventScript_AreaSign::
# 14 "data/maps/SafariZone_North/scripts.pory"
	msgbox SafariZone_North_Text_Area2, MSGBOX_SIGN
# 15 "data/maps/SafariZone_North/scripts.pory"
	end
# 16 "data/maps/SafariZone_North/scripts.pory"

# 17 "data/maps/SafariZone_North/scripts.pory"
SafariZone_North_EventScript_TrainerTips2::
# 18 "data/maps/SafariZone_North/scripts.pory"
	msgbox SafariZone_North_Text_ZigzagThroughTallGrass, MSGBOX_SIGN
# 19 "data/maps/SafariZone_North/scripts.pory"
	end
# 20 "data/maps/SafariZone_North/scripts.pory"

# 21 "data/maps/SafariZone_North/scripts.pory"
SafariZone_North_EventScript_TrainerTips3::
# 22 "data/maps/SafariZone_North/scripts.pory"
	msgbox SafariZone_North_Text_WinFreeHMFindSecretHouse, MSGBOX_SIGN
# 23 "data/maps/SafariZone_North/scripts.pory"
	end
