SafariZone_North_Text_RestHouse::
    .string "Rest House$"

SafariZone_North_Text_SecretHouseStillAhead::
    .string "Trainer Tips\p"
    .string "The Secret House is still ahead.$"

SafariZone_North_Text_Area2::
    .string "Area 2$"

SafariZone_North_Text_ZigzagThroughTallGrass::
    .string "Trainer Tips\p"
    .string "Pokémon hide in tall grass.\p"
    .string "Zigzag through grassy areas to\n"
    .string "flush them out.$"

SafariZone_North_Text_WinFreeHMFindSecretHouse::
    .string "Trainer Tips\p"
    .string "Win a free HM for finding the\n"
    .string "Secret House.$"

