SafariZone_North_Text_RestHouse:: @ 817789D
    .string "Rest House$"

SafariZone_North_Text_SecretHouseStillAhead:: @ 81778A8
    .string "Trainer Tips\p"
    .string "The Secret House is still ahead.$"

SafariZone_North_Text_Area2:: @ 81778D6
    .string "Area 2$"

SafariZone_North_Text_ZigzagThroughTallGrass:: @ 81778DD
    .string "Trainer Tips\p"
    .string "Pokémon hide in tall grass.\p"
    .string "Zigzag through grassy areas to\n"
    .string "flush them out.$"

SafariZone_North_Text_WinFreeHMFindSecretHouse:: @ 8177935
    .string "Trainer Tips\p"
    .string "Win a free HM for finding the\n"
    .string "Secret House.$"

