# 1 "data/maps/SafariZone_West_RestHouse/scripts.pory"

# 2 "data/maps/SafariZone_West_RestHouse/scripts.pory"
SafariZone_West_RestHouse_MapScripts::
# 3 "data/maps/SafariZone_West_RestHouse/scripts.pory"
	.byte 0
# 4 "data/maps/SafariZone_West_RestHouse/scripts.pory"

# 5 "data/maps/SafariZone_West_RestHouse/scripts.pory"
SafariZone_West_RestHouse_EventScript_Man::
# 6 "data/maps/SafariZone_West_RestHouse/scripts.pory"
	msgbox SafariZone_West_Text_BaitMakesMonStickAround, MSGBOX_NPC
# 7 "data/maps/SafariZone_West_RestHouse/scripts.pory"
	end
# 8 "data/maps/SafariZone_West_RestHouse/scripts.pory"

# 9 "data/maps/SafariZone_West_RestHouse/scripts.pory"
SafariZone_West_RestHouse_EventScript_Scientist::
# 10 "data/maps/SafariZone_West_RestHouse/scripts.pory"
	msgbox SafariZone_West_Text_RocksMakeMonRunButEasierCatch, MSGBOX_NPC
# 11 "data/maps/SafariZone_West_RestHouse/scripts.pory"
	end
# 12 "data/maps/SafariZone_West_RestHouse/scripts.pory"

# 13 "data/maps/SafariZone_West_RestHouse/scripts.pory"
SafariZone_West_RestHouse_EventScript_CooltrainerF::
# 14 "data/maps/SafariZone_West_RestHouse/scripts.pory"
	msgbox SafariZone_West_Text_HikedLotsDidntSeeMonIWanted, MSGBOX_NPC
# 15 "data/maps/SafariZone_West_RestHouse/scripts.pory"
	end
