SSAnne_Deck_MapScripts:: @ 8160A68
	.byte 0

SSAnne_Deck_EventScript_160A69:: @ 8160A69
	msgbox gUnknown_817326F, 2
	end

SSAnne_Deck_EventScript_160A72:: @ 8160A72
	msgbox gUnknown_81732C6, 2
	end

SSAnne_Deck_EventScript_160A7B:: @ 8160A7B
	msgbox gUnknown_81732A2, 2
	end

SSAnne_Deck_EventScript_160A84:: @ 8160A84
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_SAILOR_EDMOND, 0, Text_173308, Text_17332B
	msgbox gUnknown_817333E, 6
	end

SSAnne_Deck_EventScript_160A9B:: @ 8160A9B
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_SAILOR_TREVOR, 0, Text_173382, Text_1733A0
	msgbox gUnknown_81733B5, 6
	end
