SSAnne_Deck_Text_ShipDepartingSoon:: @ 817326F
    .string "The party's over.\n"
    .string "The ship will be departing soon.$"

SSAnne_Deck_Text_ScrubbingDecksHardWork:: @ 81732A2
    .string "Whew!\n"
    .string "Scrubbing decks is hard work!$"

SSAnne_Deck_Text_FeelSeasick:: @ 81732C6
    .string "Urf… I feel ill…\p"
    .string "I got seasick, so I stepped out to\n"
    .string "get some air…$"

SSAnne_Deck_Text_EdmondIntro:: @ 8173308
    .string "Hey, matey!\p"
    .string "Let's do a little jig!$"

SSAnne_Deck_Text_EdmondDefeat:: @ 817332B
    .string "You're impressive!$"

SSAnne_Deck_Text_EdmondPostBattle:: @ 817333E
    .string "How many kinds of POKéMON do you\n"
    .string "think there are in this big world?$"

SSAnne_Deck_Text_TrevorIntro:: @ 8173382
    .string "Ahoy, there!\n"
    .string "Are you seasick?$"

SSAnne_Deck_Text_TrevorDefeat:: @ 81733A0
    .string "I was just careless!$"

SSAnne_Deck_Text_TrevorPostBattle:: @ 81733B5
    .string "My pa said there are 100 kinds of\n"
    .string "POKéMON. I think there are more.$"

