CeruleanCity_House2_Text_RocketsStoleTMForDig::
.string "¡Esos miserables del TEAM ROCKET!\p"
.string "¡Mira lo que le hicieron a mi casa!\p"
.string "¡Robaron una MT para enseñar a los\n"
.string "POKéMON cómo CAVAR hoyos!\p"
.string "Iba a usarla en un MANKEY o un\n"
.string "SANDSHREW…\p"
.string "¡Me costó una fortuna!$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM::
.string "Lo que se pierde, se pierde.\p"
.string "Decidí enseñar a DIGLETT a CAVAR\n"
.string "sin una MT.$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood::
.string "¡El TEAM ROCKET debe estar intentando\n"
.string "CAVAR su camino hacia algo malo!$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut::
.string "¡El TEAM ROCKET dejó una salida!$"

