CeruleanCity_House2_Text_RocketsStoleTMForDig::
    .string "Those miserable Rockets!\p"
    .string "Look what they've done to my\n"
    .string "house!\p"
    .string "They stole a TM for teaching\n"
    .string "Pokémon how to Dig holes!\p"
    .string "I was going to use it on a\n"
    .string "Mankey or a Sandshrew…\p"
    .string "That cost me a bundle, it did!$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM::
    .string "I figure what's lost is lost.\p"
    .string "I decided to teach Diglett how to\n"
    .string "Dig without a TM.$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood::
    .string "Team Rocket must be trying to Dig\n"
    .string "their way into no good!$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut::
    .string "Team Rocket left a way out!$"

