CeruleanCity_House2_Text_RocketsStoleTMForDig::
    .string "Those miserable ROCKETS!\p"
    .string "Look what they've done to my\n"
    .string "house!\p"
    .string "They stole a TM for teaching\n"
    .string "POKéMON how to DIG holes!\p"
    .string "I was going to use it on a\n"
    .string "MANKEY or a SANDSHREW…\p"
    .string "That cost me a bundle, it did!$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM::
    .string "I figure what's lost is lost.\p"
    .string "I decided to teach DIGLETT how to\n"
    .string "DIG without a TM.$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood::
    .string "TEAM ROCKET must be trying to DIG\n"
    .string "their way into no good!$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut::
    .string "TEAM ROCKET left a way out!$"

