SilphCo_1F_Text_WelcomePresidentInBoardroom:: @ 81754F7
    .string "Welcome.\p"
    .string "The PRESIDENT is in the boardroom\n"
    .string "on 11F.$"

@ Tentative translation. Unknown origin
SilphCo_1F_Text_DestroyedWontBeFixedForWhile:: @ 817552A
    .string "めちゃめちゃに　こわされてる\n"
    .string "とうぶん　なおりそうに　ない‥$"

SilphCo_1F_Text_FloorSign:: @ 8175549
    .string "SILPH CO. HEAD OFFICE\n"
    .string "1F$"

