Route15_WestEntrance_1F_EventObjects:
	object_event 1, 60, 0, 6, 0, 2, 0, 3, 8, 17, 0, 0, 0, 0, 0, Route15_WestEntrance_1F_EventScript_170089, 0, 0, 0

Route15_WestEntrance_1F_MapWarps:
	warp_def 1, 6, 3, 0, 801
	warp_def 1, 7, 3, 0, 801
	warp_def 11, 6, 3, 1, 801
	warp_def 11, 7, 3, 1, 801
	warp_def 9, 10, 3, 0, 6145

Route15_WestEntrance_1F_MapEvents::
	map_events Route15_WestEntrance_1F_EventObjects, Route15_WestEntrance_1F_MapWarps, 0x0, 0x0
