LavenderTown_House1_Text_Cubone:: @ 819396B
    .string "CUBONE: Kyarugoo!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother:: @ 819397D
    .string "Those horrible ROCKETS!\n"
    .string "They deserve no mercy!\p"
    .string "That poor CUBONE's mother…\p"
    .string "It was killed trying to escape from\n"
    .string "TEAM ROCKET.$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone:: @ 81939F8
    .string "The ghost of POKéMON TOWER is\n"
    .string "gone!\p"
    .string "Someone must have soothed its\n"
    .string "restless spirit!$"

