SaffronCity_House_Text_DontLookAtMyLetter:: @ 819BE74
    .string "…Thank you for writing.\n"
    .string "I hope to see you soon!\p"
    .string "…Hey!\n"
    .string "Don't look at my letter!$"

SaffronCity_House_Text_Pidgey:: @ 819BEC3
    .string "PIDGEY: Kurukkoo!$"

SaffronCity_House_Text_GettingCopycatPokeDoll:: @ 819BED5
    .string "The COPYCAT is cute!\n"
    .string "I'm getting her a POKé DOLL.$"

SaffronCity_House_Text_ExplainPPUp:: @ 819BF07
    .string "I was given a PP UP as a gift.\p"
    .string "It's used to increase the PP of\n"
    .string "a POKéMON's move.\p"
    .string "I should use it on a powerful move\n"
    .string "with only a few PP.$"

