# 1 "data/maps/SSAnne_2F_Room2/scripts.pory"

# 2 "data/maps/SSAnne_2F_Room2/scripts.pory"
SSAnne_2F_Room2_MapScripts::
# 3 "data/maps/SSAnne_2F_Room2/scripts.pory"
	.byte 0
# 4 "data/maps/SSAnne_2F_Room2/scripts.pory"

# 5 "data/maps/SSAnne_2F_Room2/scripts.pory"
SSAnne_2F_Room2_EventScript_Dale::
# 6 "data/maps/SSAnne_2F_Room2/scripts.pory"
	trainerbattle_single TRAINER_FISHERMAN_DALE, SSAnne_2F_Room2_Text_DaleIntro, SSAnne_2F_Room2_Text_DaleDefeat
# 7 "data/maps/SSAnne_2F_Room2/scripts.pory"
	msgbox SSAnne_2F_Room2_Text_DalePostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/SSAnne_2F_Room2/scripts.pory"
	end
# 9 "data/maps/SSAnne_2F_Room2/scripts.pory"

# 10 "data/maps/SSAnne_2F_Room2/scripts.pory"
SSAnne_2F_Room2_EventScript_Brooks::
# 11 "data/maps/SSAnne_2F_Room2/scripts.pory"
	trainerbattle_single TRAINER_GENTLEMAN_BROOKS, SSAnne_2F_Room2_Text_BrooksIntro, SSAnne_2F_Room2_Text_BrooksDefeat
# 12 "data/maps/SSAnne_2F_Room2/scripts.pory"
	msgbox SSAnne_2F_Room2_Text_BrooksPostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/SSAnne_2F_Room2/scripts.pory"
	end
