Text_173D63:: @ 8173D63
    .string "Competing against the young keeps\n"
    .string "me youthful.$"

Text_173D92:: @ 8173D92
    .string "Good match!\n"
    .string "Ah, I feel young again!$"

gUnknown_8173DB6:: @ 8173DB6
    .string "Fifteen years ago, I would\n"
    .string "have won!$"

Text_173DDB:: @ 8173DDB
    .string "Check out what I fished up!$"

Text_173DF7:: @ 8173DF7
    .string "I'm all out!$"

gUnknown_8173E04:: @ 8173E04
    .string "Party?\p"
    .string "The cruise ship's party should be\n"
    .string "over by now.$"

