Route4_MapScripts::
	.byte 0

Route4_EventScript_Unused::
	end

Route4_EventScript_MtMoonSign::
	msgbox Route4_Text_MtMoonEntrance, MSGBOX_SIGN
	end

Route4_EventScript_RouteSign::
	msgbox Route4_Text_RouteSign, MSGBOX_SIGN
	end

Route4_EventScript_IfFindRareTakeToPewterMuseum::
	msgbox Route4_Text_IfFindRareTakeToPewterMuseum, MSGBOX_NPC
	end


Route4_EventScript_GeodudeHelpsClearLooseRocks::
	msgbox Route4_Text_GeodudeHelpsClearLooseRocks, MSGBOX_NPC
	end