gUnknown_81838D7:: @ 81838D7
    .string "Ouch! I tripped over a rocky\n"
    .string "POKéMON, GEODUDE!$"

Text_183906:: @ 8183906
    .string "I came to MT. MOON in search of\n"
    .string "mushroom POKéMON.$"

Text_183938:: @ 8183938
    .string "After all I did to catch them!$"

Text_183957:: @ 8183957
    .string "There might not be any more\n"
    .string "mushrooms here.\p"
    .string "I think I got them all.$"

gUnknown_818399B:: @ 818399B
    .string "MT. MOON\n"
    .string "Tunnel Entrance$"

gUnknown_81839B4:: @ 81839B4
    .string "ROUTE 4\n"
    .string "MT. MOON - CERULEAN CITY$"

