Route4_Text_TrippedOverGeodude::
    .string "¡Ay! Tropecé con un POKéMON\n"
    .string "rocoso, ¡GEODUDE!$"

Route4_Text_CrissyIntro::
    .string "Vine al MT. MOON en busca de\n"
    .string "POKéMON hongos.$"

Route4_Text_CrissyDefeat::
    .string "¡Después de todo lo que hice para\n"
    .string "atraparlos!$"

Route4_Text_CrissyPostBattle::
    .string "Puede que ya no haya más\n"
    .string "hongos aquí.\p"
    .string "Creo que ya los atrapé todos.$"

Route4_Text_MtMoonEntrance::
    .string "MT. MOON\n"
    .string "ENTRADA DEL TÚNEL$"

Route4_Text_RouteSign::
    .string "RUTA 4\n"
    .string "MT. MOON - CIUDAD CELESTE$"

Text_MegaPunchTeach::
    .string "¡Un puñetazo de ferocidad estruendosa!\p"
    .string "¡Cargado con poder destructivo!\p"
    .string "Cuando estés en apuros,\n"
    .string "¡MEGA PUNCH es el ataque definitivo!\l"
    .string "¿Estás de acuerdo?\p"
    .string "¡Ahora!\n"
    .string "¡Déjame enseñárselo a tu POKéMON!$"

Text_MegaPunchDeclined::
    .string "Volverás cuando entiendas\n"
    .string "el valor de MEGA PUNCH.$"

Text_MegaPunchWhichMon::
    .string "¡Bien!\n"
    .string "¿Qué POKéMON lo aprenderá?$"

Text_MegaPunchTaught::
    .string "¡Ahora somos camaradas en el arte del\n"
    .string "puñetazo!\p"
    .string "Deberías irte antes de que te vea\n"
    .string "el tonto descarriado que solo entrena\l"
    .string "sus patadas ridículas allá.$"

Text_MegaKickTeach::
    .string "¡Una patada de ferocidad brutal!\p"
    .string "¡Cargada con poder destructivo!\p"
    .string "A fin de cuentas,\n"
    .string "¡MEGA KICK es el ataque definitivo!\l"
    .string "¿No lo crees?\p"
    .string "¡Bien!\n"
    .string "¡Se la enseñaré a tu POKéMON!$"

Text_MegaKickDeclined::
    .string "Volverás arrepentido cuando\n"
    .string "entiendas el valor de MEGA KICK.$"

Text_MegaKickWhichMon::
    .string "¡Muy bien!\n"
    .string "¿Qué POKéMON quiere aprenderlo?$"

Text_MegaKickTaught::
    .string "¡Ahora somos almas gemelas en el arte\n"
    .string "de la patada!\p"
    .string "Deberías correr antes de que te vea\n"
    .string "el iluso despistado que solo entrena\l"
    .string "sus simples puñetazos allá.$"

Route4_Text_PeopleLikeAndRespectBrock::
    .string "¡Oh, vaya, esa es la MEDALLA ROCA!\n"
    .string "La obtuviste de BROCK, ¿verdad?\p"
    .string "BROCK es genial. No solo es fuerte.\n"
    .string "La gente lo quiere y lo respeta.\p"
    .string "Quiero convertirme en un LÍDER de\n"
    .string "GIMNASIO como él.$"
