VermilionCity_Text_GrimerMultipliesInSludge:: @ 817F723
    .string "We're careful about pollution here.\p"
    .string "We've heard GRIMER multiplies in\n"
    .string "toxic sludge.$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor:: @ 817F776
    .string "Did you see the S.S. ANNE moored\n"
    .string "in the harbor?$"

VermilionCity_Text_SSAnneHasDepartedForYear:: @ 817F7A6
    .string "So, the S.S. ANNE has departed?\p"
    .string "She'll be back in VERMILION about\n"
    .string "this time next year.$"

VermilionCity_Text_BuildingOnThisLand:: @ 817F7FD
    .string "I'm putting up a building on this\n"
    .string "plot of land. I own it all.\p"
    .string "My POKéMON is tamping the land\n"
    .string "to lay the foundation.$"

VermilionCity_Text_Machop:: @ 817F871
    .string "MACHOP: Guoh! Gogogoh!$"

VermilionCity_Text_MachopStompingLandFlat:: @ 817F888
    .string "A MACHOP is stomping the land flat.$"

VermilionCity_Text_SSAnneVisitsOnceAYear:: @ 817F8AC
    .string "The S.S. ANNE is a famous luxury\n"
    .string "cruise ship.\p"
    .string "It visits VERMILION once a year.$"

VermilionCity_Text_CitySign:: @ 817F8FB
    .string "VERMILION CITY\n"
    .string "The Port of Exquisite Sunsets$"

VermilionCity_Text_SnorlaxBlockingRoute12:: @ 817F928
    .string "NOTICE!\p"
    .string "ROUTE 12 may be blocked off by a\n"
    .string "sleeping POKéMON.\p"
    .string "Detour through ROCK TUNNEL to\n"
    .string "LAVENDER TOWN.\p"
    .string "VERMILION POLICE$"

VermilionCity_Text_PokemonFanClubSign:: @ 817F9A1
    .string "POKéMON FAN CLUB\n"
    .string "All POKéMON fans welcome!$"

VermilionCity_Text_GymSign:: @ 817F9CC
    .string "VERMILION CITY POKéMON GYM\n"
    .string "LEADER: LT. SURGE\l"
    .string "The Lightning American!$"

VermilionCity_Text_VermilionHarbor:: @ 817FA11
    .string "VERMILION HARBOR$"

VermilionCity_Text_WelcomeToTheSSAnne:: @ 817FA22
    .string "Welcome to the S.S. ANNE!$"

VermilionCity_Text_DoYouHaveATicket:: @ 817FA3C
    .string "Welcome to the S.S. ANNE!\p"
    .string "Excuse me, do you have a ticket?$"

VermilionCity_Text_FlashedSSTicket:: @ 817FA77
    .string "{SIZE}Á{PLAYER} flashed the S.S. TICKET!\p"
    .string "{SIZE}ÇGreat!\n"
    .string "Welcome to the S.S. ANNE!$"

VermilionCity_Text_DontHaveNeededSSTicket:: @ 817FABA
    .string "{SIZE}Á{PLAYER} doesn't have the needed\n"
    .string "S.S. TICKET.\p"
    .string "{SIZE}ÇSorry!\p"
    .string "You need a ticket to get aboard.$"

VermilionCity_Text_TheShipSetSail:: @ 817FB10
    .string "The ship set sail.$"

VermilionCity_Text_BoardSeagallopTriPass:: @ 817FB23
    .string "Ah, you have a TRI-PASS.\p"
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"

VermilionCity_Text_Seagallop7Departing:: @ 817FB67
    .string "Okay, everything's in order.\p"
    .string "SEAGALLOP HI-SPEED 7 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_BoardSeagallopRainbowPass:: @ 817FBB8
    .string "Ah, you have a RAINBOW PASS.\p"
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock:: @ 817FC00
    .string "Oh! That's a MYSTICTICKET!\n"
    .string "Now that is rare.\p"
    .string "We'll be happy to take you to\n"
    .string "NAVEL ROCK anytime.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland:: @ 817FC5F
    .string "Oh! That's an AURORATICKET!\n"
    .string "Now that is rare.\p"
    .string "We'll be happy to take you to\n"
    .string "BIRTH ISLAND anytime.$"

VermilionCity_Text_BoardSeagallopFerry:: @ 817FCC1
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"

VermilionCity_Text_Seagallop10Departing:: @ 817FCEC
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "SEAGALLOP HI-SPEED 10 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Seagallop12Departing:: @ 817FD5F
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "SEAGALLOP HI-SPEED 12 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Route2AideHasPackageForYou:: @ 817FDD2
    .string "Oh, hello, {PLAYER}!\n"
    .string "How are you doing?\p"
    .string "It's me, one of PROF. OAK's AIDES.\p"
    .string "Did you meet the other AIDE?\p"
    .string "He had a package from PROF. OAK\n"
    .string "for you, {PLAYER}.\p"
    .string "He said he'd look for you around\n"
    .string "ROUTE 2, {PLAYER}.\p"
    .string "If you're in the ROUTE 2 area,\n"
    .string "please look for him.$"

