VermilionCity_Text_GrimerMultipliesInSludge::
    .string "We're careful about pollution here.\p"
    .string "We've heard Grimer multiplies in\n"
    .string "toxic sludge.$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor::
    .string "Did you see the S.S. Anne moored\n"
    .string "in the harbor?$"

VermilionCity_Text_SSAnneHasDepartedForYear::
    .string "So, the S.S. Anne has departed?\p"
    .string "She'll be back in Vermilion about\n"
    .string "this time next year.$"

VermilionCity_Text_BuildingOnThisLand::
    .string "I'm putting up a building on this\n"
    .string "plot of land. I own it all.\p"
    .string "My Pokémon is tamping the land\n"
    .string "to lay the foundation.$"

VermilionCity_Text_Machop::
    .string "Machop: Guoh! Gogogoh!$"

VermilionCity_Text_MachopStompingLandFlat::
    .string "A Machop is stomping the land flat.$"

VermilionCity_Text_SSAnneVisitsOnceAYear::
    .string "The S.S. Anne is a famous luxury\n"
    .string "cruise ship.\p"
    .string "It visits Vermilion once a year.$"

VermilionCity_Text_CitySign::
    .string "Vermilion City\n"
    .string "The Port of Exquisite Sunsets$"

VermilionCity_Text_SnorlaxBlockingRoute12::
    .string "Notice!\p"
    .string "Route 12 may be blocked off by a\n"
    .string "sleeping Pokémon.\p"
    .string "Detour through Rock Tunnel to\n"
    .string "Lavender Town.\p"
    .string "Vermilion Police$"

VermilionCity_Text_PokemonFanClubSign::
    .string "Pokémon Fan Club\n"
    .string "All Pokémon fans welcome!$"

VermilionCity_Text_GymSign::
    .string "Vermilion City Pokémon Gym\n"
    .string "Leader: Lt. Surge\l"
    .string "The Lightning American!$"

VermilionCity_Text_VermilionHarbor::
    .string "Vermilion Harbor$"

VermilionCity_Text_WelcomeToTheSSAnne::
    .string "Welcome to the S.S. Anne!$"

VermilionCity_Text_DoYouHaveATicket::
    .string "Welcome to the S.S. Anne!\p"
    .string "Excuse me, do you have a ticket?$"

VermilionCity_Text_FlashedSSTicket::
    .string "{FONT_2}{PLAYER} flashed the S.S. Ticket!\p"
    .string "{FONT_4}Great!\n"
    .string "Welcome to the S.S. Anne!$"

VermilionCity_Text_DontHaveNeededSSTicket::
    .string "{FONT_2}{PLAYER} doesn't have the needed\n"
    .string "S.S. Ticket.\p"
    .string "{FONT_4}Sorry!\p"
    .string "You need a ticket to get aboard.$"

VermilionCity_Text_TheShipSetSail::
    .string "The ship set sail.$"

VermilionCity_Text_BoardSeagallopTriPass::
    .string "Ah, you have a Tri-Pass.\p"
    .string "Would you like to board\n"
    .string "a Seagallop ferry?$"

VermilionCity_Text_Seagallop7Departing::
    .string "Okay, everything's in order.\p"
    .string "Seagallop Hi-Speed 7 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_BoardSeagallopRainbowPass::
    .string "Ah, you have a Rainbow Pass.\p"
    .string "Would you like to board\n"
    .string "a Seagallop ferry?$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock::
    .string "Oh! That's a MysticTicket!\n"
    .string "Now that is rare.\p"
    .string "We'll be happy to take you to\n"
    .string "Navel Rock anytime.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland::
    .string "Oh! That's an AuroraTicket!\n"
    .string "Now that is rare.\p"
    .string "We'll be happy to take you to\n"
    .string "Birth Island anytime.$"

VermilionCity_Text_BoardSeagallopFerry::
    .string "Would you like to board\n"
    .string "a Seagallop ferry?$"

VermilionCity_Text_Seagallop10Departing::
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "Seagallop Hi-Speed 10 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Seagallop12Departing::
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "Seagallop Hi-Speed 12 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Route2AideHasPackageForYou::
    .string "Oh, hello, {PLAYER}!\n"
    .string "How are you doing?\p"
    .string "It's me, one of Prof. Oak's Aides.\p"
    .string "Did you meet the other Aide?\p"
    .string "He had a package from Prof. Oak\n"
    .string "for you, {PLAYER}.\p"
    .string "He said he'd look for you around\n"
    .string "Route 2, {PLAYER}.\p"
    .string "If you're in the Route 2 area,\n"
    .string "please look for him.$"

