PewterCity_House2_EventObjects:
	object_event 1, 32, 0, 3, 0, 3, 0, 3, 10, 17, 0, 0, 0, 0, 0, PewterCity_House2_EventScript_16A7DD, 0, 0, 0
	object_event 2, 16, 0, 5, 0, 3, 0, 3, 13, 17, 0, 0, 0, 0, 0, PewterCity_House2_EventScript_16A7E6, 0, 0, 0

PewterCity_House2_MapWarps:
	warp_def 3, 7, 0, 6, 770
	warp_def 4, 7, 0, 6, 770
	warp_def 5, 7, 0, 6, 770

PewterCity_House2_MapEvents::
	map_events PewterCity_House2_EventObjects, PewterCity_House2_MapWarps, 0x0, 0x0
