gUnknown_81917E4:: @ 81917E4
    .string "POKéMON learn new techniques as\n"
    .string "they grow.\p"
    .string "But some moves must be taught to\n"
    .string "them by people.$"

gUnknown_8191840:: @ 8191840
    .string "A POKéMON becomes easier to \n"
    .string "catch if it has a status problem.\p"
    .string "Sleep, poison, burn, or paralysis…\n"
    .string "Those are all effective.\p"
    .string "But catching POKéMON is never\n"
    .string "a sure thing!$"

