PokemonLeague_LoreleisRoom_Text_Intro::
    .string "Welcome to the Pokémon League.\p"
    .string "I am Lorelei of the Elite Four.\p"
    .string "No one can best me when it comes\n"
    .string "to icy Pokémon.\p"
    .string "Freezing moves are powerful.\p"
    .string "Your Pokémon will be at my mercy\n"
    .string "when they are frozen solid.\p"
    .string "Hahaha!\n"
    .string "Are you ready?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .string "Welcome to the Pokémon League.\p"
    .string "I, Lorelei of the Elite Four,\n"
    .string "have returned!\p"
    .string "You know how it goes.\n"
    .string "No one can best me when it comes\l"
    .string "to icy Pokémon.\p"
    .string "Freezing moves are powerful.\p"
    .string "Your Pokémon will be at my mercy\n"
    .string "when they are frozen solid.\p"
    .string "Hahaha!\n"
    .string "Are you ready?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "…Things shouldn't be this way!$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "You're better than I thought.\n"
    .string "Go on ahead.\p"
    .string "You only got a taste of the\n"
    .string "Pokémon League's power.$"

