gUnknown_81970FE:: @ 81970FE
    .string "おきゃくさん もう もてないよ$" @ I'm sorry I don't have any more

gUnknown_819710E:: @ 819710E
    .string "あっ そう$" @ I see

Text_197114:: @ 8197114
    .string "Hello…\n"
    .string "Lovely weather, isn't it?\l"
    .string "It's so pleasant…\p"

    .string "…Oh, dear…\n"
    .string "I must have dozed off. Welcome.\p"

    .string "My name is ERIKA.\n"
    .string "I am the LEADER of CELADON GYM.\p"

    .string "I am a student of the art of\n"
    .string "flower arranging.\p"

    .string "My POKéMON are solely of the\n"
    .string "GRASS type.\p"

    .string "…Oh, I'm sorry, I had no idea that\n"
    .string "you wished to challenge me.\p"

    .string "Very well, but I shall not lose.{PLAY_BGM MUS_EXEYE}$"

Text_197260:: @ 8197260
    .string "Oh!\n"
    .string "I concede defeat.\l"
    .string "You are remarkably strong.\p"

    .string "I must confer on you the\n"
    .string "RAINBOWBADGE.$"

gUnknown_81972B8:: @ 81972B8
    .string "You are cataloging POKéMON?\n"
    .string "I must say I'm impressed.\p"

    .string "I would never collect POKéMON if\n"
    .string "they were unattractive.$"

gUnknown_8197327:: @ 8197327
    .string "The RAINBOWBADGE will make\n"
    .string "POKéMON up to Lv. 50 obey.\p"

    .string "It also allows POKéMON to use\n"
    .string "STRENGTH in and out of battle.\p"

    .string "Please also take this with you.$"

gUnknown_81973BA:: @ 81973BA
    .string "{PLAYER} received TM19\n"
    .string "from ERIKA.$"

gUnknown_81973D7:: @ 81973D7
    .string "TM19 contains GIGA DRAIN.\p"

    .string "Half the damage it inflicts is\n"
    .string "drained to heal your POKéMON.\p"

    .string "Wouldn't you agree that it's a\n"
    .string "wonderful move?$"

gUnknown_819745D:: @ 819745D
    .string "You should make room for this.$"

Text_19747C:: @ 819747C
    .string "I should tell you about this GYM.\p"
    .string "Only real ladies are allowed in\n"
    .string "here!$"

Text_1974C4:: @ 81974C4
    .string "You're too rough!$"

gUnknown_81974D6:: @ 81974D6
    .string "Bleaah!\n"
    .string "I hope ERIKA wipes you out!$"

Text_1974FA:: @ 81974FA
    .string "Oh, welcome.\n"
    .string "I was getting bored.$"

Text_19751C:: @ 819751C
    .string "My makeup!$"

gUnknown_8197527:: @ 8197527
    .string "GRASS-type POKéMON are tough\n"
    .string "against the WATER type.\p"
    .string "They also have an edge on ROCK-\n"
    .string "and GROUND-type POKéMON.$"

Text_197595:: @ 8197595
    .string "…Weren't you peeking in here\n"
    .string "earlier?$"

Text_1975BB:: @ 81975BB
    .string "You're an eye-opener!$"

gUnknown_81975D1:: @ 81975D1
    .string "Oh, you were looking at ERIKA…\n"
    .string "You weren't looking at me…$"

Text_19760B:: @ 819760B
    .string "Look, look!\n"
    .string "See my POKéMON!\p"
    .string "I like the GRASS type.\n"
    .string "I like how they're easy to raise.$"

Text_197660:: @ 8197660
    .string "No!$"

gUnknown_8197664:: @ 8197664
    .string "We only use GRASS-type POKéMON at\n"
    .string "our GYM.\p"
    .string "Why? We also use them for making\n"
    .string "flower arrangements!$"

Text_1976C5:: @ 81976C5
    .string "Oh, hey!\p"
    .string "We don't like BUG- or FIRE-type\n"
    .string "POKéMON in here!$"

Text_1976FF:: @ 81976FF
    .string "Oh!\n"
    .string "You!$"

gUnknown_8197708:: @ 8197708
    .string "Our LEADER ERIKA might be quiet,\n"
    .string "but she's famous around here.$"

Text_197747:: @ 8197747
    .string "Pleased to meet you.\n"
    .string "My hobby is POKéMON training.$"

Text_19777A:: @ 819777A
    .string "Oh!\n"
    .string "Splendid!$"

gUnknown_8197788:: @ 8197788
    .string "I have a blind date coming up.\n"
    .string "I have to learn to be polite,\l"
    .string "especially if I have to battle.$"

Text_1977E5:: @ 81977E5
    .string "Welcome to CELADON GYM!\p"
    .string "You'd better not underestimate\n"
    .string "the nice ladies here.$"

Text_197832:: @ 8197832
    .string "Oh!\n"
    .string "Beaten!$"

gUnknown_819783E:: @ 819783E
    .string "I didn't bring my best POKéMON.\n"
    .string "Wait until next time!$"

gUnknown_8197874:: @ 8197874
    .string "CELADON POKéMON GYM\n"
    .string "LEADER: ERIKA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

gUnknown_81978AB:: @ 81978AB
    .string "CELADON POKéMON GYM\n"
    .string "LEADER: ERIKA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

