gUnknown_8195D22:: @ 8195D22
    .string "I'm thirsty!\n"
    .string "I want something to drink!\p"
    .string "{SIZE}ÁGive her a drink?$"

Text_195D5F:: @ 8195D5F
    .string "Give her which drink?$"

gUnknown_8195D75:: @ 8195D75
    .string "Yay!\p"
    .string "FRESH WATER!\p"
    .string "Thank you!\n"
    .string "You can have this from me!$"

Text_195DAD:: @ 8195DAD
    .string "{PLAYER} received a {STR_VAR_2}\n"
    .string "from the little girl.$"

gUnknown_8195DD4:: @ 8195DD4
    .string "TM16 contains LIGHT SCREEN.\p"
    .string "It's a move that weakens the power\n"
    .string "of special attacks by your foe.$"

gUnknown_8195E33:: @ 8195E33
    .string "Yay!\p"
    .string "SODA POP!\p"
    .string "Thank you!\n"
    .string "You can have this from me!$"

gUnknown_8195E68:: @ 8195E68
    .string "TM20 contains SAFEGUARD.\p"
    .string "It's a move that prevents status\n"
    .string "problems among your POKéMON.$"

gUnknown_8195EBF:: @ 8195EBF
    .string "Yay!\p"
    .string "LEMONADE!\p"
    .string "Thank you!\n"
    .string "You can have this from me!$"

gUnknown_8195EF4:: @ 8195EF4
    .string "TM33 contains REFLECT.\p"
    .string "It's a move that weakens the power\n"
    .string "of physical attacks by your foe.$"

gUnknown_8195F4F:: @ 8195F4F
    .string "You don't have space for this!$"

gUnknown_8195F6E:: @ 8195F6E
    .string "No, thank you!\n"
    .string "I'm not thirsty after all!$"

gUnknown_8195F98:: @ 8195F98
    .string "My sister is a TRAINER, believe it\n"
    .string "or not.\p"
    .string "But, she's so immature, she drives\n"
    .string "me nuts!$"

gUnknown_8195FEF:: @ 8195FEF
    .string "I'm thirsty!\n"
    .string "I want something to drink!$"

gUnknown_8196017:: @ 8196017
    .string "ROOFTOP SQUARE:\n"
    .string "VENDING MACHINES$"

Text_196038:: @ 8196038
    .string "A vending machine!\n"
    .string "What does it have?$"

gUnknown_819605E:: @ 819605E
    .string "Oops, not enough money!$"

gUnknown_8196076:: @ 8196076
    .string "A can of {STR_VAR_1} popped out!$"

gUnknown_819608E:: @ 819608E
    .string "There's no more room for stuff!$"

gUnknown_81960AE:: @ 81960AE
    .string "Not thirsty!$"

