CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink::
    .string "I'm thirsty!\n"
    .string "I want something to drink!\p"
    .string "{FONT_NORMAL}Give her a drink?$"

CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink::
    .string "Give her which drink?$"

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis::
    .string "Yay!\p"
    .string "FRESH WATER!\p"
    .string "Thank you!\n"
    .string "You can have this from me!$"

Text_ReceivedItemFromLittleGirl::
    .string "{PLAYER} received a {STR_VAR_2}\n"
    .string "from the little girl.$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16::
    .string "TM16 contains LIGHT SCREEN.\p"
    .string "It's a move that weakens the power\n"
    .string "of special attacks by your foe.$"

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis::
    .string "Yay!\p"
    .string "SODA POP!\p"
    .string "Thank you!\n"
    .string "You can have this from me!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20::
    .string "TM20 contains SAFEGUARD.\p"
    .string "It's a move that prevents status\n"
    .string "problems among your POKéMON.$"

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis::
    .string "Yay!\p"
    .string "LEMONADE!\p"
    .string "Thank you!\n"
    .string "You can have this from me!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33::
    .string "TM33 contains REFLECT.\p"
    .string "It's a move that weakens the power\n"
    .string "of physical attacks by your foe.$"

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis::
    .string "You don't have space for this!$"

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll::
    .string "No, thank you!\n"
    .string "I'm not thirsty after all!$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature::
    .string "My sister is a TRAINER, believe it\n"
    .string "or not.\p"
    .string "But, she's so immature, she drives\n"
    .string "me nuts!$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink::
    .string "I'm thirsty!\n"
    .string "I want something to drink!$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign::
    .string "ROOFTOP SQUARE:\n"
    .string "VENDING MACHINES$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave::
    .string "A vending machine!\n"
    .string "What does it have?$"

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney::
    .string "Oops, not enough money!$"

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut::
    .string "A can of {STR_VAR_1} popped out!$"

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff::
    .string "There's no more room for stuff!$"

CeladonCity_DepartmentStore_Roof_Text_NotThirsty::
    .string "Not thirsty!$"

