SSAnne_1F_Room2_Text_TylerIntro:: @ 8173999
    .string "I love POKéMON!\n"
    .string "Do you?$"

SSAnne_1F_Room2_Text_TylerDefeat:: @ 81739B1
    .string "Wow! \n"
    .string "You're great!$"

SSAnne_1F_Room2_Text_TylerPostBattle:: @ 81739C5
    .string "Listen, listen!\n"
    .string "Let me be your friend, okay?\p"
    .string "Then we can trade POKéMON and\n"
    .string "do stuff.$"

SSAnne_1F_Room2_Text_AnnIntro:: @ 8173A1A
    .string "I collected these POKéMON\n"
    .string "from all around the world!$"

SSAnne_1F_Room2_Text_AnnDefeat:: @ 8173A4F
    .string "Oh, no!\n"
    .string "I went around the world for these!$"

SSAnne_1F_Room2_Text_AnnPostBattle:: @ 8173A7A
    .string "You hurt my poor POKéMON!\p"
    .string "I demand that you heal them at a\n"
    .string "POKéMON CENTER!$"

SSAnne_1F_Room2_Text_CruisingAroundWorld:: @ 8173AC5
    .string "We are cruising around the world,\n"
    .string "my children and I.$"

