IndigoPlateau_PokemonCenter_1F_EventObjects:
	object_event 1, 68, 0, 0, 0, 7, 0, 3, 10, 17, 0, 0, 0, 0, 0, IndigoPlateau_PokemonCenter_1F_EventScript_16EACC, 0, 0, 0
	object_event 2, 64, 0, 13, 0, 10, 0, 3, 8, 17, 0, 0, 0, 0, 0, IndigoPlateau_PokemonCenter_1F_EventScript_16EB06, 0, 0, 0
	object_event 3, 91, 0, 7, 0, 14, 0, 3, 10, 17, 0, 0, 0, 0, 0, IndigoPlateau_PokemonCenter_1F_EventScript_16EAC3, 0, 0, 0
	object_event 4, 42, 0, 5, 0, 3, 0, 3, 8, 17, 0, 0, 0, 0, 0, IndigoPlateau_PokemonCenter_1F_EventScript_16EA8A, 0, 0, 0
	object_event 5, 54, 0, 23, 0, 13, 0, 3, 10, 17, 0, 0, 0, 0, 0, IndigoPlateau_PokemonCenter_1F_EventScript_1ACFAE, 157, 0, 0
	object_event 6, 0, 0, 22, 0, 9, 0, 0, 76, 17, 0, 0, 0, 0, 0, IndigoPlateau_PokemonCenter_1F_EventScript_1AD06C, 157, 0, 0
	object_event 7, 41, 0, 16, 0, 15, 0, 3, 2, 17, 0, 0, 0, 0, 0, IndigoPlateau_PokemonCenter_1F_EventScript_1AD087, 157, 0, 0
	object_event 8, 0, 0, 23, 0, 9, 0, 0, 76, 17, 0, 0, 0, 0, 0, IndigoPlateau_PokemonCenter_1F_EventScript_1AD06C, 157, 0, 0

IndigoPlateau_PokemonCenter_1F_MapWarps:
	warp_def 11, 16, 3, 0, 777
	warp_def 4, 1, 3, 0, 331
	warp_def 1, 14, 4, 0, 3329

IndigoPlateau_PokemonCenter_1F_MapEvents::
	map_events IndigoPlateau_PokemonCenter_1F_EventObjects, IndigoPlateau_PokemonCenter_1F_MapWarps, 0x0, 0x0
