Text_MetronomeTeach::
    .string "Tch-tch-tch!\n"
    .string "I'll teach you a nifty move.\p"
    .string "Teach it to a POKéMON, and watch\n"
    .string "the fun unfold!\p"
    .string "It's a move called METRONOME.\n"
    .string "Does it strike your fancy?$"

Text_MetronomeDeclined::
    .string "I tell you, it's a lot of fun!$"

Text_MetronomeWhichMon::
    .string "Okay!\n"
    .string "Which POKéMON should I teach?$"

Text_MetronomeTaught::
    .string "Tch-tch-tch!\n"
    .string "That's the sound of a METRONOME.\p"
    .string "It tweaks your POKéMON's brain into\n"
    .string "using moves it doesn't even know.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe::
    .string "Hiya!\p"
    .string "I am important doctor.\n"
    .string "Yes, very much so, indeed.\p"
    .string "Here, I study rare POKéMON fossils.\n"
    .string "All the time, I study.\p"
    .string "You!\n"
    .string "Have you a fossil for me?$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad::
    .string "No!\n"
    .string "Is too bad!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalkJP::
    .string "ちょっと　じかん　かかるよ！\p"
    .string "そこらへんを　すこし\n"
    .string "ブラブラ　してくると　よろしー！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife::
    .string "You late.\n"
    .string "Where were you?\p"
    .string "Your fossil is back to life!\n"
    .string "It was {STR_VAR_1} like I think!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor::
    .string "{PLAYER} received the {STR_VAR_1}\n"
    .string "from the doctor.$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon::
    .string "ポケモン　いっぱいで　もてないね！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain::
    .string "Oh!\n"
    .string "That is {STR_VAR_2}, it is!\p"
    .string "It is fossil of {STR_VAR_1},\n"
    .string "a POKéMON that is already extinct!\p"
    .string "My Resurrection Machine will make\n"
    .string "that POKéMON live again!$"

@ TODO: Resolve text dump error below?
CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor::
    .string "So!\n"
    .string "You hurry and give me that!\p"
    .string "{FONT_NORMAL}{PLAYER} handed over the\n"
    .string "{STR_VAR_2} to the weird doctor.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk::
    .string "I take a little time!\n"
    .string "You go for walk a little while!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain::
    .string "Aiyah!\n"
    .string "You come again!$"

