Route21_North_Text_RonaldIntro:: @ 818835A
	.string "You want to know if the fish are\n"
	.string "biting?$"

Route21_North_Text_RonaldDefeat:: @ 8188383
	.string "Dang!$"

Route21_North_Text_RonaldPostBattle:: @ 8188389
	.string "I can't catch anything good.\n"
	.string "Not one good POKéMON to be had!$"

Route21_North_Text_WadeIntro:: @ 81883C6
	.string "I got a big haul!\n"
	.string "Wanna go for it?$"

Route21_North_Text_WadeDefeat:: @ 81883E9
	.string "Heheh, MAGIKARP just don't make\n"
	.string "the grade, do they?$"

Route21_North_Text_WadePostBattle:: @ 818841D
	.string "I seem to only catch MAGIKARP!$"

Route21_North_Text_SpencerIntro:: @ 818843C
	.string "The sea cleanses my body and soul!$"

Route21_North_Text_SpencerDefeat:: @ 818845F
	.string "Ayah!$"

Route21_North_Text_SpencerPostBattle:: @ 8188465
	.string "The sea is great and all, but I\n"
	.string "like the mountains, too.$"

@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro:: @ 818849E
	.string "おれだって　たまには\n"
	.string "およぎに　くるぜ！$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat:: @ 81884B3
	.string "ぐわわ！$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle:: @ 81884B8
	.string "うきやすそう　だと？\n"
	.string "うるせー　おおきな　おせわだッ！$"
