CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor:: @ 8196940
    .string "Welcome!\p"
    .string "You can exchange your Coins for\n"
    .string "fabulous prizes next door.$"

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins:: @ 8196984
    .string "Welcome to Rocket Game Corner!\p"
    .string "Do you need some game Coins?\n"
    .string "Would you like to buy some?$"

CeladonCity_GameCorner_Text_ComePlaySometime:: @ 81969DC
    .string "No?\n"
    .string "Please come play sometime!$"

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase:: @ 81969FB
    .string "Oh, I'm sorry.\n"
    .string "You don't have a Coin Case.$"

CeladonCity_GameCorner_Text_CoinCaseIsFull:: @ 8196A26
    .string "Whoops!\n"
    .string "Your Coin Case is full.$"

CeladonCity_GameCorner_Text_CantAffordCoins:: @ 8196A46
    .string "You can't afford the Coins.$"

CeladonCity_GameCorner_Text_HereAreYourCoins:: @ 8196A62
    .string "Thank you.\n"
    .string "Here are your Coins!$"

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace:: @ 8196A82
    .string "Keep this quiet.\p"
    .string "It's rumored that this place is run\n"
    .string "by Team Rocket.$"

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds:: @ 8196AC7
    .string "I think these machines have\n"
    .string "different odds.$"

CeladonCity_GameCorner_Text_DoYouWantToPlay:: @ 8196AF3
    .string "Kid, do you want to play?$"

CeladonCity_GameCorner_Text_Received10CoinsFromMan:: @ 8196B0D
    .string "{PLAYER} received 10 Coins\n"
    .string "from the man.$"

CeladonCity_GameCorner_Text_DontNeedMyCoins:: @ 8196B30
    .string "You don't need my Coins!$"

CeladonCity_GameCorner_Text_WinsComeAndGo:: @ 8196B49
    .string "Wins seem to come and go.\n"
    .string "Nothing's a sure thing.$"

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck:: @ 8196B7B
    .string "These slot games…\n"
    .string "Win or lose, it's only by luck.$"

CeladonCity_GameCorner_Text_GymGuyAdvice:: @ 8196BAD
    .string "Hey!\p"
    .string "You have better things to do,\n"
    .string "champ in the making!\p"
    .string "Celadon Gym's Leader is Erika.\p"
    .string "She is a user of Grass-type\n"
    .string "Pokémon, and at one with nature.\p"
    .string "She might appear docile because of\n"
    .string "her flower arranging…\p"
    .string "But she's not one to be taken\n"
    .string "lightly!$"

CeladonCity_GameCorner_Text_RareMonsForCoins:: @ 8196CA1
    .string "They offer rare Pokémon that can\n"
    .string "be exchanged for your Coins.\p"
    .string "But, I just can't seem to win!$"

CeladonCity_GameCorner_Text_SoEasyToGetHooked:: @ 8196CFE
    .string "Games are scary!\n"
    .string "It's so easy to get hooked!$"

CeladonCity_GameCorner_Text_WantSomeCoins:: @ 8196D2B
    .string "What's up?\n"
    .string "Want some Coins?$"

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy:: @ 8196D47
    .string "{PLAYER} received 20 Coins\n"
    .string "from the nice guy.$"

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins:: @ 8196D6F
    .string "You have lots of Coins!$"

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant:: @ 8196D87
    .string "Darn! I need more Coins for the\n"
    .string "Pokémon I want!$"

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo:: @ 8196DB7
    .string "Hey, what? You're throwing me off!\n"
    .string "Here are some Coins, so shoo!$"

CeladonCity_GameCorner_Text_Received20CoinsFromMan:: @ 8196DF8
    .string "{PLAYER} received 20 Coins\n"
    .string "from the man.$"

CeladonCity_GameCorner_Text_YouveGotPlentyCoins:: @ 8196E1B
    .string "You've got plenty of your own\n"
    .string "Coins!$"

CeladonCity_GameCorner_Text_WatchReelsClosely:: @ 8196E40
    .string "The trick is to watch the reels\n"
    .string "closely.$"

CeladonCity_GameCorner_Text_GruntIntro:: @ 8196E69
    .string "I'm guarding this poster!\n"
    .string "Go away, or else!$"

CeladonCity_GameCorner_Text_GruntDefeat:: @ 8196E95
    .string "Dang!$"

CeladonCity_GameCorner_Text_GruntPostBattle:: @ 8196E9B
    .string "The Team Rocket Hideout might\n"
    .string "be discovered!\p"
    .string "I better tell Boss!$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt:: @ 8196EDC
    .string "Hey!\p"
    .string "A switch behind the poster!?\n"
    .string "Let's push it!$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired:: @ 8196F0D
    .string "A Coin Case is required…$"

CeladonCity_GameCorner_Text_DontHaveCoinCase:: @ 8196F26
    .string "Oops!\n"
    .string "Don't have the Coin Case!$"

CeladonCity_GameCorner_Text_SlotMachineWantToPlay:: @ 8196F46
    .string "A slot machine!\n"
    .string "Want to play?$"

CeladonCity_GameCorner_Text_OutOfOrder:: @ 8196F64
    .string "Out Of Order\n"
    .string "This is broken.$"

CeladonCity_GameCorner_Text_OutToLunch:: @ 8196F81
    .string "Out To Lunch\n"
    .string "This is reserved.$"

CeladonCity_GameCorner_Text_SomeonesKeys:: @ 8196FA0
    .string "Someone's keys!\n"
    .string "They'll be back.$"

