# 1 "data/maps/SixIsland_WaterPath/scripts.pory"

# 2 "data/maps/SixIsland_WaterPath/scripts.pory"
SixIsland_WaterPath_MapScripts::
# 3 "data/maps/SixIsland_WaterPath/scripts.pory"
	.byte 0
# 4 "data/maps/SixIsland_WaterPath/scripts.pory"

# 5 "data/maps/SixIsland_WaterPath/scripts.pory"
SixIsland_WaterPath_EventScript_HornWantedSign::
# 6 "data/maps/SixIsland_WaterPath/scripts.pory"
	msgbox SixIsland_WaterPath_Text_WantedUltimateHorn, MSGBOX_SIGN
# 7 "data/maps/SixIsland_WaterPath/scripts.pory"
	end
# 8 "data/maps/SixIsland_WaterPath/scripts.pory"

# 9 "data/maps/SixIsland_WaterPath/scripts.pory"
SixIsland_WaterPath_EventScript_RouteSign::
# 10 "data/maps/SixIsland_WaterPath/scripts.pory"
	msgbox SixIsland_WaterPath_Text_RouteSign, MSGBOX_SIGN
# 11 "data/maps/SixIsland_WaterPath/scripts.pory"
	end
