Text_18B896:: @ 818B896
    .string "I let a pleasant breeze lead me\n"
    .string "all the way here.$"

Text_18B8C8:: @ 818B8C8
    .string "Giggle… You're so cute when you're\n"
    .string "determined.$"

Text_18B8F7:: @ 818B8F7
    .string "I want to go to the woods over\n"
    .string "there, but…\p"
    .string "There are lots of BUG POKéMON.\n"
    .string "They scare me a little.$"

Text_18B959:: @ 818B959
    .string "I'm practicing in secret so no one\n"
    .string "can see me.$"

Text_18B988:: @ 818B988
    .string "Nobody saw me losing, right?$"

Text_18B9A5:: @ 818B9A5
    .string "As a performer, I don't want people\n"
    .string "to know about the effort I put in.$"

Text_18B9EC:: @ 818B9EC
    .string "What, you're suggesting that you're\n"
    .string "sick of seeing SWIMMERS like me?\p"
    .string "Aww, don't be hatin'!$"

Text_18BA47:: @ 818BA47
    .string "Oh, no, no, no.$"

Text_18BA57:: @ 818BA57
    .string "I couldn't lift the stigma of being\n"
    .string "a SWIMMER…$"

Text_18BA86:: @ 818BA86
    .string "My boyfriend's always busy, so I\n"
    .string "come swimming by myself.$"

Text_18BAC0:: @ 818BAC0
    .string "Awww, I knew this would happen!$"

Text_18BAE0:: @ 818BAE0
    .string "When I can't be with my boyfriend,\n"
    .string "I spend time with the POKéMON he\l"
    .string "gave me.$"

Text_18BB2D:: @ 818BB2D
    .string "Tell me, where are the mountains\n"
    .string "around these parts?$"

Text_18BB62:: @ 818BB62
    .string "I lost my way while I was busy\n"
    .string "battling!$"

Text_18BB8B:: @ 818BB8B
    .string "Aren't there any mountains around\n"
    .string "these parts?$"

Text_18BBBA:: @ 818BBBA
    .string "MIU: Hello, POKéMON!\n"
    .string "It's time to play!$"

Text_18BBE2:: @ 818BBE2
    .string "MIU: Oh, no!\n"
    .string "Mommy!$"

Text_18BBF6:: @ 818BBF6
    .string "MIU: It makes me all sad inside\n"
    .string "when we lose…$"

Text_18BC24:: @ 818BC24
    .string "MIU: MIA and I are TWINS.\n"
    .string "We want to battle together.$"

Text_18BC5A:: @ 818BC5A
    .string "MIA: Hello, POKéMON!\n"
    .string "It's time to battle!$"

Text_18BC84:: @ 818BC84
    .string "MIA: You're mean!\n"
    .string "You're bad for winning!$"

Text_18BCAE:: @ 818BCAE
    .string "MIA: Ohh…\n"
    .string "I'm sorry, my POKéMON…$"

Text_18BCCF:: @ 818BCCF
    .string "MIA: Oh, you only have one\n"
    .string "POKéMON?\p"
    .string "Don't you feel lonesome?$"

gUnknown_818BD0C:: @ 818BD0C
    .string "Wanted!\n"
    .string "The Ultimate Horn!$"

gUnknown_818BD27:: @ 818BD27
    .string "WATER PATH\n"
    .string "Leads to RUIN VALLEY$"

