Text_177C47:: @ 8177C47
    .string "The SAFARI ZONE's huge, wouldn't\n"
    .string "you say?\p"
    .string "FUCHSIA's GYM LEADER, KOGA, \n"
    .string "patrols the grounds every so often.\p"
    .string "Thanks to him, we can play here\n"
    .string "knowing that we're safe.$"

gUnknown_8177CEB:: @ 8177CEB
    .string "Tossing ROCKS at POKéMON might\n"
    .string "make them run, but they'll be\l"
    .string "easier to catch.$"

gUnknown_8177D39:: @ 8177D39
    .string "Using BAIT will make POKéMON more\n"
    .string "likely to stick around if they get\l"
    .string "busy eating.$"

gUnknown_8177D8B:: @ 8177D8B
    .string "I hiked a lot, but I didn't see any\n"
    .string "POKéMON I wanted.$"

