# 1 "data/maps/FiveIsland_House2/scripts.pory"

# 2 "data/maps/FiveIsland_House2/scripts.pory"
FiveIsland_House2_MapScripts::
# 3 "data/maps/FiveIsland_House2/scripts.pory"
	.byte 0
# 4 "data/maps/FiveIsland_House2/scripts.pory"

# 5 "data/maps/FiveIsland_House2/scripts.pory"
FiveIsland_House2_EventScript_OldMan::
# 6 "data/maps/FiveIsland_House2/scripts.pory"
	msgbox FiveIsland_House2_Text_MeadowBelongedToFamily, MSGBOX_NPC
# 7 "data/maps/FiveIsland_House2/scripts.pory"
	end
