OneIsland_KindleRoad_EmberSpa_EventObjects:
	object_event 1, 32, 0, 11, 0, 13, 0, 3, 8, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EmberSpa_EventScript_16535C, 0, 0, 0
	object_event 2, 30, 0, 15, 0, 11, 0, 3, 18, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EmberSpa_EventScript_165365, 0, 0, 0
	object_event 3, 54, 0, 6, 0, 8, 0, 3, 5, 18, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EmberSpa_EventScript_165380, 157, 0, 0
	object_event 4, 35, 0, 20, 0, 7, 0, 3, 8, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EmberSpa_EventScript_165377, 0, 0, 0
	object_event 5, 32, 0, 10, 0, 5, 0, 3, 8, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EmberSpa_EventScript_165399, 0, 0, 0
	object_event 6, 30, 0, 11, 0, 20, 0, 3, 5, 17, 0, 0, 0, 0, 0, OneIsland_KindleRoad_EmberSpa_EventScript_16536E, 0, 0, 0

OneIsland_KindleRoad_EmberSpa_MapWarps:
	warp_def 13, 36, 3, 2, 813

OneIsland_KindleRoad_EmberSpa_MapCoordEvents:
	coord_event 13, 13, 3, 0, 16385, 0, 0, OneIsland_KindleRoad_EmberSpa_EventScript_1653CF

OneIsland_KindleRoad_EmberSpa_MapEvents::
	map_events OneIsland_KindleRoad_EmberSpa_EventObjects, OneIsland_KindleRoad_EmberSpa_MapWarps, OneIsland_KindleRoad_EmberSpa_MapCoordEvents, 0x0
