MtEmber_RubyPath_B4F_MapScripts:: @ 81638EB
	.byte 0

MtEmber_RubyPath_B4F_EventScript_1638EC:: @ 81638EC
	lockall
	braillemessage gUnknown_81A929F
	waitbuttonpress
	releaseall
	end

MtEmber_RubyPath_B4F_EventScript_1638F5:: @ 81638F5
	lockall
	braillemessage gUnknown_81A92A3
	waitbuttonpress
	releaseall
	end

MtEmber_RubyPath_B4F_EventScript_1638FE:: @ 81638FE
	lockall
	braillemessage gUnknown_81A92A7
	waitbuttonpress
	releaseall
	end

MtEmber_RubyPath_B4F_EventScript_163907:: @ 8163907
	lockall
	braillemessage gUnknown_81A92AB
	waitbuttonpress
	releaseall
	end

MtEmber_RubyPath_B4F_EventScript_163910:: @ 8163910
	lockall
	braillemessage gUnknown_81A92AF
	waitbuttonpress
	releaseall
	end

MtEmber_RubyPath_B4F_EventScript_163919:: @ 8163919
	lockall
	braillemessage gUnknown_81A92B3
	waitbuttonpress
	releaseall
	end

MtEmber_RubyPath_B4F_EventScript_163922:: @ 8163922
	lockall
	braillemessage gUnknown_81A92B7
	waitbuttonpress
	releaseall
	end

MtEmber_RubyPath_B4F_EventScript_16392B:: @ 816392B
	lockall
	braillemessage gUnknown_81A92BC
	waitbuttonpress
	releaseall
	end

MtEmber_RubyPath_B4F_EventScript_163934:: @ 8163934
	lockall
	braillemessage gUnknown_81A92C1
	waitbuttonpress
	releaseall
	end

MtEmber_RubyPath_B4F_EventScript_16393D:: @ 816393D
	lockall
	braillemessage gUnknown_81A92C3
	waitbuttonpress
	releaseall
	end
