SilphCo_6F_Text_RocketsTookOverBuilding:: @ 8175F24
    .string "The ROCKETS came and took over\n"
    .string "the building!$"

SilphCo_6F_Text_BetterGetBackToWork:: @ 8175F51
    .string "Well, better get back to work.$"

SilphCo_6F_Text_HelpMePlease:: @ 8175F70
    .string "Oh dear, oh dear.\n"
    .string "Help me, please!$"

SilphCo_6F_Text_WeGotEngaged:: @ 8175F93
    .string "We got engaged.\n"
    .string "Heheh!$"

SilphCo_6F_Text_ThatManIsSuchACoward:: @ 8175FAA
    .string "That man next to me…\n"
    .string "He's such a coward!$"

SilphCo_6F_Text_NeedsMeToLookAfterHim:: @ 8175FD3
    .string "He's so helpless, he needed\n"
    .string "someone like me to look after him.$"

SilphCo_6F_Text_RocketsTryingToConquerWorld:: @ 8176012
    .string "TEAM ROCKET is trying to conquer\n"
    .string "the world with POKéMON.$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou:: @ 817604B
    .string "TEAM ROCKET ran away, and it's all\n"
    .string "because of you!$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts:: @ 817607E
    .string "They must have targeted SILPH for\n"
    .string "our POKéMON products.$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder:: @ 81760B6
    .string "Come work for SILPH when you\n"
    .string "get older.$"

SilphCo_6F_Text_Grunt1Intro:: @ 81760DE
    .string "I am one of the four ROCKET\n"
    .string "BROTHERS!$"

SilphCo_6F_Text_Grunt1Defeat:: @ 8176104
    .string "Flame out!$"

SilphCo_6F_Text_Grunt1PostBattle:: @ 817610F
    .string "No matter!\n"
    .string "My brothers will avenge me!$"

SilphCo_6F_Text_TaylorIntro:: @ 8176136
    .string "That rotten PRESIDENT!\p"
    .string "Serves him right for shipping me\n"
    .string "off to the TIKSI BRANCH!\p"
    .string "That's why TEAM ROCKET came after\n"
    .string "us, I'm sure of it!$"

SilphCo_6F_Text_TaylorDefeat:: @ 81761BD
    .string "Shoot!$"

SilphCo_6F_Text_TaylorPostBattle:: @ 81761C4
    .string "TIKSI BRANCH?\n"
    .string "It's in Russian no-man's-land!$"

SilphCo_6F_Text_Grunt2Intro:: @ 81761F1
    .string "You dare betray TEAM ROCKET?$"

SilphCo_6F_Text_Grunt2Defeat:: @ 817620E
    .string "You traitor!$"

SilphCo_6F_Text_Grunt2PostBattle:: @ 817621B
    .string "If you stand for justice, you\n"
    .string "betray us bad guys!$"

SilphCo_6F_Text_FloorSign:: @ 817624D
    .string "SILPH CO. HEAD OFFICE\n"
    .string "6F$"

