UndergroundPath_EastWestTunnel_MapWarps:
	warp_def 76, 3, 3, 3, 291
	warp_def 3, 4, 3, 3, 289

UndergroundPath_EastWestTunnel_MapBGEvents:
	bg_event 7, 3, 3, 7, 0, 13, 77, 1
	bg_event 17, 5, 3, 7, 0, 18, 79, 1
	bg_event 31, 4, 3, 7, 0, 17, 80, 1
	bg_event 45, 3, 3, 7, 0, 15, 81, 1
	bg_event 70, 3, 3, 7, 0, 16, 82, 1
	bg_event 55, 2, 3, 7, 0, 34, 83, 1
	bg_event 62, 5, 3, 7, 0, 14, 78, 1

UndergroundPath_EastWestTunnel_MapEvents::
	map_events 0x0, UndergroundPath_EastWestTunnel_MapWarps, 0x0, UndergroundPath_EastWestTunnel_MapBGEvents
