ThreeIsland_House2_EventObjects:
	object_event 1, 26, 0, 4, 0, 4, 0, 3, 10, 17, 0, 0, 0, 0, 0, ThreeIsland_House2_EventScript_1718F9, 0, 0, 0
	object_event 2, 25, 0, 7, 0, 4, 0, 3, 9, 17, 0, 0, 0, 0, 0, ThreeIsland_House2_EventScript_1718E0, 0, 0, 0

ThreeIsland_House2_MapWarps:
	warp_def 4, 7, 3, 3, 782

ThreeIsland_House2_MapEvents::
	map_events ThreeIsland_House2_EventObjects, ThreeIsland_House2_MapWarps, 0x0, 0x0
