VermilionCity_PokemonCenter_2F_MapScripts:: @ 816B457
    map_script 2, VermilionCity_PokemonCenter_2F_MapScript1_1BB2A3
    map_script 4, VermilionCity_PokemonCenter_2F_MapScript2_1BB1ED
    map_script 1, VermilionCity_PokemonCenter_2F_MapScript3_1BB237
    map_script 3, VermilionCity_PokemonCenter_2F_MapScript4_1BB1B4
    .byte 0

VermilionCity_PokemonCenter_2F_EventScript_16B46C:: @ 816B46C
    call EventScript_1BB4A3
    end

EventScript_16B472:: @ 816B472
    call EventScript_1BB6AB
    end

EventScript_16B478:: @ 816B478
    call EventScript_1BB7DE
    end
