SixIsland_DottedHole_B3F_MapWarps:
	warp_def 6, 7, 3, 4, 373
	warp_def 6, 1, 3, 3, 371
	warp_def 11, 5, 3, 0, 375
	warp_def 6, 9, 3, 3, 371
	warp_def 1, 5, 3, 3, 371

SixIsland_DottedHole_B3F_MapBGEvents:
	bg_event 6, 5, 0, 1, 0, SixIsland_DottedHole_B3F_EventScript_16419E

SixIsland_DottedHole_B3F_MapEvents::
	map_events 0x0, SixIsland_DottedHole_B3F_MapWarps, 0x0, SixIsland_DottedHole_B3F_MapBGEvents
