FuchsiaCity_PokemonCenter_1F_EventObjects:
	object_event 1, 64, 0, 7, 0, 2, 0, 3, 8, 17, 0, 0, 0, 0, 0, FuchsiaCity_PokemonCenter_1F_EventScript_16D700, 0, 0, 0
	object_event 2, 25, 0, 12, 0, 5, 0, 3, 8, 17, 0, 0, 0, 0, 0, FuchsiaCity_PokemonCenter_1F_EventScript_16D709, 0, 0, 0
	object_event 3, 42, 0, 13, 0, 3, 0, 3, 7, 17, 0, 0, 0, 0, 0, FuchsiaCity_PokemonCenter_1F_EventScript_16D712, 0, 0, 0
	object_event 4, 18, 0, 4, 0, 8, 0, 3, 5, 17, 0, 0, 0, 0, 0, FuchsiaCity_PokemonCenter_1F_EventScript_16D71B, 0, 0, 0

FuchsiaCity_PokemonCenter_1F_MapWarps:
	warp_def 6, 8, 3, 6, 775
	warp_def 7, 8, 3, 6, 775
	warp_def 8, 8, 3, 6, 775
	warp_def 1, 6, 4, 0, 2822

FuchsiaCity_PokemonCenter_1F_MapEvents::
	map_events FuchsiaCity_PokemonCenter_1F_EventObjects, FuchsiaCity_PokemonCenter_1F_MapWarps, 0x0, 0x0
