gUnknown_8191FFB:: @ 8191FFB
    .string "That BILL!\p"
    .string "I heard that he'll do whatever it\n"
    .string "takes to get rare POKéMON.\p"
    .string "He's not above doing all sorts\n"
    .string "of things, I've heard.$"

gUnknown_8192079:: @ 8192079
    .string "Have you heard about BILL?\p"
    .string "Everyone calls him a POKéMANIAC!\p"
    .string "I think people are just jealous of\n"
    .string "BILL, though.\p"
    .string "Who wouldn't want to boast about\n"
    .string "their POKéMON?$"

gUnknown_8192116:: @ 8192116
    .string "BILL has lots of POKéMON!\n"
    .string "He collects rare ones, too!$"

gUnknown_819214C:: @ 819214C
    .string "Why don't you go upstairs and try\n"
    .string "trading POKéMON with your friends?\p"
    .string "You could get a lot more variety\n"
    .string "by trading.\p"
    .string "The POKéMON you get in trades grow\n"
    .string "quickly, too.$"

