CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
.string "¡Ese {SHADOW DYNAMIC_COLOR4}BILL{SHADOW LIGHT_GRAY}!\p"
.string "Escuché que hará lo que sea\n"
.string "para conseguir {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} raros.\p"
.string "Dicen que no se detiene ante\n"
.string "nada para lograrlo.$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac::
.string "¿Has oído sobre {SHADOW DYNAMIC_COLOR4}BILL{SHADOW LIGHT_GRAY}?\p"
.string "¡Todos lo llaman un {SHADOW DYNAMIC_COLOR4}POKéMANÍACO{SHADOW LIGHT_GRAY}!\p"
.string "Creo que la gente solo tiene envidia\n"
.string "de {SHADOW DYNAMIC_COLOR4}BILL{SHADOW LIGHT_GRAY}.\p"
.string "¿Quién no querría presumir de sus\n"
.string "{SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}?$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
.string "{SHADOW DYNAMIC_COLOR4}BILL{SHADOW LIGHT_GRAY} tiene muchos {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}!\n"
.string "¡También colecciona los raros!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
.string "¿Por qué no subes y intercambiar\n"
.string "{SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} con tus amigos?\p"
.string "Podrías obtener mucha más variedad\n"
.string "intercambiando.\p"
.string "Los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} que recibes en\n"
.string "intercambios también crecen rápido.$"

