gUnknown_8181003:: @ 8181003
    .string "What do you want?\n"
    .string "Get lost!$"

gUnknown_818101F:: @ 818101F
    .string "BOSS said he'll take this town\n"
    .string "in the name of TEAM ROCKET!$"

gUnknown_818105A:: @ 818105A
    .string "Don't get defiant!\n"
    .string "Or I'll have to hurt you!$"

gUnknown_8181087:: @ 8181087
    .string "SAFFRON belongs to TEAM ROCKET!$"

gUnknown_81810A7:: @ 81810A7
    .string "My life as a criminal makes me feel\n"
    .string "so alive!$"

gUnknown_81810D5:: @ 81810D5
    .string "Ow!\n"
    .string "Watch where you're walking!$"

gUnknown_81810F5:: @ 81810F5
    .string "With SILPH under control, we can\n"
    .string "exploit POKéMON around the world!\p"
    .string "We'll get stinking rich, yeahah!$"

gUnknown_8181159:: @ 8181159
    .string "You beat TEAM ROCKET all alone?\n"
    .string "That's amazing!$"

gUnknown_8181189:: @ 8181189
    .string "Yeah! TEAM ROCKET is gone!\n"
    .string "It's safe to go out again!$"

gUnknown_81811BF:: @ 81811BF
    .string "People fled from here in droves\n"
    .string "when those ROCKETS came.\p"
    .string "They should be flocking back to\n"
    .string "SAFFRON now.$"

gUnknown_8181225:: @ 8181225
    .string "I flew here on my PIDGEOT when\n"
    .string "I read about SILPH.\p"
    .string "It's already over?\n"
    .string "I missed the media action…$"

gUnknown_8181286:: @ 8181286
    .string "PIDGEOT: Bi bibii!$"

gUnknown_8181299:: @ 8181299
    .string "I saw the ROCKET BOSS escaping\n"
    .string "SILPH's building.$"

gUnknown_81812CA:: @ 81812CA
    .string "I'm a security guard.\p"
    .string "Suspicious kids I don't allow in!$"

gUnknown_8181302:: @ 8181302
    .string "…\n"
    .string "Snore…\p"
    .string "Hah! He's taking a snooze!$"

gUnknown_8181326:: @ 8181326
    .string "SAFFRON CITY\n"
    .string "Shining, Golden Land of Commerce$"

gUnknown_8181354:: @ 8181354
    .string "FIGHTING DOJO$"

gUnknown_8181362:: @ 8181362
    .string "SAFFRON CITY POKéMON GYM\n"
    .string "LEADER: SABRINA\l"
    .string "The Master of PSYCHIC POKéMON!$"

gUnknown_81813AA:: @ 81813AA
    .string "TRAINER TIPS\p"
    .string "FULL HEAL cures all ailments like\n"
    .string "burns, paralysis, poisoning,\l"
    .string "freezing, and sleep.\p"
    .string "It costs a bit more, but it's more\n"
    .string "convenient than buying other items.$"

gUnknown_8181452:: @ 8181452
    .string "TRAINER TIPS\p"
    .string "The new GREAT BALL offers improved\n"
    .string "catching rates.\p"
    .string "Try it on those hard-to-catch\n"
    .string "POKéMON.$"

gUnknown_81814B9:: @ 81814B9
    .string "SILPH CO. OFFICE BUILDING$"

gUnknown_81814D3:: @ 81814D3
    .string "MR. PSYCHIC'S HOUSE$"

gUnknown_81814E7:: @ 81814E7
    .string "SILPH's latest product!\n"
    .string "Release to be determined…$"

gUnknown_8181519:: @ 8181519
    .string "POKéMON TRAINER FAN CLUB\p"
    .string "Many TRAINERS have scribbled their\n"
    .string "names on this sign.$"

