TwoIsland_PokemonCenter_1F_EventObjects:
	object_event 1, 64, 0, 7, 0, 2, 0, 3, 8, 17, 0, 0, 0, 0, 0, TwoIsland_PokemonCenter_1F_EventScript_1717C3, 0, 0, 0
	object_event 2, 51, 0, 11, 0, 5, 0, 3, 8, 17, 0, 0, 0, 0, 0, TwoIsland_PokemonCenter_1F_EventScript_1717CC, 0, 0, 0
	object_event 3, 20, 0, 4, 0, 4, 0, 3, 5, 17, 0, 0, 0, 0, 0, TwoIsland_PokemonCenter_1F_EventScript_1717D5, 0, 0, 0

TwoIsland_PokemonCenter_1F_MapWarps:
	warp_def 7, 8, 3, 2, 781
	warp_def 1, 6, 4, 0, 8451

TwoIsland_PokemonCenter_1F_MapEvents::
	map_events TwoIsland_PokemonCenter_1F_EventObjects, TwoIsland_PokemonCenter_1F_MapWarps, 0x0, 0x0
