@ Flavor text for interacting with various background objects

gUnknown_81A7606:: @ 81A7606
	msgbox gUnknown_81C0DB0, MSGBOX_SIGN
	end

gUnknown_81A760F:: @ 81A760F
	msgbox gUnknown_81C0DFD, MSGBOX_SIGN
	end

gUnknown_81A7618:: @ 81A7618
	msgbox gUnknown_81C0F99, MSGBOX_SIGN
	end

gUnknown_81A7621:: @ 81A7621
	msgbox gUnknown_81C12A7, MSGBOX_SIGN
	end

gUnknown_81A762A:: @ 81A762A
	msgbox gUnknown_81C10C1, MSGBOX_SIGN
	end

gUnknown_81A7633:: @ 81A7633
	msgbox gUnknown_81C1273, MSGBOX_SIGN
	end

gUnknown_81A763C:: @ 81A763C
	msgbox gUnknown_81C0FD8, MSGBOX_SIGN
	end

gUnknown_81A7645:: @ 81A7645
	msgbox gUnknown_81C12D6, MSGBOX_SIGN
	end

gUnknown_81A764E:: @ 81A764E
	msgbox gUnknown_81C1300, MSGBOX_SIGN
	end

gUnknown_81A7657:: @ 81A7657
	msgbox Text_DishesPlatesNeatlyLinedUp, MSGBOX_SIGN
	end

gUnknown_81A7660:: @ 81A7660
	msgbox gUnknown_81C0E40, MSGBOX_SIGN
	end

gUnknown_81A7669:: @ 81A7669
	msgbox gUnknown_81C0E73, MSGBOX_SIGN
	end

gUnknown_81A7672:: @ 81A7672
	msgbox gUnknown_81C0EAC, MSGBOX_SIGN
	end

gUnknown_81A767B:: @ 81A767B
	msgbox gUnknown_81C101B, MSGBOX_SIGN
	end

gUnknown_81A7684:: @ 81A7684
	msgbox gUnknown_81C1060, MSGBOX_SIGN
	end

gUnknown_81A768D:: @ 81A768D
	msgbox gUnknown_81C109C, MSGBOX_SIGN
	end

gUnknown_81A7696:: @ 81A7696
	msgbox gUnknown_81C10FC, MSGBOX_SIGN
	end

gUnknown_81A769F:: @ 81A769F
	msgbox gUnknown_81C1134, MSGBOX_SIGN
	end

gUnknown_81A76A8:: @ 81A76A8
	msgbox gUnknown_81C116E, MSGBOX_SIGN
	end

gUnknown_81A76B1:: @ 81A76B1
	msgbox gUnknown_81C1194, MSGBOX_SIGN
	end

gUnknown_81A76BA:: @ 81A76BA
	msgbox gUnknown_81C11BA, MSGBOX_SIGN
	end

gUnknown_81A76C3:: @ 81A76C3
	msgbox gUnknown_81C11DC, MSGBOX_SIGN
	end

gUnknown_81A76CC:: @ 81A76CC
	msgbox gUnknown_81C1217, MSGBOX_SIGN
	end

gUnknown_81A76D5:: @ 81A76D5
	msgbox gUnknown_81C124B, MSGBOX_SIGN
	end

gUnknown_81A76DE:: @ 81A76DE
	msgbox gUnknown_81C0ECB, MSGBOX_SIGN
	end

gUnknown_81A76E7:: @ 81A76E7
	msgbox gUnknown_81C0EF7, MSGBOX_SIGN
	end

gUnknown_81A76F0:: @ 81A76F0
	msgbox gUnknown_81C0F19, MSGBOX_SIGN
	end

gUnknown_81A76F9:: @ 81A76F9
	msgbox gUnknown_81C0F59, MSGBOX_SIGN
	end
