@ Flavor text for interacting with various background objects

EventScript_Bookshelf:: @ 81A7606
	msgbox Text_Bookshelf, MSGBOX_SIGN
	end

EventScript_PokeMartShelf:: @ 81A760F
	msgbox Text_PokeMartShelf, MSGBOX_SIGN
	end

EventScript_Food:: @ 81A7618
	msgbox Text_Food, MSGBOX_SIGN
	end

EventScript_VideoGame:: @ 81A7621
	msgbox Text_VideoGame, MSGBOX_SIGN
	end

EventScript_Computer:: @ 81A762A
	msgbox Text_Computer, MSGBOX_SIGN
	end

EventScript_ImpressiveMachine:: @ 81A7633
	msgbox Text_ImpressiveMachine, MSGBOX_SIGN
	end

EventScript_Blueprints:: @ 81A763C
	msgbox Text_Blueprints, MSGBOX_SIGN
	end

EventScript_Burglary:: @ 81A7645
	msgbox Text_Burglary, MSGBOX_SIGN
	end

EventScript_PlayerFacingTVScreen:: @ 81A764E
	msgbox Text_PlayerFacingTVScreen, MSGBOX_SIGN
	end

EventScript_Cabinet:: @ 81A7657
	msgbox Text_DishesPlatesNeatlyLinedUp, MSGBOX_SIGN
	end

EventScript_Kitchen:: @ 81A7660
	msgbox Text_Kitchen, MSGBOX_SIGN
	end

EventScript_Dresser:: @ 81A7669
	msgbox Text_Dresser, MSGBOX_SIGN
	end

EventScript_Snacks:: @ 81A7672
	msgbox Text_Snacks, MSGBOX_SIGN
	end

EventScript_Painting:: @ 81A767B
	msgbox Text_Painting, MSGBOX_SIGN
	end

EventScript_PowerPlantMachine:: @ 81A7684
	msgbox Text_PowerPlantMachine, MSGBOX_SIGN
	end

EventScript_Telephone:: @ 81A768D
	msgbox Text_Telephone, MSGBOX_SIGN
	end

EventScript_AdvertisingPoster:: @ 81A7696
	msgbox Text_AdvertisingPoster, MSGBOX_SIGN
	end

EventScript_TastyFood:: @ 81A769F
	msgbox Text_TastyFood, MSGBOX_SIGN
	end

EventScript_TrashBin:: @ 81A76A8
	msgbox Text_TrashBin, MSGBOX_SIGN
	end

EventScript_Cup:: @ 81A76B1
	msgbox Text_Cup, MSGBOX_SIGN
	end

EventScript_PolishedWindow:: @ 81A76BA
	msgbox Text_PolishedWindow, MSGBOX_SIGN
	end

EventScript_BeautifulSkyWindow:: @ 81A76C3
	msgbox Text_BeautifulSkyWindow, MSGBOX_SIGN
	end

EventScript_BlinkingLights:: @ 81A76CC
	msgbox Text_BlinkingLights, MSGBOX_SIGN
	end

EventScript_NeatlyLinedUpTools:: @ 81A76D5
	msgbox Text_NeatlyLinedUpTools, MSGBOX_SIGN
	end

EventScript_PokemartSign:: @ 81A76DE
	msgbox Text_PokemartSign, MSGBOX_SIGN
	end

EventScript_PokecenterSign:: @ 81A76E7
	msgbox Text_PokecenterSign, MSGBOX_SIGN
	end

EventScript_Indigo_UltimateGoal:: @ 81A76F0
	msgbox Text_Indigo_UltimateGoal, MSGBOX_SIGN
	end

EventScript_Indigo_HighestAuthority:: @ 81A76F9
	msgbox Text_Indigo_HighestAuthority, MSGBOX_SIGN
	end
