@ Flavor text for interacting with various background objects

EventScript_Bookshelf::
	msgbox Text_Bookshelf, MSGBOX_SIGN
	end

EventScript_PokeMartShelf::
	msgbox Text_PokeMartShelf, MSGBOX_SIGN
	end

EventScript_Food::
	msgbox Text_Food, MSGBOX_SIGN
	end

EventScript_VideoGame::
	msgbox Text_VideoGame, MSGBOX_SIGN
	end

EventScript_Computer::
	msgbox Text_Computer, MSGBOX_SIGN
	end

EventScript_ImpressiveMachine::
	msgbox Text_ImpressiveMachine, MSGBOX_SIGN
	end

EventScript_Blueprints::
	msgbox Text_Blueprints, MSGBOX_SIGN
	end

EventScript_Burglary::
	msgbox Text_Burglary, MSGBOX_SIGN
	end

EventScript_PlayerFacingTVScreen::
	msgbox Text_PlayerFacingTVScreen, MSGBOX_SIGN
	end

EventScript_Cabinet::
	msgbox Text_DishesPlatesNeatlyLinedUp, MSGBOX_SIGN
	end

EventScript_Kitchen::
	msgbox Text_Kitchen, MSGBOX_SIGN
	end

EventScript_Dresser::
	msgbox Text_Dresser, MSGBOX_SIGN
	end

EventScript_Snacks::
	msgbox Text_Snacks, MSGBOX_SIGN
	end

EventScript_Painting::
	msgbox Text_Painting, MSGBOX_SIGN
	end

EventScript_PowerPlantMachine::
	msgbox Text_PowerPlantMachine, MSGBOX_SIGN
	end

EventScript_Telephone::
	msgbox Text_Telephone, MSGBOX_SIGN
	end

EventScript_AdvertisingPoster::
	msgbox Text_AdvertisingPoster, MSGBOX_SIGN
	end

EventScript_TastyFood::
	msgbox Text_TastyFood, MSGBOX_SIGN
	end

EventScript_TrashBin::
	msgbox Text_TrashBin, MSGBOX_SIGN
	end

EventScript_Cup::
	msgbox Text_Cup, MSGBOX_SIGN
	end

EventScript_PolishedWindow::
	msgbox Text_PolishedWindow, MSGBOX_SIGN
	end

EventScript_BeautifulSkyWindow::
	msgbox Text_BeautifulSkyWindow, MSGBOX_SIGN
	end

EventScript_BlinkingLights::
	msgbox Text_BlinkingLights, MSGBOX_SIGN
	end

EventScript_NeatlyLinedUpTools::
	msgbox Text_NeatlyLinedUpTools, MSGBOX_SIGN
	end

EventScript_PokemartSign::
	msgbox Text_PokemartSign, MSGBOX_SIGN
	end

EventScript_PokecenterSign::
	msgbox Text_PokecenterSign, MSGBOX_SIGN
	end

EventScript_Indigo_UltimateGoal::
	msgbox Text_Indigo_UltimateGoal, MSGBOX_SIGN
	end

EventScript_Indigo_HighestAuthority::
	msgbox Text_Indigo_HighestAuthority, MSGBOX_SIGN
	end
