Route2_EventScript_1BE58E:: @ 81BE58E
	giveitem ITEM_ETHER, 1, 1
	end

Route2_EventScript_1BE59B:: @ 81BE59B
	giveitem ITEM_PARALYZE_HEAL, 1, 1
	end

ViridianForest_EventScript_1BE5A8:: @ 81BE5A8
	giveitem ITEM_POKE_BALL, 1, 1
	end

ViridianForest_EventScript_1BE5B5:: @ 81BE5B5
	giveitem ITEM_ANTIDOTE, 1, 1
	end

ViridianForest_EventScript_1BE5C2:: @ 81BE5C2
	giveitem ITEM_POTION, 1, 1
	end

MtMoon_1F_EventScript_1BE5CF:: @ 81BE5CF
	giveitem ITEM_PARALYZE_HEAL, 1, 1
	end

MtMoon_1F_EventScript_1BE5DC:: @ 81BE5DC
	giveitem ITEM_TM09, 1, 1
	end

MtMoon_1F_EventScript_1BE5E9:: @ 81BE5E9
	giveitem ITEM_POTION, 1, 1
	end

MtMoon_1F_EventScript_1BE5F6:: @ 81BE5F6
	giveitem ITEM_RARE_CANDY, 1, 1
	end

MtMoon_1F_EventScript_1BE603:: @ 81BE603
	giveitem ITEM_ESCAPE_ROPE, 1, 1
	end

MtMoon_1F_EventScript_1BE610:: @ 81BE610
	giveitem ITEM_MOON_STONE, 1, 1
	end

MtMoon_B2F_EventScript_1BE61D:: @ 81BE61D
	giveitem ITEM_STAR_PIECE, 1, 1
	end

MtMoon_B2F_EventScript_1BE62A:: @ 81BE62A
	giveitem ITEM_TM46, 1, 1
	end

Route4_EventScript_1BE637:: @ 81BE637
	giveitem ITEM_TM05, 1, 1
	end

Route24_EventScript_1BE644:: @ 81BE644
	giveitem ITEM_TM45, 1, 1
	end

Route25_EventScript_1BE651:: @ 81BE651
	giveitem ITEM_TM43, 1, 1
	end

SSAnne_1F_Room2_EventScript_1BE65E:: @ 81BE65E
	giveitem ITEM_TM31, 1, 1
	end

SSAnne_2F_Room2_EventScript_1BE66B:: @ 81BE66B
	giveitem ITEM_STARDUST, 1, 1
	end

SSAnne_2F_Room4_EventScript_1BE678:: @ 81BE678
	giveitem ITEM_X_ATTACK, 1, 1
	end

SSAnne_B1F_Room2_EventScript_1BE685:: @ 81BE685
	giveitem ITEM_TM44, 1, 1
	end

SSAnne_B1F_Room3_EventScript_1BE692:: @ 81BE692
	giveitem ITEM_ETHER, 1, 1
	end

SSAnne_B1F_Room5_EventScript_1BE69F:: @ 81BE69F
	giveitem ITEM_SUPER_POTION, 1, 1
	end

SSAnne_Kitchen_EventScript_1BE6AC:: @ 81BE6AC
	giveitem ITEM_GREAT_BALL, 1, 1
	end

Route9_EventScript_1BE6B9:: @ 81BE6B9
	giveitem ITEM_TM40, 1, 1
	end

RocketHideout_B1F_EventScript_1BE6C6:: @ 81BE6C6
	giveitem ITEM_ESCAPE_ROPE, 1, 1
	end

RocketHideout_B1F_EventScript_1BE6D3:: @ 81BE6D3
	giveitem ITEM_HYPER_POTION, 1, 1
	end

RocketHideout_B2F_EventScript_1BE6E0:: @ 81BE6E0
	giveitem ITEM_X_SPEED, 1, 1
	end

RocketHideout_B2F_EventScript_1BE6ED:: @ 81BE6ED
	giveitem ITEM_MOON_STONE, 1, 1
	end

RocketHideout_B2F_EventScript_1BE6FA:: @ 81BE6FA
	giveitem ITEM_TM12, 1, 1
	end

RocketHideout_B2F_EventScript_1BE707:: @ 81BE707
	giveitem ITEM_SUPER_POTION, 1, 1
	end

RocketHideout_B3F_EventScript_1BE714:: @ 81BE714
	giveitem ITEM_RARE_CANDY, 1, 1
	end

RocketHideout_B3F_EventScript_1BE721:: @ 81BE721
	giveitem ITEM_TM21, 1, 1
	end

RocketHideout_B4F_EventScript_1BE72E:: @ 81BE72E
	giveitem ITEM_TM49, 1, 1
	end

RocketHideout_B4F_EventScript_1BE73B:: @ 81BE73B
	giveitem ITEM_MAX_ETHER, 1, 1
	end

RocketHideout_B4F_EventScript_1BE748:: @ 81BE748
	giveitem ITEM_CALCIUM, 1, 1
	end

PokemonTower_3F_EventScript_1BE755:: @ 81BE755
	giveitem ITEM_ESCAPE_ROPE, 1, 1
	end

PokemonTower_4F_EventScript_1BE762:: @ 81BE762
	giveitem ITEM_ELIXIR, 1, 1
	end

PokemonTower_4F_EventScript_1BE76F:: @ 81BE76F
	giveitem ITEM_AWAKENING, 1, 1
	end

PokemonTower_4F_EventScript_1BE77C:: @ 81BE77C
	giveitem ITEM_GREAT_BALL, 1, 1
	end

PokemonTower_5F_EventScript_1BE789:: @ 81BE789
	giveitem ITEM_NUGGET, 1, 1
	end

PokemonTower_6F_EventScript_1BE796:: @ 81BE796
	giveitem ITEM_RARE_CANDY, 1, 1
	end

PokemonTower_6F_EventScript_1BE7A3:: @ 81BE7A3
	giveitem ITEM_X_ACCURACY, 1, 1
	end

Route12_EventScript_1BE7B0:: @ 81BE7B0
	giveitem ITEM_TM48, 1, 1
	end

Route12_EventScript_1BE7BD:: @ 81BE7BD
	giveitem ITEM_IRON, 1, 1
	end

Route15_EventScript_1BE7CA:: @ 81BE7CA
	giveitem ITEM_TM18, 1, 1
	end

SafariZone_Center_EventScript_1BE7D7:: @ 81BE7D7
	giveitem ITEM_NUGGET, 1, 1
	end

SafariZone_East_EventScript_1BE7E4:: @ 81BE7E4
	giveitem ITEM_MAX_POTION, 1, 1
	end

SafariZone_East_EventScript_1BE7F1:: @ 81BE7F1
	giveitem ITEM_FULL_RESTORE, 1, 1
	end

SafariZone_East_EventScript_1BE7FE:: @ 81BE7FE
	giveitem ITEM_TM11, 1, 1
	end

SafariZone_East_EventScript_1BE80B:: @ 81BE80B
	giveitem ITEM_LEAF_STONE, 1, 1
	end

SafariZone_North_EventScript_1BE818:: @ 81BE818
	giveitem ITEM_PROTEIN, 1, 1
	end

SafariZone_North_EventScript_1BE825:: @ 81BE825
	giveitem ITEM_TM47, 1, 1
	end

SafariZone_West_EventScript_1BE832:: @ 81BE832
	giveitem ITEM_TM32, 1, 1
	end

SafariZone_West_EventScript_1BE83F:: @ 81BE83F
	giveitem ITEM_GOLD_TEETH, 1, 1
	end

SafariZone_West_EventScript_1BE84C:: @ 81BE84C
	giveitem ITEM_MAX_POTION, 1, 1
	end

SafariZone_West_EventScript_1BE859:: @ 81BE859
	giveitem ITEM_MAX_REVIVE, 1, 1
	end

SilphCo_3F_EventScript_1BE866:: @ 81BE866
	giveitem ITEM_HYPER_POTION, 1, 1
	end

SilphCo_4F_EventScript_1BE873:: @ 81BE873
	giveitem ITEM_MAX_REVIVE, 1, 1
	end

SilphCo_4F_EventScript_1BE880:: @ 81BE880
	giveitem ITEM_ESCAPE_ROPE, 1, 1
	end

SilphCo_4F_EventScript_1BE88D:: @ 81BE88D
	giveitem ITEM_FULL_HEAL, 1, 1
	end

SilphCo_5F_EventScript_1BE89A:: @ 81BE89A
	giveitem ITEM_PROTEIN, 1, 1
	end

SilphCo_5F_EventScript_1BE8A7:: @ 81BE8A7
	giveitem ITEM_TM01, 1, 1
	end

SilphCo_5F_EventScript_1BE8B4:: @ 81BE8B4
	giveitem ITEM_CARD_KEY, 1, 1
	end

SilphCo_6F_EventScript_1BE8C1:: @ 81BE8C1
	giveitem ITEM_HP_UP, 1, 1
	end

SilphCo_6F_EventScript_1BE8CE:: @ 81BE8CE
	giveitem ITEM_X_SPECIAL, 1, 1
	end

SilphCo_7F_EventScript_1BE8DB:: @ 81BE8DB
	giveitem ITEM_CALCIUM, 1, 1
	end

SilphCo_7F_EventScript_1BE8E8:: @ 81BE8E8
	giveitem ITEM_TM08, 1, 1
	end

SilphCo_10F_EventScript_1BE8F5:: @ 81BE8F5
	giveitem ITEM_CARBOS, 1, 1
	end

SilphCo_10F_EventScript_1BE902:: @ 81BE902
	giveitem ITEM_ULTRA_BALL, 1, 1
	end

SilphCo_10F_EventScript_1BE90F:: @ 81BE90F
	giveitem ITEM_RARE_CANDY, 1, 1
	end

PowerPlant_EventScript_1BE91C:: @ 81BE91C
	giveitem ITEM_MAX_POTION, 1, 1
	end

PowerPlant_EventScript_1BE929:: @ 81BE929
	giveitem ITEM_TM17, 1, 1
	end

PowerPlant_EventScript_1BE936:: @ 81BE936
	giveitem ITEM_TM25, 1, 1
	end

PowerPlant_EventScript_1BE943:: @ 81BE943
	giveitem ITEM_THUNDER_STONE, 1, 1
	end

PowerPlant_EventScript_1BE950:: @ 81BE950
	giveitem ITEM_ELIXIR, 1, 1
	end

PokemonMansion_1F_EventScript_1BE95D:: @ 81BE95D
	giveitem ITEM_CARBOS, 1, 1
	end

PokemonMansion_1F_EventScript_1BE96A:: @ 81BE96A
	giveitem ITEM_ESCAPE_ROPE, 1, 1
	end

PokemonMansion_2F_EventScript_1BE977:: @ 81BE977
	giveitem ITEM_CALCIUM, 1, 1
	end

PokemonMansion_3F_EventScript_1BE984:: @ 81BE984
	giveitem ITEM_MAX_POTION, 1, 1
	end

PokemonMansion_3F_EventScript_1BE991:: @ 81BE991
	giveitem ITEM_IRON, 1, 1
	end

PokemonMansion_B1F_EventScript_1BE99E:: @ 81BE99E
	giveitem ITEM_TM14, 1, 1
	end

PokemonMansion_B1F_EventScript_1BE9AB:: @ 81BE9AB
	giveitem ITEM_FULL_RESTORE, 1, 1
	end

PokemonMansion_B1F_EventScript_1BE9B8:: @ 81BE9B8
	giveitem ITEM_TM22, 1, 1
	end

PokemonMansion_B1F_EventScript_1BE9C5:: @ 81BE9C5
	giveitem ITEM_SECRET_KEY, 1, 1
	end

VictoryRoad_1F_EventScript_1BE9D2:: @ 81BE9D2
	giveitem ITEM_RARE_CANDY, 1, 1
	end

VictoryRoad_1F_EventScript_1BE9DF:: @ 81BE9DF
	giveitem ITEM_TM02, 1, 1
	end

VictoryRoad_2F_EventScript_1BE9EC:: @ 81BE9EC
	giveitem ITEM_GUARD_SPEC, 1, 1
	end

VictoryRoad_2F_EventScript_1BE9F9:: @ 81BE9F9
	giveitem ITEM_TM07, 1, 1
	end

VictoryRoad_2F_EventScript_1BEA06:: @ 81BEA06
	giveitem ITEM_FULL_HEAL, 1, 1
	end

VictoryRoad_2F_EventScript_1BEA13:: @ 81BEA13
	giveitem ITEM_TM37, 1, 1
	end

VictoryRoad_3F_EventScript_1BEA20:: @ 81BEA20
	giveitem ITEM_MAX_REVIVE, 1, 1
	end

VictoryRoad_3F_EventScript_1BEA2D:: @ 81BEA2D
	giveitem ITEM_TM50, 1, 1
	end

CeruleanCave_1F_EventScript_1BEA3A:: @ 81BEA3A
	giveitem ITEM_MAX_ELIXIR, 1, 1
	end

CeruleanCave_1F_EventScript_1BEA47:: @ 81BEA47
	giveitem ITEM_NUGGET, 1, 1
	end

CeruleanCave_1F_EventScript_1BEA54:: @ 81BEA54
	giveitem ITEM_FULL_RESTORE, 1, 1
	end

CeruleanCave_2F_EventScript_1BEA61:: @ 81BEA61
	giveitem ITEM_FULL_RESTORE, 1, 1
	end

CeruleanCave_2F_EventScript_1BEA6E:: @ 81BEA6E
	giveitem ITEM_PP_UP, 1, 1
	end

CeruleanCave_2F_EventScript_1BEA7B:: @ 81BEA7B
	giveitem ITEM_ULTRA_BALL, 1, 1
	end

CeruleanCave_B1F_EventScript_1BEA88:: @ 81BEA88
	giveitem ITEM_MAX_REVIVE, 1, 1
	end

CeruleanCave_B1F_EventScript_1BEA95:: @ 81BEA95
	giveitem ITEM_ULTRA_BALL, 1, 1
	end

FuchsiaCity_Building1_EventScript_1BEAA2:: @ 81BEAA2
	giveitem ITEM_RARE_CANDY, 1, 1
	end

TwoIsland_EventScript_1BEAAF:: @ 81BEAAF
	giveitem ITEM_REVIVE, 1, 1
	end

ThreeIsland_EventScript_1BEABC:: @ 81BEABC
	giveitem ITEM_ZINC, 1, 1
	end

ViridianForest_EventScript_1BEAC9:: @ 81BEAC9
	giveitem ITEM_POTION, 1, 1
	end

MtMoon_B2F_EventScript_1BEAD6:: @ 81BEAD6
	giveitem ITEM_REVIVE, 1, 1
	end

MtMoon_B2F_EventScript_1BEAE3:: @ 81BEAE3
	giveitem ITEM_ANTIDOTE, 1, 1
	end

Route11_EventScript_1BEAF0:: @ 81BEAF0
	giveitem ITEM_X_DEFEND, 1, 1
	end

Route9_EventScript_1BEAFD:: @ 81BEAFD
	giveitem ITEM_BURN_HEAL, 1, 1
	end

RockTunnel_1F_EventScript_1BEB0A:: @ 81BEB0A
	giveitem ITEM_REPEL, 1, 1
	end

RockTunnel_1F_EventScript_1BEB17:: @ 81BEB17
	giveitem ITEM_PEARL, 1, 1
	end

RockTunnel_1F_EventScript_1BEB24:: @ 81BEB24
	giveitem ITEM_ESCAPE_ROPE, 1, 1
	end

RockTunnel_B1F_EventScript_1BEB31:: @ 81BEB31
	giveitem ITEM_REVIVE, 1, 1
	end

RockTunnel_B1F_EventScript_1BEB3E:: @ 81BEB3E
	giveitem ITEM_MAX_ETHER, 1, 1
	end

SilphCo_8F_EventScript_1BEB4B:: @ 81BEB4B
	giveitem ITEM_IRON, 1, 1
	end

SilphCo_11F_EventScript_1BEB58:: @ 81BEB58
	giveitem ITEM_ZINC, 1, 1
	end

PokemonMansion_1F_EventScript_1BEB65:: @ 81BEB65
	giveitem ITEM_PROTEIN, 1, 1
	end

PokemonMansion_2F_EventScript_1BEB72:: @ 81BEB72
	giveitem ITEM_ZINC, 1, 1
	end

PokemonMansion_2F_EventScript_1BEB7F:: @ 81BEB7F
	giveitem ITEM_HP_UP, 1, 1
	end

ViridianCity_EventScript_1BEB8C:: @ 81BEB8C
	giveitem ITEM_POTION, 1, 1
	end

Route11_EventScript_1BEB99:: @ 81BEB99
	giveitem ITEM_GREAT_BALL, 1, 1
	end

Route11_EventScript_1BEBA6:: @ 81BEBA6
	giveitem ITEM_AWAKENING, 1, 1
	end

PokemonTower_5F_EventScript_1BEBB3:: @ 81BEBB3
	giveitem ITEM_CLEANSE_TAG, 1, 1
	end

CeladonCity_EventScript_1BEBC0:: @ 81BEBC0
	giveitem ITEM_ETHER, 1, 1
	end

RocketHideout_B3F_EventScript_1BEBCD:: @ 81BEBCD
	giveitem ITEM_BLACK_GLASSES, 1, 1
	end

SafariZone_North_EventScript_1BEBDA:: @ 81BEBDA
	giveitem ITEM_QUICK_CLAW, 1, 1
	end

SeafoamIslands_1F_EventScript_1BEBE7:: @ 81BEBE7
	giveitem ITEM_ICE_HEAL, 1, 1
	end

SeafoamIslands_B1F_EventScript_1BEBF4:: @ 81BEBF4
	giveitem ITEM_WATER_STONE, 1, 1
	end

SeafoamIslands_B1F_EventScript_1BEC01:: @ 81BEC01
	giveitem ITEM_REVIVE, 1, 1
	end

SeafoamIslands_B2F_EventScript_1BEC0E:: @ 81BEC0E
	giveitem ITEM_BIG_PEARL, 1, 1
	end

SeafoamIslands_B4F_EventScript_1BEC1B:: @ 81BEC1B
	giveitem ITEM_ULTRA_BALL, 1, 1
	end

FourIsland_EventScript_1BEC28:: @ 81BEC28
	giveitem ITEM_STAR_PIECE, 1, 1
	end

FourIsland_EventScript_1BEC35:: @ 81BEC35
	giveitem ITEM_STARDUST, 1, 1
	end

OneIsland_KindleRoad_EventScript_1BEC42:: @ 81BEC42
	giveitem ITEM_ETHER, 1, 1
	end

OneIsland_KindleRoad_EventScript_1BEC4F:: @ 81BEC4F
	giveitem ITEM_MAX_REPEL, 1, 1
	end

OneIsland_KindleRoad_EventScript_1BEC5C:: @ 81BEC5C
	giveitem ITEM_CARBOS, 1, 1
	end

FiveIsland_Meadow_EventScript_1BEC69:: @ 81BEC69
	giveitem ITEM_MAX_POTION, 1, 1
	end

FiveIsland_Meadow_EventScript_1BEC76:: @ 81BEC76
	giveitem ITEM_PP_UP, 1, 1
	end

FiveIsland_MemorialPillar_EventScript_1BEC83:: @ 81BEC83
	giveitem ITEM_METAL_COAT, 1, 1
	end

SixIsland_OutcastIsland_EventScript_1BEC90:: @ 81BEC90
	giveitem ITEM_PP_UP, 1, 1
	end

SixIsland_WaterPath_EventScript_1BEC9D:: @ 81BEC9D
	giveitem ITEM_ELIXIR, 1, 1
	end

SixIsland_WaterPath_EventScript_1BECAA:: @ 81BECAA
	giveitem ITEM_DRAGON_SCALE, 1, 1
	end

SixIsland_RuinValley_EventScript_1BECB7:: @ 81BECB7
	giveitem ITEM_FULL_RESTORE, 1, 1
	end

SixIsland_RuinValley_EventScript_1BECC4:: @ 81BECC4
	giveitem ITEM_HP_UP, 1, 1
	end

SixIsland_RuinValley_EventScript_1BECD1:: @ 81BECD1
	giveitem ITEM_SUN_STONE, 1, 1
	end

SevenIsland_SevaultCanyon_EventScript_1BECDE:: @ 81BECDE
	giveitem ITEM_KINGS_ROCK, 1, 1
	end

SevenIsland_SevaultCanyon_EventScript_1BECEB:: @ 81BECEB
	giveitem ITEM_MAX_ELIXIR, 1, 1
	end

SevenIsland_SevaultCanyon_EventScript_1BECF8:: @ 81BECF8
	giveitem ITEM_NUGGET, 1, 1
	end

ThreeIsland_BerryForest_EventScript_1BED05:: @ 81BED05
	giveitem ITEM_MAX_ETHER, 1, 1
	end

ThreeIsland_BerryForest_EventScript_1BED12:: @ 81BED12
	giveitem ITEM_FULL_HEAL, 1, 1
	end

ThreeIsland_BerryForest_EventScript_1BED1F:: @ 81BED1F
	giveitem ITEM_MAX_ELIXIR, 1, 1
	end

MtEmber_Exterior_EventScript_1BED2C:: @ 81BED2C
	giveitem ITEM_ULTRA_BALL, 1, 1
	end

MtEmber_Exterior_EventScript_1BED39:: @ 81BED39
	giveitem ITEM_FIRE_STONE, 1, 1
	end

MtEmber_Exterior_EventScript_1BED46:: @ 81BED46
	giveitem ITEM_DIRE_HIT, 1, 1
	end

FourIsland_IcefallCave_1F_EventScript_1BED53:: @ 81BED53
	giveitem ITEM_ULTRA_BALL, 1, 1
	end

FourIsland_IcefallCave_1F_EventScript_1BED60:: @ 81BED60
	giveitem ITEM_HM07, 1, 1
	end

FourIsland_IcefallCave_B1F_EventScript_1BED6D:: @ 81BED6D
	giveitem ITEM_FULL_RESTORE, 1, 1
	end

FourIsland_IcefallCave_B1F_EventScript_1BED7A:: @ 81BED7A
	giveitem ITEM_NEVER_MELT_ICE, 1, 1
	end

FiveIsland_RocketWarehouse_EventScript_1BED87:: @ 81BED87
	giveitem ITEM_BIG_PEARL, 1, 1
	end

FiveIsland_RocketWarehouse_EventScript_1BED94:: @ 81BED94
	giveitem ITEM_TM36, 1, 1
	end

FiveIsland_RocketWarehouse_EventScript_1BEDA1:: @ 81BEDA1
	giveitem ITEM_PEARL, 1, 1
	end

FiveIsland_RocketWarehouse_EventScript_1BEDAE:: @ 81BEDAE
	giveitem ITEM_UP_GRADE, 1, 1
	end

FiveIsland_LostCave_Room10_EventScript_1BEDBB:: @ 81BEDBB
	giveitem ITEM_SILK_SCARF, 1, 1
	end

FiveIsland_LostCave_Room11_EventScript_1BEDC8:: @ 81BEDC8
	giveitem ITEM_LAX_INCENSE, 1, 1
	end

FiveIsland_LostCave_Room12_EventScript_1BEDD5:: @ 81BEDD5
	giveitem ITEM_SEA_INCENSE, 1, 1
	end

FiveIsland_LostCave_Room13_EventScript_1BEDE2:: @ 81BEDE2
	giveitem ITEM_MAX_REVIVE, 1, 1
	end

FiveIsland_LostCave_Room14_EventScript_1BEDEF:: @ 81BEDEF
	giveitem ITEM_RARE_CANDY, 1, 1
	end

SevenIsland_SevaultCanyon_House_EventScript_1BEDFC:: @ 81BEDFC
	giveitem ITEM_LUCKY_PUNCH, 1, 1
	end

SilphCo_4F_EventScript_1BEE09:: @ 81BEE09
	giveitem ITEM_TM41, 1, 1
	end
