CeladonCity_EventScript_ItemEther::
  finditem -1
  end

CeruleanCave_1F_EventScript_ItemFullRestore::
  finditem -1
  end

CeruleanCave_1F_EventScript_ItemMaxElixir::
  finditem -2
  end

CeruleanCave_1F_EventScript_ItemNugget::
  finditem -3
  end

CeruleanCave_2F_EventScript_ItemFullRestore::
  finditem -1
  end

CeruleanCave_2F_EventScript_ItemPPUp::
  finditem -2
  end

CeruleanCave_2F_EventScript_ItemUltraBall::
  finditem -3
  end

CeruleanCave_B1F_EventScript_ItemMaxRevive::
  finditem -1
  end

CeruleanCave_B1F_EventScript_ItemUltraBall::
  finditem -2
  end

FiveIsland_LostCave_Room10_EventScript_ItemSilkScarf::
  finditem -1
  end

FiveIsland_LostCave_Room11_EventScript_ItemLaxIncense::
  finditem -1
  end

FiveIsland_LostCave_Room12_EventScript_ItemSeaIncense::
  finditem -1
  end

FiveIsland_LostCave_Room13_EventScript_ItemMaxRevive::
  finditem -1
  end

FiveIsland_LostCave_Room14_EventScript_ItemRareCandy::
  finditem -1
  end

FiveIsland_Meadow_EventScript_ItemMaxPotion::
  finditem -1
  end

FiveIsland_Meadow_EventScript_ItemPPUp::
  finditem -2
  end

FiveIsland_MemorialPillar_EventScript_ItemMetalCoat::
  finditem -1
  end

FiveIsland_RocketWarehouse_EventScript_ItemBigPearl::
  finditem -1
  end

FiveIsland_RocketWarehouse_EventScript_ItemPearl::
  finditem -2
  end

FiveIsland_RocketWarehouse_EventScript_ItemTM36::
  finditem -3
  end

FiveIsland_RocketWarehouse_EventScript_ItemUpGrade::
  finditem -4
  end

FourIsland_EventScript_ItemStardust::
  finditem -1
  end

FourIsland_EventScript_ItemStarPiece::
  finditem -2
  end

FourIsland_IcefallCave_1F_EventScript_ItemHM07::
  finditem ITEM_HM07
  end

FourIsland_IcefallCave_1F_EventScript_ItemUltraBall::
  finditem -2
  end

FourIsland_IcefallCave_B1F_EventScript_ItemFullRestore::
  finditem -1
  end

FourIsland_IcefallCave_B1F_EventScript_ItemNeverMeltIce::
  finditem -2
  end

FuchsiaCity_WardensHouse_EventScript_ItemRareCandy::
  finditem -1
  end

MtEmber_Exterior_EventScript_ItemDireHit::
  finditem -1
  end

MtEmber_Exterior_EventScript_ItemFireStone::
  finditem -2
  end

MtEmber_Exterior_EventScript_ItemUltraBall::
  finditem -3
  end

MtMoon_1F_EventScript_ItemEscapeRope::
  finditem -1
  end

MtMoon_1F_EventScript_ItemMoonStone::
  finditem -2
  end

MtMoon_1F_EventScript_ItemParalyzeHeal::
  finditem -3
  end

MtMoon_1F_EventScript_ItemPotion::
  finditem -4
  end

MtMoon_1F_EventScript_ItemRareCandy::
  finditem -5
  end

MtMoon_1F_EventScript_ItemTM09::
  finditem -6
  end

MtMoon_B2F_EventScript_ItemAntidote::
  finditem -1
  end

MtMoon_B2F_EventScript_ItemRevive::
  finditem -2
  end

MtMoon_B2F_EventScript_ItemStarPiece::
  finditem -3
  end

MtMoon_B2F_EventScript_ItemTM46::
  finditem -4
  end

OneIsland_KindleRoad_EventScript_ItemCarbos::
  finditem -1
  end

OneIsland_KindleRoad_EventScript_ItemEther::
  finditem -2
  end

OneIsland_KindleRoad_EventScript_ItemMaxRepel::
  finditem -3
  end

PokemonMansion_1F_EventScript_ItemCarbos::
  finditem -1
  end

PokemonMansion_1F_EventScript_ItemEscapeRope::
  finditem -2
  end

PokemonMansion_1F_EventScript_ItemProtein::
  finditem -3
  end

PokemonMansion_2F_EventScript_ItemCalcium::
  finditem -1
  end

PokemonMansion_2F_EventScript_ItemHPUp::
  finditem -2
  end

PokemonMansion_2F_EventScript_ItemZinc::
  finditem -3
  end

PokemonMansion_3F_EventScript_ItemIron::
  finditem -1
  end

PokemonMansion_3F_EventScript_ItemMaxPotion::
  finditem -2
  end

PokemonMansion_B1F_EventScript_ItemFullRestore::
  finditem -1
  end

PokemonMansion_B1F_EventScript_ItemSecretKey::
  finditem ITEM_SECRET_KEY
  end

PokemonMansion_B1F_EventScript_ItemTM14::
  finditem -3
  end

PokemonMansion_B1F_EventScript_ItemTM22::
  finditem -4
  end

PokemonTower_3F_EventScript_ItemEscapeRope::
  finditem -1
  end

PokemonTower_4F_EventScript_ItemAwakening::
  finditem -1
  end

PokemonTower_4F_EventScript_ItemElixir::
  finditem -2
  end

PokemonTower_4F_EventScript_ItemGreatBall::
  finditem -3
  end

PokemonTower_5F_EventScript_ItemCleanseTag::
  finditem -1
  end

PokemonTower_5F_EventScript_ItemNugget::
  finditem -2
  end

PokemonTower_6F_EventScript_ItemRareCandy::
  finditem -1
  end

PokemonTower_6F_EventScript_ItemXAccuracy::
  finditem -2
  end

PowerPlant_EventScript_ItemElixir::
  finditem -1
  end

PowerPlant_EventScript_ItemMaxPotion::
  finditem -2
  end

PowerPlant_EventScript_ItemThunderStone::
  finditem -3
  end

PowerPlant_EventScript_ItemTM17::
  finditem -4
  end

PowerPlant_EventScript_ItemTM25::
  finditem -5
  end

RocketHideout_B1F_EventScript_ItemEscapeRope::
  finditem -1
  end

RocketHideout_B1F_EventScript_ItemHyperPotion::
  finditem -2
  end

RocketHideout_B2F_EventScript_ItemMoonStone::
  finditem -1
  end

RocketHideout_B2F_EventScript_ItemSuperPotion::
  finditem -2
  end

RocketHideout_B2F_EventScript_ItemTM12::
  finditem -3
  end

RocketHideout_B2F_EventScript_ItemXSpeed::
  finditem -4
  end

RocketHideout_B3F_EventScript_ItemBlackGlasses::
  finditem -1
  end

RocketHideout_B3F_EventScript_ItemRareCandy::
  finditem -2
  end

RocketHideout_B3F_EventScript_ItemTM21::
  finditem -3
  end

RocketHideout_B4F_EventScript_ItemCalcium::
  finditem -1
  end

RocketHideout_B4F_EventScript_ItemMaxEther::
  finditem -2
  end

RocketHideout_B4F_EventScript_ItemTM49::
  finditem -3
  end

RockTunnel_1F_EventScript_ItemEscapeRope::
  finditem -1
  end

RockTunnel_1F_EventScript_ItemPearl::
  finditem -2
  end

RockTunnel_1F_EventScript_ItemRepel::
  finditem -3
  end

RockTunnel_B1F_EventScript_ItemMaxEther::
  finditem -1
  end

RockTunnel_B1F_EventScript_ItemRevive::
  finditem -2
  end

Route11_EventScript_ItemAwakening::
  finditem -1
  end

Route11_EventScript_ItemGreatBall::
  finditem -2
  end

Route11_EventScript_ItemXDefend::
  finditem -3
  end

Route12_EventScript_ItemIron::
  finditem -1
  end

Route12_EventScript_ItemTM48::
  finditem -2
  end

Route15_EventScript_ItemTM18::
  finditem -1
  end

Route24_EventScript_ItemTM45::
  finditem -1
  end

Route25_EventScript_ItemTM43::
  finditem -1
  end

Route2_EventScript_ItemEther::
  finditem -1
  end

Route2_EventScript_ItemParalyzeHeal::
  finditem -2
  end

Route4_EventScript_ItemTM05::
  finditem -1
  end

Route9_EventScript_ItemBurnHeal::
  finditem -1
  end

Route9_EventScript_ItemTM40::
  finditem -2
  end

SafariZone_Center_EventScript_ItemNugget::
  finditem -1
  end

SafariZone_East_EventScript_ItemFullRestore::
  finditem -1
  end

SafariZone_East_EventScript_ItemLeafStone::
  finditem -2
  end

SafariZone_East_EventScript_ItemMaxPotion::
  finditem -3
  end

SafariZone_East_EventScript_ItemTM11::
  finditem -4
  end

SafariZone_North_EventScript_ItemProtein::
  finditem -1
  end

SafariZone_North_EventScript_ItemQuickClaw::
  finditem -2
  end

SafariZone_North_EventScript_ItemTM47::
  finditem -3
  end

SafariZone_West_EventScript_ItemGoldTeeth::
  finditem ITEM_GOLD_TEETH
  end

SafariZone_West_EventScript_ItemMaxPotion::
  finditem -2
  end

SafariZone_West_EventScript_ItemMaxRevive::
  finditem -3
  end

SafariZone_West_EventScript_ItemTM32::
  finditem -4
  end

SeafoamIslands_1F_EventScript_ItemIceHeal::
  finditem -1
  end

SeafoamIslands_B1F_EventScript_ItemRevive::
  finditem -1
  end

SeafoamIslands_B1F_EventScript_ItemWaterStone::
  finditem -2
  end

SeafoamIslands_B2F_EventScript_ItemBigPearl::
  finditem -1
  end

SeafoamIslands_B4F_EventScript_ItemUltraBall::
  finditem -1
  end

SevenIsland_SevaultCanyon_EventScript_ItemKingsRock::
  finditem -1
  end

SevenIsland_SevaultCanyon_EventScript_ItemMaxElixir::
  finditem -2
  end

SevenIsland_SevaultCanyon_EventScript_ItemNugget::
  finditem -3
  end

SevenIsland_SevaultCanyon_House_EventScript_ItemLuckyPunch::
  finditem -4
  end

SilphCo_10F_EventScript_ItemCarbos::
  finditem -1
  end

SilphCo_10F_EventScript_ItemRareCandy::
  finditem -2
  end

SilphCo_10F_EventScript_ItemUltraBall::
  finditem -3
  end

SilphCo_11F_EventScript_ItemZinc::
  finditem -1
  end

SilphCo_3F_EventScript_ItemHyperPotion::
  finditem -1
  end

SilphCo_4F_EventScript_ItemEscapeRope::
  finditem -1
  end

SilphCo_4F_EventScript_ItemFullHeal::
  finditem -2
  end

SilphCo_4F_EventScript_ItemMaxRevive::
  finditem -3
  end

SilphCo_4F_EventScript_ItemTM41::
  finditem -4
  end

SilphCo_5F_EventScript_ItemCardKey::
  finditem ITEM_CARD_KEY
  end

SilphCo_5F_EventScript_ItemProtein::
  finditem -2
  end

SilphCo_5F_EventScript_ItemTM01::
  finditem -3
  end

SilphCo_6F_EventScript_ItemHPUp::
  finditem -1
  end

SilphCo_6F_EventScript_ItemXSpecial::
  finditem -2
  end

SilphCo_7F_EventScript_ItemCalcium::
  finditem -1
  end

SilphCo_7F_EventScript_ItemTM08::
  finditem -2
  end

SilphCo_8F_EventScript_ItemIron::
  finditem -1
  end

SixIsland_OutcastIsland_EventScript_ItemPPUp::
  finditem -1
  end

SixIsland_RuinValley_EventScript_ItemFullRestore::
  finditem -1
  end

SixIsland_RuinValley_EventScript_ItemHPUp::
  finditem -2
  end

SixIsland_RuinValley_EventScript_ItemSunStone::
  finditem -3
  end

SixIsland_WaterPath_EventScript_ItemDragonScale::
  finditem -1
  end

SixIsland_WaterPath_EventScript_ItemElixir::
  finditem -2
  end

SSAnne_1F_Room2_EventScript_ItemTM31::
  finditem -1
  end

SSAnne_2F_Room2_EventScript_ItemStardust::
  finditem -2
  end

SSAnne_2F_Room4_EventScript_ItemXAttack::
  finditem -3
  end

SSAnne_B1F_Room2_EventScript_ItemTM44::
  finditem -4
  end

SSAnne_B1F_Room3_EventScript_ItemEther::
  finditem -5
  end

SSAnne_B1F_Room5_EventScript_ItemSuperPotion::
  finditem -6
  end

SSAnne_Kitchen_EventScript_ItemGreatBall::
  finditem -1
  end

ThreeIsland_BerryForest_EventScript_ItemFullHeal::
  finditem -1
  end

ThreeIsland_BerryForest_EventScript_ItemMaxElixir::
  finditem -2
  end

ThreeIsland_BerryForest_EventScript_ItemMaxEther::
  finditem -3
  end

ThreeIsland_EventScript_ItemZinc::
  finditem -1
  end

TwoIsland_EventScript_ItemRevive::
  finditem -1
  end

VictoryRoad_1F_EventScript_ItemRareCandy::
  finditem -1
  end

VictoryRoad_1F_EventScript_ItemTM02::
  finditem -2
  end

VictoryRoad_2F_EventScript_ItemFullHeal::
  finditem -1
  end

VictoryRoad_2F_EventScript_ItemGuardSpec::
  finditem -2
  end

VictoryRoad_2F_EventScript_ItemTM07::
  finditem -3
  end

VictoryRoad_2F_EventScript_ItemTM37::
  finditem -4
  end

VictoryRoad_3F_EventScript_ItemMaxRevive::
  finditem -1
  end

VictoryRoad_3F_EventScript_ItemTM50::
  finditem -2
  end

ViridianCity_EventScript_ItemPotion::
  finditem -1
  end

ViridianForest_EventScript_ItemAntidote::
  finditem -1
  end

ViridianForest_EventScript_ItemPokeBall::
  finditem -2
  end

ViridianForest_EventScript_ItemPotion::
  finditem -3
  end

ViridianForest_EventScript_ItemPotion2::
  finditem -4
  end

