CeladonCity_EventScript_ItemEther::
  finditem -28
  end

CeruleanCave_1F_EventScript_ItemFullRestore::
  finditem -29
  end

CeruleanCave_1F_EventScript_ItemMaxElixir::
  finditem -30
  end

CeruleanCave_1F_EventScript_ItemNugget::
  finditem -31
  end

CeruleanCave_2F_EventScript_ItemFullRestore::
  finditem -32
  end

CeruleanCave_2F_EventScript_ItemPPUp::
  finditem -33
  end

CeruleanCave_2F_EventScript_ItemUltraBall::
  finditem -34
  end

CeruleanCave_B1F_EventScript_ItemMaxRevive::
  finditem -35
  end

CeruleanCave_B1F_EventScript_ItemUltraBall::
  finditem -36
  end

FiveIsland_LostCave_Room10_EventScript_ItemSilkScarf::
  finditem -37
  end

FiveIsland_LostCave_Room11_EventScript_ItemLaxIncense::
  finditem -38
  end

FiveIsland_LostCave_Room12_EventScript_ItemSeaIncense::
  finditem -39
  end

FiveIsland_LostCave_Room13_EventScript_ItemMaxRevive::
  finditem -40
  end

FiveIsland_LostCave_Room14_EventScript_ItemRareCandy::
  finditem -41
  end

FiveIsland_Meadow_EventScript_ItemMaxPotion::
  finditem -42
  end

FiveIsland_Meadow_EventScript_ItemPPUp::
  finditem -43
  end

FiveIsland_MemorialPillar_EventScript_ItemMetalCoat::
  finditem -44
  end

FiveIsland_RocketWarehouse_EventScript_ItemBigPearl::
  finditem -45
  end

FiveIsland_RocketWarehouse_EventScript_ItemPearl::
  finditem -46
  end

FiveIsland_RocketWarehouse_EventScript_ItemTM36::
  finditem -47
  end

FiveIsland_RocketWarehouse_EventScript_ItemUpGrade::
  finditem -48
  end

FourIsland_EventScript_ItemStardust::
  finditem -49
  end

FourIsland_EventScript_ItemStarPiece::
  finditem -50
  end

FourIsland_IcefallCave_1F_EventScript_ItemHM07::
  finditem ITEM_HM07
  end

FourIsland_IcefallCave_1F_EventScript_ItemUltraBall::
  finditem -51
  end

FourIsland_IcefallCave_B1F_EventScript_ItemFullRestore::
  finditem -52
  end

FourIsland_IcefallCave_B1F_EventScript_ItemNeverMeltIce::
  finditem -53
  end

FuchsiaCity_WardensHouse_EventScript_ItemRareCandy::
  finditem -54
  end

MtEmber_Exterior_EventScript_ItemDireHit::
  finditem -55
  end

MtEmber_Exterior_EventScript_ItemFireStone::
  finditem -56
  end

MtEmber_Exterior_EventScript_ItemUltraBall::
  finditem -57
  end

MtMoon_1F_EventScript_ItemEscapeRope::
  finditem -58
  end

MtMoon_1F_EventScript_ItemMoonStone::
  finditem -59
  end

MtMoon_1F_EventScript_ItemParalyzeHeal::
  finditem -60
  end

MtMoon_1F_EventScript_ItemPotion::
  finditem -61
  end

MtMoon_1F_EventScript_ItemRareCandy::
  finditem -62
  end

MtMoon_1F_EventScript_ItemTM09::
  finditem -63
  end

MtMoon_B2F_EventScript_ItemAntidote::
  finditem -64
  end

MtMoon_B2F_EventScript_ItemRevive::
  finditem -65
  end

MtMoon_B2F_EventScript_ItemStarPiece::
  finditem -66
  end

MtMoon_B2F_EventScript_ItemTM46::
  finditem -67
  end

OneIsland_KindleRoad_EventScript_ItemCarbos::
  finditem -68
  end

OneIsland_KindleRoad_EventScript_ItemEther::
  finditem -69
  end

OneIsland_KindleRoad_EventScript_ItemMaxRepel::
  finditem -70
  end

PokemonMansion_1F_EventScript_ItemCarbos::
  finditem -71
  end

PokemonMansion_1F_EventScript_ItemEscapeRope::
  finditem -72
  end

PokemonMansion_1F_EventScript_ItemProtein::
  finditem -73
  end

PokemonMansion_2F_EventScript_ItemCalcium::
  finditem -74
  end

PokemonMansion_2F_EventScript_ItemHPUp::
  finditem -75
  end

PokemonMansion_2F_EventScript_ItemZinc::
  finditem -76
  end

PokemonMansion_3F_EventScript_ItemIron::
  finditem -77
  end

PokemonMansion_3F_EventScript_ItemMaxPotion::
  finditem -78
  end

PokemonMansion_B1F_EventScript_ItemFullRestore::
  finditem -79
  end

PokemonMansion_B1F_EventScript_ItemSecretKey::
  finditem ITEM_SECRET_KEY
  end

PokemonMansion_B1F_EventScript_ItemTM14::
  finditem -80
  end

PokemonMansion_B1F_EventScript_ItemTM22::
  finditem -81
  end

PokemonTower_3F_EventScript_ItemEscapeRope::
  finditem -82
  end

PokemonTower_4F_EventScript_ItemAwakening::
  finditem -83
  end

PokemonTower_4F_EventScript_ItemElixir::
  finditem -84
  end

PokemonTower_4F_EventScript_ItemGreatBall::
  finditem -85
  end

PokemonTower_5F_EventScript_ItemCleanseTag::
  finditem -86
  end

PokemonTower_5F_EventScript_ItemNugget::
  finditem -87
  end

PokemonTower_6F_EventScript_ItemRareCandy::
  finditem -88
  end

PokemonTower_6F_EventScript_ItemXAccuracy::
  finditem -89
  end

PowerPlant_EventScript_ItemElixir::
  finditem -90
  end

PowerPlant_EventScript_ItemMaxPotion::
  finditem -91
  end

PowerPlant_EventScript_ItemThunderStone::
  finditem -92
  end

PowerPlant_EventScript_ItemTM17::
  finditem -93
  end

PowerPlant_EventScript_ItemTM25::
  finditem -94
  end

RocketHideout_B1F_EventScript_ItemEscapeRope::
  finditem -95
  end

RocketHideout_B1F_EventScript_ItemHyperPotion::
  finditem -96
  end

RocketHideout_B2F_EventScript_ItemMoonStone::
  finditem -97
  end

RocketHideout_B2F_EventScript_ItemSuperPotion::
  finditem -98
  end

RocketHideout_B2F_EventScript_ItemTM12::
  finditem -99
  end

RocketHideout_B2F_EventScript_ItemXSpeed::
  finditem -100
  end

RocketHideout_B3F_EventScript_ItemBlackGlasses::
  finditem -101
  end

RocketHideout_B3F_EventScript_ItemRareCandy::
  finditem -102
  end

RocketHideout_B3F_EventScript_ItemTM21::
  finditem -103
  end

RocketHideout_B4F_EventScript_ItemCalcium::
  finditem -104
  end

RocketHideout_B4F_EventScript_ItemMaxEther::
  finditem -105
  end

RocketHideout_B4F_EventScript_ItemTM49::
  finditem -106
  end

RockTunnel_1F_EventScript_ItemEscapeRope::
  finditem -107
  end

RockTunnel_1F_EventScript_ItemPearl::
  finditem -108
  end

RockTunnel_1F_EventScript_ItemRepel::
  finditem -109
  end

RockTunnel_B1F_EventScript_ItemMaxEther::
  finditem -110
  end

RockTunnel_B1F_EventScript_ItemRevive::
  finditem -111
  end

Route11_EventScript_ItemAwakening::
  finditem -112
  end

Route11_EventScript_ItemGreatBall::
  finditem -113
  end

Route11_EventScript_ItemXDefend::
  finditem -114
  end

Route12_EventScript_ItemIron::
  finditem -115
  end

Route12_EventScript_ItemTM48::
  finditem -116
  end

Route15_EventScript_ItemTM18::
  finditem -117
  end

Route24_EventScript_ItemTM45::
  finditem -118
  end

Route25_EventScript_ItemTM43::
  finditem -119
  end

Route2_EventScript_ItemEther::
  finditem -120
  end

Route2_EventScript_ItemParalyzeHeal::
  finditem -121
  end

Route4_EventScript_ItemTM05::
  finditem -122
  end

Route9_EventScript_ItemBurnHeal::
  finditem -123
  end

Route9_EventScript_ItemTM40::
  finditem -124
  end

SafariZone_Center_EventScript_ItemNugget::
  finditem -125
  end

SafariZone_East_EventScript_ItemFullRestore::
  finditem -126
  end

SafariZone_East_EventScript_ItemLeafStone::
  finditem -127
  end

SafariZone_East_EventScript_ItemMaxPotion::
  finditem -128
  end

SafariZone_East_EventScript_ItemTM11::
  finditem -129
  end

SafariZone_North_EventScript_ItemProtein::
  finditem -130
  end

SafariZone_North_EventScript_ItemQuickClaw::
  finditem -131
  end

SafariZone_North_EventScript_ItemTM47::
  finditem -132
  end

SafariZone_West_EventScript_ItemGoldTeeth::
  finditem ITEM_GOLD_TEETH
  end

SafariZone_West_EventScript_ItemMaxPotion::
  finditem -133
  end

SafariZone_West_EventScript_ItemMaxRevive::
  finditem -134
  end

SafariZone_West_EventScript_ItemTM32::
  finditem -135
  end

SeafoamIslands_1F_EventScript_ItemIceHeal::
  finditem -136
  end

SeafoamIslands_B1F_EventScript_ItemRevive::
  finditem -137
  end

SeafoamIslands_B1F_EventScript_ItemWaterStone::
  finditem -138
  end

SeafoamIslands_B2F_EventScript_ItemBigPearl::
  finditem -139
  end

SeafoamIslands_B4F_EventScript_ItemUltraBall::
  finditem -140
  end

SevenIsland_SevaultCanyon_EventScript_ItemKingsRock::
  finditem -141
  end

SevenIsland_SevaultCanyon_EventScript_ItemMaxElixir::
  finditem -142
  end

SevenIsland_SevaultCanyon_EventScript_ItemNugget::
  finditem -143
  end

SevenIsland_SevaultCanyon_House_EventScript_ItemLuckyPunch::
  finditem -144
  end

SilphCo_10F_EventScript_ItemCarbos::
  finditem -145
  end

SilphCo_10F_EventScript_ItemRareCandy::
  finditem -146
  end

SilphCo_10F_EventScript_ItemUltraBall::
  finditem -147
  end

SilphCo_11F_EventScript_ItemZinc::
  finditem -148
  end

SilphCo_3F_EventScript_ItemHyperPotion::
  finditem -149
  end

SilphCo_4F_EventScript_ItemEscapeRope::
  finditem -150
  end

SilphCo_4F_EventScript_ItemFullHeal::
  finditem -151
  end

SilphCo_4F_EventScript_ItemMaxRevive::
  finditem -152
  end

SilphCo_4F_EventScript_ItemTM41::
  finditem -153
  end

SilphCo_5F_EventScript_ItemCardKey::
  finditem ITEM_CARD_KEY
  end

SilphCo_5F_EventScript_ItemProtein::
  finditem -154
  end

SilphCo_5F_EventScript_ItemTM01::
  finditem -155
  end

SilphCo_6F_EventScript_ItemHPUp::
  finditem -156
  end

SilphCo_6F_EventScript_ItemXSpecial::
  finditem -157
  end

SilphCo_7F_EventScript_ItemCalcium::
  finditem -158
  end

SilphCo_7F_EventScript_ItemTM08::
  finditem -159
  end

SilphCo_8F_EventScript_ItemIron::
  finditem -160
  end

SixIsland_OutcastIsland_EventScript_ItemPPUp::
  finditem -161
  end

SixIsland_RuinValley_EventScript_ItemFullRestore::
  finditem -162
  end

SixIsland_RuinValley_EventScript_ItemHPUp::
  finditem -163
  end

SixIsland_RuinValley_EventScript_ItemSunStone::
  finditem -164
  end

SixIsland_WaterPath_EventScript_ItemDragonScale::
  finditem -165
  end

SixIsland_WaterPath_EventScript_ItemElixir::
  finditem -166
  end

SSAnne_1F_Room2_EventScript_ItemTM31::
  finditem -167
  end

SSAnne_2F_Room2_EventScript_ItemStardust::
  finditem -168
  end

SSAnne_2F_Room4_EventScript_ItemXAttack::
  finditem -169
  end

SSAnne_B1F_Room2_EventScript_ItemTM44::
  finditem -170
  end

SSAnne_B1F_Room3_EventScript_ItemEther::
  finditem -171
  end

SSAnne_B1F_Room5_EventScript_ItemSuperPotion::
  finditem -172
  end

SSAnne_Kitchen_EventScript_ItemGreatBall::
  finditem -173
  end

ThreeIsland_BerryForest_EventScript_ItemFullHeal::
  finditem -174
  end

ThreeIsland_BerryForest_EventScript_ItemMaxElixir::
  finditem -175
  end

ThreeIsland_BerryForest_EventScript_ItemMaxEther::
  finditem -176
  end

ThreeIsland_EventScript_ItemZinc::
  finditem -177
  end

TwoIsland_EventScript_ItemRevive::
  finditem -178
  end

VictoryRoad_1F_EventScript_ItemRareCandy::
  finditem -179
  end

VictoryRoad_1F_EventScript_ItemTM02::
  finditem -180
  end

VictoryRoad_2F_EventScript_ItemFullHeal::
  finditem -181
  end

VictoryRoad_2F_EventScript_ItemGuardSpec::
  finditem -182
  end

VictoryRoad_2F_EventScript_ItemTM07::
  finditem -183
  end

VictoryRoad_2F_EventScript_ItemTM37::
  finditem -184
  end

VictoryRoad_3F_EventScript_ItemMaxRevive::
  finditem -185
  end

VictoryRoad_3F_EventScript_ItemTM50::
  finditem -186
  end

ViridianCity_EventScript_ItemPotion::
  finditem -187
  end

ViridianForest_EventScript_ItemAntidote::
  finditem -188
  end

ViridianForest_EventScript_ItemPokeBall::
  finditem -189
  end

ViridianForest_EventScript_ItemPotion::
  finditem -190
  end

ViridianForest_EventScript_ItemPotion2::
  finditem -191
  end

