Movement_QuestionMark::
	emote_question_mark
	step_end

Movement_ExclamationMark::
	emote_exclamation_mark
	step_end

Movement_Delay48::
	delay_16
	delay_16
	delay_16
	step_end

Movement_FacePlayer::
	face_player
	step_end

@ Unused
Movement_FaceAwayPlayer::
	face_away_player
	step_end

Movement_FaceOriginalDirection::
	face_original_direction
	step_end

Movement_WalkInPlaceFastestLeft::
	walk_in_place_fastest_left
	step_end

Movement_WalkInPlaceFastestUp::
	walk_in_place_fastest_up
	step_end

Movement_WalkInPlaceFastestRight::
	walk_in_place_fastest_right
	step_end

Movement_WalkInPlaceFastestDown::
	walk_in_place_fastest_down
	step_end

Movement_FaceRight::
	face_right
	step_end

Movement_FaceDown::
	face_down
	step_end

Movement_WalkUp5::
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

@ Unused
Movement_WalkUp4::
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Movement_Delay32::
	delay_16
	delay_16
	step_end

@ Unused
Movement_WalkUp::
	walk_up
	step_end

@ Unused
Movement_WalkUp2::
	walk_up
	walk_up
	step_end
