Movement_QuestionMark:: @ 81A75D9
	emote_question_mark
	step_end

Movement_ExclamationMark:: @ 81A75DB
	emote_exclamation_mark
	step_end

Movement_Delay48:: @ 81A75DD
	delay_16
	delay_16
	delay_16
	step_end

Movement_FacePlayer:: @ 81A75E1
	face_player
	step_end

@ Unused
Movement_FaceAwayPlayer:: @ 81A75E3
	face_away_player
	step_end

Movement_FaceOriginalDirection:: @ 81A75E5
	face_original_direction
	step_end

Movement_WalkInPlaceFastestLeft:: @ 81A75E7
	walk_in_place_fastest_left
	step_end

Movement_WalkInPlaceFastestUp:: @ 81A75E9
	walk_in_place_fastest_up
	step_end

Movement_WalkInPlaceFastestRight:: @ 81A75EB
	walk_in_place_fastest_right
	step_end

Movement_WalkInPlaceFastestDown:: @ 81A75ED
	walk_in_place_fastest_down
	step_end

Movement_FaceRight:: @ 81A75EF
	face_right
	step_end

Movement_FaceDown:: @ 81A75F1
	face_down
	step_end

Movement_WalkUp5:: @ 81A75F3
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

@ Unused
Movement_WalkUp4:: @ 81A75F9
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Movement_Delay32:: @ 81A75FE
	delay_16
	delay_16
	step_end

@ Unused
Movement_WalkUp:: @ 81A7601
	walk_up
	step_end

@ Unused
Movement_WalkUp2:: @ 81A7603
	walk_up
	walk_up
	step_end
