Movement_QuestionMark::
	emote_question_mark
	step_end

Movement_ExclamationMark::
	emote_exclamation_mark
	step_end

Movement_Delay48::
	delay_16
	delay_16
	delay_16
	step_end

Movement_FacePlayer::
	face_player
	step_end

@ Unused
Movement_FaceAwayPlayer::
	face_away_player
	step_end

Movement_FaceOriginalDirection::
	face_original_direction
	step_end

Movement_WalkInPlaceFasterLeft::
	walk_in_place_faster_left
	step_end

Movement_WalkInPlaceFasterUp::
	walk_in_place_faster_up
	step_end

Movement_WalkInPlaceFasterRight::
	walk_in_place_faster_right
	step_end

Movement_WalkInPlaceFasterDown::
	walk_in_place_faster_down
	step_end

Movement_FaceRight::
	face_right
	step_end

Movement_FaceDown::
	face_down
	step_end

Movement_WalkUp5::
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

@ Unused
Movement_WalkUp4::
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Movement_Delay32::
	delay_16
	delay_16
	step_end

@ Unused
Movement_WalkUp::
	walk_up
	step_end

@ Unused
Movement_WalkUp2::
	walk_up
	walk_up
	step_end
