SSAnne_CaptainsOffice2_EventObjects:
	object_event 1, 92, 0, 10, 0, 14, 0, 3, 8, 17, 0, 0, 0, 0, 0, SSAnne_CaptainsOffice2_EventScript_1BED6D, 498, 0, 0
	object_event 2, 92, 0, 21, 0, 7, 0, 3, 8, 17, 0, 0, 0, 0, 0, SSAnne_CaptainsOffice2_EventScript_1BED7A, 499, 0, 0

SSAnne_CaptainsOffice2_MapWarps:
	warp_def 12, 12, 3, 2, 367
	warp_def 12, 3, 3, 3, 367
	warp_def 15, 16, 3, 4, 367

SSAnne_CaptainsOffice2_MapEvents::
	map_events SSAnne_CaptainsOffice2_EventObjects, SSAnne_CaptainsOffice2_MapWarps, 0x0, 0x0
