FiveIsland_ResortGorgeous_House_Text_PleaseHearMyWish::
    .string "SELPHY: Oh?\n"
    .string "Do I know you from somewhere?\p"
    .string "Oh, but that doesn't matter.\p"
    .string "I am exquisitely bored.\n"
    .string "Please, hear my wish.$"

FiveIsland_ResortGorgeous_House_Text_WishToSeeMonPlease::
    .string "I wish to see a POKéMON.\n"
    .string "A darling {STR_VAR_1}.\p"
    .string "I want to see one right away.\n"
    .string "Please, make my wish come true.$"

FiveIsland_ResortGorgeous_House_Text_OhImTiredOfWaiting::
    .string "SELPHY: Oh, I'm tired of this.\n"
    .string "I'm tired of waiting for you.\p"
    .string "I'll forgive you this time, but\n"
    .string "please don't fail me next time.$"

FiveIsland_ResortGorgeous_House_Text_MonYouCaughtForMeThankYou::
    .string "SELPHY: Oh, hello, there.\p"
    .string "Oh, my gracious. That must be the\n"
    .string "{STR_VAR_1} you caught for me.\p"
    .string "Giggle…\n"
    .string "I see a resemblance to you.\p"
    .string "Thank you so kindly.\p"
    .string "… …  … …  … …\n"
    .string "Is something the matter?\p"
    .string "You may leave.\p"
    .string "… …  … …  … …\n"
    .string "Oh, fine. I understand now.\p"
    .string "SEBASTIAN!\n"
    .string "I need you here this instant!$"

FiveIsland_ResortGorgeous_House_Text_ButlerYesMyLady::
    .string "Butler: Yes, my lady.$"

FiveIsland_ResortGorgeous_House_Text_SelphyGiveTokenOfAppreciation::
    .string "SELPHY: See to it that this person\n"
    .string "is given a token of appreciation.$"

FiveIsland_ResortGorgeous_House_Text_ButlerIShallDoAsYouBid::
    .string "Butler: I shall do as you bid,\n"
    .string "my lady.$"

FiveIsland_ResortGorgeous_House_Text_ButlerPleaseAcceptThisAsHerThanks::
    .string "Butler: I sincerely thank you for\n"
    .string "pleasing Lady SELPHY.\p"
    .string "Please accept this as her thanks…$"

FiveIsland_ResortGorgeous_House_Text_ButlerBagAppearsToBeFull::
    .string "Butler: Your BAG appears to be\n"
    .string "unfortunately full.$"

FiveIsland_ResortGorgeous_House_Text_OhHowDisappointing::
    .string "Oh…\n"
    .string "How disappointing.$"

FiveIsland_ResortGorgeous_House_Text_SelphyWishYouBestOfLuck::
    .string "SELPHY: I wish you the best of\n"
    .string "luck.$"

FiveIsland_ResortGorgeous_House_Text_LadySelphySmileHasBrillianceOfSun::
    .string "Butler: The smile of Lady SELPHY\n"
    .string "has the brilliance of the sun.\p"
    .string "Please, I beg you to bring joy\n"
    .string "to Lady SELPHY.$"

