gUnknown_81A42A0:: @ 81A42A0
    .string "SELPHY: Oh?\n"
    .string "Do I know you from somewhere?\p"
    .string "Oh, but that doesn't matter.\p"
    .string "I am exquisitely bored.\n"
    .string "Please, hear my wish.$"

gUnknown_81A4315:: @ 81A4315
    .string "I wish to see a POKéMON.\n"
    .string "A darling {STR_VAR_1}.\p"
    .string "I want to see one right away.\n"
    .string "Please, make my wish come true.$"

gUnknown_81A437A:: @ 81A437A
    .string "SELPHY: Oh, I'm tired of this.\n"
    .string "I'm tired of waiting for you.\p"
    .string "I'll forgive you this time, but\n"
    .string "please don't fail me next time.$"

gUnknown_81A43F7:: @ 81A43F7
    .string "SELPHY: Oh, hello, there.\p"
    .string "Oh, my gracious. That must be the\n"
    .string "{STR_VAR_1} you caught for me.\p"
    .string "Giggle…\n"
    .string "I see a resemblance to you.\p"
    .string "Thank you so kindly.\p"
    .string "… …  … …  … …\n"
    .string "Is something the matter?\p"
    .string "You may leave.\p"
    .string "… …  … …  … …\n"
    .string "Oh, fine. I understand now.\p"
    .string "SEBASTIAN!\n"
    .string "I need you here this instant!$"

gUnknown_81A450B:: @ 81A450B
    .string "Butler: Yes, my lady.$"

gUnknown_81A4521:: @ 81A4521
    .string "SELPHY: See to it that this person\n"
    .string "is given a token of appreciation.$"

gUnknown_81A4566:: @ 81A4566
    .string "Butler: I shall do as you bid,\n"
    .string "my lady.$"

gUnknown_81A458E:: @ 81A458E
    .string "Butler: I sincerely thank you for\n"
    .string "pleasing Lady SELPHY.\p"
    .string "Please accept this as her thanks…$"

gUnknown_81A45E8:: @ 81A45E8
    .string "Butler: Your BAG appears to be\n"
    .string "unfortunately full.$"

gUnknown_81A461B:: @ 81A461B
    .string "Oh…\n"
    .string "How disappointing.$"

gUnknown_81A4632:: @ 81A4632
    .string "SELPHY: I wish you the best of\n"
    .string "luck.$"

gUnknown_81A4657:: @ 81A4657
    .string "Butler: The smile of Lady SELPHY\n"
    .string "has the brilliance of the sun.\p"
    .string "Please, I beg you to bring joy\n"
    .string "to Lady SELPHY.$"

