SixIsland_PokemonCenter_2F_MapScripts:: @ 8171E20
	map_script 2, SixIsland_PokemonCenter_2F_MapScript1_1BB2A3
	map_script 4, SixIsland_PokemonCenter_2F_MapScript2_1BB1ED
	map_script 1, SixIsland_PokemonCenter_2F_MapScript3_1BB237
	map_script 3, SixIsland_PokemonCenter_2F_MapScript4_1BB1B4
	.byte 0

SixIsland_PokemonCenter_2F_EventScript_171E35:: @ 8171E35
	call EventScript_1BB4A3
	end

EventScript_171E3B:: @ 8171E3B
	call EventScript_1BB6AB
	end

EventScript_171E41:: @ 8171E41
	call EventScript_1BB7DE
	end
