Text_186C4D:: @ 8186C4D
    .string "What do you want?$"

Text_186C5F:: @ 8186C5F
    .string "Don't you dare laugh!$"

Text_186C75:: @ 8186C75
    .string "We like just hanging here.\n"
    .string "What's it to you?$"

Text_186CA2:: @ 8186CA2
    .string "Nice BIKE!\n"
    .string "Hand it over!$"

Text_186CBB:: @ 8186CBB
    .string "Knockout!$"

Text_186CC5:: @ 8186CC5
    .string "Forget it, who needs your BIKE!$"

Text_186CE5:: @ 8186CE5
    .string "Come out and play, little mouse!$"

Text_186D06:: @ 8186D06
    .string "You little rat!$"

Text_186D16:: @ 8186D16
    .string "I hate losing!\n"
    .string "Get out of my face!$"

Text_186D39:: @ 8186D39
    .string "Hey, you just bumped me!$"

Text_186D52:: @ 8186D52
    .string "Kaboom!$"

Text_186D5A:: @ 8186D5A
    .string "We'll always be hanging around here\n"
    .string "even if you don't like it.\p"
    .string "You can detour to VERMILION from\n"
    .string "FUCHSIA going along the coast.$"

Text_186DD9:: @ 8186DD9
    .string "I'm feeling hungry and mean!\n"
    .string "I need a punching bag!$"

Text_186E0D:: @ 8186E0D
    .string "Bad, bad, bad!$"

Text_186E1C:: @ 8186E1C
    .string "If I'm going to have POKéMON, they\n"
    .string "may as well be ferocious.\p"
    .string "I'd use them to leave my enemies\n"
    .string "in tatters.$"

Text_186E86:: @ 8186E86
    .string "Hey, there!\n"
    .string "Let's have ourselves a good time!$"

Text_186EB4:: @ 8186EB4
    .string "Don't make me mad!$"

Text_186EC7:: @ 8186EC7
    .string "I get my kicks by harassing people\n"
    .string "with my stinking POKéMON.\p"
    .string "They're great for startling people.\n"
    .string "And, they bite, too.$"

Route16_Text_MonSprawledOutInSlumber:: @ 8186F3D
    .string "A POKéMON is sprawled out in\n"
    .string "a deep and comfortable slumber.$"

Route16_Text_CyclingRoadSign:: @ 8186F7A
    .string "Enjoy the slope!\n"
    .string "CYCLING ROAD$"

Route16_Text_RouteSign:: @ 8186F98
    .string "ROUTE 16\n"
    .string "CELADON CITY - FUCHSIA CITY$"

Text_186FBD:: @ 8186FBD
    .string "JED: Our love knows no bounds.\n"
    .string "We're in love and we show it!$"

Text_186FFA:: @ 8186FFA
    .string "JED: Oh, no!\n"
    .string "My love has seen me as a loser!$"

Text_187027:: @ 8187027
    .string "JED: Listen, LEA.\n"
    .string "You need to focus less on me.$"

Text_187057:: @ 8187057
    .string "JED: You have just one POKéMON?\n"
    .string "Is there no love in your heart?$"

Text_187097:: @ 8187097
    .string "LEA: Sometimes, the intensity of\n"
    .string "our love scares me.$"

Text_1870CC:: @ 81870CC
    .string "LEA: Ohh! But JED looks cool\n"
    .string "even in a loss!$"

Text_1870F9:: @ 81870F9
    .string "LEA: Ehehe, I'm sorry.\n"
    .string "JED is so cool.$"

Text_187120:: @ 8187120
    .string "LEA: Oh, you don't have two\n"
    .string "POKéMON with you?\p"
    .string "Doesn't it feel lonely for you or\n"
    .string "your POKéMON?$"
