Text_186A95:: @ 8186A95
    .string "MYA: You're perfect.\n"
    .string "Help me train my little brother?$"

Text_186ACB:: @ 8186ACB
    .string "MYA: RON, you have to focus!\n"
    .string "Concentrate on what you're doing!$"

Text_186B0A:: @ 8186B0A
    .string "MYA: Okay, we'll turn it up.\n"
    .string "I'll add to our training menu!$"

Text_186B46:: @ 8186B46
    .string "MYA: Do you want to challenge us?\n"
    .string "You'll need two POKéMON, though.$"

Text_186B89:: @ 8186B89
    .string "RON: My sister gets scary when we\n"
    .string "lose.$"

Text_186BB1:: @ 8186BB1
    .string "RON: Oh, no, no…\n"
    .string "Sis, I'm sorry!$"

Text_186BD2:: @ 8186BD2
    .string "RON: Oh, bleah…\n"
    .string "I wish I had a nice sister…$"

Text_186BFE:: @ 8186BFE
    .string "RON: Did you want to battle with\n"
    .string "my sister and me?\p"
    .string "You need two POKéMON, then.$"

Text_186C4D:: @ 8186C4D
    .string "What do you want?$"

Text_186C5F:: @ 8186C5F
    .string "Don't you dare laugh!$"

Text_186C75:: @ 8186C75
    .string "We like just hanging here.\n"
    .string "What's it to you?$"

Text_186CA2:: @ 8186CA2
    .string "Nice BIKE!\n"
    .string "Hand it over!$"

Text_186CBB:: @ 8186CBB
    .string "Knockout!$"

Text_186CC5:: @ 8186CC5
    .string "Forget it, who needs your BIKE!$"

Text_186CE5:: @ 8186CE5
    .string "Come out and play, little mouse!$"

Text_186D06:: @ 8186D06
    .string "You little rat!$"

Text_186D16:: @ 8186D16
    .string "I hate losing!\n"
    .string "Get out of my face!$"

Text_186D39:: @ 8186D39
    .string "Hey, you just bumped me!$"

Text_186D52:: @ 8186D52
    .string "Kaboom!$"

Text_186D5A:: @ 8186D5A
    .string "We'll always be hanging around here\n"
    .string "even if you don't like it.\p"
    .string "You can detour to VERMILION from\n"
    .string "FUCHSIA going along the coast.$"

Text_186DD9:: @ 8186DD9
    .string "I'm feeling hungry and mean!\n"
    .string "I need a punching bag!$"

Text_186E0D:: @ 8186E0D
    .string "Bad, bad, bad!$"

Text_186E1C:: @ 8186E1C
    .string "If I'm going to have POKéMON, they\n"
    .string "may as well be ferocious.\p"
    .string "I'd use them to leave my enemies\n"
    .string "in tatters.$"

Text_186E86:: @ 8186E86
    .string "Hey, there!\n"
    .string "Let's have ourselves a good time!$"

Text_186EB4:: @ 8186EB4
    .string "Don't make me mad!$"

Text_186EC7:: @ 8186EC7
    .string "I get my kicks by harassing people\n"
    .string "with my stinking POKéMON.\p"
    .string "They're great for startling people.\n"
    .string "And, they bite, too.$"

Route16_Text_MonSprawledOutInSlumber:: @ 8186F3D
    .string "A POKéMON is sprawled out in\n"
    .string "a deep and comfortable slumber.$"

Route16_Text_CyclingRoadSign:: @ 8186F7A
    .string "Enjoy the slope!\n"
    .string "CYCLING ROAD$"

Route16_Text_RouteSign:: @ 8186F98
    .string "ROUTE 16\n"
    .string "CELADON CITY - FUCHSIA CITY$"

