Route16_Text_LaoIntro::
    .string "What do you want?$"

Route16_Text_LaoDefeat::
    .string "Don't you dare laugh!$"

Route16_Text_LaoPostBattle::
    .string "We like just hanging here.\n"
    .string "What's it to you?$"

Route16_Text_KojiIntro::
    .string "Nice Bike!\n"
    .string "Hand it over!$"

Route16_Text_KojiDefeat::
    .string "Knockout!$"

Route16_Text_KojiPostBattle::
    .string "Forget it, who needs your Bike!$"

Route16_Text_LukeIntro::
    .string "Come out and play, little mouse!$"

Route16_Text_LukeDefeat::
    .string "You little rat!$"

Route16_Text_LukePostBattle::
    .string "I hate losing!\n"
    .string "Get out of my face!$"

Route16_Text_HideoIntro::
    .string "Hey, you just bumped me!$"

Route16_Text_HideoDefeat::
    .string "Kaboom!$"

Route16_Text_HideoPostBattle::
    .string "We'll always be hanging around here\n"
    .string "even if you don't like it.\p"
    .string "You can detour to Vermilion from\n"
    .string "Fuchsia going along the coast.$"

Route16_Text_CamronIntro::
    .string "I'm feeling hungry and mean!\n"
    .string "I need a punching bag!$"

Route16_Text_CamronDefeat::
    .string "Bad, bad, bad!$"

Route16_Text_CamronPostBattle::
    .string "If I'm going to have Pokémon, they\n"
    .string "may as well be ferocious.\p"
    .string "I'd use them to leave my enemies\n"
    .string "in tatters.$"

Route16_Text_RubenIntro::
    .string "Hey, there!\n"
    .string "Let's have ourselves a good time!$"

Route16_Text_RubenDefeat::
    .string "Don't make me mad!$"

Route16_Text_RubenPostBattle::
    .string "I get my kicks by harassing people\n"
    .string "with my stinking Pokémon.\p"
    .string "They're great for startling people.\n"
    .string "And, they bite, too.$"

Route16_Text_MonSprawledOutInSlumber::
    .string "A Pokémon is sprawled out in\n"
    .string "a deep and comfortable slumber.$"

Route16_Text_CyclingRoadSign::
    .string "Enjoy the slope!\n"
    .string "Cycling Road$"

Route16_Text_RouteSign::
    .string "Route 16\n"
    .string "Celadon City - Fuchsia City$"

Route16_Text_JedIntro::
    .string "Jed: Our love knows no bounds.\n"
    .string "We're in love and we show it!$"

Route16_Text_JedDefeat::
    .string "Jed: Oh, no!\n"
    .string "My love has seen me as a loser!$"

Route16_Text_JedPostBattle::
    .string "Jed: Listen, Lea.\n"
    .string "You need to focus less on me.$"

Route16_Text_JedNotEnoughMons::
    .string "Jed: You have just one Pokémon?\n"
    .string "Is there no love in your heart?$"

Route16_Text_LeaIntro::
    .string "Lea: Sometimes, the intensity of\n"
    .string "our love scares me.$"

Route16_Text_LeaDefeat::
    .string "Lea: Ohh! But Jed looks cool\n"
    .string "even in a loss!$"

Route16_Text_LeaPostBattle::
    .string "Lea: Ehehe, I'm sorry.\n"
    .string "Jed is so cool.$"

Route16_Text_LeaNotEnoughMons::
    .string "Lea: Oh, you don't have two\n"
    .string "Pokémon with you?\p"
    .string "Doesn't it feel lonely for you or\n"
    .string "your Pokémon?$"
