# 1 "data/maps/UndergroundPath_WestEntrance/scripts.pory"

# 2 "data/maps/UndergroundPath_WestEntrance/scripts.pory"
UndergroundPath_WestEntrance_MapScripts::
# 3 "data/maps/UndergroundPath_WestEntrance/scripts.pory"
	.byte 0
# 4 "data/maps/UndergroundPath_WestEntrance/scripts.pory"

# 5 "data/maps/UndergroundPath_WestEntrance/scripts.pory"
UndergroundPath_WestEntrance_EventScript_BaldingMan::
# 6 "data/maps/UndergroundPath_WestEntrance/scripts.pory"
	msgbox UndergroundPath_WestEntrance_Text_SleepyMonNearCeladon, MSGBOX_NPC
# 7 "data/maps/UndergroundPath_WestEntrance/scripts.pory"
	end
