CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
.string "Solo los {SHADOW DYNAMIC_COLOR4}ENTRENADORES{SHADOW LIGHT_GRAY} expertos\n"
.string "pueden reunir {SHADOW DYNAMIC_COLOR4}MEDALLAS POKéMON{SHADOW LIGHT_GRAY}.\p"
.string "Veo que tienes al menos una.\p"
.string "¿Sabías que esas {SHADOW DYNAMIC_COLOR4}MEDALLAS{SHADOW LIGHT_GRAY} guardan\n"
.string "asombrosos secretos?$"

CeruleanCity_House1_Text_DescribeWhichBadge::
.string "Entonces...\p"
.string "¿Cuál de las ocho {SHADOW DYNAMIC_COLOR4}MEDALLAS{SHADOW LIGHT_GRAY} quieres\n"
.string "que describa?$"

CeruleanCity_House1_Text_ComeVisitAnytime::
.string "Ven a visitarme cuando quieras.$"

CeruleanCity_House1_Text_AttackStatFlash::
.string "El {SHADOW DYNAMIC_COLOR4}ATAQUE{SHADOW LIGHT_GRAY} de todos tus\n"
.string "{SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} aumenta un poco.\p"
.string "También te permite usar el movimiento\n"
.string "{SHADOW DYNAMIC_COLOR4}DESTELLO{SHADOW LIGHT_GRAY} fuera de combate.$"

CeruleanCity_House1_Text_ObeyLv30Cut::
.string "Los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} de hasta Nv. 30 te\n"
.string "obedecerán.\p"
.string "Eso incluye a los forasteros que\n"
.string "obtienes en intercambios.\p"
.string "Los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} de niveles más altos\n"
.string "serán rebeldes en combate.\p"
.string "También te permite usar el movimiento\n"
.string "{SHADOW DYNAMIC_COLOR4}CORTE{SHADOW LIGHT_GRAY} fuera de combate.$"

CeruleanCity_House1_Text_SpeedStatFly::
.string "La {SHADOW DYNAMIC_COLOR4}VELOCIDAD{SHADOW LIGHT_GRAY} de todos tus\n"
.string "{SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} aumenta un poco.\p"
.string "También te permite usar el movimiento\n"
.string "{SHADOW DYNAMIC_COLOR4}VUELO{SHADOW LIGHT_GRAY} fuera de combate.$"

CeruleanCity_House1_Text_ObeyLv50Strength::
.string "Los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} de hasta Nv. 50 te\n"
.string "obedecerán.\p"
.string "Eso incluye a los forasteros que\n"
.string "obtienes en intercambios.\p"
.string "Los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} de niveles más altos\n"
.string "serán rebeldes en combate.\p"
.string "También te permite usar el movimiento\n"
.string "{SHADOW DYNAMIC_COLOR4}FUERZA{SHADOW LIGHT_GRAY} fuera de combate.$"

CeruleanCity_House1_Text_DefenseStatSurf::
.string "La {SHADOW DYNAMIC_COLOR4}DEFENSA{SHADOW LIGHT_GRAY} de todos tus\n"
.string "{SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} aumenta un poco.\p"
.string "También te permite usar el movimiento\n"
.string "{SHADOW DYNAMIC_COLOR4}SURF{SHADOW LIGHT_GRAY} fuera de combate.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
.string "Los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} de hasta Nv. 70 te\n"
.string "obedecerán.\p"
.string "Eso incluye a los forasteros que\n"
.string "obtienes en intercambios.\p"
.string "Los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} de niveles más altos\n"
.string "serán rebeldes en combate.\p"
.string "También te permite usar el movimiento\n"
.string "{SHADOW DYNAMIC_COLOR4}GOLPE ROCA{SHADOW LIGHT_GRAY} fuera de combate.$"

CeruleanCity_House1_Text_SpStatsWaterfall::
.string "El {SHADOW DYNAMIC_COLOR4}AT. ESP.{SHADOW LIGHT_GRAY} y la {SHADOW DYNAMIC_COLOR4}DEF. ESP.{SHADOW LIGHT_GRAY} de\n"
.string "todos tus {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} suben un poco.\p"
.string "También te permite usar el movimiento\n"
.string "{SHADOW DYNAMIC_COLOR4}CASCADA{SHADOW LIGHT_GRAY} fuera de combate.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
.string "¡Todos los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} te obedecerán!$"

