CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
.string "Solo los ENTRENADORES expertos pueden\n"
.string "reunir MEDALLAS POKéMON.\p"
.string "Veo que tienes al menos una.\p"
.string "¿Sabías que esas MEDALLAS guardan\n"
.string "asombrosos secretos?$"

CeruleanCity_House1_Text_DescribeWhichBadge::
.string "Entonces…\p"
.string "¿Cuál de las ocho MEDALLAS quieres\n"
.string "que describa?$"

CeruleanCity_House1_Text_ComeVisitAnytime::
.string "Ven a visitarme cuando quieras.$"

CeruleanCity_House1_Text_AttackStatFlash::
.string "El ATAQUE de todos tus\n"
.string "POKéMON aumenta un poco.\p"
.string "También te permite usar el movimiento\n"
.string "DESTELLO fuera de combate.$"

CeruleanCity_House1_Text_ObeyLv30Cut::
.string "Los POKéMON de hasta Nv. 30 te\n"
.string "obedecerán.\p"
.string "Eso incluye a los forasteros que\n"
.string "obtienes en intercambios.\p"
.string "Los POKéMON de niveles más altos\n"
.string "serán rebeldes en combate.\p"
.string "También te permite usar el movimiento\n"
.string "CORTE fuera de combate.$"

CeruleanCity_House1_Text_SpeedStatFly::
.string "La VELOCIDAD de todos tus\n"
.string "POKéMON aumenta un poco.\p"
.string "También te permite usar el movimiento\n"
.string "VUELO fuera de combate.$"

CeruleanCity_House1_Text_ObeyLv50Strength::
.string "Los POKéMON de hasta Nv. 50 te\n"
.string "obedecerán.\p"
.string "Eso incluye a los forasteros que\n"
.string "obtienes en intercambios.\p"
.string "Los POKéMON de niveles más altos\n"
.string "serán rebeldes en combate.\p"
.string "También te permite usar el movimiento\n"
.string "FUERZA fuera de combate.$"

CeruleanCity_House1_Text_DefenseStatSurf::
.string "La DEFENSA de todos tus\n"
.string "POKéMON aumenta un poco.\p"
.string "También te permite usar el movimiento\n"
.string "SURF fuera de combate.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
.string "Los POKéMON de hasta Nv. 70 te\n"
.string "obedecerán.\p"
.string "Eso incluye a los forasteros que\n"
.string "obtienes en intercambios.\p"
.string "Los POKéMON de niveles más altos\n"
.string "serán rebeldes en combate.\p"
.string "También te permite usar el movimiento\n"
.string "GOLPE ROCA fuera de combate.$"

CeruleanCity_House1_Text_SpStatsWaterfall::
.string "El AT. ESP. y la DEF. ESP. de\n"
.string "todos tus POKéMON suben un poco.\p"
.string "También te permite usar el movimiento\n"
.string "CASCADA fuera de combate.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
.string "¡Todos los POKéMON te obedecerán!$"

