ViridianCity_PokemonCenter_1F_EventObjects:
	object_event 1, 64, 0, 7, 0, 2, 0, 3, 8, 17, 0, 0, 0, 0, 0, ViridianCity_PokemonCenter_1F_EventScript_16A2CF, 0, 0, 0
	object_event 2, 61, 0, 12, 0, 5, 0, 3, 8, 17, 0, 0, 0, 0, 0, ViridianCity_PokemonCenter_1F_EventScript_16A2E1, 0, 0, 0
	object_event 3, 19, 0, 4, 0, 7, 0, 3, 1, 17, 0, 0, 0, 0, 0, ViridianCity_PokemonCenter_1F_EventScript_16A2D8, 0, 0, 0
	object_event 4, 18, 0, 2, 0, 3, 0, 3, 2, 17, 0, 0, 0, 0, 0, ViridianCity_PokemonCenter_1F_EventScript_16A2EA, 0, 0, 0

ViridianCity_PokemonCenter_1F_MapWarps:
	warp_def 6, 8, 3, 0, 769
	warp_def 7, 8, 3, 0, 769
	warp_def 8, 8, 3, 0, 769
	warp_def 1, 6, 4, 0, 1285

ViridianCity_PokemonCenter_1F_MapEvents::
	map_events ViridianCity_PokemonCenter_1F_EventObjects, ViridianCity_PokemonCenter_1F_MapWarps, 0x0, 0x0
