ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC:: @ 8190384
    .string "Please feel free to use that PC in\n"
    .string "the corner.\p"
    .string "The receptionist told me so.\n"
    .string "It's so kind of her!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown:: @ 81903E5
    .string "There's a Pokémon Center in every\n"
    .string "town ahead.\p"
    .string "They charge no money, so don't\n"
    .string "be shy about healing Pokémon.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons:: @ 8190450
    .string "Pokémon Centers heal your tired,\n"
    .string "hurt, or fainted Pokémon.\p"
    .string "They make all Pokémon completely\n"
    .string "healthy.$"

