# 1 "data/maps/Route3/scripts.pory"

# 2 "data/maps/Route3/scripts.pory"
Route3_MapScripts::
# 3 "data/maps/Route3/scripts.pory"
	.byte 0
# 4 "data/maps/Route3/scripts.pory"

# 5 "data/maps/Route3/scripts.pory"
Route3_EventScript_Youngster::
# 6 "data/maps/Route3/scripts.pory"
	msgbox Route3_Text_TunnelFromCeruleanTiring, MSGBOX_NPC
# 7 "data/maps/Route3/scripts.pory"
	end
# 8 "data/maps/Route3/scripts.pory"

# 9 "data/maps/Route3/scripts.pory"
Route3_EventScript_RouteSign::
# 10 "data/maps/Route3/scripts.pory"
	msgbox Route3_Text_RouteSign, MSGBOX_SIGN
# 11 "data/maps/Route3/scripts.pory"
	end
