Route3_Text_TunnelFromCeruleanTiring:: @ 8183491
    .string "Whew… I better take a rest…\n"
    .string "Groan…\p"
    .string "That tunnel from CERULEAN takes a\n"
    .string "lot out of you!$"

Route3_Text_ColtonIntro:: @ 81834E6
    .string "Hey!\n"
    .string "I saw you in VIRIDIAN FOREST!$"

Route3_Text_ColtonDefeat:: @ 8183509
    .string "You beat me again!$"

Route3_Text_ColtonPostBattle:: @ 818351C
    .string "There are other kinds of POKéMON\n"
    .string "than the ones you find in forests.$"

Route3_Text_BenIntro:: @ 8183560
    .string "Hi!\n"
    .string "I like shorts!\p"
    .string "They're delightfully comfy and\n"
    .string "easy to wear!$"

Route3_Text_BenDefeat:: @ 81835A0
    .string "I don't believe it!$"

Route3_Text_BenPostBattle:: @ 81835B4
    .string "Are you using a POKéMON CENTER's\n"
    .string "PC for storing your POKéMON?\p"
    .string "Each BOX can hold up to\n"
    .string "30 POKéMON.$"

Route3_Text_JaniceIntro:: @ 8183616
    .string "Excuse me!\n"
    .string "You looked at me, didn't you?$"

Route3_Text_JaniceDefeat:: @ 818363F
    .string "You're mean!$"

Route3_Text_JanicePostBattle:: @ 818364C
    .string "You shouldn't be staring if you\n"
    .string "don't want to battle!$"

Route3_Text_GregIntro:: @ 8183682
    .string "Are you a TRAINER?\n"
    .string "Let's get with it right away!$"

Route3_Text_GregDefeat:: @ 81836B3
    .string "If I had new POKéMON, I would've\n"
    .string "won!$"

Route3_Text_GregPostBattle:: @ 81836D9
    .string "If a POKéMON BOX on the PC gets\n"
    .string "full, just switch to another BOX.$"

Route3_Text_SallyIntro:: @ 818371B
    .string "That look you gave me…\n"
    .string "It's so intriguing!$"

Route3_Text_SallyDefeat:: @ 8183746
    .string "Be nice!$"

Route3_Text_SallyPostBattle:: @ 818374F
    .string "You can avoid battles by not\n"
    .string "letting TRAINERS see you.$"

Route3_Text_CalvinIntro:: @ 8183786
    .string "Hey! You're not wearing shorts!\n"
    .string "What's wrong with you?$"

Route3_Text_CalvinDefeat:: @ 81837BD
    .string "Lost!\n"
    .string "Lost! Lost!$"

Route3_Text_CalvinPostBattle:: @ 81837CF
    .string "I always wear shorts, even in\n"
    .string "winter. That's my policy.$"

Route3_Text_JamesIntro:: @ 8183807
    .string "I'll battle you with the POKéMON\n"
    .string "I just caught.$"

Route3_Text_JamesDefeat:: @ 8183837
    .string "Done like dinner!$"

Route3_Text_JamesPostBattle:: @ 8183849
    .string "Trained POKéMON are stronger than\n"
    .string "the wild ones.$"

Route3_Text_RobinIntro:: @ 818387A
    .string "Eek!\n"
    .string "Did you touch me?$"

Route3_Text_RobinDefeat:: @ 8183891
    .string "That's it?$"

Route3_Text_RobinPostBattle:: @ 818389C
    .string "ROUTE 4 is at the foot of\n"
    .string "MT. MOON.$"

Route3_Text_RouteSign:: @ 81838C0
    .string "ROUTE 3\n"
    .string "MT. MOON AHEAD$"

