Route3_Text_TunnelFromCeruleanTiring::
    .string "Uf... Será mejor que descanse un\n"
     .string "poco...\p"
    .string "¡Ese monte desde {SHADOW DYNAMIC_COLOR4}CIUDAD CELESTE{SHADOW LIGHT_GRAY}\n"
    .string "te deja agotado!$"

Route3_Text_ColtonIntro::
    .string "¡Hey!\n"
    .string "¡Te vi en el {SHADOW DYNAMIC_COLOR4}BOSQUE VERDE{SHADOW LIGHT_GRAY}!$"

Route3_Text_ColtonDefeat::
    .string "¡ME GANASTE OTRA VEZ!$"

Route3_Text_ColtonPostBattle::
    .string "Hay otros tipos de {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} además\n"
    .string "de los que encuentras en bosques.$"

Route3_Text_BenIntro::
    .string "¡Me gustan los pantalones cortos!\p"
    .string "¡Son cómodos y fáciles de usar!$"

Route3_Text_BenDefeat::
    .string "¡NO LO PUEDO CREER!$"

Route3_Text_BenPostBattle::
    .string "¿Estás usando la {SHADOW DYNAMIC_COLOR4}PC del {SHADOW DYNAMIC_COLOR4}CENTRO\n"
    .string "POKéMON{SHADOW LIGHT_GRAY} para guardar tus {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}?\p"
    .string "Cada {SHADOW DYNAMIC_COLOR4}CAJA{SHADOW LIGHT_GRAY} puede contener hasta\n"
    .string "30 {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}.$"

Route3_Text_JaniceIntro::
    .string "¡Disculpa!\n"
    .string "¡Me miraste, ¿verdad?!$"

Route3_Text_JaniceDefeat::
    .string "¡QUÉ INSOLENTE!$"

Route3_Text_JanicePostBattle::
    .string "¡No deberías mirar si no quieres\n"
    .string "pelear!$"

Route3_Text_GregIntro::
    .string "¿Te gusta combatir?\n"
    .string "¡Entonces, a pelear ya mismo!$"

Route3_Text_GregDefeat::
    .string "¡SI TUVIERA NUEVOS POKéMON TE\n"
    .string "HABRÍA GANADO!$"

Route3_Text_GregPostBattle::
    .string "Si una {SHADOW DYNAMIC_COLOR4}CAJA{SHADOW LIGHT_GRAY} de {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} en la {SHADOW DYNAMIC_COLOR4}PC{SHADOW LIGHT_GRAY}\n"
    .string "se llena, solo cambia a otra.$"

Route3_Text_SallyIntro::
    .string "Esa mirada que me diste...\n"
    .string "¡Es tan intrigante!$"

Route3_Text_SallyDefeat::
    .string "¡SÉ AMABLE!$"

Route3_Text_SallyPostBattle::
    .string "Puedes evitar combates si no dejas\n"
    .string "que otros {SHADOW DYNAMIC_COLOR4}ENTRENADORES{SHADOW LIGHT_GRAY} te vean.$"

Route3_Text_CalvinIntro::
    .string "¡Hey! ¡No estás usando shorts!\n"
    .string "¿Qué te pasa?$"

Route3_Text_CalvinDefeat::
    .string "¡PERDÍ!\n"
    .string "¡PERDÍ, PERDÍ!$"

Route3_Text_CalvinPostBattle::
    .string "Siempre uso shorts,\n"
    .string "incluso en invierno. ¡Esa es mi regla!$"

Route3_Text_JamesIntro::
    .string "Voy a luchar con los POKéMON\n"
    .string "que acabo de atrapar.$"

Route3_Text_JamesDefeat::
    .string "ESO FUE MÁS RÁPIDO DE LO QUE PENSABA$"

Route3_Text_JamesPostBattle::
    .string "Los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} entrenados son más\n"
    .string "fuertes que los salvajes.$"

Route3_Text_RobinIntro::
    .string "¡Ay!\n"
    .string "¿Me tocaste?$"

Route3_Text_RobinDefeat::
    .string "¿ESO FUE TODO?$"

Route3_Text_RobinPostBattle::
    .string "La {SHADOW DYNAMIC_COLOR4}RUTA 4{SHADOW LIGHT_GRAY} está al pie del\n"
    .string "{SHADOW DYNAMIC_COLOR4}MONTE LUNAR{SHADOW LIGHT_GRAY}.$"

Route3_Text_RouteSign::
    .string "{SHADOW DYNAMIC_COLOR4}RUTA 3{SHADOW LIGHT_GRAY}\n"
    .string "MONTE MOON ADELANTE$"
