Route3_Text_TunnelFromCeruleanTiring::
    .string "Whew… I better take a rest…\n"
    .string "Groan…\p"
    .string "That tunnel from Cerulean takes a\n"
    .string "lot out of you!$"

Route3_Text_ColtonIntro::
    .string "Hey!\n"
    .string "I saw you in Viridian Forest!$"

Route3_Text_ColtonDefeat::
    .string "You beat me again!$"

Route3_Text_ColtonPostBattle::
    .string "There are other kinds of Pokémon\n"
    .string "than the ones you find in forests.$"

Route3_Text_BenIntro::
    .string "Hi!\n"
    .string "I like shorts!\p"
    .string "They're delightfully comfy and\n"
    .string "easy to wear!$"

Route3_Text_BenDefeat::
    .string "I don't believe it!$"

Route3_Text_BenPostBattle::
    .string "Are you using a Pokémon Center's\n"
    .string "PC for storing your Pokémon?\p"
    .string "Each Box can hold up to\n"
    .string "30 Pokémon.$"

Route3_Text_JaniceIntro::
    .string "Excuse me!\n"
    .string "You looked at me, didn't you?$"

Route3_Text_JaniceDefeat::
    .string "You're mean!$"

Route3_Text_JanicePostBattle::
    .string "You shouldn't be staring if you\n"
    .string "don't want to battle!$"

Route3_Text_GregIntro::
    .string "Are you a Trainer?\n"
    .string "Let's get with it right away!$"

Route3_Text_GregDefeat::
    .string "If I had new Pokémon, I would've\n"
    .string "won!$"

Route3_Text_GregPostBattle::
    .string "If a Pokémon Box on the PC gets\n"
    .string "full, just switch to another Box.$"

Route3_Text_SallyIntro::
    .string "That look you gave me…\n"
    .string "It's so intriguing!$"

Route3_Text_SallyDefeat::
    .string "Be nice!$"

Route3_Text_SallyPostBattle::
    .string "You can avoid battles by not\n"
    .string "letting Trainers see you.$"

Route3_Text_CalvinIntro::
    .string "Hey! You're not wearing shorts!\n"
    .string "What's wrong with you?$"

Route3_Text_CalvinDefeat::
    .string "Lost!\n"
    .string "Lost! Lost!$"

Route3_Text_CalvinPostBattle::
    .string "I always wear shorts, even in\n"
    .string "winter. That's my policy.$"

Route3_Text_JamesIntro::
    .string "I'll battle you with the Pokémon\n"
    .string "I just caught.$"

Route3_Text_JamesDefeat::
    .string "Done like dinner!$"

Route3_Text_JamesPostBattle::
    .string "Trained Pokémon are stronger than\n"
    .string "the wild ones.$"

Route3_Text_RobinIntro::
    .string "Eek!\n"
    .string "Did you touch me?$"

Route3_Text_RobinDefeat::
    .string "That's it?$"

Route3_Text_RobinPostBattle::
    .string "Route 4 is at the foot of\n"
    .string "Mt. Moon.$"

Route3_Text_RouteSign::
    .string "Route 3\n"
    .string "Mt. Moon Ahead$"

