SevenIsland_Mart_Text_MonHavePersonalitiesOfTheirOwn::
    .string "POKéMON have personalities of their\n"
    .string "own, just like people.\p"
    .string "My PIKACHU has a HASTY nature,\n"
    .string "so it grew to be a speedy POKéMON.$"

SevenIsland_Mart_Text_PreparationsCompleteForRuins::
    .string "Okay, preparations are complete\n"
    .string "for me to explore the RUINS.$"

SevenIsland_Mart_Text_NeedToFishOnSevenIsland::
    .string "I need to fish on SEVEN ISLAND.\p"
    .string "That will complete my fishing tour\n"
    .string "of the SEVII ISLANDS.\p"
    .string "I'd better stock up on some\n"
    .string "POKé BALLS first, though.$"

