Text_DoubleEdgeTeach:: @ 81749F9
    .string "You should be proud of yourself,\n"
    .string "having battled your way through\l"
    .string "Victory Road so courageously.\p"
    .string "In recognition of your feat,\n"
    .string "I'll teach you Double-Edge.\p"
    .string "Would you like me to teach that\n"
    .string "technique?$"

Text_DoubleEdgeDeclined:: @ 8174ABC
    .string "I'll teach you the technique\n"
    .string "anytime.$"

Text_DoubleEdgeWhichMon:: @ 8174AE2
    .string "Which Pokémon should I teach\n"
    .string "Double-Edge?$"

Text_DoubleEdgeTaught:: @ 8174B0C
    .string "Keep that drive going for the\n"
    .string "Pokémon League!\p"
    .string "Take a run at them and knock 'em\n"
    .string "out!$"

VictoryRoad_3F_Text_GeorgeIntro:: @ 8174B60
    .string "I heard rumors of a child prodigy.$"

VictoryRoad_3F_Text_GeorgeDefeat:: @ 8174B83
    .string "The rumors were true!$"

VictoryRoad_3F_Text_GeorgePostBattle:: @ 8174B99
    .string "So, it was you who beat Giovanni\n"
    .string "of Team Rocket?$"

VictoryRoad_3F_Text_AlexaIntro:: @ 8174BCA
    .string "Trainers live to seek stronger\n"
    .string "opponents.$"

VictoryRoad_3F_Text_AlexaDefeat:: @ 8174BF4
    .string "Oh!\n"
    .string "So strong!$"

VictoryRoad_3F_Text_AlexaPostBattle:: @ 8174C03
    .string "By fighting tough battles, you get\n"
    .string "stronger.$"

VictoryRoad_3F_Text_CarolineIntro:: @ 8174C30
    .string "I'll show you just how good you\n"
    .string "are. Not!$"

VictoryRoad_3F_Text_CarolineDefeat:: @ 8174C5A
    .string "I'm furious!$"

VictoryRoad_3F_Text_CarolinePostBattle:: @ 8174C67
    .string "You showed me just how good\n"
    .string "I was…$"

VictoryRoad_3F_Text_ColbyIntro:: @ 8174C8A
    .string "Only the chosen can pass here!$"

VictoryRoad_3F_Text_ColbyDefeat:: @ 8174CA9
    .string "I don't believe it!$"

VictoryRoad_3F_Text_ColbyPostBattle:: @ 8174CBD
    .string "All Trainers here are headed to\n"
    .string "the Pokémon League.\p"
    .string "Don't let down your guard.$"

VictoryRoad_3F_Text_RayIntro:: @ 8174D0C
    .string "Ray: Together, the two of us are\n"
    .string "destined for greatness!$"

VictoryRoad_3F_Text_RayDefeat:: @ 8174D45
    .string "Ray: Ludicrous!\n"
    .string "This can't be!$"

VictoryRoad_3F_Text_RayPostBattle:: @ 8174D64
    .string "Ray: You've beaten us.\n"
    .string "Greatness remains elusive…$"

VictoryRoad_3F_Text_RayNotEnoughMons:: @ 8174D96
    .string "Ray: Together, the two of us are\n"
    .string "striving for the pinnacle.\p"
    .string "We need you to bring two Pokémon\n"
    .string "into battle with us.$"

VictoryRoad_3F_Text_TyraIntro:: @ 8174E08
    .string "Tyra: We're trying to become\n"
    .string "champions together.$"

VictoryRoad_3F_Text_TyraDefeat:: @ 8174E39
    .string "Tyra: Oh, but…$"

VictoryRoad_3F_Text_TyraPostBattle:: @ 8174E48
    .string "Tyra: You've taught me that power\n"
    .string "can be infinite in shape and form.$"

VictoryRoad_3F_Text_TyraNotEnoughMons:: @ 8174E8D
    .string "Tyra: You can't battle with us if\n"
    .string "you have only one Pokémon.$"

