SaffronCity_Duplicate_EventObjects:
	object_event 1, 49, 0, 22, 0, 15, 0, 3, 8, 17, 0, 0, 0, 0, 0, SaffronCity_Duplicate_EventScript_16737A, 62, 0, 0
	object_event 2, 49, 0, 26, 0, 16, 0, 3, 5, 20, 0, 0, 0, 0, 0, SaffronCity_Duplicate_EventScript_167383, 62, 0, 0
	object_event 3, 49, 0, 46, 0, 13, 0, 3, 8, 17, 0, 0, 0, 0, 0, SaffronCity_Duplicate_EventScript_16738C, 62, 0, 0
	object_event 4, 49, 0, 27, 0, 22, 0, 3, 8, 17, 0, 0, 0, 0, 0, SaffronCity_Duplicate_EventScript_167395, 62, 0, 0
	object_event 5, 49, 0, 25, 0, 33, 0, 3, 5, 23, 0, 0, 0, 0, 0, SaffronCity_Duplicate_EventScript_16739E, 62, 0, 0
	object_event 6, 49, 0, 34, 0, 31, 0, 3, 8, 17, 0, 0, 0, 0, 0, SaffronCity_Duplicate_EventScript_1673B9, 62, 0, 0
	object_event 7, 49, 0, 30, 0, 39, 0, 3, 5, 21, 0, 0, 0, 0, 0, SaffronCity_Duplicate_EventScript_1673B0, 62, 0, 0
	object_event 8, 49, 0, 48, 0, 24, 0, 3, 5, 20, 0, 0, 0, 0, 0, SaffronCity_Duplicate_EventScript_1673A7, 62, 0, 0
	object_event 9, 18, 0, 37, 0, 32, 0, 3, 1, 17, 0, 0, 0, 0, 0, SaffronCity_Duplicate_EventScript_1673EC, 63, 0, 0
	object_event 10, 47, 0, 21, 0, 23, 0, 3, 2, 17, 0, 0, 0, 0, 0, SaffronCity_Duplicate_EventScript_1673E3, 63, 0, 0
	object_event 11, 25, 0, 39, 0, 16, 0, 3, 7, 17, 0, 0, 0, 0, 0, SaffronCity_Duplicate_EventScript_16741A, 63, 0, 0
	object_event 12, 19, 0, 44, 0, 22, 0, 3, 8, 17, 0, 0, 0, 0, 0, SaffronCity_Duplicate_EventScript_1673FE, 63, 0, 0
	object_event 13, 114, 0, 45, 0, 22, 0, 3, 8, 17, 0, 0, 0, 0, 0, SaffronCity_Duplicate_EventScript_167407, 63, 0, 0
	object_event 14, 22, 0, 32, 0, 39, 0, 3, 5, 21, 0, 0, 0, 0, 0, SaffronCity_Duplicate_EventScript_1673F5, 63, 0, 0
	object_event 15, 24, 0, 47, 0, 24, 0, 3, 5, 17, 0, 0, 0, 0, 0, SaffronCity_Duplicate_EventScript_1AD03A, 157, 0, 0

SaffronCity_Duplicate_MapWarps:
	warp_def 33, 30, 0, 1, 303
	warp_def 22, 14, 0, 1, 3584
	warp_def 40, 12, 0, 1, 3586
	warp_def 46, 12, 0, 1, 3587
	warp_def 27, 21, 0, 1, 3588
	warp_def 40, 21, 0, 1, 3589
	warp_def 24, 38, 0, 1, 3590
	warp_def 43, 38, 0, 1, 3592
	warp_def 8, 27, 3, 2, 4864
	warp_def 34, 5, 3, 2, 4353
	warp_def 58, 27, 3, 1, 5120
	warp_def 34, 46, 3, 0, 4608
	warp_def 35, 46, 3, 0, 4608
	warp_def 35, 5, 3, 2, 4353
	warp_def 47, 21, 0, 0, 3593

SaffronCity_Duplicate_MapBGEvents:
	bg_event 29, 14, 0, 0, 0, SaffronCity_Duplicate_EventScript_167423
	bg_event 42, 14, 0, 0, 0, SaffronCity_Duplicate_EventScript_16742C
	bg_event 13, 25, 0, 0, 0, SaffronCity_Duplicate_EventScript_167471
	bg_event 18, 30, 0, 0, 0, SaffronCity_Duplicate_EventScript_167456
	bg_event 29, 31, 0, 0, 0, SaffronCity_Duplicate_EventScript_16745F
	bg_event 54, 25, 0, 0, 0, SaffronCity_Duplicate_EventScript_16744D
	bg_event 50, 14, 0, 0, 0, SaffronCity_Duplicate_EventScript_167435
	bg_event 40, 38, 0, 0, 0, SaffronCity_Duplicate_EventScript_167468
	bg_event 49, 22, 0, 0, 0, SaffronCity_Duplicate_EventScript_16747A

SaffronCity_Duplicate_MapEvents::
	map_events SaffronCity_Duplicate_EventObjects, SaffronCity_Duplicate_MapWarps, 0x0, SaffronCity_Duplicate_MapBGEvents
