UnknownMap_00_00:: @ 834F188
	.incbin "baserom.gba", 0x34F188, 0x1C

UnknownMap_00_01:: @ 834F1A4
	.incbin "baserom.gba", 0x34F1A4, 0x1C

UnknownMap_00_02:: @ 834F1C0
	.incbin "baserom.gba", 0x34F1C0, 0x1C

UnknownMap_00_03:: @ 834F1DC
	.incbin "baserom.gba", 0x34F1DC, 0x1C

UnknownMap_00_04:: @ 834F1F8
	.incbin "baserom.gba", 0x34F1F8, 0x1C

ViridianForest:: @ 834F214
	.incbin "baserom.gba", 0x34F214, 0x1C

MtMoon_1F:: @ 834F230
	.incbin "baserom.gba", 0x34F230, 0x1C

MtMoon_B1F:: @ 834F24C
	.incbin "baserom.gba", 0x34F24C, 0x1C

MtMoon_B2F:: @ 834F268
	.incbin "baserom.gba", 0x34F268, 0x1C

SSAnne_Exterior:: @ 834F284
	.incbin "baserom.gba", 0x34F284, 0x1C

SSAnne_1F_Corridor:: @ 834F2A0
	.incbin "baserom.gba", 0x34F2A0, 0x1C

SSAnne_2F_Corridor:: @ 834F2BC
	.incbin "baserom.gba", 0x34F2BC, 0x1C

SSAnne_3F_Corridor:: @ 834F2D8
	.incbin "baserom.gba", 0x34F2D8, 0x1C

SSAnne_B1F_Corridor:: @ 834F2F4
	.incbin "baserom.gba", 0x34F2F4, 0x1C

SSAnne_Deck:: @ 834F310
	.incbin "baserom.gba", 0x34F310, 0x1C

SSAnne_Kitchen:: @ 834F32C
	.incbin "baserom.gba", 0x34F32C, 0x1C

SSAnne_CaptainsOffice:: @ 834F348
	.incbin "baserom.gba", 0x34F348, 0x1C

SSAnne_1F_Room1:: @ 834F364
	.incbin "baserom.gba", 0x34F364, 0x1C

SSAnne_1F_Room2:: @ 834F380
	.incbin "baserom.gba", 0x34F380, 0x1C

SSAnne_1F_Room3:: @ 834F39C
	.incbin "baserom.gba", 0x34F39C, 0x1C

SSAnne_1F_Room4:: @ 834F3B8
	.incbin "baserom.gba", 0x34F3B8, 0x1C

SSAnne_1F_Room5:: @ 834F3D4
	.incbin "baserom.gba", 0x34F3D4, 0x1C

SSAnne_1F_Room7:: @ 834F3F0
	.incbin "baserom.gba", 0x34F3F0, 0x1C

SSAnne_2F_Room1:: @ 834F40C
	.incbin "baserom.gba", 0x34F40C, 0x1C

SSAnne_2F_Room2:: @ 834F428
	.incbin "baserom.gba", 0x34F428, 0x1C

SSAnne_2F_Room3:: @ 834F444
	.incbin "baserom.gba", 0x34F444, 0x1C

SSAnne_2F_Room4:: @ 834F460
	.incbin "baserom.gba", 0x34F460, 0x1C

SSAnne_2F_Room5:: @ 834F47C
	.incbin "baserom.gba", 0x34F47C, 0x1C

SSAnne_2F_Room6:: @ 834F498
	.incbin "baserom.gba", 0x34F498, 0x1C

SSAnne_B1F_Room1:: @ 834F4B4
	.incbin "baserom.gba", 0x34F4B4, 0x1C

SSAnne_B1F_Room2:: @ 834F4D0
	.incbin "baserom.gba", 0x34F4D0, 0x1C

SSAnne_B1F_Room3:: @ 834F4EC
	.incbin "baserom.gba", 0x34F4EC, 0x1C

SSAnne_B1F_Room4:: @ 834F508
	.incbin "baserom.gba", 0x34F508, 0x1C

SSAnne_B1F_Room5:: @ 834F524
	.incbin "baserom.gba", 0x34F524, 0x1C

SSAnne_1F_Room6:: @ 834F540
	.incbin "baserom.gba", 0x34F540, 0x1C

UndergroundPath_NorthEntrance:: @ 834F55C
	.incbin "baserom.gba", 0x34F55C, 0x1C

UndergroundPath_NorthSouthTunnel:: @ 834F578
	.incbin "baserom.gba", 0x34F578, 0x1C

UndergroundPath_SouthEntrance:: @ 834F594
	.incbin "baserom.gba", 0x34F594, 0x1C

UndergroundPath_WestEntrance:: @ 834F5B0
	.incbin "baserom.gba", 0x34F5B0, 0x1C

UndergroundPath_EastWestTunnel:: @ 834F5CC
	.incbin "baserom.gba", 0x34F5CC, 0x1C

UndergroundPath_EastEntrance:: @ 834F5E8
	.incbin "baserom.gba", 0x34F5E8, 0x1C

DiglettsCave_NorthEntrance:: @ 834F604
	.incbin "baserom.gba", 0x34F604, 0x1C

DiglettsCave_B1F:: @ 834F620
	.incbin "baserom.gba", 0x34F620, 0x1C

DiglettsCave_SouthEntrance:: @ 834F63C
	.incbin "baserom.gba", 0x34F63C, 0x1C

VictoryRoad_1F:: @ 834F658
	.incbin "baserom.gba", 0x34F658, 0x1C

VictoryRoad_2F:: @ 834F674
	.incbin "baserom.gba", 0x34F674, 0x1C

VictoryRoad_3F:: @ 834F690
	.incbin "baserom.gba", 0x34F690, 0x1C

RocketHideout_B1F:: @ 834F6AC
	.incbin "baserom.gba", 0x34F6AC, 0x1C

RocketHideout_B2F:: @ 834F6C8
	.incbin "baserom.gba", 0x34F6C8, 0x1C

RocketHideout_B3F:: @ 834F6E4
	.incbin "baserom.gba", 0x34F6E4, 0x1C

RocketHideout_B4F:: @ 834F700
	.incbin "baserom.gba", 0x34F700, 0x1C

RocketHideout_Elevator:: @ 834F71C
	.incbin "baserom.gba", 0x34F71C, 0x1C

SilphCo_1F:: @ 834F738
	.incbin "baserom.gba", 0x34F738, 0x1C

SilphCo_2F:: @ 834F754
	.incbin "baserom.gba", 0x34F754, 0x1C

SilphCo_3F:: @ 834F770
	.incbin "baserom.gba", 0x34F770, 0x1C

SilphCo_4F:: @ 834F78C
	.incbin "baserom.gba", 0x34F78C, 0x1C

SilphCo_5F:: @ 834F7A8
	.incbin "baserom.gba", 0x34F7A8, 0x1C

SilphCo_6F:: @ 834F7C4
	.incbin "baserom.gba", 0x34F7C4, 0x1C

SilphCo_7F:: @ 834F7E0
	.incbin "baserom.gba", 0x34F7E0, 0x1C

SilphCo_8F:: @ 834F7FC
	.incbin "baserom.gba", 0x34F7FC, 0x1C

SilphCo_9F:: @ 834F818
	.incbin "baserom.gba", 0x34F818, 0x1C

SilphCo_10F:: @ 834F834
	.incbin "baserom.gba", 0x34F834, 0x1C

SilphCo_11F:: @ 834F850
	.incbin "baserom.gba", 0x34F850, 0x1C

SilphCo_Elevator:: @ 834F86C
	.incbin "baserom.gba", 0x34F86C, 0x1C

PokemonMansion_1F:: @ 834F888
	.incbin "baserom.gba", 0x34F888, 0x1C

PokemonMansion_2F:: @ 834F8A4
	.incbin "baserom.gba", 0x34F8A4, 0x1C

PokemonMansion_3F:: @ 834F8C0
	.incbin "baserom.gba", 0x34F8C0, 0x1C

PokemonMansion_B1F:: @ 834F8DC
	.incbin "baserom.gba", 0x34F8DC, 0x1C

SafariZone_Center:: @ 834F8F8
	.incbin "baserom.gba", 0x34F8F8, 0x1C

SafariZone_East:: @ 834F914
	.incbin "baserom.gba", 0x34F914, 0x1C

SafariZone_North:: @ 834F930
	.incbin "baserom.gba", 0x34F930, 0x1C

SafariZone_West:: @ 834F94C
	.incbin "baserom.gba", 0x34F94C, 0x1C

SafariZone_Building1:: @ 834F968
	.incbin "baserom.gba", 0x34F968, 0x1C

SafariZone_Building2:: @ 834F984
	.incbin "baserom.gba", 0x34F984, 0x1C

SafariZone_Building3:: @ 834F9A0
	.incbin "baserom.gba", 0x34F9A0, 0x1C

SafariZone_Building4:: @ 834F9BC
	.incbin "baserom.gba", 0x34F9BC, 0x1C

SafariZone_SecretHouse:: @ 834F9D8
	.incbin "baserom.gba", 0x34F9D8, 0x1C

CeruleanCave_1F:: @ 834F9F4
	.incbin "baserom.gba", 0x34F9F4, 0x1C

CeruleanCave_2F:: @ 834FA10
	.incbin "baserom.gba", 0x34FA10, 0x1C

CeruleanCave_B1F:: @ 834FA2C
	.incbin "baserom.gba", 0x34FA2C, 0x1C

PokemonLeague_LoreleisRoom:: @ 834FA48
	.incbin "baserom.gba", 0x34FA48, 0x1C

PokemonLeague_BrunosRoom:: @ 834FA64
	.incbin "baserom.gba", 0x34FA64, 0x1C

PokemonLeague_AgathasRoom:: @ 834FA80
	.incbin "baserom.gba", 0x34FA80, 0x1C

PokemonLeague_LancesRoom:: @ 834FA9C
	.incbin "baserom.gba", 0x34FA9C, 0x1C

PokemonLeague_ChampionsRoom:: @ 834FAB8
	.incbin "baserom.gba", 0x34FAB8, 0x1C

PokemonLeague_HallOfFame:: @ 834FAD4
	.incbin "baserom.gba", 0x34FAD4, 0x1C

RockTunnel_1F:: @ 834FAF0
	.incbin "baserom.gba", 0x34FAF0, 0x1C

RockTunnel_B1F:: @ 834FB0C
	.incbin "baserom.gba", 0x34FB0C, 0x1C

SeafoamIslands_1F:: @ 834FB28
	.incbin "baserom.gba", 0x34FB28, 0x1C

SeafoamIslands_B1F:: @ 834FB44
	.incbin "baserom.gba", 0x34FB44, 0x1C

SeafoamIslands_B2F:: @ 834FB60
	.incbin "baserom.gba", 0x34FB60, 0x1C

SeafoamIslands_B3F:: @ 834FB7C
	.incbin "baserom.gba", 0x34FB7C, 0x1C

SeafoamIslands_B4F:: @ 834FB98
	.incbin "baserom.gba", 0x34FB98, 0x1C

PokemonTower_1F:: @ 834FBB4
	.incbin "baserom.gba", 0x34FBB4, 0x1C

PokemonTower_2F:: @ 834FBD0
	.incbin "baserom.gba", 0x34FBD0, 0x1C

PokemonTower_3F:: @ 834FBEC
	.incbin "baserom.gba", 0x34FBEC, 0x1C

PokemonTower_4F:: @ 834FC08
	.incbin "baserom.gba", 0x34FC08, 0x1C

PokemonTower_5F:: @ 834FC24
	.incbin "baserom.gba", 0x34FC24, 0x1C

PokemonTower_6F:: @ 834FC40
	.incbin "baserom.gba", 0x34FC40, 0x1C

PokemonTower_7F:: @ 834FC5C
	.incbin "baserom.gba", 0x34FC5C, 0x1C

PowerPlant:: @ 834FC78
	.incbin "baserom.gba", 0x34FC78, 0x1C

MtEmber_RubyPath_B4F:: @ 834FC94
	.incbin "baserom.gba", 0x34FC94, 0x1C

MtEmber_Exterior:: @ 834FCB0
	.incbin "baserom.gba", 0x34FCB0, 0x1C

MtEmber_SummitPath_1F:: @ 834FCCC
	.incbin "baserom.gba", 0x34FCCC, 0x1C

MtEmber_SummitPath_2F:: @ 834FCE8
	.incbin "baserom.gba", 0x34FCE8, 0x1C

MtEmber_SummitPath_3F:: @ 834FD04
	.incbin "baserom.gba", 0x34FD04, 0x1C

MtEmber_Summit:: @ 834FD20
	.incbin "baserom.gba", 0x34FD20, 0x1C

MtEmber_RubyPath_B5F:: @ 834FD3C
	.incbin "baserom.gba", 0x34FD3C, 0x1C

SSAnne_Kitchen3:: @ 834FD58
	.incbin "baserom.gba", 0x34FD58, 0x1C

MtEmber_RubyPath_B1F:: @ 834FD74
	.incbin "baserom.gba", 0x34FD74, 0x1C

MtEmber_RubyPath_B2F:: @ 834FD90
	.incbin "baserom.gba", 0x34FD90, 0x1C

MtEmber_RubyPath_B3F:: @ 834FDAC
	.incbin "baserom.gba", 0x34FDAC, 0x1C

MtEmber_RubyPath_B1F_Stairs:: @ 834FDC8
	.incbin "baserom.gba", 0x34FDC8, 0x1C

MtEmber_RubyPath_B2F_Stairs:: @ 834FDE4
	.incbin "baserom.gba", 0x34FDE4, 0x1C

ThreeIsland_BerryForest:: @ 834FE00
	.incbin "baserom.gba", 0x34FE00, 0x1C

FourIsland_IcefallCave_Entrance:: @ 834FE1C
	.incbin "baserom.gba", 0x34FE1C, 0x1C

FourIsland_IcefallCave_1F:: @ 834FE38
	.incbin "baserom.gba", 0x34FE38, 0x1C

SSAnne_CaptainsOffice2:: @ 834FE54
	.incbin "baserom.gba", 0x34FE54, 0x1C

SSAnne_CaptainsOffice3:: @ 834FE70
	.incbin "baserom.gba", 0x34FE70, 0x1C

SSAnne_CaptainsOffice4:: @ 834FE8C
	.incbin "baserom.gba", 0x34FE8C, 0x1C

SSAnne_CaptainsOffice5:: @ 834FEA8
	.incbin "baserom.gba", 0x34FEA8, 0x1C

SixIsland_DottedHole_B1F:: @ 834FEC4
	.incbin "baserom.gba", 0x34FEC4, 0x1C

SixIsland_DottedHole_B2F:: @ 834FEE0
	.incbin "baserom.gba", 0x34FEE0, 0x1C

SixIsland_DottedHole_B3F:: @ 834FEFC
	.incbin "baserom.gba", 0x34FEFC, 0x1C

SSAnne_CaptainsOffice9:: @ 834FF18
	.incbin "baserom.gba", 0x34FF18, 0x1C

SixIsland_DottedHole_SapphireRoom:: @ 834FF34
	.incbin "baserom.gba", 0x34FF34, 0x1C

SSAnne_1F_Room11:: @ 834FF50
	.incbin "baserom.gba", 0x34FF50, 0x1C

SSAnne_1F_Room12:: @ 834FF6C
	.incbin "baserom.gba", 0x34FF6C, 0x1C

NavelRock_Exterior:: @ 834FF88
	.incbin "baserom.gba", 0x34FF88, 0x1C

SevenIsland_TrainerTower_1F:: @ 834FFA4
	.incbin "baserom.gba", 0x34FFA4, 0x1C

SevenIsland_TrainerTower_2F:: @ 834FFC0
	.incbin "baserom.gba", 0x34FFC0, 0x1C

SevenIsland_TrainerTower_3F:: @ 834FFDC
	.incbin "baserom.gba", 0x34FFDC, 0x1C

SevenIsland_TrainerTower_4F:: @ 834FFF8
	.incbin "baserom.gba", 0x34FFF8, 0x1C

SevenIsland_TrainerTower_5F:: @ 8350014
	.incbin "baserom.gba", 0x350014, 0x1C

SevenIsland_TrainerTower_6F:: @ 8350030
	.incbin "baserom.gba", 0x350030, 0x1C

SevenIsland_TrainerTower_7F:: @ 835004C
	.incbin "baserom.gba", 0x35004C, 0x1C

SevenIsland_TrainerTower_8F:: @ 8350068
	.incbin "baserom.gba", 0x350068, 0x1C

SevenIsland_TrainerTower_Roof:: @ 8350084
	.incbin "baserom.gba", 0x350084, 0x1C

SevenIsland_TrainerTower_Lobby:: @ 83500A0
	.incbin "baserom.gba", 0x3500A0, 0x1C

SevenIsland_TrainerTower_Elevator:: @ 83500BC
	.incbin "baserom.gba", 0x3500BC, 0x1C

FiveIsland_LostCave_Entrance:: @ 83500D8
	.incbin "baserom.gba", 0x3500D8, 0x1C

FiveIsland_LostCave_Room1:: @ 83500F4
	.incbin "baserom.gba", 0x3500F4, 0x1C

FiveIsland_LostCave_Room2:: @ 8350110
	.incbin "baserom.gba", 0x350110, 0x1C

FiveIsland_LostCave_Room3:: @ 835012C
	.incbin "baserom.gba", 0x35012C, 0x1C

FiveIsland_LostCave_Room4:: @ 8350148
	.incbin "baserom.gba", 0x350148, 0x1C

FiveIsland_LostCave_Room5:: @ 8350164
	.incbin "baserom.gba", 0x350164, 0x1C

FiveIsland_LostCave_Room6:: @ 8350180
	.incbin "baserom.gba", 0x350180, 0x1C

FiveIsland_LostCave_Room7:: @ 835019C
	.incbin "baserom.gba", 0x35019C, 0x1C

FiveIsland_LostCave_Room8:: @ 83501B8
	.incbin "baserom.gba", 0x3501B8, 0x1C

FiveIsland_LostCave_Room9:: @ 83501D4
	.incbin "baserom.gba", 0x3501D4, 0x1C

FiveIsland_LostCave_Room10:: @ 83501F0
	.incbin "baserom.gba", 0x3501F0, 0x1C

FiveIsland_LostCave_Room11:: @ 835020C
	.incbin "baserom.gba", 0x35020C, 0x1C

FiveIsland_LostCave_Room12:: @ 8350228
	.incbin "baserom.gba", 0x350228, 0x1C

FiveIsland_LostCave_Room13:: @ 8350244
	.incbin "baserom.gba", 0x350244, 0x1C

FiveIsland_LostCave_Room14:: @ 8350260
	.incbin "baserom.gba", 0x350260, 0x1C

SevenIsland_TanobyRuins_MoneanChamber:: @ 835027C
	.incbin "baserom.gba", 0x35027C, 0x1C

SevenIsland_TanobyRuins_LiptooChamber:: @ 8350298
	.incbin "baserom.gba", 0x350298, 0x1C

SevenIsland_TanobyRuins_WeepthChamber:: @ 83502B4
	.incbin "baserom.gba", 0x3502B4, 0x1C

SevenIsland_TanobyRuins_DilfordChamber:: @ 83502D0
	.incbin "baserom.gba", 0x3502D0, 0x1C

SevenIsland_TanobyRuins_ScufibChamber:: @ 83502EC
	.incbin "baserom.gba", 0x3502EC, 0x1C

SevenIsland_TanobyRuins_RixyChamber:: @ 8350308
	.incbin "baserom.gba", 0x350308, 0x1C

SevenIsland_TanobyRuins_ViapoisChamber:: @ 8350324
	.incbin "baserom.gba", 0x350324, 0x1C

ThreeIsland_DunsparceTunnel:: @ 8350340
	.incbin "baserom.gba", 0x350340, 0x1C

SevenIsland_SeavaultCanyon_TanobyKey:: @ 835035C
	.incbin "baserom.gba", 0x35035C, 0x1C

NavelRock_1F:: @ 8350378
	.incbin "baserom.gba", 0x350378, 0x1C

NavelRock_Summit:: @ 8350394
	.incbin "baserom.gba", 0x350394, 0x1C

NavelRock_Base:: @ 83503B0
	.incbin "baserom.gba", 0x3503B0, 0x1C

NavelRock_SummitPath_2F:: @ 83503CC
	.incbin "baserom.gba", 0x3503CC, 0x1C

NavelRock_SummitPath_3F:: @ 83503E8
	.incbin "baserom.gba", 0x3503E8, 0x1C

NavelRock_SummitPath_4F:: @ 8350404
	.incbin "baserom.gba", 0x350404, 0x1C

NavelRock_SummitPath_5F:: @ 8350420
	.incbin "baserom.gba", 0x350420, 0x1C

NavelRock_BasePath_B1F:: @ 835043C
	.incbin "baserom.gba", 0x35043C, 0x1C

NavelRock_BasePath_B2F:: @ 8350458
	.incbin "baserom.gba", 0x350458, 0x1C

NavelRock_BasePath_B3F:: @ 8350474
	.incbin "baserom.gba", 0x350474, 0x1C

NavelRock_BasePath_B4F:: @ 8350490
	.incbin "baserom.gba", 0x350490, 0x1C

NavelRock_BasePath_B5F:: @ 83504AC
	.incbin "baserom.gba", 0x3504AC, 0x1C

NavelRock_BasePath_B6F:: @ 83504C8
	.incbin "baserom.gba", 0x3504C8, 0x1C

NavelRock_BasePath_B7F:: @ 83504E4
	.incbin "baserom.gba", 0x3504E4, 0x1C

NavelRock_BasePath_B8F:: @ 8350500
	.incbin "baserom.gba", 0x350500, 0x1C

NavelRock_BasePath_B9F:: @ 835051C
	.incbin "baserom.gba", 0x35051C, 0x1C

NavelRock_BasePath_B10F:: @ 8350538
	.incbin "baserom.gba", 0x350538, 0x1C

NavelRock_BasePath_B11F:: @ 8350554
	.incbin "baserom.gba", 0x350554, 0x1C

NavelRock_B1F:: @ 8350570
	.incbin "baserom.gba", 0x350570, 0x1C

NavelRock_Fork:: @ 835058C
	.incbin "baserom.gba", 0x35058C, 0x1C

BirthIsland_Exterior:: @ 83505A8
	.incbin "baserom.gba", 0x3505A8, 0x1C

OneIsland_KindleRoad_EmberSpa:: @ 83505C4
	.incbin "baserom.gba", 0x3505C4, 0x1C

BirthIsland_Harbor:: @ 83505E0
	.incbin "baserom.gba", 0x3505E0, 0x1C

NavelRock_Harbor:: @ 83505FC
	.incbin "baserom.gba", 0x3505FC, 0x1C

PalletTown:: @ 8350618
	.incbin "baserom.gba", 0x350618, 0x1C

ViridianCity:: @ 8350634
	.incbin "baserom.gba", 0x350634, 0x1C

PewterCity:: @ 8350650
	.incbin "baserom.gba", 0x350650, 0x1C

CeruleanCity:: @ 835066C
	.incbin "baserom.gba", 0x35066C, 0x1C

LavenderTown:: @ 8350688
	.incbin "baserom.gba", 0x350688, 0x1C

VermilionCity:: @ 83506A4
	.incbin "baserom.gba", 0x3506A4, 0x1C

CeladonCity:: @ 83506C0
	.incbin "baserom.gba", 0x3506C0, 0x1C

FuchsiaCity:: @ 83506DC
	.incbin "baserom.gba", 0x3506DC, 0x1C

CinnabarIsland:: @ 83506F8
	.incbin "baserom.gba", 0x3506F8, 0x1C

IndigoPlateau_Exterior:: @ 8350714
	.incbin "baserom.gba", 0x350714, 0x1C

SaffronCity_Duplicate:: @ 8350730
	.incbin "baserom.gba", 0x350730, 0x1C

SaffronCity:: @ 835074C
	.incbin "baserom.gba", 0x35074C, 0x1C

OneIsland:: @ 8350768
	.incbin "baserom.gba", 0x350768, 0x1C

TwoIsland:: @ 8350784
	.incbin "baserom.gba", 0x350784, 0x1C

ThreeIsland:: @ 83507A0
	.incbin "baserom.gba", 0x3507A0, 0x1C

FourIsland:: @ 83507BC
	.incbin "baserom.gba", 0x3507BC, 0x1C

FiveIsland:: @ 83507D8
	.incbin "baserom.gba", 0x3507D8, 0x1C

SevenIsland:: @ 83507F4
	.incbin "baserom.gba", 0x3507F4, 0x1C

SixIsland:: @ 8350810
	.incbin "baserom.gba", 0x350810, 0x1C

Route1:: @ 835082C
	.incbin "baserom.gba", 0x35082C, 0x1C

Route2:: @ 8350848
	.incbin "baserom.gba", 0x350848, 0x1C

Route3:: @ 8350864
	.incbin "baserom.gba", 0x350864, 0x1C

Route4:: @ 8350880
	.incbin "baserom.gba", 0x350880, 0x1C

Route5:: @ 835089C
	.incbin "baserom.gba", 0x35089C, 0x1C

Route6:: @ 83508B8
	.incbin "baserom.gba", 0x3508B8, 0x1C

Route7:: @ 83508D4
	.incbin "baserom.gba", 0x3508D4, 0x1C

Route8:: @ 83508F0
	.incbin "baserom.gba", 0x3508F0, 0x1C

Route9:: @ 835090C
	.incbin "baserom.gba", 0x35090C, 0x1C

Route10:: @ 8350928
	.incbin "baserom.gba", 0x350928, 0x1C

Route11:: @ 8350944
	.incbin "baserom.gba", 0x350944, 0x1C

Route12:: @ 8350960
	.incbin "baserom.gba", 0x350960, 0x1C

Route13:: @ 835097C
	.incbin "baserom.gba", 0x35097C, 0x1C

Route14:: @ 8350998
	.incbin "baserom.gba", 0x350998, 0x1C

Route15:: @ 83509B4
	.incbin "baserom.gba", 0x3509B4, 0x1C

Route16:: @ 83509D0
	.incbin "baserom.gba", 0x3509D0, 0x1C

Route17:: @ 83509EC
	.incbin "baserom.gba", 0x3509EC, 0x1C

Route18:: @ 8350A08
	.incbin "baserom.gba", 0x350A08, 0x1C

Route19:: @ 8350A24
	.incbin "baserom.gba", 0x350A24, 0x1C

Route20:: @ 8350A40
	.incbin "baserom.gba", 0x350A40, 0x1C

Route21_North:: @ 8350A5C
	.incbin "baserom.gba", 0x350A5C, 0x1C

Route21_South:: @ 8350A78
	.incbin "baserom.gba", 0x350A78, 0x1C

Route22:: @ 8350A94
	.incbin "baserom.gba", 0x350A94, 0x1C

Route23:: @ 8350AB0
	.incbin "baserom.gba", 0x350AB0, 0x1C

Route24:: @ 8350ACC
	.incbin "baserom.gba", 0x350ACC, 0x1C

Route25:: @ 8350AE8
	.incbin "baserom.gba", 0x350AE8, 0x1C

OneIsland_KindleRoad:: @ 8350B04
	.incbin "baserom.gba", 0x350B04, 0x1C

OneIsland_TreasureBeach:: @ 8350B20
	.incbin "baserom.gba", 0x350B20, 0x1C

TwoIsland_CapeBrink:: @ 8350B3C
	.incbin "baserom.gba", 0x350B3C, 0x1C

ThreeIsland_BondBridge:: @ 8350B58
	.incbin "baserom.gba", 0x350B58, 0x1C

ThreeIsland_Port:: @ 8350B74
	.incbin "baserom.gba", 0x350B74, 0x1C

UnknownMap_03_50:: @ 8350B90
	.incbin "baserom.gba", 0x350B90, 0x1C

UnknownMap_03_51:: @ 8350BAC
	.incbin "baserom.gba", 0x350BAC, 0x1C

UnknownMap_03_52:: @ 8350BC8
	.incbin "baserom.gba", 0x350BC8, 0x1C

UnknownMap_03_53:: @ 8350BE4
	.incbin "baserom.gba", 0x350BE4, 0x1C

FiveIsland_ResortGorgeous:: @ 8350C00
	.incbin "baserom.gba", 0x350C00, 0x1C

FiveIsland_WaterLabyrinth:: @ 8350C1C
	.incbin "baserom.gba", 0x350C1C, 0x1C

FiveIsland_Meadow:: @ 8350C38
	.incbin "baserom.gba", 0x350C38, 0x1C

FiveIsland_MemorialPillar:: @ 8350C54
	.incbin "baserom.gba", 0x350C54, 0x1C

SixIsland_OutcastIsland:: @ 8350C70
	.incbin "baserom.gba", 0x350C70, 0x1C

SixIsland_GreenPath:: @ 8350C8C
	.incbin "baserom.gba", 0x350C8C, 0x1C

SixIsland_WaterPath:: @ 8350CA8
	.incbin "baserom.gba", 0x350CA8, 0x1C

SixIsland_RuinValley:: @ 8350CC4
	.incbin "baserom.gba", 0x350CC4, 0x1C

SevenIsland_TrainerTower:: @ 8350CE0
	.incbin "baserom.gba", 0x350CE0, 0x1C

SevenIsland_SevaultCanyon_Entrance:: @ 8350CFC
	.incbin "baserom.gba", 0x350CFC, 0x1C

SevenIsland_SevaultCanyon:: @ 8350D18
	.incbin "baserom.gba", 0x350D18, 0x1C

SevenIsland_TanobyRuins:: @ 8350D34
	.incbin "baserom.gba", 0x350D34, 0x1C

PalletTown_PlayersHouse_1F:: @ 8350D50
	.incbin "baserom.gba", 0x350D50, 0x1C

PalletTown_PlayersHouse_2F:: @ 8350D6C
	.incbin "baserom.gba", 0x350D6C, 0x1C

PalletTown_GarysHouse:: @ 8350D88
	.incbin "baserom.gba", 0x350D88, 0x1C

PalletTown_ProfessorOaksLab:: @ 8350DA4
	.incbin "baserom.gba", 0x350DA4, 0x1C

ViridianCity_House1:: @ 8350DC0
	.incbin "baserom.gba", 0x350DC0, 0x1C

ViridianCity_Gym:: @ 8350DDC
	.incbin "baserom.gba", 0x350DDC, 0x1C

ViridianCity_House2:: @ 8350DF8
	.incbin "baserom.gba", 0x350DF8, 0x1C

ViridianCity_Mart:: @ 8350E14
	.incbin "baserom.gba", 0x350E14, 0x1C

ViridianCity_PokemonCenter_1F:: @ 8350E30
	.incbin "baserom.gba", 0x350E30, 0x1C

ViridianCity_PokemonCenter_2F:: @ 8350E4C
	.incbin "baserom.gba", 0x350E4C, 0x1C

PewterCity_Museum_1F:: @ 8350E68
	.incbin "baserom.gba", 0x350E68, 0x1C

PewterCity_Museum_2F:: @ 8350E84
	.incbin "baserom.gba", 0x350E84, 0x1C

PewterCity_Gym:: @ 8350EA0
	.incbin "baserom.gba", 0x350EA0, 0x1C

PewterCity_Mart:: @ 8350EBC
	.incbin "baserom.gba", 0x350EBC, 0x1C

PewterCity_House1:: @ 8350ED8
	.incbin "baserom.gba", 0x350ED8, 0x1C

PewterCity_PokemonCenter_1F:: @ 8350EF4
	.incbin "baserom.gba", 0x350EF4, 0x1C

PewterCity_PokemonCenter_2F:: @ 8350F10
	.incbin "baserom.gba", 0x350F10, 0x1C

PewterCity_House2:: @ 8350F2C
	.incbin "baserom.gba", 0x350F2C, 0x1C

CeruleanCity_House1:: @ 8350F48
	.incbin "baserom.gba", 0x350F48, 0x1C

CeruleanCity_House2:: @ 8350F64
	.incbin "baserom.gba", 0x350F64, 0x1C

CeruleanCity_House3:: @ 8350F80
	.incbin "baserom.gba", 0x350F80, 0x1C

CeruleanCity_PokemonCenter_1F:: @ 8350F9C
	.incbin "baserom.gba", 0x350F9C, 0x1C

CeruleanCity_PokemonCenter_2F:: @ 8350FB8
	.incbin "baserom.gba", 0x350FB8, 0x1C

CeruleanCity_Gym:: @ 8350FD4
	.incbin "baserom.gba", 0x350FD4, 0x1C

CeruleanCity_BikeShop:: @ 8350FF0
	.incbin "baserom.gba", 0x350FF0, 0x1C

CeruleanCity_Mart:: @ 835100C
	.incbin "baserom.gba", 0x35100C, 0x1C

CeruleanCity_House4:: @ 8351028
	.incbin "baserom.gba", 0x351028, 0x1C

CeruleanCity_House5:: @ 8351044
	.incbin "baserom.gba", 0x351044, 0x1C

LavenderTown_PokemonCenter_1F:: @ 8351060
	.incbin "baserom.gba", 0x351060, 0x1C

LavenderTown_PokemonCenter_2F:: @ 835107C
	.incbin "baserom.gba", 0x35107C, 0x1C

LavenderTown_VolunteerPokemonHouse:: @ 8351098
	.incbin "baserom.gba", 0x351098, 0x1C

LavenderTown_House1:: @ 83510B4
	.incbin "baserom.gba", 0x3510B4, 0x1C

LavenderTown_House2:: @ 83510D0
	.incbin "baserom.gba", 0x3510D0, 0x1C

LavenderTown_Mart:: @ 83510EC
	.incbin "baserom.gba", 0x3510EC, 0x1C

VermilionCity_House1:: @ 8351108
	.incbin "baserom.gba", 0x351108, 0x1C

VermilionCity_PokemonCenter_1F:: @ 8351124
	.incbin "baserom.gba", 0x351124, 0x1C

VermilionCity_PokemonCenter_2F:: @ 8351140
	.incbin "baserom.gba", 0x351140, 0x1C

VermilionCity_PokemonFanClub:: @ 835115C
	.incbin "baserom.gba", 0x35115C, 0x1C

VermilionCity_House2:: @ 8351178
	.incbin "baserom.gba", 0x351178, 0x1C

VermilionCity_Mart:: @ 8351194
	.incbin "baserom.gba", 0x351194, 0x1C

VermilionCity_Gym:: @ 83511B0
	.incbin "baserom.gba", 0x3511B0, 0x1C

VermilionCity_House3:: @ 83511CC
	.incbin "baserom.gba", 0x3511CC, 0x1C

CeladonCity_DepartmentStore_1F:: @ 83511E8
	.incbin "baserom.gba", 0x3511E8, 0x1C

CeladonCity_DepartmentStore_2F:: @ 8351204
	.incbin "baserom.gba", 0x351204, 0x1C

CeladonCity_DepartmentStore_3F:: @ 8351220
	.incbin "baserom.gba", 0x351220, 0x1C

CeladonCity_DepartmentStore_4F:: @ 835123C
	.incbin "baserom.gba", 0x35123C, 0x1C

CeladonCity_DepartmentStore_5F:: @ 8351258
	.incbin "baserom.gba", 0x351258, 0x1C

CeladonCity_DepartmentStore_Roof:: @ 8351274
	.incbin "baserom.gba", 0x351274, 0x1C

CeladonCity_DepartmentStore_Elevator:: @ 8351290
	.incbin "baserom.gba", 0x351290, 0x1C

CeladonCity_Condominiums_1F:: @ 83512AC
	.incbin "baserom.gba", 0x3512AC, 0x1C

CeladonCity_Condominiums_2F:: @ 83512C8
	.incbin "baserom.gba", 0x3512C8, 0x1C

CeladonCity_Condominiums_3F:: @ 83512E4
	.incbin "baserom.gba", 0x3512E4, 0x1C

CeladonCity_Condominiums_Roof:: @ 8351300
	.incbin "baserom.gba", 0x351300, 0x1C

CeladonCity_Condominiums_RoofRoom:: @ 835131C
	.incbin "baserom.gba", 0x35131C, 0x1C

CeladonCity_PokemonCenter_1F:: @ 8351338
	.incbin "baserom.gba", 0x351338, 0x1C

CeladonCity_PokemonCenter_2F:: @ 8351354
	.incbin "baserom.gba", 0x351354, 0x1C

CeladonCity_GameCorner:: @ 8351370
	.incbin "baserom.gba", 0x351370, 0x1C

CeladonCity_GameCorner_PrizeRoom:: @ 835138C
	.incbin "baserom.gba", 0x35138C, 0x1C

CeladonCity_Gym:: @ 83513A8
	.incbin "baserom.gba", 0x3513A8, 0x1C

CeladonCity_Restaurant:: @ 83513C4
	.incbin "baserom.gba", 0x3513C4, 0x1C

CeladonCity_House1:: @ 83513E0
	.incbin "baserom.gba", 0x3513E0, 0x1C

CeladonCity_Hotel:: @ 83513FC
	.incbin "baserom.gba", 0x3513FC, 0x1C

FuchsiaCity_SafariZone_Entrance:: @ 8351418
	.incbin "baserom.gba", 0x351418, 0x1C

FuchsiaCity_Mart:: @ 8351434
	.incbin "baserom.gba", 0x351434, 0x1C

FuchsiaCity_ZooBuilding:: @ 8351450
	.incbin "baserom.gba", 0x351450, 0x1C

FuchsiaCity_Gym:: @ 835146C
	.incbin "baserom.gba", 0x35146C, 0x1C

FuchsiaCity_House1:: @ 8351488
	.incbin "baserom.gba", 0x351488, 0x1C

FuchsiaCity_PokemonCenter_1F:: @ 83514A4
	.incbin "baserom.gba", 0x3514A4, 0x1C

FuchsiaCity_PokemonCenter_2F:: @ 83514C0
	.incbin "baserom.gba", 0x3514C0, 0x1C

FuchsiaCity_Building1:: @ 83514DC
	.incbin "baserom.gba", 0x3514DC, 0x1C

FuchsiaCity_House2:: @ 83514F8
	.incbin "baserom.gba", 0x3514F8, 0x1C

FuchsiaCity_House3:: @ 8351514
	.incbin "baserom.gba", 0x351514, 0x1C

CinnabarIsland_Gym:: @ 8351530
	.incbin "baserom.gba", 0x351530, 0x1C

CinnabarIsland_PokemonLab_Entrance:: @ 835154C
	.incbin "baserom.gba", 0x35154C, 0x1C

CinnabarIsland_PokemonLab_Lounge:: @ 8351568
	.incbin "baserom.gba", 0x351568, 0x1C

CinnabarIsland_PokemonLab_ResearchRoom:: @ 8351584
	.incbin "baserom.gba", 0x351584, 0x1C

CinnabarIsland_PokemonLab_ExperimentRoom:: @ 83515A0
	.incbin "baserom.gba", 0x3515A0, 0x1C

CinnabarIsland_PokemonCenter_1F:: @ 83515BC
	.incbin "baserom.gba", 0x3515BC, 0x1C

CinnabarIsland_PokemonCenter_2F:: @ 83515D8
	.incbin "baserom.gba", 0x3515D8, 0x1C

CinnabarIsland_Mart:: @ 83515F4
	.incbin "baserom.gba", 0x3515F4, 0x1C

IndigoPlateau_PokemonCenter_1F:: @ 8351610
	.incbin "baserom.gba", 0x351610, 0x1C

IndigoPlateau_PokemonCenter_2F:: @ 835162C
	.incbin "baserom.gba", 0x35162C, 0x1C

SaffronCity_House1_1F:: @ 8351648
	.incbin "baserom.gba", 0x351648, 0x1C

SaffronCity_House1_2F:: @ 8351664
	.incbin "baserom.gba", 0x351664, 0x1C

SaffronCity_Dojo:: @ 8351680
	.incbin "baserom.gba", 0x351680, 0x1C

SaffronCity_Gym:: @ 835169C
	.incbin "baserom.gba", 0x35169C, 0x1C

SaffronCity_House2:: @ 83516B8
	.incbin "baserom.gba", 0x3516B8, 0x1C

SaffronCity_Mart:: @ 83516D4
	.incbin "baserom.gba", 0x3516D4, 0x1C

SaffronCity_PokemonCenter_1F:: @ 83516F0
	.incbin "baserom.gba", 0x3516F0, 0x1C

SaffronCity_PokemonCenter_2F:: @ 835170C
	.incbin "baserom.gba", 0x35170C, 0x1C

SaffronCity_House3:: @ 8351728
	.incbin "baserom.gba", 0x351728, 0x1C

SaffronCity_PokemonTrainerFanClub:: @ 8351744
	.incbin "baserom.gba", 0x351744, 0x1C

Route2_ViridianForest_SouthEntrance:: @ 8351760
	.incbin "baserom.gba", 0x351760, 0x1C

Route2_House:: @ 835177C
	.incbin "baserom.gba", 0x35177C, 0x1C

Route2_EastBuilding:: @ 8351798
	.incbin "baserom.gba", 0x351798, 0x1C

Route2_ViridianForest_NorthEntrance:: @ 83517B4
	.incbin "baserom.gba", 0x3517B4, 0x1C

Route4_PokemonCenter_1F:: @ 83517D0
	.incbin "baserom.gba", 0x3517D0, 0x1C

Route4_PokemonCenter_2F:: @ 83517EC
	.incbin "baserom.gba", 0x3517EC, 0x1C

Route5_PokemonDayCare:: @ 8351808
	.incbin "baserom.gba", 0x351808, 0x1C

Route5_SouthEntrance:: @ 8351824
	.incbin "baserom.gba", 0x351824, 0x1C

Route6_NorthEntrance:: @ 8351840
	.incbin "baserom.gba", 0x351840, 0x1C

UnknownMap_18_01:: @ 835185C
	.incbin "baserom.gba", 0x35185C, 0x1C

Route7_EastEntrance:: @ 8351878
	.incbin "baserom.gba", 0x351878, 0x1C

Route8_WestEntrance:: @ 8351894
	.incbin "baserom.gba", 0x351894, 0x1C

Route10_PokemonCenter_1F:: @ 83518B0
	.incbin "baserom.gba", 0x3518B0, 0x1C

Route10_PokemonCenter_2F:: @ 83518CC
	.incbin "baserom.gba", 0x3518CC, 0x1C

Route11_EastEntrance_1F:: @ 83518E8
	.incbin "baserom.gba", 0x3518E8, 0x1C

Route11_EastEntrance_2F:: @ 8351904
	.incbin "baserom.gba", 0x351904, 0x1C

Route12_NorthEntrance_1F:: @ 8351920
	.incbin "baserom.gba", 0x351920, 0x1C

Route12_NorthEntrance_2F:: @ 835193C
	.incbin "baserom.gba", 0x35193C, 0x1C

Route12_FishingHouse:: @ 8351958
	.incbin "baserom.gba", 0x351958, 0x1C

Route15_WestEntrance_1F:: @ 8351974
	.incbin "baserom.gba", 0x351974, 0x1C

Route15_WestEntrance_2F:: @ 8351990
	.incbin "baserom.gba", 0x351990, 0x1C

Route16_House:: @ 83519AC
	.incbin "baserom.gba", 0x3519AC, 0x1C

Route16_NorthEntrance_1F:: @ 83519C8
	.incbin "baserom.gba", 0x3519C8, 0x1C

Route16_NorthEntrance_2F:: @ 83519E4
	.incbin "baserom.gba", 0x3519E4, 0x1C

Route18_EastEntrance_1F:: @ 8351A00
	.incbin "baserom.gba", 0x351A00, 0x1C

Route18_EastEntrance_2F:: @ 8351A1C
	.incbin "baserom.gba", 0x351A1C, 0x1C

UnusedHouse_27_00:: @ 8351A38
	.incbin "baserom.gba", 0x351A38, 0x1C

Route22_NorthEntrance:: @ 8351A54
	.incbin "baserom.gba", 0x351A54, 0x1C

UnusedHouse_29_00:: @ 8351A70
	.incbin "baserom.gba", 0x351A70, 0x1C

Route25_SeaCottage:: @ 8351A8C
	.incbin "baserom.gba", 0x351A8C, 0x1C

SevenIsland_House_Room1:: @ 8351AA8
	.incbin "baserom.gba", 0x351AA8, 0x1C

SevenIsland_House_Room2:: @ 8351AC4
	.incbin "baserom.gba", 0x351AC4, 0x1C

SevenIsland_Mart:: @ 8351AE0
	.incbin "baserom.gba", 0x351AE0, 0x1C

SevenIsland_PokemonCenter_1F:: @ 8351AFC
	.incbin "baserom.gba", 0x351AFC, 0x1C

SevenIsland_PokemonCenter_2F:: @ 8351B18
	.incbin "baserom.gba", 0x351B18, 0x1C

UnusedHouse_31_05:: @ 8351B34
	.incbin "baserom.gba", 0x351B34, 0x1C

SevenIsland_Harbor:: @ 8351B50
	.incbin "baserom.gba", 0x351B50, 0x1C

OneIsland_PokemonCenter_1F:: @ 8351B6C
	.incbin "baserom.gba", 0x351B6C, 0x1C

OneIsland_PokemonCenter_2F:: @ 8351B88
	.incbin "baserom.gba", 0x351B88, 0x1C

OneIsland_House1:: @ 8351BA4
	.incbin "baserom.gba", 0x351BA4, 0x1C

OneIsland_House2:: @ 8351BC0
	.incbin "baserom.gba", 0x351BC0, 0x1C

OneIsland_Harbor:: @ 8351BDC
	.incbin "baserom.gba", 0x351BDC, 0x1C

TwoIsland_JoyfulGameCorner:: @ 8351BF8
	.incbin "baserom.gba", 0x351BF8, 0x1C

TwoIsland_House:: @ 8351C14
	.incbin "baserom.gba", 0x351C14, 0x1C

TwoIsland_PokemonCenter_1F:: @ 8351C30
	.incbin "baserom.gba", 0x351C30, 0x1C

TwoIsland_PokemonCenter_2F:: @ 8351C4C
	.incbin "baserom.gba", 0x351C4C, 0x1C

TwoIsland_Harbor:: @ 8351C68
	.incbin "baserom.gba", 0x351C68, 0x1C

ThreeIsland_House1:: @ 8351C84
	.incbin "baserom.gba", 0x351C84, 0x1C

ThreeIsland_PokemonCenter_1F:: @ 8351CA0
	.incbin "baserom.gba", 0x351CA0, 0x1C

ThreeIsland_PokemonCenter_2F:: @ 8351CBC
	.incbin "baserom.gba", 0x351CBC, 0x1C

ThreeIsland_Mart:: @ 8351CD8
	.incbin "baserom.gba", 0x351CD8, 0x1C

ThreeIsland_House2:: @ 8351CF4
	.incbin "baserom.gba", 0x351CF4, 0x1C

ThreeIsland_House3:: @ 8351D10
	.incbin "baserom.gba", 0x351D10, 0x1C

ThreeIsland_House4:: @ 8351D2C
	.incbin "baserom.gba", 0x351D2C, 0x1C

ThreeIsland_House5:: @ 8351D48
	.incbin "baserom.gba", 0x351D48, 0x1C

FourIsland_PokemonDayCare:: @ 8351D64
	.incbin "baserom.gba", 0x351D64, 0x1C

FourIsland_PokemonCenter_1F:: @ 8351D80
	.incbin "baserom.gba", 0x351D80, 0x1C

FourIsland_PokemonCenter_2F:: @ 8351D9C
	.incbin "baserom.gba", 0x351D9C, 0x1C

FourIsland_House1:: @ 8351DB8
	.incbin "baserom.gba", 0x351DB8, 0x1C

FourIsland_LoreleisHouse:: @ 8351DD4
	.incbin "baserom.gba", 0x351DD4, 0x1C

FourIsland_Harbor:: @ 8351DF0
	.incbin "baserom.gba", 0x351DF0, 0x1C

FourIsland_House2:: @ 8351E0C
	.incbin "baserom.gba", 0x351E0C, 0x1C

FourIsland_Mart:: @ 8351E28
	.incbin "baserom.gba", 0x351E28, 0x1C

FiveIsland_PokemonCenter_1F:: @ 8351E44
	.incbin "baserom.gba", 0x351E44, 0x1C

FiveIsland_PokemonCenter_2F:: @ 8351E60
	.incbin "baserom.gba", 0x351E60, 0x1C

FiveIsland_Harbor:: @ 8351E7C
	.incbin "baserom.gba", 0x351E7C, 0x1C

FiveIsland_House1:: @ 8351E98
	.incbin "baserom.gba", 0x351E98, 0x1C

FiveIsland_House2:: @ 8351EB4
	.incbin "baserom.gba", 0x351EB4, 0x1C

SixIsland_PokemonCenter_1F:: @ 8351ED0
	.incbin "baserom.gba", 0x351ED0, 0x1C

SixIsland_PokemonCenter_2F:: @ 8351EEC
	.incbin "baserom.gba", 0x351EEC, 0x1C

SixIsland_Harbor:: @ 8351F08
	.incbin "baserom.gba", 0x351F08, 0x1C

SixIsland_House:: @ 8351F24
	.incbin "baserom.gba", 0x351F24, 0x1C

SixIsland_Mart:: @ 8351F40
	.incbin "baserom.gba", 0x351F40, 0x1C

ThreeIsland_Harbor:: @ 8351F5C
	.incbin "baserom.gba", 0x351F5C, 0x1C

FiveIsland_ResortGorgeous_House:: @ 8351F78
	.incbin "baserom.gba", 0x351F78, 0x1C

TwoIsland_CapeBrink_House:: @ 8351F94
	.incbin "baserom.gba", 0x351F94, 0x1C

SixIsland_WaterPath_House1:: @ 8351FB0
	.incbin "baserom.gba", 0x351FB0, 0x1C

SixIsland_WaterPath_House2:: @ 8351FCC
	.incbin "baserom.gba", 0x351FCC, 0x1C

SevenIsland_SevaultCanyon_House:: @ 8351FE8
	.incbin "baserom.gba", 0x351FE8, 0x1C

gMapGroup_00:: @ 8352004
	.4byte UnknownMap_00_00
	.4byte UnknownMap_00_01
	.4byte UnknownMap_00_02
	.4byte UnknownMap_00_03
	.4byte UnknownMap_00_04

gMapGroup_01:: @ 8352018
	.4byte ViridianForest
	.4byte MtMoon_1F
	.4byte MtMoon_B1F
	.4byte MtMoon_B2F
	.4byte SSAnne_Exterior
	.4byte SSAnne_1F_Corridor
	.4byte SSAnne_2F_Corridor
	.4byte SSAnne_3F_Corridor
	.4byte SSAnne_B1F_Corridor
	.4byte SSAnne_Deck
	.4byte SSAnne_Kitchen
	.4byte SSAnne_CaptainsOffice
	.4byte SSAnne_1F_Room1
	.4byte SSAnne_1F_Room2
	.4byte SSAnne_1F_Room3
	.4byte SSAnne_1F_Room4
	.4byte SSAnne_1F_Room5
	.4byte SSAnne_1F_Room7
	.4byte SSAnne_2F_Room1
	.4byte SSAnne_2F_Room2
	.4byte SSAnne_2F_Room3
	.4byte SSAnne_2F_Room4
	.4byte SSAnne_2F_Room5
	.4byte SSAnne_2F_Room6
	.4byte SSAnne_B1F_Room1
	.4byte SSAnne_B1F_Room2
	.4byte SSAnne_B1F_Room3
	.4byte SSAnne_B1F_Room4
	.4byte SSAnne_B1F_Room5
	.4byte SSAnne_1F_Room6
	.4byte UndergroundPath_NorthEntrance
	.4byte UndergroundPath_NorthSouthTunnel
	.4byte UndergroundPath_SouthEntrance
	.4byte UndergroundPath_WestEntrance
	.4byte UndergroundPath_EastWestTunnel
	.4byte UndergroundPath_EastEntrance
	.4byte DiglettsCave_NorthEntrance
	.4byte DiglettsCave_B1F
	.4byte DiglettsCave_SouthEntrance
	.4byte VictoryRoad_1F
	.4byte VictoryRoad_2F
	.4byte VictoryRoad_3F
	.4byte RocketHideout_B1F
	.4byte RocketHideout_B2F
	.4byte RocketHideout_B3F
	.4byte RocketHideout_B4F
	.4byte RocketHideout_Elevator
	.4byte SilphCo_1F
	.4byte SilphCo_2F
	.4byte SilphCo_3F
	.4byte SilphCo_4F
	.4byte SilphCo_5F
	.4byte SilphCo_6F
	.4byte SilphCo_7F
	.4byte SilphCo_8F
	.4byte SilphCo_9F
	.4byte SilphCo_10F
	.4byte SilphCo_11F
	.4byte SilphCo_Elevator
	.4byte PokemonMansion_1F
	.4byte PokemonMansion_2F
	.4byte PokemonMansion_3F
	.4byte PokemonMansion_B1F
	.4byte SafariZone_Center
	.4byte SafariZone_East
	.4byte SafariZone_North
	.4byte SafariZone_West
	.4byte SafariZone_Building1
	.4byte SafariZone_Building2
	.4byte SafariZone_Building3
	.4byte SafariZone_Building4
	.4byte SafariZone_SecretHouse
	.4byte CeruleanCave_1F
	.4byte CeruleanCave_2F
	.4byte CeruleanCave_B1F
	.4byte PokemonLeague_LoreleisRoom
	.4byte PokemonLeague_BrunosRoom
	.4byte PokemonLeague_AgathasRoom
	.4byte PokemonLeague_LancesRoom
	.4byte PokemonLeague_ChampionsRoom
	.4byte PokemonLeague_HallOfFame
	.4byte RockTunnel_1F
	.4byte RockTunnel_B1F
	.4byte SeafoamIslands_1F
	.4byte SeafoamIslands_B1F
	.4byte SeafoamIslands_B2F
	.4byte SeafoamIslands_B3F
	.4byte SeafoamIslands_B4F
	.4byte PokemonTower_1F
	.4byte PokemonTower_2F
	.4byte PokemonTower_3F
	.4byte PokemonTower_4F
	.4byte PokemonTower_5F
	.4byte PokemonTower_6F
	.4byte PokemonTower_7F
	.4byte PowerPlant
	.4byte MtEmber_RubyPath_B4F
	.4byte MtEmber_Exterior
	.4byte MtEmber_SummitPath_1F
	.4byte MtEmber_SummitPath_2F
	.4byte MtEmber_SummitPath_3F
	.4byte MtEmber_Summit
	.4byte MtEmber_RubyPath_B5F
	.4byte SSAnne_Kitchen3
	.4byte MtEmber_RubyPath_B1F
	.4byte MtEmber_RubyPath_B2F
	.4byte MtEmber_RubyPath_B3F
	.4byte MtEmber_RubyPath_B1F_Stairs
	.4byte MtEmber_RubyPath_B2F_Stairs
	.4byte ThreeIsland_BerryForest
	.4byte FourIsland_IcefallCave_Entrance
	.4byte FourIsland_IcefallCave_1F
	.4byte SSAnne_CaptainsOffice2
	.4byte SSAnne_CaptainsOffice3
	.4byte SSAnne_CaptainsOffice4
	.4byte SSAnne_CaptainsOffice5
	.4byte SixIsland_DottedHole_B1F
	.4byte SixIsland_DottedHole_B2F
	.4byte SixIsland_DottedHole_B3F
	.4byte SSAnne_CaptainsOffice9
	.4byte SixIsland_DottedHole_SapphireRoom
	.4byte SSAnne_1F_Room11
	.4byte SSAnne_1F_Room12

gMapGroup_02:: @ 8352204
	.4byte NavelRock_Exterior
	.4byte SevenIsland_TrainerTower_1F
	.4byte SevenIsland_TrainerTower_2F
	.4byte SevenIsland_TrainerTower_3F
	.4byte SevenIsland_TrainerTower_4F
	.4byte SevenIsland_TrainerTower_5F
	.4byte SevenIsland_TrainerTower_6F
	.4byte SevenIsland_TrainerTower_7F
	.4byte SevenIsland_TrainerTower_8F
	.4byte SevenIsland_TrainerTower_Roof
	.4byte SevenIsland_TrainerTower_Lobby
	.4byte SevenIsland_TrainerTower_Elevator
	.4byte FiveIsland_LostCave_Entrance
	.4byte FiveIsland_LostCave_Room1
	.4byte FiveIsland_LostCave_Room2
	.4byte FiveIsland_LostCave_Room3
	.4byte FiveIsland_LostCave_Room4
	.4byte FiveIsland_LostCave_Room5
	.4byte FiveIsland_LostCave_Room6
	.4byte FiveIsland_LostCave_Room7
	.4byte FiveIsland_LostCave_Room8
	.4byte FiveIsland_LostCave_Room9
	.4byte FiveIsland_LostCave_Room10
	.4byte FiveIsland_LostCave_Room11
	.4byte FiveIsland_LostCave_Room12
	.4byte FiveIsland_LostCave_Room13
	.4byte FiveIsland_LostCave_Room14
	.4byte SevenIsland_TanobyRuins_MoneanChamber
	.4byte SevenIsland_TanobyRuins_LiptooChamber
	.4byte SevenIsland_TanobyRuins_WeepthChamber
	.4byte SevenIsland_TanobyRuins_DilfordChamber
	.4byte SevenIsland_TanobyRuins_ScufibChamber
	.4byte SevenIsland_TanobyRuins_RixyChamber
	.4byte SevenIsland_TanobyRuins_ViapoisChamber
	.4byte ThreeIsland_DunsparceTunnel
	.4byte SevenIsland_SeavaultCanyon_TanobyKey
	.4byte NavelRock_1F
	.4byte NavelRock_Summit
	.4byte NavelRock_Base
	.4byte NavelRock_SummitPath_2F
	.4byte NavelRock_SummitPath_3F
	.4byte NavelRock_SummitPath_4F
	.4byte NavelRock_SummitPath_5F
	.4byte NavelRock_BasePath_B1F
	.4byte NavelRock_BasePath_B2F
	.4byte NavelRock_BasePath_B3F
	.4byte NavelRock_BasePath_B4F
	.4byte NavelRock_BasePath_B5F
	.4byte NavelRock_BasePath_B6F
	.4byte NavelRock_BasePath_B7F
	.4byte NavelRock_BasePath_B8F
	.4byte NavelRock_BasePath_B9F
	.4byte NavelRock_BasePath_B10F
	.4byte NavelRock_BasePath_B11F
	.4byte NavelRock_B1F
	.4byte NavelRock_Fork
	.4byte BirthIsland_Exterior
	.4byte OneIsland_KindleRoad_EmberSpa
	.4byte BirthIsland_Harbor
	.4byte NavelRock_Harbor

gMapGroup_03:: @ 83522F4
	.4byte PalletTown
	.4byte ViridianCity
	.4byte PewterCity
	.4byte CeruleanCity
	.4byte LavenderTown
	.4byte VermilionCity
	.4byte CeladonCity
	.4byte FuchsiaCity
	.4byte CinnabarIsland
	.4byte IndigoPlateau_Exterior
	.4byte SaffronCity_Duplicate
	.4byte SaffronCity
	.4byte OneIsland
	.4byte TwoIsland
	.4byte ThreeIsland
	.4byte FourIsland
	.4byte FiveIsland
	.4byte SevenIsland
	.4byte SixIsland
	.4byte Route1
	.4byte Route2
	.4byte Route3
	.4byte Route4
	.4byte Route5
	.4byte Route6
	.4byte Route7
	.4byte Route8
	.4byte Route9
	.4byte Route10
	.4byte Route11
	.4byte Route12
	.4byte Route13
	.4byte Route14
	.4byte Route15
	.4byte Route16
	.4byte Route17
	.4byte Route18
	.4byte Route19
	.4byte Route20
	.4byte Route21_North
	.4byte Route21_South
	.4byte Route22
	.4byte Route23
	.4byte Route24
	.4byte Route25
	.4byte OneIsland_KindleRoad
	.4byte OneIsland_TreasureBeach
	.4byte TwoIsland_CapeBrink
	.4byte ThreeIsland_BondBridge
	.4byte ThreeIsland_Port
	.4byte UnknownMap_03_50
	.4byte UnknownMap_03_51
	.4byte UnknownMap_03_52
	.4byte UnknownMap_03_53
	.4byte FiveIsland_ResortGorgeous
	.4byte FiveIsland_WaterLabyrinth
	.4byte FiveIsland_Meadow
	.4byte FiveIsland_MemorialPillar
	.4byte SixIsland_OutcastIsland
	.4byte SixIsland_GreenPath
	.4byte SixIsland_WaterPath
	.4byte SixIsland_RuinValley
	.4byte SevenIsland_TrainerTower
	.4byte SevenIsland_SevaultCanyon_Entrance
	.4byte SevenIsland_SevaultCanyon
	.4byte SevenIsland_TanobyRuins

gMapGroup_04:: @ 83523FC
	.4byte PalletTown_PlayersHouse_1F
	.4byte PalletTown_PlayersHouse_2F
	.4byte PalletTown_GarysHouse
	.4byte PalletTown_ProfessorOaksLab

gMapGroup_05:: @ 835240C
	.4byte ViridianCity_House1
	.4byte ViridianCity_Gym
	.4byte ViridianCity_House2
	.4byte ViridianCity_Mart
	.4byte ViridianCity_PokemonCenter_1F
	.4byte ViridianCity_PokemonCenter_2F

gMapGroup_06:: @ 8352424
	.4byte PewterCity_Museum_1F
	.4byte PewterCity_Museum_2F
	.4byte PewterCity_Gym
	.4byte PewterCity_Mart
	.4byte PewterCity_House1
	.4byte PewterCity_PokemonCenter_1F
	.4byte PewterCity_PokemonCenter_2F
	.4byte PewterCity_House2

gMapGroup_07:: @ 8352444
	.4byte CeruleanCity_House1
	.4byte CeruleanCity_House2
	.4byte CeruleanCity_House3
	.4byte CeruleanCity_PokemonCenter_1F
	.4byte CeruleanCity_PokemonCenter_2F
	.4byte CeruleanCity_Gym
	.4byte CeruleanCity_BikeShop
	.4byte CeruleanCity_Mart
	.4byte CeruleanCity_House4
	.4byte CeruleanCity_House5

gMapGroup_08:: @ 835246C
	.4byte LavenderTown_PokemonCenter_1F
	.4byte LavenderTown_PokemonCenter_2F
	.4byte LavenderTown_VolunteerPokemonHouse
	.4byte LavenderTown_House1
	.4byte LavenderTown_House2
	.4byte LavenderTown_Mart

gMapGroup_09:: @ 8352484
	.4byte VermilionCity_House1
	.4byte VermilionCity_PokemonCenter_1F
	.4byte VermilionCity_PokemonCenter_2F
	.4byte VermilionCity_PokemonFanClub
	.4byte VermilionCity_House2
	.4byte VermilionCity_Mart
	.4byte VermilionCity_Gym
	.4byte VermilionCity_House3

gMapGroup_10:: @ 83524A4
	.4byte CeladonCity_DepartmentStore_1F
	.4byte CeladonCity_DepartmentStore_2F
	.4byte CeladonCity_DepartmentStore_3F
	.4byte CeladonCity_DepartmentStore_4F
	.4byte CeladonCity_DepartmentStore_5F
	.4byte CeladonCity_DepartmentStore_Roof
	.4byte CeladonCity_DepartmentStore_Elevator
	.4byte CeladonCity_Condominiums_1F
	.4byte CeladonCity_Condominiums_2F
	.4byte CeladonCity_Condominiums_3F
	.4byte CeladonCity_Condominiums_Roof
	.4byte CeladonCity_Condominiums_RoofRoom
	.4byte CeladonCity_PokemonCenter_1F
	.4byte CeladonCity_PokemonCenter_2F
	.4byte CeladonCity_GameCorner
	.4byte CeladonCity_GameCorner_PrizeRoom
	.4byte CeladonCity_Gym
	.4byte CeladonCity_Restaurant
	.4byte CeladonCity_House1
	.4byte CeladonCity_Hotel

gMapGroup_11:: @ 83524F4
	.4byte FuchsiaCity_SafariZone_Entrance
	.4byte FuchsiaCity_Mart
	.4byte FuchsiaCity_ZooBuilding
	.4byte FuchsiaCity_Gym
	.4byte FuchsiaCity_House1
	.4byte FuchsiaCity_PokemonCenter_1F
	.4byte FuchsiaCity_PokemonCenter_2F
	.4byte FuchsiaCity_Building1
	.4byte FuchsiaCity_House2
	.4byte FuchsiaCity_House3

gMapGroup_12:: @ 835251C
	.4byte CinnabarIsland_Gym
	.4byte CinnabarIsland_PokemonLab_Entrance
	.4byte CinnabarIsland_PokemonLab_Lounge
	.4byte CinnabarIsland_PokemonLab_ResearchRoom
	.4byte CinnabarIsland_PokemonLab_ExperimentRoom
	.4byte CinnabarIsland_PokemonCenter_1F
	.4byte CinnabarIsland_PokemonCenter_2F
	.4byte CinnabarIsland_Mart

gMapGroup_13:: @ 835253C
	.4byte IndigoPlateau_PokemonCenter_1F
	.4byte IndigoPlateau_PokemonCenter_2F

gMapGroup_14:: @ 8352544
	.4byte SaffronCity_House1_1F
	.4byte SaffronCity_House1_2F
	.4byte SaffronCity_Dojo
	.4byte SaffronCity_Gym
	.4byte SaffronCity_House2
	.4byte SaffronCity_Mart
	.4byte SaffronCity_PokemonCenter_1F
	.4byte SaffronCity_PokemonCenter_2F
	.4byte SaffronCity_House3
	.4byte SaffronCity_PokemonTrainerFanClub

gMapGroup_15:: @ 835256C
	.4byte Route2_ViridianForest_SouthEntrance
	.4byte Route2_House
	.4byte Route2_EastBuilding
	.4byte Route2_ViridianForest_NorthEntrance

gMapGroup_16:: @ 835257C
	.4byte Route4_PokemonCenter_1F
	.4byte Route4_PokemonCenter_2F

gMapGroup_17:: @ 8352584
	.4byte Route5_PokemonDayCare
	.4byte Route5_SouthEntrance

gMapGroup_18:: @ 835258C
	.4byte Route6_NorthEntrance
	.4byte UnknownMap_18_01

gMapGroup_19:: @ 8352594
	.4byte Route7_EastEntrance

gMapGroup_20:: @ 8352598
	.4byte Route8_WestEntrance

gMapGroup_21:: @ 835259C
	.4byte Route10_PokemonCenter_1F
	.4byte Route10_PokemonCenter_2F

gMapGroup_22:: @ 83525A4
	.4byte Route11_EastEntrance_1F
	.4byte Route11_EastEntrance_2F

gMapGroup_23:: @ 83525AC
	.4byte Route12_NorthEntrance_1F
	.4byte Route12_NorthEntrance_2F
	.4byte Route12_FishingHouse

gMapGroup_24:: @ 83525B8
	.4byte Route15_WestEntrance_1F
	.4byte Route15_WestEntrance_2F

gMapGroup_25:: @ 83525C0
	.4byte Route16_House
	.4byte Route16_NorthEntrance_1F
	.4byte Route16_NorthEntrance_2F

gMapGroup_26:: @ 83525CC
	.4byte Route18_EastEntrance_1F
	.4byte Route18_EastEntrance_2F

gMapGroup_27:: @ 83525D4
	.4byte UnusedHouse_27_00

gMapGroup_28:: @ 83525D8
	.4byte Route22_NorthEntrance

gMapGroup_29:: @ 83525DC
	.4byte UnusedHouse_29_00

gMapGroup_30:: @ 83525E0
	.4byte Route25_SeaCottage

gMapGroup_31:: @ 83525E4
	.4byte SevenIsland_House_Room1
	.4byte SevenIsland_House_Room2
	.4byte SevenIsland_Mart
	.4byte SevenIsland_PokemonCenter_1F
	.4byte SevenIsland_PokemonCenter_2F
	.4byte UnusedHouse_31_05
	.4byte SevenIsland_Harbor

gMapGroup_32:: @ 8352600
	.4byte OneIsland_PokemonCenter_1F
	.4byte OneIsland_PokemonCenter_2F
	.4byte OneIsland_House1
	.4byte OneIsland_House2
	.4byte OneIsland_Harbor

gMapGroup_33:: @ 8352614
	.4byte TwoIsland_JoyfulGameCorner
	.4byte TwoIsland_House
	.4byte TwoIsland_PokemonCenter_1F
	.4byte TwoIsland_PokemonCenter_2F
	.4byte TwoIsland_Harbor

gMapGroup_34:: @ 8352628
	.4byte ThreeIsland_House1
	.4byte ThreeIsland_PokemonCenter_1F
	.4byte ThreeIsland_PokemonCenter_2F
	.4byte ThreeIsland_Mart
	.4byte ThreeIsland_House2
	.4byte ThreeIsland_House3
	.4byte ThreeIsland_House4
	.4byte ThreeIsland_House5

gMapGroup_35:: @ 8352648
	.4byte FourIsland_PokemonDayCare
	.4byte FourIsland_PokemonCenter_1F
	.4byte FourIsland_PokemonCenter_2F
	.4byte FourIsland_House1
	.4byte FourIsland_LoreleisHouse
	.4byte FourIsland_Harbor
	.4byte FourIsland_House2
	.4byte FourIsland_Mart

gMapGroup_36:: @ 8352668
	.4byte FiveIsland_PokemonCenter_1F
	.4byte FiveIsland_PokemonCenter_2F
	.4byte FiveIsland_Harbor
	.4byte FiveIsland_House1
	.4byte FiveIsland_House2

gMapGroup_37:: @ 835267C
	.4byte SixIsland_PokemonCenter_1F
	.4byte SixIsland_PokemonCenter_2F
	.4byte SixIsland_Harbor
	.4byte SixIsland_House
	.4byte SixIsland_Mart

gMapGroup_38:: @ 8352690
	.4byte ThreeIsland_Harbor

gMapGroup_39:: @ 8352694
	.4byte FiveIsland_ResortGorgeous_House

gMapGroup_40:: @ 8352698
	.4byte TwoIsland_CapeBrink_House

gMapGroup_41:: @ 835269C
	.4byte SixIsland_WaterPath_House1
	.4byte SixIsland_WaterPath_House2

gMapGroup_42:: @ 83526A4
	.4byte SevenIsland_SevaultCanyon_House

gMapGroups:: @ 0x83526A8
	.4byte gMapGroup_00
	.4byte gMapGroup_01
	.4byte gMapGroup_02
	.4byte gMapGroup_03
	.4byte gMapGroup_04
	.4byte gMapGroup_05
	.4byte gMapGroup_06
	.4byte gMapGroup_07
	.4byte gMapGroup_08
	.4byte gMapGroup_09
	.4byte gMapGroup_10
	.4byte gMapGroup_11
	.4byte gMapGroup_12
	.4byte gMapGroup_13
	.4byte gMapGroup_14
	.4byte gMapGroup_15
	.4byte gMapGroup_16
	.4byte gMapGroup_17
	.4byte gMapGroup_18
	.4byte gMapGroup_19
	.4byte gMapGroup_20
	.4byte gMapGroup_21
	.4byte gMapGroup_22
	.4byte gMapGroup_23
	.4byte gMapGroup_24
	.4byte gMapGroup_25
	.4byte gMapGroup_26
	.4byte gMapGroup_27
	.4byte gMapGroup_28
	.4byte gMapGroup_29
	.4byte gMapGroup_30
	.4byte gMapGroup_31
	.4byte gMapGroup_32
	.4byte gMapGroup_33
	.4byte gMapGroup_34
	.4byte gMapGroup_35
	.4byte gMapGroup_36
	.4byte gMapGroup_37
	.4byte gMapGroup_38
	.4byte gMapGroup_39
	.4byte gMapGroup_40
	.4byte gMapGroup_41
	.4byte gMapGroup_42
