ThreeIsland_PokemonCenter_2F_MapScripts:: @ 8171865
	map_script MAP_SCRIPT_ON_FRAME_TABLE, ThreeIsland_PokemonCenter_2F_MapScript1_1BB2A3
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, ThreeIsland_PokemonCenter_2F_MapScript2_1BB1ED
	map_script MAP_SCRIPT_ON_LOAD, ThreeIsland_PokemonCenter_2F_MapScript3_1BB237
	map_script MAP_SCRIPT_ON_TRANSITION, ThreeIsland_PokemonCenter_2F_MapScript4_1BB1B4
	.byte 0

ThreeIsland_PokemonCenter_2F_EventScript_17187A:: @ 817187A
	call EventScript_1BB4A3
	end

EventScript_171880:: @ 8171880
	call EventScript_1BB6AB
	end

EventScript_171886:: @ 8171886
	call EventScript_1BB7DE
	end
