ViridianForest_MapScripts:: @ 816051F
    map_script 3, ViridianForest_MapScript1_160525
    .byte 0

ViridianForest_MapScript1_160525:: @ 8160525
    setworldmapflag 2212
    end

ViridianForest_EventScript_160529:: @ 8160529
    loadword 0, gUnknown_8172255
    callstd 2
    end

ViridianForest_EventScript_160532:: @ 8160532
    loadword 0, gUnknown_8172559
    callstd 2
    end

ViridianForest_EventScript_16053B:: @ 816053B
    loadword 0, gUnknown_81725C7
    callstd 3
    end

ViridianForest_EventScript_160544:: @ 8160544
    loadword 0, gUnknown_8172629
    callstd 3
    end

ViridianForest_EventScript_16054D:: @ 816054D
    loadword 0, gUnknown_817265C
    callstd 3
    end

ViridianForest_EventScript_160556:: @ 8160556
    loadword 0, gUnknown_81726A3
    callstd 3
    end

ViridianForest_EventScript_16055F:: @ 816055F
    loadword 0, gUnknown_817271D
    callstd 3
    end

ViridianForest_EventScript_160568:: @ 8160568
    loadword 0, gUnknown_8172773
    callstd 3
    end

ViridianForest_EventScript_160571:: @ 8160571
    trainerbattle 0, 102, 0, Text_1722C7, Text_1722F9
    loadword 0, gUnknown_8172315
    callstd 6
    end

ViridianForest_EventScript_160588:: @ 8160588
    trainerbattle 0, 103, 0, Text_17234A, Text_17237D
    loadword 0, gUnknown_8172398
    callstd 6
    end

ViridianForest_EventScript_16059F:: @ 816059F
    trainerbattle 0, 104, 0, Text_1723D4, Text_172402
    loadword 0, gUnknown_817241F
    callstd 6
    end

ViridianForest_EventScript_1605B6:: @ 81605B6
    trainerbattle 0, 531, 0, Text_172482, Text_1724BF
    loadword 0, gUnknown_81724DC
    callstd 6
    end

ViridianForest_EventScript_1605CD:: @ 81605CD
    trainerbattle 0, 532, 0, Text_1724F9, Text_17251B
    loadword 0, gUnknown_8172527
    callstd 6
    end
