ViridianForest_Text_FriendsItchingToBattle::
    .string "{COLOR DARK_GRAY}¡Vine aquí con amigos para atrapar\n"
    .string "algunos {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} tipo {SHADOW DYNAMIC_COLOR4}BICHO{SHADOW LIGHT_GRAY}!\p"
    .string "Todos están ansiosos por\n"
    .string "participar en batallas {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}.$"

ViridianForest_Text_RickIntro::
    .string "{COLOR DARK_GRAY}¡Hey! Tú tienes {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}, ¿verdad?\n"
    .string "¡Ven, vamos a tener una batalla!$"

ViridianForest_Text_RickDefeat::
    .string "¡Nooo!\n¿CATERPIE, estás bien?$"

ViridianForest_Text_RickPostBattle::
    .string "{COLOR DARK_GRAY}¡Ssh!\n"
    .string "¡Vas a espantar a los bichos!...$"

ViridianForest_Text_DougIntro::
    .string "{COLOR DARK_GRAY}¡Eh!\p"
    .string "¡Hay que tener disciplina para ser\n"
    .string "{SHADOW DYNAMIC_COLOR4}ENTRENADOR POKÉMON{SHADOW LIGHT_GRAY}!$"

ViridianForest_Text_DougDefeat::
    .string "¿SERÁ POSIBLE?\n"
    .string "¡NO ME QUEDAN MÁS POKÉMON!$"

ViridianForest_Text_DougPostBattle::
    .string "{COLOR DARK_GRAY}¡Vaya! \n"
    .string "¡Voy a atrapar unos más fuertes!$"

ViridianForest_Text_SammyIntro::
    .string "{COLOR DARK_GRAY}¡Eh, espera!\n"
    .string "¿Por qué tienes tanta prisa?$"

ViridianForest_Text_SammyDefeat::
    .string "¡ME RINDO!\n"
    .string "¡ERES DEMASIADO FUERTE!$"

ViridianForest_Text_SammyPostBattle::
    .string "{COLOR DARK_GRAY}¡A veces puedes encontrar cosas\n"
    .string "en el suelo!\p"
    .string "¡Estoy buscando los objetos que\n"
    .string "se me cayeron!$"

ViridianForest_Text_AnthonyIntro::
    .string "{COLOR DARK_GRAY}Estoy obsesionado con la belleza\n"
    .string "del {SHADOW DYNAMIC_COLOR4}BOSQUE VERDE{SHADOW LIGHT_GRAY}...$"

ViridianForest_Text_AnthonyDefeat::
    .string "¡OH!\n"
    .string "¡TUS POKéMON SON MUY FUERTES!$"

ViridianForest_Text_AnthonyPostBattle::
    .string "{COLOR DARK_GRAY}Parece que estoy un poco\n"
    .string "deshidratado...\p"
    .string "Llevo horas aqui admirando la\n"
    .string "naturaleza...$"

ViridianForest_Text_NPC::
    .string "No quiero luchar, solo estoy esperando\n"
    .string "el momento perfecto para atrapar mi\l"
    .string "próximo {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}.$"

ViridianForest_Text_CharlieIntro::
    .string "{COLOR DARK_GRAY}¿Has experimentado alguna vez la\n"
    .string "emoción de ver a tus {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}\l"
    .string "evolucionar?$"

ViridianForest_Text_CharlieDefeat::
    .string "¡OH!\n"
    .string "¡HE PERDIDO!$"

ViridianForest_Text_CharliePostBattle::
    .string "{COLOR DARK_GRAY}Es sorprendente lo rápido que\n"
    .string "evolucionan los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}.$"

ViridianForest_Text_RanOutOfPokeBalls::
    .string "{COLOR DARK_GRAY}¡Estaba lanzando {SHADOW DYNAMIC_COLOR4}POKé BALLS{SHADOW LIGHT_GRAY} para\n"
    .string "atrapar {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} y de repente se\l"
    .string "escapó!\p"
    .string "Por eso siempre es bueno llevar\n"
    .string "muchas {SHADOW DYNAMIC_COLOR4}POKé BALLS{SHADOW LIGHT_GRAY}.$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
    .string "{SHADOW DYNAMIC_COLOR4}PISTAS ENTRENADOR{SHADOW LIGHT_GRAY}\p"
    .string "¡Debilita a los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} antes\n"
    .string "de intentar capturarlos!\p"
    .string "¡Si están fuertes, podrían escapar!$"

ViridianForest_Text_UseAntidoteForPoison::
    .string "{SHADOW DYNAMIC_COLOR4}PISTAS ENTRENADOR{SHADOW LIGHT_GRAY}\p"
    .string "¡Usa {SHADOW DYNAMIC_COLOR4}ANTÍDOTO{SHADOW LIGHT_GRAY} contra el veneno!\p"
    .string "¡Lo conseguirás en las {SHADOW DYNAMIC_COLOR4}TIENDAS\n"
    .string "POKéMON{SHADOW LIGHT_GRAY}!$"
    

ViridianForest_Text_ContactOakViaPCToRatePokedex::
    .string "{SHADOW DYNAMIC_COLOR4}PISTAS ENTRENADOR{SHADOW LIGHT_GRAY}\p"
    .string "¡Para evaluar tu {SHADOW DYNAMIC_COLOR4}POKéDEX{SHADOW LIGHT_GRAY}, llama\n"
    .string "al {SHADOW DYNAMIC_COLOR4}PROF. OAK{SHADOW LIGHT_GRAY} vía {SHADOW DYNAMIC_COLOR4}PC{SHADOW LIGHT_GRAY}!$"

ViridianForest_Text_CantCatchOwnedMons::
    .string "{SHADOW DYNAMIC_COLOR4}PISTAS ENTRENADOR{SHADOW LIGHT_GRAY}\p"
    .string "¡No robes los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} de otros\n"
    .string "{SHADOW DYNAMIC_COLOR4}ENTRENADORES{SHADOW LIGHT_GRAY}!\p"
    .string "¡Captura sólo {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} salvajes\n"
    .string "con las {SHADOW DYNAMIC_COLOR4}POKé BALLS{SHADOW LIGHT_GRAY}!$"

ViridianForest_Text_WeakenMonsBeforeCapture::
    .string "{SHADOW DYNAMIC_COLOR4}PISTAS ENTRENADOR{SHADOW LIGHT_GRAY}\p"
    .string "¡Debilita a los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} antes\n"
    .string "de intentar capturarlos!\p"
    .string "¡Si están fuertes, podrían escapar!$"

ViridianForest_Text_LeavingViridianForest::
    .string "{SHADOW DYNAMIC_COLOR4}BOSQUE VERDE\n"
    .string "{UP_ARROW_2}{SHADOW LIGHT_GRAY} RUTA 2 NORTE$"

ViridianForest_Text_Batalla1_Rojo::
    .string "{SHADOW DYNAMIC_COLOR4}ROJO:{SHADOW LIGHT_GRAY} ¡Mira donde te encuentro!\p"
    .string "¿Cómo va la búsqueda de nuevos\n"
    .string "{SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}?$"

ViridianForest_Text_Batalla2_Rojo::
    .string "{SHADOW DYNAMIC_COLOR4}ROJO:{SHADOW LIGHT_GRAY} ¡Te dije que el {SHADOW DYNAMIC_COLOR4}BOSQUE VERDE{SHADOW LIGHT_GRAY}\n"
    .string "era fascinante!\p"
    .string "Además de tener una gran variedad\n"
    .string "de {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}.\p"
    .string "Me encantaría ver qué nuevas\n"
    .string "especies has registrado...$"

ViridianForest_Text_Batalla3_Rojo::
    .string "¡TIENES UN EQUIPO IMPRESIONANTE!$"

ViridianForest_Text_Batalla4_Rojo::
    .string "{SHADOW DYNAMIC_COLOR4}ROJO:{SHADOW LIGHT_GRAY} Creo que es hora de que me vaya...\n"
    .string "Todavía nos queda mucho camino\l"
    .string "por delante.$"


ViridianForest_Text_Batalla5_Rojo::
    .string "{SHADOW DYNAMIC_COLOR4}ROJO:{SHADOW LIGHT_GRAY} ¡Soy tan despistado!\n"
    .string "Casi me voy sin entregarte esto...$"

ViridianForest_Text_RepExpRojo::
    .string "{SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY} obtuvo {SHADOW DYNAMIC_COLOR4}REPARTIR EXP.{SHADOW LIGHT_GRAY}\n"
    .string "de manos de {SHADOW DYNAMIC_COLOR4}ROJO{SHADOW LIGHT_GRAY}.$"

ViridianForest_Text_Batalla6_Rojo::
    .string "{SHADOW DYNAMIC_COLOR4}ROJO{SHADOW LIGHT_GRAY}: El {SHADOW DYNAMIC_COLOR4}REPARTIR EXP.{SHADOW LIGHT_GRAY} es un objeto\n"
    .string "que un {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} puede llevar consigo.\p"
    .string "Con este objeto, el {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} que lo\n"  
    .string "tenga ganará puntos de experiencia,\l"
    .string "incluso si no se encuentra\l"
    .string "en combate.\p"
    .string "Estoy seguro de que te será de\n"  
    .string "gran ayuda en tu aventura.$"

ViridianForest_Text_BosqueVerde::
    .string "{SHADOW DYNAMIC_COLOR4}BOSQUE VERDE{SHADOW LIGHT_GRAY}\p"
    .string "Entre sombras y laberintos los\n"
    .string "{SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} danzan en la penumbra.$"