ViridianForest_Text_FriendsItchingToBattle:: @ 8172255
    .string "I came here with some friends to\n"
    .string "catch us some Bug Pokémon!\p"
    .string "They're all itching to get into\n"
    .string "some Pokémon battles!$"

ViridianForest_Text_RickIntro:: @ 81722C7
    .string "Hey! You have Pokémon!\n"
    .string "Come on!\l"
    .string "Let's battle 'em!$"

ViridianForest_Text_RickDefeat:: @ 81722F9
    .string "No!\nCaterpie can't hack it!$"

ViridianForest_Text_RickPostBattle:: @ 8172315
    .string "Ssh! You'll scare the bugs away.\n"
    .string "Another time, okay?$"

ViridianForest_Text_DougIntro:: @ 817234A
    .string "Yo!\n"
    .string "You can't jam out if you're a\l"
    .string "Pokémon Trainer!$"

ViridianForest_Text_DougDefeat:: @ 817237D
    .string "Huh?\n"
    .string "I ran out of Pokémon!$"

ViridianForest_Text_DougPostBattle:: @ 8172398
    .string "That totally stinks! I'm going to\n"
    .string "catch some stronger ones!$"

ViridianForest_Text_SammyIntro:: @ 81723D4
    .string "Hey, wait up!\n"
    .string "What's the hurry? Why the rush?$"

ViridianForest_Text_SammyDefeat:: @ 8172402
    .string "I give!\n"
    .string "You're good at this!$"

ViridianForest_Text_SammyPostBattle:: @ 817241F
    .string "Sometimes, you can find stuff on\n"
    .string "the ground.\p"
    .string "I'm looking for the stuff I\n"
    .string "dropped. Can you help me?$"

ViridianForest_Text_AnthonyIntro:: @ 8172482
    .string "I might be little, but I won't like\n"
    .string "it if you go easy on me!$"

ViridianForest_Text_AnthonyDefeat:: @ 81724BF
    .string "Oh, boo.\n"
    .string "Nothing went right.$"

ViridianForest_Text_AnthonyPostBattle:: @ 81724DC
    .string "I lost some of my allowance…$"

ViridianForest_Text_CharlieIntro:: @ 81724F9
    .string "Did you know that Pokémon evolve?$"

ViridianForest_Text_CharlieDefeat:: @ 817251B
    .string "Oh!\n"
    .string "I lost!$"

ViridianForest_Text_CharliePostBattle:: @ 8172527
    .string "Bug Pokémon evolve quickly.\n"
    .string "They're a lot of fun!$"

ViridianForest_Text_RanOutOfPokeBalls:: @ 8172559
    .string "I was throwing Poké Balls to\n"
    .string "catch Pokémon, and I ran out.\p"
    .string "That's why you can never have too\n"
    .string "many Poké Balls.$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak:: @ 81725C7
    .string "Trainer Tips\p"
    .string "If your Pokémon are weak and you\n"
    .string "want to avoid battles, stay away\l"
    .string "from grassy areas!$"

ViridianForest_Text_UseAntidoteForPoison:: @ 8172629
    .string "For poison, use Antidote!\n"
    .string "Get it at Pokémon Marts!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex:: @ 817265C
    .string "Trainer Tips\p"
    .string "Contact Prof. Oak via a PC to\n"
    .string "get your Pokédex evaluated!$"

ViridianForest_Text_CantCatchOwnedMons:: @ 81726A3
    .string "Trainer Tips\p"
    .string "You can't catch a Pokémon that\n"
    .string "belongs to someone else.\p"
    .string "Throw Poké Balls only at wild\n"
    .string "Pokémon to catch them!$"

ViridianForest_Text_WeakenMonsBeforeCapture:: @ 817271D
    .string "Trainer Tips\p"
    .string "Weaken Pokémon before attempting\n"
    .string "capture!\p"
    .string "When healthy, they may escape!$"

ViridianForest_Text_LeavingViridianForest:: @ 8172773
    .string "Leaving Viridian Forest\n"
    .string "Pewter City Ahead$"

