SevenIsland_House_Room1_Text_OnlyEnjoymentWatchingBattles::
    .string "I may not look like much now,\n"
    .string "but when I was younger…\p"
    .string "I flew everywhere, challenging\n"
    .string "TRAINERS wherever I found them.\p"
    .string "Now, my only source of enjoyment\n"
    .string "is reminiscing about the past while\l"
    .string "watching battles.$"

SevenIsland_House_Room1_Text_SlightBreezeAroundBox::
    .string "There is a slight breeze blowing\n"
    .string "around the box.$"

SevenIsland_House_Room1_Text_ChallengeVisitingTrainer::
    .string "Ah!\n"
    .string "Welcome, my friend!\p"
    .string "Let me tell you something. There's\n"
    .string "a hidden room in the basement.\p"
    .string "A TRAINER named {STR_VAR_1} is\n"
    .string "waiting there now.\p"
    .string "Tell me, you did come to challenge\n"
    .string "{STR_VAR_1}, am I right?$"

SevenIsland_House_Room1_Text_OhYouWontBattle::
    .string "Oh…\n"
    .string "You won't battle…\p"
    .string "I see, I see.\n"
    .string "… …\p"
    .string "Well, perhaps if you change your\n"
    .string "mind, do come back.$"

SevenIsland_House_Room1_Text_LimitThreeMonsPerSide::
    .string "Ah!\n"
    .string "You will battle for me?\p"
    .string "It was worth my time moving the\n"
    .string "box aside, then.\p"
    .string "… …\n"
    .string "But there is one slight problem.\p"
    .string "This hidden room is not built very\n"
    .string "sturdy.\p"
    .string "Can I get you to limit it to\n"
    .string "battles of three POKéMON per side?$"

SevenIsland_House_Room1_Text_SaveProgressBeforeBattle::
    .string "Fine! Before your battle, would\n"
    .string "you like to save your game?$"

SevenIsland_House_Room1_Text_DontHoldAnythingBack::
    .string "All right.\n"
    .string "Don't hold anything back!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_1::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room2_Text_MatchEndedUpDraw::
    .string "The match ended up a draw.$"

SevenIsland_House_Room1_Text_DrawWasIt::
    .string "A draw, was it?\p"
    .string "However, let me say that it was\n"
    .string "a worthy spectacle.\p"
    .string "I'd say it was a wonderful battle\n"
    .string "with a real sense of depth!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_2::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_AstoundingBattle::
    .string "Bravo!\p"
    .string "Bravo, indeed!\n"
    .string "What an astounding battle!\p"
    .string "It was so astounding, why, it keeps\n"
    .string "filling my eyes with tears!\p"
    .string "The thrust and parry of expertly\n"
    .string "used techniques!\p"
    .string "The clash of power upon power!\p"
    .string "Yes!\n"
    .string "It was sheer magnificence!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_3::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_FeelYourDisappointment::
    .string "Too bad!\n"
    .string "I feel your disappointment.\p"
    .string "However, that disappointment is\n"
    .string "what will make you better.\p"
    .string "Use it, learn from it, and make it\n"
    .string "motivate you to seek greatness.\p"
    .string "Forget not this disappointment\n"
    .string "and redouble your training!$"

