FiveIsland_House1_JPText_HusbandWentOffFishing:: @ 81A3C71
    .string "こんばんの　おかずは\n"
    .string "ようい　しなくて　いいぞ！\p"
    .string "って　だんなが\n"
    .string "つりに　いったん　だけど‥\l"
    .string "しんじて　いいのかねえ$"

FiveIsland_House1_Text_HusbandWentOffFishing:: @ 81A3CAC
    .string "Don't worry about buying anything\n"
    .string "for dinner tonight!\p"
    .string "…That's what my husband said when\n"
    .string "he went off fishing today.\p"
    .string "I'm not sure if I can count on him\n"
    .string "to live up to that promise.$"

