MtMoon_B2F_Text_MiguelIntro::
    .string "¡Oye, detente!\p"
    .string "¡Encontré estos fósiles!\n"
    .string "¡Los dos son míos!$"

MtMoon_B2F_Text_MiguelDefeat::
    .string "¡ESTÁ BIEN!\n"
    .string "¡COMPARTIRÉ!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
    .string "¡Cada uno tomará un fósil!\n"
    .string "¡Nada de avaricia!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
    .string "Muy bien.\n"
    .string "¡Entonces este fósil es mío!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
    .string "Muy lejos, en la {SHADOW DYNAMIC_COLOR4}ISLA CANELA{SHADOW LIGHT_GRAY},\n"
    .string "hay un {SHADOW DYNAMIC_COLOR4}LABORATORIO POKéMON{SHADOW LIGHT_GRAY}.\p"
    .string "Allí investigan cómo regenerar\n"
    .string "fósiles.$"

MtMoon_B2F_Text_Grunt1Intro::
    .string "Nosotros, el {SHADOW DYNAMIC_COLOR4}EQUIPO ROCKET{SHADOW LIGHT_GRAY},\n"
    .string "¡encontraremos los fósiles!\p"
    .string "Revivir {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} con ellos haremos\n"
    .string "enormes riquezas!$"

MtMoon_B2F_Text_Grunt1Defeat::
    .string "¡ARGH!\n"
    .string "¡AHORA ESTOY FURIOSO!$"

MtMoon_B2F_Text_Grunt1PostBattle::
    .string "¡Me hiciste enojar!\p"
    .string "¡El {SHADOW DYNAMIC_COLOR4}EQUIPO ROCKET{SHADOW LIGHT_GRAY} te pondrá en\n"
    .string "su lista negra!$"

MtMoon_B2F_Text_Grunt2Intro::
    .string "Nosotros, el {SHADOW DYNAMIC_COLOR4}EQUIPO ROCKET{SHADOW LIGHT_GRAY}, somos\n"
    .string "gánsteres {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}!\p"
    .string "¡Infundimos miedo con nuestra fuerza!$"

MtMoon_B2F_Text_Grunt2Defeat::
    .string "¡LA ARRUINÉ!$"

MtMoon_B2F_Text_Grunt2PostBattle::
    .string "¡Rayos!\n"
    .string "¡Mis compañeros no soportarán esto!$"

MtMoon_B2F_Text_Grunt3Intro::
    .string "¡Estamos trabajando aquí!\n"
    .string "¡Lárgate, niñ{OA}!$"

MtMoon_B2F_Text_Grunt3Defeat::
    .string "ASÍ QUE ERES BUENO…$"

MtMoon_B2F_Text_Grunt3PostBattle::
    .string "¡Si encuentras un fósil, dámelo \n"
    .string "y lárgate!$"

MtMoon_B2F_Text_Grunt4Intro::
    .string "¡L{OA}s niñ{OA}s no deberían meterse\n"
    .string "con los adultos!\p"
    .string "¡Podría acabar mal!$"

MtMoon_B2F_Text_Grunt4Defeat::
    .string "¡ESTOY QUE ARDO!$"

MtMoon_B2F_Text_Grunt4PostBattle::
    .string "Los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} vivían aquí mucho antes\n"
    .string "de que llegara la gente.$"

MtMoon_B2F_Text_YouWantDomeFossil::
    .string "¿Quieres el {SHADOW DYNAMIC_COLOR4}FÓSIL DOMO{SHADOW LIGHT_GRAY}?$"

MtMoon_B2F_Text_YouWantHelixFossil::
    .string "¿Quieres el {SHADOW DYNAMIC_COLOR4}FÓSIL HÉLIX{SHADOW LIGHT_GRAY}?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
    .string "¡Obtuviste el {SHADOW DYNAMIC_COLOR4}FÓSIL HÉLIX{SHADOW LIGHT_GRAY}!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
    .string "¡Obtuviste el {SHADOW DYNAMIC_COLOR4}FÓSIL DOMO{SHADOW LIGHT_GRAY}!$"

MtMoon_B2F_Text_Jessie_Intro::
    .string "¡Alto ahí, mocos{OA}!\n"
    .string "Ese fósil ya tiene dueños.$"

MtMoon_B2F_Text_James_Intro::
    .string "Entrégalo ahora ya...\n"
    .string "o tendremos que actuar.$"

MtMoon_B2F_Text_Jessie_Reveal::
    .string "¿Que no nos reconoces?\n"
    .string "Soy {SHADOW DYNAMIC_COLOR4}JESSIE{SHADOW LIGHT_GRAY} del {SHADOW DYNAMIC_COLOR4}EQUIPO ROCKET{SHADOW LIGHT_GRAY}.$"

MtMoon_B2F_Text_James_RevealFemale::
    .string "...y yo soy {SHADOW DYNAMIC_COLOR4}JAMES{SHADOW LIGHT_GRAY}.\n"
    .string "No te harás la heroína con nosotros.$"

MtMoon_B2F_Text_James_RevealMale::
    .string "...y yo soy {SHADOW DYNAMIC_COLOR4}JAMES{SHADOW LIGHT_GRAY}.\n"
    .string "No te harás el héroe con nosotros.$"

MtMoon_B2F_Text_Jessie_DoubleChallenge::
    .string "¿Te crees valiente?\n"
    .string "¡Nos enfrentarás a los dos!$"

MtMoon_B2F_Text_James_DoubleChallenge::
    .string "¡Batalla doble!\n"
    .string "Verás lo que es el trabajo en equipo.$"

MtMoon_B2F_Text_Jessie_RunAway::
    .string "Esto no acaba aquí...$"

MtMoon_B2F_Text_James_RunAway::
    .string "...¡El {SHADOW DYNAMIC_COLOR4}EQUIPO ROCKET{SHADOW LIGHT_GRAY} volverá por ti!$"

MtMoon_B2F_Text_Jessie_James_Defeat::
    .string "¡IMPOSIBLE!\n"
    .string "¡NUESTRO DÚO PERFECTO... DERROTADO!$"