FiveIsland_LostCave_Room1_EventObjects:
	object_event 1, 56, 0, 5, 0, 4, 0, 3, 2, 17, 0, 1, 0, 1, 0, FiveIsland_LostCave_Room1_EventScript_164BF7, 0, 0, 0

FiveIsland_LostCave_Room1_MapWarps:
	warp_def 8, 2, 3, 1, 524
	warp_def 5, 1, 3, 3, 525
	warp_def 8, 5, 3, 3, 526
	warp_def 5, 8, 3, 1, 525
	warp_def 2, 5, 3, 2, 525

FiveIsland_LostCave_Room1_MapEvents::
	map_events FiveIsland_LostCave_Room1_EventObjects, FiveIsland_LostCave_Room1_MapWarps, 0x0, 0x0
