FiveIsland_LostCave_Room1_Text_LawsonIntro:: @ 817CEF5
    .string "Aiyeeeeeh!\p"
    .string "I thought this was an ancient ruin.\n"
    .string "But it's teeming with ghosts!$"

FiveIsland_LostCave_Room1_Text_LawsonDefeat:: @ 817CF42
    .string "Aiyeeeeeh!\n"
    .string "Mercy!$"

FiveIsland_LostCave_Room1_Text_LawsonPostBattle:: @ 817CF54
    .string "I'm trying to get out of here, but\n"
    .string "I always end up at the same spot.\p"
    .string "Maybe the number of boulders is\n"
    .string "a hint…$"

