TwoIsland_JoyfulGameCorner_EventObjects:
	object_event 1, 30, 0, 5, 0, 5, 0, 1, 10, 17, 0, 0, 0, 0, 0, TwoIsland_JoyfulGameCorner_EventScript_17155F, 0, 0, 0
	object_event 2, 53, 0, 5, 0, 8, 0, 3, 7, 17, 0, 0, 0, 0, 0, 0x0, 116, 0, 0
	object_event 3, 17, 0, 6, 0, 5, 0, 1, 9, 17, 0, 0, 0, 0, 0, TwoIsland_JoyfulGameCorner_EventScript_17160C, 117, 0, 0
	object_event 4, 25, 0, 4, 0, 2, 0, 3, 8, 17, 0, 0, 0, 0, 0, TwoIsland_JoyfulGameCorner_EventScript_171535, 0, 0, 0

TwoIsland_JoyfulGameCorner_MapWarps:
	warp_def 5, 8, 3, 0, 781

TwoIsland_JoyfulGameCorner_MapBGEvents:
	bg_event 1, 1, 0, 0, 0, TwoIsland_JoyfulGameCorner_EventScript_1BC2E7
	bg_event 0, 1, 0, 0, 0, TwoIsland_JoyfulGameCorner_EventScript_1BC2FC

TwoIsland_JoyfulGameCorner_MapEvents::
	map_events TwoIsland_JoyfulGameCorner_EventObjects, TwoIsland_JoyfulGameCorner_MapWarps, 0x0, TwoIsland_JoyfulGameCorner_MapBGEvents
