gUnknown_81A2408:: @ 81A2408
    .string "Now, where's LOSTELLE gotten to\n"
    .string "today?\p"
    .string "She always brings me lunch every\n"
    .string "day right about now…$"

gUnknown_81A2465:: @ 81A2465
    .string "Hm? You, there!\n"
    .string "Are you a friend of LOSTELLE's?\p"
    .string "Have you seen LOSTELLE around?\n"
    .string "I don't know where she might be.\l"
    .string "She should've been here long ago.\p"
    .string "LOSTELLE's a cutie - she got my\n"
    .string "looks - so what if someone…\p"
    .string "What if something's happened to\n"
    .string "my LOSTELLE?!\p"
    .string "Please, help me find her!\n"
    .string "Please go search THREE ISLAND!$"

gUnknown_81A259A:: @ 81A259A
    .string "Hah? What is this GAME CORNER?\n"
    .string "How much sadder can this get?\p"
    .string "Those clowns…\p"
    .string "They said they'd be waiting on the\n"
    .string "island, so where are they?\p"
    .string "Hey, you! Is this the only THREE\n"
    .string "ISLAND around here?$"

gUnknown_81A2658:: @ 81A2658
    .string "Try waking up before you crawl out\n"
    .string "of bed, you punk.\p"
    .string "This is TWO ISLAND!\p"
    .string "Move it! Get your filthy motorbike\n"
    .string "out of my place!$"

gUnknown_81A26D5:: @ 81A26D5
    .string "Huh…\n"
    .string "Oh, oh, gotcha.\p"
    .string "Tch…\n"
    .string "These islands are confusing…$"

gUnknown_81A270C:: @ 81A270C
    .string "Would you look at that?\n"
    .string "That punk scuffed up my floor.$"

gUnknown_81A2743:: @ 81A2743
    .string "Hey, but listen! I'm begging you,\n"
    .string "you have to go to THREE ISLAND.\p"
    .string "If anything were to happen to my\n"
    .string "LOSTELLE…\p"
    .string "My place is the house with the red\n"
    .string "roof on THREE ISLAND.\p"
    .string "She may just show up late here,\n"
    .string "so I can't run off anywhere.\p"
    .string "That's why I have to get you to do\n"
    .string "me this big favor.$"

gUnknown_81A285C:: @ 81A285C
    .string "I'm sorry.\n"
    .string "We're not running any games today.$"

gUnknown_81A288A:: @ 81A288A
    .string "We'll get the games going soon\n"
    .string "for you!$"

gUnknown_81A28B2:: @ 81A28B2
    .string "So you rescued LOSTELLE?\n"
    .string "How can I thank you?\p"
    .string "LOSTELLE, darling, forgive me!\p"
    .string "Daddy didn't know you were scared\n"
    .string "and in trouble!$"

gUnknown_81A2931:: @ 81A2931
    .string "LOSTELLE: It's okay, Daddy.\n"
    .string "I got to be friends with {PLAYER}!$"

gUnknown_81A296A:: @ 81A296A
    .string "Oh, what's that?\n"
    .string "You're saying that this is for me?\p"
    .string "How did you know that I love rare\n"
    .string "rocks and gems?\p"
    .string "You sure know how to make a guy\n"
    .string "happy.$"

Text_1A29F7:: @ 81A29F7
    .string "{PLAYER} handed the METEORITE\n"
    .string "to LOSTELLE's daddy.$"

gUnknown_81A2A24:: @ 81A2A24
    .string "Oh, I see, this is from BILL!\n"
    .string "You have to thank him for me!\p"
    .string "You know, you've been fantastic.\n"
    .string "I want you to have this.$"

gUnknown_81A2A9A:: @ 81A2A9A
    .string "{PLAYER} received a MOON STONE\n"
    .string "from LOSTELLE's daddy.$"

gUnknown_81A2ACA:: @ 81A2ACA
    .string "Your BAG's not going to fit another\n"
    .string "thing…$"

gUnknown_81A2AF5:: @ 81A2AF5
    .string "All right, I'll get the GAME CORNER\n"
    .string "running right away.\p"
    .string "You have to come visit with a\n"
    .string "friend.$"

gUnknown_81A2B53:: @ 81A2B53
    .string "Listen, listen!\p"
    .string "Please show me you being cool\n"
    .string "again!$"

