Text_1882E1:: @ 81882E1
    .string "Strong TRAINERS and WATER POKéMON\n"
    .string "are common sights in these parts.\p"
    .string "They say that MISTY of the\n"
    .string "CERULEAN GYM trains here.$"

Text_18835A:: @ 818835A
    .string "You want to know if the fish are\n"
    .string "biting?$"

Text_188383:: @ 8188383
    .string "Dang!$"

Text_188389:: @ 8188389
    .string "I can't catch anything good.\n"
    .string "Not one good POKéMON to be had!$"

Text_1883C6:: @ 81883C6
    .string "I got a big haul!\n"
    .string "Wanna go for it?$"

Text_1883E9:: @ 81883E9
    .string "Heheh, MAGIKARP just don't make\n"
    .string "the grade, do they?$"

Text_18841D:: @ 818841D
    .string "I seem to only catch MAGIKARP!$"

Text_18843C:: @ 818843C
    .string "The sea cleanses my body and soul!$"

Text_18845F:: @ 818845F
    .string "Ayah!$"

Text_188465:: @ 8188465
    .string "The sea is great and all, but I\n"
    .string "like the mountains, too.$"

Text_18849E:: @ 818849E
    .string "おれだって　たまには\n"
    .string "およぎに　くるぜ！$"

Text_1884B3:: @ 81884B3
    .string "ぐわわ！$"

Text_1884B8:: @ 81884B8
    .string "うきやすそう　だと？\n"
    .string "うるせー　おおきな　おせわだッ！$"

Text_1884D4:: @ 81884D4
    .string "I caught my POKéMON at sea.$"

Text_1884F0:: @ 81884F0
    .string "Diver!!\n"
    .string "Down!!$"

Text_1884FF:: @ 81884FF
    .string "Where'd you catch your POKéMON?$"

Text_18851F:: @ 818851F
    .string "Right now, I'm in a triathlon meet.$"

Text_188543:: @ 8188543
    .string "Pant…\n"
    .string "Pant… Pant…$"

Text_188555:: @ 8188555
    .string "I'm beat! But, I still have the\n"
    .string "bike race and marathon left!$"

Text_188592:: @ 8188592
    .string "Ahh!\n"
    .string "Feel the sun and the wind!$"

Text_1885B2:: @ 81885B2
    .string "Yow!\n"
    .string "I lost!$"

Text_1885BF:: @ 81885BF
    .string "I'm sunburnt to a crisp!$"

Text_1885D8:: @ 81885D8
    .string "Hey, don't scare away the fish!$"

Text_1885F8:: @ 81885F8
    .string "Sorry! I'm just so frustrated from\n"
    .string "not catching anything.$"

Text_188632:: @ 8188632
    .string "Sheesh, I haven't caught a thing.\n"
    .string "Could this place actually be a\l"
    .string "giant pool or something?$"

Text_18868C:: @ 818868C
    .string "Keep me company till I get a hit.$"

Text_1886AE:: @ 81886AE
    .string "That burned some time.$"

Text_1886C5:: @ 81886C5
    .string "Oh wait!\n"
    .string "I got a bite! Yeah!$"

Text_1886E2:: @ 81886E2
    .string "LIL: Huh? A battle?\n"
    .string "IAN, can't you do it alone?$"

Text_188712:: @ 8188712
    .string "LIL: Oh, see?\n"
    .string "We lost. Happy now?$"

Text_188734:: @ 8188734
    .string "LIL: I'm tired.\n"
    .string "Can't we go home already?$"

Text_18875E:: @ 818875E
    .string "LIL: Huh? A battle?\n"
    .string "I can't be bothered to do it alone.\l"
    .string "Bring two POKéMON, won't you?$"

Text_1887B4:: @ 81887B4
    .string "IAN: My sis doesn't get enough\n"
    .string "exercise, so I made her come.$"

Text_1887F1:: @ 81887F1
    .string "IAN: Awww, Sis!\n"
    .string "Get it together!$"

Text_188812:: @ 8188812
    .string "IAN: Come on, Sis!\p"
    .string "You're not going to lose weight\n"
    .string "like this!$"

Text_188850:: @ 8188850
    .string "IAN: We want a two-on-two battle.\n"
    .string "So can you bring two POKéMON?$"

gUnknown_8188890:: @ 8188890
    .string "{RIVAL}: Hey! {PLAYER}!\p"
    .string "You're off to the POKéMON LEAGUE?\n"
    .string "Forget about it!\p"
    .string "You probably don't have any\n"
    .string "BADGES, do you?\p"
    .string "The guard won't let you through\n"
    .string "without them.\p"
    .string "By the way, did your POKéMON get\n"
    .string "any stronger?$"

Text_188959:: @ 8188959
    .string "Awww!\n"
    .string "You just lucked out!$"

gUnknown_8188974:: @ 8188974
    .string "I heard the POKéMON LEAGUE is\n"
    .string "crawling with tough TRAINERS.\p"
    .string "I have to figure out how to get\n"
    .string "past them.\p"
    .string "You should quit dawdling and get a\n"
    .string "move on!$"

Text_188A07:: @ 8188A07
    .string "{RIVAL}“なんだ？\n"
    .string "ポケモン　2ひきも\l"
    .string "もってるの　なぜか　だって？\p"
    .string "おまえも\n"
    .string "つかまえれば　いい　じゃん！$"

gUnknown_8188A3C:: @ 8188A3C
    .string "{RIVAL}: What? {PLAYER}!\n"
    .string "What a surprise to see you here!\p"
    .string "So you're going to the POKéMON\n"
    .string "LEAGUE?\p"
    .string "You collected all the BADGES, too?\n"
    .string "That's cool!\p"
    .string "Then I'll whip you, {PLAYER}, as a\n"
    .string "warm-up for the POKéMON LEAGUE!\p"
    .string "Come on!$"

Text_188B08:: @ 8188B08
    .string "What!?\p"
    .string "I was just careless, you!$"

gUnknown_8188B29:: @ 8188B29
    .string "That loosened me up.\n"
    .string "I'm ready for the POKéMON LEAGUE!\p"
    .string "{PLAYER}, you need more practice.\p"
    .string "But hey, you know that!\n"
    .string "I'm out of here. Smell ya!$"

Text_188BAF:: @ 8188BAF
    .string "{RIVAL}“ひゃははッ　{PLAYER}ー！\n"
    .string "それで　がんばってるのかよ！\l"
    .string "おれの　さいのうに　くらべりゃ\l"
    .string "{PLAYER}は　まだまだ　だな！\p"
    .string "もっと　れんしゅう　こいよ！\n"
    .string "あははーッ！$"

gUnknown_8188BFF:: @ 8188BFF
    .string "POKéMON LEAGUE\n"
    .string "Front Gate$"

