Route22_Text_EarlyRivalIntro::
	.string "{RIVAL}: Hey!\p"
	.string "I was just\n"
	.string "looking for you.\p"
	.string "Been battling\n"
	.string "trainers already?\p"
	.string "I noticed something.\p"
	.string "Every time a POKéMON\n"
	.string "faints...\p"
	.string "there's something\n"
	.string "left behind.\p"
	.string "You saw it too,\n"
	.string "didn't you?\p"
	.string "Whatever it is...\p"
	.string "I'm going to\n"
	.string "collect more\l"
	.string "than you.$"

Route22_Text_EarlyRivalDefeat::
	.string "Hmph!\p"
	.string "You got lucky.\p"
	.string "But I'm already\n"
	.string "figuring this out.\p"
	.string "The more battles\n"
	.string "you win...\p"
	.string "the stronger\n"
	.string "you become.\p"
	.string "Just watch.$"

Route22_Text_EarlyRivalPostBattle::
	.string "I heard the POKéMON LEAGUE is\n"
	.string "crawling with tough TRAINERS.\p"
	.string "I have to figure out how to get\n"
	.string "past them.\p"
	.string "You should quit dawdling and get a\n"
	.string "move on!$"

@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons::
	.string "{RIVAL}“なんだ？\n"
	.string "ポケモン　2ひきも\l"
	.string "もってるの　なぜか　だって？\p"
	.string "おまえも\n"
	.string "つかまえれば　いい　じゃん！$"

Route22_Text_LateRivalIntro::
	.string "{RIVAL}: What? {PLAYER}!\n"
	.string "What a surprise to see you here!\p"
	.string "So you're going to the POKéMON\n"
	.string "LEAGUE?\p"
	.string "You collected all the BADGES, too?\n"
	.string "That's cool!\p"
	.string "Then I'll whip you, {PLAYER}, as a\n"
	.string "warm-up for the POKéMON LEAGUE!\p"
	.string "Come on!$"

Route22_Text_LateRivalDefeat::
	.string "What!?\p"
	.string "I was just careless, you!$"

Route22_Text_LateRivalPostBattle::
	.string "That loosened me up.\n"
	.string "I'm ready for the POKéMON LEAGUE!\p"
	.string "{PLAYER}, you need more practice.\p"
	.string "But hey, you know that!\n"
	.string "I'm out of here. Smell ya!$"

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory::
	.string "{RIVAL}“ひゃははッ　{PLAYER}ー！\n"
	.string "それで　がんばってるのかよ！\l"
	.string "おれの　さいのうに　くらべりゃ\l"
	.string "{PLAYER}は　まだまだ　だな！\p"
	.string "もっと　れんしゅう　こいよ！\n"
	.string "あははーッ！$"

Route22_Text_LeagueGateSign::
	.string "POKéMON LEAGUE\n"
	.string "Front Gate$"

