OneIsland_TreasureBeach_Text_AmaraIntro:: @ 8189D5A
    .string "Lying back, rocked by the waves…\n"
    .string "It's exquisite.$"

OneIsland_TreasureBeach_Text_AmaraDefeat:: @ 8189D8B
    .string "I lost…\n"
    .string "It feels awful.$"

OneIsland_TreasureBeach_Text_AmaraPostBattle:: @ 8189DA3
    .string "The sea is pleasantly warm in these\n"
    .string "parts.$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach:: @ 8189DCE
    .string "Good things get washed up by the\n"
    .string "ocean current onto this beach.\p"
    .string "That's why I often come here for\n"
    .string "some beachcombing.$"

