ViridianCity_House1_Text_NicknamingIsFun:: @ 818F292
    .string "Coming up with nicknames is fun,\n"
    .string "but it's not so easy to do.\p"
    .string "Clever names are nice, but simple\n"
    .string "names are easier to remember.$"

ViridianCity_House1_Text_MyDaddyLovesMonsToo:: @ 818F30F
    .string "My daddy loves Pokémon, too.$"

ViridianCity_House1_Text_Speary:: @ 818F32C
    .string "Speary: Tetweet!$"

ViridianCity_House1_Text_SpearowNameSpeary:: @ 818F33D
    .string "Spearow\n"
    .string "Name: Speary$"

