Text_177460:: @ 8177460
    .string "A secret switch!\p"
    .string "Press it?$"

Text_17747B:: @ 817747B
    .string "Who wouldn't?$"

Text_177489:: @ 8177489
    .string "Not quite yet!$"

Text_177498:: @ 8177498
    .string "I can't get out!\n"
    .string "This old place is one big puzzle.$"

Text_1774CB:: @ 81774CB
    .string "Oh, no!\n"
    .string "My bag of loot!$"

gUnknown_81774E3:: @ 81774E3
    .string "The switches here open and close\n"
    .string "alternating sets of doors.$"

gUnknown_817751F:: @ 817751F
    .string "Diary: July 5\n"
    .string "Guyana, South America\p"
    .string "A new POKéMON was discovered deep\n"
    .string "in the jungle.$"

gUnknown_8177574:: @ 8177574
    .string "Diary: July 10\n"
    .string "We christened the newly discovered\l"
    .string "POKéMON, MEW.$"

