PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
.string "¿¡Qué!?\p"
.string "¿Qué el {SHADOW DYNAMIC_COLOR4}EQUIPO ROCKET{SHADOW LIGHT_GRAY} está en el\n"
.string "{SHADOW DYNAMIC_COLOR4}MT. MOON{SHADOW LIGHT_GRAY}?\p"
.string "¡Estoy hablando por teléfono!\n"
.string "¿Será posible?$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff::
    .string "Puu pupuu!$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy::
.string "Aaah..., qué sueño...\p"
.string "Cuando {SHADOW DYNAMIC_COLOR4}JIGGLYPUFF{SHADOW LIGHT_GRAY} canta, los\n"
.string "{SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} se duermen...\p"
.string "Y yo también...\n"
.string "Qué sueño...$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu::
.string "¡Yo quiero un {SHADOW DYNAMIC_COLOR4}PIKACHU{SHADOW LIGHT_GRAY}, así que voy\n"
.string "a intercambiar a mi {SHADOW DYNAMIC_COLOR4}CLEFAIRY{SHADOW LIGHT_GRAY} por uno!$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid::
.string "Voy a intercambiar mi {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} con\n"
.string "ese chico de ahí.\p"
.string "Como tengo dos {SHADOW DYNAMIC_COLOR4}PIKACHU{SHADOW LIGHT_GRAY},\n"
.string "voy a pasarle uno.$"

PewterCity_PokemonCenter_1F_Text_Silvio::
.string "¿Has oído hablar de {SHADOW DYNAMIC_COLOR4}SILVIO{SHADOW LIGHT_GRAY}?\n"
.string "Es un experto en piedras y minerales.$"
