# 1 "data/maps/SSAnne_B1F_Room1/scripts.pory"

# 2 "data/maps/SSAnne_B1F_Room1/scripts.pory"
SSAnne_B1F_Room1_MapScripts::
# 3 "data/maps/SSAnne_B1F_Room1/scripts.pory"
	.byte 0
# 4 "data/maps/SSAnne_B1F_Room1/scripts.pory"

# 5 "data/maps/SSAnne_B1F_Room1/scripts.pory"
SSAnne_B1F_Room1_EventScript_Barny::
# 6 "data/maps/SSAnne_B1F_Room1/scripts.pory"
	trainerbattle_single TRAINER_FISHERMAN_BARNY, SSAnne_B1F_Room1_Text_BarnyIntro, SSAnne_B1F_Room1_Text_BarnyDefeat
# 7 "data/maps/SSAnne_B1F_Room1/scripts.pory"
	msgbox SSAnne_B1F_Room1_Text_BarnyPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/SSAnne_B1F_Room1/scripts.pory"
	end
# 9 "data/maps/SSAnne_B1F_Room1/scripts.pory"

# 10 "data/maps/SSAnne_B1F_Room1/scripts.pory"
SSAnne_B1F_Room1_EventScript_Phillip::
# 11 "data/maps/SSAnne_B1F_Room1/scripts.pory"
	trainerbattle_single TRAINER_SAILOR_PHILLIP, SSAnne_B1F_Room1_Text_PhillipIntro, SSAnne_B1F_Room1_Text_PhillipDefeat
# 12 "data/maps/SSAnne_B1F_Room1/scripts.pory"
	msgbox SSAnne_B1F_Room1_Text_PhillipPostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/SSAnne_B1F_Room1/scripts.pory"
	end
