gUnknown_819FDFA:: @ 819FDFA
    .string "Hiya! I'm a POKéMON…\n"
    .string "…No I'm not!\p"
    .string "Call me BILL!\n"
    .string "I'm a true-blue POKéMANIAC!\p"
    .string "Hey!\n"
    .string "What's with that skeptical look?\p"
    .string "I'm not joshing you, pal.\p"
    .string "I screwed up an experiment and got\n"
    .string "combined with a POKéMON!\p"
    .string "So, how about it?\n"
    .string "Help me out here!$"

gUnknown_819FEE6:: @ 819FEE6
    .string "Hiya! I'm a POKéMON…\n"
    .string "…No I'm not!\p"
    .string "Call me BILL!\n"
    .string "I'm a true-blue POKéMANIAC!\p"
    .string "Hey!\n"
    .string "What's with that skeptical look?\p"
    .string "I'm not joshing you, lady.\p"
    .string "I screwed up an experiment and got\n"
    .string "combined with a POKéMON!\p"
    .string "So, how about it?\n"
    .string "Help me out here!$"

gUnknown_819FFD3:: @ 819FFD3
    .string "Wait till I get inside the\n"
    .string "TELEPORTER.\p"
    .string "When I do, go to my PC and run\n"
    .string "the Cell Separation System.$"

gUnknown_81A0035:: @ 81A0035
    .string "No!?\n"
    .string "Now don't be so cold!\p"
    .string "Come on, you gotta help a guy in\n"
    .string "deep, deep trouble!\p"
    .string "What do you say, chief?\n"
    .string "Please?\l"
    .string "Okay?\l"
    .string "All right!$"

gUnknown_81A00B6:: @ 81A00B6
    .string "No!?\n"
    .string "Now don't be so cold!\p"
    .string "Come on, you gotta help a guy in\n"
    .string "deep, deep trouble!\p"
    .string "What do you say, beautiful?\n"
    .string "Please?\l"
    .string "Okay?\l"
    .string "All right!$"

gUnknown_81A013B:: @ 81A013B
    .string "BILL: Yeehah!\n"
    .string "Thanks, bud! I owe you one!\p"
    .string "So, did you come to see my\n"
    .string "POKéMON collection?\p"
    .string "You didn't?\n"
    .string "That's a bummer.\p"
    .string "I've got to thank you…\n"
    .string "Oh, here, maybe this'll do.$"

gUnknown_81A01E4:: @ 81A01E4
    .string "BILL: Yeehah!\n"
    .string "Thanks, lady! I owe you one!\p"
    .string "So, did you come to see my\n"
    .string "POKéMON collection?\p"
    .string "You didn't?\n"
    .string "That's a bummer.\p"
    .string "I've got to thank you…\n"
    .string "Oh, here, maybe this'll do.$"

gUnknown_81A028E:: @ 81A028E
    .string "{PLAYER} received an S.S. TICKET\n"
    .string "from BILL.$"

gUnknown_81A02B4:: @ 81A02B4
    .string "You've got too much stuff!$"

gUnknown_81A02CF:: @ 81A02CF
    .string "That cruise ship S.S. ANNE is in\n"
    .string "VERMILION CITY.\p"
    .string "I hear there are lots of TRAINERS\n"
    .string "on board, too.\p"
    .string "They invited me to their party, but\n"
    .string "I can't stand fancy do's.\p"
    .string "Why don't you go instead of me?\n"
    .string "Go on and have a good time.$"

gUnknown_81A03AB:: @ 81A03AB
    .string "BILL: Feel like checking out some\n"
    .string "of my rare POKéMON on my PC?\p"
    .string "Go on, check out my PC.$"

gUnknown_81A0402:: @ 81A0402
    .string "TELEPORTER is displayed on the PC\n"
    .string "monitor.$"

gUnknown_81A042D:: @ 81A042D
    .string "{PLAYER} initiated the TELEPORTER's\n"
    .string "Cell Separator.$"

gUnknown_81A045B:: @ 81A045B
    .string "BILL's favorite POKéMON list!$"

Text_1A0479:: @ 81A0479
    .string "Which POKéMON do you want to see?$"

