@ Male and female text identical, differ (presumably) in JP
Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreMale:: @ 819EDE1
    .string "My POKéMON's ashes are stored in\n"
    .string "POKéMON TOWER.\p"
    .string "You can have this TM.\n"
    .string "I don't need it anymore…$"

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreFemale:: @ 819EE40
    .string "My POKéMON's ashes are stored in\n"
    .string "POKéMON TOWER.\p"
    .string "You can have this TM.\n"
    .string "I don't need it anymore…$"

Route12_NorthEntrance_2F_Text_ReceivedTM27FromLittleGirl:: @ 819EE9F
    .string "{PLAYER} received TM27\n"
    .string "from the little girl.$"

Route12_NorthEntrance_2F_Text_ExplainTM27:: @ 819EEC6
    .string "TM27 is a move called RETURN…\p"
    .string "If you treat your POKéMON good,\n"
    .string "it will return your love by working\l"
    .string "its hardest in battle.$"

Route12_NorthEntrance_2F_Text_DontHaveRoomForThis:: @ 819EF3F
    .string "You don't have room for this.$"

Route12_NorthEntrance_2F_Text_TheresManFishing:: @ 819EF5D
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "There's a man fishing!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower:: @ 819EFA0
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "It's POKéMON TOWER!$"

