gUnknown_8179CFF:: @ 8179CFF
    .string "{RIVAL}: Hey, {PLAYER}!\n"
    .string "What brings you here?\l"
    .string "Is your POKéMON dead?\p"
    .string "Hey! It's alive!\p"
    .string "I can at least make them faint!\n"
    .string "Let's go!$"

Text_179D73:: @ 8179D73
    .string "What?\n"
    .string "You stinker!\p"
    .string "I took it easy on you, too!$"

Text_179DA2:: @ 8179DA2
    .string "{RIVAL}“あーあ‥！\n"
    .string "ほんとに　くたばっちまったぞ！\l"
    .string "よわいなー！\l"
    .string "もっと　ちゃんと　そだてて　やれよ$"

gUnknown_8179DD4:: @ 8179DD4
    .string "How's your POKéDEX coming?\n"
    .string "I just caught a CUBONE!\p"
    .string "I can't find the bigger MAROWAK.\n"
    .string "Where could they be?\p"
    .string "I bet there aren't any left!\p"
    .string "Well, I better get going.\n"
    .string "I've got a lot to accomplish,\l"
    .string "unlike you.\p"
    .string "Smell ya later!$"

gUnknown_8179EAE:: @ 8179EAE
    .string "Even we could not identify the\n"
    .string "wayward ghosts.\p"
    .string "A SILPH SCOPE might be able to\n"
    .string "unmask them.$"

