UnknownMap_00_01_EventObjects:
	object_event 1, 66, 0, 9, 0, 6, 0, 3, 9, 0, 0, 0, 0, 0, 0, UnknownMap_00_01_EventScript_1BB9C1, 0, 0, 0

UnknownMap_00_01_MapWarps:
	warp_def 5, 8, 3, 127, 32639
	warp_def 6, 8, 3, 127, 32639

UnknownMap_00_01_MapCoordEvents:
	coord_event 4, 5, 3, 0, 16384, 0, 0, UnknownMap_00_01_EventScript_1BB950
	coord_event 7, 5, 3, 0, 16384, 0, 0, UnknownMap_00_01_EventScript_1BB95C

UnknownMap_00_01_MapEvents::
	map_events UnknownMap_00_01_EventObjects, UnknownMap_00_01_MapWarps, UnknownMap_00_01_MapCoordEvents, 0x0
