SSAnne_1F_Corridor_EventObjects:
	object_event 1, 62, 0, 18, 0, 8, 0, 3, 7, 17, 0, 0, 0, 0, 0, SSAnne_1F_Corridor_EventScript_1608D5, 0, 0, 0
	object_event 2, 47, 0, 12, 0, 9, 0, 3, 8, 17, 0, 0, 0, 0, 0, SSAnne_1F_Corridor_EventScript_1608CC, 0, 0, 0

SSAnne_1F_Corridor_MapWarps:
	warp_def 3, 8, 3, 0, 262
	warp_def 2, 18, 3, 0, 266
	warp_def 19, 1, 3, 2, 260
	warp_def 20, 0, 0, 3, 260
	warp_def 3, 20, 0, 0, 266
	warp_def 28, 17, 3, 0, 264
	warp_def 5, 10, 3, 0, 268
	warp_def 8, 10, 3, 0, 269
	warp_def 11, 10, 3, 0, 270
	warp_def 14, 10, 3, 0, 271
	warp_def 17, 10, 3, 0, 272
	warp_def 23, 10, 3, 0, 273
	warp_def 20, 10, 3, 0, 285

SSAnne_1F_Corridor_MapEvents::
	map_events SSAnne_1F_Corridor_EventObjects, SSAnne_1F_Corridor_MapWarps, 0x0, 0x0
