# 1 "data/maps/SSAnne_1F_Corridor/scripts.pory"

# 2 "data/maps/SSAnne_1F_Corridor/scripts.pory"
SSAnne_1F_Corridor_MapScripts::
# 3 "data/maps/SSAnne_1F_Corridor/scripts.pory"
	.byte 0
# 4 "data/maps/SSAnne_1F_Corridor/scripts.pory"

# 5 "data/maps/SSAnne_1F_Corridor/scripts.pory"
SSAnne_1F_Corridor_EventScript_WorkerM::
# 6 "data/maps/SSAnne_1F_Corridor/scripts.pory"
	msgbox SSAnne_1F_Corridor_Text_LeStrongSilentType, MSGBOX_NPC
# 7 "data/maps/SSAnne_1F_Corridor/scripts.pory"
	end
# 8 "data/maps/SSAnne_1F_Corridor/scripts.pory"

# 9 "data/maps/SSAnne_1F_Corridor/scripts.pory"
SSAnne_1F_Corridor_EventScript_Sailor::
# 10 "data/maps/SSAnne_1F_Corridor/scripts.pory"
	msgbox SSAnne_1F_Corridor_Text_PassengersAreRestless, MSGBOX_NPC
# 11 "data/maps/SSAnne_1F_Corridor/scripts.pory"
	end
