gUnknown_8172EE7:: @ 8172EE7
    .string "Bonjour!\n"
    .string "I am le waiter on this ship!\p"
    .string "I will be happy to serve you\n"
    .string "anything you please!\p"
    .string "… … …\n"
    .string "Ah! Le strong silent type!$"

gUnknown_8172F60:: @ 8172F60
    .string "The passengers are restless from\n"
    .string "this long voyage.\p"
    .string "You might be challenged by the\n"
    .string "more bored ones!$"

