# 1 "data/maps/DiglettsCave_NorthEntrance/scripts.pory"

# 2 "data/maps/DiglettsCave_NorthEntrance/scripts.pory"
DiglettsCave_NorthEntrance_MapScripts::
# 3 "data/maps/DiglettsCave_NorthEntrance/scripts.pory"
	.byte 0
# 4 "data/maps/DiglettsCave_NorthEntrance/scripts.pory"

# 5 "data/maps/DiglettsCave_NorthEntrance/scripts.pory"
DiglettsCave_NorthEntrance_EventScript_Hiker::
# 6 "data/maps/DiglettsCave_NorthEntrance/scripts.pory"
	msgbox DiglettsCave_NorthEntrance_RockTunnelPitchBlack, MSGBOX_NPC
# 7 "data/maps/DiglettsCave_NorthEntrance/scripts.pory"
	end
