Text_19DD66:: @ 819DD66
    .string "I run the DAY-CARE service.\p"
    .string "Would you like me to raise one of\n"
    .string "your POKéMON?$"

Text_19DDB2:: @ 819DDB2
    .string "Come again.$"

Text_19DDBE:: @ 819DDBE
    .string "Which POKéMON should I raise?$"

Text_19DDDC:: @ 819DDDC
    .string "Fine.\n"
    .string "Come anytime you like.$"

Text_19DDF9:: @ 819DDF9
    .string "Fine, I'll look after your\n"
    .string "{STR_VAR_1} for a while.$"

Text_19DE24:: @ 819DE24
    .string "Come see me in a while.$"

Text_19DE3C:: @ 819DE3C
    .string "You're back already?\p"
    .string "Your {STR_VAR_1} needs to spend\n"
    .string "some more time with me.$"

Text_19DE80:: @ 819DE80
    .string "You owe me ¥{STR_VAR_2} for the return\n"
    .string "of this POKéMON.$"

Text_19DEAF:: @ 819DEAF
    .string "Thank you!\n"
    .string "Here's your POKéMON.$"

Text_19DECF:: @ 819DECF
    .string "{PLAYER} got {STR_VAR_1} back\n"
    .string "from the DAY-CARE MAN.$"

Text_19DEF5:: @ 819DEF5
    .string "Oh? You only have one POKéMON\n"
    .string "with you.$"

Text_19DF1D:: @ 819DF1D
    .string "If you leave me that POKéMON,\n"
    .string "what will you battle with?$"

Text_19DF56:: @ 819DF56
    .string "Your {STR_VAR_1} has grown a lot.\n"
    .string "Yes, quite a lot, I'd say.\p"
    .string "Let me see…\n"
    .string "By level, it's grown by {STR_VAR_2}.\p"
    .string "Aren't I great?$"

Text_19DFC2:: @ 819DFC2
    .string "You can't take this POKéMON back\n"
    .string "if you've got no room for it.$"

Text_19E001:: @ 819E001
    .string "You don't have enough money.$"

Text_19E01E:: @ 819E01E
    .string "きみの\n"
    .string "みてみるかね？$"

Text_19E02A:: @ 819E02A
    .string "わるいけど　ひでんのわざを　もった\n"
    .string "ポケモンは　あずかれないなぁ$"

gUnknown_819E04B:: @ 819E04B
    .string "I'm on guard duty.\n"
    .string "Gee, I'm thirsty, though!\p"
    .string "Oh, wait there, the road's closed.$"

gUnknown_819E09B:: @ 819E09B
    .string "Oh, that TEA…\n"
    .string "It looks awfully tasty…$"

gUnknown_819E0C1:: @ 819E0C1
    .string "Huh? I can have this drink?\n"
    .string "Gee, thanks!\l"
    .string "… …\l"
    .string "Glug, glug…\l"
    .string "… …\l"
    .string "Gulp…\l"
    .string "If you want to go to SAFFRON\l"
    .string "CITY…\l"
    .string "… …\l"
    .string "You can go on through.\p"
    .string "I'll share this TEA with the other\n"
    .string "guards!$"

gUnknown_819E16D:: @ 819E16D
    .string "Hi, how's it going?$"

