CeruleanCity_Gym_Text_MistyIntro::
.string "¡Hola, eres nuevo por aquí!\p"
.string "Solo los ENTRENADORES con una\n"
.string "política sobre los POKéMON pueden ser profesionales.\p"
.string "¿Cuál es tu forma de atrapar y\n"
.string "entrenar POKéMON?\p"
.string "¡Mi política es un ataque total con\n"
.string "POKéMON de tipo AGUA!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CeruleanCity_Gym_Text_ExplainTM03::
.string "La MT03 enseña HIDROPULSO.\p"
.string "¡Úsala en un POKéMON acuático!$"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
.string "La MEDALLA CASCADA hace que todos\n"
.string "los POKéMON hasta Nv. 30 obedezcan.\p"
.string "Eso incluye a los forasteros que\n"
.string "obtienes en intercambios.\p"
.string "Hay más. Ahora puedes usar CORTE\n"
.string "en cualquier momento, incluso fuera de combate.\p"
.string "Puedes cortar arbolitos para abrir\n"
.string "nuevos caminos.\p"
.string "También puedes llevarte mi MT favorita.$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
.string "{PLAYER} recibió la MT03\n"
.string "de MISTY.$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
.string "¡Será mejor que hagas espacio para esto!$"

CeruleanCity_Gym_Text_MistyDefeat::
.string "¡VAYA!\n"
.string "¡ERES INCREÍBLE!\p"
.string "¡MUY BIEN!\p"
.string "PUEDES QUEDARTE CON LA MEDALLA CASCADA PARA\n"
.string "DEMOSTRAR QUE ME VENCISTE.$"

CeruleanCity_Gym_Text_DianaIntro::
.string "¿Qué? ¿Tú?\n"
.string "¡Soy más que suficiente para ti!\p"
.string "MISTY no tendrá que molestarse.$"

CeruleanCity_Gym_Text_DianaDefeat::
.string "¡ME SUPERASTE!$"

CeruleanCity_Gym_Text_DianaPostBattle::
.string "Tienes que enfrentarte a otros\n"
.string "ENTRENADORES para ver qué tan bueno eres.$"

CeruleanCity_Gym_Text_LuisIntro::
.string "¡Splash!\p"
.string "¡Soy el primero!\n"
.string "¡Vamos!$"

CeruleanCity_Gym_Text_LuisDefeat::
.string "¡ESO NO PUEDE SER!$"

CeruleanCity_Gym_Text_LuisPostBattle::
.string "MISTY es una ENTRENADORA que seguirá\n"
.string "mejorando.\p"
.string "¡No perderá contra alguien como tú!$"

CeruleanCity_Gym_Text_GymGuyAdvice::
.string "¡Hey!\n"
.string "¡Futuro campeón!\p"
.string "¡Déjame darte un consejo!\p"
.string "La LÍDER, MISTY, es una profesional\n"
.string "que usa POKéMON de tipo AGUA.\p"
.string "Puedes drenarles toda el agua con\n"
.string "POKéMON de tipo PLANTA.\p"
.string "O podrías usar POKéMON de tipo ELÉCTRICO\n"
.string "y electrocutarlos.$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
.string "¡Venciste a MISTY!\n"
.string "¿Ves? ¿Qué te dije?\p"
.string "Tú y yo, chico, hacemos un\n"
.string "equipo bastante bueno.$"

CeruleanCity_Gym_Text_GymStatue::
.string "GIMNASIO POKéMON DE CIUDAD CELESTE\n"
.string "LÍDER: MISTY\p"
.string "ENTRENADORES GANADORES:\n"
.string "{RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
.string "GIMNASIO POKéMON DE CIUDAD CELESTE\n"
.string "LÍDER: MISTY\p"
.string "ENTRENADORES GANADORES:\n"
.string "{RIVAL}, {PLAYER}$"

