PewterCity_Text_MiAbuelitoDice::
    .string "¡Mi abuelito dice que don {SHADOW DYNAMIC_COLOR4}SILVIO{SHADOW LIGHT_GRAY}\n"
    .string "puede hablar con las piedras!$"

PewterCity_Text_Montanista::
    .string "Como montañista experimentado,\n"
    .string "conozco cada rincón y grieta de\l"
    .string "estas montañas.$"

PewterCity_Text_Nino::
    .string "¿Crees que el {SHADOW DYNAMIC_COLOR4}EQUIPO ROCKET{SHADOW LIGHT_GRAY}\n"
    .string "intentará robar el {SHADOW DYNAMIC_COLOR4}ONIX{SHADOW LIGHT_GRAY} de {SHADOW DYNAMIC_COLOR4}BROCK{SHADOW LIGHT_GRAY}?$"

PewterCity_Text_ClefairyCameFromMoon::
    .string "¡Dicen que los {SHADOW DYNAMIC_COLOR4}CLEFAIRY{SHADOW LIGHT_GRAY} vinieron\n"
    .string "de la luna!\p"
    .string "¡Aparecieron tras la caída de\n"
    .string "varias {SHADOW DYNAMIC_COLOR4}PIEDRAS LUNARES{SHADOW LIGHT_GRAY}\l"
    .string "en el {SHADOW DYNAMIC_COLOR4}MT. MOON{SHADOW LIGHT_GRAY}!$"

PewterCity_Text_BrockOnlySeriousTrainerHere::
    .string "¡No hay muchos {SHADOW DYNAMIC_COLOR4}ENTRENADORES{SHADOW LIGHT_GRAY}\n"
    .string "de {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} por aquí!\p"
    .string "¡Todos parecen {SHADOW DYNAMIC_COLOR4}CAZABICHOS{SHADOW LIGHT_GRAY}, salvo\n"
    .string "{SHADOW DYNAMIC_COLOR4}BROCK{SHADOW LIGHT_GRAY}, del {SHADOW DYNAMIC_COLOR4}GIMNASIO{SHADOW LIGHT_GRAY} de\l"
    .string "{SHADOW DYNAMIC_COLOR4}CIUDAD PLATEADA{SHADOW LIGHT_GRAY}!$"

PewterCity_Text_DidYouCheckOutMuseum::
    .string "¿Has estado en el {SHADOW DYNAMIC_COLOR4}MUSEO DE CIENCIA{SHADOW LIGHT_GRAY}?$"

PewterCity_Text_WerentThoseFossilsAmazing::
    .string "¿No eran geniales esos fósiles\n"
    .string "del {SHADOW DYNAMIC_COLOR4}MT. MOON{SHADOW LIGHT_GRAY}?$"

PewterCity_Text_ReallyYouHaveToGo::
    .string "¿De verdad?\n"
    .string "¡Pues tienes que ir!$"

PewterCity_Text_ThisIsTheMuseum::
    .string "Aqui está el {SHADOW DYNAMIC_COLOR4}MUSEO DE CIENCIA{SHADOW LIGHT_GRAY}\p"
    .string "{SHADOW LIGHT_GRAY}¡Hay que pagar para entrar, pero\n"
    .string "vale la pena! ¡Hasta luego!$"

PewterCity_Text_DoYouKnowWhatImDoing::
    .string "¡Psssst!\n"
    .string "¿Sabes lo que estoy haciendo?$"

PewterCity_Text_ThatsRightItsHardWork::
    .string "¡Eso es!\n"
    .string "¡Un trabajo tremendo!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
    .string "¡Utilizo el {SHADOW DYNAMIC_COLOR4}REPELENTE{SHADOW LIGHT_GRAY} para echar\n"
    .string "de mi jardín a los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe::
    .string "¡Oye, espera un momento!\p"
    .string "¿Has tenido la oportunidad de\n"
    .string "conocer a {SHADOW DYNAMIC_COLOR4}BROCK{SHADOW LIGHT_GRAY}?\p"
    .string "Su destreza en combate es\n"
    .string "legendaria en toda la región.\p"
    .string "Antes de seguir tu camino, te\n"
    .string "animo a que entres al {SHADOW DYNAMIC_COLOR4}GIMNASIO{SHADOW LIGHT_GRAY} y\l"
    .string "lo enfrentes en batalla.\p"
    .string "¡Sígueme!$"

PewterCity_Text_GoTakeOnBrock::
    .string "¡Aquí estamos! Este es el {SHADOW DYNAMIC_COLOR4}GIMNASIO\n"
    .string "{SHADOW LIGHT_GRAY}de {SHADOW DYNAMIC_COLOR4}CIUDAD PLATEADA{SHADOW LIGHT_GRAY}\p"
    .string "Estoy seguro de que tendrás una\n"
    .string "batalla emocionante.\p"
    .string "¡Ve y desafía a {SHADOW DYNAMIC_COLOR4}BROCK{SHADOW DYNAMIC_COLOR4}!$"

PewterCity_Text_TrainerTipsEarningEXP::
    .string "{SHADOW DYNAMIC_COLOR4}PISTAS ENTRENADOR\p"
    .string "{SHADOW LIGHT_GRAY}¡Todo {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} que luche en un\n"
    .string "combate ganará {SHADOW DYNAMIC_COLOR4}EXPERIENCIA{SHADOW LIGHT_GRAY}!$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
    .string "{COLOR RED}{SHADOW LIGHT_RED}¡AVISO!{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\p"
    .string "¡Unos ladrones han robado fósiles\n"
    .string "de {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} del {SHADOW DYNAMIC_COLOR4}MT. MOON{SHADOW LIGHT_GRAY}!\p"
    .string "¡Avisa a la {SHADOW DYNAMIC_COLOR4}POLICÍA{SHADOW LIGHT_GRAY} de {SHADOW DYNAMIC_COLOR4}CIUDAD{SHADOW LIGHT_GRAY}\n"
    .string "{SHADOW DYNAMIC_COLOR4}PLATEADA{SHADOW LIGHT_GRAY} si sabes de algo!$"

PewterCity_Text_MuseumOfScience::
    .string "{SHADOW DYNAMIC_COLOR4}MUSEO DE CIENCIA DE\n"
    .string "CIUDAD PLATEADA$"

PewterCity_Text_GymSign::
    .string "{SHADOW DYNAMIC_COLOR4}GIMNASIO POKéMON DE PLATEADA\p"
    .string "LIDER: BROCK\n"
    .string "{SHADOW LIGHT_GRAY}¡Es fuerte como una roca!$"

PewterCity_Text_CitySign::
    .string "{SHADOW DYNAMIC_COLOR4}CIUDAD PLANTEADA{SHADOW LIGHT_GRAY}\n"
    .string "Ciudad de riscos inaccesibles$"

PewterCity_Text_SilvoMart_Cerrado::
        .string "{SHADOW DYNAMIC_COLOR4}CERRADO{SHADOW LIGHT_GRAY}\n"
        .string "Vuelvo enseguida...$"

PewterCity_Text_SilvoMart_Sign::
    .string "{SHADOW DYNAMIC_COLOR4}TIENDA DE PIEDRAS DEL SABER{SHADOW LIGHT_GRAY}\n"
    .string "El poder del cambio.$"