# 1 "data/maps/PokemonTower_3F/scripts.pory"

# 2 "data/maps/PokemonTower_3F/scripts.pory"
PokemonTower_3F_MapScripts::
# 3 "data/maps/PokemonTower_3F/scripts.pory"
	.byte 0
# 4 "data/maps/PokemonTower_3F/scripts.pory"

# 5 "data/maps/PokemonTower_3F/scripts.pory"
PokemonTower_3F_EventScript_Patricia::
# 6 "data/maps/PokemonTower_3F/scripts.pory"
	trainerbattle_single TRAINER_CHANNELER_PATRICIA, PokemonTower_3F_Text_PatriciaIntro, PokemonTower_3F_Text_PatriciaDefeat
# 7 "data/maps/PokemonTower_3F/scripts.pory"
	msgbox PokemonTower_3F_Text_PatriciaPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/PokemonTower_3F/scripts.pory"
	end
# 9 "data/maps/PokemonTower_3F/scripts.pory"

# 10 "data/maps/PokemonTower_3F/scripts.pory"
PokemonTower_3F_EventScript_Carly::
# 11 "data/maps/PokemonTower_3F/scripts.pory"
	trainerbattle_single TRAINER_CHANNELER_CARLY, PokemonTower_3F_Text_CarlyIntro, PokemonTower_3F_Text_CarlyDefeat
# 12 "data/maps/PokemonTower_3F/scripts.pory"
	msgbox PokemonTower_3F_Text_CarlyPostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/PokemonTower_3F/scripts.pory"
	end
# 14 "data/maps/PokemonTower_3F/scripts.pory"

# 15 "data/maps/PokemonTower_3F/scripts.pory"
PokemonTower_3F_EventScript_Hope::
# 16 "data/maps/PokemonTower_3F/scripts.pory"
	trainerbattle_single TRAINER_CHANNELER_HOPE, PokemonTower_3F_Text_HopeIntro, PokemonTower_3F_Text_HopeDefeat
# 17 "data/maps/PokemonTower_3F/scripts.pory"
	msgbox PokemonTower_3F_Text_HopePostBattle, MSGBOX_AUTOCLOSE
# 18 "data/maps/PokemonTower_3F/scripts.pory"
	end
