PokemonTower_3F_MapScripts:: @ 81633A6
	.byte 0

PokemonTower_3F_EventScript_1633A7:: @ 81633A7
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_CHANNELER_PATRICIA, 0, Text_179FA0, Text_179FBC
	msgbox gUnknown_8179FD3, 6
	end

PokemonTower_3F_EventScript_1633BE:: @ 81633BE
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_CHANNELER_CARLY, 0, Text_179F62, Text_179F72
	msgbox gUnknown_8179F88, 6
	end

PokemonTower_3F_EventScript_1633D5:: @ 81633D5
	trainerbattle TRAINER_BATTLE_SINGLE, TRAINER_CHANNELER_HOPE, 0, Text_179F09, Text_179F21
	msgbox gUnknown_8179F31, 6
	end
