PokemonTower_3F_MapScripts:: @ 81633A6
	.byte 0

PokemonTower_3F_EventScript_1633A7:: @ 81633A7
	trainerbattle 0, 441, 0, Text_179FA0, Text_179FBC
	loadword 0, gUnknown_8179FD3
	callstd 6
	end

PokemonTower_3F_EventScript_1633BE:: @ 81633BE
	trainerbattle 0, 442, 0, Text_179F62, Text_179F72
	loadword 0, gUnknown_8179F88
	callstd 6
	end

PokemonTower_3F_EventScript_1633D5:: @ 81633D5
	trainerbattle 0, 443, 0, Text_179F09, Text_179F21
	loadword 0, gUnknown_8179F31
	callstd 6
	end
