Text_179F09:: @ 8179F09
    .string "Urrg… Awaa…\n"
    .string "Huhu… Graa…$"

Text_179F21:: @ 8179F21
    .string "Hwa!\n"
    .string "I'm saved!$"

gUnknown_8179F31:: @ 8179F31
    .string "The ghosts can be identified by\n"
    .string "the SILPH SCOPE.$"

Text_179F62:: @ 8179F62
    .string "Kekeke…\n"
    .string "Kwaaah!$"

Text_179F72:: @ 8179F72
    .string "Hmm?\n"
    .string "What am I doing?$"

gUnknown_8179F88:: @ 8179F88
    .string "Sorry!\n"
    .string "I was possessed!$"

Text_179FA0:: @ 8179FA0
    .string "Be gone!\n"
    .string "Malevolent spirit!$"

Text_179FBC:: @ 8179FBC
    .string "Whew!\n"
    .string "The spirit left!$"

gUnknown_8179FD3:: @ 8179FD3
    .string "The others above…\n"
    .string "They must have been possessed.$"

