PokemonTower_3F_Text_HopeIntro:: @ 8179F09
    .string "Urrg… Awaa…\n"
    .string "Huhu… Graa…$"

PokemonTower_3F_Text_HopeDefeat:: @ 8179F21
    .string "Hwa!\n"
    .string "I'm saved!$"

PokemonTower_3F_Text_HopePostBattle:: @ 8179F31
    .string "The ghosts can be identified by\n"
    .string "the SILPH SCOPE.$"

PokemonTower_3F_Text_CarlyIntro:: @ 8179F62
    .string "Kekeke…\n"
    .string "Kwaaah!$"

PokemonTower_3F_Text_CarlyDefeat:: @ 8179F72
    .string "Hmm?\n"
    .string "What am I doing?$"

PokemonTower_3F_Text_CarlyPostBattle:: @ 8179F88
    .string "Sorry!\n"
    .string "I was possessed!$"

PokemonTower_3F_Text_PatriciaIntro:: @ 8179FA0
    .string "Be gone!\n"
    .string "Malevolent spirit!$"

PokemonTower_3F_Text_PatriciaDefeat:: @ 8179FBC
    .string "Whew!\n"
    .string "The spirit left!$"

PokemonTower_3F_Text_PatriciaPostBattle:: @ 8179FD3
    .string "The others above…\n"
    .string "They must have been possessed.$"

