SevenIsland_TrainerTower_5F_MapScripts:: @ 8164770
	map_script 5, SevenIsland_TrainerTower_5F_MapScript1_1C4F54
	map_script 3, SevenIsland_TrainerTower_5F_MapScript2_1C4F62
	map_script 2, SevenIsland_TrainerTower_5F_MapScript3_1C5046
	.byte 0

SevenIsland_TrainerTower_5F_EventScript_164780:: @ 8164780
	call EventScript_1C52F4
	end

EventScript_164786:: @ 8164786
	call EventScript_1C533B
	end

EventScript_16478C:: @ 816478C
	call EventScript_1C5382
	end

EventScript_164792:: @ 8164792
	call EventScript_1C538C
	end

EventScript_164798:: @ 8164798
	call EventScript_1C53AA
	end
