gUnknown_819F5AB:: @ 819F5AB
    .string "Hi! Remember me?\n"
    .string "I'm one of PROF. OAK's AIDES.\p"
    .string "If your POKéDEX has complete data\n"
    .string "on {STR_VAR_1} species, I'm supposed to\l"
    .string "give you a reward.\p"
    .string "PROF. OAK entrusted me with the\n"
    .string "{STR_VAR_2} for you.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "{STR_VAR_1} kinds of POKéMON?$"

gUnknown_819F6AA:: @ 819F6AA
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"

gUnknown_819F6FD:: @ 819F6FD
    .string "{PLAYER} received the {STR_VAR_2}\n"
    .string "from the AIDE.$"

gUnknown_819F71F:: @ 819F71F
    .string "EXP. SHARE is an item to be held\n"
    .string "by a POKéMON.\p"
    .string "The POKéMON will receive a share\n"
    .string "of the EXP. Points without having\l"
    .string "to battle.$"

gUnknown_819F79C:: @ 819F79C
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "A large, shining bird is flying\n"
    .string "toward the sea.$"

gUnknown_819F7F8:: @ 819F7F8
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "It looks like a small island on\n"
    .string "the horizon!$"

