# 1 "data/maps/CeladonCity_Condominiums_2F/scripts.pory"

# 2 "data/maps/CeladonCity_Condominiums_2F/scripts.pory"
CeladonCity_Condominiums_2F_MapScripts::
# 3 "data/maps/CeladonCity_Condominiums_2F/scripts.pory"
	.byte 0
# 4 "data/maps/CeladonCity_Condominiums_2F/scripts.pory"

# 5 "data/maps/CeladonCity_Condominiums_2F/scripts.pory"
CeladonCity_Condominiums_2F_EventScript_MeetingRoomSign::
# 6 "data/maps/CeladonCity_Condominiums_2F/scripts.pory"
	msgbox CeladonCity_Condominiums_2F_Text_GameFreakMeetingRoom, MSGBOX_SIGN
# 7 "data/maps/CeladonCity_Condominiums_2F/scripts.pory"
	end
