SilphCo_9F_Text_YouShouldTakeQuickNap:: @ 8176B54
    .string "You look tired.\n"
    .string "You should take a quick nap.$"

SilphCo_9F_Text_DontGiveUp:: @ 8176B81
    .string "Don't give up!$"

SilphCo_9F_Text_ThankYouSoMuch:: @ 8176B90
    .string "Thank you so much.$"

SilphCo_9F_Text_Grunt1Intro:: @ 8176BA3
    .string "Your POKéMON seem to adore you,\n"
    .string "kid!$"

SilphCo_9F_Text_Grunt1Defeat:: @ 8176BC8
    .string "Ghaaah!$"

SilphCo_9F_Text_Grunt1PostBattle:: @ 8176BD0
    .string "If I had started as a TRAINER at\n"
    .string "your age…$"

SilphCo_9F_Text_EdIntro:: @ 8176BFB
    .string "Your POKéMON have weak points!\n"
    .string "I can nail them!$"

SilphCo_9F_Text_EdDefeat:: @ 8176C2B
    .string "You hammered me!$"

SilphCo_9F_Text_EdPostBattle:: @ 8176C3C
    .string "Exploiting weak spots does work.\n"
    .string "Think about type advantages.$"

SilphCo_9F_Text_Grunt2Intro:: @ 8176C7A
    .string "I am one of the four ROCKET\n"
    .string "BROTHERS!$"

SilphCo_9F_Text_Grunt2Defeat:: @ 8176CA0
    .string "Warg!\n"
    .string "Brothers, I lost!$"

SilphCo_9F_Text_Grunt2PostBattle:: @ 8176CB8
    .string "My brothers will avenge me!$"

SilphCo_9F_Text_FloorSign:: @ 8176CD4
    .string "SILPH CO. HEAD OFFICE\n"
    .string "9F$"

