SilphCo_9F_Text_YouShouldTakeQuickNap::
    .string "You look tired.\n"
    .string "You should take a quick nap.$"

SilphCo_9F_Text_DontGiveUp::
    .string "Don't give up!$"

SilphCo_9F_Text_ThankYouSoMuch::
    .string "Thank you so much.$"

SilphCo_9F_Text_Grunt1Intro::
    .string "Your POKéMON seem to adore you,\n"
    .string "kid!$"

SilphCo_9F_Text_Grunt1Defeat::
    .string "Ghaaah!$"

SilphCo_9F_Text_Grunt1PostBattle::
    .string "If I had started as a TRAINER at\n"
    .string "your age…$"

SilphCo_9F_Text_EdIntro::
    .string "Your POKéMON have weak points!\n"
    .string "I can nail them!$"

SilphCo_9F_Text_EdDefeat::
    .string "You hammered me!$"

SilphCo_9F_Text_EdPostBattle::
    .string "Exploiting weak spots does work.\n"
    .string "Think about type advantages.$"

SilphCo_9F_Text_Grunt2Intro::
    .string "I am one of the four ROCKET\n"
    .string "BROTHERS!$"

SilphCo_9F_Text_Grunt2Defeat::
    .string "Warg!\n"
    .string "Brothers, I lost!$"

SilphCo_9F_Text_Grunt2PostBattle::
    .string "My brothers will avenge me!$"

SilphCo_9F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "9F$"

