Route25_Text_JoeyIntro:: @ 81890C0
    .string "Local TRAINERS come here to\n"
    .string "practice.$"

Route25_Text_JoeyDefeat:: @ 81890E6
    .string "You're decent.$"

Route25_Text_JoeyPostBattle:: @ 81890F5
    .string "All POKéMON have weaknesses.\n"
    .string "Even the strongest ones.\p"
    .string "That's why it's best to raise\n"
    .string "POKéMON of different types.$"

Route25_Text_DanIntro:: @ 8189165
    .string "Dad took me to a great party on\n"
    .string "the S.S. ANNE at VERMILION CITY.$"

Route25_Text_DanDefeat:: @ 81891A6
    .string "I'm not mad!$"

Route25_Text_DanPostBattle:: @ 81891B3
    .string "On the S.S. ANNE, I saw TRAINERS\n"
    .string "from around the world.$"

Route25_Text_FlintIntro:: @ 81891EB
    .string "I'm a cool guy.\n"
    .string "I've got a girlfriend!$"

Route25_Text_FlintDefeat:: @ 8189212
    .string "Aww, darn…$"

Route25_Text_FlintPostBattle:: @ 818921D
    .string "Oh, well.\n"
    .string "My girlfriend will cheer me up.$"

Route25_Text_KelseyIntro:: @ 8189247
    .string "Hi!\n"
    .string "My boyfriend is cool!$"

Route25_Text_KelseyDefeat:: @ 8189261
    .string "My conditioning isn't the best…$"

Route25_Text_KelseyPostBattle:: @ 8189281
    .string "I wish my boyfriend was as good\n"
    .string "as you.$"

Route25_Text_ChadIntro:: @ 81892A9
    .string "I had this feeling…\n"
    .string "I knew I had to battle you!$"

Route25_Text_ChadDefeat:: @ 81892D9
    .string "I knew I'd lose, too!$"

Route25_Text_ChadPostBattle:: @ 81892EF
    .string "If your POKéMON gets confused,\n"
    .string "switch it out.\p"
    .string "That's a good tactic.$"

Route25_Text_HaleyIntro:: @ 8189333
    .string "My friend has many cute POKéMON.\n"
    .string "I'm so jealous!$"

Route25_Text_HaleyDefeat:: @ 8189364
    .string "I'm not so jealous!$"

Route25_Text_HaleyPostBattle:: @ 8189378
    .string "You came from MT. MOON?\n"
    .string "May I have a CLEFAIRY?$"

Route25_Text_FranklinIntro:: @ 81893A7
    .string "I just got down from MT. MOON,\n"
    .string "but I've still got gas in the tank!$"

Route25_Text_FranklinDefeat:: @ 81893EA
    .string "You worked hard!$"

Route25_Text_FranklinPostBattle:: @ 81893FB
    .string "Drat!\n"
    .string "A ZUBAT bit me back in that cave.$"

Route25_Text_NobIntro:: @ 8189423
    .string "I'm off to see a POKéMANIAC's\n"
    .string "collection at the cape.$"

Route25_Text_NobDefeat:: @ 8189459
    .string "You done got me, and real good,\n"
    .string "too!$"

Route25_Text_NobPostBattle:: @ 818947E
    .string "The POKéMANIAC sure lives up to\n"
    .string "his name.\p"
    .string "His collection includes many rare\n"
    .string "species of POKéMON.$"

Route25_Text_WayneIntro:: @ 81894DE
    .string "You're going to see BILL?\n"
    .string "First, we battle!$"

Route25_Text_WayneDefeat:: @ 818950A
    .string "You're something.$"

Route25_Text_WaynePostBattle:: @ 818951C
    .string "The trail below is a shortcut to\n"
    .string "CERULEAN CITY.$"

Route25_Text_SeaCottageSign:: @ 818954C
    .string "SEA COTTAGE\n"
    .string "BILL lives here!$"

Route25_Text_MistyHighHopesAboutThisPlace:: @ 8189569
    .string "This cape is a famous date spot.\p"
    .string "MISTY, the GYM LEADER, has high\n"
    .string "hopes about this place.$"

Route25_Text_AreYouHereAlone:: @ 81895C2
    .string "Hello, are you here alone?\p"
    .string "If you're out at CERULEAN's cape…\n"
    .string "Well, it should be as a couple.$"

