Text_188E74:: @ 8188E74
    .string "I saw your feat from the grass!$"

Text_188E94:: @ 8188E94
    .string "I thought not!$"

Text_188EA3:: @ 8188EA3
    .string "I hid because the people on the\n"
    .string "bridge frightened me.$"

Text_188ED9:: @ 8188ED9
    .string "Okay! I'm No. 5!\n"
    .string "I'll stomp you!$"

Text_188EFA:: @ 8188EFA
    .string "Whoa!\n"
    .string "Too much!$"

Text_188F0A:: @ 8188F0A
    .string "I did my best. I have no regrets!$"

Text_188F2C:: @ 8188F2C
    .string "I'm No. 4!\n"
    .string "Getting tired?$"

Text_188F46:: @ 8188F46
    .string "I lost, too!$"

Text_188F53:: @ 8188F53
    .string "I did my best, so I've no regrets!$"

Text_188F76:: @ 8188F76
    .string "Here's No. 3!\n"
    .string "I won't be easy!$"

Text_188F95:: @ 8188F95
    .string "Ow!\n"
    .string "Stomped flat!$"

Text_188FA7:: @ 8188FA7
    .string "I did my best. I have no regrets!$"

Text_188FC9:: @ 8188FC9
    .string "I'm second!\n"
    .string "Now it's serious!$"

Text_188FE7:: @ 8188FE7
    .string "How could I lose?$"

Text_188FF9:: @ 8188FF9
    .string "I did my best. I have no regrets!$"

Text_18901B:: @ 818901B
    .string "People call this the NUGGET\n"
    .string "BRIDGE!\p"
    .string "Beat us five TRAINERS and win\n"
    .string "a fabulous prize!\p"
    .string "Think you got what it takes?$"

Text_18908C:: @ 818908C
    .string "Whoo!\n"
    .string "Good stuff!$"

Text_18909E:: @ 818909E
    .string "I did my best. I have no regrets!$"

Text_1890C0:: @ 81890C0
    .string "Local TRAINERS come here to\n"
    .string "practice.$"

Text_1890E6:: @ 81890E6
    .string "You're decent.$"

Text_1890F5:: @ 81890F5
    .string "All POKéMON have weaknesses.\n"
    .string "Even the strongest ones.\p"
    .string "That's why it's best to raise\n"
    .string "POKéMON of different types.$"

Text_189165:: @ 8189165
    .string "Dad took me to a great party on\n"
    .string "the S.S. ANNE at VERMILION CITY.$"

Text_1891A6:: @ 81891A6
    .string "I'm not mad!$"

Text_1891B3:: @ 81891B3
    .string "On the S.S. ANNE, I saw TRAINERS\n"
    .string "from around the world.$"

Text_1891EB:: @ 81891EB
    .string "I'm a cool guy.\n"
    .string "I've got a girlfriend!$"

Text_189212:: @ 8189212
    .string "Aww, darn…$"

Text_18921D:: @ 818921D
    .string "Oh, well.\n"
    .string "My girlfriend will cheer me up.$"

Text_189247:: @ 8189247
    .string "Hi!\n"
    .string "My boyfriend is cool!$"

Text_189261:: @ 8189261
    .string "My conditioning isn't the best…$"

Text_189281:: @ 8189281
    .string "I wish my boyfriend was as good\n"
    .string "as you.$"

Text_1892A9:: @ 81892A9
    .string "I had this feeling…\n"
    .string "I knew I had to battle you!$"

Text_1892D9:: @ 81892D9
    .string "I knew I'd lose, too!$"

Text_1892EF:: @ 81892EF
    .string "If your POKéMON gets confused,\n"
    .string "switch it out.\p"
    .string "That's a good tactic.$"

Text_189333:: @ 8189333
    .string "My friend has many cute POKéMON.\n"
    .string "I'm so jealous!$"

Text_189364:: @ 8189364
    .string "I'm not so jealous!$"

Text_189378:: @ 8189378
    .string "You came from MT. MOON?\n"
    .string "May I have a CLEFAIRY?$"

Text_1893A7:: @ 81893A7
    .string "I just got down from MT. MOON,\n"
    .string "but I've still got gas in the tank!$"

Text_1893EA:: @ 81893EA
    .string "You worked hard!$"

Text_1893FB:: @ 81893FB
    .string "Drat!\n"
    .string "A ZUBAT bit me back in that cave.$"

Text_189423:: @ 8189423
    .string "I'm off to see a POKéMANIAC's\n"
    .string "collection at the cape.$"

Text_189459:: @ 8189459
    .string "You done got me, and real good,\n"
    .string "too!$"

Text_18947E:: @ 818947E
    .string "The POKéMANIAC sure lives up to\n"
    .string "his name.\p"
    .string "His collection includes many rare\n"
    .string "species of POKéMON.$"

Text_1894DE:: @ 81894DE
    .string "You're going to see BILL?\n"
    .string "First, we battle!$"

Text_18950A:: @ 818950A
    .string "You're something.$"

Text_18951C:: @ 818951C
    .string "The trail below is a shortcut to\n"
    .string "CERULEAN CITY.$"

gUnknown_818954C:: @ 818954C
    .string "SEA COTTAGE\n"
    .string "BILL lives here!$"

Text_189569:: @ 8189569
    .string "This cape is a famous date spot.\p"
    .string "MISTY, the GYM LEADER, has high\n"
    .string "hopes about this place.$"

gUnknown_81895C2:: @ 81895C2
    .string "Hello, are you here alone?\p"
    .string "If you're out at CERULEAN's cape…\n"
    .string "Well, it should be as a couple.$"

