ThreeIsland_Port_EventObjects:
	object_event 1, 31, 0, 14, 0, 9, 0, 3, 1, 17, 0, 0, 0, 0, 0, ThreeIsland_Port_EventScript_168796, 0, 0, 0
	object_event 2, 53, 0, 8, 0, 8, 0, 3, 28, 19, 0, 0, 0, 0, 0, ThreeIsland_Port_EventScript_1687CC, 121, 0, 0
	object_event 3, 53, 0, 13, 0, 10, 0, 3, 49, 34, 0, 0, 0, 0, 0, ThreeIsland_Port_EventScript_1687D5, 121, 0, 0

ThreeIsland_Port_MapWarps:
	warp_def 16, 4, 0, 0, 546
	warp_def 38, 5, 3, 1, 546
	warp_def 12, 13, 3, 0, 9728

ThreeIsland_Port_MapEvents::
	map_events ThreeIsland_Port_EventObjects, ThreeIsland_Port_MapWarps, 0x0, 0x0
