PalletTown_ProfessorOaksLab_EventObjects:
	object_event 1, 55, 0, 3, 0, 11, 0, 3, 1, 0, 0, 0, 0, 0, 0, PalletTown_ProfessorOaksLab_EventScript_169DEE, 0, 0, 0
	object_event 2, 48, 0, 2, 0, 10, 0, 3, 3, 64, 0, 0, 0, 0, 0, PalletTown_ProfessorOaksLab_EventScript_169E46, 0, 0, 0
	object_event 3, 55, 0, 11, 0, 10, 0, 3, 1, 0, 0, 0, 0, 0, 0, PalletTown_ProfessorOaksLab_EventScript_169E1A, 0, 0, 0
	object_event 4, 71, 0, 6, 0, 3, 0, 3, 8, 17, 0, 0, 0, 0, 0, PalletTown_ProfessorOaksLab_EventScript_169595, 43, 0, 0
	object_event 5, 92, 0, 8, 0, 4, 0, 0, 8, 17, 0, 0, 0, 0, 0, PalletTown_ProfessorOaksLab_EventScript_169BAB, 40, 0, 0
	object_event 6, 92, 0, 9, 0, 4, 0, 0, 8, 17, 0, 0, 0, 0, 0, PalletTown_ProfessorOaksLab_EventScript_169D78, 41, 0, 0
	object_event 7, 92, 0, 10, 0, 4, 0, 0, 8, 17, 0, 0, 0, 0, 0, PalletTown_ProfessorOaksLab_EventScript_169DAE, 42, 0, 0
	object_event 8, 72, 0, 5, 0, 4, 0, 3, 8, 17, 0, 0, 0, 0, 0, PalletTown_ProfessorOaksLab_EventScript_16955F, 45, 0, 0
	object_event 9, 94, 0, 4, 0, 1, 0, 0, 8, 17, 0, 0, 0, 0, 0, PalletTown_ProfessorOaksLab_EventScript_169E5F, 58, 0, 0
	object_event 10, 94, 0, 5, 0, 1, 0, 0, 8, 17, 0, 0, 0, 0, 0, PalletTown_ProfessorOaksLab_EventScript_169E5F, 58, 0, 0

PalletTown_ProfessorOaksLab_MapWarps:
	warp_def 6, 12, 3, 2, 768
	warp_def 7, 12, 3, 2, 768
	warp_def 5, 12, 3, 2, 768

PalletTown_ProfessorOaksLab_MapCoordEvents:
	coord_event 5, 8, 3, 0, 16469, 2, 0, PalletTown_ProfessorOaksLab_EventScript_1692C3
	coord_event 6, 8, 3, 0, 16469, 2, 0, PalletTown_ProfessorOaksLab_EventScript_1692C3
	coord_event 7, 8, 3, 0, 16469, 2, 0, PalletTown_ProfessorOaksLab_EventScript_1692C3
	coord_event 5, 8, 3, 0, 16469, 3, 0, PalletTown_ProfessorOaksLab_EventScript_1692E7
	coord_event 6, 8, 3, 0, 16469, 3, 0, PalletTown_ProfessorOaksLab_EventScript_1692F3
	coord_event 7, 8, 3, 0, 16469, 3, 0, PalletTown_ProfessorOaksLab_EventScript_1692FF

PalletTown_ProfessorOaksLab_MapBGEvents:
	bg_event 2, 1, 0, 0, 0, PalletTown_ProfessorOaksLab_EventScript_169E68
	bg_event 3, 1, 0, 0, 0, PalletTown_ProfessorOaksLab_EventScript_169E68
	bg_event 6, 1, 0, 0, 0, PalletTown_ProfessorOaksLab_EventScript_169E71
	bg_event 7, 1, 0, 0, 0, PalletTown_ProfessorOaksLab_EventScript_169E7A

PalletTown_ProfessorOaksLab_MapEvents::
	map_events PalletTown_ProfessorOaksLab_EventObjects, PalletTown_ProfessorOaksLab_MapWarps, PalletTown_ProfessorOaksLab_MapCoordEvents, PalletTown_ProfessorOaksLab_MapBGEvents
