Name_Rival::
    .string "{RIVAL}$"

Name_Oak::
    .string "OAK$"

@NPC MAPA
PalletTown_ProfessorOaksLab_Text_Cientifico1::
    .string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Estudio a los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}.\n"
    .string "Soy ayudante del {SHADOW DYNAMIC_COLOR4}PROF. OAK{SHADOW LIGHT_GRAY}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}.$"


PalletTown_ProfessorOaksLab_Text_Cientifico3::
    .string "{COLOR DARK_GRAY}El {SHADOW DYNAMIC_COLOR4}PROF. OAK{SHADOW LIGHT_GRAY} es una eminencia en\n"
    .string "todo lo relacionado con la\l"
    .string "investigación de los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}.\p"
    .string "¡Es admirados por muchos de los\n"
    .string "{SHADOW DYNAMIC_COLOR4}ENTRENADORES POKéMON{SHADOW LIGHT_GRAY}!$"

@EVENTO ELECIÓN POKéMON INCIAL - INICIO
PalletTown_ProfessorOaksLab_Text_EstoyAburrido::
    .string "¡Abuelo!\n"
    .string "¡Ya me aburrí de tanto esperar!$"

PalletTown_ProfessorOaksLab_Text_TenPaciencia::
    .string "¿{SHADOW DYNAMIC_COLOR4}{RIVAL}{SHADOW LIGHT_GRAY}?\n"
    .string "Ten un poco de paciencia...$"

PalletTown_ProfessorOaksLab_Text_YaRecorde::
    .string "¡Oh, claro!\n"
    .string "Ya recordé por qué los llamé...$"

PalletTown_ProfessorOaksLab_Text_MiraEstasPokeballs::
    .string "{SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY}, mira estas {SHADOW DYNAMIC_COLOR4}POKé BALLS{SHADOW LIGHT_GRAY}.\n"
    .string "Cada una tiene un {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} distinto.\p"
    .string "Ya estás en edad para tener tu\n"
    .string "primer compañero de batalla.\p"
    .string "En mi juventud fui un buen\n"
    .string "{SHADOW DYNAMIC_COLOR4}ENTRENADOR POKéMON{SHADOW LIGHT_GRAY}...\p"
    .string "¡O al menos eso recuerdo!\p"
    .string "Ahora estoy pensando en jubilarme\n"
    .string "por fin...\p"
    .string "Me encantaría que ustedes continúen\n"
    .string "con este legado.$"

PalletTown_ProfessorOaksLab_Text_VoyASerElMejor::
    .string "¡Voy a ser el mejor {SHADOW DYNAMIC_COLOR4}ENTRENADOR{SHADOW LIGHT_GRAY} de\n"
    .string "todos!$"

PalletTown_ProfessorOaksLab_Text_DesdeNino::
    .string "Desde que éramos niños, siempre te\n"
    .string "he ganado en todo...$"

PalletTown_ProfessorOaksLab_Text_CualQuieres::
    .string "{SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY}, tú primero. ¿Cuál quieres\n"
    .string "para ti?$"

PalletTown_ProfessorOaksLab_Text_YoQue::
    .string "¡¿Eh?! ¿Y yo qué?$"

PalletTown_ProfessorOaksLab_Text_TambienTeDare::
    .string "¡Tranquilo, {SHADOW DYNAMIC_COLOR4}{RIVAL}{SHADOW LIGHT_GRAY}! ¡También te\n"
    .string "daré uno!\p"
    .string "Pero primero, deja que {SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY} elija...$"

@EVENTO ELECIÓN POKéMON INCIAL - ELECCIÓN POKéBALL
PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "¡Asi que {SHADOW DYNAMIC_COLOR4}CHARMANDER{SHADOW LIGHT_GRAY}!\n"
    .string "Necesitaras mucha paciencia con él.\p"
    .string "Bueno, {SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY}, entonces ¿quieres\n"
    .string "al {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} tipo {SHADOW DYNAMIC_COLOR4}FUEGO{SHADOW LIGHT_GRAY}?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "¡Asi que {SHADOW DYNAMIC_COLOR4}SQUIRTLE{SHADOW LIGHT_GRAY}!\n"
    .string "Merece la pena si o si.\p"
    .string "Bueno, {SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY}, entonces ¿quieres\n"
    .string "al {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} tipo {SHADOW DYNAMIC_COLOR4}AGUA{SHADOW LIGHT_GRAY}?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "¡Asi que {SHADOW DYNAMIC_COLOR4}BULBASAUR{SHADOW LIGHT_GRAY}!\n"
    .string "Resulta muy fácil criarlo.\p"
    .string "Bueno, {SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY}, entonces ¿quieres\n"
    .string "al {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} tipo {SHADOW DYNAMIC_COLOR4}PLANTA{SHADOW LIGHT_GRAY}?$"

@EVENTO ELECIÓN POKéMON INCIAL - MIENTRAS ELECCIÓN POKéBALL - RIVAL
PalletTown_ProfessorOaksLab_Text_SiEligesBien::
    .string "¡A ver si eliges bien, {SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY}!\p"
    .string "¡No quiero excusas cuando pierdas!$"

@EVENTO ELECIÓN POKéMON INCIAL - MIENTRAS ELECCIÓN POKéBALL - OAK
PalletTown_ProfessorOaksLab_Text_EsasTresPokeBalls::
    .string "Muy bien, {SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY}...\p"
    .string "Esas tres {SHADOW DYNAMIC_COLOR4}POKé BALLS{SHADOW LIGHT_GRAY} contienen un\n"
    .string "{SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} cada una.\p"
    .string "¿Cuál quieres para ti?$"

@EVENTO ELECIÓN POKéMON INCIAL - MIENTRAS ELECCIÓN POKéBALL - SALIDA
PalletTown_ProfessorOaksLab_Text_NoPuedesIrte::
    .string "¡No puedes irte sin un {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}!\n"
    .string "¡Es peligroso allá afuera!$"

@EVENTO ELECIÓN POKéMON INCIAL - MIENTRAS ELECCIÓN POKéBALL - NPC RIVAL
PalletTown_ProfessorOaksLab_Text_MiPokemonPareceMuchoMas::
    .string "Mi {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} parece mucho más\n"
    .string "fuerte que el tuyo.$"

@EVENTO ELECIÓN POKéMON INCIAL - MIENTRAS ELECCIÓN POKéBALL - POKéBALL ELEGIDA
PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "{COLOR DARK_GRAY}¡Recibiste a {SHADOW DYNAMIC_COLOR4}{STR_VAR_1}{SHADOW LIGHT_GRAY}\n"
    .string "de parte del {SHADOW DYNAMIC_COLOR4}PROF. OAK{SHADOW LIGHT_GRAY}!$"

PalletTown_ProfessorOaksLab_Text_EsePokemonTiene::
    .string "¡Ese {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} tiene mucha energía!$"

PalletTown_ProfessorOaksLab_Text_EntoncesEsteSera::
    .string "¡Entonces, este será el mío!$"

PalletTown_ProfessorOaksLab_Text_SiApareceUnPokemon::
    .string "Si aparece un {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} salvaje,\n"
    .string "tu compañero podrá defenderte.\p"
    .string "Con su ayuda, no te será difícil\n"
    .string "llegar a la siguiente ciudad.$"

@EVENTO ELECIÓN POKéMON INCIAL - MIENTRAS ELECCIÓN POKéBALL - BATALLA CON EL RIVAL
PalletTown_ProfessorOaksLab_Text_NoVasAHuir::
    .string "¡Espera, {SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY}!\p"
    .string "¡No vas a huir sin una pelea,\n"
    .string "¿verdad?!\p"
    .string "¡Vamos, probemos a nuestros {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}!\n"
    .string "¡Quiero ver si estás a la altura!$"

PalletTown_ProfessorOaksLab_Text_HareQueMi::
    .string "¡De acuerdo!\p"
    .string "¡Haré que mi {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} participe en\n"
    .string "más batallas!\p"
    .string "Así potenciaré al máximo sus\n"
    .string "habilidades.$"

@AUN SIN REVISAR
PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "{COLOR DARK_GRAY}{SHADOW DYNAMIC_COLOR4}{RIVAL}:{SHADOW LIGHT_GRAY} ¿Qué haces aqui, {SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY}?\p"
    .string "Abuelo no está.$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "¿QUÉ?\p"
    .string "¡NO LO PUEDO CREER!\n"
    .string "¡ESCOGÍ EL POKéMON EQUIVOCADO!$"

@ Also used for early Route 22 battle
Text_RivalVictory::
    .string "¡Bien!\n"
    .string "¿No soy el mejor?$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "{RIVAL}: Gramps!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "{RIVAL}: I almost forgot!\n"
    .string "What did you call me for?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "{RIVAL}: All right, Gramps!\n"
    .string "Leave it all to me!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "{PLAYER}, I hate to say it, but you\n"
    .string "won't be necessary for this.\p"
    .string "I know! I'll borrow a TOWN MAP\n"
    .string "from my sis!\p"
    .string "I'll tell her not to lend you one,\n"
    .string "{PLAYER}! Hahaha!\p"
    .string "Don't bother coming around to\n"
    .string "my place after this!$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
.string "{COLOR DARK_GRAY}{SHADOW DYNAMIC_COLOR4}PROF. OAK:{SHADOW LIGHT_GRAY} ¡{SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY}, entrena a tu\n"
.string "{SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} en batalla!$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "OAK: Oh, {PLAYER}!\n"
    .string "How is my old POKéMON?\p"
    .string "Well, it seems to be growing more\n"
    .string "attached to you.\p"
    .string "You must be talented as a POKéMON\n"
    .string "TRAINER.\p"
    .string "What's that?\n"
    .string "You have something for me?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "{PLAYER} delivered OAK'S PARCEL.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "AHHHh!\n"
    .string "It's the custom POKé BALL!\p"
    .string "I had it on order.\n"
    .string "Thank you!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "OAK: Oh, right!\n"
    .string "I have a request for you two.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "On the desk there is my invention,\n"
    .string "the POKéDEX!\p"
    .string "It automatically records data on\n"
    .string "POKéMON you've seen or caught.\p"
    .string "It's a high-tech encyclopedia!$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "OAK: {PLAYER} and {RIVAL}.\n"
    .string "Take these with you.$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "OAK: You can't get detailed data\n"
    .string "on POKéMON by just seeing them.\p"
    .string "You must catch them to obtain\n"
    .string "complete data.\p"
    .string "So, here are some tools for\n"
    .string "catching wild POKéMON.$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "When a wild POKéMON appears,\n"
    .string "it's fair game.\p"
    .string "Just throw a POKé BALL at it and\n"
    .string "try to catch it!\p"
    .string "This won't always work, however.\p"
    .string "A healthy POKéMON can escape.\n"
    .string "You have to be lucky!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "To make a complete guide on all\n"
    .string "the POKéMON in the world…\p"
    .string "That was my dream!\p"
    .string "But, I'm too old.\n"
    .string "I can't get the job done.\p"
    .string "So, I want you two to fulfill my\n"
    .string "dream for me.\p"
    .string "Get moving, you two.\p"
    .string "This is a great undertaking in\n"
    .string "POKéMON history!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
.string "{SHADOW DYNAMIC_COLOR4}PROF. OAK{SHADOW LIGHT_GRAY}: {SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY}, los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} de\n"
.string "{SHADOW DYNAMIC_COLOR4}KANTO{SHADOW LIGHT_GRAY} te espera!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "Ah, {PLAYER}!\n"
    .string "How is your POKéDEX shaping up?\p"
    .string "{RIVAL} has already caught some\n"
    .string "POKéMON and added to the data.\p"
    .string "So, {PLAYER}, let's have a look at\n"
    .string "your POKéDEX.\p"
    .string "…What's the matter?\n"
    .string "You've added no new data at all.\p"
    .string "I'll give you these, so do try a\n"
    .string "little harder.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "OAK: Come see me sometime.\p"
    .string "After all, I want to know how your\n"
    .string "POKéDEX is coming along.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "It's like an encyclopedia, but the\n"
    .string "pages are blank.$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "¡Eso de ahí son las {SHADOW DYNAMIC_COLOR4}POKé BALLS{SHADOW LIGHT_GRAY}!\n"
    .string "¡Dentro de ellas hay {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "Es el último {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} del {SHADOW DYNAMIC_COLOR4}PROF. OAK{SHADOW LIGHT_GRAY}.$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "Press START to open the MENU!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "The SAVE option is on the MENU.\n"
    .string "Use it regularly.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "All POKéMON types have strong and\n"
    .string "weak points against others.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "There's an e-mail message here.\p"
    .string "…\p"
    .string "Finally!\n"
    .string "The ultimate TRAINERS of the\l"
    .string "POKéMON LEAGUE are ready to\l"
    .string "take on all comers!\p"
    .string "Bring your best POKéMON and see\n"
    .string "how you rate as a TRAINER!\p"
    .string "POKéMON LEAGUE HQ\n"
    .string "INDIGO PLATEAU\p"
    .string "PROF. OAK, please visit us!\n"
    .string "…$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "Hi, {PLAYER}. I bet you've become\n"
    .string "good friends with your POKéMON.\p"
    .string "By the way, did you know about\n"
    .string "DAISY?\p"
    .string "If you show DAISY your POKéMON,\n"
    .string "she can tell how much it likes you.\p"
    .string "Occasionally, she will even groom\n"
    .string "a POKéMON for you.\p"
    .string "This is a secret, so please don't\n"
    .string "tell anyone.$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "PROF. OAK is going to have his own\n"
    .string "radio show soon.\p"
    .string "The program will be called PROF.\n"
    .string "OAK's POKéMON SEMINAR.$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "Ah, now this is excellent!\p"
    .string "{PLAYER}, I have another important\n"
    .string "favor to ask of you.\p"
    .string "I need you to listen closely.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "Recently, there have been sightings\n"
    .string "of many rare POKéMON species.\p"
    .string "I'm talking about POKéMON that\n"
    .string "have never been seen in KANTO.\p"
    .string "I would love to go see things for\n"
    .string "myself, but I'm much too old.\p"
    .string "Since I can't do it, {PLAYER}, I'd\n"
    .string "like you to go in my place.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "{RIVAL}: Hey! Gramps! No fair!\n"
    .string "What about me?$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "OAK: I know, I know.\n"
    .string "Of course I need your help, too.\p"
    .string "Now, I need to see both your\n"
    .string "POKéDEXES.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "PROF. OAK took both POKéDEX\n"
    .string "units.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "… … …  … … …\p"
    .string "… … …  … … …\p"
    .string "…And that's done!\p"
    .string "Now these units can record data on\n"
    .string "a lot more POKéMON.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "{PLAYER}'s POKéDEX was upgraded!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "Now, {PLAYER} and {RIVAL}!\p"
    .string "This time, you really must work\n"
    .string "towards filling your POKéDEXES.\p"
    .string "I urge you to make them the best\n"
    .string "and the most complete of all time!\p"
    .string "Truly, this is a monumentally great\n"
    .string "undertaking in POKéMON history!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "{RIVAL}: Gramps, calm down.\n"
    .string "Don't get so excited.\p"
    .string "I'll get the POKéDEX completed,\n"
    .string "don't you worry about a thing.\p"
    .string "I think I'll try looking around\n"
    .string "ONE ISLAND first…\p"
    .string "Anyways, I'm outta here!$"

@EVENTO RECIBIR POKEDEX Y POKERADAR
PalletTown_ProfessorOaksLab_Text_QueAlegriaVertePorAqui::
    .string "¡{SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY}!\n"
    .string "¡Qué alegría verte por aquí!\p"
    .string "¿Cómo va todo con tu {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}?\p"
    .string "¡Se nota que ha creado un fuerte\n"
    .string "lazo contigo!$"

PalletTown_ProfessorOaksLab_Text_RojoMeAcaba::
    .string "{SHADOW DYNAMIC_COLOR4}ROJO{SHADOW LIGHT_GRAY} me acaba de traer unas {SHADOW DYNAMIC_COLOR4}POKéDEX{SHADOW LIGHT_GRAY}\n"
    .string "que envió mi colega, el {SHADOW DYNAMIC_COLOR4}PROF. ELM{SHADOW LIGHT_GRAY},\l"
    .string "desde {SHADOW DYNAMIC_COLOR4}PUEBLO PRIMAVERA{SHADOW LIGHT_GRAY}.$"

PalletTown_ProfessorOaksLab_Text_HojaMeAcaba::
    .string "{SHADOW DYNAMIC_COLOR4}HOJA{SHADOW LIGHT_GRAY} me acaba de traer unas {SHADOW DYNAMIC_COLOR4}POKéDEX{SHADOW LIGHT_GRAY}\n"
    .string "que envió mi colega, el {SHADOW DYNAMIC_COLOR4}PROF. ELM{SHADOW LIGHT_GRAY},\l"
    .string "desde {SHADOW DYNAMIC_COLOR4}PUEBLO PRIMAVERA{SHADOW LIGHT_GRAY}.$"

PalletTown_ProfessorOaksLab_Text_YAhoraQueNecesitas::
    .string "¿Y ahora qué necesitas?\p"
    .string "Estoy ocupado...\p"
    .string "Tengo cosas más importantes\n"
    .string "que hacer...$"

PalletTown_ProfessorOaksLab_Text_RelajateUnPoco::
    .string "¡Relájate un poco, {SHADOW DYNAMIC_COLOR4}{RIVAL}{SHADOW LIGHT_GRAY}!\n"
    .string "Lo que quiero es pedirles un favor\l"
    .string "muy especial...$"

PalletTown_ProfessorOaksLab_Text_HeDedicadoMiVida::
    .string "He dedicado toda mi vida a crear una\n"
    .string "{SHADOW DYNAMIC_COLOR4}ENCICLOPEDIA POKéMON{SHADOW LIGHT_GRAY}, conocida\l"
    .string "como {SHADOW DYNAMIC_COLOR4}POKéDEX{SHADOW LIGHT_GRAY}.$"

PalletTown_ProfessorOaksLab_Text_GenialConEsaEnciclpedia::
    .string "¡Perfecto!\p"
    .string "Con esa enciclopedia voy a poder\n"
    .string "identificar a los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} más\l"
    .string "fuertes...$"

PalletTown_ProfessorOaksLab_Text_YAtraprlosAntes::
    .string "¡Y atraparlos antes que ustedes!$"

PalletTown_ProfessorOaksLab_Text_MiColegaElm::
    .string "Mi colega {SHADOW DYNAMIC_COLOR4}ELM{SHADOW LIGHT_GRAY} me está ayudando a\n"
    .string "mejorar esta herramienta.\p"
    .string "La hemos actualizado con información\n"
    .string "sobre nuevas especies.\p"
    .string "Las {SHADOW DYNAMIC_COLOR4}POKéDEX{SHADOW LIGHT_GRAY} que me envió están\n"
    .string "completamente vacías.\p"
    .string "Por eso quiero pedirles una misión de\n"
    .string "gran importancia...\p"
    .string "¿Estarían dispuestos a llenarlas con\n"
    .string "información de todos los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} de\l"
    .string "la región de {SHADOW DYNAMIC_COLOR4}KANTO{SHADOW LIGHT_GRAY}?$"

PalletTown_ProfessorOaksLab_Text_OyeAbuelo::
    .string "¡Oye, abuelo!\p"
    .string "Lo que estás pidiendo...\p"
    .string "Es completamente imposible...$"

PalletTown_ProfessorOaksLab_Text_QuieroQueRecorranCada::
    .string "Quiero que recorran cada rincón y\n"
    .string "descubran todos los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} que\l"
    .string "habitan en esta región.$"

PalletTown_ProfessorOaksLab_Text_RecibisteUnaPokedex::
    .string "{COLOR DARK_GRAY}¡Recibiste una {SHADOW DYNAMIC_COLOR4}POKéDEX{SHADOW LIGHT_GRAY}\n"
    .string "de parte del {SHADOW DYNAMIC_COLOR4}PROF. OAK{SHADOW LIGHT_GRAY}!$"

PalletTown_ProfessorOaksLab_Text_LesProporcionareAlgunas::
    .string "Les proporcionaré algunas {SHADOW DYNAMIC_COLOR4}POKéBALLS{SHADOW LIGHT_GRAY}\n"
    .string "para que puedan comenzar la tarea\l"
    .string "del mejor modo posible.$"

PalletTown_ProfessorOaksLab_Text_RecibistePokeBalls::
    .string "{COLOR DARK_GRAY}¡Recibiste 5 {SHADOW DYNAMIC_COLOR4}POKé BALLS{SHADOW LIGHT_GRAY}\n"
    .string "de parte del {SHADOW DYNAMIC_COLOR4}PROF. OAK{SHADOW LIGHT_GRAY}!$"

PalletTown_ProfessorOaksLab_Text_RecibistePokeRadar::
    .string "{COLOR DARK_GRAY}¡Recibiste un {SHADOW DYNAMIC_COLOR4}POKéRADAR{SHADOW LIGHT_GRAY}\n"
    .string "de parte del {SHADOW DYNAMIC_COLOR4}PROF. OAK{SHADOW LIGHT_GRAY}!$"

PalletTown_ProfessorOaksLab_Text_HaObtenidPokerada::
    .string "¡{SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY} ha obtenido un {SHADOW DYNAMIC_COLOR4}POKéRADAR{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}!$"

PalletTown_ProfessorOaksLab_Text_ElPokeRadarLesIndicara::
    .string "El {SHADOW DYNAMIC_COLOR4}POKéRADAR{SHADOW LIGHT_GRAY} les indicará las zonas\n"
    .string "de hierba donde podría haber\l"
    .string "{SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} escondidos.\p"
    .string "Estoy seguro de que les será de gran\n"
    .string "ayuda para ustedes.$"

PalletTown_ProfessorOaksLab_Text_QueFastidio::
    .string "¡Qué fastidio!\p"
    .string "¡Yo quería ir ya por las medallas de\n"
    .string "gimnasio, no ponerme a llenar una\l"
    .string "{SHADOW DYNAMIC_COLOR4}POKéDEX{SHADOW LIGHT_GRAY}!\p"
    .string "Esto es una pérdida de tiempo...$"

PalletTown_ProfessorOaksLab_Text_NadieTeImpide::
    .string "Nadie te impide desafiar a los\n"
    .string "líderes de gimnasio.\p"
    .string "Cada quien vive su aventura a su\n"
    .string "ritmo.\p"
    .string "Pero en el camino, puedes ayudarme\n"
    .string "con la {SHADOW DYNAMIC_COLOR4}POKéDEX{SHADOW LIGHT_GRAY}.\p"
    .string "Sería un gesto valioso para tu viejo\n"
    .string "abuelo.$"

PalletTown_ProfessorOaksLab_Text_RojoSoloUnoDeNosotros::
    .string "{SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY}... {SHADOW DYNAMIC_COLOR4}ROJO{SHADOW LIGHT_GRAY}...\p"
    .string "Solo uno de nosotros llegará a ser\n"
    .string "un verdadero {SHADOW DYNAMIC_COLOR4}MAESTRO POKéMON{SHADOW LIGHT_GRAY}.\p"
    .string "Y créanme, ese voy a ser yo.\n"
    .string "Sin ayuda. Sin distracciones.$"

PalletTown_ProfessorOaksLab_Text_HojaSoloUnoDeNosotros::
    .string "{SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY}... {SHADOW DYNAMIC_COLOR4}HOJA{SHADOW LIGHT_GRAY}...\n"
    .string "Solo uno de nosotros llegará a ser\n"
    .string "un verdadero {SHADOW DYNAMIC_COLOR4}MAESTRO POKéMON{SHADOW LIGHT_GRAY}.\p"
    .string "Y créanme, ese voy a ser yo.\n"
    .string "Sin ayuda. Sin distracciones.$"

PalletTown_ProfessorOaksLab_Text_EstoyEmocionado::
    .string "¡Estoy emocionado por la aventura!\p"
    .string "Iré a explorar el {SHADOW DYNAMIC_COLOR4}BOSQUE VERDE{SHADOW LIGHT_GRAY}.\p"
    .string "Debe haber {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} increíbles por\n"
    .string "allí.$"

PalletTown_ProfessorOaksLab_Text_EstoyEmocionada::
    .string "¡Estoy emocionada por la aventura!\p"
    .string "Iré a explorar el {SHADOW DYNAMIC_COLOR4}BOSQUE VERDE{SHADOW LIGHT_GRAY}.\p"
    .string "Debe haber {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}  increíbles por\n"
    .string "allí.$"

PalletTown_ProfessorOaksLab_Text_LosPokemonDeLaRegion::
    .string "¡Los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} de la región los\n"
    .string "esperan!\p"
    .string "¡Buena suerte!$"