PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround:: @ 818DC67
    .string "{RIVAL}: What, it's only {PLAYER}?\n"
    .string "Gramps isn't around.$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting:: @ 818DC94
    .string "{RIVAL}: Gramps!\n"
    .string "I'm fed up with waiting!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe:: @ 818DCB9
    .string "{RIVAL}: Hey! Gramps! No fair!\n"
    .string "What about me?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer:: @ 818DCE2
    .string "{RIVAL}: Heh, I don't need to be\n"
    .string "greedy like you. I'm mature!\p"
    .string "Go ahead and choose, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen:: @ 818DD34
    .string "{RIVAL}: I'll take this one, then!$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak:: @ 818DD52
    .string "{RIVAL} received the {STR_VAR_1}\n"
    .string "from Prof. Oak!$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher:: @ 818DD75
    .string "{RIVAL}: My Pokémon looks a lot\n"
    .string "tougher than yours.$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons:: @ 818DDA4
    .string "{RIVAL}: Wait, {PLAYER}!\n"
    .string "Let's check out our Pokémon!\p"
    .string "Come on, I'll take you on!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat:: @ 818DDEA
    .string "What?\n"
    .string "Unbelievable!\l"
    .string "I picked the wrong Pokémon!$"

@ Also used for early Route 22 battle
Text_RivalVictory:: @ 818DE1A
    .string "{RIVAL}: Yeah!\n"
    .string "Am I great or what?$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon:: @ 818DE38
    .string "{RIVAL}: Okay! I'll make my\n"
    .string "Pokémon battle to toughen it up!\p"
    .string "{PLAYER}! Gramps!\n"
    .string "Smell you later!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps:: @ 818DE8D
    .string "{RIVAL}: Gramps!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor:: @ 818DE99
    .string "{RIVAL}: I almost forgot!\n"
    .string "What did you call me for?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps:: @ 818DEC8
    .string "{RIVAL}: All right, Gramps!\n"
    .string "Leave it all to me!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap:: @ 818DEF3
    .string "{PLAYER}, I hate to say it, but you\n"
    .string "won't be necessary for this.\p"
    .string "I know! I'll borrow a Town Map\n"
    .string "from my sis!\p"
    .string "I'll tell her not to lend you one,\n"
    .string "{PLAYER}! Hahaha!\p"
    .string "Don't bother coming around to\n"
    .string "my place after this!$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne:: @ 818DFBC
    .string "Oak: {RIVAL}?\n"
    .string "Let me think…\p"
    .string "Oh, that's right, I told you to\n"
    .string "come! Just wait!\p"
    .string "Here, {PLAYER}.\p"
    .string "There are three Pokémon here.\p"
    .string "Haha!\p"
    .string "The Pokémon are held inside\n"
    .string "these Poké Balls.\p"
    .string "When I was young, I was a serious\n"
    .string "Pokémon Trainer.\p"
    .string "But now, in my old age, I have\n"
    .string "only these three left.\p"
    .string "You can have one.\n"
    .string "Go on, choose!$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival:: @ 818E0EA
    .string "Oak: Be patient, {RIVAL}.\n"
    .string "You can have one, too!$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose:: @ 818E116
    .string "Oak: Now, {PLAYER}.\p"
    .string "Inside those three Poké Balls are\n"
    .string "Pokémon.\p"
    .string "Which one will you choose for\n"
    .string "yourself?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet:: @ 818E177
    .string "Oak: Hey!\n"
    .string "Don't go away yet!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander:: @ 818E194
    .string "Ah! Charmander is your choice.\n"
    .string "You should raise it patiently.\p"
    .string "So, {PLAYER}, you're claiming the\n"
    .string "Fire Pokémon Charmander?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle:: @ 818E207
    .string "Hm! Squirtle is your choice.\n"
    .string "It's one worth raising.\p"
    .string "So, {PLAYER}, you've decided on the\n"
    .string "Water Pokémon Squirtle?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur:: @ 818E272
    .string "I see! Bulbasaur is your choice.\n"
    .string "It's very easy to raise.\p"
    .string "So, {PLAYER}, you want to go with\n"
    .string "the Grass Pokémon Bulbasaur?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic:: @ 818E2E5
    .string "This Pokémon is really quite\n"
    .string "energetic!$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak:: @ 818E30D
    .string "{PLAYER} received the {STR_VAR_1}\n"
    .string "from Prof. Oak!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon:: @ 818E330
    .string "Oak: If a wild Pokémon appears,\n"
    .string "your Pokémon can battle it.\p"
    .string "With it at your side, you should be\n"
    .string "able to reach the next town.$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow:: @ 818E3AD
    .string "Oak: {PLAYER}, raise your young\n"
    .string "Pokémon by making it battle.\p"
    .string "It has to battle for it to grow.$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe:: @ 818E405
    .string "Oak: Oh, {PLAYER}!\n"
    .string "How is my old Pokémon?\p"
    .string "Well, it seems to be growing more\n"
    .string "attached to you.\p"
    .string "You must be talented as a Pokémon\n"
    .string "Trainer.\p"
    .string "What's that?\n"
    .string "You have something for me?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel:: @ 818E4AF
    .string "{PLAYER} delivered Oak's Parcel.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered:: @ 818E4CA
    .string "Ah! \n"
    .string "It's the custom Poké Ball!\p"
    .string "I had it on order.\n"
    .string "Thank you!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo:: @ 818E508
    .string "Oak: Oh, right!\n"
    .string "I have a request for you two.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk:: @ 818E536
    .string "On the desk there is my invention,\n"
    .string "the Pokédex!\p"
    .string "It automatically records data on\n"
    .string "Pokémon you've seen or caught.\p"
    .string "It's a high-tech encyclopedia!$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou:: @ 818E5C5
    .string "Oak: {PLAYER} and {RIVAL}.\n"
    .string "Take these with you.$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak:: @ 818E5EA
    .string "{PLAYER} received the Pokédex\n"
    .string "from Prof. Oak.$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese:: @ 818E612
    .string "Oak: You can't get detailed data\n"
    .string "on Pokémon by just seeing them.\p"
    .string "You must catch them to obtain\n"
    .string "complete data.\p"
    .string "So, here are some tools for\n"
    .string "catching wild Pokémon.$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls:: @ 818E6B3
    .string "{PLAYER} received five Poké Balls.$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching:: @ 818E6D0
    .string "When a wild Pokémon appears,\n"
    .string "it's fair game.\p"
    .string "Just throw a Poké Ball at it and\n"
    .string "try to catch it!\p"
    .string "This won't always work, however.\p"
    .string "A healthy Pokémon can escape.\n"
    .string "You have to be lucky!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream:: @ 818E784
    .string "To make a complete guide on all\n"
    .string "the Pokémon in the world…\p"
    .string "That was my dream!\p"
    .string "But, I'm too old.\n"
    .string "I can't get the job done.\p"
    .string "So, I want you two to fulfill my\n"
    .string "dream for me.\p"
    .string "Get moving, you two.\p"
    .string "This is a great undertaking in\n"
    .string "Pokémon history!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait:: @ 818E871
    .string "Pokémon around the world wait for\n"
    .string "you, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex:: @ 818E89C
    .string "Ah, {PLAYER}!\n"
    .string "How is your Pokédex shaping up?\p"
    .string "{RIVAL} has already caught some\n"
    .string "Pokémon and added to the data.\p"
    .string "So, {PLAYER}, let's have a look at\n"
    .string "your Pokédex.\p"
    .string "…What's the matter?\n"
    .string "You've added no new data at all.\p"
    .string "I'll give you these, so do try a\n"
    .string "little harder.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime:: @ 818E98E
    .string "Oak: Come see me sometime.\p"
    .string "After all, I want to know how your\n"
    .string "Pokédex is coming along.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia:: @ 818E9E5
    .string "It's like an encyclopedia, but the\n"
    .string "pages are blank.$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls:: @ 818EA19
    .string "Those are Poké Balls.\n"
    .string "They contain Pokémon!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon:: @ 818EA45
    .string "That's Prof. Oak's last Pokémon.$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu:: @ 818EA66
    .string "Press Start to open the Menu!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu:: @ 818EA84
    .string "The Save option is on the Menu.\n"
    .string "Use it regularly.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints:: @ 818EAB6
    .string "All Pokémon types have strong and\n"
    .string "weak points against others.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage:: @ 818EAF4
    .string "There's an e-mail message here.\p"
    .string "…\p"
    .string "Finally!\n"
    .string "The ultimate Trainers of the\l"
    .string "Pokémon League are ready to\l"
    .string "take on all comers!\p"
    .string "Bring your best Pokémon and see\n"
    .string "how you rate as a Trainer!\p"
    .string "Pokémon League HQ\n"
    .string "Indigo Plateau\p"
    .string "Prof. Oak, please visit us!\n"
    .string "…$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide:: @ 818EBE6
    .string "I study Pokémon as Prof. Oak's\n"
    .string "Aide.$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons:: @ 818EC0B
    .string "Hi, {PLAYER}. I bet you've become\n"
    .string "good friends with your Pokémon.\p"
    .string "By the way, did you know about\n"
    .string "Daisy?\p"
    .string "If you show Daisy your Pokémon,\n"
    .string "she can tell how much it likes you.\p"
    .string "Occasionally, she will even groom\n"
    .string "a Pokémon for you.\p"
    .string "This is a secret, so please don't\n"
    .string "tell anyone.$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow:: @ 818ED15
    .string "Prof. Oak is going to have his own\n"
    .string "radio show soon.\p"
    .string "The program will be called Prof.\n"
    .string "Oak's Pokémon Seminar.$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons:: @ 818ED81
    .string "Prof. Oak may not look like much,\n"
    .string "but he's the authority on Pokémon.\p"
    .string "Many Pokémon Trainers hold him in\n"
    .string "high regard.$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer:: @ 818EDF5
    .string "Ah, now this is excellent!\p"
    .string "{PLAYER}, I have another important\n"
    .string "favor to ask of you.\p"
    .string "I need you to listen closely.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons:: @ 818EE60
    .string "Recently, there have been sightings\n"
    .string "of many rare Pokémon species.\p"
    .string "I'm talking about Pokémon that\n"
    .string "have never been seen in Kanto.\p"
    .string "I would love to go see things for\n"
    .string "myself, but I'm much too old.\p"
    .string "Since I can't do it, {PLAYER}, I'd\n"
    .string "like you to go in my place.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything:: @ 818EF59
    .string "{RIVAL}: Hey, I heard that!\p"
    .string "Gramps, what's with favoring\n"
    .string "{PLAYER} over me all the time?\p"
    .string "I went and collected more Pokémon,\n"
    .string "and faster, too.\p"
    .string "You should just let me handle\n"
    .string "everything.$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes:: @ 818F004
    .string "Oak: I know, I know.\n"
    .string "Of course I need your help, too.\p"
    .string "Now, I need to see both your\n"
    .string "Pokédexes.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits:: @ 818F062
    .string "Prof. Oak took both Pokédex\n"
    .string "units.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData:: @ 818F085
    .string "… … …  … … …\p"
    .string "… … …  … … …\p"
    .string "…And that's done!\p"
    .string "Now these units can record data on\n"
    .string "a lot more Pokémon.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded:: @ 818F0E8
    .string "{PLAYER}'s Pokédex was upgraded!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex:: @ 818F103
    .string "Now, {PLAYER} and {RIVAL}!\p"
    .string "This time, you really must work\n"
    .string "towards filling your Pokédexes.\p"
    .string "I urge you to make them the best\n"
    .string "and the most complete of all time!\p"
    .string "Truly, this is a monumentally great\n"
    .string "undertaking in Pokémon history!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex:: @ 818F1DB
    .string "{RIVAL}: Gramps, calm down.\n"
    .string "Don't get so excited.\p"
    .string "I'll get the Pokédex completed,\n"
    .string "don't you worry about a thing.\p"
    .string "I think I'll try looking around\n"
    .string "One Island first…\p"
    .string "Anyways, I'm outta here!$"

