FourIsland_Mart_EventObjects:
	object_event 1, 68, 0, 2, 0, 3, 0, 0, 10, 17, 0, 0, 0, 0, 0, FourIsland_Mart_EventScript_171CAE, 0, 0, 0
	object_event 2, 32, 0, 6, 0, 5, 0, 3, 10, 17, 0, 0, 0, 0, 0, FourIsland_Mart_EventScript_1ACF46, 0, 0, 0
	object_event 3, 39, 0, 8, 0, 3, 0, 3, 2, 18, 0, 0, 0, 0, 0, FourIsland_Mart_EventScript_171CE8, 0, 0, 0

FourIsland_Mart_MapWarps:
	warp_def 4, 7, 3, 7, 783

FourIsland_Mart_MapEvents::
	map_events FourIsland_Mart_EventObjects, FourIsland_Mart_MapWarps, 0x0, 0x0
