FourIsland_Mart_Text_LoreleiGrewUpOnThisIsland::
    .string "We've had a great and powerful\n"
    .string "Trainer grow up on this island.\p"
    .string "I bet even you'd know her.\n"
    .string "It's Lorelei of the Elite Four!\p"
    .string "When Lorelei was just a tyke,\n"
    .string "I taught her about Pokémon.$"

FourIsland_Mart_Text_IcefallCaveIsFrigid::
    .string "The Sevii Islands are in a warm\n"
    .string "region overall.\p"
    .string "But there is one exception you\n"
    .string "need to know about.\p"
    .string "The Icefall Cave is frigid because\n"
    .string "of the Pokémon that live in it.$"

