Route11_EastEntrance_1F_EventObjects:
	object_event 1, 60, 0, 6, 0, 2, 0, 3, 8, 17, 0, 0, 0, 0, 0, Route11_EastEntrance_1F_EventScript_16FD22, 0, 0, 0
	object_event 2, 60, 0, 4, 0, 10, 0, 0, 7, 17, 0, 0, 0, 0, 0, Route11_EastEntrance_1F_EventScript_16FD2B, 0, 0, 0

Route11_EastEntrance_1F_MapWarps:
	warp_def 1, 6, 3, 1, 797
	warp_def 1, 7, 3, 1, 797
	warp_def 11, 6, 3, 2, 797
	warp_def 11, 7, 3, 2, 797
	warp_def 9, 10, 3, 0, 5633

Route11_EastEntrance_1F_MapEvents::
	map_events Route11_EastEntrance_1F_EventObjects, Route11_EastEntrance_1F_MapWarps, 0x0, 0x0
