Route9_Text_AliciaIntro::
    .string "You have Pokémon with you!\n"
    .string "You're mine!$"

Route9_Text_AliciaDefeat::
    .string "You deceived me…$"

Route9_Text_AliciaPostBattle::
    .string "The tunnel coming up is pitch-black\n"
    .string "inside.\p"
    .string "You'll need Flash to get through\n"
    .string "there.$"

Route9_Text_ChrisIntro::
    .string "Who's that walking there with those\n"
    .string "good-looking Pokémon?$"

Route9_Text_ChrisDefeat::
    .string "Out like a light!$"

Route9_Text_ChrisPostBattle::
    .string "Keep walking!$"

Route9_Text_DrewIntro::
    .string "I'm taking the Rock Tunnel to\n"
    .string "go to Lavender…$"

Route9_Text_DrewDefeat::
    .string "Can't measure up…$"

Route9_Text_DrewPostBattle::
    .string "Are you off to Rock Tunnel, too?$"

Route9_Text_CaitlinIntro::
    .string "Don't you dare patronize me!$"

Route9_Text_CaitlinDefeat::
    .string "No!\n"
    .string "You're too much.$"

Route9_Text_CaitlinPostBattle::
    .string "You're obviously talented.\n"
    .string "Good luck to you!$"

Route9_Text_JeremyIntro::
    .string "Bwahaha!\n"
    .string "Great! I was bored, eh!$"

Route9_Text_JeremyDefeat::
    .string "Keep it coming, eh!\p"
    .string "Oh wait.\n"
    .string "I'm out of Pokémon!$"

Route9_Text_JeremyPostBattle::
    .string "You sure had guts standing up to\n"
    .string "me there, eh?$"

Route9_Text_BriceIntro::
    .string "Hahaha!\n"
    .string "Aren't you a little toughie!$"

Route9_Text_BriceDefeat::
    .string "What's that?$"

Route9_Text_BricePostBattle::
    .string "Hahaha!\n"
    .string "Kids should be tough!$"

Route9_Text_BrentIntro::
    .string "I got up early every day to raise\n"
    .string "my Pokémon from cocoons!$"

Route9_Text_BrentDefeat::
    .string "What?\p"
    .string "What a total waste of time!$"

Route9_Text_BrentPostBattle::
    .string "I have to collect more than bugs\n"
    .string "to get stronger…$"

Route9_Text_AlanIntro::
    .string "Hahahaha!\n"
    .string "Bring it on!$"

Route9_Text_AlanDefeat::
    .string "Hahahaha!\n"
    .string "You beat me fair!$"

Route9_Text_AlanPostBattle::
    .string "Hahahaha!\n"
    .string "Us hearty guys always laugh!$"

Route9_Text_ConnerIntro::
    .string "Go, my super Bug Pokémon!$"

Route9_Text_ConnerDefeat::
    .string "My bugs…$"

Route9_Text_ConnerPostBattle::
    .string "If you don't like Bug Pokémon,\n"
    .string "you bug me!$"

Route9_Text_RouteSign::
    .string "Route 9\n"
    .string "Cerulean City - Rock Tunnel$"

