FiveIsland_PokemonCenter_1F_EventObjects:
	object_event 1, 64, 0, 7, 0, 2, 0, 3, 8, 17, 0, 0, 0, 0, 0, FiveIsland_PokemonCenter_1F_EventScript_171D00, 0, 0, 0
	object_event 2, 42, 0, 9, 0, 4, 0, 3, 7, 17, 0, 0, 0, 0, 0, FiveIsland_PokemonCenter_1F_EventScript_171D12, 0, 0, 0
	object_event 3, 59, 0, 4, 0, 8, 0, 3, 5, 17, 0, 0, 0, 0, 0, FiveIsland_PokemonCenter_1F_EventScript_171D09, 0, 0, 0
	object_event 4, 0, 0, 2, 0, 1, 0, 0, 76, 17, 0, 0, 0, 0, 0, FiveIsland_PokemonCenter_1F_EventScript_1ACF5F, 157, 0, 0
	object_event 5, 0, 0, 3, 0, 1, 0, 0, 76, 17, 0, 0, 0, 0, 0, FiveIsland_PokemonCenter_1F_EventScript_1ACF5F, 157, 0, 0

FiveIsland_PokemonCenter_1F_MapWarps:
	warp_def 7, 8, 3, 1, 784
	warp_def 1, 6, 4, 0, 9217

FiveIsland_PokemonCenter_1F_MapEvents::
	map_events FiveIsland_PokemonCenter_1F_EventObjects, FiveIsland_PokemonCenter_1F_MapWarps, 0x0, 0x0
