# 1 "data/maps/SafariZone_Center_RestHouse/scripts.pory"

# 2 "data/maps/SafariZone_Center_RestHouse/scripts.pory"
SafariZone_Center_RestHouse_MapScripts::
# 3 "data/maps/SafariZone_Center_RestHouse/scripts.pory"
	.byte 0
# 4 "data/maps/SafariZone_Center_RestHouse/scripts.pory"

# 5 "data/maps/SafariZone_Center_RestHouse/scripts.pory"
SafariZone_Center_RestHouse_EventScript_Sara::
# 6 "data/maps/SafariZone_Center_RestHouse/scripts.pory"
	msgbox SafariZone_Center_Text_WhereDidErikGo, MSGBOX_NPC
# 7 "data/maps/SafariZone_Center_RestHouse/scripts.pory"
	end
# 8 "data/maps/SafariZone_Center_RestHouse/scripts.pory"

# 9 "data/maps/SafariZone_Center_RestHouse/scripts.pory"
SafariZone_Center_RestHouse_EventScript_Scientist::
# 10 "data/maps/SafariZone_Center_RestHouse/scripts.pory"
	msgbox SafariZone_Center_Text_CatchingMonsAsGifts, MSGBOX_NPC
# 11 "data/maps/SafariZone_Center_RestHouse/scripts.pory"
	end
