# 1 "data/maps/ThreeIsland_BondBridge/scripts.pory"

# 2 "data/maps/ThreeIsland_BondBridge/scripts.pory"
ThreeIsland_BondBridge_MapScripts::
# 3 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.byte 0
# 4 "data/maps/ThreeIsland_BondBridge/scripts.pory"

# 5 "data/maps/ThreeIsland_BondBridge/scripts.pory"
ThreeIsland_BondBridge_EventScript_BerryForestSign::
# 6 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	msgbox ThreeIsland_BondBridge_Text_BerryForestAhead, MSGBOX_SIGN
# 7 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	end
# 8 "data/maps/ThreeIsland_BondBridge/scripts.pory"

# 9 "data/maps/ThreeIsland_BondBridge/scripts.pory"
ThreeIsland_BondBridge_EventScript_BondBridgeSign::
# 10 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	msgbox ThreeIsland_BondBridge_Text_BondBridgeSign, MSGBOX_SIGN
# 11 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	end
