SeafoamIslands_1F_EventObjects:
	object_event 1, 97, 0, 22, 0, 12, 0, 3, 8, 0, 0, 66, 0, 0, 0, SeafoamIslands_1F_EventScript_1BE11D, 64, 0, 0
	object_event 2, 97, 0, 32, 0, 9, 0, 3, 8, 0, 0, 67, 0, 0, 0, SeafoamIslands_1F_EventScript_1BE11D, 65, 0, 0
	object_event 3, 92, 0, 11, 0, 8, 0, 3, 8, 17, 0, 0, 0, 0, 0, SeafoamIslands_1F_EventScript_1BEBE7, 468, 0, 0

SeafoamIslands_1F_MapWarps:
	warp_def 10, 6, 3, 0, 340
	warp_def 31, 4, 3, 1, 340
	warp_def 28, 19, 3, 2, 340
	warp_def 6, 21, 3, 0, 806
	warp_def 32, 21, 3, 1, 806
	warp_def 21, 8, 3, 9, 340
	warp_def 30, 8, 3, 10, 340

SeafoamIslands_1F_MapEvents::
	map_events SeafoamIslands_1F_EventObjects, SeafoamIslands_1F_MapWarps, 0x0, 0x0
