MtEmber_RubyPath_B2F_EventObjects:
	object_event 1, 97, 0, 9, 0, 3, 0, 3, 1, 0, 0, 0, 0, 0, 0, MtEmber_RubyPath_B2F_EventScript_1BE11D, 0, 0, 0
	object_event 2, 97, 0, 12, 0, 5, 0, 3, 1, 0, 0, 0, 0, 0, 0, MtEmber_RubyPath_B2F_EventScript_1BE11D, 0, 0, 0
	object_event 3, 97, 0, 12, 0, 2, 0, 3, 1, 0, 0, 0, 0, 0, 0, MtEmber_RubyPath_B2F_EventScript_1BE11D, 0, 0, 0
	object_event 4, 96, 0, 4, 0, 8, 0, 3, 1, 17, 0, 0, 0, 0, 0, MtEmber_RubyPath_B2F_EventScript_1BE00C, 18, 0, 0
	object_event 5, 96, 0, 1, 0, 8, 0, 3, 1, 17, 0, 0, 0, 0, 0, MtEmber_RubyPath_B2F_EventScript_1BE00C, 19, 0, 0
	object_event 6, 96, 0, 4, 0, 5, 0, 3, 1, 17, 0, 0, 0, 0, 0, MtEmber_RubyPath_B2F_EventScript_1BE00C, 20, 0, 0
	object_event 7, 96, 0, 5, 0, 5, 0, 3, 1, 17, 0, 0, 0, 0, 0, MtEmber_RubyPath_B2F_EventScript_1BE00C, 21, 0, 0

MtEmber_RubyPath_B2F_MapWarps:
	warp_def 1, 7, 3, 1, 360
	warp_def 13, 9, 3, 0, 362

MtEmber_RubyPath_B2F_MapEvents::
	map_events MtEmber_RubyPath_B2F_EventObjects, MtEmber_RubyPath_B2F_MapWarps, 0x0, 0x0
