CeruleanCity_Mart_EventObjects:
	object_event 1, 68, 0, 2, 0, 3, 0, 0, 10, 17, 0, 0, 0, 0, 0, CeruleanCity_Mart_EventScript_16ACB0, 0, 0, 0
	object_event 2, 23, 0, 9, 0, 2, 0, 3, 5, 20, 0, 0, 0, 0, 0, CeruleanCity_Mart_EventScript_16ACA7, 0, 0, 0
	object_event 3, 18, 0, 1, 0, 7, 0, 3, 7, 17, 0, 0, 0, 0, 0, CeruleanCity_Mart_EventScript_16AC9E, 0, 0, 0

CeruleanCity_Mart_MapWarps:
	warp_def 3, 7, 3, 6, 771
	warp_def 4, 7, 3, 6, 771
	warp_def 5, 7, 3, 6, 771

CeruleanCity_Mart_MapEvents::
	map_events CeruleanCity_Mart_EventObjects, CeruleanCity_Mart_MapWarps, 0x0, 0x0
