CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
.string "El REPELENTE no solo mantiene alejados\n"
.string "a los insectos, también sirve contra POKéMON débiles.\p"
.string "Pon a tu POKéMON más fuerte en la\n"
.string "izquierda de la LISTA POKéMON.\p"
.string "Si tu primer POKéMON es fuerte,\n"
.string "el efecto del REPELENTE se potencia.$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
.string "¿Conoces el CARAMELO RARO?\n"
.string "No lo venden en las tiendas.\p"
.string "Creo que hace que los POKéMON\n"
.string "crezcan muy rápido de repente.$"

