
	.include "data/maps/UnknownMap_00_00/scripts.inc"
	.include "data/maps/UnknownMap_00_01/scripts.inc"
	.include "data/maps/UnknownMap_00_02/scripts.inc"
	.include "data/maps/UnknownMap_00_03/scripts.inc"
	.include "data/maps/UnknownMap_00_04/scripts.inc"
	.include "data/maps/ViridianForest/scripts.inc"
	.include "data/maps/MtMoon_1F/scripts.inc"
	.include "data/maps/MtMoon_B1F/scripts.inc"
	.include "data/maps/MtMoon_B2F/scripts.inc"
	.include "data/maps/SSAnne_Exterior/scripts.inc"
	.include "data/maps/SSAnne_1F_Corridor/scripts.inc"
	.include "data/maps/SSAnne_2F_Corridor/scripts.inc"
	.include "data/maps/SSAnne_3F_Corridor/scripts.inc"
	.include "data/maps/SSAnne_B1F_Corridor/scripts.inc"
	.include "data/maps/SSAnne_Deck/scripts.inc"
	.include "data/maps/SSAnne_Kitchen/scripts.inc"
	.include "data/maps/SSAnne_CaptainsOffice/scripts.inc"
	.include "data/maps/SSAnne_1F_Room1/scripts.inc"
	.include "data/maps/SSAnne_1F_Room2/scripts.inc"
	.include "data/maps/SSAnne_1F_Room3/scripts.inc"
	.include "data/maps/SSAnne_1F_Room4/scripts.inc"
	.include "data/maps/SSAnne_1F_Room5/scripts.inc"
	.include "data/maps/SSAnne_1F_Room7/scripts.inc"
	.include "data/maps/SSAnne_2F_Room1/scripts.inc"
	.include "data/maps/SSAnne_2F_Room2/scripts.inc"
	.include "data/maps/SSAnne_2F_Room3/scripts.inc"
	.include "data/maps/SSAnne_2F_Room4/scripts.inc"
	.include "data/maps/SSAnne_2F_Room5/scripts.inc"
	.include "data/maps/SSAnne_2F_Room6/scripts.inc"
	.include "data/maps/SSAnne_B1F_Room1/scripts.inc"
	.include "data/maps/SSAnne_B1F_Room2/scripts.inc"
	.include "data/maps/SSAnne_B1F_Room3/scripts.inc"
	.include "data/maps/SSAnne_B1F_Room4/scripts.inc"
	.include "data/maps/SSAnne_B1F_Room5/scripts.inc"
	.include "data/maps/SSAnne_1F_Room6/scripts.inc"
	.include "data/maps/UndergroundPath_NorthEntrance/scripts.inc"
	.include "data/maps/UndergroundPath_NorthSouthTunnel/scripts.inc"
	.include "data/maps/UndergroundPath_SouthEntrance/scripts.inc"
	.include "data/maps/UndergroundPath_WestEntrance/scripts.inc"
	.include "data/maps/UndergroundPath_EastWestTunnel/scripts.inc"
	.include "data/maps/UndergroundPath_EastEntrance/scripts.inc"
	.include "data/maps/DiglettsCave_NorthEntrance/scripts.inc"
	.include "data/maps/DiglettsCave_B1F/scripts.inc"
	.include "data/maps/DiglettsCave_SouthEntrance/scripts.inc"
	.include "data/maps/VictoryRoad_1F/scripts.inc"
	.include "data/maps/VictoryRoad_2F/scripts.inc"
	.include "data/maps/VictoryRoad_3F/scripts.inc"
	.include "data/maps/RocketHideout_B1F/scripts.inc"
	.include "data/maps/RocketHideout_B2F/scripts.inc"
	.include "data/maps/RocketHideout_B3F/scripts.inc"
	.include "data/maps/RocketHideout_B4F/scripts.inc"
	.include "data/maps/RocketHideout_Elevator/scripts.inc"
	.include "data/maps/SilphCo_1F/scripts.inc"
	.include "data/maps/SilphCo_2F/scripts.inc"
	.include "data/maps/SilphCo_3F/scripts.inc"
	.include "data/maps/SilphCo_4F/scripts.inc"
	.include "data/maps/SilphCo_5F/scripts.inc"
	.include "data/maps/SilphCo_6F/scripts.inc"
	.include "data/maps/SilphCo_7F/scripts.inc"
	.include "data/maps/SilphCo_8F/scripts.inc"
	.include "data/maps/SilphCo_9F/scripts.inc"
	.include "data/maps/SilphCo_10F/scripts.inc"
	.include "data/maps/SilphCo_11F/scripts.inc"
	.include "data/maps/SilphCo_Elevator/scripts.inc"
	.include "data/maps/PokemonMansion_1F/scripts.inc"
	.include "data/maps/PokemonMansion_2F/scripts.inc"
	.include "data/maps/PokemonMansion_3F/scripts.inc"
	.include "data/maps/PokemonMansion_B1F/scripts.inc"
	.include "data/maps/SafariZone_Center/scripts.inc"
	.include "data/maps/SafariZone_East/scripts.inc"
	.include "data/maps/SafariZone_North/scripts.inc"
	.include "data/maps/SafariZone_West/scripts.inc"
	.include "data/maps/SafariZone_Building1/scripts.inc"
	.include "data/maps/SafariZone_Building2/scripts.inc"
	.include "data/maps/SafariZone_Building3/scripts.inc"
	.include "data/maps/SafariZone_Building4/scripts.inc"
	.include "data/maps/SafariZone_SecretHouse/scripts.inc"
	.include "data/maps/CeruleanCave_1F/scripts.inc"
	.include "data/maps/CeruleanCave_2F/scripts.inc"
	.include "data/maps/CeruleanCave_B1F/scripts.inc"
	.include "data/maps/PokemonLeague_LoreleisRoom/scripts.inc"
	.include "data/maps/PokemonLeague_BrunosRoom/scripts.inc"
	.include "data/maps/PokemonLeague_AgathasRoom/scripts.inc"
	.include "data/maps/PokemonLeague_LancesRoom/scripts.inc"
	.include "data/maps/PokemonLeague_ChampionsRoom/scripts.inc"
	.include "data/maps/PokemonLeague_HallOfFame/scripts.inc"
	.include "data/maps/RockTunnel_1F/scripts.inc"
	.include "data/maps/RockTunnel_B1F/scripts.inc"
	.include "data/maps/SeafoamIslands_1F/scripts.inc"
	.include "data/maps/SeafoamIslands_B1F/scripts.inc"
	.include "data/maps/SeafoamIslands_B2F/scripts.inc"
	.include "data/maps/SeafoamIslands_B3F/scripts.inc"
	.include "data/maps/SeafoamIslands_B4F/scripts.inc"
	.include "data/maps/PokemonTower_1F/scripts.inc"
	.include "data/maps/PokemonTower_2F/scripts.inc"
	.include "data/maps/PokemonTower_3F/scripts.inc"
	.include "data/maps/PokemonTower_4F/scripts.inc"
	.include "data/maps/PokemonTower_5F/scripts.inc"
	.include "data/maps/PokemonTower_6F/scripts.inc"
	.include "data/maps/PokemonTower_7F/scripts.inc"
	.include "data/maps/PowerPlant/scripts.inc"
	.include "data/maps/MtEmber_RubyPath_B4F/scripts.inc"
	.include "data/maps/MtEmber_Exterior/scripts.inc"
	.include "data/maps/MtEmber_SummitPath_1F/scripts.inc"
	.include "data/maps/MtEmber_SummitPath_2F/scripts.inc"
	.include "data/maps/MtEmber_SummitPath_3F/scripts.inc"
	.include "data/maps/MtEmber_Summit/scripts.inc"
	.include "data/maps/MtEmber_RubyPath_B5F/scripts.inc"
	.include "data/maps/MtEmber_RubyPath_1F/scripts.inc"
	.include "data/maps/MtEmber_RubyPath_B1F/scripts.inc"
	.include "data/maps/MtEmber_RubyPath_B2F/scripts.inc"
	.include "data/maps/MtEmber_RubyPath_B3F/scripts.inc"
	.include "data/maps/MtEmber_RubyPath_B1F_Stairs/scripts.inc"
	.include "data/maps/MtEmber_RubyPath_B2F_Stairs/scripts.inc"
	.include "data/maps/ThreeIsland_BerryForest/scripts.inc"
	.include "data/maps/FourIsland_IcefallCave_Entrance/scripts.inc"
	.include "data/maps/FourIsland_IcefallCave_1F/scripts.inc"
	.include "data/maps/FourIsland_IcefallCave_B1F/scripts.inc"
	.include "data/maps/FourIsland_IcefallCave_Back/scripts.inc"
	.include "data/maps/FiveIsland_RocketWarehouse/scripts.inc"
	.include "data/maps/SixIsland_DottedHole_1F/scripts.inc"
	.include "data/maps/SixIsland_DottedHole_B1F/scripts.inc"
	.include "data/maps/SixIsland_DottedHole_B2F/scripts.inc"
	.include "data/maps/SixIsland_DottedHole_B3F/scripts.inc"
	.include "data/maps/SixIsland_DottedHole_B4F/scripts.inc"
	.include "data/maps/SixIsland_DottedHole_SapphireRoom/scripts.inc"
	.include "data/maps/SixIsland_PatternBush/scripts.inc"
	.include "data/maps/SixIsland_AlteringCave/scripts.inc"
	.include "data/maps/NavelRock_Exterior/scripts.inc"
	.include "data/maps/SevenIsland_TrainerTower_1F/scripts.inc"
	.include "data/maps/SevenIsland_TrainerTower_2F/scripts.inc"
	.include "data/maps/SevenIsland_TrainerTower_3F/scripts.inc"
	.include "data/maps/SevenIsland_TrainerTower_4F/scripts.inc"
	.include "data/maps/SevenIsland_TrainerTower_5F/scripts.inc"
	.include "data/maps/SevenIsland_TrainerTower_6F/scripts.inc"
	.include "data/maps/SevenIsland_TrainerTower_7F/scripts.inc"
	.include "data/maps/SevenIsland_TrainerTower_8F/scripts.inc"
	.include "data/maps/SevenIsland_TrainerTower_Roof/scripts.inc"
	.include "data/maps/SevenIsland_TrainerTower_Lobby/scripts.inc"
	.include "data/maps/SevenIsland_TrainerTower_Elevator/scripts.inc"
	.include "data/maps/FiveIsland_LostCave_Entrance/scripts.inc"
	.include "data/maps/FiveIsland_LostCave_Room1/scripts.inc"
	.include "data/maps/FiveIsland_LostCave_Room2/scripts.inc"
	.include "data/maps/FiveIsland_LostCave_Room3/scripts.inc"
	.include "data/maps/FiveIsland_LostCave_Room4/scripts.inc"
	.include "data/maps/FiveIsland_LostCave_Room5/scripts.inc"
	.include "data/maps/FiveIsland_LostCave_Room6/scripts.inc"
	.include "data/maps/FiveIsland_LostCave_Room7/scripts.inc"
	.include "data/maps/FiveIsland_LostCave_Room8/scripts.inc"
	.include "data/maps/FiveIsland_LostCave_Room9/scripts.inc"
	.include "data/maps/FiveIsland_LostCave_Room10/scripts.inc"
	.include "data/maps/FiveIsland_LostCave_Room11/scripts.inc"
	.include "data/maps/FiveIsland_LostCave_Room12/scripts.inc"
	.include "data/maps/FiveIsland_LostCave_Room13/scripts.inc"
	.include "data/maps/FiveIsland_LostCave_Room14/scripts.inc"
	.include "data/maps/SevenIsland_TanobyRuins_MoneanChamber/scripts.inc"
	.include "data/maps/SevenIsland_TanobyRuins_LiptooChamber/scripts.inc"
	.include "data/maps/SevenIsland_TanobyRuins_WeepthChamber/scripts.inc"
	.include "data/maps/SevenIsland_TanobyRuins_DilfordChamber/scripts.inc"
	.include "data/maps/SevenIsland_TanobyRuins_ScufibChamber/scripts.inc"
	.include "data/maps/SevenIsland_TanobyRuins_RixyChamber/scripts.inc"
	.include "data/maps/SevenIsland_TanobyRuins_ViapoisChamber/scripts.inc"
	.include "data/maps/ThreeIsland_DunsparceTunnel/scripts.inc"
	.include "data/maps/SevenIsland_SeavaultCanyon_TanobyKey/scripts.inc"
	.include "data/maps/NavelRock_1F/scripts.inc"
	.include "data/maps/NavelRock_Summit/scripts.inc"
	.include "data/maps/NavelRock_Base/scripts.inc"
	.include "data/maps/NavelRock_SummitPath_2F/scripts.inc"
	.include "data/maps/NavelRock_SummitPath_3F/scripts.inc"
	.include "data/maps/NavelRock_SummitPath_4F/scripts.inc"
	.include "data/maps/NavelRock_SummitPath_5F/scripts.inc"
	.include "data/maps/NavelRock_BasePath_B1F/scripts.inc"
	.include "data/maps/NavelRock_BasePath_B2F/scripts.inc"
	.include "data/maps/NavelRock_BasePath_B3F/scripts.inc"
	.include "data/maps/NavelRock_BasePath_B4F/scripts.inc"
	.include "data/maps/NavelRock_BasePath_B5F/scripts.inc"
	.include "data/maps/NavelRock_BasePath_B6F/scripts.inc"
	.include "data/maps/NavelRock_BasePath_B7F/scripts.inc"
	.include "data/maps/NavelRock_BasePath_B8F/scripts.inc"
	.include "data/maps/NavelRock_BasePath_B9F/scripts.inc"
	.include "data/maps/NavelRock_BasePath_B10F/scripts.inc"
	.include "data/maps/NavelRock_BasePath_B11F/scripts.inc"
	.include "data/maps/NavelRock_B1F/scripts.inc"
	.include "data/maps/NavelRock_Fork/scripts.inc"
	.include "data/maps/BirthIsland_Exterior/scripts.inc"
	.include "data/maps/OneIsland_KindleRoad_EmberSpa/scripts.inc"
	.include "data/maps/BirthIsland_Harbor/scripts.inc"
	.include "data/maps/PalletTown/scripts.inc"
	.include "data/maps/ViridianCity/scripts.inc"
	.include "data/maps/PewterCity/scripts.inc"
	.include "data/maps/CeruleanCity/scripts.inc"
	.include "data/maps/LavenderTown/scripts.inc"
	.include "data/maps/VermilionCity/scripts.inc"
	.include "data/maps/CeladonCity/scripts.inc"
	.include "data/maps/FuchsiaCity/scripts.inc"
	.include "data/maps/CinnabarIsland/scripts.inc"
	.include "data/maps/IndigoPlateau_Exterior/scripts.inc"
	.include "data/maps/SaffronCity_Duplicate/scripts.inc"
	.include "data/maps/SaffronCity/scripts.inc"
	.include "data/maps/OneIsland/scripts.inc"
	.include "data/maps/TwoIsland/scripts.inc"
	.include "data/maps/ThreeIsland/scripts.inc"
	.include "data/maps/FourIsland/scripts.inc"
	.include "data/maps/FiveIsland/scripts.inc"
	.include "data/maps/SevenIsland/scripts.inc"
	.include "data/maps/SixIsland/scripts.inc"
	.include "data/maps/Route1/scripts.inc"
	.include "data/maps/Route2/scripts.inc"
	.include "data/maps/Route3/scripts.inc"
	.include "data/maps/Route4/scripts.inc"
	.include "data/maps/Route5/scripts.inc"
	.include "data/maps/Route6/scripts.inc"
	.include "data/maps/Route7/scripts.inc"
	.include "data/maps/Route8/scripts.inc"
	.include "data/maps/Route9/scripts.inc"
	.include "data/maps/Route10/scripts.inc"
	.include "data/maps/Route11/scripts.inc"
	.include "data/maps/Route12/scripts.inc"
	.include "data/maps/Route13/scripts.inc"
	.include "data/maps/Route14/scripts.inc"
	.include "data/maps/Route15/scripts.inc"
	.include "data/maps/Route16/scripts.inc"
	.include "data/maps/Route17/scripts.inc"
	.include "data/maps/Route18/scripts.inc"
	.include "data/maps/Route19/scripts.inc"
	.include "data/maps/Route20/scripts.inc"
	.include "data/maps/Route21_North/scripts.inc"
	.include "data/maps/Route21_South/scripts.inc"
	.include "data/maps/Route22/scripts.inc"
	.include "data/maps/Route23/scripts.inc"
	.include "data/maps/Route24/scripts.inc"
	.include "data/maps/Route25/scripts.inc"
	.include "data/maps/OneIsland_KindleRoad/scripts.inc"
	.include "data/maps/OneIsland_TreasureBeach/scripts.inc"
	.include "data/maps/TwoIsland_CapeBrink/scripts.inc"
	.include "data/maps/ThreeIsland_BondBridge/scripts.inc"
	.include "data/maps/ThreeIsland_Port/scripts.inc"
	.include "data/maps/UnknownMap_03_50/scripts.inc"
	.include "data/maps/UnknownMap_03_51/scripts.inc"
	.include "data/maps/UnknownMap_03_52/scripts.inc"
	.include "data/maps/UnknownMap_03_53/scripts.inc"
	.include "data/maps/FiveIsland_ResortGorgeous/scripts.inc"
	.include "data/maps/FiveIsland_WaterLabyrinth/scripts.inc"
	.include "data/maps/FiveIsland_Meadow/scripts.inc"
	.include "data/maps/FiveIsland_MemorialPillar/scripts.inc"
	.include "data/maps/SixIsland_OutcastIsland/scripts.inc"
	.include "data/maps/SixIsland_GreenPath/scripts.inc"
	.include "data/maps/SixIsland_WaterPath/scripts.inc"
	.include "data/maps/SixIsland_RuinValley/scripts.inc"
	.include "data/maps/SevenIsland_TrainerTower/scripts.inc"
	.include "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.inc"
	.include "data/maps/SevenIsland_SevaultCanyon/scripts.inc"
	.include "data/maps/SevenIsland_TanobyRuins/scripts.inc"
	.include "data/maps/PalletTown_PlayersHouse_1F/scripts.inc"
	.include "data/maps/PalletTown_PlayersHouse_2F/scripts.inc"
	.include "data/maps/PalletTown_GarysHouse/scripts.inc"
	.include "data/maps/PalletTown_ProfessorOaksLab/scripts.inc"
	.include "data/maps/ViridianCity_House1/scripts.inc"
	.include "data/maps/ViridianCity_Gym/scripts.inc"
	.include "data/maps/ViridianCity_House2/scripts.inc"
	.include "data/maps/ViridianCity_Mart/scripts.inc"
	.include "data/maps/ViridianCity_PokemonCenter_1F/scripts.inc"
	.include "data/maps/ViridianCity_PokemonCenter_2F/scripts.inc"
	.include "data/maps/PewterCity_Museum_1F/scripts.inc"
	.include "data/maps/PewterCity_Museum_2F/scripts.inc"
	.include "data/maps/PewterCity_Gym/scripts.inc"
	.include "data/maps/PewterCity_Mart/scripts.inc"
	.include "data/maps/PewterCity_House1/scripts.inc"
	.include "data/maps/PewterCity_PokemonCenter_1F/scripts.inc"
	.include "data/maps/PewterCity_PokemonCenter_2F/scripts.inc"
	.include "data/maps/PewterCity_House2/scripts.inc"
	.include "data/maps/CeruleanCity_House1/scripts.inc"
	.include "data/maps/CeruleanCity_House2/scripts.inc"
	.include "data/maps/CeruleanCity_House3/scripts.inc"
	.include "data/maps/CeruleanCity_PokemonCenter_1F/scripts.inc"
	.include "data/maps/CeruleanCity_PokemonCenter_2F/scripts.inc"
	.include "data/maps/CeruleanCity_Gym/scripts.inc"
	.include "data/maps/CeruleanCity_BikeShop/scripts.inc"
	.include "data/maps/CeruleanCity_Mart/scripts.inc"
	.include "data/maps/CeruleanCity_House4/scripts.inc"
	.include "data/maps/CeruleanCity_House5/scripts.inc"
	.include "data/maps/LavenderTown_PokemonCenter_1F/scripts.inc"
	.include "data/maps/LavenderTown_PokemonCenter_2F/scripts.inc"
	.include "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.inc"
	.include "data/maps/LavenderTown_House1/scripts.inc"
	.include "data/maps/LavenderTown_House2/scripts.inc"
	.include "data/maps/LavenderTown_Mart/scripts.inc"
	.include "data/maps/VermilionCity_House1/scripts.inc"
	.include "data/maps/VermilionCity_PokemonCenter_1F/scripts.inc"
	.include "data/maps/VermilionCity_PokemonCenter_2F/scripts.inc"
	.include "data/maps/VermilionCity_PokemonFanClub/scripts.inc"
	.include "data/maps/VermilionCity_Mart/scripts.inc"
	.include "data/maps/VermilionCity_Gym/scripts.inc"
	.include "data/maps/VermilionCity_House3/scripts.inc"
	.include "data/maps/CeladonCity_DepartmentStore_1F/scripts.inc"
	.include "data/maps/CeladonCity_DepartmentStore_2F/scripts.inc"
	.include "data/maps/CeladonCity_DepartmentStore_3F/scripts.inc"
	.include "data/maps/CeladonCity_DepartmentStore_4F/scripts.inc"
	.include "data/maps/CeladonCity_DepartmentStore_5F/scripts.inc"
	.include "data/maps/CeladonCity_DepartmentStore_Roof/scripts.inc"
	.include "data/maps/CeladonCity_DepartmentStore_Elevator/scripts.inc"
	.include "data/maps/CeladonCity_Condominiums_1F/scripts.inc"
	.include "data/maps/CeladonCity_Condominiums_2F/scripts.inc"
	.include "data/maps/CeladonCity_Condominiums_3F/scripts.inc"
	.include "data/maps/CeladonCity_Condominiums_Roof/scripts.inc"
	.include "data/maps/CeladonCity_Condominiums_RoofRoom/scripts.inc"
	.include "data/maps/CeladonCity_PokemonCenter_1F/scripts.inc"
	.include "data/maps/CeladonCity_PokemonCenter_2F/scripts.inc"
	.include "data/maps/CeladonCity_GameCorner/scripts.inc"
	.include "data/maps/CeladonCity_GameCorner_PrizeRoom/scripts.inc"
	.include "data/maps/CeladonCity_Gym/scripts.inc"
	.include "data/maps/CeladonCity_Restaurant/scripts.inc"
	.include "data/maps/CeladonCity_House1/scripts.inc"
	.include "data/maps/CeladonCity_Hotel/scripts.inc"
	.include "data/maps/FuchsiaCity_SafariZone_Entrance/scripts.inc"
	.include "data/maps/FuchsiaCity_Mart/scripts.inc"
	.include "data/maps/FuchsiaCity_ZooBuilding/scripts.inc"
	.include "data/maps/FuchsiaCity_Gym/scripts.inc"
	.include "data/maps/FuchsiaCity_House1/scripts.inc"
	.include "data/maps/FuchsiaCity_PokemonCenter_1F/scripts.inc"
	.include "data/maps/FuchsiaCity_PokemonCenter_2F/scripts.inc"
	.include "data/maps/FuchsiaCity_Building1/scripts.inc"
	.include "data/maps/FuchsiaCity_House2/scripts.inc"
	.include "data/maps/FuchsiaCity_House3/scripts.inc"
	.include "data/maps/CinnabarIsland_Gym/scripts.inc"
	.include "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.inc"
	.include "data/maps/CinnabarIsland_PokemonLab_Lounge/scripts.inc"
	.include "data/maps/CinnabarIsland_PokemonLab_ResearchRoom/scripts.inc"
	.include "data/maps/CinnabarIsland_PokemonLab_ExperimentRoom/scripts.inc"
	.include "data/maps/CinnabarIsland_PokemonCenter_1F/scripts.inc"
	.include "data/maps/CinnabarIsland_PokemonCenter_2F/scripts.inc"
	.include "data/maps/CinnabarIsland_Mart/scripts.inc"
	.include "data/maps/IndigoPlateau_PokemonCenter_1F/scripts.inc"
	.include "data/maps/IndigoPlateau_PokemonCenter_2F/scripts.inc"
	.include "data/maps/SaffronCity_House1_1F/scripts.inc"
	.include "data/maps/SaffronCity_House1_2F/scripts.inc"
	.include "data/maps/SaffronCity_Dojo/scripts.inc"
	.include "data/maps/SaffronCity_Gym/scripts.inc"
	.include "data/maps/SaffronCity_House2/scripts.inc"
	.include "data/maps/SaffronCity_Mart/scripts.inc"
	.include "data/maps/SaffronCity_PokemonCenter_1F/scripts.inc"
	.include "data/maps/SaffronCity_PokemonCenter_2F/scripts.inc"
	.include "data/maps/SaffronCity_House3/scripts.inc"
	.include "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.inc"
	.include "data/maps/Route2_ViridianForest_SouthEntrance/scripts.inc"
	.include "data/maps/Route2_House/scripts.inc"
	.include "data/maps/Route2_EastBuilding/scripts.inc"
	.include "data/maps/Route2_ViridianForest_NorthEntrance/scripts.inc"
	.include "data/maps/Route4_PokemonCenter_1F/scripts.inc"
	.include "data/maps/Route4_PokemonCenter_2F/scripts.inc"
	.include "data/maps/Route5_PokemonDayCare/scripts.inc"
	.include "data/maps/Route5_SouthEntrance/scripts.inc"
	.include "data/maps/Route6_NorthEntrance/scripts.inc"
	.include "data/maps/UnknownMap_18_01/scripts.inc"
	.include "data/maps/Route7_EastEntrance/scripts.inc"
	.include "data/maps/Route8_WestEntrance/scripts.inc"
	.include "data/maps/Route10_PokemonCenter_1F/scripts.inc"
	.include "data/maps/Route10_PokemonCenter_2F/scripts.inc"
	.include "data/maps/Route11_EastEntrance_1F/scripts.inc"
	.include "data/maps/Route11_EastEntrance_2F/scripts.inc"
	.include "data/maps/Route12_NorthEntrance_1F/scripts.inc"
	.include "data/maps/Route12_NorthEntrance_2F/scripts.inc"
	.include "data/maps/Route12_FishingHouse/scripts.inc"
	.include "data/maps/Route15_WestEntrance_1F/scripts.inc"
	.include "data/maps/Route15_WestEntrance_2F/scripts.inc"
	.include "data/maps/Route16_House/scripts.inc"
	.include "data/maps/Route16_NorthEntrance_1F/scripts.inc"
	.include "data/maps/Route16_NorthEntrance_2F/scripts.inc"
	.include "data/maps/Route18_EastEntrance_1F/scripts.inc"
	.include "data/maps/Route18_EastEntrance_2F/scripts.inc"
	.include "data/maps/UnusedHouse_27_00/scripts.inc"
	.include "data/maps/Route22_NorthEntrance/scripts.inc"
	.include "data/maps/UnusedHouse_29_00/scripts.inc"
	.include "data/maps/Route25_SeaCottage/scripts.inc"
	.include "data/maps/SevenIsland_House_Room1/scripts.inc"
	.include "data/maps/SevenIsland_House_Room2/scripts.inc"
	.include "data/maps/SevenIsland_Mart/scripts.inc"
	.include "data/maps/SevenIsland_PokemonCenter_1F/scripts.inc"
	.include "data/maps/SevenIsland_PokemonCenter_2F/scripts.inc"
	.include "data/maps/UnusedHouse_31_05/scripts.inc"
	.include "data/maps/SevenIsland_Harbor/scripts.inc"
	.include "data/maps/OneIsland_PokemonCenter_1F/scripts.inc"
	.include "data/maps/OneIsland_PokemonCenter_2F/scripts.inc"
	.include "data/maps/OneIsland_House1/scripts.inc"
	.include "data/maps/OneIsland_House2/scripts.inc"
	.include "data/maps/OneIsland_Harbor/scripts.inc"
	.include "data/maps/TwoIsland_JoyfulGameCorner/scripts.inc"
	.include "data/maps/TwoIsland_House/scripts.inc"
	.include "data/maps/TwoIsland_PokemonCenter_1F/scripts.inc"
	.include "data/maps/TwoIsland_PokemonCenter_2F/scripts.inc"
	.include "data/maps/TwoIsland_Harbor/scripts.inc"
	.include "data/maps/ThreeIsland_House1/scripts.inc"
	.include "data/maps/ThreeIsland_PokemonCenter_1F/scripts.inc"
	.include "data/maps/ThreeIsland_PokemonCenter_2F/scripts.inc"
	.include "data/maps/ThreeIsland_Mart/scripts.inc"
	.include "data/maps/ThreeIsland_House2/scripts.inc"
	.include "data/maps/ThreeIsland_House3/scripts.inc"
	.include "data/maps/ThreeIsland_House4/scripts.inc"
	.include "data/maps/ThreeIsland_House5/scripts.inc"
	.include "data/maps/FourIsland_PokemonDayCare/scripts.inc"
	.include "data/maps/FourIsland_PokemonCenter_1F/scripts.inc"
	.include "data/maps/FourIsland_PokemonCenter_2F/scripts.inc"
	.include "data/maps/FourIsland_House1/scripts.inc"
	.include "data/maps/FourIsland_LoreleisHouse/scripts.inc"
	.include "data/maps/FourIsland_Harbor/scripts.inc"
	.include "data/maps/FourIsland_House2/scripts.inc"
	.include "data/maps/FourIsland_Mart/scripts.inc"
	.include "data/maps/FiveIsland_PokemonCenter_1F/scripts.inc"
	.include "data/maps/FiveIsland_PokemonCenter_2F/scripts.inc"
	.include "data/maps/FiveIsland_Harbor/scripts.inc"
	.include "data/maps/FiveIsland_House1/scripts.inc"
	.include "data/maps/FiveIsland_House2/scripts.inc"
	.include "data/maps/SixIsland_PokemonCenter_1F/scripts.inc"
	.include "data/maps/SixIsland_PokemonCenter_2F/scripts.inc"
	.include "data/maps/SixIsland_Harbor/scripts.inc"
	.include "data/maps/SixIsland_House/scripts.inc"
	.include "data/maps/SixIsland_Mart/scripts.inc"
	.include "data/maps/ThreeIsland_Harbor/scripts.inc"
	.include "data/maps/FiveIsland_ResortGorgeous_House/scripts.inc"
	.include "data/maps/TwoIsland_CapeBrink_House/scripts.inc"
	.include "data/maps/SixIsland_WaterPath_House1/scripts.inc"
	.include "data/maps/SixIsland_WaterPath_House2/scripts.inc"
	.include "data/maps/SevenIsland_SevaultCanyon_House/scripts.inc"



	.include "data/maps/ViridianForest/text.inc"
	.include "data/maps/MtMoon_1F/text.inc"
	.include "data/maps/MtMoon_B2F/text.inc"
	.include "data/maps/SSAnne_1F_Corridor/text.inc"
	.include "data/maps/SSAnne_2F_Corridor/text.inc"
	.include "data/maps/SSAnne_3F_Corridor/text.inc"
	.include "data/maps/SSAnne_Deck/text.inc"
	.include "data/maps/SSAnne_Kitchen/text.inc"
	.include "data/maps/SSAnne_CaptainsOffice/text.inc"
	.include "data/maps/SSAnne_1F_Room1/text.inc"
	.include "data/maps/SSAnne_1F_Room2/text.inc"
	.include "data/maps/SSAnne_1F_Room3/text.inc"
	.include "data/maps/SSAnne_1F_Room4/text.inc"
	.include "data/maps/SSAnne_1F_Room5/text.inc"
	.include "data/maps/SSAnne_1F_Room7/text.inc"
	.include "data/maps/SSAnne_2F_Room1/text.inc"
	.include "data/maps/SSAnne_2F_Room2/text.inc"
	.include "data/maps/SSAnne_2F_Room3/text.inc"
	.include "data/maps/SSAnne_2F_Room4/text.inc"
	.include "data/maps/SSAnne_2F_Room5/text.inc"
	.include "data/maps/SSAnne_2F_Room6/text.inc"
	.include "data/maps/SSAnne_B1F_Room1/text.inc"
	.include "data/maps/SSAnne_B1F_Room2/text.inc"
	.include "data/maps/SSAnne_B1F_Room3/text.inc"
	.include "data/maps/SSAnne_B1F_Room4/text.inc"
	.include "data/maps/SSAnne_B1F_Room5/text.inc"
	.include "data/maps/SSAnne_1F_Room6/text.inc"
	.include "data/maps/UndergroundPath_SouthEntrance/text.inc"
	.include "data/maps/UndergroundPath_WestEntrance/text.inc"
	.include "data/maps/UndergroundPath_EastEntrance/text.inc"
	.include "data/maps/DiglettsCave_NorthEntrance/text.inc"
	.include "data/maps/DiglettsCave_SouthEntrance/text.inc"
	.include "data/maps/VictoryRoad_1F/text.inc"
	.include "data/maps/VictoryRoad_2F/text.inc"
	.include "data/maps/VictoryRoad_3F/text.inc"
	.include "data/maps/RocketHideout_B1F/text.inc"
	.include "data/maps/RocketHideout_B2F/text.inc"
	.include "data/maps/RocketHideout_B3F/text.inc"
	.include "data/maps/RocketHideout_B4F/text.inc"
	.include "data/maps/RocketHideout_Elevator/text.inc"
	.include "data/maps/SilphCo_1F/text.inc"
	.include "data/maps/SilphCo_2F/text.inc"
	.include "data/maps/SilphCo_3F/text.inc"
	.include "data/maps/SilphCo_4F/text.inc"
	.include "data/maps/SilphCo_5F/text.inc"
	.include "data/maps/SilphCo_6F/text.inc"
	.include "data/maps/SilphCo_7F/text.inc"
	.include "data/maps/SilphCo_8F/text.inc"
	.include "data/maps/SilphCo_9F/text.inc"
	.include "data/maps/SilphCo_10F/text.inc"
	.include "data/maps/SilphCo_11F/text.inc"
	.include "data/maps/PokemonMansion_1F/text.inc"
	.include "data/maps/PokemonMansion_2F/text.inc"
	.include "data/maps/PokemonMansion_3F/text.inc"
	.include "data/maps/PokemonMansion_B1F/text.inc"
	.include "data/maps/SafariZone_Center/text.inc"
	.include "data/maps/SafariZone_East/text.inc"
	.include "data/maps/SafariZone_North/text.inc"
	.include "data/maps/SafariZone_West/text.inc"
	.include "data/maps/SafariZone_Building1/text.inc"
	.include "data/maps/SafariZone_Building2/text.inc"
	.include "data/maps/SafariZone_Building3/text.inc"
	.include "data/maps/SafariZone_Building4/text.inc"
	.include "data/maps/SafariZone_SecretHouse/text.inc"
	.include "data/maps/CeruleanCave_B1F/text.inc"
	.include "data/maps/PokemonLeague_LoreleisRoom/text.inc"
	.include "data/maps/PokemonLeague_BrunosRoom/text.inc"
	.include "data/maps/PokemonLeague_AgathasRoom/text.inc"
	.include "data/maps/PokemonLeague_LancesRoom/text.inc"
	.include "data/maps/PokemonLeague_ChampionsRoom/text.inc"
	.include "data/maps/PokemonLeague_HallOfFame/text.inc"
	.include "data/maps/RockTunnel_1F/text.inc"
	.include "data/maps/RockTunnel_B1F/text.inc"
	.include "data/maps/SeafoamIslands_B4F/text.inc"
	.include "data/maps/PokemonTower_1F/text.inc"
	.include "data/maps/PokemonTower_2F/text.inc"
	.include "data/maps/PokemonTower_3F/text.inc"
	.include "data/maps/PokemonTower_4F/text.inc"
	.include "data/maps/PokemonTower_5F/text.inc"
	.include "data/maps/PokemonTower_6F/text.inc"
	.include "data/maps/PokemonTower_7F/text.inc"
	.include "data/maps/MtEmber_Exterior/text.inc"
	.include "data/maps/MtEmber_RubyPath_B3F/text.inc"
	.include "data/maps/ThreeIsland_BerryForest/text.inc"
	.include "data/maps/FourIsland_IcefallCave_Back/text.inc"
	.include "data/maps/FiveIsland_RocketWarehouse/text.inc"
	.include "data/maps/SixIsland_DottedHole_SapphireRoom/text.inc"
	.include "data/maps/SixIsland_PatternBush/text.inc"
	.include "data/maps/SevenIsland_TrainerTower_Lobby/text.inc"
	.include "data/maps/FiveIsland_LostCave_Room1/text.inc"
	.include "data/maps/FiveIsland_LostCave_Room4/text.inc"
	.include "data/maps/FiveIsland_LostCave_Room10/text.inc"
	.include "data/maps/ThreeIsland_DunsparceTunnel/text.inc"
	.include "data/maps/SevenIsland_SeavaultCanyon_TanobyKey/text.inc"
	.include "data/maps/OneIsland_KindleRoad_EmberSpa/text.inc"
	.include "data/maps/PalletTown/text.inc"
	.include "data/maps/ViridianCity/text.inc"
	.include "data/maps/PewterCity/text.inc"
	.include "data/maps/CeruleanCity/text.inc"
	.include "data/maps/LavenderTown/text.inc"
	.include "data/maps/VermilionCity/text.inc"
	.include "data/maps/CeladonCity/text.inc"
	.include "data/maps/FuchsiaCity/text.inc"
	.include "data/maps/CinnabarIsland/text.inc"
	.include "data/maps/SaffronCity_Duplicate/text.inc"
	.include "data/maps/OneIsland/text.inc"
	.include "data/maps/TwoIsland/text.inc"
	.include "data/maps/ThreeIsland/text.inc"
	.include "data/maps/FourIsland/text.inc"
	.include "data/maps/FiveIsland/text.inc"
	.include "data/maps/SevenIsland/text.inc"
	.include "data/maps/SixIsland/text.inc"
	.include "data/maps/Route1/text.inc"
	.include "data/maps/Route2/text.inc"
	.include "data/maps/Route3/text.inc"
	.include "data/maps/Route4/text.inc"
	.include "data/maps/Route5/text.inc"
	.include "data/maps/Route6/text.inc"
	.include "data/maps/Route7/text.inc"
	.include "data/maps/Route8/text.inc"
	.include "data/maps/Route9/text.inc"
	.include "data/maps/Route10/text.inc"
	.include "data/maps/Route11/text.inc"
	.include "data/maps/Route12/text.inc"
	.include "data/maps/Route13/text.inc"
	.include "data/maps/Route14/text.inc"
	.include "data/maps/Route15/text.inc"
	.include "data/maps/Route16/text.inc"
	.include "data/maps/Route17/text.inc"
	.include "data/maps/Route18/text.inc"
	.include "data/maps/Route19/text.inc"
	.include "data/maps/Route20/text.inc"
	.include "data/maps/Route22/text.inc"
	.include "data/maps/Route23/text.inc"
	.include "data/maps/Route24/text.inc"
	.include "data/maps/Route25/text.inc"
	.include "data/maps/OneIsland_KindleRoad/text.inc"
	.include "data/maps/OneIsland_TreasureBeach/text.inc"
	.include "data/maps/ThreeIsland_BondBridge/text.inc"
	.include "data/maps/ThreeIsland_Port/text.inc"
	.include "data/maps/FiveIsland_ResortGorgeous/text.inc"
	.include "data/maps/FiveIsland_WaterLabyrinth/text.inc"
	.include "data/maps/FiveIsland_Meadow/text.inc"
	.include "data/maps/FiveIsland_MemorialPillar/text.inc"
	.include "data/maps/SixIsland_OutcastIsland/text.inc"
	.include "data/maps/SixIsland_GreenPath/text.inc"
	.include "data/maps/SixIsland_WaterPath/text.inc"
	.include "data/maps/SixIsland_RuinValley/text.inc"
	.include "data/maps/SevenIsland_TrainerTower/text.inc"
	.include "data/maps/SevenIsland_SevaultCanyon_Entrance/text.inc"
	.include "data/maps/SevenIsland_SevaultCanyon/text.inc"
	.include "data/maps/PalletTown_PlayersHouse_1F/text.inc"
	.include "data/maps/PalletTown_PlayersHouse_2F/text.inc"
	.include "data/maps/PalletTown_GarysHouse/text.inc"
	.include "data/maps/PalletTown_ProfessorOaksLab/text.inc"
	.include "data/maps/ViridianCity_House1/text.inc"
	.include "data/maps/ViridianCity_Gym/text.inc"
	.include "data/maps/ViridianCity_House2/text.inc"
	.include "data/maps/ViridianCity_Mart/text.inc"
	.include "data/maps/ViridianCity_PokemonCenter_1F/text.inc"
	.include "data/maps/PewterCity_Museum_1F/text.inc"
	.include "data/maps/PewterCity_Museum_2F/text.inc"
	.include "data/maps/PewterCity_Gym/text.inc"
	.include "data/maps/PewterCity_Mart/text.inc"
	.include "data/maps/PewterCity_House1/text.inc"
	.include "data/maps/PewterCity_PokemonCenter_1F/text.inc"
	.include "data/maps/PewterCity_House2/text.inc"
	.include "data/maps/CeruleanCity_House1/text.inc"
	.include "data/maps/CeruleanCity_House2/text.inc"
	.include "data/maps/CeruleanCity_House3/text.inc"
	.include "data/maps/CeruleanCity_PokemonCenter_1F/text.inc"
	.include "data/maps/CeruleanCity_Gym/text.inc"
	.include "data/maps/CeruleanCity_BikeShop/text.inc"
	.include "data/maps/CeruleanCity_Mart/text.inc"
	.include "data/maps/CeruleanCity_House4/text.inc"
	.include "data/maps/CeruleanCity_House5/text.inc"
	.include "data/maps/LavenderTown_PokemonCenter_1F/text.inc"
	.include "data/maps/LavenderTown_VolunteerPokemonHouse/text.inc"
	.include "data/maps/LavenderTown_House1/text.inc"
	.include "data/maps/LavenderTown_House2/text.inc"
	.include "data/maps/LavenderTown_Mart/text.inc"
	.include "data/maps/VermilionCity_House1/text.inc"
	.include "data/maps/VermilionCity_PokemonCenter_1F/text.inc"
	.include "data/maps/VermilionCity_PokemonFanClub/text.inc"
	.include "data/maps/VermilionCity_Mart/text.inc"
	.include "data/maps/VermilionCity_Gym/text.inc"
	.include "data/maps/VermilionCity_House3/text.inc"
	.include "data/maps/CeladonCity_DepartmentStore_1F/text.inc"
	.include "data/maps/CeladonCity_DepartmentStore_2F/text.inc"
	.include "data/maps/CeladonCity_DepartmentStore_3F/text.inc"
	.include "data/maps/CeladonCity_DepartmentStore_4F/text.inc"
	.include "data/maps/CeladonCity_DepartmentStore_5F/text.inc"
	.include "data/maps/CeladonCity_DepartmentStore_Roof/text.inc"
	.include "data/maps/CeladonCity_Condominiums_1F/text.inc"
	.include "data/maps/CeladonCity_Condominiums_2F/text.inc"
	.include "data/maps/CeladonCity_Condominiums_3F/text.inc"
	.include "data/maps/CeladonCity_Condominiums_Roof/text.inc"
	.include "data/maps/CeladonCity_Condominiums_RoofRoom/text.inc"
	.include "data/maps/CeladonCity_PokemonCenter_1F/text.inc"
	.include "data/maps/CeladonCity_GameCorner/text.inc"
	.include "data/maps/CeladonCity_GameCorner_PrizeRoom/text.inc"
	.include "data/maps/CeladonCity_Gym/text.inc"
	.include "data/maps/CeladonCity_Restaurant/text.inc"
	.include "data/maps/CeladonCity_House1/text.inc"
	.include "data/maps/CeladonCity_Hotel/text.inc"
	.include "data/maps/FuchsiaCity_SafariZone_Entrance/text.inc"
	.include "data/maps/FuchsiaCity_Mart/text.inc"
	.include "data/maps/FuchsiaCity_ZooBuilding/text.inc"
	.include "data/maps/FuchsiaCity_Gym/text.inc"
	.include "data/maps/FuchsiaCity_House1/text.inc"
	.include "data/maps/FuchsiaCity_PokemonCenter_1F/text.inc"
	.include "data/maps/FuchsiaCity_Building1/text.inc"
	.include "data/maps/FuchsiaCity_House2/text.inc"
	.include "data/maps/FuchsiaCity_House3/text.inc"
	.include "data/maps/CinnabarIsland_Gym/text.inc"
	.include "data/maps/CinnabarIsland_PokemonLab_Entrance/text.inc"
	.include "data/maps/CinnabarIsland_PokemonLab_Lounge/text.inc"
	.include "data/maps/CinnabarIsland_PokemonLab_ResearchRoom/text.inc"
	.include "data/maps/CinnabarIsland_PokemonLab_ExperimentRoom/text.inc"
	.include "data/maps/CinnabarIsland_PokemonCenter_1F/text.inc"
	.include "data/maps/CinnabarIsland_Mart/text.inc"
	.include "data/maps/IndigoPlateau_PokemonCenter_1F/text.inc"
	.include "data/maps/SaffronCity_House1_1F/text.inc"
	.include "data/maps/SaffronCity_House1_2F/text.inc"
	.include "data/maps/SaffronCity_Dojo/text.inc"
	.include "data/maps/SaffronCity_Gym/text.inc"
	.include "data/maps/SaffronCity_House2/text.inc"
	.include "data/maps/SaffronCity_Mart/text.inc"
	.include "data/maps/SaffronCity_PokemonCenter_1F/text.inc"
	.include "data/maps/SaffronCity_House3/text.inc"
	.include "data/maps/SaffronCity_PokemonTrainerFanClub/text.inc"
	.include "data/maps/Route2_ViridianForest_SouthEntrance/text.inc"
	.include "data/maps/Route2_House/text.inc"
	.include "data/maps/Route2_EastBuilding/text.inc"
	.include "data/maps/Route2_ViridianForest_NorthEntrance/text.inc"
	.include "data/maps/Route4_PokemonCenter_1F/text.inc"
	.include "data/maps/Route5_SouthEntrance/text.inc"
	.include "data/maps/Route6_NorthEntrance/text.inc"
	.include "data/maps/Route7_EastEntrance/text.inc"
	.include "data/maps/Route8_WestEntrance/text.inc"
	.include "data/maps/Route10_PokemonCenter_1F/text.inc"
	.include "data/maps/Route11_EastEntrance_1F/text.inc"
	.include "data/maps/Route11_EastEntrance_2F/text.inc"
	.include "data/maps/Route12_NorthEntrance_1F/text.inc"
	.include "data/maps/Route12_NorthEntrance_2F/text.inc"
	.include "data/maps/Route12_FishingHouse/text.inc"
	.include "data/maps/Route15_WestEntrance_1F/text.inc"
	.include "data/maps/Route15_WestEntrance_2F/text.inc"
	.include "data/maps/Route16_House/text.inc"
	.include "data/maps/Route16_NorthEntrance_1F/text.inc"
	.include "data/maps/Route16_NorthEntrance_2F/text.inc"
	.include "data/maps/Route18_EastEntrance_1F/text.inc"
	.include "data/maps/Route18_EastEntrance_2F/text.inc"
	.include "data/maps/Route25_SeaCottage/text.inc"
	.include "data/maps/SevenIsland_House_Room1/text.inc"
	.include "data/maps/SevenIsland_Mart/text.inc"
	.include "data/maps/SevenIsland_PokemonCenter_1F/text.inc"
	.include "data/maps/OneIsland_PokemonCenter_1F/text.inc"
	.include "data/maps/OneIsland_House1/text.inc"
	.include "data/maps/OneIsland_House2/text.inc"
	.include "data/maps/TwoIsland_JoyfulGameCorner/text.inc"
	.include "data/maps/TwoIsland_House/text.inc"
	.include "data/maps/TwoIsland_PokemonCenter_1F/text.inc"
	.include "data/maps/ThreeIsland_House1/text.inc"
	.include "data/maps/ThreeIsland_PokemonCenter_1F/text.inc"
	.include "data/maps/ThreeIsland_Mart/text.inc"
	.include "data/maps/ThreeIsland_House2/text.inc"
	.include "data/maps/ThreeIsland_House3/text.inc"
	.include "data/maps/ThreeIsland_House4/text.inc"
	.include "data/maps/ThreeIsland_House5/text.inc"
	.include "data/maps/FourIsland_PokemonCenter_1F/text.inc"
	.include "data/maps/FourIsland_House1/text.inc"
	.include "data/maps/FourIsland_LoreleisHouse/text.inc"
	.include "data/maps/FourIsland_Mart/text.inc"
	.include "data/maps/FiveIsland_PokemonCenter_1F/text.inc"
	.include "data/maps/FiveIsland_House1/text.inc"
	.include "data/maps/FiveIsland_House2/text.inc"
	.include "data/maps/SixIsland_PokemonCenter_1F/text.inc"
	.include "data/maps/SixIsland_House/text.inc"
	.include "data/maps/SixIsland_Mart/text.inc"
	.include "data/maps/FiveIsland_ResortGorgeous_House/text.inc"
	.include "data/maps/SixIsland_WaterPath_House1/text.inc"
	.include "data/maps/SixIsland_WaterPath_House2/text.inc"
	.include "data/maps/SevenIsland_SevaultCanyon_House/text.inc"



gStdScript_2:: @ 81A4E3F
	lock
	faceplayer
	message 0x0
	waitmessage
	waitbuttonpress
	release
	return

gStdScript_3:: @ 81A4E4A
	lockall
	message 0x0
	waitmessage
	waitbuttonpress
	releaseall
	return

gStdScript_4:: @ 81A4E54
	message 0x0
	waitmessage
	waitbuttonpress
	return

gStdScript_5:: @ 81A4E5C
	message 0x0
	waitmessage
	yesnobox 20, 8
	return

gStdScript_ItemMessageAndFanfare:: @ 81A4E66
	textcolor 3
	compare_var_to_value VAR_0x8002, MUS_FANFA1
	call_if 1, EventScript_1A4EA2
	compare_var_to_value VAR_0x8002, BGM_FRLG_ME_KEYITEM
	call_if 1, EventScript_1A4EA6
	message 0x0
	waitmessage
	waitfanfare
	compare_var_to_value VAR_0x8002, MUS_FANFA1
	call_if 1, EventScript_1A4EAA
	setorcopyvar VAR_0x8000, VAR_0x8000
	setorcopyvar VAR_0x8001, VAR_0x8001
	callstd 8
	call EventScript_1A6675
	return

EventScript_1A4EA2:: @ 81A4EA2
	playfanfare MUS_FANFA1
	return

EventScript_1A4EA6:: @ 81A4EA6
	playfanfare BGM_FRLG_ME_KEYITEM
	return

EventScript_1A4EAA:: @ 81A4EAA
	delay 50
	return

EventScript_1A4EAE:: @ 81A4EAE
	return

EventScript_1A4EAF:: @ 81A4EAF
	special sub_806F67C
	waitstate
	return

gUnknown_81A4EB4:: @ 81A4EB4
	lock
	special sub_8080628
	special ScrSpecial_EndTrainerApproach
	waitstate
	goto EventScript_1A4FC7

gUnknown_81A4EC1:: @ 81A4EC1
	lock
	faceplayer
	applymovement VAR_LAST_TALKED, Movement_1A4FC5
	waitmovement 0
	specialvar VAR_RESULT, ScrSpecial_HasTrainerBeenFought
	compare_var_to_value VAR_RESULT, 0
	goto_if 5, EventScript_1A4EE8
	special sub_8080628
	special sub_8080398
	goto EventScript_1A4FC7

EventScript_1A4EE8:: @ 81A4EE8
	ontrainerbattleend

gUnknown_81A4EE9:: @ 81A4EE9
	lock
	faceplayer
	call EventScript_1A4FBA
	specialvar VAR_RESULT, ScrSpecial_HasTrainerBeenFought
	compare_var_to_value VAR_RESULT, 0
	goto_if 5, EventScript_1A4F20
	special CheckForAlivePartyMons
	compare_var_to_value VAR_RESULT, 0
	goto_if 5, EventScript_1A4F19
	special sub_8080628
	special sub_8080398
	goto EventScript_1A4FC7

EventScript_1A4F19:: @ 81A4F19
	special sub_8080618
	waitmessage
	waitbuttonpress
	release
	end

EventScript_1A4F20:: @ 81A4F20
	ontrainerbattleend

gUnknown_81A4F21:: @ 81A4F21
	applymovement VAR_LAST_TALKED, Movement_1A4FC5
	waitmovement 0
	special sub_8080628
	special sub_8110AB4
	compare_var_to_value VAR_RESULT, 2
	goto_if_eq EventScript_1A501A
	battlebegin
	ontrainerbattleend

gUnknown_81A4F3E:: @ 81A4F3E
	call EventScript_1A4FBA
	specialvar VAR_RESULT, sub_810CEB4
	compare_var_to_value VAR_RESULT, 0
	goto_if_eq EventScript_1A4F72
	special sub_8080628
	special sub_8080398
	special sub_80805D8
	waitmessage
	waitbuttonpress
	special sub_8110AB4
	compare_var_to_value VAR_RESULT, 2
	goto_if_eq EventScript_1A4FB8
	special sub_80805B0
	waitstate
	releaseall
	end

EventScript_1A4F72:: @ 81A4F72
	ontrainerbattleend

gUnknown_81A4F73:: @ 81A4F73
	specialvar VAR_RESULT, sub_810CEB4
	compare_var_to_value VAR_RESULT, 0
	goto_if_eq EventScript_1A4FB0
	special CheckForAlivePartyMons
	compare_var_to_value VAR_RESULT, 0
	goto_if 5, EventScript_1A4FB1
	special sub_8080628
	special sub_8080398
	special sub_80805D8
	waitmessage
	waitbuttonpress
	special sub_8110AB4
	compare_var_to_value VAR_RESULT, 2
	goto_if_eq EventScript_1A4FB8
	special sub_80805B0
	waitstate
	releaseall
	end

EventScript_1A4FB0:: @ 81A4FB0
	ontrainerbattleend

EventScript_1A4FB1:: @ 81A4FB1
	special sub_8080618
	waitmessage
	waitbuttonpress
	release
	end

EventScript_1A4FB8:: @ 81A4FB8
	releaseall
	end

EventScript_1A4FBA:: @ 81A4FBA
	applymovement VAR_LAST_TALKED, Movement_1A4FC5
	waitmovement 0
	return

Movement_1A4FC5:: @ 81A4FC5
	step_67
	step_end

EventScript_1A4FC7:: @ 81A4FC7
	special sub_80805D8
	waitmessage
	waitbuttonpress
	special sub_8110AB4
	compare_var_to_value VAR_RESULT, 2
	goto_if_eq EventScript_1A501A
	battlebegin
	specialvar VAR_RESULT, sub_80803CC
	compare_var_to_value VAR_RESULT, 0
	goto_if_eq EventScript_1A5017
	compare_var_to_value VAR_RESULT, 2
	goto_if_eq EventScript_1A5019
	compare_var_to_value VAR_RESULT, 1
	goto_if_eq EventScript_1A5019
	compare_var_to_value VAR_RESULT, 6
	goto_if_eq EventScript_1A5019
	compare_var_to_value VAR_RESULT, 8
	goto_if_eq EventScript_1A5019

EventScript_1A5017:: @ 81A5017
	releaseall
	end

EventScript_1A5019:: @ 81A5019
	ontrainerbattleendgoto

EventScript_1A501A:: @ 81A501A
	special sub_80803FC
	releaseall
	end

gStdScript_Message_WaitButton_AndRelease:: @ 81A501F
	message 0x0
	waitmessage
	waitbuttonpress
	release
	return



gUnknown_81A5028:: @ 81A5028
	.string "Would you like to mix records with\n"
	.string "other TRAINERS?$"

Text_1A505B:: @ 81A505B
	.string "We hope to see you again!$"

Text_1A5075:: @ 81A5075
	.string "{PLAYER} booted up the PC.$"

gUnknown_81A508A:: @ 81A508A
	.string "Which PC should be accessed?$"

Text_1A50A7:: @ 81A50A7
	.string "Accessed Someone's PC.$"

Text_1A50BE:: @ 81A50BE
	.string "POKéMON Storage System opened.$"

Text_1A50DD:: @ 81A50DD
	.string "Accessed {PLAYER}'s PC.$"

Text_1A50EF:: @ 81A50EF
	.string "Accessed BILL's PC.$"

Text_1A5103:: @ 81A5103
	.string "Welcome to the POKéMON CABLE CLUB\n"
	.string "TRADE CENTER.$"

Text_1A5133:: @ 81A5133
	.string "Welcome to the POKéMON CABLE CLUB\n"
	.string "COLOSSEUM.$"

Text_1A5160:: @ 81A5160
	.string "Welcome to the POKéMON CABLE CLUB\n"
	.string "TIME CAPSULE.$"

gUnknown_81A5190:: @ 81A5190
	.string "Please come again!$"

Text_1A51A3:: @ 81A51A3
	.string "Welcome!\p"
	.string "We're having a discount sale today!$"

Text_1A51D0:: @ 81A51D0
	.string "{PLAYER}{KUN}, welcome!\p"
	.string "What can I do for you?$"

Text_1A51F6:: @ 81A51F6
	.string "Obtained the {STR_VAR_2}!$"

gUnknown_81A5207:: @ 81A5207
	.string "The BAG is full…$"

gUnknown_81A5218:: @ 81A5218
	.string "{PLAYER} put the {STR_VAR_2}\n"
	.string "in the {STR_VAR_3}.$"

Text_1A5231:: @ 81A5231
	.string "{PLAYER} found one {STR_VAR_2}!$"

gUnknown_81A5242:: @ 81A5242
	.string "Too bad!\n"
	.string "The BAG is full…$"

Text_1A525C:: @ 81A525C
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_1A526C:: @ 81A526C
	.string "{PLAYER} put the COINS away in\n"
	.string "the COIN CASE.$"

Text_1A5294:: @ 81A5294
	.string "Too bad!\n"
	.string "The COIN CASE is full…$"

Text_1A52B4:: @ 81A52B4
	.string "Too bad!\n"
	.string "There's nothing to put them in…$"

Text_1A52DD:: @ 81A52DD
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"

Text_1A52F0:: @ 81A52F0
	.string "Obtained the {STR_VAR_2}!$"

Text_1A5301:: @ 81A5301
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

gUnknown_81A532F:: @ 81A532F
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"

Text_1A5351:: @ 81A5351
	.string "じゅんびちゅうです！$"

Text_1A535C:: @ 81A535C
	.string "Which floor do you want?$"

Text_1A5375:: @ 81A5375
	.string "An item in the BAG can be\n"
	.string "registered to SELECT for easy use.$"

Text_1A53B2:: @ 81A53B2
	.string "パソコンに\n"
	.string "ポケモン　トレーナー　こうざの\l"
	.string "メールが　きている！\p"
	.string "‥‥　‥‥　‥‥\p"
	.string "ポケモンが　おぼえられる　わざは　4つ！\p"
	.string "どんな　わざを　おぼえさせるかで\n"
	.string "トレーナーの　じつりょくが　とわれます！\p"
	.string "‥‥　‥‥　‥‥$"

gUnknown_81A5420:: @ 81A5420
	.string "{PLAYER} booted up the PC.$"

Text_1A5435:: @ 81A5435
	.string "つうしんは　キャンセルされました$"

Text_1A5446:: @ 81A5446
	.string "Want to give a nickname to the\n"
	.string "{STR_VAR_2} you received?$"

gText_PkmnFainted3:: @ 81A5476
	.string "{STR_VAR_1} fainted…\p"
	.string "$"

Text_1A5483:: @ 81A5483
	.string "Welcome to our POKéMON CENTER!\p"
	.string "Would you like me to heal your\n"
	.string "POKéMON back to perfect health?$"

Text_1A54E1:: @ 81A54E1
	.string "Okay, I'll take your POKéMON for a\n"
	.string "few seconds.$"

Text_1A5511:: @ 81A5511
	.string "We hope to see you again!$"

Text_1A552B:: @ 81A552B
	.string "Thank you for waiting.\n"
	.string "We've restored your POKéMON to\l"
	.string "full health.$"

Text_1A556E:: @ 81A556E
	.string "The water is dyed a deep blue…\n"
	.string "Would you like to SURF?$"

Text_1A55A5:: @ 81A55A5
	.string "{STR_VAR_1} used SURF!$"

Text_1A55B3:: @ 81A55B3
	.string "The current is much too fast!\n"
	.string "SURF can't be used here…$"

Text_1A55EA:: @ 81A55EA
	.string "どこか　とおくの　とびらが\n"
	.string "ひらいたような　おとだ‥‥$"

Text_1A5606:: @ 81A5606
	.string "かべに\n"
	.string "おおきな　あなが　あいている！$"

Text_1A561A:: @ 81A561A
	.string "I'm terribly sorry.\n"
	.string "The POKéMON WIRELESS CLUB is\l"
	.string "undergoing adjustments now.$"

Text_1A5667:: @ 81A5667
	.string "It appears to be undergoing\n"
	.string "adjustments…$"

Text_1A5690:: @ 81A5690
	.string "{PLAYER} handed over the\n"
	.string "{STR_VAR_1}.$"

gUnknown_81A56A7:: @ 81A56A7
	.string "Do you want to give a nickname to\n"
	.string "this {STR_VAR_1}?$"

Text_1A56D2:: @ 81A56D2
	.string "おッ！　ダウジングマシンが\n"
	.string "はんのう　してるぞ！\p"
	.string "ましたに　どうぐが　うまってる！\n"
	.string "‥‥‥$"

Text_1A5700:: @ 81A5700
	.string "{PLAYER} dug up one {STR_VAR_2}\n"
	.string "from deep in the ground.$"

Text_1A572A:: @ 81A572A
	.string "Only truly skilled TRAINERS are\n"
	.string "allowed through.\p"
	.string "You don't have the {STR_VAR_1}\n"
	.string "yet!$"

Text_1A5776:: @ 81A5776
	.string "Rules are rules.\n"
	.string "I can't let you pass.$"

Text_1A579D:: @ 81A579D
	.string "Oh! That is the {STR_VAR_1}!\n"
	.string "Go right ahead.$"

Text_1A57C1:: @ 81A57C1
	.string "You can pass here only if you have\n"
	.string "the {STR_VAR_1}.\p"
	.string "You don't have the {STR_VAR_1}\n"
	.string "yet.\p"
	.string "You have to have it to get to\n"
	.string "the POKéMON LEAGUE.$"

Text_1A5839:: @ 81A5839
	.string "You can pass here only if you have\n"
	.string "the {STR_VAR_1}.\p"
	.string "Oh! That is the {STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM}{MUS_FANFA1}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "Okay, then.\n"
	.string "Please, go right ahead.$"

Text_1A58A7:: @ 81A58A7
	.string "Let's see…\n"
	.string "Uh-oh! You have caught only\l"
	.string "{STR_VAR_3} kinds of POKéMON!\p"
	.string "You need {STR_VAR_1} kinds\n"
	.string "if you want the {STR_VAR_2}.$"

Text_1A5909:: @ 81A5909
	.string "…Oh. I see.\p"
	.string "When you get {STR_VAR_1} kinds of POKéMON,\n"
	.string "come back for the {STR_VAR_2}.$"

Text_1A594D:: @ 81A594D
	.string "Oh! I see you don't have any\n"
	.string "room for the {STR_VAR_2}.$"

gUnknown_81A597B:: @ 81A597B
	.string "I'm looking for the POKéMON\n"
	.string "{STR_VAR_1}!\p"
	.string "Wanna trade one for my\n"
	.string "{STR_VAR_2}?$"

gUnknown_81A59B6:: @ 81A59B6
	.string "Awww!\n"
	.string "Oh, well…$"

gUnknown_81A59C6:: @ 81A59C6
	.string "What?\n"
	.string "That's no {STR_VAR_1}!$"

gUnknown_81A59DA:: @ 81A59DA
	.string "Hey, thanks!$"

gUnknown_81A59E7:: @ 81A59E7
	.string "Isn't my old {STR_VAR_2} great?$"

gUnknown_81A59FE:: @ 81A59FE
	.string "Hello, there! Do you happen to\n"
	.string "have a {STR_VAR_1}?\p"
	.string "Would you agree to a trade for\n"
	.string "my {STR_VAR_2}?$"

gUnknown_81A5A4E:: @ 81A5A4E
	.string "Well, if you don't want to…$"

gUnknown_81A5A6A:: @ 81A5A6A
	.string "Hmmm?\n"
	.string "This isn't a {STR_VAR_1}.\p"
	.string "Think of me if you get one.$"

gUnknown_81A5A9D:: @ 81A5A9D
	.string "Thanks!$"

gUnknown_81A5AA5:: @ 81A5AA5
	.string "The {STR_VAR_2} that I traded you,\n"
	.string "has it grown stronger?$"

gUnknown_81A5AD6:: @ 81A5AD6
	.string "Hi!\n"
	.string "Do you have a {STR_VAR_1}?\p"
	.string "Want to trade it for my\n"
	.string "{STR_VAR_2}?$"

gUnknown_81A5B08:: @ 81A5B08
	.string "That's too bad.$"

gUnknown_81A5B18:: @ 81A5B18
	.string "…This is no {STR_VAR_1}.\p"
	.string "If you get one, trade it with me.$"

gUnknown_81A5B4A:: @ 81A5B4A
	.string "Thanks, you're a pal!$"

gUnknown_81A5B60:: @ 81A5B60
	.string "How is my old {STR_VAR_2}?\n"
	.string "My {STR_VAR_1} is doing great!$"

Text_1A5B88:: @ 81A5B88
	.string "Bingo!\n"
	.string "The CARD KEY opened the door!$"

Text_1A5BAD:: @ 81A5BAD
	.string "No!\n"
	.string "It needs a CARD KEY!$"

Text_1A5BC6:: @ 81A5BC6
	.string "Accessed PROF. OAK's PC…\p"
	.string "Accessed the POKéDEX Rating\n"
	.string "System…$"

Text_1A5C03:: @ 81A5C03
	.string "Would you like to have your\n"
	.string "POKéDEX rated?$"

Text_1A5C2E:: @ 81A5C2E
	.string "Closed link to PROF. OAK's PC.$"

Text_1A5C4D:: @ 81A5C4D
	.string "Someone's voice rang out,\n"
	.string "“Don't run away!”$"

Text_1A5C79:: @ 81A5C79
	.string "えっとー\n"
	.string "{STR_VAR_2}が　みてみたいなー\p"
	.string "それも　{STR_VAR_1}{STR_VAR_3}\n"
	.string "{STR_VAR_2}が　みてみたいなー$"

Text_1A5C9F:: @ 81A5C9F
	.string "わぁー　すごい！\n"
	.string "{STR_VAR_1}{STR_VAR_3}{STR_VAR_2}だー！\p"
	.string "ありがとー\n"
	.string "また　よろしくねー！$"

Text_1A5CC3:: @ 81A5CC3
	.string "それっ　ちがうよー！$"

Text_1A5CCE:: @ 81A5CCE
	.string "そっか‥$"

Text_1A5CD3:: @ 81A5CD3
	.string "ドアは　しまっている‥$"

Text_1A5CDF:: @ 81A5CDF
	.string "The door is open…$"

Text_1A5CF1:: @ 81A5CF1
	.string "{STR_VAR_2} was transferred to\n"
	.string "Someone's PC.\p"
	.string "It was placed in \n"
	.string "BOX “{STR_VAR_1}.”$"

Text_1A5D31:: @ 81A5D31
	.string "{STR_VAR_2} was transferred to\n"
	.string "BILL'S PC.\p"
	.string "It was placed in \n"
	.string "BOX “{STR_VAR_1}.”$"

Text_1A5D6E:: @ 81A5D6E
	.string "BOX “{STR_VAR_3}” on\n"
	.string "Someone's PC was full.\p"
	.string "{STR_VAR_2} was transferred to\n"
	.string "BOX “{STR_VAR_1}.”$"

Text_1A5DB1:: @ 81A5DB1
	.string "BOX “{STR_VAR_3}” on\n"
	.string "BILL'S PC was full.\p"
	.string "{STR_VAR_2} was transferred to\n"
	.string "BOX “{STR_VAR_1}.”$"

Text_1A5DF1:: @ 81A5DF1
	.string "{PLAYER} obtained\n"
	.string "the {STR_VAR_1}!$"

Text_1A5E05:: @ 81A5E05
	.string "ポケモンを　もちきれないので\n"
	.string "パソコンの　ボックス“{STR_VAR_1}”　に\l"
	.string "{STR_VAR_2}を　てんそうした！$"

gUnknown_81A5E31:: @ 81A5E31
	.string "There's no more room for POKéMON!\p"
	.string "The POKéMON BOXES are full and\n"
	.string "can't accept any more!$"

Text_1A5E89:: @ 81A5E89
	.string "First, you should restore your\n"
	.string "POKéMON to full health.$"

Text_1A5EC0:: @ 81A5EC0
	.string "Your POKéMON have been healed\n"
	.string "to perfect health.\p"
	.string "If your POKéMON's energy, HP,\n"
	.string "is down, please come see us.\p"
	.string "If you're planning to go far in the\n"
	.string "field, you should buy some POTIONS\l"
	.string "at the POKéMON MART.\p"
	.string "We hope you excel!$"

Text_1A5F9B:: @ 81A5F9B
	.string "Your POKéMON have been healed\n"
	.string "to perfect health.\p"
	.string "We hope you excel!$"

Text_1A5FDF:: @ 81A5FDF
	.string "MOM: {PLAYER}!\n"
	.string "Welcome home.\p"
	.string "It sounds like you had quite\n"
	.string "an experience.\p"
	.string "Maybe you should take a quick\n"
	.string "rest.$"

Text_1A6046:: @ 81A6046
	.string "MOM: Oh, good! You and your\n"
	.string "POKéMON are looking great.\p"
	.string "I just heard from PROF. OAK.\p"
	.string "He said that POKéMON's energy is\n"
	.string "measured in HP.\p"
	.string "If your POKéMON lose their HP,\n"
	.string "you can restore them at any\l"
	.string "POKéMON CENTER.\p"
	.string "If you're going to travel far away,\n"
	.string "the smart TRAINER stocks up on\l"
	.string "POTIONS at the POKéMON MART.\p"
	.string "Make me proud, honey!\p"
	.string "Take care!$"

Text_1A6197:: @ 81A6197
	.string "{PLAYER} is out of usable\n"
	.string "POKéMON!\p"
	.string "{PLAYER} panicked and lost ¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "{PLAYER} whited out!$"

Text_1A61E5:: @ 81A61E5
	.string "{PLAYER} is out of usable\n"
	.string "POKéMON!\p"
	.string "{PLAYER} whited out!$"

Text_1A6211:: @ 81A6211
	.string "Hi, there!\n"
	.string "May I help you?$"

Text_1A622C:: @ 81A622C
	.string "There is a questionnaire.\n"
	.string "Would you like to fill it out?$"

Text_1A6265:: @ 81A6265
	.string "Thank you for taking the time to\n"
	.string "fill out our questionnaire.\p"
	.string "Your feedback will be used for\n"
	.string "future reference.$"

Text_1A62D3:: @ 81A62D3
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must know about\n"
	.string "the MYSTERY GIFT.\p"
	.string "From now on, you should be\n"
	.string "receiving MYSTERY GIFTS!$"

Text_1A6359:: @ 81A6359
	.string "Once you save your game, you can\n"
	.string "access the MYSTERY GIFT.$"

Text_1A6393:: @ 81A6393
	.string "Thank you for accessing the\n"
	.string "MYSTERY GIFT System.$"

Text_1A63C4:: @ 81A63C4
	.string "The {STR_VAR_1} flew away!$"

Text_1A63D6:: @ 81A63D6
	.string "ベッドが　ある‥‥\n"
	.string "やすんでいこう$"

Text_1A63E8:: @ 81A63E8
	.string "{PLAYER} found a {STR_VAR_2}!\n"
	.string "It contains {STR_VAR_1}.$"

Text_1A6407:: @ 81A6407
	.string "おつかれさん！\n"
	.string "どこに　いきたいんだ？$"

Text_1A641B:: @ 81A641B
	.string "All right!\n"
	.string "All aboard SEAGALLOP HI-SPEED {STR_VAR_1}!$"

Text_1A6448:: @ 81A6448
	.string "Gyaoo!$"

Text_1A644F:: @ 81A644F
	.string "This move can be learned only\n"
	.string "once. Is that okay?$"


EventScript_ResetAllMapFlags:: @ 81A6481
	setflag FLAG_0x02B
	setflag FLAG_0x02C
	setflag FLAG_0x033
	setflag FLAG_0x092
	setflag FLAG_0x035
	setflag FLAG_0x036
	setflag FLAG_0x037
	setflag FLAG_0x03C
	setflag FLAG_0x03D
	setflag FLAG_0x0A1
	setflag FLAG_0x03F
	setflag FLAG_0x04F
	setflag FLAG_0x05A
	setflag FLAG_0x0A3
	setflag FLAG_0x0A4
	setflag FLAG_0x062
	setflag FLAG_0x06B
	setflag FLAG_0x0A2
	setflag FLAG_0x08C
	setflag FLAG_0x06C
	setflag FLAG_0x06D
	setflag FLAG_0x06E
	setflag FLAG_0x06F
	setflag FLAG_0x075
	setflag FLAG_0x074
	setflag FLAG_0x07B
	setflag FLAG_0x07C
	setflag FLAG_0x07D
	setflag FLAG_0x076
	setflag FLAG_0x091
	setflag FLAG_0x097
	setflag FLAG_0x090
	setflag FLAG_0x094
	setflag FLAG_0x095
	setflag FLAG_0x096
	setflag FLAG_0x099
	setflag FLAG_0x0A5
	setflag FLAG_0x0A6
	setflag FLAG_0x0A7
	setflag FLAG_0x0A8
	setflag FLAG_0x0A9
	setflag FLAG_0x0AA
	setflag FLAG_0x0AB
	setflag FLAG_0x0AC
	setflag FLAG_0x09D
	setflag FLAG_0x09E
	setflag FLAG_0x09F
	setflag FLAG_0x0A0
	setflag FLAG_0x0AE
	setvar VAR_0x4025, 500
	end

EventScript_1A651A:: @ 81A651A
	clearflag FLAG_0x09D
	call EventScript_1A6551
	special sub_81130A8
	specialvar VAR_RESULT, sub_806E25C
	compare_var_to_value VAR_RESULT, 0
	call_if 1, EventScript_1A653B
	call EventScript_1A6541
	return

EventScript_1A653B:: @ 81A653B
	setvar VAR_MAP_SCENE_PALLET_TOWN, 2
	return

EventScript_1A6541:: @ 81A6541
	clearflag FLAG_0x2F5
	clearflag FLAG_0x2F6
	clearflag FLAG_0x2F7
	return

gUnknown_81A654B:: @ 81A654B
	call EventScript_1A6551
	end

EventScript_1A6551:: @ 81A6551
	clearflag FLAG_0x4B8
	clearflag FLAG_0x4B9
	clearflag FLAG_0x4BA
	clearflag FLAG_0x4BB
	clearflag FLAG_0x4BC
	cleartrainerflag 438
	cleartrainerflag 439
	cleartrainerflag 440
	cleartrainerflag 739
	cleartrainerflag 740
	cleartrainerflag 741
	setvar VAR_0x4068, 0
	return

EventScript_1A6578:: @ 81A6578
	special sub_8110AB4
	compare_var_to_value VAR_RESULT, 2
	goto_if_eq EventScript_1A7AE0
	message Text_1A5483
	waitmessage
	multichoice 19, 8, 0, 2
	switch VAR_RESULT
	case 0, EventScript_1A65B8
	case 1 EventScript_1A6663
	case 127, EventScript_1A6663
	end

EventScript_1A65B8:: @ 81A65B8
	incrementgamestat 15
	message Text_1A54E1
	waitmessage
	call EventScript_1A65CE
	special sub_80CC524
	goto EventScript_1A65EC
	end

EventScript_1A65CE:: @ 81A65CE
	applymovement VAR_LAST_TALKED, Movement_1A75E7
	waitmovement 0
	dofieldeffect 25
	waitfieldeffect 25
	applymovement VAR_LAST_TALKED, Movement_1A75ED
	waitmovement 0
	special sp000_heal_pokemon
	return

EventScript_1A65EC:: @ 81A65EC
	specialvar VAR_RESULT, sub_80CD074
	compare_var_to_value VAR_RESULT, 0
	goto_if_eq EventScript_1A661D
	specialvar VAR_RESULT, sp182_move_string
	copyvar VAR_0x8008, VAR_RESULT
	compare_var_to_value VAR_0x8008, 0
	goto_if_eq EventScript_1A661D
	compare_var_to_value VAR_0x8008, 1
	goto_if_eq EventScript_1A6636
	end

EventScript_1A661D:: @ 81A661D
	message Text_1A552B
	waitmessage
	applymovement VAR_LAST_TALKED, Movement_1A666C
	waitmovement 0
	msgbox Text_1A5511
	return

EventScript_1A6636:: @ 81A6636
	checkflag 2114
	goto_if_eq EventScript_1A661D
	msgbox Text_1A552B
	setflag 2114
	message Text_1BCCCA
	waitmessage
	applymovement VAR_LAST_TALKED, Movement_1A666C
	waitmovement 0
	msgbox Text_1A5511
	return

EventScript_1A6663:: @ 81A6663
	msgbox Text_1A5511
	return

Movement_1A666C:: @ 81A666C
	step_5b
	step_1a
	step_end

EventScript_1A666F:: @ 81A666F
	copyvar VAR_MON_BOX_POS, VAR_MON_BOX_ID
	return

EventScript_1A6675:: @ 81A6675
	copyvar VAR_MON_BOX_ID, VAR_MON_BOX_POS
	return



gStdScript_0:: @ 81A667B
	copyvar VAR_MON_BOX_POS, VAR_MON_BOX_ID
	textcolor 3
	additem VAR_0x8000, VAR_0x8001
	copyvar VAR_0x8007, VAR_RESULT
	call EventScript_1A6697
	copyvar VAR_MON_BOX_ID, VAR_MON_BOX_POS
	return

EventScript_1A6697:: @ 81A6697
	bufferitemnameplural 1, VAR_0x8000, VAR_0x8001
	checkitemtype VAR_0x8000
	call EventScript_1A66BC
	compare_var_to_value VAR_0x8007, 1
	call_if 1, EventScript_1A6749
	compare_var_to_value VAR_0x8007, 0
	call_if 1, EventScript_1A675E
	return

EventScript_1A66BC:: @ 81A66BC
	copyvar VAR_0x8000, VAR_RESULT
	compare_var_to_value VAR_0x8000, 1
	goto_if_eq EventScript_1A66F9
	compare_var_to_value VAR_0x8000, 2
	goto_if_eq EventScript_1A6709
	compare_var_to_value VAR_0x8000, 3
	goto_if_eq EventScript_1A6719
	compare_var_to_value VAR_0x8000, 4
	goto_if_eq EventScript_1A6729
	compare_var_to_value VAR_0x8000, 5
	goto_if_eq EventScript_1A6739
	end

EventScript_1A66F9:: @ 81A66F9
	getstdstring 2, 24
	compare_var_to_value VAR_0x8007, 1
	call_if 1, EventScript_1A6764
	return

EventScript_1A6709:: @ 81A6709
	getstdstring 2, 25
	compare_var_to_value VAR_0x8007, 1
	call_if 1, EventScript_1A6764
	return

EventScript_1A6719:: @ 81A6719
	getstdstring 2, 26
	compare_var_to_value VAR_0x8007, 1
	call_if 1, EventScript_1A6764
	return

EventScript_1A6729:: @ 81A6729
	getstdstring 2, 27
	compare_var_to_value VAR_0x8007, 1
	call_if 1, EventScript_1A6768
	return

EventScript_1A6739:: @ 81A6739
	getstdstring 2, 28
	compare_var_to_value VAR_0x8007, 1
	call_if 1, EventScript_1A6764
	return

EventScript_1A6749:: @ 81A6749
	message Text_1A51F6
	waitfanfare
	waitmessage
	msgbox gUnknown_81A5218
	setvar VAR_RESULT, 1
	return

EventScript_1A675E:: @ 81A675E
	setvar VAR_RESULT, 0
	return

EventScript_1A6764:: @ 81A6764
	playfanfare MUS_FANFA1
	return

EventScript_1A6768:: @ 81A6768
	playfanfare MUS_FANFA1
	return

gStdScript_7:: @ 81A676C
	adddecor VAR_0x8000
	copyvar VAR_0x8007, VAR_RESULT
	call EventScript_1A677A
	return

EventScript_1A677A:: @ 81A677A
	getdecorname 1, VAR_0x8000
	compare_var_to_value VAR_0x8007, 1
	call_if 1, EventScript_1A6795
	compare_var_to_value VAR_0x8007, 0
	call_if 1, EventScript_1A67AD
	return

EventScript_1A6795:: @ 81A6795
	playfanfare MUS_FANFA4
	message Text_1A52F0
	waitfanfare
	waitmessage
	msgbox gUnknown_81A532F
	setvar VAR_RESULT, 1
	return

EventScript_1A67AD:: @ 81A67AD
	setvar VAR_RESULT, 0
	return

gStdScript_1:: @ 81A67B3
	lock
	faceplayer
	waitse
	copyvar VAR_0x8004, VAR_0x8000
	copyvar VAR_0x8005, VAR_0x8001
	checkitemspace VAR_0x8000, VAR_0x8001
	copyvar VAR_0x8007, VAR_RESULT
	getitemname 1, VAR_0x8000
	checkitemtype VAR_0x8000
	call EventScript_1A66BC
	compare_var_to_value VAR_0x8007, 1
	call_if 1, EventScript_1A67EE
	compare_var_to_value VAR_0x8007, 0
	call_if 1, EventScript_1A682D
	release
	return

EventScript_1A67EE:: @ 81A67EE
	removeobject VAR_LAST_TALKED
	additem VAR_0x8004, VAR_0x8005
	specialvar VAR_RESULT, sub_80CC8CC
	copyvar VAR_0x8008, VAR_RESULT
	compare_var_to_value VAR_0x8008, 1
	call_if 1, EventScript_1A6821
	compare_var_to_value VAR_0x8008, 0
	call_if 1, EventScript_1A6827
	waitfanfare
	waitmessage
	msgbox gUnknown_81A5218
	return

EventScript_1A6821:: @ 81A6821
	message Text_1A63E8
	return

EventScript_1A6827:: @ 81A6827
	message Text_1A5231
	return

EventScript_1A682D:: @ 81A682D
	msgbox Text_1A51F6
	msgbox gUnknown_81A5242
	setvar VAR_RESULT, 0
	return

EventScript_PickUpHiddenItem:: @ 81A6843
	lockall
	textcolor 3
	waitse
	compare_var_to_value VAR_0x8005, 0
	goto_if_eq EventScript_PickUpHiddenCoins
	call EventScript_GiveItem
	compare_var_to_value VAR_0x8007, 1
	goto_if_eq EventScript_ItemInPocketMessage
	compare_var_to_value VAR_0x8007, 0
	goto_if_eq EventScript_BagIsFullMessage
	end

EventScript_GiveItem::
	additem VAR_0x8005, VAR_0x8006
	copyvar VAR_0x8007, VAR_RESULT
	getitemname 1, VAR_0x8005
	checkitemtype VAR_0x8005
	call EventScript_1A66BC
	return

EventScript_ItemInPocketMessage::
	compare_var_to_value VAR_0x8006, 1
	call_if 1, EventScript_FoundSingleItemMessage
	compare_var_to_value VAR_0x8006, 1
	call_if 5, EventScript_FoundMultipleItemsMessage
	waitfanfare
	waitmessage
	msgbox gUnknown_81A5218
	special Special_SetHiddenItemFlag
	releaseall
	end

EventScript_FoundSingleItemMessage::
	message Text_1A5231
	return

EventScript_FoundCoinsMessage::
	getnumberstring 0, VAR_0x8006
	message Text_1A525C
	return

EventScript_FoundMultipleItemsMessage::
	getnumberstring 0, VAR_0x8006
	message Text_1A52DD
	return

EventScript_BagIsFullMessage::
	msgbox Text_1A5231
	msgbox gUnknown_81A5242
	setvar VAR_RESULT, 0
	releaseall
	end

EventScript_PickUpHiddenCoins::
	checkflag FLAG_GOT_COIN_CASE
	goto_if 0, EventScript_HiddenCoinsButNoCoinCase
	checkcoins VAR_RESULT
	specialvar VAR_RESULT, Special_CheckAddCoins
	compare_var_to_value VAR_RESULT, 0
	goto_if_eq EventScript_HiddenCoinsButTheCoinCaseIsFull
	givecoins VAR_0x8006
	getstdstring 1, 0x17
	call EventScript_1A6764
	call EventScript_FoundCoinsMessage
	waitfanfare
	waitmessage
	msgbox Text_1A526C
	special Special_SetHiddenItemFlag
	releaseall
	end

EventScript_HiddenCoinsButTheCoinCaseIsFull::
	getnumberstring 0, VAR_0x8006
	getstdstring 1, 0x17
	msgbox Text_1A525C
	msgbox Text_1A5294
	setvar VAR_RESULT, 0
	releaseall
	end

EventScript_HiddenCoinsButNoCoinCase::
	getnumberstring 0, VAR_0x8006
	getstdstring 1, 0x17
	msgbox Text_1A525C
	msgbox Text_1A52B4
	setvar VAR_RESULT, 0
	releaseall
	end

gUnknown_81A6955:: @ 81A6955
	.incbin "baserom.gba", 0x1A6955, 0x173

gUnknown_81A6AC8:: @ 81A6AC8
	.incbin "baserom.gba", 0x1A6AC8, 0x45

gUnknown_81A6B0D:: @ 81A6B0D
	.incbin "baserom.gba", 0x1A6B0D, 0xB

EventScript_1A6B18:: @ 81A6B18
	.incbin "baserom.gba", 0x1A6B18, 0xE1

EventScript_1A6BF9:: @ 81A6BF9
	.incbin "baserom.gba", 0x1A6BF9, 0x2D

EventScript_1A6C26:: @ 81A6C26
	.incbin "baserom.gba", 0x1A6C26, 0xC

gUnknown_81A6C32:: @ 81A6C32
	.incbin "baserom.gba", 0x1A6C32, 0xE5

gUnknown_81A6D17:: @ 81A6D17
	.incbin "baserom.gba", 0x1A6D17, 0x56

gUnknown_81A6D6D:: @ 81A6D6D
	.incbin "baserom.gba", 0x1A6D6D, 0x72

gUnknown_81A6DDF:: @ 81A6DDF
	.incbin "baserom.gba", 0x1A6DDF, 0x57

gUnknown_81A6E36:: @ 81A6E36
	.incbin "baserom.gba", 0x1A6E36, 0x6E

gUnknown_81A6EA4:: @ 81A6EA4
	.incbin "baserom.gba", 0x1A6EA4, 0x67

gUnknown_81A6F0B:: @ 81A6F0B
	.incbin "baserom.gba", 0x1A6F0B, 0x66

gUnknown_81A6F71:: @ 81A6F71
	.incbin "baserom.gba", 0x1A6F71, 0x3A

gUnknown_81A6FAB:: @ 81A6FAB
	.incbin "baserom.gba", 0x1A6FAB, 0x46

gUnknown_81A6FF1:: @ 81A6FF1
	.incbin "baserom.gba", 0x1A6FF1, 0x40

gUnknown_81A7031:: @ 81A7031
	.incbin "baserom.gba", 0x1A7031, 0x32

gUnknown_81A7063:: @ 81A7063
	.incbin "baserom.gba", 0x1A7063, 0x42

gUnknown_81A70A5:: @ 81A70A5
	.incbin "baserom.gba", 0x1A70A5, 0x33

gUnknown_81A70D8:: @ 81A70D8
	.incbin "baserom.gba", 0x1A70D8, 0x30

gUnknown_81A7108:: @ 81A7108
	.incbin "baserom.gba", 0x1A7108, 0x2F

gUnknown_81A7137:: @ 81A7137
	.incbin "baserom.gba", 0x1A7137, 0x3E

gUnknown_81A7175:: @ 81A7175
	.incbin "baserom.gba", 0x1A7175, 0x11C

Text_1A7291:: @ 81A7291
	.incbin "baserom.gba", 0x1A7291, 0x1C

gUnknown_81A72AD:: @ 81A72AD
	.incbin "baserom.gba", 0x1A72AD, 0xCE

EventScript_1A737B:: @ 81A737B
	.incbin "baserom.gba", 0x1A737B, 0x170

EventScript_1A74EB:: @ 81A74EB
	.incbin "baserom.gba", 0x1A74EB, 0x1B

EventScript_1A7506:: @ 81A7506
	.incbin "baserom.gba", 0x1A7506, 0x19

EventScript_1A751F:: @ 81A751F
	.incbin "baserom.gba", 0x1A751F, 0x19

EventScript_1A7538:: @ 81A7538
	.incbin "baserom.gba", 0x1A7538, 0x2B

EventScript_1A7563:: @ 81A7563
	.incbin "baserom.gba", 0x1A7563, 0x26

EventScript_1A7589:: @ 81A7589
	.incbin "baserom.gba", 0x1A7589, 0x13

EventScript_1A759C:: @ 81A759C
	.incbin "baserom.gba", 0x1A759C, 0x39

EventScript_1A75D5:: @ 81A75D5
	.incbin "baserom.gba", 0x1A75D5, 0x4

Movement_1A75D9:: @ 81A75D9
	.incbin "baserom.gba", 0x1A75D9, 0x2

Movement_1A75DB:: @ 81A75DB
	.incbin "baserom.gba", 0x1A75DB, 0x2

Movement_1A75DD:: @ 81A75DD
	.incbin "baserom.gba", 0x1A75DD, 0x4

Movement_1A75E1:: @ 81A75E1
	.incbin "baserom.gba", 0x1A75E1, 0x4

Movement_1A75E5:: @ 81A75E5
	.incbin "baserom.gba", 0x1A75E5, 0x2

Movement_1A75E7:: @ 81A75E7
	.incbin "baserom.gba", 0x1A75E7, 0x2

Movement_1A75E9:: @ 81A75E9
	.incbin "baserom.gba", 0x1A75E9, 0x2

Movement_1A75EB:: @ 81A75EB
	.incbin "baserom.gba", 0x1A75EB, 0x2

Movement_1A75ED:: @ 81A75ED
	.incbin "baserom.gba", 0x1A75ED, 0x2

Movement_1A75EF:: @ 81A75EF
	.incbin "baserom.gba", 0x1A75EF, 0x2

Movement_1A75F1:: @ 81A75F1
	.incbin "baserom.gba", 0x1A75F1, 0x15

gUnknown_81A7606:: @ 81A7606
	.incbin "baserom.gba", 0x1A7606, 0x9

gUnknown_81A760F:: @ 81A760F
	.incbin "baserom.gba", 0x1A760F, 0x9

gUnknown_81A7618:: @ 81A7618
	.incbin "baserom.gba", 0x1A7618, 0x9

gUnknown_81A7621:: @ 81A7621
	.incbin "baserom.gba", 0x1A7621, 0x9

gUnknown_81A762A:: @ 81A762A
	.incbin "baserom.gba", 0x1A762A, 0x9

gUnknown_81A7633:: @ 81A7633
	.incbin "baserom.gba", 0x1A7633, 0x9

gUnknown_81A763C:: @ 81A763C
	.incbin "baserom.gba", 0x1A763C, 0x9

gUnknown_81A7645:: @ 81A7645
	.incbin "baserom.gba", 0x1A7645, 0x9

gUnknown_81A764E:: @ 81A764E
	.incbin "baserom.gba", 0x1A764E, 0x9

gUnknown_81A7657:: @ 81A7657
	.incbin "baserom.gba", 0x1A7657, 0x9

gUnknown_81A7660:: @ 81A7660
	.incbin "baserom.gba", 0x1A7660, 0x9

gUnknown_81A7669:: @ 81A7669
	.incbin "baserom.gba", 0x1A7669, 0x9

gUnknown_81A7672:: @ 81A7672
	.incbin "baserom.gba", 0x1A7672, 0x9

gUnknown_81A767B:: @ 81A767B
	.incbin "baserom.gba", 0x1A767B, 0x9

gUnknown_81A7684:: @ 81A7684
	.incbin "baserom.gba", 0x1A7684, 0x9

gUnknown_81A768D:: @ 81A768D
	.incbin "baserom.gba", 0x1A768D, 0x9

gUnknown_81A7696:: @ 81A7696
	.incbin "baserom.gba", 0x1A7696, 0x9

gUnknown_81A769F:: @ 81A769F
	.incbin "baserom.gba", 0x1A769F, 0x9

gUnknown_81A76A8:: @ 81A76A8
	.incbin "baserom.gba", 0x1A76A8, 0x9

gUnknown_81A76B1:: @ 81A76B1
	.incbin "baserom.gba", 0x1A76B1, 0x9

gUnknown_81A76BA:: @ 81A76BA
	.incbin "baserom.gba", 0x1A76BA, 0x9

gUnknown_81A76C3:: @ 81A76C3
	.incbin "baserom.gba", 0x1A76C3, 0x9

gUnknown_81A76CC:: @ 81A76CC
	.incbin "baserom.gba", 0x1A76CC, 0x9

gUnknown_81A76D5:: @ 81A76D5
	.incbin "baserom.gba", 0x1A76D5, 0x9

gUnknown_81A76DE:: @ 81A76DE
	.incbin "baserom.gba", 0x1A76DE, 0x9

gUnknown_81A76E7:: @ 81A76E7
	.incbin "baserom.gba", 0x1A76E7, 0x9

gUnknown_81A76F0:: @ 81A76F0
	.incbin "baserom.gba", 0x1A76F0, 0x9

gUnknown_81A76F9:: @ 81A76F9
	.incbin "baserom.gba", 0x1A76F9, 0x9

gUnknown_81A7702:: @ 81A7702
	.incbin "baserom.gba", 0x1A7702, 0x9E

gUnknown_81A77A0:: @ 81A77A0
	.incbin "baserom.gba", 0x1A77A0, 0x9

EventScript_1A77A9:: @ 81A77A9
	.incbin "baserom.gba", 0x1A77A9, 0x1

EventScript_1A77AA:: @ 81A77AA
	.incbin "baserom.gba", 0x1A77AA, 0x6

EventScript_1A77B0:: @ 81A77B0
	.incbin "baserom.gba", 0x1A77B0, 0x6

Route16_NorthEntrance_1F_EventScript_1A77B6:: @ 81A77B6
Route18_EastEntrance_1F_EventScript_1A77B6:: @ 81A77B6
	.incbin "baserom.gba", 0x1A77B6, 0xB

Route16_NorthEntrance_1F_EventScript_1A77C1:: @ 81A77C1
Route18_EastEntrance_1F_EventScript_1A77C1:: @ 81A77C1
	.incbin "baserom.gba", 0x1A77C1, 0x42

EventScript_1A7803:: @ 81A7803
	.incbin "baserom.gba", 0x1A7803, 0x69

EventScript_1A786C:: @ 81A786C
	.incbin "baserom.gba", 0x1A786C, 0x102

EventScript_1A796E:: @ 81A796E
	.incbin "baserom.gba", 0x1A796E, 0x14B

EventScript_1A7AB9:: @ 81A7AB9
	.incbin "baserom.gba", 0x1A7AB9, 0x4

EventScript_1A7ABD:: @ 81A7ABD
	.incbin "baserom.gba", 0x1A7ABD, 0xA

EventScript_1A7AC7:: @ 81A7AC7
	.incbin "baserom.gba", 0x1A7AC7, 0xA

EventScript_1A7AD1:: @ 81A7AD1
	.incbin "baserom.gba", 0x1A7AD1, 0xA

gUnknown_81A7ADB:: @ 81A7ADB
	.incbin "baserom.gba", 0x1A7ADB, 0x5

EventScript_1A7AE0:: @ 81A7AE0
	.incbin "baserom.gba", 0x1A7AE0, 0x2

EventScript_1A7AE2:: @ 81A7AE2
	.incbin "baserom.gba", 0x1A7AE2, 0x98

EventScript_1A7B7A:: @ 81A7B7A
	.incbin "baserom.gba", 0x1A7B7A, 0x1C4

EventScript_1A7D3E:: @ 81A7D3E
	.incbin "baserom.gba", 0x1A7D3E, 0x134

EventScript_1A7E72:: @ 81A7E72
	.incbin "baserom.gba", 0x1A7E72, 0xDA

EventScript_1A7F4C:: @ 81A7F4C
	.incbin "baserom.gba", 0x1A7F4C, 0x1FD

EventScript_1A8149:: @ 81A8149
	.incbin "baserom.gba", 0x1A8149, 0x2E

EventScript_1A8177:: @ 81A8177
	.incbin "baserom.gba", 0x1A8177, 0x2E

EventScript_1A81A5:: @ 81A81A5
	.incbin "baserom.gba", 0x1A81A5, 0x37

EventScript_1A81DC:: @ 81A81DC
	.incbin "baserom.gba", 0x1A81DC, 0x37

EventScript_1A8213:: @ 81A8213
	.incbin "baserom.gba", 0x1A8213, 0x2E

EventScript_1A8241:: @ 81A8241
	.incbin "baserom.gba", 0x1A8241, 0x2E

EventScript_1A826F:: @ 81A826F
	.incbin "baserom.gba", 0x1A826F, 0x37

EventScript_1A82A6:: @ 81A82A6
	.incbin "baserom.gba", 0x1A82A6, 0x37

EventScript_1A82DD:: @ 81A82DD
	.incbin "baserom.gba", 0x1A82DD, 0x37

EventScript_1A8314:: @ 81A8314
	.incbin "baserom.gba", 0x1A8314, 0x37

EventScript_1A834B:: @ 81A834B
	.incbin "baserom.gba", 0x1A834B, 0x2E

EventScript_1A8379:: @ 81A8379
	.incbin "baserom.gba", 0x1A8379, 0x2E

EventScript_1A83A7:: @ 81A83A7
	.incbin "baserom.gba", 0x1A83A7, 0x2E

EventScript_1A83D5:: @ 81A83D5
	.incbin "baserom.gba", 0x1A83D5, 0x37

EventScript_1A840C:: @ 81A840C
	.incbin "baserom.gba", 0x1A840C, 0x37

EventScript_1A8443:: @ 81A8443
	.incbin "baserom.gba", 0x1A8443, 0x37

EventScript_1A847A:: @ 81A847A
	.incbin "baserom.gba", 0x1A847A, 0x2E

EventScript_1A84A8:: @ 81A84A8
	.incbin "baserom.gba", 0x1A84A8, 0x2E

EventScript_1A84D6:: @ 81A84D6
	.incbin "baserom.gba", 0x1A84D6, 0x2E

EventScript_1A8504:: @ 81A8504
	.incbin "baserom.gba", 0x1A8504, 0x417

SilphCo_2F_EventScript_1A891B:: @ 81A891B
	.incbin "baserom.gba", 0x1A891B, 0x1A

SilphCo_2F_EventScript_1A8935:: @ 81A8935
	.incbin "baserom.gba", 0x1A8935, 0x1A

SilphCo_3F_EventScript_1A894F:: @ 81A894F
	.incbin "baserom.gba", 0x1A894F, 0x1A

SilphCo_3F_EventScript_1A8969:: @ 81A8969
	.incbin "baserom.gba", 0x1A8969, 0x1A

SilphCo_4F_EventScript_1A8983:: @ 81A8983
	.incbin "baserom.gba", 0x1A8983, 0x1A

SilphCo_4F_EventScript_1A899D:: @ 81A899D
	.incbin "baserom.gba", 0x1A899D, 0x1A

SilphCo_5F_EventScript_1A89B7:: @ 81A89B7
	.incbin "baserom.gba", 0x1A89B7, 0x1A

SilphCo_5F_EventScript_1A89D1:: @ 81A89D1
	.incbin "baserom.gba", 0x1A89D1, 0x1A

SilphCo_5F_EventScript_1A89EB:: @ 81A89EB
	.incbin "baserom.gba", 0x1A89EB, 0x1A

SilphCo_6F_EventScript_1A8A05:: @ 81A8A05
	.incbin "baserom.gba", 0x1A8A05, 0x1A

SilphCo_7F_EventScript_1A8A1F:: @ 81A8A1F
	.incbin "baserom.gba", 0x1A8A1F, 0x1A

SilphCo_7F_EventScript_1A8A39:: @ 81A8A39
	.incbin "baserom.gba", 0x1A8A39, 0x1A

SilphCo_7F_EventScript_1A8A53:: @ 81A8A53
	.incbin "baserom.gba", 0x1A8A53, 0x1A

SilphCo_8F_EventScript_1A8A6D:: @ 81A8A6D
	.incbin "baserom.gba", 0x1A8A6D, 0x1A

SilphCo_9F_EventScript_1A8A87:: @ 81A8A87
	.incbin "baserom.gba", 0x1A8A87, 0x1A

SilphCo_9F_EventScript_1A8AA1:: @ 81A8AA1
	.incbin "baserom.gba", 0x1A8AA1, 0x1A

SilphCo_9F_EventScript_1A8ABB:: @ 81A8ABB
	.incbin "baserom.gba", 0x1A8ABB, 0x1A

SilphCo_9F_EventScript_1A8AD5:: @ 81A8AD5
	.incbin "baserom.gba", 0x1A8AD5, 0x1A

SilphCo_10F_EventScript_1A8AEF:: @ 81A8AEF
	.incbin "baserom.gba", 0x1A8AEF, 0x1A

SilphCo_11F_EventScript_1A8B09:: @ 81A8B09
	.incbin "baserom.gba", 0x1A8B09, 0x11E

EventScript_1A8C27:: @ 81A8C27
	.incbin "baserom.gba", 0x1A8C27, 0xC

EventScript_1A8C33:: @ 81A8C33
	.incbin "baserom.gba", 0x1A8C33, 0x9

EventScript_1A8C3C:: @ 81A8C3C
	.incbin "baserom.gba", 0x1A8C3C, 0x71

EventScript_1A8CAD:: @ 81A8CAD
	.incbin "baserom.gba", 0x1A8CAD, 0x10

EventScript_1A8CBD:: @ 81A8CBD
	.incbin "baserom.gba", 0x1A8CBD, 0xC

EventScript_1A8CC9:: @ 81A8CC9
	.incbin "baserom.gba", 0x1A8CC9, 0x10

EventScript_1A8CD9:: @ 81A8CD9
	.incbin "baserom.gba", 0x1A8CD9, 0x14

gUnknown_81A8CED:: @ 81A8CED
	.incbin "baserom.gba", 0x1A8CED, 0x9

CeruleanCity_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
CinnabarIsland_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
FiveIsland_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
FuchsiaCity_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
OneIsland_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
PewterCity_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
SevenIsland_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
VermilionCity_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
FourIsland_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
SixIsland_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
ThreeIsland_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
TwoIsland_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
Route10_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
Route10_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
Route4_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
SaffronCity_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
IndigoPlateau_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
CeladonCity_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
LavenderTown_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
ViridianCity_PokemonCenter_2F_EventScript_1A8CF6:: @ 81A8CF6
	.incbin "baserom.gba", 0x1A8CF6, 0x6

CeruleanCity_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
CinnabarIsland_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
FiveIsland_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
FuchsiaCity_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
OneIsland_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
PewterCity_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
SevenIsland_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
VermilionCity_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
FourIsland_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
SixIsland_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
ThreeIsland_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
TwoIsland_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
Route10_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
Route10_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
Route4_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
SaffronCity_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
IndigoPlateau_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
CeladonCity_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
LavenderTown_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
ViridianCity_PokemonCenter_2F_EventScript_1A8CFC:: @ 81A8CFC
	.incbin "baserom.gba", 0x1A8CFC, 0x6

CeruleanCity_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
CinnabarIsland_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
FiveIsland_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
FuchsiaCity_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
OneIsland_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
PewterCity_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
SevenIsland_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
VermilionCity_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
FourIsland_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
SixIsland_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
ThreeIsland_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
TwoIsland_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
Route10_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
Route10_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
Route4_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
SaffronCity_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
IndigoPlateau_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
CeladonCity_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
LavenderTown_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
ViridianCity_PokemonCenter_2F_EventScript_1A8D02:: @ 81A8D02
	.incbin "baserom.gba", 0x1A8D02, 0x6

VermilionCity_PokemonCenter_1F_EventScript_1A8D08:: @ 81A8D08
	.incbin "baserom.gba", 0x1A8D08, 0x41

EventScript_ItemfinderDigUpUnderfootItem:: @ 81A8D49
	lockall
	textcolor 3
	waitse
	call EventScript_GiveItem
	compare_var_to_value VAR_0x8007, 1
	goto_if_eq EventScript_DigUpItemPutInPocket
	compare_var_to_value VAR_0x8007, 0
	goto_if_eq EventScript_DigUpItemBagIsFull
	end

EventScript_DigUpItemPutInPocket::
	message Text_1A5700
	waitfanfare
	waitmessage
	delay 60
	msgbox gUnknown_81A5218
	special Special_SetHiddenItemFlag
	releaseall
	end

EventScript_DigUpItemBagIsFull::
	msgbox Text_1A5700
	msgbox gUnknown_81A5242
	setvar VAR_RESULT, 0
	releaseall
	end

gUnknown_81A8D97:: @ 81A8D97
	.incbin "baserom.gba", 0x1A8D97, 0x41

gUnknown_81A8DD8:: @ 81A8DD8
	.incbin "baserom.gba", 0x1A8DD8, 0x25

gUnknown_81A8DFD:: @ 81A8DFD
	.incbin "baserom.gba", 0x1A8DFD, 0x5B

gStdScript_8:: @ 81A8E58
	.incbin "baserom.gba", 0x1A8E58, 0x6D

EventScript_1A8EC5:: @ 81A8EC5
	.incbin "baserom.gba", 0x1A8EC5, 0x8F

EventScript_1A8F54:: @ 81A8F54
	.incbin "baserom.gba", 0x1A8F54, 0x9A

EventScript_1A8FEE:: @ 81A8FEE
	.incbin "baserom.gba", 0x1A8FEE, 0xB

EventScript_1A8FF9:: @ 81A8FF9
	.incbin "baserom.gba", 0x1A8FF9, 0xB

EventScript_1A9004:: @ 81A9004
	.incbin "baserom.gba", 0x1A9004, 0xB

EventScript_1A900F:: @ 81A900F
	.incbin "baserom.gba", 0x1A900F, 0xCB

EventScript_1A90DA:: @ 81A90DA
	.incbin "baserom.gba", 0x1A90DA, 0x1C

EventScript_1A90F6:: @ 81A90F6
	.incbin "baserom.gba", 0x1A90F6, 0x12

EventScript_1A9108:: @ 81A9108
	.incbin "baserom.gba", 0x1A9108, 0x16

EventScript_1A911E:: @ 81A911E
	.incbin "baserom.gba", 0x1A911E, 0xB7

EventScript_1A91D5:: @ 81A91D5
	.incbin "baserom.gba", 0x1A91D5, 0x58

EventScript_1A922D:: @ 81A922D
	.incbin "baserom.gba", 0x1A922D, 0x9

EventScript_1A9236:: @ 81A9236
	.incbin "baserom.gba", 0x1A9236, 0x15

EventScript_1A924B:: @ 81A924B
	.incbin "baserom.gba", 0x1A924B, 0x13

EventScript_1A925E:: @ 81A925E
	.incbin "baserom.gba", 0x1A925E, 0xE

EventScript_1A926C:: @ 81A926C
	.incbin "baserom.gba", 0x1A926C, 0x10

EventScript_1A927C:: @ 81A927C
	.incbin "baserom.gba", 0x1A927C, 0xC

gUnknown_81A9288:: @ 81A9288
	.incbin "baserom.gba", 0x1A9288, 0x3

gUnknown_81A928B:: @ 81A928B
	.incbin "baserom.gba", 0x1A928B, 0x5

gUnknown_81A9290:: @ 81A9290
	.incbin "baserom.gba", 0x1A9290, 0x6

gUnknown_81A9296:: @ 81A9296
	.incbin "baserom.gba", 0x1A9296, 0x5

gUnknown_81A929B:: @ 81A929B
	.incbin "baserom.gba", 0x1A929B, 0x4

gUnknown_81A929F:: @ 81A929F
	.incbin "baserom.gba", 0x1A929F, 0x4

gUnknown_81A92A3:: @ 81A92A3
	.incbin "baserom.gba", 0x1A92A3, 0x4

gUnknown_81A92A7:: @ 81A92A7
	.incbin "baserom.gba", 0x1A92A7, 0x4

gUnknown_81A92AB:: @ 81A92AB
	.incbin "baserom.gba", 0x1A92AB, 0x4

gUnknown_81A92AF:: @ 81A92AF
	.incbin "baserom.gba", 0x1A92AF, 0x4

gUnknown_81A92B3:: @ 81A92B3
	.incbin "baserom.gba", 0x1A92B3, 0x4

gUnknown_81A92B7:: @ 81A92B7
	.incbin "baserom.gba", 0x1A92B7, 0x5

gUnknown_81A92BC:: @ 81A92BC
	.incbin "baserom.gba", 0x1A92BC, 0x5

gUnknown_81A92C1:: @ 81A92C1
	.incbin "baserom.gba", 0x1A92C1, 0x2

gUnknown_81A92C3:: @ 81A92C3
	.incbin "baserom.gba", 0x1A92C3, 0x2

gUnknown_81A92C5:: @ 81A92C5
	.incbin "baserom.gba", 0x1A92C5, 0xB

gUnknown_81A92D0:: @ 81A92D0
	.incbin "baserom.gba", 0x1A92D0, 0xC

gUnknown_81A92DC:: @ 81A92DC
	.incbin "baserom.gba", 0x1A92DC, 0xA

gUnknown_81A92E6:: @ 81A92E6
	.incbin "baserom.gba", 0x1A92E6, 0xC

gUnknown_81A92F2:: @ 81A92F2
	.incbin "baserom.gba", 0x1A92F2, 0xC

gUnknown_81A92FE:: @ 81A92FE
	.incbin "baserom.gba", 0x1A92FE, 0xC

gUnknown_81A930A:: @ 81A930A
	.incbin "baserom.gba", 0x1A930A, 0xC

gUnknown_81A9316:: @ 81A9316
	.incbin "baserom.gba", 0x1A9316, 0xB

gUnknown_81A9321:: @ 81A9321
	.incbin "baserom.gba", 0x1A9321, 0xC

gUnknown_81A932D:: @ 81A932D
	.incbin "baserom.gba", 0x1A932D, 0xB

gUnknown_81A9338:: @ 81A9338
	.incbin "baserom.gba", 0x1A9338, 0x7

gUnknown_81A933F:: @ 81A933F
	.incbin "baserom.gba", 0x1A933F, 0xB

gUnknown_81A934A:: @ 81A934A
	.incbin "baserom.gba", 0x1A934A, 0xC

gUnknown_81A9356:: @ 81A9356
	.incbin "baserom.gba", 0x1A9356, 0xC

gUnknown_81A9362:: @ 81A9362
	.incbin "baserom.gba", 0x1A9362, 0x6

gUnknown_81A9368:: @ 81A9368
	.incbin "baserom.gba", 0x1A9368, 0xC

gUnknown_81A9374:: @ 81A9374
	.incbin "baserom.gba", 0x1A9374, 0x8

gUnknown_81A937C:: @ 81A937C
	.incbin "baserom.gba", 0x1A937C, 0xB

gUnknown_81A9387:: @ 81A9387
	.incbin "baserom.gba", 0x1A9387, 0xC

gUnknown_81A9393:: @ 81A9393
	.incbin "baserom.gba", 0x1A9393, 0xC

gUnknown_81A939F:: @ 81A939F
	.incbin "baserom.gba", 0x1A939F, 0xC

gUnknown_81A93AB:: @ 81A93AB
	.incbin "baserom.gba", 0x1A93AB, 0x9

gUnknown_81A93B4:: @ 81A93B4
	.incbin "baserom.gba", 0x1A93B4, 0xC

gUnknown_81A93C0:: @ 81A93C0
	.incbin "baserom.gba", 0x1A93C0, 0x9

Route3_EventScript_1A93C9:: @ 81A93C9
	.incbin "baserom.gba", 0x1A93C9, 0x3E

Route3_EventScript_1A9407:: @ 81A9407
	.incbin "baserom.gba", 0x1A9407, 0x3E

Route3_EventScript_1A9445:: @ 81A9445
	.incbin "baserom.gba", 0x1A9445, 0x3E

Route3_EventScript_1A9483:: @ 81A9483
	.incbin "baserom.gba", 0x1A9483, 0x3E

Route3_EventScript_1A94C1:: @ 81A94C1
	.incbin "baserom.gba", 0x1A94C1, 0x3E

Route3_EventScript_1A94FF:: @ 81A94FF
	.incbin "baserom.gba", 0x1A94FF, 0x3E

Route3_EventScript_1A953D:: @ 81A953D
	.incbin "baserom.gba", 0x1A953D, 0x3E

Route3_EventScript_1A957B:: @ 81A957B
	.incbin "baserom.gba", 0x1A957B, 0x3E

Route4_EventScript_1A95B9:: @ 81A95B9
	.incbin "baserom.gba", 0x1A95B9, 0x3E

Route24_EventScript_1A95F7:: @ 81A95F7
	.incbin "baserom.gba", 0x1A95F7, 0x3E

Route24_EventScript_1A9635:: @ 81A9635
	.incbin "baserom.gba", 0x1A9635, 0x3E

Route24_EventScript_1A9673:: @ 81A9673
	.incbin "baserom.gba", 0x1A9673, 0x3E

Route24_EventScript_1A96B1:: @ 81A96B1
	.incbin "baserom.gba", 0x1A96B1, 0x3E

Route24_EventScript_1A96EF:: @ 81A96EF
	.incbin "baserom.gba", 0x1A96EF, 0x3E

Route24_EventScript_1A972D:: @ 81A972D
	.incbin "baserom.gba", 0x1A972D, 0x3E

Route25_EventScript_1A976B:: @ 81A976B
	.incbin "baserom.gba", 0x1A976B, 0x3E

Route25_EventScript_1A97A9:: @ 81A97A9
	.incbin "baserom.gba", 0x1A97A9, 0x3E

Route25_EventScript_1A97E7:: @ 81A97E7
	.incbin "baserom.gba", 0x1A97E7, 0x3E

Route25_EventScript_1A9825:: @ 81A9825
	.incbin "baserom.gba", 0x1A9825, 0x3E

Route25_EventScript_1A9863:: @ 81A9863
	.incbin "baserom.gba", 0x1A9863, 0x3E

Route25_EventScript_1A98A1:: @ 81A98A1
	.incbin "baserom.gba", 0x1A98A1, 0x3E

Route25_EventScript_1A98DF:: @ 81A98DF
	.incbin "baserom.gba", 0x1A98DF, 0x3E

Route25_EventScript_1A991D:: @ 81A991D
	.incbin "baserom.gba", 0x1A991D, 0x3E

Route25_EventScript_1A995B:: @ 81A995B
	.incbin "baserom.gba", 0x1A995B, 0x3E

Route6_EventScript_1A9999:: @ 81A9999
	.incbin "baserom.gba", 0x1A9999, 0x3E

Route6_EventScript_1A99D7:: @ 81A99D7
	.incbin "baserom.gba", 0x1A99D7, 0x3E

Route6_EventScript_1A9A15:: @ 81A9A15
	.incbin "baserom.gba", 0x1A9A15, 0x3E

Route6_EventScript_1A9A53:: @ 81A9A53
	.incbin "baserom.gba", 0x1A9A53, 0x3E

Route6_EventScript_1A9A91:: @ 81A9A91
	.incbin "baserom.gba", 0x1A9A91, 0x3E

Route6_EventScript_1A9ACF:: @ 81A9ACF
	.incbin "baserom.gba", 0x1A9ACF, 0x3E

Route11_EventScript_1A9B0D:: @ 81A9B0D
	.incbin "baserom.gba", 0x1A9B0D, 0x3E

Route11_EventScript_1A9B4B:: @ 81A9B4B
	.incbin "baserom.gba", 0x1A9B4B, 0x3E

Route11_EventScript_1A9B89:: @ 81A9B89
	.incbin "baserom.gba", 0x1A9B89, 0x3E

Route11_EventScript_1A9BC7:: @ 81A9BC7
	.incbin "baserom.gba", 0x1A9BC7, 0x3E

Route11_EventScript_1A9C05:: @ 81A9C05
	.incbin "baserom.gba", 0x1A9C05, 0x3E

Route11_EventScript_1A9C43:: @ 81A9C43
	.incbin "baserom.gba", 0x1A9C43, 0x3E

Route11_EventScript_1A9C81:: @ 81A9C81
	.incbin "baserom.gba", 0x1A9C81, 0x3E

Route11_EventScript_1A9CBF:: @ 81A9CBF
	.incbin "baserom.gba", 0x1A9CBF, 0x3E

Route11_EventScript_1A9CFD:: @ 81A9CFD
	.incbin "baserom.gba", 0x1A9CFD, 0x3E

Route11_EventScript_1A9D3B:: @ 81A9D3B
	.incbin "baserom.gba", 0x1A9D3B, 0x3E

Route9_EventScript_1A9D79:: @ 81A9D79
	.incbin "baserom.gba", 0x1A9D79, 0x3E

Route9_EventScript_1A9DB7:: @ 81A9DB7
	.incbin "baserom.gba", 0x1A9DB7, 0x3E

Route9_EventScript_1A9DF5:: @ 81A9DF5
	.incbin "baserom.gba", 0x1A9DF5, 0x3E

Route9_EventScript_1A9E33:: @ 81A9E33
	.incbin "baserom.gba", 0x1A9E33, 0x3E

Route9_EventScript_1A9E71:: @ 81A9E71
	.incbin "baserom.gba", 0x1A9E71, 0x3E

Route9_EventScript_1A9EAF:: @ 81A9EAF
	.incbin "baserom.gba", 0x1A9EAF, 0x3E

Route9_EventScript_1A9EED:: @ 81A9EED
	.incbin "baserom.gba", 0x1A9EED, 0x3E

Route9_EventScript_1A9F2B:: @ 81A9F2B
	.incbin "baserom.gba", 0x1A9F2B, 0x3E

Route9_EventScript_1A9F69:: @ 81A9F69
	.incbin "baserom.gba", 0x1A9F69, 0x3E

Route10_EventScript_1A9FA7:: @ 81A9FA7
	.incbin "baserom.gba", 0x1A9FA7, 0x3E

Route10_EventScript_1A9FE5:: @ 81A9FE5
	.incbin "baserom.gba", 0x1A9FE5, 0x3E

Route10_EventScript_1AA023:: @ 81AA023
	.incbin "baserom.gba", 0x1AA023, 0x3E

Route10_EventScript_1AA061:: @ 81AA061
	.incbin "baserom.gba", 0x1AA061, 0x3E

Route10_EventScript_1AA09F:: @ 81AA09F
	.incbin "baserom.gba", 0x1AA09F, 0x3E

Route10_EventScript_1AA0DD:: @ 81AA0DD
	.incbin "baserom.gba", 0x1AA0DD, 0x3E

Route8_EventScript_1AA11B:: @ 81AA11B
	.incbin "baserom.gba", 0x1AA11B, 0x3E

Route8_EventScript_1AA159:: @ 81AA159
	.incbin "baserom.gba", 0x1AA159, 0x3E

Route8_EventScript_1AA197:: @ 81AA197
	.incbin "baserom.gba", 0x1AA197, 0x3E

Route8_EventScript_1AA1D5:: @ 81AA1D5
	.incbin "baserom.gba", 0x1AA1D5, 0x3E

Route8_EventScript_1AA213:: @ 81AA213
	.incbin "baserom.gba", 0x1AA213, 0x3E

Route8_EventScript_1AA251:: @ 81AA251
	.incbin "baserom.gba", 0x1AA251, 0x3E

Route8_EventScript_1AA28F:: @ 81AA28F
	.incbin "baserom.gba", 0x1AA28F, 0x3E

Route8_EventScript_1AA2CD:: @ 81AA2CD
	.incbin "baserom.gba", 0x1AA2CD, 0x3E

Route8_EventScript_1AA30B:: @ 81AA30B
	.incbin "baserom.gba", 0x1AA30B, 0x3E

Route8_EventScript_1AA349:: @ 81AA349
	.incbin "baserom.gba", 0x1AA349, 0x46

Route8_EventScript_1AA38F:: @ 81AA38F
	.incbin "baserom.gba", 0x1AA38F, 0x46

Route8_EventScript_1AA3D5:: @ 81AA3D5
	.incbin "baserom.gba", 0x1AA3D5, 0x3E

Route8_EventScript_1AA413:: @ 81AA413
	.incbin "baserom.gba", 0x1AA413, 0x3E

Route12_EventScript_1AA451:: @ 81AA451
	.incbin "baserom.gba", 0x1AA451, 0x3E

Route12_EventScript_1AA48F:: @ 81AA48F
	.incbin "baserom.gba", 0x1AA48F, 0x3E

Route12_EventScript_1AA4CD:: @ 81AA4CD
	.incbin "baserom.gba", 0x1AA4CD, 0x3E

Route12_EventScript_1AA50B:: @ 81AA50B
	.incbin "baserom.gba", 0x1AA50B, 0x3E

Route12_EventScript_1AA549:: @ 81AA549
	.incbin "baserom.gba", 0x1AA549, 0x3E

Route12_EventScript_1AA587:: @ 81AA587
	.incbin "baserom.gba", 0x1AA587, 0x3E

Route12_EventScript_1AA5C5:: @ 81AA5C5
	.incbin "baserom.gba", 0x1AA5C5, 0x3E

Route12_EventScript_1AA603:: @ 81AA603
	.incbin "baserom.gba", 0x1AA603, 0x46

Route12_EventScript_1AA649:: @ 81AA649
	.incbin "baserom.gba", 0x1AA649, 0x46

Route13_EventScript_1AA68F:: @ 81AA68F
	.incbin "baserom.gba", 0x1AA68F, 0x3E

Route13_EventScript_1AA6CD:: @ 81AA6CD
	.incbin "baserom.gba", 0x1AA6CD, 0x3E

Route13_EventScript_1AA70B:: @ 81AA70B
	.incbin "baserom.gba", 0x1AA70B, 0x3E

Route13_EventScript_1AA749:: @ 81AA749
	.incbin "baserom.gba", 0x1AA749, 0x3E

Route13_EventScript_1AA787:: @ 81AA787
	.incbin "baserom.gba", 0x1AA787, 0x3E

Route13_EventScript_1AA7C5:: @ 81AA7C5
	.incbin "baserom.gba", 0x1AA7C5, 0x3E

Route13_EventScript_1AA803:: @ 81AA803
	.incbin "baserom.gba", 0x1AA803, 0x3E

Route13_EventScript_1AA841:: @ 81AA841
	.incbin "baserom.gba", 0x1AA841, 0x3E

Route13_EventScript_1AA87F:: @ 81AA87F
	.incbin "baserom.gba", 0x1AA87F, 0x3E

Route13_EventScript_1AA8BD:: @ 81AA8BD
	.incbin "baserom.gba", 0x1AA8BD, 0x3E

Route14_EventScript_1AA8FB:: @ 81AA8FB
	.incbin "baserom.gba", 0x1AA8FB, 0x3E

Route14_EventScript_1AA939:: @ 81AA939
	.incbin "baserom.gba", 0x1AA939, 0x3E

Route14_EventScript_1AA977:: @ 81AA977
	.incbin "baserom.gba", 0x1AA977, 0x3E

Route14_EventScript_1AA9B5:: @ 81AA9B5
	.incbin "baserom.gba", 0x1AA9B5, 0x3E

Route14_EventScript_1AA9F3:: @ 81AA9F3
	.incbin "baserom.gba", 0x1AA9F3, 0x3E

Route14_EventScript_1AAA31:: @ 81AAA31
	.incbin "baserom.gba", 0x1AAA31, 0x3E

Route14_EventScript_1AAA6F:: @ 81AAA6F
	.incbin "baserom.gba", 0x1AAA6F, 0x3E

Route14_EventScript_1AAAAD:: @ 81AAAAD
	.incbin "baserom.gba", 0x1AAAAD, 0x3E

Route14_EventScript_1AAAEB:: @ 81AAAEB
	.incbin "baserom.gba", 0x1AAAEB, 0x3E

Route14_EventScript_1AAB29:: @ 81AAB29
	.incbin "baserom.gba", 0x1AAB29, 0x3E

Route14_EventScript_1AAB67:: @ 81AAB67
	.incbin "baserom.gba", 0x1AAB67, 0x46

Route14_EventScript_1AABAD:: @ 81AABAD
	.incbin "baserom.gba", 0x1AABAD, 0x46

Route15_EventScript_1AABF3:: @ 81AABF3
	.incbin "baserom.gba", 0x1AABF3, 0x3E

Route15_EventScript_1AAC31:: @ 81AAC31
	.incbin "baserom.gba", 0x1AAC31, 0x3E

Route15_EventScript_1AAC6F:: @ 81AAC6F
	.incbin "baserom.gba", 0x1AAC6F, 0x3E

Route15_EventScript_1AACAD:: @ 81AACAD
	.incbin "baserom.gba", 0x1AACAD, 0x3E

Route15_EventScript_1AACEB:: @ 81AACEB
	.incbin "baserom.gba", 0x1AACEB, 0x3E

Route15_EventScript_1AAD29:: @ 81AAD29
	.incbin "baserom.gba", 0x1AAD29, 0x3E

Route15_EventScript_1AAD67:: @ 81AAD67
	.incbin "baserom.gba", 0x1AAD67, 0x3E

Route15_EventScript_1AADA5:: @ 81AADA5
	.incbin "baserom.gba", 0x1AADA5, 0x3E

Route15_EventScript_1AADE3:: @ 81AADE3
	.incbin "baserom.gba", 0x1AADE3, 0x3E

Route15_EventScript_1AAE21:: @ 81AAE21
	.incbin "baserom.gba", 0x1AAE21, 0x3E

Route15_EventScript_1AAE5F:: @ 81AAE5F
	.incbin "baserom.gba", 0x1AAE5F, 0x46

Route15_EventScript_1AAEA5:: @ 81AAEA5
	.incbin "baserom.gba", 0x1AAEA5, 0x46

Route16_EventScript_1AAEEB:: @ 81AAEEB
	.incbin "baserom.gba", 0x1AAEEB, 0x3E

Route16_EventScript_1AAF29:: @ 81AAF29
	.incbin "baserom.gba", 0x1AAF29, 0x3E

Route16_EventScript_1AAF67:: @ 81AAF67
	.incbin "baserom.gba", 0x1AAF67, 0x3E

Route16_EventScript_1AAFA5:: @ 81AAFA5
	.incbin "baserom.gba", 0x1AAFA5, 0x3E

Route16_EventScript_1AAFE3:: @ 81AAFE3
	.incbin "baserom.gba", 0x1AAFE3, 0x3E

Route16_EventScript_1AB021:: @ 81AB021
	.incbin "baserom.gba", 0x1AB021, 0x3E

Route16_EventScript_1AB05F:: @ 81AB05F
	.incbin "baserom.gba", 0x1AB05F, 0x46

Route16_EventScript_1AB0A5:: @ 81AB0A5
	.incbin "baserom.gba", 0x1AB0A5, 0x46

Route17_EventScript_1AB0EB:: @ 81AB0EB
	.incbin "baserom.gba", 0x1AB0EB, 0x3E

Route17_EventScript_1AB129:: @ 81AB129
	.incbin "baserom.gba", 0x1AB129, 0x3E

Route17_EventScript_1AB167:: @ 81AB167
	.incbin "baserom.gba", 0x1AB167, 0x3E

Route17_EventScript_1AB1A5:: @ 81AB1A5
	.incbin "baserom.gba", 0x1AB1A5, 0x3E

Route17_EventScript_1AB1E3:: @ 81AB1E3
	.incbin "baserom.gba", 0x1AB1E3, 0x3E

Route17_EventScript_1AB221:: @ 81AB221
	.incbin "baserom.gba", 0x1AB221, 0x3E

Route17_EventScript_1AB25F:: @ 81AB25F
	.incbin "baserom.gba", 0x1AB25F, 0x3E

Route17_EventScript_1AB29D:: @ 81AB29D
	.incbin "baserom.gba", 0x1AB29D, 0x3E

Route17_EventScript_1AB2DB:: @ 81AB2DB
	.incbin "baserom.gba", 0x1AB2DB, 0x3E

Route17_EventScript_1AB319:: @ 81AB319
	.incbin "baserom.gba", 0x1AB319, 0x3E

Route18_EventScript_1AB357:: @ 81AB357
	.incbin "baserom.gba", 0x1AB357, 0x3E

Route18_EventScript_1AB395:: @ 81AB395
	.incbin "baserom.gba", 0x1AB395, 0x3E

Route18_EventScript_1AB3D3:: @ 81AB3D3
	.incbin "baserom.gba", 0x1AB3D3, 0x3E

Route19_EventScript_1AB411:: @ 81AB411
	.incbin "baserom.gba", 0x1AB411, 0x3E

Route19_EventScript_1AB44F:: @ 81AB44F
	.incbin "baserom.gba", 0x1AB44F, 0x3E

Route19_EventScript_1AB48D:: @ 81AB48D
	.incbin "baserom.gba", 0x1AB48D, 0x3E

Route19_EventScript_1AB4CB:: @ 81AB4CB
	.incbin "baserom.gba", 0x1AB4CB, 0x3E

Route19_EventScript_1AB509:: @ 81AB509
	.incbin "baserom.gba", 0x1AB509, 0x3E

Route19_EventScript_1AB547:: @ 81AB547
	.incbin "baserom.gba", 0x1AB547, 0x3E

Route19_EventScript_1AB585:: @ 81AB585
	.incbin "baserom.gba", 0x1AB585, 0x3E

Route19_EventScript_1AB5C3:: @ 81AB5C3
	.incbin "baserom.gba", 0x1AB5C3, 0x3E

Route19_EventScript_1AB601:: @ 81AB601
	.incbin "baserom.gba", 0x1AB601, 0x3E

Route19_EventScript_1AB63F:: @ 81AB63F
	.incbin "baserom.gba", 0x1AB63F, 0x3E

Route19_EventScript_1AB67D:: @ 81AB67D
	.incbin "baserom.gba", 0x1AB67D, 0x46

Route19_EventScript_1AB6C3:: @ 81AB6C3
	.incbin "baserom.gba", 0x1AB6C3, 0x46

Route20_EventScript_1AB709:: @ 81AB709
	.incbin "baserom.gba", 0x1AB709, 0x3E

Route20_EventScript_1AB747:: @ 81AB747
	.incbin "baserom.gba", 0x1AB747, 0x3E

Route20_EventScript_1AB785:: @ 81AB785
	.incbin "baserom.gba", 0x1AB785, 0x3E

Route20_EventScript_1AB7C3:: @ 81AB7C3
	.incbin "baserom.gba", 0x1AB7C3, 0x3E

Route20_EventScript_1AB801:: @ 81AB801
	.incbin "baserom.gba", 0x1AB801, 0x3E

Route20_EventScript_1AB83F:: @ 81AB83F
	.incbin "baserom.gba", 0x1AB83F, 0x3E

Route20_EventScript_1AB87D:: @ 81AB87D
	.incbin "baserom.gba", 0x1AB87D, 0x3E

Route20_EventScript_1AB8BB:: @ 81AB8BB
	.incbin "baserom.gba", 0x1AB8BB, 0x3E

Route20_EventScript_1AB8F9:: @ 81AB8F9
	.incbin "baserom.gba", 0x1AB8F9, 0x3E

Route20_EventScript_1AB937:: @ 81AB937
	.incbin "baserom.gba", 0x1AB937, 0x3E

Route21_North_EventScript_1AB975:: @ 81AB975
	.incbin "baserom.gba", 0x1AB975, 0x3E

Route21_South_EventScript_1AB9B3:: @ 81AB9B3
	.incbin "baserom.gba", 0x1AB9B3, 0x3E

Route21_North_EventScript_1AB9F1:: @ 81AB9F1
	.incbin "baserom.gba", 0x1AB9F1, 0x3E

Route21_South_EventScript_1ABA2F:: @ 81ABA2F
	.incbin "baserom.gba", 0x1ABA2F, 0x3E

Route21_North_EventScript_1ABA6D:: @ 81ABA6D
	.incbin "baserom.gba", 0x1ABA6D, 0x3E

Route21_South_EventScript_1ABAAB:: @ 81ABAAB
	.incbin "baserom.gba", 0x1ABAAB, 0x3E

Route21_South_EventScript_1ABAE9:: @ 81ABAE9
	.incbin "baserom.gba", 0x1ABAE9, 0x3E

Route21_South_EventScript_1ABB27:: @ 81ABB27
	.incbin "baserom.gba", 0x1ABB27, 0x3E

Route21_North_EventScript_1ABB65:: @ 81ABB65
	.incbin "baserom.gba", 0x1ABB65, 0x46

Route21_North_EventScript_1ABBAB:: @ 81ABBAB
	.incbin "baserom.gba", 0x1ABBAB, 0x46

OneIsland_KindleRoad_EventScript_1ABBF1:: @ 81ABBF1
	.incbin "baserom.gba", 0x1ABBF1, 0x3E

OneIsland_KindleRoad_EventScript_1ABC2F:: @ 81ABC2F
	.incbin "baserom.gba", 0x1ABC2F, 0x3E

OneIsland_KindleRoad_EventScript_1ABC6D:: @ 81ABC6D
	.incbin "baserom.gba", 0x1ABC6D, 0x3E

OneIsland_KindleRoad_EventScript_1ABCAB:: @ 81ABCAB
	.incbin "baserom.gba", 0x1ABCAB, 0x3E

OneIsland_KindleRoad_EventScript_1ABCE9:: @ 81ABCE9
	.incbin "baserom.gba", 0x1ABCE9, 0x3E

OneIsland_KindleRoad_EventScript_1ABD27:: @ 81ABD27
	.incbin "baserom.gba", 0x1ABD27, 0x3E

OneIsland_KindleRoad_EventScript_1ABD65:: @ 81ABD65
	.incbin "baserom.gba", 0x1ABD65, 0x3E

OneIsland_KindleRoad_EventScript_1ABDA3:: @ 81ABDA3
	.incbin "baserom.gba", 0x1ABDA3, 0x3E

OneIsland_KindleRoad_EventScript_1ABDE1:: @ 81ABDE1
	.incbin "baserom.gba", 0x1ABDE1, 0x3E

OneIsland_KindleRoad_EventScript_1ABE1F:: @ 81ABE1F
	.incbin "baserom.gba", 0x1ABE1F, 0x3E

OneIsland_KindleRoad_EventScript_1ABE5D:: @ 81ABE5D
	.incbin "baserom.gba", 0x1ABE5D, 0x3E

OneIsland_KindleRoad_EventScript_1ABE9B:: @ 81ABE9B
	.incbin "baserom.gba", 0x1ABE9B, 0x46

OneIsland_KindleRoad_EventScript_1ABEE1:: @ 81ABEE1
	.incbin "baserom.gba", 0x1ABEE1, 0x46

OneIsland_TreasureBeach_EventScript_1ABF27:: @ 81ABF27
	.incbin "baserom.gba", 0x1ABF27, 0x3E

ThreeIsland_BondBridge_EventScript_1ABF65:: @ 81ABF65
	.incbin "baserom.gba", 0x1ABF65, 0x3E

ThreeIsland_BondBridge_EventScript_1ABFA3:: @ 81ABFA3
	.incbin "baserom.gba", 0x1ABFA3, 0x3E

ThreeIsland_BondBridge_EventScript_1ABFE1:: @ 81ABFE1
	.incbin "baserom.gba", 0x1ABFE1, 0x3E

ThreeIsland_BondBridge_EventScript_1AC01F:: @ 81AC01F
	.incbin "baserom.gba", 0x1AC01F, 0x3E

ThreeIsland_BondBridge_EventScript_1AC05D:: @ 81AC05D
	.incbin "baserom.gba", 0x1AC05D, 0x3E

ThreeIsland_BondBridge_EventScript_1AC09B:: @ 81AC09B
	.incbin "baserom.gba", 0x1AC09B, 0x46

ThreeIsland_BondBridge_EventScript_1AC0E1:: @ 81AC0E1
	.incbin "baserom.gba", 0x1AC0E1, 0x46

FiveIsland_ResortGorgeous_EventScript_1AC127:: @ 81AC127
	.incbin "baserom.gba", 0x1AC127, 0x3E

FiveIsland_ResortGorgeous_EventScript_1AC165:: @ 81AC165
	.incbin "baserom.gba", 0x1AC165, 0x3E

FiveIsland_ResortGorgeous_EventScript_1AC1A3:: @ 81AC1A3
	.incbin "baserom.gba", 0x1AC1A3, 0x3E

FiveIsland_ResortGorgeous_EventScript_1AC1E1:: @ 81AC1E1
	.incbin "baserom.gba", 0x1AC1E1, 0x3E

FiveIsland_ResortGorgeous_EventScript_1AC21F:: @ 81AC21F
	.incbin "baserom.gba", 0x1AC21F, 0x3E

FiveIsland_ResortGorgeous_EventScript_1AC25D:: @ 81AC25D
	.incbin "baserom.gba", 0x1AC25D, 0x3E

FiveIsland_ResortGorgeous_EventScript_1AC29B:: @ 81AC29B
	.incbin "baserom.gba", 0x1AC29B, 0x3E

FiveIsland_WaterLabyrinth_EventScript_1AC2D9:: @ 81AC2D9
	.incbin "baserom.gba", 0x1AC2D9, 0x3E

FiveIsland_MemorialPillar_EventScript_1AC317:: @ 81AC317
	.incbin "baserom.gba", 0x1AC317, 0x3E

FiveIsland_MemorialPillar_EventScript_1AC355:: @ 81AC355
	.incbin "baserom.gba", 0x1AC355, 0x3E

FiveIsland_MemorialPillar_EventScript_1AC393:: @ 81AC393
	.incbin "baserom.gba", 0x1AC393, 0x3E

SixIsland_OutcastIsland_EventScript_1AC3D1:: @ 81AC3D1
	.incbin "baserom.gba", 0x1AC3D1, 0x3E

SixIsland_OutcastIsland_EventScript_1AC40F:: @ 81AC40F
	.incbin "baserom.gba", 0x1AC40F, 0x3E

SixIsland_OutcastIsland_EventScript_1AC44D:: @ 81AC44D
	.incbin "baserom.gba", 0x1AC44D, 0x3E

SixIsland_OutcastIsland_EventScript_1AC48B:: @ 81AC48B
	.incbin "baserom.gba", 0x1AC48B, 0x46

SixIsland_OutcastIsland_EventScript_1AC4D1:: @ 81AC4D1
	.incbin "baserom.gba", 0x1AC4D1, 0x46

SixIsland_GreenPath_EventScript_1AC517:: @ 81AC517
	.incbin "baserom.gba", 0x1AC517, 0x3E

SixIsland_WaterPath_EventScript_1AC555:: @ 81AC555
	.incbin "baserom.gba", 0x1AC555, 0x3E

SixIsland_WaterPath_EventScript_1AC593:: @ 81AC593
	.incbin "baserom.gba", 0x1AC593, 0x3E

SixIsland_WaterPath_EventScript_1AC5D1:: @ 81AC5D1
	.incbin "baserom.gba", 0x1AC5D1, 0x3E

SixIsland_WaterPath_EventScript_1AC60F:: @ 81AC60F
	.incbin "baserom.gba", 0x1AC60F, 0x3E

SixIsland_WaterPath_EventScript_1AC64D:: @ 81AC64D
	.incbin "baserom.gba", 0x1AC64D, 0x46

SixIsland_WaterPath_EventScript_1AC693:: @ 81AC693
	.incbin "baserom.gba", 0x1AC693, 0x46

SixIsland_WaterPath_EventScript_1AC6D9:: @ 81AC6D9
	.incbin "baserom.gba", 0x1AC6D9, 0x3E

SixIsland_RuinValley_EventScript_1AC717:: @ 81AC717
	.incbin "baserom.gba", 0x1AC717, 0x3E

SixIsland_RuinValley_EventScript_1AC755:: @ 81AC755
	.incbin "baserom.gba", 0x1AC755, 0x3E

SixIsland_RuinValley_EventScript_1AC793:: @ 81AC793
	.incbin "baserom.gba", 0x1AC793, 0x3E

SixIsland_RuinValley_EventScript_1AC7D1:: @ 81AC7D1
	.incbin "baserom.gba", 0x1AC7D1, 0x3E

SixIsland_RuinValley_EventScript_1AC80F:: @ 81AC80F
	.incbin "baserom.gba", 0x1AC80F, 0x3E

SevenIsland_TrainerTower_EventScript_1AC84D:: @ 81AC84D
	.incbin "baserom.gba", 0x1AC84D, 0x3E

SevenIsland_TrainerTower_EventScript_1AC88B:: @ 81AC88B
	.incbin "baserom.gba", 0x1AC88B, 0x3E

SevenIsland_SevaultCanyon_Entrance_EventScript_1AC8C9:: @ 81AC8C9
	.incbin "baserom.gba", 0x1AC8C9, 0x3E

SevenIsland_SevaultCanyon_Entrance_EventScript_1AC907:: @ 81AC907
	.incbin "baserom.gba", 0x1AC907, 0x46

SevenIsland_SevaultCanyon_Entrance_EventScript_1AC94D:: @ 81AC94D
	.incbin "baserom.gba", 0x1AC94D, 0x46

SevenIsland_SevaultCanyon_Entrance_EventScript_1AC993:: @ 81AC993
	.incbin "baserom.gba", 0x1AC993, 0x3E

SevenIsland_SevaultCanyon_Entrance_EventScript_1AC9D1:: @ 81AC9D1
	.incbin "baserom.gba", 0x1AC9D1, 0x3E

SevenIsland_SevaultCanyon_Entrance_EventScript_1ACA0F:: @ 81ACA0F
	.incbin "baserom.gba", 0x1ACA0F, 0x3E

SevenIsland_SevaultCanyon_EventScript_1ACA4D:: @ 81ACA4D
	.incbin "baserom.gba", 0x1ACA4D, 0x3E

SevenIsland_SevaultCanyon_EventScript_1ACA8B:: @ 81ACA8B
	.incbin "baserom.gba", 0x1ACA8B, 0x3E

SevenIsland_SevaultCanyon_EventScript_1ACAC9:: @ 81ACAC9
	.incbin "baserom.gba", 0x1ACAC9, 0x3E

SevenIsland_SevaultCanyon_EventScript_1ACB07:: @ 81ACB07
	.incbin "baserom.gba", 0x1ACB07, 0x3E

SevenIsland_SevaultCanyon_EventScript_1ACB45:: @ 81ACB45
	.incbin "baserom.gba", 0x1ACB45, 0x3E

SevenIsland_SevaultCanyon_EventScript_1ACB83:: @ 81ACB83
	.incbin "baserom.gba", 0x1ACB83, 0x3E

SevenIsland_SevaultCanyon_EventScript_1ACBC1:: @ 81ACBC1
	.incbin "baserom.gba", 0x1ACBC1, 0x46

SevenIsland_SevaultCanyon_EventScript_1ACC07:: @ 81ACC07
	.incbin "baserom.gba", 0x1ACC07, 0x46

SevenIsland_TanobyRuins_EventScript_1ACC4D:: @ 81ACC4D
	.incbin "baserom.gba", 0x1ACC4D, 0x3E

SevenIsland_TanobyRuins_EventScript_1ACC8B:: @ 81ACC8B
	.incbin "baserom.gba", 0x1ACC8B, 0x3E

SevenIsland_TanobyRuins_EventScript_1ACCC9:: @ 81ACCC9
	.incbin "baserom.gba", 0x1ACCC9, 0x3E

SevenIsland_TanobyRuins_EventScript_1ACD07:: @ 81ACD07
	.incbin "baserom.gba", 0x1ACD07, 0x5E

ViridianCity_House2_EventScript_1ACD65:: @ 81ACD65
	.incbin "baserom.gba", 0x1ACD65, 0x6B

FourIsland_PokemonCenter_1F_EventScript_1ACDD0:: @ 81ACDD0
	.incbin "baserom.gba", 0x1ACDD0, 0x1A

Route4_EventScript_1ACDEA:: @ 81ACDEA
	.incbin "baserom.gba", 0x1ACDEA, 0x19

MtMoon_1F_EventScript_1ACE03:: @ 81ACE03
	.incbin "baserom.gba", 0x1ACE03, 0x19

PewterCity_Museum_1F_EventScript_1ACE1C:: @ 81ACE1C
	.incbin "baserom.gba", 0x1ACE1C, 0x1A

Route20_EventScript_1ACE36:: @ 81ACE36
	.incbin "baserom.gba", 0x1ACE36, 0x19

Route25_EventScript_1ACE4F:: @ 81ACE4F
	.incbin "baserom.gba", 0x1ACE4F, 0x19

CeruleanCity_PokemonCenter_1F_EventScript_1ACE68:: @ 81ACE68
	.incbin "baserom.gba", 0x1ACE68, 0x1B

VermilionCity_PokemonCenter_1F_EventScript_1ACE83:: @ 81ACE83
	.incbin "baserom.gba", 0x1ACE83, 0x1A

CeladonCity_Condominiums_2F_EventScript_1ACE9D:: @ 81ACE9D
	.incbin "baserom.gba", 0x1ACE9D, 0x1B

FuchsiaCity_Building1_EventScript_1ACEB8:: @ 81ACEB8
	.incbin "baserom.gba", 0x1ACEB8, 0x1B

SafariZone_Building3_EventScript_1ACED3:: @ 81ACED3
	.incbin "baserom.gba", 0x1ACED3, 0x19

SaffronCity_PokemonCenter_1F_EventScript_1ACEEC:: @ 81ACEEC
	.incbin "baserom.gba", 0x1ACEEC, 0x1B

CinnabarIsland_Gym_EventScript_1ACF07:: @ 81ACF07
	.incbin "baserom.gba", 0x1ACF07, 0x25

FiveIsland_ResortGorgeous_House_EventScript_1ACF2C:: @ 81ACF2C
	.incbin "baserom.gba", 0x1ACF2C, 0x1A

FourIsland_Mart_EventScript_1ACF46:: @ 81ACF46
	.incbin "baserom.gba", 0x1ACF46, 0x19

FiveIsland_PokemonCenter_1F_EventScript_1ACF5F:: @ 81ACF5F
	.incbin "baserom.gba", 0x1ACF5F, 0x1B

SaffronCity_PokemonTrainerFanClub_EventScript_1ACF7A:: @ 81ACF7A
	.incbin "baserom.gba", 0x1ACF7A, 0x1B

SevenIsland_SevaultCanyon_EventScript_1ACF95:: @ 81ACF95
	.incbin "baserom.gba", 0x1ACF95, 0x19

IndigoPlateau_PokemonCenter_1F_EventScript_1ACFAE:: @ 81ACFAE
	.incbin "baserom.gba", 0x1ACFAE, 0x26

SevenIsland_PokemonCenter_1F_EventScript_1ACFD4:: @ 81ACFD4
	.incbin "baserom.gba", 0x1ACFD4, 0x1B

SixIsland_Mart_EventScript_1ACFEF:: @ 81ACFEF
	.incbin "baserom.gba", 0x1ACFEF, 0x4B

SaffronCity_Duplicate_EventScript_1AD03A:: @ 81AD03A
	.incbin "baserom.gba", 0x1AD03A, 0x19

CeladonCity_DepartmentStore_2F_EventScript_1AD053:: @ 81AD053
	.incbin "baserom.gba", 0x1AD053, 0x19

IndigoPlateau_PokemonCenter_1F_EventScript_1AD06C:: @ 81AD06C
	.incbin "baserom.gba", 0x1AD06C, 0x1B

IndigoPlateau_PokemonCenter_1F_EventScript_1AD087:: @ 81AD087
	.incbin "baserom.gba", 0x1AD087, 0x19

LavenderTown_PokemonCenter_1F_EventScript_1AD0A0:: @ 81AD0A0
	.incbin "baserom.gba", 0x1AD0A0, 0x19

CinnabarIsland_PokemonCenter_1F_EventScript_1AD0B9:: @ 81AD0B9
	.incbin "baserom.gba", 0x1AD0B9, 0x1B

SilphCo_5F_EventScript_1AD0D4:: @ 81AD0D4
	.incbin "baserom.gba", 0x1AD0D4, 0x19

@ 0x19
SilphCo_8F_EventScript_1AD0ED:: @ 81AD0ED
	.incbin "baserom.gba", 0x1AD0ED, 0x19

	.include "data/text/fame_checker.inc"

CeladonCity_GameCorner_EventScript_1B2867:: @ 81B2867
	.incbin "baserom.gba", 0x1B2867, 0xD1

FourIsland_House2_EventScript_1B2938:: @ 81B2938
	.incbin "baserom.gba", 0x1B2938, 0x4C0

	.include "data/text/help_system.inc"

CeladonCity_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
CeruleanCity_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
CinnabarIsland_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
FiveIsland_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
FourIsland_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
FuchsiaCity_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
IndigoPlateau_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
LavenderTown_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
OneIsland_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
PewterCity_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
Route10_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
Route4_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
SaffronCity_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
SevenIsland_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
SixIsland_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
ThreeIsland_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
TwoIsland_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
VermilionCity_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
ViridianCity_PokemonCenter_2F_MapScript4_1BB1B4:: @ 81BB1B4
	.incbin "baserom.gba", 0x1BB1B4, 0x1E

CeruleanCity_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
CinnabarIsland_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
FiveIsland_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
FuchsiaCity_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
OneIsland_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
PewterCity_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
SevenIsland_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
VermilionCity_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
FourIsland_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
SixIsland_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
ThreeIsland_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
TwoIsland_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
Route10_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
Route10_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
Route4_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
SaffronCity_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
IndigoPlateau_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
CeladonCity_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
LavenderTown_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
ViridianCity_PokemonCenter_2F_EventScript_1BB1D2:: @ 81BB1D2
	.incbin "baserom.gba", 0x1BB1D2, 0x1B

CeladonCity_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
CeruleanCity_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
CinnabarIsland_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
FiveIsland_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
FourIsland_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
FuchsiaCity_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
IndigoPlateau_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
LavenderTown_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
OneIsland_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
PewterCity_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
Route10_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
Route4_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
SaffronCity_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
SevenIsland_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
SixIsland_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
ThreeIsland_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
TwoIsland_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
VermilionCity_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
ViridianCity_PokemonCenter_2F_MapScript2_1BB1ED:: @ 81BB1ED
	.incbin "baserom.gba", 0x1BB1ED, 0x3A

EventScript_1BB227:: @ 81BB227
	.incbin "baserom.gba", 0x1BB227, 0x10

CeladonCity_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
CeruleanCity_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
CinnabarIsland_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
FiveIsland_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
FourIsland_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
FuchsiaCity_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
IndigoPlateau_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
LavenderTown_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
OneIsland_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
PewterCity_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
Route10_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
Route4_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
SaffronCity_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
SevenIsland_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
SixIsland_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
ThreeIsland_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
TwoIsland_JoyfulGameCorner_MapScript4_1BB237:: @ 81BB237
TwoIsland_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
VermilionCity_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
ViridianCity_PokemonCenter_2F_MapScript3_1BB237:: @ 81BB237
	.incbin "baserom.gba", 0x1BB237, 0x6C

CeladonCity_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
CeruleanCity_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
CinnabarIsland_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
FiveIsland_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
FourIsland_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
FuchsiaCity_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
IndigoPlateau_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
LavenderTown_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
OneIsland_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
PewterCity_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
Route10_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
Route4_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
SaffronCity_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
SevenIsland_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
SixIsland_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
ThreeIsland_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
TwoIsland_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
VermilionCity_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
ViridianCity_PokemonCenter_2F_MapScript1_1BB2A3:: @ 81BB2A3
	.incbin "baserom.gba", 0x1BB2A3, 0x5A

EventScript_1BB2FD:: @ 81BB2FD
	.incbin "baserom.gba", 0x1BB2FD, 0x1A6

EventScript_1BB4A3:: @ 81BB4A3
	.incbin "baserom.gba", 0x1BB4A3, 0x208

EventScript_1BB6AB:: @ 81BB6AB
	.incbin "baserom.gba", 0x1BB6AB, 0x133

EventScript_1BB7DE:: @ 81BB7DE
	.incbin "baserom.gba", 0x1BB7DE, 0xC9

gUnknown_81BB8A7:: @ 81BB8A7
	.incbin "baserom.gba", 0x1BB8A7, 0x1C

gUnknown_81BB8C3:: @ 81BB8C3
UnknownMap_00_00_EventScript_1BB8C3:: @ 81BB8C3
	.incbin "baserom.gba", 0x1BB8C3, 0xC

gUnknown_81BB8CF:: @ 81BB8CF
UnknownMap_00_00_EventScript_1BB8CF:: @ 81BB8CF
	.incbin "baserom.gba", 0x1BB8CF, 0xC

gUnknown_81BB8DB:: @ 81BB8DB
UnknownMap_00_03_EventScript_1BB8DB:: @ 81BB8DB
	.incbin "baserom.gba", 0x1BB8DB, 0x1D

gUnknown_81BB8F8:: @ 81BB8F8
UnknownMap_00_03_EventScript_1BB8F8:: @ 81BB8F8
	.incbin "baserom.gba", 0x1BB8F8, 0x1D

gUnknown_81BB915:: @ 81BB915
UnknownMap_00_03_EventScript_1BB915:: @ 81BB915
	.incbin "baserom.gba", 0x1BB915, 0x1D

gUnknown_81BB932:: @ 81BB932
UnknownMap_00_03_EventScript_1BB932:: @ 81BB932
	.incbin "baserom.gba", 0x1BB932, 0x1E

gUnknown_81BB950:: @ 81BB950
UnknownMap_00_01_EventScript_1BB950:: @ 81BB950
	.incbin "baserom.gba", 0x1BB950, 0xC

gUnknown_81BB95C:: @ 81BB95C
UnknownMap_00_01_EventScript_1BB95C:: @ 81BB95C
	.incbin "baserom.gba", 0x1BB95C, 0x24

gUnknown_81BB980:: @ 81BB980
UnknownMap_00_02_EventScript_1BB980:: @ 81BB980
	.incbin "baserom.gba", 0x1BB980, 0x1

gUnknown_81BB981:: @ 81BB981
	.incbin "baserom.gba", 0x1BB981, 0x11

gUnknown_81BB992:: @ 81BB992
	.incbin "baserom.gba", 0x1BB992, 0x11

gUnknown_81BB9A3:: @ 81BB9A3
	.incbin "baserom.gba", 0x1BB9A3, 0xC

UnknownMap_00_00_EventScript_1BB9AF:: @ 81BB9AF
	.incbin "baserom.gba", 0x1BB9AF, 0x12

UnknownMap_00_01_EventScript_1BB9C1:: @ 81BB9C1
	.incbin "baserom.gba", 0x1BB9C1, 0x12

UnknownMap_00_02_EventScript_1BB9D3:: @ 81BB9D3
	.incbin "baserom.gba", 0x1BB9D3, 0x1

gUnknown_81BB9D4:: @ 81BB9D4
	.incbin "baserom.gba", 0x1BB9D4, 0x1C

gUnknown_81BB9F0:: @ 81BB9F0
	.incbin "baserom.gba", 0x1BB9F0, 0xC

gUnknown_81BB9FC:: @ 81BB9FC
	.incbin "baserom.gba", 0x1BB9FC, 0x5DC

gUnknown_81BBFD8:: @ 81BBFD8
	.incbin "baserom.gba", 0x1BBFD8, 0x84

CeladonCity_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
CeruleanCity_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
CinnabarIsland_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
FiveIsland_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
FourIsland_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
FuchsiaCity_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
IndigoPlateau_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
LavenderTown_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
OneIsland_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
PewterCity_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
Route10_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
Route4_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
SaffronCity_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
SevenIsland_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
SixIsland_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
ThreeIsland_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
TwoIsland_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
VermilionCity_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
ViridianCity_PokemonCenter_1F_MapScript2_1BC05C:: @ 81BC05C
	.incbin "baserom.gba", 0x1BC05C, 0x4

EventScript_1BC060:: @ 81BC060
	.incbin "baserom.gba", 0x1BC060, 0x6E

EventScript_1BC0CE:: @ 81BC0CE
	.incbin "baserom.gba", 0x1BC0CE, 0x219

TwoIsland_JoyfulGameCorner_EventScript_1BC2E7:: @ 81BC2E7
	.incbin "baserom.gba", 0x1BC2E7, 0x15

TwoIsland_JoyfulGameCorner_EventScript_1BC2FC:: @ 81BC2FC
	.incbin "baserom.gba", 0x1BC2FC, 0x1B0

gUnknown_81BC4AC:: @ 81BC4AC
	.incbin "baserom.gba", 0x1BC4AC, 0x22

gUnknown_81BC4CE:: @ 81BC4CE
	.incbin "baserom.gba", 0x1BC4CE, 0x3F

gUnknown_81BC50D:: @ 81BC50D
	.incbin "baserom.gba", 0x1BC50D, 0x3F

gUnknown_81BC54C:: @ 81BC54C
	.incbin "baserom.gba", 0x1BC54C, 0x77E

Text_1BCCCA:: @ 81BCCCA
	.incbin "baserom.gba", 0x1BCCCA, 0x1249

CeladonCity_EventScript_1BDF13:: @ 81BDF13
CeladonCity_Gym_EventScript_1BDF13:: @ 81BDF13
FiveIsland_Meadow_EventScript_1BDF13:: @ 81BDF13
PewterCity_EventScript_1BDF13:: @ 81BDF13
Route10_EventScript_1BDF13:: @ 81BDF13
Route12_EventScript_1BDF13:: @ 81BDF13
Route14_EventScript_1BDF13:: @ 81BDF13
Route16_EventScript_1BDF13:: @ 81BDF13
Route25_EventScript_1BDF13:: @ 81BDF13
Route2_EventScript_1BDF13:: @ 81BDF13
Route8_EventScript_1BDF13:: @ 81BDF13
ThreeIsland_BerryForest_EventScript_1BDF13:: @ 81BDF13
ThreeIsland_BondBridge_EventScript_1BDF13:: @ 81BDF13
ThreeIsland_EventScript_1BDF13:: @ 81BDF13
Route9_EventScript_1BDF13:: @ 81BDF13
Route13_EventScript_1BDF13:: @ 81BDF13
TwoIsland_EventScript_1BDF13:: @ 81BDF13
FuchsiaCity_EventScript_1BDF13:: @ 81BDF13
VermilionCity_EventScript_1BDF13:: @ 81BDF13
VermilionCity_EventScript_1BDF13:: @ 81BDF13
CeruleanCity_EventScript_1BDF13:: @ 81BDF13
ViridianCity_EventScript_1BDF13:: @ 81BDF13
	.incbin "baserom.gba", 0x1BDF13, 0x58

gUnknown_81BDF6B:: @ 81BDF6B
	.incbin "baserom.gba", 0x1BDF6B, 0xA1

CeruleanCave_2F_EventScript_1BE00C:: @ 81BE00C
MtEmber_Exterior_EventScript_1BE00C:: @ 81BE00C
MtEmber_RubyPath_B1F_Stairs_EventScript_1BE00C:: @ 81BE00C
MtEmber_RubyPath_B2F_EventScript_1BE00C:: @ 81BE00C
MtEmber_SummitPath_2F_EventScript_1BE00C:: @ 81BE00C
MtEmber_RubyPath_1F_EventScript_1BE00C:: @ 81BE00C
SevenIsland_SevaultCanyon_EventScript_1BE00C:: @ 81BE00C
FourIsland_EventScript_1BE00C:: @ 81BE00C
OneIsland_KindleRoad_EventScript_1BE00C:: @ 81BE00C
MtEmber_RubyPath_B2F_Stairs_EventScript_1BE00C:: @ 81BE00C
MtEmber_RubyPath_B3F_EventScript_1BE00C:: @ 81BE00C
MtEmber_RubyPath_B1F_EventScript_1BE00C:: @ 81BE00C
MtEmber_RubyPath_B1F_EventScript_1BE00C:: @ 81BE00C
RockTunnel_B1F_EventScript_1BE00C:: @ 81BE00C
CeruleanCave_B1F_EventScript_1BE00C:: @ 81BE00C
CeruleanCave_1F_EventScript_1BE00C:: @ 81BE00C
	.incbin "baserom.gba", 0x1BE00C, 0x58

EventScript_FldEffRockSmash:: @ 81BE064
	.incbin "baserom.gba", 0x1BE064, 0xB9

MtEmber_Exterior_EventScript_1BE11D:: @ 81BE11D
MtEmber_RubyPath_B2F_EventScript_1BE11D:: @ 81BE11D
MtEmber_Summit_EventScript_1BE11D:: @ 81BE11D
SeafoamIslands_1F_EventScript_1BE11D:: @ 81BE11D
SeafoamIslands_B2F_EventScript_1BE11D:: @ 81BE11D
SevenIsland_SevaultCanyon_EventScript_1BE11D:: @ 81BE11D
VictoryRoad_1F_EventScript_1BE11D:: @ 81BE11D
VictoryRoad_3F_EventScript_1BE11D:: @ 81BE11D
SixIsland_RuinValley_EventScript_1BE11D:: @ 81BE11D
FuchsiaCity_Building1_EventScript_1BE11D:: @ 81BE11D
SevenIsland_SeavaultCanyon_TanobyKey_EventScript_1BE11D:: @ 81BE11D
MtEmber_RubyPath_B3F_EventScript_1BE11D:: @ 81BE11D
SeafoamIslands_B3F_EventScript_1BE11D:: @ 81BE11D
SeafoamIslands_B3F_EventScript_1BE11D:: @ 81BE11D
SeafoamIslands_B1F_EventScript_1BE11D:: @ 81BE11D
VictoryRoad_2F_EventScript_1BE11D:: @ 81BE11D
	.incbin "baserom.gba", 0x1BE11D, 0x51

EventScript_FldEffStrength:: @ 81BE16E
	.incbin "baserom.gba", 0x1BE16E, 0x149

gUnknown_81BE2B7:: @ 81BE2B7
	.incbin "baserom.gba", 0x1BE2B7, 0x48

gUnknown_81BE2FF:: @ 81BE2FF
	.incbin "baserom.gba", 0x1BE2FF, 0x265

EventScript_FailSweetScent:: @ 81BE564
	.incbin "baserom.gba", 0x1BE564, 0x2A

Route2_EventScript_1BE58E:: @ 81BE58E
	.incbin "baserom.gba", 0x1BE58E, 0xD

Route2_EventScript_1BE59B:: @ 81BE59B
	.incbin "baserom.gba", 0x1BE59B, 0xD

ViridianForest_EventScript_1BE5A8:: @ 81BE5A8
	.incbin "baserom.gba", 0x1BE5A8, 0xD

ViridianForest_EventScript_1BE5B5:: @ 81BE5B5
	.incbin "baserom.gba", 0x1BE5B5, 0xD

ViridianForest_EventScript_1BE5C2:: @ 81BE5C2
	.incbin "baserom.gba", 0x1BE5C2, 0xD

MtMoon_1F_EventScript_1BE5CF:: @ 81BE5CF
	.incbin "baserom.gba", 0x1BE5CF, 0xD

MtMoon_1F_EventScript_1BE5DC:: @ 81BE5DC
	.incbin "baserom.gba", 0x1BE5DC, 0xD

MtMoon_1F_EventScript_1BE5E9:: @ 81BE5E9
	.incbin "baserom.gba", 0x1BE5E9, 0xD

MtMoon_1F_EventScript_1BE5F6:: @ 81BE5F6
	.incbin "baserom.gba", 0x1BE5F6, 0xD

MtMoon_1F_EventScript_1BE603:: @ 81BE603
	.incbin "baserom.gba", 0x1BE603, 0xD

MtMoon_1F_EventScript_1BE610:: @ 81BE610
	.incbin "baserom.gba", 0x1BE610, 0xD

MtMoon_B2F_EventScript_1BE61D:: @ 81BE61D
	.incbin "baserom.gba", 0x1BE61D, 0xD

MtMoon_B2F_EventScript_1BE62A:: @ 81BE62A
	.incbin "baserom.gba", 0x1BE62A, 0xD

Route4_EventScript_1BE637:: @ 81BE637
	.incbin "baserom.gba", 0x1BE637, 0xD

Route24_EventScript_1BE644:: @ 81BE644
	.incbin "baserom.gba", 0x1BE644, 0xD

Route25_EventScript_1BE651:: @ 81BE651
	.incbin "baserom.gba", 0x1BE651, 0xD

SSAnne_1F_Room2_EventScript_1BE65E:: @ 81BE65E
	.incbin "baserom.gba", 0x1BE65E, 0xD

SSAnne_2F_Room2_EventScript_1BE66B:: @ 81BE66B
	.incbin "baserom.gba", 0x1BE66B, 0xD

SSAnne_2F_Room4_EventScript_1BE678:: @ 81BE678
	.incbin "baserom.gba", 0x1BE678, 0xD

SSAnne_B1F_Room2_EventScript_1BE685:: @ 81BE685
	.incbin "baserom.gba", 0x1BE685, 0xD

SSAnne_B1F_Room3_EventScript_1BE692:: @ 81BE692
	.incbin "baserom.gba", 0x1BE692, 0xD

SSAnne_B1F_Room5_EventScript_1BE69F:: @ 81BE69F
	.incbin "baserom.gba", 0x1BE69F, 0xD

SSAnne_Kitchen_EventScript_1BE6AC:: @ 81BE6AC
	.incbin "baserom.gba", 0x1BE6AC, 0xD

Route9_EventScript_1BE6B9:: @ 81BE6B9
	.incbin "baserom.gba", 0x1BE6B9, 0xD

RocketHideout_B1F_EventScript_1BE6C6:: @ 81BE6C6
	.incbin "baserom.gba", 0x1BE6C6, 0xD

RocketHideout_B1F_EventScript_1BE6D3:: @ 81BE6D3
	.incbin "baserom.gba", 0x1BE6D3, 0xD

RocketHideout_B2F_EventScript_1BE6E0:: @ 81BE6E0
	.incbin "baserom.gba", 0x1BE6E0, 0xD

RocketHideout_B2F_EventScript_1BE6ED:: @ 81BE6ED
	.incbin "baserom.gba", 0x1BE6ED, 0xD

RocketHideout_B2F_EventScript_1BE6FA:: @ 81BE6FA
	.incbin "baserom.gba", 0x1BE6FA, 0xD

RocketHideout_B2F_EventScript_1BE707:: @ 81BE707
	.incbin "baserom.gba", 0x1BE707, 0xD

RocketHideout_B3F_EventScript_1BE714:: @ 81BE714
	.incbin "baserom.gba", 0x1BE714, 0xD

RocketHideout_B3F_EventScript_1BE721:: @ 81BE721
	.incbin "baserom.gba", 0x1BE721, 0xD

RocketHideout_B4F_EventScript_1BE72E:: @ 81BE72E
	.incbin "baserom.gba", 0x1BE72E, 0xD

RocketHideout_B4F_EventScript_1BE73B:: @ 81BE73B
	.incbin "baserom.gba", 0x1BE73B, 0xD

RocketHideout_B4F_EventScript_1BE748:: @ 81BE748
	.incbin "baserom.gba", 0x1BE748, 0xD

PokemonTower_3F_EventScript_1BE755:: @ 81BE755
	.incbin "baserom.gba", 0x1BE755, 0xD

PokemonTower_4F_EventScript_1BE762:: @ 81BE762
	.incbin "baserom.gba", 0x1BE762, 0xD

PokemonTower_4F_EventScript_1BE76F:: @ 81BE76F
	.incbin "baserom.gba", 0x1BE76F, 0xD

PokemonTower_4F_EventScript_1BE77C:: @ 81BE77C
	.incbin "baserom.gba", 0x1BE77C, 0xD

PokemonTower_5F_EventScript_1BE789:: @ 81BE789
	.incbin "baserom.gba", 0x1BE789, 0xD

PokemonTower_6F_EventScript_1BE796:: @ 81BE796
	.incbin "baserom.gba", 0x1BE796, 0xD

PokemonTower_6F_EventScript_1BE7A3:: @ 81BE7A3
	.incbin "baserom.gba", 0x1BE7A3, 0xD

Route12_EventScript_1BE7B0:: @ 81BE7B0
	.incbin "baserom.gba", 0x1BE7B0, 0xD

Route12_EventScript_1BE7BD:: @ 81BE7BD
	.incbin "baserom.gba", 0x1BE7BD, 0xD

Route15_EventScript_1BE7CA:: @ 81BE7CA
	.incbin "baserom.gba", 0x1BE7CA, 0xD

SafariZone_Center_EventScript_1BE7D7:: @ 81BE7D7
	.incbin "baserom.gba", 0x1BE7D7, 0xD

SafariZone_East_EventScript_1BE7E4:: @ 81BE7E4
	.incbin "baserom.gba", 0x1BE7E4, 0xD

SafariZone_East_EventScript_1BE7F1:: @ 81BE7F1
	.incbin "baserom.gba", 0x1BE7F1, 0xD

SafariZone_East_EventScript_1BE7FE:: @ 81BE7FE
	.incbin "baserom.gba", 0x1BE7FE, 0xD

SafariZone_East_EventScript_1BE80B:: @ 81BE80B
	.incbin "baserom.gba", 0x1BE80B, 0xD

SafariZone_North_EventScript_1BE818:: @ 81BE818
	.incbin "baserom.gba", 0x1BE818, 0xD

SafariZone_North_EventScript_1BE825:: @ 81BE825
	.incbin "baserom.gba", 0x1BE825, 0xD

SafariZone_West_EventScript_1BE832:: @ 81BE832
	.incbin "baserom.gba", 0x1BE832, 0xD

SafariZone_West_EventScript_1BE83F:: @ 81BE83F
	.incbin "baserom.gba", 0x1BE83F, 0xD

SafariZone_West_EventScript_1BE84C:: @ 81BE84C
	.incbin "baserom.gba", 0x1BE84C, 0xD

SafariZone_West_EventScript_1BE859:: @ 81BE859
	.incbin "baserom.gba", 0x1BE859, 0xD

SilphCo_3F_EventScript_1BE866:: @ 81BE866
	.incbin "baserom.gba", 0x1BE866, 0xD

SilphCo_4F_EventScript_1BE873:: @ 81BE873
	.incbin "baserom.gba", 0x1BE873, 0xD

SilphCo_4F_EventScript_1BE880:: @ 81BE880
	.incbin "baserom.gba", 0x1BE880, 0xD

SilphCo_4F_EventScript_1BE88D:: @ 81BE88D
	.incbin "baserom.gba", 0x1BE88D, 0xD

SilphCo_5F_EventScript_1BE89A:: @ 81BE89A
	.incbin "baserom.gba", 0x1BE89A, 0xD

SilphCo_5F_EventScript_1BE8A7:: @ 81BE8A7
	.incbin "baserom.gba", 0x1BE8A7, 0xD

SilphCo_5F_EventScript_1BE8B4:: @ 81BE8B4
	.incbin "baserom.gba", 0x1BE8B4, 0xD

SilphCo_6F_EventScript_1BE8C1:: @ 81BE8C1
	.incbin "baserom.gba", 0x1BE8C1, 0xD

SilphCo_6F_EventScript_1BE8CE:: @ 81BE8CE
	.incbin "baserom.gba", 0x1BE8CE, 0xD

SilphCo_7F_EventScript_1BE8DB:: @ 81BE8DB
	.incbin "baserom.gba", 0x1BE8DB, 0xD

SilphCo_7F_EventScript_1BE8E8:: @ 81BE8E8
	.incbin "baserom.gba", 0x1BE8E8, 0xD

SilphCo_10F_EventScript_1BE8F5:: @ 81BE8F5
	.incbin "baserom.gba", 0x1BE8F5, 0xD

SilphCo_10F_EventScript_1BE902:: @ 81BE902
	.incbin "baserom.gba", 0x1BE902, 0xD

SilphCo_10F_EventScript_1BE90F:: @ 81BE90F
	.incbin "baserom.gba", 0x1BE90F, 0xD

PowerPlant_EventScript_1BE91C:: @ 81BE91C
	.incbin "baserom.gba", 0x1BE91C, 0xD

PowerPlant_EventScript_1BE929:: @ 81BE929
	.incbin "baserom.gba", 0x1BE929, 0xD

PowerPlant_EventScript_1BE936:: @ 81BE936
	.incbin "baserom.gba", 0x1BE936, 0xD

PowerPlant_EventScript_1BE943:: @ 81BE943
	.incbin "baserom.gba", 0x1BE943, 0xD

PowerPlant_EventScript_1BE950:: @ 81BE950
	.incbin "baserom.gba", 0x1BE950, 0xD

PokemonMansion_1F_EventScript_1BE95D:: @ 81BE95D
	.incbin "baserom.gba", 0x1BE95D, 0xD

PokemonMansion_1F_EventScript_1BE96A:: @ 81BE96A
	.incbin "baserom.gba", 0x1BE96A, 0xD

PokemonMansion_2F_EventScript_1BE977:: @ 81BE977
	.incbin "baserom.gba", 0x1BE977, 0xD

PokemonMansion_3F_EventScript_1BE984:: @ 81BE984
	.incbin "baserom.gba", 0x1BE984, 0xD

PokemonMansion_3F_EventScript_1BE991:: @ 81BE991
	.incbin "baserom.gba", 0x1BE991, 0xD

PokemonMansion_B1F_EventScript_1BE99E:: @ 81BE99E
	.incbin "baserom.gba", 0x1BE99E, 0xD

PokemonMansion_B1F_EventScript_1BE9AB:: @ 81BE9AB
	.incbin "baserom.gba", 0x1BE9AB, 0xD

PokemonMansion_B1F_EventScript_1BE9B8:: @ 81BE9B8
	.incbin "baserom.gba", 0x1BE9B8, 0xD

PokemonMansion_B1F_EventScript_1BE9C5:: @ 81BE9C5
	.incbin "baserom.gba", 0x1BE9C5, 0xD

VictoryRoad_1F_EventScript_1BE9D2:: @ 81BE9D2
	.incbin "baserom.gba", 0x1BE9D2, 0xD

VictoryRoad_1F_EventScript_1BE9DF:: @ 81BE9DF
	.incbin "baserom.gba", 0x1BE9DF, 0xD

VictoryRoad_2F_EventScript_1BE9EC:: @ 81BE9EC
	.incbin "baserom.gba", 0x1BE9EC, 0xD

VictoryRoad_2F_EventScript_1BE9F9:: @ 81BE9F9
	.incbin "baserom.gba", 0x1BE9F9, 0xD

VictoryRoad_2F_EventScript_1BEA06:: @ 81BEA06
	.incbin "baserom.gba", 0x1BEA06, 0xD

VictoryRoad_2F_EventScript_1BEA13:: @ 81BEA13
	.incbin "baserom.gba", 0x1BEA13, 0xD

VictoryRoad_3F_EventScript_1BEA20:: @ 81BEA20
	.incbin "baserom.gba", 0x1BEA20, 0xD

VictoryRoad_3F_EventScript_1BEA2D:: @ 81BEA2D
	.incbin "baserom.gba", 0x1BEA2D, 0xD

CeruleanCave_1F_EventScript_1BEA3A:: @ 81BEA3A
	.incbin "baserom.gba", 0x1BEA3A, 0xD

CeruleanCave_1F_EventScript_1BEA47:: @ 81BEA47
	.incbin "baserom.gba", 0x1BEA47, 0xD

CeruleanCave_1F_EventScript_1BEA54:: @ 81BEA54
	.incbin "baserom.gba", 0x1BEA54, 0xD

CeruleanCave_2F_EventScript_1BEA61:: @ 81BEA61
	.incbin "baserom.gba", 0x1BEA61, 0xD

CeruleanCave_2F_EventScript_1BEA6E:: @ 81BEA6E
	.incbin "baserom.gba", 0x1BEA6E, 0xD

CeruleanCave_2F_EventScript_1BEA7B:: @ 81BEA7B
	.incbin "baserom.gba", 0x1BEA7B, 0xD

CeruleanCave_B1F_EventScript_1BEA88:: @ 81BEA88
	.incbin "baserom.gba", 0x1BEA88, 0xD

CeruleanCave_B1F_EventScript_1BEA95:: @ 81BEA95
	.incbin "baserom.gba", 0x1BEA95, 0xD

FuchsiaCity_Building1_EventScript_1BEAA2:: @ 81BEAA2
	.incbin "baserom.gba", 0x1BEAA2, 0xD

TwoIsland_EventScript_1BEAAF:: @ 81BEAAF
	.incbin "baserom.gba", 0x1BEAAF, 0xD

ThreeIsland_EventScript_1BEABC:: @ 81BEABC
	.incbin "baserom.gba", 0x1BEABC, 0xD

ViridianForest_EventScript_1BEAC9:: @ 81BEAC9
	.incbin "baserom.gba", 0x1BEAC9, 0xD

MtMoon_B2F_EventScript_1BEAD6:: @ 81BEAD6
	.incbin "baserom.gba", 0x1BEAD6, 0xD

MtMoon_B2F_EventScript_1BEAE3:: @ 81BEAE3
	.incbin "baserom.gba", 0x1BEAE3, 0xD

Route11_EventScript_1BEAF0:: @ 81BEAF0
	.incbin "baserom.gba", 0x1BEAF0, 0xD

Route9_EventScript_1BEAFD:: @ 81BEAFD
	.incbin "baserom.gba", 0x1BEAFD, 0xD

RockTunnel_1F_EventScript_1BEB0A:: @ 81BEB0A
	.incbin "baserom.gba", 0x1BEB0A, 0xD

RockTunnel_1F_EventScript_1BEB17:: @ 81BEB17
	.incbin "baserom.gba", 0x1BEB17, 0xD

RockTunnel_1F_EventScript_1BEB24:: @ 81BEB24
	.incbin "baserom.gba", 0x1BEB24, 0xD

RockTunnel_B1F_EventScript_1BEB31:: @ 81BEB31
	.incbin "baserom.gba", 0x1BEB31, 0xD

RockTunnel_B1F_EventScript_1BEB3E:: @ 81BEB3E
	.incbin "baserom.gba", 0x1BEB3E, 0xD

SilphCo_8F_EventScript_1BEB4B:: @ 81BEB4B
	.incbin "baserom.gba", 0x1BEB4B, 0xD

SilphCo_11F_EventScript_1BEB58:: @ 81BEB58
	.incbin "baserom.gba", 0x1BEB58, 0xD

PokemonMansion_1F_EventScript_1BEB65:: @ 81BEB65
	.incbin "baserom.gba", 0x1BEB65, 0xD

PokemonMansion_2F_EventScript_1BEB72:: @ 81BEB72
	.incbin "baserom.gba", 0x1BEB72, 0xD

PokemonMansion_2F_EventScript_1BEB7F:: @ 81BEB7F
	.incbin "baserom.gba", 0x1BEB7F, 0xD

ViridianCity_EventScript_1BEB8C:: @ 81BEB8C
	.incbin "baserom.gba", 0x1BEB8C, 0xD

Route11_EventScript_1BEB99:: @ 81BEB99
	.incbin "baserom.gba", 0x1BEB99, 0xD

Route11_EventScript_1BEBA6:: @ 81BEBA6
	.incbin "baserom.gba", 0x1BEBA6, 0xD

PokemonTower_5F_EventScript_1BEBB3:: @ 81BEBB3
	.incbin "baserom.gba", 0x1BEBB3, 0xD

CeladonCity_EventScript_1BEBC0:: @ 81BEBC0
	.incbin "baserom.gba", 0x1BEBC0, 0xD

RocketHideout_B3F_EventScript_1BEBCD:: @ 81BEBCD
	.incbin "baserom.gba", 0x1BEBCD, 0xD

SafariZone_North_EventScript_1BEBDA:: @ 81BEBDA
	.incbin "baserom.gba", 0x1BEBDA, 0xD

SeafoamIslands_1F_EventScript_1BEBE7:: @ 81BEBE7
	.incbin "baserom.gba", 0x1BEBE7, 0xD

SeafoamIslands_B1F_EventScript_1BEBF4:: @ 81BEBF4
	.incbin "baserom.gba", 0x1BEBF4, 0xD

SeafoamIslands_B1F_EventScript_1BEC01:: @ 81BEC01
	.incbin "baserom.gba", 0x1BEC01, 0xD

SeafoamIslands_B2F_EventScript_1BEC0E:: @ 81BEC0E
	.incbin "baserom.gba", 0x1BEC0E, 0xD

SeafoamIslands_B4F_EventScript_1BEC1B:: @ 81BEC1B
	.incbin "baserom.gba", 0x1BEC1B, 0xD

FourIsland_EventScript_1BEC28:: @ 81BEC28
	.incbin "baserom.gba", 0x1BEC28, 0xD

FourIsland_EventScript_1BEC35:: @ 81BEC35
	.incbin "baserom.gba", 0x1BEC35, 0xD

OneIsland_KindleRoad_EventScript_1BEC42:: @ 81BEC42
	.incbin "baserom.gba", 0x1BEC42, 0xD

OneIsland_KindleRoad_EventScript_1BEC4F:: @ 81BEC4F
	.incbin "baserom.gba", 0x1BEC4F, 0xD

OneIsland_KindleRoad_EventScript_1BEC5C:: @ 81BEC5C
	.incbin "baserom.gba", 0x1BEC5C, 0xD

FiveIsland_Meadow_EventScript_1BEC69:: @ 81BEC69
	.incbin "baserom.gba", 0x1BEC69, 0xD

FiveIsland_Meadow_EventScript_1BEC76:: @ 81BEC76
	.incbin "baserom.gba", 0x1BEC76, 0xD

FiveIsland_MemorialPillar_EventScript_1BEC83:: @ 81BEC83
	.incbin "baserom.gba", 0x1BEC83, 0xD

SixIsland_OutcastIsland_EventScript_1BEC90:: @ 81BEC90
	.incbin "baserom.gba", 0x1BEC90, 0xD

SixIsland_WaterPath_EventScript_1BEC9D:: @ 81BEC9D
	.incbin "baserom.gba", 0x1BEC9D, 0xD

SixIsland_WaterPath_EventScript_1BECAA:: @ 81BECAA
	.incbin "baserom.gba", 0x1BECAA, 0xD

SixIsland_RuinValley_EventScript_1BECB7:: @ 81BECB7
	.incbin "baserom.gba", 0x1BECB7, 0xD

SixIsland_RuinValley_EventScript_1BECC4:: @ 81BECC4
	.incbin "baserom.gba", 0x1BECC4, 0xD

SixIsland_RuinValley_EventScript_1BECD1:: @ 81BECD1
	.incbin "baserom.gba", 0x1BECD1, 0xD

SevenIsland_SevaultCanyon_EventScript_1BECDE:: @ 81BECDE
	.incbin "baserom.gba", 0x1BECDE, 0xD

SevenIsland_SevaultCanyon_EventScript_1BECEB:: @ 81BECEB
	.incbin "baserom.gba", 0x1BECEB, 0xD

SevenIsland_SevaultCanyon_EventScript_1BECF8:: @ 81BECF8
	.incbin "baserom.gba", 0x1BECF8, 0xD

ThreeIsland_BerryForest_EventScript_1BED05:: @ 81BED05
	.incbin "baserom.gba", 0x1BED05, 0xD

ThreeIsland_BerryForest_EventScript_1BED12:: @ 81BED12
	.incbin "baserom.gba", 0x1BED12, 0xD

ThreeIsland_BerryForest_EventScript_1BED1F:: @ 81BED1F
	.incbin "baserom.gba", 0x1BED1F, 0xD

MtEmber_Exterior_EventScript_1BED2C:: @ 81BED2C
	.incbin "baserom.gba", 0x1BED2C, 0xD

MtEmber_Exterior_EventScript_1BED39:: @ 81BED39
	.incbin "baserom.gba", 0x1BED39, 0xD

MtEmber_Exterior_EventScript_1BED46:: @ 81BED46
	.incbin "baserom.gba", 0x1BED46, 0xD

FourIsland_IcefallCave_1F_EventScript_1BED53:: @ 81BED53
	.incbin "baserom.gba", 0x1BED53, 0xD

FourIsland_IcefallCave_1F_EventScript_1BED60:: @ 81BED60
	.incbin "baserom.gba", 0x1BED60, 0xD

FourIsland_IcefallCave_B1F_EventScript_1BED6D:: @ 81BED6D
	.incbin "baserom.gba", 0x1BED6D, 0xD

FourIsland_IcefallCave_B1F_EventScript_1BED7A:: @ 81BED7A
	.incbin "baserom.gba", 0x1BED7A, 0xD

FiveIsland_RocketWarehouse_EventScript_1BED87:: @ 81BED87
	.incbin "baserom.gba", 0x1BED87, 0xD

FiveIsland_RocketWarehouse_EventScript_1BED94:: @ 81BED94
	.incbin "baserom.gba", 0x1BED94, 0xD

FiveIsland_RocketWarehouse_EventScript_1BEDA1:: @ 81BEDA1
	.incbin "baserom.gba", 0x1BEDA1, 0xD

FiveIsland_RocketWarehouse_EventScript_1BEDAE:: @ 81BEDAE
	.incbin "baserom.gba", 0x1BEDAE, 0xD

FiveIsland_LostCave_Room10_EventScript_1BEDBB:: @ 81BEDBB
	.incbin "baserom.gba", 0x1BEDBB, 0xD

FiveIsland_LostCave_Room11_EventScript_1BEDC8:: @ 81BEDC8
	.incbin "baserom.gba", 0x1BEDC8, 0xD

FiveIsland_LostCave_Room12_EventScript_1BEDD5:: @ 81BEDD5
	.incbin "baserom.gba", 0x1BEDD5, 0xD

FiveIsland_LostCave_Room13_EventScript_1BEDE2:: @ 81BEDE2
	.incbin "baserom.gba", 0x1BEDE2, 0xD

FiveIsland_LostCave_Room14_EventScript_1BEDEF:: @ 81BEDEF
	.incbin "baserom.gba", 0x1BEDEF, 0xD

SevenIsland_SevaultCanyon_House_EventScript_1BEDFC:: @ 81BEDFC
	.incbin "baserom.gba", 0x1BEDFC, 0xD

SilphCo_4F_EventScript_1BEE09:: @ 81BEE09
	.incbin "baserom.gba", 0x1BEE09, 0xD

PewterCity_PokemonCenter_1F_EventScript_1BEE16:: @ 81BEE16
	.incbin "baserom.gba", 0x1BEE16, 0x582

Route5_PokemonDayCare_EventScript_1BF398:: @ 81BF398
	.incbin "baserom.gba", 0x1BF398, 0x1AE

gUnknown_81BF546:: @ 81BF546
	.incbin "baserom.gba", 0x1BF546, 0xF

gUnknown_81BF555:: @ 81BF555
	.incbin "baserom.gba", 0x1BF555, 0x8E

gUnknown_81BF5E3:: @ 81BF5E3
	.incbin "baserom.gba", 0x1BF5E3, 0xB7

gUnknown_81BF69A:: @ 81BF69A
	.incbin "baserom.gba", 0x1BF69A, 0x35

gUnknown_81BF6CF:: @ 81BF6CF
	.incbin "baserom.gba", 0x1BF6CF, 0x21

gUnknown_81BF6F0:: @ 81BF6F0
	.incbin "baserom.gba", 0x1BF6F0, 0x3A

Text_1BF72A:: @ 81BF72A
	.incbin "baserom.gba", 0x1BF72A, 0x2B

gUnknown_81BF755:: @ 81BF755
	.incbin "baserom.gba", 0x1BF755, 0x34

gUnknown_81BF789:: @ 81BF789
	.incbin "baserom.gba", 0x1BF789, 0x2D

gUnknown_81BF7B6:: @ 81BF7B6
	.incbin "baserom.gba", 0x1BF7B6, 0x2E

gUnknown_81BF7E4:: @ 81BF7E4
	.incbin "baserom.gba", 0x1BF7E4, 0x55

gUnknown_81BF839:: @ 81BF839
	.incbin "baserom.gba", 0x1BF839, 0x27

gUnknown_81BF860:: @ 81BF860
	.incbin "baserom.gba", 0x1BF860, 0x3F

gUnknown_81BF89F:: @ 81BF89F
	.incbin "baserom.gba", 0x1BF89F, 0x57

gUnknown_81BF8F6:: @ 81BF8F6
	.incbin "baserom.gba", 0x1BF8F6, 0x20

gUnknown_81BF916:: @ 81BF916
	.incbin "baserom.gba", 0x1BF916, 0x1C

gUnknown_81BF932:: @ 81BF932
	.incbin "baserom.gba", 0x1BF932, 0x1D

gUnknown_81BF94F:: @ 81BF94F
	.incbin "baserom.gba", 0x1BF94F, 0x27

gUnknown_81BF976:: @ 81BF976
	.incbin "baserom.gba", 0x1BF976, 0x12

gUnknown_81BF988:: @ 81BF988
	.incbin "baserom.gba", 0x1BF988, 0x44

gUnknown_81BF9CC:: @ 81BF9CC
	.incbin "baserom.gba", 0x1BF9CC, 0x23

gUnknown_81BF9EF:: @ 81BF9EF
	.incbin "baserom.gba", 0x1BF9EF, 0x4C

gUnknown_81BFA3B:: @ 81BFA3B
	.incbin "baserom.gba", 0x1BFA3B, 0x2C

gUnknown_81BFA67:: @ 81BFA67
	.incbin "baserom.gba", 0x1BFA67, 0x1E

gUnknown_81BFA85:: @ 81BFA85
	.incbin "baserom.gba", 0x1BFA85, 0x28

gUnknown_81BFAAD:: @ 81BFAAD
	.incbin "baserom.gba", 0x1BFAAD, 0x3B

gUnknown_81BFAE8:: @ 81BFAE8
	.incbin "baserom.gba", 0x1BFAE8, 0x21

gUnknown_81BFB09:: @ 81BFB09
	.incbin "baserom.gba", 0x1BFB09, 0x56

gUnknown_81BFB5F:: @ 81BFB5F
	.incbin "baserom.gba", 0x1BFB5F, 0x6

gUnknown_81BFB65:: @ 81BFB65
	.incbin "baserom.gba", 0x1BFB65, 0x22

EventScript_SafariWarpOut:: @ 81BFB87
	.incbin "baserom.gba", 0x1BFB87, 0x23

EventScript_SafariRetire:: @ 81BFBAA
	.incbin "baserom.gba", 0x1BFBAA, 0x1B

EventScript_SafariTimesUp:: @ 81BFBC5
	.incbin "baserom.gba", 0x1BFBC5, 0x12

EventScript_SafariOutOfBalls:: @ 81BFBD7
	.incbin "baserom.gba", 0x1BFBD7, 0x2D5

gUnknown_81BFEAC:: @ 81BFEAC
	.incbin "baserom.gba", 0x1BFEAC, 0x1164

gUnknown_81C1010:: @ 81C1010
	.incbin "baserom.gba", 0x1C1010, 0xC

gUnknown_81C101C:: @ 81C101C
	.incbin "baserom.gba", 0x1C101C, 0x345

gUnknown_81C1361:: @ 81C1361
	.incbin "baserom.gba", 0x1C1361, 0x1B

gUnknown_81C137C:: @ 81C137C
	.incbin "baserom.gba", 0x1C137C, 0x5A

gUnknown_81C13D6:: @ 81C13D6
	.incbin "baserom.gba", 0x1C13D6, 0x53

gUnknown_81C1429:: @ 81C1429
	.incbin "baserom.gba", 0x1C1429, 0x3385

VictoryRoad_2F_EventScript_1C47AE:: @ 81C47AE
	.incbin "baserom.gba", 0x1C47AE, 0x68

EventScript_1C4816:: @ 81C4816
	.incbin "baserom.gba", 0x1C4816, 0x68

RockTunnel_B1F_EventScript_1C487E:: @ 81C487E
	.incbin "baserom.gba", 0x1C487E, 0x68

MtEmber_Exterior_EventScript_1C48E6:: @ 81C48E6
	.incbin "baserom.gba", 0x1C48E6, 0x68

Route4_EventScript_1C494E:: @ 81C494E
	.incbin "baserom.gba", 0x1C494E, 0x68

Route4_EventScript_1C49B6:: @ 81C49B6
	.incbin "baserom.gba", 0x1C49B6, 0x68

EventScript_1C4A1E:: @ 81C4A1E
	.incbin "baserom.gba", 0x1C4A1E, 0x68

EventScript_1C4A86:: @ 81C4A86
	.incbin "baserom.gba", 0x1C4A86, 0x68

FuchsiaCity_EventScript_1C4AEE:: @ 81C4AEE
	.incbin "baserom.gba", 0x1C4AEE, 0x68

SevenIsland_EventScript_1C4B56:: @ 81C4B56
	.incbin "baserom.gba", 0x1C4B56, 0x68

PewterCity_Museum_1F_EventScript_1C4BBE:: @ 81C4BBE
	.incbin "baserom.gba", 0x1C4BBE, 0x68

EventScript_1C4C26:: @ 81C4C26
	.incbin "baserom.gba", 0x1C4C26, 0x68

EventScript_1C4C8E:: @ 81C4C8E
	.incbin "baserom.gba", 0x1C4C8E, 0x68

EventScript_1C4CF6:: @ 81C4CF6
	.incbin "baserom.gba", 0x1C4CF6, 0x8E

FourIsland_House1_EventScript_1C4D84:: @ 81C4D84
	.incbin "baserom.gba", 0x1C4D84, 0x68

TwoIsland_CapeBrink_House_EventScript_1C4DEC:: @ 81C4DEC
	.incbin "baserom.gba", 0x1C4DEC, 0x168

SevenIsland_TrainerTower_1F_MapScript1_1C4F54:: @ 81C4F54
SevenIsland_TrainerTower_2F_MapScript1_1C4F54:: @ 81C4F54
SevenIsland_TrainerTower_3F_MapScript1_1C4F54:: @ 81C4F54
SevenIsland_TrainerTower_4F_MapScript1_1C4F54:: @ 81C4F54
SevenIsland_TrainerTower_5F_MapScript1_1C4F54:: @ 81C4F54
SevenIsland_TrainerTower_6F_MapScript1_1C4F54:: @ 81C4F54
SevenIsland_TrainerTower_7F_MapScript1_1C4F54:: @ 81C4F54
SevenIsland_TrainerTower_8F_MapScript1_1C4F54:: @ 81C4F54
SevenIsland_TrainerTower_Elevator_MapScript1_1C4F54:: @ 81C4F54
SevenIsland_TrainerTower_Roof_MapScript1_1C4F54:: @ 81C4F54
	.incbin "baserom.gba", 0x1C4F54, 0xE

SevenIsland_TrainerTower_1F_MapScript2_1C4F62:: @ 81C4F62
SevenIsland_TrainerTower_2F_MapScript2_1C4F62:: @ 81C4F62
SevenIsland_TrainerTower_3F_MapScript2_1C4F62:: @ 81C4F62
SevenIsland_TrainerTower_4F_MapScript2_1C4F62:: @ 81C4F62
SevenIsland_TrainerTower_5F_MapScript2_1C4F62:: @ 81C4F62
SevenIsland_TrainerTower_6F_MapScript2_1C4F62:: @ 81C4F62
SevenIsland_TrainerTower_7F_MapScript2_1C4F62:: @ 81C4F62
SevenIsland_TrainerTower_8F_MapScript2_1C4F62:: @ 81C4F62
	.incbin "baserom.gba", 0x1C4F62, 0xE4

SevenIsland_TrainerTower_1F_MapScript3_1C5046:: @ 81C5046
SevenIsland_TrainerTower_2F_MapScript3_1C5046:: @ 81C5046
SevenIsland_TrainerTower_3F_MapScript3_1C5046:: @ 81C5046
SevenIsland_TrainerTower_4F_MapScript3_1C5046:: @ 81C5046
SevenIsland_TrainerTower_5F_MapScript3_1C5046:: @ 81C5046
SevenIsland_TrainerTower_6F_MapScript3_1C5046:: @ 81C5046
SevenIsland_TrainerTower_7F_MapScript3_1C5046:: @ 81C5046
SevenIsland_TrainerTower_8F_MapScript3_1C5046:: @ 81C5046
SevenIsland_TrainerTower_Elevator_MapScript2_1C5046:: @ 81C5046
SevenIsland_TrainerTower_Roof_MapScript2_1C5046:: @ 81C5046
	.incbin "baserom.gba", 0x1C5046, 0x2AE

EventScript_1C52F4:: @ 81C52F4
	.incbin "baserom.gba", 0x1C52F4, 0x47

EventScript_1C533B:: @ 81C533B
	.incbin "baserom.gba", 0x1C533B, 0x47

EventScript_1C5382:: @ 81C5382
	.incbin "baserom.gba", 0x1C5382, 0xA

EventScript_1C538C:: @ 81C538C
	.incbin "baserom.gba", 0x1C538C, 0x1E

EventScript_1C53AA:: @ 81C53AA
	.incbin "baserom.gba", 0x1C53AA, 0xF2

gUnknown_81C549C:: @ 81C549C
	.incbin "baserom.gba", 0x1C549C, 0x13

SevenIsland_TrainerTower_2F_EventScript_1C54AF:: @ 81C54AF
SevenIsland_TrainerTower_4F_EventScript_1C54AF:: @ 81C54AF
SevenIsland_TrainerTower_6F_EventScript_1C54AF:: @ 81C54AF
SevenIsland_TrainerTower_8F_EventScript_1C54AF:: @ 81C54AF
SevenIsland_TrainerTower_5F_EventScript_1C54AF:: @ 81C54AF
SevenIsland_TrainerTower_7F_EventScript_1C54AF:: @ 81C54AF
SevenIsland_TrainerTower_3F_EventScript_1C54AF:: @ 81C54AF
SevenIsland_TrainerTower_1F_EventScript_1C54AF:: @ 81C54AF
	.incbin "baserom.gba", 0x1C54AF, 0x5

SevenIsland_TrainerTower_2F_EventScript_1C54B4:: @ 81C54B4
SevenIsland_TrainerTower_4F_EventScript_1C54B4:: @ 81C54B4
SevenIsland_TrainerTower_6F_EventScript_1C54B4:: @ 81C54B4
SevenIsland_TrainerTower_8F_EventScript_1C54B4:: @ 81C54B4
SevenIsland_TrainerTower_5F_EventScript_1C54B4:: @ 81C54B4
SevenIsland_TrainerTower_7F_EventScript_1C54B4:: @ 81C54B4
SevenIsland_TrainerTower_3F_EventScript_1C54B4:: @ 81C54B4
SevenIsland_TrainerTower_1F_EventScript_1C54B4:: @ 81C54B4
	.incbin "baserom.gba", 0x1C54B4, 0x36

SevenIsland_TrainerTower_2F_EventScript_1C54EA:: @ 81C54EA
SevenIsland_TrainerTower_4F_EventScript_1C54EA:: @ 81C54EA
SevenIsland_TrainerTower_6F_EventScript_1C54EA:: @ 81C54EA
SevenIsland_TrainerTower_8F_EventScript_1C54EA:: @ 81C54EA
SevenIsland_TrainerTower_5F_EventScript_1C54EA:: @ 81C54EA
SevenIsland_TrainerTower_7F_EventScript_1C54EA:: @ 81C54EA
SevenIsland_TrainerTower_3F_EventScript_1C54EA:: @ 81C54EA
SevenIsland_TrainerTower_1F_EventScript_1C54EA:: @ 81C54EA
	.incbin "baserom.gba", 0x1C54EA, 0x71

gUnknown_81C555B:: @ 81C555B
	.incbin "baserom.gba", 0x1C555B, 0x6E

gUnknown_81C55C9:: @ 81C55C9
	.incbin "baserom.gba", 0x1C55C9, 0x21

gUnknown_81C55EA:: @ 81C55EA
	.incbin "baserom.gba", 0x1C55EA, 0x3B

gUnknown_81C5625:: @ 81C5625
	.incbin "baserom.gba", 0x1C5625, 0x22

gUnknown_81C5647:: @ 81C5647
	.incbin "baserom.gba", 0x1C5647, 0x23

@ 0xE5
gUnknown_81C566A:: @ 81C566A
	.incbin "baserom.gba", 0x1C566A, 0xE5

gOtherText_NewName:: @ 81C574F
	.string "NEW NAME$"

gNameChoice_Green:: @ 81C5758
	.string "GREEN$"

gNameChoice_Red:: @ 81C575E
	.string "RED$"

gNameChoice_Leaf:: @ 81C5762
	.string "LEAF$"

gNameChoice_Fire:: @ 81C5767
	.string "FIRE$"

gNameChoice_Gary:: @ 81C576C
	.string "GARY$"

gNameChoice_Kaz:: @ 81C5771
	.string "KAZ$"

gNameChoice_Toru:: @ 81C5775
	.string "TORU$"

gNameChoice_Ash:: @ 81C577A
	.string "ASH$"

gNameChoice_Kene:: @ 81C577E
	.string "KENE$"

gNameChoice_Geki:: @ 81C5783
	.string "GEKI$"

gNameChoice_Jak:: @ 81C5788
	.string "JAK$"

gNameChoice_Janne:: @ 81C578C
	.string "JANNE$"

gNameChoice_Jonn:: @ 81C5792
	.string "JONN$"

gNameChoice_Kamon:: @ 81C5797
	.string "KAMON$"

gNameChoice_Karl:: @ 81C579D
	.string "KARL$"

gNameChoice_Taylor:: @ 81C57A2
	.string "TAYLOR$"

gNameChoice_Oscar:: @ 81C57A9
	.string "OSCAR$"

gNameChoice_Hiro:: @ 81C57AF
	.string "HIRO$"

gNameChoice_Max:: @ 81C57B4
	.string "MAX$"

gNameChoice_Jon:: @ 81C57B8
	.string "JON$"

gNameChoice_Ralph:: @ 81C57BC
	.string "RALPH$"

gNameChoice_Kay:: @ 81C57C2
	.string "KAY$"

gNameChoice_Tosh:: @ 81C57C6
	.string "TOSH$"

gNameChoice_Roak:: @ 81C57CB
	.string "ROAK$"

gNameChoice_Omi:: @ 81C57D0
	.string "OMI$"

gNameChoice_Jodi:: @ 81C57D4
	.string "JODI$"

gNameChoice_Amanda:: @ 81C57D9
	.string "AMANDA$"

gNameChoice_Hillary:: @ 81C57E0
	.string "HILLARY$"

gNameChoice_Makey:: @ 81C57E8
	.string "MAKEY$"

gNameChoice_Michi:: @ 81C57EE
	.string "MICHI$"

gNameChoice_Paula:: @ 81C57F4
	.string "PAULA$"

gNameChoice_June:: @ 81C57FA
	.string "JUNE$"

gNameChoice_Cassie:: @ 81C57FF
	.string "CASSIE$"

gNameChoice_Rey:: @ 81C5806
	.string "REY$"

gNameChoice_Seda:: @ 81C580A
	.string "SEDA$"

gNameChoice_Kiko:: @ 81C580F
	.string "KIKO$"

gNameChoice_Mina:: @ 81C5814
	.string "MINA$"

gNameChoice_Norie:: @ 81C5819
	.string "NORIE$"

gNameChoice_Sai:: @ 81C581F
	.string "SAI$"

gNameChoice_Momo:: @ 81C5823
	.string "MOMO$"

gNameChoice_Suzi:: @ 81C5828
	.string "SUZI$"

gNewGame_HelpDocs1:: @ 81C582D
	.string "The various buttons will be explained in\n"
	.string "the order of their importance.$"

gNewGame_HelpDocs2:: @ 81C5875
	.string "Moves the main character.\n"
	.string "Also used to choose various data\n"
	.string "headings.$"

gNewGame_HelpDocs3:: @ 81C58BA
	.string "Used to confirm a choice, check\n"
	.string "things, chat, and scroll text.$"

gNewGame_HelpDocs4:: @ 81C58F9
	.string "Used to exit, cancel a choice,\n"
	.string "and cancel a mode.$"

gNewGame_HelpDocs5:: @ 81C592B
	.string "Press this button to open the\n"
	.string "MENU.$"

gNewGame_HelpDocs6:: @ 81C594F
	.string "Used to shift items and to use\n"
	.string "a registered item.$"

gNewGame_HelpDocs7:: @ 81C5981
	.string "If you need help playing the\n"
	.string "game, or on how to do things,\n"
	.string "press the L or R Button.$"

gOakText_AskPlayerGender:: @ 81C59D5
	.string "Now tell me. Are you a boy?\n"
	.string "Or are you a girl?$"

gNewGameAdventureIntro1::
	.string "In the world which you are about to\n"
	.string "enter, you will embark on a grand\n"
	.string "adventure with you as the hero.\n"
	.string "\n"
	.string "Speak to people and check things\n"
	.string "wherever you go, be it towns, roads,\n"
	.string "or caves. Gather information and\n"
	.string "hints from every source.$"

gNewGameAdventureIntro2::
	.string "New paths will open to you by helping\n"
	.string "people in need, overcoming challenges,\n"
	.string "and solving mysteries.\n"
	.string "\n"
	.string "At times, you will be challenged by\n"
	.string "others and attacked by wild creatures.\n"
	.string "Be brave and keep pushing on.$"

gNewGameAdventureIntro3::
	.string "Through your adventure, we hope\n"
	.string "that you will interact with all sorts\n"
	.string "of people and achieve personal growth.\n"
	.string "That is our biggest objective.\n"
	.string "\n"
	.string "Press the A Button, and let your\n"
	.string "adventure begin!$"

gOakText_WelcomeToTheWorld:: @ 81C5C78
	.string "Hello, there!\n"
	.string "Glad to meet you!\pWelcome to the world of POKéMON!\pMy name is OAK.\pPeople affectionately refer to me\n"
	.string "as the POKéMON PROFESSOR.\p$"

gOakText_WorldInhabited1:: @ 81C5D06
	.string "This world…$"

gOakText_WorldInhabited2:: @ 81C5D12
	.string "…is inhabited far and wide by\n"
	.string "creatures called POKéMON.\p$"

gOakText_PetsBattlingStudy:: @ 81C5D4B
	.string "For some people, POKéMON are pets.\n"
	.string "Others use them for battling.\pAs for myself…\pI study POKéMON as a profession.\p$"

gOakText_TellMeALittleAboutYourself:: @ 81C5DBD
	.string "But first, tell me a little about\n"
	.string "yourself.\p$"

gOakText_AskPlayerName:: @ 81C5DEA
	.string "Let's begin with your name.\n"
	.string "What is it?\p$"

gOakText_FinalizePlayerName:: @ 81C5E13
	.string "Right…\n"
	.string "So your name is {PLAYER}.$"

gOakText_IntroduceRival:: @ 81C5E2E
	.string "This is my grandson.\pHe's been your rival since you both\n"
	.string "were babies.\p…Erm, what was his name now?$"

gOakText_AskRivalName:: @ 81C5E91
	.string "Your rival's name, what was it now?$"

gOakText_ConfirmRivalName:: @ 81C5EB5
	.string "…Er, was it {RIVAL}?$"

gOakText_RememberRivalName:: @ 81C5EC5
	.string "That's right! I remember now!\n"
	.string "His name is {RIVAL}!\p$"

gOakText_LegendAboutToUnfold:: @ 81C5EF4
	.string "{PLAYER}!\pYour very own POKéMON legend is\n"
	.string "about to unfold!\pA world of dreams and adventures\n"
	.string "with POKéMON awaits! Let's go!$"

@ pokedude data
gUnknown_81C5F69::
	.string "POKé DUDE: The speedier of the\n"
	.string "battlers gets to attack first.$"

gUnknown_81C5FA7::
	.string "It looks like my RATTATA was\n"
	.string "faster than the PIDGEY.$"

gUnknown_81C5FDC::
	.string "The battlers take turns attacking\n"
	.string "and reducing each other's HP.$"

gUnknown_81C601C::
	.string "My RATTATA reduced the foe's HP\n"
	.string "to zero, so it wins!\p"

	.string "The POKéMON that took part in the\n"
	.string "battle get EXP. Points.\p"

	.string "When a POKéMON collects enough\n"
	.string "EXP. Points, it levels up.\p"

	.string "Leveling up makes your POKéMON\n"
	.string "stronger than before.$"

gUnknown_81C60FA::
	.string "POKé DUDE: Uh-oh…\n"
	.string "My RATTATA has been poisoned…\p"

	.string "If a POKéMON is poisoned, it loses\n"
	.string "HP steadily.$"

gUnknown_81C615A::
	.string "If a POKéMON develops a status\n"
	.string "problem, heal it right away.$"

gUnknown_81C6196::
	.string "Using an item on a POKéMON uses\n"
	.string "up one turn, though.\p"

	.string "Now, it's the opponent's turn!$"

gUnknown_81C61EA::
	.string "Yay!\n"
	.string "We managed to win!$"

gUnknown_81C6202::
	.string "POKé DUDE: The move BUBBLE is\n"
	.string "a WATER-type attack.\p"

	.string "The targeted ODDISH is a\n"
	.string "GRASS/POISON-type POKéMON.\p"

	.string "The WATER-type attack is absorbed\n"
	.string "by the GRASS-type POKéMON…\p"

	.string "As a result, the move becomes not\n"
	.string "very effective, and inflicts only\l"
	.string "half the usual damage.$"

gUnknown_81C6301::
	.string "Uh-oh, this is not good!\p"

	.string "The ABSORB attack you just saw\n"
	.string "is a GRASS-type move.\p"

	.string "POLIWAG is a WATER-type POKéMON.\p"

	.string "So, ABSORB becomes super\n"
	.string "effective, doubling the damage.$"

gUnknown_81C63A9::
	.string "It's not going to be easy to win\n"
	.string "with this matchup…\p"

	.string "Let's try shifting POKéMON!$"

gUnknown_81C63F9::
	.string "Shifting POKéMON in and out uses\n"
	.string "up one turn.\p"

	.string "Now, it's the opponent's turn.$"

gUnknown_81C6446::
	.string "BUTTERFREE is a BUG/FLYING-type\n"
	.string "POKéMON.\p"

	.string "Against this POKéMON, a GRASS-\n"
	.string "type attack…\p"

	.string "…inflicts only half the usual\n"
	.string "damage on a BUG-type POKéMON…\p"

	.string "…And, it also causes only half the\n"
	.string "damage on a FLYING-type POKéMON.\p"

	.string "Therefore, BUTTERFREE, being a\n"
	.string "BUG/FLYING POKéMON, only takes\l"
	.string "one quarter of the usual damage.$"

gUnknown_81C657A::
	.string "ODDISH is a GRASS/POISON-type\n"
	.string "POKéMON.\p"

	.string "A FLYING- or PSYCHIC-type attack\n"
	.string "is super effective against it.\p"

	.string "One of those types of attacks will\n"
	.string "inflict double the usual damage.\p"

	.string "Okay, here we go!$"

gUnknown_81C6637::
	.string "Yeah!\n"
	.string "We won!$"

gUnknown_81C6645::
	.string "POKé DUDE: When you're trying to\n"
	.string "catch a POKéMON, don't throw any\l"
	.string "POKé BALLS right away.\p"

	.string "First, you need to weaken it by\n"
	.string "reducing its HP.$"

gUnknown_81C66CF::
	.string "Okay, that should be good enough.\p"

	.string "But, if it's possible, it would be\n"
	.string "best if the target has a status\l"
	.string "problem.\p"

	.string "For instance, it would be easier\n"
	.string "to catch if it were asleep or\l"
	.string "paralyzed.$"

gUnknown_81C6787::
	.string "This will make the POKéMON a lot\n"
	.string "easier to catch!\p"

	.string "Oh, yes. If you paralyze a\n"
	.string "POKéMON, you can't make it fall\l"
	.string "asleep on top of paralysis.\p"

	.string "In other words, you can't double\n"
	.string "up status problems, okay?$"

gUnknown_81C684B::
	.string "Okay!\n"
	.string "Let me throw my POKé BALL!$"

gUnknown_81C686C::
	.string "Before you throw a POKé BALL,\n"
	.string "consider the condition and the\l"
	.string "type of POKéMON, and pick the kind\l"
	.string "of BALL that would work best.$"
