	.align 2
sWildMons_SevenIslandTanobyRuinsMoneanChamber_Land:: @ 83C73A0
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN

	.align 2
sWildMonInfo_SevenIslandTanobyRuinsMoneanChamber_Land:: @ 83C73D0
	.byte 7
	.align 2
	.4byte sWildMons_SevenIslandTanobyRuinsMoneanChamber_Land

	.align 2
sWildMons_SevenIslandTanobyRuinsLiptooChamber_Land:: @ 83C73D8
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN

	.align 2
sWildMonInfo_SevenIslandTanobyRuinsLiptooChamber_Land:: @ 83C7408
	.byte 7
	.align 2
	.4byte sWildMons_SevenIslandTanobyRuinsLiptooChamber_Land

	.align 2
sWildMons_SevenIslandTanobyRuinsWeepthChamber_Land:: @ 83C7410
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN

	.align 2
sWildMonInfo_SevenIslandTanobyRuinsWeepthChamber_Land:: @ 83C7440
	.byte 7
	.align 2
	.4byte sWildMons_SevenIslandTanobyRuinsWeepthChamber_Land

	.align 2
sWildMons_SevenIslandTanobyRuinsDilfordChamber_Land:: @ 83C7448
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN

	.align 2
sWildMonInfo_SevenIslandTanobyRuinsDilfordChamber_Land:: @ 83C7478
	.byte 7
	.align 2
	.4byte sWildMons_SevenIslandTanobyRuinsDilfordChamber_Land

	.align 2
sWildMons_SevenIslandTanobyRuinsScufibChamber_Land:: @ 83C7480
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN

	.align 2
sWildMonInfo_SevenIslandTanobyRuinsScufibChamber_Land:: @ 83C74B0
	.byte 7
	.align 2
	.4byte sWildMons_SevenIslandTanobyRuinsScufibChamber_Land

	.align 2
sWildMons_SevenIslandTanobyRuinsRixyChamber_Land:: @ 83C74B8
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN

	.align 2
sWildMonInfo_SevenIslandTanobyRuinsRixyChamber_Land:: @ 83C74E8
	.byte 7
	.align 2
	.4byte sWildMons_SevenIslandTanobyRuinsRixyChamber_Land

	.align 2
sWildMons_SevenIslandTanobyRuinsViapoisChamber_Land:: @ 83C74F0
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN
	.byte 25, 25
	.2byte SPECIES_UNOWN

	.align 2
sWildMonInfo_SevenIslandTanobyRuinsViapoisChamber_Land:: @ 83C7520
	.byte 7
	.align 2
	.4byte sWildMons_SevenIslandTanobyRuinsViapoisChamber_Land

	.align 2
sWildMons_ViridianForest_Land:: @ 83C7528
	.byte 4, 4
	.2byte SPECIES_CATERPIE
	.byte 4, 4
	.2byte SPECIES_WEEDLE
	.byte 5, 5
	.2byte SPECIES_CATERPIE
	.byte 5, 5
	.2byte SPECIES_WEEDLE
	.byte 3, 3
	.2byte SPECIES_CATERPIE
	.byte 3, 3
	.2byte SPECIES_WEEDLE
	.byte 5, 5
	.2byte SPECIES_METAPOD
	.byte 5, 5
	.2byte SPECIES_KAKUNA
	.byte 4, 4
	.2byte SPECIES_KAKUNA
	.byte 3, 3
	.2byte SPECIES_PIKACHU
	.byte 6, 6
	.2byte SPECIES_KAKUNA
	.byte 5, 5
	.2byte SPECIES_PIKACHU

	.align 2
sWildMonInfo_ViridianForest_Land:: @ 83C7558
	.byte 14
	.align 2
	.4byte sWildMons_ViridianForest_Land

	.align 2
sWildMons_MtMoon1F_Land:: @ 83C7560
	.byte 7, 7
	.2byte SPECIES_ZUBAT
	.byte 8, 8
	.2byte SPECIES_ZUBAT
	.byte 7, 7
	.2byte SPECIES_GEODUDE
	.byte 9, 9
	.2byte SPECIES_ZUBAT
	.byte 10, 10
	.2byte SPECIES_ZUBAT
	.byte 8, 8
	.2byte SPECIES_GEODUDE
	.byte 9, 9
	.2byte SPECIES_GEODUDE
	.byte 8, 8
	.2byte SPECIES_PARAS
	.byte 7, 7
	.2byte SPECIES_ZUBAT
	.byte 7, 7
	.2byte SPECIES_ZUBAT
	.byte 7, 7
	.2byte SPECIES_ZUBAT
	.byte 8, 8
	.2byte SPECIES_CLEFAIRY

	.align 2
sWildMonInfo_MtMoon1F_Land:: @ 83C7590
	.byte 7
	.align 2
	.4byte sWildMons_MtMoon1F_Land

	.align 2
sWildMons_MtMoonB1F_Land:: @ 83C7598
	.byte 7, 7
	.2byte SPECIES_PARAS
	.byte 8, 8
	.2byte SPECIES_PARAS
	.byte 5, 5
	.2byte SPECIES_PARAS
	.byte 6, 6
	.2byte SPECIES_PARAS
	.byte 9, 9
	.2byte SPECIES_PARAS
	.byte 10, 10
	.2byte SPECIES_PARAS
	.byte 7, 7
	.2byte SPECIES_PARAS
	.byte 8, 8
	.2byte SPECIES_PARAS
	.byte 5, 5
	.2byte SPECIES_PARAS
	.byte 6, 6
	.2byte SPECIES_PARAS
	.byte 9, 9
	.2byte SPECIES_PARAS
	.byte 10, 10
	.2byte SPECIES_PARAS

	.align 2
sWildMonInfo_MtMoonB1F_Land:: @ 83C75C8
	.byte 5
	.align 2
	.4byte sWildMons_MtMoonB1F_Land

	.align 2
sWildMons_MtMoonB2F_Land:: @ 83C75D0
	.byte 8, 8
	.2byte SPECIES_ZUBAT
	.byte 9, 9
	.2byte SPECIES_GEODUDE
	.byte 9, 9
	.2byte SPECIES_ZUBAT
	.byte 10, 10
	.2byte SPECIES_ZUBAT
	.byte 10, 10
	.2byte SPECIES_GEODUDE
	.byte 10, 10
	.2byte SPECIES_PARAS
	.byte 12, 12
	.2byte SPECIES_PARAS
	.byte 10, 10
	.2byte SPECIES_CLEFAIRY
	.byte 11, 11
	.2byte SPECIES_ZUBAT
	.byte 11, 11
	.2byte SPECIES_ZUBAT
	.byte 11, 11
	.2byte SPECIES_ZUBAT
	.byte 12, 12
	.2byte SPECIES_CLEFAIRY

	.align 2
sWildMonInfo_MtMoonB2F_Land:: @ 83C7600
	.byte 7
	.align 2
	.4byte sWildMons_MtMoonB2F_Land

	.align 2
sWildMons_SSAnneExterior_Water:: @ 83C7608
	.byte 5, 10
	.2byte SPECIES_TENTACOOL
	.byte 10, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 30
	.2byte SPECIES_TENTACOOL
	.byte 30, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL

	.align 2
sWildMonInfo_SSAnneExterior_Water:: @ 83C761C
	.byte 1
	.align 2
	.4byte sWildMons_SSAnneExterior_Water

	.align 2
sWildMons_SSAnneExterior_Fish:: @ 83C7624
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_KRABBY
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_SHELLDER
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_HORSEA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_SSAnneExterior_Fish:: @ 83C764C
	.byte 10
	.align 2
	.4byte sWildMons_SSAnneExterior_Fish

	.align 2
sWildMons_DiglettsCaveB1F_Land:: @ 83C7654
	.byte 18, 18
	.2byte SPECIES_DIGLETT
	.byte 19, 19
	.2byte SPECIES_DIGLETT
	.byte 17, 17
	.2byte SPECIES_DIGLETT
	.byte 15, 15
	.2byte SPECIES_DIGLETT
	.byte 16, 16
	.2byte SPECIES_DIGLETT
	.byte 20, 20
	.2byte SPECIES_DIGLETT
	.byte 21, 21
	.2byte SPECIES_DIGLETT
	.byte 22, 22
	.2byte SPECIES_DIGLETT
	.byte 17, 17
	.2byte SPECIES_DIGLETT
	.byte 29, 29
	.2byte SPECIES_DUGTRIO
	.byte 17, 17
	.2byte SPECIES_DIGLETT
	.byte 31, 31
	.2byte SPECIES_DUGTRIO

	.align 2
sWildMonInfo_DiglettsCaveB1F_Land:: @ 83C7684
	.byte 5
	.align 2
	.4byte sWildMons_DiglettsCaveB1F_Land

	.align 2
sWildMons_VictoryRoad1F_Land:: @ 83C768C
	.byte 32, 32
	.2byte SPECIES_MACHOP
	.byte 32, 32
	.2byte SPECIES_GEODUDE
	.byte 40, 40
	.2byte SPECIES_ONIX
	.byte 43, 43
	.2byte SPECIES_ONIX
	.byte 46, 46
	.2byte SPECIES_ONIX
	.byte 32, 32
	.2byte SPECIES_ZUBAT
	.byte 44, 44
	.2byte SPECIES_ARBOK
	.byte 44, 44
	.2byte SPECIES_GOLBAT
	.byte 44, 44
	.2byte SPECIES_MAROWAK
	.byte 44, 44
	.2byte SPECIES_MACHOKE
	.byte 46, 46
	.2byte SPECIES_MACHOKE
	.byte 46, 46
	.2byte SPECIES_MAROWAK

	.align 2
sWildMonInfo_VictoryRoad1F_Land:: @ 83C76BC
	.byte 7
	.align 2
	.4byte sWildMons_VictoryRoad1F_Land

	.align 2
sWildMons_VictoryRoad2F_Land:: @ 83C76C4
	.byte 34, 34
	.2byte SPECIES_MACHOP
	.byte 34, 34
	.2byte SPECIES_GEODUDE
	.byte 42, 42
	.2byte SPECIES_PRIMEAPE
	.byte 45, 45
	.2byte SPECIES_ONIX
	.byte 48, 48
	.2byte SPECIES_ONIX
	.byte 34, 34
	.2byte SPECIES_ZUBAT
	.byte 46, 46
	.2byte SPECIES_ARBOK
	.byte 46, 46
	.2byte SPECIES_GOLBAT
	.byte 46, 46
	.2byte SPECIES_MAROWAK
	.byte 46, 46
	.2byte SPECIES_MACHOKE
	.byte 48, 48
	.2byte SPECIES_MACHOKE
	.byte 48, 48
	.2byte SPECIES_MAROWAK

	.align 2
sWildMonInfo_VictoryRoad2F_Land:: @ 83C76F4
	.byte 7
	.align 2
	.4byte sWildMons_VictoryRoad2F_Land

	.align 2
sWildMons_VictoryRoad3F_Land:: @ 83C76FC
	.byte 32, 32
	.2byte SPECIES_MACHOP
	.byte 32, 32
	.2byte SPECIES_GEODUDE
	.byte 40, 40
	.2byte SPECIES_ONIX
	.byte 43, 43
	.2byte SPECIES_ONIX
	.byte 46, 46
	.2byte SPECIES_ONIX
	.byte 32, 32
	.2byte SPECIES_ZUBAT
	.byte 44, 44
	.2byte SPECIES_ARBOK
	.byte 44, 44
	.2byte SPECIES_GOLBAT
	.byte 44, 44
	.2byte SPECIES_MAROWAK
	.byte 44, 44
	.2byte SPECIES_MACHOKE
	.byte 46, 46
	.2byte SPECIES_MACHOKE
	.byte 46, 46
	.2byte SPECIES_MAROWAK

	.align 2
sWildMonInfo_VictoryRoad3F_Land:: @ 83C772C
	.byte 7
	.align 2
	.4byte sWildMons_VictoryRoad3F_Land

	.align 2
sWildMons_PokemonMansion1F_Land:: @ 83C7734
	.byte 28, 28
	.2byte SPECIES_KOFFING
	.byte 32, 32
	.2byte SPECIES_RATICATE
	.byte 30, 30
	.2byte SPECIES_KOFFING
	.byte 36, 36
	.2byte SPECIES_RATICATE
	.byte 30, 30
	.2byte SPECIES_GROWLITHE
	.byte 28, 28
	.2byte SPECIES_RATTATA
	.byte 28, 28
	.2byte SPECIES_GRIMER
	.byte 32, 32
	.2byte SPECIES_WEEZING
	.byte 32, 32
	.2byte SPECIES_GROWLITHE
	.byte 26, 26
	.2byte SPECIES_RATTATA
	.byte 32, 32
	.2byte SPECIES_GROWLITHE
	.byte 26, 26
	.2byte SPECIES_RATTATA

	.align 2
sWildMonInfo_PokemonMansion1F_Land:: @ 83C7764
	.byte 7
	.align 2
	.4byte sWildMons_PokemonMansion1F_Land

	.align 2
sWildMons_PokemonMansion2F_Land:: @ 83C776C
	.byte 28, 28
	.2byte SPECIES_KOFFING
	.byte 32, 32
	.2byte SPECIES_RATICATE
	.byte 30, 30
	.2byte SPECIES_KOFFING
	.byte 36, 36
	.2byte SPECIES_RATICATE
	.byte 30, 30
	.2byte SPECIES_GROWLITHE
	.byte 28, 28
	.2byte SPECIES_RATTATA
	.byte 28, 28
	.2byte SPECIES_GRIMER
	.byte 32, 32
	.2byte SPECIES_WEEZING
	.byte 32, 32
	.2byte SPECIES_GROWLITHE
	.byte 26, 26
	.2byte SPECIES_RATTATA
	.byte 32, 32
	.2byte SPECIES_GROWLITHE
	.byte 26, 26
	.2byte SPECIES_RATTATA

	.align 2
sWildMonInfo_PokemonMansion2F_Land:: @ 83C779C
	.byte 7
	.align 2
	.4byte sWildMons_PokemonMansion2F_Land

	.align 2
sWildMons_PokemonMansion3F_Land:: @ 83C77A4
	.byte 28, 28
	.2byte SPECIES_KOFFING
	.byte 32, 32
	.2byte SPECIES_RATICATE
	.byte 30, 30
	.2byte SPECIES_KOFFING
	.byte 36, 36
	.2byte SPECIES_RATICATE
	.byte 30, 30
	.2byte SPECIES_GROWLITHE
	.byte 28, 28
	.2byte SPECIES_RATTATA
	.byte 28, 28
	.2byte SPECIES_GRIMER
	.byte 32, 32
	.2byte SPECIES_WEEZING
	.byte 32, 32
	.2byte SPECIES_GROWLITHE
	.byte 26, 26
	.2byte SPECIES_RATTATA
	.byte 32, 32
	.2byte SPECIES_GROWLITHE
	.byte 26, 26
	.2byte SPECIES_RATTATA

	.align 2
sWildMonInfo_PokemonMansion3F_Land:: @ 83C77D4
	.byte 7
	.align 2
	.4byte sWildMons_PokemonMansion3F_Land

	.align 2
sWildMons_PokemonMansionB1F_Land:: @ 83C77DC
	.byte 28, 28
	.2byte SPECIES_KOFFING
	.byte 34, 34
	.2byte SPECIES_RATICATE
	.byte 30, 30
	.2byte SPECIES_KOFFING
	.byte 30, 30
	.2byte SPECIES_DITTO
	.byte 30, 30
	.2byte SPECIES_GROWLITHE
	.byte 38, 38
	.2byte SPECIES_RATICATE
	.byte 28, 28
	.2byte SPECIES_GRIMER
	.byte 34, 34
	.2byte SPECIES_WEEZING
	.byte 32, 32
	.2byte SPECIES_GROWLITHE
	.byte 26, 26
	.2byte SPECIES_RATTATA
	.byte 32, 32
	.2byte SPECIES_GROWLITHE
	.byte 26, 26
	.2byte SPECIES_RATTATA

	.align 2
sWildMonInfo_PokemonMansionB1F_Land:: @ 83C780C
	.byte 5
	.align 2
	.4byte sWildMons_PokemonMansionB1F_Land

	.align 2
sWildMons_SafariZoneCenter_Land:: @ 83C7814
	.byte 25, 25
	.2byte SPECIES_RHYHORN
	.byte 22, 22
	.2byte SPECIES_NIDORAN_M
	.byte 24, 24
	.2byte SPECIES_EXEGGCUTE
	.byte 25, 25
	.2byte SPECIES_EXEGGCUTE
	.byte 22, 22
	.2byte SPECIES_VENONAT
	.byte 31, 31
	.2byte SPECIES_NIDORINO
	.byte 31, 31
	.2byte SPECIES_NIDORINA
	.byte 30, 30
	.2byte SPECIES_PARASECT
	.byte 22, 22
	.2byte SPECIES_VENONAT
	.byte 23, 23
	.2byte SPECIES_SCYTHER
	.byte 22, 22
	.2byte SPECIES_VENONAT
	.byte 23, 23
	.2byte SPECIES_CHANSEY

	.align 2
sWildMonInfo_SafariZoneCenter_Land:: @ 83C7844
	.byte 21
	.align 2
	.4byte sWildMons_SafariZoneCenter_Land

	.align 2
sWildMons_SafariZoneCenter_Water:: @ 83C784C
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 30
	.2byte SPECIES_PSYDUCK
	.byte 30, 35
	.2byte SPECIES_PSYDUCK
	.byte 35, 40
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_SafariZoneCenter_Water:: @ 83C7860
	.byte 2
	.align 2
	.4byte sWildMons_SafariZoneCenter_Water

	.align 2
sWildMons_SafariZoneCenter_Fish:: @ 83C7868
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_GOLDEEN
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_POLIWAG
	.byte 15, 25
	.2byte SPECIES_GOLDEEN
	.byte 20, 30
	.2byte SPECIES_SEAKING
	.byte 15, 25
	.2byte SPECIES_DRATINI
	.byte 15, 35
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_DRAGONAIR

	.align 2
sWildMonInfo_SafariZoneCenter_Fish:: @ 83C7890
	.byte 20
	.align 2
	.4byte sWildMons_SafariZoneCenter_Fish

	.align 2
sWildMons_SafariZoneEast_Land:: @ 83C7898
	.byte 24, 24
	.2byte SPECIES_NIDORAN_M
	.byte 26, 26
	.2byte SPECIES_DODUO
	.byte 23, 23
	.2byte SPECIES_EXEGGCUTE
	.byte 25, 25
	.2byte SPECIES_EXEGGCUTE
	.byte 22, 22
	.2byte SPECIES_PARAS
	.byte 33, 33
	.2byte SPECIES_NIDORINO
	.byte 24, 24
	.2byte SPECIES_NIDORAN_F
	.byte 25, 25
	.2byte SPECIES_PARASECT
	.byte 22, 22
	.2byte SPECIES_PARAS
	.byte 25, 25
	.2byte SPECIES_KANGASKHAN
	.byte 22, 22
	.2byte SPECIES_PARAS
	.byte 28, 28
	.2byte SPECIES_SCYTHER

	.align 2
sWildMonInfo_SafariZoneEast_Land:: @ 83C78C8
	.byte 21
	.align 2
	.4byte sWildMons_SafariZoneEast_Land

	.align 2
sWildMons_SafariZoneEast_Water:: @ 83C78D0
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 30
	.2byte SPECIES_PSYDUCK
	.byte 30, 35
	.2byte SPECIES_PSYDUCK
	.byte 35, 40
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_SafariZoneEast_Water:: @ 83C78E4
	.byte 2
	.align 2
	.4byte sWildMons_SafariZoneEast_Water

	.align 2
sWildMons_SafariZoneEast_Fish:: @ 83C78EC
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_GOLDEEN
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_POLIWAG
	.byte 15, 25
	.2byte SPECIES_GOLDEEN
	.byte 20, 30
	.2byte SPECIES_SEAKING
	.byte 15, 25
	.2byte SPECIES_DRATINI
	.byte 15, 35
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_DRAGONAIR

	.align 2
sWildMonInfo_SafariZoneEast_Fish:: @ 83C7914
	.byte 20
	.align 2
	.4byte sWildMons_SafariZoneEast_Fish

	.align 2
sWildMons_SafariZoneNorth_Land:: @ 83C791C
	.byte 26, 26
	.2byte SPECIES_RHYHORN
	.byte 30, 30
	.2byte SPECIES_NIDORAN_M
	.byte 25, 25
	.2byte SPECIES_EXEGGCUTE
	.byte 27, 27
	.2byte SPECIES_EXEGGCUTE
	.byte 23, 23
	.2byte SPECIES_PARAS
	.byte 30, 30
	.2byte SPECIES_NIDORINO
	.byte 30, 30
	.2byte SPECIES_NIDORINA
	.byte 32, 32
	.2byte SPECIES_VENOMOTH
	.byte 23, 23
	.2byte SPECIES_PARAS
	.byte 26, 26
	.2byte SPECIES_CHANSEY
	.byte 23, 23
	.2byte SPECIES_PARAS
	.byte 28, 28
	.2byte SPECIES_TAUROS

	.align 2
sWildMonInfo_SafariZoneNorth_Land:: @ 83C794C
	.byte 21
	.align 2
	.4byte sWildMons_SafariZoneNorth_Land

	.align 2
sWildMons_SafariZoneNorth_Water:: @ 83C7954
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 30
	.2byte SPECIES_PSYDUCK
	.byte 30, 35
	.2byte SPECIES_PSYDUCK
	.byte 35, 40
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_SafariZoneNorth_Water:: @ 83C7968
	.byte 2
	.align 2
	.4byte sWildMons_SafariZoneNorth_Water

	.align 2
sWildMons_SafariZoneNorth_Fish:: @ 83C7970
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_GOLDEEN
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_POLIWAG
	.byte 15, 25
	.2byte SPECIES_GOLDEEN
	.byte 20, 30
	.2byte SPECIES_SEAKING
	.byte 15, 25
	.2byte SPECIES_DRATINI
	.byte 15, 35
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_DRAGONAIR

	.align 2
sWildMonInfo_SafariZoneNorth_Fish:: @ 83C7998
	.byte 20
	.align 2
	.4byte sWildMons_SafariZoneNorth_Fish

	.align 2
sWildMons_SafariZoneWest_Land:: @ 83C79A0
	.byte 26, 26
	.2byte SPECIES_DODUO
	.byte 22, 22
	.2byte SPECIES_NIDORAN_M
	.byte 25, 25
	.2byte SPECIES_EXEGGCUTE
	.byte 27, 27
	.2byte SPECIES_EXEGGCUTE
	.byte 23, 23
	.2byte SPECIES_VENONAT
	.byte 30, 30
	.2byte SPECIES_NIDORINO
	.byte 30, 30
	.2byte SPECIES_NIDORAN_F
	.byte 32, 32
	.2byte SPECIES_VENOMOTH
	.byte 23, 23
	.2byte SPECIES_VENONAT
	.byte 25, 25
	.2byte SPECIES_TAUROS
	.byte 23, 23
	.2byte SPECIES_VENONAT
	.byte 28, 28
	.2byte SPECIES_KANGASKHAN

	.align 2
sWildMonInfo_SafariZoneWest_Land:: @ 83C79D0
	.byte 21
	.align 2
	.4byte sWildMons_SafariZoneWest_Land

	.align 2
sWildMons_SafariZoneWest_Water:: @ 83C79D8
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 30
	.2byte SPECIES_PSYDUCK
	.byte 30, 35
	.2byte SPECIES_PSYDUCK
	.byte 35, 40
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_SafariZoneWest_Water:: @ 83C79EC
	.byte 2
	.align 2
	.4byte sWildMons_SafariZoneWest_Water

	.align 2
sWildMons_SafariZoneWest_Fish:: @ 83C79F4
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_GOLDEEN
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_POLIWAG
	.byte 15, 25
	.2byte SPECIES_GOLDEEN
	.byte 20, 30
	.2byte SPECIES_SEAKING
	.byte 15, 25
	.2byte SPECIES_DRATINI
	.byte 15, 35
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_DRAGONAIR

	.align 2
sWildMonInfo_SafariZoneWest_Fish:: @ 83C7A1C
	.byte 20
	.align 2
	.4byte sWildMons_SafariZoneWest_Fish

	.align 2
sWildMons_CeruleanCave1F_Land:: @ 83C7A24
	.byte 49, 49
	.2byte SPECIES_MAGNETON
	.byte 49, 49
	.2byte SPECIES_PARASECT
	.byte 46, 46
	.2byte SPECIES_GOLBAT
	.byte 46, 46
	.2byte SPECIES_MACHOKE
	.byte 52, 52
	.2byte SPECIES_PRIMEAPE
	.byte 52, 52
	.2byte SPECIES_DITTO
	.byte 58, 58
	.2byte SPECIES_ELECTRODE
	.byte 58, 58
	.2byte SPECIES_PARASECT
	.byte 55, 55
	.2byte SPECIES_GOLBAT
	.byte 55, 55
	.2byte SPECIES_WOBBUFFET
	.byte 61, 61
	.2byte SPECIES_PRIMEAPE
	.byte 61, 61
	.2byte SPECIES_DITTO

	.align 2
sWildMonInfo_CeruleanCave1F_Land:: @ 83C7A54
	.byte 7
	.align 2
	.4byte sWildMons_CeruleanCave1F_Land

	.align 2
sWildMons_CeruleanCave1F_Water:: @ 83C7A5C
	.byte 30, 40
	.2byte SPECIES_PSYDUCK
	.byte 40, 50
	.2byte SPECIES_GOLDUCK
	.byte 45, 55
	.2byte SPECIES_GOLDUCK
	.byte 40, 50
	.2byte SPECIES_PSYDUCK
	.byte 40, 50
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_CeruleanCave1F_Water:: @ 83C7A70
	.byte 2
	.align 2
	.4byte sWildMons_CeruleanCave1F_Water

	.align 2
sWildMons_CeruleanCave1F_Rock:: @ 83C7A78
	.byte 30, 40
	.2byte SPECIES_GEODUDE
	.byte 40, 50
	.2byte SPECIES_GRAVELER
	.byte 45, 55
	.2byte SPECIES_GRAVELER
	.byte 40, 50
	.2byte SPECIES_GEODUDE
	.byte 40, 50
	.2byte SPECIES_GEODUDE

	.align 2
sWildMonInfo_CeruleanCave1F_Rock:: @ 83C7A8C
	.byte 50
	.align 2
	.4byte sWildMons_CeruleanCave1F_Rock

	.align 2
sWildMons_CeruleanCave1F_Fish:: @ 83C7A94
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_POLIWAG
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_GOLDEEN
	.byte 15, 25
	.2byte SPECIES_POLIWAG
	.byte 20, 30
	.2byte SPECIES_POLIWHIRL
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 15, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_CeruleanCave1F_Fish:: @ 83C7ABC
	.byte 20
	.align 2
	.4byte sWildMons_CeruleanCave1F_Fish

	.align 2
sWildMons_CeruleanCave2F_Land:: @ 83C7AC4
	.byte 49, 49
	.2byte SPECIES_GOLBAT
	.byte 49, 49
	.2byte SPECIES_MACHOKE
	.byte 52, 52
	.2byte SPECIES_MAGNETON
	.byte 52, 52
	.2byte SPECIES_PARASECT
	.byte 55, 55
	.2byte SPECIES_KADABRA
	.byte 55, 55
	.2byte SPECIES_DITTO
	.byte 58, 58
	.2byte SPECIES_GOLBAT
	.byte 58, 58
	.2byte SPECIES_WOBBUFFET
	.byte 61, 61
	.2byte SPECIES_ELECTRODE
	.byte 61, 61
	.2byte SPECIES_PARASECT
	.byte 64, 64
	.2byte SPECIES_KADABRA
	.byte 64, 64
	.2byte SPECIES_DITTO

	.align 2
sWildMonInfo_CeruleanCave2F_Land:: @ 83C7AF4
	.byte 7
	.align 2
	.4byte sWildMons_CeruleanCave2F_Land

	.align 2
sWildMons_CeruleanCave2F_Rock:: @ 83C7AFC
	.byte 35, 45
	.2byte SPECIES_GEODUDE
	.byte 45, 55
	.2byte SPECIES_GRAVELER
	.byte 50, 60
	.2byte SPECIES_GRAVELER
	.byte 45, 55
	.2byte SPECIES_GEODUDE
	.byte 45, 55
	.2byte SPECIES_GEODUDE

	.align 2
sWildMonInfo_CeruleanCave2F_Rock:: @ 83C7B10
	.byte 50
	.align 2
	.4byte sWildMons_CeruleanCave2F_Rock

	.align 2
sWildMons_CeruleanCaveB1F_Land:: @ 83C7B18
	.byte 58, 58
	.2byte SPECIES_KADABRA
	.byte 58, 58
	.2byte SPECIES_DITTO
	.byte 55, 55
	.2byte SPECIES_MAGNETON
	.byte 55, 55
	.2byte SPECIES_PARASECT
	.byte 52, 52
	.2byte SPECIES_GOLBAT
	.byte 52, 52
	.2byte SPECIES_MACHOKE
	.byte 67, 67
	.2byte SPECIES_KADABRA
	.byte 67, 67
	.2byte SPECIES_DITTO
	.byte 64, 64
	.2byte SPECIES_ELECTRODE
	.byte 64, 64
	.2byte SPECIES_PARASECT
	.byte 61, 61
	.2byte SPECIES_GOLBAT
	.byte 61, 61
	.2byte SPECIES_WOBBUFFET

	.align 2
sWildMonInfo_CeruleanCaveB1F_Land:: @ 83C7B48
	.byte 7
	.align 2
	.4byte sWildMons_CeruleanCaveB1F_Land

	.align 2
sWildMons_CeruleanCaveB1F_Water:: @ 83C7B50
	.byte 40, 50
	.2byte SPECIES_PSYDUCK
	.byte 50, 60
	.2byte SPECIES_GOLDUCK
	.byte 55, 65
	.2byte SPECIES_GOLDUCK
	.byte 50, 60
	.2byte SPECIES_PSYDUCK
	.byte 50, 60
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_CeruleanCaveB1F_Water:: @ 83C7B64
	.byte 2
	.align 2
	.4byte sWildMons_CeruleanCaveB1F_Water

	.align 2
sWildMons_CeruleanCaveB1F_Rock:: @ 83C7B6C
	.byte 40, 50
	.2byte SPECIES_GEODUDE
	.byte 50, 60
	.2byte SPECIES_GRAVELER
	.byte 55, 65
	.2byte SPECIES_GRAVELER
	.byte 50, 60
	.2byte SPECIES_GEODUDE
	.byte 50, 60
	.2byte SPECIES_GEODUDE

	.align 2
sWildMonInfo_CeruleanCaveB1F_Rock:: @ 83C7B80
	.byte 50
	.align 2
	.4byte sWildMons_CeruleanCaveB1F_Rock

	.align 2
sWildMons_CeruleanCaveB1F_Fish:: @ 83C7B88
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_POLIWAG
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_GOLDEEN
	.byte 15, 25
	.2byte SPECIES_POLIWAG
	.byte 20, 30
	.2byte SPECIES_POLIWHIRL
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 15, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_GYARADOS

	.align 2
sWildMonInfo_CeruleanCaveB1F_Fish:: @ 83C7BB0
	.byte 20
	.align 2
	.4byte sWildMons_CeruleanCaveB1F_Fish

	.align 2
sWildMons_RockTunnel1F_Land:: @ 83C7BB8
	.byte 15, 15
	.2byte SPECIES_ZUBAT
	.byte 16, 16
	.2byte SPECIES_GEODUDE
	.byte 16, 16
	.2byte SPECIES_MANKEY
	.byte 17, 17
	.2byte SPECIES_GEODUDE
	.byte 16, 16
	.2byte SPECIES_ZUBAT
	.byte 16, 16
	.2byte SPECIES_MACHOP
	.byte 17, 17
	.2byte SPECIES_MANKEY
	.byte 17, 17
	.2byte SPECIES_MACHOP
	.byte 15, 15
	.2byte SPECIES_GEODUDE
	.byte 13, 13
	.2byte SPECIES_ONIX
	.byte 15, 15
	.2byte SPECIES_GEODUDE
	.byte 15, 15
	.2byte SPECIES_ONIX

	.align 2
sWildMonInfo_RockTunnel1F_Land:: @ 83C7BE8
	.byte 7
	.align 2
	.4byte sWildMons_RockTunnel1F_Land

	.align 2
sWildMons_RockTunnelB1F_Land:: @ 83C7BF0
	.byte 16, 16
	.2byte SPECIES_ZUBAT
	.byte 17, 17
	.2byte SPECIES_GEODUDE
	.byte 17, 17
	.2byte SPECIES_MANKEY
	.byte 16, 16
	.2byte SPECIES_GEODUDE
	.byte 15, 15
	.2byte SPECIES_ZUBAT
	.byte 17, 17
	.2byte SPECIES_MACHOP
	.byte 16, 16
	.2byte SPECIES_MANKEY
	.byte 13, 13
	.2byte SPECIES_ONIX
	.byte 15, 15
	.2byte SPECIES_GEODUDE
	.byte 15, 15
	.2byte SPECIES_ONIX
	.byte 15, 15
	.2byte SPECIES_GEODUDE
	.byte 17, 17
	.2byte SPECIES_ONIX

	.align 2
sWildMonInfo_RockTunnelB1F_Land:: @ 83C7C20
	.byte 7
	.align 2
	.4byte sWildMons_RockTunnelB1F_Land

	.align 2
sWildMons_RockTunnelB1F_Rock:: @ 83C7C28
	.byte 5, 20
	.2byte SPECIES_GEODUDE
	.byte 10, 20
	.2byte SPECIES_GEODUDE
	.byte 15, 30
	.2byte SPECIES_GEODUDE
	.byte 25, 40
	.2byte SPECIES_GRAVELER
	.byte 30, 40
	.2byte SPECIES_GRAVELER

	.align 2
sWildMonInfo_RockTunnelB1F_Rock:: @ 83C7C3C
	.byte 50
	.align 2
	.4byte sWildMons_RockTunnelB1F_Rock

	.align 2
sWildMons_SeafoamIslands1F_Land:: @ 83C7C44
	.byte 27, 27
	.2byte SPECIES_PSYDUCK
	.byte 29, 29
	.2byte SPECIES_PSYDUCK
	.byte 31, 31
	.2byte SPECIES_PSYDUCK
	.byte 22, 22
	.2byte SPECIES_ZUBAT
	.byte 22, 22
	.2byte SPECIES_ZUBAT
	.byte 24, 24
	.2byte SPECIES_ZUBAT
	.byte 26, 26
	.2byte SPECIES_GOLBAT
	.byte 28, 28
	.2byte SPECIES_GOLBAT
	.byte 33, 33
	.2byte SPECIES_PSYDUCK
	.byte 26, 26
	.2byte SPECIES_ZUBAT
	.byte 26, 26
	.2byte SPECIES_PSYDUCK
	.byte 30, 30
	.2byte SPECIES_GOLBAT

	.align 2
sWildMonInfo_SeafoamIslands1F_Land:: @ 83C7C74
	.byte 7
	.align 2
	.4byte sWildMons_SeafoamIslands1F_Land

	.align 2
sWildMons_SeafoamIslandsB1F_Land:: @ 83C7C7C
	.byte 29, 29
	.2byte SPECIES_PSYDUCK
	.byte 31, 31
	.2byte SPECIES_PSYDUCK
	.byte 28, 28
	.2byte SPECIES_SEEL
	.byte 22, 22
	.2byte SPECIES_ZUBAT
	.byte 22, 22
	.2byte SPECIES_ZUBAT
	.byte 24, 24
	.2byte SPECIES_ZUBAT
	.byte 26, 26
	.2byte SPECIES_GOLBAT
	.byte 28, 28
	.2byte SPECIES_GOLBAT
	.byte 33, 33
	.2byte SPECIES_GOLDUCK
	.byte 26, 26
	.2byte SPECIES_ZUBAT
	.byte 35, 35
	.2byte SPECIES_GOLDUCK
	.byte 30, 30
	.2byte SPECIES_GOLBAT

	.align 2
sWildMonInfo_SeafoamIslandsB1F_Land:: @ 83C7CAC
	.byte 7
	.align 2
	.4byte sWildMons_SeafoamIslandsB1F_Land

	.align 2
sWildMons_SeafoamIslandsB2F_Land:: @ 83C7CB4
	.byte 30, 30
	.2byte SPECIES_PSYDUCK
	.byte 32, 32
	.2byte SPECIES_PSYDUCK
	.byte 30, 30
	.2byte SPECIES_SEEL
	.byte 32, 32
	.2byte SPECIES_SEEL
	.byte 22, 22
	.2byte SPECIES_ZUBAT
	.byte 24, 24
	.2byte SPECIES_ZUBAT
	.byte 26, 26
	.2byte SPECIES_GOLBAT
	.byte 34, 34
	.2byte SPECIES_GOLDUCK
	.byte 32, 32
	.2byte SPECIES_GOLDUCK
	.byte 28, 28
	.2byte SPECIES_GOLBAT
	.byte 32, 32
	.2byte SPECIES_GOLDUCK
	.byte 30, 30
	.2byte SPECIES_GOLBAT

	.align 2
sWildMonInfo_SeafoamIslandsB2F_Land:: @ 83C7CE4
	.byte 7
	.align 2
	.4byte sWildMons_SeafoamIslandsB2F_Land

	.align 2
sWildMons_SeafoamIslandsB3F_Land:: @ 83C7CEC
	.byte 30, 30
	.2byte SPECIES_SEEL
	.byte 32, 32
	.2byte SPECIES_SEEL
	.byte 32, 32
	.2byte SPECIES_PSYDUCK
	.byte 30, 30
	.2byte SPECIES_PSYDUCK
	.byte 32, 32
	.2byte SPECIES_GOLDUCK
	.byte 24, 24
	.2byte SPECIES_ZUBAT
	.byte 26, 26
	.2byte SPECIES_GOLBAT
	.byte 34, 34
	.2byte SPECIES_GOLDUCK
	.byte 32, 32
	.2byte SPECIES_DEWGONG
	.byte 28, 28
	.2byte SPECIES_GOLBAT
	.byte 34, 34
	.2byte SPECIES_DEWGONG
	.byte 30, 30
	.2byte SPECIES_GOLBAT

	.align 2
sWildMonInfo_SeafoamIslandsB3F_Land:: @ 83C7D1C
	.byte 7
	.align 2
	.4byte sWildMons_SeafoamIslandsB3F_Land

	.align 2
sWildMons_SeafoamIslandsB3F_Water:: @ 83C7D24
	.byte 25, 35
	.2byte SPECIES_SEEL
	.byte 25, 30
	.2byte SPECIES_HORSEA
	.byte 35, 40
	.2byte SPECIES_DEWGONG
	.byte 30, 40
	.2byte SPECIES_PSYDUCK
	.byte 35, 40
	.2byte SPECIES_GOLDUCK

	.align 2
sWildMonInfo_SeafoamIslandsB3F_Water:: @ 83C7D38
	.byte 2
	.align 2
	.4byte sWildMons_SeafoamIslandsB3F_Water

	.align 2
sWildMons_SeafoamIslandsB3F_Fish:: @ 83C7D40
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_KRABBY
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 20, 30
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 15, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_GYARADOS

	.align 2
sWildMonInfo_SeafoamIslandsB3F_Fish:: @ 83C7D68
	.byte 20
	.align 2
	.4byte sWildMons_SeafoamIslandsB3F_Fish

	.align 2
sWildMons_SeafoamIslandsB4F_Land:: @ 83C7D70
	.byte 30, 30
	.2byte SPECIES_SEEL
	.byte 32, 32
	.2byte SPECIES_SEEL
	.byte 32, 32
	.2byte SPECIES_PSYDUCK
	.byte 34, 34
	.2byte SPECIES_SEEL
	.byte 32, 32
	.2byte SPECIES_GOLDUCK
	.byte 26, 26
	.2byte SPECIES_GOLBAT
	.byte 34, 34
	.2byte SPECIES_DEWGONG
	.byte 34, 34
	.2byte SPECIES_GOLDUCK
	.byte 36, 36
	.2byte SPECIES_DEWGONG
	.byte 28, 28
	.2byte SPECIES_GOLBAT
	.byte 36, 36
	.2byte SPECIES_DEWGONG
	.byte 30, 30
	.2byte SPECIES_GOLBAT

	.align 2
sWildMonInfo_SeafoamIslandsB4F_Land:: @ 83C7DA0
	.byte 7
	.align 2
	.4byte sWildMons_SeafoamIslandsB4F_Land

	.align 2
sWildMons_SeafoamIslandsB4F_Water:: @ 83C7DA8
	.byte 25, 35
	.2byte SPECIES_SEEL
	.byte 25, 30
	.2byte SPECIES_HORSEA
	.byte 35, 40
	.2byte SPECIES_DEWGONG
	.byte 30, 40
	.2byte SPECIES_PSYDUCK
	.byte 35, 40
	.2byte SPECIES_GOLDUCK

	.align 2
sWildMonInfo_SeafoamIslandsB4F_Water:: @ 83C7DBC
	.byte 2
	.align 2
	.4byte sWildMons_SeafoamIslandsB4F_Water

	.align 2
sWildMons_SeafoamIslandsB4F_Fish:: @ 83C7DC4
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_KRABBY
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 20, 30
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 15, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_GYARADOS

	.align 2
sWildMonInfo_SeafoamIslandsB4F_Fish:: @ 83C7DEC
	.byte 20
	.align 2
	.4byte sWildMons_SeafoamIslandsB4F_Fish

	.align 2
sWildMons_PokemonTower3F_Land:: @ 83C7DF4
	.byte 15, 15
	.2byte SPECIES_GASTLY
	.byte 16, 16
	.2byte SPECIES_GASTLY
	.byte 17, 17
	.2byte SPECIES_GASTLY
	.byte 13, 13
	.2byte SPECIES_GASTLY
	.byte 14, 14
	.2byte SPECIES_GASTLY
	.byte 18, 18
	.2byte SPECIES_GASTLY
	.byte 19, 19
	.2byte SPECIES_GASTLY
	.byte 15, 15
	.2byte SPECIES_CUBONE
	.byte 17, 17
	.2byte SPECIES_GASTLY
	.byte 17, 17
	.2byte SPECIES_CUBONE
	.byte 17, 17
	.2byte SPECIES_GASTLY
	.byte 20, 20
	.2byte SPECIES_HAUNTER

	.align 2
sWildMonInfo_PokemonTower3F_Land:: @ 83C7E24
	.byte 2
	.align 2
	.4byte sWildMons_PokemonTower3F_Land

	.align 2
sWildMons_PokemonTower4F_Land:: @ 83C7E2C
	.byte 15, 15
	.2byte SPECIES_GASTLY
	.byte 16, 16
	.2byte SPECIES_GASTLY
	.byte 17, 17
	.2byte SPECIES_GASTLY
	.byte 13, 13
	.2byte SPECIES_GASTLY
	.byte 14, 14
	.2byte SPECIES_GASTLY
	.byte 18, 18
	.2byte SPECIES_GASTLY
	.byte 20, 20
	.2byte SPECIES_HAUNTER
	.byte 15, 15
	.2byte SPECIES_CUBONE
	.byte 17, 17
	.2byte SPECIES_GASTLY
	.byte 17, 17
	.2byte SPECIES_CUBONE
	.byte 17, 17
	.2byte SPECIES_GASTLY
	.byte 19, 19
	.2byte SPECIES_GASTLY

	.align 2
sWildMonInfo_PokemonTower4F_Land:: @ 83C7E5C
	.byte 4
	.align 2
	.4byte sWildMons_PokemonTower4F_Land

	.align 2
sWildMons_PokemonTower5F_Land:: @ 83C7E64
	.byte 15, 15
	.2byte SPECIES_GASTLY
	.byte 16, 16
	.2byte SPECIES_GASTLY
	.byte 17, 17
	.2byte SPECIES_GASTLY
	.byte 13, 13
	.2byte SPECIES_GASTLY
	.byte 14, 14
	.2byte SPECIES_GASTLY
	.byte 18, 18
	.2byte SPECIES_GASTLY
	.byte 20, 20
	.2byte SPECIES_HAUNTER
	.byte 15, 15
	.2byte SPECIES_CUBONE
	.byte 17, 17
	.2byte SPECIES_GASTLY
	.byte 17, 17
	.2byte SPECIES_CUBONE
	.byte 17, 17
	.2byte SPECIES_GASTLY
	.byte 19, 19
	.2byte SPECIES_GASTLY

	.align 2
sWildMonInfo_PokemonTower5F_Land:: @ 83C7E94
	.byte 6
	.align 2
	.4byte sWildMons_PokemonTower5F_Land

	.align 2
sWildMons_PokemonTower6F_Land:: @ 83C7E9C
	.byte 16, 16
	.2byte SPECIES_GASTLY
	.byte 17, 17
	.2byte SPECIES_GASTLY
	.byte 18, 18
	.2byte SPECIES_GASTLY
	.byte 14, 14
	.2byte SPECIES_GASTLY
	.byte 15, 15
	.2byte SPECIES_GASTLY
	.byte 19, 19
	.2byte SPECIES_GASTLY
	.byte 21, 21
	.2byte SPECIES_HAUNTER
	.byte 17, 17
	.2byte SPECIES_CUBONE
	.byte 18, 18
	.2byte SPECIES_GASTLY
	.byte 19, 19
	.2byte SPECIES_CUBONE
	.byte 18, 18
	.2byte SPECIES_GASTLY
	.byte 23, 23
	.2byte SPECIES_HAUNTER

	.align 2
sWildMonInfo_PokemonTower6F_Land:: @ 83C7ECC
	.byte 8
	.align 2
	.4byte sWildMons_PokemonTower6F_Land

	.align 2
sWildMons_PokemonTower7F_Land:: @ 83C7ED4
	.byte 16, 16
	.2byte SPECIES_GASTLY
	.byte 17, 17
	.2byte SPECIES_GASTLY
	.byte 18, 18
	.2byte SPECIES_GASTLY
	.byte 15, 15
	.2byte SPECIES_GASTLY
	.byte 19, 19
	.2byte SPECIES_GASTLY
	.byte 23, 23
	.2byte SPECIES_HAUNTER
	.byte 17, 17
	.2byte SPECIES_CUBONE
	.byte 19, 19
	.2byte SPECIES_CUBONE
	.byte 18, 18
	.2byte SPECIES_GASTLY
	.byte 23, 23
	.2byte SPECIES_HAUNTER
	.byte 18, 18
	.2byte SPECIES_GASTLY
	.byte 25, 25
	.2byte SPECIES_HAUNTER

	.align 2
sWildMonInfo_PokemonTower7F_Land:: @ 83C7F04
	.byte 10
	.align 2
	.4byte sWildMons_PokemonTower7F_Land

	.align 2
sWildMons_PowerPlant_Land:: @ 83C7F0C
	.byte 22, 22
	.2byte SPECIES_VOLTORB
	.byte 22, 22
	.2byte SPECIES_MAGNEMITE
	.byte 25, 25
	.2byte SPECIES_VOLTORB
	.byte 25, 25
	.2byte SPECIES_MAGNEMITE
	.byte 22, 22
	.2byte SPECIES_PIKACHU
	.byte 24, 24
	.2byte SPECIES_PIKACHU
	.byte 31, 31
	.2byte SPECIES_MAGNETON
	.byte 34, 34
	.2byte SPECIES_MAGNETON
	.byte 26, 26
	.2byte SPECIES_PIKACHU
	.byte 32, 32
	.2byte SPECIES_ELECTABUZZ
	.byte 26, 26
	.2byte SPECIES_PIKACHU
	.byte 35, 35
	.2byte SPECIES_ELECTABUZZ

	.align 2
sWildMonInfo_PowerPlant_Land:: @ 83C7F3C
	.byte 7
	.align 2
	.4byte sWildMons_PowerPlant_Land

	.align 2
sWildMons_MtEmberExterior_Land:: @ 83C7F44
	.byte 30, 30
	.2byte SPECIES_PONYTA
	.byte 38, 38
	.2byte SPECIES_FEAROW
	.byte 33, 33
	.2byte SPECIES_PONYTA
	.byte 32, 32
	.2byte SPECIES_SPEAROW
	.byte 35, 35
	.2byte SPECIES_MACHOP
	.byte 33, 33
	.2byte SPECIES_GEODUDE
	.byte 36, 36
	.2byte SPECIES_PONYTA
	.byte 40, 40
	.2byte SPECIES_FEAROW
	.byte 30, 30
	.2byte SPECIES_SPEAROW
	.byte 39, 39
	.2byte SPECIES_RAPIDASH
	.byte 30, 30
	.2byte SPECIES_SPEAROW
	.byte 42, 42
	.2byte SPECIES_RAPIDASH

	.align 2
sWildMonInfo_MtEmberExterior_Land:: @ 83C7F74
	.byte 21
	.align 2
	.4byte sWildMons_MtEmberExterior_Land

	.align 2
sWildMons_MtEmberExterior_Rock:: @ 83C7F7C
	.byte 5, 20
	.2byte SPECIES_GEODUDE
	.byte 10, 20
	.2byte SPECIES_GEODUDE
	.byte 15, 30
	.2byte SPECIES_GEODUDE
	.byte 25, 40
	.2byte SPECIES_GRAVELER
	.byte 30, 40
	.2byte SPECIES_GRAVELER

	.align 2
sWildMonInfo_MtEmberExterior_Rock:: @ 83C7F90
	.byte 50
	.align 2
	.4byte sWildMons_MtEmberExterior_Rock

	.align 2
sWildMons_MtEmberSummitPath1F_Land:: @ 83C7F98
	.byte 33, 33
	.2byte SPECIES_GEODUDE
	.byte 35, 35
	.2byte SPECIES_MACHOP
	.byte 29, 29
	.2byte SPECIES_GEODUDE
	.byte 31, 31
	.2byte SPECIES_GEODUDE
	.byte 31, 31
	.2byte SPECIES_MACHOP
	.byte 33, 33
	.2byte SPECIES_MACHOP
	.byte 35, 35
	.2byte SPECIES_GEODUDE
	.byte 37, 37
	.2byte SPECIES_MACHOP
	.byte 37, 37
	.2byte SPECIES_GEODUDE
	.byte 39, 39
	.2byte SPECIES_MACHOP
	.byte 37, 37
	.2byte SPECIES_GEODUDE
	.byte 39, 39
	.2byte SPECIES_MACHOP

	.align 2
sWildMonInfo_MtEmberSummitPath1F_Land:: @ 83C7FC8
	.byte 7
	.align 2
	.4byte sWildMons_MtEmberSummitPath1F_Land

	.align 2
sWildMons_MtEmberSummitPath2F_Land:: @ 83C7FD0
	.byte 34, 34
	.2byte SPECIES_GEODUDE
	.byte 36, 36
	.2byte SPECIES_MACHOP
	.byte 30, 30
	.2byte SPECIES_GEODUDE
	.byte 32, 32
	.2byte SPECIES_GEODUDE
	.byte 32, 32
	.2byte SPECIES_MACHOP
	.byte 34, 34
	.2byte SPECIES_MACHOP
	.byte 38, 38
	.2byte SPECIES_MACHOKE
	.byte 38, 38
	.2byte SPECIES_MACHOKE
	.byte 40, 40
	.2byte SPECIES_MACHOKE
	.byte 40, 40
	.2byte SPECIES_MACHOKE
	.byte 40, 40
	.2byte SPECIES_MACHOKE
	.byte 40, 40
	.2byte SPECIES_MACHOKE

	.align 2
sWildMonInfo_MtEmberSummitPath2F_Land:: @ 83C8000
	.byte 7
	.align 2
	.4byte sWildMons_MtEmberSummitPath2F_Land

	.align 2
sWildMons_MtEmberSummitPath2F_Rock:: @ 83C8008
	.byte 5, 20
	.2byte SPECIES_GEODUDE
	.byte 10, 20
	.2byte SPECIES_GEODUDE
	.byte 15, 30
	.2byte SPECIES_GEODUDE
	.byte 25, 40
	.2byte SPECIES_GRAVELER
	.byte 30, 40
	.2byte SPECIES_GRAVELER

	.align 2
sWildMonInfo_MtEmberSummitPath2F_Rock:: @ 83C801C
	.byte 50
	.align 2
	.4byte sWildMons_MtEmberSummitPath2F_Rock

	.align 2
sWildMons_MtEmberSummitPath3F_Land:: @ 83C8024
	.byte 33, 33
	.2byte SPECIES_GEODUDE
	.byte 35, 35
	.2byte SPECIES_MACHOP
	.byte 29, 29
	.2byte SPECIES_GEODUDE
	.byte 31, 31
	.2byte SPECIES_GEODUDE
	.byte 31, 31
	.2byte SPECIES_MACHOP
	.byte 33, 33
	.2byte SPECIES_MACHOP
	.byte 35, 35
	.2byte SPECIES_GEODUDE
	.byte 37, 37
	.2byte SPECIES_MACHOP
	.byte 37, 37
	.2byte SPECIES_GEODUDE
	.byte 39, 39
	.2byte SPECIES_MACHOP
	.byte 37, 37
	.2byte SPECIES_GEODUDE
	.byte 39, 39
	.2byte SPECIES_MACHOP

	.align 2
sWildMonInfo_MtEmberSummitPath3F_Land:: @ 83C8054
	.byte 7
	.align 2
	.4byte sWildMons_MtEmberSummitPath3F_Land

	.align 2
sWildMons_MtEmberRubyPath1F_Land:: @ 83C805C
	.byte 36, 36
	.2byte SPECIES_GEODUDE
	.byte 38, 38
	.2byte SPECIES_MACHOP
	.byte 32, 32
	.2byte SPECIES_GEODUDE
	.byte 34, 34
	.2byte SPECIES_GEODUDE
	.byte 34, 34
	.2byte SPECIES_MACHOP
	.byte 36, 36
	.2byte SPECIES_MACHOP
	.byte 38, 38
	.2byte SPECIES_GEODUDE
	.byte 40, 40
	.2byte SPECIES_MACHOKE
	.byte 40, 40
	.2byte SPECIES_GEODUDE
	.byte 42, 42
	.2byte SPECIES_MACHOKE
	.byte 40, 40
	.2byte SPECIES_GEODUDE
	.byte 42, 42
	.2byte SPECIES_MACHOKE

	.align 2
sWildMonInfo_MtEmberRubyPath1F_Land:: @ 83C808C
	.byte 7
	.align 2
	.4byte sWildMons_MtEmberRubyPath1F_Land

	.align 2
sWildMons_MtEmberRubyPath1F_Rock:: @ 83C8094
	.byte 25, 35
	.2byte SPECIES_GEODUDE
	.byte 30, 45
	.2byte SPECIES_GRAVELER
	.byte 35, 50
	.2byte SPECIES_GRAVELER
	.byte 30, 40
	.2byte SPECIES_GEODUDE
	.byte 30, 40
	.2byte SPECIES_GEODUDE

	.align 2
sWildMonInfo_MtEmberRubyPath1F_Rock:: @ 83C80A8
	.byte 50
	.align 2
	.4byte sWildMons_MtEmberRubyPath1F_Rock

	.align 2
sWildMons_MtEmberRubyPathB1F_Land:: @ 83C80B0
	.byte 38, 38
	.2byte SPECIES_GEODUDE
	.byte 36, 36
	.2byte SPECIES_GEODUDE
	.byte 34, 34
	.2byte SPECIES_GEODUDE
	.byte 40, 40
	.2byte SPECIES_GEODUDE
	.byte 24, 24
	.2byte SPECIES_SLUGMA
	.byte 26, 26
	.2byte SPECIES_SLUGMA
	.byte 42, 42
	.2byte SPECIES_GEODUDE
	.byte 28, 28
	.2byte SPECIES_SLUGMA
	.byte 42, 42
	.2byte SPECIES_GEODUDE
	.byte 30, 30
	.2byte SPECIES_SLUGMA
	.byte 42, 42
	.2byte SPECIES_GEODUDE
	.byte 30, 30
	.2byte SPECIES_SLUGMA

	.align 2
sWildMonInfo_MtEmberRubyPathB1F_Land:: @ 83C80E0
	.byte 7
	.align 2
	.4byte sWildMons_MtEmberRubyPathB1F_Land

	.align 2
sWildMons_MtEmberRubyPathB1F_Rock:: @ 83C80E8
	.byte 25, 35
	.2byte SPECIES_GEODUDE
	.byte 30, 45
	.2byte SPECIES_GRAVELER
	.byte 35, 50
	.2byte SPECIES_GRAVELER
	.byte 30, 40
	.2byte SPECIES_GEODUDE
	.byte 30, 40
	.2byte SPECIES_GEODUDE

	.align 2
sWildMonInfo_MtEmberRubyPathB1F_Rock:: @ 83C80FC
	.byte 50
	.align 2
	.4byte sWildMons_MtEmberRubyPathB1F_Rock

	.align 2
sWildMons_MtEmberRubyPathB2F_Land:: @ 83C8104
	.byte 40, 40
	.2byte SPECIES_GEODUDE
	.byte 26, 26
	.2byte SPECIES_SLUGMA
	.byte 42, 42
	.2byte SPECIES_GEODUDE
	.byte 24, 24
	.2byte SPECIES_SLUGMA
	.byte 28, 28
	.2byte SPECIES_SLUGMA
	.byte 30, 30
	.2byte SPECIES_SLUGMA
	.byte 44, 44
	.2byte SPECIES_GEODUDE
	.byte 32, 32
	.2byte SPECIES_SLUGMA
	.byte 44, 44
	.2byte SPECIES_GEODUDE
	.byte 22, 22
	.2byte SPECIES_SLUGMA
	.byte 44, 44
	.2byte SPECIES_GEODUDE
	.byte 22, 22
	.2byte SPECIES_SLUGMA

	.align 2
sWildMonInfo_MtEmberRubyPathB2F_Land:: @ 83C8134
	.byte 7
	.align 2
	.4byte sWildMons_MtEmberRubyPathB2F_Land

	.align 2
sWildMons_MtEmberRubyPathB2F_Rock:: @ 83C813C
	.byte 25, 35
	.2byte SPECIES_GEODUDE
	.byte 30, 45
	.2byte SPECIES_GRAVELER
	.byte 35, 50
	.2byte SPECIES_GRAVELER
	.byte 30, 40
	.2byte SPECIES_GEODUDE
	.byte 30, 40
	.2byte SPECIES_GEODUDE

	.align 2
sWildMonInfo_MtEmberRubyPathB2F_Rock:: @ 83C8150
	.byte 50
	.align 2
	.4byte sWildMons_MtEmberRubyPathB2F_Rock

	.align 2
sWildMons_MtEmberRubyPathB3F_Land:: @ 83C8158
	.byte 26, 26
	.2byte SPECIES_SLUGMA
	.byte 28, 28
	.2byte SPECIES_SLUGMA
	.byte 30, 30
	.2byte SPECIES_SLUGMA
	.byte 32, 32
	.2byte SPECIES_SLUGMA
	.byte 24, 24
	.2byte SPECIES_SLUGMA
	.byte 22, 22
	.2byte SPECIES_SLUGMA
	.byte 20, 20
	.2byte SPECIES_SLUGMA
	.byte 34, 34
	.2byte SPECIES_SLUGMA
	.byte 36, 36
	.2byte SPECIES_SLUGMA
	.byte 18, 18
	.2byte SPECIES_SLUGMA
	.byte 36, 36
	.2byte SPECIES_SLUGMA
	.byte 18, 18
	.2byte SPECIES_SLUGMA

	.align 2
sWildMonInfo_MtEmberRubyPathB3F_Land:: @ 83C8188
	.byte 7
	.align 2
	.4byte sWildMons_MtEmberRubyPathB3F_Land

	.align 2
sWildMons_MtEmberRubyPathB3F_Rock:: @ 83C8190
	.byte 15, 25
	.2byte SPECIES_SLUGMA
	.byte 25, 35
	.2byte SPECIES_SLUGMA
	.byte 40, 45
	.2byte SPECIES_MAGCARGO
	.byte 35, 45
	.2byte SPECIES_MAGCARGO
	.byte 25, 35
	.2byte SPECIES_MAGCARGO

	.align 2
sWildMonInfo_MtEmberRubyPathB3F_Rock:: @ 83C81A4
	.byte 50
	.align 2
	.4byte sWildMons_MtEmberRubyPathB3F_Rock

	.align 2
sWildMons_MtEmberRubyPathB1FStairs_Land:: @ 83C81AC
	.byte 40, 40
	.2byte SPECIES_GEODUDE
	.byte 26, 26
	.2byte SPECIES_SLUGMA
	.byte 42, 42
	.2byte SPECIES_GEODUDE
	.byte 24, 24
	.2byte SPECIES_SLUGMA
	.byte 28, 28
	.2byte SPECIES_SLUGMA
	.byte 30, 30
	.2byte SPECIES_SLUGMA
	.byte 44, 44
	.2byte SPECIES_GEODUDE
	.byte 32, 32
	.2byte SPECIES_SLUGMA
	.byte 44, 44
	.2byte SPECIES_GEODUDE
	.byte 22, 22
	.2byte SPECIES_SLUGMA
	.byte 44, 44
	.2byte SPECIES_GEODUDE
	.byte 22, 22
	.2byte SPECIES_SLUGMA

	.align 2
sWildMonInfo_MtEmberRubyPathB1FStairs_Land:: @ 83C81DC
	.byte 7
	.align 2
	.4byte sWildMons_MtEmberRubyPathB1FStairs_Land

	.align 2
sWildMons_MtEmberRubyPathB1FStairs_Rock:: @ 83C81E4
	.byte 25, 35
	.2byte SPECIES_GEODUDE
	.byte 30, 45
	.2byte SPECIES_GRAVELER
	.byte 35, 50
	.2byte SPECIES_GRAVELER
	.byte 30, 40
	.2byte SPECIES_GEODUDE
	.byte 30, 40
	.2byte SPECIES_GEODUDE

	.align 2
sWildMonInfo_MtEmberRubyPathB1FStairs_Rock:: @ 83C81F8
	.byte 50
	.align 2
	.4byte sWildMons_MtEmberRubyPathB1FStairs_Rock

	.align 2
sWildMons_MtEmberRubyPathB2FStairs_Land:: @ 83C8200
	.byte 38, 38
	.2byte SPECIES_GEODUDE
	.byte 36, 36
	.2byte SPECIES_GEODUDE
	.byte 34, 34
	.2byte SPECIES_GEODUDE
	.byte 40, 40
	.2byte SPECIES_GEODUDE
	.byte 24, 24
	.2byte SPECIES_SLUGMA
	.byte 26, 26
	.2byte SPECIES_SLUGMA
	.byte 42, 42
	.2byte SPECIES_GEODUDE
	.byte 28, 28
	.2byte SPECIES_SLUGMA
	.byte 42, 42
	.2byte SPECIES_GEODUDE
	.byte 30, 30
	.2byte SPECIES_SLUGMA
	.byte 42, 42
	.2byte SPECIES_GEODUDE
	.byte 30, 30
	.2byte SPECIES_SLUGMA

	.align 2
sWildMonInfo_MtEmberRubyPathB2FStairs_Land:: @ 83C8230
	.byte 7
	.align 2
	.4byte sWildMons_MtEmberRubyPathB2FStairs_Land

	.align 2
sWildMons_MtEmberRubyPathB2FStairs_Rock:: @ 83C8238
	.byte 25, 35
	.2byte SPECIES_GEODUDE
	.byte 30, 45
	.2byte SPECIES_GRAVELER
	.byte 35, 50
	.2byte SPECIES_GRAVELER
	.byte 30, 40
	.2byte SPECIES_GEODUDE
	.byte 30, 40
	.2byte SPECIES_GEODUDE

	.align 2
sWildMonInfo_MtEmberRubyPathB2FStairs_Rock:: @ 83C824C
	.byte 50
	.align 2
	.4byte sWildMons_MtEmberRubyPathB2FStairs_Rock

	.align 2
sWildMons_ThreeIslandBerryForest_Land:: @ 83C8254
	.byte 37, 37
	.2byte SPECIES_PIDGEOTTO
	.byte 35, 35
	.2byte SPECIES_GLOOM
	.byte 32, 32
	.2byte SPECIES_PIDGEY
	.byte 30, 30
	.2byte SPECIES_ODDISH
	.byte 34, 34
	.2byte SPECIES_VENONAT
	.byte 34, 34
	.2byte SPECIES_DROWZEE
	.byte 35, 35
	.2byte SPECIES_EXEGGCUTE
	.byte 31, 31
	.2byte SPECIES_PSYDUCK
	.byte 37, 37
	.2byte SPECIES_VENOMOTH
	.byte 37, 37
	.2byte SPECIES_HYPNO
	.byte 40, 40
	.2byte SPECIES_VENOMOTH
	.byte 40, 40
	.2byte SPECIES_HYPNO

	.align 2
sWildMonInfo_ThreeIslandBerryForest_Land:: @ 83C8284
	.byte 21
	.align 2
	.4byte sWildMons_ThreeIslandBerryForest_Land

	.align 2
sWildMons_ThreeIslandBerryForest_Water:: @ 83C828C
	.byte 5, 20
	.2byte SPECIES_PSYDUCK
	.byte 20, 35
	.2byte SPECIES_PSYDUCK
	.byte 35, 40
	.2byte SPECIES_PSYDUCK
	.byte 35, 40
	.2byte SPECIES_GOLDUCK
	.byte 35, 40
	.2byte SPECIES_GOLDUCK

	.align 2
sWildMonInfo_ThreeIslandBerryForest_Water:: @ 83C82A0
	.byte 2
	.align 2
	.4byte sWildMons_ThreeIslandBerryForest_Water

	.align 2
sWildMons_ThreeIslandBerryForest_Fish:: @ 83C82A8
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_GOLDEEN
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_POLIWAG
	.byte 15, 25
	.2byte SPECIES_GOLDEEN
	.byte 20, 30
	.2byte SPECIES_SEAKING
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 15, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_ThreeIslandBerryForest_Fish:: @ 83C82D0
	.byte 20
	.align 2
	.4byte sWildMons_ThreeIslandBerryForest_Fish

	.align 2
sWildMons_FourIslandIcefallCaveEntrance_Land:: @ 83C82D8
	.byte 43, 43
	.2byte SPECIES_SEEL
	.byte 45, 45
	.2byte SPECIES_GOLBAT
	.byte 45, 45
	.2byte SPECIES_SEEL
	.byte 47, 47
	.2byte SPECIES_SEEL
	.byte 40, 40
	.2byte SPECIES_ZUBAT
	.byte 49, 49
	.2byte SPECIES_DEWGONG
	.byte 51, 51
	.2byte SPECIES_DEWGONG
	.byte 41, 41
	.2byte SPECIES_PSYDUCK
	.byte 48, 48
	.2byte SPECIES_GOLBAT
	.byte 53, 53
	.2byte SPECIES_DEWGONG
	.byte 48, 48
	.2byte SPECIES_GOLBAT
	.byte 53, 53
	.2byte SPECIES_DEWGONG

	.align 2
sWildMonInfo_FourIslandIcefallCaveEntrance_Land:: @ 83C8308
	.byte 7
	.align 2
	.4byte sWildMons_FourIslandIcefallCaveEntrance_Land

	.align 2
sWildMons_FourIslandIcefallCaveEntrance_Water:: @ 83C8310
	.byte 5, 35
	.2byte SPECIES_SEEL
	.byte 5, 35
	.2byte SPECIES_PSYDUCK
	.byte 35, 40
	.2byte SPECIES_DEWGONG
	.byte 5, 15
	.2byte SPECIES_WOOPER
	.byte 5, 15
	.2byte SPECIES_WOOPER

	.align 2
sWildMonInfo_FourIslandIcefallCaveEntrance_Water:: @ 83C8324
	.byte 2
	.align 2
	.4byte sWildMons_FourIslandIcefallCaveEntrance_Water

	.align 2
sWildMons_FourIslandIcefallCaveEntrance_Fish:: @ 83C832C
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_POLIWAG
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_GOLDEEN
	.byte 15, 25
	.2byte SPECIES_POLIWAG
	.byte 20, 30
	.2byte SPECIES_POLIWHIRL
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 15, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_FourIslandIcefallCaveEntrance_Fish:: @ 83C8354
	.byte 20
	.align 2
	.4byte sWildMons_FourIslandIcefallCaveEntrance_Fish

	.align 2
sWildMons_FourIslandIcefallCave1F_Land:: @ 83C835C
	.byte 25, 25
	.2byte SPECIES_SWINUB
	.byte 45, 45
	.2byte SPECIES_GOLBAT
	.byte 45, 45
	.2byte SPECIES_SEEL
	.byte 27, 27
	.2byte SPECIES_SWINUB
	.byte 40, 40
	.2byte SPECIES_ZUBAT
	.byte 29, 29
	.2byte SPECIES_SWINUB
	.byte 30, 30
	.2byte SPECIES_DELIBIRD
	.byte 31, 31
	.2byte SPECIES_SWINUB
	.byte 48, 48
	.2byte SPECIES_GOLBAT
	.byte 23, 23
	.2byte SPECIES_SWINUB
	.byte 48, 48
	.2byte SPECIES_GOLBAT
	.byte 23, 23
	.2byte SPECIES_SWINUB

	.align 2
sWildMonInfo_FourIslandIcefallCave1F_Land:: @ 83C838C
	.byte 7
	.align 2
	.4byte sWildMons_FourIslandIcefallCave1F_Land

	.align 2
sWildMons_FourIslandIcefallCaveB1F_Land:: @ 83C8394
	.byte 25, 25
	.2byte SPECIES_SWINUB
	.byte 45, 45
	.2byte SPECIES_GOLBAT
	.byte 45, 45
	.2byte SPECIES_SEEL
	.byte 27, 27
	.2byte SPECIES_SWINUB
	.byte 40, 40
	.2byte SPECIES_ZUBAT
	.byte 29, 29
	.2byte SPECIES_SWINUB
	.byte 30, 30
	.2byte SPECIES_DELIBIRD
	.byte 31, 31
	.2byte SPECIES_SWINUB
	.byte 48, 48
	.2byte SPECIES_GOLBAT
	.byte 23, 23
	.2byte SPECIES_SWINUB
	.byte 48, 48
	.2byte SPECIES_GOLBAT
	.byte 23, 23
	.2byte SPECIES_SWINUB

	.align 2
sWildMonInfo_FourIslandIcefallCaveB1F_Land:: @ 83C83C4
	.byte 7
	.align 2
	.4byte sWildMons_FourIslandIcefallCaveB1F_Land

	.align 2
sWildMons_FourIslandIcefallCaveBack_Land:: @ 83C83CC
	.byte 43, 43
	.2byte SPECIES_SEEL
	.byte 45, 45
	.2byte SPECIES_GOLBAT
	.byte 45, 45
	.2byte SPECIES_SEEL
	.byte 47, 47
	.2byte SPECIES_SEEL
	.byte 40, 40
	.2byte SPECIES_ZUBAT
	.byte 49, 49
	.2byte SPECIES_DEWGONG
	.byte 51, 51
	.2byte SPECIES_DEWGONG
	.byte 41, 41
	.2byte SPECIES_PSYDUCK
	.byte 48, 48
	.2byte SPECIES_GOLBAT
	.byte 53, 53
	.2byte SPECIES_DEWGONG
	.byte 48, 48
	.2byte SPECIES_GOLBAT
	.byte 53, 53
	.2byte SPECIES_DEWGONG

	.align 2
sWildMonInfo_FourIslandIcefallCaveBack_Land:: @ 83C83FC
	.byte 7
	.align 2
	.4byte sWildMons_FourIslandIcefallCaveBack_Land

	.align 2
sWildMons_FourIslandIcefallCaveBack_Water:: @ 83C8404
	.byte 5, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 45
	.2byte SPECIES_TENTACOOL
	.byte 35, 45
	.2byte SPECIES_TENTACRUEL
	.byte 30, 45
	.2byte SPECIES_LAPRAS

	.align 2
sWildMonInfo_FourIslandIcefallCaveBack_Water:: @ 83C8418
	.byte 2
	.align 2
	.4byte sWildMons_FourIslandIcefallCaveBack_Water

	.align 2
sWildMons_FourIslandIcefallCaveBack_Fish:: @ 83C8420
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_SHELLDER
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_FourIslandIcefallCaveBack_Fish:: @ 83C8448
	.byte 20
	.align 2
	.4byte sWildMons_FourIslandIcefallCaveBack_Fish

	.align 2
sWildMons_SixIslandPatternBush_Land:: @ 83C8450
	.byte 9, 9
	.2byte SPECIES_SPINARAK
	.byte 9, 9
	.2byte SPECIES_KAKUNA
	.byte 14, 14
	.2byte SPECIES_SPINARAK
	.byte 6, 6
	.2byte SPECIES_CATERPIE
	.byte 6, 6
	.2byte SPECIES_WEEDLE
	.byte 15, 15
	.2byte SPECIES_HERACROSS
	.byte 9, 9
	.2byte SPECIES_METAPOD
	.byte 20, 20
	.2byte SPECIES_HERACROSS
	.byte 9, 9
	.2byte SPECIES_LEDYBA
	.byte 25, 25
	.2byte SPECIES_HERACROSS
	.byte 14, 14
	.2byte SPECIES_LEDYBA
	.byte 30, 30
	.2byte SPECIES_HERACROSS

	.align 2
sWildMonInfo_SixIslandPatternBush_Land:: @ 83C8480
	.byte 21
	.align 2
	.4byte sWildMons_SixIslandPatternBush_Land

	.align 2
sWildMons_FiveIslandLostCaveRoom1_Land:: @ 83C8488
	.byte 40, 40
	.2byte SPECIES_GASTLY
	.byte 37, 37
	.2byte SPECIES_ZUBAT
	.byte 44, 44
	.2byte SPECIES_HAUNTER
	.byte 46, 46
	.2byte SPECIES_HAUNTER
	.byte 41, 41
	.2byte SPECIES_GOLBAT
	.byte 43, 43
	.2byte SPECIES_GOLBAT
	.byte 38, 38
	.2byte SPECIES_GASTLY
	.byte 48, 48
	.2byte SPECIES_HAUNTER
	.byte 50, 50
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW
	.byte 52, 52
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW

	.align 2
sWildMonInfo_FiveIslandLostCaveRoom1_Land:: @ 83C84B8
	.byte 1
	.align 2
	.4byte sWildMons_FiveIslandLostCaveRoom1_Land

	.align 2
sWildMons_FiveIslandLostCaveRoom2_Land:: @ 83C84C0
	.byte 40, 40
	.2byte SPECIES_GASTLY
	.byte 37, 37
	.2byte SPECIES_ZUBAT
	.byte 44, 44
	.2byte SPECIES_HAUNTER
	.byte 46, 46
	.2byte SPECIES_HAUNTER
	.byte 41, 41
	.2byte SPECIES_GOLBAT
	.byte 43, 43
	.2byte SPECIES_GOLBAT
	.byte 38, 38
	.2byte SPECIES_GASTLY
	.byte 48, 48
	.2byte SPECIES_HAUNTER
	.byte 50, 50
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW
	.byte 52, 52
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW

	.align 2
sWildMonInfo_FiveIslandLostCaveRoom2_Land:: @ 83C84F0
	.byte 2
	.align 2
	.4byte sWildMons_FiveIslandLostCaveRoom2_Land

	.align 2
sWildMons_FiveIslandLostCaveRoom3_Land:: @ 83C84F8
	.byte 40, 40
	.2byte SPECIES_GASTLY
	.byte 37, 37
	.2byte SPECIES_ZUBAT
	.byte 44, 44
	.2byte SPECIES_HAUNTER
	.byte 46, 46
	.2byte SPECIES_HAUNTER
	.byte 41, 41
	.2byte SPECIES_GOLBAT
	.byte 43, 43
	.2byte SPECIES_GOLBAT
	.byte 38, 38
	.2byte SPECIES_GASTLY
	.byte 48, 48
	.2byte SPECIES_HAUNTER
	.byte 50, 50
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW
	.byte 52, 52
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW

	.align 2
sWildMonInfo_FiveIslandLostCaveRoom3_Land:: @ 83C8528
	.byte 3
	.align 2
	.4byte sWildMons_FiveIslandLostCaveRoom3_Land

	.align 2
sWildMons_FiveIslandLostCaveRoom4_Land:: @ 83C8530
	.byte 40, 40
	.2byte SPECIES_GASTLY
	.byte 37, 37
	.2byte SPECIES_ZUBAT
	.byte 44, 44
	.2byte SPECIES_HAUNTER
	.byte 46, 46
	.2byte SPECIES_HAUNTER
	.byte 41, 41
	.2byte SPECIES_GOLBAT
	.byte 43, 43
	.2byte SPECIES_GOLBAT
	.byte 38, 38
	.2byte SPECIES_GASTLY
	.byte 48, 48
	.2byte SPECIES_HAUNTER
	.byte 50, 50
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW
	.byte 52, 52
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW

	.align 2
sWildMonInfo_FiveIslandLostCaveRoom4_Land:: @ 83C8560
	.byte 4
	.align 2
	.4byte sWildMons_FiveIslandLostCaveRoom4_Land

	.align 2
sWildMons_FiveIslandLostCaveRoom5_Land:: @ 83C8568
	.byte 40, 40
	.2byte SPECIES_GASTLY
	.byte 37, 37
	.2byte SPECIES_ZUBAT
	.byte 44, 44
	.2byte SPECIES_HAUNTER
	.byte 46, 46
	.2byte SPECIES_HAUNTER
	.byte 41, 41
	.2byte SPECIES_GOLBAT
	.byte 43, 43
	.2byte SPECIES_GOLBAT
	.byte 38, 38
	.2byte SPECIES_GASTLY
	.byte 48, 48
	.2byte SPECIES_HAUNTER
	.byte 50, 50
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW
	.byte 52, 52
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW

	.align 2
sWildMonInfo_FiveIslandLostCaveRoom5_Land:: @ 83C8598
	.byte 5
	.align 2
	.4byte sWildMons_FiveIslandLostCaveRoom5_Land

	.align 2
sWildMons_FiveIslandLostCaveRoom6_Land:: @ 83C85A0
	.byte 40, 40
	.2byte SPECIES_GASTLY
	.byte 37, 37
	.2byte SPECIES_ZUBAT
	.byte 44, 44
	.2byte SPECIES_HAUNTER
	.byte 46, 46
	.2byte SPECIES_HAUNTER
	.byte 41, 41
	.2byte SPECIES_GOLBAT
	.byte 43, 43
	.2byte SPECIES_GOLBAT
	.byte 38, 38
	.2byte SPECIES_GASTLY
	.byte 48, 48
	.2byte SPECIES_HAUNTER
	.byte 50, 50
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW
	.byte 52, 52
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW

	.align 2
sWildMonInfo_FiveIslandLostCaveRoom6_Land:: @ 83C85D0
	.byte 6
	.align 2
	.4byte sWildMons_FiveIslandLostCaveRoom6_Land

	.align 2
sWildMons_FiveIslandLostCaveRoom7_Land:: @ 83C85D8
	.byte 40, 40
	.2byte SPECIES_GASTLY
	.byte 37, 37
	.2byte SPECIES_ZUBAT
	.byte 44, 44
	.2byte SPECIES_HAUNTER
	.byte 46, 46
	.2byte SPECIES_HAUNTER
	.byte 41, 41
	.2byte SPECIES_GOLBAT
	.byte 43, 43
	.2byte SPECIES_GOLBAT
	.byte 38, 38
	.2byte SPECIES_GASTLY
	.byte 48, 48
	.2byte SPECIES_HAUNTER
	.byte 50, 50
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW
	.byte 52, 52
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW

	.align 2
sWildMonInfo_FiveIslandLostCaveRoom7_Land:: @ 83C8608
	.byte 7
	.align 2
	.4byte sWildMons_FiveIslandLostCaveRoom7_Land

	.align 2
sWildMons_FiveIslandLostCaveRoom8_Land:: @ 83C8610
	.byte 40, 40
	.2byte SPECIES_GASTLY
	.byte 37, 37
	.2byte SPECIES_ZUBAT
	.byte 44, 44
	.2byte SPECIES_HAUNTER
	.byte 46, 46
	.2byte SPECIES_HAUNTER
	.byte 41, 41
	.2byte SPECIES_GOLBAT
	.byte 43, 43
	.2byte SPECIES_GOLBAT
	.byte 38, 38
	.2byte SPECIES_GASTLY
	.byte 48, 48
	.2byte SPECIES_HAUNTER
	.byte 50, 50
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW
	.byte 52, 52
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW

	.align 2
sWildMonInfo_FiveIslandLostCaveRoom8_Land:: @ 83C8640
	.byte 8
	.align 2
	.4byte sWildMons_FiveIslandLostCaveRoom8_Land

	.align 2
sWildMons_FiveIslandLostCaveRoom9_Land:: @ 83C8648
	.byte 40, 40
	.2byte SPECIES_GASTLY
	.byte 37, 37
	.2byte SPECIES_ZUBAT
	.byte 44, 44
	.2byte SPECIES_HAUNTER
	.byte 46, 46
	.2byte SPECIES_HAUNTER
	.byte 41, 41
	.2byte SPECIES_GOLBAT
	.byte 43, 43
	.2byte SPECIES_GOLBAT
	.byte 38, 38
	.2byte SPECIES_GASTLY
	.byte 48, 48
	.2byte SPECIES_HAUNTER
	.byte 50, 50
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW
	.byte 52, 52
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW

	.align 2
sWildMonInfo_FiveIslandLostCaveRoom9_Land:: @ 83C8678
	.byte 9
	.align 2
	.4byte sWildMons_FiveIslandLostCaveRoom9_Land

	.align 2
sWildMons_FiveIslandLostCaveRoom10_Land:: @ 83C8680
	.byte 40, 40
	.2byte SPECIES_GASTLY
	.byte 37, 37
	.2byte SPECIES_ZUBAT
	.byte 44, 44
	.2byte SPECIES_HAUNTER
	.byte 46, 46
	.2byte SPECIES_HAUNTER
	.byte 41, 41
	.2byte SPECIES_GOLBAT
	.byte 43, 43
	.2byte SPECIES_GOLBAT
	.byte 38, 38
	.2byte SPECIES_GASTLY
	.byte 48, 48
	.2byte SPECIES_HAUNTER
	.byte 50, 50
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW
	.byte 52, 52
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW

	.align 2
sWildMonInfo_FiveIslandLostCaveRoom10_Land:: @ 83C86B0
	.byte 10
	.align 2
	.4byte sWildMons_FiveIslandLostCaveRoom10_Land

	.align 2
sWildMons_FiveIslandLostCaveRoom11_Land:: @ 83C86B8
	.byte 40, 40
	.2byte SPECIES_GASTLY
	.byte 37, 37
	.2byte SPECIES_ZUBAT
	.byte 44, 44
	.2byte SPECIES_HAUNTER
	.byte 46, 46
	.2byte SPECIES_HAUNTER
	.byte 41, 41
	.2byte SPECIES_GOLBAT
	.byte 15, 15
	.2byte SPECIES_MURKROW
	.byte 20, 20
	.2byte SPECIES_MURKROW
	.byte 48, 48
	.2byte SPECIES_HAUNTER
	.byte 50, 50
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW
	.byte 52, 52
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW

	.align 2
sWildMonInfo_FiveIslandLostCaveRoom11_Land:: @ 83C86E8
	.byte 5
	.align 2
	.4byte sWildMons_FiveIslandLostCaveRoom11_Land

	.align 2
sWildMons_FiveIslandLostCaveRoom12_Land:: @ 83C86F0
	.byte 40, 40
	.2byte SPECIES_GASTLY
	.byte 37, 37
	.2byte SPECIES_ZUBAT
	.byte 44, 44
	.2byte SPECIES_HAUNTER
	.byte 46, 46
	.2byte SPECIES_HAUNTER
	.byte 41, 41
	.2byte SPECIES_GOLBAT
	.byte 15, 15
	.2byte SPECIES_MURKROW
	.byte 20, 20
	.2byte SPECIES_MURKROW
	.byte 48, 48
	.2byte SPECIES_HAUNTER
	.byte 50, 50
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW
	.byte 52, 52
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW

	.align 2
sWildMonInfo_FiveIslandLostCaveRoom12_Land:: @ 83C8720
	.byte 5
	.align 2
	.4byte sWildMons_FiveIslandLostCaveRoom12_Land

	.align 2
sWildMons_FiveIslandLostCaveRoom13_Land:: @ 83C8728
	.byte 40, 40
	.2byte SPECIES_GASTLY
	.byte 37, 37
	.2byte SPECIES_ZUBAT
	.byte 44, 44
	.2byte SPECIES_HAUNTER
	.byte 46, 46
	.2byte SPECIES_HAUNTER
	.byte 41, 41
	.2byte SPECIES_GOLBAT
	.byte 15, 15
	.2byte SPECIES_MURKROW
	.byte 20, 20
	.2byte SPECIES_MURKROW
	.byte 48, 48
	.2byte SPECIES_HAUNTER
	.byte 50, 50
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW
	.byte 52, 52
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW

	.align 2
sWildMonInfo_FiveIslandLostCaveRoom13_Land:: @ 83C8758
	.byte 5
	.align 2
	.4byte sWildMons_FiveIslandLostCaveRoom13_Land

	.align 2
sWildMons_FiveIslandLostCaveRoom14_Land:: @ 83C8760
	.byte 40, 40
	.2byte SPECIES_GASTLY
	.byte 37, 37
	.2byte SPECIES_ZUBAT
	.byte 44, 44
	.2byte SPECIES_HAUNTER
	.byte 46, 46
	.2byte SPECIES_HAUNTER
	.byte 41, 41
	.2byte SPECIES_GOLBAT
	.byte 15, 15
	.2byte SPECIES_MURKROW
	.byte 20, 20
	.2byte SPECIES_MURKROW
	.byte 48, 48
	.2byte SPECIES_HAUNTER
	.byte 50, 50
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW
	.byte 52, 52
	.2byte SPECIES_HAUNTER
	.byte 22, 22
	.2byte SPECIES_MURKROW

	.align 2
sWildMonInfo_FiveIslandLostCaveRoom14_Land:: @ 83C8790
	.byte 5
	.align 2
	.4byte sWildMons_FiveIslandLostCaveRoom14_Land

	.align 2
sWildMons_OneIslandKindleRoad_Land:: @ 83C8798
	.byte 32, 32
	.2byte SPECIES_SPEAROW
	.byte 34, 34
	.2byte SPECIES_PONYTA
	.byte 36, 36
	.2byte SPECIES_FEAROW
	.byte 31, 31
	.2byte SPECIES_PONYTA
	.byte 31, 31
	.2byte SPECIES_GEODUDE
	.byte 31, 31
	.2byte SPECIES_MEOWTH
	.byte 30, 30
	.2byte SPECIES_SPEAROW
	.byte 34, 34
	.2byte SPECIES_PSYDUCK
	.byte 37, 37
	.2byte SPECIES_RAPIDASH
	.byte 37, 37
	.2byte SPECIES_PERSIAN
	.byte 40, 40
	.2byte SPECIES_RAPIDASH
	.byte 40, 40
	.2byte SPECIES_PERSIAN

	.align 2
sWildMonInfo_OneIslandKindleRoad_Land:: @ 83C87C8
	.byte 21
	.align 2
	.4byte sWildMons_OneIslandKindleRoad_Land

	.align 2
sWildMons_OneIslandKindleRoad_Water:: @ 83C87D0
	.byte 5, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL

	.align 2
sWildMonInfo_OneIslandKindleRoad_Water:: @ 83C87E4
	.byte 2
	.align 2
	.4byte sWildMons_OneIslandKindleRoad_Water

	.align 2
sWildMons_OneIslandKindleRoad_Rock:: @ 83C87EC
	.byte 5, 20
	.2byte SPECIES_GEODUDE
	.byte 10, 20
	.2byte SPECIES_GEODUDE
	.byte 15, 30
	.2byte SPECIES_GEODUDE
	.byte 25, 40
	.2byte SPECIES_GRAVELER
	.byte 30, 40
	.2byte SPECIES_GRAVELER

	.align 2
sWildMonInfo_OneIslandKindleRoad_Rock:: @ 83C8800
	.byte 25
	.align 2
	.4byte sWildMons_OneIslandKindleRoad_Rock

	.align 2
sWildMons_OneIslandKindleRoad_Fish:: @ 83C8808
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_OneIslandKindleRoad_Fish:: @ 83C8830
	.byte 20
	.align 2
	.4byte sWildMons_OneIslandKindleRoad_Fish

	.align 2
sWildMons_OneIslandTreasureBeach_Land:: @ 83C8838
	.byte 32, 32
	.2byte SPECIES_SPEAROW
	.byte 33, 33
	.2byte SPECIES_TANGELA
	.byte 31, 31
	.2byte SPECIES_SPEAROW
	.byte 35, 35
	.2byte SPECIES_TANGELA
	.byte 36, 36
	.2byte SPECIES_FEAROW
	.byte 31, 31
	.2byte SPECIES_MEOWTH
	.byte 38, 38
	.2byte SPECIES_FEAROW
	.byte 31, 31
	.2byte SPECIES_PSYDUCK
	.byte 40, 40
	.2byte SPECIES_FEAROW
	.byte 37, 37
	.2byte SPECIES_PERSIAN
	.byte 40, 40
	.2byte SPECIES_FEAROW
	.byte 40, 40
	.2byte SPECIES_PERSIAN

	.align 2
sWildMonInfo_OneIslandTreasureBeach_Land:: @ 83C8868
	.byte 21
	.align 2
	.4byte sWildMons_OneIslandTreasureBeach_Land

	.align 2
sWildMons_OneIslandTreasureBeach_Water:: @ 83C8870
	.byte 5, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL

	.align 2
sWildMonInfo_OneIslandTreasureBeach_Water:: @ 83C8884
	.byte 2
	.align 2
	.4byte sWildMons_OneIslandTreasureBeach_Water

	.align 2
sWildMons_OneIslandTreasureBeach_Fish:: @ 83C888C
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_OneIslandTreasureBeach_Fish:: @ 83C88B4
	.byte 20
	.align 2
	.4byte sWildMons_OneIslandTreasureBeach_Fish

	.align 2
sWildMons_TwoIslandCapeBrink_Land:: @ 83C88BC
	.byte 31, 31
	.2byte SPECIES_SPEAROW
	.byte 30, 30
	.2byte SPECIES_ODDISH
	.byte 32, 32
	.2byte SPECIES_ODDISH
	.byte 36, 36
	.2byte SPECIES_GLOOM
	.byte 36, 36
	.2byte SPECIES_FEAROW
	.byte 31, 31
	.2byte SPECIES_MEOWTH
	.byte 38, 38
	.2byte SPECIES_GLOOM
	.byte 31, 31
	.2byte SPECIES_PSYDUCK
	.byte 37, 37
	.2byte SPECIES_GOLDUCK
	.byte 37, 37
	.2byte SPECIES_PERSIAN
	.byte 40, 40
	.2byte SPECIES_GOLDUCK
	.byte 40, 40
	.2byte SPECIES_PERSIAN

	.align 2
sWildMonInfo_TwoIslandCapeBrink_Land:: @ 83C88EC
	.byte 21
	.align 2
	.4byte sWildMons_TwoIslandCapeBrink_Land

	.align 2
sWildMons_TwoIslandCapeBrink_Water:: @ 83C88F4
	.byte 5, 20
	.2byte SPECIES_PSYDUCK
	.byte 20, 35
	.2byte SPECIES_PSYDUCK
	.byte 35, 40
	.2byte SPECIES_PSYDUCK
	.byte 35, 40
	.2byte SPECIES_GOLDUCK
	.byte 35, 40
	.2byte SPECIES_GOLDUCK

	.align 2
sWildMonInfo_TwoIslandCapeBrink_Water:: @ 83C8908
	.byte 2
	.align 2
	.4byte sWildMons_TwoIslandCapeBrink_Water

	.align 2
sWildMons_TwoIslandCapeBrink_Fish:: @ 83C8910
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_POLIWAG
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_GOLDEEN
	.byte 15, 25
	.2byte SPECIES_POLIWAG
	.byte 20, 30
	.2byte SPECIES_POLIWHIRL
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 15, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_TwoIslandCapeBrink_Fish:: @ 83C8938
	.byte 20
	.align 2
	.4byte sWildMons_TwoIslandCapeBrink_Fish

	.align 2
sWildMons_ThreeIslandBondBridge_Land:: @ 83C8940
	.byte 32, 32
	.2byte SPECIES_PIDGEY
	.byte 31, 31
	.2byte SPECIES_ODDISH
	.byte 29, 29
	.2byte SPECIES_PIDGEY
	.byte 36, 36
	.2byte SPECIES_GLOOM
	.byte 34, 34
	.2byte SPECIES_PIDGEOTTO
	.byte 31, 31
	.2byte SPECIES_MEOWTH
	.byte 34, 34
	.2byte SPECIES_VENONAT
	.byte 31, 31
	.2byte SPECIES_PSYDUCK
	.byte 37, 37
	.2byte SPECIES_PIDGEOTTO
	.byte 37, 37
	.2byte SPECIES_PERSIAN
	.byte 40, 40
	.2byte SPECIES_PIDGEOTTO
	.byte 40, 40
	.2byte SPECIES_PERSIAN

	.align 2
sWildMonInfo_ThreeIslandBondBridge_Land:: @ 83C8970
	.byte 21
	.align 2
	.4byte sWildMons_ThreeIslandBondBridge_Land

	.align 2
sWildMons_ThreeIslandBondBridge_Water:: @ 83C8978
	.byte 5, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL

	.align 2
sWildMonInfo_ThreeIslandBondBridge_Water:: @ 83C898C
	.byte 2
	.align 2
	.4byte sWildMons_ThreeIslandBondBridge_Water

	.align 2
sWildMons_ThreeIslandBondBridge_Fish:: @ 83C8994
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_ThreeIslandBondBridge_Fish:: @ 83C89BC
	.byte 20
	.align 2
	.4byte sWildMons_ThreeIslandBondBridge_Fish

	.align 2
sWildMons_ThreeIslandPort_Land:: @ 83C89C4
	.byte 15, 15
	.2byte SPECIES_DUNSPARCE
	.byte 15, 15
	.2byte SPECIES_DUNSPARCE
	.byte 10, 10
	.2byte SPECIES_DUNSPARCE
	.byte 10, 10
	.2byte SPECIES_DUNSPARCE
	.byte 20, 20
	.2byte SPECIES_DUNSPARCE
	.byte 20, 20
	.2byte SPECIES_DUNSPARCE
	.byte 25, 25
	.2byte SPECIES_DUNSPARCE
	.byte 30, 30
	.2byte SPECIES_DUNSPARCE
	.byte 25, 25
	.2byte SPECIES_DUNSPARCE
	.byte 30, 30
	.2byte SPECIES_DUNSPARCE
	.byte 5, 5
	.2byte SPECIES_DUNSPARCE
	.byte 35, 35
	.2byte SPECIES_DUNSPARCE

	.align 2
sWildMonInfo_ThreeIslandPort_Land:: @ 83C89F4
	.byte 1
	.align 2
	.4byte sWildMons_ThreeIslandPort_Land

	.align 2
sWildMons_FiveIslandResortGorgeous_Water:: @ 83C89FC
	.byte 5, 35
	.2byte SPECIES_TENTACOOL
	.byte 5, 15
	.2byte SPECIES_HOPPIP
	.byte 35, 40
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL

	.align 2
sWildMonInfo_FiveIslandResortGorgeous_Water:: @ 83C8A10
	.byte 2
	.align 2
	.4byte sWildMons_FiveIslandResortGorgeous_Water

	.align 2
sWildMons_FiveIslandResortGorgeous_Fish:: @ 83C8A18
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_QWILFISH
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_FiveIslandResortGorgeous_Fish:: @ 83C8A40
	.byte 20
	.align 2
	.4byte sWildMons_FiveIslandResortGorgeous_Fish

	.align 2
sWildMons_FiveIslandWaterLabyrinth_Water:: @ 83C8A48
	.byte 5, 20
	.2byte SPECIES_TENTACOOL
	.byte 5, 15
	.2byte SPECIES_HOPPIP
	.byte 35, 40
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL

	.align 2
sWildMonInfo_FiveIslandWaterLabyrinth_Water:: @ 83C8A5C
	.byte 2
	.align 2
	.4byte sWildMons_FiveIslandWaterLabyrinth_Water

	.align 2
sWildMons_FiveIslandWaterLabyrinth_Fish:: @ 83C8A64
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_QWILFISH
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_FiveIslandWaterLabyrinth_Fish:: @ 83C8A8C
	.byte 20
	.align 2
	.4byte sWildMons_FiveIslandWaterLabyrinth_Fish

	.align 2
sWildMons_FiveIslandMeadow_Land:: @ 83C8A94
	.byte 44, 44
	.2byte SPECIES_PIDGEY
	.byte 10, 10
	.2byte SPECIES_SENTRET
	.byte 48, 48
	.2byte SPECIES_PIDGEOTTO
	.byte 10, 10
	.2byte SPECIES_HOPPIP
	.byte 15, 15
	.2byte SPECIES_SENTRET
	.byte 41, 41
	.2byte SPECIES_MEOWTH
	.byte 15, 15
	.2byte SPECIES_HOPPIP
	.byte 41, 41
	.2byte SPECIES_PSYDUCK
	.byte 50, 50
	.2byte SPECIES_PIDGEOTTO
	.byte 47, 47
	.2byte SPECIES_PERSIAN
	.byte 50, 50
	.2byte SPECIES_PIDGEOTTO
	.byte 50, 50
	.2byte SPECIES_PERSIAN

	.align 2
sWildMonInfo_FiveIslandMeadow_Land:: @ 83C8AC4
	.byte 21
	.align 2
	.4byte sWildMons_FiveIslandMeadow_Land

	.align 2
sWildMons_FiveIslandMeadow_Water:: @ 83C8ACC
	.byte 5, 35
	.2byte SPECIES_TENTACOOL
	.byte 5, 15
	.2byte SPECIES_HOPPIP
	.byte 35, 40
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL

	.align 2
sWildMonInfo_FiveIslandMeadow_Water:: @ 83C8AE0
	.byte 2
	.align 2
	.4byte sWildMons_FiveIslandMeadow_Water

	.align 2
sWildMons_FiveIslandMeadow_Fish:: @ 83C8AE8
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_QWILFISH
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_FiveIslandMeadow_Fish:: @ 83C8B10
	.byte 20
	.align 2
	.4byte sWildMons_FiveIslandMeadow_Fish

	.align 2
sWildMons_FiveIslandMemorialPillar_Land:: @ 83C8B18
	.byte 10, 10
	.2byte SPECIES_HOPPIP
	.byte 12, 12
	.2byte SPECIES_HOPPIP
	.byte 8, 8
	.2byte SPECIES_HOPPIP
	.byte 14, 14
	.2byte SPECIES_HOPPIP
	.byte 10, 10
	.2byte SPECIES_HOPPIP
	.byte 12, 12
	.2byte SPECIES_HOPPIP
	.byte 16, 16
	.2byte SPECIES_HOPPIP
	.byte 6, 6
	.2byte SPECIES_HOPPIP
	.byte 8, 8
	.2byte SPECIES_HOPPIP
	.byte 14, 14
	.2byte SPECIES_HOPPIP
	.byte 8, 8
	.2byte SPECIES_HOPPIP
	.byte 14, 14
	.2byte SPECIES_HOPPIP

	.align 2
sWildMonInfo_FiveIslandMemorialPillar_Land:: @ 83C8B48
	.byte 21
	.align 2
	.4byte sWildMons_FiveIslandMemorialPillar_Land

	.align 2
sWildMons_FiveIslandMemorialPillar_Water:: @ 83C8B50
	.byte 5, 35
	.2byte SPECIES_TENTACOOL
	.byte 5, 15
	.2byte SPECIES_HOPPIP
	.byte 35, 40
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL

	.align 2
sWildMonInfo_FiveIslandMemorialPillar_Water:: @ 83C8B64
	.byte 2
	.align 2
	.4byte sWildMons_FiveIslandMemorialPillar_Water

	.align 2
sWildMons_FiveIslandMemorialPillar_Fish:: @ 83C8B6C
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_QWILFISH
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_FiveIslandMemorialPillar_Fish:: @ 83C8B94
	.byte 20
	.align 2
	.4byte sWildMons_FiveIslandMemorialPillar_Fish

	.align 2
sWildMons_SixIslandOutcastIsland_Water:: @ 83C8B9C
	.byte 5, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL

	.align 2
sWildMonInfo_SixIslandOutcastIsland_Water:: @ 83C8BB0
	.byte 2
	.align 2
	.4byte sWildMons_SixIslandOutcastIsland_Water

	.align 2
sWildMons_SixIslandOutcastIsland_Fish:: @ 83C8BB8
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_QWILFISH
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_SixIslandOutcastIsland_Fish:: @ 83C8BE0
	.byte 20
	.align 2
	.4byte sWildMons_SixIslandOutcastIsland_Fish

	.align 2
sWildMons_SixIslandGreenPath_Water:: @ 83C8BE8
	.byte 5, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL

	.align 2
sWildMonInfo_SixIslandGreenPath_Water:: @ 83C8BFC
	.byte 2
	.align 2
	.4byte sWildMons_SixIslandGreenPath_Water

	.align 2
sWildMons_SixIslandGreenPath_Fish:: @ 83C8C04
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_QWILFISH
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_SixIslandGreenPath_Fish:: @ 83C8C2C
	.byte 20
	.align 2
	.4byte sWildMons_SixIslandGreenPath_Fish

	.align 2
sWildMons_SixIslandWaterPath_Land:: @ 83C8C34
	.byte 44, 44
	.2byte SPECIES_SPEAROW
	.byte 10, 10
	.2byte SPECIES_SENTRET
	.byte 44, 44
	.2byte SPECIES_ODDISH
	.byte 48, 48
	.2byte SPECIES_FEAROW
	.byte 15, 15
	.2byte SPECIES_SENTRET
	.byte 41, 41
	.2byte SPECIES_MEOWTH
	.byte 48, 48
	.2byte SPECIES_GLOOM
	.byte 41, 41
	.2byte SPECIES_PSYDUCK
	.byte 50, 50
	.2byte SPECIES_FEAROW
	.byte 47, 47
	.2byte SPECIES_PERSIAN
	.byte 50, 50
	.2byte SPECIES_FEAROW
	.byte 50, 50
	.2byte SPECIES_PERSIAN

	.align 2
sWildMonInfo_SixIslandWaterPath_Land:: @ 83C8C64
	.byte 21
	.align 2
	.4byte sWildMons_SixIslandWaterPath_Land

	.align 2
sWildMons_SixIslandWaterPath_Water:: @ 83C8C6C
	.byte 5, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL

	.align 2
sWildMonInfo_SixIslandWaterPath_Water:: @ 83C8C80
	.byte 2
	.align 2
	.4byte sWildMons_SixIslandWaterPath_Water

	.align 2
sWildMons_SixIslandWaterPath_Fish:: @ 83C8C88
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_QWILFISH
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_SixIslandWaterPath_Fish:: @ 83C8CB0
	.byte 20
	.align 2
	.4byte sWildMons_SixIslandWaterPath_Fish

	.align 2
sWildMons_SixIslandRuinValley_Land:: @ 83C8CB8
	.byte 15, 15
	.2byte SPECIES_NATU
	.byte 44, 44
	.2byte SPECIES_SPEAROW
	.byte 18, 18
	.2byte SPECIES_YANMA
	.byte 15, 15
	.2byte SPECIES_WOOPER
	.byte 49, 49
	.2byte SPECIES_FEAROW
	.byte 43, 43
	.2byte SPECIES_MEOWTH
	.byte 25, 25
	.2byte SPECIES_WOBBUFFET
	.byte 41, 41
	.2byte SPECIES_PSYDUCK
	.byte 20, 20
	.2byte SPECIES_NATU
	.byte 49, 49
	.2byte SPECIES_PERSIAN
	.byte 20, 20
	.2byte SPECIES_NATU
	.byte 52, 52
	.2byte SPECIES_PERSIAN

	.align 2
sWildMonInfo_SixIslandRuinValley_Land:: @ 83C8CE8
	.byte 21
	.align 2
	.4byte sWildMons_SixIslandRuinValley_Land

	.align 2
sWildMons_SixIslandRuinValley_Water:: @ 83C8CF0
	.byte 5, 20
	.2byte SPECIES_WOOPER
	.byte 10, 20
	.2byte SPECIES_WOOPER
	.byte 15, 25
	.2byte SPECIES_WOOPER
	.byte 20, 25
	.2byte SPECIES_WOOPER
	.byte 20, 25
	.2byte SPECIES_WOOPER

	.align 2
sWildMonInfo_SixIslandRuinValley_Water:: @ 83C8D04
	.byte 2
	.align 2
	.4byte sWildMons_SixIslandRuinValley_Water

	.align 2
sWildMons_SixIslandRuinValley_Fish:: @ 83C8D0C
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_POLIWAG
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_GOLDEEN
	.byte 15, 25
	.2byte SPECIES_POLIWAG
	.byte 20, 30
	.2byte SPECIES_POLIWHIRL
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 15, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_SixIslandRuinValley_Fish:: @ 83C8D34
	.byte 20
	.align 2
	.4byte sWildMons_SixIslandRuinValley_Fish

	.align 2
sWildMons_SevenIslandTrainerTower_Water:: @ 83C8D3C
	.byte 5, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL

	.align 2
sWildMonInfo_SevenIslandTrainerTower_Water:: @ 83C8D50
	.byte 2
	.align 2
	.4byte sWildMons_SevenIslandTrainerTower_Water

	.align 2
sWildMons_SevenIslandTrainerTower_Fish:: @ 83C8D58
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_QWILFISH
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_SevenIslandTrainerTower_Fish:: @ 83C8D80
	.byte 20
	.align 2
	.4byte sWildMons_SevenIslandTrainerTower_Fish

	.align 2
sWildMons_SevenIslandSevaultCanyonEntrance_Land:: @ 83C8D88
	.byte 44, 44
	.2byte SPECIES_SPEAROW
	.byte 10, 10
	.2byte SPECIES_SENTRET
	.byte 10, 10
	.2byte SPECIES_PHANPY
	.byte 48, 48
	.2byte SPECIES_FEAROW
	.byte 15, 15
	.2byte SPECIES_SENTRET
	.byte 41, 41
	.2byte SPECIES_MEOWTH
	.byte 50, 50
	.2byte SPECIES_FEAROW
	.byte 41, 41
	.2byte SPECIES_PSYDUCK
	.byte 15, 15
	.2byte SPECIES_PHANPY
	.byte 47, 47
	.2byte SPECIES_PERSIAN
	.byte 15, 15
	.2byte SPECIES_PHANPY
	.byte 50, 50
	.2byte SPECIES_PERSIAN

	.align 2
sWildMonInfo_SevenIslandSevaultCanyonEntrance_Land:: @ 83C8DB8
	.byte 21
	.align 2
	.4byte sWildMons_SevenIslandSevaultCanyonEntrance_Land

	.align 2
sWildMons_SevenIslandSevaultCanyon_Land:: @ 83C8DC0
	.byte 46, 46
	.2byte SPECIES_GEODUDE
	.byte 15, 15
	.2byte SPECIES_PHANPY
	.byte 46, 46
	.2byte SPECIES_CUBONE
	.byte 50, 50
	.2byte SPECIES_FEAROW
	.byte 52, 52
	.2byte SPECIES_MAROWAK
	.byte 43, 43
	.2byte SPECIES_MEOWTH
	.byte 54, 54
	.2byte SPECIES_ONIX
	.byte 30, 30
	.2byte SPECIES_SKARMORY
	.byte 15, 15
	.2byte SPECIES_LARVITAR
	.byte 49, 49
	.2byte SPECIES_PERSIAN
	.byte 20, 20
	.2byte SPECIES_LARVITAR
	.byte 52, 52
	.2byte SPECIES_PERSIAN

	.align 2
sWildMonInfo_SevenIslandSevaultCanyon_Land:: @ 83C8DF0
	.byte 21
	.align 2
	.4byte sWildMons_SevenIslandSevaultCanyon_Land

	.align 2
sWildMons_SevenIslandSevaultCanyon_Rock:: @ 83C8DF8
	.byte 25, 35
	.2byte SPECIES_GEODUDE
	.byte 30, 45
	.2byte SPECIES_GRAVELER
	.byte 35, 50
	.2byte SPECIES_GRAVELER
	.byte 30, 40
	.2byte SPECIES_GEODUDE
	.byte 30, 40
	.2byte SPECIES_GEODUDE

	.align 2
sWildMonInfo_SevenIslandSevaultCanyon_Rock:: @ 83C8E0C
	.byte 25
	.align 2
	.4byte sWildMons_SevenIslandSevaultCanyon_Rock

	.align 2
sWildMons_SevenIslandTanobyRuins_Water:: @ 83C8E14
	.byte 5, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL

	.align 2
sWildMonInfo_SevenIslandTanobyRuins_Water:: @ 83C8E28
	.byte 2
	.align 2
	.4byte sWildMons_SevenIslandTanobyRuins_Water

	.align 2
sWildMons_SevenIslandTanobyRuins_Fish:: @ 83C8E30
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_QWILFISH
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_SevenIslandTanobyRuins_Fish:: @ 83C8E58
	.byte 20
	.align 2
	.4byte sWildMons_SevenIslandTanobyRuins_Fish

	.align 2
sWildMons_Route1_Land:: @ 83C8E60
	.byte 3, 3
	.2byte SPECIES_PIDGEY
	.byte 3, 3
	.2byte SPECIES_RATTATA
	.byte 3, 3
	.2byte SPECIES_PIDGEY
	.byte 3, 3
	.2byte SPECIES_RATTATA
	.byte 2, 2
	.2byte SPECIES_PIDGEY
	.byte 2, 2
	.2byte SPECIES_RATTATA
	.byte 3, 3
	.2byte SPECIES_PIDGEY
	.byte 3, 3
	.2byte SPECIES_RATTATA
	.byte 4, 4
	.2byte SPECIES_PIDGEY
	.byte 4, 4
	.2byte SPECIES_RATTATA
	.byte 5, 5
	.2byte SPECIES_PIDGEY
	.byte 4, 4
	.2byte SPECIES_RATTATA

	.align 2
sWildMonInfo_Route1_Land:: @ 83C8E90
	.byte 21
	.align 2
	.4byte sWildMons_Route1_Land

	.align 2
sWildMons_Route2_Land:: @ 83C8E98
	.byte 3, 3
	.2byte SPECIES_RATTATA
	.byte 3, 3
	.2byte SPECIES_PIDGEY
	.byte 4, 4
	.2byte SPECIES_RATTATA
	.byte 4, 4
	.2byte SPECIES_PIDGEY
	.byte 2, 2
	.2byte SPECIES_RATTATA
	.byte 2, 2
	.2byte SPECIES_PIDGEY
	.byte 5, 5
	.2byte SPECIES_RATTATA
	.byte 5, 5
	.2byte SPECIES_PIDGEY
	.byte 4, 4
	.2byte SPECIES_CATERPIE
	.byte 4, 4
	.2byte SPECIES_WEEDLE
	.byte 5, 5
	.2byte SPECIES_CATERPIE
	.byte 5, 5
	.2byte SPECIES_WEEDLE

	.align 2
sWildMonInfo_Route2_Land:: @ 83C8EC8
	.byte 21
	.align 2
	.4byte sWildMons_Route2_Land

	.align 2
sWildMons_Route3_Land:: @ 83C8ED0
	.byte 6, 6
	.2byte SPECIES_SPEAROW
	.byte 6, 6
	.2byte SPECIES_PIDGEY
	.byte 7, 7
	.2byte SPECIES_SPEAROW
	.byte 7, 7
	.2byte SPECIES_MANKEY
	.byte 6, 6
	.2byte SPECIES_NIDORAN_M
	.byte 7, 7
	.2byte SPECIES_PIDGEY
	.byte 8, 8
	.2byte SPECIES_SPEAROW
	.byte 3, 3
	.2byte SPECIES_JIGGLYPUFF
	.byte 7, 7
	.2byte SPECIES_NIDORAN_M
	.byte 5, 5
	.2byte SPECIES_JIGGLYPUFF
	.byte 6, 6
	.2byte SPECIES_NIDORAN_F
	.byte 7, 7
	.2byte SPECIES_JIGGLYPUFF

	.align 2
sWildMonInfo_Route3_Land:: @ 83C8F00
	.byte 21
	.align 2
	.4byte sWildMons_Route3_Land

	.align 2
sWildMons_Route4_Land:: @ 83C8F08
	.byte 10, 10
	.2byte SPECIES_SPEAROW
	.byte 10, 10
	.2byte SPECIES_RATTATA
	.byte 6, 6
	.2byte SPECIES_EKANS
	.byte 10, 10
	.2byte SPECIES_EKANS
	.byte 8, 8
	.2byte SPECIES_SPEAROW
	.byte 8, 8
	.2byte SPECIES_RATTATA
	.byte 12, 12
	.2byte SPECIES_SPEAROW
	.byte 12, 12
	.2byte SPECIES_RATTATA
	.byte 10, 10
	.2byte SPECIES_MANKEY
	.byte 8, 8
	.2byte SPECIES_EKANS
	.byte 12, 12
	.2byte SPECIES_MANKEY
	.byte 12, 12
	.2byte SPECIES_EKANS

	.align 2
sWildMonInfo_Route4_Land:: @ 83C8F38
	.byte 21
	.align 2
	.4byte sWildMons_Route4_Land

	.align 2
sWildMons_Route4_Water:: @ 83C8F40
	.byte 5, 10
	.2byte SPECIES_TENTACOOL
	.byte 10, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 30
	.2byte SPECIES_TENTACOOL
	.byte 30, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL

	.align 2
sWildMonInfo_Route4_Water:: @ 83C8F54
	.byte 2
	.align 2
	.4byte sWildMons_Route4_Water

	.align 2
sWildMons_Route4_Fish:: @ 83C8F5C
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_KRABBY
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_HORSEA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_Route4_Fish:: @ 83C8F84
	.byte 20
	.align 2
	.4byte sWildMons_Route4_Fish

	.align 2
sWildMons_Route5_Land:: @ 83C8F8C
	.byte 10, 10
	.2byte SPECIES_MEOWTH
	.byte 13, 13
	.2byte SPECIES_PIDGEY
	.byte 13, 13
	.2byte SPECIES_ODDISH
	.byte 12, 12
	.2byte SPECIES_MEOWTH
	.byte 15, 15
	.2byte SPECIES_ODDISH
	.byte 15, 15
	.2byte SPECIES_PIDGEY
	.byte 16, 16
	.2byte SPECIES_ODDISH
	.byte 16, 16
	.2byte SPECIES_PIDGEY
	.byte 15, 15
	.2byte SPECIES_PIDGEY
	.byte 14, 14
	.2byte SPECIES_MEOWTH
	.byte 15, 15
	.2byte SPECIES_PIDGEY
	.byte 16, 16
	.2byte SPECIES_MEOWTH

	.align 2
sWildMonInfo_Route5_Land:: @ 83C8FBC
	.byte 21
	.align 2
	.4byte sWildMons_Route5_Land

	.align 2
sWildMons_Route6_Land:: @ 83C8FC4
	.byte 10, 10
	.2byte SPECIES_MEOWTH
	.byte 13, 13
	.2byte SPECIES_PIDGEY
	.byte 13, 13
	.2byte SPECIES_ODDISH
	.byte 12, 12
	.2byte SPECIES_MEOWTH
	.byte 15, 15
	.2byte SPECIES_ODDISH
	.byte 15, 15
	.2byte SPECIES_PIDGEY
	.byte 16, 16
	.2byte SPECIES_ODDISH
	.byte 16, 16
	.2byte SPECIES_PIDGEY
	.byte 15, 15
	.2byte SPECIES_PIDGEY
	.byte 14, 14
	.2byte SPECIES_MEOWTH
	.byte 15, 15
	.2byte SPECIES_PIDGEY
	.byte 16, 16
	.2byte SPECIES_MEOWTH

	.align 2
sWildMonInfo_Route6_Land:: @ 83C8FF4
	.byte 21
	.align 2
	.4byte sWildMons_Route6_Land

	.align 2
sWildMons_Route6_Water:: @ 83C8FFC
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 30
	.2byte SPECIES_PSYDUCK
	.byte 30, 35
	.2byte SPECIES_PSYDUCK
	.byte 35, 40
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_Route6_Water:: @ 83C9010
	.byte 2
	.align 2
	.4byte sWildMons_Route6_Water

	.align 2
sWildMons_Route6_Fish:: @ 83C9018
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_POLIWAG
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_GOLDEEN
	.byte 15, 25
	.2byte SPECIES_POLIWAG
	.byte 20, 30
	.2byte SPECIES_POLIWHIRL
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 15, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_Route6_Fish:: @ 83C9040
	.byte 20
	.align 2
	.4byte sWildMons_Route6_Fish

	.align 2
sWildMons_Route7_Land:: @ 83C9048
	.byte 19, 19
	.2byte SPECIES_PIDGEY
	.byte 17, 17
	.2byte SPECIES_MEOWTH
	.byte 19, 19
	.2byte SPECIES_ODDISH
	.byte 18, 18
	.2byte SPECIES_MEOWTH
	.byte 22, 22
	.2byte SPECIES_PIDGEY
	.byte 22, 22
	.2byte SPECIES_ODDISH
	.byte 18, 18
	.2byte SPECIES_GROWLITHE
	.byte 20, 20
	.2byte SPECIES_GROWLITHE
	.byte 17, 17
	.2byte SPECIES_MEOWTH
	.byte 19, 19
	.2byte SPECIES_MEOWTH
	.byte 17, 17
	.2byte SPECIES_MEOWTH
	.byte 20, 20
	.2byte SPECIES_MEOWTH

	.align 2
sWildMonInfo_Route7_Land:: @ 83C9078
	.byte 21
	.align 2
	.4byte sWildMons_Route7_Land

	.align 2
sWildMons_Route8_Land:: @ 83C9080
	.byte 18, 18
	.2byte SPECIES_PIDGEY
	.byte 18, 18
	.2byte SPECIES_MEOWTH
	.byte 16, 16
	.2byte SPECIES_GROWLITHE
	.byte 20, 20
	.2byte SPECIES_PIDGEY
	.byte 20, 20
	.2byte SPECIES_MEOWTH
	.byte 17, 17
	.2byte SPECIES_EKANS
	.byte 17, 17
	.2byte SPECIES_GROWLITHE
	.byte 19, 19
	.2byte SPECIES_EKANS
	.byte 17, 17
	.2byte SPECIES_EKANS
	.byte 15, 15
	.2byte SPECIES_GROWLITHE
	.byte 17, 17
	.2byte SPECIES_EKANS
	.byte 18, 18
	.2byte SPECIES_GROWLITHE

	.align 2
sWildMonInfo_Route8_Land:: @ 83C90B0
	.byte 21
	.align 2
	.4byte sWildMons_Route8_Land

	.align 2
sWildMons_Route9_Land:: @ 83C90B8
	.byte 16, 16
	.2byte SPECIES_SPEAROW
	.byte 16, 16
	.2byte SPECIES_RATTATA
	.byte 11, 11
	.2byte SPECIES_EKANS
	.byte 15, 15
	.2byte SPECIES_EKANS
	.byte 13, 13
	.2byte SPECIES_SPEAROW
	.byte 14, 14
	.2byte SPECIES_RATTATA
	.byte 17, 17
	.2byte SPECIES_SPEAROW
	.byte 17, 17
	.2byte SPECIES_RATTATA
	.byte 14, 14
	.2byte SPECIES_RATTATA
	.byte 13, 13
	.2byte SPECIES_EKANS
	.byte 14, 14
	.2byte SPECIES_RATTATA
	.byte 17, 17
	.2byte SPECIES_EKANS

	.align 2
sWildMonInfo_Route9_Land:: @ 83C90E8
	.byte 21
	.align 2
	.4byte sWildMons_Route9_Land

	.align 2
sWildMons_Route10_Land:: @ 83C90F0
	.byte 16, 16
	.2byte SPECIES_SPEAROW
	.byte 16, 16
	.2byte SPECIES_VOLTORB
	.byte 11, 11
	.2byte SPECIES_EKANS
	.byte 15, 15
	.2byte SPECIES_EKANS
	.byte 13, 13
	.2byte SPECIES_SPEAROW
	.byte 14, 14
	.2byte SPECIES_VOLTORB
	.byte 17, 17
	.2byte SPECIES_SPEAROW
	.byte 17, 17
	.2byte SPECIES_VOLTORB
	.byte 14, 14
	.2byte SPECIES_VOLTORB
	.byte 13, 13
	.2byte SPECIES_EKANS
	.byte 14, 14
	.2byte SPECIES_VOLTORB
	.byte 17, 17
	.2byte SPECIES_EKANS

	.align 2
sWildMonInfo_Route10_Land:: @ 83C9120
	.byte 21
	.align 2
	.4byte sWildMons_Route10_Land

	.align 2
sWildMons_Route10_Water:: @ 83C9128
	.byte 5, 10
	.2byte SPECIES_TENTACOOL
	.byte 10, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 30
	.2byte SPECIES_TENTACOOL
	.byte 30, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL

	.align 2
sWildMonInfo_Route10_Water:: @ 83C913C
	.byte 2
	.align 2
	.4byte sWildMons_Route10_Water

	.align 2
sWildMons_Route10_Fish:: @ 83C9144
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_KRABBY
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_HORSEA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_Route10_Fish:: @ 83C916C
	.byte 20
	.align 2
	.4byte sWildMons_Route10_Fish

	.align 2
sWildMons_Route11_Land:: @ 83C9174
	.byte 14, 14
	.2byte SPECIES_EKANS
	.byte 15, 15
	.2byte SPECIES_SPEAROW
	.byte 12, 12
	.2byte SPECIES_EKANS
	.byte 13, 13
	.2byte SPECIES_SPEAROW
	.byte 11, 11
	.2byte SPECIES_DROWZEE
	.byte 13, 13
	.2byte SPECIES_DROWZEE
	.byte 15, 15
	.2byte SPECIES_EKANS
	.byte 17, 17
	.2byte SPECIES_SPEAROW
	.byte 12, 12
	.2byte SPECIES_EKANS
	.byte 15, 15
	.2byte SPECIES_DROWZEE
	.byte 12, 12
	.2byte SPECIES_EKANS
	.byte 15, 15
	.2byte SPECIES_DROWZEE

	.align 2
sWildMonInfo_Route11_Land:: @ 83C91A4
	.byte 21
	.align 2
	.4byte sWildMons_Route11_Land

	.align 2
sWildMons_Route11_Water:: @ 83C91AC
	.byte 5, 10
	.2byte SPECIES_TENTACOOL
	.byte 10, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 30
	.2byte SPECIES_TENTACOOL
	.byte 30, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL

	.align 2
sWildMonInfo_Route11_Water:: @ 83C91C0
	.byte 2
	.align 2
	.4byte sWildMons_Route11_Water

	.align 2
sWildMons_Route11_Fish:: @ 83C91C8
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_KRABBY
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_HORSEA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_Route11_Fish:: @ 83C91F0
	.byte 20
	.align 2
	.4byte sWildMons_Route11_Fish

	.align 2
sWildMons_Route12_Land:: @ 83C91F8
	.byte 24, 24
	.2byte SPECIES_ODDISH
	.byte 24, 24
	.2byte SPECIES_VENONAT
	.byte 22, 22
	.2byte SPECIES_ODDISH
	.byte 23, 23
	.2byte SPECIES_PIDGEY
	.byte 25, 25
	.2byte SPECIES_PIDGEY
	.byte 26, 26
	.2byte SPECIES_VENONAT
	.byte 26, 26
	.2byte SPECIES_ODDISH
	.byte 27, 27
	.2byte SPECIES_PIDGEY
	.byte 23, 23
	.2byte SPECIES_PIDGEY
	.byte 28, 28
	.2byte SPECIES_GLOOM
	.byte 23, 23
	.2byte SPECIES_PIDGEY
	.byte 30, 30
	.2byte SPECIES_GLOOM

	.align 2
sWildMonInfo_Route12_Land:: @ 83C9228
	.byte 21
	.align 2
	.4byte sWildMons_Route12_Land

	.align 2
sWildMons_Route12_Water:: @ 83C9230
	.byte 5, 10
	.2byte SPECIES_TENTACOOL
	.byte 10, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 30
	.2byte SPECIES_TENTACOOL
	.byte 30, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL

	.align 2
sWildMonInfo_Route12_Water:: @ 83C9244
	.byte 2
	.align 2
	.4byte sWildMons_Route12_Water

	.align 2
sWildMons_Route12_Fish:: @ 83C924C
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_KRABBY
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_HORSEA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_Route12_Fish:: @ 83C9274
	.byte 60
	.align 2
	.4byte sWildMons_Route12_Fish

	.align 2
sWildMons_Route13_Land:: @ 83C927C
	.byte 24, 24
	.2byte SPECIES_ODDISH
	.byte 24, 24
	.2byte SPECIES_VENONAT
	.byte 22, 22
	.2byte SPECIES_ODDISH
	.byte 27, 27
	.2byte SPECIES_PIDGEY
	.byte 25, 25
	.2byte SPECIES_PIDGEY
	.byte 26, 26
	.2byte SPECIES_VENONAT
	.byte 26, 26
	.2byte SPECIES_ODDISH
	.byte 25, 25
	.2byte SPECIES_DITTO
	.byte 29, 29
	.2byte SPECIES_PIDGEOTTO
	.byte 28, 28
	.2byte SPECIES_GLOOM
	.byte 29, 29
	.2byte SPECIES_PIDGEOTTO
	.byte 30, 30
	.2byte SPECIES_GLOOM

	.align 2
sWildMonInfo_Route13_Land:: @ 83C92AC
	.byte 21
	.align 2
	.4byte sWildMons_Route13_Land

	.align 2
sWildMons_Route13_Water:: @ 83C92B4
	.byte 5, 10
	.2byte SPECIES_TENTACOOL
	.byte 10, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 30
	.2byte SPECIES_TENTACOOL
	.byte 30, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL

	.align 2
sWildMonInfo_Route13_Water:: @ 83C92C8
	.byte 2
	.align 2
	.4byte sWildMons_Route13_Water

	.align 2
sWildMons_Route13_Fish:: @ 83C92D0
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_KRABBY
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_HORSEA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_Route13_Fish:: @ 83C92F8
	.byte 20
	.align 2
	.4byte sWildMons_Route13_Fish

	.align 2
sWildMons_Route14_Land:: @ 83C9300
	.byte 24, 24
	.2byte SPECIES_ODDISH
	.byte 24, 24
	.2byte SPECIES_VENONAT
	.byte 22, 22
	.2byte SPECIES_ODDISH
	.byte 23, 23
	.2byte SPECIES_DITTO
	.byte 27, 27
	.2byte SPECIES_PIDGEY
	.byte 26, 26
	.2byte SPECIES_VENONAT
	.byte 26, 26
	.2byte SPECIES_ODDISH
	.byte 30, 30
	.2byte SPECIES_GLOOM
	.byte 23, 23
	.2byte SPECIES_DITTO
	.byte 29, 29
	.2byte SPECIES_PIDGEOTTO
	.byte 23, 23
	.2byte SPECIES_DITTO
	.byte 29, 29
	.2byte SPECIES_PIDGEOTTO

	.align 2
sWildMonInfo_Route14_Land:: @ 83C9330
	.byte 21
	.align 2
	.4byte sWildMons_Route14_Land

	.align 2
sWildMons_Route15_Land:: @ 83C9338
	.byte 24, 24
	.2byte SPECIES_ODDISH
	.byte 24, 24
	.2byte SPECIES_VENONAT
	.byte 22, 22
	.2byte SPECIES_ODDISH
	.byte 27, 27
	.2byte SPECIES_PIDGEY
	.byte 25, 25
	.2byte SPECIES_PIDGEY
	.byte 26, 26
	.2byte SPECIES_VENONAT
	.byte 26, 26
	.2byte SPECIES_ODDISH
	.byte 25, 25
	.2byte SPECIES_DITTO
	.byte 29, 29
	.2byte SPECIES_PIDGEOTTO
	.byte 28, 28
	.2byte SPECIES_GLOOM
	.byte 29, 29
	.2byte SPECIES_PIDGEOTTO
	.byte 30, 30
	.2byte SPECIES_GLOOM

	.align 2
sWildMonInfo_Route15_Land:: @ 83C9368
	.byte 21
	.align 2
	.4byte sWildMons_Route15_Land

	.align 2
sWildMons_Route16_Land:: @ 83C9370
	.byte 20, 20
	.2byte SPECIES_SPEAROW
	.byte 18, 18
	.2byte SPECIES_DODUO
	.byte 18, 18
	.2byte SPECIES_RATTATA
	.byte 20, 20
	.2byte SPECIES_RATTATA
	.byte 22, 22
	.2byte SPECIES_SPEAROW
	.byte 20, 20
	.2byte SPECIES_DODUO
	.byte 22, 22
	.2byte SPECIES_RATTATA
	.byte 22, 22
	.2byte SPECIES_DODUO
	.byte 18, 18
	.2byte SPECIES_RATTATA
	.byte 23, 23
	.2byte SPECIES_RATICATE
	.byte 18, 18
	.2byte SPECIES_RATTATA
	.byte 25, 25
	.2byte SPECIES_RATICATE

	.align 2
sWildMonInfo_Route16_Land:: @ 83C93A0
	.byte 21
	.align 2
	.4byte sWildMons_Route16_Land

	.align 2
sWildMons_Route17_Land:: @ 83C93A8
	.byte 20, 20
	.2byte SPECIES_SPEAROW
	.byte 24, 24
	.2byte SPECIES_DODUO
	.byte 22, 22
	.2byte SPECIES_SPEAROW
	.byte 26, 26
	.2byte SPECIES_DODUO
	.byte 25, 25
	.2byte SPECIES_RATICATE
	.byte 27, 27
	.2byte SPECIES_RATICATE
	.byte 28, 28
	.2byte SPECIES_DODUO
	.byte 29, 29
	.2byte SPECIES_RATICATE
	.byte 22, 22
	.2byte SPECIES_RATTATA
	.byte 25, 25
	.2byte SPECIES_FEAROW
	.byte 22, 22
	.2byte SPECIES_RATTATA
	.byte 27, 27
	.2byte SPECIES_FEAROW

	.align 2
sWildMonInfo_Route17_Land:: @ 83C93D8
	.byte 21
	.align 2
	.4byte sWildMons_Route17_Land

	.align 2
sWildMons_Route18_Land:: @ 83C93E0
	.byte 20, 20
	.2byte SPECIES_SPEAROW
	.byte 24, 24
	.2byte SPECIES_DODUO
	.byte 22, 22
	.2byte SPECIES_SPEAROW
	.byte 26, 26
	.2byte SPECIES_DODUO
	.byte 25, 25
	.2byte SPECIES_RATICATE
	.byte 25, 25
	.2byte SPECIES_FEAROW
	.byte 28, 28
	.2byte SPECIES_DODUO
	.byte 29, 29
	.2byte SPECIES_RATICATE
	.byte 22, 22
	.2byte SPECIES_RATTATA
	.byte 27, 27
	.2byte SPECIES_FEAROW
	.byte 22, 22
	.2byte SPECIES_RATTATA
	.byte 29, 29
	.2byte SPECIES_FEAROW

	.align 2
sWildMonInfo_Route18_Land:: @ 83C9410
	.byte 21
	.align 2
	.4byte sWildMons_Route18_Land

	.align 2
sWildMons_Route19_Water:: @ 83C9418
	.byte 5, 10
	.2byte SPECIES_TENTACOOL
	.byte 10, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 30
	.2byte SPECIES_TENTACOOL
	.byte 30, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL

	.align 2
sWildMonInfo_Route19_Water:: @ 83C942C
	.byte 2
	.align 2
	.4byte sWildMons_Route19_Water

	.align 2
sWildMons_Route19_Fish:: @ 83C9434
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_KRABBY
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_Route19_Fish:: @ 83C945C
	.byte 20
	.align 2
	.4byte sWildMons_Route19_Fish

	.align 2
sWildMons_Route20_Water:: @ 83C9464
	.byte 5, 10
	.2byte SPECIES_TENTACOOL
	.byte 10, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 30
	.2byte SPECIES_TENTACOOL
	.byte 30, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL

	.align 2
sWildMonInfo_Route20_Water:: @ 83C9478
	.byte 2
	.align 2
	.4byte sWildMons_Route20_Water

	.align 2
sWildMons_Route20_Fish:: @ 83C9480
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_KRABBY
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_Route20_Fish:: @ 83C94A8
	.byte 20
	.align 2
	.4byte sWildMons_Route20_Fish

	.align 2
sWildMons_Route21North_Land:: @ 83C94B0
	.byte 22, 22
	.2byte SPECIES_TANGELA
	.byte 23, 23
	.2byte SPECIES_TANGELA
	.byte 24, 24
	.2byte SPECIES_TANGELA
	.byte 21, 21
	.2byte SPECIES_TANGELA
	.byte 25, 25
	.2byte SPECIES_TANGELA
	.byte 20, 20
	.2byte SPECIES_TANGELA
	.byte 19, 19
	.2byte SPECIES_TANGELA
	.byte 26, 26
	.2byte SPECIES_TANGELA
	.byte 18, 18
	.2byte SPECIES_TANGELA
	.byte 27, 27
	.2byte SPECIES_TANGELA
	.byte 17, 17
	.2byte SPECIES_TANGELA
	.byte 28, 28
	.2byte SPECIES_TANGELA

	.align 2
sWildMonInfo_Route21North_Land:: @ 83C94E0
	.byte 14
	.align 2
	.4byte sWildMons_Route21North_Land

	.align 2
sWildMons_Route21North_Water:: @ 83C94E8
	.byte 5, 10
	.2byte SPECIES_TENTACOOL
	.byte 10, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 30
	.2byte SPECIES_TENTACOOL
	.byte 30, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL

	.align 2
sWildMonInfo_Route21North_Water:: @ 83C94FC
	.byte 2
	.align 2
	.4byte sWildMons_Route21North_Water

	.align 2
sWildMons_Route21North_Fish:: @ 83C9504
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_KRABBY
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_Route21North_Fish:: @ 83C952C
	.byte 20
	.align 2
	.4byte sWildMons_Route21North_Fish

	.align 2
sWildMons_Route21South_Land:: @ 83C9534
	.byte 22, 22
	.2byte SPECIES_TANGELA
	.byte 23, 23
	.2byte SPECIES_TANGELA
	.byte 24, 24
	.2byte SPECIES_TANGELA
	.byte 21, 21
	.2byte SPECIES_TANGELA
	.byte 25, 25
	.2byte SPECIES_TANGELA
	.byte 20, 20
	.2byte SPECIES_TANGELA
	.byte 19, 19
	.2byte SPECIES_TANGELA
	.byte 26, 26
	.2byte SPECIES_TANGELA
	.byte 18, 18
	.2byte SPECIES_TANGELA
	.byte 27, 27
	.2byte SPECIES_TANGELA
	.byte 17, 17
	.2byte SPECIES_TANGELA
	.byte 28, 28
	.2byte SPECIES_TANGELA

	.align 2
sWildMonInfo_Route21South_Land:: @ 83C9564
	.byte 14
	.align 2
	.4byte sWildMons_Route21South_Land

	.align 2
sWildMons_Route21South_Water:: @ 83C956C
	.byte 5, 10
	.2byte SPECIES_TENTACOOL
	.byte 10, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 30
	.2byte SPECIES_TENTACOOL
	.byte 30, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL

	.align 2
sWildMonInfo_Route21South_Water:: @ 83C9580
	.byte 2
	.align 2
	.4byte sWildMons_Route21South_Water

	.align 2
sWildMons_Route21South_Fish:: @ 83C9588
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_KRABBY
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_Route21South_Fish:: @ 83C95B0
	.byte 20
	.align 2
	.4byte sWildMons_Route21South_Fish

	.align 2
sWildMons_Route22_Land:: @ 83C95B8
	.byte 3, 3
	.2byte SPECIES_RATTATA
	.byte 3, 3
	.2byte SPECIES_MANKEY
	.byte 4, 4
	.2byte SPECIES_RATTATA
	.byte 4, 4
	.2byte SPECIES_MANKEY
	.byte 2, 2
	.2byte SPECIES_RATTATA
	.byte 2, 2
	.2byte SPECIES_MANKEY
	.byte 3, 3
	.2byte SPECIES_SPEAROW
	.byte 5, 5
	.2byte SPECIES_SPEAROW
	.byte 5, 5
	.2byte SPECIES_RATTATA
	.byte 5, 5
	.2byte SPECIES_MANKEY
	.byte 5, 5
	.2byte SPECIES_RATTATA
	.byte 5, 5
	.2byte SPECIES_MANKEY

	.align 2
sWildMonInfo_Route22_Land:: @ 83C95E8
	.byte 21
	.align 2
	.4byte sWildMons_Route22_Land

	.align 2
sWildMons_Route22_Water:: @ 83C95F0
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 30
	.2byte SPECIES_PSYDUCK
	.byte 30, 35
	.2byte SPECIES_PSYDUCK
	.byte 35, 40
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_Route22_Water:: @ 83C9604
	.byte 2
	.align 2
	.4byte sWildMons_Route22_Water

	.align 2
sWildMons_Route22_Fish:: @ 83C960C
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_POLIWAG
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_GOLDEEN
	.byte 15, 25
	.2byte SPECIES_POLIWAG
	.byte 20, 30
	.2byte SPECIES_POLIWHIRL
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 15, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_Route22_Fish:: @ 83C9634
	.byte 20
	.align 2
	.4byte sWildMons_Route22_Fish

	.align 2
sWildMons_Route23_Land:: @ 83C963C
	.byte 32, 32
	.2byte SPECIES_MANKEY
	.byte 40, 40
	.2byte SPECIES_FEAROW
	.byte 34, 34
	.2byte SPECIES_MANKEY
	.byte 34, 34
	.2byte SPECIES_SPEAROW
	.byte 32, 32
	.2byte SPECIES_EKANS
	.byte 34, 34
	.2byte SPECIES_EKANS
	.byte 42, 42
	.2byte SPECIES_PRIMEAPE
	.byte 44, 44
	.2byte SPECIES_ARBOK
	.byte 32, 32
	.2byte SPECIES_SPEAROW
	.byte 42, 42
	.2byte SPECIES_FEAROW
	.byte 32, 32
	.2byte SPECIES_SPEAROW
	.byte 44, 44
	.2byte SPECIES_FEAROW

	.align 2
sWildMonInfo_Route23_Land:: @ 83C966C
	.byte 21
	.align 2
	.4byte sWildMons_Route23_Land

	.align 2
sWildMons_Route23_Water:: @ 83C9674
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 30
	.2byte SPECIES_PSYDUCK
	.byte 30, 35
	.2byte SPECIES_PSYDUCK
	.byte 35, 40
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_Route23_Water:: @ 83C9688
	.byte 2
	.align 2
	.4byte sWildMons_Route23_Water

	.align 2
sWildMons_Route23_Fish:: @ 83C9690
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_POLIWAG
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_GOLDEEN
	.byte 15, 25
	.2byte SPECIES_POLIWAG
	.byte 20, 30
	.2byte SPECIES_POLIWHIRL
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 15, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_Route23_Fish:: @ 83C96B8
	.byte 20
	.align 2
	.4byte sWildMons_Route23_Fish

	.align 2
sWildMons_Route24_Land:: @ 83C96C0
	.byte 7, 7
	.2byte SPECIES_WEEDLE
	.byte 7, 7
	.2byte SPECIES_CATERPIE
	.byte 11, 11
	.2byte SPECIES_PIDGEY
	.byte 12, 12
	.2byte SPECIES_ODDISH
	.byte 13, 13
	.2byte SPECIES_ODDISH
	.byte 10, 10
	.2byte SPECIES_ABRA
	.byte 13, 13
	.2byte SPECIES_PIDGEY
	.byte 14, 14
	.2byte SPECIES_ODDISH
	.byte 8, 8
	.2byte SPECIES_KAKUNA
	.byte 8, 8
	.2byte SPECIES_ABRA
	.byte 8, 8
	.2byte SPECIES_METAPOD
	.byte 12, 12
	.2byte SPECIES_ABRA

	.align 2
sWildMonInfo_Route24_Land:: @ 83C96F0
	.byte 21
	.align 2
	.4byte sWildMons_Route24_Land

	.align 2
sWildMons_Route24_Water:: @ 83C96F8
	.byte 5, 10
	.2byte SPECIES_TENTACOOL
	.byte 10, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 30
	.2byte SPECIES_TENTACOOL
	.byte 30, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL

	.align 2
sWildMonInfo_Route24_Water:: @ 83C970C
	.byte 2
	.align 2
	.4byte sWildMons_Route24_Water

	.align 2
sWildMons_Route24_Fish:: @ 83C9714
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_KRABBY
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_HORSEA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_Route24_Fish:: @ 83C973C
	.byte 20
	.align 2
	.4byte sWildMons_Route24_Fish

	.align 2
sWildMons_Route25_Land:: @ 83C9744
	.byte 8, 8
	.2byte SPECIES_WEEDLE
	.byte 8, 8
	.2byte SPECIES_CATERPIE
	.byte 13, 13
	.2byte SPECIES_PIDGEY
	.byte 14, 14
	.2byte SPECIES_ODDISH
	.byte 13, 13
	.2byte SPECIES_ODDISH
	.byte 11, 11
	.2byte SPECIES_ABRA
	.byte 11, 11
	.2byte SPECIES_PIDGEY
	.byte 12, 12
	.2byte SPECIES_ODDISH
	.byte 9, 9
	.2byte SPECIES_KAKUNA
	.byte 9, 9
	.2byte SPECIES_ABRA
	.byte 9, 9
	.2byte SPECIES_METAPOD
	.byte 13, 13
	.2byte SPECIES_ABRA

	.align 2
sWildMonInfo_Route25_Land:: @ 83C9774
	.byte 21
	.align 2
	.4byte sWildMons_Route25_Land

	.align 2
sWildMons_Route25_Water:: @ 83C977C
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 30
	.2byte SPECIES_PSYDUCK
	.byte 30, 35
	.2byte SPECIES_PSYDUCK
	.byte 35, 40
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_Route25_Water:: @ 83C9790
	.byte 2
	.align 2
	.4byte sWildMons_Route25_Water

	.align 2
sWildMons_Route25_Fish:: @ 83C9798
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_POLIWAG
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_GOLDEEN
	.byte 15, 25
	.2byte SPECIES_POLIWAG
	.byte 20, 30
	.2byte SPECIES_POLIWHIRL
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 15, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_Route25_Fish:: @ 83C97C0
	.byte 20
	.align 2
	.4byte sWildMons_Route25_Fish

	.align 2
sWildMons_PalletTown_Water:: @ 83C97C8
	.byte 5, 10
	.2byte SPECIES_TENTACOOL
	.byte 10, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 30
	.2byte SPECIES_TENTACOOL
	.byte 30, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL

	.align 2
sWildMonInfo_PalletTown_Water:: @ 83C97DC
	.byte 1
	.align 2
	.4byte sWildMons_PalletTown_Water

	.align 2
sWildMons_PalletTown_Fish:: @ 83C97E4
	.byte 5, 10
	.2byte SPECIES_MAGIKARP
	.byte 5, 10
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_KRABBY
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_SHELLDER
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_PalletTown_Fish:: @ 83C980C
	.byte 10
	.align 2
	.4byte sWildMons_PalletTown_Fish

	.align 2
sWildMons_ViridianCity_Water:: @ 83C9814
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 30
	.2byte SPECIES_PSYDUCK
	.byte 30, 35
	.2byte SPECIES_PSYDUCK
	.byte 35, 40
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_ViridianCity_Water:: @ 83C9828
	.byte 1
	.align 2
	.4byte sWildMons_ViridianCity_Water

	.align 2
sWildMons_ViridianCity_Fish:: @ 83C9830
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_POLIWAG
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_GOLDEEN
	.byte 15, 25
	.2byte SPECIES_POLIWAG
	.byte 20, 30
	.2byte SPECIES_POLIWHIRL
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 15, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_ViridianCity_Fish:: @ 83C9858
	.byte 10
	.align 2
	.4byte sWildMons_ViridianCity_Fish

	.align 2
sWildMons_CeruleanCity_Water:: @ 83C9860
	.byte 5, 10
	.2byte SPECIES_TENTACOOL
	.byte 10, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 30
	.2byte SPECIES_TENTACOOL
	.byte 30, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL

	.align 2
sWildMonInfo_CeruleanCity_Water:: @ 83C9874
	.byte 1
	.align 2
	.4byte sWildMons_CeruleanCity_Water

	.align 2
sWildMons_CeruleanCity_Fish:: @ 83C987C
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_KRABBY
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_HORSEA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_CeruleanCity_Fish:: @ 83C98A4
	.byte 10
	.align 2
	.4byte sWildMons_CeruleanCity_Fish

	.align 2
sWildMons_VermilionCity_Water:: @ 83C98AC
	.byte 5, 10
	.2byte SPECIES_TENTACOOL
	.byte 10, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 30
	.2byte SPECIES_TENTACOOL
	.byte 30, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL

	.align 2
sWildMonInfo_VermilionCity_Water:: @ 83C98C0
	.byte 1
	.align 2
	.4byte sWildMons_VermilionCity_Water

	.align 2
sWildMons_VermilionCity_Fish:: @ 83C98C8
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_KRABBY
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_SHELLDER
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_HORSEA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_VermilionCity_Fish:: @ 83C98F0
	.byte 10
	.align 2
	.4byte sWildMons_VermilionCity_Fish

	.align 2
sWildMons_CeladonCity_Water:: @ 83C98F8
	.byte 5, 10
	.2byte SPECIES_PSYDUCK
	.byte 10, 20
	.2byte SPECIES_PSYDUCK
	.byte 20, 30
	.2byte SPECIES_PSYDUCK
	.byte 30, 40
	.2byte SPECIES_PSYDUCK
	.byte 30, 40
	.2byte SPECIES_KOFFING

	.align 2
sWildMonInfo_CeladonCity_Water:: @ 83C990C
	.byte 1
	.align 2
	.4byte sWildMons_CeladonCity_Water

	.align 2
sWildMons_CeladonCity_Fish:: @ 83C9914
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 15, 25
	.2byte SPECIES_MAGIKARP
	.byte 15, 25
	.2byte SPECIES_MAGIKARP
	.byte 15, 25
	.2byte SPECIES_MAGIKARP
	.byte 25, 35
	.2byte SPECIES_MAGIKARP
	.byte 30, 40
	.2byte SPECIES_GRIMER

	.align 2
sWildMonInfo_CeladonCity_Fish:: @ 83C993C
	.byte 10
	.align 2
	.4byte sWildMons_CeladonCity_Fish

	.align 2
sWildMons_FuchsiaCity_Water:: @ 83C9944
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 20, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 30
	.2byte SPECIES_PSYDUCK
	.byte 30, 35
	.2byte SPECIES_PSYDUCK
	.byte 35, 40
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_FuchsiaCity_Water:: @ 83C9958
	.byte 1
	.align 2
	.4byte sWildMons_FuchsiaCity_Water

	.align 2
sWildMons_FuchsiaCity_Fish:: @ 83C9960
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_GOLDEEN
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_POLIWAG
	.byte 15, 25
	.2byte SPECIES_GOLDEEN
	.byte 20, 30
	.2byte SPECIES_SEAKING
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 15, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_FuchsiaCity_Fish:: @ 83C9988
	.byte 10
	.align 2
	.4byte sWildMons_FuchsiaCity_Fish

	.align 2
sWildMons_CinnabarIsland_Water:: @ 83C9990
	.byte 5, 10
	.2byte SPECIES_TENTACOOL
	.byte 10, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 30
	.2byte SPECIES_TENTACOOL
	.byte 30, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL

	.align 2
sWildMonInfo_CinnabarIsland_Water:: @ 83C99A4
	.byte 1
	.align 2
	.4byte sWildMons_CinnabarIsland_Water

	.align 2
sWildMons_CinnabarIsland_Fish:: @ 83C99AC
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_KRABBY
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_SHELLDER
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_CinnabarIsland_Fish:: @ 83C99D4
	.byte 10
	.align 2
	.4byte sWildMons_CinnabarIsland_Fish

	.align 2
sWildMons_OneIsland_Water:: @ 83C99DC
	.byte 5, 20
	.2byte SPECIES_TENTACOOL
	.byte 20, 35
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL

	.align 2
sWildMonInfo_OneIsland_Water:: @ 83C99F0
	.byte 1
	.align 2
	.4byte sWildMons_OneIsland_Water

	.align 2
sWildMons_OneIsland_Fish:: @ 83C99F8
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_SHELLDER
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_OneIsland_Fish:: @ 83C9A20
	.byte 10
	.align 2
	.4byte sWildMons_OneIsland_Fish

	.align 2
sWildMons_FourIsland_Water:: @ 83C9A28
	.byte 5, 15
	.2byte SPECIES_WOOPER
	.byte 5, 35
	.2byte SPECIES_PSYDUCK
	.byte 15, 25
	.2byte SPECIES_WOOPER
	.byte 15, 25
	.2byte SPECIES_WOOPER
	.byte 15, 25
	.2byte SPECIES_WOOPER

	.align 2
sWildMonInfo_FourIsland_Water:: @ 83C9A3C
	.byte 2
	.align 2
	.4byte sWildMons_FourIsland_Water

	.align 2
sWildMons_FourIsland_Fish:: @ 83C9A44
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_POLIWAG
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_GOLDEEN
	.byte 15, 25
	.2byte SPECIES_POLIWAG
	.byte 20, 30
	.2byte SPECIES_POLIWHIRL
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 15, 25
	.2byte SPECIES_PSYDUCK
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_FourIsland_Fish:: @ 83C9A6C
	.byte 20
	.align 2
	.4byte sWildMons_FourIsland_Fish

	.align 2
sWildMons_FiveIsland_Water:: @ 83C9A74
	.byte 5, 35
	.2byte SPECIES_TENTACOOL
	.byte 5, 15
	.2byte SPECIES_HOPPIP
	.byte 35, 40
	.2byte SPECIES_TENTACOOL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL
	.byte 35, 40
	.2byte SPECIES_TENTACRUEL

	.align 2
sWildMonInfo_FiveIsland_Water:: @ 83C9A88
	.byte 1
	.align 2
	.4byte sWildMons_FiveIsland_Water

	.align 2
sWildMons_FiveIsland_Fish:: @ 83C9A90
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 5
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 5, 15
	.2byte SPECIES_MAGIKARP
	.byte 5, 15
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_HORSEA
	.byte 15, 25
	.2byte SPECIES_SHELLDER
	.byte 15, 25
	.2byte SPECIES_GYARADOS
	.byte 25, 35
	.2byte SPECIES_SEADRA
	.byte 25, 35
	.2byte SPECIES_PSYDUCK

	.align 2
sWildMonInfo_FiveIsland_Fish:: @ 83C9AB8
	.byte 10
	.align 2
	.4byte sWildMons_FiveIsland_Fish

	.align 2
sWildMons_SixIslandAlteringCave_Land:: @ 83C9AC0
	.byte 10, 10
	.2byte SPECIES_ZUBAT
	.byte 12, 12
	.2byte SPECIES_ZUBAT
	.byte 8, 8
	.2byte SPECIES_ZUBAT
	.byte 14, 14
	.2byte SPECIES_ZUBAT
	.byte 10, 10
	.2byte SPECIES_ZUBAT
	.byte 12, 12
	.2byte SPECIES_ZUBAT
	.byte 16, 16
	.2byte SPECIES_ZUBAT
	.byte 6, 6
	.2byte SPECIES_ZUBAT
	.byte 8, 8
	.2byte SPECIES_ZUBAT
	.byte 14, 14
	.2byte SPECIES_ZUBAT
	.byte 8, 8
	.2byte SPECIES_ZUBAT
	.byte 14, 14
	.2byte SPECIES_ZUBAT

	.align 2
sWildMonInfo_SixIslandAlteringCave_Land:: @ 83C9AF0
	.byte 5
	.align 2
	.4byte sWildMons_SixIslandAlteringCave_Land

	.align 2
sWildMons_SixIslandAlteringCave_2_Land:: @ 83C9AF8
	.byte 7, 7
	.2byte SPECIES_MAREEP
	.byte 9, 9
	.2byte SPECIES_MAREEP
	.byte 5, 5
	.2byte SPECIES_MAREEP
	.byte 11, 11
	.2byte SPECIES_MAREEP
	.byte 7, 7
	.2byte SPECIES_MAREEP
	.byte 9, 9
	.2byte SPECIES_MAREEP
	.byte 13, 13
	.2byte SPECIES_MAREEP
	.byte 3, 3
	.2byte SPECIES_MAREEP
	.byte 5, 5
	.2byte SPECIES_MAREEP
	.byte 11, 11
	.2byte SPECIES_MAREEP
	.byte 5, 5
	.2byte SPECIES_MAREEP
	.byte 11, 11
	.2byte SPECIES_MAREEP

	.align 2
sWildMonInfo_SixIslandAlteringCave_2_Land:: @ 83C9B28
	.byte 5
	.align 2
	.4byte sWildMons_SixIslandAlteringCave_2_Land

	.align 2
sWildMons_SixIslandAlteringCave_3_Land:: @ 83C9B30
	.byte 23, 23
	.2byte SPECIES_PINECO
	.byte 25, 25
	.2byte SPECIES_PINECO
	.byte 22, 22
	.2byte SPECIES_PINECO
	.byte 27, 27
	.2byte SPECIES_PINECO
	.byte 23, 23
	.2byte SPECIES_PINECO
	.byte 25, 25
	.2byte SPECIES_PINECO
	.byte 29, 29
	.2byte SPECIES_PINECO
	.byte 19, 19
	.2byte SPECIES_PINECO
	.byte 21, 21
	.2byte SPECIES_PINECO
	.byte 27, 27
	.2byte SPECIES_PINECO
	.byte 21, 21
	.2byte SPECIES_PINECO
	.byte 27, 27
	.2byte SPECIES_PINECO

	.align 2
sWildMonInfo_SixIslandAlteringCave_3_Land:: @ 83C9B60
	.byte 5
	.align 2
	.4byte sWildMons_SixIslandAlteringCave_3_Land

	.align 2
sWildMons_SixIslandAlteringCave_4_Land:: @ 83C9B68
	.byte 16, 16
	.2byte SPECIES_HOUNDOUR
	.byte 18, 18
	.2byte SPECIES_HOUNDOUR
	.byte 14, 14
	.2byte SPECIES_HOUNDOUR
	.byte 20, 20
	.2byte SPECIES_HOUNDOUR
	.byte 16, 16
	.2byte SPECIES_HOUNDOUR
	.byte 18, 18
	.2byte SPECIES_HOUNDOUR
	.byte 22, 22
	.2byte SPECIES_HOUNDOUR
	.byte 12, 12
	.2byte SPECIES_HOUNDOUR
	.byte 14, 14
	.2byte SPECIES_HOUNDOUR
	.byte 20, 20
	.2byte SPECIES_HOUNDOUR
	.byte 14, 14
	.2byte SPECIES_HOUNDOUR
	.byte 20, 20
	.2byte SPECIES_HOUNDOUR

	.align 2
sWildMonInfo_SixIslandAlteringCave_4_Land:: @ 83C9B98
	.byte 5
	.align 2
	.4byte sWildMons_SixIslandAlteringCave_4_Land

	.align 2
sWildMons_SixIslandAlteringCave_5_Land:: @ 83C9BA0
	.byte 22, 22
	.2byte SPECIES_TEDDIURSA
	.byte 24, 24
	.2byte SPECIES_TEDDIURSA
	.byte 20, 20
	.2byte SPECIES_TEDDIURSA
	.byte 26, 26
	.2byte SPECIES_TEDDIURSA
	.byte 22, 22
	.2byte SPECIES_TEDDIURSA
	.byte 24, 24
	.2byte SPECIES_TEDDIURSA
	.byte 28, 28
	.2byte SPECIES_TEDDIURSA
	.byte 18, 18
	.2byte SPECIES_TEDDIURSA
	.byte 20, 20
	.2byte SPECIES_TEDDIURSA
	.byte 26, 26
	.2byte SPECIES_TEDDIURSA
	.byte 20, 20
	.2byte SPECIES_TEDDIURSA
	.byte 26, 26
	.2byte SPECIES_TEDDIURSA

	.align 2
sWildMonInfo_SixIslandAlteringCave_5_Land:: @ 83C9BD0
	.byte 5
	.align 2
	.4byte sWildMons_SixIslandAlteringCave_5_Land

	.align 2
sWildMons_SixIslandAlteringCave_6_Land:: @ 83C9BD8
	.byte 22, 22
	.2byte SPECIES_AIPOM
	.byte 24, 24
	.2byte SPECIES_AIPOM
	.byte 20, 20
	.2byte SPECIES_AIPOM
	.byte 26, 26
	.2byte SPECIES_AIPOM
	.byte 22, 22
	.2byte SPECIES_AIPOM
	.byte 24, 24
	.2byte SPECIES_AIPOM
	.byte 28, 28
	.2byte SPECIES_AIPOM
	.byte 18, 18
	.2byte SPECIES_AIPOM
	.byte 20, 20
	.2byte SPECIES_AIPOM
	.byte 26, 26
	.2byte SPECIES_AIPOM
	.byte 20, 20
	.2byte SPECIES_AIPOM
	.byte 26, 26
	.2byte SPECIES_AIPOM

	.align 2
sWildMonInfo_SixIslandAlteringCave_6_Land:: @ 83C9C08
	.byte 5
	.align 2
	.4byte sWildMons_SixIslandAlteringCave_6_Land

	.align 2
sWildMons_SixIslandAlteringCave_7_Land:: @ 83C9C10
	.byte 22, 22
	.2byte SPECIES_SHUCKLE
	.byte 24, 24
	.2byte SPECIES_SHUCKLE
	.byte 20, 20
	.2byte SPECIES_SHUCKLE
	.byte 26, 26
	.2byte SPECIES_SHUCKLE
	.byte 22, 22
	.2byte SPECIES_SHUCKLE
	.byte 24, 24
	.2byte SPECIES_SHUCKLE
	.byte 28, 28
	.2byte SPECIES_SHUCKLE
	.byte 18, 18
	.2byte SPECIES_SHUCKLE
	.byte 20, 20
	.2byte SPECIES_SHUCKLE
	.byte 26, 26
	.2byte SPECIES_SHUCKLE
	.byte 20, 20
	.2byte SPECIES_SHUCKLE
	.byte 26, 26
	.2byte SPECIES_SHUCKLE

	.align 2
sWildMonInfo_SixIslandAlteringCave_7_Land:: @ 83C9C40
	.byte 5
	.align 2
	.4byte sWildMons_SixIslandAlteringCave_7_Land

	.align 2
sWildMons_SixIslandAlteringCave_8_Land:: @ 83C9C48
	.byte 22, 22
	.2byte SPECIES_STANTLER
	.byte 24, 24
	.2byte SPECIES_STANTLER
	.byte 20, 20
	.2byte SPECIES_STANTLER
	.byte 26, 26
	.2byte SPECIES_STANTLER
	.byte 22, 22
	.2byte SPECIES_STANTLER
	.byte 24, 24
	.2byte SPECIES_STANTLER
	.byte 28, 28
	.2byte SPECIES_STANTLER
	.byte 18, 18
	.2byte SPECIES_STANTLER
	.byte 20, 20
	.2byte SPECIES_STANTLER
	.byte 26, 26
	.2byte SPECIES_STANTLER
	.byte 20, 20
	.2byte SPECIES_STANTLER
	.byte 26, 26
	.2byte SPECIES_STANTLER

	.align 2
sWildMonInfo_SixIslandAlteringCave_8_Land:: @ 83C9C78
	.byte 5
	.align 2
	.4byte sWildMons_SixIslandAlteringCave_8_Land

	.align 2
sWildMons_SixIslandAlteringCave_9_Land:: @ 83C9C80
	.byte 22, 22
	.2byte SPECIES_SMEARGLE
	.byte 24, 24
	.2byte SPECIES_SMEARGLE
	.byte 20, 20
	.2byte SPECIES_SMEARGLE
	.byte 26, 26
	.2byte SPECIES_SMEARGLE
	.byte 22, 22
	.2byte SPECIES_SMEARGLE
	.byte 24, 24
	.2byte SPECIES_SMEARGLE
	.byte 28, 28
	.2byte SPECIES_SMEARGLE
	.byte 18, 18
	.2byte SPECIES_SMEARGLE
	.byte 20, 20
	.2byte SPECIES_SMEARGLE
	.byte 26, 26
	.2byte SPECIES_SMEARGLE
	.byte 20, 20
	.2byte SPECIES_SMEARGLE
	.byte 26, 26
	.2byte SPECIES_SMEARGLE

	.align 2
sWildMonInfo_SixIslandAlteringCave_9_Land:: @ 83C9CB0
	.byte 5
	.align 2
	.4byte sWildMons_SixIslandAlteringCave_9_Land

	.align 2
gWildMonHeaders:: @ 83C9CB8
	.byte MAP_GROUP(SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER), MAP_NUM(SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER)
	.align 2
	.4byte sWildMonInfo_SevenIslandTanobyRuinsMoneanChamber_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SEVEN_ISLAND_TANOBY_RUINS_LIPTOO_CHAMBER), MAP_NUM(SEVEN_ISLAND_TANOBY_RUINS_LIPTOO_CHAMBER)
	.align 2
	.4byte sWildMonInfo_SevenIslandTanobyRuinsLiptooChamber_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SEVEN_ISLAND_TANOBY_RUINS_WEEPTH_CHAMBER), MAP_NUM(SEVEN_ISLAND_TANOBY_RUINS_WEEPTH_CHAMBER)
	.align 2
	.4byte sWildMonInfo_SevenIslandTanobyRuinsWeepthChamber_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SEVEN_ISLAND_TANOBY_RUINS_DILFORD_CHAMBER), MAP_NUM(SEVEN_ISLAND_TANOBY_RUINS_DILFORD_CHAMBER)
	.align 2
	.4byte sWildMonInfo_SevenIslandTanobyRuinsDilfordChamber_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SEVEN_ISLAND_TANOBY_RUINS_SCUFIB_CHAMBER), MAP_NUM(SEVEN_ISLAND_TANOBY_RUINS_SCUFIB_CHAMBER)
	.align 2
	.4byte sWildMonInfo_SevenIslandTanobyRuinsScufibChamber_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SEVEN_ISLAND_TANOBY_RUINS_RIXY_CHAMBER), MAP_NUM(SEVEN_ISLAND_TANOBY_RUINS_RIXY_CHAMBER)
	.align 2
	.4byte sWildMonInfo_SevenIslandTanobyRuinsRixyChamber_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SEVEN_ISLAND_TANOBY_RUINS_VIAPOIS_CHAMBER), MAP_NUM(SEVEN_ISLAND_TANOBY_RUINS_VIAPOIS_CHAMBER)
	.align 2
	.4byte sWildMonInfo_SevenIslandTanobyRuinsViapoisChamber_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(VIRIDIAN_FOREST), MAP_NUM(VIRIDIAN_FOREST)
	.align 2
	.4byte sWildMonInfo_ViridianForest_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(MT_MOON_1F), MAP_NUM(MT_MOON_1F)
	.align 2
	.4byte sWildMonInfo_MtMoon1F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(MT_MOON_B1F), MAP_NUM(MT_MOON_B1F)
	.align 2
	.4byte sWildMonInfo_MtMoonB1F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(MT_MOON_B2F), MAP_NUM(MT_MOON_B2F)
	.align 2
	.4byte sWildMonInfo_MtMoonB2F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SSANNE_EXTERIOR), MAP_NUM(SSANNE_EXTERIOR)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_SSAnneExterior_Water
	.4byte NULL
	.4byte sWildMonInfo_SSAnneExterior_Fish
	.byte MAP_GROUP(DIGLETTS_CAVE_B1F), MAP_NUM(DIGLETTS_CAVE_B1F)
	.align 2
	.4byte sWildMonInfo_DiglettsCaveB1F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(VICTORY_ROAD_1F), MAP_NUM(VICTORY_ROAD_1F)
	.align 2
	.4byte sWildMonInfo_VictoryRoad1F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(VICTORY_ROAD_2F), MAP_NUM(VICTORY_ROAD_2F)
	.align 2
	.4byte sWildMonInfo_VictoryRoad2F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(VICTORY_ROAD_3F), MAP_NUM(VICTORY_ROAD_3F)
	.align 2
	.4byte sWildMonInfo_VictoryRoad3F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(POKEMON_MANSION_1F), MAP_NUM(POKEMON_MANSION_1F)
	.align 2
	.4byte sWildMonInfo_PokemonMansion1F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(POKEMON_MANSION_2F), MAP_NUM(POKEMON_MANSION_2F)
	.align 2
	.4byte sWildMonInfo_PokemonMansion2F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(POKEMON_MANSION_3F), MAP_NUM(POKEMON_MANSION_3F)
	.align 2
	.4byte sWildMonInfo_PokemonMansion3F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(POKEMON_MANSION_B1F), MAP_NUM(POKEMON_MANSION_B1F)
	.align 2
	.4byte sWildMonInfo_PokemonMansionB1F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SAFARI_ZONE_CENTER), MAP_NUM(SAFARI_ZONE_CENTER)
	.align 2
	.4byte sWildMonInfo_SafariZoneCenter_Land
	.4byte sWildMonInfo_SafariZoneCenter_Water
	.4byte NULL
	.4byte sWildMonInfo_SafariZoneCenter_Fish
	.byte MAP_GROUP(SAFARI_ZONE_EAST), MAP_NUM(SAFARI_ZONE_EAST)
	.align 2
	.4byte sWildMonInfo_SafariZoneEast_Land
	.4byte sWildMonInfo_SafariZoneEast_Water
	.4byte NULL
	.4byte sWildMonInfo_SafariZoneEast_Fish
	.byte MAP_GROUP(SAFARI_ZONE_NORTH), MAP_NUM(SAFARI_ZONE_NORTH)
	.align 2
	.4byte sWildMonInfo_SafariZoneNorth_Land
	.4byte sWildMonInfo_SafariZoneNorth_Water
	.4byte NULL
	.4byte sWildMonInfo_SafariZoneNorth_Fish
	.byte MAP_GROUP(SAFARI_ZONE_WEST), MAP_NUM(SAFARI_ZONE_WEST)
	.align 2
	.4byte sWildMonInfo_SafariZoneWest_Land
	.4byte sWildMonInfo_SafariZoneWest_Water
	.4byte NULL
	.4byte sWildMonInfo_SafariZoneWest_Fish
	.byte MAP_GROUP(CERULEAN_CAVE_1F), MAP_NUM(CERULEAN_CAVE_1F)
	.align 2
	.4byte sWildMonInfo_CeruleanCave1F_Land
	.4byte sWildMonInfo_CeruleanCave1F_Water
	.4byte sWildMonInfo_CeruleanCave1F_Rock
	.4byte sWildMonInfo_CeruleanCave1F_Fish
	.byte MAP_GROUP(CERULEAN_CAVE_2F), MAP_NUM(CERULEAN_CAVE_2F)
	.align 2
	.4byte sWildMonInfo_CeruleanCave2F_Land
	.4byte NULL
	.4byte sWildMonInfo_CeruleanCave2F_Rock
	.4byte NULL
	.byte MAP_GROUP(CERULEAN_CAVE_B1F), MAP_NUM(CERULEAN_CAVE_B1F)
	.align 2
	.4byte sWildMonInfo_CeruleanCaveB1F_Land
	.4byte sWildMonInfo_CeruleanCaveB1F_Water
	.4byte sWildMonInfo_CeruleanCaveB1F_Rock
	.4byte sWildMonInfo_CeruleanCaveB1F_Fish
	.byte MAP_GROUP(ROCK_TUNNEL_1F), MAP_NUM(ROCK_TUNNEL_1F)
	.align 2
	.4byte sWildMonInfo_RockTunnel1F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(ROCK_TUNNEL_B1F), MAP_NUM(ROCK_TUNNEL_B1F)
	.align 2
	.4byte sWildMonInfo_RockTunnelB1F_Land
	.4byte NULL
	.4byte sWildMonInfo_RockTunnelB1F_Rock
	.4byte NULL
	.byte MAP_GROUP(SEAFOAM_ISLANDS_1F), MAP_NUM(SEAFOAM_ISLANDS_1F)
	.align 2
	.4byte sWildMonInfo_SeafoamIslands1F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SEAFOAM_ISLANDS_B1F), MAP_NUM(SEAFOAM_ISLANDS_B1F)
	.align 2
	.4byte sWildMonInfo_SeafoamIslandsB1F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SEAFOAM_ISLANDS_B2F), MAP_NUM(SEAFOAM_ISLANDS_B2F)
	.align 2
	.4byte sWildMonInfo_SeafoamIslandsB2F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SEAFOAM_ISLANDS_B3F), MAP_NUM(SEAFOAM_ISLANDS_B3F)
	.align 2
	.4byte sWildMonInfo_SeafoamIslandsB3F_Land
	.4byte sWildMonInfo_SeafoamIslandsB3F_Water
	.4byte NULL
	.4byte sWildMonInfo_SeafoamIslandsB3F_Fish
	.byte MAP_GROUP(SEAFOAM_ISLANDS_B4F), MAP_NUM(SEAFOAM_ISLANDS_B4F)
	.align 2
	.4byte sWildMonInfo_SeafoamIslandsB4F_Land
	.4byte sWildMonInfo_SeafoamIslandsB4F_Water
	.4byte NULL
	.4byte sWildMonInfo_SeafoamIslandsB4F_Fish
	.byte MAP_GROUP(POKEMON_TOWER_3F), MAP_NUM(POKEMON_TOWER_3F)
	.align 2
	.4byte sWildMonInfo_PokemonTower3F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(POKEMON_TOWER_4F), MAP_NUM(POKEMON_TOWER_4F)
	.align 2
	.4byte sWildMonInfo_PokemonTower4F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(POKEMON_TOWER_5F), MAP_NUM(POKEMON_TOWER_5F)
	.align 2
	.4byte sWildMonInfo_PokemonTower5F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(POKEMON_TOWER_6F), MAP_NUM(POKEMON_TOWER_6F)
	.align 2
	.4byte sWildMonInfo_PokemonTower6F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(POKEMON_TOWER_7F), MAP_NUM(POKEMON_TOWER_7F)
	.align 2
	.4byte sWildMonInfo_PokemonTower7F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(POWER_PLANT), MAP_NUM(POWER_PLANT)
	.align 2
	.4byte sWildMonInfo_PowerPlant_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(MT_EMBER_EXTERIOR), MAP_NUM(MT_EMBER_EXTERIOR)
	.align 2
	.4byte sWildMonInfo_MtEmberExterior_Land
	.4byte NULL
	.4byte sWildMonInfo_MtEmberExterior_Rock
	.4byte NULL
	.byte MAP_GROUP(MT_EMBER_SUMMIT_PATH_1F), MAP_NUM(MT_EMBER_SUMMIT_PATH_1F)
	.align 2
	.4byte sWildMonInfo_MtEmberSummitPath1F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(MT_EMBER_SUMMIT_PATH_2F), MAP_NUM(MT_EMBER_SUMMIT_PATH_2F)
	.align 2
	.4byte sWildMonInfo_MtEmberSummitPath2F_Land
	.4byte NULL
	.4byte sWildMonInfo_MtEmberSummitPath2F_Rock
	.4byte NULL
	.byte MAP_GROUP(MT_EMBER_SUMMIT_PATH_3F), MAP_NUM(MT_EMBER_SUMMIT_PATH_3F)
	.align 2
	.4byte sWildMonInfo_MtEmberSummitPath3F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(MT_EMBER_RUBY_PATH_1F), MAP_NUM(MT_EMBER_RUBY_PATH_1F)
	.align 2
	.4byte sWildMonInfo_MtEmberRubyPath1F_Land
	.4byte NULL
	.4byte sWildMonInfo_MtEmberRubyPath1F_Rock
	.4byte NULL
	.byte MAP_GROUP(MT_EMBER_RUBY_PATH_B1F), MAP_NUM(MT_EMBER_RUBY_PATH_B1F)
	.align 2
	.4byte sWildMonInfo_MtEmberRubyPathB1F_Land
	.4byte NULL
	.4byte sWildMonInfo_MtEmberRubyPathB1F_Rock
	.4byte NULL
	.byte MAP_GROUP(MT_EMBER_RUBY_PATH_B2F), MAP_NUM(MT_EMBER_RUBY_PATH_B2F)
	.align 2
	.4byte sWildMonInfo_MtEmberRubyPathB2F_Land
	.4byte NULL
	.4byte sWildMonInfo_MtEmberRubyPathB2F_Rock
	.4byte NULL
	.byte MAP_GROUP(MT_EMBER_RUBY_PATH_B3F), MAP_NUM(MT_EMBER_RUBY_PATH_B3F)
	.align 2
	.4byte sWildMonInfo_MtEmberRubyPathB3F_Land
	.4byte NULL
	.4byte sWildMonInfo_MtEmberRubyPathB3F_Rock
	.4byte NULL
	.byte MAP_GROUP(MT_EMBER_RUBY_PATH_B1F_STAIRS), MAP_NUM(MT_EMBER_RUBY_PATH_B1F_STAIRS)
	.align 2
	.4byte sWildMonInfo_MtEmberRubyPathB1FStairs_Land
	.4byte NULL
	.4byte sWildMonInfo_MtEmberRubyPathB1FStairs_Rock
	.4byte NULL
	.byte MAP_GROUP(MT_EMBER_RUBY_PATH_B2F_STAIRS), MAP_NUM(MT_EMBER_RUBY_PATH_B2F_STAIRS)
	.align 2
	.4byte sWildMonInfo_MtEmberRubyPathB2FStairs_Land
	.4byte NULL
	.4byte sWildMonInfo_MtEmberRubyPathB2FStairs_Rock
	.4byte NULL
	.byte MAP_GROUP(THREE_ISLAND_BERRY_FOREST), MAP_NUM(THREE_ISLAND_BERRY_FOREST)
	.align 2
	.4byte sWildMonInfo_ThreeIslandBerryForest_Land
	.4byte sWildMonInfo_ThreeIslandBerryForest_Water
	.4byte NULL
	.4byte sWildMonInfo_ThreeIslandBerryForest_Fish
	.byte MAP_GROUP(FOUR_ISLAND_ICEFALL_CAVE_ENTRANCE), MAP_NUM(FOUR_ISLAND_ICEFALL_CAVE_ENTRANCE)
	.align 2
	.4byte sWildMonInfo_FourIslandIcefallCaveEntrance_Land
	.4byte sWildMonInfo_FourIslandIcefallCaveEntrance_Water
	.4byte NULL
	.4byte sWildMonInfo_FourIslandIcefallCaveEntrance_Fish
	.byte MAP_GROUP(FOUR_ISLAND_ICEFALL_CAVE_1F), MAP_NUM(FOUR_ISLAND_ICEFALL_CAVE_1F)
	.align 2
	.4byte sWildMonInfo_FourIslandIcefallCave1F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(FOUR_ISLAND_ICEFALL_CAVE_B1F), MAP_NUM(FOUR_ISLAND_ICEFALL_CAVE_B1F)
	.align 2
	.4byte sWildMonInfo_FourIslandIcefallCaveB1F_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(FOUR_ISLAND_ICEFALL_CAVE_BACK), MAP_NUM(FOUR_ISLAND_ICEFALL_CAVE_BACK)
	.align 2
	.4byte sWildMonInfo_FourIslandIcefallCaveBack_Land
	.4byte sWildMonInfo_FourIslandIcefallCaveBack_Water
	.4byte NULL
	.4byte sWildMonInfo_FourIslandIcefallCaveBack_Fish
	.byte MAP_GROUP(SIX_ISLAND_PATTERN_BUSH), MAP_NUM(SIX_ISLAND_PATTERN_BUSH)
	.align 2
	.4byte sWildMonInfo_SixIslandPatternBush_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(FIVE_ISLAND_LOST_CAVE_ROOM1), MAP_NUM(FIVE_ISLAND_LOST_CAVE_ROOM1)
	.align 2
	.4byte sWildMonInfo_FiveIslandLostCaveRoom1_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(FIVE_ISLAND_LOST_CAVE_ROOM2), MAP_NUM(FIVE_ISLAND_LOST_CAVE_ROOM2)
	.align 2
	.4byte sWildMonInfo_FiveIslandLostCaveRoom2_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(FIVE_ISLAND_LOST_CAVE_ROOM3), MAP_NUM(FIVE_ISLAND_LOST_CAVE_ROOM3)
	.align 2
	.4byte sWildMonInfo_FiveIslandLostCaveRoom3_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(FIVE_ISLAND_LOST_CAVE_ROOM4), MAP_NUM(FIVE_ISLAND_LOST_CAVE_ROOM4)
	.align 2
	.4byte sWildMonInfo_FiveIslandLostCaveRoom4_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(FIVE_ISLAND_LOST_CAVE_ROOM5), MAP_NUM(FIVE_ISLAND_LOST_CAVE_ROOM5)
	.align 2
	.4byte sWildMonInfo_FiveIslandLostCaveRoom5_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(FIVE_ISLAND_LOST_CAVE_ROOM6), MAP_NUM(FIVE_ISLAND_LOST_CAVE_ROOM6)
	.align 2
	.4byte sWildMonInfo_FiveIslandLostCaveRoom6_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(FIVE_ISLAND_LOST_CAVE_ROOM7), MAP_NUM(FIVE_ISLAND_LOST_CAVE_ROOM7)
	.align 2
	.4byte sWildMonInfo_FiveIslandLostCaveRoom7_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(FIVE_ISLAND_LOST_CAVE_ROOM8), MAP_NUM(FIVE_ISLAND_LOST_CAVE_ROOM8)
	.align 2
	.4byte sWildMonInfo_FiveIslandLostCaveRoom8_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(FIVE_ISLAND_LOST_CAVE_ROOM9), MAP_NUM(FIVE_ISLAND_LOST_CAVE_ROOM9)
	.align 2
	.4byte sWildMonInfo_FiveIslandLostCaveRoom9_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(FIVE_ISLAND_LOST_CAVE_ROOM10), MAP_NUM(FIVE_ISLAND_LOST_CAVE_ROOM10)
	.align 2
	.4byte sWildMonInfo_FiveIslandLostCaveRoom10_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(FIVE_ISLAND_LOST_CAVE_ROOM11), MAP_NUM(FIVE_ISLAND_LOST_CAVE_ROOM11)
	.align 2
	.4byte sWildMonInfo_FiveIslandLostCaveRoom11_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(FIVE_ISLAND_LOST_CAVE_ROOM12), MAP_NUM(FIVE_ISLAND_LOST_CAVE_ROOM12)
	.align 2
	.4byte sWildMonInfo_FiveIslandLostCaveRoom12_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(FIVE_ISLAND_LOST_CAVE_ROOM13), MAP_NUM(FIVE_ISLAND_LOST_CAVE_ROOM13)
	.align 2
	.4byte sWildMonInfo_FiveIslandLostCaveRoom13_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(FIVE_ISLAND_LOST_CAVE_ROOM14), MAP_NUM(FIVE_ISLAND_LOST_CAVE_ROOM14)
	.align 2
	.4byte sWildMonInfo_FiveIslandLostCaveRoom14_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(ONE_ISLAND_KINDLE_ROAD), MAP_NUM(ONE_ISLAND_KINDLE_ROAD)
	.align 2
	.4byte sWildMonInfo_OneIslandKindleRoad_Land
	.4byte sWildMonInfo_OneIslandKindleRoad_Water
	.4byte sWildMonInfo_OneIslandKindleRoad_Rock
	.4byte sWildMonInfo_OneIslandKindleRoad_Fish
	.byte MAP_GROUP(ONE_ISLAND_TREASURE_BEACH), MAP_NUM(ONE_ISLAND_TREASURE_BEACH)
	.align 2
	.4byte sWildMonInfo_OneIslandTreasureBeach_Land
	.4byte sWildMonInfo_OneIslandTreasureBeach_Water
	.4byte NULL
	.4byte sWildMonInfo_OneIslandTreasureBeach_Fish
	.byte MAP_GROUP(TWO_ISLAND_CAPE_BRINK), MAP_NUM(TWO_ISLAND_CAPE_BRINK)
	.align 2
	.4byte sWildMonInfo_TwoIslandCapeBrink_Land
	.4byte sWildMonInfo_TwoIslandCapeBrink_Water
	.4byte NULL
	.4byte sWildMonInfo_TwoIslandCapeBrink_Fish
	.byte MAP_GROUP(THREE_ISLAND_BOND_BRIDGE), MAP_NUM(THREE_ISLAND_BOND_BRIDGE)
	.align 2
	.4byte sWildMonInfo_ThreeIslandBondBridge_Land
	.4byte sWildMonInfo_ThreeIslandBondBridge_Water
	.4byte NULL
	.4byte sWildMonInfo_ThreeIslandBondBridge_Fish
	.byte MAP_GROUP(THREE_ISLAND_PORT), MAP_NUM(THREE_ISLAND_PORT)
	.align 2
	.4byte sWildMonInfo_ThreeIslandPort_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(FIVE_ISLAND_RESORT_GORGEOUS), MAP_NUM(FIVE_ISLAND_RESORT_GORGEOUS)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_FiveIslandResortGorgeous_Water
	.4byte NULL
	.4byte sWildMonInfo_FiveIslandResortGorgeous_Fish
	.byte MAP_GROUP(FIVE_ISLAND_WATER_LABYRINTH), MAP_NUM(FIVE_ISLAND_WATER_LABYRINTH)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_FiveIslandWaterLabyrinth_Water
	.4byte NULL
	.4byte sWildMonInfo_FiveIslandWaterLabyrinth_Fish
	.byte MAP_GROUP(FIVE_ISLAND_MEADOW), MAP_NUM(FIVE_ISLAND_MEADOW)
	.align 2
	.4byte sWildMonInfo_FiveIslandMeadow_Land
	.4byte sWildMonInfo_FiveIslandMeadow_Water
	.4byte NULL
	.4byte sWildMonInfo_FiveIslandMeadow_Fish
	.byte MAP_GROUP(FIVE_ISLAND_MEMORIAL_PILLAR), MAP_NUM(FIVE_ISLAND_MEMORIAL_PILLAR)
	.align 2
	.4byte sWildMonInfo_FiveIslandMemorialPillar_Land
	.4byte sWildMonInfo_FiveIslandMemorialPillar_Water
	.4byte NULL
	.4byte sWildMonInfo_FiveIslandMemorialPillar_Fish
	.byte MAP_GROUP(SIX_ISLAND_OUTCAST_ISLAND), MAP_NUM(SIX_ISLAND_OUTCAST_ISLAND)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_SixIslandOutcastIsland_Water
	.4byte NULL
	.4byte sWildMonInfo_SixIslandOutcastIsland_Fish
	.byte MAP_GROUP(SIX_ISLAND_GREEN_PATH), MAP_NUM(SIX_ISLAND_GREEN_PATH)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_SixIslandGreenPath_Water
	.4byte NULL
	.4byte sWildMonInfo_SixIslandGreenPath_Fish
	.byte MAP_GROUP(SIX_ISLAND_WATER_PATH), MAP_NUM(SIX_ISLAND_WATER_PATH)
	.align 2
	.4byte sWildMonInfo_SixIslandWaterPath_Land
	.4byte sWildMonInfo_SixIslandWaterPath_Water
	.4byte NULL
	.4byte sWildMonInfo_SixIslandWaterPath_Fish
	.byte MAP_GROUP(SIX_ISLAND_RUIN_VALLEY), MAP_NUM(SIX_ISLAND_RUIN_VALLEY)
	.align 2
	.4byte sWildMonInfo_SixIslandRuinValley_Land
	.4byte sWildMonInfo_SixIslandRuinValley_Water
	.4byte NULL
	.4byte sWildMonInfo_SixIslandRuinValley_Fish
	.byte MAP_GROUP(SEVEN_ISLAND_TRAINER_TOWER), MAP_NUM(SEVEN_ISLAND_TRAINER_TOWER)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_SevenIslandTrainerTower_Water
	.4byte NULL
	.4byte sWildMonInfo_SevenIslandTrainerTower_Fish
	.byte MAP_GROUP(SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE), MAP_NUM(SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE)
	.align 2
	.4byte sWildMonInfo_SevenIslandSevaultCanyonEntrance_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SEVEN_ISLAND_SEVAULT_CANYON), MAP_NUM(SEVEN_ISLAND_SEVAULT_CANYON)
	.align 2
	.4byte sWildMonInfo_SevenIslandSevaultCanyon_Land
	.4byte NULL
	.4byte sWildMonInfo_SevenIslandSevaultCanyon_Rock
	.4byte NULL
	.byte MAP_GROUP(SEVEN_ISLAND_TANOBY_RUINS), MAP_NUM(SEVEN_ISLAND_TANOBY_RUINS)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_SevenIslandTanobyRuins_Water
	.4byte NULL
	.4byte sWildMonInfo_SevenIslandTanobyRuins_Fish
	.byte MAP_GROUP(ROUTE1), MAP_NUM(ROUTE1)
	.align 2
	.4byte sWildMonInfo_Route1_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(ROUTE2), MAP_NUM(ROUTE2)
	.align 2
	.4byte sWildMonInfo_Route2_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(ROUTE3), MAP_NUM(ROUTE3)
	.align 2
	.4byte sWildMonInfo_Route3_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(ROUTE4), MAP_NUM(ROUTE4)
	.align 2
	.4byte sWildMonInfo_Route4_Land
	.4byte sWildMonInfo_Route4_Water
	.4byte NULL
	.4byte sWildMonInfo_Route4_Fish
	.byte MAP_GROUP(ROUTE5), MAP_NUM(ROUTE5)
	.align 2
	.4byte sWildMonInfo_Route5_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(ROUTE6), MAP_NUM(ROUTE6)
	.align 2
	.4byte sWildMonInfo_Route6_Land
	.4byte sWildMonInfo_Route6_Water
	.4byte NULL
	.4byte sWildMonInfo_Route6_Fish
	.byte MAP_GROUP(ROUTE7), MAP_NUM(ROUTE7)
	.align 2
	.4byte sWildMonInfo_Route7_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(ROUTE8), MAP_NUM(ROUTE8)
	.align 2
	.4byte sWildMonInfo_Route8_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(ROUTE9), MAP_NUM(ROUTE9)
	.align 2
	.4byte sWildMonInfo_Route9_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(ROUTE10), MAP_NUM(ROUTE10)
	.align 2
	.4byte sWildMonInfo_Route10_Land
	.4byte sWildMonInfo_Route10_Water
	.4byte NULL
	.4byte sWildMonInfo_Route10_Fish
	.byte MAP_GROUP(ROUTE11), MAP_NUM(ROUTE11)
	.align 2
	.4byte sWildMonInfo_Route11_Land
	.4byte sWildMonInfo_Route11_Water
	.4byte NULL
	.4byte sWildMonInfo_Route11_Fish
	.byte MAP_GROUP(ROUTE12), MAP_NUM(ROUTE12)
	.align 2
	.4byte sWildMonInfo_Route12_Land
	.4byte sWildMonInfo_Route12_Water
	.4byte NULL
	.4byte sWildMonInfo_Route12_Fish
	.byte MAP_GROUP(ROUTE13), MAP_NUM(ROUTE13)
	.align 2
	.4byte sWildMonInfo_Route13_Land
	.4byte sWildMonInfo_Route13_Water
	.4byte NULL
	.4byte sWildMonInfo_Route13_Fish
	.byte MAP_GROUP(ROUTE14), MAP_NUM(ROUTE14)
	.align 2
	.4byte sWildMonInfo_Route14_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(ROUTE15), MAP_NUM(ROUTE15)
	.align 2
	.4byte sWildMonInfo_Route15_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(ROUTE16), MAP_NUM(ROUTE16)
	.align 2
	.4byte sWildMonInfo_Route16_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(ROUTE17), MAP_NUM(ROUTE17)
	.align 2
	.4byte sWildMonInfo_Route17_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(ROUTE18), MAP_NUM(ROUTE18)
	.align 2
	.4byte sWildMonInfo_Route18_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(ROUTE19), MAP_NUM(ROUTE19)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_Route19_Water
	.4byte NULL
	.4byte sWildMonInfo_Route19_Fish
	.byte MAP_GROUP(ROUTE20), MAP_NUM(ROUTE20)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_Route20_Water
	.4byte NULL
	.4byte sWildMonInfo_Route20_Fish
	.byte MAP_GROUP(ROUTE21_NORTH), MAP_NUM(ROUTE21_NORTH)
	.align 2
	.4byte sWildMonInfo_Route21North_Land
	.4byte sWildMonInfo_Route21North_Water
	.4byte NULL
	.4byte sWildMonInfo_Route21North_Fish
	.byte MAP_GROUP(ROUTE21_SOUTH), MAP_NUM(ROUTE21_SOUTH)
	.align 2
	.4byte sWildMonInfo_Route21South_Land
	.4byte sWildMonInfo_Route21South_Water
	.4byte NULL
	.4byte sWildMonInfo_Route21South_Fish
	.byte MAP_GROUP(ROUTE22), MAP_NUM(ROUTE22)
	.align 2
	.4byte sWildMonInfo_Route22_Land
	.4byte sWildMonInfo_Route22_Water
	.4byte NULL
	.4byte sWildMonInfo_Route22_Fish
	.byte MAP_GROUP(ROUTE23), MAP_NUM(ROUTE23)
	.align 2
	.4byte sWildMonInfo_Route23_Land
	.4byte sWildMonInfo_Route23_Water
	.4byte NULL
	.4byte sWildMonInfo_Route23_Fish
	.byte MAP_GROUP(ROUTE24), MAP_NUM(ROUTE24)
	.align 2
	.4byte sWildMonInfo_Route24_Land
	.4byte sWildMonInfo_Route24_Water
	.4byte NULL
	.4byte sWildMonInfo_Route24_Fish
	.byte MAP_GROUP(ROUTE25), MAP_NUM(ROUTE25)
	.align 2
	.4byte sWildMonInfo_Route25_Land
	.4byte sWildMonInfo_Route25_Water
	.4byte NULL
	.4byte sWildMonInfo_Route25_Fish
	.byte MAP_GROUP(PALLET_TOWN), MAP_NUM(PALLET_TOWN)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_PalletTown_Water
	.4byte NULL
	.4byte sWildMonInfo_PalletTown_Fish
	.byte MAP_GROUP(VIRIDIAN_CITY), MAP_NUM(VIRIDIAN_CITY)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_ViridianCity_Water
	.4byte NULL
	.4byte sWildMonInfo_ViridianCity_Fish
	.byte MAP_GROUP(CERULEAN_CITY), MAP_NUM(CERULEAN_CITY)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_CeruleanCity_Water
	.4byte NULL
	.4byte sWildMonInfo_CeruleanCity_Fish
	.byte MAP_GROUP(VERMILION_CITY), MAP_NUM(VERMILION_CITY)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_VermilionCity_Water
	.4byte NULL
	.4byte sWildMonInfo_VermilionCity_Fish
	.byte MAP_GROUP(CELADON_CITY), MAP_NUM(CELADON_CITY)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_CeladonCity_Water
	.4byte NULL
	.4byte sWildMonInfo_CeladonCity_Fish
	.byte MAP_GROUP(FUCHSIA_CITY), MAP_NUM(FUCHSIA_CITY)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_FuchsiaCity_Water
	.4byte NULL
	.4byte sWildMonInfo_FuchsiaCity_Fish
	.byte MAP_GROUP(CINNABAR_ISLAND), MAP_NUM(CINNABAR_ISLAND)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_CinnabarIsland_Water
	.4byte NULL
	.4byte sWildMonInfo_CinnabarIsland_Fish
	.byte MAP_GROUP(ONE_ISLAND), MAP_NUM(ONE_ISLAND)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_OneIsland_Water
	.4byte NULL
	.4byte sWildMonInfo_OneIsland_Fish
	.byte MAP_GROUP(FOUR_ISLAND), MAP_NUM(FOUR_ISLAND)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_FourIsland_Water
	.4byte NULL
	.4byte sWildMonInfo_FourIsland_Fish
	.byte MAP_GROUP(FIVE_ISLAND), MAP_NUM(FIVE_ISLAND)
	.align 2
	.4byte NULL
	.4byte sWildMonInfo_FiveIsland_Water
	.4byte NULL
	.4byte sWildMonInfo_FiveIsland_Fish
	.byte MAP_GROUP(SIX_ISLAND_ALTERING_CAVE), MAP_NUM(SIX_ISLAND_ALTERING_CAVE)
	.align 2
	.4byte sWildMonInfo_SixIslandAlteringCave_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SIX_ISLAND_ALTERING_CAVE), MAP_NUM(SIX_ISLAND_ALTERING_CAVE)
	.align 2
	.4byte sWildMonInfo_SixIslandAlteringCave_2_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SIX_ISLAND_ALTERING_CAVE), MAP_NUM(SIX_ISLAND_ALTERING_CAVE)
	.align 2
	.4byte sWildMonInfo_SixIslandAlteringCave_3_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SIX_ISLAND_ALTERING_CAVE), MAP_NUM(SIX_ISLAND_ALTERING_CAVE)
	.align 2
	.4byte sWildMonInfo_SixIslandAlteringCave_4_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SIX_ISLAND_ALTERING_CAVE), MAP_NUM(SIX_ISLAND_ALTERING_CAVE)
	.align 2
	.4byte sWildMonInfo_SixIslandAlteringCave_5_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SIX_ISLAND_ALTERING_CAVE), MAP_NUM(SIX_ISLAND_ALTERING_CAVE)
	.align 2
	.4byte sWildMonInfo_SixIslandAlteringCave_6_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SIX_ISLAND_ALTERING_CAVE), MAP_NUM(SIX_ISLAND_ALTERING_CAVE)
	.align 2
	.4byte sWildMonInfo_SixIslandAlteringCave_7_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SIX_ISLAND_ALTERING_CAVE), MAP_NUM(SIX_ISLAND_ALTERING_CAVE)
	.align 2
	.4byte sWildMonInfo_SixIslandAlteringCave_8_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(SIX_ISLAND_ALTERING_CAVE), MAP_NUM(SIX_ISLAND_ALTERING_CAVE)
	.align 2
	.4byte sWildMonInfo_SixIslandAlteringCave_9_Land
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.byte MAP_GROUP(UNDEFINED), MAP_NUM(UNDEFINED)
	.align 2
	.4byte NULL
	.4byte NULL
	.4byte NULL
	.4byte NULL
