Route11_Text_HugoIntro:: @ 8184F01
    .string "Win, lose, or draw!$"

Route11_Text_HugoDefeat:: @ 8184F15
    .string "Atcha!\n"
    .string "Didn't go my way!$"

Route11_Text_HugoPostBattle:: @ 8184F2E
    .string "POKéMON is life!\n"
    .string "And to live is to play games!$"

Route11_Text_JasperIntro:: @ 8184F5D
    .string "Competition!\n"
    .string "I can't get enough!$"

Route11_Text_JasperDefeat:: @ 8184F7E
    .string "I had a chance!$"

Route11_Text_JasperPostBattle:: @ 8184F8E
    .string "You can't be a coward in the world\n"
    .string "of POKéMON!$"

Route11_Text_EddieIntro:: @ 8184FBD
    .string "Let's go, but don't cheat!$"

Route11_Text_EddieDefeat:: @ 8184FD8
    .string "Huh?\n"
    .string "That's not right!$"

Route11_Text_EddiePostBattle:: @ 8184FEF
    .string "I did my best.\n"
    .string "I have no regrets.$"

Route11_Text_BraxtonIntro:: @ 8185011
    .string "Careful!\n"
    .string "I'm laying down some cables!$"

Route11_Text_BraxtonDefeat:: @ 8185037
    .string "That was electric!$"

Route11_Text_BraxtonPostBattle:: @ 818504A
    .string "Spread the word to save energy!$"

Route11_Text_DillonIntro:: @ 818506A
    .string "I just became a TRAINER.\n"
    .string "But, I think I can win.$"

Route11_Text_DillonDefeat:: @ 818509B
    .string "My POKéMON couldn't win…\n"
    .string "Haven't they grown enough?$"

Route11_Text_DillonPostBattle:: @ 81850CF
    .string "What now?\n"
    .string "Leave me alone!$"

Route11_Text_DirkIntro:: @ 81850E9
    .string "Fwahaha!\n"
    .string "I have never lost!$"

Route11_Text_DirkDefeat:: @ 8185105
    .string "My first loss!$"

Route11_Text_DirkPostBattle:: @ 8185114
    .string "You were just lucky, that's all.$"

Route11_Text_DarianIntro:: @ 8185135
    .string "I have never won before…$"

Route11_Text_DarianDefeat:: @ 818514E
    .string "I saw this coming…$"

Route11_Text_DarianPostBattle:: @ 8185161
    .string "I was unlucky, as always.$"

Route11_Text_YasuIntro:: @ 818517B
    .string "I'm the best in my class.\n"
    .string "I train every morning.$"

Route11_Text_YasuDefeat:: @ 81851AC
    .string "Darn!\n"
    .string "My POKéMON need to be stronger!$"

Route11_Text_YasuPostBattle:: @ 81851D2
    .string "There's a fat POKéMON that comes\n"
    .string "down from the mountains.\p"
    .string "I bet it'd be strong if you can\n"
    .string "catch it.$"

Route11_Text_BernieIntro:: @ 8185236
    .string "Watch out for live wires!$"

Route11_Text_BernieDefeat:: @ 8185250
    .string "Whoa!\n"
    .string "You spark plug!$"

Route11_Text_BerniePostBattle:: @ 8185266
    .string "Well, better get back to work.$"

Route11_Text_DaveIntro:: @ 8185285
    .string "I raised my POKéMON carefully.\n"
    .string "They should be ready by now!$"

Route11_Text_DaveDefeat:: @ 81852C1
    .string "Bye-bye!\n"
    .string "Thank you, and good-bye!$"

Route11_Text_DavePostBattle:: @ 81852E3
    .string "Tch…\n"
    .string "I better go find stronger ones!$"

Route11_Text_DiglettsCave:: @ 8185308
    .string "DIGLETT'S CAVE$"

