Text_184F01:: @ 8184F01
    .string "Win, lose, or draw!$"

Text_184F15:: @ 8184F15
    .string "Atcha!\n"
    .string "Didn't go my way!$"

Text_184F2E:: @ 8184F2E
    .string "POKéMON is life!\n"
    .string "And to live is to play games!$"

Text_184F5D:: @ 8184F5D
    .string "Competition!\n"
    .string "I can't get enough!$"

Text_184F7E:: @ 8184F7E
    .string "I had a chance!$"

Text_184F8E:: @ 8184F8E
    .string "You can't be a coward in the world\n"
    .string "of POKéMON!$"

Text_184FBD:: @ 8184FBD
    .string "Let's go, but don't cheat!$"

Text_184FD8:: @ 8184FD8
    .string "Huh?\n"
    .string "That's not right!$"

Text_184FEF:: @ 8184FEF
    .string "I did my best.\n"
    .string "I have no regrets.$"

Text_185011:: @ 8185011
    .string "Careful!\n"
    .string "I'm laying down some cables!$"

Text_185037:: @ 8185037
    .string "That was electric!$"

Text_18504A:: @ 818504A
    .string "Spread the word to save energy!$"

Text_18506A:: @ 818506A
    .string "I just became a TRAINER.\n"
    .string "But, I think I can win.$"

Text_18509B:: @ 818509B
    .string "My POKéMON couldn't win…\n"
    .string "Haven't they grown enough?$"

Text_1850CF:: @ 81850CF
    .string "What now?\n"
    .string "Leave me alone!$"

Text_1850E9:: @ 81850E9
    .string "Fwahaha!\n"
    .string "I have never lost!$"

Text_185105:: @ 8185105
    .string "My first loss!$"

Text_185114:: @ 8185114
    .string "You were just lucky, that's all.$"

Text_185135:: @ 8185135
    .string "I have never won before…$"

Text_18514E:: @ 818514E
    .string "I saw this coming…$"

Text_185161:: @ 8185161
    .string "I was unlucky, as always.$"

Text_18517B:: @ 818517B
    .string "I'm the best in my class.\n"
    .string "I train every morning.$"

Text_1851AC:: @ 81851AC
    .string "Darn!\n"
    .string "My POKéMON need to be stronger!$"

Text_1851D2:: @ 81851D2
    .string "There's a fat POKéMON that comes\n"
    .string "down from the mountains.\p"
    .string "I bet it'd be strong if you can\n"
    .string "catch it.$"

Text_185236:: @ 8185236
    .string "Watch out for live wires!$"

Text_185250:: @ 8185250
    .string "Whoa!\n"
    .string "You spark plug!$"

Text_185266:: @ 8185266
    .string "Well, better get back to work.$"

Text_185285:: @ 8185285
    .string "I raised my POKéMON carefully.\n"
    .string "They should be ready by now!$"

Text_1852C1:: @ 81852C1
    .string "Bye-bye!\n"
    .string "Thank you, and good-bye!$"

Text_1852E3:: @ 81852E3
    .string "Tch…\n"
    .string "I better go find stronger ones!$"

gUnknown_8185308:: @ 8185308
    .string "DIGLETT'S CAVE$"

