# 1 "data/maps/CeladonCity_House1/scripts.pory"

# 2 "data/maps/CeladonCity_House1/scripts.pory"
CeladonCity_House1_MapScripts::
# 3 "data/maps/CeladonCity_House1/scripts.pory"
	.byte 0
# 4 "data/maps/CeladonCity_House1/scripts.pory"

# 5 "data/maps/CeladonCity_House1/scripts.pory"
CeladonCity_House1_EventScript_RocketChief::
# 6 "data/maps/CeladonCity_House1/scripts.pory"
	msgbox CeladonCity_House1_Text_SlotsReelInTheDough, MSGBOX_NPC
# 7 "data/maps/CeladonCity_House1/scripts.pory"
	end
# 8 "data/maps/CeladonCity_House1/scripts.pory"

# 9 "data/maps/CeladonCity_House1/scripts.pory"
CeladonCity_House1_EventScript_Rocket1::
# 10 "data/maps/CeladonCity_House1/scripts.pory"
	msgbox CeladonCity_House1_Text_ShippedMonsAsSlotPrizes, MSGBOX_NPC
# 11 "data/maps/CeladonCity_House1/scripts.pory"
	end
# 12 "data/maps/CeladonCity_House1/scripts.pory"

# 13 "data/maps/CeladonCity_House1/scripts.pory"
CeladonCity_House1_EventScript_Rocket2::
# 14 "data/maps/CeladonCity_House1/scripts.pory"
	msgbox CeladonCity_House1_Text_DontTouchGameCornerPoster, MSGBOX_NPC
# 15 "data/maps/CeladonCity_House1/scripts.pory"
	end
