SixIsland_OutcastIsland_EventObjects:
	object_event 1, 49, 0, 9, 0, 24, 0, 3, 1, 17, 0, 1, 0, 1, 0, SixIsland_OutcastIsland_EventScript_168B16, 136, 0, 0
	object_event 2, 57, 0, 12, 0, 15, 0, 3, 7, 17, 0, 1, 0, 1, 0, SixIsland_OutcastIsland_EventScript_1AC3D1, 0, 0, 0
	object_event 3, 43, 0, 13, 0, 34, 0, 1, 1, 17, 0, 1, 0, 1, 0, SixIsland_OutcastIsland_EventScript_1AC40F, 0, 0, 0
	object_event 4, 44, 0, 14, 0, 61, 0, 1, 50, 66, 0, 1, 0, 1, 0, SixIsland_OutcastIsland_EventScript_1AC44D, 0, 0, 0
	object_event 5, 44, 0, 10, 0, 44, 0, 1, 7, 17, 0, 1, 0, 1, 0, SixIsland_OutcastIsland_EventScript_1AC48B, 0, 0, 0
	object_event 6, 36, 0, 11, 0, 44, 0, 1, 7, 17, 0, 1, 0, 1, 0, SixIsland_OutcastIsland_EventScript_1AC4D1, 0, 0, 0
	object_event 7, 92, 0, 11, 0, 16, 0, 3, 8, 17, 0, 0, 0, 0, 0, SixIsland_OutcastIsland_EventScript_1BEC90, 481, 0, 0

SixIsland_OutcastIsland_MapWarps:
	warp_def 7, 21, 3, 0, 378

SixIsland_OutcastIsland_MapBGEvents:
	bg_event 16, 23, 3, 7, 0, 109, 178, 1
	bg_event 6, 24, 3, 7, 0, 6, 179, 1

SixIsland_OutcastIsland_MapEvents::
	map_events SixIsland_OutcastIsland_EventObjects, SixIsland_OutcastIsland_MapWarps, 0x0, SixIsland_OutcastIsland_MapBGEvents
