SixIsland_OutcastIsland_Text_RocketIntro:: @ 818B35A
    .string "There're no rare Pokémon around\n"
    .string "these parts! Not a one!\p"
    .string "That burns me up, man.\n"
    .string "I'll take it out on you!$"

SixIsland_OutcastIsland_Text_RocketDefeat:: @ 818B3C2
    .string "…Huh?$"

SixIsland_OutcastIsland_Text_RocketPostBattle:: @ 818B3C8
    .string "So listen, you haven't seen any\n"
    .string "rare Pokémon, have you?$"

SixIsland_OutcastIsland_Text_TylorIntro:: @ 818B400
    .string "I'm having no luck at all.\n"
    .string "A battle'd be a change of pace!$"

SixIsland_OutcastIsland_Text_TylorDefeat:: @ 818B43B
    .string "Nope, no luck at all…$"

SixIsland_OutcastIsland_Text_TylorPostBattle:: @ 818B451
    .string "I can't very well go home without\n"
    .string "catching something, though.$"

SixIsland_OutcastIsland_Text_MymoIntro:: @ 818B48F
    .string "Gasp… Gasp…\p"
    .string "I swam here from Six Isle Port\n"
    .string "in one go.$"

SixIsland_OutcastIsland_Text_MymoDefeat:: @ 818B4C5
    .string "Gasp…\n"
    .string "Gasp…$"

SixIsland_OutcastIsland_Text_MymoPostBattle:: @ 818B4D1
    .string "I'm only at the halfway point…\n"
    .string "I'm beat…$"

SixIsland_OutcastIsland_Text_NicoleIntro:: @ 818B4FA
    .string "It's not so easy sending Pokémon\n"
    .string "out while swimming, you know?$"

SixIsland_OutcastIsland_Text_NicoleDefeat:: @ 818B539
    .string "I didn't lose to you at swimming.\n"
    .string "This doesn't bother me.$"

SixIsland_OutcastIsland_Text_NicolePostBattle:: @ 818B573
    .string "Are you headed for the island up\n"
    .string "past here?\p"
    .string "I didn't see anything interesting\n"
    .string "there.$"

SixIsland_OutcastIsland_Text_AvaIntro:: @ 818B5C8
    .string "Ava: Let's have a two-on-two\n"
    .string "marine battle!$"

SixIsland_OutcastIsland_Text_AvaDefeat:: @ 818B5F4
    .string "Ava: Oh, you're amazing!\n"
    .string "Even better, you're on your own!$"

SixIsland_OutcastIsland_Text_AvaPostBattle:: @ 818B62E
    .string "Ava: You know, I do prefer the\n"
    .string "sea over any pool.$"

SixIsland_OutcastIsland_Text_AvaNotEnoughMons:: @ 818B660
    .string "Ava: You're challenging us to\n"
    .string "a battle?\p"
    .string "You'll need at least two Pokémon\n"
    .string "if you want to do that.$"

SixIsland_OutcastIsland_Text_GebIntro:: @ 818B6C1
    .string "Geb: Big Sister, help!\n"
    .string "Please battle with me!$"

SixIsland_OutcastIsland_Text_GebDefeat:: @ 818B6EF
    .string "Geb: Wow, Big Sister, this person's\n"
    .string "really good!$"

SixIsland_OutcastIsland_Text_GebPostBattle:: @ 818B720
    .string "Geb: I'm hanging onto my sister\n"
    .string "because I can't touch the bottom.$"

SixIsland_OutcastIsland_Text_GebNotEnoughMons:: @ 818B762
    .string "Geb: Please battle against me and\n"
    .string "my sister!\p"
    .string "…Oh, you don't have two Pokémon?$"
