Route14_Text_CarterIntro:: @ 8185E4D
    .string "You need to use TMs to teach good\n"
    .string "moves to POKéMON.$"

Route14_Text_CarterDefeat:: @ 8185E81
    .string "Not good enough quite yet.$"

Route14_Text_CarterPostBattle:: @ 8185E9C
    .string "You have some HMs, right? POKéMON\n"
    .string "can't forget those moves easily.$"

Route14_Text_MitchIntro:: @ 8185EDF
    .string "My bird POKéMON should be ready\n"
    .string "for battle.$"

Route14_Text_MitchDefeat:: @ 8185F0B
    .string "Not ready yet!$"

Route14_Text_MitchPostBattle:: @ 8185F1A
    .string "My bird POKéMON need to learn\n"
    .string "better moves.$"

Route14_Text_BeckIntro:: @ 8185F46
    .string "They have TMs on sale at the\n"
    .string "CELADON DEPT. STORE.\p"
    .string "TMs aren't really rare, but not\n"
    .string "many people have HMs.$"

Route14_Text_BeckDefeat:: @ 8185FAE
    .string "Aww, bummer!$"

Route14_Text_BeckPostBattle:: @ 8185FBB
    .string "Try teaching POKéMON a move that's\n"
    .string "the same type as it.\p"
    .string "That apparently boosts the power\n"
    .string "of the move.$"

Route14_Text_MarlonIntro:: @ 8186021
    .string "Have you taught your bird POKéMON\n"
    .string "how to FLY?\p"
    .string "You'll be able to soar with it into\n"
    .string "the sky!$"

Route14_Text_MarlonDefeat:: @ 818607C
    .string "Shot down in flames!$"

Route14_Text_MarlonPostBattle:: @ 8186091
    .string "Bird POKéMON are my one true love.\n"
    .string "I don't want to raise anything else.$"

Route14_Text_DonaldIntro:: @ 81860D9
    .string "Have you heard the legend of the\n"
    .string "winged mirages?$"

Route14_Text_DonaldDefeat:: @ 818610A
    .string "Why?\n"
    .string "Why'd I lose?$"

Route14_Text_DonaldPostBattle:: @ 818611D
    .string "Well, the winged mirages are the\n"
    .string "legendary bird POKéMON.\p"
    .string "There are three of them: ARTICUNO,\n"
    .string "ZAPDOS, and MOLTRES.$"

Route14_Text_BennyIntro:: @ 818618E
    .string "I'm not into it, but okay.\n"
    .string "Let's go!$"

Route14_Text_BennyDefeat:: @ 81861B3
    .string "I knew it!$"

Route14_Text_BennyPostBattle:: @ 81861BE
    .string "Winning, losing… It's insignificant\n"
    .string "under this huge sky.$"

Route14_Text_LukasIntro:: @ 81861F7
    .string "C'mon, c'mon.\n"
    .string "Let's go, let's go, let's go!$"

Route14_Text_LukasDefeat:: @ 8186223
    .string "Arrg!\n"
    .string "Lost! Get lost!$"

Route14_Text_LukasPostBattle:: @ 8186239
    .string "What, what, what?\n"
    .string "What do you want still?$"

Route14_Text_IsaacIntro:: @ 8186263
    .string "I need to burn some time.\n"
    .string "Shut up and battle.$"

Route14_Text_IsaacDefeat:: @ 8186291
    .string "What?\n"
    .string "You!?$"

Route14_Text_IsaacPostBattle:: @ 818629D
    .string "Raising POKéMON is a drag, man.$"

Route14_Text_GeraldIntro:: @ 81862BD
    .string "We ride out here because of the\n"
    .string "wide-open spaces.$"

Route14_Text_GeraldDefeat:: @ 81862EF
    .string "Wipeout!$"

Route14_Text_GeraldPostBattle:: @ 81862F8
    .string "It's cool you made your POKéMON so\n"
    .string "strong.\p"
    .string "Might is right!\n"
    .string "And you know it!$"

Route14_Text_MalikIntro:: @ 8186344
    .string "POKéMON battle?\n"
    .string "Cool! Rumble!$"

Route14_Text_MalikDefeat:: @ 8186362
    .string "Blown away!$"

Route14_Text_MalikPostBattle:: @ 818636E
    .string "You know who'd win, you and me\n"
    .string "one-on-one!$"

Route14_Text_RouteSign:: @ 8186399
    .string "ROUTE 14\n"
    .string "West to FUCHSIA CITY$"

Route14_Text_KiriIntro:: @ 81863B7
    .string "KIRI: JAN, let's try really,\n"
    .string "really hard together.$"

Route14_Text_KiriDefeat:: @ 81863EA
    .string "KIRI: Whimper…\n"
    .string "We lost, didn't we?$"

Route14_Text_KiriPostBattle:: @ 818640D
    .string "KIRI: Did we lose because of me?$"

Route14_Text_KiriNotEnoughMons:: @ 818642E
    .string "KIRI: We can battle if you have\n"
    .string "two POKéMON.$"

Route14_Text_JanIntro:: @ 818645B
    .string "JAN: KIRI, here we go!\n"
    .string "We have to try hard!$"

Route14_Text_JanDefeat:: @ 8186487
    .string "JAN: Eeeeh!\n"
    .string "No fair!$"

Route14_Text_JanPostBattle:: @ 818649C
    .string "JAN: KIRI, don't cry!\n"
    .string "We'll just try harder next time.$"

Route14_Text_JanNotEnoughMons:: @ 81864D3
    .string "JAN: You want to battle?\n"
    .string "You don't have enough POKéMON.$"
