Text_185E4D:: @ 8185E4D
    .string "You need to use TMs to teach good\n"
    .string "moves to POKéMON.$"

Text_185E81:: @ 8185E81
    .string "Not good enough quite yet.$"

Text_185E9C:: @ 8185E9C
    .string "You have some HMs, right? POKéMON\n"
    .string "can't forget those moves easily.$"

Text_185EDF:: @ 8185EDF
    .string "My bird POKéMON should be ready\n"
    .string "for battle.$"

Text_185F0B:: @ 8185F0B
    .string "Not ready yet!$"

Text_185F1A:: @ 8185F1A
    .string "My bird POKéMON need to learn\n"
    .string "better moves.$"

Text_185F46:: @ 8185F46
    .string "They have TMs on sale at the\n"
    .string "CELADON DEPT. STORE.\p"
    .string "TMs aren't really rare, but not\n"
    .string "many people have HMs.$"

Text_185FAE:: @ 8185FAE
    .string "Aww, bummer!$"

Text_185FBB:: @ 8185FBB
    .string "Try teaching POKéMON a move that's\n"
    .string "the same type as it.\p"
    .string "That apparently boosts the power\n"
    .string "of the move.$"

Text_186021:: @ 8186021
    .string "Have you taught your bird POKéMON\n"
    .string "how to FLY?\p"
    .string "You'll be able to soar with it into\n"
    .string "the sky!$"

Text_18607C:: @ 818607C
    .string "Shot down in flames!$"

Text_186091:: @ 8186091
    .string "Bird POKéMON are my one true love.\n"
    .string "I don't want to raise anything else.$"

Text_1860D9:: @ 81860D9
    .string "Have you heard the legend of the\n"
    .string "winged mirages?$"

Text_18610A:: @ 818610A
    .string "Why?\n"
    .string "Why'd I lose?$"

Text_18611D:: @ 818611D
    .string "Well, the winged mirages are the\n"
    .string "legendary bird POKéMON.\p"
    .string "There are three of them: ARTICUNO,\n"
    .string "ZAPDOS, and MOLTRES.$"

Text_18618E:: @ 818618E
    .string "I'm not into it, but okay.\n"
    .string "Let's go!$"

Text_1861B3:: @ 81861B3
    .string "I knew it!$"

Text_1861BE:: @ 81861BE
    .string "Winning, losing… It's insignificant\n"
    .string "under this huge sky.$"

Text_1861F7:: @ 81861F7
    .string "C'mon, c'mon.\n"
    .string "Let's go, let's go, let's go!$"

Text_186223:: @ 8186223
    .string "Arrg!\n"
    .string "Lost! Get lost!$"

Text_186239:: @ 8186239
    .string "What, what, what?\n"
    .string "What do you want still?$"

Text_186263:: @ 8186263
    .string "I need to burn some time.\n"
    .string "Shut up and battle.$"

Text_186291:: @ 8186291
    .string "What?\n"
    .string "You!?$"

Text_18629D:: @ 818629D
    .string "Raising POKéMON is a drag, man.$"

Text_1862BD:: @ 81862BD
    .string "We ride out here because of the\n"
    .string "wide-open spaces.$"

Text_1862EF:: @ 81862EF
    .string "Wipeout!$"

Text_1862F8:: @ 81862F8
    .string "It's cool you made your POKéMON so\n"
    .string "strong.\p"
    .string "Might is right!\n"
    .string "And you know it!$"

Text_186344:: @ 8186344
    .string "POKéMON battle?\n"
    .string "Cool! Rumble!$"

Text_186362:: @ 8186362
    .string "Blown away!$"

Text_18636E:: @ 818636E
    .string "You know who'd win, you and me\n"
    .string "one-on-one!$"

gUnknown_8186399:: @ 8186399
    .string "ROUTE 14\n"
    .string "West to FUCHSIA CITY$"

