gUnknown_8172FC3:: @ 8172FC3
    .string "This ship, she is a luxury liner for\n"
    .string "TRAINERS of the world!\p"
    .string "At every port, we hold parties with\n"
    .string "invited TRAINERS.$"

gUnknown_8173035:: @ 8173035
    .string "{RIVAL}: Bonjour!\n"
    .string "{PLAYER}!\p"
    .string "Imagine seeing you here!\n"
    .string "{PLAYER}, were you really invited?\p"
    .string "So how's your POKéDEX coming?\p"
    .string "I already caught 40 kinds, pal.\n"
    .string "Different kinds are everywhere.\p"
    .string "Crawl around in grassy areas, and\n"
    .string "look hard for them.$"

Text_173110:: @ 8173110
    .string "Humph!\p"
    .string "At least you're raising your\n"
    .string "POKéMON!$"

Text_17313D:: @ 817313D
    .string "{PLAYER}‥！\n"
    .string "ふなよい　してるのか！\p"
    .string "もっと　からだ\n"
    .string "きたえた　ほうが　いいぜ！$"

gUnknown_8173164:: @ 8173164
    .string "{RIVAL}: I heard there was a CUT\n"
    .string "master on board.\p"
    .string "But he was just a seasick old man!\p"
    .string "CUT itself is really useful.\n"
    .string "Yup, it'll be handy.\p"
    .string "You should go see him, too.\n"
    .string "Smell ya!$"

