Route10_Text_MarkIntro:: @ 8184B8A
    .string "Wow, you came all the way here?\n"
    .string "Maybe you're a POKéMANIAC, too?\l"
    .string "Want to see my collection?$"

Route10_Text_MarkDefeat:: @ 8184BE5
    .string "Humph.\n"
    .string "I'm not angry!$"

Route10_Text_MarkPostBattle:: @ 8184BFB
    .string "I have more rare POKéMON at home!$"

Route10_Text_ClarkIntro:: @ 8184C1D
    .string "Ha-hahah-ah-ha!$"

Route10_Text_ClarkDefeat:: @ 8184C2D
    .string "Ha-haha!\n"
    .string "Not laughing!\l"
    .string "Ha-hay fever! Haha-ha-choo!$"

Route10_Text_ClarkPostBattle:: @ 8184C60
    .string "Haha-ha-choo!\n"
    .string "Ha-choo!\l"
    .string "Snort! Snivel!$"

Route10_Text_HermanIntro:: @ 8184C86
    .string "Hi, kid!\n"
    .string "Want to see my POKéMON?$"

Route10_Text_HermanDefeat:: @ 8184CA7
    .string "Oh, no!\n"
    .string "My POKéMON!$"

Route10_Text_HermanPostBattle:: @ 8184CBB
    .string "I don't like you.\n"
    .string "I don't like anyone better than me!$"

Route10_Text_HeidiIntro:: @ 8184CF1
    .string "I've been out at a POKéMON GYM\n"
    .string "a few times.\p"
    .string "…But I always lose.$"

Route10_Text_HeidiDefeat:: @ 8184D31
    .string "Ohh!\n"
    .string "After all my training!$"

Route10_Text_HeidiPostBattle:: @ 8184D4D
    .string "I noticed some POKéMANIACS\n"
    .string "prowling around.\p"
    .string "Can you imagine? Them?\n"
    .string "Up here in the mountains?$"

Route10_Text_TrentIntro:: @ 8184DAA
    .string "Ah!\n"
    .string "This mountain air is delicious!$"

Route10_Text_TrentDefeat:: @ 8184DCE
    .string "That cleared my head!$"

Route10_Text_TrentPostBattle:: @ 8184DE4
    .string "I feel bloated on mountain air!$"

Route10_Text_CarolIntro:: @ 8184E04
    .string "I'm feeling a bit faint.\n"
    .string "I haven't hiked in some time.$"

Route10_Text_CarolDefeat:: @ 8184E3B
    .string "I'm too tired.\n"
    .string "I wasn't up for it.$"

Route10_Text_CarolPostBattle:: @ 8184E5E
    .string "The POKéMON here in the mountains\n"
    .string "are so chunky…\p"
    .string "I wish there were pink POKéMON\n"
    .string "with a floral pattern!$"

Route10_Text_RockTunnelDetourToLavender:: @ 8184EC5
    .string "ROCK TUNNEL\n"
    .string "Detour to LAVENDER TOWN$"

Route10_Text_RockTunnel:: @ 8184EE9
    .string "ROCK TUNNEL$"

Route10_Text_PowerPlant:: @ 8184EF5
    .string "POWER PLANT$"

