Text_19358E:: @ 819358E
    .string "I recently moved to this town.\p"
    .string "I hear that MR. FUJI's not from\n"
    .string "these parts originally, either.$"

gUnknown_81935ED:: @ 81935ED
    .string "That's odd, MR. FUJI isn't here.\n"
    .string "Where'd he go?$"

gUnknown_819361D:: @ 819361D
    .string "MR. FUJI had been praying alone\n"
    .string "for CUBONE's mother.$"

gUnknown_8193652:: @ 8193652
    .string "This is really MR. FUJI's house.\p"
    .string "He's really kind.\p"
    .string "He looks after abandoned and\n"
    .string "orphaned POKéMON.$"

gUnknown_81936B4:: @ 81936B4
    .string "It's so warm!\n"
    .string "POKéMON are so nice to hug.$"

gUnknown_81936DE:: @ 81936DE
    .string "NIDORINO: Gaoo!$"

gUnknown_81936EE:: @ 81936EE
    .string "PSYDUCK: Gwappa!$"

gUnknown_81936FF:: @ 81936FF
    .string "MR. FUJI: {PLAYER}…\p"
    .string "Your POKéDEX quest is one that\n"
    .string "requires strong dedication.\p"
    .string "Without deep love for POKéMON,\n"
    .string "your quest may fail.\p"
    .string "I'm not sure if this will help you,\n"
    .string "but I'd like you to have it.$"

gUnknown_81937BD:: @ 81937BD
    .string "{PLAYER} received a POKé FLUTE\n"
    .string "from MR. FUJI.$"

gUnknown_81937E5:: @ 81937E5
    .string "Upon hearing the POKé FLUTE,\n"
    .string "sleeping POKéMON will spring awake.\p"
    .string "Try using it on POKéMON that are\n"
    .string "sleeping obstacles.$"

gUnknown_819385B:: @ 819385B
    .string "You must make room for this!$"

gUnknown_8193878:: @ 8193878
    .string "MR. FUJI: Has my POKé FLUTE\n"
    .string "helped you?$"

gUnknown_81938A0:: @ 81938A0
    .string "POKéMON FAN MAGAZINE\n"
    .string "Monthly Grand Prize Drawing!\p"
    .string "The application form is…\p"
    .string "Gone! It's been clipped out.\n"
    .string "Someone must have applied already.$"

gUnknown_819392B:: @ 819392B
    .string "POKéMON magazines line the shelf.\p"
    .string "POKéMON INSIDER…\p"
    .string "POKéMON FAN…$"

