Text_179366:: @ 8179366
    .string "This tunnel goes a long way, kid!$"

Text_179388:: @ 8179388
    .string "Doh!\n"
    .string "You win!$"

gUnknown_8179396:: @ 8179396
    .string "Watch for ONIX.\n"
    .string "They appear only occasionally.\p"
    .string "High-level ones can put the\n"
    .string "squeeze on you!$"

Text_1793F1:: @ 81793F1
    .string "Hmm.\n"
    .string "Maybe I'm lost in here…$"

Text_17940E:: @ 817940E
    .string "Ease up!\n"
    .string "What am I doing?\l"
    .string "Which way is out?$"

gUnknown_817943A:: @ 817943A
    .string "That sleeping POKéMON on ROUTE 12\n"
    .string "forced me to take this detour.$"

Text_17947B:: @ 817947B
    .string "Outsiders like you need to show me\n"
    .string "some respect!$"

Text_1794AC:: @ 81794AC
    .string "I give!$"

gUnknown_81794B4:: @ 81794B4
    .string "You're talented enough to hike!$"

Text_1794D4:: @ 81794D4
    .string "POKéMON fight!\n"
    .string "Ready, go!$"

Text_1794EE:: @ 81794EE
    .string "Game over!$"

gUnknown_81794F9:: @ 81794F9
    .string "Oh well, I'll get a ZUBAT as I go!$"

Text_17951C:: @ 817951C
    .string "Eek!\p"
    .string "Don't try anything funny in the\n"
    .string "dark!$"

Text_179547:: @ 8179547
    .string "It was too dark…$"

gUnknown_8179558:: @ 8179558
    .string "I saw a MACHOP in this tunnel.$"

Text_179577:: @ 8179577
    .string "I came this far looking for wild\n"
    .string "POKéMON.$"

Text_1795A1:: @ 81795A1
    .string "I'm out of POKéMON!$"

gUnknown_81795B5:: @ 81795B5
    .string "You looked cute and harmless.\n"
    .string "Was I ever wrong!$"

Text_1795E5:: @ 81795E5
    .string "You have POKéMON!\n"
    .string "Let's start!$"

Text_179604:: @ 8179604
    .string "You play hard!$"

gUnknown_8179613:: @ 8179613
    .string "Whew!\n"
    .string "I'm all sweaty now.$"

gUnknown_817962D:: @ 817962D
    .string "ROCK TUNNEL\n"
    .string "CERULEAN CITY - LAVENDER TOWN$"

