RockTunnel_1F_Text_LennyIntro:: @ 8179366
    .string "This tunnel goes a long way, kid!$"

RockTunnel_1F_Text_LennyDefeat:: @ 8179388
    .string "Doh!\n"
    .string "You win!$"

RockTunnel_1F_Text_LennyPostBattle:: @ 8179396
    .string "Watch for ONIX.\n"
    .string "They appear only occasionally.\p"
    .string "High-level ones can put the\n"
    .string "squeeze on you!$"

RockTunnel_1F_Text_OliverIntro:: @ 81793F1
    .string "Hmm.\n"
    .string "Maybe I'm lost in here…$"

RockTunnel_1F_Text_OliverDefeat:: @ 817940E
    .string "Ease up!\n"
    .string "What am I doing?\l"
    .string "Which way is out?$"

RockTunnel_1F_Text_OliverPostBattle:: @ 817943A
    .string "That sleeping POKéMON on ROUTE 12\n"
    .string "forced me to take this detour.$"

RockTunnel_1F_Text_LucasIntro:: @ 817947B
    .string "Outsiders like you need to show me\n"
    .string "some respect!$"

RockTunnel_1F_Text_LucasDefeat:: @ 81794AC
    .string "I give!$"

RockTunnel_1F_Text_LucasPostBattle:: @ 81794B4
    .string "You're talented enough to hike!$"

RockTunnel_1F_Text_AshtonIntro:: @ 81794D4
    .string "POKéMON fight!\n"
    .string "Ready, go!$"

RockTunnel_1F_Text_AshtonDefeat:: @ 81794EE
    .string "Game over!$"

RockTunnel_1F_Text_AshtonPostBattle:: @ 81794F9
    .string "Oh well, I'll get a ZUBAT as I go!$"

RockTunnel_1F_Text_LeahIntro:: @ 817951C
    .string "Eek!\p"
    .string "Don't try anything funny in the\n"
    .string "dark!$"

RockTunnel_1F_Text_LeahDefeat:: @ 8179547
    .string "It was too dark…$"

RockTunnel_1F_Text_LeahPostBattle:: @ 8179558
    .string "I saw a MACHOP in this tunnel.$"

RockTunnel_1F_Text_DanaIntro:: @ 8179577
    .string "I came this far looking for wild\n"
    .string "POKéMON.$"

RockTunnel_1F_Text_DanaDefeat:: @ 81795A1
    .string "I'm out of POKéMON!$"

RockTunnel_1F_Text_DanaPostBattle:: @ 81795B5
    .string "You looked cute and harmless.\n"
    .string "Was I ever wrong!$"

RockTunnel_1F_Text_ArianaIntro:: @ 81795E5
    .string "You have POKéMON!\n"
    .string "Let's start!$"

RockTunnel_1F_Text_ArianaDefeat:: @ 8179604
    .string "You play hard!$"

RockTunnel_1F_Text_ArianaPostBattle:: @ 8179613
    .string "Whew!\n"
    .string "I'm all sweaty now.$"

RockTunnel_1F_Text_RouteSign:: @ 817962D
    .string "ROCK TUNNEL\n"
    .string "CERULEAN CITY - LAVENDER TOWN$"

