CeladonCity_Restaurant_EventObjects:
	object_event 1, 59, 0, 12, 0, 7, 0, 3, 5, 18, 0, 0, 0, 0, 0, CeladonCity_Restaurant_EventScript_16D1EB, 0, 0, 0
	object_event 2, 28, 0, 11, 0, 4, 0, 3, 3, 33, 0, 0, 0, 0, 0, CeladonCity_Restaurant_EventScript_16D1F4, 0, 0, 0
	object_event 3, 27, 0, 9, 0, 4, 0, 3, 10, 17, 0, 0, 0, 0, 0, CeladonCity_Restaurant_EventScript_16D25E, 0, 0, 0
	object_event 4, 30, 0, 1, 0, 2, 0, 0, 8, 17, 0, 0, 0, 0, 0, CeladonCity_Restaurant_EventScript_16D1FD, 0, 0, 0
	object_event 5, 47, 0, 3, 0, 7, 0, 0, 9, 17, 0, 0, 0, 0, 0, CeladonCity_Restaurant_EventScript_16D255, 0, 0, 0

CeladonCity_Restaurant_MapWarps:
	warp_def 5, 9, 0, 7, 774
	warp_def 6, 9, 0, 7, 774
	warp_def 7, 9, 0, 7, 774

CeladonCity_Restaurant_MapEvents::
	map_events CeladonCity_Restaurant_EventObjects, CeladonCity_Restaurant_MapWarps, 0x0, 0x0
