gUnknown_81978E6:: @ 81978E6
    .string "Hi!\p"
    .string "Sorry, but we're taking a break\n"
    .string "right now.$"

gUnknown_8197915:: @ 8197915
    .string "My POKéMON are weak, so I often\n"
    .string "have to go to the DRUGSTORE.$"

gUnknown_8197952:: @ 8197952
    .string "Psst! There's a basement under the\n"
    .string "GAME CORNER, I hear.$"

gUnknown_819798A:: @ 819798A
    .string "Munch…\p"
    .string "The man at that table lost it all\n"
    .string "at the slots.$"

gUnknown_81979C1:: @ 81979C1
    .string "Go ahead! Laugh!\n"
    .string "I'm flat-out busted!\p"
    .string "No more slots for me!\n"
    .string "I'm going straight!\p"
    .string "Here!\n"
    .string "I won't be needing this anymore!$"

gUnknown_8197A38:: @ 8197A38
    .string "{PLAYER} received a COIN CASE\n"
    .string "from the man.$"

gUnknown_8197A5E:: @ 8197A5E
    .string "Make room for this!$"

gUnknown_8197A72:: @ 8197A72
    .string "I always thought I was going to\n"
    .string "win it back…$"

