FiveIsland_MemorialPillar_EventObjects:
	object_event 1, 25, 0, 8, 0, 44, 0, 4, 15, 17, 0, 0, 0, 0, 0, FiveIsland_MemorialPillar_EventScript_1689D3, 0, 0, 0
	object_event 2, 26, 0, 12, 0, 6, 0, 3, 21, 17, 0, 1, 0, 3, 0, FiveIsland_MemorialPillar_EventScript_1AC317, 0, 0, 0
	object_event 3, 26, 0, 14, 0, 17, 0, 3, 19, 17, 0, 1, 0, 2, 0, FiveIsland_MemorialPillar_EventScript_1AC355, 0, 0, 0
	object_event 4, 26, 0, 17, 0, 31, 0, 3, 2, 17, 0, 1, 0, 3, 0, FiveIsland_MemorialPillar_EventScript_1AC393, 0, 0, 0
	object_event 5, 92, 0, 4, 0, 47, 0, 3, 8, 17, 0, 0, 0, 0, 0, FiveIsland_MemorialPillar_EventScript_1BEC83, 480, 0, 0

FiveIsland_MemorialPillar_MapBGEvents:
	bg_event 9, 43, 0, 1, 0, FiveIsland_MemorialPillar_EventScript_168A48
	bg_event 8, 52, 3, 7, 0, 107, 170, 1
	bg_event 15, 7, 3, 7, 0, 148, 171, 1
	bg_event 17, 22, 3, 7, 0, 142, 172, 1
	bg_event 14, 25, 3, 7, 0, 149, 173, 1

FiveIsland_MemorialPillar_MapEvents::
	map_events FiveIsland_MemorialPillar_EventObjects, 0x0, 0x0, FiveIsland_MemorialPillar_MapBGEvents
