FiveIsland_MemorialPillar_Text_MiloIntro:: @ 818AE50
    .string "I'm the eldest of the BIRD\n"
    .string "BROTHERS.\p"
    .string "The best thing about birds…\n"
    .string "It has to be the beak.$"

FiveIsland_MemorialPillar_Text_MiloDefeat:: @ 818AEA8
    .string "Oh, so sharp!$"

FiveIsland_MemorialPillar_Text_MiloPostBattle:: @ 818AEB6
    .string "You can fly to FOUR ISLAND from\n"
    .string "here.$"

FiveIsland_MemorialPillar_Text_ChazIntro:: @ 818AEDC
    .string "I'm the middle kid of the BIRD\n"
    .string "BROTHERS.\p"
    .string "The best thing about birds…\n"
    .string "It has to be the wings.$"

FiveIsland_MemorialPillar_Text_ChazDefeat:: @ 818AF39
    .string "Flap, flap!$"

FiveIsland_MemorialPillar_Text_ChazPostBattle:: @ 818AF45
    .string "There was a really somber guy\n"
    .string "over that way.$"

FiveIsland_MemorialPillar_Text_HaroldIntro:: @ 818AF72
    .string "I'm the youngest of the BIRD\n"
    .string "BROTHERS.\p"
    .string "The best thing about birds…\n"
    .string "It has to be the down.$"

FiveIsland_MemorialPillar_Text_HaroldDefeat:: @ 818AFCC
    .string "Down is so comfy…\n"
    .string "It makes me drowsy…$"

FiveIsland_MemorialPillar_Text_HaroldPostBattle:: @ 818AFF2
    .string "It fills me with happiness when\n"
    .string "bird POKéMON beg playfully…$"

FiveIsland_MemorialPillar_Text_ScrubScrub:: @ 818B02E
    .string "Scrub, scrub…$"

FiveIsland_MemorialPillar_Text_YourMonsLookHealthy:: @ 818B03C
    .string "Hello…\n"
    .string "Your POKéMON look healthy…$"

FiveIsland_MemorialPillar_Text_ThisIsWhereIBuriedMyOnix:: @ 818B05E
    .string "This is where I buried my ONIX…\n"
    .string "It was named TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering:: @ 818B095
    .string "“Here lies TECTONIX” is engraved\n"
    .string "on a boulder.\p"
    .string "There is a LEMONADE placed as an\n"
    .string "offering in front of the grave.$"

FiveIsland_MemorialPillar_Text_LeaveAnotherLemonadeOffering:: @ 818B105
    .string "Would you like to leave another\n"
    .string "LEMONADE as an offering?$"

FiveIsland_MemorialPillar_Text_PlacedCanOfLemonade:: @ 818B13E
    .string "{PLAYER} placed a can of LEMONADE\n"
    .string "in front of the grave.$"

FiveIsland_MemorialPillar_Text_ThankYouPleaseTakeThis:: @ 818B171
    .string "Th-thank you…\p"
    .string "That was my TECTONIX's favorite\n"
    .string "drink…\p"
    .string "I don't even know you, but your\n"
    .string "act of kindness…\p"
    .string "It's uplifted me a little.\p"
    .string "Can you please take this as my\n"
    .string "thanks?$"

FiveIsland_MemorialPillar_Text_BeGoodToYourMonsToo:: @ 818B219
    .string "Please be good to your POKéMON,\n"
    .string "too.$"

FiveIsland_MemorialPillar_Text_DontHaveRoomForIt:: @ 818B23E
    .string "If you don't have room for it,\n"
    .string "I'll hold it for you till next time.$"

FiveIsland_MemorialPillar_Text_StillHaveThingAsMyThanks:: @ 818B282
    .string "Oh, it's you from that time…\p"
    .string "I still have that thing I wanted\n"
    .string "you to have as my thanks.$"

FiveIsland_MemorialPillar_Text_ScrubScrubTectonix:: @ 818B2DA
    .string "Scrub, scrub…\p"
    .string "… … …\n"
    .string "TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonix:: @ 818B2F8
    .string "Boulders and rocks are neatly piled\n"
    .string "up as a cairn.\p"
    .string "“Here lies TECTONIX” is engraved\n"
    .string "on a boulder.$"

