SaffronCity_House1_1F_EventObjects:
	object_event 1, 30, 0, 8, 0, 4, 0, 3, 9, 17, 0, 0, 0, 0, 0, SaffronCity_House1_1F_EventScript_16EB40, 0, 0, 0
	object_event 2, 31, 0, 3, 0, 3, 0, 3, 8, 17, 0, 0, 0, 0, 0, SaffronCity_House1_1F_EventScript_16EB37, 0, 0, 0
	object_event 3, 117, 0, 4, 0, 4, 0, 3, 3, 33, 0, 0, 0, 0, 0, SaffronCity_House1_1F_EventScript_16EB49, 0, 0, 0

SaffronCity_House1_1F_MapWarps:
	warp_def 3, 8, 3, 1, 778
	warp_def 4, 8, 3, 1, 778
	warp_def 5, 8, 3, 1, 778
	warp_def 10, 2, 3, 0, 3585

SaffronCity_House1_1F_MapEvents::
	map_events SaffronCity_House1_1F_EventObjects, SaffronCity_House1_1F_MapWarps, 0x0, 0x0
