Text_19A9E7:: @ 819A9E7
    .string "AGATHA's GHOST-type POKéMON are\n"
    .string "horrifically terrifying in toughness.\p"
    .string "I took my FIGHTING-type POKéMON\n"
    .string "and raised them to the max.\p"
    .string "I went at AGATHA feeling pretty\n"
    .string "confident, but she whupped us.\p"
    .string "That old lady's also got a really\n"
    .string "short fuse, too.\p"
    .string "It doesn't take anything to get\n"
    .string "that scary lady hollering.$"

Text_19AB16:: @ 819AB16
    .string "Maybe becoming an ELITE FOUR\n"
    .string "member is in the blood.\p"
    .string "From what I've heard, LANCE has\n"
    .string "a cousin who's a GYM LEADER\l"
    .string "somewhere far away.$"

gUnknown_819AB9B:: @ 819AB9B
    .string "My daughter is so self-centered.\n"
    .string "She has but a few friends.$"

gUnknown_819ABD7:: @ 819ABD7
    .string "My daughter likes to mimic people.\n"
    .string "It's rather vexing.\p"
    .string "Her mimicry has earned her the\n"
    .string "nickname COPYCAT around here.$"

gUnknown_819AC4B:: @ 819AC4B
    .string "CHANSEY: Chaan! Sii!$"

