FuchsiaCity_PokemonCenter_2F_MapScripts:: @ 816D724
	map_script MAP_SCRIPT_ON_FRAME_TABLE, FuchsiaCity_PokemonCenter_2F_MapScript1_1BB2A3
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, FuchsiaCity_PokemonCenter_2F_MapScript2_1BB1ED
	map_script MAP_SCRIPT_ON_LOAD, FuchsiaCity_PokemonCenter_2F_MapScript3_1BB237
	map_script MAP_SCRIPT_ON_TRANSITION, FuchsiaCity_PokemonCenter_2F_MapScript4_1BB1B4
	.byte 0

FuchsiaCity_PokemonCenter_2F_EventScript_16D739:: @ 816D739
	call EventScript_1BB4A3
	end

EventScript_16D73F:: @ 816D73F
	call EventScript_1BB6AB
	end

EventScript_16D745:: @ 816D745
	call EventScript_1BB7DE
	end
