Route1_Text_WorkAtPokeMartTakeSample::
    .string "{COLOR DARK_GRAY}¡Hola!\n"
    .string "Trabajo en una {SHADOW DYNAMIC_COLOR4}TIENDA POKéMON{SHADOW LIGHT_GRAY}.\p"
    .string "Contamos con una amplia variedad\n"
    .string "de cosas que te encantarán.\p"
    .string "Visítanos en {SHADOW DYNAMIC_COLOR4}CIUDAD VERDE{SHADOW LIGHT_GRAY}.\p"
    .string "¡Mira, te daré una muestra!\n"
    .string "¡Aquí tienes!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "{COLOR DARK_GRAY}¡También tenemos {SHADOW DYNAMIC_COLOR4}POKé BALLS{SHADOW LIGHT_GRAY}\n"
    .string "para capturar los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}!$"

Route1_Text_PutPotionAway::
    .string "{COLOR BLUE}{SHADOW LIGHT_BLUE}{PLAYER}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} puso la {COLOR BLUE}{SHADOW LIGHT_BLUE}POCIÓN\n"
    .string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}en el {COLOR BLUE}{SHADOW LIGHT_BLUE}BOLSILLO{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} de {COLOR BLUE}{SHADOW LIGHT_BLUE}OBJETOS\l"
    .string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}de la {COLOR BLUE}{SHADOW LIGHT_BLUE}MOCHILA{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}.$"

Route1_Text_CanJumpFromLedges::
    .string "{COLOR DARK_GRAY}¿Ves esos bordes del camino?\p"
    .string "Dan miedo, pero puedes saltar\n"
    .string "por encima de ellos.\p"
    .string "¡De esa forma podrás volver más\n"
    .string "rápidamente a {SHADOW DYNAMIC_COLOR4}PUEBLO PALETA{SHADOW LIGHT_GRAY}!$"

Route1_Text_RouteSign::
    .string "{SHADOW DYNAMIC_COLOR4}RUTA 1{SHADOW LIGHT_GRAY}\n"
    .string "PUEBLO PALETA - CIUDAD VERDE$"

Route1_Text_RouteSign2::
    .string "Una apacible senda campestres de\n"
    .string "exuberante vegetación.$"

Route1_EventScript_TrainerAnibalIntro::
    .string "{COLOR DARK_GRAY}Sabes que significa eso, ¿verdad?$"

Route1_EventScript_TrainerAnibalDefeat::
    .string "¡PERO QUE FUERTE ERES!$"

Route1_EventScript_TrainerAnibalPostBattle::
    .string "{COLOR DARK_GRAY}¡Vayas por donde vayas habrá\n"
    .string "{SHADOW DYNAMIC_COLOR4}ENTRENADORES{SHADOW LIGHT_GRAY} dispuestos a\l"
    .string "retarte a un combate!$"