gUnknown_818329D:: @ 818329D
    .string "Hi!\n"
    .string "I work at a POKéMON MART.\p"
    .string "It's part of a convenient chain\n"
    .string "selling all sorts of items.\p"
    .string "Please, visit us in VIRIDIAN CITY.\p"
    .string "I know, I'll give you a sample.\n"
    .string "Here you go!$"

gUnknown_8183347:: @ 8183347
    .string "Please come see us if you need\n"
    .string "POKé BALLS for catching POKéMON.$"

gUnknown_8183387:: @ 8183387
    .string "{PLAYER} put the POTION away in\n"
    .string "the BAG's ITEMS POCKET.$"

gUnknown_81833B9:: @ 81833B9
    .string "See those ledges along the road?\p"
    .string "It's a bit scary, but you can jump\n"
    .string "from them.\p"
    .string "You can get back to PALLET TOWN\n"
    .string "quicker that way.$"

gUnknown_818343A:: @ 818343A
    .string "ROUTE 1\n"
    .string "PALLET TOWN - VIRIDIAN CITY$"

