OneIsland_PokemonCenter_2F_MapScripts:: @ 8171334
	map_script MAP_SCRIPT_ON_FRAME_TABLE, OneIsland_PokemonCenter_2F_MapScript1_1BB2A3
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, OneIsland_PokemonCenter_2F_MapScript2_1BB1ED
	map_script MAP_SCRIPT_ON_LOAD, OneIsland_PokemonCenter_2F_MapScript3_1BB237
	map_script MAP_SCRIPT_ON_TRANSITION, OneIsland_PokemonCenter_2F_MapScript4_1BB1B4
	.byte 0

OneIsland_PokemonCenter_2F_EventScript_171349:: @ 8171349
	call EventScript_1BB4A3
	end

EventScript_17134F:: @ 817134F
	call EventScript_1BB6AB
	end

EventScript_171355:: @ 8171355
	call EventScript_1BB7DE
	end
