gUnknown_817A0E3:: @ 817A0E3
    .string "Come, child!\n"
    .string "I have purified this space.\l"
    .string "You can rest here.$"

Text_17A11F:: @ 817A11F
    .string "Give…me…\n"
    .string "your…all…$"

Text_17A132:: @ 817A132
    .string "Gasp!$"

gUnknown_817A138:: @ 817A138
    .string "I was under possession.$"

Text_17A150:: @ 817A150
    .string "You…shall…\n"
    .string "join…us…$"

Text_17A164:: @ 817A164
    .string "What a nightmare!$"

gUnknown_817A176:: @ 817A176
    .string "I was possessed.$"

Text_17A187:: @ 817A187
    .string "Zombies!$"

Text_17A190:: @ 817A190
    .string "Ha?$"

gUnknown_817A194:: @ 817A194
    .string "I regained my senses.$"

Text_17A1AA:: @ 817A1AA
    .string "Urgah…\n"
    .string "Urff…$"

Text_17A1B7:: @ 817A1B7
    .string "Whoo!$"

gUnknown_817A1BD:: @ 817A1BD
    .string "I fell to evil spirits despite my\n"
    .string "training in the mountains…$"

gUnknown_817A1FA:: @ 817A1FA
    .string "Entered the purified and protected\n"
    .string "zone.\p"
    .string "{PLAYER}'s POKéMON were fully\n"
    .string "healed.$"

