PokemonTower_5F_Text_RestHereInPurifiedSpace:: @ 817A0E3
    .string "Come, child!\n"
    .string "I have purified this space.\l"
    .string "You can rest here.$"

PokemonTower_5F_Text_TammyIntro:: @ 817A11F
    .string "Give…me…\n"
    .string "your…all…$"

PokemonTower_5F_Text_TammyDefeat:: @ 817A132
    .string "Gasp!$"

PokemonTower_5F_Text_TammyPostBattle:: @ 817A138
    .string "I was under possession.$"

PokemonTower_5F_Text_RuthIntro:: @ 817A150
    .string "You…shall…\n"
    .string "join…us…$"

PokemonTower_5F_Text_RuthDefeat:: @ 817A164
    .string "What a nightmare!$"

PokemonTower_5F_Text_RuthPostBattle:: @ 817A176
    .string "I was possessed.$"

PokemonTower_5F_Text_KarinaIntro:: @ 817A187
    .string "Zombies!$"

PokemonTower_5F_Text_KarinaDefeat:: @ 817A190
    .string "Ha?$"

PokemonTower_5F_Text_KarinaPostBattle:: @ 817A194
    .string "I regained my senses.$"

PokemonTower_5F_Text_JanaeIntro:: @ 817A1AA
    .string "Urgah…\n"
    .string "Urff…$"

PokemonTower_5F_Text_JanaeDefeat:: @ 817A1B7
    .string "Whoo!$"

PokemonTower_5F_Text_JanaePostBattle:: @ 817A1BD
    .string "I fell to evil spirits despite my\n"
    .string "training in the mountains…$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed:: @ 817A1FA
    .string "Entered the purified and protected\n"
    .string "zone.\p"
    .string "{PLAYER}'s POKéMON were fully\n"
    .string "healed.$"

