PokemonTower_5F_Text_RestHereInPurifiedSpace::
    .string "Come, child!\n"
    .string "I have purified this space.\l"
    .string "You can rest here.$"

PokemonTower_5F_Text_TammyIntro::
    .string "Give…me…\n"
    .string "your…all…$"

PokemonTower_5F_Text_TammyDefeat::
    .string "Gasp!$"

PokemonTower_5F_Text_TammyPostBattle::
    .string "I was under possession.$"

PokemonTower_5F_Text_RuthIntro::
    .string "You…shall…\n"
    .string "join…us…$"

PokemonTower_5F_Text_RuthDefeat::
    .string "What a nightmare!$"

PokemonTower_5F_Text_RuthPostBattle::
    .string "I was possessed.$"

PokemonTower_5F_Text_KarinaIntro::
    .string "Zombies!$"

PokemonTower_5F_Text_KarinaDefeat::
    .string "Ha?$"

PokemonTower_5F_Text_KarinaPostBattle::
    .string "I regained my senses.$"

PokemonTower_5F_Text_JanaeIntro::
    .string "Urgah…\n"
    .string "Urff…$"

PokemonTower_5F_Text_JanaeDefeat::
    .string "Whoo!$"

PokemonTower_5F_Text_JanaePostBattle::
    .string "I fell to evil spirits despite my\n"
    .string "training in the mountains…$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed::
    .string "Entered the purified and protected\n"
    .string "zone.\p"
    .string "{PLAYER}'s POKéMON were fully\n"
    .string "healed.$"

