Route16_NorthEntrance_1F_Text_NoPedestriansOnCyclingRoad::
    .string "No pedestrians are allowed on\n"
    .string "CYCLING ROAD!$"

Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse::
    .string "CYCLING ROAD is a downhill course\n"
    .string "by the sea. It's a great ride.$"

Route16_NorthEntrance_1F_Text_ExcuseMeWaitUp::
    .string "Excuse me!\n"
    .string "Wait up, please!$"

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort::
    .string "How'd you get in?\n"
    .string "Good effort!$"

