Route16_NorthEntrance_1F_Text_NoPedestriansOnCyclingRoad:: @ 819F95F
    .string "No pedestrians are allowed on\n"
    .string "CYCLING ROAD!$"

Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse:: @ 819F98B
    .string "CYCLING ROAD is a downhill course\n"
    .string "by the sea. It's a great ride.$"

Route16_NorthEntrance_1F_Text_ExcuseMeWaitUp:: @ 819F9CC
    .string "Excuse me!\n"
    .string "Wait up, please!$"

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort:: @ 819F9E8
    .string "How'd you get in?\n"
    .string "Good effort!$"

