MtEmber_RubyPath_B1F_EventObjects:
	object_event 1, 96, 0, 1, 0, 8, 0, 3, 1, 17, 0, 0, 0, 0, 0, MtEmber_RubyPath_B1F_EventScript_1BE00C, 18, 0, 0
	object_event 2, 96, 0, 1, 0, 11, 0, 3, 1, 17, 0, 0, 0, 0, 0, MtEmber_RubyPath_B1F_EventScript_1BE00C, 19, 0, 0
	object_event 3, 96, 0, 3, 0, 12, 0, 3, 1, 17, 0, 0, 0, 0, 0, MtEmber_RubyPath_B1F_EventScript_1BE00C, 20, 0, 0
	object_event 4, 96, 0, 5, 0, 14, 0, 3, 1, 17, 0, 0, 0, 0, 0, MtEmber_RubyPath_B1F_EventScript_1BE00C, 21, 0, 0

MtEmber_RubyPath_B1F_MapWarps:
	warp_def 9, 21, 0, 1, 359
	warp_def 6, 1, 0, 0, 361

MtEmber_RubyPath_B1F_MapEvents::
	map_events MtEmber_RubyPath_B1F_EventObjects, MtEmber_RubyPath_B1F_MapWarps, 0x0, 0x0
