# 1 "data/maps/SSAnne_2F_Room6/scripts.pory"

# 2 "data/maps/SSAnne_2F_Room6/scripts.pory"
SSAnne_2F_Room6_MapScripts::
# 3 "data/maps/SSAnne_2F_Room6/scripts.pory"
	.byte 0
# 4 "data/maps/SSAnne_2F_Room6/scripts.pory"

# 5 "data/maps/SSAnne_2F_Room6/scripts.pory"
SSAnne_2F_Room6_EventScript_Woman1::
# 6 "data/maps/SSAnne_2F_Room6/scripts.pory"
	msgbox SSAnne_2F_Room6_Text_CaptainIsAwfullySick, MSGBOX_NPC
# 7 "data/maps/SSAnne_2F_Room6/scripts.pory"
	end
# 8 "data/maps/SSAnne_2F_Room6/scripts.pory"

# 9 "data/maps/SSAnne_2F_Room6/scripts.pory"
SSAnne_2F_Room6_EventScript_Woman2::
# 10 "data/maps/SSAnne_2F_Room6/scripts.pory"
	msgbox SSAnne_2F_Room6_Text_ManyPeopleGetSeasick, MSGBOX_NPC
# 11 "data/maps/SSAnne_2F_Room6/scripts.pory"
	end
