gUnknown_81964D7:: @ 81964D7
    .string "There is nothing that I don't know,\n"
    .string "like I wrote on the blackboard.\p"
    .string "I know about the world of POKéMON\n"
    .string "in your GAME BOY ADVANCE!\p"
    .string "Get together with your friends and\n"
    .string "enjoy trading POKéMON!$"

Text_196591:: @ 8196591
    .string "{PLAYER} obtained an EEVEE!$"

Text_1965A7:: @ 81965A7
    .string "ポケモンが　いっぱいだ\n"
    .string "ボックスを　かえて　きなさい$"

gUnknown_81965C2:: @ 81965C2
    .string "POKéMON Lecture\p"
    .string "Playing with the Wireless Adapter$"

Text_1965F4:: @ 81965F4
    .string "Which heading do you want to read?$"

gUnknown_8196617:: @ 8196617
    .string "The POKéMON WIRELESS CLUB is\n"
    .string "upstairs at any POKéMON CENTER.\p"
    .string "Visit one to link up with friend(s)\n"
    .string "using your Wireless Adapter.$"

gUnknown_8196695:: @ 8196695
    .string "To link only with a friend, go to\n"
    .string "the DIRECT CORNER.\p"
    .string "It is the right counter at the\n"
    .string "POKéMON WIRELESS CLUB.\p"
    .string "Go into the TRADE CORNER or the\n"
    .string "COLOSSEUM with your friend.$"

gUnknown_819673C:: @ 819673C
    .string "To link and communicate with\n"
    .string "anyone, go to the UNION ROOM.\p"
    .string "It is the left counter at the\n"
    .string "POKéMON WIRELESS CLUB.\p"
    .string "Go to the UNION ROOM and enjoy\n"
    .string "meeting other TRAINERS.$"

gUnknown_81967E3:: @ 81967E3
    .string "It's a pamphlet on TMs.\p"
    .string "… …\p"
    .string "There are fifty TMs in all.\p"
    .string "There are also seven HMs that\n"
    .string "can be used repeatedly.\p"
    .string "SILPH CO.$"

