CeladonCity_GameCorner_PrizeRoom_EventObjects:
	object_event 1, 30, 0, 2, 0, 6, 0, 3, 2, 17, 0, 0, 0, 0, 0, CeladonCity_GameCorner_PrizeRoom_EventScript_16CB76, 0, 0, 0
	object_event 2, 33, 0, 6, 0, 7, 0, 3, 1, 17, 0, 0, 0, 0, 0, CeladonCity_GameCorner_PrizeRoom_EventScript_16CB7F, 0, 0, 0
	object_event 3, 47, 0, 4, 0, 2, 0, 3, 8, 17, 0, 0, 0, 0, 0, CeladonCity_GameCorner_PrizeRoom_EventScript_16CB88, 0, 0, 0
	object_event 4, 47, 0, 6, 0, 2, 0, 3, 8, 17, 0, 0, 0, 0, 0, CeladonCity_GameCorner_PrizeRoom_EventScript_16CE1D, 0, 0, 0
	object_event 5, 47, 0, 2, 0, 2, 0, 3, 8, 17, 0, 0, 0, 0, 0, CeladonCity_GameCorner_PrizeRoom_EventScript_16CF88, 0, 0, 0

CeladonCity_GameCorner_PrizeRoom_MapWarps:
	warp_def 3, 9, 0, 5, 774
	warp_def 4, 8, 3, 5, 774
	warp_def 5, 9, 0, 5, 774

CeladonCity_GameCorner_PrizeRoom_MapEvents::
	map_events CeladonCity_GameCorner_PrizeRoom_EventObjects, CeladonCity_GameCorner_PrizeRoom_MapWarps, 0x0, 0x0
