CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon:: @ 8196FC1
    .string "I sure do fancy that PORYGON!\n"
    .string "But, it's hard to win at slots!$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday:: @ 8196FFF
    .string "Gahaha! I raked it in today!\n"
    .string "If only every day were like this…$"

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired:: @ 819703E
    .string "A COIN CASE is required…$"

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes:: @ 8197057
    .string "We exchange your COINS for prizes.$"

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize:: @ 819707A
    .string "Which prize would you like?$"

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo:: @ 8197096
    .string "はい どうぞ$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize:: @ 819709D
    .string "So, you want the {STR_VAR_1}?$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM:: @ 81970B2
    .string "Okay, a TM of {STR_VAR_2}\n"
    .string "is what you want?$"

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins:: @ 81970D5
    .string "Sorry, you'll need more COINS\n"
    .string "than that.$"

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom:: @ 81970FE
    .string "おきゃくさん もう もてないよ$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen:: @ 819710E
    .string "あっ そう$"

