SixIsland_PatternBush_Text_BethanyIntro:: @ 817BF3A
    .string "I'm curious, how do you raise your\n"
    .string "POKéMON?$"

SixIsland_PatternBush_Text_BethanyDefeat:: @ 817BF66
    .string "You raise your POKéMON with a\n"
    .string "whole lot of love!$"

SixIsland_PatternBush_Text_BethanyPostBattle:: @ 817BF97
    .string "In the same way your mother raised\n"
    .string "you full of love, you should raise\l"
    .string "your POKéMON.$"

SixIsland_PatternBush_Text_AllisonIntro:: @ 817BFEB
    .string "I'm working to preserve the natural\n"
    .string "ecology of POKéMON here.$"

SixIsland_PatternBush_Text_AllisonDefeat:: @ 817C028
    .string "Oh, for someone so young, you are\n"
    .string "tremendous!$"

SixIsland_PatternBush_Text_AllisonPostBattle:: @ 817C056
    .string "I'm not saying that you shouldn't\n"
    .string "catch POKéMON.\p"
    .string "I just want people to raise their\n"
    .string "POKéMON responsibly.$"

SixIsland_PatternBush_Text_GarretIntro:: @ 817C0BE
    .string "I caught a BUG POKéMON that lives\n"
    .string "only around here!$"

SixIsland_PatternBush_Text_GarretDefeat:: @ 817C0F2
    .string "Heheh…\n"
    .string "Isn't my POKéMON awesome?$"

SixIsland_PatternBush_Text_GarretPostBattle:: @ 817C113
    .string "There's a girl near the BUSH who\n"
    .string "measures HERACROSS for TRAINERS.$"

SixIsland_PatternBush_Text_JonahIntro:: @ 817C155
    .string "You know, it just doesn't feel right\n"
    .string "if I don't use BUG POKéMON.$"

SixIsland_PatternBush_Text_JonahDefeat:: @ 817C196
    .string "It's okay, losing is a fun part of\n"
    .string "POKéMON's appeal, too.$"

SixIsland_PatternBush_Text_JonahPostBattle:: @ 817C1D0
    .string "By the way, “appeal” is a weird\n"
    .string "word, if you think about it.\p"
    .string "Like, is it like an orange peel?\n"
    .string "Or like a ringing bell?$"

SixIsland_PatternBush_Text_VanceIntro:: @ 817C246
    .string "Yeah, yeah, yeah!\n"
    .string "Look at all the BUG POKéMON!$"

SixIsland_PatternBush_Text_VanceDefeat:: @ 817C275
    .string "I got beat while I was still busy\n"
    .string "celebrating!$"

SixIsland_PatternBush_Text_VancePostBattle:: @ 817C2A4
    .string "I'm going to bring my little brother\n"
    .string "here next time.$"

SixIsland_PatternBush_Text_NashIntro:: @ 817C2D9
    .string "Look, look! There are funny\n"
    .string "patterns on the ground.$"

SixIsland_PatternBush_Text_NashDefeat:: @ 817C30D
    .string "Super awesome!$"

SixIsland_PatternBush_Text_NashPostBattle:: @ 817C31C
    .string "The funny patterns on the ground…\p"
    .string "They look like the patterns on my\n"
    .string "grandpa's clothes.$"

SixIsland_PatternBush_Text_CordellIntro:: @ 817C373
    .string "I bet you think I'm just some guy,\n"
    .string "don't you, eh?$"

SixIsland_PatternBush_Text_CordellDefeat:: @ 817C3A5
    .string "I bet you think I'm weak,\n"
    .string "don't you, eh?$"

SixIsland_PatternBush_Text_CordellPostBattle:: @ 817C3CE
    .string "Ayup, you townies come around all\n"
    .string "so dandy with a hat that flashy…\p"
    .string "How about giving me that?$"

SixIsland_PatternBush_Text_DaliaIntro:: @ 817C42B
    .string "Take a deep breath.\n"
    .string "Isn't the air delicious?$"

SixIsland_PatternBush_Text_DaliaDefeat:: @ 817C458
    .string "If you'd like, I can teach you how\n"
    .string "to breathe properly.$"

SixIsland_PatternBush_Text_DaliaPostBattle:: @ 817C490
    .string "First, exhale.\n"
    .string "Blow everything out.\p"
    .string "When you can't exhale anymore,\n"
    .string "inhale the clean air!\p"
    .string "Isn't it refreshing?$"

SixIsland_PatternBush_Text_JoanaIntro:: @ 817C4FE
    .string "I love BUG POKéMON.\n"
    .string "That's why I'm here all the time.\p"
    .string "Am I the only girl like that?$"

SixIsland_PatternBush_Text_JoanaDefeat:: @ 817C552
    .string "I lost, but I'm still laughing.\n"
    .string "Am I the only girl like that?$"

SixIsland_PatternBush_Text_JoanaPostBattle:: @ 817C590
    .string "I'm going to keep on collecting\n"
    .string "BUG POKéMON.\p"
    .string "Am I the only girl like that?$"

SixIsland_PatternBush_Text_RileyIntro:: @ 817C5DB
    .string "This is a good spot.\n"
    .string "I'll pitch my tent here.$"

SixIsland_PatternBush_Text_RileyDefeat:: @ 817C609
    .string "Wimped out…$"

SixIsland_PatternBush_Text_RileyPostBattle:: @ 817C615
    .string "I'm going to observe the night sky\n"
    .string "here.$"

SixIsland_PatternBush_Text_MarcyIntro:: @ 817C63E
    .string "Oh, yuck!\n"
    .string "I think a bug stung me!$"

SixIsland_PatternBush_Text_MarcyDefeat:: @ 817C660
    .string "It wasn't a bug.\n"
    .string "I cut my shin on some grass.$"

SixIsland_PatternBush_Text_MarcyPostBattle:: @ 817C68E
    .string "A little cut like that…\n"
    .string "A little spit's enough to cure it!$"

SixIsland_PatternBush_Text_LaytonIntro:: @ 817C6C9
    .string "Have you noticed something odd\n"
    .string "about these parts?$"

SixIsland_PatternBush_Text_LaytonDefeat:: @ 817C6FB
    .string "Have you taken a good look around\n"
    .string "your feet?$"

SixIsland_PatternBush_Text_LaytonPostBattle:: @ 817C728
    .string "There are places here in PATTERN\n"
    .string "BUSH where grass won't grow.\p"
    .string "What could be the cause of such\n"
    .string "a phenomenon?$"

