SilphCo_10F_Text_GruntIntro:: @ 8176CED
    .string "Welcome to 10F!\n"
    .string "So good of you to join me!$"

SilphCo_10F_Text_GruntDefeat:: @ 8176D18
    .string "I'm stunned!$"

SilphCo_10F_Text_GruntPostBattle:: @ 8176D25
    .string "Nice try, but the boardroom is up\n"
    .string "one more floor.$"

SilphCo_10F_Text_TravisIntro:: @ 8176D57
    .string "Enough of your silly games!$"

SilphCo_10F_Text_TravisDefeat:: @ 8176D73
    .string "No continues left!$"

SilphCo_10F_Text_TravisPostBattle:: @ 8176D86
    .string "Are you satisfied with beating me?\n"
    .string "Then go on home!$"

SilphCo_10F_Text_WaaaImScared:: @ 8176DBA
    .string "Waaaaa!\n"
    .string "I'm scared!$"

SilphCo_10F_Text_KeepMeCryingASecret:: @ 8176DCE
    .string "About me crying…\n"
    .string "Please keep it a secret.$"

SilphCo_10F_Text_FloorSign:: @ 8176DF8
    .string "SILPH CO. HEAD OFFICE\n"
    .string "10F$"

