# 1 "data/maps/SSAnne_1F_Room1/scripts.pory"

# 2 "data/maps/SSAnne_1F_Room1/scripts.pory"
SSAnne_1F_Room1_MapScripts::
# 3 "data/maps/SSAnne_1F_Room1/scripts.pory"
	.byte 0
# 4 "data/maps/SSAnne_1F_Room1/scripts.pory"

# 5 "data/maps/SSAnne_1F_Room1/scripts.pory"
SSAnne_1F_Room1_EventScript_Gentleman::
# 6 "data/maps/SSAnne_1F_Room1/scripts.pory"
	msgbox SSAnne_1F_Room1_Text_ImAGlobalPoliceAgent, MSGBOX_NPC
# 7 "data/maps/SSAnne_1F_Room1/scripts.pory"
	end
