PalletTown_PlayersHouse_1F_Text_AllKidsLeaveOakLookingForYou::
    .string "En fin...\p"
    .string "Tod{OA}s los muchach{OA}s se van de casa.\n"
    .string "¡Así es la vida!\p"
    .string "¡Ah si!\p"
    .string "El {SHADOW DYNAMIC_COLOR4}PROF. OAK{SHADOW LIGHT_GRAY} quería verte.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "¡{SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY}!\p"
    .string "Deberías tomarte un descanso.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "¡Muy bien! ¡Tú y tus {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}\n"
    .string "están en plena forma!\p"
    .string "¡Cuidate!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "Hay una película en la TV...\p"
    .string "Cuatro chicos caminan por unas\n"
    .string "vías del tren...$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "Están dando una película...\p"
    .string "Sale una chica con coletas andando\n"
    .string "por una calle empedrada...$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Oops, wrong side…$"

