gUnknown_818D2F0:: @ 818D2F0
    .string "MOM: …Right.\n"
    .string "All boys leave home someday.\l"
    .string "It said so on TV.\p"
    .string "Oh, yes. PROF. OAK, next door, was\n"
    .string "looking for you.$"

gUnknown_818D360:: @ 818D360
    .string "MOM: …Right.\n"
    .string "All girls dream of traveling.\l"
    .string "It said so on TV.\p"
    .string "Oh, yes. PROF. OAK, next door, was\n"
    .string "looking for you.$"

gUnknown_818D3D1:: @ 818D3D1
    .string "MOM: {PLAYER}!\n"
    .string "You should take a quick rest.$"

gUnknown_818D3F8:: @ 818D3F8
    .string "MOM: Oh, good! You and your\n"
    .string "POKéMON are looking great.\l"
    .string "Take care now!$"

gUnknown_818D43E:: @ 818D43E
    .string "There's a movie on TV.\n"
    .string "Four boys are walking on railroad\l"
    .string "tracks.\p"
    .string "…I better go, too.$"

gUnknown_818D492:: @ 818D492
    .string "There's a movie on TV.\n"
    .string "A girl with her hair in pigtails is\l"
    .string "walking up a brick road.\p"
    .string "…I better go, too.$"

gUnknown_818D4F9:: @ 818D4F9
    .string "Oops, wrong side…$"

