#ifndef GUARD_FAME_CHECKER_H
#define GUARD_FAME_CHECKER_H

#include "main.h"

enum {
    FAMECHECKER_OAK,
    FAMECHECKER_DAISY,
    FAMECHECKER_BROCK,
    FAMECHECKER_MISTY,
    FAMECHECKER_LTSURGE,
    FAMECHECKER_ERIKA,
    FAMECHECKER_KOGA,
    FAMECHECKER_SABRINA,
    FAMECHECKER_BLAINE,
    FAMECHECKER_LORELEI,
    FAMECHECKER_BRUNO,
    FAMECHECKER_AGATHA,
    FAMECHECKER_LANCE,
    FAMECHECKER_BILL,
    FAMECHECKER_MRFUJI,
    FAMECHECKER_GIOVANNI
};

void ResetFameChecker(void);
void UseFameChecker(MainCallback savedCallback);

#endif //GUARD_FAME_CHECKER_H
