#ifndef GUARD_FIELD_WEATHER_EFFECTS_H
#define GUARD_FIELD_WEATHER_EFFECTS_H

bool8 Ash_Finish(void);
bool8 Bubbles_Finish(void);
bool8 Clouds_Finish(void);
bool8 Fog1_Finish(void);
bool8 Fog2_Finish(void);
bool8 LightRain_Finish(void);
bool8 Rain_Finish(void);
bool8 Sandstorm_Finish(void);
bool8 Snow_Finish(void);
bool8 sub_807B434(void);
bool8 sub_807B6BC(void);
bool8 sub_807D8D0(void);
void Ash_InitAll(void);
void Ash_InitVars(void);
void Ash_Main(void);
void Bubbles_InitAll(void);
void Bubbles_InitVars(void);
void Bubbles_Main(void);
void Clouds_InitAll(void);
void Clouds_InitVars(void);
void Clouds_Main(void);
void Drought_InitAll(void);
void Drought_InitVars(void);
void Drought_Main(void);
void Fog1_InitAll(void);
void Fog1_InitVars(void);
void Fog1_Main(void);
void Fog2_InitAll(void);
void Fog2_InitVars(void);
void Fog2_Main(void);
void LightRain_InitAll(void);
void LightRain_InitVars(void);
void LightRain_Main(void);
void Rain_Main(void);
void Sandstorm_InitAll(void);
void Sandstorm_InitVars(void);
void Sandstorm_Main(void);
void Snow_InitAll(void);
void Snow_InitVars(void);
void Weather11_InitAll(void);
void Weather11_InitVars(void);
void Weather2_InitAll(void);
void Weather2_InitVars(void);
void nullsub_48(void);
void nullsub_49(void);
void snowflakes_progress2(void);
void sub_807C2E4(void);
void sub_807C358(void);
void sub_807C388(void);
void sub_807C3F4(void);

#endif //GUARD_FIELD_WEATHER_EFFECTS_H
