RocketHideout_B3F_MapScripts:: @ 81612B9
	.byte 0

RocketHideout_B3F_EventScript_1612BA:: @ 81612BA
	trainerbattle_single TRAINER_TEAM_ROCKET_GRUNT_14, Text_17511A, Text_17514A
	msgbox gUnknown_817515B, MSGBOX_AUTOCLOSE
	end

RocketHideout_B3F_EventScript_1612D1:: @ 81612D1
	trainerbattle_single TRAINER_TEAM_ROCKET_GRUNT_15, Text_17519E, Text_1751CE
	msgbox gUnknown_81751E0, MSGBOX_AUTOCLOSE
	end
