SaffronCity_PokemonCenter_1F_Text_GrowthRatesDifferBySpecies:: @ 819C023
    .string "Pokémon growth rates differ from\n"
    .string "species to species.$"

SaffronCity_PokemonCenter_1F_Text_SilphCoVictimOfFame:: @ 819C058
    .string "Silph Co. is widely known to all.\p"
    .string "It's a victim of its own fame - it\n"
    .string "attracted Team Rocket.$"

SaffronCity_PokemonCenter_1F_Text_GreatIfEliteFourCameBeatRockets:: @ 819C0B4
    .string "Sigh…\n"
    .string "Wouldn't this be great?\p"
    .string "If the Elite Four came and\n"
    .string "stomped Team Rocket?$"

SaffronCity_PokemonCenter_1F_Text_TeamRocketTookOff:: @ 819C102
    .string "Team Rocket took off!\n"
    .string "We can go out safely again!\l"
    .string "That's great!$"

