gUnknown_819C023:: @ 819C023
    .string "POKéMON growth rates differ from\n"
    .string "species to species.$"

gUnknown_819C058:: @ 819C058
    .string "SILPH CO. is widely known to all.\p"
    .string "It's a victim of its own fame - it\n"
    .string "attracted TEAM ROCKET.$"

gUnknown_819C0B4:: @ 819C0B4
    .string "Sigh…\n"
    .string "Wouldn't this be great?\p"
    .string "If the ELITE FOUR came and\n"
    .string "stomped TEAM ROCKET?$"

gUnknown_819C102:: @ 819C102
    .string "TEAM ROCKET took off!\n"
    .string "We can go out safely again!\l"
    .string "That's great!$"

