Route16_House_EventObjects:
	object_event 1, 23, 0, 4, 0, 2, 0, 3, 2, 17, 0, 0, 0, 0, 0, Route16_House_EventScript_17014F, 0, 0, 0
	object_event 2, 133, 0, 9, 0, 3, 0, 3, 2, 17, 0, 0, 0, 0, 0, Route16_House_EventScript_1701AF, 0, 0, 0

Route16_House_MapWarps:
	warp_def 3, 7, 3, 0, 802
	warp_def 4, 7, 3, 0, 802
	warp_def 5, 7, 3, 0, 802

Route16_House_MapEvents::
	map_events Route16_House_EventObjects, Route16_House_MapWarps, 0x0, 0x0
