gUnknown_819F851:: @ 819F851
    .string "Oh, dear.\n"
    .string "You've found my secret retreat.\p"
    .string "Please don't tell anyone I'm here.\n"
    .string "I'll make it up to you with this!$"

gUnknown_819F8C0:: @ 819F8C0
    .string "{PLAYER} received HM02\n"
    .string "from the girl.$"

gUnknown_819F8E0:: @ 819F8E0
    .string "HM02 is FLY.\n"
    .string "It's a wonderfully convenient move.\p"
    .string "Please, put it to good use.$"

gUnknown_819F92D:: @ 819F92D
    .string "You don't have any room for this.$"

gUnknown_819F94F:: @ 819F94F
    .string "FEAROW: Kyueen!$"

