Route16_House_Text_FoundMySecretRetreat::
    .string "Oh, dear.\n"
    .string "You've found my secret retreat.\p"
    .string "Please don't tell anyone I'm here.\n"
    .string "I'll make it up to you with this!$"

Route16_House_Text_ReceivedHM02FromGirl::
    .string "{PLAYER} received HM02\n"
    .string "from the girl.$"

Route16_House_Text_ExplainHM02::
    .string "HM02 is FLY.\n"
    .string "It's a wonderfully convenient move.\p"
    .string "Please, put it to good use.$"

Route16_House_Text_DontHaveAnyRoomForThis::
    .string "You don't have any room for this.$"

Route16_House_Text_Fearow::
    .string "FEAROW: Kyueen!$"

