PokemonTower_1F_EventObjects:
	object_event 1, 48, 0, 18, 0, 13, 0, 3, 7, 17, 0, 0, 0, 0, 0, PokemonTower_1F_EventScript_16327C, 0, 0, 0
	object_event 2, 58, 0, 18, 0, 7, 0, 3, 9, 17, 0, 0, 0, 0, 0, PokemonTower_1F_EventScript_16323F, 0, 0, 0
	object_event 3, 28, 0, 15, 0, 6, 0, 3, 7, 17, 0, 0, 0, 0, 0, PokemonTower_1F_EventScript_163248, 0, 0, 0
	object_event 4, 31, 0, 7, 0, 8, 0, 3, 2, 17, 0, 0, 0, 0, 0, PokemonTower_1F_EventScript_16325A, 0, 0, 0
	object_event 5, 30, 0, 8, 0, 12, 0, 3, 2, 34, 0, 0, 0, 0, 0, PokemonTower_1F_EventScript_163251, 0, 0, 0

PokemonTower_1F_MapWarps:
	warp_def 10, 19, 3, 0, 772
	warp_def 11, 18, 3, 0, 772
	warp_def 12, 19, 3, 0, 772
	warp_def 18, 9, 3, 1, 345

PokemonTower_1F_MapEvents::
	map_events PokemonTower_1F_EventObjects, PokemonTower_1F_MapWarps, 0x0, 0x0
