PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .string "Pokémon Tower was erected in the\n"
    .string "memory of Pokémon that died.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "Did you come to pay respects?\p"
    .string "Bless your Pokémon-loving heart,\n"
    .string "son.$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "Did you come to pay respects?\p"
    .string "Bless your Pokémon-loving heart,\n"
    .string "girl.$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "I came to pray for my dearly\n"
    .string "departed Clefairy.\p"
    .string "Sniff!\n"
    .string "I'm awash in tears…$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .string "My Growlithe…\n"
    .string "Why did you die?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .string "I am a Channeler.\p"
    .string "There are spirits up to mischief.\n"
    .string "I sense them high in the Tower.$"

