# 1 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"

# 2 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
FuchsiaCity_SafariZone_Office_MapScripts::
# 3 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	.byte 0
# 4 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"

# 5 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
FuchsiaCity_SafariZone_Office_EventScript_Worker1::
# 6 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	msgbox FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke, MSGBOX_NPC
# 7 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	end
# 8 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"

# 9 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
FuchsiaCity_SafariZone_Office_EventScript_Worker2::
# 10 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	msgbox FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable, MSGBOX_NPC
# 11 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	end
# 12 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"

# 13 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
FuchsiaCity_SafariZone_Office_EventScript_Worker3::
# 14 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	msgbox FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden, MSGBOX_NPC
# 15 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	end
# 16 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"

# 17 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
FuchsiaCity_SafariZone_Office_EventScript_Worker4::
# 18 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	msgbox FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone, MSGBOX_NPC
# 19 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	end
