FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
    .string "We nicknamed the WARDEN\n"
    .string "“SLOWPOKE.”\p"
    .string "You know, he has that vacant look\n"
    .string "like a SLOWPOKE.$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
    .string "WARDEN SLOWPOKE is very\n"
    .string "knowledgeable about POKéMON.\p"
    .string "He even has some fossils of rare,\n"
    .string "extinct POKéMON.$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
    .string "WARDEN SLOWPOKE came in, but\n"
    .string "I couldn't understand him.\p"
    .string "I think he's got a speech problem!$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
    .string "WARDEN SLOWPOKE is running a\n"
    .string "promotion campaign right now.\p"
    .string "Try to get to the farthest corner\n"
    .string "of the SAFARI ZONE.\p"
    .string "If you can make it, you'll win a\n"
    .string "very convenient prize.$"

