# 1 "data/maps/OneIsland_House2/scripts.pory"

# 2 "data/maps/OneIsland_House2/scripts.pory"
OneIsland_House2_MapScripts::
# 3 "data/maps/OneIsland_House2/scripts.pory"
	.byte 0
# 4 "data/maps/OneIsland_House2/scripts.pory"

# 5 "data/maps/OneIsland_House2/scripts.pory"
OneIsland_House2_EventScript_Lass::
# 6 "data/maps/OneIsland_House2/scripts.pory"
	msgbox OneIsland_House2_Text_IWantToStayHereForever, MSGBOX_NPC
# 7 "data/maps/OneIsland_House2/scripts.pory"
	end
