Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .string "The types of POKéMON match up\n"
    .string "differently with each other.\p"
    .string "Every type is stronger than some\n"
    .string "types and weaker than others.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .string "A NUGGET is totally useless.\n"
    .string "So I sold it for ¥5000.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .string "I heard that ghosts haunt\n"
    .string "LAVENDER TOWN.$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
    .string "I'm one of PROF. OAK's RICH AIDES.\n"
    .string "So, {PLAYER}, let me ask you...\p"
    .string "Have you gathered data on at least\n"
    .string "40 kinds of POKéMON?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .string "Congratulations, here you go!$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
    .string "{PLAYER} received ¥10,000\n"
    .string "from the RICH AIDE.$"

Route10_PokemonCenter_1F_Text_ExplainEverstone::
    .string "Man, am I rich or what?!$"

