SixIsland_Mart_EventObjects:
	object_event 1, 68, 0, 2, 0, 3, 0, 0, 10, 17, 0, 0, 0, 0, 0, SixIsland_Mart_EventScript_171E66, 0, 0, 0
	object_event 2, 35, 0, 8, 0, 3, 0, 3, 2, 17, 0, 0, 0, 0, 0, SixIsland_Mart_EventScript_1ACFEF, 0, 0, 0
	object_event 3, 40, 0, 7, 0, 7, 0, 3, 2, 17, 0, 0, 0, 0, 0, SixIsland_Mart_EventScript_171EA0, 0, 0, 0

SixIsland_Mart_MapWarps:
	warp_def 4, 7, 3, 3, 786

SixIsland_Mart_MapEvents::
	map_events SixIsland_Mart_EventObjects, SixIsland_Mart_MapWarps, 0x0, 0x0
