SixIsland_Mart_Text_AgathaOldestEverEliteFourMember:: @ 81A41CA
    .string "Play with Pokémon lots and live\n"
    .string "a long life!\p"
    .string "Take Agatha, for example.\p"
    .string "She set a record for being the\n"
    .string "oldest-ever Elite Four member.\p"
    .string "She spurs me to do bigger things.$"

SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter:: @ 81A4271
    .string "I should buy some Mail and write\n"
    .string "him a letter…$"

