SSAnne_B1F_Room2_EventObjects:
	object_event 1, 62, 0, 3, 0, 5, 0, 3, 1, 17, 0, 1, 0, 1, 0, SSAnne_B1F_Room2_EventScript_160D77, 0, 0, 0
	object_event 2, 92, 0, 3, 0, 2, 0, 3, 8, 17, 0, 0, 0, 0, 0, SSAnne_B1F_Room2_EventScript_1BE685, 359, 0, 0

SSAnne_B1F_Room2_MapWarps:
	warp_def 4, 7, 3, 2, 264

SSAnne_B1F_Room2_MapEvents::
	map_events SSAnne_B1F_Room2_EventObjects, SSAnne_B1F_Room2_MapWarps, 0x0, 0x0
