CeruleanCity_Text_RivalIntro::
.string "{RIVAL}: ¡Hey, {PLAYER}!\p"
.string "¿Aún te andas quedando atrás\n"
.string "por aquí?\p"
.string "¡A mí me va genial! Atrapé un montón\n"
.string "de POKéMON fuertes e inteligentes.\p"
.string "A ver, déjame ver qué atrapaste,\n"
.string "¡{PLAYER}!$"

CeruleanCity_Text_RivalDefeat::
.string "¡OYE!\n"
.string "¡TÓMALO CON CALMA!\l"
.string "¡YA GANASTE!$"

CeruleanCity_Text_RivalPostBattle::
.string "{RIVAL}: Oye, ¿adivina qué?\p"
.string "Fui con BILL y me mostró\n"
.string "sus raros POKéMON.\p"
.string "¡Eso añadió muchas páginas a mi\n"
.string "POKéDEX!\p"
.string "Después de todo, BILL es famoso\n"
.string "mundialmente como un POKéMANÍACO.\p"
.string "También inventó el Sistema de\n"
.string "Almacenamiento en PC.\p"
.string "Ya que usas su sistema,\n"
.string "deberías ir a agradecerle.\p"
.string "Bueno, será mejor que siga mi camino.\n"
.string "¡Hasta luego!$"

CeruleanCity_Text_OhRightLittlePresentAsFavor::
.string "Ah, claro.\p"
.string "Me das un poco de pena, en serio.\n"
.string "Siempre vas detrás de mí.\p"
.string "Así que toma, te daré un pequeño\n"
.string "regalo como favor.$"

CeruleanCity_Text_ExplainFameCheckerSmellYa::
.string "Un chismoso como tú....\n"
.string "Eso te viene perfecto.\p"
.string "Yo no lo necesito porque no\n"
.string "me importan los demás.\p"
.string "Bien, esta vez sí me voy.\n"
.string "¡Hasta luego!$"

@ RB translation: "¡Je! ¡No eres rival para mi genio!"
CeruleanCity_Text_RivalVictory::
.string "¡Je!\n"
.string "¡No eres rival para mi genio!$"

CeruleanCity_Text_GruntIntro::
.string "¡Oye! ¡Fuera!\n"
.string "¡Este no es tu patio!\p"
.string "....¿Eh?\n"
.string "¿Yo?\p"
.string "¡Soy un transeúnte inocente!\n"
.string "¿No me crees?{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

CeruleanCity_Text_GruntDefeat::
.string "RECLUTA: ¡ALTO! ¡ME RINDO!\n"
.string "¡ME IRÉ EN SILENCIO!$"

CeruleanCity_Text_OkayIllReturnStolenTM::
.string "....Está bien.\n"
.string "Devolveré la MT que robé.$"

CeruleanCity_Text_RecoveredTM28FromGrunt::
.string "{PLAYER} recuperó la MT28 del\n"
.string "RECLUTA del TEAM ROCKET.$"

CeruleanCity_Text_BetterGetMovingBye::
.string "Será mejor que me vaya.\n"
.string "¡Adiós!$"

CeruleanCity_Text_MakeRoomForThisCantRun::
.string "¡Haz espacio para esto!\n"
.string "¡No puedo huir hasta dártelo!$"


@pendiente A mayuscula
CeruleanCity_Text_TrainerLifeIsToughIsntIt::
.string "¿También eres {SHADOW DYNAMIC_COLOR4}ENTRENADOR{A}{SHADOW LIGHT_GRAY}?\p"
.string "Coleccionar, luchar...\n"
.string "Es una vida dura, ¿no?$"

CeruleanCity_Text_YouCanCutDownSmallTrees::
.string "¿Sabías que puedes CORTAR los\n"
.string "árboles pequeños?\p"
.string "Incluso el arbolito frente a la\n"
.string "tienda se puede CORTAR.\p"
.string "Aunque creo que hay otra forma de\n"
.string "rodearlo.$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree::
.string "Si ese {SHADOW DYNAMIC_COLOR4}SLOWBRO{SHADOW LIGHT_GRAY} no estuviera allí,\n"
.string "podrías {SHADOW DYNAMIC_COLOR4}CORTAR{SHADOW LIGHT_GRAY} el arbolito.\p"
.string "Así podrías llegar al otro lado.\p"
.string "Aunque creo que hay otra forma de\n"
.string "rodearlo.$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
.string "¿Estás haciendo una enciclopedia de\n"
.string "{SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}?\p"
.string "Eso suena divertido.$"

CeruleanCity_Text_PeopleHereWereRobbed::
.string "La gente de aquí fue robada.\p"
.string "¡Es obvio que el {SHADOW DYNAMIC_COLOR4}EQUIPO ROCKET{SHADOW LIGHT_GRAY} está\n"
.string "detrás de este vil crimen!\p"
.string "¡Hasta nuestra {SHADOW DYNAMIC_COLOR4}FUERZA POLICIAL{SHADOW LIGHT_GRAY} tiene\n"
.string "problemas con esos villanos!$"

CeruleanCity_Text_SlowbroUseSonicboom::
.string "¡Vamos, {SHADOW DYNAMIC_COLOR4}SLOWBRO{SHADOW LIGHT_GRAY}!\n"
.string "¡Usa {SHADOW DYNAMIC_COLOR4}SONICBOOM{SHADOW LIGHT_GRAY}!$"

CeruleanCity_Text_SlowbroPayAttention::
.string "¡Vamos, {SHADOW DYNAMIC_COLOR4}SLOWBRO{SHADOW LIGHT_GRAY}, pon atención!$"

CeruleanCity_Text_SlowbroPunch::
.string "¡{SHADOW DYNAMIC_COLOR4}SLOWBRO{SHADOW LIGHT_GRAY}, da un puñetazo!$"

CeruleanCity_Text_NoYouBlewItAgain::
.string "¡No!\n"
.string "¡La arruinaste otra vez!$"

CeruleanCity_Text_SlowbroWithdraw::
.string "¡{SHADOW DYNAMIC_COLOR4}SLOWBRO{SHADOW LIGHT_GRAY}, {SHADOW DYNAMIC_COLOR4}REFUGIO{SHADOW LIGHT_GRAY}!$"

CeruleanCity_Text_HardToControlMonsObedience::
.string "¡No! ¡Eso está mal!\n"
.string "¡Es difícil controlar a los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}!\p"
.string "La obediencia de tus {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} depende\n"
.string "de tus habilidades como {SHADOW DYNAMIC_COLOR4}ENTRENADOR{SHADOW LIGHT_GRAY}.$"

CeruleanCity_Text_SlowbroTookSnooze::
.string "{SHADOW DYNAMIC_COLOR4}SLOWBRO{SHADOW LIGHT_GRAY} se echó una siesta....$"

CeruleanCity_Text_SlowbroLoafingAround::
.string "{SHADOW DYNAMIC_COLOR4}SLOWBRO{SHADOW LIGHT_GRAY} está holgazaneando....$"

CeruleanCity_Text_SlowbroTurnedAway::
.string "{SHADOW DYNAMIC_COLOR4}SLOWBRO{SHADOW LIGHT_GRAY} se dio la vuelta....$"

CeruleanCity_Text_SlowbroIgnoredOrders::
.string "{SHADOW DYNAMIC_COLOR4}SLOWBRO{SHADOW LIGHT_GRAY} ignoró las órdenes....$"

CeruleanCity_Text_WantBrightRedBicycle::
.string "Quiero una bicicleta roja brillante.\p"
.string "La mantendré en casa para que no\n"
.string "se ensucie.$"

CeruleanCity_Text_ThisIsCeruleanCave::
.string "Esta es la CUEVA CELESTE.\p"
.string "Dentro viven POKéMON terriblemente\n"
.string "fuertes.\p"
.string "Se necesita un ENTRENADOR muy especial\n"
.string "para que lo dejen entrar.\p"
.string "Para empezar, tendrías que ser lo\n"
.string "suficientemente fuerte como para ser el\l"
.string "CAMPEÓN de la LIGA POKéMON.\p"
.string "Y además, tendrías que haber\n"
.string "logrado un gran mérito.$"

CeruleanCity_Text_CitySign::
.string "{SHADOW DYNAMIC_COLOR4}CIUDAD CELESTE{SHADOW LIGHT_GRAY}\p"
.string "La rodea una misteriosa aura\n"
.string "azul$"

CeruleanCity_Text_TrainerTipsHeldItems::
.string "{SHADOW DYNAMIC_COLOR4}CONSEJO ENTRENADOR{SHADOW LIGHT_GRAY}\p"
.string "Un {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} puede llevar un objeto.\p"
.string "Algunos objetos incluso pueden\n"
.string "ser usados en combate por el\l"
.string "{SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} que lo lleva.$"

CeruleanCity_Text_BikeShopSign::
.string "{SHADOW DYNAMIC_COLOR4}TIENDA DE BICICLETAS{SHADOW LIGHT_GRAY}\n"
.string "¡Hierba y cuevas sin esfuerzo!$"

CeruleanCity_Text_GymSign::
.string "{SHADOW DYNAMIC_COLOR4}GIMNASIO POKéMON DE CIUDAD CELESTE{SHADOW LIGHT_GRAY}\n"
.string "{SHADOW DYNAMIC_COLOR4}LÍDER: {SHADOW DYNAMIC_COLOR4}MISTY{SHADOW LIGHT_GRAY}\l"
.string "¡La sirena marimacho!$"

CeruleanCity_Text_WinBattlesOnBridgeGetPrize::
.string "{SHADOW DYNAMIC_COLOR4}CIUDAD CELESTE{SHADOW LIGHT_GRAY} es famosa por su\n"
.string "hermoso puente al norte.\p"
.string "Lo llaman {SHADOW DYNAMIC_COLOR4}PUENTE PEPITA{SHADOW LIGHT_GRAY}.\p"
.string "¡Dicen que si lo cruzas, te esperan\n"
.string "grandes desafíos!$"

CeruleanCity_Text_NuggetBridgeHoldsGreatChallenges::
.string "¡A veces veo a {SHADOW DYNAMIC_COLOR4}ENTRENADORES{SHADOW LIGHT_GRAY}\n"
.string "peleando en el puente del norte!\p"
.string "Dicen que si ganas todas las\n"
.string "batallas, te dan un premio.$"

CeruleanCity_Text_MistyIsStrongestWaterTypeLeader::
.string "¿Ves ese gran edificio?\n"
.string "Es el {SHADOW DYNAMIC_COLOR4}GIMNASIO{SHADOW LIGHT_GRAY} de {SHADOW DYNAMIC_COLOR4}MISTY{SHADOW LIGHT_GRAY}.\p"
.string "Ella es la {SHADOW DYNAMIC_COLOR4}LIDER{SHADOW LIGHT_GRAY} más fuerte de toda\n"
.string "la región...\p"
.string "Al menos en cuanto a {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} de\n"
.string "tipo {SHADOW DYNAMIC_COLOR4}AGUA{SHADOW LIGHT_GRAY}.$"

CeruleanCity_Text_Voltorb::
.string "¡Volt!$"

CeruleanCity_Text_Psyduck::
.string "¡Psy!$"