CeruleanCity_Text_RivalIntro:: @ 817EAD7
    .string "{RIVAL}: Yo! {PLAYER}!\p"
    .string "You're still struggling along back\n"
    .string "here?\p"
    .string "I'm doing great! I caught a bunch\n"
    .string "of strong and smart POKéMON!\p"
    .string "Here, let me see what you caught,\n"
    .string "{PLAYER}!$"

CeruleanCity_Text_RivalDefeat:: @ 817EB71
    .string "Hey!\n"
    .string "Take it easy!\l"
    .string "You won already!$"

CeruleanCity_Text_RivalPostBattle:: @ 817EB95
    .string "{RIVAL}: Hey, guess what?\p"
    .string "I went to BILL's and got him to\n"
    .string "show me his rare POKéMON.\p"
    .string "That added a lot of pages to my\n"
    .string "POKéDEX!\p"
    .string "After all, BILL's world famous as a\n"
    .string "POKéMANIAC.\p"
    .string "He invented the POKéMON Storage\n"
    .string "System on PC, too.\p"
    .string "Since you're using his system,\n"
    .string "you should go thank him.\p"
    .string "Well, I better get rolling!\n"
    .string "Smell ya later!$"

CeruleanCity_Text_OhRightLittlePresentAsFavor:: @ 817ECD4
    .string "Oh, yeah, right.\p"
    .string "I feel sorry for you. No, really.\n"
    .string "You're always plodding behind me.\p"
    .string "So here, I'll give you a little\n"
    .string "present as a favor.$"

CeruleanCity_Text_ExplainFameCheckerSmellYa:: @ 817ED5D
    .string "A chatty gossip like you…\n"
    .string "That thing's perfect.\p"
    .string "I don't need it because I don't\n"
    .string "give a hoot about others.\p"
    .string "All right, this time I really am\n"
    .string "gone. Smell ya!$"

@ RB translation: "Heh! You're no match for my genius!"
CeruleanCity_Text_RivalVictory:: @ 817EDF8
    .string "なんたって！\n"
    .string "おれは　てんさい　だからよ！$"

CeruleanCity_Text_GruntIntro:: @ 817EE0E
    .string "Hey! Stay out!\n"
    .string "It's not your yard!\p"
    .string "…Huh?\n"
    .string "Me?\p"
    .string "I'm an innocent bystander!\n"
    .string "Don't you believe me?{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

CeruleanCity_Text_GruntDefeat:: @ 817EE70
    .string "GRUNT: Stop! I give up!\n"
    .string "I'll leave quietly!$"

CeruleanCity_Text_OkayIllReturnStolenTM:: @ 817EE9C
    .string "…Okay.\n"
    .string "I'll return the TM I stole.$"

CeruleanCity_Text_RecoveredTM28FromGrunt:: @ 817EEBF
    .string "{PLAYER} recovered TM28 from\n"
    .string "the TEAM ROCKET GRUNT.$"

CeruleanCity_Text_BetterGetMovingBye:: @ 817EEED
    .string "I better get moving!\n"
    .string "Bye!$"

CeruleanCity_Text_MakeRoomForThisCantRun:: @ 817EF07
    .string "Make room for this!\n"
    .string "I can't run until I give it to you!$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt:: @ 817EF3F
    .string "You're a TRAINER, too?\p"
    .string "Collecting, battling…\n"
    .string "It's a tough life, isn't it?$"

CeruleanCity_Text_YouCanCutDownSmallTrees:: @ 817EF89
    .string "Did you know that you can CUT down\n"
    .string "small trees?\p"
    .string "Even that small tree in front of\n"
    .string "the shop can be CUT down.\p"
    .string "I think there's a way around it,\n"
    .string "though.$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree:: @ 817F01D
    .string "If that SLOWBRO wasn't there, you\n"
    .string "could CUT down the small tree.\p"
    .string "That way, you could get to the\n"
    .string "other side.\p"
    .string "I think there's a way around it,\n"
    .string "though.$"

CeruleanCity_Text_PokemonEncyclopediaAmusing:: @ 817F0B2
    .string "You're making an encyclopedia on\n"
    .string "POKéMON? That sounds amusing.$"

CeruleanCity_Text_PeopleHereWereRobbed:: @ 817F0F1
    .string "The people here were robbed.\p"
    .string "It's obvious that TEAM ROCKET is\n"
    .string "behind this most heinous crime!\p"
    .string "Even our POLICE FORCE has\n"
    .string "trouble with the ROCKETS!$"

CeruleanCity_Text_SlowbroUseSonicboom:: @ 817F183
    .string "Okay! SLOWBRO!\n"
    .string "Use SONICBOOM!$"

CeruleanCity_Text_SlowbroPayAttention:: @ 817F1A1
    .string "Come on, SLOWBRO, pay attention!$"

CeruleanCity_Text_SlowbroPunch:: @ 817F1C2
    .string "SLOWBRO, punch!$"

CeruleanCity_Text_NoYouBlewItAgain:: @ 817F1D2
    .string "No!\n"
    .string "You blew it again!$"

CeruleanCity_Text_SlowbroWithdraw:: @ 817F1E9
    .string "SLOWBRO, WITHDRAW!$"

CeruleanCity_Text_HardToControlMonsObedience:: @ 817F1FC
    .string "No! That's wrong!\n"
    .string "It's so hard to control POKéMON!\p"
    .string "Your POKéMON's obedience depends\n"
    .string "on your abilities as a TRAINER.$"

CeruleanCity_Text_SlowbroTookSnooze:: @ 817F270
    .string "SLOWBRO took a snooze…$"

CeruleanCity_Text_SlowbroLoafingAround:: @ 817F287
    .string "SLOWBRO is loafing around…$"

CeruleanCity_Text_SlowbroTurnedAway:: @ 817F2A2
    .string "SLOWBRO turned away…$"

CeruleanCity_Text_SlowbroIgnoredOrders:: @ 817F2B7
    .string "SLOWBRO ignored orders…$"

CeruleanCity_Text_WantBrightRedBicycle:: @ 817F2CF
    .string "I want a bright red bicycle.\p"
    .string "I'll keep it at home, so it won't\n"
    .string "get dirty.$"

CeruleanCity_Text_ThisIsCeruleanCave:: @ 817F319
    .string "This is CERULEAN CAVE.\p"
    .string "Horribly strong POKéMON live inside\n"
    .string "there.\p"
    .string "It takes a very special TRAINER to\n"
    .string "be allowed inside there.\p"
    .string "You'd have to be strong enough to\n"
    .string "become the POKéMON LEAGUE\l"
    .string "CHAMPION for starters.\p"
    .string "And, you would have to have\n"
    .string "made a great achievement.$"

CeruleanCity_Text_CitySign:: @ 817F420
    .string "CERULEAN CITY\n"
    .string "A Mysterious, Blue Aura Surrounds\l"
    .string "It$"

CeruleanCity_Text_TrainerTipsHeldItems:: @ 817F453
    .string "TRAINER TIPS\p"
    .string "A POKéMON can be made to hold\n"
    .string "an item.\p"
    .string "Some items can even be used by\n"
    .string "the holding POKéMON in battle.$"

CeruleanCity_Text_BikeShopSign:: @ 817F4C5
    .string "Grass and caves handled easily!\n"
    .string "BIKE SHOP$"

CeruleanCity_Text_GymSign:: @ 817F4EF
    .string "CERULEAN CITY POKéMON GYM\n"
    .string "LEADER: MISTY\l"
    .string "The Tomboyish Mermaid!$"

