CeruleanCity_BikeShop_Text_WelcomeToBikeShop:: @ 8192755
    .string "Hi!\n"
    .string "Welcome to our Bike Shop.\p"
    .string "Have we got just the Bike for\n"
    .string "you!$"

CeruleanCity_BikeShop_Text_SorryYouCantAffordIt:: @ 8192796
    .string "Sorry!\n"
    .string "You can't afford it!$"

CeruleanCity_BikeShop_Text_OhBikeVoucherHereYouGo:: @ 81927B2
    .string "Oh, that's…\p"
    .string "A Bike Voucher!\p"
    .string "Okay!\n"
    .string "Here you go!$"

CeruleanCity_BikeShop_Text_ExchangedVoucherForBicycle:: @ 81927E1
    .string "{PLAYER} exchanged the\n"
    .string "Bike Voucher for a Bicycle.$"

CeruleanCity_BikeShop_Text_ThankYouComeAgain:: @ 819280E
    .string "Thank you!\n"
    .string "Come back again sometime!$"

CeruleanCity_BikeShop_Text_HowDoYouLikeNewBicycle:: @ 8192833
    .string "How do you like your new Bicycle?\n"
    .string "Do you like how it rides?\p"
    .string "You can take it out on Cycling\n"
    .string "Road and even into caves!$"

CeruleanCity_BikeShop_Text_MakeRoomForBicycle:: @ 81928A8
    .string "You better make room for your\n"
    .string "Bicycle!$"

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe:: @ 81928CF
    .string "A plain city bike is good enough\n"
    .string "for me.\p"
    .string "After all, you can't put a shopping\n"
    .string "basket on a mountain bike.$"

CeruleanCity_BikeShop_Text_BikesCoolButExpensive:: @ 8192937
    .string "These bikes are cool, but they're\n"
    .string "way expensive!$"

CeruleanCity_BikeShop_Text_WowYourBikeIsCool:: @ 8192968
    .string "Wow.\n"
    .string "Your Bike is really cool!$"

@ Unused
CeruleanCity_BikeShop_Text_GermanFoldableBicyleFinallyOnMarket:: @ 8192987
    .string "ついに　はつばい！\p"
    .string "ドイツ　せい　さいこうきゅう\n"
    .string "おりたたみ　じてんしゃ！$"

CeruleanCity_BikeShop_Text_ShinyNewBicycle:: @ 81929AD
    .string "A shiny new Bicycle!$"

