FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen::
    .string "There are many Pokémon locked\n"
    .string "away in the pen…$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled::
    .string "The pen door is unlocked.\n"
    .string "The Pokémon appear to have fled.$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro::
    .string "Did you come here knowing it's\n"
    .string "Team Rocket's Warehouse?$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat::
    .string "What do you think you're doing?!$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle::
    .string "Team Rocket broke up?\n"
    .string "What planet are you from?$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro::
    .string "Oh, now your Pokémon look strong.\n"
    .string "You're willing to sell them?\p"
    .string "Oh?\n"
    .string "You wanted to battle?$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat::
    .string "Oh, but…\n"
    .string "Too much!$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle::
    .string "We can give you a great price.\n"
    .string "Sell us your Pokémon!$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro::
    .string "I got word about you from the\n"
    .string "others.\p"
    .string "But there's no way a kid like you'd\n"
    .string "know our Boss Giovanni!$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat::
    .string "Don't…you…dare…laugh…$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle::
    .string "Don't mess in the doings of adults,\n"
    .string "you jumped-up pip-squeak!$"

FiveIsland_RocketWarehouse_Text_Admin1Intro::
    .string "I don't know or care if what I'm\n"
    .string "doing is right or wrong…\p"
    .string "I just put my faith in Giovanni\n"
    .string "and do as I am told.$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat::
    .string "I…\n"
    .string "I'm shattered…$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle::
    .string "You're doing things according to\n"
    .string "your beliefs and morals.\p"
    .string "I understand now…$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough::
    .string "I've made it so you can come back\n"
    .string "in through there.\p"
    .string "Why don't you go get rested and\n"
    .string "refreshed for what lies ahead?\p"
    .string "The Admin after me outranks me\n"
    .string "thoroughly as a Trainer.\p"
    .string "You'd better steel yourself for one\n"
    .string "harsh challenge.$"

FiveIsland_RocketWarehouse_Text_Admin2Intro::
    .string "That's quite enough of you \n"
    .string "playing the hero, kid.\p"
    .string "Spreading lies about how Team\n"
    .string "Rocket has disbanded…\p"
    .string "It's such an obvious attempt to\n"
    .string "cause confusion in our ranks.\p"
    .string "Fortunately, we're not so ignorant\n"
    .string "to fall for the lies of a child!\p"
    .string "And now, I'll show you how scary\n"
    .string "an angry adult can be!$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat::
    .string "Urgh…\n"
    .string "You were too strong…\p"
    .string "…\n"
    .string "Th-that's Giovanni's Badge!\p"
    .string "So it's true?\n"
    .string "Team Rocket really has disbanded?$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle::
    .string "We will abandon this Warehouse…\p"
    .string "But don't think this is over.\n"
    .string "I won't let this be the end.\p"
    .string "I will find Giovanni.\n"
    .string "And I will resurrect Team Rocket!\l"
    .string "I will…\p"
    .string "Until then, farewell!$"

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText::
    .string "A report with graphs and text is on\n"
    .string "the PC monitor.\p"
    .string "“The Influence of Magnetic Waves\n"
    .string "on Pokémon Evolution”…\p"
    .string "… … … … … …\p"
    .string "It's too difficult to understand…$"

FiveIsland_RocketWarehouse_Text_GideonIntro::
    .string "I almost managed to sell the\n"
    .string "Sapphire for huge money…\p"
    .string "Then, you just had to come along\n"
    .string "and blow the whole deal apart!\p"
    .string "Fufu… Fufufufu…\n"
    .string "There's no forgiveness for you!$"

FiveIsland_RocketWarehouse_Text_GideonDefeat::
    .string "Gah! Darn!\n"
    .string "Darn! Darn!$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle::
    .string "If I can't sell it, it's worthless!\n"
    .string "Go ahead, take it!$"

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe::
    .string "What do you want now?\n"
    .string "Go on, get lost, leave me be.$"

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair::
    .string "What, you again?\p"
    .string "You… You're not Giovanni's kid,\n"
    .string "are you?\p"
    .string "No, that can't be right!\n"
    .string "Giovanni's kid has red hair.\p"
    .string "You don't have any reasons for\n"
    .string "bugging me. Leave me alone!$"

