CeruleanCity_House3_EventObjects:
	object_event 1, 32, 0, 2, 0, 2, 0, 3, 7, 17, 0, 0, 0, 0, 0, CeruleanCity_House3_EventScript_16A9B1, 0, 0, 0
	object_event 2, 35, 0, 7, 0, 5, 0, 3, 9, 17, 0, 0, 0, 0, 0, CeruleanCity_House3_EventScript_16A9A8, 0, 0, 0

CeruleanCity_House3_MapWarps:
	warp_def 3, 7, 0, 2, 771
	warp_def 4, 7, 0, 2, 771
	warp_def 5, 7, 0, 2, 771

CeruleanCity_House3_MapEvents::
	map_events CeruleanCity_House3_EventObjects, CeruleanCity_House3_MapWarps, 0x0, 0x0
