# 1 "data/maps/CeladonCity_DepartmentStore_1F/scripts.pory"

# 2 "data/maps/CeladonCity_DepartmentStore_1F/scripts.pory"
CeladonCity_DepartmentStore_1F_MapScripts::
# 3 "data/maps/CeladonCity_DepartmentStore_1F/scripts.pory"
	.byte 0
# 4 "data/maps/CeladonCity_DepartmentStore_1F/scripts.pory"

# 5 "data/maps/CeladonCity_DepartmentStore_1F/scripts.pory"
CeladonCity_DepartmentStore_1F_EventScript_Receptionist::
# 6 "data/maps/CeladonCity_DepartmentStore_1F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore, MSGBOX_NPC
# 7 "data/maps/CeladonCity_DepartmentStore_1F/scripts.pory"
	end
# 8 "data/maps/CeladonCity_DepartmentStore_1F/scripts.pory"

# 9 "data/maps/CeladonCity_DepartmentStore_1F/scripts.pory"
CeladonCity_DepartmentStore_1F_EventScript_LayoutSign::
# 10 "data/maps/CeladonCity_DepartmentStore_1F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_1F_Text_FloorDescriptions, MSGBOX_SIGN
# 11 "data/maps/CeladonCity_DepartmentStore_1F/scripts.pory"
	end
# 12 "data/maps/CeladonCity_DepartmentStore_1F/scripts.pory"

# 13 "data/maps/CeladonCity_DepartmentStore_1F/scripts.pory"
CeladonCity_DepartmentStore_1F_EventScript_FloorSign::
# 14 "data/maps/CeladonCity_DepartmentStore_1F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_1F_Text_ServiceCounter, MSGBOX_SIGN
# 15 "data/maps/CeladonCity_DepartmentStore_1F/scripts.pory"
	end
