CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore:: @ 81954DD
    .string "Hello!\n"
    .string "Welcome to CELADON DEPT. STORE.\p"
    .string "The board on the right describes\n"
    .string "the store layout.$"

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions:: @ 8195537
    .string "1F: SERVICE COUNTER\p"
    .string "2F: TRAINER'S MARKET\p"
    .string "3F: TV GAME SHOP\p"
    .string "4F: WISE MAN GIFTS\p"
    .string "5F: DRUGSTORE\p"
    .string "ROOFTOP SQUARE: VENDING MACHINES$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter:: @ 81955B3
    .string "1F: SERVICE COUNTER$"

