@ Unused
FiveIsland_Meadow_Text_DoorNeedsTwoPasswords:: @ 818AB73
    .string "とびらを　あけるには\n"
    .string "パスワードが　2つ　いるようだ$"

FiveIsland_Meadow_Text_EnteredPasswordAnotherNeeded:: @ 818AB8E
    .string "{PLAYER} entered a password.\p"
    .string "“GOLDEEN need log.”\p"
    .string "… …  … …  … …\p"
    .string "Another password is needed to\n"
    .string "open the door…$"

FiveIsland_Meadow_Text_EnteredPasswordDoorOpened:: @ 818ABF4
    .string "{PLAYER} entered two passwords.\p"
    .string "“GOLDEEN need log.”\n"
    .string "“Yes, nah, CHANSEY.”\p"
    .string "… …  … …  … …\p"
    .string "The WAREHOUSE's door opened!$"

FiveIsland_Meadow_Text_WarehouseDoorAlreadyOpen:: @ 818AC62
    .string "The WAREHOUSE's door is already\n"
    .string "open.$"

FiveIsland_Meadow_Text_Rocket1Intro:: @ 818AC88
    .string "This area's strictly off-limits!\n"
    .string "Out, out!$"

FiveIsland_Meadow_Text_Rocket1Defeat:: @ 818ACB3
    .string "Is this for real?$"

FiveIsland_Meadow_Text_Rocket1PostBattle:: @ 818ACC5
    .string "You don't have any business here!\n"
    .string "Go home!$"

FiveIsland_Meadow_Text_Rocket2Intro:: @ 818ACF0
    .string "There's nothing past here except\n"
    .string "our WAREHOUSE.\p"
    .string "So what brings you here?$"

FiveIsland_Meadow_Text_Rocket2Defeat:: @ 818AD39
    .string "That wasn't supposed to happen…$"

FiveIsland_Meadow_Text_Rocket2PostBattle:: @ 818AD59
    .string "You're wanting to know what's inside\n"
    .string "this WAREHOUSE?\p"
    .string "It's better you didn't know.\n"
    .string "For your own sake, I mean.$"

FiveIsland_Meadow_Text_Rocket3Intro:: @ 818ADC6
    .string "You'd be wasting time even if you\n"
    .string "were to get by me.$"

FiveIsland_Meadow_Text_Rocket3Defeat:: @ 818ADFB
    .string "Oh, that makes me furious!$"

FiveIsland_Meadow_Text_Rocket3PostBattle:: @ 818AE16
    .string "You won't be able to get in without\n"
    .string "the passwords anyway.$"

