Text_18AAD5:: @ 818AAD5
    .string "This is an excellent environment\n"
    .string "for raising POKéMON.$"

Text_18AB0B:: @ 818AB0B
    .string "Your POKéMON are growing up\n"
    .string "admirably well!$"

Text_18AB37:: @ 818AB37
    .string "You know, I think you have the\n"
    .string "talent to be a good BREEDER.$"

Text_18AB73:: @ 818AB73
    .string "とびらを　あけるには\n"
    .string "パスワードが　2つ　いるようだ$"

gUnknown_818AB8E:: @ 818AB8E
    .string "{PLAYER} entered a password.\p"
    .string "“GOLDEEN need log.”\p"
    .string "… …  … …  … …\p"
    .string "Another password is needed to\n"
    .string "open the door…$"

Text_18ABF4:: @ 818ABF4
    .string "{PLAYER} entered two passwords.\p"
    .string "“GOLDEEN need log.”\n"
    .string "“Yes, nah, CHANSEY.”\p"
    .string "… …  … …  … …\p"
    .string "The WAREHOUSE's door opened!$"

gUnknown_818AC62:: @ 818AC62
    .string "The WAREHOUSE's door is already\n"
    .string "open.$"

Text_18AC88:: @ 818AC88
    .string "This area's strictly off-limits!\n"
    .string "Out, out!$"

Text_18ACB3:: @ 818ACB3
    .string "Is this for real?$"

gUnknown_818ACC5:: @ 818ACC5
    .string "You don't have any business here!\n"
    .string "Go home!$"

Text_18ACF0:: @ 818ACF0
    .string "There's nothing past here except\n"
    .string "our WAREHOUSE.\p"
    .string "So what brings you here?$"

Text_18AD39:: @ 818AD39
    .string "That wasn't supposed to happen…$"

gUnknown_818AD59:: @ 818AD59
    .string "You're wanting to know what's inside\n"
    .string "this WAREHOUSE?\p"
    .string "It's better you didn't know.\n"
    .string "For your own sake, I mean.$"

Text_18ADC6:: @ 818ADC6
    .string "You'd be wasting time even if you\n"
    .string "were to get by me.$"

Text_18ADFB:: @ 818ADFB
    .string "Oh, that makes me furious!$"

gUnknown_818AE16:: @ 818AE16
    .string "You won't be able to get in without\n"
    .string "the passwords anyway.$"

