SeafoamIslands_B2F_EventObjects:
	object_event 1, 97, 0, 22, 0, 8, 0, 3, 8, 0, 0, 70, 0, 0, 0, SeafoamIslands_B2F_EventScript_1BE11D, 68, 0, 0
	object_event 2, 97, 0, 30, 0, 8, 0, 3, 8, 0, 0, 71, 0, 0, 0, SeafoamIslands_B2F_EventScript_1BE11D, 69, 0, 0
	object_event 3, 92, 0, 18, 0, 15, 0, 3, 8, 17, 0, 0, 0, 0, 0, SeafoamIslands_B2F_EventScript_1BEC0E, 471, 0, 0

SeafoamIslands_B2F_MapWarps:
	warp_def 7, 17, 3, 0, 342
	warp_def 32, 4, 3, 1, 342
	warp_def 31, 17, 4, 2, 342
	warp_def 7, 4, 3, 3, 340
	warp_def 17, 9, 4, 4, 340
	warp_def 25, 19, 3, 5, 340
	warp_def 32, 14, 4, 6, 340
	warp_def 22, 7, 3, 7, 340
	warp_def 29, 8, 3, 8, 340
	warp_def 24, 8, 3, 5, 342
	warp_def 27, 8, 3, 6, 342

SeafoamIslands_B2F_MapEvents::
	map_events SeafoamIslands_B2F_EventObjects, SeafoamIslands_B2F_MapWarps, 0x0, 0x0
