# 1 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"

# 2 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
CeladonCity_DepartmentStore_3F_MapScripts::
# 3 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.byte 0
# 4 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"

# 5 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_CounterTutor::
# 6 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	goto EventScript_CounterTutor
# 7 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	end
# 8 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"

# 9 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_GBAKid1::
# 10 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer, MSGBOX_NPC
# 11 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	end
# 12 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"

# 13 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_GBAKid2::
# 14 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter, MSGBOX_NPC
# 15 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	end
# 16 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"

# 17 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_GBAKid3::
# 18 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade, MSGBOX_NPC
# 19 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	end
# 20 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"

# 21 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_LittleGirl::
# 22 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID, MSGBOX_NPC
# 23 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	end
# 24 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"

# 25 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_SuperNES::
# 26 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_ItsSuperNES, MSGBOX_SIGN
# 27 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	end
# 28 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"

# 29 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_TV1::
# 30 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_AnRPG, MSGBOX_SIGN
# 31 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	end
# 32 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"

# 33 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_TV2::
# 34 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_SportsGame, MSGBOX_SIGN
# 35 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	end
# 36 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"

# 37 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_TV3::
# 38 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_PuzzleGame, MSGBOX_SIGN
# 39 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	end
# 40 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"

# 41 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_TV4::
# 42 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_FightingGame, MSGBOX_SIGN
# 43 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	end
# 44 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"

# 45 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_FloorSign::
# 46 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_TVGameShop, MSGBOX_SIGN
# 47 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	end
# 48 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"

# 49 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
CeladonCity_DepartmentStore_3F_EventScript_Poster::
# 50 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon, MSGBOX_SIGN
# 51 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	end
