CeladonCity_DepartmentStore_3F_MapScripts:: @ 816BB84
	.byte 0

CeladonCity_DepartmentStore_3F_EventScript_16BB85:: @ 816BB85
	goto EventScript_1C4C26
	end

CeladonCity_DepartmentStore_3F_EventScript_16BB8B:: @ 816BB8B
	msgbox gUnknown_81956E9, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_16BB94:: @ 816BB94
	msgbox gUnknown_8195769, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_16BB9D:: @ 816BB9D
	msgbox gUnknown_81957B0, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_16BBA6:: @ 816BBA6
	msgbox gUnknown_8195823, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_16BBAF:: @ 816BBAF
	msgbox gUnknown_8195863, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_16BBB8:: @ 816BBB8
	msgbox gUnknown_8195875, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_16BBC1:: @ 816BBC1
	msgbox gUnknown_8195897, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_16BBCA:: @ 816BBCA
	msgbox gUnknown_81958B8, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_16BBD3:: @ 816BBD3
	msgbox gUnknown_81958D8, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_16BBDC:: @ 816BBDC
	msgbox gUnknown_81958F6, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_16BBE5:: @ 816BBE5
	msgbox gUnknown_8195907, MSGBOX_SIGN
	end
