CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer:: @ 81956E9
    .string "Captured POKéMON are registered\n"
    .string "with an ID No. and the OT.\p"
    .string "OT stands for “Original TRAINER” -\n"
    .string "the TRAINER that caught it first.$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter:: @ 8195769
    .string "All right!\p"
    .string "My buddy's going to trade me his\n"
    .string "KANGASKHAN for my HAUNTER!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade:: @ 81957B0
    .string "Come on, HAUNTER!\p"
    .string "I love HAUNTER!\n"
    .string "I collect them!\p"
    .string "Huh?\p"
    .string "HAUNTER turned into a different\n"
    .string "POKéMON while being traded!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID:: @ 8195823
    .string "You can identify POKéMON you get\n"
    .string "in trades by their ID Numbers.$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES:: @ 8195863
    .string "It's a Super NES.$"

CeladonCity_DepartmentStore_3F_Text_AnRPG:: @ 8195875
    .string "An RPG!\n"
    .string "There's no time for that!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame:: @ 8195897
    .string "A sports game!\n"
    .string "Dad'll like that!$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame:: @ 81958B8
    .string "A puzzle game!\n"
    .string "Looks addictive!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame:: @ 81958D8
    .string "A fighting game!\n"
    .string "Looks tough!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop:: @ 81958F6
    .string "3F: TV GAME SHOP$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon:: @ 8195907
    .string "Red and Green!\n"
    .string "Both are POKéMON!$"

Text_CounterTeach:: @ 8195928
    .string "Oh, hi!\n"
    .string "I finally finished POKéMON.\p"
    .string "Not done yet? How about I teach\n"
    .string "you a good move?\p"
    .string "The move I have in mind is\n"
    .string "COUNTER.\p"
    .string "Not like the one I'm leaning on,\n"
    .string "mind you!$"

Text_CounterDeclined:: @ 81959CC
    .string "You're not interested? Come see\n"
    .string "me if you change your mind.$"

Text_CounterWhichMon:: @ 8195A08
    .string "Which POKéMON should I teach\n"
    .string "COUNTER to?$"

Text_CounterTaught:: @ 8195A31
    .string "Are you using that COUNTER move\n"
    .string "I taught your POKéMON?$"
