CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
    .string "Captured Pokémon are registered\n"
    .string "with an ID No. and the OT.\p"
    .string "OT stands for “Original Trainer” -\n"
    .string "the Trainer that caught it first.$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
    .string "All right!\p"
    .string "My buddy's going to trade me his\n"
    .string "Kangaskhan for my Haunter!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
    .string "Come on, Haunter!\p"
    .string "I love Haunter!\n"
    .string "I collect them!\p"
    .string "Huh?\p"
    .string "Haunter turned into a different\n"
    .string "Pokémon while being traded!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
    .string "You can identify Pokémon you get\n"
    .string "in trades by their ID Numbers.$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
    .string "It's a Super NES.$"

CeladonCity_DepartmentStore_3F_Text_AnRPG::
    .string "An RPG!\n"
    .string "There's no time for that!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame::
    .string "A sports game!\n"
    .string "Dad'll like that!$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
    .string "A puzzle game!\n"
    .string "Looks addictive!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame::
    .string "A fighting game!\n"
    .string "Looks tough!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
    .string "3F: TV Game Shop$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
    .string "Red and Green!\n"
    .string "Both are Pokémon!$"

Text_CounterTeach::
    .string "Oh, hi!\n"
    .string "I finally finished Pokémon.\p"
    .string "Not done yet? How about I teach\n"
    .string "you a good move?\p"
    .string "The move I have in mind is\n"
    .string "Counter.\p"
    .string "Not like the one I'm leaning on,\n"
    .string "mind you!$"

Text_CounterDeclined::
    .string "You're not interested? Come see\n"
    .string "me if you change your mind.$"

Text_CounterWhichMon::
    .string "Which Pokémon should I teach\n"
    .string "Counter to?$"

Text_CounterTaught::
    .string "Are you using that Counter move\n"
    .string "I taught your Pokémon?$"
