Route11_EastEntrance_2F_Text_GiveItemfinderIfCaught30::
    .string "I'm one of PROF. OAK's RICH AIDES.\n"
    .string "So, {PLAYER}, let me ask you...\p"
    .string "Have you gathered data on at least\n"
    .string "30 kinds of POKéMON?$"

Route11_EastEntrance_2F_Text_GreatHereYouGo::
    .string "Congratulations, here you go!$"

Route11_EastEntrance_2F_Text_ReceivedItemfinderFromAide::
    .string "{PLAYER} received ¥30,000\n"
    .string "from the RICH AIDE.$"

Route11_EastEntrance_2F_Text_ExplainItemfinder::
    .string "Man, am I rich or what?!$"

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "A big POKéMON is asleep on a road!$"

Route11_EastEntrance_2F_Text_WhatABreathtakingView::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "What a breathtaking view!$"

Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "To get to LAVENDER TOWN from\n"
    .string "CERULEAN CITY…\p"
    .string "ROCK TUNNEL appears to be a good\n"
    .string "route to take.$"

