PewterCity_House1_EventObjects:
	object_event 1, 30, 0, 1, 0, 2, 0, 3, 7, 17, 0, 0, 0, 0, 0, PewterCity_House1_EventScript_16A71D, 0, 0, 0
	object_event 2, 16, 0, 5, 0, 3, 0, 3, 10, 17, 0, 0, 0, 0, 0, PewterCity_House1_EventScript_16A726, 0, 0, 0
	object_event 3, 123, 0, 6, 0, 3, 0, 3, 9, 17, 0, 0, 0, 0, 0, PewterCity_House1_EventScript_16A736, 0, 0, 0

PewterCity_House1_MapWarps:
	warp_def 3, 7, 0, 4, 770
	warp_def 4, 7, 0, 4, 770
	warp_def 5, 7, 0, 4, 770

PewterCity_House1_MapEvents::
	map_events PewterCity_House1_EventObjects, PewterCity_House1_MapWarps, 0x0, 0x0
