PewterCity_House1_Text_Nidoran::
    .string "Nidoran♂: Bowbow!$"

PewterCity_House1_Text_NidoranSit::
    .string "Nidoran, sit!$"

PewterCity_House1_Text_TradeMonsAreFinicky::
    .string "Our Pokémon's an outsider, so it's\n"
    .string "finicky and hard to handle.\p"
    .string "An outsider is a Pokémon that you\n"
    .string "get in a trade.\p"
    .string "It grows fast, but it may ignore an\n"
    .string "unskilled Trainer in battle.\p"
    .string "If only we had some Badges…$"

