PewterCity_House1_Text_Nidoran::
    .string "{COLOR DARK_GRAY}{SHADOW DYNAMIC_COLOR4}NIDORAN♂:{SHADOW LIGHT_GRAY} Bowbow!$"

PewterCity_House1_Text_NidoranSit::
    .string "{COLOR DARK_GRAY}¡Siéntate, {SHADOW DYNAMIC_COLOR4}NIDORAN{SHADOW LIGHT_GRAY}!$"

PewterCity_House1_Text_TradeMonsAreFinicky::
    .string "{COLOR DARK_GRAY}Nuestro {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} es forastero,\n"
    .string "y es difícil de manejar.\p"
    .string "Un forastero es un {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}\n"
    .string "intercambiado con otro jugador.\p"
    .string "¡Crece deprisa, pero a veces\n"
    .string "novatos en combates!\p"
    .string "¡Ojalá tuviéramos algunas\n"
    .string "{SHADOW DYNAMIC_COLOR4}MEDALLAS{SHADOW LIGHT_GRAY}!$"