PewterCity_House1_Text_Nidoran:: @ 81915BB
    .string "NIDORAN♂: Bowbow!$"

PewterCity_House1_Text_NidoranSit:: @ 81915CD
    .string "NIDORAN, sit!$"

PewterCity_House1_Text_TradeMonsAreFinicky:: @ 81915DB
    .string "Our POKéMON's an outsider, so it's\n"
    .string "finicky and hard to handle.\p"
    .string "An outsider is a POKéMON that you\n"
    .string "get in a trade.\p"
    .string "It grows fast, but it may ignore an\n"
    .string "unskilled TRAINER in battle.\p"
    .string "If only we had some BADGES…$"

