Text_190CD4:: @ 8190CD4
    .string "So, you're here. I'm BROCK.\n"
    .string "I'm PEWTER's GYM LEADER.\p"
    .string "My rock-hard willpower is evident\n"
    .string "even in my POKéMON.\p"
    .string "My POKéMON are all rock hard, and\n"
    .string "have true-grit determination.\p"
    .string "That's right - my POKéMON are all\n"
    .string "the ROCK type!\p"
    .string "Fuhaha! You're going to challenge\n"
    .string "me knowing that you'll lose?\p"
    .string "That's the TRAINER's honor that\n"
    .string "compels you to challenge me.\p"
    .string "Fine, then!\n"
    .string "Show me your best!{PLAY_BGM}{BGM_FRLG_LEADER_EYE}$"

Text_190E4F:: @ 8190E4F
    .string "I took you for granted, and so\n"
    .string "I lost.\p"
    .string "As proof of your victory, I confer\n"
    .string "on you this…the official POKéMON\l"
    .string "LEAGUE BOULDERBADGE.\p"
    .string "{SIZE}Á{PLAYER} received the BOULDERBADGE\n"
    .string "from BROCK!{PAUSE_MUSIC}{PLAY_BGM}{MUS_ME_BACHI}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}\p"
    .string "{SIZE}ÇJust having the BOULDERBADGE makes\n"
    .string "your POKéMON more powerful.\p"
    .string "It also enables the use of the\n"
    .string "move FLASH outside of battle.\p"
    .string "Of course, a POKéMON must know the\n"
    .string "move FLASH to use it.$"

gUnknown_8190FC1:: @ 8190FC1
    .string "Wait!\n"
    .string "Take this with you.$"

gUnknown_8190FDB:: @ 8190FDB
    .string "{PLAYER} received TM39\n"
    .string "from BROCK.$"

gUnknown_8190FF8:: @ 8190FF8
    .string "A TM, Technical Machine, contains a\n"
    .string "technique for POKéMON.\p"
    .string "Using a TM teaches the move it\n"
    .string "contains to a POKéMON.\p"
    .string "A TM is good for only one use.\p"
    .string "So, when you use one, pick the\n"
    .string "POKéMON carefully.\p"
    .string "Anyways…\n"
    .string "TM39 contains ROCK TOMB.\p"
    .string "It hurls boulders at the foe and\n"
    .string "lowers its SPEED.$"

gUnknown_819110F:: @ 819110F
    .string "There are all kinds of TRAINERS in\n"
    .string "this huge world of ours.\p"
    .string "You appear to be very gifted as a\n"
    .string "POKéMON TRAINER.\p"
    .string "So let me make a suggestion.\p"
    .string "Go to the GYM in CERULEAN and test\n"
    .string "your abilities.$"

gUnknown_81911CE:: @ 81911CE
    .string "You don't have room for this.$"

Text_1911EC:: @ 81911EC
    .string "Stop right there, kid!\p"
    .string "You're ten thousand light-years \n"
    .string "from facing BROCK!$"

Text_191237:: @ 8191237
    .string "Darn!\p"
    .string "Light-years isn't time…\n"
    .string "It measures distance!$"

gUnknown_819126B:: @ 819126B
    .string "You're pretty hot.\n"
    .string "…But not as hot as BROCK!$"

gUnknown_8191298:: @ 8191298
    .string "Hiya!\n"
    .string "Do you want to dream big?\p"
    .string "Do you dare to dream of becoming\n"
    .string "the POKéMON champ?\p"
    .string "I'm no TRAINER, but I can advise\n"
    .string "you on how to win.\p"
    .string "Let me take you to the top!$"

gUnknown_819133C:: @ 819133C
    .string "All right!\n"
    .string "Let's get happening!$"

gUnknown_819135C:: @ 819135C
    .string "The first POKéMON out in a match is\n"
    .string "at the left of the POKéMON LIST.\p"
    .string "By changing the order of POKéMON,\n"
    .string "you may gain an advantage.\p"
    .string "Try different orders to suit your\n"
    .string "opponent's party.$"

gUnknown_8191412:: @ 8191412
    .string "It's a free service!\n"
    .string "Let's get happening!$"

gUnknown_819143C:: @ 819143C
    .string "Just as I thought!\n"
    .string "You're POKéMON champ material!$"

gUnknown_819146E:: @ 819146E
    .string "PEWTER POKéMON GYM\n"
    .string "LEADER: BROCK\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

gUnknown_81914A4:: @ 81914A4
    .string "PEWTER POKéMON GYM\n"
    .string "LEADER: BROCK\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

