VermilionCity_PokemonCenter_1F_Text_TrainerMonsStrongerThanWild::
    .string "Even if they are the same level,\n"
    .string "POKéMON can have very different\l"
    .string "stats and abilities.\p"
    .string "A POKéMON raised by a TRAINER is\n"
    .string "stronger than one in the wild.$"

VermilionCity_PokemonCenter_1F_Text_PoisonedMonFaintedWhileWalking::
    .string "My POKéMON was poisoned!\n"
    .string "It fainted while we were walking!$"

VermilionCity_PokemonCenter_1F_Text_AllMonWeakToSpecificTypes::
    .string "It is true that a higher-level\n"
    .string "POKéMON will be more powerful…\p"
    .string "But, all POKéMON will have weak\n"
    .string "points against specific types.\p"
    .string "So, there appears to be no\n"
    .string "universally strong POKéMON.$"

VermilionCity_PokemonCenter_1F_Text_UrgeToBattleSomeoneAgain::
    .string "The urge to battle with someone\n"
    .string "you've tangled with before…\p"
    .string "Have you ever had that urge?\n"
    .string "I'm sure you have.\p"
    .string "I wanted to battle certain people\n"
    .string "again over and over, too.\p"
    .string "So, I've been giving these away.\n"
    .string "Please, take one!$"

VermilionCity_PokemonCenter_1F_Text_UseDeviceForRematches::
    .string "Use that device and you'll find\n"
    .string "TRAINERS looking for a rematch.\p"
    .string "You have to charge its battery to\n"
    .string "use it, though.$"

VermilionCity_PokemonCenter_1F_Text_ExplainVSSeeker::
    .string "How do you use the VS SEEKER?\n"
    .string "There's nothing to it.\p"
    .string "Use it like beep-beep-beep, and\n"
    .string "TRAINERS around you will notice.\p"
    .string "If any TRAINER wants a rematch,\n"
    .string "it will let you know immediately.\p"
    .string "Charge its battery and use it\n"
    .string "while you're on a road.$"
