gUnknown_817DABB:: @ 817DABB
    .string "Those POKé BALLS at your waist!\n"
    .string "You have POKéMON, don't you?\p"
    .string "It's great that you can carry and\n"
    .string "use POKéMON anytime, anywhere.$"

gUnknown_817DB39:: @ 817DB39
    .string "This POKéMON GYM is always closed.\p"
    .string "I wonder who the LEADER is?$"

gUnknown_817DB78:: @ 817DB78
    .string "VIRIDIAN GYM's LEADER returned!$"

gUnknown_817DB98:: @ 817DB98
    .string "You want to know about the two\n"
    .string "kinds of caterpillar POKéMON?$"

gUnknown_817DBD5:: @ 817DBD5
    .string "Oh, okay then!$"

gUnknown_817DBE4:: @ 817DBE4
    .string "CATERPIE has no poison,\n"
    .string "but WEEDLE does.\p"
    .string "Watch that your POKéMON aren't\n"
    .string "stabbed by WEEDLE's POISON STING.$"

gUnknown_817DC4E:: @ 817DC4E
    .string "Oh, Grandpa!\n"
    .string "Don't be so mean!\p"
    .string "I'm so sorry.\n"
    .string "He hasn't had his coffee yet.$"

gUnknown_817DC99:: @ 817DC99
    .string "I go shopping in PEWTER CITY\n"
    .string "occasionally.\p"
    .string "I have to take the winding trail in\n"
    .string "VIRIDIAN FOREST when I go.$"

gUnknown_817DD03:: @ 817DD03
    .string "I absolutely forbid you from\n"
    .string "going through here!\p"
    .string "This is private property!$"

gUnknown_817DD4E:: @ 817DD4E
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "Hm?\n"
    .string "What is that red box you have?\p"
    .string "Ah, so you're working on your\n"
    .string "POKéDEX.\p"
    .string "Then let me give you a word of\n"
    .string "advice.\p"
    .string "Whenever you catch a POKéMON,\n"
    .string "the POKéDEX automatically updates\l"
    .string "its data.\p"
    .string "…You don't know how to catch\n"
    .string "a POKéMON?\p"
    .string "I suppose I had better show you\n"
    .string "then!$"

gUnknown_817DE9B:: @ 817DE9B
    .string "There! Now tell me, that was\n"
    .string "educational, was it not?\p"
    .string "And here, take this, too.$"

gUnknown_817DEEB:: @ 817DEEB
    .string "If there's something you don't\n"
    .string "understand, watch that.\p"
    .string "It will teach you about the basics\n"
    .string "of being a POKéMON TRAINER.$"

gUnknown_817DF61:: @ 817DF61
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "Incidentally, are you filling your\n"
    .string "POKéDEX?\p"
    .string "At first, focus on weakening the\n"
    .string "POKéMON before trying to catch it.$"

gUnknown_817E046:: @ 817E046
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "Incidentally, is my old TEACHY TV\n"
    .string "helping you?$"

gUnknown_817E0EA:: @ 817E0EA
    .string "Wahaha!\n"
    .string "It's my grandson on the show!\p"
    .string "Since he's the one doing the\n"
    .string "teaching, you're bound to learn.$"

gUnknown_817E14E:: @ 817E14E
    .string "Hm… You're too busy to not even\n"
    .string "have the time for TEACHY TV…\p"
    .string "Time is money, and neither should\n"
    .string "be ill spent…$"

gUnknown_817E1BB:: @ 817E1BB
    .string "VIRIDIAN CITY \n"
    .string "The Eternally Green Paradise$"

gUnknown_817E1E7:: @ 817E1E7
    .string "TRAINER TIPS\p"
    .string "Catch POKéMON and expand your\n"
    .string "collection.\p"
    .string "The more you have, the easier it\n"
    .string "is to battle.$"

gUnknown_817E24D:: @ 817E24D
    .string "TRAINER TIPS\p"
    .string "The battle moves of POKéMON are\n"
    .string "limited by their POWER POINTS, PP.\p"
    .string "To replenish PP, rest your tired\n"
    .string "POKéMON at a POKéMON CENTER.$"

gUnknown_817E2DB:: @ 817E2DB
    .string "VIRIDIAN CITY POKéMON GYM$"

gUnknown_817E2F5:: @ 817E2F5
    .string "VIRIDIAN GYM's doors are locked…$"

