ViridianCity_Text_CanCarryMonsAnywhere:: @ 817DABB
    .string "Those Poké Balls at your waist!\n"
    .string "You have Pokémon, don't you?\p"
    .string "It's great that you can carry and\n"
    .string "use Pokémon anytime, anywhere.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs:: @ 817DB39
    .string "This Pokémon Gym is always closed.\p"
    .string "I wonder who the Leader is?$"

ViridianCity_Text_ViridiansGymLeaderReturned:: @ 817DB78
    .string "Viridian Gym's Leader returned!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons:: @ 817DB98
    .string "You want to know about the two\n"
    .string "kinds of caterpillar Pokémon?$"

ViridianCity_Text_OhOkayThen:: @ 817DBD5
    .string "Oh, okay then!$"

ViridianCity_Text_ExplainCaterpieWeedle:: @ 817DBE4
    .string "Caterpie has no poison,\n"
    .string "but Weedle does.\p"
    .string "Watch that your Pokémon aren't\n"
    .string "stabbed by Weedle's Poison Sting.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet:: @ 817DC4E
    .string "Oh, Grandpa!\n"
    .string "Don't be so mean!\p"
    .string "I'm so sorry.\n"
    .string "He hasn't had his coffee yet.$"

ViridianCity_Text_GoShoppingInPewterOccasionally:: @ 817DC99
    .string "I go shopping in Pewter City\n"
    .string "occasionally.\p"
    .string "I have to take the winding trail in\n"
    .string "Viridian Forest when I go.$"

ViridianCity_Text_ThisIsPrivateProperty:: @ 817DD03
    .string "I absolutely forbid you from\n"
    .string "going through here!\p"
    .string "This is private property!$"

ViridianCity_Text_ShowYouHowToCatchMons:: @ 817DD4E
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "Hm?\n"
    .string "What is that red box you have?\p"
    .string "Ah, so you're working on your\n"
    .string "Pokédex.\p"
    .string "Then let me give you a word of\n"
    .string "advice.\p"
    .string "Whenever you catch a Pokémon,\n"
    .string "the Pokédex automatically updates\l"
    .string "its data.\p"
    .string "…You don't know how to catch\n"
    .string "a Pokémon?\p"
    .string "I suppose I had better show you\n"
    .string "then!$"

ViridianCity_Text_ThatWasEducationalTakeThis:: @ 817DE9B
    .string "There! Now tell me, that was\n"
    .string "educational, was it not?\p"
    .string "And here, take this, too.$"

ViridianCity_Text_WatchThatToLearnBasics:: @ 817DEEB
    .string "If there's something you don't\n"
    .string "understand, watch that.\p"
    .string "It will teach you about the basics\n"
    .string "of being a Pokémon Trainer.$"

ViridianCity_Text_WeakenMonsFirstToCatch:: @ 817DF61
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "Incidentally, are you filling your\n"
    .string "Pokédex?\p"
    .string "At first, focus on weakening the\n"
    .string "Pokémon before trying to catch it.$"

ViridianCity_Text_HowsTeachyTVHelping:: @ 817E046
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "Incidentally, is my old Teachy TV\n"
    .string "helping you?$"

ViridianCity_Text_MyGrandsonOnTheShow:: @ 817E0EA
    .string "Wahaha!\n"
    .string "It's my grandson on the show!\p"
    .string "Since he's the one doing the\n"
    .string "teaching, you're bound to learn.$"

ViridianCity_Text_TooBusyForTeachyTV:: @ 817E14E
    .string "Hm… You're too busy to not even\n"
    .string "have the time for Teachy TV…\p"
    .string "Time is money, and neither should\n"
    .string "be ill spent…$"

ViridianCity_Text_CitySign:: @ 817E1BB
    .string "Viridian City \n"
    .string "The Eternally Green Paradise$"

ViridianCity_Text_CatchMonsForEasierBattles:: @ 817E1E7
    .string "Trainer Tips\p"
    .string "Catch Pokémon and expand your\n"
    .string "collection.\p"
    .string "The more you have, the easier it\n"
    .string "is to battle.$"

ViridianCity_Text_MovesLimitedByPP:: @ 817E24D
    .string "Trainer Tips\p"
    .string "The battle moves of Pokémon are\n"
    .string "limited by their Power Points, PP.\p"
    .string "To replenish PP, rest your tired\n"
    .string "Pokémon at a Pokémon Center.$"

ViridianCity_Text_GymSign:: @ 817E2DB
    .string "Viridian City Pokémon Gym$"

ViridianCity_Text_GymDoorsAreLocked:: @ 817E2F5
    .string "Viridian Gym's doors are locked…$"

