ViridianCity_Text_CanCarryMonsAnywhere::
    .string "¿Llevas {SHADOW DYNAMIC_COLOR4}POKé BALLS{SHADOW LIGHT_GRAY}?\n"
    .string "¡Entonces tú tienes {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}!\p"
    .string "¡Es genial poder llevar y usar los\n"
    .string "{SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} en cualquier momento!$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "Este {SHADOW DYNAMIC_COLOR4}GIMNASIO POKéMON{SHADOW LIGHT_GRAY} está\n"
    .string "siempre cerrado...\p"
    .string "Me pregunto quién será su {SHADOW DYNAMIC_COLOR4}LIDER{SHADOW LIGHT_GRAY}.$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "VIRIDIAN GYM's LEADER returned!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "¿Quieres saber algo sobre los dos\n"
    .string "tipo de orugas {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}?$"

ViridianCity_Text_OhOkayThen::
    .string "Vale, pues nada.$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "¡{SHADOW DYNAMIC_COLOR4}CATERPIE{SHADOW LIGHT_GRAY} no tiene veneno,\n"
    .string "pero {SHADOW DYNAMIC_COLOR4}WEEDLE{SHADOW LIGHT_GRAY}, sí!\p"
    .string "¡Cuidado con su {SHADOW DYNAMIC_COLOR4}PICOTAZO\n"
    .string "VENENOSO{SHADOW LIGHT_GRAY}!$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "¡Oh, abuelo!\n"
    .string "¡No seas tan malo!\p"
    .string "Lo siento, todavía no se ha tomado\n"
    .string "su café...$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "¡Cuando voy de compras a\n"
    .string "{SHADOW DYNAMIC_COLOR4}CIUDAD PLATEADA{SHADOW LIGHT_GRAY}, tomo el sinuoso\l"
    .string "camino del {SHADOW DYNAMIC_COLOR4}BOSQUE VERDE{SHADOW LIGHT_GRAY}!$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "¡No puedes pasar por aquí!\p"
    .string "¡{SHADOW DYNAMIC_COLOR4}Es propiedad privada{SHADOW LIGHT_GRAY}!$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "Lo bien que me sienta tomarme\n"
    .string "un café... ¡Me pone de buena ánimo!\p"
    .string "¿Hum?\n"
    .string "¿Y esa caja roja que llevas ahí?\p"
    .string "Así que estás trabajando en tu\n"
    .string "{SHADOW DYNAMIC_COLOR4}POKéDEX{SHADOW LIGHT_GRAY}.\p"
    .string "Pues deja que te diga algo...\p"
    .string "Cuando atrapes un {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY},\n"
    .string "la {SHADOW DYNAMIC_COLOR4}POKéDEX{SHADOW LIGHT_GRAY} actualizará sus datos\l"
    .string "de forma automática.\p"
    .string "Anda, toma esto es para ti...$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "{SHADOW LIGHT_GRAY}Úsala cuando haya alguna cosilla\n"
    .string "que no entiendas.\p"
    .string "Te explicará muy bien lo básico\n"
    .string "para ser una buena {SHADOW DYNAMIC_COLOR4}ENTRENADORA{SHADOW LIGHT_GRAY}.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Lo bien que me sienta tomarme\n"
    .string "un café... ¡Me pone de buena ánimo!\p"
    .string "Aunque creo que estaba demasiado\n"
    .string "cargado... Me duele la cabeza.\p"
    .string "A todo esto... ¿Estás completando\n"
    .string "la {SHADOW DYNAMIC_COLOR4}POKéDEX{SHADOW LIGHT_GRAY}?\p"
    .string "No olvides que conviene agotar\n"
    .string "todo lo posible a los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}\l"
    .string "antes de intentar atraparlos.$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "Incidentally, is my old TEACHY TV\n"
    .string "helping you?$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "Wahaha!\n"
    .string "It's my grandson on the show!\p"
    .string "Since he's the one doing the\n"
    .string "teaching, you're bound to learn.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Hm… You're too busy to not even\n"
    .string "have the time for TEACHY TV…\p"
    .string "Time is money, and neither should\n"
    .string "be ill spent…$"

ViridianCity_Text_Basura::
    .string "Aquí solo hay basura...$"

ViridianCity_Text_BasuraItem1::
    .string "{SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY} encontró una {SHADOW DYNAMIC_COLOR4}POCIÓN{SHADOW LIGHT_GRAY}\n"
    .string "en la basura.$"

ViridianCity_Text_BasuraItem2::
    .string "{SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY} encontró una {SHADOW DYNAMIC_COLOR4}POKéBALL{SHADOW LIGHT_GRAY}\n"
    .string "en la basura.$"
     
ViridianCity_Text_BasuraItem3::
    .string "{SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY} encontró un {SHADOW DYNAMIC_COLOR4}ANTÍDOTO{SHADOW LIGHT_GRAY}\n"
    .string "en la basura.$"

ViridianCity_Text_CitySign::
    .string "{SHADOW DYNAMIC_COLOR4}CIUDAD VERDE{SHADOW LIGHT_GRAY}\n"
    .string "El paraíso del eterno verdor$"

ViridianCity_Text_EventScript_LetreroEscuela::
    .string "{SHADOW DYNAMIC_COLOR4}ESCUELA DE ENTRENADORES{SHADOW LIGHT_GRAY}\n"
    .string "¡Aprende y crea escuela!$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "{SHADOW DYNAMIC_COLOR4}PISTAS DE ENTRENADOR{SHADOW LIGHT_GRAY}\p"
    .string "Atrapa {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} para ampliar tu\n"
    .string "colección.\p"
    .string "Cuantos más tengas, más fácil será\n"
    .string "la lucha.$"

ViridianCity_Text_MovesLimitedByPP::
    .string "{SHADOW DYNAMIC_COLOR4}PISTAS DE ENTRENADOR{SHADOW LIGHT_GRAY}\p"
    .string "Los ataques de tus {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} se \n"
    .string "basan de sus {SHADOW DYNAMIC_COLOR4}PUNTOS DE PODER (PP){SHADOW LIGHT_GRAY}.\p"
    .string "Haz que descansen en un {SHADOW DYNAMIC_COLOR4}CENTRO\n"
    .string "POKéMON{SHADOW LIGHT_GRAY} para recargar sus {SHADOW DYNAMIC_COLOR4}PP{SHADOW LIGHT_GRAY}.$"

ViridianCity_Text_GymSign::
    .string "{SHADOW DYNAMIC_COLOR4}GIMNASIO POKéMON DE CIUDAD VERDE$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "GIMNASIO POKÉMON\n"
    .string "{COLOR RED}{SHADOW LIGHT_RED}CERRADO$"

ViridianCity_Text_TrainerClefairy::
    .string "Pasar los días en compañia a mi\n"
    .string "{SHADOW DYNAMIC_COLOR4}CLEFAIRY{SHADOW LIGHT_GRAY} lo mejor de mi vida$"

ViridianCity_Text_EntrenadorBuscaLider::
    .string "Todas las veces que he venido a\n"
    .string "{SHADOW DYNAMIC_COLOR4}CIUDAD VERDE{SHADOW LIGHT_GRAY} nunca he podido\l"
    .string "encontrar al {SHADOW DYNAMIC_COLOR4}LIDER{SHADOW DYNAMIC_COLOR4} de {SHADOW DYNAMIC_COLOR4}GIMNASIO{SHADOW DYNAMIC_COLOR4}.$"

ViridianCity_Text_Trainer_Psyduck::
    .string "¡Vamos {SHADOW DYNAMIC_COLOR4}PSYDUCK{SHADOW LIGHT_GRAY}!\n"
    .string "Aún te queda algo de energía...$"

ViridianCity_Text_Trainer_Nidoran::
    .string "¡NIDORAN!\p"
    .string "¡Ataca!$"

ViridianCity_Text_InfoEscuela::
    .string "Además de tener un {SHADOW DYNAMIC_COLOR4}GIMNASIO\n"
    .string "POKéMON{SHADOW LIGHT_GRAY} en {SHADOW DYNAMIC_COLOR4}CIUDAD PLATEADA{SHADOW LIGHT_GRAY},\p"
    .string "también tenemos una {SHADOW DYNAMIC_COLOR4}ESCUELA DE\n"
    .string "ENTRENADORES{SHADOW LIGHT_GRAY}.$"
