Text_1A3505:: @ 81A3505
    .string "Ready?\n"
    .string "Boing!\p"
    .string "We're having a BODY SLAM match\n"
    .string "to see who wimps out first.\p"
    .string "If you were to join us, you'd be\n"
    .string "squashed like a bug, though…\p"
    .string "How about I teach BODY SLAM to\n"
    .string "a POKéMON of yours instead?$"

Text_1A35C7:: @ 81A35C7
    .string "Come again!\n"
    .string "Boing!$"

Text_1A35DA:: @ 81A35DA
    .string "Which POKéMON wants to learn how\n"
    .string "to BODY SLAM?$"

Text_1A3609:: @ 81A3609
    .string "Boioing!$"

Text_1A3612:: @ 81A3612
    .string "それ　ぼよーん！\n"
    .string "おまえ　おもいなあー！$"

gUnknown_81A3627:: @ 81A3627
    .string "There's a rare kind of ICE POKéMON\n"
    .string "that lives in the cave.\p"
    .string "We get a lot of visitors hoping to\n"
    .string "see that POKéMON.$"

gUnknown_81A3697:: @ 81A3697
    .string "Oh? A POKéMON EGG?\n"
    .string "…I have no idea.\p"
    .string "…Oh, wait. The DAY-CARE people\n"
    .string "in town were saying something.\p"
    .string "They said that they'd found EGGS\n"
    .string "before on their property.$"

gUnknown_81A3734:: @ 81A3734
    .string "What's this?\p"
    .string "The new POKéMON JOURNAL hasn't\n"
    .string "arrived on this island?$"

