CeruleanCity_House4_Text_NothingEntertaining::
.string "Ay…\n"
.string "Mucho tiempo, poco que hacer…\p"
.string "¿No pasa nada entretenido\n"
.string "en ninguna parte?$"

CeruleanCity_House4_Text_NewNewsInformativeHaveThis::
.string "¡Ah!\n"
.string "¡Un nuevo reporte de noticias!\p"
.string "Hmm…\p"
.string "¡Ya veo!\n"
.string "¡Eso fue muy informativo!\p"
.string "Te aplaudo por interesarte en las\n"
.string "noticias a tan corta edad.\p"
.string "Como agradecimiento por compartirlas\n"
.string "conmigo, quiero darte esto.$"

CeruleanCity_House4_Text_IncredibleNewsHaveBerries::
.string "¡Oh, oh!\n"
.string "¡E-este reporte de noticias!\p"
.string "Hmm…\p"
.string "¡Increíble!\n"
.string "¡Qué noticia tan impresionante!\p"
.string "¡Hace mucho que no veía algo tan\n"
.string "increíble!\p"
.string "Gracias por compartir esta fantástica\n"
.string "noticia. ¡Toma un montón de BAYAS!$"

CeruleanCity_House4_Text_WishCouldShareNewsWithOthers::
.string "Es una pena no compartir estas\n"
.string "noticias con otros…\p"
.string "Ojalá pudiera contárselo a alguien…\n"
.string "Que otros supieran las noticias…$"

CeruleanCity_House4_Text_ThanksForSpreadingNewsTakeThis::
.string "¿Ah, difundiste las noticias por mí?\p"
.string "Las buenas noticias valen la pena cuando\n"
.string "toda clase de gente las comparte.\p"
.string "Como agradecimiento por difundirlas,\n"
.string "¡toma esto!$"

CeruleanCity_House4_Text_MagnificentNewsSpreadHaveBerries::
.string "¿Has difundido aún más las noticias?\n"
.string "¡Magnífico!\p"
.string "Esa noticia debe estar encantada de\n"
.string "ser compartida así.\p"
.string "¡Claro que sí!\p"
.string "Considera esto una muestra de\n"
.string "aprecio mía y de la noticia.\p"
.string "Te daré más BAYAS de lo habitual.$"

CeruleanCity_House4_Text_EnjoyingMyselfWithAllSortsOfNews::
.string "Estoy disfrutando bastante con todo\n"
.string "tipo de noticias.\p"
.string "¡Sí, estoy satisfecho!\n"
.string "No me aburriré por un buen rato.$"

CeruleanCity_House4_Text_YourBerryPouchIsFull::
.string "¿Eh? Tu BOLSA DE BAYAS está llena.\n"
.string "Entonces mi regalo queda sin entregar.$"

