CeruleanCity_House4_Text_NothingEntertaining::
    .string "Sigh…\n"
    .string "Too much time, too little to do…\p"
    .string "Is nothing entertaining happening\n"
    .string "anywhere?$"

CeruleanCity_House4_Text_NewNewsInformativeHaveThis::
    .string "Ah!\n"
    .string "A new news report!\p"
    .string "Hmm…\p"
    .string "I see!\n"
    .string "That was quite informative!\p"
    .string "I applaud you for taking interest\n"
    .string "in the news at your young age.\p"
    .string "As my thanks for sharing the news\n"
    .string "with me, I want you to have this.$"

CeruleanCity_House4_Text_IncredibleNewsHaveBerries::
    .string "Oh, oh!\n"
    .string "Th-this news report!\p"
    .string "Hmm…\p"
    .string "Amazing!\n"
    .string "What an incredible piece of news!\p"
    .string "I haven't seen a news story this\n"
    .string "incredible in too long a time!\p"
    .string "Thanks for sharing this fantastic\n"
    .string "news. Have a bunch of BERRIES!$"

CeruleanCity_House4_Text_WishCouldShareNewsWithOthers::
    .string "It seems such a shame to not share\n"
    .string "this news with other folks…\p"
    .string "I wish I could tell someone…\n"
    .string "Let others know the news…$"

CeruleanCity_House4_Text_ThanksForSpreadingNewsTakeThis::
    .string "Ah, you've spread the news for me?\p"
    .string "Good news becomes worthwhile when\n"
    .string "all sorts of people share it.\p"
    .string "As my thanks for your spreading\n"
    .string "the news, take this!$"

CeruleanCity_House4_Text_MagnificentNewsSpreadHaveBerries::
    .string "You've spread the news some more?\n"
    .string "Magnificent!\p"
    .string "That piece of news must be\n"
    .string "delighted to be passed around so.\p"
    .string "Yes, indeed!\p"
    .string "Consider this a show of\n"
    .string "appreciation from me and the news.\p"
    .string "I'll give you more BERRIES than\n"
    .string "I usually do.$"

CeruleanCity_House4_Text_EnjoyingMyselfWithAllSortsOfNews::
    .string "I'm quite enjoying myself with all\n"
    .string "sorts of news.\p"
    .string "Yes, I am satisfied!\n"
    .string "I won't be bored for a while.$"

CeruleanCity_House4_Text_YourBerryPouchIsFull::
    .string "Hm? Your BERRY POUCH is full.\n"
    .string "My gift remains ungiven, then.$"

