# 1 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"

# 2 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"
SevenIsland_PokemonCenter_2F_MapScripts::
# 3 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, CableClub_OnFrame
# 4 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, CableClub_OnWarp
# 5 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, CableClub_OnLoad
# 6 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CableClub_OnTransition
# 7 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"
	.byte 0
# 8 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"

# 9 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"
@ The below 3 are unused and leftover from RS
# 10 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"
SevenIsland_PokemonCenter_2F_EventScript_Colosseum::
# 11 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"
	call CableClub_EventScript_Colosseum
# 12 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"
	end
# 13 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"

# 14 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"
SevenIsland_PokemonCenter_2F_EventScript_TradeCenter::
# 15 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"
	call CableClub_EventScript_TradeCenter
# 16 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"
	end
# 17 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"

# 18 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"
SevenIsland_PokemonCenter_2F_EventScript_RecordCorner::
# 19 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"
	call CableClub_EventScript_RecordCorner
# 20 "data/maps/SevenIsland_PokemonCenter_2F/scripts.pory"
	end
