	.align 2
gTilesetTiles_PalletTown:: @ 826D37C
	.incbin "data/tilesets/secondary/pallet_town/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PalletTown:: @ 826D7C0
	.incbin "data/tilesets/secondary/pallet_town/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/15.gbapal"

	.align 2
gTilesetTiles_ViridianCity:: @ 826D9C0
	.incbin "data/tilesets/secondary/viridian_city/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_ViridianCity:: @ 826DFC0
	.incbin "data/tilesets/secondary/viridian_city/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/15.gbapal"

	.align 2
gTilesetTiles_PewterCity:: @ 826E1C0
	.incbin "data/tilesets/secondary/pewter_city/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PewterCity:: @ 826EAB8
	.incbin "data/tilesets/secondary/pewter_city/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/15.gbapal"

	.align 2
gTilesetTiles_CeruleanCity:: @ 826ECB8
	.incbin "data/tilesets/secondary/cerulean_city/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanCity:: @ 826F4B8
	.incbin "data/tilesets/secondary/cerulean_city/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/15.gbapal"

	.align 2
gTilesetTiles_LavenderTown:: @ 826F6B8
	.incbin "data/tilesets/secondary/lavender_town/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_LavenderTown:: @ 8270438
	.incbin "data/tilesets/secondary/lavender_town/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/15.gbapal"

	.align 2
gTilesetTiles_VermilionCity:: @ 8270638
	.incbin "data/tilesets/secondary/vermilion_city/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_VermilionCity:: @ 8270DA0
	.incbin "data/tilesets/secondary/vermilion_city/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/15.gbapal"

	.align 2
gTilesetTiles_CeladonCity:: @ 8270FA0
	.incbin "data/tilesets/secondary/celadon_city/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeladonCity:: @ 8271C74
	.incbin "data/tilesets/secondary/celadon_city/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/15.gbapal"

	.align 2
gTilesetTiles_FuchsiaCity:: @ 8271E74
	.incbin "data/tilesets/secondary/fuchsia_city/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FuchsiaCity:: @ 8272A5C
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/15.gbapal"

	.align 2
gTilesetTiles_CinnabarIsland:: @ 8272C5C
	.incbin "data/tilesets/secondary/cinnabar_island/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CinnabarIsland:: @ 8273358
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/15.gbapal"

	.align 2
gTilesetTiles_IndigoPlateau:: @ 8273558
	.incbin "data/tilesets/secondary/indigo_plateau/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_IndigoPlateau:: @ 82742D0
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/15.gbapal"

	.align 2
gTilesetTiles_SaffronCity:: @ 82744D0
	.incbin "data/tilesets/secondary/saffron_city/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SaffronCity:: @ 8275094
	.incbin "data/tilesets/secondary/saffron_city/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/15.gbapal"

	.align 2
gTilesetTiles_Building:: @ Building
	.incbin "data/tilesets/primary/building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Building:: @ Building
	.incbin "data/tilesets/primary/building/palettes/00.gbapal"
	.incbin "data/tilesets/primary/building/palettes/01.gbapal"
	.incbin "data/tilesets/primary/building/palettes/02.gbapal"
	.incbin "data/tilesets/primary/building/palettes/03.gbapal"
	.incbin "data/tilesets/primary/building/palettes/04.gbapal"
	.incbin "data/tilesets/primary/building/palettes/05.gbapal"
	.incbin "data/tilesets/primary/building/palettes/06.gbapal"
	.incbin "data/tilesets/primary/building/palettes/07.gbapal"
	.incbin "data/tilesets/primary/building/palettes/08.gbapal"
	.incbin "data/tilesets/primary/building/palettes/09.gbapal"
	.incbin "data/tilesets/primary/building/palettes/10.gbapal"
	.incbin "data/tilesets/primary/building/palettes/11.gbapal"
	.incbin "data/tilesets/primary/building/palettes/12.gbapal"
	.incbin "data/tilesets/primary/building/palettes/13.gbapal"
	.incbin "data/tilesets/primary/building/palettes/14.gbapal"
	.incbin "data/tilesets/primary/building/palettes/15.gbapal"

	.align 2
gTilesetTiles_Mart:: @ 8277894
	.incbin "data/tilesets/secondary/mart/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Mart:: @ 8277A5C
	.incbin "data/tilesets/secondary/mart/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonCenter:: @ 8277C5C
	.incbin "data/tilesets/secondary/pokemon_center/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonCenter:: @ 8278CC4
	.incbin "data/tilesets/secondary/pokemon_center/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/15.gbapal"

	.align 2
gTilesetTiles_Cave:: @ 8278EC4
	.incbin "data/tilesets/secondary/cave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Cave:: @ 827A1A8
	.incbin "data/tilesets/secondary/cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/15.gbapal"

	.align 2
gTilesetTiles_Dummy1:: @ 827A3A8
	.incbin "data/tilesets/secondary/dummy_1/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Dummy1:: @ 827A3B8
	.incbin "data/tilesets/secondary/dummy_1/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/15.gbapal"

	.align 2
gTilesetTiles_Museum:: @ 827A5B8
	.incbin "data/tilesets/secondary/museum/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Museum:: @ 827AE14
	.incbin "data/tilesets/secondary/museum/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/15.gbapal"

	.align 2
gTilesetTiles_CableClub:: @ 827B014
	.incbin "data/tilesets/secondary/cable_club/tiles.4bpp"

	.align 2
gTilesetPalettes_CableClub:: @ 827FF14
	.incbin "data/tilesets/secondary/cable_club/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/15.gbapal"

	.align 2
gTilesetTiles_BikeShop:: @ 8280114
	.incbin "data/tilesets/secondary/bike_shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BikeShop:: @ 82804EC
	.incbin "data/tilesets/secondary/bike_shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/15.gbapal"

	.align 2
gTilesetTiles_Lab:: @ 82806EC
	.incbin "data/tilesets/secondary/lab/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lab:: @ 8280D00
	.incbin "data/tilesets/secondary/lab/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/15.gbapal"

	.align 2
gTilesetTiles_HoennBuilding:: @ 8280F00
	.incbin "data/tilesets/secondary/hoenn_building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_HoennBuilding:: @ 82823A4
	.incbin "data/tilesets/secondary/hoenn_building/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/15.gbapal"

	.align 2
gTilesetTiles_GameCorner:: @ 82825A4
	.incbin "data/tilesets/secondary/game_corner/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GameCorner:: @ 8282FBC
	.incbin "data/tilesets/secondary/game_corner/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/15.gbapal"

	.align 2
gTilesetTiles_PewterGym:: @ 82831BC
	.incbin "data/tilesets/secondary/pewter_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PewterGym:: @ 82839B0
	.incbin "data/tilesets/secondary/pewter_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_CeruleanGym:: @ 8283BB0
	.incbin "data/tilesets/secondary/cerulean_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanGym:: @ 8283FF8
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_VermilionGym:: @ 82841F8
	.incbin "data/tilesets/secondary/vermilion_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_VermilionGym:: @ 82849B8
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_CeladonGym:: @ 8284BB8
	.incbin "data/tilesets/secondary/celadon_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeladonGym:: @ 8285150
	.incbin "data/tilesets/secondary/celadon_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_FuchsiaGym:: @ 8285350
	.incbin "data/tilesets/secondary/fuchsia_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FuchsiaGym:: @ 82857A4
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_SaffronGym:: @ 82859A4
	.incbin "data/tilesets/secondary/saffron_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SaffronGym:: @ 8285D90
	.incbin "data/tilesets/secondary/saffron_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_CinnabarGym:: @ 8285F90
	.incbin "data/tilesets/secondary/cinnabar_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CinnabarGym:: @ 82865D4
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_ViridianGym:: @ 82867D4
	.incbin "data/tilesets/secondary/viridian_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_ViridianGym:: @ 8286BC8
	.incbin "data/tilesets/secondary/viridian_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_SSAnne:: @ 8286DC8
	.incbin "data/tilesets/secondary/ss_anne/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SSAnne:: @ 8287B80
	.incbin "data/tilesets/secondary/ss_anne/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/15.gbapal"

	.align 2
gTilesetTiles_Dummy2:: @ 8287D80
	.incbin "data/tilesets/secondary/dummy_2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Dummy2:: @ 8287D94
	.incbin "data/tilesets/secondary/dummy_2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/15.gbapal"

	.align 2
gTilesetTiles_ViridianForest:: @ 8287F94
	.incbin "data/tilesets/secondary/viridian_forest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_ViridianForest:: @ 8288444
	.incbin "data/tilesets/secondary/viridian_forest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/15.gbapal"

	.align 2
gTilesetTiles_UnusedGatehouse1:: @ 8288644
	.incbin "data/tilesets/secondary/unused_gatehouse_1/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_UnusedGatehouse1:: @ 8288C60
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/15.gbapal"

	.align 2
gTilesetTiles_RockTunnel:: @ 8288E60
	.incbin "data/tilesets/secondary/rock_tunnel/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RockTunnel:: @ 8289FC8
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/15.gbapal"

	.align 2
gTilesetTiles_DiglettsCave:: @ 828A1C8
	.incbin "data/tilesets/secondary/digletts_cave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_DiglettsCave:: @ 828B250
	.incbin "data/tilesets/secondary/digletts_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/15.gbapal"

	.align 2
gTilesetTiles_SeafoamIslands:: @ 828B450
	.incbin "data/tilesets/secondary/seafoam_islands/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeafoamIslands:: @ 828CAA0
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/15.gbapal"

	.align 2
gTilesetTiles_UnusedGatehouse2:: @ 828CCA0
	.incbin "data/tilesets/secondary/unused_gatehouse_2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_UnusedGatehouse2:: @ 828D2BC
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/15.gbapal"

	.align 2
gTilesetTiles_CeruleanCave:: @ 828D4BC
	.incbin "data/tilesets/secondary/cerulean_cave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanCave:: @ 828E3A4
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/15.gbapal"

	.align 2
gTilesetTiles_GenericBuilding2:: @ 828E5A4
	.incbin "data/tilesets/secondary/generic_building_2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GenericBuilding2:: @ 828EC70
	.incbin "data/tilesets/secondary/generic_building_2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/15.gbapal"

	.align 2
gTilesetTiles_PowerPlant:: @ 828EE70
	.incbin "data/tilesets/secondary/power_plant/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PowerPlant:: @ 828F378
	.incbin "data/tilesets/secondary/power_plant/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/15.gbapal"

	.align 2
gTilesetTiles_SeaCottage:: @ 828F578
	.incbin "data/tilesets/secondary/sea_cottage/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeaCottage:: @ 828F9D8
	.incbin "data/tilesets/secondary/sea_cottage/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/15.gbapal"

	.align 2
gTilesetTiles_SilphCo:: @ 828FBD8
	.incbin "data/tilesets/secondary/condominiums/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SilphCo:: @ 8290DD0
	.incbin "data/tilesets/secondary/condominiums/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/15.gbapal"

	.align 2
gTilesetTiles_UndergroundPath:: @ 8290FD0
	.incbin "data/tilesets/secondary/underground_path/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_UndergroundPath:: @ 8291274
	.incbin "data/tilesets/secondary/underground_path/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonTower:: @ 8291474
	.incbin "data/tilesets/secondary/pokemon_tower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonTower:: @ 8291AFC
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/15.gbapal"

	.align 2
gTilesetTiles_SafariZoneBuilding:: @ 8291CFC
	.incbin "data/tilesets/secondary/safari_zone_building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SafariZoneBuilding:: @ 82920F0
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonMansion:: @ 82922F0
	.incbin "data/tilesets/secondary/pokemon_mansion/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonMansion:: @ 8292FF0
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/15.gbapal"

	.align 2
gTilesetTiles_RestaurantHotel:: @ 82931F0
	.incbin "data/tilesets/secondary/restaurant_hotel/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RestaurantHotel:: @ 8293660
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/15.gbapal"

	.align 2
gTilesetTiles_School:: @ 8293860
	.incbin "data/tilesets/secondary/school/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_School:: @ 8293B0C
	.incbin "data/tilesets/secondary/school/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/15.gbapal"

	.align 2
gTilesetTiles_FanClubDaycare:: @ 8293D0C
	.incbin "data/tilesets/secondary/fan_club_daycare/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FanClubDaycare:: @ 8294144
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/15.gbapal"

	.align 2
gTilesetTiles_BurgledHouse:: @ 8294344
	.incbin "data/tilesets/secondary/burgled_house/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BurgledHouse:: @ 8294D08
	.incbin "data/tilesets/secondary/burgled_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/15.gbapal"

	.align 2
gTilesetTiles_Dummy3:: @ 8294F08
	.incbin "data/tilesets/secondary/dummy_3/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Dummy3:: @ 8294F18
	.incbin "data/tilesets/secondary/dummy_3/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/15.gbapal"

	.align 2
gTilesetTiles_Dummy4:: @ 8295118
	.incbin "data/tilesets/secondary/dummy_4/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Dummy4:: @ 829512C
	.incbin "data/tilesets/secondary/dummy_4/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/15.gbapal"

	.align 2
gTilesetTiles_MtEmber:: @ 829532C
	.incbin "data/tilesets/secondary/mt_ember/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MtEmber:: @ 82967D4
	.incbin "data/tilesets/secondary/mt_ember/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/15.gbapal"

	.align 2
gTilesetTiles_BerryForest:: @ 82969D4
	.incbin "data/tilesets/secondary/berry_forest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BerryForest:: @ 8296E90
	.incbin "data/tilesets/secondary/berry_forest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/15.gbapal"

	.align 2
gTilesetTiles_NavelRock:: @ 8297090
	.incbin "data/tilesets/secondary/navel_rock/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_NavelRock:: @ 82983BC
	.incbin "data/tilesets/secondary/navel_rock/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/15.gbapal"

	.align 2
gTilesetTiles_TanobyRuins:: @ 82985BC
	.incbin "data/tilesets/secondary/tanoby_ruins/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_TanobyRuins:: @ 8298970
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/15.gbapal"

	.align 2
gTilesetTiles_SeviiIslands123:: @ 8298B70
	.incbin "data/tilesets/secondary/sevii_islands_123/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeviiIslands123:: @ 8299AA4
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/15.gbapal"

	.align 2
gTilesetTiles_SeviiIslands45:: @ 8299CA4
	.incbin "data/tilesets/secondary/sevii_islands_45/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeviiIslands45:: @ 829AB04
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/15.gbapal"

	.align 2
gTilesetTiles_SeviiIslands67:: @ 829AD04
	.incbin "data/tilesets/secondary/sevii_islands_67/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeviiIslands67:: @ 829BD64
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/15.gbapal"

	.align 2
gTilesetTiles_TrainerTower:: @ 829BF64
	.incbin "data/tilesets/secondary/trainer_tower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_TrainerTower:: @ 829CEE4
	.incbin "data/tilesets/secondary/trainer_tower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/15.gbapal"

	.align 2
gTilesetTiles_IslandHarbor:: @ 829D0E4
	.incbin "data/tilesets/secondary/island_harbor/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_IslandHarbor:: @ 829D894
	.incbin "data/tilesets/secondary/island_harbor/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonLeague:: @ 829DA94
	.incbin "data/tilesets/secondary/pokemon_league/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonLeague:: @ 829EA50
	.incbin "data/tilesets/secondary/pokemon_league/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/15.gbapal"

	.align 2
gTilesetTiles_HallOfFame:: @ 829EC50
	.incbin "data/tilesets/secondary/hall_of_fame/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_HallOfFame:: @ 829F4C8
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/15.gbapal"
