    .align 2
gTilesetTiles_826D37C:: @ 826D37C
    .incbin "data/tilesets/secondary/82D4AAC/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_826D7C0:: @ 826D7C0
    .incbin "data/tilesets/secondary/82D4AAC/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4AAC/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4AAC/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4AAC/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4AAC/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4AAC/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4AAC/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4AAC/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4AAC/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4AAC/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4AAC/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4AAC/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4AAC/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4AAC/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4AAC/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4AAC/palettes/15.gbapal"

    .align 2
gTilesetTiles_826D9C0:: @ 826D9C0
    .incbin "data/tilesets/secondary/82D4AC4/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_826DFC0:: @ 826DFC0
    .incbin "data/tilesets/secondary/82D4AC4/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4AC4/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4AC4/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4AC4/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4AC4/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4AC4/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4AC4/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4AC4/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4AC4/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4AC4/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4AC4/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4AC4/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4AC4/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4AC4/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4AC4/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4AC4/palettes/15.gbapal"

    .align 2
gTilesetTiles_826E1C0:: @ 826E1C0
    .incbin "data/tilesets/secondary/82D4ADC/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_826EAB8:: @ 826EAB8
    .incbin "data/tilesets/secondary/82D4ADC/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4ADC/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4ADC/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4ADC/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4ADC/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4ADC/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4ADC/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4ADC/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4ADC/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4ADC/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4ADC/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4ADC/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4ADC/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4ADC/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4ADC/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4ADC/palettes/15.gbapal"

    .align 2
gTilesetTiles_826ECB8:: @ 826ECB8
    .incbin "data/tilesets/secondary/82D4AF4/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_826F4B8:: @ 826F4B8
    .incbin "data/tilesets/secondary/82D4AF4/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4AF4/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4AF4/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4AF4/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4AF4/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4AF4/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4AF4/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4AF4/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4AF4/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4AF4/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4AF4/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4AF4/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4AF4/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4AF4/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4AF4/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4AF4/palettes/15.gbapal"

    .align 2
gTilesetTiles_826F6B8:: @ 826F6B8
    .incbin "data/tilesets/secondary/82D4B0C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8270438:: @ 8270438
    .incbin "data/tilesets/secondary/82D4B0C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4B0C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4B0C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4B0C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4B0C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4B0C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4B0C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4B0C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4B0C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4B0C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4B0C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4B0C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4B0C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4B0C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4B0C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4B0C/palettes/15.gbapal"

    .align 2
gTilesetTiles_8270638:: @ 8270638
    .incbin "data/tilesets/secondary/82D4B24/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8270DA0:: @ 8270DA0
    .incbin "data/tilesets/secondary/82D4B24/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4B24/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4B24/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4B24/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4B24/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4B24/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4B24/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4B24/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4B24/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4B24/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4B24/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4B24/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4B24/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4B24/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4B24/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4B24/palettes/15.gbapal"

    .align 2
gTilesetTiles_8270FA0:: @ 8270FA0
    .incbin "data/tilesets/secondary/82D4B3C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8271C74:: @ 8271C74
    .incbin "data/tilesets/secondary/82D4B3C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4B3C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4B3C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4B3C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4B3C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4B3C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4B3C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4B3C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4B3C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4B3C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4B3C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4B3C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4B3C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4B3C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4B3C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4B3C/palettes/15.gbapal"

    .align 2
gTilesetTiles_8271E74:: @ 8271E74
    .incbin "data/tilesets/secondary/82D4B54/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8272A5C:: @ 8272A5C
    .incbin "data/tilesets/secondary/82D4B54/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4B54/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4B54/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4B54/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4B54/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4B54/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4B54/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4B54/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4B54/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4B54/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4B54/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4B54/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4B54/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4B54/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4B54/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4B54/palettes/15.gbapal"

    .align 2
gTilesetTiles_8272C5C:: @ 8272C5C
    .incbin "data/tilesets/secondary/82D4B6C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8273358:: @ 8273358
    .incbin "data/tilesets/secondary/82D4B6C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4B6C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4B6C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4B6C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4B6C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4B6C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4B6C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4B6C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4B6C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4B6C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4B6C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4B6C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4B6C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4B6C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4B6C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4B6C/palettes/15.gbapal"

    .align 2
gTilesetTiles_8273558:: @ 8273558
    .incbin "data/tilesets/secondary/82D4B84/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_82742D0:: @ 82742D0
    .incbin "data/tilesets/secondary/82D4B84/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4B84/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4B84/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4B84/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4B84/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4B84/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4B84/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4B84/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4B84/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4B84/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4B84/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4B84/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4B84/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4B84/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4B84/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4B84/palettes/15.gbapal"

    .align 2
gTilesetTiles_82744D0:: @ 82744D0
    .incbin "data/tilesets/secondary/82D4B9C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8275094:: @ 8275094
    .incbin "data/tilesets/secondary/82D4B9C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4B9C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4B9C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4B9C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4B9C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4B9C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4B9C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4B9C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4B9C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4B9C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4B9C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4B9C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4B9C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4B9C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4B9C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4B9C/palettes/15.gbapal"

    .align 2
gTilesetTiles_8275294:: @ 8275294
    .incbin "data/tilesets/primary/82D4BB4/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8277694:: @ 8277694
    .incbin "data/tilesets/primary/82D4BB4/palettes/0.gbapal"
    .incbin "data/tilesets/primary/82D4BB4/palettes/1.gbapal"
    .incbin "data/tilesets/primary/82D4BB4/palettes/2.gbapal"
    .incbin "data/tilesets/primary/82D4BB4/palettes/3.gbapal"
    .incbin "data/tilesets/primary/82D4BB4/palettes/4.gbapal"
    .incbin "data/tilesets/primary/82D4BB4/palettes/5.gbapal"
    .incbin "data/tilesets/primary/82D4BB4/palettes/6.gbapal"
    .incbin "data/tilesets/primary/82D4BB4/palettes/7.gbapal"
    .incbin "data/tilesets/primary/82D4BB4/palettes/8.gbapal"
    .incbin "data/tilesets/primary/82D4BB4/palettes/9.gbapal"
    .incbin "data/tilesets/primary/82D4BB4/palettes/10.gbapal"
    .incbin "data/tilesets/primary/82D4BB4/palettes/11.gbapal"
    .incbin "data/tilesets/primary/82D4BB4/palettes/12.gbapal"
    .incbin "data/tilesets/primary/82D4BB4/palettes/13.gbapal"
    .incbin "data/tilesets/primary/82D4BB4/palettes/14.gbapal"
    .incbin "data/tilesets/primary/82D4BB4/palettes/15.gbapal"

    .align 2
gTilesetTiles_8277894:: @ 8277894
    .incbin "data/tilesets/secondary/82D4BCC/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8277A5C:: @ 8277A5C
    .incbin "data/tilesets/secondary/82D4BCC/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4BCC/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4BCC/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4BCC/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4BCC/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4BCC/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4BCC/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4BCC/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4BCC/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4BCC/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4BCC/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4BCC/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4BCC/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4BCC/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4BCC/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4BCC/palettes/15.gbapal"

    .align 2
gTilesetTiles_8277C5C:: @ 8277C5C
    .incbin "data/tilesets/secondary/82D4BE4/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8278CC4:: @ 8278CC4
    .incbin "data/tilesets/secondary/82D4BE4/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4BE4/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4BE4/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4BE4/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4BE4/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4BE4/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4BE4/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4BE4/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4BE4/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4BE4/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4BE4/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4BE4/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4BE4/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4BE4/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4BE4/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4BE4/palettes/15.gbapal"

    .align 2
gTilesetTiles_8278EC4:: @ 8278EC4
    .incbin "data/tilesets/secondary/82D4BFC/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_827A1A8:: @ 827A1A8
    .incbin "data/tilesets/secondary/82D4BFC/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4BFC/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4BFC/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4BFC/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4BFC/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4BFC/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4BFC/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4BFC/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4BFC/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4BFC/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4BFC/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4BFC/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4BFC/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4BFC/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4BFC/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4BFC/palettes/15.gbapal"

    .align 2
gTilesetTiles_827A3A8:: @ 827A3A8
    .incbin "data/tilesets/secondary/82D4C14/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_827A3B8:: @ 827A3B8
    .incbin "data/tilesets/secondary/82D4C14/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4C14/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4C14/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4C14/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4C14/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4C14/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4C14/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4C14/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4C14/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4C14/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4C14/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4C14/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4C14/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4C14/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4C14/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4C14/palettes/15.gbapal"

    .align 2
gTilesetTiles_827A5B8:: @ 827A5B8
    .incbin "data/tilesets/secondary/82D4C2C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_827AE14:: @ 827AE14
    .incbin "data/tilesets/secondary/82D4C2C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4C2C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4C2C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4C2C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4C2C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4C2C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4C2C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4C2C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4C2C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4C2C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4C2C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4C2C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4C2C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4C2C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4C2C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4C2C/palettes/15.gbapal"

    .align 2
gTilesetTiles_827B014:: @ 827B014
    .incbin "data/tilesets/secondary/82D4C44/tiles.4bpp"

    .align 2
gTilesetPalettes_827FF14:: @ 827FF14
    .incbin "data/tilesets/secondary/82D4C44/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4C44/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4C44/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4C44/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4C44/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4C44/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4C44/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4C44/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4C44/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4C44/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4C44/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4C44/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4C44/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4C44/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4C44/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4C44/palettes/15.gbapal"

    .align 2
gTilesetTiles_8280114:: @ 8280114
    .incbin "data/tilesets/secondary/82D4C5C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_82804EC:: @ 82804EC
    .incbin "data/tilesets/secondary/82D4C5C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4C5C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4C5C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4C5C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4C5C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4C5C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4C5C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4C5C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4C5C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4C5C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4C5C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4C5C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4C5C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4C5C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4C5C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4C5C/palettes/15.gbapal"

    .align 2
gTilesetTiles_82806EC:: @ 82806EC
    .incbin "data/tilesets/secondary/82D4C8C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8280D00:: @ 8280D00
    .incbin "data/tilesets/secondary/82D4C8C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4C8C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4C8C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4C8C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4C8C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4C8C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4C8C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4C8C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4C8C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4C8C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4C8C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4C8C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4C8C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4C8C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4C8C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4C8C/palettes/15.gbapal"

    .align 2
gTilesetTiles_8280F00:: @ 8280F00
    .incbin "data/tilesets/secondary/82D4CD4/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_82823A4:: @ 82823A4
    .incbin "data/tilesets/secondary/82D4CD4/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4CD4/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4CD4/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4CD4/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4CD4/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4CD4/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4CD4/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4CD4/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4CD4/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4CD4/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4CD4/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4CD4/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4CD4/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4CD4/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4CD4/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4CD4/palettes/15.gbapal"

    .align 2
gTilesetTiles_82825A4:: @ 82825A4
    .incbin "data/tilesets/secondary/82D4CEC/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8282FBC:: @ 8282FBC
    .incbin "data/tilesets/secondary/82D4CEC/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4CEC/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4CEC/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4CEC/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4CEC/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4CEC/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4CEC/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4CEC/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4CEC/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4CEC/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4CEC/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4CEC/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4CEC/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4CEC/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4CEC/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4CEC/palettes/15.gbapal"

    .align 2
gTilesetTiles_82831BC:: @ 82831BC
    .incbin "data/tilesets/secondary/82D4D04/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_82839B0:: @ 82839B0
    .incbin "data/tilesets/secondary/82D4D04/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4D04/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4D04/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4D04/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4D04/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4D04/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4D04/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4D04/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4D04/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4D04/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4D04/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4D04/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4D04/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4D04/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4D04/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4D04/palettes/15.gbapal"

    .align 2
gTilesetTiles_8283BB0:: @ 8283BB0
    .incbin "data/tilesets/secondary/82D4D1C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8283FF8:: @ 8283FF8
    .incbin "data/tilesets/secondary/82D4D1C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4D1C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4D1C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4D1C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4D1C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4D1C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4D1C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4D1C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4D1C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4D1C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4D1C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4D1C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4D1C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4D1C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4D1C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4D1C/palettes/15.gbapal"

    .align 2
gTilesetTiles_82841F8:: @ 82841F8
    .incbin "data/tilesets/secondary/82D4D34/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_82849B8:: @ 82849B8
    .incbin "data/tilesets/secondary/82D4D34/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4D34/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4D34/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4D34/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4D34/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4D34/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4D34/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4D34/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4D34/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4D34/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4D34/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4D34/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4D34/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4D34/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4D34/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4D34/palettes/15.gbapal"

    .align 2
gTilesetTiles_8284BB8:: @ 8284BB8
    .incbin "data/tilesets/secondary/82D4D4C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8285150:: @ 8285150
    .incbin "data/tilesets/secondary/82D4D4C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4D4C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4D4C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4D4C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4D4C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4D4C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4D4C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4D4C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4D4C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4D4C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4D4C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4D4C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4D4C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4D4C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4D4C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4D4C/palettes/15.gbapal"

    .align 2
gTilesetTiles_8285350:: @ 8285350
    .incbin "data/tilesets/secondary/82D4CA4/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_82857A4:: @ 82857A4
    .incbin "data/tilesets/secondary/82D4CA4/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4CA4/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4CA4/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4CA4/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4CA4/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4CA4/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4CA4/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4CA4/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4CA4/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4CA4/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4CA4/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4CA4/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4CA4/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4CA4/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4CA4/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4CA4/palettes/15.gbapal"

    .align 2
gTilesetTiles_82859A4:: @ 82859A4
    .incbin "data/tilesets/secondary/82D4D64/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8285D90:: @ 8285D90
    .incbin "data/tilesets/secondary/82D4D64/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4D64/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4D64/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4D64/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4D64/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4D64/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4D64/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4D64/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4D64/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4D64/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4D64/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4D64/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4D64/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4D64/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4D64/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4D64/palettes/15.gbapal"

    .align 2
gTilesetTiles_8285F90:: @ 8285F90
    .incbin "data/tilesets/secondary/82D4D7C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_82865D4:: @ 82865D4
    .incbin "data/tilesets/secondary/82D4D7C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4D7C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4D7C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4D7C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4D7C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4D7C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4D7C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4D7C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4D7C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4D7C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4D7C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4D7C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4D7C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4D7C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4D7C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4D7C/palettes/15.gbapal"

    .align 2
gTilesetTiles_82867D4:: @ 82867D4
    .incbin "data/tilesets/secondary/82D4CBC/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8286BC8:: @ 8286BC8
    .incbin "data/tilesets/secondary/82D4CBC/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4CBC/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4CBC/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4CBC/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4CBC/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4CBC/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4CBC/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4CBC/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4CBC/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4CBC/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4CBC/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4CBC/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4CBC/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4CBC/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4CBC/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4CBC/palettes/15.gbapal"

    .align 2
gTilesetTiles_8286DC8:: @ 8286DC8
    .incbin "data/tilesets/secondary/82D4D94/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8287B80:: @ 8287B80
    .incbin "data/tilesets/secondary/82D4D94/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4D94/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4D94/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4D94/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4D94/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4D94/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4D94/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4D94/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4D94/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4D94/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4D94/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4D94/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4D94/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4D94/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4D94/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4D94/palettes/15.gbapal"

    .align 2
gTilesetTiles_8287D80:: @ 8287D80
    .incbin "data/tilesets/secondary/82D4DAC/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8287D94:: @ 8287D94
    .incbin "data/tilesets/secondary/82D4DAC/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4DAC/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4DAC/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4DAC/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4DAC/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4DAC/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4DAC/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4DAC/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4DAC/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4DAC/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4DAC/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4DAC/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4DAC/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4DAC/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4DAC/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4DAC/palettes/15.gbapal"

    .align 2
gTilesetTiles_8287F94:: @ 8287F94
    .incbin "data/tilesets/secondary/82D4DC4/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8288444:: @ 8288444
    .incbin "data/tilesets/secondary/82D4DC4/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4DC4/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4DC4/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4DC4/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4DC4/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4DC4/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4DC4/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4DC4/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4DC4/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4DC4/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4DC4/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4DC4/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4DC4/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4DC4/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4DC4/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4DC4/palettes/15.gbapal"

    .align 2
gTilesetTiles_8288644:: @ 8288644
    .incbin "data/tilesets/secondary/82D4DDC/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8288C60:: @ 8288C60
    .incbin "data/tilesets/secondary/82D4DDC/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4DDC/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4DDC/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4DDC/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4DDC/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4DDC/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4DDC/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4DDC/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4DDC/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4DDC/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4DDC/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4DDC/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4DDC/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4DDC/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4DDC/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4DDC/palettes/15.gbapal"

    .align 2
gTilesetTiles_8288E60:: @ 8288E60
    .incbin "data/tilesets/secondary/82D4DF4/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8289FC8:: @ 8289FC8
    .incbin "data/tilesets/secondary/82D4DF4/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4DF4/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4DF4/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4DF4/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4DF4/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4DF4/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4DF4/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4DF4/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4DF4/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4DF4/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4DF4/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4DF4/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4DF4/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4DF4/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4DF4/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4DF4/palettes/15.gbapal"

    .align 2
gTilesetTiles_828A1C8:: @ 828A1C8
    .incbin "data/tilesets/secondary/82D4E0C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_828B250:: @ 828B250
    .incbin "data/tilesets/secondary/82D4E0C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4E0C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4E0C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4E0C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4E0C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4E0C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4E0C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4E0C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4E0C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4E0C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4E0C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4E0C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4E0C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4E0C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4E0C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4E0C/palettes/15.gbapal"

    .align 2
gTilesetTiles_828B450:: @ 828B450
    .incbin "data/tilesets/secondary/82D4E24/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_828CAA0:: @ 828CAA0
    .incbin "data/tilesets/secondary/82D4E24/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4E24/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4E24/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4E24/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4E24/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4E24/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4E24/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4E24/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4E24/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4E24/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4E24/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4E24/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4E24/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4E24/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4E24/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4E24/palettes/15.gbapal"

    .align 2
gTilesetTiles_828CCA0:: @ 828CCA0
    .incbin "data/tilesets/secondary/82D4E3C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_828D2BC:: @ 828D2BC
    .incbin "data/tilesets/secondary/82D4E3C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4E3C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4E3C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4E3C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4E3C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4E3C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4E3C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4E3C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4E3C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4E3C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4E3C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4E3C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4E3C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4E3C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4E3C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4E3C/palettes/15.gbapal"

    .align 2
gTilesetTiles_828D4BC:: @ 828D4BC
    .incbin "data/tilesets/secondary/82D4E54/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_828E3A4:: @ 828E3A4
    .incbin "data/tilesets/secondary/82D4E54/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4E54/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4E54/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4E54/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4E54/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4E54/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4E54/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4E54/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4E54/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4E54/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4E54/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4E54/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4E54/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4E54/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4E54/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4E54/palettes/15.gbapal"

    .align 2
gTilesetTiles_828E5A4:: @ 828E5A4
    .incbin "data/tilesets/secondary/82D4E84/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_828EC70:: @ 828EC70
    .incbin "data/tilesets/secondary/82D4E84/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4E84/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4E84/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4E84/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4E84/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4E84/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4E84/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4E84/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4E84/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4E84/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4E84/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4E84/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4E84/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4E84/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4E84/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4E84/palettes/15.gbapal"

    .align 2
gTilesetTiles_828EE70:: @ 828EE70
    .incbin "data/tilesets/secondary/82D4E9C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_828F378:: @ 828F378
    .incbin "data/tilesets/secondary/82D4E9C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4E9C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4E9C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4E9C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4E9C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4E9C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4E9C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4E9C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4E9C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4E9C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4E9C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4E9C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4E9C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4E9C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4E9C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4E9C/palettes/15.gbapal"

    .align 2
gTilesetTiles_828F578:: @ 828F578
    .incbin "data/tilesets/secondary/82D4EB4/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_828F9D8:: @ 828F9D8
    .incbin "data/tilesets/secondary/82D4EB4/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4EB4/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4EB4/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4EB4/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4EB4/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4EB4/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4EB4/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4EB4/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4EB4/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4EB4/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4EB4/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4EB4/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4EB4/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4EB4/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4EB4/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4EB4/palettes/15.gbapal"

    .align 2
gTilesetTiles_828FBD8:: @ 828FBD8
    .incbin "data/tilesets/secondary/82D4F8C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8290DD0:: @ 8290DD0
    .incbin "data/tilesets/secondary/82D4F8C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4F8C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4F8C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4F8C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4F8C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4F8C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4F8C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4F8C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4F8C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4F8C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4F8C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4F8C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4F8C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4F8C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4F8C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4F8C/palettes/15.gbapal"

    .align 2
gTilesetTiles_8290FD0:: @ 8290FD0
    .incbin "data/tilesets/secondary/82D4EE4/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8291274:: @ 8291274
    .incbin "data/tilesets/secondary/82D4EE4/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4EE4/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4EE4/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4EE4/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4EE4/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4EE4/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4EE4/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4EE4/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4EE4/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4EE4/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4EE4/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4EE4/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4EE4/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4EE4/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4EE4/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4EE4/palettes/15.gbapal"

    .align 2
gTilesetTiles_8291474:: @ 8291474
    .incbin "data/tilesets/secondary/82D4EFC/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8291AFC:: @ 8291AFC
    .incbin "data/tilesets/secondary/82D4EFC/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4EFC/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4EFC/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4EFC/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4EFC/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4EFC/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4EFC/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4EFC/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4EFC/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4EFC/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4EFC/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4EFC/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4EFC/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4EFC/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4EFC/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4EFC/palettes/15.gbapal"

    .align 2
gTilesetTiles_8291CFC:: @ 8291CFC
    .incbin "data/tilesets/secondary/82D4F14/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_82920F0:: @ 82920F0
    .incbin "data/tilesets/secondary/82D4F14/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4F14/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4F14/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4F14/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4F14/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4F14/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4F14/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4F14/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4F14/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4F14/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4F14/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4F14/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4F14/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4F14/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4F14/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4F14/palettes/15.gbapal"

    .align 2
gTilesetTiles_82922F0:: @ 82922F0
    .incbin "data/tilesets/secondary/82D4F2C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8292FF0:: @ 8292FF0
    .incbin "data/tilesets/secondary/82D4F2C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4F2C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4F2C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4F2C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4F2C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4F2C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4F2C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4F2C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4F2C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4F2C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4F2C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4F2C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4F2C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4F2C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4F2C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4F2C/palettes/15.gbapal"

    .align 2
gTilesetTiles_82931F0:: @ 82931F0
    .incbin "data/tilesets/secondary/82D4F44/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8293660:: @ 8293660
    .incbin "data/tilesets/secondary/82D4F44/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4F44/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4F44/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4F44/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4F44/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4F44/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4F44/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4F44/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4F44/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4F44/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4F44/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4F44/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4F44/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4F44/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4F44/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4F44/palettes/15.gbapal"

    .align 2
gTilesetTiles_8293860:: @ 8293860
    .incbin "data/tilesets/secondary/82D4F5C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8293B0C:: @ 8293B0C
    .incbin "data/tilesets/secondary/82D4F5C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4F5C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4F5C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4F5C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4F5C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4F5C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4F5C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4F5C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4F5C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4F5C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4F5C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4F5C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4F5C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4F5C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4F5C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4F5C/palettes/15.gbapal"

    .align 2
gTilesetTiles_8293D0C:: @ 8293D0C
    .incbin "data/tilesets/secondary/82D4F74/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8294144:: @ 8294144
    .incbin "data/tilesets/secondary/82D4F74/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4F74/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4F74/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4F74/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4F74/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4F74/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4F74/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4F74/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4F74/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4F74/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4F74/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4F74/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4F74/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4F74/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4F74/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4F74/palettes/15.gbapal"

    .align 2
gTilesetTiles_8294344:: @ 8294344
    .incbin "data/tilesets/secondary/82D4FA4/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8294D08:: @ 8294D08
    .incbin "data/tilesets/secondary/82D4FA4/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4FA4/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4FA4/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4FA4/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4FA4/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4FA4/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4FA4/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4FA4/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4FA4/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4FA4/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4FA4/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4FA4/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4FA4/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4FA4/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4FA4/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4FA4/palettes/15.gbapal"

    .align 2
gTilesetTiles_8294F08:: @ 8294F08
    .incbin "data/tilesets/secondary/82D4FBC/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8294F18:: @ 8294F18
    .incbin "data/tilesets/secondary/82D4FBC/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4FBC/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4FBC/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4FBC/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4FBC/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4FBC/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4FBC/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4FBC/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4FBC/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4FBC/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4FBC/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4FBC/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4FBC/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4FBC/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4FBC/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4FBC/palettes/15.gbapal"

    .align 2
gTilesetTiles_8295118:: @ 8295118
    .incbin "data/tilesets/secondary/82D4FD4/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_829512C:: @ 829512C
    .incbin "data/tilesets/secondary/82D4FD4/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4FD4/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4FD4/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4FD4/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4FD4/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4FD4/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4FD4/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4FD4/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4FD4/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4FD4/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4FD4/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4FD4/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4FD4/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4FD4/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4FD4/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4FD4/palettes/15.gbapal"

    .align 2
gTilesetTiles_829532C:: @ 829532C
    .incbin "data/tilesets/secondary/82D4FEC/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_82967D4:: @ 82967D4
    .incbin "data/tilesets/secondary/82D4FEC/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D4FEC/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D4FEC/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D4FEC/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D4FEC/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D4FEC/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D4FEC/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D4FEC/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D4FEC/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D4FEC/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D4FEC/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D4FEC/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D4FEC/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D4FEC/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D4FEC/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D4FEC/palettes/15.gbapal"

    .align 2
gTilesetTiles_82969D4:: @ 82969D4
    .incbin "data/tilesets/secondary/82D5004/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8296E90:: @ 8296E90
    .incbin "data/tilesets/secondary/82D5004/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D5004/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D5004/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D5004/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D5004/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D5004/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D5004/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D5004/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D5004/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D5004/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D5004/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D5004/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D5004/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D5004/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D5004/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D5004/palettes/15.gbapal"

    .align 2
gTilesetTiles_8297090:: @ 8297090
    .incbin "data/tilesets/secondary/82D501C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_82983BC:: @ 82983BC
    .incbin "data/tilesets/secondary/82D501C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D501C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D501C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D501C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D501C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D501C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D501C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D501C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D501C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D501C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D501C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D501C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D501C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D501C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D501C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D501C/palettes/15.gbapal"

    .align 2
gTilesetTiles_82985BC:: @ 82985BC
    .incbin "data/tilesets/secondary/82D5034/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8298970:: @ 8298970
    .incbin "data/tilesets/secondary/82D5034/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D5034/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D5034/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D5034/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D5034/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D5034/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D5034/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D5034/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D5034/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D5034/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D5034/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D5034/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D5034/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D5034/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D5034/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D5034/palettes/15.gbapal"

    .align 2
gTilesetTiles_8298B70:: @ 8298B70
    .incbin "data/tilesets/secondary/82D504C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_8299AA4:: @ 8299AA4
    .incbin "data/tilesets/secondary/82D504C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D504C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D504C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D504C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D504C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D504C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D504C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D504C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D504C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D504C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D504C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D504C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D504C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D504C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D504C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D504C/palettes/15.gbapal"

    .align 2
gTilesetTiles_8299CA4:: @ 8299CA4
    .incbin "data/tilesets/secondary/82D5064/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_829AB04:: @ 829AB04
    .incbin "data/tilesets/secondary/82D5064/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D5064/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D5064/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D5064/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D5064/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D5064/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D5064/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D5064/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D5064/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D5064/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D5064/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D5064/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D5064/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D5064/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D5064/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D5064/palettes/15.gbapal"

    .align 2
gTilesetTiles_829AD04:: @ 829AD04
    .incbin "data/tilesets/secondary/82D507C/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_829BD64:: @ 829BD64
    .incbin "data/tilesets/secondary/82D507C/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D507C/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D507C/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D507C/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D507C/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D507C/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D507C/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D507C/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D507C/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D507C/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D507C/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D507C/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D507C/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D507C/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D507C/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D507C/palettes/15.gbapal"

    .align 2
gTilesetTiles_829BF64:: @ 829BF64
    .incbin "data/tilesets/secondary/82D5094/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_829CEE4:: @ 829CEE4
    .incbin "data/tilesets/secondary/82D5094/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D5094/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D5094/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D5094/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D5094/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D5094/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D5094/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D5094/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D5094/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D5094/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D5094/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D5094/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D5094/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D5094/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D5094/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D5094/palettes/15.gbapal"

    .align 2
gTilesetTiles_829D0E4:: @ 829D0E4
    .incbin "data/tilesets/secondary/82D50AC/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_829D894:: @ 829D894
    .incbin "data/tilesets/secondary/82D50AC/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D50AC/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D50AC/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D50AC/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D50AC/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D50AC/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D50AC/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D50AC/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D50AC/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D50AC/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D50AC/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D50AC/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D50AC/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D50AC/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D50AC/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D50AC/palettes/15.gbapal"

    .align 2
gTilesetTiles_829DA94:: @ 829DA94
    .incbin "data/tilesets/secondary/82D50C4/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_829EA50:: @ 829EA50
    .incbin "data/tilesets/secondary/82D50C4/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D50C4/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D50C4/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D50C4/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D50C4/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D50C4/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D50C4/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D50C4/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D50C4/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D50C4/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D50C4/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D50C4/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D50C4/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D50C4/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D50C4/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D50C4/palettes/15.gbapal"

    .align 2
gTilesetTiles_829EC50:: @ 829EC50
    .incbin "data/tilesets/secondary/82D50DC/tiles.4bpp.lz"

    .align 2
gTilesetPalettes_829F4C8:: @ 829F4C8
    .incbin "data/tilesets/secondary/82D50DC/palettes/0.gbapal"
    .incbin "data/tilesets/secondary/82D50DC/palettes/1.gbapal"
    .incbin "data/tilesets/secondary/82D50DC/palettes/2.gbapal"
    .incbin "data/tilesets/secondary/82D50DC/palettes/3.gbapal"
    .incbin "data/tilesets/secondary/82D50DC/palettes/4.gbapal"
    .incbin "data/tilesets/secondary/82D50DC/palettes/5.gbapal"
    .incbin "data/tilesets/secondary/82D50DC/palettes/6.gbapal"
    .incbin "data/tilesets/secondary/82D50DC/palettes/7.gbapal"
    .incbin "data/tilesets/secondary/82D50DC/palettes/8.gbapal"
    .incbin "data/tilesets/secondary/82D50DC/palettes/9.gbapal"
    .incbin "data/tilesets/secondary/82D50DC/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/82D50DC/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/82D50DC/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/82D50DC/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/82D50DC/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/82D50DC/palettes/15.gbapal"
