	.align 2
gTileset_82D4A94::
	.incbin "baserom.gba", 0x2D4A94, 0x18

	.align 2
gTileset_82D4AAC::
	.incbin "baserom.gba", 0x2D4AAC, 0x18

	.align 2
gTileset_82D4AC4::
	.incbin "baserom.gba", 0x2D4AC4, 0x18

	.align 2
gTileset_82D4ADC::
	.incbin "baserom.gba", 0x2D4ADC, 0x18

	.align 2
gTileset_82D4AF4::
	.incbin "baserom.gba", 0x2D4AF4, 0x18

	.align 2
gTileset_82D4B0C::
	.incbin "baserom.gba", 0x2D4B0C, 0x18

	.align 2
gTileset_82D4B24::
	.incbin "baserom.gba", 0x2D4B24, 0x18

	.align 2
gTileset_82D4B3C::
	.incbin "baserom.gba", 0x2D4B3C, 0x18

	.align 2
gTileset_82D4B54::
	.incbin "baserom.gba", 0x2D4B54, 0x18

	.align 2
gTileset_82D4B6C::
	.incbin "baserom.gba", 0x2D4B6C, 0x18

	.align 2
gTileset_82D4B84::
	.incbin "baserom.gba", 0x2D4B84, 0x18

	.align 2
gTileset_82D4B9C::
	.incbin "baserom.gba", 0x2D4B9C, 0x18

	.align 2
gTileset_82D4BB4::
	.incbin "baserom.gba", 0x2D4BB4, 0x18

	.align 2
gTileset_82D4BCC::
	.incbin "baserom.gba", 0x2D4BCC, 0x18

	.align 2
gTileset_82D4BE4::
	.incbin "baserom.gba", 0x2D4BE4, 0x18

	.align 2
gTileset_82D4BFC::
	.incbin "baserom.gba", 0x2D4BFC, 0x18

	.align 2
gTileset_82D4C14::
	.incbin "baserom.gba", 0x2D4C14, 0x18

	.align 2
gTileset_82D4C2C::
	.incbin "baserom.gba", 0x2D4C2C, 0x18

	.align 2
gTileset_82D4C44::
	.incbin "baserom.gba", 0x2D4C44, 0x18

	.align 2
gTileset_82D4C5C::
	.incbin "baserom.gba", 0x2D4C5C, 0x18

	.align 2
gTileset_82D4C74::
	.incbin "baserom.gba", 0x2D4C74, 0x18

	.align 2
gTileset_82D4C8C::
	.incbin "baserom.gba", 0x2D4C8C, 0x18

	.align 2
gTileset_82D4CA4::
	.incbin "baserom.gba", 0x2D4CA4, 0x18

	.align 2
gTileset_82D4CBC::
	.incbin "baserom.gba", 0x2D4CBC, 0x18

	.align 2
gTileset_82D4CD4::
	.incbin "baserom.gba", 0x2D4CD4, 0x18

	.align 2
gTileset_82D4CEC::
	.incbin "baserom.gba", 0x2D4CEC, 0x18

	.align 2
gTileset_82D4D04::
	.incbin "baserom.gba", 0x2D4D04, 0x18

	.align 2
gTileset_82D4D1C::
	.incbin "baserom.gba", 0x2D4D1C, 0x18

	.align 2
gTileset_82D4D34::
	.incbin "baserom.gba", 0x2D4D34, 0x18

	.align 2
gTileset_82D4D4C::
	.incbin "baserom.gba", 0x2D4D4C, 0x18

	.align 2
gTileset_82D4D64::
	.incbin "baserom.gba", 0x2D4D64, 0x18

	.align 2
gTileset_82D4D7C::
	.incbin "baserom.gba", 0x2D4D7C, 0x18

	.align 2
gTileset_82D4D94::
	.incbin "baserom.gba", 0x2D4D94, 0x18

	.align 2
gTileset_82D4DAC:: @ unreferenced
	.incbin "baserom.gba", 0x2D4DAC, 0x18

	.align 2
gTileset_82D4DC4::
	.incbin "baserom.gba", 0x2D4DC4, 0x18

	.align 2
gTileset_82D4DDC:: @ unused
	.incbin "baserom.gba", 0x2D4DDC, 0x18

	.align 2
gTileset_82D4DF4::
	.incbin "baserom.gba", 0x2D4DF4, 0x18

	.align 2
gTileset_82D4E0C::
	.incbin "baserom.gba", 0x2D4E0C, 0x18

	.align 2
gTileset_82D4E24::
	.incbin "baserom.gba", 0x2D4E24, 0x18

	.align 2
gTileset_82D4E3C:: @ unused
	.incbin "baserom.gba", 0x2D4E3C, 0x18

	.align 2
gTileset_82D4E54::
	.incbin "baserom.gba", 0x2D4E54, 0x18

	.align 2
gTileset_82D4E6C::
	.incbin "baserom.gba", 0x2D4E6C, 0x18

	.align 2
gTileset_82D4E84::
	.incbin "baserom.gba", 0x2D4E84, 0x18

	.align 2
gTileset_82D4E9C::
	.incbin "baserom.gba", 0x2D4E9C, 0x18

	.align 2
gTileset_82D4EB4::
	.incbin "baserom.gba", 0x2D4EB4, 0x18

	.align 2
gTileset_82D4ECC::
	.incbin "baserom.gba", 0x2D4ECC, 0x18

	.align 2
gTileset_82D4EE4::
	.incbin "baserom.gba", 0x2D4EE4, 0x18

	.align 2
gTileset_82D4EFC::
	.incbin "baserom.gba", 0x2D4EFC, 0x18

	.align 2
gTileset_82D4F14::
	.incbin "baserom.gba", 0x2D4F14, 0x18

	.align 2
gTileset_82D4F2C::
	.incbin "baserom.gba", 0x2D4F2C, 0x18

	.align 2
gTileset_82D4F44::
	.incbin "baserom.gba", 0x2D4F44, 0x18

	.align 2
gTileset_82D4F5C::
	.incbin "baserom.gba", 0x2D4F5C, 0x18

	.align 2
gTileset_82D4F74::
	.incbin "baserom.gba", 0x2D4F74, 0x18

	.align 2
gTileset_82D4F8C::
	.incbin "baserom.gba", 0x2D4F8C, 0x18

	.align 2
gTileset_82D4FA4::
	.incbin "baserom.gba", 0x2D4FA4, 0x18

	.align 2
gTileset_82D4FBC:: @ unused
	.incbin "baserom.gba", 0x2D4FBC, 0x18

	.align 2
gTileset_82D4FD4:: @ unused
	.incbin "baserom.gba", 0x2D4FD4, 0x18

	.align 2
gTileset_82D4FEC::
	.incbin "baserom.gba", 0x2D4FEC, 0x18

	.align 2
gTileset_82D5004::
	.incbin "baserom.gba", 0x2D5004, 0x18

	.align 2
gTileset_82D501C::
	.incbin "baserom.gba", 0x2D501C, 0x18

	.align 2
gTileset_82D5034::
	.incbin "baserom.gba", 0x2D5034, 0x18

	.align 2
gTileset_82D504C::
	.incbin "baserom.gba", 0x2D504C, 0x18

	.align 2
gTileset_82D5064::
	.incbin "baserom.gba", 0x2D5064, 0x18

	.align 2
gTileset_82D507C::
	.incbin "baserom.gba", 0x2D507C, 0x18

	.align 2
gTileset_82D5094::
	.incbin "baserom.gba", 0x2D5094, 0x18

	.align 2
gTileset_82D50AC::
	.incbin "baserom.gba", 0x2D50AC, 0x18

	.align 2
gTileset_82D50C4::
	.incbin "baserom.gba", 0x2D50C4, 0x18

	.align 2
gTileset_82D50DC::
	.incbin "baserom.gba", 0x2D50DC, 0x18

