
	.align 2
gTileset_82D4A94::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8EA1D68
	.4byte gTilesetPalettes_8EA1B68
	.4byte gMetatiles_829F6C8
	.4byte sub_8070154
	.4byte gMetatileAttributes_82A1EC8

	.align 2
gTileset_82D4AAC::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_826D37C
	.4byte gTilesetPalettes_826D7C0
	.4byte gMetatiles_82A28C8
	.4byte 0x0
	.4byte gMetatileAttributes_82A2E58

	.align 2
gTileset_82D4AC4::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_826D9C0
	.4byte gTilesetPalettes_826DFC0
	.4byte gMetatiles_82A2FBC
	.4byte 0x0
	.4byte gMetatileAttributes_82A35AC

	.align 2
gTileset_82D4ADC::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_826E1C0
	.4byte gTilesetPalettes_826EAB8
	.4byte gMetatiles_82A3728
	.4byte 0x0
	.4byte gMetatileAttributes_82A3C18

	.align 2
gTileset_82D4AF4::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_826ECB8
	.4byte gTilesetPalettes_826F4B8
	.4byte gMetatiles_82A3D54
	.4byte 0x0
	.4byte gMetatileAttributes_82A45B4

	.align 2
gTileset_82D4B0C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_826F6B8
	.4byte gTilesetPalettes_8270438
	.4byte gMetatiles_82A47CC
	.4byte 0x0
	.4byte gMetatileAttributes_82A556C

	.align 2
gTileset_82D4B24::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8270638
	.4byte gTilesetPalettes_8270DA0
	.4byte gMetatiles_82A58D4
	.4byte 0x0
	.4byte gMetatileAttributes_82A6354

	.align 2
gTileset_82D4B3C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8270FA0
	.4byte gTilesetPalettes_8271C74
	.4byte gMetatiles_82A65F4
	.4byte sub_80701D8
	.4byte gMetatileAttributes_82A74F4

	.align 2
gTileset_82D4B54::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8271E74
	.4byte gTilesetPalettes_8272A5C
	.4byte gMetatiles_82A78B4
	.4byte 0x0
	.4byte gMetatileAttributes_82A84B4

	.align 2
gTileset_82D4B6C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8272C5C
	.4byte gTilesetPalettes_8273358
	.4byte gMetatiles_82A87B4
	.4byte 0x0
	.4byte gMetatileAttributes_82A8BB4

	.align 2
gTileset_82D4B84::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8273558
	.4byte gTilesetPalettes_82742D0
	.4byte gMetatiles_82A8CB4
	.4byte 0x0
	.4byte gMetatileAttributes_82A97B4

	.align 2
gTileset_82D4B9C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_82744D0
	.4byte gTilesetPalettes_8275094
	.4byte gMetatiles_82A9A74
	.4byte 0x0
	.4byte gMetatileAttributes_82AA6F4

	.align 2
gTileset_82D4BB4::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8275294
	.4byte gTilesetPalettes_8277694
	.4byte gMetatiles_82AD7B4
	.4byte 0x0
	.4byte gMetatileAttributes_82AFFB4

	.align 2
gTileset_82D4BCC::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8277894
	.4byte gTilesetPalettes_8277A5C
	.4byte gMetatiles_82B3524
	.4byte 0x0
	.4byte gMetatileAttributes_82B3954

	.align 2
gTileset_82D4BE4::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8277C5C
	.4byte gTilesetPalettes_8278CC4
	.4byte gMetatiles_82B3A60
	.4byte 0x0
	.4byte gMetatileAttributes_82B4A50

	.align 2
gTileset_82D4BFC::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8278EC4
	.4byte gTilesetPalettes_827A1A8
	.4byte gMetatiles_82B502C
	.4byte 0x0
	.4byte gMetatileAttributes_82B5A3C

	.align 2
gTileset_82D4C14::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_827A3A8
	.4byte gTilesetPalettes_827A3B8
	.4byte gMetatiles_82B09B4
	.4byte 0x0
	.4byte gMetatileAttributes_82B09D4

	.align 2
gTileset_82D4C2C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_827A5B8
	.4byte gTilesetPalettes_827AE14
	.4byte gMetatiles_82C5738
	.4byte 0x0
	.4byte gMetatileAttributes_82C5FA8

	.align 2
gTileset_82D4C44::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_827B014
	.4byte gTilesetPalettes_827FF14
	.4byte gMetatiles_82C61C4
	.4byte 0x0
	.4byte gMetatileAttributes_82C71C4

	.align 2
gTileset_82D4C5C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8280114
	.4byte gTilesetPalettes_82804EC
	.4byte gMetatiles_82B31DC
	.4byte 0x0
	.4byte gMetatileAttributes_82B347C

	.align 2
gTileset_82D4C74::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8EA99F4
	.4byte gTilesetPalettes_8EA97F4
	.4byte gMetatiles_82B4E4C
	.4byte 0x0
	.4byte gMetatileAttributes_82B4FCC

	.align 2
gTileset_82D4C8C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_82806EC
	.4byte gTilesetPalettes_8280D00
	.4byte gMetatiles_82B68A0
	.4byte 0x0
	.4byte gMetatileAttributes_82B7390

	.align 2
gTileset_82D4CA4::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8285350
	.4byte gTilesetPalettes_82857A4
	.4byte gMetatiles_82AC364
	.4byte 0x0
	.4byte gMetatileAttributes_82AC584

	.align 2
gTileset_82D4CBC::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_82867D4
	.4byte gTilesetPalettes_8286BC8
	.4byte gMetatiles_82AD124
	.4byte 0x0
	.4byte gMetatileAttributes_82AD664

	.align 2
gTileset_82D4CD4::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8280F00
	.4byte gTilesetPalettes_82823A4
	.4byte gMetatiles_82B09DC
	.4byte 0x0
	.4byte gMetatileAttributes_82B29DC

	.align 2
gTileset_82D4CEC::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_82825A4
	.4byte gTilesetPalettes_8282FBC
	.4byte gMetatiles_82B5CC0
	.4byte 0x0
	.4byte gMetatileAttributes_82B6640

	.align 2
gTileset_82D4D04::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_82831BC
	.4byte gTilesetPalettes_82839B0
	.4byte gMetatiles_82AAA14
	.4byte 0x0
	.4byte gMetatileAttributes_82AB064

	.align 2
gTileset_82D4D1C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8283BB0
	.4byte gTilesetPalettes_8283FF8
	.4byte gMetatiles_82AB1F8
	.4byte 0x0
	.4byte gMetatileAttributes_82AB738

	.align 2
gTileset_82D4D34::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_82841F8
	.4byte gTilesetPalettes_82849B8
	.4byte gMetatiles_82AB888
	.4byte sub_807031C
	.4byte gMetatileAttributes_82ABD38

	.align 2
gTileset_82D4D4C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8284BB8
	.4byte gTilesetPalettes_8285150
	.4byte gMetatiles_82ABE64
	.4byte sub_8070380
	.4byte gMetatileAttributes_82AC264

	.align 2
gTileset_82D4D64::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_82859A4
	.4byte gTilesetPalettes_8285D90
	.4byte gMetatiles_82AC60C
	.4byte 0x0
	.4byte gMetatileAttributes_82AC8EC

	.align 2
gTileset_82D4D7C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8285F90
	.4byte gTilesetPalettes_82865D4
	.4byte gMetatiles_82AC9A4
	.4byte 0x0
	.4byte gMetatileAttributes_82ACFA4

	.align 2
gTileset_82D4D94::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8286DC8
	.4byte gTilesetPalettes_8287B80
	.4byte gMetatiles_82B764C
	.4byte 0x0
	.4byte gMetatileAttributes_82B8B4C

	.align 2
gTileset_82D4DAC::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8287D80
	.4byte gTilesetPalettes_8287D94
	.4byte gMetatiles_82B908C
	.4byte 0x0
	.4byte gMetatileAttributes_82B90AC

	.align 2
gTileset_82D4DC4::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8287F94
	.4byte gTilesetPalettes_8288444
	.4byte gMetatiles_82B90B4
	.4byte 0x0
	.4byte gMetatileAttributes_82B9364

	.align 2
gTileset_82D4DDC::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8288644
	.4byte gTilesetPalettes_8288C60
	.4byte gMetatiles_82B9410
	.4byte 0x0
	.4byte gMetatileAttributes_82B9B30

	.align 2
gTileset_82D4DF4::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8288E60
	.4byte gTilesetPalettes_8289FC8
	.4byte gMetatiles_82B9CF8
	.4byte 0x0
	.4byte gMetatileAttributes_82BA678

	.align 2
gTileset_82D4E0C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_828A1C8
	.4byte gTilesetPalettes_828B250
	.4byte gMetatiles_82BA8D8
	.4byte 0x0
	.4byte gMetatileAttributes_82BB2A8

	.align 2
gTileset_82D4E24::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_828B450
	.4byte gTilesetPalettes_828CAA0
	.4byte gMetatiles_82BB51C
	.4byte 0x0
	.4byte gMetatileAttributes_82BC49C

	.align 2
gTileset_82D4E3C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_828CCA0
	.4byte gTilesetPalettes_828D2BC
	.4byte gMetatiles_82BC87C
	.4byte 0x0
	.4byte gMetatileAttributes_82BCF9C

	.align 2
gTileset_82D4E54::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_828D4BC
	.4byte gTilesetPalettes_828E3A4
	.4byte gMetatiles_82BD164
	.4byte 0x0
	.4byte gMetatileAttributes_82BD9C4

	.align 2
gTileset_82D4E6C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8EA9F88
	.4byte gTilesetPalettes_8EA9D88
	.4byte gMetatiles_82BDBDC
	.4byte 0x0
	.4byte gMetatileAttributes_82BEB3C

	.align 2
gTileset_82D4E84::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_828E5A4
	.4byte gTilesetPalettes_828EC70
	.4byte gMetatiles_82BEF14
	.4byte 0x0
	.4byte gMetatileAttributes_82BFA94

	.align 2
gTileset_82D4E9C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_828EE70
	.4byte gTilesetPalettes_828F378
	.4byte gMetatiles_82BFD74
	.4byte 0x0
	.4byte gMetatileAttributes_82C0704

	.align 2
gTileset_82D4EB4::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_828F578
	.4byte gTilesetPalettes_828F9D8
	.4byte gMetatiles_82C0968
	.4byte 0x0
	.4byte gMetatileAttributes_82C0D18

	.align 2
gTileset_82D4ECC::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_828FBD8
	.4byte gTilesetPalettes_8290DD0
	.4byte gMetatiles_82C0E04
	.4byte sub_8070250
	.4byte gMetatileAttributes_82C25A4

	.align 2
gTileset_82D4EE4::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8290FD0
	.4byte gTilesetPalettes_8291274
	.4byte gMetatiles_82C2B8C
	.4byte 0x0
	.4byte gMetatileAttributes_82C300C

	.align 2
gTileset_82D4EFC::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8291474
	.4byte gTilesetPalettes_8291AFC
	.4byte gMetatiles_82C312C
	.4byte 0x0
	.4byte gMetatileAttributes_82C377C

	.align 2
gTileset_82D4F14::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8291CFC
	.4byte gTilesetPalettes_82920F0
	.4byte gMetatiles_82C3910
	.4byte 0x0
	.4byte gMetatileAttributes_82C4110

	.align 2
gTileset_82D4F2C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_82922F0
	.4byte gTilesetPalettes_8292FF0
	.4byte gMetatiles_82C4310
	.4byte 0x0
	.4byte gMetatileAttributes_82C5330

	.align 2
gTileset_82D4F44::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_82931F0
	.4byte gTilesetPalettes_8293660
	.4byte gMetatiles_82C75C4
	.4byte 0x0
	.4byte gMetatileAttributes_82C7C44

	.align 2
gTileset_82D4F5C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8293860
	.4byte gTilesetPalettes_8293B0C
	.4byte gMetatiles_82C7DE4
	.4byte 0x0
	.4byte gMetatileAttributes_82C80C4

	.align 2
gTileset_82D4F74::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8293D0C
	.4byte gTilesetPalettes_8294144
	.4byte gMetatiles_82C817C
	.4byte 0x0
	.4byte gMetatileAttributes_82C8C1C

	.align 2
gTileset_82D4F8C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_828FBD8
	.4byte gTilesetPalettes_8290DD0
	.4byte gMetatiles_82C8EC4
	.4byte 0x0
	.4byte gMetatileAttributes_82C9C34

	.align 2
gTileset_82D4FA4::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8294344
	.4byte gTilesetPalettes_8294D08
	.4byte gMetatiles_82C9F90
	.4byte 0x0
	.4byte gMetatileAttributes_82CA320

	.align 2
gTileset_82D4FBC::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8294F08
	.4byte gTilesetPalettes_8294F18
	.4byte gMetatiles_82CA404
	.4byte 0x0
	.4byte gMetatileAttributes_82CA424

	.align 2
gTileset_82D4FD4::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8295118
	.4byte gTilesetPalettes_829512C
	.4byte gMetatiles_82CA42C
	.4byte 0x0
	.4byte gMetatileAttributes_82CA44C

	.align 2
gTileset_82D4FEC::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_829532C
	.4byte gTilesetPalettes_82967D4
	.4byte gMetatiles_82CA454
	.4byte sub_80702B4
	.4byte gMetatileAttributes_82CB274

	.align 2
gTileset_82D5004::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_82969D4
	.4byte gTilesetPalettes_8296E90
	.4byte gMetatiles_82CB5FC
	.4byte 0x0
	.4byte gMetatileAttributes_82CB89C

	.align 2
gTileset_82D501C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8297090
	.4byte gTilesetPalettes_82983BC
	.4byte gMetatiles_82CB944
	.4byte 0x0
	.4byte gMetatileAttributes_82CC704

	.align 2
gTileset_82D5034::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_82985BC
	.4byte gTilesetPalettes_8298970
	.4byte gMetatiles_82CCA74
	.4byte 0x0
	.4byte gMetatileAttributes_82CD054

	.align 2
gTileset_82D504C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8298B70
	.4byte gTilesetPalettes_8299AA4
	.4byte gMetatiles_82CD1CC
	.4byte 0x0
	.4byte gMetatileAttributes_82CE39C

	.align 2
gTileset_82D5064::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_8299CA4
	.4byte gTilesetPalettes_829AB04
	.4byte gMetatiles_82CE810
	.4byte 0x0
	.4byte gMetatileAttributes_82CF190

	.align 2
gTileset_82D507C::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_829AD04
	.4byte gTilesetPalettes_829BD64
	.4byte gMetatiles_82CF3F0
	.4byte 0x0
	.4byte gMetatileAttributes_82D02F0

	.align 2
gTileset_82D5094::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_829BF64
	.4byte gTilesetPalettes_829CEE4
	.4byte gMetatiles_82D06B0
	.4byte 0x0
	.4byte gMetatileAttributes_82D18B0

	.align 2
gTileset_82D50AC::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_829D0E4
	.4byte gTilesetPalettes_829D894
	.4byte gMetatiles_82D1D30
	.4byte 0x0
	.4byte gMetatileAttributes_82D2220

	.align 2
gTileset_82D50C4::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_829DA94
	.4byte gTilesetPalettes_829EA50
	.4byte gMetatiles_82D235C
	.4byte 0x0
	.4byte gMetatileAttributes_82D3B5C

	.align 2
gTileset_82D50DC::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_829EC50
	.4byte gTilesetPalettes_829F4C8
	.4byte gMetatiles_82D415C
	.4byte 0x0
	.4byte gMetatileAttributes_82D48BC

