
	.align 2
gTileset_General::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_General
	.4byte gTilesetPalettes_General
	.4byte gMetatiles_General
	.4byte InitTilesetAnim_General
	.4byte gMetatileAttributes_General

	.align 2
gTileset_PalletTown::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_PalletTown
	.4byte gTilesetPalettes_PalletTown
	.4byte gMetatiles_PalletTown
	.4byte 0x0
	.4byte gMetatileAttributes_PalletTown

	.align 2
gTileset_ViridianCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_ViridianCity
	.4byte gTilesetPalettes_ViridianCity
	.4byte gMetatiles_ViridianCity
	.4byte 0x0
	.4byte gMetatileAttributes_ViridianCity

	.align 2
gTileset_PewterCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_PewterCity
	.4byte gTilesetPalettes_PewterCity
	.4byte gMetatiles_PewterCity
	.4byte 0x0
	.4byte gMetatileAttributes_PewterCity

	.align 2
gTileset_CeruleanCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_CeruleanCity
	.4byte gTilesetPalettes_CeruleanCity
	.4byte gMetatiles_CeruleanCity
	.4byte 0x0
	.4byte gMetatileAttributes_CeruleanCity

	.align 2
gTileset_LavenderTown::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_LavenderTown
	.4byte gTilesetPalettes_LavenderTown
	.4byte gMetatiles_LavenderTown
	.4byte 0x0
	.4byte gMetatileAttributes_LavenderTown

	.align 2
gTileset_VermilionCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_VermilionCity
	.4byte gTilesetPalettes_VermilionCity
	.4byte gMetatiles_VermilionCity
	.4byte 0x0
	.4byte gMetatileAttributes_VermilionCity

	.align 2
gTileset_CeladonCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_CeladonCity
	.4byte gTilesetPalettes_CeladonCity
	.4byte gMetatiles_CeladonCity
	.4byte InitTilesetAnim_CeladonCity
	.4byte gMetatileAttributes_CeladonCity

	.align 2
gTileset_FuchsiaCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_FuchsiaCity
	.4byte gTilesetPalettes_FuchsiaCity
	.4byte gMetatiles_FuchsiaCity
	.4byte 0x0
	.4byte gMetatileAttributes_FuchsiaCity

	.align 2
gTileset_CinnabarIsland::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_CinnabarIsland
	.4byte gTilesetPalettes_CinnabarIsland
	.4byte gMetatiles_CinnabarIsland
	.4byte 0x0
	.4byte gMetatileAttributes_CinnabarIsland

	.align 2
gTileset_IndigoPlateau::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_IndigoPlateau
	.4byte gTilesetPalettes_IndigoPlateau
	.4byte gMetatiles_IndigoPlateau
	.4byte 0x0
	.4byte gMetatileAttributes_IndigoPlateau

	.align 2
gTileset_SaffronCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_SaffronCity
	.4byte gTilesetPalettes_SaffronCity
	.4byte gMetatiles_SaffronCity
	.4byte 0x0
	.4byte gMetatileAttributes_SaffronCity

	.align 2
gTileset_Building::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_Building
	.4byte gTilesetPalettes_Building
	.4byte gMetatiles_Building
	.4byte 0x0
	.4byte gMetatileAttributes_Building

	.align 2
gTileset_Mart::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_Mart
	.4byte gTilesetPalettes_Mart
	.4byte gMetatiles_Mart
	.4byte 0x0
	.4byte gMetatileAttributes_Mart

	.align 2
gTileset_PokemonCenter::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonCenter
	.4byte gTilesetPalettes_PokemonCenter
	.4byte gMetatiles_PokemonCenter
	.4byte 0x0
	.4byte gMetatileAttributes_PokemonCenter

	.align 2
gTileset_Cave::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_Cave
	.4byte gTilesetPalettes_Cave
	.4byte gMetatiles_Cave
	.4byte 0x0
	.4byte gMetatileAttributes_Cave

	.align 2
gTileset_Dummy1::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_Dummy1
	.4byte gTilesetPalettes_Dummy1
	.4byte gMetatiles_Dummy1
	.4byte 0x0
	.4byte gMetatileAttributes_Dummy1

	.align 2
gTileset_Museum::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_Museum
	.4byte gTilesetPalettes_Museum
	.4byte gMetatiles_Museum
	.4byte 0x0
	.4byte gMetatileAttributes_Museum

	.align 2
gTileset_CableClub::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_CableClub
	.4byte gTilesetPalettes_CableClub
	.4byte gMetatiles_CableClub
	.4byte 0x0
	.4byte gMetatileAttributes_CableClub

	.align 2
gTileset_BikeShop::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_BikeShop
	.4byte gTilesetPalettes_BikeShop
	.4byte gMetatiles_BikeShop
	.4byte 0x0
	.4byte gMetatileAttributes_BikeShop

	.align 2
gTileset_GenericBuilding1::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_GenericBuilding1
	.4byte gTilesetPalettes_GenericBuilding1
	.4byte gMetatiles_GenericBuilding1
	.4byte 0x0
	.4byte gMetatileAttributes_GenericBuilding1

	.align 2
gTileset_Lab::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_Lab
	.4byte gTilesetPalettes_Lab
	.4byte gMetatiles_Lab
	.4byte 0x0
	.4byte gMetatileAttributes_Lab

	.align 2
gTileset_FuchsiaGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_FuchsiaGym
	.4byte gTilesetPalettes_FuchsiaGym
	.4byte gMetatiles_FuchsiaGym
	.4byte 0x0
	.4byte gMetatileAttributes_FuchsiaGym

	.align 2
gTileset_ViridianGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_ViridianGym
	.4byte gTilesetPalettes_ViridianGym
	.4byte gMetatiles_ViridianGym
	.4byte 0x0
	.4byte gMetatileAttributes_ViridianGym

	.align 2
gTileset_HoennBuilding::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_HoennBuilding
	.4byte gTilesetPalettes_HoennBuilding
	.4byte gMetatiles_HoennBuilding
	.4byte 0x0
	.4byte gMetatileAttributes_HoennBuilding

	.align 2
gTileset_GameCorner::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_GameCorner
	.4byte gTilesetPalettes_GameCorner
	.4byte gMetatiles_GameCorner
	.4byte 0x0
	.4byte gMetatileAttributes_GameCorner

	.align 2
gTileset_PewterGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_PewterGym
	.4byte gTilesetPalettes_PewterGym
	.4byte gMetatiles_PewterGym
	.4byte 0x0
	.4byte gMetatileAttributes_PewterGym

	.align 2
gTileset_CeruleanGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_CeruleanGym
	.4byte gTilesetPalettes_CeruleanGym
	.4byte gMetatiles_CeruleanGym
	.4byte 0x0
	.4byte gMetatileAttributes_CeruleanGym

	.align 2
gTileset_VermilionGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_VermilionGym
	.4byte gTilesetPalettes_VermilionGym
	.4byte gMetatiles_VermilionGym
	.4byte InitTilesetAnim_VermilionGym
	.4byte gMetatileAttributes_VermilionGym

	.align 2
gTileset_CeladonGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_CeladonGym
	.4byte gTilesetPalettes_CeladonGym
	.4byte gMetatiles_CeladonGym
	.4byte InitTilesetAnim_CeladonGym
	.4byte gMetatileAttributes_CeladonGym

	.align 2
gTileset_SaffronGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_SaffronGym
	.4byte gTilesetPalettes_SaffronGym
	.4byte gMetatiles_SaffronGym
	.4byte 0x0
	.4byte gMetatileAttributes_SaffronGym

	.align 2
gTileset_CinnabarGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_CinnabarGym
	.4byte gTilesetPalettes_CinnabarGym
	.4byte gMetatiles_CinnabarGym
	.4byte 0x0
	.4byte gMetatileAttributes_CinnabarGym

	.align 2
gTileset_SSAnne::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_SSAnne
	.4byte gTilesetPalettes_SSAnne
	.4byte gMetatiles_SSAnne
	.4byte 0x0
	.4byte gMetatileAttributes_SSAnne

	.align 2
gTileset_Dummy2::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_Dummy2
	.4byte gTilesetPalettes_Dummy2
	.4byte gMetatiles_Dummy2
	.4byte 0x0
	.4byte gMetatileAttributes_Dummy2

	.align 2
gTileset_ViridianForest::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_ViridianForest
	.4byte gTilesetPalettes_ViridianForest
	.4byte gMetatiles_ViridianForest
	.4byte 0x0
	.4byte gMetatileAttributes_ViridianForest

	.align 2
gTileset_UnusedGatehouse1::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_UnusedGatehouse1
	.4byte gTilesetPalettes_UnusedGatehouse1
	.4byte gMetatiles_UnusedGatehouse1
	.4byte 0x0
	.4byte gMetatileAttributes_UnusedGatehouse1

	.align 2
gTileset_RockTunnel::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_RockTunnel
	.4byte gTilesetPalettes_RockTunnel
	.4byte gMetatiles_RockTunnel
	.4byte 0x0
	.4byte gMetatileAttributes_RockTunnel

	.align 2
gTileset_DiglettsCave::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_DiglettsCave
	.4byte gTilesetPalettes_DiglettsCave
	.4byte gMetatiles_DiglettsCave
	.4byte 0x0
	.4byte gMetatileAttributes_DiglettsCave

	.align 2
gTileset_SeafoamIslands::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_SeafoamIslands
	.4byte gTilesetPalettes_SeafoamIslands
	.4byte gMetatiles_SeafoamIslands
	.4byte 0x0
	.4byte gMetatileAttributes_SeafoamIslands

	.align 2
gTileset_UnusedGatehouse2::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_UnusedGatehouse2
	.4byte gTilesetPalettes_UnusedGatehouse2
	.4byte gMetatiles_UnusedGatehouse2
	.4byte 0x0
	.4byte gMetatileAttributes_UnusedGatehouse2

	.align 2
gTileset_CeruleanCave::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_CeruleanCave
	.4byte gTilesetPalettes_CeruleanCave
	.4byte gMetatiles_CeruleanCave
	.4byte 0x0
	.4byte gMetatileAttributes_CeruleanCave

	.align 2
gTileset_DepartmentStore::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_DepartmentStore
	.4byte gTilesetPalettes_DepartmentStore
	.4byte gMetatiles_DepartmentStore
	.4byte 0x0
	.4byte gMetatileAttributes_DepartmentStore

	.align 2
gTileset_GenericBuilding2::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_GenericBuilding2
	.4byte gTilesetPalettes_GenericBuilding2
	.4byte gMetatiles_GenericBuilding2
	.4byte 0x0
	.4byte gMetatileAttributes_GenericBuilding2

	.align 2
gTileset_PowerPlant::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_PowerPlant
	.4byte gTilesetPalettes_PowerPlant
	.4byte gMetatiles_PowerPlant
	.4byte 0x0
	.4byte gMetatileAttributes_PowerPlant

	.align 2
gTileset_SeaCottage::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_SeaCottage
	.4byte gTilesetPalettes_SeaCottage
	.4byte gMetatiles_SeaCottage
	.4byte 0x0
	.4byte gMetatileAttributes_SeaCottage

	.align 2
gTileset_SilphCo::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_SilphCo
	.4byte gTilesetPalettes_SilphCo
	.4byte gMetatiles_SilphCo
	.4byte InitTilesetAnim_SilphCo
	.4byte gMetatileAttributes_SilphCo

	.align 2
gTileset_UndergroundPath::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_UndergroundPath
	.4byte gTilesetPalettes_UndergroundPath
	.4byte gMetatiles_UndergroundPath
	.4byte 0x0
	.4byte gMetatileAttributes_UndergroundPath

	.align 2
gTileset_PokemonTower::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonTower
	.4byte gTilesetPalettes_PokemonTower
	.4byte gMetatiles_PokemonTower
	.4byte 0x0
	.4byte gMetatileAttributes_PokemonTower

	.align 2
gTileset_SafariZoneBuilding::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_SafariZoneBuilding
	.4byte gTilesetPalettes_SafariZoneBuilding
	.4byte gMetatiles_SafariZoneBuilding
	.4byte 0x0
	.4byte gMetatileAttributes_SafariZoneBuilding

	.align 2
gTileset_PokemonMansion::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonMansion
	.4byte gTilesetPalettes_PokemonMansion
	.4byte gMetatiles_PokemonMansion
	.4byte 0x0
	.4byte gMetatileAttributes_PokemonMansion

	.align 2
gTileset_RestaurantHotel::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_RestaurantHotel
	.4byte gTilesetPalettes_RestaurantHotel
	.4byte gMetatiles_RestaurantHotel
	.4byte 0x0
	.4byte gMetatileAttributes_RestaurantHotel

	.align 2
gTileset_School::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_School
	.4byte gTilesetPalettes_School
	.4byte gMetatiles_School
	.4byte 0x0
	.4byte gMetatileAttributes_School

	.align 2
gTileset_FanClubDaycare::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_FanClubDaycare
	.4byte gTilesetPalettes_FanClubDaycare
	.4byte gMetatiles_FanClubDaycare
	.4byte 0x0
	.4byte gMetatileAttributes_FanClubDaycare

	.align 2
gTileset_Condominiums::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_SilphCo
	.4byte gTilesetPalettes_SilphCo
	.4byte gMetatiles_Condominiums
	.4byte 0x0
	.4byte gMetatileAttributes_Condominiums

	.align 2
gTileset_BurgledHouse::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_BurgledHouse
	.4byte gTilesetPalettes_BurgledHouse
	.4byte gMetatiles_BurgledHouse
	.4byte 0x0
	.4byte gMetatileAttributes_BurgledHouse

	.align 2
gTileset_Dummy3::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_Dummy3
	.4byte gTilesetPalettes_Dummy3
	.4byte gMetatiles_Dummy3
	.4byte 0x0
	.4byte gMetatileAttributes_Dummy3

	.align 2
gTileset_Dummy4::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_Dummy4
	.4byte gTilesetPalettes_Dummy4
	.4byte gMetatiles_Dummy4
	.4byte 0x0
	.4byte gMetatileAttributes_Dummy4

	.align 2
gTileset_MtEmber::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_MtEmber
	.4byte gTilesetPalettes_MtEmber
	.4byte gMetatiles_MtEmber
	.4byte InitTilesetAnim_MtEmber
	.4byte gMetatileAttributes_MtEmber

	.align 2
gTileset_BerryForest::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_BerryForest
	.4byte gTilesetPalettes_BerryForest
	.4byte gMetatiles_BerryForest
	.4byte 0x0
	.4byte gMetatileAttributes_BerryForest

	.align 2
gTileset_NavelRock::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_NavelRock
	.4byte gTilesetPalettes_NavelRock
	.4byte gMetatiles_NavelRock
	.4byte 0x0
	.4byte gMetatileAttributes_NavelRock

	.align 2
gTileset_TanobyRuins::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_TanobyRuins
	.4byte gTilesetPalettes_TanobyRuins
	.4byte gMetatiles_TanobyRuins
	.4byte 0x0
	.4byte gMetatileAttributes_TanobyRuins

	.align 2
gTileset_SeviiIslands123::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_SeviiIslands123
	.4byte gTilesetPalettes_SeviiIslands123
	.4byte gMetatiles_SeviiIslands123
	.4byte 0x0
	.4byte gMetatileAttributes_SeviiIslands123

	.align 2
gTileset_SeviiIslands45::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_SeviiIslands45
	.4byte gTilesetPalettes_SeviiIslands45
	.4byte gMetatiles_SeviiIslands45
	.4byte 0x0
	.4byte gMetatileAttributes_SeviiIslands45

	.align 2
gTileset_SeviiIslands67::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_SeviiIslands67
	.4byte gTilesetPalettes_SeviiIslands67
	.4byte gMetatiles_SeviiIslands67
	.4byte 0x0
	.4byte gMetatileAttributes_SeviiIslands67

	.align 2
gTileset_TrainerTower::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_TrainerTower
	.4byte gTilesetPalettes_TrainerTower
	.4byte gMetatiles_TrainerTower
	.4byte 0x0
	.4byte gMetatileAttributes_TrainerTower

	.align 2
gTileset_IslandHarbor::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_IslandHarbor
	.4byte gTilesetPalettes_IslandHarbor
	.4byte gMetatiles_IslandHarbor
	.4byte 0x0
	.4byte gMetatileAttributes_IslandHarbor

	.align 2
gTileset_PokemonLeague::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonLeague
	.4byte gTilesetPalettes_PokemonLeague
	.4byte gMetatiles_PokemonLeague
	.4byte 0x0
	.4byte gMetatileAttributes_PokemonLeague

	.align 2
gTileset_HallOfFame::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0 @ padding
	.4byte gTilesetTiles_HallOfFame
	.4byte gTilesetPalettes_HallOfFame
	.4byte gMetatiles_HallOfFame
	.4byte 0x0
	.4byte gMetatileAttributes_HallOfFame

