    .align 1
gMetatiles_829F6C8:: @ 829F6C8
    .incbin "data/tilesets/primary/82D4A94/metatiles.bin"

    .align 1
gMetatileAttributes_82A1EC8:: @ 82A1EC8
    .incbin "data/tilesets/primary/82D4A94/metatile_attributes.bin"

    .align 1
gMetatiles_82A28C8:: @ 82A28C8
    .incbin "data/tilesets/secondary/82D4AAC/metatiles.bin"

    .align 1
gMetatileAttributes_82A2E58:: @ 82A2E58
    .incbin "data/tilesets/secondary/82D4AAC/metatile_attributes.bin"

    .align 1
gMetatiles_82A2FBC:: @ 82A2FBC
    .incbin "data/tilesets/secondary/82D4AC4/metatiles.bin"

    .align 1
gMetatileAttributes_82A35AC:: @ 82A35AC
    .incbin "data/tilesets/secondary/82D4AC4/metatile_attributes.bin"

    .align 1
gMetatiles_82A3728:: @ 82A3728
    .incbin "data/tilesets/secondary/82D4ADC/metatiles.bin"

    .align 1
gMetatileAttributes_82A3C18:: @ 82A3C18
    .incbin "data/tilesets/secondary/82D4ADC/metatile_attributes.bin"

    .align 1
gMetatiles_82A3D54:: @ 82A3D54
    .incbin "data/tilesets/secondary/82D4AF4/metatiles.bin"

    .align 1
gMetatileAttributes_82A45B4:: @ 82A45B4
    .incbin "data/tilesets/secondary/82D4AF4/metatile_attributes.bin"

    .align 1
gMetatiles_82A47CC:: @ 82A47CC
    .incbin "data/tilesets/secondary/82D4B0C/metatiles.bin"

    .align 1
gMetatileAttributes_82A556C:: @ 82A556C
    .incbin "data/tilesets/secondary/82D4B0C/metatile_attributes.bin"

    .align 1
gMetatiles_82A58D4:: @ 82A58D4
    .incbin "data/tilesets/secondary/82D4B24/metatiles.bin"

    .align 1
gMetatileAttributes_82A6354:: @ 82A6354
    .incbin "data/tilesets/secondary/82D4B24/metatile_attributes.bin"

    .align 1
gMetatiles_82A65F4:: @ 82A65F4
    .incbin "data/tilesets/secondary/82D4B3C/metatiles.bin"

    .align 1
gMetatileAttributes_82A74F4:: @ 82A74F4
    .incbin "data/tilesets/secondary/82D4B3C/metatile_attributes.bin"

    .align 1
gMetatiles_82A78B4:: @ 82A78B4
    .incbin "data/tilesets/secondary/82D4B54/metatiles.bin"

    .align 1
gMetatileAttributes_82A84B4:: @ 82A84B4
    .incbin "data/tilesets/secondary/82D4B54/metatile_attributes.bin"

    .align 1
gMetatiles_82A87B4:: @ 82A87B4
    .incbin "data/tilesets/secondary/82D4B6C/metatiles.bin"

    .align 1
gMetatileAttributes_82A8BB4:: @ 82A8BB4
    .incbin "data/tilesets/secondary/82D4B6C/metatile_attributes.bin"

    .align 1
gMetatiles_82A8CB4:: @ 82A8CB4
    .incbin "data/tilesets/secondary/82D4B84/metatiles.bin"

    .align 1
gMetatileAttributes_82A97B4:: @ 82A97B4
    .incbin "data/tilesets/secondary/82D4B84/metatile_attributes.bin"

    .align 1
gMetatiles_82A9A74:: @ 82A9A74
    .incbin "data/tilesets/secondary/82D4B9C/metatiles.bin"

    .align 1
gMetatileAttributes_82AA6F4:: @ 82AA6F4
    .incbin "data/tilesets/secondary/82D4B9C/metatile_attributes.bin"

    .align 1
gMetatiles_82AAA14:: @ 82AAA14
    .incbin "data/tilesets/secondary/82D4D04/metatiles.bin"

    .align 1
gMetatileAttributes_82AB064:: @ 82AB064
    .incbin "data/tilesets/secondary/82D4D04/metatile_attributes.bin"

    .align 1
gMetatiles_82AB1F8:: @ 82AB1F8
    .incbin "data/tilesets/secondary/82D4D1C/metatiles.bin"

    .align 1
gMetatileAttributes_82AB738:: @ 82AB738
    .incbin "data/tilesets/secondary/82D4D1C/metatile_attributes.bin"

    .align 1
gMetatiles_82AB888:: @ 82AB888
    .incbin "data/tilesets/secondary/82D4D34/metatiles.bin"

    .align 1
gMetatileAttributes_82ABD38:: @ 82ABD38
    .incbin "data/tilesets/secondary/82D4D34/metatile_attributes.bin"

    .align 1
gMetatiles_82ABE64:: @ 82ABE64
    .incbin "data/tilesets/secondary/82D4D4C/metatiles.bin"

    .align 1
gMetatileAttributes_82AC264:: @ 82AC264
    .incbin "data/tilesets/secondary/82D4D4C/metatile_attributes.bin"

    .align 1
gMetatiles_82AC364:: @ 82AC364
    .incbin "data/tilesets/secondary/82D4CA4/metatiles.bin"

    .align 1
gMetatileAttributes_82AC584:: @ 82AC584
    .incbin "data/tilesets/secondary/82D4CA4/metatile_attributes.bin"

    .align 1
gMetatiles_82AC60C:: @ 82AC60C
    .incbin "data/tilesets/secondary/82D4D64/metatiles.bin"

    .align 1
gMetatileAttributes_82AC8EC:: @ 82AC8EC
    .incbin "data/tilesets/secondary/82D4D64/metatile_attributes.bin"

    .align 1
gMetatiles_82AC9A4:: @ 82AC9A4
    .incbin "data/tilesets/secondary/82D4D7C/metatiles.bin"

    .align 1
gMetatileAttributes_82ACFA4:: @ 82ACFA4
    .incbin "data/tilesets/secondary/82D4D7C/metatile_attributes.bin"

    .align 1
gMetatiles_82AD124:: @ 82AD124
    .incbin "data/tilesets/secondary/82D4CBC/metatiles.bin"

    .align 1
gMetatileAttributes_82AD664:: @ 82AD664
    .incbin "data/tilesets/secondary/82D4CBC/metatile_attributes.bin"

    .align 1
gMetatiles_82AD7B4:: @ 82AD7B4
    .incbin "data/tilesets/primary/82D4BB4/metatiles.bin"

    .align 1
gMetatileAttributes_82AFFB4:: @ 82AFFB4
    .incbin "data/tilesets/primary/82D4BB4/metatile_attributes.bin"

    .align 1
gMetatiles_82B09B4:: @ 82B09B4
    .incbin "data/tilesets/secondary/82D4C14/metatiles.bin"

    .align 1
gMetatileAttributes_82B09D4:: @ 82B09D4
    .incbin "data/tilesets/secondary/82D4C14/metatile_attributes.bin"

    .align 1
gMetatiles_82B09DC:: @ 82B09DC
    .incbin "data/tilesets/secondary/82D4CD4/metatiles.bin"

    .align 1
gMetatileAttributes_82B29DC:: @ 82B29DC
    .incbin "data/tilesets/secondary/82D4CD4/metatile_attributes.bin"

    .align 1
gMetatiles_82B31DC:: @ 82B31DC
    .incbin "data/tilesets/secondary/82D4C5C/metatiles.bin"

    .align 1
gMetatileAttributes_82B347C:: @ 82B347C
    .incbin "data/tilesets/secondary/82D4C5C/metatile_attributes.bin"

    .align 1
gMetatiles_82B3524:: @ 82B3524
    .incbin "data/tilesets/secondary/82D4BCC/metatiles.bin"

    .align 1
gMetatileAttributes_82B3954:: @ 82B3954
    .incbin "data/tilesets/secondary/82D4BCC/metatile_attributes.bin"

    .align 1
gMetatiles_82B3A60:: @ 82B3A60
    .incbin "data/tilesets/secondary/82D4BE4/metatiles.bin"

    .align 1
gMetatileAttributes_82B4A50:: @ 82B4A50
    .incbin "data/tilesets/secondary/82D4BE4/metatile_attributes.bin"

    .align 1
gMetatiles_82B4E4C:: @ 82B4E4C
    .incbin "data/tilesets/secondary/82D4C74/metatiles.bin"

    .align 1
gMetatileAttributes_82B4FCC:: @ 82B4FCC
    .incbin "data/tilesets/secondary/82D4C74/metatile_attributes.bin"

    .align 1
gMetatiles_82B502C:: @ 82B502C
    .incbin "data/tilesets/secondary/82D4BFC/metatiles.bin"

    .align 1
gMetatileAttributes_82B5A3C:: @ 82B5A3C
    .incbin "data/tilesets/secondary/82D4BFC/metatile_attributes.bin"

    .align 1
gMetatiles_82B5CC0:: @ 82B5CC0
    .incbin "data/tilesets/secondary/82D4CEC/metatiles.bin"

    .align 1
gMetatileAttributes_82B6640:: @ 82B6640
    .incbin "data/tilesets/secondary/82D4CEC/metatile_attributes.bin"

    .align 1
gMetatiles_82B68A0:: @ 82B68A0
    .incbin "data/tilesets/secondary/82D4C8C/metatiles.bin"

    .align 1
gMetatileAttributes_82B7390:: @ 82B7390
    .incbin "data/tilesets/secondary/82D4C8C/metatile_attributes.bin"

    .align 1
gMetatiles_82B764C:: @ 82B764C
    .incbin "data/tilesets/secondary/82D4D94/metatiles.bin"

    .align 1
gMetatileAttributes_82B8B4C:: @ 82B8B4C
    .incbin "data/tilesets/secondary/82D4D94/metatile_attributes.bin"

    .align 1
gMetatiles_82B908C:: @ 82B908C
    .incbin "data/tilesets/secondary/82D4DAC/metatiles.bin"

    .align 1
gMetatileAttributes_82B90AC:: @ 82B90AC
    .incbin "data/tilesets/secondary/82D4DAC/metatile_attributes.bin"

    .align 1
gMetatiles_82B90B4:: @ 82B90B4
    .incbin "data/tilesets/secondary/82D4DC4/metatiles.bin"

    .align 1
gMetatileAttributes_82B9364:: @ 82B9364
    .incbin "data/tilesets/secondary/82D4DC4/metatile_attributes.bin"

    .align 1
gMetatiles_82B9410:: @ 82B9410
    .incbin "data/tilesets/secondary/82D4DDC/metatiles.bin"

    .align 1
gMetatileAttributes_82B9B30:: @ 82B9B30
    .incbin "data/tilesets/secondary/82D4DDC/metatile_attributes.bin"

    .align 1
gMetatiles_82B9CF8:: @ 82B9CF8
    .incbin "data/tilesets/secondary/82D4DF4/metatiles.bin"

    .align 1
gMetatileAttributes_82BA678:: @ 82BA678
    .incbin "data/tilesets/secondary/82D4DF4/metatile_attributes.bin"

    .align 1
gMetatiles_82BA8D8:: @ 82BA8D8
    .incbin "data/tilesets/secondary/82D4E0C/metatiles.bin"

    .align 1
gMetatileAttributes_82BB2A8:: @ 82BB2A8
    .incbin "data/tilesets/secondary/82D4E0C/metatile_attributes.bin"

    .align 1
gMetatiles_82BB51C:: @ 82BB51C
    .incbin "data/tilesets/secondary/82D4E24/metatiles.bin"

    .align 1
gMetatileAttributes_82BC49C:: @ 82BC49C
    .incbin "data/tilesets/secondary/82D4E24/metatile_attributes.bin"

    .align 1
gMetatiles_82BC87C:: @ 82BC87C
    .incbin "data/tilesets/secondary/82D4E3C/metatiles.bin"

    .align 1
gMetatileAttributes_82BCF9C:: @ 82BCF9C
    .incbin "data/tilesets/secondary/82D4E3C/metatile_attributes.bin"

    .align 1
gMetatiles_82BD164:: @ 82BD164
    .incbin "data/tilesets/secondary/82D4E54/metatiles.bin"

    .align 1
gMetatileAttributes_82BD9C4:: @ 82BD9C4
    .incbin "data/tilesets/secondary/82D4E54/metatile_attributes.bin"

    .align 1
gMetatiles_82BDBDC:: @ 82BDBDC
    .incbin "data/tilesets/secondary/82D4E6C/metatiles.bin"

    .align 1
gMetatileAttributes_82BEB3C:: @ 82BEB3C
    .incbin "data/tilesets/secondary/82D4E6C/metatile_attributes.bin"

    .align 1
gMetatiles_82BEF14:: @ 82BEF14
    .incbin "data/tilesets/secondary/82D4E84/metatiles.bin"

    .align 1
gMetatileAttributes_82BFA94:: @ 82BFA94
    .incbin "data/tilesets/secondary/82D4E84/metatile_attributes.bin"

    .align 1
gMetatiles_82BFD74:: @ 82BFD74
    .incbin "data/tilesets/secondary/82D4E9C/metatiles.bin"

    .align 1
gMetatileAttributes_82C0704:: @ 82C0704
    .incbin "data/tilesets/secondary/82D4E9C/metatile_attributes.bin"

    .align 1
gMetatiles_82C0968:: @ 82C0968
    .incbin "data/tilesets/secondary/82D4EB4/metatiles.bin"

    .align 1
gMetatileAttributes_82C0D18:: @ 82C0D18
    .incbin "data/tilesets/secondary/82D4EB4/metatile_attributes.bin"

    .align 1
gMetatiles_82C0E04:: @ 82C0E04
    .incbin "data/tilesets/secondary/82D4ECC/metatiles.bin"

    .align 1
gMetatileAttributes_82C25A4:: @ 82C25A4
    .incbin "data/tilesets/secondary/82D4ECC/metatile_attributes.bin"

    .align 1
gMetatiles_82C2B8C:: @ 82C2B8C
    .incbin "data/tilesets/secondary/82D4EE4/metatiles.bin"

    .align 1
gMetatileAttributes_82C300C:: @ 82C300C
    .incbin "data/tilesets/secondary/82D4EE4/metatile_attributes.bin"

    .align 1
gMetatiles_82C312C:: @ 82C312C
    .incbin "data/tilesets/secondary/82D4EFC/metatiles.bin"

    .align 1
gMetatileAttributes_82C377C:: @ 82C377C
    .incbin "data/tilesets/secondary/82D4EFC/metatile_attributes.bin"

    .align 1
gMetatiles_82C3910:: @ 82C3910
    .incbin "data/tilesets/secondary/82D4F14/metatiles.bin"

    .align 1
gMetatileAttributes_82C4110:: @ 82C4110
    .incbin "data/tilesets/secondary/82D4F14/metatile_attributes.bin"

    .align 1
gMetatiles_82C4310:: @ 82C4310
    .incbin "data/tilesets/secondary/82D4F2C/metatiles.bin"

    .align 1
gMetatileAttributes_82C5330:: @ 82C5330
    .incbin "data/tilesets/secondary/82D4F2C/metatile_attributes.bin"

    .align 1
gMetatiles_82C5738:: @ 82C5738
    .incbin "data/tilesets/secondary/82D4C2C/metatiles.bin"

    .align 1
gMetatileAttributes_82C5FA8:: @ 82C5FA8
    .incbin "data/tilesets/secondary/82D4C2C/metatile_attributes.bin"

    .align 1
gMetatiles_82C61C4:: @ 82C61C4
    .incbin "data/tilesets/secondary/82D4C44/metatiles.bin"

    .align 1
gMetatileAttributes_82C71C4:: @ 82C71C4
    .incbin "data/tilesets/secondary/82D4C44/metatile_attributes.bin"

    .align 1
gMetatiles_82C75C4:: @ 82C75C4
    .incbin "data/tilesets/secondary/82D4F44/metatiles.bin"

    .align 1
gMetatileAttributes_82C7C44:: @ 82C7C44
    .incbin "data/tilesets/secondary/82D4F44/metatile_attributes.bin"

    .align 1
gMetatiles_82C7DE4:: @ 82C7DE4
    .incbin "data/tilesets/secondary/82D4F5C/metatiles.bin"

    .align 1
gMetatileAttributes_82C80C4:: @ 82C80C4
    .incbin "data/tilesets/secondary/82D4F5C/metatile_attributes.bin"

    .align 1
gMetatiles_82C817C:: @ 82C817C
    .incbin "data/tilesets/secondary/82D4F74/metatiles.bin"

    .align 1
gMetatileAttributes_82C8C1C:: @ 82C8C1C
    .incbin "data/tilesets/secondary/82D4F74/metatile_attributes.bin"

    .align 1
gMetatiles_82C8EC4:: @ 82C8EC4
    .incbin "data/tilesets/secondary/82D4F8C/metatiles.bin"

    .align 1
gMetatileAttributes_82C9C34:: @ 82C9C34
    .incbin "data/tilesets/secondary/82D4F8C/metatile_attributes.bin"

    .align 1
gMetatiles_82C9F90:: @ 82C9F90
    .incbin "data/tilesets/secondary/82D4FA4/metatiles.bin"

    .align 1
gMetatileAttributes_82CA320:: @ 82CA320
    .incbin "data/tilesets/secondary/82D4FA4/metatile_attributes.bin"

    .align 1
gMetatiles_82CA404:: @ 82CA404
    .incbin "data/tilesets/secondary/82D4FBC/metatiles.bin"

    .align 1
gMetatileAttributes_82CA424:: @ 82CA424
    .incbin "data/tilesets/secondary/82D4FBC/metatile_attributes.bin"

    .align 1
gMetatiles_82CA42C:: @ 82CA42C
    .incbin "data/tilesets/secondary/82D4FD4/metatiles.bin"

    .align 1
gMetatileAttributes_82CA44C:: @ 82CA44C
    .incbin "data/tilesets/secondary/82D4FD4/metatile_attributes.bin"

    .align 1
gMetatiles_82CA454:: @ 82CA454
    .incbin "data/tilesets/secondary/82D4FEC/metatiles.bin"

    .align 1
gMetatileAttributes_82CB274:: @ 82CB274
    .incbin "data/tilesets/secondary/82D4FEC/metatile_attributes.bin"

    .align 1
gMetatiles_82CB5FC:: @ 82CB5FC
    .incbin "data/tilesets/secondary/82D5004/metatiles.bin"

    .align 1
gMetatileAttributes_82CB89C:: @ 82CB89C
    .incbin "data/tilesets/secondary/82D5004/metatile_attributes.bin"

    .align 1
gMetatiles_82CB944:: @ 82CB944
    .incbin "data/tilesets/secondary/82D501C/metatiles.bin"

    .align 1
gMetatileAttributes_82CC704:: @ 82CC704
    .incbin "data/tilesets/secondary/82D501C/metatile_attributes.bin"

    .align 1
gMetatiles_82CCA74:: @ 82CCA74
    .incbin "data/tilesets/secondary/82D5034/metatiles.bin"

    .align 1
gMetatileAttributes_82CD054:: @ 82CD054
    .incbin "data/tilesets/secondary/82D5034/metatile_attributes.bin"

    .align 1
gMetatiles_82CD1CC:: @ 82CD1CC
    .incbin "data/tilesets/secondary/82D504C/metatiles.bin"

    .align 1
gMetatileAttributes_82CE39C:: @ 82CE39C
    .incbin "data/tilesets/secondary/82D504C/metatile_attributes.bin"

    .align 1
gMetatiles_82CE810:: @ 82CE810
    .incbin "data/tilesets/secondary/82D5064/metatiles.bin"

    .align 1
gMetatileAttributes_82CF190:: @ 82CF190
    .incbin "data/tilesets/secondary/82D5064/metatile_attributes.bin"

    .align 1
gMetatiles_82CF3F0:: @ 82CF3F0
    .incbin "data/tilesets/secondary/82D507C/metatiles.bin"

    .align 1
gMetatileAttributes_82D02F0:: @ 82D02F0
    .incbin "data/tilesets/secondary/82D507C/metatile_attributes.bin"

    .align 1
gMetatiles_82D06B0:: @ 82D06B0
    .incbin "data/tilesets/secondary/82D5094/metatiles.bin"

    .align 1
gMetatileAttributes_82D18B0:: @ 82D18B0
    .incbin "data/tilesets/secondary/82D5094/metatile_attributes.bin"

    .align 1
gMetatiles_82D1D30:: @ 82D1D30
    .incbin "data/tilesets/secondary/82D50AC/metatiles.bin"

    .align 1
gMetatileAttributes_82D2220:: @ 82D2220
    .incbin "data/tilesets/secondary/82D50AC/metatile_attributes.bin"

    .align 1
gMetatiles_82D235C:: @ 82D235C
    .incbin "data/tilesets/secondary/82D50C4/metatiles.bin"

    .align 1
gMetatileAttributes_82D3B5C:: @ 82D3B5C
    .incbin "data/tilesets/secondary/82D50C4/metatile_attributes.bin"

    .align 1
gMetatiles_82D415C:: @ 82D415C
    .incbin "data/tilesets/secondary/82D50DC/metatiles.bin"

    .align 1
gMetatileAttributes_82D48BC:: @ 82D48BC
    .incbin "data/tilesets/secondary/82D50DC/metatile_attributes.bin"
