	.align 1
gMetatiles_General::
	.incbin "data/tilesets/primary/general/metatiles.bin"

	.align 1
gMetatileAttributes_General::
	.incbin "data/tilesets/primary/general/metatile_attributes.bin"

	.align 1
gMetatiles_PalletTown::
	.incbin "data/tilesets/secondary/pallet_town/metatiles.bin"

	.align 1
gMetatileAttributes_PalletTown::
	.incbin "data/tilesets/secondary/pallet_town/metatile_attributes.bin"

	.align 1
gMetatiles_ViridianCity::
	.incbin "data/tilesets/secondary/viridian_city/metatiles.bin"

	.align 1
gMetatileAttributes_ViridianCity::
	.incbin "data/tilesets/secondary/viridian_city/metatile_attributes.bin"

	.align 1
gMetatiles_PewterCity::
	.incbin "data/tilesets/secondary/pewter_city/metatiles.bin"

	.align 1
gMetatileAttributes_PewterCity::
	.incbin "data/tilesets/secondary/pewter_city/metatile_attributes.bin"

	.align 1
gMetatiles_CeruleanCity::
	.incbin "data/tilesets/secondary/cerulean_city/metatiles.bin"

	.align 1
gMetatileAttributes_CeruleanCity::
	.incbin "data/tilesets/secondary/cerulean_city/metatile_attributes.bin"

	.align 1
gMetatiles_LavenderTown::
	.incbin "data/tilesets/secondary/lavender_town/metatiles.bin"

	.align 1
gMetatileAttributes_LavenderTown::
	.incbin "data/tilesets/secondary/lavender_town/metatile_attributes.bin"

	.align 1
gMetatiles_VermilionCity::
	.incbin "data/tilesets/secondary/vermilion_city/metatiles.bin"

	.align 1
gMetatileAttributes_VermilionCity::
	.incbin "data/tilesets/secondary/vermilion_city/metatile_attributes.bin"

	.align 1
gMetatiles_CeladonCity::
	.incbin "data/tilesets/secondary/celadon_city/metatiles.bin"

	.align 1
gMetatileAttributes_CeladonCity::
	.incbin "data/tilesets/secondary/celadon_city/metatile_attributes.bin"

	.align 1
gMetatiles_FuchsiaCity::
	.incbin "data/tilesets/secondary/fuchsia_city/metatiles.bin"

	.align 1
gMetatileAttributes_FuchsiaCity::
	.incbin "data/tilesets/secondary/fuchsia_city/metatile_attributes.bin"

	.align 1
gMetatiles_CinnabarIsland::
	.incbin "data/tilesets/secondary/cinnabar_island/metatiles.bin"

	.align 1
gMetatileAttributes_CinnabarIsland::
	.incbin "data/tilesets/secondary/cinnabar_island/metatile_attributes.bin"

	.align 1
gMetatiles_IndigoPlateau::
	.incbin "data/tilesets/secondary/indigo_plateau/metatiles.bin"

	.align 1
gMetatileAttributes_IndigoPlateau::
	.incbin "data/tilesets/secondary/indigo_plateau/metatile_attributes.bin"

	.align 1
gMetatiles_SaffronCity::
	.incbin "data/tilesets/secondary/saffron_city/metatiles.bin"

	.align 1
gMetatileAttributes_SaffronCity::
	.incbin "data/tilesets/secondary/saffron_city/metatile_attributes.bin"

	.align 1
gMetatiles_PewterGym::
	.incbin "data/tilesets/secondary/pewter_gym/metatiles.bin"

	.align 1
gMetatileAttributes_PewterGym::
	.incbin "data/tilesets/secondary/pewter_gym/metatile_attributes.bin"

	.align 1
gMetatiles_CeruleanGym::
	.incbin "data/tilesets/secondary/cerulean_gym/metatiles.bin"

	.align 1
gMetatileAttributes_CeruleanGym::
	.incbin "data/tilesets/secondary/cerulean_gym/metatile_attributes.bin"

	.align 1
gMetatiles_VermilionGym::
	.incbin "data/tilesets/secondary/vermilion_gym/metatiles.bin"

	.align 1
gMetatileAttributes_VermilionGym::
	.incbin "data/tilesets/secondary/vermilion_gym/metatile_attributes.bin"

	.align 1
gMetatiles_CeladonGym::
	.incbin "data/tilesets/secondary/celadon_gym/metatiles.bin"

	.align 1
gMetatileAttributes_CeladonGym::
	.incbin "data/tilesets/secondary/celadon_gym/metatile_attributes.bin"

	.align 1
gMetatiles_FuchsiaGym::
	.incbin "data/tilesets/secondary/fuchsia_gym/metatiles.bin"

	.align 1
gMetatileAttributes_FuchsiaGym::
	.incbin "data/tilesets/secondary/fuchsia_gym/metatile_attributes.bin"

	.align 1
gMetatiles_SaffronGym::
	.incbin "data/tilesets/secondary/saffron_gym/metatiles.bin"

	.align 1
gMetatileAttributes_SaffronGym::
	.incbin "data/tilesets/secondary/saffron_gym/metatile_attributes.bin"

	.align 1
gMetatiles_CinnabarGym::
	.incbin "data/tilesets/secondary/cinnabar_gym/metatiles.bin"

	.align 1
gMetatileAttributes_CinnabarGym::
	.incbin "data/tilesets/secondary/cinnabar_gym/metatile_attributes.bin"

	.align 1
gMetatiles_ViridianGym::
	.incbin "data/tilesets/secondary/viridian_gym/metatiles.bin"

	.align 1
gMetatileAttributes_ViridianGym::
	.incbin "data/tilesets/secondary/viridian_gym/metatile_attributes.bin"

	.align 1
gMetatiles_Building:: @ Building
	.incbin "data/tilesets/primary/building/metatiles.bin"

	.align 1
gMetatileAttributes_Building:: @ Building
	.incbin "data/tilesets/primary/building/metatile_attributes.bin"

	.align 1
gMetatiles_Dummy1::
	.incbin "data/tilesets/secondary/dummy_1/metatiles.bin"

	.align 1
gMetatileAttributes_Dummy1::
	.incbin "data/tilesets/secondary/dummy_1/metatile_attributes.bin"

	.align 1
gMetatiles_HoennBuilding::
	.incbin "data/tilesets/secondary/hoenn_building/metatiles.bin"

	.align 1
gMetatileAttributes_HoennBuilding::
	.incbin "data/tilesets/secondary/hoenn_building/metatile_attributes.bin"

	.align 1
gMetatiles_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/metatiles.bin"

	.align 1
gMetatileAttributes_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/metatile_attributes.bin"

	.align 1
gMetatiles_Mart::
	.incbin "data/tilesets/secondary/mart/metatiles.bin"

	.align 1
gMetatileAttributes_Mart::
	.incbin "data/tilesets/secondary/mart/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/metatile_attributes.bin"

	.align 1
gMetatiles_GenericBuilding1::
	.incbin "data/tilesets/secondary/generic_building_1/metatiles.bin"

	.align 1
gMetatileAttributes_GenericBuilding1::
	.incbin "data/tilesets/secondary/generic_building_1/metatile_attributes.bin"

	.align 1
gMetatiles_Cave::
	.incbin "data/tilesets/secondary/cave/metatiles.bin"

	.align 1
gMetatileAttributes_Cave::
	.incbin "data/tilesets/secondary/cave/metatile_attributes.bin"

	.align 1
gMetatiles_GameCorner::
	.incbin "data/tilesets/secondary/game_corner/metatiles.bin"

	.align 1
gMetatileAttributes_GameCorner::
	.incbin "data/tilesets/secondary/game_corner/metatile_attributes.bin"

	.align 1
gMetatiles_Lab::
	.incbin "data/tilesets/secondary/lab/metatiles.bin"

	.align 1
gMetatileAttributes_Lab::
	.incbin "data/tilesets/secondary/lab/metatile_attributes.bin"

	.align 1
gMetatiles_SSAnne::
	.incbin "data/tilesets/secondary/ss_anne/metatiles.bin"

	.align 1
gMetatileAttributes_SSAnne::
	.incbin "data/tilesets/secondary/ss_anne/metatile_attributes.bin"

	.align 1
gMetatiles_Dummy2::
	.incbin "data/tilesets/secondary/dummy_2/metatiles.bin"

	.align 1
gMetatileAttributes_Dummy2::
	.incbin "data/tilesets/secondary/dummy_2/metatile_attributes.bin"

	.align 1
gMetatiles_ViridianForest::
	.incbin "data/tilesets/secondary/viridian_forest/metatiles.bin"

	.align 1
gMetatileAttributes_ViridianForest::
	.incbin "data/tilesets/secondary/viridian_forest/metatile_attributes.bin"

	.align 1
gMetatiles_UnusedGatehouse1::
	.incbin "data/tilesets/secondary/unused_gatehouse_1/metatiles.bin"

	.align 1
gMetatileAttributes_UnusedGatehouse1::
	.incbin "data/tilesets/secondary/unused_gatehouse_1/metatile_attributes.bin"

	.align 1
gMetatiles_RockTunnel::
	.incbin "data/tilesets/secondary/rock_tunnel/metatiles.bin"

	.align 1
gMetatileAttributes_RockTunnel::
	.incbin "data/tilesets/secondary/rock_tunnel/metatile_attributes.bin"

	.align 1
gMetatiles_DiglettsCave::
	.incbin "data/tilesets/secondary/digletts_cave/metatiles.bin"

	.align 1
gMetatileAttributes_DiglettsCave::
	.incbin "data/tilesets/secondary/digletts_cave/metatile_attributes.bin"

	.align 1
gMetatiles_SeafoamIslands::
	.incbin "data/tilesets/secondary/seafoam_islands/metatiles.bin"

	.align 1
gMetatileAttributes_SeafoamIslands::
	.incbin "data/tilesets/secondary/seafoam_islands/metatile_attributes.bin"

	.align 1
gMetatiles_UnusedGatehouse2::
	.incbin "data/tilesets/secondary/unused_gatehouse_2/metatiles.bin"

	.align 1
gMetatileAttributes_UnusedGatehouse2::
	.incbin "data/tilesets/secondary/unused_gatehouse_2/metatile_attributes.bin"

	.align 1
gMetatiles_CeruleanCave::
	.incbin "data/tilesets/secondary/cerulean_cave/metatiles.bin"

	.align 1
gMetatileAttributes_CeruleanCave::
	.incbin "data/tilesets/secondary/cerulean_cave/metatile_attributes.bin"

	.align 1
gMetatiles_DepartmentStore::
	.incbin "data/tilesets/secondary/department_store/metatiles.bin"

	.align 1
gMetatileAttributes_DepartmentStore::
	.incbin "data/tilesets/secondary/department_store/metatile_attributes.bin"

	.align 1
gMetatiles_GenericBuilding2::
	.incbin "data/tilesets/secondary/generic_building_2/metatiles.bin"

	.align 1
gMetatileAttributes_GenericBuilding2::
	.incbin "data/tilesets/secondary/generic_building_2/metatile_attributes.bin"

	.align 1
gMetatiles_PowerPlant::
	.incbin "data/tilesets/secondary/power_plant/metatiles.bin"

	.align 1
gMetatileAttributes_PowerPlant::
	.incbin "data/tilesets/secondary/power_plant/metatile_attributes.bin"

	.align 1
gMetatiles_SeaCottage::
	.incbin "data/tilesets/secondary/sea_cottage/metatiles.bin"

	.align 1
gMetatileAttributes_SeaCottage::
	.incbin "data/tilesets/secondary/sea_cottage/metatile_attributes.bin"

	.align 1
gMetatiles_SilphCo::
	.incbin "data/tilesets/secondary/silph_co/metatiles.bin"

	.align 1
gMetatileAttributes_SilphCo::
	.incbin "data/tilesets/secondary/silph_co/metatile_attributes.bin"

	.align 1
gMetatiles_UndergroundPath::
	.incbin "data/tilesets/secondary/underground_path/metatiles.bin"

	.align 1
gMetatileAttributes_UndergroundPath::
	.incbin "data/tilesets/secondary/underground_path/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonTower::
	.incbin "data/tilesets/secondary/pokemon_tower/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonTower::
	.incbin "data/tilesets/secondary/pokemon_tower/metatile_attributes.bin"

	.align 1
gMetatiles_SafariZoneBuilding::
	.incbin "data/tilesets/secondary/safari_zone_building/metatiles.bin"

	.align 1
gMetatileAttributes_SafariZoneBuilding::
	.incbin "data/tilesets/secondary/safari_zone_building/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonMansion::
	.incbin "data/tilesets/secondary/pokemon_mansion/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonMansion::
	.incbin "data/tilesets/secondary/pokemon_mansion/metatile_attributes.bin"

	.align 1
gMetatiles_Museum::
	.incbin "data/tilesets/secondary/museum/metatiles.bin"

	.align 1
gMetatileAttributes_Museum::
	.incbin "data/tilesets/secondary/museum/metatile_attributes.bin"

	.align 1
gMetatiles_CableClub::
	.incbin "data/tilesets/secondary/cable_club/metatiles.bin"

	.align 1
gMetatileAttributes_CableClub::
	.incbin "data/tilesets/secondary/cable_club/metatile_attributes.bin"

	.align 1
gMetatiles_RestaurantHotel::
	.incbin "data/tilesets/secondary/restaurant_hotel/metatiles.bin"

	.align 1
gMetatileAttributes_RestaurantHotel::
	.incbin "data/tilesets/secondary/restaurant_hotel/metatile_attributes.bin"

	.align 1
gMetatiles_School::
	.incbin "data/tilesets/secondary/school/metatiles.bin"

	.align 1
gMetatileAttributes_School::
	.incbin "data/tilesets/secondary/school/metatile_attributes.bin"

	.align 1
gMetatiles_FanClubDaycare::
	.incbin "data/tilesets/secondary/fan_club_daycare/metatiles.bin"

	.align 1
gMetatileAttributes_FanClubDaycare::
	.incbin "data/tilesets/secondary/fan_club_daycare/metatile_attributes.bin"

	.align 1
gMetatiles_Condominiums::
	.incbin "data/tilesets/secondary/condominiums/metatiles.bin"

	.align 1
gMetatileAttributes_Condominiums::
	.incbin "data/tilesets/secondary/condominiums/metatile_attributes.bin"

	.align 1
gMetatiles_BurgledHouse::
	.incbin "data/tilesets/secondary/burgled_house/metatiles.bin"

	.align 1
gMetatileAttributes_BurgledHouse::
	.incbin "data/tilesets/secondary/burgled_house/metatile_attributes.bin"

	.align 1
gMetatiles_Dummy3::
	.incbin "data/tilesets/secondary/dummy_3/metatiles.bin"

	.align 1
gMetatileAttributes_Dummy3::
	.incbin "data/tilesets/secondary/dummy_3/metatile_attributes.bin"

	.align 1
gMetatiles_Dummy4::
	.incbin "data/tilesets/secondary/dummy_4/metatiles.bin"

	.align 1
gMetatileAttributes_Dummy4::
	.incbin "data/tilesets/secondary/dummy_4/metatile_attributes.bin"

	.align 1
gMetatiles_MtEmber::
	.incbin "data/tilesets/secondary/mt_ember/metatiles.bin"

	.align 1
gMetatileAttributes_MtEmber::
	.incbin "data/tilesets/secondary/mt_ember/metatile_attributes.bin"

	.align 1
gMetatiles_BerryForest::
	.incbin "data/tilesets/secondary/berry_forest/metatiles.bin"

	.align 1
gMetatileAttributes_BerryForest::
	.incbin "data/tilesets/secondary/berry_forest/metatile_attributes.bin"

	.align 1
gMetatiles_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/metatiles.bin"

	.align 1
gMetatileAttributes_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/metatile_attributes.bin"

	.align 1
gMetatiles_TanobyRuins::
	.incbin "data/tilesets/secondary/tanoby_ruins/metatiles.bin"

	.align 1
gMetatileAttributes_TanobyRuins::
	.incbin "data/tilesets/secondary/tanoby_ruins/metatile_attributes.bin"

	.align 1
gMetatiles_SeviiIslands123::
	.incbin "data/tilesets/secondary/sevii_islands_123/metatiles.bin"

	.align 1
gMetatileAttributes_SeviiIslands123::
	.incbin "data/tilesets/secondary/sevii_islands_123/metatile_attributes.bin"

	.align 1
gMetatiles_SeviiIslands45::
	.incbin "data/tilesets/secondary/sevii_islands_45/metatiles.bin"

	.align 1
gMetatileAttributes_SeviiIslands45::
	.incbin "data/tilesets/secondary/sevii_islands_45/metatile_attributes.bin"

	.align 1
gMetatiles_SeviiIslands67::
	.incbin "data/tilesets/secondary/sevii_islands_67/metatiles.bin"

	.align 1
gMetatileAttributes_SeviiIslands67::
	.incbin "data/tilesets/secondary/sevii_islands_67/metatile_attributes.bin"

	.align 1
gMetatiles_TrainerTower::
	.incbin "data/tilesets/secondary/trainer_tower/metatiles.bin"

	.align 1
gMetatileAttributes_TrainerTower::
	.incbin "data/tilesets/secondary/trainer_tower/metatile_attributes.bin"

	.align 1
gMetatiles_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/metatiles.bin"

	.align 1
gMetatileAttributes_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonLeague::
	.incbin "data/tilesets/secondary/pokemon_league/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonLeague::
	.incbin "data/tilesets/secondary/pokemon_league/metatile_attributes.bin"

	.align 1
gMetatiles_HallOfFame::
	.incbin "data/tilesets/secondary/hall_of_fame/metatiles.bin"

	.align 1
gMetatileAttributes_HallOfFame::
	.incbin "data/tilesets/secondary/hall_of_fame/metatile_attributes.bin"
