PokemonLeague_AgathasRoom_Text_Intro:: @ 817844D
    .string "I am Agatha of the Elite Four.\p"
    .string "I hear Oak's taken a lot of\n"
    .string "interest in you, child.\p"
    .string "That old duff was once tough and\n"
    .string "handsome.\p"
    .string "But that was decades ago.\n"
    .string "He's a shadow of his former self.\p"
    .string "Now he just wants to fiddle with\n"
    .string "his Pokédex.\p"
    .string "He's wrong.\n"
    .string "Pokémon are for battling!\p"
    .string "{PLAYER}! I'll show you how a real\n"
    .string "Trainer battles!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_RematchIntro:: @ 817858D
    .string "I am Agatha of the Elite Four.\p"
    .string "You're the child that Oak's taken\n"
    .string "under his wing, aren't you?\p"
    .string "That old duff was once tough and\n"
    .string "handsome.\p"
    .string "But that was decades ago.\n"
    .string "He's a shadow of his former self.\p"
    .string "Now he just wants to fiddle with\n"
    .string "his Pokédex.\p"
    .string "He's wrong.\n"
    .string "Pokémon are for battling!\p"
    .string "{PLAYER}! I'll show you how a real\n"
    .string "Trainer battles!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_Defeat:: @ 81786D7
    .string "Oh, my!\n"
    .string "You're something special, child!$"

PokemonLeague_AgathasRoom_Text_PostBattle:: @ 8178700
    .string "You win!\p"
    .string "I see what the old duff sees in\n"
    .string "you now.\p"
    .string "I have nothing else to say.\n"
    .string "Run along now, child!$"

