VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon:: @ 81949CB
	.string "Hi!\n"
	.string "Do you have a {STR_VAR_1}?\p"
	.string "Want to trade it for my\n"
	.string "{STR_VAR_2}?$"

VermilionCity_House2_Text_ThatsTooBad:: @ 81949FD
	.string "That's too bad.$"

VermilionCity_House2_Text_ThisIsNoMon:: @ 8194A0D
	.string "…This is no {STR_VAR_1}.\p"
	.string "If you get one, please trade it\n"
	.string "to me!$"

VermilionCity_House2_Text_ThankYou:: @ 8194A44
	.string "Thank you!$"

VermilionCity_House2_Text_HowIsMyOldMon:: @ 8194A4F
	.string "How is my old {STR_VAR_2}?\p"
	.string "My {STR_VAR_1} is doing great!$"
