Route2_Text_RouteSign::
    .string "{SHADOW DYNAMIC_COLOR4}RUTA 2 - SUR{SHADOW LIGHT_GRAY}\n"
    .string "CIUDAD VERDE - CIUDAD PLATEADA$"

Route2_Text_RouteSign2::
    .string "{SHADOW DYNAMIC_COLOR4}RUTA 2 - NORTE{SHADOW LIGHT_GRAY}\n"
    .string "CIUDAD VERDE - CIUDAD PLATEADA$"

Route2_Text_RouteSign3::
    .string "{SHADOW DYNAMIC_COLOR4}{UP_ARROW_2} BOSQUE VERDE$"

Route2_Text_Policia::
    .string "{COLOR DARK_GRAY}Los informes de actividad del\n"
    .string "{SHADOW DYNAMIC_COLOR4}EQUIPO ROCKET{SHADOW LIGHT_GRAY}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} están en aumento.\p"
    .string "Mantén tus ojos y oídos abiertos\n"
    .string "mientras viajas.$"

Route2_Text_Adolescente::
    .string "{COLOR DARK_GRAY}Dicen que si tienes paciencia,\n"
    .string "podrías encontrar {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} súper\l"
    .string "raros en esta hierba alta.\p"
    .string "¡Estoy decidida a atrapar uno hoy!$"

Route2_Text_EntrenadorDamian1::
    .string "{COLOR DARK_GRAY}Este camino tiene sus secretos...\p"
    .string "¿Estás listo para descubrirlos en\n"
    .string "batalla?$"

Route2_Text_EntrenadorDamian2::
    .string "TU VICTORIA AÑADE OTRO RELATO DE\n"
    .string "VALENTÍA$"

Route2_Text_EntrenadorDamian3::
    .string "{COLOR DARK_GRAY}En el {SHADOW DYNAMIC_COLOR4}BOSQUE VERDE{SHADOW LIGHT_GRAY}, hay rumores de\n"
    .string "{SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} raros que no suelen\l"
    .string "encontrarse por aquí.$"

Route2_Text_DiglettsCave::
    .string "CUEVA DIGLETT$"

