ViridianCity_Mart_EventObjects:
	object_event 1, 68, 0, 2, 0, 3, 0, 0, 10, 17, 0, 0, 0, 0, 0, ViridianCity_Mart_EventScript_16A268, 0, 0, 0
	object_event 2, 18, 0, 6, 0, 2, 0, 3, 2, 17, 0, 0, 0, 0, 0, ViridianCity_Mart_EventScript_16A2B7, 0, 0, 0
	object_event 3, 23, 0, 9, 0, 5, 0, 3, 3, 17, 0, 0, 0, 0, 0, ViridianCity_Mart_EventScript_16A2AE, 0, 0, 0

ViridianCity_Mart_MapWarps:
	warp_def 3, 7, 3, 4, 769
	warp_def 4, 7, 3, 4, 769
	warp_def 5, 7, 3, 4, 769

ViridianCity_Mart_MapEvents::
	map_events ViridianCity_Mart_EventObjects, ViridianCity_Mart_MapWarps, 0x0, 0x0
