
ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "{COLOR DARK_GRAY}Creo que en esta tienda venden\n"
    .string "muchos {SHADOW DYNAMIC_COLOR4}ANTÍDOTOS{SHADOW LIGHT_GRAY}.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "{COLOR DARK_GRAY}Yo tengo algunas {SHADOW DYNAMIC_COLOR4}POCIONES{SHADOW LIGHT_GRAY}.\p"
    .string "Nunca sabes cuándo tus {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}\n"
    .string "pueden necesitarlas.$"

ViridianCity_Mart_Text_QueAlegriaEncontrarteAqui::
    .string "¡{SHADOW DYNAMIC_COLOR4}{PLAYER}{SHADOW LIGHT_GRAY}!\n"
    .string "¡Qué alegría encontrarte aquí!$"

ViridianCity_Mart_Text_VinePorUnasPokeball::
    .string "Vine por unas {SHADOW DYNAMIC_COLOR4}POKé BALL{SHADOW LIGHT_GRAY}, nunca están\n"
    .string "de más...\p"
    .string "Ahora vuelvo a {SHADOW DYNAMIC_COLOR4}PUEBLO PALETA{SHADOW LIGHT_GRAY}...\n"
    .string "Ando ayudando al {SHADOW DYNAMIC_COLOR4}PROF. OAK{SHADOW LIGHT_GRAY} con algo.\p"
    .string "Si pasas por allá, creo que se va\n"
    .string "a alegrar mucho.$"

ViridianCity_Mart_Text_NosVemosEnElLaboratorio::
.string "¡Nos vemos en el laboratorio!$"
