ViridianCity_Mart_Text_YouCameFromPallet:: @ 819021A
    .string "Hey!\n"
    .string "You came from Pallet Town?$"

ViridianCity_Mart_Text_TakeThisToProfOak:: @ 819023A
    .string "You know Prof. Oak, right?\p"
    .string "His order came in.\n"
    .string "Can I get you to take it to him?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk:: @ 8190289
    .string "{PLAYER} received Oak's Parcel\n"
    .string "from the Pokémon Mart clerk.$"

ViridianCity_Mart_Text_SayHiToOakForMe:: @ 81902BF
    .string "Okay, thanks! Please say hi to\n"
    .string "Prof. Oak for me, too.$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes:: @ 81902F5
    .string "This shop does good business in\n"
    .string "Antidotes, I've heard.$"

ViridianCity_Mart_Text_GotToBuySomePotions:: @ 819032C
    .string "I've got to buy some Potions.\p"
    .string "You never know when your Pokémon\n"
    .string "will need quick healing.$"

