FuchsiaCity_SafariZone_Entrance_Text_WelcomeToSafariZone:: @ 8197C6B
    .string "Welcome to the Safari Zone!$"

FuchsiaCity_SafariZone_Entrance_Text_PlaySafariGameFor500:: @ 8197C87
    .string "For just ¥500, you can play the\n"
    .string "Safari Game.\p"
    .string "You can roam the wide-open safari\n"
    .string "and catch what you like.\p"
    .string "Would you like to play?$"

FuchsiaCity_SafariZone_Entrance_Text_ThatllBe500WeOnlyUseSpecialBalls:: @ 8197D07
    .string "That'll be ¥500, please!\p"
    .string "We only use a special kind of \n"
    .string "Poké Balls here.$"

FuchsiaCity_SafariZone_Entrance_Text_PlayerReceived30SafariBalls:: @ 8197D50
    .string "{PLAYER} received 30 Safari Balls\n"
    .string "from the attendant.$"

FuchsiaCity_SafariZone_Entrance_Text_CallYouOnPAWhenYouRunOut:: @ 8197D80
    .string "We'll call you on the PA when you\n"
    .string "run out of time or Safari Balls.\p"
    .string "Well, I'll wish you the best of\n"
    .string "luck!$"

FuchsiaCity_SafariZone_Entrance_Text_OkayPleaseComeAgain:: @ 8197DE9
    .string "Okay.\n"
    .string "Please come again!$"

FuchsiaCity_SafariZone_Entrance_Text_OopsNotEnoughMoney:: @ 8197E02
    .string "Oops!\n"
    .string "Not enough money!$"

FuchsiaCity_SafariZone_Entrance_Text_GoingToLeaveSafariZoneEarly:: @ 8197E1A
    .string "Are you going to leave the\n"
    .string "Safari Zone early?$"

FuchsiaCity_SafariZone_Entrance_Text_PleaseReturnSafariBalls:: @ 8197E48
    .string "Please return any Safari Balls\n"
    .string "you may have left.$"

FuchsiaCity_SafariZone_Entrance_Text_GoodLuck:: @ 8197E7A
    .string "Good luck!$"

FuchsiaCity_SafariZone_Entrance_Text_CatchFairShareComeAgain:: @ 8197E85
    .string "Did you catch your fair share?\n"
    .string "Come again!$"

FuchsiaCity_SafariZone_Entrance_Text_FirstTimeAtSafariZone:: @ 8197EB0
    .string "Hi! Is it your first time here at\n"
    .string "the Safari Zone?$"

FuchsiaCity_SafariZone_Entrance_Text_ExplainSafariZone:: @ 8197EE3
    .string "The Safari Zone actually has\n"
    .string "four zones in it.\p"
    .string "Each zone has different kinds of\n"
    .string "Pokémon, even some rare ones.\p"
    .string "Use the supplied Safari Balls to\n"
    .string "catch them.\p"
    .string "You can also throw Bait or Rocks\n"
    .string "besides the Safari Balls.\p"
    .string "If you throw Bait, the Pokémon\n"
    .string "becomes less likely to flee, but\l"
    .string "harder to catch.\p"
    .string "If you throw Rocks, the Pokémon\n"
    .string "becomes more likely to flee, but\l"
    .string "easier to catch.\p"
    .string "When you run out of time or Safari\n"
    .string "Balls, it's game over for you!$"

FuchsiaCity_SafariZone_Entrance_Text_SorryYoureARegularHere:: @ 819809E
    .string "Sorry, you're a regular here!$"

