# 1 "data/maps/FourIsland_IcefallCave_Entrance/scripts.pory"

# 2 "data/maps/FourIsland_IcefallCave_Entrance/scripts.pory"
FourIsland_IcefallCave_Entrance_MapScripts::
# 3 "data/maps/FourIsland_IcefallCave_Entrance/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FourIsland_IcefallCave_Entrance_OnTransition
# 4 "data/maps/FourIsland_IcefallCave_Entrance/scripts.pory"
	.byte 0
# 5 "data/maps/FourIsland_IcefallCave_Entrance/scripts.pory"

# 6 "data/maps/FourIsland_IcefallCave_Entrance/scripts.pory"
FourIsland_IcefallCave_Entrance_OnTransition::
# 7 "data/maps/FourIsland_IcefallCave_Entrance/scripts.pory"
	setworldmapflag FLAG_WORLD_MAP_FOUR_ISLAND_ICEFALL_CAVE_ENTRANCE
# 8 "data/maps/FourIsland_IcefallCave_Entrance/scripts.pory"
	end
