Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze::
    .string "{COLOR DARK_GRAY}¿Entraras en el {SHADOW DYNAMIC_COLOR4}BOSQUE VERDE{SHADOW LIGHT_GRAY}?\n"
    .string "Es un laberinto natural...\l"
    .string "¡Asegúrate de no perderte!$"

Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite::
    .string "{COLOR DARK_GRAY}¡No subestimes a {SHADOW DYNAMIC_COLOR4}RATTATA{SHADOW LIGHT_GRAY} solo por su\n"
    .string "tamaño, es capaz de morder fuerte!\p"
    .string "¿Ya has capturado uno?$"
