Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze::
    .string "Are you going to VIRIDIAN FOREST?\n"
    .string "It's a natural maze in there.\l"
    .string "Be careful you don't get lost.$"

Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite::
    .string "RATTATA may be small, but don't\n"
    .string "underestimate its wicked bite.\p"
    .string "Have you caught one already?$"

