Text_1840C5:: @ 81840C5
    .string "You look good at POKéMON, but how\n"
    .string "is your chemistry grade?$"

Text_184100:: @ 8184100
    .string "Ow!\n"
    .string "Meltdown!$"

Text_18410E:: @ 818410E
    .string "I am better at school than this!$"

Text_18412F:: @ 818412F
    .string "All right!\n"
    .string "Let's play a game!$"

Text_18414D:: @ 818414D
    .string "Drat!\n"
    .string "Came up short!$"

Text_184162:: @ 8184162
    .string "Things didn't work today.$"

Text_18417C:: @ 818417C
    .string "You should be informed.\n"
    .string "You need strategy to win at this!$"

Text_1841B6:: @ 81841B6
    .string "It's not logical!$"

Text_1841C8:: @ 81841C8
    .string "Go with GRIMER first…and…\n"
    .string "…and…then…$"

Text_1841ED:: @ 81841ED
    .string "I like NIDORAN, so I collect them!$"

Text_184210:: @ 8184210
    .string "Why?\n"
    .string "Why??$"

Text_18421B:: @ 818421B
    .string "When POKéMON grow up, they get\n"
    .string "ugly! They shouldn't evolve.$"

Text_184257:: @ 8184257
    .string "School is fun, but so are POKéMON.$"

Text_18427A:: @ 818427A
    .string "You made it clear to me that\n"
    .string "I should stick with school.$"

Text_1842B3:: @ 81842B3
    .string "I was planning on getting some\n"
    .string "fresh air for a change, but…\p"
    .string "We're stuck here because of the\n"
    .string "gates at SAFFRON.$"

Text_184321:: @ 8184321
    .string "MEOWTH is so cute, meow, meow,\n"
    .string "meow!$"

Text_184346:: @ 8184346
    .string "Meeeeyow!$"

Text_184350:: @ 8184350
    .string "I think PIDGEY and RATTATA are\n"
    .string "cute, too!$"

Text_18437A:: @ 818437A
    .string "We must look silly standing here\n"
    .string "like this.$"

Text_1843A6:: @ 81843A6
    .string "Look what you did to my poor, cute\n"
    .string "POKéMON!$"

Text_1843D2:: @ 81843D2
    .string "SAFFRON's gatekeeper won't let us\n"
    .string "go through.\p"
    .string "I know he's doing his job, but I\n"
    .string "think he's mean.$"

Text_184432:: @ 8184432
    .string "I'm a rambling, gaming dude!$"

Text_18444F:: @ 818444F
    .string "Missed the big chance!$"

Text_184466:: @ 8184466
    .string "Playing games and POKéMON are like\n"
    .string "eating peanuts! I just can't stop!$"

Text_1844AC:: @ 81844AC
    .string "What's a cute, round, and fluffy\n"
    .string "POKéMON?$"

Text_1844D6:: @ 81844D6
    .string "Stop!\p"
    .string "Don't be so mean to my CLEFAIRY!$"

Text_1844FD:: @ 81844FD
    .string "I read that CLEFAIRY evolves when\n"
    .string "it's exposed to a MOON STONE.\p"
    .string "I read that in a POKéMON JOURNAL.\n"
    .string "I wonder if it's true?$"

gUnknown_8184576:: @ 8184576
    .string "UNDERGROUND PATH\n"
    .string "CELADON CITY - LAVENDER TOWN$"

