FiveIsland_LostCave_Room10_EventObjects:
	object_event 1, 28, 0, 5, 0, 5, 0, 3, 7, 17, 0, 0, 0, 0, 0, 0x0, 147, 0, 0
	object_event 2, 92, 0, 5, 0, 2, 0, 3, 8, 17, 0, 0, 0, 0, 0, FiveIsland_LostCave_Room10_EventScript_1BEDBB, 504, 0, 0

FiveIsland_LostCave_Room10_MapWarps:
	warp_def 5, 8, 3, 1, 525

FiveIsland_LostCave_Room10_MapEvents::
	map_events FiveIsland_LostCave_Room10_EventObjects, FiveIsland_LostCave_Room10_MapWarps, 0x0, 0x0
