Text_CounterTeach:: @ 8195928
    .string "Oh, hi!\n"
    .string "I finally finished POKéMON.\p"
    .string "Not done yet? How about I teach\n"
    .string "you a good move?\p"
    .string "The move I have in mind is\n"
    .string "COUNTER.\p"
    .string "Not like the one I'm leaning on,\n"
    .string "mind you!$"

Text_CounterDeclined:: @ 81959CC
    .string "You're not interested? Come see\n"
    .string "me if you change your mind.$"

Text_CounterWhichMon:: @ 8195A08
    .string "Which POKéMON should I teach\n"
    .string "COUNTER to?$"

Text_CounterTaught:: @ 8195A31
    .string "Are you using that COUNTER move\n"
    .string "I taught your POKéMON?$"

gUnknown_8195A68:: @ 8195A68
    .string "I'm getting a present for my\n"
    .string "girlfriend.\p"
    .string "I guess a POKé DOLL will be it.\n"
    .string "It's the popular thing.$"

gUnknown_8195AC9:: @ 8195AC9
    .string "I heard something useful.\p"
    .string "If a wild POKéMON appears, you can\n"
    .string "distract it with a POKé DOLL.\p"
    .string "You can run away while the wild\n"
    .string "POKéMON is distracted.$"

gUnknown_8195B5B:: @ 8195B5B
    .string "Express yourself with gifts!\n"
    .string "4F: WISE MAN GIFTS\p"
    .string "Evolution Special!\n"
    .string "Element STONES on sale now!$"

