PalletTown_Text_OakDontGoOut::
    .string "{SHADOW DYNAMIC_COLOR4}PROF. OAK:{SHADOW LIGHT_GRAY} ¡ALTO AHÍ!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "{SHADOW DYNAMIC_COLOR4}PROF. OAK:{SHADOW LIGHT_GRAY} ¡Cuidado! ¡En la hierba\n"
    .string "viven {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} salvajes!$"

PalletTown_Text_Vaya::
    .string "{SHADOW DYNAMIC_COLOR4}PROF. OAK:{SHADOW LIGHT_GRAY} ¡Vaya, eso estuvo cerca!$"

PalletTown_Text_DespuesPikachu::
    .string "{SHADOW DYNAMIC_COLOR4}PROF. OAK:{SHADOW LIGHT_GRAY} Los {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} pueden\n"
    .string "aparecer en la hierba alta en\l"
    .string "cualquier momento.\p"
    .string "¡Necesitas a tu propio {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}\n"
    .string "como protección!\p" 
    .string "¡Ven conmigo!$" 

PalletTown_Text_RaisingMonsToo::
    .string "{COLOR DARK_GRAY}¡Yo también entreno a mis {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY}!\p"
    .string "¡Cuando se hagan fuertes me\n"
    .string "protegerán!$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡La tecnología es increíble!\p"
    .string "Ahora puedes guardar y sacar\n"
    .string "objetos y {SHADOW DYNAMIC_COLOR4}POKéMON{SHADOW LIGHT_GRAY} vía {SHADOW DYNAMIC_COLOR4}PC{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}!$"

PalletTown_Text_OakPokemonResearchLab::
    .string "LABORATORIO DE INVESTIGACIÓN\n"
    .string "DE POKéMON DEL PROF. OAK$"

PalletTown_Text_PlayersHouse::
    .string "CASA DE {PLAYER}$"

PalletTown_Text_RivalsHouse::
    .string "CASA DE {RIVAL}$"
 
PalletTown_Text_TownSign::
    .string "{SHADOW DYNAMIC_COLOR4}PUEBLO PALETA\n"
    .string "{SHADOW LIGHT_GRAY}¡Un lienzo en blanco de tu viaje!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You're back, are you?\p"
    .string "How much have you filled in your\n"
    .string "POKéDEX?\p"
    .string "May I see it?\p"
    .string "Let's see…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "You've caught {STR_VAR_2}…\p"
    .string "Hm, it looks as if you're putting\n"
    .string "in an honest effort.\p"
    .string "When you manage to fill it some\n"
    .string "more, come show me, please.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "You've caught… {STR_VAR_2}!?\n"
    .string "Now, this is impressive!\p"
    .string "There's something I wanted to ask\n"
    .string "of you, {PLAYER}.\p"
    .string "Come.\n"
    .string "Follow me.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You seem to be enjoying traveling.\p"
    .string "Knowing you, {PLAYER}, I can easily\n"
    .string "imagine you going out to even more\l"
    .string "exotic locales.\p"
    .string "Good for you, good for you.\n"
    .string "Hohoho.$"


@ZAPATILLAS DEPORTIVAS
PalletTown_Text_Zapatillas1::
    .string "{COLOR DARK_GRAY}{SHADOW DYNAMIC_COLOR4}MAMÁ:{SHADOW LIGHT_GRAY} ¡Espera un momento, querida!\p"
    .string "Sabía que estarías ansiosa por\n"
    .string "comenzar tu viaje, pero no puede\l"
    .string "irte sin esto...$"

PalletTown_Text_Zapatillas2::
    .string "{COLOR DARK_GRAY}{SHADOW DYNAMIC_COLOR4}MAMÁ:{SHADOW LIGHT_GRAY} Son {SHADOW DYNAMIC_COLOR4}ZAPATILLAS DEPORTIVAS{SHADOW LIGHT_GRAY}\n"
    .string "de última generación.\p"
    .string "Con ellas, podrás moverte mucho\n"
    .string "más rápido.\p"
    .string "No puedo seguirte en tu aventura,\n"
    .string "pero al menos puedo asegurarme de\l"
    .string "que tengas un buen par de zapatos\l"
    .string "en tus pies.$"

PalletTown_Text_Zapatillas3::
    .string "{COLOR DARK_GRAY}{SHADOW DYNAMIC_COLOR4}MAMÁ:{SHADOW LIGHT_GRAY} No olvides que {SHADOW DYNAMIC_COLOR4}PUEBLO PALETA{SHADOW LIGHT_GRAY}\n"
    .string "siempre será tu hogar.\p"
    .string "Siempre serás bienvenida aquí, no\n"
    .string "importa lo lejos que viajes.$"


PalletTown_Text_RecibirZapatillas::
    .string "{COLOR DARK_GRAY}¡Recibiste las {SHADOW DYNAMIC_COLOR4}ZAPATILLAS DEPORTIVAS{SHADOW LIGHT_GRAY}\n"
    .string "de parte de {SHADOW DYNAMIC_COLOR4}MAMÁ{SHADOW LIGHT_GRAY}!$"
