# 1 "data/maps/CeladonCity_Hotel/scripts.pory"

# 2 "data/maps/CeladonCity_Hotel/scripts.pory"
CeladonCity_Hotel_MapScripts::
# 3 "data/maps/CeladonCity_Hotel/scripts.pory"
	.byte 0
# 4 "data/maps/CeladonCity_Hotel/scripts.pory"

# 5 "data/maps/CeladonCity_Hotel/scripts.pory"
CeladonCity_Hotel_EventScript_Receptionist::
# 6 "data/maps/CeladonCity_Hotel/scripts.pory"
	msgbox CeladonCity_Hotel_Text_ThisHotelIsForPeople, MSGBOX_NPC
# 7 "data/maps/CeladonCity_Hotel/scripts.pory"
	end
# 8 "data/maps/CeladonCity_Hotel/scripts.pory"

# 9 "data/maps/CeladonCity_Hotel/scripts.pory"
CeladonCity_Hotel_EventScript_Beauty::
# 10 "data/maps/CeladonCity_Hotel/scripts.pory"
	msgbox CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend, MSGBOX_NPC
# 11 "data/maps/CeladonCity_Hotel/scripts.pory"
	end
# 12 "data/maps/CeladonCity_Hotel/scripts.pory"

# 13 "data/maps/CeladonCity_Hotel/scripts.pory"
CeladonCity_Hotel_EventScript_BeautyBoyfriend::
# 14 "data/maps/CeladonCity_Hotel/scripts.pory"
	msgbox CeladonCity_Hotel_Text_WhyDidSheBringBrother, MSGBOX_NPC
# 15 "data/maps/CeladonCity_Hotel/scripts.pory"
	end
# 16 "data/maps/CeladonCity_Hotel/scripts.pory"

# 17 "data/maps/CeladonCity_Hotel/scripts.pory"
CeladonCity_Hotel_EventScript_BeautyBrother::
# 18 "data/maps/CeladonCity_Hotel/scripts.pory"
	msgbox CeladonCity_Hotel_Text_SisBroughtMeOnVacation, MSGBOX_NPC
# 19 "data/maps/CeladonCity_Hotel/scripts.pory"
	end
