@ Odd, doesnt seem to be corresponding text in RB. Unclear what this was meant for
Text_BuddhistAltar:: @ 8197B6F
    .string "ぶつだん　だ‥$"

CeladonCity_Hotel_Text_ThisHotelIsForPeople:: @ 8197B77
    .string "POKéMON?\n"
    .string "No, this is a hotel for people.\p"
    .string "We're full up, unfortunately.$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend:: @ 8197BBE
    .string "I'm on vacation with my brother and\n"
    .string "boyfriend.\p"
    .string "CELADON is such a pretty city!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother:: @ 8197C0C
    .string "Why?\n"
    .string "Why did she bring her brother?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation:: @ 8197C30
    .string "Yippee! I'm on vacation!\n"
    .string "My sis brought me along! Awesome!$"

