gUnknown_8182A03:: @ 8182A03
    .string "FOUR ISLAND\n"
    .string "The Warm, Blue, Floe Island$"

gUnknown_8182A2B:: @ 8182A2B
    .string "LORELEI has returned.\p"
    .string "Did she find the city life too\n"
    .string "stressful, I wonder?$"

gUnknown_8182A75:: @ 8182A75
    .string "LORELEI has gone back.\p"
    .string "The LAPRAS she has, I imagine it\n"
    .string "to be the one she met as a child.\p"
    .string "I believe it was in ICEFALL CAVE\n"
    .string "that she caught it.\p"
    .string "Perhaps that POKéMON has been with\n"
    .string "her ever since.$"

gUnknown_8182B37:: @ 8182B37
    .string "{RIVAL}: Hey!\n"
    .string "{PLAYER}!\p"
    .string "What are you doing here in the\n"
    .string "SEVII ISLANDS?\p"
    .string "You should quit copying me,\n"
    .string "you know?\p"
    .string "Anyways, I already got my POKéMON\n"
    .string "EGG, so I'm done with this island.\p"
    .string "Heh, I bet you don't even know\n"
    .string "about POKéMON EGGS.\p"
    .string "You'll never fill your NATIONAL\n"
    .string "POKéDEX that way.\p"
    .string "By the way, I saw someone we both\n"
    .string "know on this island.\p"
    .string "Why don't you go look around if\n"
    .string "it makes you curious?\p"
    .string "Me, I don't have the time to\n"
    .string "waste.\p"
    .string "Be smelling ya!$"

gUnknown_8182CE3:: @ 8182CE3
    .string "Oh, you found me!\n"
    .string "Please don't tell LORELEI.\p"
    .string "Did you know that LORELEI has lots\n"
    .string "and lots of stuffed dolls?\p"
    .string "Every time she comes back to\n"
    .string "FOUR ISLAND, her collection grows!$"

gUnknown_8182D8E:: @ 8182D8E
    .string "Ooh, chilly!\p"
    .string "I made a slushie using ice I\n"
    .string "shaved inside ICEFALL CAVE.\p"
    .string "It's chilly and tasty!$"

gUnknown_8182DEB:: @ 8182DEB
    .string "LORELEI'S HOUSE$"

