ViridianCity_House2_Text_TryingToMemorizeNotes:: @ 818FC00
    .string "Whew! I'm trying to memorize all my\n"
    .string "notes.$"

ViridianCity_House2_Text_ReadBlackboardCarefully:: @ 818FC2B
    .string "Okay!\p"
    .string "Be sure to read what's on the\n"
    .string "blackboard carefully!$"

ViridianCity_House2_Text_NotebookFirstPage:: @ 818FC65
    .string "Let's check out the notebook.\p"
    .string "First page…\p"
    .string "Poké Balls are used to catch\n"
    .string "Pokémon.\p"
    .string "Up to six Pokémon can be carried\n"
    .string "in your party.\p"
    .string "People who raise and battle\n"
    .string "with Pokémon are called Trainers.$"

ViridianCity_House2_Text_NotebookSecondPage:: @ 818FD23
    .string "Second page…\p"
    .string "A healthy Pokémon may be hard to\n"
    .string "catch, so weaken it first.\p"
    .string "Poison, burn, or cause another\n"
    .string "status problem to weaken it.$"

ViridianCity_House2_Text_NotebookThirdPage:: @ 818FDA8
    .string "Third page…\p"
    .string "Pokémon Trainers seek others to\n"
    .string "engage in Pokémon battles.\p"
    .string "To Trainers, the taste of victory\n"
    .string "is sweet, indeed.\p"
    .string "Battles are constantly waged at\n"
    .string "Pokémon Gyms everywhere.$"

ViridianCity_House2_Text_NotebookFourthPage:: @ 818FE5C
    .string "Fourth page…\p"
    .string "The ultimate goal for all Pokémon\n"
    .string "Trainers is simple.\p"
    .string "It is to defeat the top eight\n"
    .string "Pokémon Gym Leaders.\p"
    .string "Do so to earn the right to face…\p"
    .string "The Elite Four of the Pokémon\n"
    .string "League!$"

ViridianCity_House2_Text_TurnThePage:: @ 818FF19
    .string "Turn the page?$"

ViridianCity_House2_Text_HeyDontLookAtMyNotes:: @ 818FF28
    .string "Girl: Hey!\n"
    .string "Don't look at my notes!$"

ViridianCity_House2_Text_BlackboardListsStatusProblems:: @ 818FF4B
    .string "The blackboard lists Pokémon\n"
    .string "Status problems during battles.$"

ViridianCity_House2_Text_ReadWhichTopic:: @ 818FF88
    .string "Which topic do you want to read?$"

ViridianCity_House2_Text_ExplainSleep:: @ 818FFA9
    .string "A Pokémon can't attack if it's\n"
    .string "asleep.\p"
    .string "Pokémon will stay asleep even\n"
    .string "after battles.\p"
    .string "Use Awakening to awaken one\n"
    .string "from sleep.$"

ViridianCity_House2_Text_ExplainBurn:: @ 8190025
    .string "A burn reduces Attack power.\n"
    .string "It also causes ongoing HP loss.\p"
    .string "A burn remains after a battle.\n"
    .string "Use Burn Heal to cure a burn.$"

ViridianCity_House2_Text_ExplainPoison:: @ 819009F
    .string "When poisoned, a Pokémon's health\n"
    .string "steadily drops.\p"
    .string "Poison lingers after battles.\n"
    .string "Use an Antidote to cure poison!$"

ViridianCity_House2_Text_ExplainFreeze:: @ 819010F
    .string "A frozen Pokémon becomes\n"
    .string "helplessly immobile.\p"
    .string "It stays frozen even after the\n"
    .string "battle ends.\p"
    .string "Use Ice Heal to thaw out the\n"
    .string "suffering Pokémon.$"

ViridianCity_House2_Text_ExplainParalysis:: @ 8190199
    .string "Paralysis reduces Speed and may\n"
    .string "prevent the Pokémon from moving.\p"
    .string "Paralysis remains after battles.\n"
    .string "Use Parlyz Heal for treatment.$"

